CREATE OR REPLACE FUNCTION "NHS_CMB_SITECODE"
  RETURN TYPES.CURSOR_TYPE
AS
  OUTCUR TYPES.CURSOR_TYPE;
BEGIN
  OPEN OUTCUR FOR
    select STECODE, STENAME from site order by stecode;
  RETURN OUTCUR;
END NHS_CMB_SITECODE;
/
