CREATE OR REPLACE FUNCTION "NHS_CMB_SMSCONTENT"
	RETURN Types.cursor_type
AS
	outcur types.cursor_type;
BEGIN
	OPEN outcur FOR
		SELECT SMCID, SMCDESC
		FROM   SMSCONTENT
		WHERE  ROWNUM < 100
		AND    SMCSTS = -1
		ORDER  BY SMCORD;
	RETURN outcur;
END NHS_CMB_SMSCONTENT;
/


