create or replace function "NHS_CMB_ACCOUNT_RECEIVABLE"
RETURN TYPES.CURSOR_TYPE AS
OUTCOR TYPES.CURSOR_TYPE;
BEGIN
     OPEN OUTCOR FOR
          select ARCCODE,ARCCODE || '  '|| ARCNAME FROM ARCODE where arcprimcomp is null order by ARCNAME;
     RETURN OUTCOR;
END NHS_CMB_ACCOUNT_RECEIVABLE;
/
