CREATE OR REPLACE FUNCTION "NHS_CMB_PURPOSE" 
RETURN TYPES.CURSOR_TYPE AS
  OUTCOR TYPES.CURSOR_TYPE;
BEGIN
  OPEN OUTCOR FOR
    SELECT SEQ, PURPOSE FROM CALLCHARTPURPOSE ORDER BY PURPOSE;
  RETURN OUTCOR;
END NHS_CMB_PURPOSE;
/
