CREATE OR REPLACE FUNCTION "NHS_CMB_ALERTSRC"
	RETURN Types.cursor_type
AS
	outcur types.cursor_type;
BEGIN
	OPEN outcur FOR
		SELECT BKAID, BKADESC
		FROM   BOOKINGALERT
		WHERE  BKASTS = -1
		ORDER BY BKAORD;
	RETURN outcur;
END NHS_CMB_ALERTSRC;
/
