CREATE OR REPLACE FUNCTION "NHS_CMB_ACM"
	RETURN Types.CURSOR_type
AS
	outcur types.cursor_type;
BEGIN
	OPEN OUTCUR FOR
		SELECT AcmCode, AcmName
		FROM ACM
		WHERE ROWNUM < 100
		ORDER BY AcmCode;

	RETURN OUTCUR;
END NHS_CMB_ACM;
/
