create or replace FUNCTION "NHS_CMB_DOCCLASS"
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
BEGIN
	OPEN OUTCUR FOR
			SELECT HPKEY, HPSTATUS 
			FROM HPSTATUS 
			WHERE HPTYPE = 'DOCCLASS'
			ORDER BY HPKEY ASC;
	RETURN OUTCUR;
END NHS_CMB_DOCCLASS;
/
