CREATE OR REPLACE FUNCTION "NHS_CMB_MEDRECLOC"
RETURN TYPES.CURSOR_TYPE
 AS
  OUTCUR TYPES.CURSOR_TYPE;
BEGIN
  OPEN OUTCUR FOR
    SELECT MRLID,MRLDESC
    FROM MEDRECLOC
    ORDER BY MRLDESC;
  RETURN OUTCUR;
END NHS_CMB_MEDRECLOC;
/


