CREATE OR REPLACE FUNCTION "NHS_CMB_DEST"
  RETURN Types.CURSOR_type
AS
  outcur types.cursor_type;
BEGIN
  OPEN OUTCUR FOR
      SELECT D.DESCODE, D.DESDESC
      FROM DEST D
      WHERE ROWNUM < 100
      ORDER BY D.DESDESC;
   RETURN OUTCUR;
end NHS_CMB_DEST;
/


