CREATE OR REPLACE FUNCTION "NHS_CMB_NATUREOFVISIT"
	RETURN Types.cursor_type
AS
	outcur types.cursor_type;
BEGIN
	OPEN outcur FOR
		SELECT HPKEY, HPSTATUS
		FROM   HPSTATUS
		WHERE  HPTYPE = 'NATUREOFVISIT'
		AND    HPACTIVE = -1
		ORDER BY HPKEY;
	RETURN outcur;
END NHS_CMB_NATUREOFVISIT;
/
