CREATE OR REPLACE FUNCTION "NHS_CMB_MEDRECTYPE"
RETURN TYPES.CURSOR_TYPE
 AS
  OUTCUR TYPES.CURSOR_TYPE;
BEGIN
  OPEN OUTCUR FOR
    SELECT MRMID,MRMDESC
    FROM MEDRECMED;
  RETURN OUTCUR;
END NHS_CMB_MEDRECTYPE;
/


