CREATE OR REPLACE FUNCTION "NHS_CMB_ITEMCODE"
RETURN TYPES.CURSOR_TYPE AS
  OUTCUR TYPES.CURSOR_TYPE;
BEGIN
  OPEN OUTCUR FOR
    SELECT ITMCODE, ITMNAME
    FROM ITEM
    where Itmtype = 'D' and Itmcat = 'D'
    ORDER BY ITMCODE ;
    RETURN OUTCUR;
END NHS_CMB_ITEMCODE;
/
