CREATE OR REPLACE FUNCTION "NHS_CMB_CMCODE"
  RETURN TYPES.CURSOR_TYPE
AS
  OUTCUR TYPES.CURSOR_TYPE;
BEGIN
  OPEN OUTCUR FOR
    SELECT  CMCODE, CMCNAME FROM CMCFORM ORDER BY CMCODE;
  RETURN OUTCUR;
END NHS_CMB_CMCODE;
/
