CREATE OR REPLACE FUNCTION "NHS_CMB_MOTHERLANG"
  RETURN Types.CURSOR_type
AS
  outcur types.cursor_type;
BEGIN
  OPEN OUTCUR FOR
      SELECT MOTHCODE, MOTHDESC
      FROM MOTHERLANG
      WHERE ROWNUM < 100
      ORDER BY MOTHCODE;
   RETURN OUTCUR;
END NHS_CMB_MOTHERLANG;
/


