CREATE OR REPLACE FUNCTION NHS_CMB_RELDOC (
	v_DOCCODE IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR  TYPES.CURSOR_TYPE;
	SQLSTR  VARCHAR2(1000);
BEGIN
	OPEN OUTCUR FOR
		SELECT A.DOCCODE FROM (
			SELECT DOCCODE AS DOCCODE  FROM DOCTOR WHERE MSTRDOCCODE IN (
				SELECT MSTRDOCCODE AS DOCCODE FROM DOCTOR WHERE DOCCODE = v_DOCCODE
			)
			UNION
			SELECT MSTRDOCCODE AS DOCCODE FROM DOCTOR WHERE DOCCODE = v_DOCCODE
			UNION
			SELECT DOCCODE AS DOCCODE  FROM DOCTOR WHERE MSTRDOCCODE = v_DOCCODE
			UNION
			SELECT DOCCODE AS DOCCODE  FROM DOCTOR WHERE DOCCODE=v_DOCCODE) A
		WHERE A.DOCCODE IS NOT NULL
		ORDER BY A.DOCCODE;
	RETURN OUTCUR;
END NHS_CMB_RELDOC;
/
