CREATE OR REPLACE FUNCTION "NHS_CMB_DOCTORLOCATION" (
	i_ComputerIP IN VARCHAR2
)
	RETURN Types.cursor_type
AS
	outcur types.cursor_type;
	v_Count NUMBER;
BEGIN
	SELECT COUNT(1) INTO v_Count FROM HPSTATUS WHERE HPTYPE = 'DOCLOC' AND HPKEY = i_ComputerIP;
	IF v_Count > 0 THEN
		OPEN outcur FOR
			SELECT DOCLOCID, DOCLOCNAME
			FROM (
				SELECT DOCLOCID, DOCLOCNAME, 1 AS ORDERING, ORDERBY
				FROM   DOCLOCATION
				WHERE  DOCLOCID IN (SELECT HPSTATUS FROM HPSTATUS WHERE HPTYPE = 'DOCLOC' AND HPKEY = i_ComputerIP)
				UNION
				SELECT DOCLOCID, DOCLOCNAME, 2 AS ORDERING, ORDERBY
				FROM   DOCLOCATION
				WHERE  DOCLOCID NOT IN (SELECT HPSTATUS FROM HPSTATUS WHERE HPTYPE = 'DOCLOC' AND HPKEY = i_ComputerIP)
			)
			ORDER BY ORDERING, ORDERBY;
	ELSE
		OPEN outcur FOR
			SELECT DOCLOCID, DOCLOCNAME
			FROM   DOCLOCATION
			ORDER BY ORDERBY;
	END IF;

	RETURN outcur;
END NHS_CMB_DOCTORLOCATION;
/
