CREATE OR REPLACE FUNCTION "NHS_CMB_RELIGIOUS"
  RETURN Types.CURSOR_type
AS
  outcur types.cursor_type;
BEGIN
  OPEN OUTCUR FOR
      SELECT RELCODE, RELDESC
      FROM RELIGIOUS
      WHERE ROWNUM < 100
      ORDER BY RELCODE;
   RETURN OUTCUR;
END NHS_CMB_RELIGIOUS;
/


