CREATE OR REPLACE Function "NHS_CMB_HATSQUERY"
	RETURN TYPES.CURSOR_TYPE
AS
	Outcur Types.Cursor_Type;
BEGIN
	Open Outcur For
		SELECT NAME FROM AA_QUERY ORDER BY STATEMENT_NO;
	RETURN OUTCUR;
END NHS_CMB_HATSQUERY;
/
