CREATE OR REPLACE FUNCTION "NHS_CMB_ARNATURE"
	RETURN Types.CURSOR_type
AS
	outcur types.cursor_type;
BEGIN
	OPEN OUTCUR FOR
		SELECT ARNID, ARNNAME
		FROM ARNATURE
		WHERE ARNACTIVE = -1
		ORDER BY ARNID;
	RETURN OUTCUR;
END NHS_CMB_ARNATURE;
/
