create or replace
FUNCTION      "NHS_CMB_OTPROCFEST"
	RETURN Types.CURSOR_type
AS
	outcur types.cursor_type;
BEGIN
  	OPEN OUTCUR FOR
		SELECT P.PROCCODE, P.PROCDESC ||(decode(trim(C.REFCODE) ,'','',' - ' || C.REFCODE))
		FROM FIN_PROC P, FIN_CODE C
		WHERE P.PROCCODE = C.PROCCODE (+)
		ORDER BY P.PROCDESC;
  RETURN OUTCUR;
END NHS_CMB_OTPROCFEST;
/