create or replace FUNCTION "NHS_CMB_QUALIFICATION"
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
BEGIN
	OPEN OUTCUR FOR
		select QLFID, QLFNAME || ' ' || QLFCNAME
		FROM   QUALIFICATION
		WHERE  QLFCNAME IS NOT NULL
		ORDER BY QLFID;
	RETURN OUTCUR;
END NHS_CMB_QUALIFICATION;
/
