CREATE OR REPLACE FUNCTION "NHS_CMB_REASONLATE"
  RETURN Types.CURSOR_type
AS
  outcur types.cursor_type;
BEGIN
  OPEN OUTCUR FOR
    SELECT OTCID, OTCDESC
      FROM OT_CODE
     WHERE OTCTYPE = 'RL'
       AND OTCSTS = -1
     ORDER BY OTCORD, OTCDESC;
   RETURN OUTCUR;
END NHS_CMB_REASONLATE;
/


