CREATE OR REPLACE FUNCTION "NHS_CMB_ALERTSRC_SLIP"
	RETURN Types.cursor_type
AS
	outcur types.cursor_type;
BEGIN
	IF GET_CURRENT_STECODE() = 'HKAH' THEN
		OPEN outcur FOR
			SELECT BKAID, BKADESC
			FROM   BOOKINGALERT
			WHERE  BKASTS = -1
			AND    BKAID IN ('9', '10')
			ORDER BY BKAORD;
	END IF;

	RETURN outcur;
END NHS_CMB_ALERTSRC_SLIP;
/
