CREATE OR REPLACE FUNCTION "NHS_CMB_ALERTSRC_BOOKING"
	RETURN Types.cursor_type
AS
	outcur types.cursor_type;
BEGIN
	IF GET_CURRENT_STECODE() = 'TWAH' THEN
		OPEN outcur FOR
			SELECT BKAID, BKADESC
			FROM   BOOKINGALERT
			WHERE  BKASTS = -1
			ORDER BY BKAORD;
	ELSE
		OPEN outcur FOR
			SELECT BKAID, BKADESC
			FROM   BOOKINGALERT
			WHERE  BKASTS = -1
			AND    BKAID NOT IN ('11', '12', '13', '21', '22', '23', '34', '44', '70', '72', '73')
			ORDER BY BKAORD;
	END IF;

	RETURN outcur;
END NHS_CMB_ALERTSRC_BOOKING;
/
