CREATE OR REPLACE FUNCTION "NHS_CMB_PROCPRIM"
RETURN TYPES.CURSOR_TYPE AS
  OUTCUR TYPES.CURSOR_TYPE;
BEGIN
  OPEN OUTCUR FOR
    SELECT OTPID, OTPDESC || '  ' || OTPCODE AS OTPNAME
      FROM OT_PROC
     WHERE OTPSTS = -1
     ORDER BY OTPNAME;
  RETURN OUTCUR;
END NHS_CMB_PROCPRIM;
/


