CREATE OR REPLACE FUNCTION "NHS_CMB_RELATIONSHIP"
	RETURN Types.CURSOR_type
AS
	outcur types.cursor_type;
BEGIN
	OPEN OUTCUR FOR
		SELECT RELATIONDESC
		FROM RELATIONSHIP
		WHERE ROWNUM < 100
		ORDER BY RELATIONDESC;
	RETURN OUTCUR;
END NHS_CMB_RELATIONSHIP;
/
