CREATE OR REPLACE FUNCTION "NHS_CMB_PAYTYPE"
	RETURN Types.CURSOR_type
AS
	outcur types.cursor_type;
BEGIN
	OPEN OUTCUR FOR
		SELECT '', '0.All' FROM DUAL
		UNION
		SELECT 'A', '1.Autopay' FROM DUAL
		UNION
		SELECT 'C', '2.Cash' FROM DUAL
		UNION
		SELECT 'Q', '3.Cheque' FROM DUAL
		UNION
		SELECT 'D', '4.Credit Card' FROM DUAL
		UNION
		SELECT 'U', '5.CUP' FROM DUAL
		UNION
		SELECT 'E', '6.EPS' FROM DUAL
		UNION
		SELECT 'T', '7.Octopus' FROM DUAL
		UNION
		SELECT 'R', '8.Wechat/Alipay' FROM DUAL
		UNION
		SELECT 'O', '9.Others' FROM DUAL
		ORDER BY 2;

	RETURN OUTCUR;
END NHS_CMB_PAYTYPE;
/
