CREATE OR REPLACE FUNCTION "NHS_CMB_USER"
  RETURN Types.CURSOR_type
AS
  outcur types.cursor_type;
BEGIN
  OPEN OUTCUR FOR
      SELECT USRID, USRNAME
      FROM USR
      WHERE ROWNUM < 100
      ORDER BY USRNAME;
   RETURN OUTCUR;
END NHS_CMB_USER;
/


