CREATE OR REPLACE FUNCTION "NHS_CMB_CASHREF"
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
BEGIN
	OPEN OUTCUR FOR
		SELECT CRFDESC
		FROM   CASHREF
		ORDER BY CRFDESC;

	RETURN OUTCUR;
END NHS_CMB_CASHREF;
/
