CREATE OR REPLACE FUNCTION "NHS_CMB_EHRPMIDOCTYPE"
  RETURN TYPES.CURSOR_TYPE
AS
  OUTCUR TYPES.CURSOR_TYPE;
BEGIN
  OPEN OUTCUR FOR
    SELECT EHRCODE, EHRDESC FROM EHR_PMIDOCTYPE ORDER BY EHRSEQ, EHRCODE;
  RETURN OUTCUR;
END NHS_CMB_EHRPMIDOCTYPE;
/
