create or replace
FUNCTION "NHS_CMB_DEPTAPPROOMTYPE"
(
	V_ACTIVE_ONLY IN VARCHAR2,	-- Y, N
	V_DEPTCID IN VARCHAR2,
  V_ACTIVE IN VARCHAR2,
  V_DEPTTYPE IN VARCHAR2
)
RETURN TYPES.CURSOR_TYPE AS
  OUTCUR TYPES.CURSOR_TYPE;
  STRSQL VARCHAR2(2000);
BEGIN
  STRSQL := 'SELECT DEPTCID, DEPTCDESC
	FROM DEPT_CODE
	WHERE (DEPTCTYPE = ''RM'' ';

  IF V_ACTIVE IS NOT NULL AND LENGTH(V_ACTIVE) > 0 THEN
    IF V_ACTIVE = 'Y' THEN
       STRSQL := STRSQL || 'AND DEPTCSTS = -1 ';
    ELSIF V_ACTIVE = 'N' THEN
       STRSQL := STRSQL || 'AND DEPTCSTS = 0 ';
    END IF;
  END IF;

  STRSQL := STRSQL || ') ';

	IF v_DEPTTYPE IS NOT NULL THEN
		STRSQL := STRSQL || ' AND DEPTTYPE = ''' || V_DEPTTYPE || '''';
	END IF;
      
  
  if v_deptcid is not null then
	  IF V_ACTIVE_ONLY = 'Y' THEN
	  	strsql := strsql || ' AND';
	  ELSE
	  	strsql := strsql || ' OR';
	  end if;
	  strsql := strsql || ' DEPTCID = ' || v_deptcid;
  END IF;

  STRSQL := STRSQL || ' ORDER BY DEPTCORD';

  open outcur for
    STRSQL;
  RETURN OUTCUR;
END NHS_CMB_DEPTAPPROOMTYPE;
/