CREATE OR REPLACE FUNCTION "NHS_CMB_TRANSMISC"
	RETURN Types.CURSOR_type
AS
	outcur types.cursor_type;
BEGIN
	OPEN outcur FOR
		SELECT HPKEY, HPSTATUS
		FROM   HPSTATUS
		WHERE  HPTYPE = 'TRANSMISC'
		AND    HPACTIVE = -1
		ORDER BY HPRMK;

	RETURN OUTCUR;
END NHS_CMB_TRANSMISC;
/
