CREATE OR REPLACE FUNCTION "NHS_CMB_MEDRECVOL"(
	v_PATNO IN VARCHAR2,
	v_EXCLUDEVOL	IN VARCHAR2
)
RETURN TYPES.CURSOR_TYPE
 AS
  OUTCUR TYPES.CURSOR_TYPE;
BEGIN
  OPEN OUTCUR FOR
    SELECT MRHVOLLAB ID, MRHVOLLAB TEXT
    FROM MEDRECHDR h
    WHERE PATNO = v_PATNO
    	AND ((v_EXCLUDEVOL IS NOT NULL AND MRHVOLLAB <> v_EXCLUDEVOL) OR (v_EXCLUDEVOL IS NULL))
    ORDER BY MRHVOLLAB;
  RETURN OUTCUR;
END NHS_CMB_MEDRECVOL;
/
