CREATE OR REPLACE FUNCTION "NHS_CMB_MARITALSTATUS"
	RETURN Types.CURSOR_type
AS
	outcur types.cursor_type;
BEGIN
	OPEN OUTCUR FOR
		SELECT MARCODE, MARDESC
		FROM MARITALSTATUS
		WHERE ROWNUM < 100
		ORDER BY MARORDER;

	RETURN OUTCUR;
END NHS_CMB_MARITALSTATUS;
/
