CREATE OR REPLACE FUNCTION "NHS_CMB_MARKETINGSOURCE"
  RETURN Types.CURSOR_type
AS
  outcur types.cursor_type;
BEGIN
  OPEN OUTCUR FOR
      SELECT MKTSRCCODE, MKTSRCDESC
      FROM MARKETINGSOURCE
      WHERE ROWNUM < 100
      ORDER BY MKTSRCDESC;
   RETURN OUTCUR;
END NHS_CMB_MARKETINGSOURCE;
/
