CREATE OR REPLACE FUNCTION "NHS_CMB_SPECDEST"
RETURN TYPES.CURSOR_TYPE AS
  OUTCUR TYPES.CURSOR_TYPE;
BEGIN
  OPEN OUTCUR FOR
    SELECT OTCID, OTCDESC
      FROM OT_CODE
     WHERE OTCTYPE = 'SD'
       AND OTCSTS = -1
     ORDER BY OTCORD, OTCDESC;
  RETURN OUTCUR;
END NHS_CMB_SPECDEST;
/


