CREATE OR REPLACE FUNCTION "NHS_CMB_DEPTSERVICE"
	RETURN Types.CURSOR_type
AS
	outcur types.cursor_type;
BEGIN
	OPEN OUTCUR FOR
		SELECT DscCode, DscDesc
		FROM   DPSERV
		WHERE  ROWNUM < 100
		ORDER BY DscCode;

	RETURN OUTCUR;
END NHS_CMB_DEPTSERVICE;
/
