CREATE OR REPLACE FUNCTION "NHS_CMB_BOOKINGSRC"
	RETURN Types.cursor_type
AS
	outcur types.cursor_type;
BEGIN
	OPEN outcur FOR
		SELECT BKSID, BKSDESC
		FROM   BOOKINGSRC
		WHERE  BKSSTS = -1
		AND    BKSTYPE in ('A','O')
		ORDER  BY BKSORD;
	RETURN outcur;
END NHS_CMB_BOOKINGSRC;
/
