CREATE OR REPLACE FUNCTION "NHS_CMB_WARD"
	RETURN Types.CURSOR_type
AS
	outcur types.cursor_type;
BEGIN
	OPEN OUTCUR FOR
		SELECT wrdcode, wrdname
		FROM WARD
		WHERE ACTIVE = -1
		ORDER BY wrdname;
	RETURN OUTCUR;
END NHS_CMB_WARD;
/
