CREATE OR REPLACE FUNCTION "NHS_CMB_ROLE"
	RETURN Types.CURSOR_type
AS
	outcur TYPES.CURSOR_TYPE;
BEGIN
	OPEN outcur FOR
		SELECT ROLID, ROLNAM
		FROM   ROLE
		WHERE  ROWNUM < 100
		ORDER BY ROLDESC;
	RETURN outcur;
END NHS_CMB_ROLE;
/
