CREATE OR REPLACE FUNCTION "NHS_CMB_BED"
	RETURN Types.CURSOR_type
AS
	outcur types.cursor_type;
BEGIN
	OPEN OUTCUR FOR
		SELECT B.BEDCODE, B.BEDCODE, R.ACMCODE, B.BEDREMARK
		FROM   BED B LEFT JOIN ROOM R ON B.ROMCODE = R.ROMCODE LEFT JOIN WARD W ON W.WRDCODE = R.WRDCODE
		WHERE  B.BEDCODE NOT IN (SELECT RLKKEY FROM RLOCK WHERE RLKTYPE = 'Bed')
		AND    W.ACTIVE = -1
		AND   (B.BEDREMARK IS NULL OR B.BEDREMARK NOT LIKE 'Invalid%')
--		AND    B.BEDOFF = -1
		ORDER BY B.BedCode;
	RETURN OUTCUR;
end NHS_CMB_BED;
/
