CREATE OR REPLACE FUNCTION "NHS_CMB_SPECIALTY_CODE"
RETURN TYPES.CURSOR_TYPE AS
  OUTCUR TYPES.CURSOR_TYPE;
BEGIN
  OPEN OUTCUR FOR
    SELECT SPCCODE, SPCNAME
      FROM SPEC
     ORDER BY SPCCODE;
  RETURN OUTCUR;
END NHS_CMB_SPECIALTY_CODE;
/

