create or replace function "NHS_CMB_ITEMSET"
RETURN TYPES.CURSOR_TYPE AS
OUTCOR TYPES.CURSOR_TYPE;
BEGIN
     OPEN OUTCOR FOR
          SELECT CPSID, CPSCODE || '  '|| CPSDESC FROM conpceset order by CPSCODE;
     RETURN OUTCOR;
END NHS_CMB_ITEMSET;
/
