CREATE OR REPLACE FUNCTION "NHS_CMB_OTCODETYPE"
  RETURN Types.CURSOR_type
AS
  outcur types.cursor_type;
BEGIN
  OPEN OUTCUR FOR
      SELECT OTCID||'',OTCDESC
        FROM OT_CODE
       WHERE OTCTYPE = 'RM'
       ORDER BY OTCORD;
   RETURN OUTCUR;
END NHS_CMB_OTCODETYPE;
/


