CREATE OR REPLACE FUNCTION NHS_CMB_CHART_LOCATION (
	v_SITECODE IN VARCHAR2
)
	RETURN Types.cursor_type
AS
	outcur types.cursor_type;
BEGIN
	OPEN outcur FOR
		SELECT MRLID, MRLDESC
		FROM   MEDRECLOC
		WHERE  STECODE = v_SITECODE
		AND    MRLDESC NOT LIKE 'Z-MRD%'
		ORDER BY MRLDESC;
	RETURN OUTCUR;
END NHS_CMB_CHART_LOCATION;
/
