create or replace
FUNCTION "NHS_CMB_PRIVILEGE"
RETURN TYPES.CURSOR_TYPE AS
  OUTCUR TYPES.CURSOR_TYPE;
BEGIN
  OPEN OUTCUR FOR
    select PRICODE, PRINAME
    from PRIVILEGE
    order by pricode;
    --WHERE ROWNUM < 500
    RETURN OUTCUR;
END NHS_CMB_PRIVILEGE;
/