CREATE OR REPLACE FUNCTION NHS_CMB_SUPP_CATEGORY
	RETURN Types.CURSOR_type
AS
	OUTCUR types.cursor_type;
BEGIN
	OPEN OUTCUR FOR
		SELECT SCYCODE, SCYDESC
		FROM   SUPPCATEGORY
		WHERE SCYACTIVE = -1
    	ORDER BY SCYCODE;

	RETURN OUTCUR;
END NHS_CMB_SUPP_CATEGORY;
/
