CREATE OR REPLACE FUNCTION "NHS_CMB_PATCAT"
	RETURN Types.CURSOR_type
AS
	outcur types.cursor_type;
BEGIN
	OPEN OUTCUR FOR
		SELECT PCYCODE, PCYDESC, PCYID
		FROM   PATCAT
		WHERE  ACTIVE = -1
		ORDER  BY PCYCODE ASC;
	RETURN OUTCUR;
END NHS_CMB_PATCAT;
/
