CREATE OR REPLACE FUNCTION "NHS_LIS_ACCOUNTTRAN"
(V_ATXREFID IN VARCHAR2)
 RETURN TYPES.CURSOR_TYPE AS
  OUTCUR TYPES.CURSOR_TYPE;
BEGIN
  OPEN OUTCUR FOR
    SELECT A.ATXID,
           TO_CHAR(A.ATXTDATE, 'DD/MM/YYYY'),
           A.ATXAMT,
           B.ARPRECNO,
           A.ATXSTS
      FROM ARTX A, ARPTX B
     WHERE A.ARPID = B.ARPID
       AND A.ATXSTS <> 'R'
       AND A.ATXREFID = V_ATXREFID
     ORDER BY ATXTDATE;
  RETURN OUTCUR;
END NHS_LIS_ACCOUNTTRAN;
/
