CREATE OR REPLACE FUNCTION NHS_ACT_ARPAYMENTENTRY(
V_ACTION   IN VARCHAR2,
V_ARCCODE  IN VARCHAR2,
V_AMT      IN VARCHAR2,
V_ARPRECNO IN VARCHAR2,
V_ARPTDATE IN VARCHAR2,
V_ARPCDATE IN VARCHAR2,
V_ARPDESC  IN VARCHAR2,
V_USRID      IN VARCHAR2,
O_ERRMSG   OUT VARCHAR2)
  RETURN NUMBER AS
  O_ERRCODE NUMBER;
  V_ARPID   NUMBER;

BEGIN
  O_ERRMSG  := 'OK';
  O_ERRCODE := 0;
  IF V_ACTION = 'ADD' THEN
    SELECT SEQ_ARPTX.NEXTVAL INTO V_ARPID FROM DUAL;

    INSERT INTO ARPTX
      (ARPID,
       ARCCODE,
       ARPOAMT,
       ARPAAMT,
       ARPRECNO,
       ARPTDATE,
       ARPCDATE,
       ARPDESC,
       ARPTYPE,
       ARPSTS,
       USRID)
    VALUES
      (V_ARPID,
       V_ARCCODE,
       V_AMT,
       0,
       V_ARPRECNO,
       DECODE(V_ARPTDATE,NULL,SYSDATE,TO_CHAR(V_ARPTDATE,'DD/MM/YYYY')),
       DECODE(V_ARPCDATE,NULL,SYSDATE,TO_CHAR(V_ARPCDATE,'DD/MM/YYYY')),
       V_ARPDESC,
       'P',
       'N',
       V_USRID);

    UPDATE ARCODE
       SET  ARCUAMT = ARCUAMT + TO_NUMBER(V_AMT)
     WHERE ARCCODE = V_ARCCODE;
    IF SQL%ROWCOUNT = 0 THEN
      ROLLBACK;
      O_ERRMSG  := 'update Fail.';
      O_ERRCODE := -1;
      RETURN O_ERRCODE;
    END IF;
    O_ERRCODE := V_ARPID;
  ELSE
    O_ERRMSG  := 'parameter error.';
    O_ERRCODE := -1;
  END IF;

  RETURN O_ERRCODE;
END NHS_ACT_ARPAYMENTENTRY;
/
