CREATE OR REPLACE FUNCTION "NHS_LIS_ACCOUNTSLIP"
(v_ARCCODE IN VARCHAR2,
v_ATXID   IN VARCHAR2,
v_SLIPNO  IN VARCHAR2,
v_PATNO   IN VARCHAR2)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
BEGIN
	OPEN OUTCUR FOR
		SELECT ATXID,
			SLPNO,
			PATNO,
			ATXAMT,
			ATXAMT - ATXSAMT AS DIFF,
			TO_CHAR(ATXTDATE, 'DD/MM/YYYY'),
			ATXDESC,
			ATXREFID,
			ARCCODE
		FROM  ARTX
		WHERE ARPID IS NULL
		AND   ATXTTYPE = 'C'
		AND   ATXSTS = 'N'
		AND  (ARCCODE = v_ARCCODE OR v_ARCCODE IS NULL)
		AND  (ATXID = v_ATXID OR v_ATXID IS NULL)
		AND  ((v_SLIPNO IS NULL AND SLPNO IS NULL) OR (v_SLIPNO IS NOT NULL AND SLPNO = v_SLIPNO))
		AND  (PATNO = v_PATNO OR v_PATNO IS NULL)
		ORDER BY SLPNO;
	RETURN OUTCUR;
END NHS_LIS_ACCOUNTSLIP;
/
