@./schedule/NHS_ACT_BOOKING.sql
@./schedule/NHS_ACT_BOOKING_CANCEL.sql
@./schedule/NHS_ACT_BOOKING_CHANGE.sql
@./schedule/NHS_ACT_BOOKING_CHECK.sql
@./schedule/NHS_ACT_DEPTAPP_CANC.sql
@./schedule/NHS_ACT_NEWEDITDEPTAPP.sql
@./schedule/NHS_ACT_SCHEDULE.sql
@./schedule/NHS_ACT_SCHEDULE_BLOCK.sql
@./schedule/NHS_ACT_SCHEDULE_BY_SPEC.sql
@./schedule/NHS_ACT_SCHEDULE_MUTI.sql
@./schedule/NHS_ACT_SCHEDULE_RMK.sql
@./schedule/NHS_ACT_SCHEDULE_SINGLE.sql
@./schedule/NHS_ACT_SCHEDULE_UNBLOCK.sql
@./schedule/NHS_ACT_TEMPLATE.sql
@./schedule/NHS_GET_BOOKING.sql
@./NHS_GET_DEPTAPPBYNO.sql
@./schedule/NHS_GET_DOCTOR_ACTIVE.sql
@./schedule/NHS_GET_DOCTSLOT.sql
@./schedule/NHS_GET_MedRecGetCur.sql
@./schedule/NHS_LIS_APPLISTING_PAT.sql
@./schedule/NHS_LIS_BOOKING.sql
@./schedule/NHS_LIS_DEPT_ROOM.sql
@./schedule/NHS_LIS_DEPTAPPBSE.sql
@./NHS_LIS_DEPTDVATABLELIST.sql
@./NHS_LIS_DEPTDVBTABLELIST.sql
@./schedule/NHS_LIS_PRINTAPP.sql
@./schedule/NHS_LIS_SCHEDULE.sql
@./schedule/NHS_LIS_SLOT.sql
@./schedule/NHS_LIS_SLOT_BY_SPEC.sql
@./schedule/NHS_LIS_TEMPLATE.sql
@./schedule/NHS_UTL_BOOKING_CANCEL_LOG.sql
exit