CREATE OR REPLACE FUNCTION "NHS_RPT_SPCAPPLISTING" (
	v_BKGSDATE IN VARCHAR2,
	v_BKGEDATE IN VARCHAR2,
	v_SPCCODE  IN VARCHAR2,
	v_USRID    IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
	SQLSTR  VARCHAR2(5000);
BEGIN
	SQLSTR := 'SELECT /*+ NO_MERGE */
					/*+ INDEX( B IDX_BOOKING_BKGSDATE P IDX_PATIENT_10 ) ORDERED USE_NL(B, S, D) */
				  TO_CHAR(B.BKGSDATE, ''DD/MM/YYYY HH24:MI'') || '' - ''||TO_CHAR(B.BKGEDATE, ''HH24:MI'') as BKGDATE,
				  B.PATNO,
				  PE.DENTALNO,
				  B.BKGPNAME,
				  TO_CHAR(P.PATBDATE,''dd/MON/YYYY'',''NLS_DATE_LANGUAGE=AMERICAN''),
				  B.BKGMTEL
				FROM BOOKING B
				LEFT JOIN BOOKING_EXTRA BE ON B.BKGID = BE.BKGID
				LEFT JOIN PATIENT P ON B.PATNO = P.PATNO
				LEFT JOIN PATIENT_EXTRA PE ON B.PATNO = PE.PATNO
				INNER JOIN SCHEDULE S ON B.SCHID = S.SCHID ';

	IF v_SPCCODE IS NOT NULL THEN
		IF v_SPCCODE = 'DENTIST' THEN
			SQLSTR := SQLSTR || ' INNER JOIN DOCTOR D ON S.DOCCODE = D.DOCCODE AND D.SPCCODE IN (''DENTIST'', ''DENHYG'', ''ORALMAX'', ''PROSDON'')';
		ELSE
			SQLSTR := SQLSTR || ' INNER JOIN DOCTOR D ON S.DOCCODE = D.DOCCODE AND D.SPCCODE = ''' || v_SPCCODE || ''' ';
		END IF;
	ELSE
		SQLSTR := SQLSTR || ' LEFT JOIN DOCTOR D ON S.DOCCODE = D.DOCCODE ';
	END IF;

	SQLSTR := SQLSTR || ' WHERE B.STECODE = '''|| GET_CURRENT_STECODE || '''';

	IF v_BKGSDATE IS NOT NULL THEN
		SQLSTR := SQLSTR || ' AND B.BKGSDATE >= TO_DATE(''' || v_BKGSDATE || ' 00:00:00'', ''DD/MM/YYYY HH24:MI:SS'')';
	END IF;

	IF v_BKGEDATE IS NOT NULL THEN
		SQLSTR := SQLSTR || ' AND B.BKGEDATE <= TO_DATE(''' || v_BKGEDATE || ' 23:59:59'', ''DD/MM/YYYY HH24:MI:SS'')';
	END IF;

		SQLSTR := SQLSTR || ' AND BKGSTS = ''N''';

		SQLSTR := SQLSTR || ' ORDER BY B.BKGSDATE ';
		
	OPEN OUTCUR FOR SQLSTR;

	RETURN OUTCUR;
END NHS_RPT_SPCAPPLISTING;
/
