CREATE OR REPLACE FUNCTION "NHS_GET_DOCTSLOT" (
	v_DOCCODE IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
BEGIN
	OPEN OUTCUR FOR
		SELECT 
			docfname ||' '|| docgname, 
			doctslot, 
			CASE WHEN spccode in ('DENTIST', 'DENHYG', 'ORALMAX', 'PROSDON') THEN 'DENTIST' ELSE spccode END DEPT_SPCCODE
		FROM  DOCTOR
		WHERE doccode = v_DOCCODE;
	RETURN OUTCUR;
END NHS_GET_DOCTSLOT;
/
