create or replace FUNCTION                     "NHS_LIS_APPRMDVATABLELIST" (
	v_BKGSDATE IN VARCHAR2,
  v_ROOM  IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
	SQLSTR VARCHAR2(2000);
BEGIN
SQLSTR := 'SELECT 
      B.BKGID,
      B.BKGSTS,
			TO_CHAR(B.BKGSDATE, ''DD/MM/YYYY HH24:MI''),
			TO_CHAR(B.BKGEDATE, ''DD/MM/YYYY HH24:MI''),
			S.DOCCODE,
      B.BKGPNAME,
      '''',
      B.PATNO,
      D.DOCFNAME||'' ''||D.DOCGNAME,
      '''',
      '''',
      ''B'',
      B.BKGRMK,
      B.SLTID,
      B.SCHID,
      SE.RMID
		FROM BOOKING B
		LEFT JOIN PATIENT P ON B.PATNO = P.PATNO
		INNER JOIN SCHEDULE S ON B.SCHID = S.SCHID 
    LEFT JOIN DOCTOR D ON S.DOCCODE = D.DOCCODE
    LEFT JOIN SCHEDULE_EXTRA SE ON S.SCHID = SE.SCHID
    INNER JOIN HPSTATUS HP ON SE.RMID = HP.HPSTATUS AND HPTYPE=''DRROOM'' AND HPKEY = '''||V_ROOM||'''
    WHERE B.BKGSDATE >= TO_DATE(''' || v_BKGSDATE || ' 00:00:00'', ''DD/MM/YYYY HH24:MI:SS'')
		AND B.BKGSDATE < TO_DATE(''' || v_BKGSDATE || ' 00:00:00'', ''DD/MM/YYYY HH24:MI:SS'') + 1
    AND B.BKGEDATE >= TO_DATE(''' || v_BKGSDATE || ' 00:00:00'', ''DD/MM/YYYY HH24:MI:SS'') 
    AND B.BKGEDATE < TO_DATE(''' || v_BKGSDATE || ' 00:00:00'', ''DD/MM/YYYY HH24:MI:SS'') + 1
    AND SE.RMID IS NOT NULL
    AND   B.BKGSTS IN (''N'', ''F'')
    UNION
    SELECT       
      r.regid,
      r.regsts,
			TO_CHAR(r.regdate, ''DD/MM/YYYY HH24:MI''),
			TO_CHAR(r.regdate+ (1/1440*14), ''DD/MM/YYYY HH24:MI''),
			r.DOCCODE,
      P.PATFNAME||'' ''||P.PATGNAME,
      '''',
      r.PATNO,
      D.DOCFNAME||'' ''||D.DOCGNAME,
      '''',
      '''',
      ''R'',
      r.REGOPCAT,
      null,null,RE.RMID FROM REG R
      INNER JOIN PATIENT P ON R.PATNO = P.PATNO
      LEFT JOIN REG_EXTRA RE ON R.REGID = RE.REGID
      INNER JOIN DOCTOR D ON  R.DOCCODE = D.DOCCODE
      INNER JOIN HPSTATUS HP ON RE.RMID = HP.HPSTATUS AND HPTYPE=''DRROOM'' AND HPKEY = '''||V_ROOM||'''
      WHERE R.REGOPCAT IN (''W'',''P'',''U'')  
      AND R.REGSTS = ''N'' 
        AND  R.REGDATE >= TO_DATE(''' || v_BKGSDATE || ' 00:00:00'', ''DD/MM/YYYY HH24:MI:SS'') 
    AND  R.REGDATE < TO_DATE(''' || v_BKGSDATE || ' 00:00:00'', ''DD/MM/YYYY HH24:MI:SS'') + 1';
      
  DBMS_OUTPUT.PUT_LINE(SQLSTR);
	OPEN OUTCUR FOR SQLSTR;
	RETURN OUTCUR;
END NHS_LIS_APPRMDVATABLELIST;
/
