CREATE OR REPLACE FUNCTION "NHS_LIS_BOOKINGALERT" (
	v_BKGALERT IN VARCHAR2,
	v_BKGSDATE IN VARCHAR2,
	v_BKGEDATE IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	v_COUNT NUMBER := 0;
	v_QUOTAD NUMBER := 0;
	v_QUOTAM NUMBER := 0;
	v_QUOTAY NUMBER := 0;
	OUTCUR TYPES.CURSOR_TYPE;
	SQLSTR  VARCHAR2(5000);
BEGIN
	SELECT COUNT(1) INTO v_COUNT FROM BOOKINGALERT WHERE BKAID = v_BKGALERT AND (BKAQUOTAD = -1 OR BKAQUOTAM = -1 OR BKAQUOTAY = -1);
	IF v_COUNT > 0 THEN
		SELECT BKAQUOTAD, BKAQUOTAM, BKAQUOTAY INTO v_QUOTAD, v_QUOTAM, v_QUOTAY
		FROM BOOKINGALERT WHERE BKAID = v_BKGALERT AND (BKAQUOTAD = -1 OR BKAQUOTAM = -1 OR BKAQUOTAY = -1);
	END IF;

	IF v_QUOTAY = -1 THEN
		IF v_BKGALERT IN ('31', '41') THEN
			SQLSTR := 'SELECT '''', ''DR. '' || D.DOCFNAME || '' '' || D.DOCGNAME || '' ('' || D.DOCCODE || '')'',
					NHS_UTL_ALERTQUOTA(''' || v_BKGALERT || ''', D.DOCCODE, (TO_DATE(''01/01/'' || SUBSTR(''' || v_BKGSDATE || ''', 7) || '' 00:00:00'', ''DD/MM/YYYY HH24:MI:SS'')))
				FROM   DOCTOR D
				WHERE  D.DOCSTS = -1
				AND    D.DOCCODE IN (SELECT SUBSTR(HPSTATUS, 6) FROM HPSTATUS WHERE HPTYPE = ''QUOTAYEAR'' AND HPKEY = ''' || v_BKGALERT || ''' AND HPSTATUS LIKE TO_CHAR(TO_DATE(''' || v_BKGSDATE || ' 00:00:00'', ''DD/MM/YYYY HH24:MI:SS''), ''YYYY'') || ''_%'')
				ORDER BY D.DOCFNAME, D.DOCGNAME';
		ELSE
			SQLSTR := 'SELECT '''', TO_CHAR(TO_DATE(''' || v_BKGSDATE || ' 00:00:00'', ''DD/MM/YYYY HH24:MI:SS''), ''YYYY''), NHS_UTL_ALERTQUOTA(''' || v_BKGALERT || ''', '''', (TO_DATE(''' || v_BKGSDATE || ' 00:00:00'', ''DD/MM/YYYY HH24:MI:SS''))) FROM DUAL';
		END IF;
	ELSIF v_QUOTAM = -1 THEN
		SQLSTR := 'SELECT DISTINCT * from (SELECT '''', TO_CHAR(TO_DATE(''' || v_BKGSDATE || ' 00:00:00'', ''DD/MM/YYYY HH24:MI:SS'') + ROWNUM - 1, ''MM'') || '' '' || TO_CHAR(TO_DATE(''' || v_BKGSDATE || ' 00:00:00'', ''DD/MM/YYYY HH24:MI:SS'') + ROWNUM - 1, ''MONTH'') as qday,
				NHS_UTL_ALERTQUOTA(''' || v_BKGALERT || ''', '''', (TO_DATE(''' || v_BKGSDATE || ' 00:00:00'', ''DD/MM/YYYY HH24:MI:SS'') + ROWNUM - 1))
			FROM   ALL_OBJECTS
			WHERE  ROWNUM <= (TO_DATE(''' || v_BKGEDATE || ' 00:00:00'', ''DD/MM/YYYY HH24:MI:SS'') + 1) - TO_DATE(''' || v_BKGSDATE || ' 00:00:00'', ''DD/MM/YYYY HH24:MI:SS'')) ORDER BY QDAY ';
	ELSE
		SQLSTR := 'SELECT '''', TO_CHAR(TO_DATE(''' || v_BKGSDATE || ' 00:00:00'', ''DD/MM/YYYY HH24:MI:SS'') + ROWNUM - 1, ''DD/MM/YYYY (DAY)''),
				NHS_UTL_ALERTQUOTA(''' || v_BKGALERT || ''', '''', (TO_DATE(''' || v_BKGSDATE || ' 00:00:00'', ''DD/MM/YYYY HH24:MI:SS'') + ROWNUM - 1))
			FROM   ALL_OBJECTS
			WHERE  ROWNUM <= (TO_DATE(''' || v_BKGEDATE || ' 00:00:00'', ''DD/MM/YYYY HH24:MI:SS'') + 1) - TO_DATE(''' || v_BKGSDATE || ' 00:00:00'', ''DD/MM/YYYY HH24:MI:SS'') ';
	END IF;

	OPEN OUTCUR FOR SQLSTR;
	RETURN OUTCUR;
END NHS_LIS_BOOKINGALERT;
/
