create or replace
FUNCTION           "NHS_ACT_NEWEDITDEPTAPP"(
	v_ACTION                IN VARCHAR2,
  v_DEPTTYPE                IN VARCHAR2,
	v_DEPTAID                 IN VARCHAR2,
	v_PATNO                 IN VARCHAR2,
	v_DEPTAFNAME              IN VARCHAR2,
	v_DEPTAGNAME              IN VARCHAR2,
	v_DEPTAHKID               IN VARCHAR2,
	v_DEPTABDATE              IN VARCHAR2,
	v_DEPTATEL                IN VARCHAR2,
	v_DEPTAOSDATE             IN VARCHAR2,
	v_DEPTAOEDATE             IN VARCHAR2,
	v_DEPTCID_RM              IN VARCHAR2,
	v_DEPTPID                 IN VARCHAR2,
	v_USRID                	  IN VARCHAR2,
	v_DEPTASEX                IN VARCHAR2,
	v_PATTYPE               IN VARCHAR2,
	v_DOCCODE_R             IN VARCHAR2,
	v_OLDSDATE              IN VARCHAR2,
	v_OLDEDATE              IN VARCHAR2,
	v_OLDROOM               IN VARCHAR2,
	v_ISCONTINUEMULTI       IN VARCHAR2,
	v_ISCONTINUEOVERLAP     IN VARCHAR2,
	v_DEPTPRMK              IN VARCHAR2,
	V_DEPTSPECBOOK			IN VARCHAR2,
	V_WARD					IN VARCHAR2,
  V_BED					IN VARCHAR2,
  V_DOCCODE_P   IN VARCHAR2,
	o_ERRMSG                OUT VARCHAR2
)
	RETURN NUMBER
AS
	o_errcode NUMBER;
	v_noOfRec NUMBER;
	v_newDEPTpid NUMBER;
	V_DEPTAID2 VARCHAR2(22);
  V_RMOTHER VARCHAR2(2);

BEGIN
	o_ERRCODE := 0;
	o_ERRMSG := 'OK';
	V_NOOFREC := 0;
  V_RMOTHER := '13';

	IF (v_ACTION = 'ADD' OR
		(v_ACTION = 'MOD' AND
			(v_OLDSDATE <> v_DEPTAOSDATE OR v_OLDEDATE <> v_DEPTAOEDATE OR v_OLDROOM <> v_DEPTCID_RM))) AND
			v_ISCONTINUEOVERLAP = 'N' THEN

		SELECT COUNT(1) INTO v_NOOFREC
		FROM   DEPT_APP A, DEPT_CODE C
		where  C.DEPTCSTS = -1
		AND    C.DEPTCTYPE = 'RM'
		AND    A.DEPTASTS NOT IN ('C','U','P') --not in Cancel,unblock,logged cancelled case
		AND    (v_DEPTAID IS NULL OR A.DEPTAID <> v_DEPTAID)
		AND    (v_DEPTCID_RM IS NULL OR (A.DEPTCID_RM = v_DEPTCID_RM AND V_DEPTCID_RM <> V_RMOTHER))
		AND    (A.DEPTAOSDATE < TO_DATE(v_DEPTAOSDATE, 'DD/MM/YYYY HH24:MI') OR A.DEPTAOSDATE < TO_DATE(v_DEPTAOEDATE, 'DD/MM/YYYY HH24:MI'))
		AND    (A.DEPTAOEDATE > TO_DATE(v_DEPTAOSDATE, 'DD/MM/YYYY HH24:MI') OR A.DEPTAOEDATE > TO_DATE(v_DEPTAOEDATE, 'DD/MM/YYYY HH24:MI'));

		IF v_NOOFREC > 0 THEN
			RETURN -200;
		END IF;
	END IF;

	-- SAVE
	IF v_ACTION = 'ADD' THEN
		SELECT SEQ_DEPT_APP.NEXTVAL INTO v_NEWDEPTPID FROM DUAL;

		INSERT INTO DEPT_APP (
			DEPTTYPE, DEPTAID, PATNO, DEPTAFNAME, DEPTAGNAME, DEPTAHKID, DEPTABDATE, DEPTATEL,
			DEPTAOSDATE, DEPTAOEDATE, DEPTCID_RM, DEPTPID,
			DEPTASTS, DEPTACDATE,
			DEPTUSRID, STECODE, DEPTASEX, PATTYPE,
			DOCCODE_R, DEPTPRMK, DEPTSPECBOOK,DEPTWARD, DEPTBED,DOCCODE_P
		) VALUES (
			v_DEPTTYPE, v_NEWDEPTPID, v_PATNO, v_DEPTAFNAME, v_DEPTAGNAME, v_DEPTAHKID,
			TO_DATE(v_DEPTABDATE,'DD/MM/YYYY'),
			v_DEPTATEL,
			TO_DATE(v_DEPTAOSDATE,'DD/MM/YYYY HH24:MI'),
			TO_DATE(v_DEPTAOEDATE,'DD/MM/YYYY HH24:MI'),
			v_DEPTCID_RM, v_DEPTPID,
			'N', SYSDATE, v_USRID, GET_CURRENT_STECODE(), v_DEPTASEX, v_PATTYPE,
			v_DOCCODE_R, v_DEPTPRMK, v_DEPTSPECBOOK,v_WARD, v_BED, V_DOCCODE_P
		);

		---------------
		-- save table
		---------------
		v_DEPTAID2 := v_NEWDEPTPID;

	ELSIF v_ACTION = 'MOD' THEN
		UPDATE DEPT_APP
		SET
			PATNO = v_PATNO,
			DEPTAFNAME = v_DEPTAFNAME,
			DEPTAGNAME = v_DEPTAGNAME,
			DEPTAHKID = v_DEPTAHKID,
			DEPTABDATE = TO_DATE(v_DEPTABDATE,'DD/MM/YYYY'),
			DEPTATEL = v_DEPTATEL,
			DEPTAOSDATE = TO_DATE(v_DEPTAOSDATE,'DD/MM/YYYY HH24:MI'),
			DEPTAOEDATE = TO_DATE(v_DEPTAOEDATE,'DD/MM/YYYY HH24:MI'),
			DEPTCID_RM = v_DEPTCID_RM,
			DEPTPID = v_DEPTPID,
			DEPTASEX = v_DEPTASEX,
			PATTYPE = v_PATTYPE,
			DOCCODE_R = v_DOCCODE_R,
			DEPTPRMK = v_DEPTPRMK,
			DEPTSPECBOOK = v_DEPTSPECBOOK,
			DEPTWARD = V_WARD,
			DEPTBED = V_BED,
      DOCCODE_P = V_DOCCODE_P,
      MODIFY_USER = v_USRID,
      MODIFY_DATE = SYSDATE
		WHERE DEPTAID = v_DEPTAID;
	END IF;
	RETURN o_ERRCODE;
EXCEPTION
WHEN OTHERS THEN
	ROLLBACK;
	dbms_output.put_line('An ERROR was encountered - '||SQLCODE||' -ERROR- '||SQLERRM);
	o_ERRMSG := SQLERRM || o_ERRMSG;

	RETURN -999;
END NHS_ACT_NEWEDITDEPTAPP;
/
