CREATE OR REPLACE FUNCTION "NHS_LIS_REGISTRATIONCHECK" (
	i_SPCCODE       IN VARCHAR2,
	i_IASSESSED     IN VARCHAR2,
	i_BKGSDATE_FROM IN VARCHAR2,
	i_BKGSDATE_TO   IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	v_COUNT NUMBER := 0;
	OUTCUR TYPES.CURSOR_TYPE;
BEGIN
	IF i_IASSESSED IS NOT NULL THEN
		IF i_IASSESSED = '20' THEN
			OPEN OUTCUR FOR
				SELECT '', 'DR. ' || DOCFNAME || ' (' || DOCCODE || ')', SUM(COUNT_DOC) TOTAL_COUNT_DOC
				FROM (
					SELECT D.DOCFNAME, D.DOCCODE, COUNT(1) COUNT_DOC
					FROM   BOOKING B
					INNER JOIN SCHEDULE S ON B.SCHID = S.SCHID
					INNER JOIN DOCTOR D ON S.DOCCODE = D.DOCCODE
					WHERE  B.BKGFDATE >= TO_DATE(i_BKGSDATE_FROM || ' 00:00:00', 'DD/MM/YYYY HH24:MI:SS')
					AND    B.BKGFDATE <= TO_DATE(i_BKGSDATE_TO || ' 23:59:59', 'DD/MM/YYYY HH24:MI:SS')
					AND    B.BKGSTS = 'F'
					AND    B.BKGALERT IN ('21', '22', '23')
					AND    D.DOCSTS = -1
					AND    D.SPCCODE = 'GP'
					GROUP BY D.DOCCODE, D.DOCFNAME
					UNION
					SELECT D.DOCFNAME, D.DOCCODE, 0 COUNT_DOC
					FROM   DOCTOR D
					WHERE  D.DOCSTS = -1
					AND    D.SPCCODE = 'GP'
					AND    D.DOCCODE NOT IN ('PBOG')
					AND   (D.DOCCODE NOT LIKE '9%' OR (D.DOCCODE like '9%' AND LENGTH(D.DOCCODE) <> 4))
					AND    D.DOCCODE NOT IN ('408')
					AND    D.ISPOSTSCHEDULE = -1
				)
				GROUP BY DOCCODE, DOCFNAME
				ORDER BY TOTAL_COUNT_DOC ASC, DOCFNAME, DOCCODE;
		ELSE
			OPEN OUTCUR FOR
				SELECT '', 'DR. ' || DOCFNAME || ' (' || DOCCODE || ')', SUM(COUNT_DOC) TOTAL_COUNT_DOC
				FROM (
					SELECT D.DOCFNAME, D.DOCCODE, COUNT(1) COUNT_DOC
					FROM   BOOKING B
					INNER JOIN SCHEDULE S ON B.SCHID = S.SCHID
					INNER JOIN DOCTOR D ON S.DOCCODE = D.DOCCODE
					WHERE  B.BKGFDATE >= TO_DATE(i_BKGSDATE_FROM || ' 00:00:00', 'DD/MM/YYYY HH24:MI:SS')
					AND    B.BKGFDATE <= TO_DATE(i_BKGSDATE_TO || ' 23:59:59', 'DD/MM/YYYY HH24:MI:SS')
					AND    B.BKGSTS = 'F'
					AND    B.BKGALERT = i_IASSESSED
					AND    D.DOCSTS = -1
					AND    D.SPCCODE = 'GP'
					GROUP BY D.DOCCODE, D.DOCFNAME
					UNION
					SELECT D.DOCFNAME, D.DOCCODE, 0 COUNT_DOC
					FROM   DOCTOR D
					WHERE  D.DOCSTS = -1
					AND    D.SPCCODE = 'GP'
					AND    D.DOCCODE NOT IN ('PBOG')
					AND   (D.DOCCODE NOT LIKE '9%' OR (D.DOCCODE like '9%' AND LENGTH(D.DOCCODE) <> 4))
					AND    D.DOCCODE NOT IN ('408')
					AND    D.ISPOSTSCHEDULE = -1
				)
				GROUP BY DOCCODE, DOCFNAME
				ORDER BY TOTAL_COUNT_DOC ASC, DOCFNAME, DOCCODE;
		END IF;
	ELSE
		OPEN OUTCUR FOR
			SELECT '', 'DR. ' || DOCFNAME || ' (' || DOCCODE || ')', SUM(COUNT_DOC) TOTAL_COUNT_DOC
			FROM (
				SELECT D.DOCFNAME, D.DOCCODE, COUNT(1) COUNT_DOC
				FROM   BOOKING B
				INNER JOIN SCHEDULE S ON B.SCHID = S.SCHID
				INNER JOIN DOCTOR D ON S.DOCCODE = D.DOCCODE
				WHERE  B.BKGFDATE >= TO_DATE(i_BKGSDATE_FROM || ' 00:00:00', 'DD/MM/YYYY HH24:MI:SS')
				AND    B.BKGFDATE <= TO_DATE(i_BKGSDATE_TO || ' 23:59:59', 'DD/MM/YYYY HH24:MI:SS')
				AND    B.BKGSTS = 'F'
				AND    D.DOCSTS = -1
				AND    D.SPCCODE = 'GP'
				GROUP BY D.DOCCODE, D.DOCFNAME
				UNION
				SELECT D.DOCFNAME, D.DOCCODE, 0 COUNT_DOC
				FROM   DOCTOR D
				WHERE  D.DOCSTS = -1
				AND    D.SPCCODE = 'GP'
				AND    D.DOCCODE NOT IN ('PBOG')
				AND   (D.DOCCODE NOT LIKE '9%' OR (D.DOCCODE like '9%' AND LENGTH(D.DOCCODE) <> 4))
				AND    D.DOCCODE NOT IN ('408')
				AND    D.ISPOSTSCHEDULE = -1
			)
			GROUP BY DOCCODE, DOCFNAME
			ORDER BY TOTAL_COUNT_DOC ASC, DOCFNAME, DOCCODE;
	END IF;

	RETURN OUTCUR;
END NHS_LIS_REGISTRATIONCHECK;
/
