CREATE OR REPLACE FUNCTION "NHS_LIS_SLOT_BY_SPEC"(
	v_SPCCODE IN VARCHAR2,
	v_DOCLOCID    IN VARCHAR2,
	v_STECODE IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
BEGIN
	OPEN OUTCUR FOR
		-- "", "SCHID", "Doctor Code", "Time", "Duration"
		SELECT '', S.SCHID, Q.DOCCODE, TO_CHAR(SLTSTIME, 'DD/MM/YYYY HH24:MI') SLTSTIME_STR, SCHLEN
		FROM (	SELECT MIN(SLTID) AS SLTID, DOCCODE
				FROM (	SELECT SL.SLTID, S.SCHID, S.DOCCODE, SL.SLTSTIME, S.SCHLEN
						FROM SLOT SL, SCHEDULE S, DOCTOR D
						WHERE SL.SLTSTIME >= SYSDATE
						AND   SL.SLTSTIME < TRUNC(SYSDATE) + 1
						AND   S.STECODE = v_STECODE
						AND   D.SPCCODE = v_SPCCODE
						AND ( v_DOCLOCID IS NULL OR S.DOCLOCID = v_DOCLOCID )
						AND   S.DOCCODE = D.DOCCODE
						AND   D.DOCSTS = -1
						AND   S.SCHSTS = 'N'
						AND   SL.SCHID = S.SCHID
						AND   SL.SLTCNT = 0)
				GROUP BY DOCCODE) Q,
			SLOT SL2,
			SCHEDULE S
		WHERE SL2.SCHID = S.SCHID
		AND   Q.SLTID = SL2.SLTID
		ORDER BY SLTSTIME_STR, Q.DOCCODE;

	RETURN OUTCUR;
END NHS_LIS_SLOT_BY_SPEC;
/
