CREATE OR REPLACE FUNCTION "NHS_LIS_SLOT" (
	v_SCHID IN VARCHAR2
)
	RETURN Types.cursor_type
AS
	outcur types.cursor_type;
BEGIN
	IF GET_CURRENT_STECODE = 'TWAH' THEN
		OPEN OUTCUR FOR
			SELECT
				SLTID,
				SCHID,
				TO_CHAR(SLTSTIME,'dd/mm/yyyy hh24:mi:ss'),
				TO_CHAR(SLTSTIME, 'hh24:mi'),
				SLTCNT,
				0
			FROM SLOT
			WHERE SCHID = TO_NUMBER(v_SCHID)
			ORDER BY SLTSTIME;
	ELSE
		OPEN OUTCUR FOR
			SELECT SLTID, SCHID, SLTSDATE, SLTSTIME, SLTCNT, DECODE(NEWCASE, 0, '', '*')
			FROM (
				SELECT
					SLTID,
					SCHID,
					TO_CHAR(SLTSTIME,'dd/mm/yyyy hh24:mi:ss') SLTSDATE,
					TO_CHAR(SLTSTIME, 'hh24:mi') SLTSTIME,
					SLTCNT,
					NHS_UTL_BOOKING_NEWCASE(SCHID, SLTID) NEWCASE
				FROM SLOT
				WHERE SCHID = TO_NUMBER(v_SCHID)
			)
			ORDER BY SLTSTIME;
	END IF;

	RETURN OUTCUR;
END NHS_LIS_SLOT;
/
