CREATE OR REPLACE FUNCTION "NHS_GET_DOCTOR_ACTIVE" (
	v_DOCCODE IN VARCHAR2
)
	RETURN types.CURSOR_TYPE
AS
	OUTCUR types.CURSOR_TYPE;
	DOCTOR_STATUS_ACTIVE NUMBER := -1;
BEGIN
	OPEN OUTCUR FOR
		SELECT DocFName || ' ' || DocGName, DocTSlot, DocCName, SpcCode
		FROM   Doctor
		WHERE  doccode = v_DOCCODE
		and    docsts = DOCTOR_STATUS_ACTIVE;

	RETURN OUTCUR;
END NHS_GET_DOCTOR_ACTIVE;
/
