CREATE OR REPLACE FUNCTION "NHS_LIS_DEPTDVATABLELIST" (
	v_STDSTART IN VARCHAR2,
	v_SITECODE IN VARCHAR2,
	v_DEPTTYPE IN VARCHAR2,
	v_OTCCHR_1 IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
	SQLSTR VARCHAR2(2000);
BEGIN
	SQLSTR := '	
		SELECT A.DEPTAID, A.DEPTASTS, TO_CHAR(A.DEPTAOSDATE,''dd/mm/yyyy hh24:mi''),
				TO_CHAR(A.DEPTAOEDATE,''dd/mm/yyyy hh24:mi''), C.DEPTCID, C.DEPTCDESC,
				C.DEPTCORD, A.DEPTAFNAME || '' '' || A.DEPTAGNAME AS PATNAME,
				P.DEPTPSFORM, A.PATNO, docfname || '' '' || docgname as docname, P.DEPTPDESC, A.DEPTSPECBOOK
		FROM  DEPT_PROC P, DEPT_APP A, DEPT_CODE C, DOCTOR D
		WHERE A.DEPTPID = P.DEPTPID
		AND   A.DEPTCID_RM = C.DEPTCID
		AND   C.DEPTCSTS  = -1
		AND   A.DOCCODE_R = D.DOCCODE(+)
		AND   C.DEPTCTYPE = ''RM''
		AND   (A.DEPTASTS = ''N'' OR A.DEPTASTS = ''F'')
		AND   TRUNC(A.DEPTAOSDATE) <= TO_DATE('''||v_STDSTART||''', ''dd/mm/yyyy'')
		AND   TRUNC(A.DEPTAOEDATE) >= TO_DATE('''||v_STDSTART||''', ''dd/mm/yyyy'')    
		AND   A.STECODE = ''' || v_SITECODE || '''
    	AND   A.DEPTTYPE = ''' || v_DEPTTYPE || '''';

	IF v_OTCCHR_1 IS NOT NULL THEN
		SQLSTR := SQLSTR || ' AND C.DEPTCCHR_1 = ''' || v_OTCCHR_1 || '''';
	ELSE
		SQLSTR := SQLSTR||' AND (C.DEPTCCHR_1 IS NULL OR C.DEPTCCHR_1 = '''')';
	END IF;
	SQLSTR := SQLSTR||' ORDER BY C.DEPTCORD, A.DEPTAOSDATE';

	OPEN OUTCUR FOR SQLSTR;
	RETURN OUTCUR;
END NHS_LIS_DEPTDVATABLELIST;
/