create or replace
FUNCTION "NHS_LIS_DEPTAPPBSE" (
  v_DEPTTYPE   IN VARCHAR2,
	v_DEPTAOSDATE  IN VARCHAR2,
	v_DEPTAOEDATE  IN VARCHAR2,
	v_DEPTASTS     IN VARCHAR2,
	v_PATNO      IN VARCHAR2,
	v_DEPTAFNAME   IN VARCHAR2,
	v_DEPTCID      IN VARCHAR2,
	v_DEPTPID      IN VARCHAR2,
	v_SORTER     IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	SQLSTR VARCHAR2(2000);
	OUTCUR TYPES.CURSOR_TYPE;
BEGIN
	SQLSTR := '
		SELECT A.DEPTAID,
			'''' AS ALLERGY,
			TO_CHAR(A.DEPTAOSDATE, ''DD/MM/YYYY HH24:MI''),
			TO_CHAR(A.DEPTAOEDATE, ''DD/MM/YYYY HH24:MI''),
			DECODE(PAT.PMCID, NULL, NULL, 0, NULL, ''M'') AS MERGED,
			A.PATNO,
			A.DEPTAFNAME,
			A.DEPTAGNAME,
			A.DEPTAFNAME || '' '' || A.DEPTAGNAME AS PATNAME,
			TRUNC(MONTHS_BETWEEN(SYSDATE, A.DEPTABDATE) / 12) AS AGE,
			C.DEPTCDESC AS DEPTPDESC_RM,
			P.DEPTPDESC,
			DECODE(A.DEPTASTS, ''N'', ''Normal'', ''F'', ''Confirmed'', ''C'', ''Cancel'') AS STATUS,
			U.USRNAME,
			A.DEPTASTS
		FROM DEPT_APP  A,			
			DEPT_PROC P,
			USR     U,
			DEPT_CODE C,
			PATIENT PAT
		WHERE A.DEPTPID = P.DEPTPID		
		AND A.DEPTUSRID = U.USRID
		AND A.DEPTCID_RM = C.DEPTCID
		AND A.PATNO = PAT.PATNO(+)
		AND C.DEPTCTYPE = ''RM'' ';
    
  IF v_DEPTTYPE IS NOT NULL THEN
		SQLSTR := SQLSTR || ' AND A.DEPTTYPE = ''' || V_DEPTTYPE || '''';
	END IF;

	IF v_DEPTAOSDATE IS NOT NULL THEN
		SQLSTR:=SQLSTR ||' AND TRUNC(A.DEPTAOSDATE, ''mi'') >= TO_DATE(''' || v_DEPTAOSDATE || ''', ''DD/MM/YYYY HH24:MI'')';
	END IF;

	IF v_DEPTAOEDATE IS NOT NULL THEN
		SQLSTR:=SQLSTR ||' AND TRUNC(A.DEPTAOSDATE, ''mi'') <= TO_DATE(''' || v_DEPTAOEDATE || ''', ''DD/MM/YYYY HH24:MI'') ';
	END IF;

	IF v_DEPTASTS IS NOT NULL THEN
		SQLSTR := SQLSTR || ' AND A.DEPTASTS = ''' || v_DEPTASTS || '''';
	END IF;

	IF v_PATNO IS NOT NULL THEN
		SQLSTR := SQLSTR || ' AND A.PATNO = ''' || v_PATNO || '''';
	END IF;

	IF v_DEPTAFNAME IS NOT NULL THEN
		SQLSTR := SQLSTR || ' AND A.DEPTAFNAME || '' '' || A.DEPTAGNAME LIKE ''' || v_DEPTAFNAME||'%''';
	END IF;

	IF v_DEPTCID IS NOT NULL THEN
		SQLSTR := SQLSTR || ' AND C.DEPTCID = ''' || v_DEPTCID || '''';
	END IF;

	IF v_DEPTPID IS NOT NULL THEN
		SQLSTR := SQLSTR || ' AND P.DEPTPID = '||v_DEPTPID;
	END IF;
	IF v_SORTER IS NOT NULL THEN
		SQLSTR := SQLSTR || ' ORDER BY '||v_SORTER;
	END IF;

	OPEN OUTCUR FOR SQLSTR;
	RETURN OUTCUR;
END NHS_LIS_DEPTAPPBSE;