CREATE OR REPLACE FUNCTION "NHS_GET_MEDRECGETCUR"(
	v_PatNo IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
	MEDICAL_RECORD_NORMAL VARCHAR2(1) := 'N';
BEGIN
	OPEN OUTCUR FOR
		SELECT l.MrlDesc, m.MrmDesc, m.AutoAdd
		FROM   MedRecHdr h, MedRecMed m, MedRecDtl d, MedRecLoc l
		WHERE  h.PatNo = v_PatNo
		AND    h.MrmID = m.MrmID
		AND    h.MrdID = d.MrdID
		AND    NVL(d.MrlID_r, d.MrlID_l) = l.MrlID
		AND    h.MrhSts = MEDICAL_RECORD_NORMAL
		ORDER BY h.MrhID DESC;
	RETURN OUTCUR;
END NHS_GET_MEDRECGETCUR;
/
