//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.30 at 04:23:32 PM CST 
//


package org.hl7.v3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for allergy_detail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="allergy_detail">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:hl7-org:v3}record_key"/>
 *         &lt;element ref="{urn:hl7-org:v3}transaction_dtm"/>
 *         &lt;element ref="{urn:hl7-org:v3}transaction_type"/>
 *         &lt;element ref="{urn:hl7-org:v3}last_update_dtm" minOccurs="0"/>
 *         &lt;element ref="{urn:hl7-org:v3}episode_no" minOccurs="0"/>
 *         &lt;element ref="{urn:hl7-org:v3}attendance_inst_id" minOccurs="0"/>
 *         &lt;element name="type_of_allergen" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="type_of_allergen_code" type="{urn:hl7-org:v3}type_of_allergen_code" minOccurs="0"/>
 *                   &lt;element name="type_of_allergen_desc" type="{urn:hl7-org:v3}type_of_allergen_desc" minOccurs="0"/>
 *                   &lt;element name="type_of_allergen_lt_desc" type="{urn:hl7-org:v3}type_of_allergen_lt_desc" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="allergen" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="allergen_rt_name" type="{urn:hl7-org:v3}allergen_rt_name" minOccurs="0"/>
 *                   &lt;element name="allergen_rt_id" type="{urn:hl7-org:v3}allergen_rt_id" minOccurs="0"/>
 *                   &lt;element name="allergen_rt_desc" type="{urn:hl7-org:v3}allergen_rt_desc" minOccurs="0"/>
 *                   &lt;element name="allergen_lt_code" type="{urn:hl7-org:v3}allergen_lt_code" minOccurs="0"/>
 *                   &lt;element name="allergen_lt_desc" type="{urn:hl7-org:v3}allergen_lt_desc" minOccurs="0"/>
 *                   &lt;element name="level_of_certainty_code" type="{urn:hl7-org:v3}level_of_certainty_code" minOccurs="0"/>
 *                   &lt;element name="level_of_certainty_desc" type="{urn:hl7-org:v3}level_of_certainty_desc" minOccurs="0"/>
 *                   &lt;element name="level_of_certainty_lt_desc" type="{urn:hl7-org:v3}level_of_certainty_lt_desc" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="allergic_reaction" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="allergic_reaction_code" type="{urn:hl7-org:v3}allergic_reaction_code" minOccurs="0"/>
 *                   &lt;element name="allergic_reaction_desc" type="{urn:hl7-org:v3}allergic_reaction_desc" minOccurs="0"/>
 *                   &lt;element name="allergic_reaction_lt_desc" type="{urn:hl7-org:v3}allergic_reaction_lt_desc" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="delete_allergen_reason" type="{urn:hl7-org:v3}delete_allergen_reason" minOccurs="0"/>
 *         &lt;element name="allergen_remark" type="{urn:hl7-org:v3}allergen_remark" minOccurs="0"/>
 *         &lt;element name="allergy_note" type="{urn:hl7-org:v3}allergy_note" minOccurs="0"/>
 *         &lt;element ref="{urn:hl7-org:v3}record_creation_dtm" minOccurs="0"/>
 *         &lt;element ref="{urn:hl7-org:v3}record_creation_inst_id" minOccurs="0"/>
 *         &lt;element ref="{urn:hl7-org:v3}record_creation_inst_name" minOccurs="0"/>
 *         &lt;element ref="{urn:hl7-org:v3}record_update_dtm" minOccurs="0"/>
 *         &lt;element ref="{urn:hl7-org:v3}record_update_inst_id" minOccurs="0"/>
 *         &lt;element ref="{urn:hl7-org:v3}record_update_inst_name" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "allergy_detail", propOrder = {
    "recordKey",
    "transactionDtm",
    "transactionType",
    "lastUpdateDtm",
    "episodeNo",
    "attendanceInstId",
    "typeOfAllergen",
    "allergen",
    "allergicReaction",
    "deleteAllergenReason",
    "allergenRemark",
    "allergyNote",
    "recordCreationDtm",
    "recordCreationInstId",
    "recordCreationInstName",
    "recordUpdateDtm",
    "recordUpdateInstId",
    "recordUpdateInstName"
})
public class AllergyDetail {

    @XmlElement(name = "record_key", required = true)
    protected String recordKey;
    @XmlElement(name = "transaction_dtm", required = true)
    protected String transactionDtm;
    @XmlElement(name = "transaction_type", required = true)
    protected String transactionType;
    @XmlElement(name = "last_update_dtm")
    protected String lastUpdateDtm;
    @XmlElement(name = "episode_no")
    protected String episodeNo;
    @XmlElement(name = "attendance_inst_id")
    protected String attendanceInstId;
    @XmlElement(name = "type_of_allergen")
    protected AllergyDetail.TypeOfAllergen typeOfAllergen;
    protected AllergyDetail.Allergen allergen;
    @XmlElement(name = "allergic_reaction")
    protected List<AllergyDetail.AllergicReaction> allergicReaction;
    @XmlElement(name = "delete_allergen_reason")
    protected String deleteAllergenReason;
    @XmlElement(name = "allergen_remark")
    protected String allergenRemark;
    @XmlElement(name = "allergy_note")
    protected String allergyNote;
    @XmlElement(name = "record_creation_dtm")
    protected String recordCreationDtm;
    @XmlElement(name = "record_creation_inst_id")
    protected String recordCreationInstId;
    @XmlElement(name = "record_creation_inst_name")
    protected String recordCreationInstName;
    @XmlElement(name = "record_update_dtm")
    protected String recordUpdateDtm;
    @XmlElement(name = "record_update_inst_id")
    protected String recordUpdateInstId;
    @XmlElement(name = "record_update_inst_name")
    protected String recordUpdateInstName;

    /**
     * Gets the value of the recordKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordKey() {
        return recordKey;
    }

    /**
     * Sets the value of the recordKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordKey(String value) {
        this.recordKey = value;
    }

    /**
     * Gets the value of the transactionDtm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionDtm() {
        return transactionDtm;
    }

    /**
     * Sets the value of the transactionDtm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionDtm(String value) {
        this.transactionDtm = value;
    }

    /**
     * Gets the value of the transactionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionType() {
        return transactionType;
    }

    /**
     * Sets the value of the transactionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionType(String value) {
        this.transactionType = value;
    }

    /**
     * Gets the value of the lastUpdateDtm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastUpdateDtm() {
        return lastUpdateDtm;
    }

    /**
     * Sets the value of the lastUpdateDtm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastUpdateDtm(String value) {
        this.lastUpdateDtm = value;
    }

    /**
     * Gets the value of the episodeNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEpisodeNo() {
        return episodeNo;
    }

    /**
     * Sets the value of the episodeNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEpisodeNo(String value) {
        this.episodeNo = value;
    }

    /**
     * Gets the value of the attendanceInstId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttendanceInstId() {
        return attendanceInstId;
    }

    /**
     * Sets the value of the attendanceInstId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttendanceInstId(String value) {
        this.attendanceInstId = value;
    }

    /**
     * Gets the value of the typeOfAllergen property.
     * 
     * @return
     *     possible object is
     *     {@link AllergyDetail.TypeOfAllergen }
     *     
     */
    public AllergyDetail.TypeOfAllergen getTypeOfAllergen() {
        return typeOfAllergen;
    }

    /**
     * Sets the value of the typeOfAllergen property.
     * 
     * @param value
     *     allowed object is
     *     {@link AllergyDetail.TypeOfAllergen }
     *     
     */
    public void setTypeOfAllergen(AllergyDetail.TypeOfAllergen value) {
        this.typeOfAllergen = value;
    }

    /**
     * Gets the value of the allergen property.
     * 
     * @return
     *     possible object is
     *     {@link AllergyDetail.Allergen }
     *     
     */
    public AllergyDetail.Allergen getAllergen() {
        return allergen;
    }

    /**
     * Sets the value of the allergen property.
     * 
     * @param value
     *     allowed object is
     *     {@link AllergyDetail.Allergen }
     *     
     */
    public void setAllergen(AllergyDetail.Allergen value) {
        this.allergen = value;
    }

    /**
     * Gets the value of the allergicReaction property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the allergicReaction property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAllergicReaction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AllergyDetail.AllergicReaction }
     * 
     * 
     */
    public List<AllergyDetail.AllergicReaction> getAllergicReaction() {
        if (allergicReaction == null) {
            allergicReaction = new ArrayList<AllergyDetail.AllergicReaction>();
        }
        return this.allergicReaction;
    }

    /**
     * Gets the value of the deleteAllergenReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeleteAllergenReason() {
        return deleteAllergenReason;
    }

    /**
     * Sets the value of the deleteAllergenReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeleteAllergenReason(String value) {
        this.deleteAllergenReason = value;
    }

    /**
     * Gets the value of the allergenRemark property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAllergenRemark() {
        return allergenRemark;
    }

    /**
     * Sets the value of the allergenRemark property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAllergenRemark(String value) {
        this.allergenRemark = value;
    }

    /**
     * Gets the value of the allergyNote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAllergyNote() {
        return allergyNote;
    }

    /**
     * Sets the value of the allergyNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAllergyNote(String value) {
        this.allergyNote = value;
    }

    /**
     * Gets the value of the recordCreationDtm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordCreationDtm() {
        return recordCreationDtm;
    }

    /**
     * Sets the value of the recordCreationDtm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordCreationDtm(String value) {
        this.recordCreationDtm = value;
    }

    /**
     * Gets the value of the recordCreationInstId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordCreationInstId() {
        return recordCreationInstId;
    }

    /**
     * Sets the value of the recordCreationInstId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordCreationInstId(String value) {
        this.recordCreationInstId = value;
    }

    /**
     * Gets the value of the recordCreationInstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordCreationInstName() {
        return recordCreationInstName;
    }

    /**
     * Sets the value of the recordCreationInstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordCreationInstName(String value) {
        this.recordCreationInstName = value;
    }

    /**
     * Gets the value of the recordUpdateDtm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordUpdateDtm() {
        return recordUpdateDtm;
    }

    /**
     * Sets the value of the recordUpdateDtm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordUpdateDtm(String value) {
        this.recordUpdateDtm = value;
    }

    /**
     * Gets the value of the recordUpdateInstId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordUpdateInstId() {
        return recordUpdateInstId;
    }

    /**
     * Sets the value of the recordUpdateInstId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordUpdateInstId(String value) {
        this.recordUpdateInstId = value;
    }

    /**
     * Gets the value of the recordUpdateInstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordUpdateInstName() {
        return recordUpdateInstName;
    }

    /**
     * Sets the value of the recordUpdateInstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordUpdateInstName(String value) {
        this.recordUpdateInstName = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="allergen_rt_name" type="{urn:hl7-org:v3}allergen_rt_name" minOccurs="0"/>
     *         &lt;element name="allergen_rt_id" type="{urn:hl7-org:v3}allergen_rt_id" minOccurs="0"/>
     *         &lt;element name="allergen_rt_desc" type="{urn:hl7-org:v3}allergen_rt_desc" minOccurs="0"/>
     *         &lt;element name="allergen_lt_code" type="{urn:hl7-org:v3}allergen_lt_code" minOccurs="0"/>
     *         &lt;element name="allergen_lt_desc" type="{urn:hl7-org:v3}allergen_lt_desc" minOccurs="0"/>
     *         &lt;element name="level_of_certainty_code" type="{urn:hl7-org:v3}level_of_certainty_code" minOccurs="0"/>
     *         &lt;element name="level_of_certainty_desc" type="{urn:hl7-org:v3}level_of_certainty_desc" minOccurs="0"/>
     *         &lt;element name="level_of_certainty_lt_desc" type="{urn:hl7-org:v3}level_of_certainty_lt_desc" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "allergenRtName",
        "allergenRtId",
        "allergenRtDesc",
        "allergenLtCode",
        "allergenLtDesc",
        "levelOfCertaintyCode",
        "levelOfCertaintyDesc",
        "levelOfCertaintyLtDesc"
    })
    public static class Allergen {

        @XmlElement(name = "allergen_rt_name")
        protected String allergenRtName;
        @XmlElement(name = "allergen_rt_id")
        protected String allergenRtId;
        @XmlElement(name = "allergen_rt_desc")
        protected String allergenRtDesc;
        @XmlElement(name = "allergen_lt_code")
        protected String allergenLtCode;
        @XmlElement(name = "allergen_lt_desc")
        protected String allergenLtDesc;
        @XmlElement(name = "level_of_certainty_code")
        protected String levelOfCertaintyCode;
        @XmlElement(name = "level_of_certainty_desc")
        protected String levelOfCertaintyDesc;
        @XmlElement(name = "level_of_certainty_lt_desc")
        protected String levelOfCertaintyLtDesc;

        /**
         * Gets the value of the allergenRtName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAllergenRtName() {
            return allergenRtName;
        }

        /**
         * Sets the value of the allergenRtName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAllergenRtName(String value) {
            this.allergenRtName = value;
        }

        /**
         * Gets the value of the allergenRtId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAllergenRtId() {
            return allergenRtId;
        }

        /**
         * Sets the value of the allergenRtId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAllergenRtId(String value) {
            this.allergenRtId = value;
        }

        /**
         * Gets the value of the allergenRtDesc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAllergenRtDesc() {
            return allergenRtDesc;
        }

        /**
         * Sets the value of the allergenRtDesc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAllergenRtDesc(String value) {
            this.allergenRtDesc = value;
        }

        /**
         * Gets the value of the allergenLtCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAllergenLtCode() {
            return allergenLtCode;
        }

        /**
         * Sets the value of the allergenLtCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAllergenLtCode(String value) {
            this.allergenLtCode = value;
        }

        /**
         * Gets the value of the allergenLtDesc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAllergenLtDesc() {
            return allergenLtDesc;
        }

        /**
         * Sets the value of the allergenLtDesc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAllergenLtDesc(String value) {
            this.allergenLtDesc = value;
        }

        /**
         * Gets the value of the levelOfCertaintyCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLevelOfCertaintyCode() {
            return levelOfCertaintyCode;
        }

        /**
         * Sets the value of the levelOfCertaintyCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLevelOfCertaintyCode(String value) {
            this.levelOfCertaintyCode = value;
        }

        /**
         * Gets the value of the levelOfCertaintyDesc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLevelOfCertaintyDesc() {
            return levelOfCertaintyDesc;
        }

        /**
         * Sets the value of the levelOfCertaintyDesc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLevelOfCertaintyDesc(String value) {
            this.levelOfCertaintyDesc = value;
        }

        /**
         * Gets the value of the levelOfCertaintyLtDesc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLevelOfCertaintyLtDesc() {
            return levelOfCertaintyLtDesc;
        }

        /**
         * Sets the value of the levelOfCertaintyLtDesc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLevelOfCertaintyLtDesc(String value) {
            this.levelOfCertaintyLtDesc = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="allergic_reaction_code" type="{urn:hl7-org:v3}allergic_reaction_code" minOccurs="0"/>
     *         &lt;element name="allergic_reaction_desc" type="{urn:hl7-org:v3}allergic_reaction_desc" minOccurs="0"/>
     *         &lt;element name="allergic_reaction_lt_desc" type="{urn:hl7-org:v3}allergic_reaction_lt_desc" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "allergicReactionCode",
        "allergicReactionDesc",
        "allergicReactionLtDesc"
    })
    public static class AllergicReaction {

        @XmlElement(name = "allergic_reaction_code")
        protected String allergicReactionCode;
        @XmlElement(name = "allergic_reaction_desc")
        protected String allergicReactionDesc;
        @XmlElement(name = "allergic_reaction_lt_desc")
        protected String allergicReactionLtDesc;

        /**
         * Gets the value of the allergicReactionCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAllergicReactionCode() {
            return allergicReactionCode;
        }

        /**
         * Sets the value of the allergicReactionCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAllergicReactionCode(String value) {
            this.allergicReactionCode = value;
        }

        /**
         * Gets the value of the allergicReactionDesc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAllergicReactionDesc() {
            return allergicReactionDesc;
        }

        /**
         * Sets the value of the allergicReactionDesc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAllergicReactionDesc(String value) {
            this.allergicReactionDesc = value;
        }

        /**
         * Gets the value of the allergicReactionLtDesc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAllergicReactionLtDesc() {
            return allergicReactionLtDesc;
        }

        /**
         * Sets the value of the allergicReactionLtDesc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAllergicReactionLtDesc(String value) {
            this.allergicReactionLtDesc = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="type_of_allergen_code" type="{urn:hl7-org:v3}type_of_allergen_code" minOccurs="0"/>
     *         &lt;element name="type_of_allergen_desc" type="{urn:hl7-org:v3}type_of_allergen_desc" minOccurs="0"/>
     *         &lt;element name="type_of_allergen_lt_desc" type="{urn:hl7-org:v3}type_of_allergen_lt_desc" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "typeOfAllergenCode",
        "typeOfAllergenDesc",
        "typeOfAllergenLtDesc"
    })
    public static class TypeOfAllergen {

        @XmlElement(name = "type_of_allergen_code")
        protected String typeOfAllergenCode;
        @XmlElement(name = "type_of_allergen_desc")
        protected String typeOfAllergenDesc;
        @XmlElement(name = "type_of_allergen_lt_desc")
        protected String typeOfAllergenLtDesc;

        /**
         * Gets the value of the typeOfAllergenCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTypeOfAllergenCode() {
            return typeOfAllergenCode;
        }

        /**
         * Sets the value of the typeOfAllergenCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTypeOfAllergenCode(String value) {
            this.typeOfAllergenCode = value;
        }

        /**
         * Gets the value of the typeOfAllergenDesc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTypeOfAllergenDesc() {
            return typeOfAllergenDesc;
        }

        /**
         * Sets the value of the typeOfAllergenDesc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTypeOfAllergenDesc(String value) {
            this.typeOfAllergenDesc = value;
        }

        /**
         * Gets the value of the typeOfAllergenLtDesc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTypeOfAllergenLtDesc() {
            return typeOfAllergenLtDesc;
        }

        /**
         * Sets the value of the typeOfAllergenLtDesc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTypeOfAllergenLtDesc(String value) {
            this.typeOfAllergenLtDesc = value;
        }

    }

}
