//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.30 at 04:23:32 PM CST 
//


package org.hl7.v3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for causative_agent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="causative_agent">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:hl7-org:v3}record_key"/>
 *         &lt;element ref="{urn:hl7-org:v3}transaction_dtm"/>
 *         &lt;element ref="{urn:hl7-org:v3}transaction_type"/>
 *         &lt;element ref="{urn:hl7-org:v3}last_update_dtm" minOccurs="0"/>
 *         &lt;element ref="{urn:hl7-org:v3}episode_no" minOccurs="0"/>
 *         &lt;element ref="{urn:hl7-org:v3}attendance_inst_id" minOccurs="0"/>
 *         &lt;element name="causative_agent_name" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="causative_agent_rt_name" type="{urn:hl7-org:v3}causative_agent_rt_name" minOccurs="0"/>
 *                   &lt;element name="causative_agent_rt_id" type="{urn:hl7-org:v3}causative_agent_rt_id" minOccurs="0"/>
 *                   &lt;element name="causative_agent_rt_desc" type="{urn:hl7-org:v3}causative_agent_rt_desc" minOccurs="0"/>
 *                   &lt;element name="causative_agent_lt_code" type="{urn:hl7-org:v3}causative_agent_lt_code" minOccurs="0"/>
 *                   &lt;element name="causative_agent_lt_desc" type="{urn:hl7-org:v3}causative_agent_lt_desc" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="level_of_severity" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="level_of_severity_code" type="{urn:hl7-org:v3}level_of_severity_code" minOccurs="0"/>
 *                   &lt;element name="level_of_severity_desc" type="{urn:hl7-org:v3}level_of_severity_desc" minOccurs="0"/>
 *                   &lt;element name="level_of_severity_lt_desc" type="{urn:hl7-org:v3}level_of_severity_lt_desc" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="adr_desc" type="{urn:hl7-org:v3}adr_desc" minOccurs="0"/>
 *         &lt;element name="delete_reason" type="{urn:hl7-org:v3}delete_reason" minOccurs="0"/>
 *         &lt;element name="causative_agent_remark" type="{urn:hl7-org:v3}causative_agent_remark" minOccurs="0"/>
 *         &lt;element name="adr_note" type="{urn:hl7-org:v3}adr_note" minOccurs="0"/>
 *         &lt;element ref="{urn:hl7-org:v3}record_creation_dtm" minOccurs="0"/>
 *         &lt;element ref="{urn:hl7-org:v3}record_creation_inst_id" minOccurs="0"/>
 *         &lt;element ref="{urn:hl7-org:v3}record_creation_inst_name" minOccurs="0"/>
 *         &lt;element ref="{urn:hl7-org:v3}record_update_dtm" minOccurs="0"/>
 *         &lt;element ref="{urn:hl7-org:v3}record_update_inst_id" minOccurs="0"/>
 *         &lt;element ref="{urn:hl7-org:v3}record_update_inst_name" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "causative_agent", propOrder = {
    "recordKey",
    "transactionDtm",
    "transactionType",
    "lastUpdateDtm",
    "episodeNo",
    "attendanceInstId",
    "causativeAgentName",
    "levelOfSeverity",
    "adrDesc",
    "deleteReason",
    "causativeAgentRemark",
    "adrNote",
    "recordCreationDtm",
    "recordCreationInstId",
    "recordCreationInstName",
    "recordUpdateDtm",
    "recordUpdateInstId",
    "recordUpdateInstName"
})
public class CausativeAgent {

    @XmlElement(name = "record_key", required = true)
    protected String recordKey;
    @XmlElement(name = "transaction_dtm", required = true)
    protected String transactionDtm;
    @XmlElement(name = "transaction_type", required = true)
    protected String transactionType;
    @XmlElement(name = "last_update_dtm")
    protected String lastUpdateDtm;
    @XmlElement(name = "episode_no")
    protected String episodeNo;
    @XmlElement(name = "attendance_inst_id")
    protected String attendanceInstId;
    @XmlElement(name = "causative_agent_name")
    protected CausativeAgent.CausativeAgentName causativeAgentName;
    @XmlElement(name = "level_of_severity")
    protected CausativeAgent.LevelOfSeverity levelOfSeverity;
    @XmlElement(name = "adr_desc")
    protected String adrDesc;
    @XmlElement(name = "delete_reason")
    protected String deleteReason;
    @XmlElement(name = "causative_agent_remark")
    protected String causativeAgentRemark;
    @XmlElement(name = "adr_note")
    protected String adrNote;
    @XmlElement(name = "record_creation_dtm")
    protected String recordCreationDtm;
    @XmlElement(name = "record_creation_inst_id")
    protected String recordCreationInstId;
    @XmlElement(name = "record_creation_inst_name")
    protected String recordCreationInstName;
    @XmlElement(name = "record_update_dtm")
    protected String recordUpdateDtm;
    @XmlElement(name = "record_update_inst_id")
    protected String recordUpdateInstId;
    @XmlElement(name = "record_update_inst_name")
    protected String recordUpdateInstName;

    /**
     * Gets the value of the recordKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordKey() {
        return recordKey;
    }

    /**
     * Sets the value of the recordKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordKey(String value) {
        this.recordKey = value;
    }

    /**
     * Gets the value of the transactionDtm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionDtm() {
        return transactionDtm;
    }

    /**
     * Sets the value of the transactionDtm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionDtm(String value) {
        this.transactionDtm = value;
    }

    /**
     * Gets the value of the transactionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionType() {
        return transactionType;
    }

    /**
     * Sets the value of the transactionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionType(String value) {
        this.transactionType = value;
    }

    /**
     * Gets the value of the lastUpdateDtm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastUpdateDtm() {
        return lastUpdateDtm;
    }

    /**
     * Sets the value of the lastUpdateDtm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastUpdateDtm(String value) {
        this.lastUpdateDtm = value;
    }

    /**
     * Gets the value of the episodeNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEpisodeNo() {
        return episodeNo;
    }

    /**
     * Sets the value of the episodeNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEpisodeNo(String value) {
        this.episodeNo = value;
    }

    /**
     * Gets the value of the attendanceInstId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttendanceInstId() {
        return attendanceInstId;
    }

    /**
     * Sets the value of the attendanceInstId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttendanceInstId(String value) {
        this.attendanceInstId = value;
    }

    /**
     * Gets the value of the causativeAgentName property.
     * 
     * @return
     *     possible object is
     *     {@link CausativeAgent.CausativeAgentName }
     *     
     */
    public CausativeAgent.CausativeAgentName getCausativeAgentName() {
        return causativeAgentName;
    }

    /**
     * Sets the value of the causativeAgentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link CausativeAgent.CausativeAgentName }
     *     
     */
    public void setCausativeAgentName(CausativeAgent.CausativeAgentName value) {
        this.causativeAgentName = value;
    }

    /**
     * Gets the value of the levelOfSeverity property.
     * 
     * @return
     *     possible object is
     *     {@link CausativeAgent.LevelOfSeverity }
     *     
     */
    public CausativeAgent.LevelOfSeverity getLevelOfSeverity() {
        return levelOfSeverity;
    }

    /**
     * Sets the value of the levelOfSeverity property.
     * 
     * @param value
     *     allowed object is
     *     {@link CausativeAgent.LevelOfSeverity }
     *     
     */
    public void setLevelOfSeverity(CausativeAgent.LevelOfSeverity value) {
        this.levelOfSeverity = value;
    }

    /**
     * Gets the value of the adrDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdrDesc() {
        return adrDesc;
    }

    /**
     * Sets the value of the adrDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdrDesc(String value) {
        this.adrDesc = value;
    }

    /**
     * Gets the value of the deleteReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeleteReason() {
        return deleteReason;
    }

    /**
     * Sets the value of the deleteReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeleteReason(String value) {
        this.deleteReason = value;
    }

    /**
     * Gets the value of the causativeAgentRemark property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCausativeAgentRemark() {
        return causativeAgentRemark;
    }

    /**
     * Sets the value of the causativeAgentRemark property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCausativeAgentRemark(String value) {
        this.causativeAgentRemark = value;
    }

    /**
     * Gets the value of the adrNote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdrNote() {
        return adrNote;
    }

    /**
     * Sets the value of the adrNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdrNote(String value) {
        this.adrNote = value;
    }

    /**
     * Gets the value of the recordCreationDtm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordCreationDtm() {
        return recordCreationDtm;
    }

    /**
     * Sets the value of the recordCreationDtm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordCreationDtm(String value) {
        this.recordCreationDtm = value;
    }

    /**
     * Gets the value of the recordCreationInstId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordCreationInstId() {
        return recordCreationInstId;
    }

    /**
     * Sets the value of the recordCreationInstId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordCreationInstId(String value) {
        this.recordCreationInstId = value;
    }

    /**
     * Gets the value of the recordCreationInstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordCreationInstName() {
        return recordCreationInstName;
    }

    /**
     * Sets the value of the recordCreationInstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordCreationInstName(String value) {
        this.recordCreationInstName = value;
    }

    /**
     * Gets the value of the recordUpdateDtm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordUpdateDtm() {
        return recordUpdateDtm;
    }

    /**
     * Sets the value of the recordUpdateDtm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordUpdateDtm(String value) {
        this.recordUpdateDtm = value;
    }

    /**
     * Gets the value of the recordUpdateInstId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordUpdateInstId() {
        return recordUpdateInstId;
    }

    /**
     * Sets the value of the recordUpdateInstId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordUpdateInstId(String value) {
        this.recordUpdateInstId = value;
    }

    /**
     * Gets the value of the recordUpdateInstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordUpdateInstName() {
        return recordUpdateInstName;
    }

    /**
     * Sets the value of the recordUpdateInstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordUpdateInstName(String value) {
        this.recordUpdateInstName = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="causative_agent_rt_name" type="{urn:hl7-org:v3}causative_agent_rt_name" minOccurs="0"/>
     *         &lt;element name="causative_agent_rt_id" type="{urn:hl7-org:v3}causative_agent_rt_id" minOccurs="0"/>
     *         &lt;element name="causative_agent_rt_desc" type="{urn:hl7-org:v3}causative_agent_rt_desc" minOccurs="0"/>
     *         &lt;element name="causative_agent_lt_code" type="{urn:hl7-org:v3}causative_agent_lt_code" minOccurs="0"/>
     *         &lt;element name="causative_agent_lt_desc" type="{urn:hl7-org:v3}causative_agent_lt_desc" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "causativeAgentRtName",
        "causativeAgentRtId",
        "causativeAgentRtDesc",
        "causativeAgentLtCode",
        "causativeAgentLtDesc"
    })
    public static class CausativeAgentName {

        @XmlElement(name = "causative_agent_rt_name")
        protected String causativeAgentRtName;
        @XmlElement(name = "causative_agent_rt_id")
        protected String causativeAgentRtId;
        @XmlElement(name = "causative_agent_rt_desc")
        protected String causativeAgentRtDesc;
        @XmlElement(name = "causative_agent_lt_code")
        protected String causativeAgentLtCode;
        @XmlElement(name = "causative_agent_lt_desc")
        protected String causativeAgentLtDesc;

        /**
         * Gets the value of the causativeAgentRtName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCausativeAgentRtName() {
            return causativeAgentRtName;
        }

        /**
         * Sets the value of the causativeAgentRtName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCausativeAgentRtName(String value) {
            this.causativeAgentRtName = value;
        }

        /**
         * Gets the value of the causativeAgentRtId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCausativeAgentRtId() {
            return causativeAgentRtId;
        }

        /**
         * Sets the value of the causativeAgentRtId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCausativeAgentRtId(String value) {
            this.causativeAgentRtId = value;
        }

        /**
         * Gets the value of the causativeAgentRtDesc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCausativeAgentRtDesc() {
            return causativeAgentRtDesc;
        }

        /**
         * Sets the value of the causativeAgentRtDesc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCausativeAgentRtDesc(String value) {
            this.causativeAgentRtDesc = value;
        }

        /**
         * Gets the value of the causativeAgentLtCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCausativeAgentLtCode() {
            return causativeAgentLtCode;
        }

        /**
         * Sets the value of the causativeAgentLtCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCausativeAgentLtCode(String value) {
            this.causativeAgentLtCode = value;
        }

        /**
         * Gets the value of the causativeAgentLtDesc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCausativeAgentLtDesc() {
            return causativeAgentLtDesc;
        }

        /**
         * Sets the value of the causativeAgentLtDesc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCausativeAgentLtDesc(String value) {
            this.causativeAgentLtDesc = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="level_of_severity_code" type="{urn:hl7-org:v3}level_of_severity_code" minOccurs="0"/>
     *         &lt;element name="level_of_severity_desc" type="{urn:hl7-org:v3}level_of_severity_desc" minOccurs="0"/>
     *         &lt;element name="level_of_severity_lt_desc" type="{urn:hl7-org:v3}level_of_severity_lt_desc" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "levelOfSeverityCode",
        "levelOfSeverityDesc",
        "levelOfSeverityLtDesc"
    })
    public static class LevelOfSeverity {

        @XmlElement(name = "level_of_severity_code")
        protected String levelOfSeverityCode;
        @XmlElement(name = "level_of_severity_desc")
        protected String levelOfSeverityDesc;
        @XmlElement(name = "level_of_severity_lt_desc")
        protected String levelOfSeverityLtDesc;

        /**
         * Gets the value of the levelOfSeverityCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLevelOfSeverityCode() {
            return levelOfSeverityCode;
        }

        /**
         * Sets the value of the levelOfSeverityCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLevelOfSeverityCode(String value) {
            this.levelOfSeverityCode = value;
        }

        /**
         * Gets the value of the levelOfSeverityDesc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLevelOfSeverityDesc() {
            return levelOfSeverityDesc;
        }

        /**
         * Sets the value of the levelOfSeverityDesc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLevelOfSeverityDesc(String value) {
            this.levelOfSeverityDesc = value;
        }

        /**
         * Gets the value of the levelOfSeverityLtDesc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLevelOfSeverityLtDesc() {
            return levelOfSeverityLtDesc;
        }

        /**
         * Sets the value of the levelOfSeverityLtDesc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLevelOfSeverityLtDesc(String value) {
            this.levelOfSeverityLtDesc = value;
        }

    }

}
