//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.30 at 04:23:32 PM CST 
//


package org.hl7.v3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="immu_detail" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="record_no" type="{urn:hl7-org:v3}record_no" minOccurs="0"/>
 *                   &lt;element name="record_remark" type="{urn:hl7-org:v3}record_remark" minOccurs="0"/>
 *                   &lt;element name="vaccine_adm" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{urn:hl7-org:v3}record_key"/>
 *                             &lt;element ref="{urn:hl7-org:v3}transaction_dtm"/>
 *                             &lt;element ref="{urn:hl7-org:v3}transaction_type"/>
 *                             &lt;element ref="{urn:hl7-org:v3}last_update_dtm" minOccurs="0"/>
 *                             &lt;element ref="{urn:hl7-org:v3}episode_no" minOccurs="0"/>
 *                             &lt;element ref="{urn:hl7-org:v3}attendance_inst_id" minOccurs="0"/>
 *                             &lt;element name="vaccine_rt_name" type="{urn:hl7-org:v3}vaccine_rt_name" minOccurs="0"/>
 *                             &lt;element name="vaccine_rt_id" type="{urn:hl7-org:v3}vaccine_rt_id" minOccurs="0"/>
 *                             &lt;element name="vaccine_rt_desc" type="{urn:hl7-org:v3}vaccine_rt_desc" minOccurs="0"/>
 *                             &lt;element name="vaccine_lt_id" type="{urn:hl7-org:v3}vaccine_lt_id" minOccurs="0"/>
 *                             &lt;element name="vaccine_lt_desc" type="{urn:hl7-org:v3}vaccine_lt_desc" minOccurs="0"/>
 *                             &lt;element name="route_of_adm_cd" type="{urn:hl7-org:v3}route_of_adm_cd" minOccurs="0"/>
 *                             &lt;element name="route_of_adm_desc" type="{urn:hl7-org:v3}route_of_adm_desc" minOccurs="0"/>
 *                             &lt;element name="route_of_adm_lt_desc" type="{urn:hl7-org:v3}route_of_adm_lt_desc" minOccurs="0"/>
 *                             &lt;element name="site_of_adm_cd" type="{urn:hl7-org:v3}site_of_adm_cd" minOccurs="0"/>
 *                             &lt;element name="site_of_adm_desc" type="{urn:hl7-org:v3}site_of_adm_desc" minOccurs="0"/>
 *                             &lt;element name="site_of_adm_lt_desc" type="{urn:hl7-org:v3}site_of_adm_lt_desc" minOccurs="0"/>
 *                             &lt;element name="vaccination_provider_cd" type="{urn:hl7-org:v3}vaccination_provider_cd" minOccurs="0"/>
 *                             &lt;element name="vaccination_provider_desc" type="{urn:hl7-org:v3}vaccination_provider_desc" minOccurs="0"/>
 *                             &lt;element name="vaccination_provider_lt_desc" type="{urn:hl7-org:v3}vaccination_provider_lt_desc" minOccurs="0"/>
 *                             &lt;element name="historical_immu" type="{urn:hl7-org:v3}historical_immu" minOccurs="0"/>
 *                             &lt;element name="vaccine_adm_date" type="{urn:hl7-org:v3}vaccine_adm_date" minOccurs="0"/>
 *                             &lt;element name="vaccine_dose_sequence" type="{urn:hl7-org:v3}vaccine_dose_sequence" minOccurs="0"/>
 *                             &lt;element name="batch_no" type="{urn:hl7-org:v3}batch_no" minOccurs="0"/>
 *                             &lt;element name="vaccine_adm_premises" type="{urn:hl7-org:v3}vaccine_adm_premises" minOccurs="0"/>
 *                             &lt;element name="vaccine_adm_remark" type="{urn:hl7-org:v3}vaccine_adm_remark" minOccurs="0"/>
 *                             &lt;element ref="{urn:hl7-org:v3}record_creation_dtm" minOccurs="0"/>
 *                             &lt;element ref="{urn:hl7-org:v3}record_creation_inst_id" minOccurs="0"/>
 *                             &lt;element ref="{urn:hl7-org:v3}record_creation_inst_name" minOccurs="0"/>
 *                             &lt;element ref="{urn:hl7-org:v3}record_update_dtm" minOccurs="0"/>
 *                             &lt;element ref="{urn:hl7-org:v3}record_update_inst_id" minOccurs="0"/>
 *                             &lt;element ref="{urn:hl7-org:v3}record_update_inst_name" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="immu_report" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="report_title" type="{urn:hl7-org:v3}report_title" minOccurs="0"/>
 *                             &lt;element name="text_report" type="{urn:hl7-org:v3}text_report" minOccurs="0"/>
 *                             &lt;element name="report_date" type="{urn:hl7-org:v3}report_date" minOccurs="0"/>
 *                             &lt;element ref="{urn:hl7-org:v3}file_ind" minOccurs="0"/>
 *                             &lt;element ref="{urn:hl7-org:v3}file_name" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "immuDetail"
})
@XmlRootElement(name = "immunisationDetail")
public class ImmunisationDetail {

    @XmlElement(name = "immu_detail", required = true)
    protected List<ImmunisationDetail.ImmuDetail> immuDetail;

    /**
     * Gets the value of the immuDetail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the immuDetail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImmuDetail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ImmunisationDetail.ImmuDetail }
     * 
     * 
     */
    public List<ImmunisationDetail.ImmuDetail> getImmuDetail() {
        if (immuDetail == null) {
            immuDetail = new ArrayList<ImmunisationDetail.ImmuDetail>();
        }
        return this.immuDetail;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="record_no" type="{urn:hl7-org:v3}record_no" minOccurs="0"/>
     *         &lt;element name="record_remark" type="{urn:hl7-org:v3}record_remark" minOccurs="0"/>
     *         &lt;element name="vaccine_adm" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{urn:hl7-org:v3}record_key"/>
     *                   &lt;element ref="{urn:hl7-org:v3}transaction_dtm"/>
     *                   &lt;element ref="{urn:hl7-org:v3}transaction_type"/>
     *                   &lt;element ref="{urn:hl7-org:v3}last_update_dtm" minOccurs="0"/>
     *                   &lt;element ref="{urn:hl7-org:v3}episode_no" minOccurs="0"/>
     *                   &lt;element ref="{urn:hl7-org:v3}attendance_inst_id" minOccurs="0"/>
     *                   &lt;element name="vaccine_rt_name" type="{urn:hl7-org:v3}vaccine_rt_name" minOccurs="0"/>
     *                   &lt;element name="vaccine_rt_id" type="{urn:hl7-org:v3}vaccine_rt_id" minOccurs="0"/>
     *                   &lt;element name="vaccine_rt_desc" type="{urn:hl7-org:v3}vaccine_rt_desc" minOccurs="0"/>
     *                   &lt;element name="vaccine_lt_id" type="{urn:hl7-org:v3}vaccine_lt_id" minOccurs="0"/>
     *                   &lt;element name="vaccine_lt_desc" type="{urn:hl7-org:v3}vaccine_lt_desc" minOccurs="0"/>
     *                   &lt;element name="route_of_adm_cd" type="{urn:hl7-org:v3}route_of_adm_cd" minOccurs="0"/>
     *                   &lt;element name="route_of_adm_desc" type="{urn:hl7-org:v3}route_of_adm_desc" minOccurs="0"/>
     *                   &lt;element name="route_of_adm_lt_desc" type="{urn:hl7-org:v3}route_of_adm_lt_desc" minOccurs="0"/>
     *                   &lt;element name="site_of_adm_cd" type="{urn:hl7-org:v3}site_of_adm_cd" minOccurs="0"/>
     *                   &lt;element name="site_of_adm_desc" type="{urn:hl7-org:v3}site_of_adm_desc" minOccurs="0"/>
     *                   &lt;element name="site_of_adm_lt_desc" type="{urn:hl7-org:v3}site_of_adm_lt_desc" minOccurs="0"/>
     *                   &lt;element name="vaccination_provider_cd" type="{urn:hl7-org:v3}vaccination_provider_cd" minOccurs="0"/>
     *                   &lt;element name="vaccination_provider_desc" type="{urn:hl7-org:v3}vaccination_provider_desc" minOccurs="0"/>
     *                   &lt;element name="vaccination_provider_lt_desc" type="{urn:hl7-org:v3}vaccination_provider_lt_desc" minOccurs="0"/>
     *                   &lt;element name="historical_immu" type="{urn:hl7-org:v3}historical_immu" minOccurs="0"/>
     *                   &lt;element name="vaccine_adm_date" type="{urn:hl7-org:v3}vaccine_adm_date" minOccurs="0"/>
     *                   &lt;element name="vaccine_dose_sequence" type="{urn:hl7-org:v3}vaccine_dose_sequence" minOccurs="0"/>
     *                   &lt;element name="batch_no" type="{urn:hl7-org:v3}batch_no" minOccurs="0"/>
     *                   &lt;element name="vaccine_adm_premises" type="{urn:hl7-org:v3}vaccine_adm_premises" minOccurs="0"/>
     *                   &lt;element name="vaccine_adm_remark" type="{urn:hl7-org:v3}vaccine_adm_remark" minOccurs="0"/>
     *                   &lt;element ref="{urn:hl7-org:v3}record_creation_dtm" minOccurs="0"/>
     *                   &lt;element ref="{urn:hl7-org:v3}record_creation_inst_id" minOccurs="0"/>
     *                   &lt;element ref="{urn:hl7-org:v3}record_creation_inst_name" minOccurs="0"/>
     *                   &lt;element ref="{urn:hl7-org:v3}record_update_dtm" minOccurs="0"/>
     *                   &lt;element ref="{urn:hl7-org:v3}record_update_inst_id" minOccurs="0"/>
     *                   &lt;element ref="{urn:hl7-org:v3}record_update_inst_name" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="immu_report" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="report_title" type="{urn:hl7-org:v3}report_title" minOccurs="0"/>
     *                   &lt;element name="text_report" type="{urn:hl7-org:v3}text_report" minOccurs="0"/>
     *                   &lt;element name="report_date" type="{urn:hl7-org:v3}report_date" minOccurs="0"/>
     *                   &lt;element ref="{urn:hl7-org:v3}file_ind" minOccurs="0"/>
     *                   &lt;element ref="{urn:hl7-org:v3}file_name" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "recordNo",
        "recordRemark",
        "vaccineAdm",
        "immuReport"
    })
    public static class ImmuDetail {

        @XmlElement(name = "record_no")
        protected String recordNo;
        @XmlElement(name = "record_remark")
        protected String recordRemark;
        @XmlElement(name = "vaccine_adm", required = true)
        protected List<ImmunisationDetail.ImmuDetail.VaccineAdm> vaccineAdm;
        @XmlElement(name = "immu_report")
        protected ImmunisationDetail.ImmuDetail.ImmuReport immuReport;

        /**
         * Gets the value of the recordNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRecordNo() {
            return recordNo;
        }

        /**
         * Sets the value of the recordNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRecordNo(String value) {
            this.recordNo = value;
        }

        /**
         * Gets the value of the recordRemark property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRecordRemark() {
            return recordRemark;
        }

        /**
         * Sets the value of the recordRemark property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRecordRemark(String value) {
            this.recordRemark = value;
        }

        /**
         * Gets the value of the vaccineAdm property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the vaccineAdm property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getVaccineAdm().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ImmunisationDetail.ImmuDetail.VaccineAdm }
         * 
         * 
         */
        public List<ImmunisationDetail.ImmuDetail.VaccineAdm> getVaccineAdm() {
            if (vaccineAdm == null) {
                vaccineAdm = new ArrayList<ImmunisationDetail.ImmuDetail.VaccineAdm>();
            }
            return this.vaccineAdm;
        }

        /**
         * Gets the value of the immuReport property.
         * 
         * @return
         *     possible object is
         *     {@link ImmunisationDetail.ImmuDetail.ImmuReport }
         *     
         */
        public ImmunisationDetail.ImmuDetail.ImmuReport getImmuReport() {
            return immuReport;
        }

        /**
         * Sets the value of the immuReport property.
         * 
         * @param value
         *     allowed object is
         *     {@link ImmunisationDetail.ImmuDetail.ImmuReport }
         *     
         */
        public void setImmuReport(ImmunisationDetail.ImmuDetail.ImmuReport value) {
            this.immuReport = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="report_title" type="{urn:hl7-org:v3}report_title" minOccurs="0"/>
         *         &lt;element name="text_report" type="{urn:hl7-org:v3}text_report" minOccurs="0"/>
         *         &lt;element name="report_date" type="{urn:hl7-org:v3}report_date" minOccurs="0"/>
         *         &lt;element ref="{urn:hl7-org:v3}file_ind" minOccurs="0"/>
         *         &lt;element ref="{urn:hl7-org:v3}file_name" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "reportTitle",
            "textReport",
            "reportDate",
            "fileInd",
            "fileName"
        })
        public static class ImmuReport {

            @XmlElement(name = "report_title")
            protected String reportTitle;
            @XmlElement(name = "text_report")
            protected String textReport;
            @XmlElement(name = "report_date")
            protected String reportDate;
            @XmlElement(name = "file_ind")
            protected String fileInd;
            @XmlElement(name = "file_name")
            protected String fileName;

            /**
             * Gets the value of the reportTitle property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getReportTitle() {
                return reportTitle;
            }

            /**
             * Sets the value of the reportTitle property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setReportTitle(String value) {
                this.reportTitle = value;
            }

            /**
             * Gets the value of the textReport property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTextReport() {
                return textReport;
            }

            /**
             * Sets the value of the textReport property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTextReport(String value) {
                this.textReport = value;
            }

            /**
             * Gets the value of the reportDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getReportDate() {
                return reportDate;
            }

            /**
             * Sets the value of the reportDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setReportDate(String value) {
                this.reportDate = value;
            }

            /**
             * Gets the value of the fileInd property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFileInd() {
                return fileInd;
            }

            /**
             * Sets the value of the fileInd property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFileInd(String value) {
                this.fileInd = value;
            }

            /**
             * Gets the value of the fileName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFileName() {
                return fileName;
            }

            /**
             * Sets the value of the fileName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFileName(String value) {
                this.fileName = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{urn:hl7-org:v3}record_key"/>
         *         &lt;element ref="{urn:hl7-org:v3}transaction_dtm"/>
         *         &lt;element ref="{urn:hl7-org:v3}transaction_type"/>
         *         &lt;element ref="{urn:hl7-org:v3}last_update_dtm" minOccurs="0"/>
         *         &lt;element ref="{urn:hl7-org:v3}episode_no" minOccurs="0"/>
         *         &lt;element ref="{urn:hl7-org:v3}attendance_inst_id" minOccurs="0"/>
         *         &lt;element name="vaccine_rt_name" type="{urn:hl7-org:v3}vaccine_rt_name" minOccurs="0"/>
         *         &lt;element name="vaccine_rt_id" type="{urn:hl7-org:v3}vaccine_rt_id" minOccurs="0"/>
         *         &lt;element name="vaccine_rt_desc" type="{urn:hl7-org:v3}vaccine_rt_desc" minOccurs="0"/>
         *         &lt;element name="vaccine_lt_id" type="{urn:hl7-org:v3}vaccine_lt_id" minOccurs="0"/>
         *         &lt;element name="vaccine_lt_desc" type="{urn:hl7-org:v3}vaccine_lt_desc" minOccurs="0"/>
         *         &lt;element name="route_of_adm_cd" type="{urn:hl7-org:v3}route_of_adm_cd" minOccurs="0"/>
         *         &lt;element name="route_of_adm_desc" type="{urn:hl7-org:v3}route_of_adm_desc" minOccurs="0"/>
         *         &lt;element name="route_of_adm_lt_desc" type="{urn:hl7-org:v3}route_of_adm_lt_desc" minOccurs="0"/>
         *         &lt;element name="site_of_adm_cd" type="{urn:hl7-org:v3}site_of_adm_cd" minOccurs="0"/>
         *         &lt;element name="site_of_adm_desc" type="{urn:hl7-org:v3}site_of_adm_desc" minOccurs="0"/>
         *         &lt;element name="site_of_adm_lt_desc" type="{urn:hl7-org:v3}site_of_adm_lt_desc" minOccurs="0"/>
         *         &lt;element name="vaccination_provider_cd" type="{urn:hl7-org:v3}vaccination_provider_cd" minOccurs="0"/>
         *         &lt;element name="vaccination_provider_desc" type="{urn:hl7-org:v3}vaccination_provider_desc" minOccurs="0"/>
         *         &lt;element name="vaccination_provider_lt_desc" type="{urn:hl7-org:v3}vaccination_provider_lt_desc" minOccurs="0"/>
         *         &lt;element name="historical_immu" type="{urn:hl7-org:v3}historical_immu" minOccurs="0"/>
         *         &lt;element name="vaccine_adm_date" type="{urn:hl7-org:v3}vaccine_adm_date" minOccurs="0"/>
         *         &lt;element name="vaccine_dose_sequence" type="{urn:hl7-org:v3}vaccine_dose_sequence" minOccurs="0"/>
         *         &lt;element name="batch_no" type="{urn:hl7-org:v3}batch_no" minOccurs="0"/>
         *         &lt;element name="vaccine_adm_premises" type="{urn:hl7-org:v3}vaccine_adm_premises" minOccurs="0"/>
         *         &lt;element name="vaccine_adm_remark" type="{urn:hl7-org:v3}vaccine_adm_remark" minOccurs="0"/>
         *         &lt;element ref="{urn:hl7-org:v3}record_creation_dtm" minOccurs="0"/>
         *         &lt;element ref="{urn:hl7-org:v3}record_creation_inst_id" minOccurs="0"/>
         *         &lt;element ref="{urn:hl7-org:v3}record_creation_inst_name" minOccurs="0"/>
         *         &lt;element ref="{urn:hl7-org:v3}record_update_dtm" minOccurs="0"/>
         *         &lt;element ref="{urn:hl7-org:v3}record_update_inst_id" minOccurs="0"/>
         *         &lt;element ref="{urn:hl7-org:v3}record_update_inst_name" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "recordKey",
            "transactionDtm",
            "transactionType",
            "lastUpdateDtm",
            "episodeNo",
            "attendanceInstId",
            "vaccineRtName",
            "vaccineRtId",
            "vaccineRtDesc",
            "vaccineLtId",
            "vaccineLtDesc",
            "routeOfAdmCd",
            "routeOfAdmDesc",
            "routeOfAdmLtDesc",
            "siteOfAdmCd",
            "siteOfAdmDesc",
            "siteOfAdmLtDesc",
            "vaccinationProviderCd",
            "vaccinationProviderDesc",
            "vaccinationProviderLtDesc",
            "historicalImmu",
            "vaccineAdmDate",
            "vaccineDoseSequence",
            "batchNo",
            "vaccineAdmPremises",
            "vaccineAdmRemark",
            "recordCreationDtm",
            "recordCreationInstId",
            "recordCreationInstName",
            "recordUpdateDtm",
            "recordUpdateInstId",
            "recordUpdateInstName"
        })
        public static class VaccineAdm {

            @XmlElement(name = "record_key", required = true)
            protected String recordKey;
            @XmlElement(name = "transaction_dtm", required = true)
            protected String transactionDtm;
            @XmlElement(name = "transaction_type", required = true)
            protected String transactionType;
            @XmlElement(name = "last_update_dtm")
            protected String lastUpdateDtm;
            @XmlElement(name = "episode_no")
            protected String episodeNo;
            @XmlElement(name = "attendance_inst_id")
            protected String attendanceInstId;
            @XmlElement(name = "vaccine_rt_name")
            protected String vaccineRtName;
            @XmlElement(name = "vaccine_rt_id")
            protected String vaccineRtId;
            @XmlElement(name = "vaccine_rt_desc")
            protected String vaccineRtDesc;
            @XmlElement(name = "vaccine_lt_id")
            protected String vaccineLtId;
            @XmlElement(name = "vaccine_lt_desc")
            protected String vaccineLtDesc;
            @XmlElement(name = "route_of_adm_cd")
            protected String routeOfAdmCd;
            @XmlElement(name = "route_of_adm_desc")
            protected String routeOfAdmDesc;
            @XmlElement(name = "route_of_adm_lt_desc")
            protected String routeOfAdmLtDesc;
            @XmlElement(name = "site_of_adm_cd")
            protected String siteOfAdmCd;
            @XmlElement(name = "site_of_adm_desc")
            protected String siteOfAdmDesc;
            @XmlElement(name = "site_of_adm_lt_desc")
            protected String siteOfAdmLtDesc;
            @XmlElement(name = "vaccination_provider_cd")
            protected String vaccinationProviderCd;
            @XmlElement(name = "vaccination_provider_desc")
            protected String vaccinationProviderDesc;
            @XmlElement(name = "vaccination_provider_lt_desc")
            protected String vaccinationProviderLtDesc;
            @XmlElement(name = "historical_immu")
            protected String historicalImmu;
            @XmlElement(name = "vaccine_adm_date")
            protected String vaccineAdmDate;
            @XmlElement(name = "vaccine_dose_sequence")
            protected String vaccineDoseSequence;
            @XmlElement(name = "batch_no")
            protected String batchNo;
            @XmlElement(name = "vaccine_adm_premises")
            protected String vaccineAdmPremises;
            @XmlElement(name = "vaccine_adm_remark")
            protected String vaccineAdmRemark;
            @XmlElement(name = "record_creation_dtm")
            protected String recordCreationDtm;
            @XmlElement(name = "record_creation_inst_id")
            protected String recordCreationInstId;
            @XmlElement(name = "record_creation_inst_name")
            protected String recordCreationInstName;
            @XmlElement(name = "record_update_dtm")
            protected String recordUpdateDtm;
            @XmlElement(name = "record_update_inst_id")
            protected String recordUpdateInstId;
            @XmlElement(name = "record_update_inst_name")
            protected String recordUpdateInstName;

            /**
             * Gets the value of the recordKey property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRecordKey() {
                return recordKey;
            }

            /**
             * Sets the value of the recordKey property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRecordKey(String value) {
                this.recordKey = value;
            }

            /**
             * Gets the value of the transactionDtm property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTransactionDtm() {
                return transactionDtm;
            }

            /**
             * Sets the value of the transactionDtm property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTransactionDtm(String value) {
                this.transactionDtm = value;
            }

            /**
             * Gets the value of the transactionType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTransactionType() {
                return transactionType;
            }

            /**
             * Sets the value of the transactionType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTransactionType(String value) {
                this.transactionType = value;
            }

            /**
             * Gets the value of the lastUpdateDtm property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLastUpdateDtm() {
                return lastUpdateDtm;
            }

            /**
             * Sets the value of the lastUpdateDtm property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLastUpdateDtm(String value) {
                this.lastUpdateDtm = value;
            }

            /**
             * Gets the value of the episodeNo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEpisodeNo() {
                return episodeNo;
            }

            /**
             * Sets the value of the episodeNo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEpisodeNo(String value) {
                this.episodeNo = value;
            }

            /**
             * Gets the value of the attendanceInstId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAttendanceInstId() {
                return attendanceInstId;
            }

            /**
             * Sets the value of the attendanceInstId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAttendanceInstId(String value) {
                this.attendanceInstId = value;
            }

            /**
             * Gets the value of the vaccineRtName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVaccineRtName() {
                return vaccineRtName;
            }

            /**
             * Sets the value of the vaccineRtName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVaccineRtName(String value) {
                this.vaccineRtName = value;
            }

            /**
             * Gets the value of the vaccineRtId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVaccineRtId() {
                return vaccineRtId;
            }

            /**
             * Sets the value of the vaccineRtId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVaccineRtId(String value) {
                this.vaccineRtId = value;
            }

            /**
             * Gets the value of the vaccineRtDesc property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVaccineRtDesc() {
                return vaccineRtDesc;
            }

            /**
             * Sets the value of the vaccineRtDesc property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVaccineRtDesc(String value) {
                this.vaccineRtDesc = value;
            }

            /**
             * Gets the value of the vaccineLtId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVaccineLtId() {
                return vaccineLtId;
            }

            /**
             * Sets the value of the vaccineLtId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVaccineLtId(String value) {
                this.vaccineLtId = value;
            }

            /**
             * Gets the value of the vaccineLtDesc property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVaccineLtDesc() {
                return vaccineLtDesc;
            }

            /**
             * Sets the value of the vaccineLtDesc property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVaccineLtDesc(String value) {
                this.vaccineLtDesc = value;
            }

            /**
             * Gets the value of the routeOfAdmCd property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRouteOfAdmCd() {
                return routeOfAdmCd;
            }

            /**
             * Sets the value of the routeOfAdmCd property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRouteOfAdmCd(String value) {
                this.routeOfAdmCd = value;
            }

            /**
             * Gets the value of the routeOfAdmDesc property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRouteOfAdmDesc() {
                return routeOfAdmDesc;
            }

            /**
             * Sets the value of the routeOfAdmDesc property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRouteOfAdmDesc(String value) {
                this.routeOfAdmDesc = value;
            }

            /**
             * Gets the value of the routeOfAdmLtDesc property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRouteOfAdmLtDesc() {
                return routeOfAdmLtDesc;
            }

            /**
             * Sets the value of the routeOfAdmLtDesc property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRouteOfAdmLtDesc(String value) {
                this.routeOfAdmLtDesc = value;
            }

            /**
             * Gets the value of the siteOfAdmCd property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSiteOfAdmCd() {
                return siteOfAdmCd;
            }

            /**
             * Sets the value of the siteOfAdmCd property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSiteOfAdmCd(String value) {
                this.siteOfAdmCd = value;
            }

            /**
             * Gets the value of the siteOfAdmDesc property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSiteOfAdmDesc() {
                return siteOfAdmDesc;
            }

            /**
             * Sets the value of the siteOfAdmDesc property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSiteOfAdmDesc(String value) {
                this.siteOfAdmDesc = value;
            }

            /**
             * Gets the value of the siteOfAdmLtDesc property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSiteOfAdmLtDesc() {
                return siteOfAdmLtDesc;
            }

            /**
             * Sets the value of the siteOfAdmLtDesc property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSiteOfAdmLtDesc(String value) {
                this.siteOfAdmLtDesc = value;
            }

            /**
             * Gets the value of the vaccinationProviderCd property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVaccinationProviderCd() {
                return vaccinationProviderCd;
            }

            /**
             * Sets the value of the vaccinationProviderCd property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVaccinationProviderCd(String value) {
                this.vaccinationProviderCd = value;
            }

            /**
             * Gets the value of the vaccinationProviderDesc property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVaccinationProviderDesc() {
                return vaccinationProviderDesc;
            }

            /**
             * Sets the value of the vaccinationProviderDesc property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVaccinationProviderDesc(String value) {
                this.vaccinationProviderDesc = value;
            }

            /**
             * Gets the value of the vaccinationProviderLtDesc property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVaccinationProviderLtDesc() {
                return vaccinationProviderLtDesc;
            }

            /**
             * Sets the value of the vaccinationProviderLtDesc property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVaccinationProviderLtDesc(String value) {
                this.vaccinationProviderLtDesc = value;
            }

            /**
             * Gets the value of the historicalImmu property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHistoricalImmu() {
                return historicalImmu;
            }

            /**
             * Sets the value of the historicalImmu property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHistoricalImmu(String value) {
                this.historicalImmu = value;
            }

            /**
             * Gets the value of the vaccineAdmDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVaccineAdmDate() {
                return vaccineAdmDate;
            }

            /**
             * Sets the value of the vaccineAdmDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVaccineAdmDate(String value) {
                this.vaccineAdmDate = value;
            }

            /**
             * Gets the value of the vaccineDoseSequence property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVaccineDoseSequence() {
                return vaccineDoseSequence;
            }

            /**
             * Sets the value of the vaccineDoseSequence property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVaccineDoseSequence(String value) {
                this.vaccineDoseSequence = value;
            }

            /**
             * Gets the value of the batchNo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBatchNo() {
                return batchNo;
            }

            /**
             * Sets the value of the batchNo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBatchNo(String value) {
                this.batchNo = value;
            }

            /**
             * Gets the value of the vaccineAdmPremises property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVaccineAdmPremises() {
                return vaccineAdmPremises;
            }

            /**
             * Sets the value of the vaccineAdmPremises property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVaccineAdmPremises(String value) {
                this.vaccineAdmPremises = value;
            }

            /**
             * Gets the value of the vaccineAdmRemark property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVaccineAdmRemark() {
                return vaccineAdmRemark;
            }

            /**
             * Sets the value of the vaccineAdmRemark property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVaccineAdmRemark(String value) {
                this.vaccineAdmRemark = value;
            }

            /**
             * Gets the value of the recordCreationDtm property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRecordCreationDtm() {
                return recordCreationDtm;
            }

            /**
             * Sets the value of the recordCreationDtm property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRecordCreationDtm(String value) {
                this.recordCreationDtm = value;
            }

            /**
             * Gets the value of the recordCreationInstId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRecordCreationInstId() {
                return recordCreationInstId;
            }

            /**
             * Sets the value of the recordCreationInstId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRecordCreationInstId(String value) {
                this.recordCreationInstId = value;
            }

            /**
             * Gets the value of the recordCreationInstName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRecordCreationInstName() {
                return recordCreationInstName;
            }

            /**
             * Sets the value of the recordCreationInstName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRecordCreationInstName(String value) {
                this.recordCreationInstName = value;
            }

            /**
             * Gets the value of the recordUpdateDtm property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRecordUpdateDtm() {
                return recordUpdateDtm;
            }

            /**
             * Sets the value of the recordUpdateDtm property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRecordUpdateDtm(String value) {
                this.recordUpdateDtm = value;
            }

            /**
             * Gets the value of the recordUpdateInstId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRecordUpdateInstId() {
                return recordUpdateInstId;
            }

            /**
             * Sets the value of the recordUpdateInstId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRecordUpdateInstId(String value) {
                this.recordUpdateInstId = value;
            }

            /**
             * Gets the value of the recordUpdateInstName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRecordUpdateInstName() {
                return recordUpdateInstName;
            }

            /**
             * Sets the value of the recordUpdateInstName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRecordUpdateInstName(String value) {
                this.recordUpdateInstName = value;
            }

        }

    }

}
