//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.30 at 04:23:32 PM CST 
//


package org.hl7.v3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="invr_detail" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{urn:hl7-org:v3}record_key"/>
 *                   &lt;element ref="{urn:hl7-org:v3}transaction_dtm"/>
 *                   &lt;element ref="{urn:hl7-org:v3}transaction_type"/>
 *                   &lt;element ref="{urn:hl7-org:v3}last_update_dtm" minOccurs="0"/>
 *                   &lt;element ref="{urn:hl7-org:v3}episode_no" minOccurs="0"/>
 *                   &lt;element ref="{urn:hl7-org:v3}attendance_inst_id" minOccurs="0"/>
 *                   &lt;element name="investigation_report" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="report_id" type="{urn:hl7-org:v3}report_id" minOccurs="0"/>
 *                             &lt;element name="investigation_report_dtm" type="{urn:hl7-org:v3}investigation_report_dtm" minOccurs="0"/>
 *                             &lt;element name="investigation_report_title" type="{urn:hl7-org:v3}investigation_report_title" minOccurs="0"/>
 *                             &lt;element name="investigation_report_text_report" type="{urn:hl7-org:v3}investigation_report_text_report" minOccurs="0"/>
 *                             &lt;element name="investigation_report_highlight" type="{urn:hl7-org:v3}investigation_report_highlight" minOccurs="0"/>
 *                             &lt;element name="investigation_report_remark" type="{urn:hl7-org:v3}investigation_report_remark" minOccurs="0"/>
 *                             &lt;element ref="{urn:hl7-org:v3}file_ind" minOccurs="0"/>
 *                             &lt;element ref="{urn:hl7-org:v3}file_name" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element ref="{urn:hl7-org:v3}record_creation_dtm" minOccurs="0"/>
 *                   &lt;element ref="{urn:hl7-org:v3}record_creation_inst_id" minOccurs="0"/>
 *                   &lt;element ref="{urn:hl7-org:v3}record_creation_inst_name" minOccurs="0"/>
 *                   &lt;element ref="{urn:hl7-org:v3}record_update_dtm" minOccurs="0"/>
 *                   &lt;element ref="{urn:hl7-org:v3}record_update_inst_id" minOccurs="0"/>
 *                   &lt;element ref="{urn:hl7-org:v3}record_update_inst_name" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "invrDetail"
})
@XmlRootElement(name = "investigationDetail")
public class InvestigationDetail {

    @XmlElement(name = "invr_detail", required = true)
    protected List<InvestigationDetail.InvrDetail> invrDetail;

    /**
     * Gets the value of the invrDetail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the invrDetail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInvrDetail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InvestigationDetail.InvrDetail }
     * 
     * 
     */
    public List<InvestigationDetail.InvrDetail> getInvrDetail() {
        if (invrDetail == null) {
            invrDetail = new ArrayList<InvestigationDetail.InvrDetail>();
        }
        return this.invrDetail;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{urn:hl7-org:v3}record_key"/>
     *         &lt;element ref="{urn:hl7-org:v3}transaction_dtm"/>
     *         &lt;element ref="{urn:hl7-org:v3}transaction_type"/>
     *         &lt;element ref="{urn:hl7-org:v3}last_update_dtm" minOccurs="0"/>
     *         &lt;element ref="{urn:hl7-org:v3}episode_no" minOccurs="0"/>
     *         &lt;element ref="{urn:hl7-org:v3}attendance_inst_id" minOccurs="0"/>
     *         &lt;element name="investigation_report" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="report_id" type="{urn:hl7-org:v3}report_id" minOccurs="0"/>
     *                   &lt;element name="investigation_report_dtm" type="{urn:hl7-org:v3}investigation_report_dtm" minOccurs="0"/>
     *                   &lt;element name="investigation_report_title" type="{urn:hl7-org:v3}investigation_report_title" minOccurs="0"/>
     *                   &lt;element name="investigation_report_text_report" type="{urn:hl7-org:v3}investigation_report_text_report" minOccurs="0"/>
     *                   &lt;element name="investigation_report_highlight" type="{urn:hl7-org:v3}investigation_report_highlight" minOccurs="0"/>
     *                   &lt;element name="investigation_report_remark" type="{urn:hl7-org:v3}investigation_report_remark" minOccurs="0"/>
     *                   &lt;element ref="{urn:hl7-org:v3}file_ind" minOccurs="0"/>
     *                   &lt;element ref="{urn:hl7-org:v3}file_name" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element ref="{urn:hl7-org:v3}record_creation_dtm" minOccurs="0"/>
     *         &lt;element ref="{urn:hl7-org:v3}record_creation_inst_id" minOccurs="0"/>
     *         &lt;element ref="{urn:hl7-org:v3}record_creation_inst_name" minOccurs="0"/>
     *         &lt;element ref="{urn:hl7-org:v3}record_update_dtm" minOccurs="0"/>
     *         &lt;element ref="{urn:hl7-org:v3}record_update_inst_id" minOccurs="0"/>
     *         &lt;element ref="{urn:hl7-org:v3}record_update_inst_name" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "recordKey",
        "transactionDtm",
        "transactionType",
        "lastUpdateDtm",
        "episodeNo",
        "attendanceInstId",
        "investigationReport",
        "recordCreationDtm",
        "recordCreationInstId",
        "recordCreationInstName",
        "recordUpdateDtm",
        "recordUpdateInstId",
        "recordUpdateInstName"
    })
    public static class InvrDetail {

        @XmlElement(name = "record_key", required = true)
        protected String recordKey;
        @XmlElement(name = "transaction_dtm", required = true)
        protected String transactionDtm;
        @XmlElement(name = "transaction_type", required = true)
        protected String transactionType;
        @XmlElement(name = "last_update_dtm")
        protected String lastUpdateDtm;
        @XmlElement(name = "episode_no")
        protected String episodeNo;
        @XmlElement(name = "attendance_inst_id")
        protected String attendanceInstId;
        @XmlElement(name = "investigation_report")
        protected InvestigationDetail.InvrDetail.InvestigationReport investigationReport;
        @XmlElement(name = "record_creation_dtm")
        protected String recordCreationDtm;
        @XmlElement(name = "record_creation_inst_id")
        protected String recordCreationInstId;
        @XmlElement(name = "record_creation_inst_name")
        protected String recordCreationInstName;
        @XmlElement(name = "record_update_dtm")
        protected String recordUpdateDtm;
        @XmlElement(name = "record_update_inst_id")
        protected String recordUpdateInstId;
        @XmlElement(name = "record_update_inst_name")
        protected String recordUpdateInstName;

        /**
         * Gets the value of the recordKey property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRecordKey() {
            return recordKey;
        }

        /**
         * Sets the value of the recordKey property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRecordKey(String value) {
            this.recordKey = value;
        }

        /**
         * Gets the value of the transactionDtm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTransactionDtm() {
            return transactionDtm;
        }

        /**
         * Sets the value of the transactionDtm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTransactionDtm(String value) {
            this.transactionDtm = value;
        }

        /**
         * Gets the value of the transactionType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTransactionType() {
            return transactionType;
        }

        /**
         * Sets the value of the transactionType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTransactionType(String value) {
            this.transactionType = value;
        }

        /**
         * Gets the value of the lastUpdateDtm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLastUpdateDtm() {
            return lastUpdateDtm;
        }

        /**
         * Sets the value of the lastUpdateDtm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLastUpdateDtm(String value) {
            this.lastUpdateDtm = value;
        }

        /**
         * Gets the value of the episodeNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEpisodeNo() {
            return episodeNo;
        }

        /**
         * Sets the value of the episodeNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEpisodeNo(String value) {
            this.episodeNo = value;
        }

        /**
         * Gets the value of the attendanceInstId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAttendanceInstId() {
            return attendanceInstId;
        }

        /**
         * Sets the value of the attendanceInstId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAttendanceInstId(String value) {
            this.attendanceInstId = value;
        }

        /**
         * Gets the value of the investigationReport property.
         * 
         * @return
         *     possible object is
         *     {@link InvestigationDetail.InvrDetail.InvestigationReport }
         *     
         */
        public InvestigationDetail.InvrDetail.InvestigationReport getInvestigationReport() {
            return investigationReport;
        }

        /**
         * Sets the value of the investigationReport property.
         * 
         * @param value
         *     allowed object is
         *     {@link InvestigationDetail.InvrDetail.InvestigationReport }
         *     
         */
        public void setInvestigationReport(InvestigationDetail.InvrDetail.InvestigationReport value) {
            this.investigationReport = value;
        }

        /**
         * Gets the value of the recordCreationDtm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRecordCreationDtm() {
            return recordCreationDtm;
        }

        /**
         * Sets the value of the recordCreationDtm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRecordCreationDtm(String value) {
            this.recordCreationDtm = value;
        }

        /**
         * Gets the value of the recordCreationInstId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRecordCreationInstId() {
            return recordCreationInstId;
        }

        /**
         * Sets the value of the recordCreationInstId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRecordCreationInstId(String value) {
            this.recordCreationInstId = value;
        }

        /**
         * Gets the value of the recordCreationInstName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRecordCreationInstName() {
            return recordCreationInstName;
        }

        /**
         * Sets the value of the recordCreationInstName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRecordCreationInstName(String value) {
            this.recordCreationInstName = value;
        }

        /**
         * Gets the value of the recordUpdateDtm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRecordUpdateDtm() {
            return recordUpdateDtm;
        }

        /**
         * Sets the value of the recordUpdateDtm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRecordUpdateDtm(String value) {
            this.recordUpdateDtm = value;
        }

        /**
         * Gets the value of the recordUpdateInstId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRecordUpdateInstId() {
            return recordUpdateInstId;
        }

        /**
         * Sets the value of the recordUpdateInstId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRecordUpdateInstId(String value) {
            this.recordUpdateInstId = value;
        }

        /**
         * Gets the value of the recordUpdateInstName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRecordUpdateInstName() {
            return recordUpdateInstName;
        }

        /**
         * Sets the value of the recordUpdateInstName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRecordUpdateInstName(String value) {
            this.recordUpdateInstName = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="report_id" type="{urn:hl7-org:v3}report_id" minOccurs="0"/>
         *         &lt;element name="investigation_report_dtm" type="{urn:hl7-org:v3}investigation_report_dtm" minOccurs="0"/>
         *         &lt;element name="investigation_report_title" type="{urn:hl7-org:v3}investigation_report_title" minOccurs="0"/>
         *         &lt;element name="investigation_report_text_report" type="{urn:hl7-org:v3}investigation_report_text_report" minOccurs="0"/>
         *         &lt;element name="investigation_report_highlight" type="{urn:hl7-org:v3}investigation_report_highlight" minOccurs="0"/>
         *         &lt;element name="investigation_report_remark" type="{urn:hl7-org:v3}investigation_report_remark" minOccurs="0"/>
         *         &lt;element ref="{urn:hl7-org:v3}file_ind" minOccurs="0"/>
         *         &lt;element ref="{urn:hl7-org:v3}file_name" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "reportId",
            "investigationReportDtm",
            "investigationReportTitle",
            "investigationReportTextReport",
            "investigationReportHighlight",
            "investigationReportRemark",
            "fileInd",
            "fileName"
        })
        public static class InvestigationReport {

            @XmlElement(name = "report_id")
            protected String reportId;
            @XmlElement(name = "investigation_report_dtm")
            protected String investigationReportDtm;
            @XmlElement(name = "investigation_report_title")
            protected String investigationReportTitle;
            @XmlElement(name = "investigation_report_text_report")
            protected String investigationReportTextReport;
            @XmlElement(name = "investigation_report_highlight")
            protected String investigationReportHighlight;
            @XmlElement(name = "investigation_report_remark")
            protected String investigationReportRemark;
            @XmlElement(name = "file_ind")
            protected String fileInd;
            @XmlElement(name = "file_name")
            protected String fileName;

            /**
             * Gets the value of the reportId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getReportId() {
                return reportId;
            }

            /**
             * Sets the value of the reportId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setReportId(String value) {
                this.reportId = value;
            }

            /**
             * Gets the value of the investigationReportDtm property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getInvestigationReportDtm() {
                return investigationReportDtm;
            }

            /**
             * Sets the value of the investigationReportDtm property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setInvestigationReportDtm(String value) {
                this.investigationReportDtm = value;
            }

            /**
             * Gets the value of the investigationReportTitle property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getInvestigationReportTitle() {
                return investigationReportTitle;
            }

            /**
             * Sets the value of the investigationReportTitle property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setInvestigationReportTitle(String value) {
                this.investigationReportTitle = value;
            }

            /**
             * Gets the value of the investigationReportTextReport property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getInvestigationReportTextReport() {
                return investigationReportTextReport;
            }

            /**
             * Sets the value of the investigationReportTextReport property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setInvestigationReportTextReport(String value) {
                this.investigationReportTextReport = value;
            }

            /**
             * Gets the value of the investigationReportHighlight property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getInvestigationReportHighlight() {
                return investigationReportHighlight;
            }

            /**
             * Sets the value of the investigationReportHighlight property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setInvestigationReportHighlight(String value) {
                this.investigationReportHighlight = value;
            }

            /**
             * Gets the value of the investigationReportRemark property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getInvestigationReportRemark() {
                return investigationReportRemark;
            }

            /**
             * Sets the value of the investigationReportRemark property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setInvestigationReportRemark(String value) {
                this.investigationReportRemark = value;
            }

            /**
             * Gets the value of the fileInd property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFileInd() {
                return fileInd;
            }

            /**
             * Sets the value of the fileInd property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFileInd(String value) {
                this.fileInd = value;
            }

            /**
             * Gets the value of the fileName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFileName() {
                return fileName;
            }

            /**
             * Sets the value of the fileName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFileName(String value) {
                this.fileName = value;
            }

        }

    }

}
