//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.30 at 04:23:32 PM CST 
//


package org.hl7.v3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="lab_req_data" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{urn:hl7-org:v3}record_key"/>
 *                   &lt;element ref="{urn:hl7-org:v3}transaction_dtm"/>
 *                   &lt;element ref="{urn:hl7-org:v3}transaction_type"/>
 *                   &lt;element ref="{urn:hl7-org:v3}last_update_dtm" minOccurs="0"/>
 *                   &lt;element ref="{urn:hl7-org:v3}episode_no" minOccurs="0"/>
 *                   &lt;element ref="{urn:hl7-org:v3}attendance_inst_id" minOccurs="0"/>
 *                   &lt;element name="request_no" type="{urn:hl7-org:v3}request_no" minOccurs="0"/>
 *                   &lt;element name="request_doctor" type="{urn:hl7-org:v3}request_doctor" minOccurs="0"/>
 *                   &lt;element name="request_participant_inst_id" type="{urn:hl7-org:v3}inst_id" minOccurs="0"/>
 *                   &lt;element name="request_participant_inst_name" type="{urn:hl7-org:v3}inst_name" minOccurs="0"/>
 *                   &lt;element name="request_participant_inst_lt_desc" type="{urn:hl7-org:v3}desc" minOccurs="0"/>
 *                   &lt;element name="order_no" type="{urn:hl7-org:v3}order_no" minOccurs="0"/>
 *                   &lt;element name="lab_category_cd" type="{urn:hl7-org:v3}lab_category_cd" minOccurs="0"/>
 *                   &lt;element name="lab_category_desc" type="{urn:hl7-org:v3}desc" minOccurs="0"/>
 *                   &lt;element name="lab_category_lt_desc" type="{urn:hl7-org:v3}desc" minOccurs="0"/>
 *                   &lt;element name="perform_lab_name" type="{urn:hl7-org:v3}perform_lab_name" minOccurs="0"/>
 *                   &lt;element name="report_reference_dtm" type="{urn:hl7-org:v3}dtm" minOccurs="0"/>
 *                   &lt;element name="clinical_info" type="{urn:hl7-org:v3}short_text" minOccurs="0"/>
 *                   &lt;element name="lab_report_comment" type="{urn:hl7-org:v3}short_text" minOccurs="0"/>
 *                   &lt;element name="specimen_type_rt_name" type="{urn:hl7-org:v3}rt_name" minOccurs="0"/>
 *                   &lt;element name="specimen_type_rt_id" type="{urn:hl7-org:v3}specimen_type_rt_id" minOccurs="0"/>
 *                   &lt;element name="specimen_type_rt_desc" type="{urn:hl7-org:v3}desc" minOccurs="0"/>
 *                   &lt;element name="specimen_type_lt_id" type="{urn:hl7-org:v3}specimen_type_lt_id" minOccurs="0"/>
 *                   &lt;element name="specimen_type_lt_desc" type="{urn:hl7-org:v3}desc" minOccurs="0"/>
 *                   &lt;element name="specimen_arrival_dtm" type="{urn:hl7-org:v3}dtm" minOccurs="0"/>
 *                   &lt;element name="specimen_collect_dtm" type="{urn:hl7-org:v3}dtm" minOccurs="0"/>
 *                   &lt;element name="specimen_details" type="{urn:hl7-org:v3}short_text" minOccurs="0"/>
 *                   &lt;element ref="{urn:hl7-org:v3}file_ind" minOccurs="0"/>
 *                   &lt;element ref="{urn:hl7-org:v3}record_creation_dtm" minOccurs="0"/>
 *                   &lt;element ref="{urn:hl7-org:v3}record_creation_inst_id" minOccurs="0"/>
 *                   &lt;element ref="{urn:hl7-org:v3}record_creation_inst_name" minOccurs="0"/>
 *                   &lt;element ref="{urn:hl7-org:v3}record_update_dtm" minOccurs="0"/>
 *                   &lt;element ref="{urn:hl7-org:v3}record_update_inst_id" minOccurs="0"/>
 *                   &lt;element ref="{urn:hl7-org:v3}record_update_inst_name" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="labgen_result_data" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{urn:hl7-org:v3}record_key"/>
 *                   &lt;element name="test_rt_name" type="{urn:hl7-org:v3}rt_name" minOccurs="0"/>
 *                   &lt;element name="test_rt_id" type="{urn:hl7-org:v3}test_rt_id" minOccurs="0"/>
 *                   &lt;element name="test_rt_desc" type="{urn:hl7-org:v3}desc" minOccurs="0"/>
 *                   &lt;element name="test_lt_id" type="{urn:hl7-org:v3}test_lt_id" minOccurs="0"/>
 *                   &lt;element name="test_lt_desc" type="{urn:hl7-org:v3}desc" minOccurs="0"/>
 *                   &lt;element name="result_type" type="{urn:hl7-org:v3}result_type" minOccurs="0"/>
 *                   &lt;element name="numeric_result" type="{urn:hl7-org:v3}numeric_result" minOccurs="0"/>
 *                   &lt;element name="reportable_result" type="{urn:hl7-org:v3}reportable_result" minOccurs="0"/>
 *                   &lt;element name="enumerated_result" type="{urn:hl7-org:v3}enumerated_result" minOccurs="0"/>
 *                   &lt;element name="text_result" type="{urn:hl7-org:v3}long_text" minOccurs="0"/>
 *                   &lt;element name="result_note" type="{urn:hl7-org:v3}short_text" minOccurs="0"/>
 *                   &lt;element name="result_unit" type="{urn:hl7-org:v3}result_unit" minOccurs="0"/>
 *                   &lt;element name="reference_range" type="{urn:hl7-org:v3}short_text" minOccurs="0"/>
 *                   &lt;element name="detection_limit_ind_cd" type="{urn:hl7-org:v3}detection_limit_ind_cd" minOccurs="0"/>
 *                   &lt;element name="detection_limit_ind_desc" type="{urn:hl7-org:v3}desc" minOccurs="0"/>
 *                   &lt;element name="detection_limit_ind_lt_desc" type="{urn:hl7-org:v3}desc" minOccurs="0"/>
 *                   &lt;element name="abnormal_ind_cd" type="{urn:hl7-org:v3}abnormal_ind_cd" minOccurs="0"/>
 *                   &lt;element name="abnormal_ind_desc" type="{urn:hl7-org:v3}desc" minOccurs="0"/>
 *                   &lt;element name="abnormal_ind_lt_desc" type="{urn:hl7-org:v3}desc" minOccurs="0"/>
 *                   &lt;element name="panel_lt_cd" type="{urn:hl7-org:v3}panel_lt_cd" minOccurs="0"/>
 *                   &lt;element name="panel_lt_desc" type="{urn:hl7-org:v3}desc" minOccurs="0"/>
 *                   &lt;element name="report_auth_dtm" type="{urn:hl7-org:v3}dtm" minOccurs="0"/>
 *                   &lt;element name="report_auth_staff_id" type="{urn:hl7-org:v3}report_auth_staff_id" minOccurs="0"/>
 *                   &lt;element name="report_auth_staff_eng_name" type="{urn:hl7-org:v3}report_auth_staff_eng_name" minOccurs="0"/>
 *                   &lt;element name="report_auth_staff_eng_given_name" type="{urn:hl7-org:v3}report_auth_staff_eng_given_name" minOccurs="0"/>
 *                   &lt;element name="report_auth_staff_eng_name_prefix" type="{urn:hl7-org:v3}report_auth_staff_eng_name_prefix" minOccurs="0"/>
 *                   &lt;element name="report_auth_staff_chi_name" type="{urn:hl7-org:v3}report_auth_staff_chi_name" minOccurs="0"/>
 *                   &lt;element name="report_auth_staff_chi_name_suffix" type="{urn:hl7-org:v3}report_auth_staff_chi_name_suffix" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="lab_report_data" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{urn:hl7-org:v3}record_key"/>
 *                   &lt;element name="report_status_cd" type="{urn:hl7-org:v3}report_status_cd" minOccurs="0"/>
 *                   &lt;element name="report_status_desc" type="{urn:hl7-org:v3}desc" minOccurs="0"/>
 *                   &lt;element name="report_status_lt_desc" type="{urn:hl7-org:v3}desc" minOccurs="0"/>
 *                   &lt;element name="report_dtm" type="{urn:hl7-org:v3}dtm" minOccurs="0"/>
 *                   &lt;element ref="{urn:hl7-org:v3}file_name" minOccurs="0"/>
 *                   &lt;element name="report_text" type="{urn:hl7-org:v3}long_text" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "labReqData",
    "labgenResultData",
    "labReportData"
})
@XmlRootElement(name = "labResultGenDetail")
public class LabResultGenDetail {

    @XmlElement(name = "lab_req_data", required = true)
    protected List<LabResultGenDetail.LabReqData> labReqData;
    @XmlElement(name = "labgen_result_data")
    protected List<LabResultGenDetail.LabgenResultData> labgenResultData;
    @XmlElement(name = "lab_report_data")
    protected List<LabResultGenDetail.LabReportData> labReportData;

    /**
     * Gets the value of the labReqData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the labReqData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLabReqData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LabResultGenDetail.LabReqData }
     * 
     * 
     */
    public List<LabResultGenDetail.LabReqData> getLabReqData() {
        if (labReqData == null) {
            labReqData = new ArrayList<LabResultGenDetail.LabReqData>();
        }
        return this.labReqData;
    }

    /**
     * Gets the value of the labgenResultData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the labgenResultData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLabgenResultData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LabResultGenDetail.LabgenResultData }
     * 
     * 
     */
    public List<LabResultGenDetail.LabgenResultData> getLabgenResultData() {
        if (labgenResultData == null) {
            labgenResultData = new ArrayList<LabResultGenDetail.LabgenResultData>();
        }
        return this.labgenResultData;
    }

    /**
     * Gets the value of the labReportData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the labReportData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLabReportData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LabResultGenDetail.LabReportData }
     * 
     * 
     */
    public List<LabResultGenDetail.LabReportData> getLabReportData() {
        if (labReportData == null) {
            labReportData = new ArrayList<LabResultGenDetail.LabReportData>();
        }
        return this.labReportData;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{urn:hl7-org:v3}record_key"/>
     *         &lt;element name="report_status_cd" type="{urn:hl7-org:v3}report_status_cd" minOccurs="0"/>
     *         &lt;element name="report_status_desc" type="{urn:hl7-org:v3}desc" minOccurs="0"/>
     *         &lt;element name="report_status_lt_desc" type="{urn:hl7-org:v3}desc" minOccurs="0"/>
     *         &lt;element name="report_dtm" type="{urn:hl7-org:v3}dtm" minOccurs="0"/>
     *         &lt;element ref="{urn:hl7-org:v3}file_name" minOccurs="0"/>
     *         &lt;element name="report_text" type="{urn:hl7-org:v3}long_text" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "recordKey",
        "reportStatusCd",
        "reportStatusDesc",
        "reportStatusLtDesc",
        "reportDtm",
        "fileName",
        "reportText"
    })
    public static class LabReportData {

        @XmlElement(name = "record_key", required = true)
        protected String recordKey;
        @XmlElement(name = "report_status_cd")
        protected String reportStatusCd;
        @XmlElement(name = "report_status_desc")
        protected String reportStatusDesc;
        @XmlElement(name = "report_status_lt_desc")
        protected String reportStatusLtDesc;
        @XmlElement(name = "report_dtm")
        protected String reportDtm;
        @XmlElement(name = "file_name")
        protected String fileName;
        @XmlElement(name = "report_text")
        protected String reportText;

        /**
         * Gets the value of the recordKey property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRecordKey() {
            return recordKey;
        }

        /**
         * Sets the value of the recordKey property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRecordKey(String value) {
            this.recordKey = value;
        }

        /**
         * Gets the value of the reportStatusCd property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReportStatusCd() {
            return reportStatusCd;
        }

        /**
         * Sets the value of the reportStatusCd property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReportStatusCd(String value) {
            this.reportStatusCd = value;
        }

        /**
         * Gets the value of the reportStatusDesc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReportStatusDesc() {
            return reportStatusDesc;
        }

        /**
         * Sets the value of the reportStatusDesc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReportStatusDesc(String value) {
            this.reportStatusDesc = value;
        }

        /**
         * Gets the value of the reportStatusLtDesc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReportStatusLtDesc() {
            return reportStatusLtDesc;
        }

        /**
         * Sets the value of the reportStatusLtDesc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReportStatusLtDesc(String value) {
            this.reportStatusLtDesc = value;
        }

        /**
         * Gets the value of the reportDtm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReportDtm() {
            return reportDtm;
        }

        /**
         * Sets the value of the reportDtm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReportDtm(String value) {
            this.reportDtm = value;
        }

        /**
         * Gets the value of the fileName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFileName() {
            return fileName;
        }

        /**
         * Sets the value of the fileName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFileName(String value) {
            this.fileName = value;
        }

        /**
         * Gets the value of the reportText property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReportText() {
            return reportText;
        }

        /**
         * Sets the value of the reportText property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReportText(String value) {
            this.reportText = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{urn:hl7-org:v3}record_key"/>
     *         &lt;element ref="{urn:hl7-org:v3}transaction_dtm"/>
     *         &lt;element ref="{urn:hl7-org:v3}transaction_type"/>
     *         &lt;element ref="{urn:hl7-org:v3}last_update_dtm" minOccurs="0"/>
     *         &lt;element ref="{urn:hl7-org:v3}episode_no" minOccurs="0"/>
     *         &lt;element ref="{urn:hl7-org:v3}attendance_inst_id" minOccurs="0"/>
     *         &lt;element name="request_no" type="{urn:hl7-org:v3}request_no" minOccurs="0"/>
     *         &lt;element name="request_doctor" type="{urn:hl7-org:v3}request_doctor" minOccurs="0"/>
     *         &lt;element name="request_participant_inst_id" type="{urn:hl7-org:v3}inst_id" minOccurs="0"/>
     *         &lt;element name="request_participant_inst_name" type="{urn:hl7-org:v3}inst_name" minOccurs="0"/>
     *         &lt;element name="request_participant_inst_lt_desc" type="{urn:hl7-org:v3}desc" minOccurs="0"/>
     *         &lt;element name="order_no" type="{urn:hl7-org:v3}order_no" minOccurs="0"/>
     *         &lt;element name="lab_category_cd" type="{urn:hl7-org:v3}lab_category_cd" minOccurs="0"/>
     *         &lt;element name="lab_category_desc" type="{urn:hl7-org:v3}desc" minOccurs="0"/>
     *         &lt;element name="lab_category_lt_desc" type="{urn:hl7-org:v3}desc" minOccurs="0"/>
     *         &lt;element name="perform_lab_name" type="{urn:hl7-org:v3}perform_lab_name" minOccurs="0"/>
     *         &lt;element name="report_reference_dtm" type="{urn:hl7-org:v3}dtm" minOccurs="0"/>
     *         &lt;element name="clinical_info" type="{urn:hl7-org:v3}short_text" minOccurs="0"/>
     *         &lt;element name="lab_report_comment" type="{urn:hl7-org:v3}short_text" minOccurs="0"/>
     *         &lt;element name="specimen_type_rt_name" type="{urn:hl7-org:v3}rt_name" minOccurs="0"/>
     *         &lt;element name="specimen_type_rt_id" type="{urn:hl7-org:v3}specimen_type_rt_id" minOccurs="0"/>
     *         &lt;element name="specimen_type_rt_desc" type="{urn:hl7-org:v3}desc" minOccurs="0"/>
     *         &lt;element name="specimen_type_lt_id" type="{urn:hl7-org:v3}specimen_type_lt_id" minOccurs="0"/>
     *         &lt;element name="specimen_type_lt_desc" type="{urn:hl7-org:v3}desc" minOccurs="0"/>
     *         &lt;element name="specimen_arrival_dtm" type="{urn:hl7-org:v3}dtm" minOccurs="0"/>
     *         &lt;element name="specimen_collect_dtm" type="{urn:hl7-org:v3}dtm" minOccurs="0"/>
     *         &lt;element name="specimen_details" type="{urn:hl7-org:v3}short_text" minOccurs="0"/>
     *         &lt;element ref="{urn:hl7-org:v3}file_ind" minOccurs="0"/>
     *         &lt;element ref="{urn:hl7-org:v3}record_creation_dtm" minOccurs="0"/>
     *         &lt;element ref="{urn:hl7-org:v3}record_creation_inst_id" minOccurs="0"/>
     *         &lt;element ref="{urn:hl7-org:v3}record_creation_inst_name" minOccurs="0"/>
     *         &lt;element ref="{urn:hl7-org:v3}record_update_dtm" minOccurs="0"/>
     *         &lt;element ref="{urn:hl7-org:v3}record_update_inst_id" minOccurs="0"/>
     *         &lt;element ref="{urn:hl7-org:v3}record_update_inst_name" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "recordKey",
        "transactionDtm",
        "transactionType",
        "lastUpdateDtm",
        "episodeNo",
        "attendanceInstId",
        "requestNo",
        "requestDoctor",
        "requestParticipantInstId",
        "requestParticipantInstName",
        "requestParticipantInstLtDesc",
        "orderNo",
        "labCategoryCd",
        "labCategoryDesc",
        "labCategoryLtDesc",
        "performLabName",
        "reportReferenceDtm",
        "clinicalInfo",
        "labReportComment",
        "specimenTypeRtName",
        "specimenTypeRtId",
        "specimenTypeRtDesc",
        "specimenTypeLtId",
        "specimenTypeLtDesc",
        "specimenArrivalDtm",
        "specimenCollectDtm",
        "specimenDetails",
        "fileInd",
        "recordCreationDtm",
        "recordCreationInstId",
        "recordCreationInstName",
        "recordUpdateDtm",
        "recordUpdateInstId",
        "recordUpdateInstName"
    })
    public static class LabReqData {

        @XmlElement(name = "record_key", required = true)
        protected String recordKey;
        @XmlElement(name = "transaction_dtm", required = true)
        protected String transactionDtm;
        @XmlElement(name = "transaction_type", required = true)
        protected String transactionType;
        @XmlElement(name = "last_update_dtm")
        protected String lastUpdateDtm;
        @XmlElement(name = "episode_no")
        protected String episodeNo;
        @XmlElement(name = "attendance_inst_id")
        protected String attendanceInstId;
        @XmlElement(name = "request_no")
        protected String requestNo;
        @XmlElement(name = "request_doctor")
        protected String requestDoctor;
        @XmlElement(name = "request_participant_inst_id")
        protected String requestParticipantInstId;
        @XmlElement(name = "request_participant_inst_name")
        protected String requestParticipantInstName;
        @XmlElement(name = "request_participant_inst_lt_desc")
        protected String requestParticipantInstLtDesc;
        @XmlElement(name = "order_no")
        protected String orderNo;
        @XmlElement(name = "lab_category_cd")
        protected String labCategoryCd;
        @XmlElement(name = "lab_category_desc")
        protected String labCategoryDesc;
        @XmlElement(name = "lab_category_lt_desc")
        protected String labCategoryLtDesc;
        @XmlElement(name = "perform_lab_name")
        protected String performLabName;
        @XmlElement(name = "report_reference_dtm")
        protected String reportReferenceDtm;
        @XmlElement(name = "clinical_info")
        protected String clinicalInfo;
        @XmlElement(name = "lab_report_comment")
        protected String labReportComment;
        @XmlElement(name = "specimen_type_rt_name")
        protected String specimenTypeRtName;
        @XmlElement(name = "specimen_type_rt_id")
        protected String specimenTypeRtId;
        @XmlElement(name = "specimen_type_rt_desc")
        protected String specimenTypeRtDesc;
        @XmlElement(name = "specimen_type_lt_id")
        protected String specimenTypeLtId;
        @XmlElement(name = "specimen_type_lt_desc")
        protected String specimenTypeLtDesc;
        @XmlElement(name = "specimen_arrival_dtm")
        protected String specimenArrivalDtm;
        @XmlElement(name = "specimen_collect_dtm")
        protected String specimenCollectDtm;
        @XmlElement(name = "specimen_details")
        protected String specimenDetails;
        @XmlElement(name = "file_ind")
        protected String fileInd;
        @XmlElement(name = "record_creation_dtm")
        protected String recordCreationDtm;
        @XmlElement(name = "record_creation_inst_id")
        protected String recordCreationInstId;
        @XmlElement(name = "record_creation_inst_name")
        protected String recordCreationInstName;
        @XmlElement(name = "record_update_dtm")
        protected String recordUpdateDtm;
        @XmlElement(name = "record_update_inst_id")
        protected String recordUpdateInstId;
        @XmlElement(name = "record_update_inst_name")
        protected String recordUpdateInstName;

        /**
         * Gets the value of the recordKey property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRecordKey() {
            return recordKey;
        }

        /**
         * Sets the value of the recordKey property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRecordKey(String value) {
            this.recordKey = value;
        }

        /**
         * Gets the value of the transactionDtm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTransactionDtm() {
            return transactionDtm;
        }

        /**
         * Sets the value of the transactionDtm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTransactionDtm(String value) {
            this.transactionDtm = value;
        }

        /**
         * Gets the value of the transactionType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTransactionType() {
            return transactionType;
        }

        /**
         * Sets the value of the transactionType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTransactionType(String value) {
            this.transactionType = value;
        }

        /**
         * Gets the value of the lastUpdateDtm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLastUpdateDtm() {
            return lastUpdateDtm;
        }

        /**
         * Sets the value of the lastUpdateDtm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLastUpdateDtm(String value) {
            this.lastUpdateDtm = value;
        }

        /**
         * Gets the value of the episodeNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEpisodeNo() {
            return episodeNo;
        }

        /**
         * Sets the value of the episodeNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEpisodeNo(String value) {
            this.episodeNo = value;
        }

        /**
         * Gets the value of the attendanceInstId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAttendanceInstId() {
            return attendanceInstId;
        }

        /**
         * Sets the value of the attendanceInstId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAttendanceInstId(String value) {
            this.attendanceInstId = value;
        }

        /**
         * Gets the value of the requestNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRequestNo() {
            return requestNo;
        }

        /**
         * Sets the value of the requestNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRequestNo(String value) {
            this.requestNo = value;
        }

        /**
         * Gets the value of the requestDoctor property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRequestDoctor() {
            return requestDoctor;
        }

        /**
         * Sets the value of the requestDoctor property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRequestDoctor(String value) {
            this.requestDoctor = value;
        }

        /**
         * Gets the value of the requestParticipantInstId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRequestParticipantInstId() {
            return requestParticipantInstId;
        }

        /**
         * Sets the value of the requestParticipantInstId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRequestParticipantInstId(String value) {
            this.requestParticipantInstId = value;
        }

        /**
         * Gets the value of the requestParticipantInstName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRequestParticipantInstName() {
            return requestParticipantInstName;
        }

        /**
         * Sets the value of the requestParticipantInstName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRequestParticipantInstName(String value) {
            this.requestParticipantInstName = value;
        }

        /**
         * Gets the value of the requestParticipantInstLtDesc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRequestParticipantInstLtDesc() {
            return requestParticipantInstLtDesc;
        }

        /**
         * Sets the value of the requestParticipantInstLtDesc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRequestParticipantInstLtDesc(String value) {
            this.requestParticipantInstLtDesc = value;
        }

        /**
         * Gets the value of the orderNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrderNo() {
            return orderNo;
        }

        /**
         * Sets the value of the orderNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrderNo(String value) {
            this.orderNo = value;
        }

        /**
         * Gets the value of the labCategoryCd property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLabCategoryCd() {
            return labCategoryCd;
        }

        /**
         * Sets the value of the labCategoryCd property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLabCategoryCd(String value) {
            this.labCategoryCd = value;
        }

        /**
         * Gets the value of the labCategoryDesc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLabCategoryDesc() {
            return labCategoryDesc;
        }

        /**
         * Sets the value of the labCategoryDesc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLabCategoryDesc(String value) {
            this.labCategoryDesc = value;
        }

        /**
         * Gets the value of the labCategoryLtDesc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLabCategoryLtDesc() {
            return labCategoryLtDesc;
        }

        /**
         * Sets the value of the labCategoryLtDesc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLabCategoryLtDesc(String value) {
            this.labCategoryLtDesc = value;
        }

        /**
         * Gets the value of the performLabName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPerformLabName() {
            return performLabName;
        }

        /**
         * Sets the value of the performLabName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPerformLabName(String value) {
            this.performLabName = value;
        }

        /**
         * Gets the value of the reportReferenceDtm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReportReferenceDtm() {
            return reportReferenceDtm;
        }

        /**
         * Sets the value of the reportReferenceDtm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReportReferenceDtm(String value) {
            this.reportReferenceDtm = value;
        }

        /**
         * Gets the value of the clinicalInfo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getClinicalInfo() {
            return clinicalInfo;
        }

        /**
         * Sets the value of the clinicalInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setClinicalInfo(String value) {
            this.clinicalInfo = value;
        }

        /**
         * Gets the value of the labReportComment property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLabReportComment() {
            return labReportComment;
        }

        /**
         * Sets the value of the labReportComment property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLabReportComment(String value) {
            this.labReportComment = value;
        }

        /**
         * Gets the value of the specimenTypeRtName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSpecimenTypeRtName() {
            return specimenTypeRtName;
        }

        /**
         * Sets the value of the specimenTypeRtName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSpecimenTypeRtName(String value) {
            this.specimenTypeRtName = value;
        }

        /**
         * Gets the value of the specimenTypeRtId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSpecimenTypeRtId() {
            return specimenTypeRtId;
        }

        /**
         * Sets the value of the specimenTypeRtId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSpecimenTypeRtId(String value) {
            this.specimenTypeRtId = value;
        }

        /**
         * Gets the value of the specimenTypeRtDesc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSpecimenTypeRtDesc() {
            return specimenTypeRtDesc;
        }

        /**
         * Sets the value of the specimenTypeRtDesc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSpecimenTypeRtDesc(String value) {
            this.specimenTypeRtDesc = value;
        }

        /**
         * Gets the value of the specimenTypeLtId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSpecimenTypeLtId() {
            return specimenTypeLtId;
        }

        /**
         * Sets the value of the specimenTypeLtId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSpecimenTypeLtId(String value) {
            this.specimenTypeLtId = value;
        }

        /**
         * Gets the value of the specimenTypeLtDesc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSpecimenTypeLtDesc() {
            return specimenTypeLtDesc;
        }

        /**
         * Sets the value of the specimenTypeLtDesc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSpecimenTypeLtDesc(String value) {
            this.specimenTypeLtDesc = value;
        }

        /**
         * Gets the value of the specimenArrivalDtm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSpecimenArrivalDtm() {
            return specimenArrivalDtm;
        }

        /**
         * Sets the value of the specimenArrivalDtm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSpecimenArrivalDtm(String value) {
            this.specimenArrivalDtm = value;
        }

        /**
         * Gets the value of the specimenCollectDtm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSpecimenCollectDtm() {
            return specimenCollectDtm;
        }

        /**
         * Sets the value of the specimenCollectDtm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSpecimenCollectDtm(String value) {
            this.specimenCollectDtm = value;
        }

        /**
         * Gets the value of the specimenDetails property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSpecimenDetails() {
            return specimenDetails;
        }

        /**
         * Sets the value of the specimenDetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSpecimenDetails(String value) {
            this.specimenDetails = value;
        }

        /**
         * Gets the value of the fileInd property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFileInd() {
            return fileInd;
        }

        /**
         * Sets the value of the fileInd property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFileInd(String value) {
            this.fileInd = value;
        }

        /**
         * Gets the value of the recordCreationDtm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRecordCreationDtm() {
            return recordCreationDtm;
        }

        /**
         * Sets the value of the recordCreationDtm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRecordCreationDtm(String value) {
            this.recordCreationDtm = value;
        }

        /**
         * Gets the value of the recordCreationInstId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRecordCreationInstId() {
            return recordCreationInstId;
        }

        /**
         * Sets the value of the recordCreationInstId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRecordCreationInstId(String value) {
            this.recordCreationInstId = value;
        }

        /**
         * Gets the value of the recordCreationInstName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRecordCreationInstName() {
            return recordCreationInstName;
        }

        /**
         * Sets the value of the recordCreationInstName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRecordCreationInstName(String value) {
            this.recordCreationInstName = value;
        }

        /**
         * Gets the value of the recordUpdateDtm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRecordUpdateDtm() {
            return recordUpdateDtm;
        }

        /**
         * Sets the value of the recordUpdateDtm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRecordUpdateDtm(String value) {
            this.recordUpdateDtm = value;
        }

        /**
         * Gets the value of the recordUpdateInstId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRecordUpdateInstId() {
            return recordUpdateInstId;
        }

        /**
         * Sets the value of the recordUpdateInstId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRecordUpdateInstId(String value) {
            this.recordUpdateInstId = value;
        }

        /**
         * Gets the value of the recordUpdateInstName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRecordUpdateInstName() {
            return recordUpdateInstName;
        }

        /**
         * Sets the value of the recordUpdateInstName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRecordUpdateInstName(String value) {
            this.recordUpdateInstName = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{urn:hl7-org:v3}record_key"/>
     *         &lt;element name="test_rt_name" type="{urn:hl7-org:v3}rt_name" minOccurs="0"/>
     *         &lt;element name="test_rt_id" type="{urn:hl7-org:v3}test_rt_id" minOccurs="0"/>
     *         &lt;element name="test_rt_desc" type="{urn:hl7-org:v3}desc" minOccurs="0"/>
     *         &lt;element name="test_lt_id" type="{urn:hl7-org:v3}test_lt_id" minOccurs="0"/>
     *         &lt;element name="test_lt_desc" type="{urn:hl7-org:v3}desc" minOccurs="0"/>
     *         &lt;element name="result_type" type="{urn:hl7-org:v3}result_type" minOccurs="0"/>
     *         &lt;element name="numeric_result" type="{urn:hl7-org:v3}numeric_result" minOccurs="0"/>
     *         &lt;element name="reportable_result" type="{urn:hl7-org:v3}reportable_result" minOccurs="0"/>
     *         &lt;element name="enumerated_result" type="{urn:hl7-org:v3}enumerated_result" minOccurs="0"/>
     *         &lt;element name="text_result" type="{urn:hl7-org:v3}long_text" minOccurs="0"/>
     *         &lt;element name="result_note" type="{urn:hl7-org:v3}short_text" minOccurs="0"/>
     *         &lt;element name="result_unit" type="{urn:hl7-org:v3}result_unit" minOccurs="0"/>
     *         &lt;element name="reference_range" type="{urn:hl7-org:v3}short_text" minOccurs="0"/>
     *         &lt;element name="detection_limit_ind_cd" type="{urn:hl7-org:v3}detection_limit_ind_cd" minOccurs="0"/>
     *         &lt;element name="detection_limit_ind_desc" type="{urn:hl7-org:v3}desc" minOccurs="0"/>
     *         &lt;element name="detection_limit_ind_lt_desc" type="{urn:hl7-org:v3}desc" minOccurs="0"/>
     *         &lt;element name="abnormal_ind_cd" type="{urn:hl7-org:v3}abnormal_ind_cd" minOccurs="0"/>
     *         &lt;element name="abnormal_ind_desc" type="{urn:hl7-org:v3}desc" minOccurs="0"/>
     *         &lt;element name="abnormal_ind_lt_desc" type="{urn:hl7-org:v3}desc" minOccurs="0"/>
     *         &lt;element name="panel_lt_cd" type="{urn:hl7-org:v3}panel_lt_cd" minOccurs="0"/>
     *         &lt;element name="panel_lt_desc" type="{urn:hl7-org:v3}desc" minOccurs="0"/>
     *         &lt;element name="report_auth_dtm" type="{urn:hl7-org:v3}dtm" minOccurs="0"/>
     *         &lt;element name="report_auth_staff_id" type="{urn:hl7-org:v3}report_auth_staff_id" minOccurs="0"/>
     *         &lt;element name="report_auth_staff_eng_name" type="{urn:hl7-org:v3}report_auth_staff_eng_name" minOccurs="0"/>
     *         &lt;element name="report_auth_staff_eng_given_name" type="{urn:hl7-org:v3}report_auth_staff_eng_given_name" minOccurs="0"/>
     *         &lt;element name="report_auth_staff_eng_name_prefix" type="{urn:hl7-org:v3}report_auth_staff_eng_name_prefix" minOccurs="0"/>
     *         &lt;element name="report_auth_staff_chi_name" type="{urn:hl7-org:v3}report_auth_staff_chi_name" minOccurs="0"/>
     *         &lt;element name="report_auth_staff_chi_name_suffix" type="{urn:hl7-org:v3}report_auth_staff_chi_name_suffix" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "recordKey",
        "testRtName",
        "testRtId",
        "testRtDesc",
        "testLtId",
        "testLtDesc",
        "resultType",
        "numericResult",
        "reportableResult",
        "enumeratedResult",
        "textResult",
        "resultNote",
        "resultUnit",
        "referenceRange",
        "detectionLimitIndCd",
        "detectionLimitIndDesc",
        "detectionLimitIndLtDesc",
        "abnormalIndCd",
        "abnormalIndDesc",
        "abnormalIndLtDesc",
        "panelLtCd",
        "panelLtDesc",
        "reportAuthDtm",
        "reportAuthStaffId",
        "reportAuthStaffEngName",
        "reportAuthStaffEngGivenName",
        "reportAuthStaffEngNamePrefix",
        "reportAuthStaffChiName",
        "reportAuthStaffChiNameSuffix"
    })
    public static class LabgenResultData {

        @XmlElement(name = "record_key", required = true)
        protected String recordKey;
        @XmlElement(name = "test_rt_name")
        protected String testRtName;
        @XmlElement(name = "test_rt_id")
        protected String testRtId;
        @XmlElement(name = "test_rt_desc")
        protected String testRtDesc;
        @XmlElement(name = "test_lt_id")
        protected String testLtId;
        @XmlElement(name = "test_lt_desc")
        protected String testLtDesc;
        @XmlElement(name = "result_type")
        protected String resultType;
        @XmlElement(name = "numeric_result")
        protected String numericResult;
        @XmlElement(name = "reportable_result")
        protected String reportableResult;
        @XmlElement(name = "enumerated_result")
        protected String enumeratedResult;
        @XmlElement(name = "text_result")
        protected String textResult;
        @XmlElement(name = "result_note")
        protected String resultNote;
        @XmlElement(name = "result_unit")
        protected String resultUnit;
        @XmlElement(name = "reference_range")
        protected String referenceRange;
        @XmlElement(name = "detection_limit_ind_cd")
        protected String detectionLimitIndCd;
        @XmlElement(name = "detection_limit_ind_desc")
        protected String detectionLimitIndDesc;
        @XmlElement(name = "detection_limit_ind_lt_desc")
        protected String detectionLimitIndLtDesc;
        @XmlElement(name = "abnormal_ind_cd")
        protected String abnormalIndCd;
        @XmlElement(name = "abnormal_ind_desc")
        protected String abnormalIndDesc;
        @XmlElement(name = "abnormal_ind_lt_desc")
        protected String abnormalIndLtDesc;
        @XmlElement(name = "panel_lt_cd")
        protected String panelLtCd;
        @XmlElement(name = "panel_lt_desc")
        protected String panelLtDesc;
        @XmlElement(name = "report_auth_dtm")
        protected String reportAuthDtm;
        @XmlElement(name = "report_auth_staff_id")
        protected String reportAuthStaffId;
        @XmlElement(name = "report_auth_staff_eng_name")
        protected String reportAuthStaffEngName;
        @XmlElement(name = "report_auth_staff_eng_given_name")
        protected String reportAuthStaffEngGivenName;
        @XmlElement(name = "report_auth_staff_eng_name_prefix")
        protected String reportAuthStaffEngNamePrefix;
        @XmlElement(name = "report_auth_staff_chi_name")
        protected String reportAuthStaffChiName;
        @XmlElement(name = "report_auth_staff_chi_name_suffix")
        protected String reportAuthStaffChiNameSuffix;

        /**
         * Gets the value of the recordKey property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRecordKey() {
            return recordKey;
        }

        /**
         * Sets the value of the recordKey property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRecordKey(String value) {
            this.recordKey = value;
        }

        /**
         * Gets the value of the testRtName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTestRtName() {
            return testRtName;
        }

        /**
         * Sets the value of the testRtName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTestRtName(String value) {
            this.testRtName = value;
        }

        /**
         * Gets the value of the testRtId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTestRtId() {
            return testRtId;
        }

        /**
         * Sets the value of the testRtId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTestRtId(String value) {
            this.testRtId = value;
        }

        /**
         * Gets the value of the testRtDesc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTestRtDesc() {
            return testRtDesc;
        }

        /**
         * Sets the value of the testRtDesc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTestRtDesc(String value) {
            this.testRtDesc = value;
        }

        /**
         * Gets the value of the testLtId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTestLtId() {
            return testLtId;
        }

        /**
         * Sets the value of the testLtId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTestLtId(String value) {
            this.testLtId = value;
        }

        /**
         * Gets the value of the testLtDesc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTestLtDesc() {
            return testLtDesc;
        }

        /**
         * Sets the value of the testLtDesc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTestLtDesc(String value) {
            this.testLtDesc = value;
        }

        /**
         * Gets the value of the resultType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getResultType() {
            return resultType;
        }

        /**
         * Sets the value of the resultType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setResultType(String value) {
            this.resultType = value;
        }

        /**
         * Gets the value of the numericResult property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNumericResult() {
            return numericResult;
        }

        /**
         * Sets the value of the numericResult property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNumericResult(String value) {
            this.numericResult = value;
        }

        /**
         * Gets the value of the reportableResult property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReportableResult() {
            return reportableResult;
        }

        /**
         * Sets the value of the reportableResult property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReportableResult(String value) {
            this.reportableResult = value;
        }

        /**
         * Gets the value of the enumeratedResult property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEnumeratedResult() {
            return enumeratedResult;
        }

        /**
         * Sets the value of the enumeratedResult property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEnumeratedResult(String value) {
            this.enumeratedResult = value;
        }

        /**
         * Gets the value of the textResult property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTextResult() {
            return textResult;
        }

        /**
         * Sets the value of the textResult property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTextResult(String value) {
            this.textResult = value;
        }

        /**
         * Gets the value of the resultNote property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getResultNote() {
            return resultNote;
        }

        /**
         * Sets the value of the resultNote property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setResultNote(String value) {
            this.resultNote = value;
        }

        /**
         * Gets the value of the resultUnit property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getResultUnit() {
            return resultUnit;
        }

        /**
         * Sets the value of the resultUnit property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setResultUnit(String value) {
            this.resultUnit = value;
        }

        /**
         * Gets the value of the referenceRange property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReferenceRange() {
            return referenceRange;
        }

        /**
         * Sets the value of the referenceRange property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReferenceRange(String value) {
            this.referenceRange = value;
        }

        /**
         * Gets the value of the detectionLimitIndCd property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDetectionLimitIndCd() {
            return detectionLimitIndCd;
        }

        /**
         * Sets the value of the detectionLimitIndCd property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDetectionLimitIndCd(String value) {
            this.detectionLimitIndCd = value;
        }

        /**
         * Gets the value of the detectionLimitIndDesc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDetectionLimitIndDesc() {
            return detectionLimitIndDesc;
        }

        /**
         * Sets the value of the detectionLimitIndDesc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDetectionLimitIndDesc(String value) {
            this.detectionLimitIndDesc = value;
        }

        /**
         * Gets the value of the detectionLimitIndLtDesc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDetectionLimitIndLtDesc() {
            return detectionLimitIndLtDesc;
        }

        /**
         * Sets the value of the detectionLimitIndLtDesc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDetectionLimitIndLtDesc(String value) {
            this.detectionLimitIndLtDesc = value;
        }

        /**
         * Gets the value of the abnormalIndCd property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAbnormalIndCd() {
            return abnormalIndCd;
        }

        /**
         * Sets the value of the abnormalIndCd property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAbnormalIndCd(String value) {
            this.abnormalIndCd = value;
        }

        /**
         * Gets the value of the abnormalIndDesc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAbnormalIndDesc() {
            return abnormalIndDesc;
        }

        /**
         * Sets the value of the abnormalIndDesc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAbnormalIndDesc(String value) {
            this.abnormalIndDesc = value;
        }

        /**
         * Gets the value of the abnormalIndLtDesc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAbnormalIndLtDesc() {
            return abnormalIndLtDesc;
        }

        /**
         * Sets the value of the abnormalIndLtDesc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAbnormalIndLtDesc(String value) {
            this.abnormalIndLtDesc = value;
        }

        /**
         * Gets the value of the panelLtCd property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPanelLtCd() {
            return panelLtCd;
        }

        /**
         * Sets the value of the panelLtCd property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPanelLtCd(String value) {
            this.panelLtCd = value;
        }

        /**
         * Gets the value of the panelLtDesc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPanelLtDesc() {
            return panelLtDesc;
        }

        /**
         * Sets the value of the panelLtDesc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPanelLtDesc(String value) {
            this.panelLtDesc = value;
        }

        /**
         * Gets the value of the reportAuthDtm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReportAuthDtm() {
            return reportAuthDtm;
        }

        /**
         * Sets the value of the reportAuthDtm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReportAuthDtm(String value) {
            this.reportAuthDtm = value;
        }

        /**
         * Gets the value of the reportAuthStaffId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReportAuthStaffId() {
            return reportAuthStaffId;
        }

        /**
         * Sets the value of the reportAuthStaffId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReportAuthStaffId(String value) {
            this.reportAuthStaffId = value;
        }

        /**
         * Gets the value of the reportAuthStaffEngName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReportAuthStaffEngName() {
            return reportAuthStaffEngName;
        }

        /**
         * Sets the value of the reportAuthStaffEngName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReportAuthStaffEngName(String value) {
            this.reportAuthStaffEngName = value;
        }

        /**
         * Gets the value of the reportAuthStaffEngGivenName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReportAuthStaffEngGivenName() {
            return reportAuthStaffEngGivenName;
        }

        /**
         * Sets the value of the reportAuthStaffEngGivenName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReportAuthStaffEngGivenName(String value) {
            this.reportAuthStaffEngGivenName = value;
        }

        /**
         * Gets the value of the reportAuthStaffEngNamePrefix property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReportAuthStaffEngNamePrefix() {
            return reportAuthStaffEngNamePrefix;
        }

        /**
         * Sets the value of the reportAuthStaffEngNamePrefix property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReportAuthStaffEngNamePrefix(String value) {
            this.reportAuthStaffEngNamePrefix = value;
        }

        /**
         * Gets the value of the reportAuthStaffChiName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReportAuthStaffChiName() {
            return reportAuthStaffChiName;
        }

        /**
         * Sets the value of the reportAuthStaffChiName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReportAuthStaffChiName(String value) {
            this.reportAuthStaffChiName = value;
        }

        /**
         * Gets the value of the reportAuthStaffChiNameSuffix property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReportAuthStaffChiNameSuffix() {
            return reportAuthStaffChiNameSuffix;
        }

        /**
         * Sets the value of the reportAuthStaffChiNameSuffix property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReportAuthStaffChiNameSuffix(String value) {
            this.reportAuthStaffChiNameSuffix = value;
        }

    }

}
