CREATE OR REPLACE FUNCTION "NHS_RPT_ABMEDRECORD"(V_BKGSDATE IN VARCHAR2,
                                                 V_BKGEDATE IN VARCHAR2,
                                                 V_BKGCDATE IN VARCHAR2,
                                                 V_STECODE  VARCHAR,
                                                 V_DOCCODE  VARCHAR)
  RETURN TYPES.CURSOR_TYPE AS
  OUTCUR TYPES.CURSOR_TYPE;
BEGIN
  OPEN OUTCUR FOR
    SELECT SIT.STENAME,
           SUBSTR(B.PATNO2, 1, 2) AS PATNOA,
           SUBSTR(B.PATNO2, 3, 2) AS PATNOB,
           SUBSTR(B.PATNO2, 5, 2) AS PATNOC,
           SUBSTR(B.PATNO2, 7, 2) AS PATNOD,
           SUBSTR(B.PATNO2, 9, 2) AS PATNOE,
           B.BKGPNAME || ' ' || DECODE(P.PATSTAFF, -1, '(S)', '') AS NAME,
           'OPD - ' || SP.SPCNAME AS SPNAME,
           D.DOCFNAME || ' ' || D.DOCGNAME AS DOCNAME,
           TO_CHAR(B.BKGSDATE, 'DD/MM/YYYY HH24:MI') AS BKGSDATE,
           U.USRNAME AS CALLEDBY,
           NHS_UTL_LOOKUP_PALERTCODES(P.PATNO) AS ALERT
      FROM (SELECT LPAD(Y.PATNO, 10, ' ') AS PATNO2, Y.* FROM BOOKING Y) B,
           SCHEDULE S,
           DOCTOR D,
           SITE SIT,
           SPEC SP,
           USR U,
           PATIENT P
     WHERE B.SCHID = S.SCHID
       AND S.DOCCODE = D.DOCCODE
       AND D.DOCPICKLIST = -1
       AND B.BKGSTS = 'N'
       AND B.STECODE = SIT.STECODE
       AND B.PATNO IS NOT NULL
       AND D.SPCCODE = SP.SPCCODE
       AND UPPER(B.USRID) = UPPER(U.USRID)
       AND B.PATNO = P.PATNO
       AND B.STECODE = V_STECODE
       AND B.BKGSDATE >= TO_DATE(V_BKGSDATE, 'DD/MM/YYYY HH24:MI')
       AND B.BKGSDATE <= TO_DATE(V_BKGEDATE, 'DD/MM/YYYY HH24:MI')
       AND (B.BKGCDATE >= TO_DATE(V_BKGCDATE, 'DD/MM/YYYY HH24:MI') OR
           V_BKGCDATE IS NULL)
       AND (S.DOCCODE = V_DOCCODE OR V_DOCCODE IS NULL)
       ORDER BY PATNOE, PATNOD, PATNOC, PATNOB, PATNOA
    --AND S.DOCCODE IN (V_DOCCODESS)
    ;
  RETURN OUTCUR;
END NHS_RPT_ABMEDRECORD;
/
