CREATE OR REPLACE FUNCTION NHS_RPT_PRINTPACKAGELST (
	V_STECODE VARCHAR2
)
	RETURN Types.cursor_type
AS
	outcur types.cursor_type;
	v_stntdate DATE := TRUNC(SYSDATE);
BEGIN
	OPEN outcur FOR
	SELECT
		P.PKGCODE "Code",
		P.PKGNAME "Name",
		P.PKGCNAME "CName",
		P.DPTCODE "Dept Code",
		P.PKGRLVL "Report Level",
		P.PKGTYPE "Type",
		P.PKGALERT "Alert"
--		SUM(I.ITCAMT1) ""
	FROM   PACKAGE P
	LEFT JOIN ITEMCHG I ON P.PKGCODE = I.PKGCODE AND ( I.itcsdt IS NULL OR I.itcsdt <= v_stntdate ) AND ( I.itcedt IS NULL OR I.itcedt >= v_stntdate )
	WHERE  1 = 1
	GROUP BY P.PKGCODE, P.PKGNAME, P.PKGCNAME, P.DPTCODE, P.PKGRLVL, P.PKGTYPE, P.PKGALERT
	ORDER BY P.PKGCODE, P.PKGNAME;
	RETURN OUTCUR;
END NHS_RPT_PRINTPACKAGELST;
/
