CREATE OR REPLACE FUNCTION "NHS_RPT_DAYCASERECEIPT_SUB"(V_SLPNO IN VARCHAR2)
	RETURN TYPES.CURSOR_TYPE AS
	OUTCUR TYPES.CURSOR_TYPE;
BEGIN
	OPEN OUTCUR FOR
		SELECT NHS_RPT_IPRECEIPT_SUB(V_SLPNO, '') FROM DUAL;
	RETURN OUTCUR;
END NHS_RPT_DAYCASERECEIPT_SUB;
/
