create or replace FUNCTION "NHS_GET_SLIPTX_U2C_STNCDATE"
(V_SLPNO SLIPTX.SLPNO%TYPE,
V_STNSEQ SLIPTX.STNSEQ%TYPE
)
  RETURN sliptx.STNCDATE%TYPE
AS
  V_STNCDATE SLIPTX.STNCDATE%TYPE;
BEGIN  
  BEGIN
    SELECT STNCDATE
    INTO V_STNCDATE     
    FROM SLIPTX
    WHERE SLPNO = V_SLPNO
    AND STNSEQ IN (
    SELECT STNDESC
    FROM SLIPTX 
    WHERE SLPNO = V_SLPNO
    AND STNSEQ = V_STNSEQ
    AND STNSTS = 'U')
    AND STNSTS = 'C';
  EXCEPTION
  WHEN OTHERS THEN
    V_STNCDATE := NULL;
  END;
RETURN V_STNCDATE;
end;
/