create or replace FUNCTION "NHS_RPT_IPSTATEMENTWB" (
	v_SLPNO IN VARCHAR2,
  	V_GENDATE IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE AS
--RETURN VARCHAR2 AS
	OUTCUR TYPES.CURSOR_TYPE;
  SQLSTR VARCHAR2(32767);
  LASTPRTDATE VARCHAR2(10);
  TO_WBDATE VARCHAR2(10);
  FROM_WBDATE VARCHAR2(10); 
  MAXPRTDATE VARCHAR2(10);
  SLPDATE VARCHAR2(10);
BEGIN
    EXECUTE IMMEDIATE ' SELECT TO_CHAR(MAX(PRINTDATE),''DD/MM/YYYY'') FROM DAYENDSLIPS WHERE SLPNO=''' || v_SLPNO || ''' AND trunc(PRINTDATE,''DD'') < trunc(TO_DATE('''||V_GENDATE||''',''DD/MM/YYYY HH24MISS''),''dd'') AND ENABLED = ''1''' INTO LASTPRTDATE;
    EXECUTE IMMEDIATE ' SELECT TO_CHAR(MAX(PRINTDATE)-1,''DD/MM/YYYY'') FROM DAYENDSLIPS WHERE SLPNO=''' || v_SLPNO || ''' AND trunc(PRINTDATE,''DD'') <= trunc(TO_DATE('''||V_GENDATE||''',''DD/MM/YYYY HH24MISS''),''dd'') AND ENABLED = ''1''' INTO MAXPRTDATE;
   BEGIN   
    IF LASTPRTDATE IS NULL AND V_GENDATE IS NOT NULL THEN        
      EXECUTE IMMEDIATE ' SELECT TO_CHAR(SLPDATE,''DD/MM/YYYY'') FROM SLIP_EXTRA WHERE SLPNO=''' || v_SLPNO || ''''  INTO SLPDATE;
      FROM_WBDATE := SLPDATE;
    ELSE
      FROM_WBDATE := LASTPRTDATE;
    END IF;
    TO_WBDATE := MAXPRTDATE;
  EXCEPTION
  WHEN OTHERS THEN
    LASTPRTDATE := NULL;
  END;

  SQLSTR := '
		SELECT NVL(S.SLPFNAME, P.PATFNAME) || '' '' ||
			NVL(S.SLPGNAME, P.PATGNAME) AS PATNAME,
			P.PATCNAME,
			S.SLPNO,
			P.PATNO,
			TO_CHAR(R.REGDATE, ''DD-Mon-YYYY'',''nls_date_language=ENGLISH'') AS REGDATE,
			TO_CHAR(R.REGDATE, ''HH24:MI'') AS REGTIME,
			I.BEDCODE || '','' || A.ACMNAME AS BEDACM,
			TO_CHAR(I.INPDDATE, ''DD-Mon-YYYY'',''nls_date_language=ENGLISH'') AS INPDDATE,
			TO_CHAR(I.INPDDATE, ''HH24:MI'') AS INPDTIME,
			D.DOCFNAME || '' '' || D.DOCGNAME AS DOCNAME,
			D.DOCCNAME, '''|| FROM_WBDATE ||''' AS FROM_WBDATE,'''||TO_WBDATE||''' AS TO_WBDATE
		FROM  SLIP S, PATIENT P, REG R, INPAT I, DOCTOR D, ACM A
		WHERE S.REGID = R.REGID
		AND   S.PATNO = P.PATNO(+)
		AND   R.INPID = I.INPID(+)
		AND   I.ACMCODE =  A.ACMCODE
		AND   S.DOCCODE = D.DOCCODE
		AND   S.SLPNO = ''' || v_SLPNO || '''';
OPEN OUTCUR FOR SQLSTR;
RETURN OUTCUR;
--RETURN SQLSTR;
END NHS_RPT_IPSTATEMENTWB;
/