create or replace FUNCTION "NHS_GET_COUNTEDIPACKAGE"(V_SLPNO IN VARCHAR2, V_ARCODE IN VARCHAR2)
	RETURN NUMBER AS
  	V_RESULT NUMBER;
    
 BEGIN

 SELECT COUNT(1) INTO V_RESULT FROM SLIPTX WHERE PKGCODE IN (SELECT HPSTATUS FROM HPSTATUS WHERE  HPKEY = V_ARCODE  AND HPRMK1 = 'PACKAGE' AND HPTYPE   = 'EDI'  AND HPACTIVE    = -1) AND SLPNO = V_SLPNO AND STNSTS IN ('N','A');
                      
  
   RETURN V_RESULT;
    	
END NHS_GET_COUNTEDIPACKAGE;
/