create or replace FUNCTION "NHS_RPT_PICKLSTLBLCRITERIA" (
	v_BKGSDATE IN VARCHAR2,
	v_BKGEDATE IN VARCHAR2,
	v_BKGCDATE IN VARCHAR2,
	v_STECODE  IN VARCHAR2,
	v_DOCCODE  IN VARCHAR2,
	v_ORDERBY  IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
BEGIN
	OPEN OUTCUR FOR
		SELECT
			D.DOCFNAME ||' ' ||D.DOCGNAME AS DOCNAME,
			TO_CHAR(B.BKGSDATE, 'HH24:MI') ||' ('||TO_CHAR(B.BKGSDATE, 'DD/MM/YYYY')||')' AS BKGSDATE,
			DECODE(IS_NUMBER(B.PATNO), 0, TRIM(TO_CHAR(B.PATNO)), B.PATNO) AS PATNO_T,
			B.BKGPNAME  as PATNAME,
      L.MRLDESC,H.MRHVOLLAB,B.DOCLOCID,NHS_GEN_MEDLBLCONTENT(B.PATNO) AS MRLBLCONTENT
--			(
--				SELECT L.MRLDESC
--				FROM   MEDRECHDR H, MEDRECDTL D, MEDRECLOC L, DOCTOR DOC
--				WHERE  H.PATNO = B.PATNO
--				AND    D.DOCCODE = DOC.DOCCODE(+)
--				AND    H.MRHVOLLAB = (SELECT MAX(MRHVOLLAB) AS MAXVOL FROM MEDRECHDR WHERE PATNO = H.PATNO AND MRHSTS = 'N')
--				AND    H.MRDID = D.MRDID
--				AND    NVL(D.MRLID_R, D.MRLID_L) = L.MRLID
--				AND    H.mrhsts = 'N'
--			) AS LOC,
--			(
--				SELECT H.MRHVOLLAB
--				FROM   MEDRECHDR H, MEDRECDTL D, MEDRECLOC L
--				WHERE  H.PATNO = B.PATNO
--				AND    H.MRHVOLLAB = (SELECT MAX(MRHVOLLAB) AS MAXVOL FROM MEDRECHDR WHERE PATNO = H.PATNO AND MRHSTS = 'N')
--				AND    H.MRDID = D.MRDID
--				AND    NVL(D.MRLID_R, D.MRLID_L) = L.MRLID
--				AND    H.mrhsts = 'N'
--			) AS VOLNUM
--			NHS_UTL_MEDREC_CUR_WCOL(B.PATNO,'CURRENTLOCATION') AS LOC,
--			NHS_UTL_MEDREC_CUR_WCOL(B.PATNO,'MRHVOLLAB') AS VOLNUM
		FROM BOOKING B, SCHEDULE S, DOCTOR D, SITE SIT,MEDRECHDR H, MEDRECDTL DT, MEDRECLOC L
		WHERE B.SCHID = S.SCHID
    AND B.PATNO = H.PATNO
    AND H.MRDID = DT.MRDID
    AND NVL(DT.MRLID_R, DT.MRLID_L) = L.MRLID
    AND    H.MRHVOLLAB = (SELECT MAX(MRHVOLLAB) AS MAXVOL FROM MEDRECHDR WHERE PATNO = B.PATNO AND MRHSTS = 'N'  AND MRMID = 1)   
		AND    H.mrhsts = 'N'
    AND   S.DOCCODE = D.DOCCODE
		AND   D.DOCPICKLIST = -1
		AND   B.BKGSTS = 'N'
		AND   B.STECODE = SIT.STECODE
		AND   B.PATNO IS NOT NULL
		AND   B.STECODE = v_STECODE
		AND   B.BKGSDATE >= TO_DATE( replace(v_BKGSDATE,'+',' '), 'DD/MM/YYYY HH24:MI')
		AND   B.BKGSDATE <= TO_DATE( replace(v_BKGEDATE,'+',' '), 'DD/MM/YYYY HH24:MI')
		AND  (B.BKGCDATE >= TO_DATE(replace(v_BKGCDATE,'+',' '), 'DD/MM/YYYY HH24:MI') OR v_BKGCDATE IS NULL)
		AND  (S.DOCCODE = v_DOCCODE OR v_DOCCODE IS NULL)
		ORDER BY
			CASE WHEN v_ORDERBY = 'P' THEN DECODE(Is_Number(B.PATNO), 0, TRIM(TO_CHAR(B.PATNO, '0000000')), LPAD(B.PATNO, 7, '0'))
				WHEN v_ORDERBY = 'T' THEN SUBSTR(LPAD(PATNO_T, 7, '0'), 10, 2)
				ELSE B.PATNO END,
			CASE WHEN v_ORDERBY = 'T' THEN SUBSTR(LPAD(PATNO_T, 7, '0'), 8, 2)
				ELSE B.PATNO END,
			CASE WHEN v_ORDERBY = 'T' THEN SUBSTR(LPAD(PATNO_T, 7, '0'), 6, 2)
				ELSE B.PATNO END,
			CASE WHEN v_ORDERBY = 'T' THEN SUBSTR(LPAD(PATNO_T, 7, '0'), 4, 2)
				ELSE B.PATNO END,
			CASE WHEN v_ORDERBY = 'T' THEN SUBSTR(LPAD(PATNO_T, 7, '0'), 2, 2)
				ELSE B.PATNO END
--		AND S.DOCCODE IN (v_DOCCODESS)
		;

	RETURN Outcur;
END NHS_RPT_PICKLSTLBLCRITERIA;
/
