create or replace
FUNCTION "NHS_RPT_OBBOOKING" (V_BPBID IN VARCHAR2)
  RETURN TYPES.CURSOR_TYPE
AS
  OUTCUR TYPES.CURSOR_TYPE;
BEGIN
  OPEN OUTCUR FOR
    SELECT B.BPBPNAME AS PATNAME,
           B.BPBCNAME AS PATCNAME,
           TO_CHAR(B.BPBHDATE,'DD/MM/YYYY') AS BPBHDATE,
           B.BPBNO,
           D.DOCFNAME || ' ' || D.DOCGNAME AS DOCNAME,
           D.DOCFAXNO AS DOCFAX,
           D.DOCOTEL AS DOCTEL,
           TO_CHAR(SYSDATE, 'D Month, YYYY', 'nls_date_language=american') PRINTDATE
      FROM BEDPREBOK B, DOCTOR D
     WHERE B.DOCCODE = D.DOCCODE
       AND B.PBPID = V_BPBID;
  RETURN OUTCUR;
END NHS_RPT_OBBOOKING;
/
