CREATE OR REPLACE FUNCTION "NHS_RPT_OBCANCELLATION"(V_BPBID IN VARCHAR2)
  RETURN TYPES.CURSOR_TYPE
AS
  OUTCUR TYPES.CURSOR_TYPE;
  SQLSTR VARCHAR2(1000);
BEGIN
  SQLSTR := '
    SELECT D.DOCFNAME || '' '' || D.DOCGNAME AS DOCNAME,
       D.DOCOFFADD1 AS ADD1,
       D.DOCOFFADD2 AS ADD2,
       D.DOCOFFADD3 AS ADD3,
       D.DOCOFFADD4 AS ADD4,
       D.DOCOTEL AS DOCTEL,
       D.DOCFAXNO AS DOCFAX,
       B.PATFNAME || '' '' || B.PATGNAME AS PATNAME,
       TO_CHAR(B.BPBHDATE, ''DD/MM/YYYY'') EDC,
       B.BPBNO
  FROM BEDPREBOK B, DOCTOR D
 WHERE B.DOCCODE = D.DOCCODE
   AND B.PBPID IN (' || V_BPBID || ')';
  OPEN OUTCUR FOR SQLSTR;
  RETURN OUTCUR;
END NHS_RPT_OBCANCELLATION;
/
