create or replace
FUNCTION "NHS_RPT_PICKLSTLBL"(V_BKGSDATE IN VARCHAR2,
                                                V_BKGEDATE IN VARCHAR2,
                                                V_BKGCDATE IN VARCHAR2,
                                                V_STECODE  VARCHAR,
                                                V_DOCCODE  VARCHAR)
  RETURN TYPES.CURSOR_TYPE AS
  OUTCUR TYPES.CURSOR_TYPE;
BEGIN
  OPEN OUTCUR FOR
    SELECT
           D.DOCFNAME ||' ' ||D.DOCGNAME AS DOCNAME,
           TO_CHAR(B.BKGSDATE, 'HH24:MI') ||' ('||TO_CHAR(B.BKGSDATE, 'DD/MM/YYYY')||')' AS BKGSDATE,
           B.PATNO,
           B.BKGPNAME  AS PATNAME,
           (SELECT L.MRLDESC || '(' || DOC.DOCFNAME || ' ' || DOC.DOCGNAME || ')'
            FROM MEDRECHDR H, MEDRECDTL D, MEDRECLOC L, DOCTOR DOC
            WHERE H.PATNO = B.PATNO
            AND D.DOCCODE = DOC.DOCCODE(+)
            AND H.MRHVOLLAB = (SELECT MAX(MRHVOLLAB) AS MAXVOL FROM MEDRECHDR WHERE PATNO = H.PATNO AND MRHSTS = 'N')
            AND H.MRDID = D.MRDID
            AND NVL(D.MRLID_R, D.MRLID_L) = L.MRLID) AS LOC,
          (SELECT H.MRHVOLLAB 
            FROM MEDRECHDR H, MEDRECDTL D, MEDRECLOC L
            WHERE H.PATNO = B.PATNO
            AND H.MRHVOLLAB = (SELECT MAX(MRHVOLLAB) AS MAXVOL FROM MEDRECHDR WHERE PATNO = H.PATNO AND MRHSTS = 'N')
            AND H.MRDID = D.MRDID
            AND NVL(D.MRLID_R, D.MRLID_L) = L.MRLID) AS VOLNUM
     FROM BOOKING B, SCHEDULE S, DOCTOR D, SITE SIT
     WHERE B.SCHID = S.SCHID
       AND S.DOCCODE = D.DOCCODE
       AND D.DOCPICKLIST = -1
       AND B.BKGSTS = 'N'
       AND B.STECODE = SIT.STECODE
       AND B.PATNO IS NOT NULL
       AND B.STECODE = V_STECODE
       AND B.BKGSDATE >= TO_DATE(V_BKGSDATE, 'DD/MM/YYYY HH24:MI')
       AND B.BKGSDATE <= TO_DATE(V_BKGEDATE, 'DD/MM/YYYY HH24:MI')
       AND (B.BKGCDATE >= TO_DATE(V_BKGCDATE, 'DD/MM/YYYY HH24:MI') OR
           V_BKGCDATE IS NULL)
       AND (S.DOCCODE = V_DOCCODE OR V_DOCCODE IS NULL)
    ORDER BY B.PATNO
    --AND S.DOCCODE IN (V_DOCCODESS)
    ;
  RETURN OUTCUR;
END NHS_RPT_PICKLSTLBL;
/