create or replace FUNCTION "NHS_RPT_DAYENDCOVERLETTER" (
	v_PRINTDATE IN VARCHAR2,
  v_SLPNO IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
BEGIN
  OPEN OUTCUR FOR
    SELECT NHS_GET_DAYENDCOVERLTRSLIP(TO_CHAR(DSLP.PRINTDATE,'DD/MM/YYYY'),DSLP.PATNO) AS ALLSLPNO, DSLP.PATNO, DSLP.PATNAME, 
    DSLP.PATFNAME, DSLP.BEDCODE, DSLP.TITDESC AS PATTITLE, DSLP.OUTAMT AS AMT, DSLP.PRINTDATE,
    TO_DATE(v_PRINTDATE,'DD/MM/YYYY')-5 AS FROMDATE,TO_DATE(v_PRINTDATE,'DD/MM/YYYY')-1 AS TODATE
    FROM
    (SELECT PATNO, PATNAME, PATFNAME, MAX(BEDCODE) AS BEDCODE, TITDESC, PRINTDATE, SUM(OUTAMT) AS OUTAMT
    FROM DAYENDSLIPS 
    WHERE TO_CHAR(PRINTDATE,'DD/MM/YYYY') = v_PRINTDATE
    AND SLPNO = v_SLPNO
    GROUP BY PATNO, PATNAME, PATFNAME, TITDESC, PRINTDATE) DSLP
    ORDER BY DSLP.PATNO;
  RETURN OUTCUR;
END NHS_RPT_DAYENDCOVERLETTER;
/