create or replace FUNCTION "NHS_GET_SLIPTX_U2C_STNSDATE"
(V_SLPNO SLIPTX.SLPNO%TYPE,
V_STNSEQ SLIPTX.STNSEQ%TYPE
)
  RETURN sliptx_extra.STNSDATE%TYPE
AS
  V_STNSDATE SLIPTX_EXTRA.STNSDATE%TYPE;
BEGIN  
  BEGIN
    SELECT STE.STNSDATE
    INTO V_STNSDATE     
    FROM SLIPTX ST, SLIPTX_EXTRA STE
    WHERE ST.STNID = STE.STNID
    AND ST.SLPNO = V_SLPNO
    AND ST.STNSEQ IN (
    SELECT STNDESC
    FROM SLIPTX 
    WHERE SLPNO = V_SLPNO
    AND STNSEQ = V_STNSEQ
    AND STNSTS = 'U')
    AND STNSTS = 'C';
  EXCEPTION
  WHEN OTHERS THEN
    V_STNSDATE := NULL;
  END;
RETURN V_STNSDATE;
end;
/