CREATE OR REPLACE FUNCTION "NHS_RPT_CHRGSMY" (
	v_SLPNO IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
BEGIN
	OPEN OUTCUR FOR
		SELECT NVL(P.PATLFNAME, NVL(S.SLPFNAME, P.PATFNAME))
           ||' '||NVL(P.PATLGNAME, NVL(S.SLPGNAME, P.PATGNAME)) AS PATNAME,
			P.PATCNAME,
			S.SLPNO,
			P.PATNO,
			TO_CHAR(R.REGDATE, 'DD-MON-YYYY','nls_date_language=ENGLISH') AS REGDATE,
			TO_CHAR(R.REGDATE, 'HH24:MI') AS REGTIME,
			I.BEDCODE || ',' || A.ACMNAME AS BEDACM,
			TO_CHAR(I.INPDDATE, 'DD-MON-YYYY','nls_date_language=ENGLISH') AS INPDDATE,
			TO_CHAR(I.INPDDATE, 'HH24:MI') AS INPDTIME,
			D.DOCFNAME || ' ' || D.DOCGNAME AS DOCNAME,
			D.DOCCNAME,
			I.BEDCODE, A.ACMNAME
		FROM  SLIP S, PATIENT P, REG R, INPAT I, DOCTOR D, ACM A
		WHERE S.REGID = R.REGID
		AND   S.PATNO = P.PATNO(+)
		AND   R.INPID = I.INPID(+)
		AND   I.ACMCODE =  A.ACMCODE
		AND   S.DOCCODE = D.DOCCODE
		AND   S.SLPNO = v_SLPNO;
  RETURN OUTCUR;
END NHS_RPT_CHRGSMY;
/
