CREATE OR REPLACE FUNCTION "NHS_RPT_APPLISTING" (
	v_BKGSDATE IN VARCHAR2,
	v_BKGEDATE IN VARCHAR2,
	v_BKGCDATE IN VARCHAR2,
	v_STECODE  IN VARCHAR2,
	v_DOCCODE  IN VARCHAR2,
	v_DOCLIST  IN VARCHAR2,
	v_ORDERBY  IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE AS
	OUTCUR TYPES.CURSOR_TYPE;
	Strsql Varchar2(30000);
	Strdoc Varchar2(30000);
	STRBKGCDATE VARCHAR2(100);
	alertVar varchar2(50);
BEGIN
	If v_DOCCODE Is Not Null Then
		STRDOC := v_DOCCODE;
	ELSE
		STRDOC := v_DOCLIST;
	END IF;

	IF v_BKGCDATE IS NOT NULL THEN
		STRBKGCDATE := ' AND B.BKGCDATE >= TO_DATE(''' || v_BKGCDATE || ''', ''DD/MM/YYYY HH24:MI'') ';
	ELSE
		STRBKGCDATE := '';
	END IF;

	Strsql:='
		SELECT
			S.DOCCODE,
			''$B'' || S.DOCCODE || NHS_GEN_CHECKDIGIT(''$B'' || S.DOCCODE) || ''#'' as DOCCODEWITHCHKDGT,
			''$B'' || S.DOCCODE as DOCCODEWITHOUTCHKDGT,
			D.DOCFNAME || '' '' || D.DOCGNAME AS DOCNAME,
			P.PATSEX || ''/'' || trunc(months_between(sysdate, p.patbdate)/12) AS SEXAGE,
			p.coucode AS COUNTRY,
			TO_CHAR(B.BKGSDATE, ''DD/MM/YYYY'') AS BKGSDATE,
			TO_CHAR(B.BKGSDATE, ''HH24:MI'') AS ATIME,
			B.PATNO,
			B.BKGPNAME  AS PATNAME,P.PATCNAME,
			B.BKGPTEL,
			TO_CHAR(B.BKGSCNT) BKGSCNT,
			TO_CHAR(B.BKGCDATE, ''DD/MM/YYYY HH24:MI'') AS BKGCDATE,
			TO_CHAR(B.BKGCDATE, ''HH24:MI'') AS CTIME,
			DECODE(U.USRNAME, NULL, B.USRID, U.USRNAME),
			NVL(b.bkgmtel, '''') AS MOBILE,
			B.BKGRMK,
			P.PATOTEL AS OFFICETEL,
			GET_ALERT_CODE(B.PATNO,null) as alert,
			SIT.STENAME,
			DECODE(b.sms, -1, ''Yes'', 0, ''No'') AS sms,
			TO_CHAR(b.smssdtok,''dd/mm/yyyy hh24:mi'') AS smssdtok,
			b.smsrtnmsg,
			NHS_UTL_LASTTEST(B.PATNO,  ''' || REPLACE(v_BKGSDATE, '+', ' ') || ''', ''' || REPLACE(v_BKGEDATE, '+', ' ') || ''', ''10'') AS TESTDONE,
			DECODE(Is_Number(B.PATNO), 0, TRIM(TO_CHAR(B.PATNO, ''000000'')), B.PATNO) AS PATNO_T,
			(
				SELECT L.MRLDESC
				FROM   MEDRECHDR H, MEDRECDTL D, MEDRECLOC L, DOCTOR DOC
				WHERE  H.PATNO = B.PATNO
				AND    D.DOCCODE = DOC.DOCCODE(+)
				AND    H.MRHVOLLAB = (SELECT MAX(MRHVOLLAB) AS MAXVOL FROM MEDRECHDR WHERE PATNO = H.PATNO AND MRHSTS = ''N'')
				AND    H.MRDID = D.MRDID
				AND    NVL(D.MRLID_R, D.MRLID_L) = L.MRLID
				AND    H.mrhsts = ''N''
			) AS LOC,
			(
				SELECT H.MRHVOLLAB
				FROM   MEDRECHDR H, MEDRECDTL D, MEDRECLOC L
				WHERE  H.PATNO = B.PATNO
				AND    H.MRHVOLLAB = (SELECT MAX(MRHVOLLAB) AS MAXVOL FROM MEDRECHDR WHERE PATNO = H.PATNO AND MRHSTS = ''N'')
				AND    H.MRDID = D.MRDID
				AND    NVL(D.MRLID_R, D.MRLID_L) = L.MRLID
				AND    H.mrhsts = ''N''
			) AS VOLNUM,
      		(NVL2(B.BKGOBLMP,''LMP:''||TO_CHAR(B.BKGOBLMP, ''DD/MM/YYYY''),'''')
			||NVL2(B.BKGOBEDC,'' EDC:''||TO_CHAR(B.BKGOBEDC, ''DD/MM/YYYY''),'''')
			||NVL2(B.BKGOBBIRTHORDER,'' Birth Order:''||B.BKGOBBIRTHORDER,'''')
			||NVL2(B.BKGOBREFERRALDOC,'' Referral Doctor:''||B.BKGOBREFERRALDOC,'''')
			||NVL2(B.BKGOBWEEKS,'' WEEKS:''||B.BKGOBWEEKS,'''') ) as MFM
		FROM  BOOKING B, SCHEDULE S, DOCTOR D, SITE SIT, PATIENT P, USR U
		WHERE B.SCHID = S.SCHID
		AND   S.DOCCODE = D.DOCCODE
		AND   D.DOCPICKLIST = -1
		AND   B.BKGSTS = ''N''
		AND   B.STECODE = SIT.STECODE
		AND   B.PATNO = P.PATNO (+)
		AND   B.USRID = U.USRID (+)
		AND   B.STECODE = ''' || v_STECODE || '''
		AND   B.BKGSDATE >= TO_DATE(''' || REPLACE(v_BKGSDATE, '+', ' ') || ''', ''DD/MM/YYYY HH24:MI'')
		AND   B.BKGSDATE <= TO_DATE(''' || REPLACE(v_BKGEDATE, '+', ' ') || ''', ''DD/MM/YYYY HH24:MI'') ' || Strbkgcdate;

	IF LENGTH(STRDOC) > 999 OR STRDOC = '-1' THEN
		STRSQL := STRSQL ||'AND S.DOCCODE in (Select doccode from doctor WHERE DOCPICKLIST = -1 AND SPCCODE != ''PHYSIO'') ';
	ELSIF STRDOC = '-2' THEN
		STRSQL := STRSQL ||'AND S.DOCCODE in (Select doccode from doctor WHERE DOCPICKLIST = -1 AND SPCCODE != ''PHYSIO'') ';
	ELSE
		STRSQL := STRSQL ||' AND S.DOCCODE in (''' || REPLACE(STRDOC, '/', ''', ''') || ''') ';
		STRSQL := STRSQL ||' AND S.DOCCODE in (Select doccode from doctor WHERE SPCCODE != ''PHYSIO'') ';
	END IF;

--

	IF v_ORDERBY = 'D' THEN
		STRSQL := STRSQL ||'order by d.doccode, atime';
	ELSIF V_ORDERBY = 'T' THEN
		Strsql := Strsql ||'order by d.doccode, SUBSTR(LPAD(PATNO_T, 6, ''0''), 9, 2), SUBSTR(LPAD(PATNO_T, 6, ''0''), 7, 2), SUBSTR(LPAD(PATNO_T, 6, ''0''), 5, 2), SUBSTR(LPAD(PATNO_T, 6, ''0''), 3, 2), SUBSTR(LPAD(PATNO_T, 6, ''0''), 1, 2)';
	ELSE
		Strsql := Strsql ||'order by d.doccode, atime';
	END IF;

	dbms_output.put_line(Strsql);

	OPEN OUTCUR FOR STRSQL;
	RETURN OUTCUR;
END NHS_RPT_APPLISTING;
/
