-- FOR REPORT RPTOTLOGLISTING
create or replace FUNCTION "NHS_GET_GETSTRFROMRTB" (
	v_OTLID INTEGER
)
	RETURN VARCHAR2
IS
	v_PART1 VARCHAR2(10);
	v_PART2 VARCHAR2(10);
	STMP VARCHAR2(1000);
	SLEFTSTR VARCHAR2(1000);
	SINPUT VARCHAR2(32767);
	IPOS1 INT;
	IPOS2 INT;
BEGIN
	v_PART1 := '\f0\fs17';
	v_PART2 := '\par';

	IF v_OTLID IS NOT NULL THEN
		BEGIN
			FOR CR IN (SELECT OTLCMT FROM OT_LOG WHERE OTLID = v_OTLID) LOOP
				SINPUT := SUBSTR(CR.OTLCMT, 1, 32767);
			END LOOP;
		EXCEPTION
		WHEN OTHERS THEN
			SINPUT := NULL;
		END;

		IF SINPUT IS NOT NULL THEN
			IPOS1 := INSTR(SINPUT, v_PART1, 1);
			IF IPOS1 > 0 THEN
				SLEFTSTR := SUBSTR(SINPUT, IPOS1 + LENGTH(v_PART1) + 1);
				IPOS2 := INSTR(SLEFTSTR, v_PART2, 1);

				WHILE IPOS2 > 0
				LOOP
					IF STMP IS NOT NULL THEN
						STMP := STMP || SUBSTR(SLEFTSTR, 1, IPOS2-1);
					ELSE
						STMP := SUBSTR(SLEFTSTR, 1, IPOS2-1);
					END IF;
					SLEFTSTR := SUBSTR(SLEFTSTR, IPOS2 + LENGTH(v_PART2) + 1);
					IPOS2 := INSTR(SLEFTSTR, v_PART2, 1);
				END LOOP;
			ELSE
				STMP := SINPUT;
			END IF;
		ELSE
			STMP := SINPUT;
		END IF;
	END IF;

	RETURN sTmp;
END NHS_GET_GETSTRFROMRTB;
/
