create or replace FUNCTION NHS_RPT_DPCHARGE
(   
    v_DPCID IN VARCHAR2
)
RETURN TYPES.CURSOR_TYPE
AS
OUTCUR TYPES.CURSOR_TYPE;
BEGIN
    OPEN OUTCUR FOR
        SELECT 
            to_char(SYSDATE,'dd/mm/yyyy') AS TXNDATE,
            T.ITMCODE AS ITMCODE, 
            T.PKGCODE AS PKGCODE,
            T.UNIT AS QTY,
            I.ITMDESC AS ITMNAME,
            T.DPCAMT AS AMOUNT,
            R.REGTYPE
        FROM DPCTX T, PQITEM I,DPCHARGE D, REG R
        WHERE SUBSTR(T.DPCBOX,0,2) = I.PQCATEGORY 
        AND SUBSTR(T.DPCBOX,3) = I.ITMCODE
        AND T.DPCID = D.DPCID
        AND T.DPCID = v_DPCID
        AND D.REGID = R.REGID
        ORDER BY T.ITMCODE;
    RETURN OUTCUR;
END NHS_RPT_DPCHARGE;
/
