create or replace
FUNCTION "NHS_RPT_RPTWEEKBILL_XLS" (
  V_PARAM1 VARCHAR2,
  V_PRINTDATE VARCHAR2
)
  RETURN TYPES.CURSOR_TYPE
AS
  OUTCUR TYPES.CURSOR_TYPE;
  V_CNT NUMBER;
  V_ADDROW NUMBER;
BEGIN
  SELECT COUNT(*)
  INTO V_CNT
  FROM (
  SELECT DISTINCT PATNO,SLPNO,PATNAME,PATFNAME,BEDCODE,TITDESC,TO_CHAR(REGDATE,'DD/MM/YYYY') AS REGDATE,SLPTYPE,ARCODE,OUTAMT
  FROM DAYENDSLIPS
  WHERE TRUNC(PRINTDATE) = TRUNC(TO_DATE(V_PRINTDATE,'DD/MM/YYYY'),'DD'));
  
  IF 14-V_CNT < 0 THEN
    V_ADDROW := 28-V_CNT;
  ELSIF 14-V_CNT = 0 THEN
    V_ADDROW := 14;
  ELSE
    V_ADDROW := 14-V_CNT;
  END IF;

  OPEN OUTCUR FOR
  SELECT DISTINCT PATNO,SLPNO,PATNAME,PATFNAME,BEDCODE,TITDESC,TO_CHAR(REGDATE,'DD/MM/YYYY') AS REGDATE,SLPTYPE,ARCODE,OUTAMT
  FROM DAYENDSLIPS
  WHERE TRUNC(PRINTDATE) = TRUNC(TO_DATE(V_PRINTDATE,'DD/MM/YYYY'),'DD')
  UNION ALL
  SELECT
  NULL AS PATNO,NULL AS SLPNO,NULL AS PATNAME,NULL AS PATFNAME,NULL AS BEDCODE,NULL AS TITDESC,NULL AS REGDATE,NULL AS SLPTYPE,NULL AS ARCODE,0 AS OUTAMT
  From DUAL
  LEFT JOIN
  (SELECT 1 FROM DUAL CONNECT BY LEVEL <= V_ADDROW) ON 1=1
  ORDER BY PATNO DESC nulls last,BEDCODE DESC,SLPNO ASC
  ;
RETURN OUTCUR;
END NHS_RPT_RPTWEEKBILL_XLS;
/