CREATE OR REPLACE
FUNCTION "NHS_GET_PHYSICALORDERFORM" (
	v_REGID IN VARCHAR2,
  	v_BKGID IN VARCHAR2
)
	RETURN Types.cursor_type
AS
	outcur Types.cursor_type;

BEGIN
	OPEN outcur for 
		SELECT R.REGID, P.PATNO, INITCAP(CONCAT(P.PATFNAME,(' '||P.PATGNAME))),
		P.PATSEX,TO_CHAR(P.PATBDATE,'dd/MM/YYYY'),P.PATIDNO,INITCAP(CONCAT(('DR. '||D.DOCFNAME),(' '||D.DOCGNAME))),TO_CHAR(R.REGDATE, 'dd/MM/YYYY HH24:MM'),
		LISTAGG(L.PKGCODE,',') WITHIN GROUP (ORDER BY R.PKGCODE), 
        LISTAGG(INITCAP(P.PKGNAME),',') WITHIN GROUP (ORDER BY R.PKGCODE), P.PATCNAME
		FROM REGPKGLINK L, PACKAGE P, REG R, PATIENT P, DOCTOR D
		WHERE P.PKGCODE = L.PKGCODE
		AND R.REGID = L.REGID
		AND R.PATNO = P.PATNO
		AND R.DOCCODE = D.DOCCODE 
		AND (R.REGID = v_REGID OR R.BKGID = v_BKGID)
		AND P.PKGPRINT = 'Y'
		GROUP BY R.REGID, P.PATNO, INITCAP(CONCAT(P.PATFNAME,(' '||P.PATGNAME))),P.PATSEX,TO_CHAR(P.PATBDATE,'dd/MM/YYYY'),P.PATIDNO,INITCAP(CONCAT(('DR. '||D.DOCFNAME),(' '||D.DOCGNAME))),TO_CHAR(R.REGDATE, 'dd/MM/YYYY HH24:MM'), P.PATCNAME;
	RETURN outcur;
END NHS_GET_PHYSICALORDERFORM;
/