-- FOR REPORT RPTOTLOGLISTING
create or replace
FUNCTION "NHS_GET_RPTOTAPPLIST2NDOP"
(
  v_OTlid VARCHAR2
)
  RETURN VARCHAR2
IS
V_OTPDESCALL VARCHAR2(2000);
V_OTPDESC OT_PROC.OTPDESC%TYPE;

CURSOR c_getOTPDesc IS
  SELECT OP.OTPDESC 
  from OT_LOG ol, OT_LOG_PROC olp, OT_PROC op
  WHERE OL.OTLID=OLP.OTLID 
  and olp.otpid=op.otpid
  AND OL.OTLID = V_OTLID
  order by op.OTPDESC;

BEGIN
  OPEN c_getOTPDesc;
  LOOP
  FETCH c_getOTPDesc INTO V_OTPDESC;
  EXIT WHEN c_getOTPDesc%NOTFOUND;
    IF V_OTPDESCALL IS NULL THEN
      V_OTPDESCALL := 'Secondary - '||V_OTPDESC;
    ELSE
      IF V_OTPDESC IS NOT NULL THEN
        V_OTPDESCALL := V_OTPDESCALL||CHR(13)||CHR(10)||'Secondary - '||V_OTPDESC;  
      END IF;
    END IF;
  END LOOP;
  CLOSE c_getOTPDesc;

  RETURN V_OTPDESCALL;
END NHS_GET_RPTOTAPPLIST2NDOP;
/