CREATE OR REPLACE FUNCTION NHS_RPT_PRINTITEMCHARGELST (
	v_SteCode VARCHAR2
)
	RETURN Types.cursor_type
AS
	outcur types.cursor_type;
BEGIN
	OPEN OUTCUR FOR
	SELECT  T.ITCID, T.ITMCODE, I.ITMNAME, T.ITCTYPE, T.PKGCODE, P.PKGNAME,
		T.ACMCODE, T.GLCCODE, T.ITCAMT1, T.ITCAMT2, T.CPSID, T.CPSPCT
	FROM    ITEMCHG T ,PACKAGE P, ITEM I
	WHERE   T.PKGCODE=P.PKGCODE(+)
	AND     I.ITMCODE = T.ITMCODE
	AND     I.ITMCAT <> 'C'
	ORDER BY T.ITMCODE, t.ItcType, t.PkgCode NULLS FIRST, t.AcmCode;

	RETURN OUTCUR;
END NHS_RPT_PRINTITEMCHARGELST;
/
