create or replace
FUNCTION NHS_RPT_TRANSFERBEDLABEL (
  V_PATNO   IN  VARCHAR2,
  V_REGID   IN  VARCHAR2
)
  RETURN types.cursor_type
AS
  outcur types.cursor_type;
  V_PATSEX  PATIENT.PATSEX%TYPE;
  V_BIRTHDATE VARCHAR2(10);
  V_PATNAME VARCHAR2(50);
  VPATCNAME VARCHAR2(10);
  isCheckDigit VARCHAR2(4);
BEGIN
  SELECT P.PATSEX, TO_CHAR(P.PATBDATE, 'DD/MM/YYYY'), P.PATFNAME || ' ' || P.PATGNAME, P.PATCNAME INTO
          V_PATSEX, V_BIRTHDATE, V_PATNAME, VPATCNAME
  FROM PATIENT P
  WHERE P.PATNO = V_PATNO;
  /*
  FROM PATIENT P, REG R, INPAT I
  WHERE P.PATNO = R.PATNO
  AND R.INPID = I.INPID
  AND R.REGID = V_REGID;
  */
  SELECT param1 INTO isCheckDigit
  FROM   sysparam
  WHERE  parcde = 'ChkDigit';

  OPEN OUTCUR FOR
  SELECT DECODE(isCheckDigit, 'YES', '*'||V_PATNO, V_PATNO), V_PATSEX, V_BIRTHDATE, V_PATNAME, VPATCNAME, 
          V_PATNO || TO_CHAR(NHS_GEN_CHECKDIGIT(V_PATNO)) || '#'
  FROM DUAL;
  RETURN OUTCUR;
END NHS_RPT_TRANSFERBEDLABEL;
/