create or replace FUNCTION "NHS_RPT_CHRGSMYCOVERLETTERSET" (
    v_PRINTDATE IN VARCHAR2,
	v_SLPNO IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
    --ALLSLPNO DAYENDSLIPS.SLPNO%TYPE;
    ALLSLPNO VARCHAR2(200);
    PATFNAME DAYENDSLIPS.PATFNAME%TYPE;
    PATTITLE DAYENDSLIPS.TITDESC%TYPE;
    AMT DAYENDSLIPS.OUTAMT%TYPE;
    FROM_DATE DATE;
    TODATE DATE;
    FROMDATE VARCHAR2(10);
    LASTPRTDATE VARCHAR2(10);
    REGDATE VARCHAR2(10);    
    SQLSTR VARCHAR2(32767);
    SQLSTRCHRG VARCHAR2(32767);    
BEGIN
    BEGIN
      EXECUTE IMMEDIATE ' SELECT TO_CHAR(MAX(PRINTDATE),''DD/MM/YYYY'') FROM DAYENDSLIPS WHERE SLPNO=''' || v_SLPNO || ''' AND trunc(PRINTDATE,''DD'') < trunc(TO_DATE('''||v_PRINTDATE||''',''DD/MM/YYYY HH24MISS''),''dd'') AND ENABLED = 1' INTO LASTPRTDATE;
      EXCEPTION
    WHEN OTHERS THEN
      LASTPRTDATE := NULL;
    END;
    
    IF v_PRINTDATE = LASTPRTDATE OR LASTPRTDATE IS NULL THEN
      BEGIN
            EXECUTE IMMEDIATE 'SELECT TO_CHAR(REGDATE,''DD/MM/YYYY'') FROM DAYENDSLIPS WHERE SLPNO=''' || v_SLPNO || ''' AND trunc(PRINTDATE,''DD'') = trunc(TO_DATE('''||v_PRINTDATE||''',''DD/MM/YYYY HH24MISS''),''dd'') AND ENABLED = 1' INTO REGDATE;
      
            EXECUTE IMMEDIATE 'SELECT TO_CHAR(MAX(PRINTDATE),''DD/MM/YYYY'') FROM DAYENDSLIPS WHERE trunc(PRINTDATE,''DD'') < trunc(TO_DATE('''||v_PRINTDATE||''',''DD/MM/YYYY HH24MISS''),''dd'') AND ENABLED = 1 and SLPNO = (
            SELECT MAX(SLPNO) FROM DAYENDSLIPS WHERE trunc(REGDATE,''DD'') = trunc(TO_DATE('''||REGDATE||''',''DD/MM/YYYY''),''dd'')
            AND SLPNO!=''' || v_SLPNO || ''' AND PATNO = (SELECT PATNO FROM DAYENDSLIPS WHERE SLPNO=''' || v_SLPNO || '''))' INTO LASTPRTDATE;
            
            IF LASTPRTDATE IS NULL THEN
                FROMDATE := REGDATE;
            ELSE
                FROMDATE := LASTPRTDATE;            
            END IF;
        EXCEPTION
      WHEN OTHERS THEN
        FROMDATE := TO_CHAR(TO_DATE(v_PRINTDATE,'DD/MM/YYYY')-5,'DD/MM/YYYY');
      END;
    ELSE
      FROMDATE := LASTPRTDATE;
    END IF;

 SQLSTR :=
    'SELECT NHS_GET_DAYENDCOVERLTRSLIP(TO_CHAR(DSLP.PRINTDATE,''DD/MM/YYYY''),DSLP.PATNO) AS ALLSLPNO,
    DSLP.PATFNAME, DSLP.TITDESC AS PATTITLE, DSLP.OUTAMT AS AMT,
    TO_DATE('''||FROMDATE||''',''DD/MM/YYYY'') AS FROMDATE,TO_DATE('''||v_PRINTDATE||''',''DD/MM/YYYY'')-1 AS TODATE
    FROM
    (SELECT PATNO, PATNAME, PATFNAME, MAX(BEDCODE) AS BEDCODE, TITDESC, PRINTDATE, SUM(OUTAMT) AS OUTAMT
    FROM DAYENDSLIPS
    WHERE TO_CHAR(PRINTDATE,''DD/MM/YYYY'') = '''||v_PRINTDATE||
    ''' AND SLPNO = '''||v_SLPNO||''' AND  ENABLED = 1
    GROUP BY PATNO, PATNAME, PATFNAME, TITDESC, PRINTDATE) DSLP
    ORDER BY DSLP.PATNO';
    
    EXECUTE IMMEDIATE SQLSTR INTO ALLSLPNO,PATFNAME,PATTITLE,AMT,FROM_DATE,TODATE;
    
    SQLSTRCHRG := 'SELECT NVL(S.SLPFNAME, P.PATFNAME) || '' '' ||
			NVL(S.SLPGNAME, P.PATGNAME) AS PATNAME,
			P.PATCNAME,
			S.SLPNO,
			P.PATNO,
			TO_CHAR(R.REGDATE, ''DD-MON-YYYY'',''nls_date_language=ENGLISH'') AS REGDATE,
			TO_CHAR(R.REGDATE, ''HH24:MI'') AS REGTIME,
			I.BEDCODE || '','' || A.ACMNAME AS BEDACM,
			TO_CHAR(I.INPDDATE, ''DD-MON-YYYY'',''nls_date_language=ENGLISH'') AS INPDDATE,
			TO_CHAR(I.INPDDATE, ''HH24:MI'') AS INPDTIME,
			D.DOCFNAME || '' '' || D.DOCGNAME AS DOCNAME,
			D.DOCCNAME,
			I.BEDCODE, 
            A.ACMNAME, '''||ALLSLPNO||''','''||PATFNAME||''','''||PATTITLE||''','''||AMT||''','''||FROMDATE||''',TO_CHAR(TO_DATE('''||TODATE||''',''DD/MM/YY''),''DD/MM/YYYY'') 
		FROM  SLIP S, PATIENT P, REG R, INPAT I, DOCTOR D, ACM A
		WHERE S.REGID = R.REGID
		AND   S.PATNO = P.PATNO(+)
		AND   R.INPID = I.INPID(+)
		AND   I.ACMCODE =  A.ACMCODE
		AND   S.DOCCODE = D.DOCCODE
		AND   S.SLPNO = '''||v_SLPNO||'''';
    OPEN OUTCUR FOR SQLSTRCHRG;        
    RETURN OUTCUR;
END NHS_RPT_CHRGSMYCOVERLETTERSET;
/