create or replace FUNCTION "NHS_RPT_IPSTATEMENTWB_SUB1"(
  V_ALLSLPNO IN VARCHAR2,
  V_GENDATE IN VARCHAR2
)
RETURN TYPES.CURSOR_TYPE AS
--RETURN VARCHAR2 AS
  OUTCUR TYPES.CURSOR_TYPE;
  SQLTMP VARCHAR2(32767);
  SQLTMP0 VARCHAR2(32767);
  SQLTMP1 VARCHAR2(32767);
  SQLWHERE1 VARCHAR2(32767);
  SQLWHERE2 VARCHAR2(32767);
  SQLSTR VARCHAR2(32767);
  LASTPRTDATE VARCHAR2(10);
  TOTALREFUND NUMBER;
  TOTALCHARGE NUMBER;
BEGIN
--TO_DATE(TO_CHAR(ST.STNTDATE, ''DD/MM/YYYY'') || '' 00:00:00'', ''DD/MM/YYYY HH24:MI:SS'')

--       AND ST.STNCDATE <trunc(TO_DATE('||V_GENDATE||',''DD/MM/YYYY HH24MISS''),''dd'')
--       AND ST.SLPNO IN (' || V_ALLSLPNO || ')';
  BEGIN
    EXECUTE IMMEDIATE ' SELECT TO_CHAR(MAX(PRINTDATE),''DD/MM/YYYY'') FROM DAYENDSLIPS WHERE SLPNO=' || V_ALLSLPNO || ' AND trunc(PRINTDATE,''DD'') < trunc(TO_DATE('''||V_GENDATE||''',''DD/MM/YYYY HH24MISS''),''dd'') AND ENABLED = 1' INTO LASTPRTDATE;
/*
    IF LASTPRTDATE IS NULL THEN
      EXECUTE IMMEDIATE ' SELECT TO_CHAR(LASTPRTDATE2,''DD/MM/YYYY'') FROM PATIENT_EXTRA WHERE PATNO = (SELECT PATNO FROM SLIP WHERE SLPNO = ''' || V_ALLSLPNO || ''')' INTO LASTPRTDATE ;
    END IF;
*/
  EXCEPTION
  WHEN OTHERS THEN
    LASTPRTDATE := NULL;
  END;

  SQLTMP0 :='SELECT IP.STNTDATE,
        IP.STNCDATE,
        IP.SLPNO,
        IP.STNBAMT,
        IP.STNNAMT,
        IP.DESCRIPTION,
        IP.QTY,
        IP.STNTYPE,
        IP.ITMTYPE,
        IP.STNRLVL,
        IP.CDESCCODE,
        DECODE(IP.CDESCCODE2,''CCP03'',IP.CDESCCODE2,DECODE((SELECT 1 FROM PACKAGE PKG WHERE PKG.PKGCODE = IP.CDESCCODE2),1,''PGP'',IP.CDESCCODE2)) AS CDESCCODE2
    FROM (';

  SQLTMP1 := '
    SELECT STNTDATE,
           DECODE(STNSTS,''C'',NHS_GET_SLIPTX_CANCEL_STNCDATE(slpno,stnseq,''' || V_GENDATE || ''') ,trunc(STNCDATE,''dd'')) STNCDATE,
           SLPNO,
           STNSEQ,
           STNBAMT,
           STNNAMT,
           DESCRIPTION,
           ITMCODE,
           QTY,
           STNTYPE,
           ITMTYPE,
           STNRLVL,
           CDESCCODE,
           CDESCCODE2,
           STNSTS
      FROM V_IPSTATEMENTWB';

  SQLWHERE1 :=') IP WHERE IP.ITMCODE != ''PAYME''
    AND IP.STNCDATE IS NOT NULL
    AND IP.SLPNO IN (''' || V_ALLSLPNO || ''')
    AND DECODE(IP.STNSTS,''C'',NHS_GET_SLIPTX_CANCEL_STNCDATE(slpno,stnseq,''' || V_GENDATE || ''') ,trunc(STNCDATE,''dd'')) <trunc(TO_DATE(''' || V_GENDATE || ' 000001'',''DD/MM/YYYY HH24MISS''),''dd'')';

  SQLWHERE2 := ' AND trunc(DECODE(IP.STNSTS,''C'',NHS_GET_SLIPTX_CANCEL_STNCDATE(slpno,stnseq,''' || V_GENDATE || ''') ,trunc(STNCDATE,''dd'')))>=trunc(TO_DATE(''' || LASTPRTDATE || ''',''DD/MM/YYYY''),''dd'')';

  IF V_GENDATE = LASTPRTDATE OR LASTPRTDATE IS NULL THEN
    SQLTMP := SQLTMP0||SQLTMP1||SQLWHERE1;
  ELSE
    SQLTMP := SQLTMP0||SQLTMP1||SQLWHERE1||SQLWHERE2;
  END IF;

  EXECUTE IMMEDIATE ' SELECT NVL(SUM(STNNAMT),0) FROM ( ' ||SQLTMP ||
                    ' AND STNTYPE=''R'' )' INTO TOTALREFUND;
  EXECUTE IMMEDIATE ' SELECT NVL(SUM(STNNAMT),0) FROM ( ' ||SQLTMP ||
                    ' AND STNTYPE IN (''D'',''O'',''X'') )' INTO TOTALCHARGE;

  SQLSTR := '
    SELECT TO_CHAR(STNTDATE, ''DD/MM/YYYY'') AS STNTDATE,SUM(AMOUNT), DESCRIPTION, DECODE(DECODE(STNTYPE,''S'',NULL,''R'',NULL,CDESCCODE2),''CCP03'',SUM(QTY)/COUNT(QTY),SUM(QTY)),
      ' ||TOTALREFUND ||' AS TOTALREFUND,' ||TOTALCHARGE ||' AS TOTALCHARGE,
      DECODE(STNTYPE,''S'',NULL,''R'',NULL,CDESCCODE) AS CDESCCODE,
      DECODE(STNTYPE,''S'',NULL,''R'',NULL,CDESCCODE2) AS CDESCCODE2,
      DECODE(STNRLVL, 4, 4, 7, 5,
                DECODE(STNTYPE, ''D'',
                      DECODE(MIN(ITMTYPE), ''D'', 1, ''H'', 2, ''S'', 3, 99),
                      ''R'', 10, ''P'', 9, ''C'', 8, ''S'', 7, ''I'', 6, ''O'', 6, ''X'', 6, 99)) AS ITEMORDER,
      STNTDATE TDATE
    FROM (
      SELECT TB.STNTDATE, (TB.STNBAMT) AS AMOUNT, TB.DESCRIPTION, DECODE(TB.CDESCCODE2,''CCP03'',TB.QTY,1) AS QTY, TB.STNTYPE,
             TB.ITMTYPE, TB.STNRLVL, TB.CDESCCODE, TB.CDESCCODE2
      FROM (  ' ||SQLTMP ||'
               AND IP.STNTYPE <> ''R''
               AND IP.STNRLVL NOT IN (3,6)
      ) TB

      UNION ALL

      SELECT TB2.STNTDATE STNTDATE, TB2.STNBAMT AS AMOUNT, TB2.DESCRIPTION, TB2.QTY QTY, TB2.STNTYPE,
             TB2.ITMTYPE, TB2.STNRLVL, TB2.CDESCCODE CDESCCODE, TB2.CDESCCODE CDESCCODE2
      FROM (  ' ||SQLTMP ||'
                AND IP.STNTYPE <> ''R''
                AND IP.STNRLVL IN (3,6)
      ) TB2

      UNION ALL

      SELECT TO_DATE(''31/12/9999'',''DD/MM/YYYY'') AS STNTDATE, (TB4.STNNAMT - TB4.STNBAMT) AMOUNT, ''DOCTOR DISCOUNT'' AS DESCRIPTION ,1 AS QTY, ''C'' AS STNTYPE,
             ''D'' AS ITMTYPE, 1 AS STNRLVL, '''' AS CDESCCODE,  '''' AS CDESCCODE2
      FROM (
            ' ||SQLTMP ||'
            AND STNTYPE IN (''D'', ''O'')
            AND ITMTYPE = ''D''
      ) TB4
      WHERE (TB4.STNNAMT - TB4.STNBAMT) <> 0

      UNION ALL

      SELECT TO_DATE(''31/12/9999'',''DD/MM/YYYY'') AS STNTDATE, (TB3.STNNAMT - TB3.STNBAMT) AS AMOUNT, ''HOSPITAL DISCOUNT'' AS DESCRIPTION ,1 AS QTY, ''C'' AS STNTYPE,
             ''H'' AS ITMTYPE, 1 AS STNRLVL, '''' AS CDESCCODE, '''' AS CDESCCODE2
      FROM (
            ' ||SQLTMP ||'
            AND STNTYPE IN (''D'', ''O'')
            AND ITMTYPE = ''H''
      ) TB3
      WHERE (TB3.STNNAMT - TB3.STNBAMT) <> 0

      UNION ALL

      SELECT  TO_DATE(''31/12/9999'',''DD/MM/YYYY'') AS STNTDATE, (TB5.STNNAMT - TB5.STNBAMT) AS AMOUNT, ''SPECIAL DISCOUNT'' AS DESCRIPTION ,1 AS QTY, ''C'' AS STNTYPE,
              ''S'' AS ITMTYPE, 1 AS STNRLVL, '''' AS CDESCCODE, '''' AS CDESCCODE2
      FROM (
            ' ||SQLTMP ||'
            AND STNTYPE IN (''D'', ''O'')
            AND ITMTYPE = ''S''
      ) TB5
      WHERE (TB5.STNNAMT - TB5.STNBAMT) <> 0

      UNION ALL

      SELECT TO_DATE(''31/12/9999'',''DD/MM/YYYY'') AS STNTDATE, (TB6.STNNAMT - TB6.STNBAMT) AMOUNT, ''OTHER DISCOUNT'' AS DESCRIPTION ,1 AS QTY, ''C'' AS STNTYPE,
             ''O'' AS ITMTYPE, 1 AS STNRLVL, '''' AS CDESCCODE, '''' AS CDESCCODE2
      FROM (
            ' ||SQLTMP ||'
            AND STNTYPE IN (''D'', ''O'')
            AND ITMTYPE = ''O''
      ) TB6
      WHERE (TB6.STNNAMT - TB6.STNBAMT) <> 0
    )
    GROUP BY STNTDATE, DESCRIPTION,  STNTYPE, STNRLVL, CDESCCODE, CDESCCODE2
    ORDER BY TDATE, ITEMORDER, case when CDESCCODE is null then 1 else 0 end, DESCRIPTION';

              DBMS_OUTPUT.PUT_LINE(SQLSTR) ;
  OPEN OUTCUR FOR SQLSTR;
  RETURN OUTCUR;
--RETURN SQLTMP;
END NHS_RPT_IPSTATEMENTWB_SUB1;
/
