create or replace FUNCTION "NHS_RPT_OPSTATEMENTAPP" (
	v_SLPNO IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
	v_Count NUMBER;
  v_TRXCount NUMBER;
BEGIN
	SELECT COUNT(1) INTO v_Count FROM sliptx WHERE stntype = 'P' AND slpno = v_SLPNO AND stnsts = 'N';
  SELECT COUNT(1) INTO v_TRXCount FROM SLIPTX WHERE SLPNO = v_SLPNO AND ITMCODE = 'RX007';
  
	OPEN OUTCUR FOR
		SELECT S.SLPNO AS SLPNO,
			P.PATNO,
			NVL(P.PATLFNAME, NVL(S.SLPFNAME, P.PATFNAME))
           ||' '||NVL(P.PATLGNAME, NVL(S.SLPGNAME, P.PATGNAME)) AS PATNAME, 
			P.PATCNAME,
			D.DOCFNAME || ' ' || D.DOCGNAME AS DOCNAME,
			D.DOCCNAME,
			v_Count,
      v_TRXCount as ISTELEC
		FROM  SLIP S, PATIENT P, DOCTOR D
		WHERE S.PATNO = P.PATNO(+)
		AND   S.DOCCODE = D.DOCCODE(+)
		AND   S.SLPNO = v_SLPNO;
	RETURN OUTCUR;
END NHS_RPT_OPSTATEMENTAPP;
/
