CREATE OR REPLACE FUNCTION NHS_RPT_RPTLBLB (
	v_REGID   VARCHAR2,
	v_PATNO   VARCHAR2,
	v_BKGID   VARCHAR2,
	v_REGTYPE VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
	REGMODE VARCHAR2(1 BYTE);
	v_REGDATE VARCHAR2(20 BYTE);
	v_DOCCODE VARCHAR2(20 BYTE);
	v_TITLE VARCHAR2(100 BYTE);
	v_TICKET NUMBER;
	v_SEQNO NUMBER;
	NOOFMSG NUMBER;
	v_ISCHECKASTERISK VARCHAR2(50 BYTE);
BEGIN
	v_SEQNO := 0;

	SELECT PARAM1 INTO v_ISCHECKASTERISK
	FROM SYSPARAM
	WHERE PARCDE = 'Chk*';

	--TITLE
	SELECT NVL(REGOPCAT, ''), TO_CHAR(REGDATE, 'DD/MM/YYYY'), DOCCODE
	INTO  REGMODE, v_REGDATE, v_DOCCODE
	FROM REG
	WHERE REGID = v_REGID;

	IF REGMODE = 'W' THEN
		v_TITLE := ' Walkin WK#';
	ELSIF REGMODE = 'P' THEN
		v_TITLE := ' Priority PT#';
	ELSE
		v_TITLE := '';
	END IF;

	IF REGMODE = 'W' OR REGMODE = 'P' THEN
		FOR REGLIST IN (SELECT REGID
			FROM v_REG
			WHERE REGDATE >= TO_DATE(v_REGDATE, 'DD/MM/YYYY')
			AND REGDATE < TO_DATE(v_REGDATE, 'DD/MM/YYYY') + 1
			AND DOCCODE = v_DOCCODE
			AND REGOPCAT = REGMODE
			AND REGSTS = 'N'
			ORDER BY REGID)
		LOOP
			IF v_SEQNO = 0 THEN
				v_SEQNO := v_SEQNO+1;
			END IF;
			IF REGLIST.REGID = v_REGID THEN
				EXIT;
			END IF;
			v_SEQNO := v_SEQNO+1;
		END LOOP;
	END IF;

	IF v_SEQNO = 0 THEN
		v_TITLE := '';
	ELSE
		v_TITLE := v_TITLE||v_SEQNO;
	END IF;

	SELECT DOCCODE,
		DECODE(v_REGTYPE, 'P', TO_CHAR(REGDATE, 'DD/MM/YYYY HH24:MI'),
		'W', TO_CHAR(REGDATE, 'DD/MM/YYYY HH24:MI'),
		TO_CHAR(REGDATE, 'HH24:MI')), TICKETNO
	INTO v_DOCCODE, v_REGDATE, v_TICKET
	FROM REG
	WHERE REGID = (
		SELECT REGID_C
		FROM PATIENT
		WHERE PATNO = v_PATNO
	);

	OPEN OUTCUR FOR
	SELECT DECODE(v_ISCHECKASTERISK, 'YES', P.STECODE||' *', P.STECODE),
		P.PATNO, P.PATFNAME||' '||P.PATGNAME, P.PATCNAME,
		TO_CHAR(P.PATBDATE, 'DD/MM/YYYY'), P.PATSEX,
		v_TITLE AS NOTEFIELD,
		(SELECT TO_CHAR(BKGSDATE, 'DD/MM/YYYY HH24:MI')
		FROM BOOKING
		WHERE BKGID = v_BKGID) AS APPT_TIME,
		TO_CHAR(v_REGDATE, 'DD/MM/YYYY HH24:MI'), v_TICKET,
		D.DOCFNAME||' '||D.DOCGNAME
	FROM PATIENT P, DOCTOR D
	WHERE D.DOCCODE = v_DOCCODE
	AND P.PATNO = v_PATNO;

	RETURN OUTCUR;
END NHS_RPT_RPTLBLB;
/
