CREATE OR REPLACE 
FUNCTION "NHS_RPT_PHYORDERFORM_MR_SUB1" (
	v_REGID IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;

BEGIN
	OPEN OUTCUR FOR
    SELECT DISTINCT IT.ITMCODE, IT.ITMNAME, GI.GUIDELINE, I.GLCCODE
		FROM REG R, GOVREG GR, GOVITEM GI, ITEMCHG I, DEPT D, PATIENT P, ITEM IT
		WHERE R.REGID = GR.REGID
		AND GI.GOVJOBCODE = GR.GOVJOBCODE
		AND GI.ITMCODE = I.ITMCODE
		AND D.DPTCODE = SUBSTR(I.GLCCODE, 0, 4)
		AND R.PATNO = P.PATNO
		AND IT.ITMCODE = I.ITMCODE
		AND GI.GOVSEX LIKE '%'||P.PATSEX||'%'
		AND I.ITCTYPE = 'O'
   		AND IT.ITMTYPE != 'D'
		AND R.REGID = v_REGID
		ORDER BY I.GLCCODE, IT.ITMCODE;
	RETURN OUTCUR;
END NHS_RPT_PHYORDERFORM_MR_SUB1;
/