CREATE OR REPLACE FUNCTION "NHS_RPT_DEPOSIT"(V_SLPNO IN VARCHAR2)
  RETURN TYPES.CURSOR_TYPE AS
  OUTCUR TYPES.CURSOR_TYPE;
BEGIN
  OPEN OUTCUR FOR
    SELECT S.SLPNO AS SLPNO,
           P.PATNO,
           DECODE(S.SLPFNAME,
                  NULL,
                  P.PATFNAME || ' ' || P.PATGNAME,
                  S.SLPFNAME || ' ' || S.SLPGNAME) AS PATNAME,
           P.PATCNAME,
           D.DOCFNAME || ' ' || D.DOCGNAME AS DOCNAME,
           D.DOCCNAME,
           TO_CHAR(SYSDATE, 'DD-MON-YYYY HH24:MI:SS','nls_date_language=ENGLISH') AS CURDATE
      FROM SLIP S, PATIENT P, DOCTOR D
     WHERE S.PATNO = P.PATNO(+)
       AND S.DOCCODE = D.DOCCODE(+)
       AND S.SLPNO = V_SLPNO;
  RETURN OUTCUR;
END NHS_RPT_DEPOSIT;
/
