CREATE OR REPLACE FUNCTION "NHS_RPT_RPTOTLOGLISTING" (
	v_OTLSDATE  IN VARCHAR2,
	v_OTLEDATE  IN VARCHAR2,
	v_OTLSTS    IN VARCHAR2,
	v_PATNO     IN VARCHAR2,
	v_OTPID     IN NUMBER,
	v_SLPTYPE   IN VARCHAR2,
	v_DOCCODE_S IN VARCHAR2,
	v_DOCCODE_A IN VARCHAR2,
	v_DOCCODE_E IN VARCHAR2,
	v_OR        IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
BEGIN
	OPEN OUTCUR FOR
		SELECT
			OL.OTLID,
			TO_CHAR(OL.OTLOSDATE,'dd/mm/yyyy hh24:mi') AS OTLOSDATE,
			TO_CHAR(OL.OTLOEDATE,'dd/mm/yyyy hh24:mi') AS OTLOEDATE,
			OL.PATNO,
			P.PATFNAME || ' ' || P.PATGNAME AS PATNAME,
			P.PATSEX AS PATSEX,
			IP.BEDCODE AS BEDNO,
			(SELECT OC.OTCDESC FROM OT_APP OA, OT_CODE OC WHERE OA.OTAID = OL.OTAID AND OA.OTCID_RM = OC.OTCID AND OC.OTCTYPE = 'RM' AND OC.OTCSTS = -1) AS OPRM,
			TO_CHAR(P.PATBDATE,'dd/mm/yyyy') AS PATDOB,
			DECODE(ol.OTLSPEC,-1,'YES',0,'NO') AS OTLSPEC,
			ST.OTCDESC AS PATTYPE,
			NHS_GET_GETSTRFROMRTB(OL.OTLID) AS OTLRMK,
			AM.OTCDESC AS OTL_AM_PRIM,
			'Primary - ' || OTP.OTPDESC||CHR(13)||CHR(10)||NHS_GET_RPTOTAPPLIST2NDOP(OL.OTLID) AS OTPNAME,
			''AS OTLANESMETH,
			'' AS OTLPROC,
			NHS_GET_RPTOTAPPLISTMEMFUNC(OL.OTLID,'M') AS OTMEMBER,
			NHS_GET_RPTOTAPPLISTMEMFUNC(OL.OTLID,'F') AS OTFUNCTION,
			DECODE(OLE.FEREQ,'Y','YES','NO') AS FEREQ,
			DECODE(OLE.FEREC,'Y','YES','NO') AS FEREC
		FROM  OT_LOG OL
		INNER JOIN PATIENT P ON OL.PATNO = P.PATNO
		INNER JOIN SLIP S ON OL.slpno = S.slpno
		LEFT JOIN REG R ON S.regid = R.regid
		LEFT JOIN INPAT IP ON R.INPID = IP.INPID
		INNER JOIN OT_PROC OTP ON OL.OTPID = OTP.OTPID
		INNER JOIN OT_CODE AM ON OL.otlanesmeth = AM.otcid
		INNER JOIN OT_CODE ST ON OL.otlid_st = ST.otcid
		LEFT JOIN OT_LOG_EXTRA OLE ON OL.OTLID = OLE.OTLID
		WHERE OL.OTLSTS <> 'X'
		AND  (TRUNC(OL.OTLDATE) >= TO_DATE(v_OTLSDATE, 'DD/MM/YYYY') Or v_OTLSDATE IS NULL)
		AND  (TRUNC(OL.OTLDATE) <= TO_DATE(v_OTLEDATE, 'DD/MM/YYYY') Or v_OTLEDATE IS NULL)
		AND  (OL.OTLSTS = v_OTLSTS OR v_OTLSTS IS NULL)
		AND  (P.PATNO = v_PATNO OR v_PATNO IS NULL)
		AND  (OL.OTPID = v_OTPID OR v_OTPID IS NULL)
		AND  (S.SLPTYPE = v_SLPTYPE OR v_SLPTYPE IS NULL)
		AND  (OL.DOCCODE_S = v_DOCCODE_S OR v_DOCCODE_S IS NULL)
		AND  (OL.DOCCODE_A = v_DOCCODE_A OR v_DOCCODE_A IS NULL)
		AND  (OL.DOCCODE_E = v_DOCCODE_E OR v_DOCCODE_E IS NULL)
		AND  (OL.OTLROOM = v_OR OR v_OR IS NULL)
		order by ol.OTLOSDATE DESC;

	RETURN OUTCUR;
END NHS_RPT_RPTOTLOGLISTING;
/
