create or replace FUNCTION "NHS_RPT_RPTARSTMT_XLS" (
  v_ArCode VARCHAR2,
  v_SteCode varchar2,
  V_DATESTART VARCHAR2,
  v_DateEnd VARCHAR2
)
  RETURN Types.cursor_type
AS
  OUTCUR TYPES.CURSOR_TYPE;
BEGIN
  OPEN OUTCUR FOR
    SELECT ARCCODE, ARCNAME, ARCADD1, ARCADD2, ARCADD3, ARCADD4,
           ARCCT, ARCTITLE, PTYPE, PNUM, FNAME, GNAME,
           REF, BDATE, ARTYPE, ORG, SETTLE, STENAME,
           SLPPLYNO, SLPVCHNO, SLPREMARK, BAL, MONTHGROUP, SORTDATE,
           (SELECT COUNT(ARCCODE)
            FROM (
            SELECT  AM.ARCCODE, AM.ARCNAME, AM.ARCADD1, AM.ARCADD2, AM.ARCADD3, AM.ARCADD4,
                    AM.ARCCT, AM.ARCTITLE, DECODE(SP.SLPTYPE, 'I', 'I', 'O', 'O', 'D', 'D', 'A') AS PTYPE,
                    AT.PATNO AS PNUM, NVL(PT.PATFNAME, SP.SLPFNAME) AS FNAME, NVL(PT.PATGNAME, SP.SLPGNAME) AS GNAME,
                    NVL(AT.SLPNO, AT.ATXDESC) AS REF, TO_CHAR(AT.ATXCDATE, 'DDMONYYYY', 'nls_date_language=ENGLISH') AS BDATE,
                    AT.ATXTTYPE AS ARTYPE,  AT.ATXAMT AS ORG, -AT.ATXSAMT AS SETTLE, AT.ATXID AS STENAME,
                    SP.SLPPLYNO, SP.SLPVCHNO, SP.SLPREMARK, (AT.ATXAMT - AT.ATXSAMT) AS BAL,
                    TO_CHAR(AT.ATXCDATE, 'YYYYMM') AS MONTHGROUP, AT.ATXCDATE SORTDATE,
                    (SELECT TO_CHAR(SE.SendBillDate, 'DDMONYYYY', 'nls_date_language=ENGLISH') FROM Slip_Extra SE WHERE SP.SLPNO = SE.SLPNO) AS SendBillDate, SP.Patrefno
            FROM    ARCODE AM, ARTX AT, SLIP SP, SITE SC, PATIENT PT
            WHERE   (AM.ARCCODE= V_ARCODE OR V_ARCODE IS NULL)
            AND     AM.STECODE = V_STECODE
            AND     (V_DATESTART IS NULL OR AT.ATXCDATE >= TO_DATE(V_DATESTART, 'DD/MM/YYYY'))
            AND     (V_DATEEND IS NULL OR AT.ATXCDATE < TO_DATE(V_DATEEND, 'DD/MM/YYYY') + 1)
            AND     AT.ARCCODE = AM.ARCCODE
            AND     AT.ATXSTS = 'N'
            AND     AT.ATXAMT - AT.ATXSAMT <> 0
            AND     AM.STECODE = SC.STECODE
            AND     AT.PATNO = PT.PATNO(+)
            AND     AT.SLPNO = SP.SLPNO(+)
            UNION ALL
            SELECT  AM.ARCCODE, AM.ARCNAME, AM.ARCADD1, AM.ARCADD2, AM.ARCADD3, AM.ARCADD4,
                    AM.ARCCT, AM.ARCTITLE, 'A' AS PTYPE, '' AS PNUM, '' AS FNAME, '' AS GNAME,
                    AP.ARPDESC AS REF, TO_CHAR(AP.ARPCDATE, 'DDMONYYYY', 'nls_date_language=ENGLISH') AS BDATE,
                    AP.ARPTYPE AS ARTYPE, AP.ARPOAMT AS ORG, AP.ARPAAMT AS SETTLE, AP.ARPID AS STENAME,
                    '' AS SLPPLYNO, '' AS SLPVCHNO, '' AS SLPREMARK, (AP.ARPOAMT + AP.ARPAAMT) AS BAL,
                    TO_CHAR(AP.ARPCDATE, 'YYYYMM') AS MonthGroup, AP.ARPCDATE SORTDATE, '' AS SendBillDate, '' AS Patrefno
            FROM    ARCODE AM, ARPTX AP, SITE SC
            WHERE   (AM.ARCCODE= V_ARCODE OR V_ARCODE IS NULL)
            AND     AM.STECODE = V_STECODE
            AND     (V_DATESTART IS NULL OR AP.ARPCDATE >= TO_DATE(V_DATESTART, 'DD/MM/YYYY'))
            AND     (V_DATEEND IS NULL OR AP.ARPCDATE < TO_DATE(V_DATEEND, 'DD/MM/YYYY') + 1)
            AND     AP.ARCCODE = AM.ARCCODE
            AND     AP.ARPSTS = 'N'
            AND     AP.ARPOAMT + AP.ARPAAMT <> 0
            AND     AM.STECODE = SC.STECODE)
            ) AS ROW_COUNT,
            SendBillDate, Patrefno, SLPDATE, REGDATE, INPDDATE
    FROM (
    SELECT  AM.ARCCODE, AM.ARCNAME, AM.ARCADD1, AM.ARCADD2, AM.ARCADD3, AM.ARCADD4,
            AM.ARCCT, AM.ARCTITLE, DECODE(SP.SLPTYPE, 'I', 'I', 'O', 'O', 'D', 'D', 'A') AS PTYPE,
            AT.PATNO AS PNUM, NVL(PT.PATFNAME, SP.SLPFNAME) AS FNAME, NVL(PT.PATGNAME, SP.SLPGNAME) AS GNAME,
            NVL(AT.SLPNO, AT.ATXDESC) AS REF, TO_CHAR(AT.ATXCDATE, 'DDMONYYYY', 'nls_date_language=ENGLISH') AS BDATE,
            AT.ATXTTYPE AS ARTYPE,  AT.ATXAMT AS ORG, -AT.ATXSAMT AS SETTLE, AT.ATXID AS STENAME,
            SP.SLPPLYNO, SP.SLPVCHNO, SP.SLPREMARK, (AT.ATXAMT - AT.ATXSAMT) AS BAL,
            TO_CHAR(AT.ATXCDATE, 'YYYYMM') AS MONTHGROUP, AT.ATXCDATE SORTDATE,
            (SELECT TO_CHAR(SE.SendBillDate, 'DDMONYYYY', 'nls_date_language=ENGLISH') FROM Slip_Extra SE WHERE SP.SLPNO = SE.SLPNO) AS SendBillDate, SP.Patrefno,
            (SELECT TO_CHAR(SE.SLPDATE, 'DDMONYYYY', 'nls_date_language=ENGLISH') FROM Slip_Extra SE WHERE SP.SLPNO = SE.SLPNO) AS SLPDATE,
            DECODE(SP.SLPTYPE,'I',(SELECT TO_CHAR(R.REGDATE, 'DDMONYYYY', 'nls_date_language=ENGLISH') FROM INPAT IP, REG R WHERE R.INPID = IP.INPID AND R.PATNO = AT.PATNO AND R.SLPNO = AT.SLPNO),
            (SELECT TO_CHAR(R.REGDATE, 'DDMONYYYY', 'nls_date_language=ENGLISH') FROM REG R WHERE R.PATNO = AT.PATNO AND R.SLPNO = AT.SLPNO)) AS REGDATE,
            (SELECT TO_CHAR(IP.INPDDATE, 'DDMONYYYY', 'nls_date_language=ENGLISH') FROM INPAT IP, REG R WHERE R.INPID = IP.INPID AND R.PATNO = AT.PATNO AND R.SLPNO = AT.SLPNO) AS INPDDATE            
    FROM    ARCODE AM, ARTX AT, SLIP SP, SITE SC, PATIENT PT
    WHERE   (AM.ARCCODE= V_ARCODE OR V_ARCODE IS NULL)
    AND     AM.STECODE = V_STECODE
    AND     (V_DATESTART IS NULL OR AT.ATXCDATE >= TO_DATE(V_DATESTART, 'DD/MM/YYYY'))
    AND     (V_DATEEND IS NULL OR AT.ATXCDATE < TO_DATE(V_DATEEND, 'DD/MM/YYYY') + 1)
    AND     AT.ARCCODE = AM.ARCCODE
    AND     AT.ATXSTS = 'N'
    AND     AT.ATXAMT - AT.ATXSAMT <> 0
    AND     AM.STECODE = SC.STECODE
    AND     AT.PATNO = PT.PATNO(+)
    AND     AT.SLPNO = SP.SLPNO(+)
    UNION ALL
    SELECT  AM.ARCCODE, AM.ARCNAME, AM.ARCADD1, AM.ARCADD2, AM.ARCADD3, AM.ARCADD4,
            AM.ARCCT, AM.ARCTITLE, 'A' AS PTYPE, '' AS PNUM, '' AS FNAME, '' AS GNAME,
            AP.ARPDESC AS REF, TO_CHAR(AP.ARPCDATE, 'DDMONYYYY', 'nls_date_language=ENGLISH') AS BDATE,
            AP.ARPTYPE AS ARTYPE, AP.ARPOAMT AS ORG, AP.ARPAAMT AS SETTLE, AP.ARPID AS STENAME,
            '' AS SLPPLYNO, '' AS SLPVCHNO, '' AS SLPREMARK, (AP.ARPOAMT + AP.ARPAAMT) AS BAL,
            TO_CHAR(AP.ARPCDATE, 'YYYYMM') AS MonthGroup, AP.ARPCDATE SORTDATE, '' AS SendBillDate, '' AS Patrefno,
            '' AS SLPDATE, '' AS REGDATE, '' AS INPDDATE
    FROM    ARCODE AM, ARPTX AP, SITE SC
    WHERE   (AM.ARCCODE= V_ARCODE OR V_ARCODE IS NULL)
    AND     AM.STECODE = V_STECODE
    AND     (V_DATESTART IS NULL OR AP.ARPCDATE >= TO_DATE(V_DATESTART, 'DD/MM/YYYY'))
    AND     (V_DATEEND IS NULL OR AP.ARPCDATE < TO_DATE(V_DATEEND, 'DD/MM/YYYY') + 1)
    AND     AP.ARCCODE = AM.ARCCODE
    AND     AP.ARPSTS = 'N'
    AND     AP.ARPOAMT + AP.ARPAAMT <> 0
    AND     AM.STECODE = SC.STECODE)
    ORDER BY ARCCODE, PTYPE, SORTDATE;

RETURN OUTCUR;
END NHS_RPT_RPTARSTMT_XLS;
/