create or replace FUNCTION "NHS_GET_DAYENDCOVERLTRSLIP" (
	V_PRINTDATE IN VARCHAR2,
  v_PATNO IN VARCHAR2
)
	RETURN VARCHAR2
AS
	OUTCUR TYPES.CURSOR_TYPE;
  V_SLPNO SLIP.SLPNO%TYPE;
	v_ALLSLPNO VARCHAR2(100);

  CURSOR C_SLPNO IS
  SELECT SLPNO
  FROM DAYENDSLIPS
  WHERE TO_CHAR(PRINTDATE,'DD/MM/YYYY') = V_PRINTDATE
  AND PATNO = v_PATNO
  ORDER BY SLPNO ASC;
BEGIN
		OPEN C_SLPNO;
		LOOP
		FETCH C_SLPNO INTO v_SLPNO;
		EXIT WHEN C_SLPNO%NOTFOUND;
      IF V_ALLSLPNO IS NOT NULL THEN
        V_ALLSLPNO := V_ALLSLPNO||CHR(13)||CHR(10)||V_SLPNO;
        DBMS_OUTPUT.PUT_LINE('[V_ALLSLPNO]:'||V_ALLSLPNO);
      ELSE
        DBMS_OUTPUT.PUT_LINE('[v_SLPNO]:'||v_SLPNO);
        v_ALLSLPNO := v_SLPNO;
      END IF;
		END LOOP;
    CLOSE C_SLPNO;
  RETURN v_ALLSLPNO;
END NHS_GET_DAYENDCOVERLTRSLIP;
/