-- FOR REPORT RPTOTLOGLISTING
create or replace
FUNCTION "NHS_GET_RPTOTAPPLISTMEMFUNC"
(
  V_OTLID VARCHAR2,
  V_TYPE VARCHAR2
)
  RETURN VARCHAR2
IS
V_RESULTALL VARCHAR2(1000);
V_DR_PA VARCHAR2(30);
V_DR_SA VARCHAR2(30);
V_DR_E VARCHAR2(30);
V_DR_PS VARCHAR2(30);
V_DR_SS VARCHAR2(30);
V_FUNC_PA VARCHAR2(30);
V_FUNC_SA VARCHAR2(30);
V_FUNC_E VARCHAR2(30);
V_FUNC_PS VARCHAR2(30);
V_FUNC_SS VARCHAR2(30);
V_TEAM_NAME VARCHAR2(30);
V_TEAM_FUNC VARCHAR2(30);

V_TEAM_NAME_ALL VARCHAR2(300);
V_TEAM_FUNC_ALL VARCHAR2(300);



CURSOR c_getOTPTeam IS
SELECT SF.OTCDESC AS STAFF,FN.OTCDESC AS FUNCTION 
from OT_LOG ol, OT_LOG_TEAM olt, OT_CODE sf, OT_CODE fn
WHERE OL.OTLID=OLT.OTLID 
AND OLT.OTCID_SF=SF.OTCID 
and olt.otcid_fn=fn.otcid
AND OL.OTLID = V_OTLID
AND SF.OTCTYPE='SF' 
AND FN.OTCTYPE='FN';
  
BEGIN
  BEGIN
    SELECT 
    DS.DOCFNAME || ' ' || DS.DOCGNAME AS DR_S, 
    DECODE(OL.DOCCODE_S,NULL,'','PRIMARY SURGEON') AS FUNC_S,  
    DA.DOCFNAME || ' ' || DA.DOCGNAME AS DR_A, 
    decode(ol.doccode_a,null,'','PRIMARY ANESTHETIST') as func_a,
    DE.DOCFNAME || ' ' || DE.DOCGNAME AS DR_E, 
    DECODE(OL.DOCCODE_E,NULL,'','ENDOSCOPIST') AS FUNC_E
    INTO V_DR_PS, V_FUNC_PS, V_DR_PA, V_FUNC_PA, V_dr_E, V_FUNC_E
    from ot_log ol, doctor da, doctor de, doctor ds
    WHERE OL.DOCCODE_A = DA.DOCCODE(+) 
    AND OL.DOCCODE_E = DE.DOCCODE(+) 
    AND OL.DOCCODE_S = DS.DOCCODE(+)
    AND OL.OTLID = V_OTLID;
  EXCEPTION
  WHEN OTHERS THEN
    V_DR_PS := NULL;
    V_FUNC_PS := NULL;
    V_DR_PA := NULL;
    V_FUNC_PA := NULL;
    V_DR_E := NULL;
    V_FUNC_E := NULL;
  END;
  
  BEGIN  
    SELECT DS.DOCFNAME || ' ' || DS.DOCGNAME AS DR_S, DECODE(OLS.DOCCODE,NULL,'','SECONDARY SURGEON') AS FUNC_S
    INTO V_DR_SS, V_FUNC_SS
    FROM OT_LOG_SURG OLS, DOCTOR DS
    WHERE OLS.DOCCODE=DS.DOCCODE 
    AND OLS.OTLID = V_OTLID;
  EXCEPTION
  WHEN OTHERS THEN
    V_DR_SS := NULL; 
    V_FUNC_SS := NULL;
  END;  
  
  BEGIN  
    SELECT DA.DOCFNAME || ' ' || DA.DOCGNAME AS DR_A, DECODE(OLA.DOCCODE,NULL,'','SECONDARY ANESTHETIST') AS FUNC_A
    INTO V_DR_SA, V_FUNC_SA
    FROM OT_LOG_ANES OLA, DOCTOR DA
    WHERE OLA.DOCCODE=DA.DOCCODE 
    AND OLA.OTLID = V_OTLID;
  EXCEPTION
  WHEN OTHERS THEN
    V_DR_SA := NULL; 
    V_FUNC_SA := NULL;
  END; 

  OPEN c_getOTPTeam;
  LOOP
  FETCH C_GETOTPTEAM INTO V_TEAM_NAME, V_TEAM_FUNC;
  EXIT WHEN C_GETOTPTEAM%NOTFOUND;
    IF V_TEAM_NAME_ALL IS NULL THEN
      V_TEAM_NAME_ALL := V_TEAM_NAME;
    ELSE
      IF V_TEAM_NAME IS NOT NULL THEN
        V_TEAM_NAME_ALL := V_TEAM_NAME_ALL||CHR(13)||CHR(10)||V_TEAM_NAME;  
      END IF;
    END IF;
    
    IF V_TEAM_FUNC_ALL IS NULL THEN
      V_TEAM_FUNC_ALL := V_TEAM_FUNC;
    ELSE
      IF V_TEAM_NAME IS NOT NULL THEN
        V_TEAM_FUNC_ALL := V_TEAM_FUNC_ALL||CHR(13)||CHR(10)||V_TEAM_FUNC;  
      END IF;
    END IF;
  END LOOP;
  CLOSE C_GETOTPTEAM;

  IF V_TYPE = 'M' THEN      -- MEMBER 
  -- PRIMARY SURGEON
    IF V_DR_PS IS NOT NULL THEN
      V_RESULTALL := V_DR_PS;
    END IF;
      
  -- SECONDARY SURGEON       
      
    IF V_RESULTALL IS NOT NULL AND V_DR_SS IS NOT NULL THEN
      V_RESULTALL := V_RESULTALL||CHR(13)||CHR(10)||V_DR_SS;  
    END IF;
    
  -- PRIMARY ANESTHETIST      
    
    IF V_RESULTALL IS NOT NULL AND V_DR_PA IS NOT NULL THEN
      V_RESULTALL := V_RESULTALL||CHR(13)||CHR(10)||V_DR_PA;  
    END IF;      
    
  -- SECONDARY ANESTHETIST      
    
    IF V_RESULTALL IS NOT NULL AND V_DR_SA IS NOT NULL THEN
      V_RESULTALL := V_RESULTALL||CHR(13)||CHR(10)||V_DR_SA;
    END IF;            

  -- TEAM

    IF V_RESULTALL IS NOT NULL AND V_TEAM_NAME_ALL IS NOT NULL THEN
      V_RESULTALL := V_RESULTALL||CHR(13)||CHR(10)||V_TEAM_NAME_ALL;  
    END IF;
      
  ELSIF V_TYPE = 'F' THEN -- FUNCTION
  -- PRIMARY SURGEON
    IF V_FUNC_PS IS NOT NULL THEN
      V_RESULTALL := V_FUNC_PS;
    END IF;
    
  -- SECONDARY SURGEON       
    
    IF V_RESULTALL IS NOT NULL AND V_FUNC_SS IS NOT NULL THEN
      V_RESULTALL := V_RESULTALL||CHR(13)||CHR(10)||V_FUNC_SS;  
    END IF;
    
  -- PRIMARY ANESTHETIST      
    
    IF V_RESULTALL IS NOT NULL AND V_FUNC_PA IS NOT NULL THEN
      V_RESULTALL := V_RESULTALL||CHR(13)||CHR(10)||V_FUNC_PA;  
    END IF;      
    
  -- SECONDARY ANESTHETIST      
    
    IF V_RESULTALL IS NOT NULL AND V_FUNC_SA IS NOT NULL THEN
      V_RESULTALL := V_RESULTALL||CHR(13)||CHR(10)||V_FUNC_SA;  
    END IF;            

  -- TEAM

    IF V_RESULTALL IS NOT NULL AND V_TEAM_FUNC_ALL IS NOT NULL THEN
      V_RESULTALL := V_RESULTALL||CHR(13)||CHR(10)||V_TEAM_FUNC_ALL;  
    END IF;
  END IF;

  RETURN V_RESULTALL;
END NHS_GET_RPTOTAPPLISTMEMFUNC;
/