create or replace FUNCTION "NHS_RPT_PHYORDERFORM" (
	v_PKGCODE IN VARCHAR2
)
RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;

BEGIN
	OPEN OUTCUR FOR
    SELECT DISTINCT D.DPTCODE, DM.DPTNAME, IT.ITMCODE, IT.ITMNAME, T.NO AS NUM, IT.DSCCODE, DV.DSCDESC
        FROM ITEMCHG I, ITEM IT, DEPT D, DPSERV DV, 
            ( SELECT D.DPTCODE, IT.DSCCODE, COUNT (D.DPTCODE) AS NO
              FROM ITEMCHG I, ITEM IT, DEPT D
              WHERE IT.ITMCODE = I.ITMCODE
              AND D.DPTCODE = SUBSTR(I.GLCCODE, 0, 4)
              AND I.PKGCODE IN (
                SELECT REGEXP_SUBSTR(v_PKGCODE,'[^,]+', 1, LEVEL) FROM DUAL
                CONNECT BY REGEXP_SUBSTR(v_PKGCODE,'[^,]+', 1, LEVEL) IS NOT NULL
              )
              AND I.ITCTYPE = 'O'
              AND IT.ITMTYPE != 'D'
              GROUP BY D.DPTCODE, IT.DSCCODE
              ORDER BY D.DPTCODE, IT.DSCCODE) T,
            ( SELECT ID AS DPTCODE, LISTAGG(DESCRIPTION, '<br>') WITHIN GROUP (ORDER BY LANGUAGE DESC) AS DPTNAME 
              FROM DESCRIPTION_MAPPING 
              WHERE TYPE = 'DEPARTMENT_NAME' 
              GROUP BY ID) DM
        WHERE IT.ITMCODE = I.ITMCODE
        AND T.DPTCODE = D.DPTCODE
        AND T.DSCCODE = IT.DSCCODE
        AND IT.DSCCODE = DV.DSCCODE
        AND D.DPTCODE = DM.DPTCODE
        AND D.DPTCODE = SUBSTR(I.GLCCODE, 0, 4)
        AND I.PKGCODE IN (
          SELECT REGEXP_SUBSTR(v_PKGCODE,'[^,]+', 1, LEVEL) FROM DUAL
          CONNECT BY REGEXP_SUBSTR(v_PKGCODE,'[^,]+', 1, LEVEL) IS NOT NULL
        )
        AND I.ITCTYPE = 'O'
        AND IT.ITMTYPE != 'D'
    UNION ALL 
    SELECT DISTINCT D.DPTCODE, DM.DPTNAME, IT.ITMCODE, IT.ITMNAME, T.NO AS NUM, IT.DSCCODE || '1' AS DSCCODE, DV.DSCDESC
        FROM ITEMCHG I, ITEM IT, DEPT D, DPSERV DV, 
            ( SELECT D.DPTCODE, IT.DSCCODE, COUNT (D.DPTCODE) AS NO
              FROM ITEMCHG I, ITEM IT, DEPT D
              WHERE IT.ITMCODE = I.ITMCODE
              AND D.DPTCODE = SUBSTR(I.GLCCODE, 0, 4)
              AND I.PKGCODE IN (
                SELECT REGEXP_SUBSTR(v_PKGCODE,'[^,]+', 1, LEVEL) FROM DUAL
                CONNECT BY REGEXP_SUBSTR(v_PKGCODE,'[^,]+', 1, LEVEL) IS NOT NULL
              )
              AND I.ITCTYPE = 'O'
              AND IT.ITMTYPE != 'D'
              GROUP BY D.DPTCODE, IT.DSCCODE
              ORDER BY D.DPTCODE, IT.DSCCODE) T,
            ( SELECT ID AS DPTCODE, LISTAGG(DESCRIPTION, '<br>') WITHIN GROUP (ORDER BY LANGUAGE DESC) AS DPTNAME 
              FROM DESCRIPTION_MAPPING 
              WHERE TYPE = 'DEPARTMENT_NAME' 
              GROUP BY ID) DM
        WHERE IT.ITMCODE = I.ITMCODE
        AND T.DPTCODE = D.DPTCODE
        AND T.DSCCODE = IT.DSCCODE
        AND IT.DSCCODE = DV.DSCCODE
        AND D.DPTCODE = DM.DPTCODE
        AND D.DPTCODE = SUBSTR(I.GLCCODE, 0, 4)
        AND I.PKGCODE IN (
          SELECT REGEXP_SUBSTR(v_PKGCODE,'[^,]+', 1, LEVEL) FROM DUAL
          CONNECT BY REGEXP_SUBSTR(v_PKGCODE,'[^,]+', 1, LEVEL) IS NOT NULL
        )
        AND I.ITCTYPE = 'O'
        AND IT.ITMTYPE != 'D'
        AND IT.DSCCODE = 'LB'
    UNION ALL 
    SELECT DISTINCT D.DPTCODE, DM.DPTNAME, IT.ITMCODE, IT.ITMNAME, T.NO AS NUM, IT.DSCCODE || '2' AS DSCCODE, DV.DSCDESC
        FROM ITEMCHG I, ITEM IT, DEPT D, DPSERV DV, 
            ( SELECT D.DPTCODE, IT.DSCCODE, COUNT (D.DPTCODE) AS NO
              FROM ITEMCHG I, ITEM IT, DEPT D
              WHERE IT.ITMCODE = I.ITMCODE
              AND D.DPTCODE = SUBSTR(I.GLCCODE, 0, 4)
              AND I.PKGCODE IN (
                SELECT REGEXP_SUBSTR(v_PKGCODE,'[^,]+', 1, LEVEL) FROM DUAL
                CONNECT BY REGEXP_SUBSTR(v_PKGCODE,'[^,]+', 1, LEVEL) IS NOT NULL
              )
              AND I.ITCTYPE = 'O'
              AND IT.ITMTYPE != 'D'
              GROUP BY D.DPTCODE, IT.DSCCODE
              ORDER BY D.DPTCODE, IT.DSCCODE) T,
            ( SELECT ID AS DPTCODE, LISTAGG(DESCRIPTION, '<br>') WITHIN GROUP (ORDER BY LANGUAGE DESC) AS DPTNAME 
              FROM DESCRIPTION_MAPPING 
              WHERE TYPE = 'DEPARTMENT_NAME' 
              GROUP BY ID) DM
        WHERE IT.ITMCODE = I.ITMCODE
        AND T.DPTCODE = D.DPTCODE
        AND T.DSCCODE = IT.DSCCODE
        AND IT.DSCCODE = DV.DSCCODE
        AND D.DPTCODE = DM.DPTCODE
        AND D.DPTCODE = SUBSTR(I.GLCCODE, 0, 4)
        AND I.PKGCODE IN (
          SELECT REGEXP_SUBSTR(v_PKGCODE,'[^,]+', 1, LEVEL) FROM DUAL
          CONNECT BY REGEXP_SUBSTR(v_PKGCODE,'[^,]+', 1, LEVEL) IS NOT NULL
        )
        AND I.ITCTYPE = 'O'
        AND IT.ITMTYPE != 'D'
        AND IT.DSCCODE = 'LB'
    ORDER BY DPTCODE, DSCCODE, ITMCODE;
  RETURN OUTCUR;
END NHS_RPT_PHYORDERFORM;