create or replace
FUNCTION "NHS_RPT_OPSTATEMENT_SUB"(V_SLPNO IN VARCHAR2)
  RETURN TYPES.CURSOR_TYPE AS
  OUTCUR TYPES.CURSOR_TYPE;
  SQLTMP VARCHAR2(20000);
  SQLSTR VARCHAR2(32767);
BEGIN
  SQLTMP := '
    SELECT STNTDATE, STNBAMT, STNNAMT, DESCRIPTION, QTY, DSCCODE, ITMFLAG, 
            CDESCCODE, STNTYPE, ITMTYPE, STNRLVL, DPTCODE, PKGCODE 
        FROM SLIPTX_STATEMENT
        WHERE SLPNO IN (' || V_SLPNO ||') ' ;

  SQLSTR := '
    SELECT UPPER(TO_CHAR(STNTDATE, ''DD Mon YYYY'',''NLS_DATE_LANGUAGE=AMERICAN'')) AS STNTDATE,AMOUNT,DESCRIPTION,QTY,
      ITMFLAG, DECODE(STNTYPE,''S'',NULL,''R'',NULL,CDESCCODE) AS CDESCCODE,
      DECODE(STNTYPE, ''D'', 
              DECODE(PKGCODE, NULL, 
                  DECODE(ITMTYPE, ''D'', 
                    DECODE(DPTCODE, NULL, 1, 0), NULL, 5, DECODE(DPTCODE, NULL, 3, 4)),
                  2),
              ''C'', 6, ''I'', 7, ''O'', 7, ''X'', 7, ''S'', 8, ''R'', 9, ''P'', 10, 99) AS ITEMORDER,
      STNTDATE TDATE
      FROM (
            SELECT TB.STNTDATE STNTDATE, SUM(TB.STNBAMT) AMOUNT, TB.DESCRIPTION,1 AS QTY,
            MAX(TB.STNTYPE) STNTYPE, MAX(TB.STNRLVL) STNRLVL, MAX(TB.ITMTYPE) ITMTYPE,
              TB.CDESCCODE CDESCCODE, TB.ITMFLAG ITMFLAG, DECODE(PKGCODE, NULL, DPTCODE, NULL) DPTCODE, PKGCODE
        FROM (  ' ||SQLTMP ||'
                 --AND ST.STNTYPE <> ''R''
                 AND STNRLVL NOT IN (3,6)) TB
        GROUP BY TB.STNTDATE, TB.DESCRIPTION, 1, TB.CDESCCODE, TB.ITMFLAG, DECODE(PKGCODE, NULL, DPTCODE, NULL), PKGCODE
      UNION ALL
      SELECT TB2.STNTDATE STNTDATE, TB2.STNBAMT AMOUNT, TB2.DESCRIPTION, TB2.QTY QTY, TB2.STNTYPE, TB2.STNRLVL,
              TB2.ITMTYPE, TB2.CDESCCODE CDESCCODE, TB2.ITMFLAG, DPTCODE, PKGCODE
        FROM (  ' ||SQLTMP ||'
                 --AND ST.STNTYPE <> ''R''
                 AND STNRLVL IN (3,6)) TB2

      UNION ALL

      SELECT STNTDATE, SUM(AMOUNT) AMOUNT, DESCRIPTION, QTY, STNTYPE, STNRLVL, ITMTYPE, CDESCCODE, ITMFLAG, DPTCODE, PKGCODE
      FROM (
              SELECT SUM(TB4.STNNAMT - TB4.STNBAMT) AMOUNT, ''DOCTOR DISCOUNT'' AS DESCRIPTION ,1 AS QTY,
                      ''C'' AS STNTYPE,''D'' AS ITMTYPE, 1 AS STNRLVL, '''' AS CDESCCODE,
                      MAX(TB4.STNTDATE) STNTDATE, ''B'' AS ITMFLAG, DPTCODE, PKGCODE
              FROM (
                    ' ||SQLTMP ||'
              ) TB4
              WHERE STNTYPE IN (''D'', ''O'')
              AND ITMTYPE = ''D''
              GROUP BY DESCRIPTION , STNTYPE, STNRLVL, ITMTYPE, ITMFLAG, DPTCODE, PKGCODE
      )
      WHERE AMOUNT <> 0
      GROUP BY  STNTDATE, DESCRIPTION , STNTYPE, STNRLVL, STNRLVL, ITMTYPE, CDESCCODE, ITMFLAG, DPTCODE, PKGCODE

      UNION ALL

      SELECT STNTDATE, SUM(AMOUNT) AMOUNT, DESCRIPTION, QTY, STNTYPE, STNRLVL, ITMTYPE, CDESCCODE, ITMFLAG, DPTCODE, PKGCODE
      FROM (
              SELECT SUM(TB3.STNNAMT - TB3.STNBAMT) AMOUNT, ''HOSPITAL DISCOUNT'' AS DESCRIPTION ,1 AS QTY,
                      ''C'' AS STNTYPE,''H'' AS ITMTYPE, 1 AS STNRLVL, '''' AS CDESCCODE,
                      MAX(TB3.STNTDATE) STNTDATE, ''B'' AS ITMFLAG, ''HD'' AS DPTCODE, ''HD'' AS PKGCODE
              FROM (
                    ' ||SQLTMP ||'
              ) TB3
              WHERE STNTYPE IN (''D'', ''O'')
              AND ITMTYPE = ''H''
              GROUP BY DESCRIPTION , STNTYPE, STNRLVL, ITMTYPE, ITMFLAG, DPTCODE, PKGCODE
      )
      WHERE AMOUNT <> 0
      GROUP BY  STNTDATE, DESCRIPTION , STNTYPE, STNRLVL, STNRLVL, ITMTYPE, CDESCCODE, ITMFLAG, DPTCODE, PKGCODE

      UNION ALL

      SELECT STNTDATE, SUM(AMOUNT) AMOUNT, DESCRIPTION, QTY, STNTYPE, STNRLVL, ITMTYPE, CDESCCODE, ITMFLAG, DPTCODE, PKGCODE
      FROM (
              SELECT SUM(TB5.STNNAMT - TB5.STNBAMT) AMOUNT, ''SPECIAL DISCOUNT'' AS DESCRIPTION ,1 AS QTY,
                      ''C'' AS STNTYPE,''S'' AS ITMTYPE, 1 AS STNRLVL, '''' AS CDESCCODE,
                      MAX(TB5.STNTDATE) STNTDATE, ''B'' AS ITMFLAG, ''SD'' AS DPTCODE, ''SD'' AS PKGCODE
              FROM (
                    ' ||SQLTMP ||'
              ) TB5
              WHERE STNTYPE IN (''D'', ''O'')
              AND ITMTYPE = ''S''
              GROUP BY DESCRIPTION , STNTYPE, STNRLVL, ITMTYPE, ITMFLAG, DPTCODE, PKGCODE
      )
      WHERE AMOUNT <> 0
      GROUP BY  STNTDATE, DESCRIPTION , STNTYPE, STNRLVL, STNRLVL, ITMTYPE, CDESCCODE, ITMFLAG, DPTCODE, PKGCODE

      UNION ALL

      SELECT STNTDATE, SUM(AMOUNT) AMOUNT, DESCRIPTION, QTY, STNTYPE, STNRLVL, ITMTYPE, CDESCCODE, ITMFLAG, DPTCODE, PKGCODE
      FROM (
              SELECT SUM(TB6.STNNAMT - TB6.STNBAMT) AMOUNT, ''OTHER DISCOUNT'' AS DESCRIPTION ,1 AS QTY,
                      ''C'' AS STNTYPE,''O'' AS ITMTYPE, 1 AS STNRLVL, '''' AS CDESCCODE,
                      MAX(TB6.STNTDATE) STNTDATE, ''B'' AS ITMFLAG, ''OD'' AS DPTCODE, ''OD'' AS PKGCODE
              FROM (
                    ' ||SQLTMP ||'
              ) TB6
              WHERE STNTYPE IN (''D'', ''O'')
              AND ITMTYPE = ''O''
              GROUP BY DESCRIPTION , STNTYPE, STNRLVL, ITMTYPE, ITMFLAG, DPTCODE, PKGCODE
      )
      WHERE AMOUNT <> 0
      GROUP BY  STNTDATE, DESCRIPTION , STNTYPE, STNRLVL, STNRLVL, ITMTYPE, CDESCCODE, ITMFLAG, DPTCODE, PKGCODE

    )
    ORDER BY ITMFLAG, TDATE, ITEMORDER, DESCRIPTION';
              dbms_output.put_line(SQLSTR) ;
  OPEN OUTCUR FOR SQLSTR;
  RETURN OUTCUR;
END NHS_RPT_OPSTATEMENT_SUB;
/