CREATE OR REPLACE FUNCTION "NHS_RPT_DAYCASERECEIPT" (
	V_SLPNO IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
BEGIN
	OPEN OUTCUR FOR
		SELECT NVL(S.SLPFNAME, P.PATFNAME) || ' ' ||
			NVL(S.SLPGNAME, P.PATGNAME) AS PATNAME,
			P.PATCNAME,
			S.SLPNO,
			P.PATNO,
			TO_CHAR(R.REGDATE, 'DD-MON-YYYY','nls_date_language=ENGLISH') AS REGDATE,
			TO_CHAR(R.REGDATE, 'HH24:MI') AS REGTIME,
			I.BEDCODE || ',' || I.ACMCODE AS BEDACM,
			TO_CHAR(I.INPDDATE, 'DD-MON-YYYY','nls_date_language=ENGLISH') AS INPDDATE,
			TO_CHAR(I.INPDDATE, 'HH24:MI') AS INPDTIME,
			D.DOCFNAME || ' ' || D.DOCGNAME AS DOCNAME,
			D.DOCCNAME
		FROM  SLIP S, PATIENT P, REG R, INPAT I, DOCTOR D
		WHERE S.REGID = R.REGID
		AND   S.PATNO = P.PATNO(+)
		AND   R.INPID = I.INPID(+)
		AND   S.DOCCODE = D.DOCCODE
		AND   S.SLPNO = V_SLPNO;

	RETURN OUTCUR;
END NHS_RPT_DAYCASERECEIPT;
/
