create or replace FUNCTION "NHS_RPT_IPSTATEMENTWB_SUB4"(
  V_ALLSLPNO IN VARCHAR2,
  V_GENDATE IN VARCHAR2
)
RETURN TYPES.CURSOR_TYPE AS
--RETURN VARCHAR2 AS
  OUTCUR TYPES.CURSOR_TYPE;
  SQLTMP VARCHAR2(32767);
  SQLTMP3 VARCHAR2(32767);
  SQLTMPU VARCHAR2(32767);
  SQLTMP0 VARCHAR2(32767);
  SQLTMPU0 VARCHAR2(32767);
  SQLTMP1 VARCHAR2(32767);
  SQLTMPU1 VARCHAR2(32767);
  SQLWHERE1 VARCHAR2(32767);
  SQLWHEREU1 VARCHAR2(32767);
  SQLWHERE2 VARCHAR2(32767);
  SQLWHERE3 VARCHAR2(32767);
  SQLSTR VARCHAR2(32767);
  LASTPRTDATE VARCHAR2(10);
  LASTPRTDATE2 VARCHAR2(10);
BEGIN
/*
  SELECT TO_CHAR(MAX(PRINTDATE),'DD/MM/YYYY')
  INTO V_LASTPRINTDATE
  FROM DAYENDSLIPS
  WHERE SLPNO = V_ALLSLPNO
  AND TO_CHAR(PRINTDATE,'DD/MM/YYYY')!=V_GENDATE;
*/
  BEGIN
    EXECUTE IMMEDIATE ' SELECT TO_CHAR(MAX(PRINTDATE),''DD/MM/YYYY'') FROM DAYENDSLIPS WHERE SLPNO=' || V_ALLSLPNO || ' AND trunc(PRINTDATE,''DD'') < trunc(TO_DATE('''||V_GENDATE||''',''DD/MM/YYYY HH24MISS''),''dd'') AND ENABLED = 1' INTO LASTPRTDATE;
/*
    IF LASTPRTDATE IS NULL THEN
      EXECUTE IMMEDIATE ' SELECT TO_CHAR(LASTPRTDATE2,''DD/MM/YYYY'') FROM PATIENT_EXTRA WHERE PATNO = (SELECT PATNO FROM SLIP WHERE SLPNO = ''' || V_ALLSLPNO || ''')' INTO LASTPRTDATE ;
      EXECUTE IMMEDIATE ' SELECT TO_CHAR(MAX(PRINTDATE),''DD/MM/YYYY'') FROM DAYENDSLIPS WHERE SLPNO=' || V_ALLSLPNO || ' AND trunc(PRINTDATE,''DD'') = trunc(TO_DATE('''||V_GENDATE||''',''DD/MM/YYYY HH24MISS''),''dd'')' INTO LASTPRTDATE2;
      IF LASTPRTDATE = LASTPRTDATE2 THEN
        LASTPRTDATE := null;
      END IF;
    END IF;
*/
  EXCEPTION
  WHEN OTHERS THEN
    LASTPRTDATE := NULL;
  END;

  SQLTMP0 :='SELECT DECODE(IP.STNSTS,''U'',IP.STNCDATE,IP.STNTDATE) AS STNTDATE,
        IP.STNCDATE,
        IP.SLPNO,
        IP.STNBAMT,
        IP.STNNAMT,
        IP.DESCRIPTION,
        IP.QTY,
        IP.STNTYPE,
        IP.ITMTYPE,
        IP.STNRLVL,
        IP.CDESCCODE
    FROM (';

  SQLTMP1 := '
    SELECT STNTDATE,
           DECODE(STNSTS,''C'',NHS_GET_SLIPTX_CANCEL_STNSDATE(slpno,stnseq,''' || V_GENDATE || ''') ,NVL(STNSDATE, STNCDATE)) STNCDATE,
           SLPNO,
           STNSEQ,
           STNBAMT,
           STNNAMT,
           DESCRIPTION,
           ITMCODE,
           QTY,
           STNTYPE,
           ITMTYPE,
           STNRLVL,
           CDESCCODE,
           STNSTS
      FROM V_IPSTATEMENTWB';

  SQLWHERE1 :=') IP WHERE IP.ITMCODE = ''PAYME''
    AND IP.STNCDATE IS NOT NULL
    AND IP.SLPNO IN (''' || V_ALLSLPNO || ''')
    AND DECODE(IP.STNSTS,''C'',NVL(NHS_GET_SLIPTX_CANCEL_STNSDATE(slpno,stnseq,''' || V_GENDATE || '''),TRUNC(SYSDATE,''DD'')) ,NVL(STNCDATE,TRUNC(SYSDATE,''DD''))) <TO_DATE(''' || V_GENDATE || ' 000001'',''DD/MM/YYYY HH24MISS'')';

  SQLWHERE3 :=') IP WHERE IP.ITMCODE = ''REF''
    AND IP.STNCDATE IS NOT NULL
    AND IP.SLPNO IN (''' || V_ALLSLPNO || ''')
    AND DECODE(IP.STNSTS,''C'',NVL(NHS_GET_SLIPTX_CANCEL_STNSDATE(slpno,stnseq,''' || V_GENDATE || '''),TRUNC(SYSDATE,''DD'')) ,NVL(STNCDATE,TRUNC(SYSDATE,''DD''))) <TO_DATE(''' || V_GENDATE || ' 000001'',''DD/MM/YYYY HH24MISS'')';

  SQLWHERE2 := ' AND trunc(DECODE(STNSTS,''C'',NVL(NHS_GET_SLIPTX_CANCEL_STNSDATE(slpno,stnseq,''' || V_GENDATE || '''),TRUNC(SYSDATE,''DD'')) ,NVL(STNCDATE,TRUNC(SYSDATE,''DD''))))>=trunc(TO_DATE(''' || LASTPRTDATE || ''',''DD/MM/YYYY''),''dd'')';

  IF V_GENDATE = LASTPRTDATE OR LASTPRTDATE IS NULL THEN
      SQLTMP := SQLTMP0||SQLTMP1||SQLWHERE1;
      SQLTMP3 := SQLTMP0||SQLTMP1||SQLWHERE3;
  ELSE
    SQLTMP := SQLTMP0||SQLTMP1||SQLWHERE1||SQLWHERE2;
    SQLTMP3 := SQLTMP0||SQLTMP1||SQLWHERE3||SQLWHERE2;
  END IF;

  SQLTMPU0 :='SELECT DECODE(IP.STNSTS,''U'',IP.STNTDATE_C,IP.STNTDATE) AS STNTDATE,
        IP.STNCDATE,
        IP.STNTDATE_C,
        IP.SLPNO,
        IP.STNBAMT,
        IP.STNNAMT,
        IP.DESCRIPTION,
        IP.QTY,
        IP.STNTYPE,
        IP.ITMTYPE,
        IP.STNRLVL,
        IP.CDESCCODE
    FROM (';

  SQLTMPU1 := '
    SELECT STNTDATE,
           STNTDATE_C,
           DECODE(STNSTS,''C'',NHS_GET_SLIPTX_CANCEL_STNCDATE(slpno,stnseq,''' || V_GENDATE || ''') ,TRUNC(STNCDATE,''DD'')) STNCDATE,
           SLPNO,
           STNSEQ,
           STNBAMT,
           STNNAMT,
           DESCRIPTION,
           ITMCODE,
           QTY,
           STNTYPE,
           ITMTYPE,
           STNRLVL,
           CDESCCODE,
           STNSTS
      FROM V_IPSTATEMENTWB_WITHU';

  SQLWHEREU1 :=') IP WHERE IP.STNCDATE IS NOT NULL
    AND IP.SLPNO IN (''' || V_ALLSLPNO || ''')
    AND DECODE(IP.STNSTS,''C'',NHS_GET_SLIPTX_CANCEL_STNCDATE(slpno,stnseq,''' || V_GENDATE || ''') ,TRUNC(STNCDATE,''DD'')) <trunc(TO_DATE(''' || V_GENDATE || ' 000001'',''DD/MM/YYYY HH24MISS''),''dd'')
    AND DECODE(IP.STNSTS,''U'',NHS_GET_SLIPTX_U2C_STNCDATE(slpno,stnseq),''R'',NHS_GET_SLIPTX_U2C_STNCDATE(slpno,stnseq),TRUNC(STNCDATE,''DD'')) < trunc(TO_DATE(''' || LASTPRTDATE || ''',''DD/MM/YYYY''),''dd'') ';
  -- STNTDATE_C>>STNCDATE
  IF V_GENDATE = LASTPRTDATE OR LASTPRTDATE IS NULL THEN
    SQLTMPU := SQLTMPU0||SQLTMPU1||SQLWHEREU1;
  ELSE
    SQLTMPU := SQLTMPU0||SQLTMPU1||SQLWHEREU1||SQLWHERE2;
  END IF;

  SQLSTR := '
    SELECT STNTDATE, AMOUNT, DESCRIPTION, QTY, CDESCCODE, ITEMORDER, TDATE
    FROM (
    SELECT NULL AS STNTDATE, OUTAMT AS AMOUNT, ''OPENING BALANCE'' AS DESCRIPTION, 0 AS QTY, null AS CDESCCODE, 0 AS ITEMORDER, null AS TDATE
    FROM DAYENDSLIPS
    WHERE SLPNO =''' || V_ALLSLPNO || '''
    AND TRUNC(PRINTDATE,''dd'') = trunc(TO_DATE(''' || LASTPRTDATE || ''',''DD/MM/YYYY''),''dd'')
    AND ENABLED = 1
    UNION ALL
    SELECT TO_CHAR(STNTDATE, ''DD/MM/YYYY'') AS STNTDATE,SUM(AMOUNT), DESCRIPTION, SUM(QTY),
      DECODE(STNTYPE,''S'',NULL,''R'',NULL,CDESCCODE) AS CDESCCODE,
      DECODE(STNRLVL, 4, 4, 7, 5,
                DECODE(STNTYPE, ''D'',
                      DECODE(ITMTYPE, ''D'', 1, ''H'', 2, ''S'', 3, 99),
                      ''R'', 10, ''P'', 9, ''C'', 8, ''S'', 7, ''I'', 6, ''O'', 6, ''X'', 6, 99)) AS ITEMORDER,
      STNTDATE TDATE
    FROM (
      SELECT TB1.STNTDATE STNTDATE, TB1.STNBAMT AS AMOUNT, TB1.DESCRIPTION, TB1.QTY QTY, TB1.STNTYPE,
             TB1.ITMTYPE, TB1.STNRLVL, TB1.CDESCCODE CDESCCODE
      FROM (  ' ||SQLTMPU ||'
      ) TB1
    UNION ALL
      SELECT TB2.STNTDATE STNTDATE, TB2.STNBAMT AS AMOUNT, TB2.DESCRIPTION, TB2.QTY QTY, TB2.STNTYPE,
             TB2.ITMTYPE, TB2.STNRLVL, TB2.CDESCCODE CDESCCODE
      FROM (  ' ||SQLTMP ||'
                AND IP.STNTYPE <> ''R''
                AND IP.STNRLVL IN (3,6)
      ) TB2
    UNION ALL
      SELECT TB3.STNTDATE STNTDATE, TB3.STNBAMT AS AMOUNT, TB3.DESCRIPTION, TB3.QTY QTY, TB3.STNTYPE,
             TB3.ITMTYPE, TB3.STNRLVL, TB3.CDESCCODE CDESCCODE
      FROM (  ' ||SQLTMP3 ||'
                AND IP.STNTYPE = ''R''
                AND IP.STNRLVL IN (3,6)
      ) TB3
    )
    GROUP BY STNTDATE, DESCRIPTION,  STNTYPE, STNRLVL, ITMTYPE, CDESCCODE)
    ORDER BY ITEMORDER ASC, TDATE, case when CDESCCODE is null then 1 else 0 end, DESCRIPTION';
              DBMS_OUTPUT.PUT_LINE(SQLSTR) ;
OPEN OUTCUR FOR SQLSTR;
RETURN OUTCUR;
--RETURN SQLTMP3;
END NHS_RPT_IPSTATEMENTWB_SUB4;
/
