create or replace
FUNCTION "NHS_RPT_RPTARADJUST"
(
  v_SteCode VARCHAR2,
  v_ArCode VARCHAR2,
  v_DateStart VARCHAR2,
  v_DateEnd VARCHAR2
)
  RETURN Types.cursor_type
AS
  outcur types.cursor_type;
BEGIN
  OPEN OUTCUR FOR
    SELECT  V_DATESTART, V_DATEEND,
            DECODE(AT.ATXTTYPE,'C','Company Level Charges','W','Write off / Adjust','D','Discount','') AS ARTYPE,
            AT.ARCCODE, AM.ARCNAME, TO_CHAR(AT.ATXCDATE, 'DDMONYYYY', 'nls_date_language=ENGLISH') AS CDATE,
            AT.PATNO AS PNUM, PT.PATFNAME AS FNAME, PT.PATGNAME AS GNAME,
            AT.ATXDESC AS REF, AT.ATXAMT AS AMT,
            DECODE(SP.SLPTYPE,'O','Out Patient','I','In Patient','D','Day Case') AS PTYPE,
            SC.STENAME, AT.USRID
    FROM   ARTX AT, ARCODE AM, PATIENT PT, SLIP SP, SITE SC
    WHERE  AT.ATXCDATE >= TO_DATE(V_DATESTART, 'DD/MM/YYYY')
    AND    AT.ATXCDATE < TO_DATE(V_DATEEND, 'DD/MM/YYYY')+1
    AND    AT.ATXTTYPE = 'C'
    AND    AT.ARPID IS NULL
    AND    AT.PATNO IS NULL
    AND    AT.ARCCODE = AM.ARCCODE
    AND    AM.STECODE = V_STECODE
    AND    (AT.ARCCODE = V_ARCODE OR V_ARCODE IS NULL)
    AND    AT.PATNO = PT.PATNO(+)
    AND    AT.SLPNO = SP.SLPNO(+)
    AND    AT.ATXSTS NOT IN ('R','C')
    AND    AM.STECODE = SC.STECODE
    AND    AT.SLPNO IS NULL
    
    UNION ALL
    
    SELECT  V_DATESTART, V_DATEEND,
            DECODE(AP.ARPTYPE,'C','Company Level Charges','W','Write off / Adjust','D','Discount','') AS ARTYPE,
            AP.ARCCODE, AM.ARCNAME, TO_CHAR(AP.ARPCDATE, 'DDMONYYYY', 'nls_date_language=ENGLISH') AS CDATE,
            '' AS PNUM, '' AS FNAME, '' AS GNAME, AP.ARPDESC AS REF,
            AP.ARPOAMT AS AMT, '' AS PTYPE, SC.STENAME, AP.USRID
    FROM    ARPTX AP, ARCODE AM, SITE SC
    WHERE   ARPSTS = 'N'
    AND     ARPRECNO IS NULL
    AND     AP.ARCCODE = AM.ARCCODE
    AND     AM.STECODE = V_STECODE
    AND     (AP.ARCCODE = V_ARCODE OR V_ARCODE IS NULL)
    AND     AM.STECODE = SC.STECODE
    AND     AP.ARPCDATE >= TO_DATE(V_DATESTART, 'DD/MM/YYYY')
    AND     AP.ARPCDATE < TO_DATE(V_DATEEND, 'DD/MM/YYYY')+1
    
    ORDER BY ARTYPE, ARCCODE, CDATE;

  RETURN OUTCUR;
END NHS_RPT_RPTARADJUST;
/