create or replace
FUNCTION            "NHS_RPT_OP_DIAGNOSIS"(V_SLPNO IN VARCHAR2, IS_PRINTDIAG IN VARCHAR2)
	RETURN TYPES.CURSOR_TYPE AS
  	OUTCUR TYPES.CURSOR_TYPE;
  	SQLSTR VARCHAR2(1000);
  	V_REGID REG.REGID%TYPE;
    --V_STFCOUNT number := 0;
    V_CNT   number;
    v_REGSTR VARCHAR2(300);

 BEGIN
  SELECT COUNT(1) INTO v_CNT FROM SLIPMERGE WHERE SLPNO = v_SLPNO;
	if V_CNT > 0 then
    SELECT LISTAGG(REGID, ''',''') WITHIN GROUP (
      ORDER BY REGID) INTO V_REGSTR
      from REG
      WHERE SLPNO IN
      (select SLPNO
      FROM SLIPMERGE
      where SEQID =
      (SELECT SEQID FROM SLIPMERGE  WHERE SLPNO = V_SLPNO
      ));
	ELSE
   SELECT REGID INTO V_REGSTR
    FROM REG
    WHERE SLPNO = V_SLPNO;
	END IF;

  
--  SELECT COUNT(1) INTO V_STFCOUNT
--  FROM PATALTLINK P
--  LEFT JOIN SLIP S ON P.PATNO = S.PATNO
--  LEFT JOIN ALERT A ON P.ALTID = A.ALTID
--  LEFT JOIN HPSTATUS H ON A.ALTCODE = H.HPSTATUS
--  WHERE S.SLPNO=V_SLPNO
--  AND H.HPTYPE='DIASALERT' AND H.HPKEY='STAFF' 
--  AND P.USRID_C IS NULL;

  
  	IF V_REGSTR IS NOT NULL AND LENGTH(V_REGSTR) > 0 AND IS_PRINTDIAG = 'Y' THEN
		    SQLSTR := 'SELECT OD.LAYMAN_DIAGNOSIS AS DIAGNOSIS,OD.DOCCODE AS DOCCODE,
					DECODE(TITTLE,'''','''',TITTLE||'' '')||DOCFNAME||'' ''||DOCGNAME as DOCNAME,
                    ECERT1,ECERT2,ECERT3,ECERT4,ECERT5,
                    ECERT6,ECERT7,ECERT8,ECERT9,ECERT10,
                    OD.PROCEDURES,GET_CURRENT_STECODE()
                    FROM OPD_DOCNOTE@CIS OD
                    LEFT JOIN ( 
                    SELECT DOCCODE,ECERT1,ECERT2,ECERT3,ECERT4,ECERT5,ECERT6,ECERT7,ECERT8,ECERT9,ECERT10
                    FROM DOCCERT) DQ ON OD.DOCCODE = DQ.DOCCODE
                    LEFT JOIN DOCTOR DR ON OD.DOCCODE = DR.DOCCODE
                    INNER JOIN REG R ON R.REGID = OD.REGID
                    WHERE OD.REGID IN ('''||V_REGSTR||''')
                     AND 
                    ((TRIM(REPLACE(OD.UPDATE_USER,''dr'','''')) = TRIM(R.DOCCODE))
                      OR 
                      (TRIM(REPLACE(OD.UPDATE_USER,''dr'','''')) = DR.MSTRDOCCODE ))';    
                      
    OPEN OUTCUR FOR SQLSTR;
      RETURN OUTCUR;
    END IF; 
    	RETURN NULL;
    	
END NHS_RPT_OP_DIAGNOSIS;
/