create or replace
FUNCTION NHS_RPT_PRINTITEMLST(
  v_SteCode VARCHAR2
)
  RETURN Types.cursor_type
AS
  outcur types.cursor_type;
BEGIN
  OPEN outcur FOR
SELECT I.ITMCODE,I.ITMNAME,I.ITMCNAME,I.ITMTYPE,
       I.ITMRLVL,I.DSCCODE,DS.DSCDESC,I.DPTCODE,
       D.DPTNAME,I.STECODE, I.ITMPOVERRD,I.ITMDOCCR,
       I.ITMCAT,I.ITMGRP 
FROM   ITEM I,DPSERV DS,DEPT D 
WHERE  I.DSCCODE=DS.DSCCODE AND I.DPTCODE=D.DPTCODE(+)
ORDER BY I.ITMCODE;
RETURN OUTCUR;
END NHS_RPT_PRINTITEMLST;
/