CREATE OR REPLACE FUNCTION "NHS_RPT_IPSTATEMENT_SUB2"(
  V_ALLSLPNO IN VARCHAR2,
  V_SPRNRANGE IN VARCHAR2
)
  RETURN TYPES.CURSOR_TYPE AS
  OUTCUR TYPES.CURSOR_TYPE;
  SQLSTR VARCHAR2(2000);
BEGIN
  SQLSTR:='
     SELECT AR.ARCCODE,
           MAX(AR.ARCNAME) AS ARCNAME,
           SUM(ART.ATXAMT) AS ATXAMT
      FROM SLIPTX ST, ARTX ART, ARCODE AR
     WHERE ST.STNXREF = ART.ATXID
       AND ART.ARCCODE = AR.ARCCODE
       AND ST.STNTYPE = ''P''
       AND ST.STNSTS = ''N''
       '|| V_SPRNRANGE ||'
       AND ST.SLPNO IN (' || V_ALLSLPNO || ')
     GROUP BY AR.ARCCODE
     ';
  OPEN OUTCUR FOR SQLSTR;
  RETURN OUTCUR;
END NHS_RPT_IPSTATEMENT_SUB2;
/
