CREATE OR REPLACE FUNCTION "NHS_RPT_NURSENOTE"
(v_dummy IN VARCHAR2)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
BEGIN

	OPEN OUTCUR FOR
		SELECT 1 from dual;
	RETURN OUTCUR;
END NHS_RPT_NURSENOTE;
/
