CREATE OR REPLACE FUNCTION NHS_RPT_RPTOTLOGSLIPAUDIT
 (v_StartDate VARCHAR2,
  v_EndDate VARCHAR2
)
  RETURN Types.cursor_type
AS
  outcur types.cursor_type;
BEGIN
  OPEN outcur FOR
SELECT A.AUDID,A.PATNO AS PATIENTNO,A.ADMUSERID,A.ADMDATE,A.PRESLPNO,A.NEWSLPNO,A.PRESEQNO,
      A.NEWSEQNO,B.STNSEQ,C.STNSEQ AS NEWSTNSEQ,B.PKGCODE AS PREPKGCODE,B.ITMCODE AS PREITMCODE,
      B.USRID AS PREUSRID,C.PKGCODE AS NEWPKGCODE,C.ITMCODE AS NEWITMCODE,C.USRID AS NEWUSRID
      FROM OT_LOG_SLIP_AUD A ,SLIPTX B,SLIPTX C
      WHERE   A.PRESLPNO=B.SLPNO(+)  AND A.PRESEQNO=B.STNSEQ(+) AND A.NEWSLPNO=C.SLPNO(+) AND A.NEWSEQNO=C.STNSEQ(+)
      AND (A.ADMDATE >= to_date(''||v_StartDate||' 00:00:00','DD/MM/YYYY HH24:MI:SS'))
      AND (A.ADMDATE <= to_date(''||v_EndDate||' 23:59:59','DD/MM/YYYY HH24:MI:SS'));
RETURN outcur;
END NHS_RPT_RPTOTLOGSLIPAUDIT;
/
