create or replace
FUNCTION           "NHS_RPT_SERVDETAILS" (
	V_SLPNO IN VARCHAR2,
  V_DSCCODE IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
  V_DSCDESC VARCHAR2(100);
  V_DSCCDESC VARCHAR2(100);
BEGIN

  --SELECT DSCDESC INTO V_DSCDESC FROM DPSERV WHERE DSCCODE = V_DSCCODE;
  --SELECT DESCRIPTION INTO V_DSCCDESC FROM DESCRIPTION_MAPPING WHERE TYPE || '.' || ID = 'DEPSERVICE.'||V_DSCCODE;
  
	OPEN OUTCUR FOR
		SELECT NVL(S.SLPFNAME, P.PATFNAME) || ' ' ||
			NVL(S.SLPGNAME, P.PATGNAME) AS PATNAME,
			P.PATCNAME,
			S.SLPNO,
			P.PATNO,
			TO_CHAR(R.REGDATE, 'DD-Mon-YYYY','nls_date_language=ENGLISH') AS REGDATE,
			TO_CHAR(R.REGDATE, 'HH24:MI') AS REGTIME,
			I.BEDCODE || ',' || A.ACMNAME AS BEDACM,
			TO_CHAR(I.INPDDATE, 'DD-Mon-YYYY','nls_date_language=ENGLISH') AS INPDDATE,
			TO_CHAR(I.INPDDATE, 'HH24:MI') AS INPDTIME,
			D.DOCFNAME || ' ' || D.DOCGNAME AS DOCNAME,
			D.DOCCNAME,
      (SELECT DSCDESC DPSERV FROM DPSERV WHERE DSCCODE = V_DSCCODE) AS DSCDESC,
      (SELECT DESCRIPTION  FROM DESCRIPTION_MAPPING WHERE  TYPE='DEPSERVICE' and ID= V_DSCCODE) AS DSCCDESC
		FROM  SLIP S, PATIENT P, REG R, INPAT I, DOCTOR D, ACM A
		WHERE S.REGID = R.REGID
		AND   S.PATNO = P.PATNO(+)
		AND   R.INPID = I.INPID(+)
		AND   I.ACMCODE =  A.ACMCODE
		AND   S.DOCCODE = D.DOCCODE
		AND   S.SLPNO = v_SLPNO;
	RETURN OUTCUR;
END NHS_RPT_SERVDETAILS;
/
