CREATE OR REPLACE FUNCTION "NHS_RPT_CHRGSMYMB" (
	v_SLPNO    IN VARCHAR2,
	v_ALLSLPNO IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
	SQLSTR VARCHAR2(4000);
	SQLTMP VARCHAR2(2000);
BEGIN
	SQLTMP := '
				NVL(S.SLPFNAME, P.PATFNAME) || '' '' ||
				NVL(S.SLPGNAME, P.PATGNAME) AS PATNAME,
				P.PATCNAME,
				S.SLPNO,
				P.PATNO,
				TO_CHAR(R.REGDATE, ''DD-MON-YYYY'',''nls_date_language=ENGLISH'') AS REGDATE,
				TO_CHAR(R.REGDATE, ''HH24:MI'') AS REGTIME,
				I.BEDCODE || '','' || A.ACMNAME AS BEDACM,
				TO_CHAR(I.INPDDATE, ''DD-MON-YYYY'',''nls_date_language=ENGLISH'') AS INPDDATE,
				TO_CHAR(I.INPDDATE, ''HH24:MI'') AS INPDTIME,
				D.DOCFNAME || '' '' || D.DOCGNAME AS DOCNAME,
				D.DOCCNAME,
				I.BEDCODE, A.ACMNAME
			FROM  SLIP S, PATIENT P, REG R, INPAT I, DOCTOR D, ACM A
			WHERE S.REGID = R.REGID
			AND   S.PATNO = P.PATNO(+)
			AND   R.INPID = I.INPID(+)
			AND   I.ACMCODE =  A.ACMCODE
			AND   S.DOCCODE = D.DOCCODE ';
  SQLSTR := '
			SELECT MB, PATNAME, PATCNAME, SLPNO, PATNO, REGDATE, REGTIME, BEDACM, INPDDATE, INPDTIME, DOCNAME, DOCCNAME
			FROM (
				SELECT ''Mother Information'' AS MB,' || SQLTMP || '
					AND S.SLPNO = ''' || v_SLPNO || '''
				UNION
				SELECT ''Baby Information'' AS MB,' || SQLTMP || '
					AND S.SLPNO IN (' || v_ALLSLPNO || ')
			)
			ORDER BY MB DESC';

	OPEN OUTCUR FOR SQLSTR;
	RETURN OUTCUR;
END NHS_RPT_CHRGSMYMB;
/
