CREATE OR REPLACE
FUNCTION "NHS_RPT_PHYORDERFORM_DEPT" (
	v_REGID IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;

BEGIN
	OPEN OUTCUR FOR
    SELECT DISTINCT SUBSTR(I.GLCCODE, 0, 4) DPTCODE, DM.DPTNAME, IT.ITMCODE, IT.ITMNAME, IT.DSCCODE, DV.DSCDESC
    FROM REG R, GOVREG GR, GOVITEM GI, ITEMCHG I, DEPT D, PATIENT P, ITEM IT, DPSERV DV,
        (SELECT ID AS DPTCODE, LISTAGG(DESCRIPTION, '<br>') WITHIN GROUP (ORDER BY LANGUAGE DESC) AS DPTNAME 
        FROM DESCRIPTION_MAPPING 
        WHERE TYPE = 'DEPARTMENT_NAME' 
        GROUP BY ID) DM
    WHERE R.REGID = GR.REGID
    AND GI.GOVJOBCODE = GR.GOVJOBCODE
    AND GI.ITMCODE = I.ITMCODE
    AND IT.DSCCODE = DV.DSCCODE
    AND D.DPTCODE = DM.DPTCODE
    AND D.DPTCODE = SUBSTR(I.GLCCODE, 0, 4)
    AND R.PATNO = P.PATNO
    AND IT.ITMCODE = I.ITMCODE
		AND GI.GOVSEX LIKE '%'||P.PATSEX||'%'
		AND I.ITCTYPE = 'O'
    AND IT.ITMTYPE != 'D'
		AND R.REGID = v_REGID
		ORDER BY SUBSTR(I.GLCCODE, 0, 4), IT.DSCCODE;
	RETURN OUTCUR;
END NHS_RPT_PHYORDERFORM_DEPT;
/