create or replace FUNCTION "NHS_RPT_DIECHOREPORT" (
	v_XRGID IN VARCHAR2
)
RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;

BEGIN
	OPEN OUTCUR FOR
		SELECT  
		--HEADER 
        P.PATFNAME || ' ' ||  P.PATGNAME AS PATNAME, J.PATNO, ST.STNDESC || ' ' || ST.STNDESC1 AS EXAMNAME, -- 1, 2, 3,
        HIST.DOCCODE, D.EDRNAME, D.ECHTITLEF, D.ECHTITLES, D.ECHTITLET, R.XJBNO, TO_CHAR(HIST.XRPDATE, 'DD/MM/YYYY') AS XRPDATE, -- 4, 5, 6, 7, 8, 9, 10
        --FOOTER
        HIST.USRID_P, TO_CHAR(P.PATBDATE, 'DD/MM/YYYY') AS PATBDATE, P.PATSEX, J.XJBTLOC, J.XJBTLOCDESC,-- 11, 12, 13, 14, 15, 
		--CONTENT
        HIST.XRPTITLE, HIST.XRPCONTENT -- 16, 17
		FROM XREPORTHIST HIST, XREPORT RPT, XREG R, XJOB J,SLIPTX ST, PATIENT P, EXDOCTOR D
		WHERE HIST.XRPID = RPT.XRPIDHIST
		AND R.XRGID = RPT.XRGID
		AND R.XJBNO = J.XJBNO
		AND R.STNID = ST.STNID 
		AND J.PATNO = P.PATNO 
		AND HIST.DOCCODE = D.DOCCODE 
		AND HIST.XRGID = v_XRGID
		AND HIST.XRPTSTS = 'A';
  RETURN OUTCUR;
END NHS_RPT_DIECHOREPORT;