CREATE OR REPLACE FUNCTION "NHS_RPT_PHYORDERFORM_MR" (
	v_REGID IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;

BEGIN
	OPEN OUTCUR FOR
    	SELECT COUNT(1) FROM DUAL;
	RETURN OUTCUR;
END NHS_RPT_PHYORDERFORM_MR;
/