CREATE OR REPLACE FUNCTION "NHS_GET_NEXTVOL"
(V_PATNO IN VARCHAR2)
  RETURN TYPES.CURSOR_TYPE
  AS
  OUTCUR TYPES.CURSOR_TYPE;
  NEWVOL  VARCHAR2(10);

BEGIN
  SELECT MAX(MRHVOLLAB) + 1 INTO NEWVOL FROM MEDRECHDR;
  IF NEWVOL IS NULL THEN
    NEWVOL := '01';
  END IF;
  IF LENGTH(NEWVOL) = 1 THEN
    NEWVOL := '0' || NEWVOL;
  END IF;
  OPEN OUTCUR FOR
    SELECT NEWVOL FROM DUAL;
  RETURN OUTCUR;
END NHS_GET_NEXTVOL;
/
