CREATE OR REPLACE FUNCTION "NHS_LIS_DISCHARGEDCPAT" (
	V_STECODE  IN VARCHAR2,
	V_DATEFROM IN VARCHAR2,
	V_DATETO   IN VARCHAR2,
	V_SDSCODE  IN VARCHAR2,
	V_PATNO    IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
	REG_STS_CANCEL VARCHAR2(1) := 'C';
BEGIN
	OPEN OUTCUR FOR
		SELECT DISTINCT *
		FROM (
			SELECT '',
				IP.DAYPID,
				P.PATNO,
				P.PATFNAME || ' ' || P.PATGNAME AS PATNAME,
				TO_CHAR(R.REGDATE,'DD/MM/YYYY HH24:MI:SS') as regdate,
				D.SPCCODE,
				TO_CHAR(IP.RECVDT,'DD/MM/YYYY'),
				IP.SDSCODE,
				IP.DESCODE,
				IP.RSNCODE,
				TO_CHAR(IP.CODEDT,'DD/MM/YYYY'),
				R.REGID AS REGID,
				SD.ISPAIRED,
				P.PATBDATE AS BIRTHDATE
			FROM DAYPAT IP, REG R, PATIENT P, DOCTOR D, SDISEASE SD
			WHERE R.REGDATE >= TO_DATE(V_DATEFROM, 'DD/MM/YYYY')
			AND R.REGDATE < TO_DATE(V_DATETO, 'DD/MM/YYYY') + 1
			AND R.DAYPID = IP.DAYPID
			AND P.PATNO = R.PATNO
			AND (P.STECODE = V_STECODE OR V_STECODE IS NULL)
			AND IP.SDSCODE = SD.SDSCODE(+)
			AND D.DOCCODE = R.DOCCODE
			AND (IP.SDSCODE = V_SDSCODE OR V_SDSCODE IS NULL)
			AND (R.PATNO = V_PATNO OR V_PATNO IS NULL)
			AND R.REGSTS <> REG_STS_CANCEL)
		ORDER BY REGDATE, PATNO;

	RETURN OUTCUR;
END NHS_LIS_DISCHARGEDCPAT;
/
