CREATE OR REPLACE FUNCTION "NHS_GET_NEWVOLLOC"
RETURN TYPES.CURSOR_TYPE
 AS
  OUTCUR TYPES.CURSOR_TYPE;
BEGIN
  OPEN OUTCUR FOR
    SELECT M.MRLID, M.MRLDESC
      FROM MEDRECLOC M, SYSPARAM S
     WHERE M.MRLID = S.PARAM1
       AND S.PARCDE LIKE 'MR%'
       AND S.PARAM2 = '05';
  RETURN OUTCUR;
END NHS_GET_NEWVOLLOC;
/
