CREATE OR REPLACE FUNCTION "NHS_ACT_DISCHARGEDPAT" (
	V_ACTION     IN VARCHAR2,
	V_USERID     IN VARCHAR2,
	V_TABLE      IN TEMPLATE_OBJ_TAB,
	O_ERRMSG     OUT VARCHAR2
)
	RETURN NUMBER
AS
	O_ERRCODE    NUMBER;
	e_comman     exception;

	MSG_NO_DIST_DESTINATION VARCHAR2(35) := 'Please enter Discharge Destination.';
BEGIN
	O_ERRCODE := -1;
	O_ERRMSG  := 'OK';

	IF V_ACTION = 'MOD' THEN
		FOR I IN 1..V_TABLE.COUNT LOOP
			-- destination
			IF V_TABLE(I).COLUMN11 IS NULL THEN
				O_ERRCODE := -1;
				O_ERRMSG := MSG_NO_DIST_DESTINATION;
				RAISE e_comman;
			END IF;

			--save new born
			IF V_TABLE(I).COLUMN06 <> V_TABLE(I).COLUMN20 THEN
				IF V_TABLE(I).COLUMN06 = 'Y' THEN
					UPDATE REG
					SET REGNB  = -1
					WHERE REGID = V_TABLE(I).COLUMN21;

					UPDATE  REG_EXTRA
					SET     MODIFY_DATE = SYSDATE,
						MODIFY_USER = V_USERID
					WHERE regid = V_TABLE(I).COLUMN21;
				ELSE
					UPDATE REG
					SET    REGNB  = 0
					WHERE  REGID = V_TABLE(I).COLUMN21;

					UPDATE  REG_EXTRA
					SET     MODIFY_DATE = SYSDATE,
						MODIFY_USER = V_USERID
					WHERE regid = V_TABLE(I).COLUMN21;
				END IF;
			END IF;

			IF LENGTH(TRIM(V_TABLE(I).COLUMN15)) > 0 THEN
				UPDATE INPAT
				SET    NURSERY = TO_DATE(V_TABLE(I).COLUMN15, 'DD/MM/YYYY')
				WHERE INPID = V_TABLE(I).COLUMN02;
			ELSE
				UPDATE INPAT
				SET    NURSERY = NULL
				WHERE INPID = V_TABLE(I).COLUMN02;
			END IF;

			UPDATE INPAT
			SET    SDSCODE = V_TABLE(I).COLUMN10,
				DESCODE = V_TABLE(I).COLUMN11,
				RSNCODE = V_TABLE(I).COLUMN12,
				INPREMARK = V_TABLE(I).COLUMN19
			WHERE INPID = V_TABLE(I).COLUMN02;

			IF LENGTH(TRIM(V_TABLE(I).COLUMN17)) > 0 THEN
				IF INSTR(V_TABLE(I).COLUMN17, '.') = 0 THEN
					UPDATE INPAT
					SET    INPSBCNT = TO_NUMBER(TRIM(V_TABLE(I).COLUMN17))
					WHERE INPID = V_TABLE(I).COLUMN02;
				ELSE
					UPDATE INPAT
					SET    INPSBCNT = TO_NUMBER(SUBSTR(TRIM(V_TABLE(I).COLUMN17), 1, LENGTH(TRIM(V_TABLE(I).COLUMN17))-2))
					WHERE INPID = V_TABLE(I).COLUMN02;
				END IF;
			ELSE
				UPDATE INPAT
				SET    INPSBCNT = NULL
				WHERE INPID = V_TABLE(I).COLUMN02;
			END IF;

			IF V_TABLE(I).COLUMN18 = 'Y' THEN
				UPDATE INPAT
				SET    COMPLICATION  = -1
				WHERE INPID = V_TABLE(I).COLUMN02;
			ELSE
				UPDATE INPAT
				SET    COMPLICATION  = 0
				WHERE INPID = V_TABLE(I).COLUMN02;
			END IF;

			IF LENGTH(TRIM(V_TABLE(I).COLUMN14)) = 0 OR LENGTH(TRIM(V_TABLE(I).COLUMN14)) IS NULL THEN
				IF TRIM(V_TABLE(I).COLUMN10) = '000' THEN
					UPDATE INPAT
					SET    RECVDT = SYSDATE
					WHERE INPID = V_TABLE(I).COLUMN02;
				ELSE
					UPDATE INPAT
					SET    RECVDT = NULL
					WHERE INPID = V_TABLE(I).COLUMN02;
				END IF;
			ELSE
				UPDATE INPAT
				SET    RECVDT = TO_DATE(V_TABLE(I).COLUMN14, 'DD/MM/YYYY')
				WHERE INPID = V_TABLE(I).COLUMN02;
			END IF;

			IF LENGTH(TRIM(V_TABLE(I).COLUMN16)) = 0 OR LENGTH(TRIM(V_TABLE(I).COLUMN16)) IS NULL THEN
				IF TRIM(V_TABLE(I).COLUMN10) <> '000' THEN
					UPDATE INPAT
					SET    CODEDT = SYSDATE
					WHERE INPID = V_TABLE(I).COLUMN02;
				ELSE
					UPDATE INPAT
					SET    CODEDT = NULL
					WHERE INPID = V_TABLE(I).COLUMN02;
				END IF;
			ELSE
				UPDATE INPAT
				SET    CODEDT = TO_DATE(V_TABLE(I).COLUMN16, 'DD/MM/YYYY')
				WHERE INPID = V_TABLE(I).COLUMN02;
			END IF;

			--update death
			IF  LENGTH(TRIM(V_TABLE(I).COLUMN03)) > 0 THEN
				IF V_TABLE(I).COLUMN11 = 'DEATH' THEN
					UPDATE PATIENT
					SET    DEATH = (SELECT INPDDATE FROM INPAT WHERE INPID = V_TABLE(I).COLUMN02)
					WHERE PATNO = V_TABLE(I).COLUMN03;
				ELSE
					UPDATE PATIENT
					SET    DEATH = NULL
					WHERE PATNO = V_TABLE(I).COLUMN03;
				END IF;
			END IF;
		END LOOP;
	END IF;

	O_ERRCODE := 0;

	RETURN O_ERRCODE;
EXCEPTION
WHEN e_comman THEN
	ROLLBACK;
	RETURN o_errCode;
WHEN OTHERS THEN
	o_errCode := -1;
	o_errmsg:= SQLERRM;
	ROLLBACK;
	RETURN o_errCode;
END NHS_ACT_DISCHARGEDPAT;
/
