CREATE OR REPLACE FUNCTION "NHS_ACT_MEDRECBATCH" (
	i_ACTION  IN VARCHAR2,
	i_MRBNO   IN VARCHAR2,
	i_MRLID_S IN VARCHAR2,
	i_MRLID_L IN VARCHAR2,
	i_USRID   IN VARCHAR2,
	o_ERRMSG  OUT VARCHAR2
)
	RETURN NUMBER
AS
	o_ERRCODE  NUMBER;
	v_MRHID MEDRECHDR.MRHID%TYPE;
	v_NEWDTLID NUMBER;
	v_MRDSTS MEDRECDTL.MRDSTS%TYPE := 'T';
	v_MRHSTS MEDRECHDR.MRHSTS%TYPE;
	v_COUNT NUMBER;
	v_COUNT2 NUMBER;

	MEDICAL_RECORD_PERMANENT VARCHAR2(1) := 'P';
BEGIN
	o_ERRCODE := 0;
	o_ERRMSG  := 'OK';

	IF i_ACTION = 'ADD' THEN
		FOR R IN (
			SELECT PATNO, MRHVOLLAB, MRHREMARK
			FROM   MEDRECBATCH
			WHERE  MRBNO = i_MRBNO
			AND    MRBSTS = -1 )
		LOOP
			SELECT COUNT(1) INTO v_COUNT FROM MEDRECHDR WHERE PATNO = R.PATNO AND MRHVOLLAB = R.MRHVOLLAB AND MRHSTS <> MEDICAL_RECORD_PERMANENT;
			IF v_COUNT = 1 THEN
				-- retrieve MRHID
				SELECT MRHID INTO v_MRHID FROM MEDRECHDR WHERE PATNO = R.PATNO AND MRHVOLLAB = R.MRHVOLLAB AND MRHSTS <> MEDICAL_RECORD_PERMANENT;

				-- get next MRDID
				SELECT SEQ_MEDRECDTL.NEXTVAL INTO v_NEWDTLID FROM DUAL;

				-- update MEDRECHDR
				UPDATE MEDRECHDR
				SET
					MRDID = v_NEWDTLID
				WHERE MRHID = v_MRHID;

				-- insert MEDRECDTL
				INSERT INTO MEDRECDTL (
					MRDID, MRHID, MRDSTS, MRDDDATE, MRDRDATE, MRLID_S, MRLID_L,
					DOCCODE, MRDRMK, USRID, MRLID_R, REQLOC
				) VALUES (
					v_NEWDTLID, v_MRHID, v_MRDSTS, SYSDATE, NULL, i_MRLID_S, i_MRLID_L,
					NULL, R.MRHREMARK, i_USRID, NULL, NULL
				);

				-- update MEDRECBATCH
				UPDATE MEDRECBATCH
				SET    MRBSTS = 0, MRHID = v_MRHID
				WHERE  PATNO = R.PATNO
				AND    MRHVOLLAB = R.MRHVOLLAB
				AND    MRBNO = i_MRBNO;
			ELSE
				SELECT COUNT(1) INTO v_COUNT2 FROM MEDRECHDR WHERE PATNO = R.PATNO AND MRHVOLLAB = R.MRHVOLLAB;
				IF v_COUNT2 = 1 THEN
					SELECT MRHSTS INTO v_MRHSTS FROM MEDRECHDR WHERE PATNO = R.PATNO AND MRHVOLLAB = R.MRHVOLLAB;
				END IF;
				DBMS_OUTPUT.PUT_LINE('ERROR: [' || R.PATNO || '][' || R.MRHVOLLAB || '][' || v_MRHSTS || '][' || v_COUNT2 || ']');
			END IF;
		END LOOP;
	END IF;

	RETURN o_ERRCODE;
EXCEPTION
WHEN OTHERS THEN
	ROLLBACK;
	DBMS_OUTPUT.PUT_LINE('An ERROR was encountered - '||SQLCODE||' -ERROR- '||SQLERRM);
	o_ERRMSG := 'An ERROR was encountered - '||SQLCODE||' -ERROR- '||SQLERRM;
	RETURN -1;
END NHS_ACT_MEDRECBATCH;
/
