create or replace
FUNCTION "NHS_GET_ADDMEDRECVOLINFO" (
  V_PATNO  IN VARCHAR2,
  V_PARAM1 IN VARCHAR2,
  V_PARAM2 IN VARCHAR2,
  V_PARAM3 IN VARCHAR2
)
 RETURN Types.cursor_type
 AS
  OUTCUR TYPES.CURSOR_TYPE;
  NEWVOL VARCHAR2(8);
  P1     VARCHAR2(50);
  P2     VARCHAR2(50);
  P3     VARCHAR2(50);
BEGIN
  
    SELECT MAX(MRHVOLLAB) + 1 INTO NEWVOL
    FROM MEDRECHDR
    WHERE MRHSTS <> 'P'
    AND PATNO = V_PATNO;
    
    SELECT PARAM1 INTO P1
    FROM SYSPARAM
    WHERE PARCDE LIKE 'MR%'
    AND (TO_NUMBER(PARAM2) = V_PARAM1);
    
    SELECT PARAM1 INTO P2
    FROM SYSPARAM
    WHERE PARCDE LIKE 'MR%'
    AND (TO_NUMBER(PARAM2) = V_PARAM2);
    
    SELECT PARAM1 INTO P3
    FROM SYSPARAM
    WHERE PARCDE LIKE 'MR%'
    AND (TO_NUMBER(PARAM2) = V_PARAM3);

    IF NEWVOL IS NULL THEN
      NEWVOL := 1;
    END IF;

    OPEN OUTCUR FOR
      SELECT NEWVOL, P1, P2, P3
      FROM DUAL;
    RETURN OUTCUR;
END NHS_GET_ADDMEDRECVOLINFO;
/