CREATE OR REPLACE FUNCTION "NHS_LIS_DRPREPORTDTLS"
(V_DRPID  IN VARCHAR2,
 V_STATUS IN VARCHAR2)

 RETURN TYPES.CURSOR_TYPE AS
  OUTCUR TYPES.CURSOR_TYPE;
BEGIN
  OPEN OUTCUR FOR
    SELECT DRPID,
           DRPSEQ,
           TO_CHAR(DRPCDATE, 'dd/mm/yyyy hh24:mi'),
           V_STATUS STATUS,
           USRID
      FROM DRPREPORTDTLS
     WHERE DRPID = V_DRPID
     ORDER BY DRPSEQ DESC;
  RETURN OUTCUR;

END NHS_LIS_DRPREPORTDTLS;
/
