create or replace
FUNCTION "NHS_GET_MEDRECGETWPAPER"(
	v_PatNo IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
	MEDICAL_RECORD_NORMAL VARCHAR2(1) := 'N';
	v_MRLDESC VARCHAR2(200);
	v_MRMDESC VARCHAR2(200);
	v_AUTOADD VARCHAR2(200);
	v_MrmID VARCHAR2(200);
	v_MRHVOLLAB VARCHAR2(10);
	HASPAPER VARCHAR2(1) := '0';
	v_ALERTNEWVOL NUMBER := '0';
	v_VOLCNT NUMBER := '0';

	CURSOR RUN_OUTCUR IS
		SELECT l.MRLDESC, m.MRMDESC, m.AUTOADD, m.MrmID, h.MRHVOLLAB
		FROM   MEDRECHDR h, MEDRECMED m, MEDRECDTL d, MEDRECLOC l
		WHERE  h.PatNo = v_PATNO
		AND    h.MrmID = m.MrmID
		AND    h.MrdID = d.MrdID
		AND    NVL(d.MRLID_R, d.MRLID_L) = l.MRLID
		AND    h.MrhSts = MEDICAL_RECORD_NORMAL
		ORDER BY h.mrhvollab DESC;
BEGIN
	OPEN RUN_OUTCUR;
	LOOP
	FETCH RUN_OUTCUR INTO v_MRLDESC, v_MRMDESC, v_AUTOADD, v_MrmID, v_MRHVOLLAB;
	EXIT WHEN RUN_OUTCUR%NOTFOUND;
		IF v_MrmID = 1 THEN
			HASPAPER := '1';
			v_VOLCNT := 0;
			EXIT;
		ELSE
			BEGIN
				SELECT 1
				INTO   v_ALERTNEWVOL
				FROM   SYSPARAM
				WHERE  PARCDE = 'AlrtNewVol'
				AND    PARAM1 = v_MrmID;

				v_VOLCNT := v_VOLCNT + v_ALERTNEWVOL;
				EXCEPTION
				WHEN OTHERS THEN
--				v_VOLCNT := v_VOLCNT;
          dbms_output.put_line('[v_VOLCNT]:'||v_VOLCNT);
			END;
		END IF;
	END LOOP;

	IF HASPAPER = '1' THEN
		OPEN OUTCUR FOR
			SELECT v_MRLDESC, v_MRMDESC, v_AUTOADD, v_MrmID, v_VOLCNT FROM DUAL;
	ELSE
		IF v_VOLCNT > 0 THEN
			OPEN OUTCUR FOR
			SELECT l.MrlDesc, m.MrmDesc, m.AutoAdd, m.MrmID, v_VOLCNT
			FROM   MedRecHdr h, MedRecMed m, MedRecDtl d, MedRecLoc l
			WHERE  h.PatNo = v_PatNo
			AND    h.MrmID = m.MrmID
			AND    h.MrdID = d.MrdID
			AND    NVL(d.MRLID_R, d.MRLID_L) = l.MRLID
			AND    h.MrhSts = MEDICAL_RECORD_NORMAL
			AND    h.MrmID IN ( SELECT PARAM1 FROM SYSPARAM WHERE PARCDE = 'AlrtNewVol')
			ORDER BY h.MRHID DESC;
		ELSE
			OPEN OUTCUR FOR
			SELECT l.MrlDesc, m.MrmDesc, m.AutoAdd, m.MrmID, v_VOLCNT
			FROM   MedRecHdr h, MedRecMed m, MedRecDtl d, MedRecLoc l
			WHERE  h.PatNo = v_PatNo
			AND    h.MrmID = m.MrmID
			AND    h.MrdID = d.MrdID
			AND    NVL(d.MRLID_R, d.MRLID_L) = L.MRLID
			AND    h.MrhSts = MEDICAL_RECORD_NORMAL
			ORDER BY h.MRHID DESC;
		END IF;
	END IF;
	RETURN OUTCUR;
END NHS_GET_MEDRECGETWPAPER;
/