CREATE OR REPLACE FUNCTION "NHS_ACT_MEDRECMERGE" (
	V_ACTION  IN VARCHAR2,
	V_TOPATNO IN VARCHAR2,
	V_FMPATNO IN VARCHAR2,
	V_USRID   IN VARCHAR2,
	V_STECODE IN VARCHAR2,
	O_ERRMSG  OUT VARCHAR2
)
	RETURN NUMBER
AS
	O_ERRCODE   NUMBER;
	V_PMCID     NUMBER;
	V_MRDSTS2   VARCHAR2(1);
	V_MRHSTS    VARCHAR2(1);
BEGIN
	O_ERRCODE := 0;
	O_ERRMSG  := 'OK';

	INSERT INTO PATMERCHT (
		PMCID,
		TO_PATNO,
		TO_PATFNAME,
		TO_PATGNAME,
		TO_PATSEX,
		TO_PATBDATE,
		TO_PATIDNO,
		PMCDATE,
		USRID,
		STECODE,
		FM_PATNO, ---FROM PAT
		FM_PATFNAME,
		FM_PATGNAME,
		FM_PATCNAME,
		FM_PATIDNO,
		FM_PATBDATE,
		FM_PATSEX,
		FM_PATMSTS,
		FM_PATADD1,
		FM_PATADD2,
		FM_PATADD3,
		FM_PATHTEL,
		FM_PATOTEL,
		FM_LOCCODE,
		FM_PATRDATE,
		FM_PATVCNT,
		FM_REGID_L,
		FM_REGID_C,
		FM_PATNB,
		FM_PATMOTHER,
		FM_PATKNAME,
		FM_PATKRELA,
		FM_PATKHTEL,
		FM_PATKOTEL,
		FM_PATKPTEL,
		FM_PATKMTEL,
		FM_PATSTS,
		FM_STECODE,
		FM_PATSTAFF,
		FM_PATMNAME,
		FM_PATITP,
		FM_TITDESC,
		FM_MOTHCODE,
		FM_COUCODE,
		FM_PATKADD,
		FM_PATPAGER,
		FM_PATFAXNO,
		FM_PATRMK,
		FM_LASTPRTDATE,
		FM_LASTUPD,
		FM_USRID,
		FM_DEATH,
		FM_RELIGIOUS,
		FM_OCCUPATION,
		FM_EDULEVEL,
		FM_PATEMAIL,
		FM_PATKEMAIL)
	SELECT
		999999999999,
		P.PATNO,
		P.PATFNAME,
		P.PATGNAME,
		P.PATSEX,
		P.PATBDATE,
		P.PATIDNO,
		SYSDATE,
		GET_CURRENT_STECODE,
		GET_CURRENT_STECODE,
		FM.PATNO, --
		FM.PATFNAME,
		FM.PATGNAME,
		FM.PATCNAME,
		FM.PATIDNO,
		FM.PATBDATE,
		FM.PATSEX,
		FM.PATMSTS,
		FM.PATADD1,
		FM.PATADD2,
		FM.PATADD3,
		FM.PATHTEL,
		FM.PATOTEL,
		FM.LOCCODE,
		FM.PATRDATE,
		FM.PATVCNT,
		FM.REGID_L,
		FM.REGID_C,
		FM.PATNB,
		FM.PATMOTHER,
		FM.PATKNAME,
		FM.PATKRELA,
		FM.PATKHTEL,
		FM.PATKOTEL,
		FM.PATKPTEL,
		FM.PATKMTEL,
		FM.PATSTS,
		FM.STECODE,
		FM.PATSTAFF,
		FM.PATMNAME,
		FM.PATITP,
		FM.TITDESC,
		FM.MOTHCODE,
		FM.COUCODE,
		FM.PATKADD,
		FM.PATPAGER,
		FM.PATFAXNO,
		FM.PATRMK,
		FM.LASTPRTDATE,
		FM.LASTUPD,
		FM.USRID,
		FM.DEATH,
		FM.RELIGIOUS,
		FM.OCCUPATION,
		FM.EDULEVEL,
		FM.PATEMAIL,
		FM.PATKEMAIL
	FROM PATIENT P, PATIENT FM
	WHERE P.PATNO = V_TOPATNO
	AND FM.PATNO = V_FMPATNO;

	SELECT SEQ_PATMERCHT.NEXTVAL INTO V_PMCID FROM DUAL;

	UPDATE PATMERCHT
		SET PMCID = V_PMCID, USRID = V_USRID, STECODE = V_STECODE
	WHERE PMCID = 999999999999;

	RETURN O_ERRCODE;
END NHS_ACT_MEDRECMERGE;
/
