create or replace
FUNCTION "NHS_ACT_DISCHARGEDCPAT"
(V_ACTION     IN VARCHAR2,
  V_USERID     IN VARCHAR2,
  V_TABLE      IN TEMPLATE_OBJ_TAB,
 O_ERRMSG     OUT VARCHAR2)

  RETURN NUMBER AS
  O_ERRCODE NUMBER;

BEGIN
  O_ERRCODE := 0;
  O_ERRMSG  := 'OK';

  IF V_ACTION = 'MOD' THEN
    FOR I IN 1..V_TABLE.COUNT LOOP
      UPDATE DAYPAT
         SET SDSCODE      = V_TABLE(I).COLUMN08,
             DESCODE      = V_TABLE(I).COLUMN09,
             RSNCODE      = V_TABLE(I).COLUMN10
       WHERE DAYPID = TO_NUMBER(V_TABLE(I).COLUMN02);
    
     IF LENGTH(TRIM(V_TABLE(I).COLUMN11)) = 0 OR LENGTH(TRIM(V_TABLE(I).COLUMN11)) IS NULL THEN
        IF TRIM(V_TABLE(I).COLUMN08) <> '000' THEN
          UPDATE DAYPAT
          SET CODEDT = SYSDATE
          WHERE DAYPID = TO_NUMBER(V_TABLE(I).COLUMN02);
        ELSE
          UPDATE DAYPAT
          SET CODEDT = null
          WHERE DAYPID = TO_NUMBER(V_TABLE(I).COLUMN02);
        END IF;
      ELSE
        UPDATE DAYPAT
        SET CODEDT = TO_DATE(V_TABLE(I).COLUMN11, 'DD/MM/YYYY')
        WHERE DAYPID = TO_NUMBER(V_TABLE(I).COLUMN02);
      END IF;
          IF LENGTH(TRIM(V_TABLE(I).COLUMN07)) = 0 OR LENGTH(TRIM(V_TABLE(I).COLUMN07)) IS NULL THEN
        IF TRIM(V_TABLE(I).COLUMN08) = '000' THEN
          UPDATE DAYPAT
          SET RECVDT = SYSDATE
          WHERE DAYPID = TO_NUMBER(V_TABLE(I).COLUMN02);
        ELSE
          UPDATE DAYPAT
          SET RECVDT = NULL
          WHERE DAYPID = TO_NUMBER(V_TABLE(I).COLUMN02);
        END IF;
      ELSE
        UPDATE DAYPAT
        SET RECVDT = TO_DATE(V_TABLE(I).COLUMN07, 'DD/MM/YYYY')
        WHERE DAYPID = TO_NUMBER(V_TABLE(I).COLUMN02);
      END IF;
      
    END LOOP;
  END IF;
  O_ERRCODE := 0;

  RETURN O_ERRCODE;
EXCEPTION
WHEN OTHERS THEN
	o_errCode := -1;
	o_errmsg:= SQLERRM;
	ROLLBACK;
	RETURN o_errCode;
END NHS_ACT_DISCHARGEDCPAT;
/
