CREATE OR REPLACE FUNCTION "NHS_ACT_MEDRECMODIFY" (
	i_ACTION  IN VARCHAR2,
	i_MRHID   IN VARCHAR2,
	i_MRDID   IN VARCHAR2,
	i_VOLUME  IN VARCHAR2,
	i_MRHSTS  IN VARCHAR2,
	i_MRMID   IN VARCHAR2,
	i_MRDRMK  IN VARCHAR2,
	i_MRLID_S IN VARCHAR2,
	i_MRLID_L IN VARCHAR2,
	i_MRLID_R IN VARCHAR2,
	i_USRID   IN VARCHAR2,
	o_ERRMSG  OUT VARCHAR2
)
	RETURN NUMBER
AS
	o_ERRCODE  NUMBER;
	v_NEWDTLID NUMBER;
	v_VOLUME MEDRECHDR.MRHVOLLAB%TYPE;
BEGIN
	o_ERRCODE := 0;
	o_ERRMSG  := 'OK';

	IF i_ACTION = 'MOD' THEN
		IF i_VOLUME IS NULL THEN
       		o_ERRCODE := -1;
       		o_ERRMSG  := 'Invalid volume number!';
       		RETURN o_ERRCODE;
		END IF;

		IF LENGTH(i_VOLUME) > 5 THEN
       		o_ERRCODE := -1;
       		o_ERRMSG  := 'Volume number is too long!';
       		RETURN o_ERRCODE;
		END IF;

		IF LENGTH(i_VOLUME) = 1 THEN
       		v_VOLUME := '0' || i_VOLUME;
		ELSE
       		v_VOLUME := i_VOLUME;
		END IF;

		UPDATE MEDRECHDR
		SET
			MRHVOLLAB = v_VOLUME,
			MRHSTS = i_MRHSTS,
			MRMID = i_MRMID
		WHERE MRHID = i_MRHID;

		UPDATE MEDRECDTL
		SET
			MRDDDATE = SYSDATE,
			MRDRMK   = i_MRDRMK,
			MRLID_S  = i_MRLID_S,
			MRLID_R  = i_MRLID_R,
			MRLID_L  = i_MRLID_L,
			USRID = i_USRID
		WHERE MRDID = i_MRDID;
	ELSIF i_ACTION = 'DEL' THEN
		SELECT SEQ_MEDRECDTL.NEXTVAL INTO v_NEWDTLID FROM DUAL;

		UPDATE MEDRECHDR
		SET
			MRHSTS = i_MRHSTS,
			MRDID = v_NEWDTLID
		WHERE MRHID = i_MRHID;

		INSERT INTO MEDRECDTL (
			MRDID, MRHID, MRDSTS, MRDDDATE, MRDRDATE, MRLID_S,
			MRLID_L, DOCCODE, MRDRMK, USRID, MRLID_R, REQLOC
		) VALUES (
			v_NEWDTLID, i_MRHID, i_MRHSTS, SYSDATE, NULL, i_MRLID_S, i_MRLID_L,
			NULL, i_MRDRMK, i_USRID, i_MRLID_R, NULL
		);
	END IF;
	RETURN o_ERRCODE;
EXCEPTION
WHEN OTHERS THEN
	ROLLBACK;
	DBMS_OUTPUT.PUT_LINE('An ERROR was encountered - '||SQLCODE||' -ERROR- '||SQLERRM);
	o_ERRMSG := 'An ERROR was encountered - '||SQLCODE||' -ERROR- '||SQLERRM;
	RETURN -1;
END NHS_ACT_MEDRECMODIFY;
/
