CREATE OR REPLACE FUNCTION NHS_LIS_MEDRECMERGE (
	v_action IN VARCHAR2,
	v_PatNo  IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	SQLSTR VARCHAR2(500);
	OUTCUR TYPES.CURSOR_TYPE;
BEGIN
	IF v_action = 'ADD' THEN
		OPEN OUTCUR FOR
			SELECT '', 'ARTX', 'ATXID', TO_CHAR(ATXID) FROM ARTX WHERE PatNo = v_PatNo
			UNION
			SELECT '', 'BDYMES', 'BMSID', TO_CHAR(BMSID) FROM BDYMES WHERE PatNo = v_PatNo
			UNION
			SELECT '', 'BEDHIST', ' BHSID', TO_CHAR(BHSID) FROM BEDHIST WHERE PatNo = v_PatNo
			UNION
			SELECT '', 'BEDPREBOK', 'PBPID', TO_CHAR(PBPID) FROM BEDPREBOK WHERE PatNo = v_PatNo
			UNION
			SELECT '', 'BOOKING', 'BKGID', TO_CHAR(BKGID) FROM BOOKING WHERE PatNo = v_PatNo
			UNION
			SELECT '', 'BRINGINDRG', 'BRGID', TO_CHAR(BRGID) FROM BRINGINDRG WHERE PatNo = v_PatNo
			UNION
			SELECT '', 'DOCHIST', 'DHSID', TO_CHAR(DHSID) FROM DOCHIST WHERE PatNo = v_PatNo
			UNION
			SELECT '', 'DOCINCOME', 'DICID', TO_CHAR(DICID) FROM DOCINCOME WHERE PatNo = v_PatNo
			UNION
			SELECT '', 'MEDRECHDR', 'MRHID', TO_CHAR(MRHID) FROM MEDRECHDR WHERE PatNo = v_PatNo
			UNION
			SELECT '', 'PATADVREA', 'PARID', TO_CHAR(PARID) FROM PATADVREA WHERE PatNo = v_PatNo
			UNION
			SELECT '', 'PATALTLINK', 'PALID', TO_CHAR(palid) from pataltlink where PatNo = v_PatNo
			UNION
			SELECT '', 'PATMEDREC', 'PMRID', TO_CHAR(PMRID) FROM PATMEDREC WHERE PatNo = v_PatNo
			UNION
			SELECT '', 'PATREFSCH', 'PRHID', TO_CHAR(PRHID) FROM PATREFSCH WHERE PatNo = v_PatNo
			UNION
			SELECT '', 'PHARBOOKING', 'PBKID', TO_CHAR(PBKID) FROM PHARBOOKING WHERE PatNo = v_PatNo
			UNION
			SELECT '', 'PHARPROGNOTES', 'PPNID', TO_CHAR(PPNID) FROM PHARPROGNOTES WHERE PatNo = v_PatNo
			UNION
			SELECT '', 'PHYADMERR', 'PAEID', TO_CHAR(PAEID) FROM PHYADMERR WHERE PatNo = v_PatNo
			UNION
			SELECT '', 'PHYDISERR', 'PDEID', TO_CHAR(PDEID) FROM PHYDISERR WHERE PatNo = v_PatNo
			UNION
			SELECT '', 'PRECAUTION', 'PRECID', TO_CHAR(PRECID) FROM PRECAUTION WHERE PatNo = v_PatNo
			UNION
			SELECT '', 'PRESCRIPTION', 'PREID', TO_CHAR(PREID) FROM PRESCRIPTION WHERE PatNo = v_PatNo
			UNION
			SELECT '', 'REG', 'REGID', TO_CHAR(REGID) FROM REG WHERE PatNo = v_PatNo
			UNION
			SELECT '', 'SLIP', 'SLPNO', TO_CHAR(SLPNO) FROM SLIP WHERE PatNo = v_PatNo
			UNION
			SELECT '', ',XAPP', 'XAPID', TO_CHAR(XAPID) FROM XAPP WHERE PatNo = v_PatNo
			UNION
			SELECT '', 'XJOB', 'XJBNO', TO_CHAR(XJBNO) FROM XJOB WHERE PatNo = v_PatNo
			UNION
			SELECT '', 'OT_App', 'OTAID', TO_CHAR(OTAID) FROM OT_App WHERE PatNo = v_PatNo
			UNION
			SELECT '', 'OT_Log', 'OTLID', TO_CHAR(OTLID) FROM OT_Log WHERE PatNo = v_PatNo
			UNION
			SELECT '', 'OT_Log_Slip_Aud', 'AUDID', TO_CHAR(AUDID) FROM OT_Log_Slip_Aud WHERE PatNo = v_PatNo
			UNION
			SELECT '', 'Xexpire', 'PatNo', TO_CHAR(PatNo) FROM Xexpire WHERE PatNo = v_PatNo
			ORDER BY 2,3,4;
	ELSIF V_ACTION = 'LIS' THEN
		OPEN OUTCUR FOR
		SELECT '', TABNAME, TABFIELD, TABREF
		FROM PatMerDtl
		WHERE pmcid IN (
			SELECT pmcid
			FROM PatMerCht
			WHERE Fm_PatNo = v_PatNo
		);
	END IF;

	RETURN OUTCUR;
END NHS_LIS_MEDRECMERGE;
/
