CREATE OR REPLACE FUNCTION "NHS_ACT_MEDRECTRANSFER" (
	i_ACTION  IN VARCHAR2,
	i_USRID   IN VARCHAR2,
	i_SENDSMS IN VARCHAR2,
	i_RECEIVE IN TEMPLATE_OBJ_TAB,
	o_ERRMSG  OUT VARCHAR2
)
	RETURN NUMBER
AS
	o_ERRCODE NUMBER(10);
	v_PATNO VARCHAR2(10);
	v_VOLNUM VARCHAR2(10);
	v_MRDID NUMBER(10);
	v_MRDDDATE DATE;
	v_MRDSTS VARCHAR2(1);
	v_CNT NUMBER(10);
	v_CONDITION NUMBER(10);
	o_errcode2 NUMBER;
	O_ERRMSG2 VARCHAR2(100);
BEGIN
	o_ERRCODE := 0;
	o_ERRMSG  := '';

	FOR I IN 1..i_RECEIVE.COUNT LOOP
		v_MRDID := NULL;
		v_MRDSTS := NULL;
		v_MRDDDATE := NULL;
		v_CNT := REGEXP_INSTR(i_RECEIVE(I).COLUMN01, '[/]');

		IF v_CNT = 0 THEN
			SELECT COUNT(1) INTO v_CNT
			FROM MEDRECHDR H, MEDRECDTL D
			WHERE H.MRDID = D.MRDID
			AND PATNO = i_RECEIVE(I).COLUMN01
			AND MRHVOLLAB IS NULL
			AND MRHSTS <> 'P';

			v_CONDITION := 1;
		ELSE
			v_PATNO := SUBSTR(i_RECEIVE(I).COLUMN01, 1, REGEXP_INSTR(i_RECEIVE(I).COLUMN01, '[/]')-1);
			v_VOLNUM := SUBSTR(i_RECEIVE(I).COLUMN01, REGEXP_INSTR(i_RECEIVE(I).COLUMN01, '[/]')+1, LENGTH(i_RECEIVE(I).COLUMN01));

			IF LENGTH(v_VOLNUM) = 0 THEN
				SELECT COUNT(1) INTO v_CNT
				FROM MEDRECHDR H, MEDRECDTL D
				WHERE H.MRDID = D.MRDID
				AND PATNO = v_PATNO
				AND MRHVOLLAB IS NULL
				AND MRHSTS <> 'P';

				v_CONDITION := 2;
			ELSE
				SELECT COUNT(1) INTO v_CNT
				FROM MEDRECHDR H, MEDRECDTL D
				WHERE H.MRDID = D.MRDID
				AND PATNO = v_PATNO
				AND MRHVOLLAB = v_VOLNUM
				AND MRHSTS <> 'P';

				v_CONDITION := 3;
			END IF;
		END IF;

		IF v_CNT = 0 THEN
			o_ERRMSG := o_ERRMSG || TO_CHAR(I - 1) || '_';
			CONTINUE;
		END IF;

		IF v_CONDITION = 1 THEN
			SELECT D.MRDID, D.MRDSTS,D.MRDRDATE  INTO v_MRDID, v_MRDSTS, v_MRDDDATE
			FROM MEDRECHDR H, MEDRECDTL D
			WHERE H.MRDID = D.MRDID
			AND PATNO = i_RECEIVE(I).COLUMN01
			AND MRHVOLLAB IS NULL
			AND MRHSTS <> 'P';
		ELSIF v_CONDITION = 2 THEN
			SELECT D.MRDID, D.MRDSTS,D.MRDRDATE  INTO v_MRDID, v_MRDSTS, v_MRDDDATE
			FROM MEDRECHDR H, MEDRECDTL D
			WHERE H.MRDID = D.MRDID
			AND PATNO = v_PATNO
			AND MRHVOLLAB IS NULL
			AND MRHSTS <> 'P';
		ELSIF v_CONDITION = 3 THEN
			SELECT D.MRDID, D.MRDSTS,D.MRDRDATE  INTO v_MRDID, v_MRDSTS, v_MRDDDATE
			FROM MEDRECHDR H, MEDRECDTL D
			WHERE H.MRDID = D.MRDID
			AND PATNO = v_PATNO
			AND MRHVOLLAB = v_VOLNUM
			AND MRHSTS <> 'P';
		END IF;

		IF v_MRDID IS NULL OR LENGTH(v_MRDID) = 0 THEN
			o_ERRMSG := o_ERRMSG || TO_CHAR(I - 1) || '_';
			CONTINUE;
		ELSIF v_MRDSTS <> 'T' THEN
			o_ERRMSG := o_ERRMSG || TO_CHAR(I - 1) || '_';
			CONTINUE;
		ELSIF v_MRDDDATE IS NOT NULL THEN
			o_ERRMSG := o_ERRMSG || TO_CHAR(I - 1) || '_';
			CONTINUE;
		ELSIF v_MRDSTS = 'T' AND v_MRDDDATE IS NULL THEN
			UPDATE MEDRECDTL
			SET
				MRDRDATE = To_DATE(i_RECEIVE(I).COLUMN03,'DD/MM/YYYY HH24:MI:SS'),
				USRID = i_USRID,
				MRLID_R = i_RECEIVE(I).COLUMN02
			WHERE MRDID = v_MRDID;
		END IF;

		IF i_SENDSMS = 'Y' AND v_PATNO IS NOT NULL THEN
			o_errcode2 := NHS_ACT_PATIENTACTIVITYLOG('ADD', v_PATNO, 'SMS', 'PTT', 'From Medical Record', i_USRID, NULL, o_errmsg2);
		END IF;
	END LOOP;

	RETURN o_ERRCODE;
EXCEPTION
WHEN OTHERS THEN
	ROLLBACK;
	DBMS_OUTPUT.PUT_LINE('An ERROR was encountered - '||SQLCODE||' -ERROR- '||SQLERRM);
	o_ERRMSG := 'An ERROR was encountered - '||SQLCODE||' -ERROR- '||SQLERRM;
	RETURN -1;
END NHS_ACT_MEDRECTRANSFER;
/
