CREATE OR REPLACE FUNCTION "NHS_GET_MEDCHARTRECLOC"
  RETURN TYPES.CURSOR_TYPE
   AS
  OUTCUR TYPES.CURSOR_TYPE;
BEGIN
  OPEN OUTCUR FOR
    SELECT MRLID, MRLDESC
      FROM SYSPARAM, MEDRECLOC
     WHERE PARCDE = 'MRTRCL'
       AND TO_CHAR(PARAM1) = MRLID;
  RETURN OUTCUR;
END NHS_GET_MEDCHARTRECLOC;
/
