ALTER TABLE AC_DOCUMENT_ACCESS
 DROP PRIMARY KEY CASCADE;
DROP TABLE AC_DOCUMENT_ACCESS CASCADE CONSTRAINTS;

CREATE TABLE AC_DOCUMENT_ACCESS
(
 AC_DOCUMENT_ID NUMBER(*,0) NOT NULL ENABLE,
 AC_USERNAME VARCHAR2(30 BYTE) DEFAULT 'ALL',
 AC_USER_ID VARCHAR2(20 BYTE) DEFAULT 'ALL',
 AC_GROUP_ID VARCHAR2(50 BYTE) DEFAULT 'ALL',
 AC_CREATED_DATE DATE DEFAULT SYSDATE,
 AC_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 AC_MODIFIED_DATE DATE DEFAULT SYSDATE,
 AC_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 AC_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (AC_DOCUMENT_ID, AC_USERNAME, AC_USER_ID, AC_GROUP_ID)
);

ALTER TABLE AC_DOCUMENT_ACCESS ADD (
 CONSTRAINT AC_DOCUMENT_ACCESS_R01
 FOREIGN KEY (AC_DOCUMENT_ID)
 REFERENCES CO_DOCUMENT (CO_DOCUMENT_ID));
--ALTER TABLE AC_DOCUMENT_ACCESS ADD (
-- CONSTRAINT AC_DOCUMENT_ACCESS_R02
-- FOREIGN KEY (AC_USERNAME)
-- REFERENCES CO_USERS (CO_USERNAME));

INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_GROUP_ID) VALUES(26, 'administration.patient.info');
INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_GROUP_ID) VALUES(27, 'administration.patient.info');
INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_GROUP_ID) VALUES(28, 'administration.patient.info');
INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_GROUP_ID) VALUES(29, 'administration.patient.info');
INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_GROUP_ID) VALUES(42, 'administration.patient.info');
INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_GROUP_ID) VALUES(43, 'administration.patient.info');
INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_GROUP_ID) VALUES(44, 'administration.patient.info');
INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_GROUP_ID) VALUES(45, 'administration.patient.info');
INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_GROUP_ID) VALUES(46, 'administration.patient.info');
INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_GROUP_ID) VALUES(47, 'administration.patient.info');
INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_GROUP_ID) VALUES(48, 'administration.patient.info');
INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_GROUP_ID) VALUES(49, 'administration.patient.info');
INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_GROUP_ID) VALUES(50, 'administration.patient.info');
INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_GROUP_ID) VALUES(55, 'administration.patient.info');

INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_GROUP_ID) VALUES(85, 'administration.patient.info');
INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_GROUP_ID) VALUES(86, 'administration.patient.info');

INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_GROUP_ID) VALUES(35, 'staff');

INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_GROUP_ID) VALUES(51, 'department.head');

-- Committee Minutes
INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_GROUP_ID) VALUES(201, 'administration.direction.plan');
INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_GROUP_ID) VALUES(202, 'administration.direction.plan');

-- DIRECTION & PLAN OF HKAH
INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_GROUP_ID) VALUES(211, 'administration.direction.plan');
INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_GROUP_ID) VALUES(212, 'administration.direction.plan');

INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_GROUP_ID) VALUES(221, 'administration.direction.plan');
INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_GROUP_ID) VALUES(222, 'administration.direction.plan');
INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_GROUP_ID) VALUES(223, 'administration.direction.plan');
INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_GROUP_ID) VALUES(224, 'administration.direction.plan');

INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_GROUP_ID) VALUES(234, 'administration.direction.plan');
INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_GROUP_ID) VALUES(235, 'administration.direction.plan');
INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_GROUP_ID) VALUES(236, 'administration.direction.plan');

INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_GROUP_ID) VALUES(244, 'administration.direction.plan');
INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_GROUP_ID) VALUES(245, 'administration.direction.plan');
INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_GROUP_ID) VALUES(246, 'administration.direction.plan');
INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_GROUP_ID) VALUES(247, 'administration.direction.plan');

INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_GROUP_ID) VALUES(295, 'administration.direction.plan');
INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_GROUP_ID) VALUES(296, 'administration.direction.plan');
INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_GROUP_ID) VALUES(297, 'administration.direction.plan');
INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_GROUP_ID) VALUES(298, 'administration.direction.plan');
INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_GROUP_ID) VALUES(299, 'administration.direction.plan');
INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_GROUP_ID) VALUES(300, 'administration.direction.plan');
INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_GROUP_ID) VALUES(301, 'administration.direction.plan');
INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_GROUP_ID) VALUES(302, 'administration.direction.plan');
INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_GROUP_ID) VALUES(303, 'administration.direction.plan');
INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_GROUP_ID) VALUES(304, 'administration.direction.plan');
INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_GROUP_ID) VALUES(305, 'administration.direction.plan');
INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_GROUP_ID) VALUES(306, 'administration.direction.plan');
INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_GROUP_ID) VALUES(307, 'administration.direction.plan');
INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_GROUP_ID) VALUES(308, 'administration.direction.plan');
INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_GROUP_ID) VALUES(309, 'administration.direction.plan');

-- crisis management
INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_GROUP_ID) VALUES(250, 'unit.manager');

-- PEM
INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_USERNAME) VALUES(408, 'admin');	-- prevent others to access
INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_USERNAME) VALUES(409, '21036');	-- Coty
INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_USERNAME) VALUES(409, 'coty.cheung');	-- Coty
INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_USERNAME) VALUES(409, '01368');	-- Patrick Yu (Assist to COO)
INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_USERNAME) VALUES(409, '21026');	-- Florence Ng (HR)
INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_USERNAME) VALUES(410, 'alex.lan');
INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_USERNAME) VALUES(410, 'iris.chuah');
INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_USERNAME) VALUES(410, 'rachel.yeung');
INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_USERNAME) VALUES(411, 'alex.lan');
INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_USERNAME) VALUES(411, 'iris.chuah');
INSERT INTO AC_DOCUMENT_ACCESS(AC_DOCUMENT_ID, AC_USERNAME) VALUES(411, 'rachel.yeung');
