ALTER TABLE CHAP_AREA
 DROP PRIMARY KEY CASCADE;
DROP TABLE CHAP_AREA CASCADE CONSTRAINTS;

CREATE TABLE CHAP_AREA
(
	ID 				NUMBER NOT NULL,
	CHAPID 			VARCHAR2(50),
	WRD_CODE 		VARCHAR2(100),
	MOTH_CODE 		VARCHAR2(100),
	RELCODE 		VARCHAR2(100),
	OTHER 			VARCHAR2(4000),
	REF_PATNO 		VARCHAR2(50),
	REF_CHAPID 		VARCHAR2(50),
	REF_CHAPNAME 	VARCHAR2(100),
	CREATE_DATE 	DATE default SYSDATE,
	CREATE_USER 	VARCHAR2(50) default 'SYSTEM',
	MODIFIED_DATE 	DATE default SYSDATE,
	MODIFIED_USER 	VARCHAR2(50) default 'SYSTEM',
	ENABLE			NUMBER(1,0) default 1 ,
	PRIMARY KEY (ID)
);

COMMIT;