ALTER TABLE CO_ATTACH_DOCUMENTS
 DROP PRIMARY KEY CASCADE;
DROP TABLE CO_ATTACH_DOCUMENTS CASCADE CONSTRAINTS;

CREATE TABLE CO_ATTACH_DOCUMENTS
(
 CO_MODULE_CODE VARCHAR2(20 BYTE) NOT NULL ENABLE,	-- education, lmc
 CO_KEY_ID NUMBER(*,0) NOT NULL,
 CO_KEY2_ID NUMBER(*,0) NOT NULL,
 CO_DOCUMENT_ID NUMBER(*,0) DEFAULT 1,
 CO_DOCUMENT_DESC VARCHAR2(200 BYTE) NOT NULL,
 CO_CREATED_DATE DATE DEFAULT SYSDATE,
 CO_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CO_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CO_MODULE_CODE, CO_KEY_ID, CO_KEY2_ID, CO_DOCUMENT_ID)
);