ALTER TABLE CO_APPROVAL_REQUEST
 DROP PRIMARY KEY CASCADE;
DROP TABLE CO_APPROVAL_REQUEST CASCADE CONSTRAINTS;

CREATE TABLE CO_APPROVAL_REQUEST
(
 CO_MODULE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,	-- education, lmc
 CO_APPROVAL_CATEGORY VARCHAR2(10 BYTE) NOT NULL ENABLE,
 CO_REQUEST_ID NUMBER(*,0) NOT NULL ENABLE,
 CO_REQUEST_SITE_CODE VARCHAR2(10 BYTE) NOT NULL,
 CO_REQUEST_DEPARTMENT_CODE VARCHAR2(10 BYTE) NOT NULL,
 CO_REQUEST_USER_TYPE VARCHAR2(10 BYTE) NOT NULL,	-- staff, patient
 CO_REQUEST_USER_ID VARCHAR2(20 BYTE) NOT NULL,
 CO_APPROVE_SITE_CODE VARCHAR2(10 BYTE) NOT NULL,
 CO_APPROVE_DEPARTMENT_CODE VARCHAR2(10 BYTE) NOT NULL,
 CO_APPROVE_USER_TYPE VARCHAR2(10 BYTE) NOT NULL,	-- staff, patient
 CO_APPROVE_USER_ID VARCHAR2(20 BYTE) NOT NULL,
 CO_APPROVE_STATUS VARCHAR2(1 BYTE) DEFAULT 'O',		-- O - Open, A - Approval, R - Reject, C - Cancel
 CO_EXTERNAL_ID NUMBER(*,0) NOT NULL ENABLE,
 CO_CREATED_DATE DATE DEFAULT SYSDATE,
 CO_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CO_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CO_REQUEST_ID, CO_REQUEST_SITE_CODE, CO_REQUEST_DEPARTMENT_CODE, CO_REQUEST_USER_TYPE, CO_REQUEST_USER_ID)
);
ALTER TABLE CO_APPROVAL_REQUEST ADD (
 CONSTRAINT CO_APPROVAL_REQUEST_R01
 FOREIGN KEY (CO_REQUEST_SITE_CODE)
 REFERENCES CO_SITE (CO_SITE_CODE));
ALTER TABLE CO_APPROVAL_REQUEST ADD (
 CONSTRAINT CO_APPROVAL_REQUEST_R02
 FOREIGN KEY (CO_REQUEST_DEPARTMENT_CODE)
 REFERENCES CO_DEPARTMENTS (CO_DEPARTMENT_CODE));
ALTER TABLE CO_APPROVAL_REQUEST ADD (
 CONSTRAINT CO_APPROVAL_REQUEST_R03
 FOREIGN KEY (CO_APPROVE_SITE_CODE)
 REFERENCES CO_SITE (CO_SITE_CODE));
ALTER TABLE CO_APPROVAL_REQUEST ADD (
 CONSTRAINT CO_APPROVAL_REQUEST_R04
 FOREIGN KEY (CO_APPROVE_DEPARTMENT_CODE)
 REFERENCES CO_DEPARTMENTS (CO_DEPARTMENT_CODE));