ALTER TABLE CO_APPROVAL_USER
 DROP PRIMARY KEY CASCADE;
DROP TABLE CO_APPROVAL_USER CASCADE CONSTRAINTS;

CREATE TABLE CO_APPROVAL_USER
(
 CO_MODULE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,	-- education, lmc
 CO_CATEGORY VARCHAR2(10 BYTE) NOT NULL ENABLE,
 CO_REQUEST_SITE_CODE VARCHAR2(10 BYTE) DEFAULT 'hkah',	-- hkah, twah
 CO_REQUEST_DEPARTMENT_CODE VARCHAR2(10 BYTE) NULL,
 CO_REQUEST_USER_TYPE VARCHAR2(10 BYTE) NULL,
 CO_REQUEST_USER_ID VARCHAR2(20 BYTE) NULL,
 CO_REQUEST_GROUP_ID VARCHAR2(30 BYTE) DEFAULT 'ALL',
 CO_APPROVAL_SITE_CODE VARCHAR2(10 BYTE) DEFAULT 'hkah',	-- hkah, twah
 CO_APPROVAL_DEPARTMENT_CODE VARCHAR2(10 BYTE) NULL,
 CO_APPROVAL_USER_TYPE VARCHAR2(10 BYTE) NOT NULL,	-- staff, patient
 CO_APPROVAL_USER_ID VARCHAR2(20 BYTE) NOT NULL,
 CO_APPROVAL_PRIORITY NUMBER(*,0) DEFAULT 1, 
 CO_CREATED_DATE DATE DEFAULT SYSDATE,
 CO_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CO_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_ENABLED NUMBER(*,0) DEFAULT 1
);
ALTER TABLE CO_APPROVAL_USER ADD (
 CONSTRAINT CO_APPROVAL_USER_R01
 FOREIGN KEY (CO_REQUEST_SITE_CODE)
 REFERENCES CO_SITE (CO_SITE_CODE));
ALTER TABLE CO_APPROVAL_USER ADD (
 CONSTRAINT CO_APPROVAL_USER_R02
 FOREIGN KEY (CO_REQUEST_DEPARTMENT_CODE)
 REFERENCES CO_DEPARTMENTS (CO_DEPARTMENT_CODE));
