ALTER TABLE CO_DOCTORS
 DROP PRIMARY KEY CASCADE;
DROP TABLE CO_DOCTORS CASCADE CONSTRAINTS;

CREATE TABLE CO_DOCTORS
(
 CO_DOCTOR_ID NUMBER(*,0) NOT NULL ENABLE,
 CO_LASTNAME VARCHAR2(50 BYTE) NULL,
 CO_FIRSTNAME VARCHAR2(60 BYTE) NULL,
 CO_CHINESENAME VARCHAR2(30 BYTE) NULL,
 CO_SEX VARCHAR2(1 BYTE) DEFAULT 'M',
 CO_DOB DATE NULL,
 CO_OFFICE_NUMBER VARCHAR2(20 BYTE) NULL,
 CO_MOBILE_NUMBER VARCHAR2(20 BYTE) NULL,
 CO_FAX_NUMBER VARCHAR2(20 BYTE) NULL,
 CO_SPECIALTY_CODE VARCHAR2(10 BYTE) NULL,
 CO_SPECIALTY_DESC VARCHAR2(50 BYTE) NULL,
 CO_DOCUMENTS VARCHAR2(1000 BYTE) NULL,
 CO_CREDENTIAL VARCHAR2(1000 BYTE) NULL,
 CO_INTEREST VARCHAR2(1000 BYTE) NULL,
 CO_CREATED_DATE DATE DEFAULT SYSDATE,
 CO_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CO_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CO_DOCTOR_ID)
);