ALTER TABLE CO_DEPARTMENT_EVENT
 DROP PRIMARY KEY CASCADE;
DROP TABLE CO_DEPARTMENT_EVENT CASCADE CONSTRAINTS;

CREATE TABLE CO_DEPARTMENT_EVENT
(
 CO_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 CO_DEPARTMENT_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 CO_MODULE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,	-- education, lmc
 CO_EVENT_ID NUMBER(*,0) NOT NULL ENABLE,
 CO_TIME_INTERVAL NUMBER(*,0) DEFAULT 1, -- by month
 CO_CREATED_DATE DATE DEFAULT SYSDATE,
 CO_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CO_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CO_SITE_CODE, CO_DEPARTMENT_CODE, CO_MODULE_CODE, CO_EVENT_ID)
);
ALTER TABLE CO_DEPARTMENT_EVENT ADD (
 CONSTRAINT CO_DEPARTMENT_EVENT_R01
 FOREIGN KEY (CO_DEPARTMENT_CODE)
 REFERENCES CO_DEPARTMENTS (CO_DEPARTMENT_CODE));
ALTER TABLE CO_DEPARTMENT_EVENT ADD (
 CONSTRAINT CO_DEPARTMENT_EVENT_R02
 FOREIGN KEY (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID)
 REFERENCES CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID));
