ALTER TABLE CO_DOCSCAN_DOCUMENT
 DROP PRIMARY KEY CASCADE;
DROP TABLE CO_DOCSCAN_DOCUMENT CASCADE CONSTRAINTS;

CREATE TABLE CO_DOCSCAN_DOCUMENT 
(	
 CO_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE, 
 CO_DOCSCAN_ID NUMBER(*,0) NOT NULL ENABLE,
 CO_DOCUMENT_ID NUMBER(*,0), 
 CO_IS_URL VARCHAR2(1 BYTE), 
 CO_URL VARCHAR2(400 BYTE), 
 CO_CREATED_DATE DATE DEFAULT SYSDATE, 
 CO_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM', 
 CO_MODIFIED_DATE DATE DEFAULT SYSDATE, 
 CO_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM', 
 CO_ENABLED NUMBER(*,0) DEFAULT 1, 
 PRIMARY KEY (CO_SITE_CODE, CO_DOCSCAN_ID)
);
ALTER TABLE CO_DOCSCAN_DOCUMENT ADD (
 CONSTRAINT CO_DOCSCAN_DOCUMENT_R01
 FOREIGN KEY (CO_SITE_CODE, CO_DOCSCAN_ID)
 REFERENCES CO_DOCSCAN (CO_SITE_CODE, CO_DOCSCAN_ID));