ALTER TABLE CO_DEPARTMENTS
 DROP PRIMARY KEY CASCADE;
DROP TABLE CO_DEPARTMENTS CASCADE CONSTRAINTS;

CREATE TABLE CO_DEPARTMENTS
(
 CO_DEPARTMENT_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 CO_DEPARTMENT_SHORT_DESC VARCHAR2(10 BYTE),
 CO_DEPARTMENT_DESC VARCHAR2(100 BYTE),
 CO_DEPARTMENT_CATEGORY VARCHAR2(20 BYTE),
 CO_DEPARTMENT_HEAD VARCHAR2(40 BYTE),
 CO_DEPARTMENT_SUBHEAD VARCHAR2(10 BYTE),
 CO_CREATED_DATE DATE DEFAULT SYSDATE,
 CO_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CO_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CO_DEPARTMENT_CODE)
);
ALTER TABLE CO_DEPARTMENTS ADD (
 CONSTRAINT CO_DEPARTMENT_R01
 FOREIGN KEY (CO_SITE_CODE)
 REFERENCES CO_SITE (CO_SITE_CODE));

SET DEFINE OFF
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE,CO_DEPARTMENT_DESC) values ('ACCT','ACCOUNTING DEPARTMENT');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE,CO_DEPARTMENT_DESC) values ('ADMI','ADMINISTRATION');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE,CO_DEPARTMENT_DESC) values ('CCS','CHILD CARE SERVICE');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE,CO_DEPARTMENT_DESC) values ('CHAP','CHAPLAINCY');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE,CO_DEPARTMENT_DESC) values ('COO','CHIEF OPERATING OFFICER');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE,CO_DEPARTMENT_DESC) values ('CSR','CENTRAL SUPPLY ROOM');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE,CO_DEPARTMENT_DESC) values ('DELP','DEVELOPMENT & COMMUNITY RELATIONS');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE,CO_DEPARTMENT_DESC) values ('DENT','DENTAL DEPARTMENT');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE,CO_DEPARTMENT_DESC) values ('DI','DIAGNOSTIC IMAGING DEPARTMENT');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE,CO_DEPARTMENT_DESC) values ('EDUCATION','STAFF EDUCATION DEPARTMENT');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE,CO_DEPARTMENT_DESC) values ('FNAN','FINANCE DEPARTMENT');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE,CO_DEPARTMENT_DESC) values ('FOOD','FOOD & DIETITIC SERVICE DEPARTMENT');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE,CO_DEPARTMENT_DESC) values ('GODN','GODOWN');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE,CO_DEPARTMENT_DESC) values ('HEMO','HEMODIALYSIS CENTRE');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE,CO_DEPARTMENT_DESC) values ('HR','HUMAN RESOURCES DEPARTMENT');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE,CO_DEPARTMENT_DESC) values ('HSKG','HOUSEKEEPING DEPARTMENT');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE,CO_DEPARTMENT_DESC) values ('IC','INFECTION CONTROL DEPARTMENT');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE,CO_DEPARTMENT_DESC) values ('IM','INFORMATION MANAGEMENT');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE,CO_DEPARTMENT_DESC) values ('LAB','CLINICAL LABORATORY');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE,CO_DEPARTMENT_DESC) values ('LSMC','LIFESTYLE MANAGEMENT CENTER');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE,CO_DEPARTMENT_DESC) values ('MANT','MAINTENANCE DEPARTMENT');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE,CO_DEPARTMENT_DESC) values ('MATERIAL','MATERIAL MANAGEMENT DEPARTMENT');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE,CO_DEPARTMENT_DESC) values ('MR','MEDICAL RECORD DEPARTMENT');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE,CO_DEPARTMENT_DESC) values ('MRKT','MARKETING & BUSINESS DEVELOPMENT');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE,CO_DEPARTMENT_DESC) values ('NA','Not Applicable');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE,CO_DEPARTMENT_DESC) values ('NUAD','NURSING ADMINISTRATION');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE,CO_DEPARTMENT_DESC) values ('OPD','OUT-PATIENT DEPARTMENT');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE,CO_DEPARTMENT_DESC) values ('OR','OPERATING ROOM');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE,CO_DEPARTMENT_DESC) values ('OSH','OSH');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE,CO_DEPARTMENT_DESC) values ('PABD','PATIENT BUSINESS DEPARTMENT');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE,CO_DEPARTMENT_DESC) values ('PHAR','PHARMACY');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE,CO_DEPARTMENT_DESC) values ('PHYS','PHYSICIAN');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE,CO_DEPARTMENT_DESC) values ('PI','PERFORMANCE IMPROVEMENT DEPARTMENT');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE,CO_DEPARTMENT_DESC) values ('PRES','PRESIDENT OFFICE');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE,CO_DEPARTMENT_DESC) values ('PROMT','PROJECT MANAGEMENT');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE,CO_DEPARTMENT_DESC) values ('PURC','PURCHASING DEPARTMENT');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE,CO_DEPARTMENT_DESC) values ('RHAB','REHABILIATION CENTER');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE,CO_DEPARTMENT_DESC) values ('SAFE','SAFETY DEPARTMENT');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE,CO_DEPARTMENT_DESC) values ('U100','UNIT 100');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE,CO_DEPARTMENT_DESC) values ('U200','UNIT 200');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE,CO_DEPARTMENT_DESC) values ('U300','UNIT 300');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE,CO_DEPARTMENT_DESC) values ('U400','UNIT 400');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE,CO_DEPARTMENT_DESC) values ('UCLK','UNIT CLERK');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE,CO_DEPARTMENT_DESC) values ('VPAD','ADMINISTRATION');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE,CO_DEPARTMENT_DESC) values ('VPMD','VP FOR MEDICAL');
