ALTER TABLE CO_ENROLLMENT
 DROP PRIMARY KEY CASCADE;
DROP TABLE CO_ENROLLMENT CASCADE CONSTRAINTS;

CREATE TABLE CO_ENROLLMENT
(
 CO_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 CO_MODULE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,	-- education, lmc
 CO_EVENT_ID NUMBER(*,0) NOT NULL ENABLE,
 CO_SCHEDULE_ID NUMBER(*,0) NULL,
 CO_ENROLL_ID NUMBER(*,0) NOT NULL ENABLE,
 CO_USER_TYPE VARCHAR2(10 BYTE) NOT NULL,	-- staff, patient
 CO_USER_ID VARCHAR2(20 BYTE) NOT NULL,
 CO_ENROLL_NO NUMBER(*,0) DEFAULT 1,
 CO_ATTEND_DATE DATE DEFAULT SYSDATE,
 CO_ATTEND_DATE2 DATE NULL,
 CO_ATTEND_STATUS INTEGER DEFAULT 0,
 CO_ASSESSMENT_PASS_DATE DATE NULL,
 CO_REMARK VARCHAR2(100 BYTE) NULL,
 CO_CREATED_DATE DATE DEFAULT SYSDATE,
 CO_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CO_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_ENROLL_ID)
);
ALTER TABLE CO_ENROLLMENT ADD (
 CONSTRAINT CO_ENROLLMENT_R01
 FOREIGN KEY (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID)
 REFERENCES CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID));