ALTER TABLE CO_EVENT_TYPES
 DROP PRIMARY KEY CASCADE;
DROP TABLE CO_EVENT_TYPES CASCADE CONSTRAINTS;

CREATE TABLE CO_EVENT_TYPES
(
 CO_LEVEL NUMBER(*,0) DEFAULT 1,
 CO_PARENT_EVENT_TYPE VARCHAR2(20 BYTE) DEFAULT 'ROOT',
 CO_EVENT_TYPE VARCHAR2(20 BYTE) NOT NULL,
 CO_EVENT_DESC VARCHAR2(100 BYTE) NOT NULL,
 CO_CREATED_DATE DATE DEFAULT SYSDATE,
 CO_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CO_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CO_LEVEL, CO_PARENT_EVENT_TYPE, CO_EVENT_TYPE, CO_EVENT_DESC)
);

INSERT INTO CO_EVENT_TYPES (CO_LEVEL, CO_EVENT_TYPE, CO_EVENT_DESC) VALUES (1, 'seminar', 'Seminar');
INSERT INTO CO_EVENT_TYPES (CO_LEVEL, CO_EVENT_TYPE, CO_EVENT_DESC) VALUES (1, 'newstart', 'Newstart');
INSERT INTO CO_EVENT_TYPES (CO_LEVEL, CO_EVENT_TYPE, CO_EVENT_DESC) VALUES (1, 'funfit', 'Funfit');
INSERT INTO CO_EVENT_TYPES (CO_LEVEL, CO_EVENT_TYPE, CO_EVENT_DESC) VALUES (1, 'health van', 'Health Van');

INSERT INTO CO_EVENT_TYPES (CO_LEVEL, CO_PARENT_EVENT_TYPE, CO_EVENT_TYPE, CO_EVENT_DESC) VALUES (2, 'newstart', 'workshop', 'Workshop');
INSERT INTO CO_EVENT_TYPES (CO_LEVEL, CO_PARENT_EVENT_TYPE, CO_EVENT_TYPE, CO_EVENT_DESC) VALUES (2, 'newstart', 'ns club', 'NS Club');
INSERT INTO CO_EVENT_TYPES (CO_LEVEL, CO_PARENT_EVENT_TYPE, CO_EVENT_TYPE, CO_EVENT_DESC) VALUES (2, 'newstart', 'long program', 'Long Program');
INSERT INTO CO_EVENT_TYPES (CO_LEVEL, CO_PARENT_EVENT_TYPE, CO_EVENT_TYPE, CO_EVENT_DESC) VALUES (2, 'newstart', 'day program', 'Day Program');
INSERT INTO CO_EVENT_TYPES (CO_LEVEL, CO_PARENT_EVENT_TYPE, CO_EVENT_TYPE, CO_EVENT_DESC) VALUES (2, 'newstart', 'corporate', 'Corporate');

INSERT INTO CO_EVENT_TYPES (CO_LEVEL, CO_PARENT_EVENT_TYPE, CO_EVENT_TYPE, CO_EVENT_DESC) VALUES (2, 'funfit', 'children', 'Children');
INSERT INTO CO_EVENT_TYPES (CO_LEVEL, CO_PARENT_EVENT_TYPE, CO_EVENT_TYPE, CO_EVENT_DESC) VALUES (2, 'funfit', 'adult', 'Adult');

INSERT INTO CO_EVENT_TYPES (CO_LEVEL, CO_PARENT_EVENT_TYPE, CO_EVENT_TYPE, CO_EVENT_DESC) VALUES (2, 'health van', 'estate', 'Estate');
INSERT INTO CO_EVENT_TYPES (CO_LEVEL, CO_PARENT_EVENT_TYPE, CO_EVENT_TYPE, CO_EVENT_DESC) VALUES (2, 'health van', 'community', 'Community');
INSERT INTO CO_EVENT_TYPES (CO_LEVEL, CO_PARENT_EVENT_TYPE, CO_EVENT_TYPE, CO_EVENT_DESC) VALUES (2, 'health van', 'center', 'Center');
INSERT INTO CO_EVENT_TYPES (CO_LEVEL, CO_PARENT_EVENT_TYPE, CO_EVENT_TYPE, CO_EVENT_DESC) VALUES (2, 'health van', 'school', 'School');