ALTER TABLE CO_EVENT
 DROP PRIMARY KEY CASCADE;
DROP TABLE CO_EVENT CASCADE CONSTRAINTS;

CREATE TABLE CO_EVENT
(
 CO_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 CO_MODULE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,	-- education, lmc
 CO_EVENT_ID NUMBER(*,0) NOT NULL ENABLE,
 CO_EVENT_DESC VARCHAR2(100 BYTE),
 CO_EVENT_SHORT_DESC VARCHAR2(50 BYTE) NULL,
 CO_EVENT_CATEGORY VARCHAR2(10 BYTE),	-- [compulsory], [inservice], [ce]Continuous Education, [other]
 CO_EVENT_TYPE VARCHAR2(20 BYTE),	-- [class] - Sit-In, [online] - On-Line, [self] learn
 CO_EVENT_TYPE2 VARCHAR2(20 BYTE),
 CO_DEPARTMENT_CODE VARCHAR2(10 BYTE) NULL,
 CO_EVENT_REMARK VARCHAR2(100 BYTE) NULL,
 CO_EVENT_REMARK2 VARCHAR2(100 BYTE) NULL,
 CO_REQUIRE_ASSESSMENT_PASS VARCHAR2(1 BYTE) DEFAULT 'N',
 CO_NON_HOSP_COURSE VARCHAR2(1 BYTE) DEFAULT 'N',
 CO_CREATED_DATE DATE DEFAULT SYSDATE,
 CO_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CO_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID)
);
ALTER TABLE CO_EVENT ADD (
 CONSTRAINT CO_EVENT_R01
 FOREIGN KEY (CO_SITE_CODE)
 REFERENCES CO_SITE (CO_SITE_CODE));


-- TWAH
-- mandatory
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('twah', 'education', 1010, NULL, 'SHARE Review', 'compulsory', 'online');
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('twah', 'education', 1020, NULL, 'Basic Infection Control (Nursing Staff; Clinical Staff)', 'compulsory', 'online');
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('twah', 'education', 1025, NULL, 'Basic Infection Control (Ancillary Staff; Other Staff)', 'compulsory', 'online');
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('twah', 'education', 1030, NULL, 'Manual Handling (Nursing Staff)', 'compulsory', 'online');
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('twah', 'education', 1070, NULL, 'Manual Handling (Clinical Staff; Ancillary Staff; Other Staff)', 'compulsory', 'online');
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('twah', 'education', 1080, NULL, 'Medical Gas Safety', 'compulsory', 'online');
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE, CO_EVENT_REMARK) VALUES ('twah', 'education', 1040, NULL, 'Cardio-pulmonary Resuscitation + AED (RN)', 'compulsory', 'class', 'A sit-in 3-hour training session taken in alternate years by RN.');
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE, CO_EVENT_REMARK) VALUES ('twah', 'education', 1045, NULL, 'Cardio-pulmonary Resuscitation + AED (EN, HCA, CA; Clinical Staff)', 'compulsory', 'class', 'A sit-in 3-hour training session taken in alternate years by EN, HCA, CA; Clinical Staff.');
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('twah', 'education', 1060, NULL, 'Fire Safety (Nursing Staff; Clinical Staff; Ancillary Staff; Other Staff)', 'compulsory', 'class');

-- new staff
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE, CO_EVENT_REMARK) VALUES ('twah', 'education', 1110, NULL, 'Hospital Orientation (New Staff) ', 'compulsory', 'class', 'A sit-in 4-hour information session scheduled monthly for New Staff.');
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('twah', 'education', 1120, NULL, 'SHARE Seminar (New Staff)', 'compulsory', 'class');

-- meeting room booking
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_EVENT_DESC, CO_EVENT_CATEGORY) VALUES ('twah', 'booking', 1002, '1F MILLER HALL MEETING ROOM', 'meeting');
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_EVENT_DESC, CO_EVENT_CATEGORY) VALUES ('twah', 'booking', 1003, '3F BREAST CENTER MEETING ROOM', 'meeting');
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_EVENT_DESC, CO_EVENT_CATEGORY) VALUES ('twah', 'booking', 1004, '7F MILLER HALL CONFERENCE ROOM', 'conference');