ALTER TABLE CO_INFORMATION_CATEGORY
 DROP PRIMARY KEY CASCADE;
DROP TABLE CO_INFORMATION_CATEGORY CASCADE CONSTRAINTS;

CREATE TABLE CO_INFORMATION_CATEGORY
(
 CO_INFORMATION_CATEGORY VARCHAR2(20 BYTE) NOT NULL ENABLE,
 CO_INFORMATION_CATEGORY_DESC VARCHAR2(200 BYTE) NULL,
 CO_FUNCTION_ID VARCHAR2(50 BYTE) NULL,
 CO_CREATED_DATE DATE DEFAULT SYSDATE,
 CO_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CO_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CO_INFORMATION_CATEGORY)
);

SET DEFINE OFF;
INSERT INTO CO_INFORMATION_CATEGORY(CO_INFORMATION_CATEGORY, CO_INFORMATION_CATEGORY_DESC, CO_FUNCTION_ID) VALUES('Departmental Report', 'Departmental Report', 'function.info.type.departmentalReport');
INSERT INTO CO_INFORMATION_CATEGORY(CO_INFORMATION_CATEGORY, CO_INFORMATION_CATEGORY_DESC, CO_FUNCTION_ID) VALUES('Health Assessment', 'Health Assessment', 'function.info.type.healthAssessment');
INSERT INTO CO_INFORMATION_CATEGORY(CO_INFORMATION_CATEGORY, CO_INFORMATION_CATEGORY_DESC, CO_FUNCTION_ID) VALUES('InPatient', 'InPatient', 'function.info.type.inPatient');
INSERT INTO CO_INFORMATION_CATEGORY(CO_INFORMATION_CATEGORY, CO_INFORMATION_CATEGORY_DESC, CO_FUNCTION_ID) VALUES('Key PI', 'Key PI', 'function.info.type.keyPI');
INSERT INTO CO_INFORMATION_CATEGORY(CO_INFORMATION_CATEGORY, CO_INFORMATION_CATEGORY_DESC, CO_FUNCTION_ID) VALUES('NURSING', 'Nursing', 'function.info.type.nursing');
INSERT INTO CO_INFORMATION_CATEGORY(CO_INFORMATION_CATEGORY, CO_INFORMATION_CATEGORY_DESC, CO_FUNCTION_ID) VALUES('Others', 'Others', 'function.info.type.others');
INSERT INTO CO_INFORMATION_CATEGORY(CO_INFORMATION_CATEGORY, CO_INFORMATION_CATEGORY_DESC, CO_FUNCTION_ID) VALUES('OutPatient', 'OutPatient', 'function.info.type.outPatient');
INSERT INTO CO_INFORMATION_CATEGORY(CO_INFORMATION_CATEGORY, CO_INFORMATION_CATEGORY_DESC, CO_FUNCTION_ID) VALUES('RISK MANAGEMENT', 'Risk Management', 'function.info.type.riskManagement');
INSERT INTO CO_INFORMATION_CATEGORY(CO_INFORMATION_CATEGORY, CO_INFORMATION_CATEGORY_DESC, CO_FUNCTION_ID) VALUES('accreditation', 'Accreditation', 'function.info.type.accreditation');
INSERT INTO CO_INFORMATION_CATEGORY(CO_INFORMATION_CATEGORY, CO_INFORMATION_CATEGORY_DESC, CO_FUNCTION_ID) VALUES('admin', 'Portal Administration', 'function.info.type.admin');
INSERT INTO CO_INFORMATION_CATEGORY(CO_INFORMATION_CATEGORY, CO_INFORMATION_CATEGORY_DESC, CO_FUNCTION_ID) VALUES('admin.plans', 'Direction & Plans for HKAH', 'function.info.type.admin.plans');
INSERT INTO CO_INFORMATION_CATEGORY(CO_INFORMATION_CATEGORY, CO_INFORMATION_CATEGORY_DESC, CO_FUNCTION_ID) VALUES('admin.plans.2007', 'Direction & Plans for HKAH 2007', 'function.info.type.admin.plans.2007');
INSERT INTO CO_INFORMATION_CATEGORY(CO_INFORMATION_CATEGORY, CO_INFORMATION_CATEGORY_DESC, CO_FUNCTION_ID) VALUES('admin.plans.2008', 'Direction & Plans for HKAH 2008', 'function.info.type.admin.plans.2008');
INSERT INTO CO_INFORMATION_CATEGORY(CO_INFORMATION_CATEGORY, CO_INFORMATION_CATEGORY_DESC, CO_FUNCTION_ID) VALUES('admin.plans.2009', 'Direction & Plans for HKAH 2009', 'function.info.type.admin.plans.2009');
INSERT INTO CO_INFORMATION_CATEGORY(CO_INFORMATION_CATEGORY, CO_INFORMATION_CATEGORY_DESC, CO_FUNCTION_ID) VALUES('admin.plans.2010', 'Direction & Plans for HKAH 2010', 'function.info.type.admin.plans.2010');
INSERT INTO CO_INFORMATION_CATEGORY(CO_INFORMATION_CATEGORY, CO_INFORMATION_CATEGORY_DESC, CO_FUNCTION_ID) VALUES('admin.plans.annual', 'Direction & Plans for HKAH Annual Plan', 'function.info.type.admin.plans.annual');
INSERT INTO CO_INFORMATION_CATEGORY(CO_INFORMATION_CATEGORY, CO_INFORMATION_CATEGORY_DESC, CO_FUNCTION_ID) VALUES('admin.plans.business', 'Direction & Plans for HKAH Business & Operation Plan', 'function.info.type.admin.plans.business');
INSERT INTO CO_INFORMATION_CATEGORY(CO_INFORMATION_CATEGORY, CO_INFORMATION_CATEGORY_DESC, CO_FUNCTION_ID) VALUES('admin.plans.medical', 'Direction & Plans for HKAH Medical Program & Marketing Plan', 'function.info.type.admin.plans.medical');
INSERT INTO CO_INFORMATION_CATEGORY(CO_INFORMATION_CATEGORY, CO_INFORMATION_CATEGORY_DESC, CO_FUNCTION_ID) VALUES('admin.plans.meeting', 'Direction & Plans for HKAH Long Range Meeting', 'function.info.type.admin.plans.meeting');
INSERT INTO CO_INFORMATION_CATEGORY(CO_INFORMATION_CATEGORY, CO_INFORMATION_CATEGORY_DESC, CO_FUNCTION_ID) VALUES('adventist.corner', 'Adventist Corner', 'function.info.type.adventist.corner');
INSERT INTO CO_INFORMATION_CATEGORY(CO_INFORMATION_CATEGORY, CO_INFORMATION_CATEGORY_DESC, CO_FUNCTION_ID) VALUES('application', 'Back Office Application', 'function.info.type.application');
INSERT INTO CO_INFORMATION_CATEGORY(CO_INFORMATION_CATEGORY, CO_INFORMATION_CATEGORY_DESC, CO_FUNCTION_ID) VALUES('briefRoom.execOrder', 'Briefing Room Executive Order', 'function.info.type.briefRoom.execOrder');
INSERT INTO CO_INFORMATION_CATEGORY(CO_INFORMATION_CATEGORY, CO_INFORMATION_CATEGORY_DESC, CO_FUNCTION_ID) VALUES('briefRoom.minutes', 'Briefing Room Minutes', 'function.info.type.briefRoom.minutes');
INSERT INTO CO_INFORMATION_CATEGORY(CO_INFORMATION_CATEGORY, CO_INFORMATION_CATEGORY_DESC, CO_FUNCTION_ID) VALUES('briefRoom.survey', 'Briefing Room Survey', 'function.info.type.briefRoom.survey');
INSERT INTO CO_INFORMATION_CATEGORY(CO_INFORMATION_CATEGORY, CO_INFORMATION_CATEGORY_DESC, CO_FUNCTION_ID) VALUES('corporate', 'Corporate', 'function.info.type.corporate');
INSERT INTO CO_INFORMATION_CATEGORY(CO_INFORMATION_CATEGORY, CO_INFORMATION_CATEGORY_DESC, CO_FUNCTION_ID) VALUES('crisis and disaster', 'Crisis and Disaster', 'function.info.type.crisisAndDisaster');
INSERT INTO CO_INFORMATION_CATEGORY(CO_INFORMATION_CATEGORY, CO_INFORMATION_CATEGORY_DESC, CO_FUNCTION_ID) VALUES('donoation', 'Donation', 'function.info.type.donoation');
INSERT INTO CO_INFORMATION_CATEGORY(CO_INFORMATION_CATEGORY, CO_INFORMATION_CATEGORY_DESC, CO_FUNCTION_ID) VALUES('fees', 'Fees', 'function.info.type.fees');
INSERT INTO CO_INFORMATION_CATEGORY(CO_INFORMATION_CATEGORY, CO_INFORMATION_CATEGORY_DESC, CO_FUNCTION_ID) VALUES('hr.benefits', 'Human Resources Employee Benefits', 'function.info.type.hr.benefits');
INSERT INTO CO_INFORMATION_CATEGORY(CO_INFORMATION_CATEGORY, CO_INFORMATION_CATEGORY_DESC, CO_FUNCTION_ID) VALUES('hr.calendar', 'Human Resources Calendar', 'function.info.type.hr.calendar');
INSERT INTO CO_INFORMATION_CATEGORY(CO_INFORMATION_CATEGORY, CO_INFORMATION_CATEGORY_DESC, CO_FUNCTION_ID) VALUES('hr.contactHR', 'Human Resources Contact HR', 'function.info.type.hr.contactHR');
INSERT INTO CO_INFORMATION_CATEGORY(CO_INFORMATION_CATEGORY, CO_INFORMATION_CATEGORY_DESC, CO_FUNCTION_ID) VALUES('hr.directory', 'Human Resources Directory', 'function.info.type.hr.directory');
INSERT INTO CO_INFORMATION_CATEGORY(CO_INFORMATION_CATEGORY, CO_INFORMATION_CATEGORY_DESC, CO_FUNCTION_ID) VALUES('hr.evaluation', 'Human Resources Performance Evaluation', 'function.info.type.hr.evaluation');
INSERT INTO CO_INFORMATION_CATEGORY(CO_INFORMATION_CATEGORY, CO_INFORMATION_CATEGORY_DESC, CO_FUNCTION_ID) VALUES('hr.forms', 'Human Resources Forms & Documents', 'function.info.type.hr.forms');
INSERT INTO CO_INFORMATION_CATEGORY(CO_INFORMATION_CATEGORY, CO_INFORMATION_CATEGORY_DESC, CO_FUNCTION_ID) VALUES('hr.jobs', 'Human Resources Jobs', 'function.info.type.hr.jobs');
INSERT INTO CO_INFORMATION_CATEGORY(CO_INFORMATION_CATEGORY, CO_INFORMATION_CATEGORY_DESC, CO_FUNCTION_ID) VALUES('hr.news', 'Human Resources News & Events', 'function.info.type.hr.news');
INSERT INTO CO_INFORMATION_CATEGORY(CO_INFORMATION_CATEGORY, CO_INFORMATION_CATEGORY_DESC, CO_FUNCTION_ID) VALUES('hr.payroll', 'Human Resources Payroll', 'function.info.type.hr.payroll');
INSERT INTO CO_INFORMATION_CATEGORY(CO_INFORMATION_CATEGORY, CO_INFORMATION_CATEGORY_DESC, CO_FUNCTION_ID) VALUES('hr.policies', 'Human Resources Policies', 'function.info.type.hr.policies');
INSERT INTO CO_INFORMATION_CATEGORY(CO_INFORMATION_CATEGORY, CO_INFORMATION_CATEGORY_DESC, CO_FUNCTION_ID) VALUES('hr.training', 'Human Resources Training & Development', 'function.info.type.hr.training');
INSERT INTO CO_INFORMATION_CATEGORY(CO_INFORMATION_CATEGORY, CO_INFORMATION_CATEGORY_DESC, CO_FUNCTION_ID) VALUES('informed consent', 'Informed Consent', 'function.info.type.informedConsent');
INSERT INTO CO_INFORMATION_CATEGORY(CO_INFORMATION_CATEGORY, CO_INFORMATION_CATEGORY_DESC, CO_FUNCTION_ID) VALUES('marketing', 'Marketing', 'function.info.type.marketing');
INSERT INTO CO_INFORMATION_CATEGORY(CO_INFORMATION_CATEGORY, CO_INFORMATION_CATEGORY_DESC, CO_FUNCTION_ID) VALUES('minutes', 'Minutes', 'function.info.type.minutes');
INSERT INTO CO_INFORMATION_CATEGORY(CO_INFORMATION_CATEGORY, CO_INFORMATION_CATEGORY_DESC, CO_FUNCTION_ID) VALUES('newsletter', 'Newsletter', 'function.info.type.newsletter');
INSERT INTO CO_INFORMATION_CATEGORY(CO_INFORMATION_CATEGORY, CO_INFORMATION_CATEGORY_DESC, CO_FUNCTION_ID) VALUES('nursing', 'Nursing', 'function.info.type.nursing');
INSERT INTO CO_INFORMATION_CATEGORY(CO_INFORMATION_CATEGORY, CO_INFORMATION_CATEGORY_DESC, CO_FUNCTION_ID) VALUES('physician', 'Physician', 'function.info.type.physician');
INSERT INTO CO_INFORMATION_CATEGORY(CO_INFORMATION_CATEGORY, CO_INFORMATION_CATEGORY_DESC, CO_FUNCTION_ID) VALUES('policy.chap', 'Poicy Chaplaincy', 'function.info.type.policy.chap');
INSERT INTO CO_INFORMATION_CATEGORY(CO_INFORMATION_CATEGORY, CO_INFORMATION_CATEGORY_DESC, CO_FUNCTION_ID) VALUES('regulations', 'Regulations', 'function.info.type.regulations');
INSERT INTO CO_INFORMATION_CATEGORY(CO_INFORMATION_CATEGORY, CO_INFORMATION_CATEGORY_DESC, CO_FUNCTION_ID) VALUES('roster', 'Roster', 'function.info.type.roster');
INSERT INTO CO_INFORMATION_CATEGORY(CO_INFORMATION_CATEGORY, CO_INFORMATION_CATEGORY_DESC, CO_FUNCTION_ID) VALUES('Report', 'Report', 'function.info.type.report');

