ALTER TABLE CO_INFORMATION_PAGE
 DROP PRIMARY KEY CASCADE;
DROP TABLE CO_INFORMATION_PAGE CASCADE CONSTRAINTS;

CREATE TABLE CO_INFORMATION_PAGE
(
 CO_INFORMATION_PAGE_ID NUMBER(*,0) NOT NULL ENABLE,
 CO_INFORMATION_CATEGORY VARCHAR2(20 BYTE) NOT NULL,	-- NURSING, ROSTER, ADMIN
 CO_INFORMATION_TYPE VARCHAR2(20 BYTE) NOT NULL,	-- PROGRAM, DOCUMENT
 CO_DESCRIPTION VARCHAR2(200 BYTE) NULL,
 CO_FUNCTION_ID VARCHAR2(50 BYTE) NULL,
 CO_FUNCTION_URL VARCHAR2(100 BYTE) NULL,
 CO_DOCUMENT_ID NUMBER(*,0) NULL,
 CO_DOCUMENT_URL VARCHAR2(200 BYTE) NULL,
 CO_DOCUMENT_WITH_FOLDER VARCHAR2(1 BYTE) DEFAULT 'N',
 CO_DOCUMENT_LATEST_FILE VARCHAR2(1 BYTE) DEFAULT 'Y',
 CO_DOCUMENT_SHOW_SUB_FOLDER VARCHAR2(1 BYTE) DEFAULT 'Y',
 CO_DOCUMENT_ONLY_CURRENT_YEAR VARCHAR2(1 BYTE) DEFAULT 'N',
 CO_DOCUMENT_SHOW_POINT_FORM VARCHAR2(1 BYTE) DEFAULT 'N',
 CO_FOLDER_SHOW_ROOT VARCHAR2(1 BYTE) DEFAULT 'Y', -- Y: show root folder
 CO_TARGET_CONTENT VARCHAR2(10 BYTE) DEFAULT 'content',
 CO_INTRANET_ONLY VARCHAR2(1 BYTE) DEFAULT 'N',
 CO_ALLOW_ADMIN VARCHAR2(1 BYTE) DEFAULT 'Y',
 CO_EXPAND_FOLDER VARCHAR2(1 BYTE) DEFAULT 'N',
 CO_CREATED_DATE DATE DEFAULT SYSDATE,
 CO_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CO_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY)
);
SET DEFINE OFF
-- Nursing
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_FUNCTION_ID, CO_FUNCTION_URL) VALUES (1, 'nursing', 'PROGRAM', 'IP Overall Occupancy (Daily)', 'function.bed.occupancy.view', '../hat/bed_census.jsp');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_FUNCTION_ID, CO_FUNCTION_URL) VALUES (2, 'nursing', 'PROGRAM', 'IP Overall Occupancy (Yearly)', 'function.bed.occupancy.view', '../hat/bed_census_yearly.jsp');
--INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_FUNCTION_ID, CO_FUNCTION_URL) VALUES (3, 'nursing', 'PROGRAM', 'IP Daily Bed Overview', 'function.inpatientBed.view', '../hat/bed_booking.jsp');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_FUNCTION_ID, CO_FUNCTION_URL) VALUES (4, 'nursing', 'PROGRAM', 'Pre-Admission', 'function.admission.view', '../registration/admission_list.jsp');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID, CO_DOCUMENT_WITH_FOLDER) VALUES (5, 'nursing', 'DOCUMENT', 'OB Bookings (current)', '33', 'Y');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID, CO_DOCUMENT_WITH_FOLDER, CO_DOCUMENT_LATEST_FILE, CO_DOCUMENT_SHOW_SUB_FOLDER, CO_DOCUMENT_ONLY_CURRENT_YEAR, CO_DOCUMENT_SHOW_POINT_FORM) VALUES (6, 'nursing', 'DOCUMENT', 'OB Bookings (archive)', '34', 'Y', 'N', 'Y', 'N', 'N');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID) VALUES (7, 'nursing', 'DOCUMENT', 'OB Deposit Refund List', '52');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID) VALUES (8, 'nursing', 'DOCUMENT', 'Supervisor', '25');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID) VALUES (9, 'nursing', 'DOCUMENT', 'Bed Class Distribution', '70');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_FUNCTION_ID, CO_FUNCTION_URL) VALUES (10, 'nursing', 'PROGRAM', 'OB Delivery Room', 'function.nurob.dr.list', '../nurob/deliveryRomm_list.jsp');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_FUNCTION_ID, CO_FUNCTION_URL) VALUES (11, 'nursing', 'PROGRAM', 'OB Admission Letter for Maternity', 'function.nurob.admltr.list', '../nurob/admltr_list.jsp');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_FUNCTION_ID, CO_FUNCTION_URL) VALUES (12, 'nursing', 'PROGRAM', 'DNT TK', 'function.dnt.tk.list', '../dental/Track_list.jsp');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_FUNCTION_ID, CO_FUNCTION_URL) VALUES (13, 'nursing', 'PROGRAM', 'Forward Scanning', 'function.fs.admin', '../forwardScanning/index.jsp');

-- Roster
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID) VALUES (1, 'roster', 'DOCUMENT', 'DH Duty Roster', '41');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID, CO_DOCUMENT_WITH_FOLDER, CO_DOCUMENT_LATEST_FILE, CO_DOCUMENT_SHOW_SUB_FOLDER, CO_DOCUMENT_ONLY_CURRENT_YEAR, CO_DOCUMENT_SHOW_POINT_FORM) VALUES (2, 'roster', 'DOCUMENT', 'GP Roster', '31', 'Y', 'N', 'Y', 'N', 'N');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID, CO_DOCUMENT_WITH_FOLDER, CO_DOCUMENT_LATEST_FILE, CO_DOCUMENT_SHOW_SUB_FOLDER, CO_DOCUMENT_ONLY_CURRENT_YEAR, CO_DOCUMENT_SHOW_POINT_FORM) VALUES (3, 'roster', 'DOCUMENT', 'OB & Gyn, Anes, Sur, Ped, Eye, ENT Roster', '40', 'Y', 'N', 'Y', 'N', 'N');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_FUNCTION_ID, CO_FUNCTION_URL) VALUES (4, 'roster', 'PROGRAM', 'OPD Doctor Schedule', '', '../hat/dr_schedule_1024.jsp');

-- Back Office Application
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_FUNCTION_ID, CO_FUNCTION_URL) VALUES (1, 'application', 'PROGRAM', 'Booking of meeting & Conference Room', 'function.meetingRoom.booking.list', '../admin/meetingroom_booking_list.jsp');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_FUNCTION_ID, CO_FUNCTION_URL, CO_TARGET_CONTENT) VALUES (2, 'application', 'PROGRAM', 'group.crm', 'function.client.view', '../common/leftright_portal.jsp?category=group.crm', 'bigcontent');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_FUNCTION_ID, CO_FUNCTION_URL) VALUES (3, 'application', 'PROGRAM', 'Doctor Database', 'function.doctor.list', '../doctor/apply_list.jsp');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_FUNCTION_ID, CO_FUNCTION_URL) VALUES (4, 'application', 'PROGRAM', 'prompt.leave', 'function.eleave.list', '../eleave/apply_list.jsp');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_FUNCTION_ID, CO_FUNCTION_URL) VALUES (5, 'application', 'PROGRAM', '', 'function.projectSummary.list', '../pmp/summary_list.jsp');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_FUNCTION_ID, CO_FUNCTION_URL) VALUES (6, 'application', 'PROGRAM', '', 'function.news.list', '../admin/news_list.jsp');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_FUNCTION_ID, CO_FUNCTION_URL) VALUES (7, 'application', 'PROGRAM', '', 'function.paperclip.list', '../paperclip/paperclip_list.jsp');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_FUNCTION_ID, CO_FUNCTION_URL) VALUES (8, 'application', 'PROGRAM', 'function.info.list', 'function.info.list', '../admin/information_page_list.jsp');	-- should have access restriction for different users
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_FUNCTION_ID, CO_FUNCTION_URL) VALUES (9, 'application', 'PROGRAM', 'group.ghc', 'function.ghc.client.view', '../ghc/apply_list.jsp');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_FUNCTION_ID, CO_FUNCTION_URL) VALUES (10, 'application', 'PROGRAM', 'group.callBack', 'function.callList.client.list', '../callBack/callList.jsp');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_FUNCTION_ID, CO_FUNCTION_URL) VALUES (11, 'application', 'PROGRAM', '', 'function.yearOfEmployee.list', '../hr/yearOfEmployee_list.jsp');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_FUNCTION_ID, CO_FUNCTION_URL) VALUES (12, 'application', 'PROGRAM', 'Health Assessment', 'function.haa.list', '../healthAssessment/check_list.jsp');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_FUNCTION_ID, CO_FUNCTION_URL) VALUES (13, 'application', 'PROGRAM', '', 'function.newHATS.run', '../hats_jnlp.jsp');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_FUNCTION_ID, CO_FUNCTION_URL) VALUES (19, 'application', 'PROGRAM', 'DI Doctor Payroll Report', 'function.di.payrollReport', '../di/incomeReport.jsp');

-- Marketing
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_URL) VALUES (1, 'marketing', 'DOCUMENT', 'Promotion', 'http://www.twah.org.hk/new/eng/promotion.htm');

-- Accreditation
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID) VALUES (1, 'accreditation', 'DOCUMENT', 'ACHS Standards - Part 1', '38');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID) VALUES (2, 'accreditation', 'DOCUMENT', 'ACHS Standards - Part 3', '39');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_URL) VALUES (3, 'accreditation', 'DOCUMENT', 'Just Done It', '\\hkim\im\Intranet\Dept\PI\ACHS\Just Done It');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID, CO_DOCUMENT_WITH_FOLDER) VALUES (4, 'accreditation', 'DOCUMENT', 'Incident Sharing (by PBO)', '32', 'Y');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID) VALUES (5, 'accreditation', 'DOCUMENT', 'Infections Disease', '30');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID, CO_DOCUMENT_WITH_FOLDER, CO_DOCUMENT_LATEST_FILE, CO_DOCUMENT_SHOW_SUB_FOLDER, CO_DOCUMENT_ONLY_CURRENT_YEAR, CO_DOCUMENT_SHOW_POINT_FORM, CO_FOLDER_SHOW_ROOT) VALUES (6, 'accreditation', 'DOCUMENT', 'Accreditation', '238', 'Y', 'N', 'Y', 'N', 'N', 'N');

-- Minutes
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID, CO_DOCUMENT_WITH_FOLDER, CO_DOCUMENT_LATEST_FILE, CO_DOCUMENT_SHOW_SUB_FOLDER, CO_DOCUMENT_ONLY_CURRENT_YEAR, CO_DOCUMENT_SHOW_POINT_FORM) VALUES (1, 'minutes', 'DOCUMENT', 'Committee Minutes 2010', '202', 'Y', 'N', 'Y', 'N', 'N');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID, CO_DOCUMENT_WITH_FOLDER, CO_DOCUMENT_LATEST_FILE, CO_DOCUMENT_SHOW_SUB_FOLDER, CO_DOCUMENT_ONLY_CURRENT_YEAR, CO_DOCUMENT_SHOW_POINT_FORM) VALUES (2, 'minutes', 'DOCUMENT', 'Committee Minutes 2009', '201', 'Y', 'N', 'Y', 'N', 'N');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_URL, CO_TARGET_CONTENT) VALUES (3, 'minutes', 'DOCUMENT', 'Highlights of AC', '\\hkim\im\Intranet\Library\General\AC Messages\index.doc', '_blank');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID, CO_DOCUMENT_WITH_FOLDER, CO_DOCUMENT_LATEST_FILE, CO_DOCUMENT_SHOW_SUB_FOLDER, CO_DOCUMENT_ONLY_CURRENT_YEAR, CO_DOCUMENT_SHOW_POINT_FORM) VALUES (4, 'minutes', 'DOCUMENT', 'Department Head', '51', 'Y', 'N', 'Y', 'N', 'N');

-- Admin
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_FUNCTION_ID, CO_FUNCTION_URL) VALUES (1, 'admin', 'PROGRAM', '', 'function.user.list', '../admin/user_list.jsp');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_FUNCTION_ID, CO_FUNCTION_URL) VALUES (2, 'admin', 'PROGRAM', '', 'function.staff.list', '../admin/staff_list.jsp');
--INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_FUNCTION_ID, CO_FUNCTION_URL) VALUES (3, 'admin', 'PROGRAM', '', 'function.function.list', '../admin/function_list.jsp');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_FUNCTION_ID, CO_FUNCTION_URL) VALUES (4, 'admin', 'PROGRAM', '', 'function.accessControl.list', '../admin/access_control_list.jsp');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_FUNCTION_ID, CO_FUNCTION_URL) VALUES (5, 'admin', 'PROGRAM', '', 'function.document.list', '../admin/document_list.htm');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_FUNCTION_ID, CO_FUNCTION_URL) VALUES (6, 'admin', 'PROGRAM', '', 'function.info.list', '../admin/information_page_list.jsp');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_FUNCTION_ID, CO_FUNCTION_URL) VALUES (7, 'admin', 'PROGRAM', '', 'function.ssoUser.list', '../sso/user_list.jsp');

-- IN Patient
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID, CO_DOCUMENT_SHOW_POINT_FORM) VALUES (1, 'InPatient', 'DOCUMENT', 'Monthly IP Report', '26', 'Y');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID, CO_DOCUMENT_SHOW_POINT_FORM) VALUES (2, 'InPatient', 'DOCUMENT', 'Daily IP', '29', 'Y');

-- Revised by ck on 2010/01/12, using std report
--INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_FUNCTION_ID, CO_FUNCTION_URL) VALUES (3, 'InPatient', 'PROGRAM', 'Inpatient Hospital Days (Midnight + Sameday)', 'function.mis.census.ipd', '../hat/census_ipd_sameday.jsp');
--INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_FUNCTION_ID, CO_FUNCTION_URL) VALUES (4, 'InPatient', 'PROGRAM', 'Inpatient Hospital Days (Midnight)', 'function.mis.census.ipd', '../hat/census_ipd_midnight.jsp');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_FUNCTION_ID, CO_FUNCTION_URL) VALUES (3, 'InPatient', 'PROGRAM', 'Inpatient Hospital Days (Midnight + Sameday)', 'function.mis.census.year', '../hat/census_mis_count.jsp?g=IPD'||chr(38)||'n=Wholeday');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_FUNCTION_ID, CO_FUNCTION_URL) VALUES (4, 'InPatient', 'PROGRAM', 'Inpatient Hospital Days (Midnight)', 'function.mis.census.year', '../hat/census_mis_count.jsp?g=IPD'||chr(38)||'n=Midnight');
-- Revised by ck on 05/12/2009,replace endo report.
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_FUNCTION_ID, CO_FUNCTION_URL) VALUES (5, 'InPatient', 'PROGRAM', 'Operating Room Procedure Census (Exclude Endoscopy)', 'function.mis.census.year', '../hat/census_mis_count.jsp?g=OT'||chr(38)||'n=NonEndo');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_FUNCTION_ID, CO_FUNCTION_URL) VALUES (6, 'InPatient', 'PROGRAM', 'Operating Room Procedure Census (Endoscopy Only)', 'function.mis.census.year', '../hat/census_mis_count.jsp?g=OT'||chr(38)||'n=Endo');

-- OUT Patient
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID, CO_DOCUMENT_SHOW_POINT_FORM) VALUES (1, 'OutPatient', 'DOCUMENT', 'Monthly OP Report', '27', 'Y');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID, CO_DOCUMENT_SHOW_POINT_FORM) VALUES (2, 'OutPatient', 'DOCUMENT', 'Monthly OP (by Doctors)', '42', 'Y');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID, CO_DOCUMENT_SHOW_POINT_FORM) VALUES (3, 'OutPatient', 'DOCUMENT', 'Monthly OP (by Doctors & indicating New/ Return Patient)', '43', 'Y');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID, CO_DOCUMENT_SHOW_POINT_FORM) VALUES (4, 'OutPatient', 'DOCUMENT', 'Monthly OP (Japanese Patient)', '44', 'Y');

INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID, CO_DOCUMENT_WITH_FOLDER, CO_DOCUMENT_LATEST_FILE, CO_DOCUMENT_SHOW_SUB_FOLDER, CO_DOCUMENT_ONLY_CURRENT_YEAR, CO_DOCUMENT_SHOW_POINT_FORM) VALUES (5, 'OutPatient', 'DOCUMENT', 'Monthly OP 05-08 (All)', '85', 'Y', 'N', 'Y', 'N', 'Y');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID, CO_DOCUMENT_WITH_FOLDER, CO_DOCUMENT_LATEST_FILE, CO_DOCUMENT_SHOW_SUB_FOLDER, CO_DOCUMENT_ONLY_CURRENT_YEAR, CO_DOCUMENT_SHOW_POINT_FORM) VALUES (6, 'OutPatient', 'DOCUMENT', 'Monthly OP 09-11 (All)', '86', 'Y', 'N', 'Y', 'N', 'Y');

INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID, CO_DOCUMENT_WITH_FOLDER, CO_DOCUMENT_LATEST_FILE, CO_DOCUMENT_SHOW_SUB_FOLDER, CO_DOCUMENT_ONLY_CURRENT_YEAR, CO_DOCUMENT_SHOW_POINT_FORM) VALUES (7, 'OutPatient', 'DOCUMENT', 'Daily OP (by doctor & shift)', '50', 'Y', 'N', 'Y', 'N', 'Y');
--INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_FUNCTION_ID, CO_FUNCTION_URL) VALUES (8, 'OutPatient', 'PROGRAM', 'Outpatient Census', 'function.mis.census.opd', '../hat/census_opd.jsp');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_FUNCTION_ID, CO_FUNCTION_URL) VALUES (8, 'OutPatient', 'PROGRAM', 'Outpatient Census', 'function.mis.census.year', '../hat/census_mis_count.jsp?g=OPD'||chr(38)||'n=DailyCount');

-- Others (created by ck on 12/11/2009)
--INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_FUNCTION_ID, CO_FUNCTION_URL) VALUES (1, 'Others', 'PROGRAM', 'LAB Referral Census', 'function.mis.census.lab', '../hat/census_lab_refer.jsp');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_FUNCTION_ID, CO_FUNCTION_URL) VALUES (1, 'Others', 'PROGRAM', 'LAB Referral Census', 'function.mis.census.year', '../hat/census_mis_count.jsp?g=LAB'||chr(38)||'n=Referral');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_FUNCTION_ID, CO_FUNCTION_URL) VALUES (2, 'Others', 'PROGRAM', 'DI CyberKnife Census (No. of Patient)', 'function.mis.census.year', '../hat/census_mis_count.jsp?g=DI'||chr(38)||'n=CyberKnife1');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_FUNCTION_ID, CO_FUNCTION_URL) VALUES (3, 'Others', 'PROGRAM', 'DI CyberKnife Census(No. of Treatment)', 'function.mis.census.year', '../hat/census_mis_count.jsp?g=DI'||chr(38)||'n=CyberKnife2');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_FUNCTION_ID, CO_FUNCTION_URL) VALUES (4, 'Others', 'PROGRAM', 'DI Interventional Radiology Census', 'function.mis.census.year', '../hat/census_mis_count.jsp?g=DI'||chr(38)||'n=Intervention');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_FUNCTION_ID, CO_FUNCTION_URL) VALUES (5, 'Others', 'PROGRAM', 'DI Referral Census', 'function.mis.census.year', '../hat/census_mis_count.jsp?g=DI'||chr(38)||'n=Referral');

INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_FUNCTION_ID, CO_FUNCTION_URL) VALUES (6, 'Others', 'PROGRAM', 'Revenue By Dept By Specialty (Inpatient)', 'function.mis.census.year', '../hat/census_revenue.jsp?n=2');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_FUNCTION_ID, CO_FUNCTION_URL) VALUES (7, 'Others', 'PROGRAM', 'Revenue By Dept By Specialty (Outpatient)', 'function.mis.census.year', '../hat/census_revenue.jsp?n=1');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_FUNCTION_ID, CO_FUNCTION_URL) VALUES (8, 'Others', 'PROGRAM', 'Revenue By Dept By Specialty (IP+OP)', 'function.mis.census.year', '../hat/census_revenue.jsp?n=3');
--20091223, cathlab report
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_FUNCTION_ID, CO_FUNCTION_URL) VALUES (9, 'Others', 'PROGRAM', 'Cath-LAB Procedure By Doctor', 'function.mis.census.year', '../hat/census_clab_procedure.jsp');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_FUNCTION_ID, CO_FUNCTION_URL) VALUES (10, 'Others', 'PROGRAM', 'Cath-LAB Procedure By Date', 'function.mis.census.year', '../hat/census_mis_count.jsp?g=CLAB'||chr(38)||'n=Procedure');

INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID) VALUES (1, 'donoation', 'DOCUMENT', 'Donation Funds & Expenses Analysis', '98');

-- Monthly Departmental Report
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID) VALUES (1, 'Departmental Report', 'DOCUMENT', 'Monthly Departmental Report', '28');

-- Key Performance Indicator
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID) VALUES (1, 'Key PI', 'DOCUMENT', 'Key Performance Indicator', '55');

-- Health Assessment
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID) VALUES (1, 'Health Assessment', 'DOCUMENT', 'Type of Physical Check', '45');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID) VALUES (2, 'Health Assessment', 'DOCUMENT', 'Individual Physician', '46');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID) VALUES (3, 'Health Assessment', 'DOCUMENT', 'GP/SP', '47');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID) VALUES (4, 'Health Assessment', 'DOCUMENT', 'Corporate', '48');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID) VALUES (5, 'Health Assessment', 'DOCUMENT', 'Optional Test', '49');

-- risk management
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID, CO_DOCUMENT_WITH_FOLDER) VALUES (1, 'RISK MANAGEMENT', 'DOCUMENT', 'HSI Sharing Minutes', '72', 'Y');

--Report
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_FUNCTION_ID, CO_FUNCTION_URL) VALUES(2, 'Report', 'PROGRAM', 'Colonoscopy - Caecum not reached reason report','function.colonoscopy.report', '../hat/colono_report.jsp');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_FUNCTION_ID, CO_FUNCTION_URL) VALUES(3, 'Report', 'PROGRAM', 'OT Cancelled Appointment Report','function.ot.cancelled.appointment.report', '../hat/opRoom_cancelled_Appointment.jsp');



-- informed consent
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID, CO_DOCUMENT_WITH_FOLDER, CO_DOCUMENT_LATEST_FILE, CO_DOCUMENT_SHOW_SUB_FOLDER, CO_DOCUMENT_ONLY_CURRENT_YEAR, CO_DOCUMENT_SHOW_POINT_FORM) VALUES (1, 'informed consent', 'DOCUMENT', 'Informed Consent', '73', 'Y', 'N', 'Y', 'N', 'N');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID, CO_DOCUMENT_WITH_FOLDER, CO_DOCUMENT_LATEST_FILE, CO_DOCUMENT_SHOW_SUB_FOLDER, CO_DOCUMENT_ONLY_CURRENT_YEAR, CO_DOCUMENT_SHOW_POINT_FORM) VALUES (2, 'informed consent', 'DOCUMENT', 'Fact Sheets', '71', 'Y', 'N', 'Y', 'N', 'N');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_URL, CO_TARGET_CONTENT) VALUES (3, 'informed consent', 'DOCUMENT', 'Helpful Resources (Click this link to access fact sheets if not listed above)', 'http://www21.ha.org.hk/smartpatient/en/operationstests_procedures.html', '_blank');

-- fee
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID) VALUES (1, 'fees', 'DOCUMENT', 'Package charges - HKAH', '94');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID) VALUES (2, 'fees', 'DOCUMENT', 'Package charges - TWAH', '95');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID) VALUES (3, 'fees', 'DOCUMENT', 'EVSS Package w/ Requriemnt', '69');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID, CO_DOCUMENT_WITH_FOLDER, CO_DOCUMENT_LATEST_FILE, CO_DOCUMENT_SHOW_SUB_FOLDER, CO_DOCUMENT_ONLY_CURRENT_YEAR, CO_DOCUMENT_SHOW_POINT_FORM) VALUES (4, 'fees', 'DOCUMENT', 'Doctor''s Consultation Charges - Outpatient', '93', 'N', 'Y', 'N', 'N', 'N');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_URL) VALUES (5, 'fees', 'DOCUMENT', 'In patient', 'http://www.hkah.org.hk/new/eng/hospitalization_fi.htm');

-- brief room
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID, CO_DOCUMENT_WITH_FOLDER, CO_DOCUMENT_LATEST_FILE, CO_DOCUMENT_SHOW_SUB_FOLDER, CO_DOCUMENT_ONLY_CURRENT_YEAR, CO_DOCUMENT_SHOW_POINT_FORM) VALUES (1, 'briefRoom.minutes', 'DOCUMENT', 'Committee Minutes 2010', '202', 'Y', 'N', 'Y', 'N', 'N');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID, CO_DOCUMENT_WITH_FOLDER, CO_DOCUMENT_LATEST_FILE, CO_DOCUMENT_SHOW_SUB_FOLDER, CO_DOCUMENT_ONLY_CURRENT_YEAR, CO_DOCUMENT_SHOW_POINT_FORM) VALUES (2, 'briefRoom.minutes', 'DOCUMENT', 'Committee Minutes 2009', '201', 'Y', 'N', 'Y', 'N', 'N');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_URL, CO_TARGET_CONTENT) VALUES (3, 'briefRoom.minutes', 'DOCUMENT', 'Highlights of AC', '\\hkim\im\Intranet\Library\General\AC Messages\index.doc', '_blank');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID, CO_DOCUMENT_WITH_FOLDER, CO_DOCUMENT_LATEST_FILE, CO_DOCUMENT_SHOW_SUB_FOLDER, CO_DOCUMENT_ONLY_CURRENT_YEAR, CO_DOCUMENT_SHOW_POINT_FORM) VALUES (4, 'briefRoom.minutes', 'DOCUMENT', 'Department Head', '51', 'Y', 'N', 'Y', 'N', 'N');

-- corporate (Long Range Strategic Plan)
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID) VALUES (1, 'admin.plans', 'DOCUMENT', 'Long Range Strategic Plan 2010', '245');

INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID) VALUES (1, 'admin.plans.meeting', 'DOCUMENT', 'HKAH Discussion on Strength', '295');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID) VALUES (2, 'admin.plans.meeting', 'DOCUMENT', 'HKAH Discussion on Weakness', '296');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID) VALUES (3, 'admin.plans.meeting', 'DOCUMENT', 'HKAH Discussion on Opportunity', '297');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID) VALUES (4, 'admin.plans.meeting', 'DOCUMENT', 'HKAH Discussion on Threats', '298');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID) VALUES (5, 'admin.plans.meeting', 'DOCUMENT', 'HKAH Discussion on IT, Facilities', '299');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID) VALUES (6, 'admin.plans.meeting', 'DOCUMENT', 'HKAH Discussion on Customer Service', '300');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID) VALUES (7, 'admin.plans.meeting', 'DOCUMENT', 'HKAH Discussion on Brand', '301');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID) VALUES (8, 'admin.plans.meeting', 'DOCUMENT', 'HKAH Discussion on Human Resource', '302');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID) VALUES (9, 'admin.plans.meeting', 'DOCUMENT', 'Power point presented by Dr. Ken Tsang<br />Sharing of Developments at Neighboring Private Hospital', '303');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID) VALUES (10, 'admin.plans.meeting', 'DOCUMENT', 'TWAH Discussion on Strength', '304');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID) VALUES (11, 'admin.plans.meeting', 'DOCUMENT', 'TWAH Discussion on Weakness', '305');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID) VALUES (12, 'admin.plans.meeting', 'DOCUMENT', 'TWAH Discussion on Opportunity', '306');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID) VALUES (13, 'admin.plans.meeting', 'DOCUMENT', 'TWAH Discussion on Threats', '307');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID) VALUES (14, 'admin.plans.meeting', 'DOCUMENT', 'Power point presented by Dr. Peter Lo<br />Sharing of Developments at Neighboring Private Hospital', '308');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID) VALUES (15, 'admin.plans.meeting', 'DOCUMENT', 'Power point presented by Dr. Chan Lung Wai<br />Sharing of Developments at Neighboring Private Hospital', '309');

INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID) VALUES (1, 'admin.plans', 'DOCUMENT', 'Long Range Strategic Plan 2010', '245');
-- corporate (HKAH Business & Operation Plan)
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID) VALUES (1, 'admin.plans.business', 'DOCUMENT', '2010', '244');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID) VALUES (2, 'admin.plans.business', 'DOCUMENT', 'HKAH Operation Report (1Q 2010)', '310');

-- corporate (HKAH Medical Program & Marketing Plan)
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID) VALUES (1, 'admin.plans.medical', 'DOCUMENT', '(2009-2010)', '246');

-- 2010 annual plans
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_URL, CO_TARGET_CONTENT) VALUES (1, 'admin.plans.annual', 'DOCUMENT', 'Annual Plan Retreat Presentation', 'file://hkim/im/Intranet/News/AnnualPlanRetreatPresentation/Content For Annual Plan Retreat Presentation.doc', '_blank');

-- 2009
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID) VALUES (1, 'admin.plans.2009', 'DOCUMENT', 'Long Range Strategic Plan Minutes in June 2009', '235');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID) VALUES (2, 'admin.plans.2009', 'DOCUMENT', 'Long Range Strategic Plan Minutes in December 2009', '234');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID) VALUES (2, 'admin.plans.2009', 'DOCUMENT', 'LongYear-end Summary Report of Incident 2009', '236');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID) VALUES (3, 'admin.plans.2009', 'DOCUMENT', 'Operation Report for 2009', '247');
-- 2008
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID) VALUES (1, 'admin.plans.2008', 'DOCUMENT', 'Long Range Strategic Plan - Executive Summary', '221');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID) VALUES (2, 'admin.plans.2008', 'DOCUMENT', 'Long Range Strategic Plan - Strategic Elements', '222');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID) VALUES (4, 'admin.plans.2008', 'DOCUMENT', 'Long Range Strategic Plan - Implementation Plan', '224');
-- 2007
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID) VALUES (1, 'admin.plans.2007', 'DOCUMENT', 'TWAH - presentation', '211');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID) VALUES (2, 'admin.plans.2007', 'DOCUMENT', 'TWAH Strategic Plan', '212');

INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID, CO_DOCUMENT_WITH_FOLDER, CO_DOCUMENT_LATEST_FILE, CO_DOCUMENT_SHOW_SUB_FOLDER, CO_DOCUMENT_ONLY_CURRENT_YEAR, CO_DOCUMENT_SHOW_POINT_FORM) VALUES (1, 'briefRoom.survey', 'DOCUMENT', 'Patient Satisfaction Survey (with patients�� comments)', '101', 'Y', 'N', 'Y', 'N', 'N');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID, CO_DOCUMENT_WITH_FOLDER, CO_DOCUMENT_LATEST_FILE, CO_DOCUMENT_SHOW_SUB_FOLDER, CO_DOCUMENT_ONLY_CURRENT_YEAR, CO_DOCUMENT_SHOW_POINT_FORM) VALUES (2, 'briefRoom.survey', 'DOCUMENT', 'Patient Satisfaction survey (quantitative data)', '102', 'Y', 'N', 'Y', 'N', 'N');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID, CO_DOCUMENT_WITH_FOLDER, CO_DOCUMENT_LATEST_FILE, CO_DOCUMENT_SHOW_SUB_FOLDER, CO_DOCUMENT_ONLY_CURRENT_YEAR, CO_DOCUMENT_SHOW_POINT_FORM) VALUES (3, 'briefRoom.survey', 'DOCUMENT', 'Year End Summary for PSS', '103', 'Y', 'N', 'Y', 'N', 'N');

-- newsletter
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID, CO_DOCUMENT_WITH_FOLDER, CO_DOCUMENT_LATEST_FILE, CO_DOCUMENT_SHOW_SUB_FOLDER, CO_DOCUMENT_ONLY_CURRENT_YEAR, CO_DOCUMENT_SHOW_POINT_FORM) VALUES (1, 'newsletter', 'DOCUMENT', 'Pulse', '131', 'Y', 'N', 'Y', 'N', 'N');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID, CO_DOCUMENT_WITH_FOLDER, CO_DOCUMENT_LATEST_FILE, CO_DOCUMENT_SHOW_SUB_FOLDER, CO_DOCUMENT_ONLY_CURRENT_YEAR, CO_DOCUMENT_SHOW_POINT_FORM) VALUES (2, 'newsletter', 'DOCUMENT', 'Staff Newsletter', '132', 'Y', 'N', 'Y', 'N', 'N');

-- human resource
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_URL) VALUES (1, 'hr.calendar', 'DOCUMENT', 'Holidays for 2010 (Chinese)', '\\hkim\im\Intranet\HR\Calendar\2010 Holidays (C).pdf');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_URL) VALUES (2, 'hr.calendar', 'DOCUMENT', 'Holidays for 2010 (English)', '\\hkim\im\Intranet\HR\Calendar\2010 Holidays (E).pdf');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_URL) VALUES (3, 'hr.calendar', 'DOCUMENT', 'Holidays for 2009 (Chinese)', '\\hkim\im\Intranet\HR\Calendar\2009 Holidays_cn.pdf');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_URL) VALUES (4, 'hr.calendar', 'DOCUMENT', 'Holidays for 2009 (English)', '\\hkim\im\Intranet\HR\Calendar\2009 Holidays.pdf');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_URL) VALUES (5, 'hr.calendar', 'DOCUMENT', 'Holiday Record Sheet', '\\hkim\im\Intranet\HR\Calendar\Holiday Record Sheet 2010.xls');

INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_URL) VALUES (1, 'hr.benefits', 'DOCUMENT', 'Categories', '');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_URL) VALUES (2, 'hr.benefits', 'DOCUMENT', 'Continuing Education Allowance', '');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_URL) VALUES (3, 'hr.benefits', 'DOCUMENT', 'Funeral Leave', '');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_URL, CO_TARGET_CONTENT) VALUES (4, 'hr.benefits', 'DOCUMENT', 'Holidays', '\\hkim\im\Intranet\HR\Public Holiday\2010 Holidays.doc', '_blank');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_URL) VALUES (5, 'hr.benefits', 'DOCUMENT', 'Meal Discounts', '');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_URL) VALUES (6, 'hr.benefits', 'DOCUMENT', 'Medical/Dental/Vision Allowance', '');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_URL, CO_TARGET_CONTENT) VALUES (7, 'hr.benefits', 'DOCUMENT', 'Retirement - MPF & ORSO Member Briefing Sessions', '\\hkim\im\Intranet\HR\Provident Fund Schemes (MPF & ORSO) Member Briefing Sessions.doc', '_blank');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_URL) VALUES (8, 'hr.benefits', 'DOCUMENT', 'Vacation', '');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_URL) VALUES (9, 'hr.benefits', 'DOCUMENT', 'Workers�� Compensation', '');

INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_URL) VALUES (1, 'hr.forms', 'DOCUMENT', 'Employee Handbook', '\\hkim\im\Intranet\HR\Employee Handbook.pdf');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_URL) VALUES (2, 'hr.forms', 'DOCUMENT', 'Conflict of Interest', '\\hkim\im\Intranet\HR\Forms\Declaration Form2009.doc.pdf');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_URL) VALUES (3, 'hr.forms', 'DOCUMENT', 'Continuing Education Request Form', '\\hkim\im\Intranet\HR\Forms\CEFORM08.doc.pdf');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_URL) VALUES (4, 'hr.forms', 'DOCUMENT', 'Personal Record Change Form', '\\hkim\im\Intranet\HR\Forms\Change Personal Rds _2010_.doc.pdf');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_URL) VALUES (5, 'hr.forms', 'DOCUMENT', 'Travel Expenses Reimbursement Form', '\\hkim\im\Intranet\HR\Forms\Local Travel Expense Claim Form.xls.pdf');

INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_URL) VALUES (1, 'hr.jobs', 'DOCUMENT', 'HKAH', 'http://www.hkah.org.hk/new/eng/employment_vancancy.php');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_URL) VALUES (2, 'hr.jobs', 'DOCUMENT', 'TWAH', 'http://www.twah.org.hk/new/eng/employment_vancancy.php');

INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_URL) VALUES (1, 'hr.directory', 'DOCUMENT', 'Language (HKAH)', '\\hkim\im\Intranet\HR\Language Jun 2010.xls.pdf');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_URL) VALUES (2, 'hr.directory', 'DOCUMENT', 'HKAH Staff', '');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_URL) VALUES (3, 'hr.directory', 'DOCUMENT', 'TWAH Staff', '');

INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID, CO_DOCUMENT_WITH_FOLDER, CO_DOCUMENT_LATEST_FILE, CO_DOCUMENT_SHOW_SUB_FOLDER, CO_DOCUMENT_ONLY_CURRENT_YEAR, CO_DOCUMENT_SHOW_POINT_FORM) VALUES (1, 'hr.news', 'DOCUMENT', 'Staff Forum', '133', 'Y', 'N', 'Y', 'N', 'N');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID, CO_DOCUMENT_WITH_FOLDER, CO_DOCUMENT_LATEST_FILE, CO_DOCUMENT_SHOW_SUB_FOLDER, CO_DOCUMENT_ONLY_CURRENT_YEAR, CO_DOCUMENT_SHOW_POINT_FORM) VALUES (2, 'hr.news', 'DOCUMENT', 'Staff Newsletter', '132', 'Y', 'N', 'Y', 'N', 'N');

INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_URL) VALUES (1, 'hr.payroll', 'DOCUMENT', 'Pay Schedule', '\\hkim\im\Intranet\HR\PaySchedule\PaySchedule2010.pdf');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_URL) VALUES (2, 'hr.payroll', 'DOCUMENT', 'E-leave', '');

INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_URL) VALUES (1, 'hr.evaluation', 'DOCUMENT', 'Guide Notes (Chinese)', '\\hkim\im\Intranet\HR\Microsoft Word - Guidance note on employee performance evaluation (Form B)-C.pdf');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_URL) VALUES (2, 'hr.evaluation', 'DOCUMENT', 'Guide Notes (English)', '\\hkim\im\Intranet\HR\Microsoft Word - Guidance note on employee performance evaluation (Form B).pdf');

INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_URL, CO_TARGET_CONTENT) VALUES (1, 'hr.policies', 'DOCUMENT', 'Recruiting, Evaluating and Hiring', '\\hkim\im\Intranet\HR\Policy\Recruiting, Evaluating and Hiring.doc', '_blank');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_URL, CO_TARGET_CONTENT) VALUES (2, 'hr.policies', 'DOCUMENT', 'Recruiting, Promoting and Increasing salary of spouse&relatives working in AHHK', '\\hkim\im\Intranet\HR\Policy\Recruiting, Promoting and Increasing salary of spouse&relatives working in AHHK.doc', '_blank');

INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_URL, CO_TARGET_COTENT) VALUES(1, 'hr.training', 'DOCUMENT', 'Orientation Schedule 2010', '\\hkim\im\Intranet\HR\OrientationSchedule2010.pdf')

INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_URL, CO_TARGET_COTENT) VALUES(1, 'hr.contactHR', 'DOCUMENT', 'Director (Iris Chuah) .................................................................1599', 'mailto:iris.chuah@hkah.org.hk');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_URL, CO_TARGET_COTENT) VALUES(1, 'hr.contactHR', 'DOCUMENT', 'Manager (Beatrice Lam) ...........................................................8788     ', 'mailto:beatrice.lam@hkah.org.hk');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_URL, CO_TARGET_COTENT) VALUES(1, 'hr.contactHR', 'DOCUMENT', 'Secretary (Miranda Lo) .............................................................1599   ', 'mailto:miranda.lo@hkah.org.hk');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_URL, CO_TARGET_COTENT) VALUES(1, 'hr.contactHR', 'DOCUMENT', 'Human Resources Assistant (Miranda Siu) .......................... 8864                    ', 'mailto:humres@hkah.org.hk');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_URL, CO_TARGET_COTENT) VALUES(1, 'hr.contactHR', 'DOCUMENT', 'Administrative Assistant (Vicki Tong) ....................................8866             ', 'mailto:miranda.siu@hkah.org.hk');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_URL, CO_TARGET_COTENT) VALUES(1, 'hr.contactHR', 'DOCUMENT', 'Secretary(Angela Ng)................................................................1549   ', 'mailto: vicki.tong@hkah.org.hk');

-- physician
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID, CO_DOCUMENT_WITH_FOLDER, CO_DOCUMENT_LATEST_FILE, CO_DOCUMENT_SHOW_SUB_FOLDER, CO_DOCUMENT_ONLY_CURRENT_YEAR, CO_DOCUMENT_SHOW_POINT_FORM, CO_FOLDER_SHOW_ROOT) VALUES (1, 'physician', 'DOCUMENT', 'OPD Schedule Checklist', '99', 'Y', 'N', 'N', 'N', 'N', 'N');

-- crisis management
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID, CO_DOCUMENT_WITH_FOLDER, CO_DOCUMENT_LATEST_FILE, CO_DOCUMENT_SHOW_SUB_FOLDER, CO_DOCUMENT_ONLY_CURRENT_YEAR, CO_DOCUMENT_SHOW_POINT_FORM, CO_FOLDER_SHOW_ROOT) VALUES (1, 'crisis and disaster', 'DOCUMENT', 'Crisis Management Committee', '250', 'Y', 'N', 'Y', 'N', 'N', 'N');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_URL, CO_TARGET_CONTENT) VALUES (2, 'crisis and disaster', 'DOCUMENT', 'Disaster Manual', '\\hkim\im\Intranet\Library\General\Disaster Manual 261008.doc', '_blank');

-- corporate
--INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_URL, CO_TARGET_CONTENT) VALUES (1, 'corporate', 'DOCUMENT', 'Phone Directory', '\\hkim\im\Intranet\Library\General\phoneDir\content.doc', '_blank');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_URL) VALUES (2, 'corporate', 'DOCUMENT', 'Organization Chart', '\\hkim\im\Intranet\Admin\Org Chart HKAH.pdf');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID) VALUES (3, 'corporate', 'DOCUMENT', 'HKAH Floor Plan', '76');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID) VALUES (4, 'corporate', 'DOCUMENT', 'TWAH Floor Plan', '77');

-- adventist corner
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_URL, CO_TARGET_CONTENT) VALUES (1, 'adventist.corner', 'DOCUMENT', 'Highlights of Administrative Council', '\\hkim\im\Intranet\Library\General\AC Messages\AC Highlights\2010\AC Highlights May 13, 10.doc', '_blank');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_URL) VALUES (2, 'adventist.corner', 'DOCUMENT', 'Hospital Round', '/upload/hospital/273/Grand Round 100504.pdf');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_URL) VALUES (3, 'adventist.corner', 'DOCUMENT', 'Executive Order ', '/intranet/portal/news_view.jsp?newsType=executive%20order');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID, CO_DOCUMENT_WITH_FOLDER, CO_DOCUMENT_LATEST_FILE, CO_DOCUMENT_SHOW_SUB_FOLDER, CO_DOCUMENT_ONLY_CURRENT_YEAR, CO_DOCUMENT_SHOW_POINT_FORM) VALUES (4, 'adventist.corner', 'DOCUMENT', 'Staff Forum', '133', 'N', 'Y', 'N', 'N', 'N');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID, CO_DOCUMENT_WITH_FOLDER, CO_DOCUMENT_LATEST_FILE, CO_DOCUMENT_SHOW_SUB_FOLDER, CO_DOCUMENT_ONLY_CURRENT_YEAR, CO_DOCUMENT_SHOW_POINT_FORM) VALUES (5, 'adventist.corner', 'DOCUMENT', 'Staff Newsletter', '132', 'N', 'Y', 'N', 'N', 'N');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_URL, CO_TARGET_CONTENT) VALUES (6, 'adventist.corner', 'DOCUMENT', 'Staff Education Calendar', '/upload/education/70/Education%20Calendar%20for%20June.doc');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID, CO_DOCUMENT_WITH_FOLDER, CO_DOCUMENT_LATEST_FILE, CO_DOCUMENT_SHOW_SUB_FOLDER, CO_DOCUMENT_ONLY_CURRENT_YEAR, CO_DOCUMENT_SHOW_POINT_FORM) VALUES (7, 'adventist.corner', 'DOCUMENT', 'Physician Newsletter (Pulse)', '131', 'N', 'Y', 'N', 'N', 'N');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID, CO_DOCUMENT_WITH_FOLDER, CO_DOCUMENT_LATEST_FILE, CO_DOCUMENT_SHOW_SUB_FOLDER, CO_DOCUMENT_ONLY_CURRENT_YEAR, CO_DOCUMENT_SHOW_POINT_FORM) VALUES (8, 'adventist.corner', 'DOCUMENT', 'Patient Satisfaction Survey', '101', 'N', 'Y', 'N', 'N', 'N');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_URL) VALUES (9, 'adventist.corner', 'DOCUMENT', 'Daily Food Menu', '/intranet/documentManage/download.jsp?documentID=66');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID) VALUES (10, 'adventist.corner', 'DOCUMENT', 'Phone Directory', '134');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID, CO_DOCUMENT_URL, CO_TARGET_CONTENT, CO_DOCUMENT_WITH_FOLDER, CO_DOCUMENT_LATEST_FILE, CO_DOCUMENT_SHOW_SUB_FOLDER, CO_DOCUMENT_ONLY_CURRENT_YEAR, CO_DOCUMENT_SHOW_POINT_FORM) VALUES (15, 'adventist.corner', 'DOCUMENT', 'PEM accountability tool - HKAH', '408', '\\www-server\PEM\PEM accountability tool - HK.doc', '_blank', 'N', 'Y', 'N', 'N', 'N');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID, CO_DOCUMENT_URL, CO_TARGET_CONTENT, CO_DOCUMENT_WITH_FOLDER, CO_DOCUMENT_LATEST_FILE, CO_DOCUMENT_SHOW_SUB_FOLDER, CO_DOCUMENT_ONLY_CURRENT_YEAR, CO_DOCUMENT_SHOW_POINT_FORM) VALUES (16, 'adventist.corner', 'DOCUMENT', 'PEM accountability tool - TWAH', '409', '\\192.168.0.20\PEM\PEM accountability tool - TW.doc', '_blank', 'N', 'Y', 'N', 'N', 'N');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID, CO_DOCUMENT_WITH_FOLDER, CO_DOCUMENT_LATEST_FILE, CO_DOCUMENT_SHOW_SUB_FOLDER, CO_DOCUMENT_ONLY_CURRENT_YEAR, CO_DOCUMENT_SHOW_POINT_FORM) VALUES (17, 'adventist.corner', 'DOCUMENT', 'PEM accountability tool - HKAH', '410', 'N', 'Y', 'N', 'N', 'N');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID, CO_DOCUMENT_WITH_FOLDER, CO_DOCUMENT_LATEST_FILE, CO_DOCUMENT_SHOW_SUB_FOLDER, CO_DOCUMENT_ONLY_CURRENT_YEAR, CO_DOCUMENT_SHOW_POINT_FORM) VALUES (18, 'adventist.corner', 'DOCUMENT', 'PEM accountability tool - TWAH', '411', 'N', 'Y', 'N', 'N', 'N');

INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID, CO_DOCUMENT_WITH_FOLDER, CO_DOCUMENT_LATEST_FILE, CO_DOCUMENT_SHOW_SUB_FOLDER, CO_DOCUMENT_ONLY_CURRENT_YEAR, CO_DOCUMENT_SHOW_POINT_FORM) VALUES (1, 'adventist.corner.guest', 'DOCUMENT', 'PEM accountability tool - HKAH', '410', 'N', 'Y', 'N', 'N', 'N');
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID, CO_DOCUMENT_WITH_FOLDER, CO_DOCUMENT_LATEST_FILE, CO_DOCUMENT_SHOW_SUB_FOLDER, CO_DOCUMENT_ONLY_CURRENT_YEAR, CO_DOCUMENT_SHOW_POINT_FORM) VALUES (2, 'adventist.corner.guest', 'DOCUMENT', 'PEM accountability tool - TWAH', '411', 'N', 'Y', 'N', 'N', 'N');

-- regulations
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID) VALUES (1, 'regulations', 'DOCUMENT', 'Ordinance - 100511.working', '294');

-- chaplaincy resources
INSERT INTO CO_INFORMATION_PAGE (CO_INFORMATION_PAGE_ID, CO_INFORMATION_CATEGORY, CO_INFORMATION_TYPE, CO_DESCRIPTION, CO_DOCUMENT_ID, CO_DOCUMENT_WITH_FOLDER, CO_DOCUMENT_LATEST_FILE, CO_DOCUMENT_SHOW_SUB_FOLDER, CO_DOCUMENT_ONLY_CURRENT_YEAR, CO_DOCUMENT_SHOW_POINT_FORM, CO_FOLDER_SHOW_ROOT) VALUES (1, 'policy.chap', 'DOCUMENT', 'Chaplaincy', '311', 'Y', 'N', 'Y', 'N', 'N', 'N');