ALTER TABLE CO_LOCATION
 DROP PRIMARY KEY CASCADE;
DROP TABLE CO_LOCATION CASCADE CONSTRAINTS;

CREATE TABLE CO_LOCATION
(
 CO_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 CO_LOCATION_ID NUMBER(*,0) NOT NULL ENABLE,
 CO_LOCATION_DESC VARCHAR2(100 BYTE),
 CO_CREATED_DATE DATE DEFAULT SYSDATE,
 CO_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CO_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CO_LOCATION_ID)
);
INSERT INTO CO_LOCATION(CO_SITE_CODE, CO_LOCATION_ID, CO_LOCATION_DESC) VALUES('twah', 1, '1F MILLER HALL MEETING ROOM');
INSERT INTO CO_LOCATION(CO_SITE_CODE, CO_LOCATION_ID, CO_LOCATION_DESC) VALUES('twah', 2, '3F BREAST CENTER MEETING ROOM');
INSERT INTO CO_LOCATION(CO_SITE_CODE, CO_LOCATION_ID, CO_LOCATION_DESC) VALUES('twah', 3, '7F MILLER HALL CONFERENCE ROOM');