ALTER TABLE CO_NEWS_CONTENT
 DROP PRIMARY KEY CASCADE;
DROP TABLE CO_NEWS_CONTENT CASCADE CONSTRAINTS;

CREATE TABLE CO_NEWS_CONTENT
(
 CO_NEWS_ID NUMBER(*,0) NOT NULL ENABLE,
 CO_NEWS_CATEGORY VARCHAR2(20 BYTE),
 CO_NEWS_CONTENT_ID NUMBER(*,0) NOT NULL,
 CO_CONTENT VARCHAR2(3000 BYTE),
 CO_CREATED_DATE DATE DEFAULT SYSDATE,
 CO_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CO_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CO_NEWS_ID, CO_NEWS_CATEGORY, CO_NEWS_CONTENT_ID)
);
ALTER TABLE CO_NEWS_CONTENT ADD (
 CONSTRAINT CO_NEWS_CONTENT_R01
 FOREIGN KEY (CO_NEWS_ID, CO_NEWS_CATEGORY)
 REFERENCES CO_NEWS (CO_NEWS_ID, CO_NEWS_CATEGORY));