ALTER TABLE CO_STAFF_DEPARTMENTS
 DROP PRIMARY KEY CASCADE;
DROP TABLE CO_STAFF_DEPARTMENTS CASCADE CONSTRAINTS;

CREATE TABLE CO_STAFF_DEPARTMENTS
(
 CO_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 CO_STAFF_ID VARCHAR2(10 BYTE) NOT NULL,
 CO_DEPARTMENT_CODE VARCHAR2(10 BYTE) NULL,
 CO_CREATED_DATE DATE DEFAULT SYSDATE,
 CO_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CO_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CO_SITE_CODE, CO_STAFF_ID, CO_DEPARTMENT_CODE)
);
ALTER TABLE CO_STAFF_DEPARTMENTS ADD (
 CONSTRAINT CO_STAFF_DEPARTMENTS_R01
 FOREIGN KEY (CO_SITE_CODE)
 REFERENCES CO_SITE (CO_SITE_CODE));
ALTER TABLE CO_STAFF_DEPARTMENTS ADD (
 CONSTRAINT CO_STAFF_DEPARTMENTS_R02
 FOREIGN KEY (CO_SITE_CODE, CO_STAFF_ID)
 REFERENCES CO_STAFFS (CO_SITE_CODE, CO_STAFF_ID));
ALTER TABLE CO_STAFF_DEPARTMENTS ADD (
 CONSTRAINT CO_STAFF_DEPARTMENTS_R03
 FOREIGN KEY (CO_DEPARTMENT_CODE)
 REFERENCES CO_DEPARTMENTS (CO_DEPARTMENT_CODE));
