ALTER TABLE CO_STAFFS
 DROP PRIMARY KEY CASCADE;
DROP TABLE CO_STAFFS CASCADE CONSTRAINTS;

CREATE TABLE CO_STAFFS
(
 CO_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 CO_STAFF_ID VARCHAR2(10 BYTE) NOT NULL,
 CO_HOSP_NO VARCHAR2(10 BYTE) NULL,
 CO_DEPARTMENT_CODE VARCHAR2(10 BYTE) NULL,
 CO_DEPARTMENT_DESC VARCHAR2(100 BYTE),
 CO_STAFFNAME VARCHAR2(100 BYTE),
 CO_LASTNAME VARCHAR2(30 BYTE),
 CO_FIRSTNAME VARCHAR2(60 BYTE),
 CO_STATUS VARCHAR2(2 BYTE) DEFAULT 'FT',
 CO_ANNUAL_INCR DATE,
 CO_HIRE_DATE  DATE NULL,
 CO_EMAIL VARCHAR2(255 BYTE),
 CO_CATEGORY VARCHAR2(2 BYTE) NULL,     --[N]ursing,[P]aramedical,other [H]ealthcare, [o]ther grades of Staff
 CO_JOB_CODE VARCHAR2(20 BYTE),
 CO_JOB_DESCRIPTION VARCHAR2(100 BYTE),
 CO_DISPLAY_NAME VARCHAR2(200 BYTE),
 CO_POSITION_1 VARCHAR2(100 BYTE),
 CO_POSITION_2 VARCHAR2(100 BYTE),
 CO_CREATED_DATE DATE DEFAULT SYSDATE,
 CO_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CO_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CO_SITE_CODE, CO_STAFF_ID)
);
ALTER TABLE CO_STAFFS ADD (
 CONSTRAINT CO_STAFFS_R01
 FOREIGN KEY (CO_SITE_CODE)
 REFERENCES CO_SITE (CO_SITE_CODE));