ALTER TABLE CO_STAFF_EVENT_INTERVAL DROP PRIMARY KEY CASCADE;
DROP TABLE CO_STAFF_EVENT_INTERVAL CASCADE CONSTRAINTS;

CREATE TABLE CO_STAFF_EVENT_INTERVAL
(
 CO_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 CO_CATEGORY VARCHAR2(2 BYTE) NULL,     --[N]ursing,[P]aramedical,other [H]ealthcare, [o]ther grades of Staff
 CO_MODULE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,	-- education, lmc
 CO_EVENT_ID NUMBER(*,0) NOT NULL ENABLE,
 CO_TIME_INTERVAL NUMBER(*,0) DEFAULT 12, -- by month
 CO_CREATED_DATE DATE DEFAULT SYSDATE,
 CO_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CO_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CO_SITE_CODE, CO_CATEGORY, CO_MODULE_CODE, CO_EVENT_ID)
);


ALTER TABLE CO_STAFF_EVENT_INTERVAL ADD (
 CONSTRAINT CO_STAFF_EVENT_INTERVAL_R01
 FOREIGN KEY (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID)
 REFERENCES CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID));
 
 ALTER TABLE CO_STAFFS MODIFY CO_CATEGORY VARCHAR2(2 BYTE);
