ALTER TABLE CO_SCHEDULE
 DROP PRIMARY KEY CASCADE;
DROP TABLE CO_SCHEDULE CASCADE CONSTRAINTS;

CREATE TABLE CO_SCHEDULE
(
 CO_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 CO_MODULE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,	-- education, lmc
 CO_EVENT_ID NUMBER(*,0) NOT NULL ENABLE,
 CO_SCHEDULE_ID NUMBER(*,0) NOT NULL ENABLE,
 CO_SCHEDULE_DESC VARCHAR2(500 BYTE),
 CO_SCHEDULE_START DATE DEFAULT SYSDATE,
 CO_SCHEDULE_END DATE NULL,
 CO_SCHEDULE_DURATION NUMBER(*,2),
 CO_SCHEDULE_SIZE INTEGER DEFAULT 0,
 CO_SCHEDULE_ENROLLED INTEGER DEFAULT 0,
 CO_LOCATION_ID NUMBER(*,0),
 CO_LOCATION_DESC VARCHAR2(100 BYTE),
 CO_LECTURE_DESC VARCHAR2(500 BYTE),
 CO_SCHEDULE_STATUS VARCHAR2(10 BYTE) DEFAULT 'open',	-- open, suspend, close,
 CO_CREATED_DATE DATE DEFAULT SYSDATE,
 CO_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CO_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_ENABLED INTEGER DEFAULT 1,
 CO_NEWS_ID NUMBER,
 PRIMARY KEY (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_SCHEDULE_ID)
);
ALTER TABLE CO_SCHEDULE ADD (
 CONSTRAINT CO_SCHEDULE_R01
 FOREIGN KEY (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID)
 REFERENCES CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID));
