ALTER TABLE CO_SITE
 DROP PRIMARY KEY CASCADE;
DROP TABLE CO_SITE CASCADE CONSTRAINTS;

CREATE TABLE CO_SITE
(
 CO_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 CO_SITE_DESC VARCHAR2(100 BYTE) NOT NULL,
 CO_CREATED_DATE DATE DEFAULT SYSDATE,
 CO_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CO_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CO_SITE_CODE)
);
INSERT INTO CO_SITE (CO_SITE_CODE, CO_SITE_DESC) VALUES ('hkah', 'Hong Kong Adventist Hospital');
INSERT INTO CO_SITE (CO_SITE_CODE, CO_SITE_DESC) VALUES ('twah', 'Tsuen Wan Adventist Hospital');