ALTER TABLE CO_TODO
 DROP PRIMARY KEY CASCADE;
DROP TABLE CO_TODO CASCADE CONSTRAINTS;

CREATE TABLE CO_TODO
(
 CO_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 CO_TODO_ID NUMBER(*,0) NOT NULL ENABLE,
 CO_TASK_ID NUMBER(*,0) NOT NULL ENABLE,
 CO_JOB_ID NUMBER(*,0) NOT NULL ENABLE,
 CO_CLASS_ID INTEGER NULL,
 CO_USERNAME VARCHAR2(30 BYTE),
 CO_CREATED_DATE DATE DEFAULT SYSDATE,
 CO_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CO_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CO_TODO_ID)
);
ALTER TABLE CO_TODO ADD (
 CONSTRAINT CO_TODO_R01
 FOREIGN KEY (CO_SITE_CODE)
 REFERENCES CO_SITE (CO_SITE_CODE));