ALTER TABLE CO_USERS
 DROP PRIMARY KEY CASCADE;
DROP TABLE CO_USERS CASCADE CONSTRAINTS;

CREATE TABLE CO_USERS
(
 CO_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 CO_USERNAME VARCHAR2(30 BYTE) NOT NULL,
 CO_GROUP_ID VARCHAR2(30 BYTE) NOT NULL ENABLE,
 CO_PASSWORD VARCHAR2(30 BYTE),
 CO_LASTNAME VARCHAR2(30 BYTE),
 CO_FIRSTNAME VARCHAR2(60 BYTE),
 CO_STREET VARCHAR2(100 BYTE),
 CO_POSTALCODE VARCHAR2(10 BYTE),
 CO_CITY VARCHAR2(30 BYTE),
 CO_COUNTRY VARCHAR2(30 BYTE),
 CO_LANGUAGE VARCHAR2(10 BYTE),
 CO_EMAIL VARCHAR2(255 BYTE),
 CO_TELEPHONE VARCHAR2(30 BYTE),
 CO_STAFF_YN VARCHAR2(1 BYTE) DEFAULT 'Y',
 CO_STAFF_ID VARCHAR2(10 BYTE) NULL,
 CO_REMARK_1 VARCHAR2(50 BYTE) NULL,
 CO_REMARK_2 VARCHAR2(50 BYTE) NULL,
 CO_REMARK_3 VARCHAR2(50 BYTE) NULL,
 CO_CREATED_DATE DATE DEFAULT SYSDATE,
 CO_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CO_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CO_USERNAME)
);
ALTER TABLE CO_USERS ADD (
 CONSTRAINT CO_USERS_R01
 FOREIGN KEY (CO_GROUP_ID)
 REFERENCES CO_GROUPS (CO_GROUP_ID));
