ALTER TABLE CRM_QUESTIONAIRE_ANSWER
 DROP PRIMARY KEY CASCADE;
DROP TABLE CRM_QUESTIONAIRE_ANSWER CASCADE CONSTRAINTS;

CREATE TABLE CRM_QUESTIONAIRE_ANSWER
(
 CRM_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 CRM_QUESTIONAIRE_ID NUMBER(*,0) NOT NULL ENABLE,
 CRM_QUESTIONAIRE_QID NUMBER(*,0) NOT NULL ENABLE,
 CRM_QUESTIONAIRE_AID NUMBER(*,0) NOT NULL ENABLE,
 CRM_ANSWER VARCHAR2(200 BYTE),
 CRM_CREATED_DATE DATE DEFAULT SYSDATE,
 CRM_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CRM_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID)
);
ALTER TABLE CRM_QUESTIONAIRE_ANSWER ADD (
 CONSTRAINT CRM_QUESTIONAIRE_ANSWER_R01
 FOREIGN KEY (CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID)
 REFERENCES CRM_QUESTIONAIRE_QUESTION (CRM_SITE_CODE, CRM_QUESTIONAIRE_ID,CRM_QUESTIONAIRE_QID));
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 1, 1, 1, 'Choice 1');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 1, 1, 2, 'Choice 2');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 1, 1, 3, 'Choice 3');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 1, 2, 1, 'Choice 1');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 1, 2, 2, 'Choice 2');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 1, 2, 3, 'Choice 3');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 1, 3, 1, 'Choice 1');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 1, 3, 2, 'Choice 2');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 1, 3, 3, 'Choice 3');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 1, 4, 1, 'Choice 1');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 1, 4, 2, 'Choice 2');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 1, 4, 3, 'Choice 3');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 1, 5, 1, 'Choice 1');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 1, 5, 2, 'Choice 2');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 1, 5, 3, 'Choice 3');

INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 2, 1, 1, 'Choice 1');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 2, 1, 2, 'Choice 2');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 2, 1, 3, 'Choice 3');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 2, 2, 1, 'Choice 1');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 2, 2, 2, 'Choice 2');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 2, 2, 3, 'Choice 3');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 2, 3, 1, 'Choice 1');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 2, 3, 2, 'Choice 2');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 2, 3, 3, 'Choice 3');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 2, 4, 1, 'Choice 1');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 2, 4, 2, 'Choice 2');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 2, 4, 3, 'Choice 3');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 2, 5, 1, 'Choice 1');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 2, 5, 2, 'Choice 2');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 2, 5, 3, 'Choice 3');

INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 3, 1, 1, 'Choice 1');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 3, 1, 2, 'Choice 2');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 3, 1, 3, 'Choice 3');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 3, 2, 1, 'Choice 1');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 3, 2, 2, 'Choice 2');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 3, 2, 3, 'Choice 3');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 3, 3, 1, 'Choice 1');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 3, 3, 2, 'Choice 2');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 3, 3, 3, 'Choice 3');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 3, 4, 1, 'Choice 1');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 3, 4, 2, 'Choice 2');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 3, 4, 3, 'Choice 3');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 3, 5, 1, 'Choice 1');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 3, 5, 2, 'Choice 2');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 3, 5, 3, 'Choice 3');

INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 4, 1, 1, 'Choice 1');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 4, 1, 2, 'Choice 2');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 4, 1, 3, 'Choice 3');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 4, 2, 1, 'Choice 1');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 4, 2, 2, 'Choice 2');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 4, 2, 3, 'Choice 3');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 4, 3, 1, 'Choice 1');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 4, 3, 2, 'Choice 2');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 4, 3, 3, 'Choice 3');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 4, 4, 1, 'Choice 1');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 4, 4, 2, 'Choice 2');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 4, 4, 3, 'Choice 3');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 4, 5, 1, 'Choice 1');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 4, 5, 2, 'Choice 2');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 4, 5, 3, 'Choice 3');

INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 5, 1, 1, 'Choice 1');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 5, 1, 2, 'Choice 2');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 5, 1, 3, 'Choice 3');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 5, 2, 1, 'Choice 1');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 5, 2, 2, 'Choice 2');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 5, 2, 3, 'Choice 3');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 5, 3, 1, 'Choice 1');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 5, 3, 2, 'Choice 2');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 5, 3, 3, 'Choice 3');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 5, 4, 1, 'Choice 1');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 5, 4, 2, 'Choice 2');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 5, 4, 3, 'Choice 3');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 5, 5, 1, 'Choice 1');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 5, 5, 2, 'Choice 2');
INSERT INTO CRM_QUESTIONAIRE_ANSWER(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTIONAIRE_AID, CRM_ANSWER) VALUES ('twah', 5, 5, 3, 'Choice 3');