ALTER TABLE CRM_CLIENTS_INTEREST
 DROP PRIMARY KEY CASCADE;
DROP TABLE CRM_CLIENTS_INTEREST CASCADE CONSTRAINTS;

CREATE TABLE CRM_CLIENTS_INTEREST
(
 CRM_CLIENT_ID NUMBER(*,0) DEFAULT 1,
 CRM_INTEREST_ID NUMBER(*,0) DEFAULT 1,
 CRM_INTEREST_SEQ NUMBER(*,0) NOT NULL ENABLE,
 CRM_INTEREST_TYPE VARCHAR2(1 BYTE) DEFAULT 'B' ,	-- Ho[B]by, Ho[S]pital
 CRM_INTEREST_REMARKS VARCHAR2(100 BYTE) NULL,
 CRM_CREATED_DATE DATE DEFAULT SYSDATE,
 CRM_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CRM_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CRM_CLIENT_ID, CRM_INTEREST_ID, CRM_INTEREST_SEQ, CRM_INTEREST_TYPE)
);