ALTER TABLE CRM_FUNDS
 DROP PRIMARY KEY CASCADE;
DROP TABLE CRM_FUNDS CASCADE CONSTRAINTS;

CREATE TABLE CRM_FUNDS
(
 CRM_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 CRM_FUND_ID NUMBER(*,0) DEFAULT 1,
 CRM_FUND_DESC VARCHAR2(100 BYTE) NULL,
 CRM_CREATED_DATE DATE DEFAULT SYSDATE,
 CRM_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CRM_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CRM_FUND_ID)
);
INSERT INTO CRM_FUNDS (CRM_SITE_CODE, CRM_FUND_ID, CRM_FUND_DESC) VALUES ('twah', 1, 'Fund 1');
INSERT INTO CRM_FUNDS (CRM_SITE_CODE, CRM_FUND_ID, CRM_FUND_DESC) VALUES ('twah', 2, 'Fund 2');
INSERT INTO CRM_FUNDS (CRM_SITE_CODE, CRM_FUND_ID, CRM_FUND_DESC) VALUES ('twah', 3, 'Fund 3');
INSERT INTO CRM_FUNDS (CRM_SITE_CODE, CRM_FUND_ID, CRM_FUND_DESC) VALUES ('twah', 4, 'Fund 4');
INSERT INTO CRM_FUNDS (CRM_SITE_CODE, CRM_FUND_ID, CRM_FUND_DESC) VALUES ('twah', 5, 'Fund 5');