ALTER TABLE CRM_PHYSICAL_FIGURE_SET
 DROP PRIMARY KEY CASCADE;
DROP TABLE CRM_PHYSICAL_FIGURE_SET CASCADE CONSTRAINTS;

CREATE TABLE CRM_PHYSICAL_FIGURE_SET
(
 CRM_FIGURE_GROUP_ID NUMBER(*,0) DEFAULT 1,
 CRM_FIGURE_ID NUMBER(*,0) DEFAULT 1,
 CRM_ORDER_SEQUENCE NUMBER(*,0) DEFAULT 1,
 CRM_CREATED_DATE DATE DEFAULT SYSDATE,
 CRM_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CRM_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CRM_FIGURE_GROUP_ID, CRM_FIGURE_ID)
);
ALTER TABLE CRM_PHYSICAL_FIGURE_SET ADD (
 CONSTRAINT CRM_PHYSICAL_FIGURE_SET_R01
 FOREIGN KEY (CRM_FIGURE_GROUP_ID)
 REFERENCES CRM_PHYSICAL_FIGURE_GROUP (CRM_FIGURE_GROUP_ID));
ALTER TABLE CRM_PHYSICAL_FIGURE_SET ADD (
 CONSTRAINT CRM_PHYSICAL_FIGURE_SET_R02
 FOREIGN KEY (CRM_FIGURE_ID)
 REFERENCES CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID));

INSERT INTO CRM_PHYSICAL_FIGURE_SET (CRM_FIGURE_GROUP_ID, CRM_FIGURE_ID, CRM_ORDER_SEQUENCE) VALUES (01, 01, 01);
INSERT INTO CRM_PHYSICAL_FIGURE_SET (CRM_FIGURE_GROUP_ID, CRM_FIGURE_ID, CRM_ORDER_SEQUENCE) VALUES (01, 02, 02);
INSERT INTO CRM_PHYSICAL_FIGURE_SET (CRM_FIGURE_GROUP_ID, CRM_FIGURE_ID, CRM_ORDER_SEQUENCE) VALUES (01, 03, 03);
INSERT INTO CRM_PHYSICAL_FIGURE_SET (CRM_FIGURE_GROUP_ID, CRM_FIGURE_ID, CRM_ORDER_SEQUENCE) VALUES (01, 04, 04);
INSERT INTO CRM_PHYSICAL_FIGURE_SET (CRM_FIGURE_GROUP_ID, CRM_FIGURE_ID, CRM_ORDER_SEQUENCE) VALUES (01, 05, 05);
INSERT INTO CRM_PHYSICAL_FIGURE_SET (CRM_FIGURE_GROUP_ID, CRM_FIGURE_ID, CRM_ORDER_SEQUENCE) VALUES (01, 06, 06);
INSERT INTO CRM_PHYSICAL_FIGURE_SET (CRM_FIGURE_GROUP_ID, CRM_FIGURE_ID, CRM_ORDER_SEQUENCE) VALUES (01, 07, 07);
INSERT INTO CRM_PHYSICAL_FIGURE_SET (CRM_FIGURE_GROUP_ID, CRM_FIGURE_ID, CRM_ORDER_SEQUENCE) VALUES (01, 08, 08);
INSERT INTO CRM_PHYSICAL_FIGURE_SET (CRM_FIGURE_GROUP_ID, CRM_FIGURE_ID, CRM_ORDER_SEQUENCE) VALUES (01, 09, 09);
INSERT INTO CRM_PHYSICAL_FIGURE_SET (CRM_FIGURE_GROUP_ID, CRM_FIGURE_ID, CRM_ORDER_SEQUENCE) VALUES (01, 10, 10);
INSERT INTO CRM_PHYSICAL_FIGURE_SET (CRM_FIGURE_GROUP_ID, CRM_FIGURE_ID, CRM_ORDER_SEQUENCE) VALUES (01, 11, 11);
INSERT INTO CRM_PHYSICAL_FIGURE_SET (CRM_FIGURE_GROUP_ID, CRM_FIGURE_ID, CRM_ORDER_SEQUENCE) VALUES (01, 12, 12);
INSERT INTO CRM_PHYSICAL_FIGURE_SET (CRM_FIGURE_GROUP_ID, CRM_FIGURE_ID, CRM_ORDER_SEQUENCE) VALUES (01, 13, 13);
INSERT INTO CRM_PHYSICAL_FIGURE_SET (CRM_FIGURE_GROUP_ID, CRM_FIGURE_ID, CRM_ORDER_SEQUENCE) VALUES (01, 14, 14);
INSERT INTO CRM_PHYSICAL_FIGURE_SET (CRM_FIGURE_GROUP_ID, CRM_FIGURE_ID, CRM_ORDER_SEQUENCE) VALUES (01, 15, 15);
INSERT INTO CRM_PHYSICAL_FIGURE_SET (CRM_FIGURE_GROUP_ID, CRM_FIGURE_ID, CRM_ORDER_SEQUENCE) VALUES (01, 16, 16);
INSERT INTO CRM_PHYSICAL_FIGURE_SET (CRM_FIGURE_GROUP_ID, CRM_FIGURE_ID, CRM_ORDER_SEQUENCE) VALUES (01, 17, 17);
INSERT INTO CRM_PHYSICAL_FIGURE_SET (CRM_FIGURE_GROUP_ID, CRM_FIGURE_ID, CRM_ORDER_SEQUENCE) VALUES (01, 18, 18);

INSERT INTO CRM_PHYSICAL_FIGURE_SET (CRM_FIGURE_GROUP_ID, CRM_FIGURE_ID, CRM_ORDER_SEQUENCE) VALUES (02, 20, 01);
INSERT INTO CRM_PHYSICAL_FIGURE_SET (CRM_FIGURE_GROUP_ID, CRM_FIGURE_ID, CRM_ORDER_SEQUENCE) VALUES (02, 21, 02);
INSERT INTO CRM_PHYSICAL_FIGURE_SET (CRM_FIGURE_GROUP_ID, CRM_FIGURE_ID, CRM_ORDER_SEQUENCE) VALUES (02, 22, 03);
INSERT INTO CRM_PHYSICAL_FIGURE_SET (CRM_FIGURE_GROUP_ID, CRM_FIGURE_ID, CRM_ORDER_SEQUENCE) VALUES (02, 23, 03);
INSERT INTO CRM_PHYSICAL_FIGURE_SET (CRM_FIGURE_GROUP_ID, CRM_FIGURE_ID, CRM_ORDER_SEQUENCE) VALUES (02, 24, 04);
INSERT INTO CRM_PHYSICAL_FIGURE_SET (CRM_FIGURE_GROUP_ID, CRM_FIGURE_ID, CRM_ORDER_SEQUENCE) VALUES (02, 25, 05);
INSERT INTO CRM_PHYSICAL_FIGURE_SET (CRM_FIGURE_GROUP_ID, CRM_FIGURE_ID, CRM_ORDER_SEQUENCE) VALUES (02, 26, 06);
INSERT INTO CRM_PHYSICAL_FIGURE_SET (CRM_FIGURE_GROUP_ID, CRM_FIGURE_ID, CRM_ORDER_SEQUENCE) VALUES (02, 27, 07);
INSERT INTO CRM_PHYSICAL_FIGURE_SET (CRM_FIGURE_GROUP_ID, CRM_FIGURE_ID, CRM_ORDER_SEQUENCE) VALUES (02, 28, 08);
INSERT INTO CRM_PHYSICAL_FIGURE_SET (CRM_FIGURE_GROUP_ID, CRM_FIGURE_ID, CRM_ORDER_SEQUENCE) VALUES (02, 29, 09);
INSERT INTO CRM_PHYSICAL_FIGURE_SET (CRM_FIGURE_GROUP_ID, CRM_FIGURE_ID, CRM_ORDER_SEQUENCE) VALUES (02, 30, 10);
INSERT INTO CRM_PHYSICAL_FIGURE_SET (CRM_FIGURE_GROUP_ID, CRM_FIGURE_ID, CRM_ORDER_SEQUENCE) VALUES (02, 31, 11);
INSERT INTO CRM_PHYSICAL_FIGURE_SET (CRM_FIGURE_GROUP_ID, CRM_FIGURE_ID, CRM_ORDER_SEQUENCE) VALUES (02, 32, 12);

INSERT INTO CRM_PHYSICAL_FIGURE_SET (CRM_FIGURE_GROUP_ID, CRM_FIGURE_ID, CRM_ORDER_SEQUENCE) VALUES (03, 33, 01);
INSERT INTO CRM_PHYSICAL_FIGURE_SET (CRM_FIGURE_GROUP_ID, CRM_FIGURE_ID, CRM_ORDER_SEQUENCE) VALUES (03, 34, 02);
INSERT INTO CRM_PHYSICAL_FIGURE_SET (CRM_FIGURE_GROUP_ID, CRM_FIGURE_ID, CRM_ORDER_SEQUENCE) VALUES (03, 35, 03);
INSERT INTO CRM_PHYSICAL_FIGURE_SET (CRM_FIGURE_GROUP_ID, CRM_FIGURE_ID, CRM_ORDER_SEQUENCE) VALUES (03, 36, 03);
INSERT INTO CRM_PHYSICAL_FIGURE_SET (CRM_FIGURE_GROUP_ID, CRM_FIGURE_ID, CRM_ORDER_SEQUENCE) VALUES (03, 37, 04);
INSERT INTO CRM_PHYSICAL_FIGURE_SET (CRM_FIGURE_GROUP_ID, CRM_FIGURE_ID, CRM_ORDER_SEQUENCE) VALUES (03, 38, 05);
INSERT INTO CRM_PHYSICAL_FIGURE_SET (CRM_FIGURE_GROUP_ID, CRM_FIGURE_ID, CRM_ORDER_SEQUENCE) VALUES (03, 39, 06);
INSERT INTO CRM_PHYSICAL_FIGURE_SET (CRM_FIGURE_GROUP_ID, CRM_FIGURE_ID, CRM_ORDER_SEQUENCE) VALUES (03, 40, 07);
INSERT INTO CRM_PHYSICAL_FIGURE_SET (CRM_FIGURE_GROUP_ID, CRM_FIGURE_ID, CRM_ORDER_SEQUENCE) VALUES (03, 41, 08);
INSERT INTO CRM_PHYSICAL_FIGURE_SET (CRM_FIGURE_GROUP_ID, CRM_FIGURE_ID, CRM_ORDER_SEQUENCE) VALUES (03, 42, 09);
INSERT INTO CRM_PHYSICAL_FIGURE_SET (CRM_FIGURE_GROUP_ID, CRM_FIGURE_ID, CRM_ORDER_SEQUENCE) VALUES (03, 43, 10);
INSERT INTO CRM_PHYSICAL_FIGURE_SET (CRM_FIGURE_GROUP_ID, CRM_FIGURE_ID, CRM_ORDER_SEQUENCE) VALUES (03, 44, 11);
INSERT INTO CRM_PHYSICAL_FIGURE_SET (CRM_FIGURE_GROUP_ID, CRM_FIGURE_ID, CRM_ORDER_SEQUENCE) VALUES (03, 45, 12);
INSERT INTO CRM_PHYSICAL_FIGURE_SET (CRM_FIGURE_GROUP_ID, CRM_FIGURE_ID, CRM_ORDER_SEQUENCE) VALUES (03, 46, 13);
INSERT INTO CRM_PHYSICAL_FIGURE_SET (CRM_FIGURE_GROUP_ID, CRM_FIGURE_ID, CRM_ORDER_SEQUENCE) VALUES (03, 28, 14);
INSERT INTO CRM_PHYSICAL_FIGURE_SET (CRM_FIGURE_GROUP_ID, CRM_FIGURE_ID, CRM_ORDER_SEQUENCE) VALUES (03, 32, 15);
