ALTER TABLE CRM_PROMOTION_INSTRUCTION
 DROP PRIMARY KEY CASCADE;
DROP TABLE CRM_PROMOTION_INSTRUCTION CASCADE CONSTRAINTS;

CREATE TABLE CRM_PROMOTION_INSTRUCTION
(
 CRM_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 CRM_MODULE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 CRM_EVENT_ID NUMBER(*,0) NOT NULL ENABLE,
 CRM_PROMO_INSTR_PID NUMBER(*,0) NOT NULL ENABLE,
 CRM_PROMO_INSTR_CODE VARCHAR2(20 BYTE),
 CRM_PROMO_INSTR_REMARKS VARCHAR2(100 BYTE),
 CRM_CREATED_DATE DATE DEFAULT SYSDATE,
 CRM_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CRM_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CRM_SITE_CODE, CRM_MODULE_CODE, CRM_EVENT_ID, CRM_PROMO_INSTR_PID)
);
ALTER TABLE CRM_PROMOTION_INSTRUCTION ADD (
 CONSTRAINT CRM_PROMOTION_INSTRUCTION_R01
 FOREIGN KEY (CRM_SITE_CODE, CRM_MODULE_CODE, CRM_EVENT_ID)
 REFERENCES CRM_PROMOTION (CRM_SITE_CODE, CRM_MODULE_CODE, CRM_EVENT_ID));
