ALTER TABLE CRM_PROMOTION_REF_CODE
 DROP PRIMARY KEY CASCADE;
DROP TABLE CRM_PROMOTION_REF_CODE CASCADE CONSTRAINTS;

CREATE TABLE CRM_PROMOTION_REF_CODE
(
 CRM_REF_TYPE_CODE VARCHAR2(5 BYTE) NOT NULL ENABLE,
 CRM_REF_TYPE_DESCRIPTION VARCHAR2(100 BYTE),
 CRM_CREATED_DATE DATE DEFAULT SYSDATE,
 CRM_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CRM_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CRM_REF_TYPE_CODE)
);

INSERT INTO CRM_PROMOTION_REF_CODE(CRM_REF_TYPE_CODE, CRM_REF_TYPE_DESCRIPTION) VALUES('RAR', 'Related AR');
INSERT INTO CRM_PROMOTION_REF_CODE(CRM_REF_TYPE_CODE, CRM_REF_TYPE_DESCRIPTION) VALUES('PC', 'Package Code');
INSERT INTO CRM_PROMOTION_REF_CODE(CRM_REF_TYPE_CODE, CRM_REF_TYPE_DESCRIPTION) VALUES('HATS', 'HATS Code');
