ALTER TABLE CRM_CLIENTS_MEMBERSHIP
 DROP PRIMARY KEY CASCADE;
DROP TABLE CRM_CLIENTS_MEMBERSHIP CASCADE CONSTRAINTS;

CREATE TABLE CRM_CLIENTS_MEMBERSHIP
(
 CRM_CLIENT_ID NUMBER(*,0) DEFAULT 1,
 CRM_CLUB_ID NUMBER(*,0) NOT NULL ENABLE,
 CRM_CLUB_SEQ NUMBER(*,0) NOT NULL ENABLE,
 CRM_CARD_TYPE NUMBER(*,0) NULL,
 CRM_MEMBER_ID VARCHAR2(30 BYTE) NULL,
 CRM_JOINED_DATE DATE DEFAULT SYSDATE,
 CRM_ISSUE_DATE DATE DEFAULT SYSDATE,
 CRM_EXPIRY_DATE DATE DEFAULT SYSDATE,
 CRM_PAID_YN VARCHAR2(1 BYTE) DEFAULT 'N',
 CRM_CREATED_DATE DATE DEFAULT SYSDATE,
 CRM_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CRM_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CRM_CLIENT_ID, CRM_CLUB_ID, CRM_CLUB_SEQ)
);

ALTER TABLE CRM_CLIENTS_MEMBERSHIP ADD (
 CONSTRAINT CRM_CLIENTS_MEMBERSHIP_R01
 FOREIGN KEY (CRM_CLIENT_ID)
 REFERENCES CRM_CLIENTS (CRM_CLIENT_ID));