ALTER TABLE CRM_CLIENTS_ACTIVITIES
 DROP PRIMARY KEY CASCADE;
DROP TABLE CRM_CLIENTS_ACTIVITIES CASCADE CONSTRAINTS;

CREATE TABLE CRM_CLIENTS_ACTIVITIES
(
 CRM_CLIENT_ACTIVITY_ID NUMBER(*,0) DEFAULT 1,
 CRM_CLIENT_ID NUMBER(*,0) DEFAULT 1,
 CRM_ACTIVITY_ID NUMBER(*,0) DEFAULT 1,
 CRM_ACTIVITY_DATE DATE DEFAULT SYSDATE,
 CRM_EVENT_ID NUMBER(*,0),
 CRM_PHYSICIAL_ID NUMBER(*,0),
 CRM_MEDICAL_ID NUMBER(*,0),
 CRM_QUESTIONAIRE_ID NUMBER(*,0),
 CRM_REMARKS VARCHAR2(100 BYTE) NULL,
 CO_DOCUMENT_ID NUMBER(*,0) NULL,
 CRM_CREATED_DATE DATE DEFAULT SYSDATE,
 CRM_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CRM_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CRM_CLIENT_ACTIVITY_ID)
);
ALTER TABLE CRM_CLIENTS_ACTIVITIES ADD (
 CONSTRAINT CRM_CLIENTS_ACTIVITIES_R01
 FOREIGN KEY (CRM_CLIENT_ID)
 REFERENCES CRM_CLIENTS (CRM_CLIENT_ID));