ALTER TABLE CRM_CLIENTS
 DROP PRIMARY KEY CASCADE;
DROP TABLE CRM_CLIENTS CASCADE CONSTRAINTS;

CREATE TABLE CRM_CLIENTS
(
 CRM_CLIENT_ID NUMBER(*,0) DEFAULT 1,
 CRM_LASTNAME VARCHAR2(50 BYTE),
 CRM_FIRSTNAME VARCHAR2(60 BYTE),
 CRM_CHINESENAME VARCHAR2(30 BYTE),
 CRM_TITLE VARCHAR2(6 BYTE),	-- Mr. Mrs., Doctor, Sir
 CRM_TITLE_DESC VARCHAR2(10 BYTE),	-- others
 CRM_RELIGION VARCHAR2(30 BYTE),
 CRM_SEX VARCHAR2(1 BYTE) DEFAULT 'M',
 CRM_DOB_YY VARCHAR2(4 BYTE),
 CRM_DOB_MM VARCHAR2(2 BYTE),
 CRM_DOB_DD VARCHAR2(2 BYTE),
 CRM_DECEASE_YY VARCHAR2(4 BYTE),
 CRM_DECEASE_MM VARCHAR2(2 BYTE),
 CRM_DECEASE_DD VARCHAR2(2 BYTE),
 CRM_AGE_GROUP NUMBER(*,0) DEFAULT 0,	-- remove it (TODO)
 CRM_DOB_YY_ESTIMATE VARCHAR2(4 BYTE),
 CRM_EDUCATION_LEVEL_ID NUMBER(*,0) DEFAULT 0,	-- 0:Unknown, 1:primary school, 2:secondary school, 3:high school, 4, undergraduate, 5:others
 CRM_EDUCATION_LEVEL_DESC VARCHAR2(50 BYTE),	-- for preload data
 CRM_OCCUPATION_ID NUMBER(*,0),
 CRM_OCCUPATION_DESC VARCHAR2(50 BYTE),	-- for preload data
 CRM_HKID VARCHAR2(20 BYTE),
 CRM_PASSPORT VARCHAR2(50 BYTE),
 CRM_STREET1 VARCHAR2(100 BYTE),
 CRM_STREET2 VARCHAR2(100 BYTE),
 CRM_STREET3 VARCHAR2(100 BYTE),
 CRM_STREET4 VARCHAR2(100 BYTE),
 CRM_DISTRICT_ID NUMBER(*,0),
 CRM_DISTRICT_DESC VARCHAR2(50 BYTE),	-- for preload data
 CRM_AREA_ID NUMBER(*,0),	-- 0:Unknown, 1:hk island, 2:kowloon, 3:NT
 CRM_COUNTRY VARCHAR2(30 BYTE),
 CRM_LANGUAGE VARCHAR2(10 BYTE),
 CRM_HOME_NUMBER VARCHAR2(20 BYTE),
 CRM_OFFICE_NUMBER VARCHAR2(20 BYTE),
 CRM_MOBILE_NUMBER VARCHAR2(20 BYTE),
 CRM_FAX_NUMBER VARCHAR2(20 BYTE),
 CRM_EMAIL VARCHAR2(50 BYTE),
 CRM_EMERGENCY_PERSON VARCHAR2(100 BYTE),
 CRM_EMERGENCY_NUMBER VARCHAR2(20 BYTE),
 CRM_EMERGENCY_RELATIONSHIP VARCHAR2(50 BYTE),
 CRM_FACEBOOK VARCHAR2(50 BYTE),
 CRM_INCOME NUMBER(*,2) DEFAULT 0,
 CRM_WILLING_PROMOTION VARCHAR2(1 BYTE) DEFAULT 'Y',
 CRM_PREFER_CONTACT_METHOD VARCHAR2(30 BYTE),
 CRM_REMARKS VARCHAR2(300 BYTE),
 CRM_CREATED_DATE DATE DEFAULT SYSDATE,
 CRM_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_CREATED_SITE_CODE VARCHAR2(10 BYTE) NOT NULL,
 CRM_CREATED_DEPARTMENT_CODE VARCHAR2(10 BYTE) NOT NULL,
 CRM_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CRM_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CRM_CLIENT_ID)
);
ALTER TABLE CRM_CLIENTS ADD (
 CONSTRAINT CRM_CLIENTS_R01
 FOREIGN KEY (CRM_CREATED_SITE_CODE)
 REFERENCES CO_SITE (CO_SITE_CODE));
ALTER TABLE CRM_CLIENTS ADD (
 CONSTRAINT CRM_CLIENTS_R02
 FOREIGN KEY (CRM_CREATED_DEPARTMENT_CODE)
 REFERENCES CO_DEPARTMENTS (CO_DEPARTMENT_CODE));
 
update CRM_CLIENTS set CRM_AGE_GROUP = 0 WHERE CRM_DOB_YY > 1999 AND CRM_DOB_YY <= 2009;
update CRM_CLIENTS set CRM_AGE_GROUP = 1 WHERE CRM_DOB_YY > 1989 AND CRM_DOB_YY <= 1999;
update CRM_CLIENTS set CRM_AGE_GROUP = 2 WHERE CRM_DOB_YY > 1979 AND CRM_DOB_YY <= 1989;
update CRM_CLIENTS set CRM_AGE_GROUP = 3 WHERE CRM_DOB_YY > 1969 AND CRM_DOB_YY <= 1979;
update CRM_CLIENTS set CRM_AGE_GROUP = 4 WHERE CRM_DOB_YY > 1959 AND CRM_DOB_YY <= 1969;
update CRM_CLIENTS set CRM_AGE_GROUP = 5 WHERE CRM_DOB_YY > 1949 AND CRM_DOB_YY <= 1959;
update CRM_CLIENTS set CRM_AGE_GROUP = 6 WHERE CRM_DOB_YY > 1900 AND CRM_DOB_YY <= 1949;
