ALTER TABLE CRM_CLIENTS_RELATIONSHIP
 DROP PRIMARY KEY CASCADE;
DROP TABLE CRM_CLIENTS_RELATIONSHIP CASCADE CONSTRAINTS;

CREATE TABLE CRM_CLIENTS_RELATIONSHIP
(
 CRM_CLIENT_ID NUMBER(*,0) DEFAULT 1,
 CRM_RELATED_CLIENT_ID NUMBER(*,0) DEFAULT 1,
 CRM_RELATIONSHIP VARCHAR2(50 BYTE) NULL,
 CRM_REMARKS VARCHAR2(100 BYTE) NULL,
 CRM_CREATED_DATE DATE DEFAULT SYSDATE,
 CRM_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CRM_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CRM_CLIENT_ID, CRM_RELATED_CLIENT_ID)
);
ALTER TABLE CRM_CLIENTS_RELATIONSHIP ADD (
 CONSTRAINT CRM_CLIENTS_RELATIONSHIP_R01
 FOREIGN KEY (CRM_CLIENT_ID)
 REFERENCES CRM_CLIENTS (CRM_CLIENT_ID));
ALTER TABLE CRM_CLIENTS_RELATIONSHIP ADD (
 CONSTRAINT CRM_CLIENTS_RELATIONSHIP_R02
 FOREIGN KEY (CRM_RELATED_CLIENT_ID)
 REFERENCES CRM_CLIENTS (CRM_CLIENT_ID));