ALTER TABLE CRM_CLIENTS_AFFILIATION
 DROP PRIMARY KEY CASCADE;
DROP TABLE CRM_CLIENTS_AFFILIATION CASCADE CONSTRAINTS;

CREATE TABLE CRM_CLIENTS_AFFILIATION
(
 CRM_CLIENT_ID NUMBER(*,0) DEFAULT 1,
 CRM_AFFILIATION_ID NUMBER(*,0) DEFAULT 1,
 CRM_COMPANY_NAME VARCHAR2(100 BYTE) NULL,
 CRM_COMPANY_TITLE VARCHAR2(100 BYTE) NULL,
 CRM_AFFILIATION_REMARKS VARCHAR2(100 BYTE) NULL,
 CRM_CREATED_DATE DATE DEFAULT SYSDATE,
 CRM_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CRM_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CRM_CLIENT_ID, CRM_AFFILIATION_ID)
);
ALTER TABLE CRM_CLIENTS_AFFILIATION ADD (
 CONSTRAINT CRM_CLIENTS_AFFILIATION_R01
 FOREIGN KEY (CRM_CLIENT_ID)
 REFERENCES CRM_CLIENTS (CRM_CLIENT_ID));