ALTER TABLE CRM_CAMPAIGNS
 DROP PRIMARY KEY CASCADE;
DROP TABLE CRM_CAMPAIGNS CASCADE CONSTRAINTS;

CREATE TABLE CRM_CAMPAIGNS
(
 CRM_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 CRM_CAMPAIGN_ID NUMBER(*,0) DEFAULT 1,
 CRM_CAMPAIGN_DESC VARCHAR2(100 BYTE) NULL,
 CRM_CREATED_DATE DATE DEFAULT SYSDATE,
 CRM_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CRM_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CRM_CAMPAIGN_ID)
);
INSERT INTO CRM_CAMPAIGNS (CRM_SITE_CODE, CRM_CAMPAIGN_ID, CRM_CAMPAIGN_DESC) VALUES ('twah', 1, 'Campaign 1');
INSERT INTO CRM_CAMPAIGNS (CRM_SITE_CODE, CRM_CAMPAIGN_ID, CRM_CAMPAIGN_DESC) VALUES ('twah', 2, 'Campaign 2');
INSERT INTO CRM_CAMPAIGNS (CRM_SITE_CODE, CRM_CAMPAIGN_ID, CRM_CAMPAIGN_DESC) VALUES ('twah', 3, 'Campaign 3');
INSERT INTO CRM_CAMPAIGNS (CRM_SITE_CODE, CRM_CAMPAIGN_ID, CRM_CAMPAIGN_DESC) VALUES ('twah', 4, 'Campaign 4');
INSERT INTO CRM_CAMPAIGNS (CRM_SITE_CODE, CRM_CAMPAIGN_ID, CRM_CAMPAIGN_DESC) VALUES ('twah', 5, 'Campaign 5');