ALTER TABLE CRM_PLANS
 DROP PRIMARY KEY CASCADE;
DROP TABLE CRM_PLANS CASCADE CONSTRAINTS;

CREATE TABLE CRM_PLANS
(
 CRM_PLAN_ID NUMBER(*,0) NOT NULL ENABLE,
 CRM_PLAN_DESC VARCHAR2(100 BYTE) NOT NULL,
 CRM_PLAN_PRICE NUMBER(*, 4) DEFAULT 0,
 CRM_PLAN_REMARKS VARCHAR2(1000 BYTE) NULL,
 CRM_CREATED_DATE DATE DEFAULT SYSDATE,
 CRM_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CRM_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CRM_PLAN_ID)
);

INSERT INTO CRM_PLANS (CRM_PLAN_ID, CRM_PLAN_DESC) VALUES (1, 'Plan A');
INSERT INTO CRM_PLANS (CRM_PLAN_ID, CRM_PLAN_DESC) VALUES (2, 'Plan B');
INSERT INTO CRM_PLANS (CRM_PLAN_ID, CRM_PLAN_DESC) VALUES (3, 'Plan C');
INSERT INTO CRM_PLANS (CRM_PLAN_ID, CRM_PLAN_DESC) VALUES (4, 'Plan D');
INSERT INTO CRM_PLANS (CRM_PLAN_ID, CRM_PLAN_DESC) VALUES (5, 'Plan E');