ALTER TABLE CRM_PROMOTION
 DROP PRIMARY KEY CASCADE;
DROP TABLE CRM_PROMOTION CASCADE CONSTRAINTS;

CREATE TABLE CRM_PROMOTION
(
 CRM_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 CRM_MODULE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 CRM_EVENT_ID NUMBER(*,0) NOT NULL ENABLE,
 CRM_INITIAL_DATE_FM DATE DEFAULT SYSDATE,
 CRM_INITIAL_DATE_TO DATE DEFAULT SYSDATE,
 CRM_PROMOTE_REMARKS VARCHAR2(3800 BYTE),
 CRM_PROMOTE_DETAILS VARCHAR2(30 BYTE),
 CRM_PROMOTE_MATERIALS VARCHAR2(30 BYTE),
 CRM_REF_TYPE_CODE VARCHAR2(5 BYTE),
 CRM_REF_CODE VARCHAR2(30 BYTE),
 CRM_PROMOTE_COMMENT VARCHAR2(3800 BYTE),
 CRM_CREATED_DATE DATE DEFAULT SYSDATE,
 CRM_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CRM_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CRM_SITE_CODE, CRM_MODULE_CODE, CRM_EVENT_ID)
);
ALTER TABLE CRM_PROMOTION ADD (
 CONSTRAINT CRM_PROMOTION_R01
 FOREIGN KEY (CRM_SITE_CODE, CRM_MODULE_CODE, CRM_EVENT_ID)
 REFERENCES CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID));
ALTER TABLE CRM_PROMOTION ADD (
 CONSTRAINT CRM_PROMOTION_R02
 FOREIGN KEY (CRM_REF_TYPE_CODE)
 REFERENCES CRM_REF_TYPE_CODE (CRM_REF_TYPE_CODE));

