ALTER TABLE CRM_CLIENTS_DONATION
 DROP PRIMARY KEY CASCADE;
DROP TABLE CRM_CLIENTS_DONATION CASCADE CONSTRAINTS;

CREATE TABLE CRM_CLIENTS_DONATION
(
 CRM_DONATION_ID NUMBER(*,0) DEFAULT 1,
 CRM_CLIENT_ID NUMBER(*,0) DEFAULT 1,
 CRM_FUND_ID NUMBER(*,0) NULL,
 CRM_CAMPAIGN_ID NUMBER(*,0) NULL,
 CRM_APPEAL_ID NUMBER(*,0) NULL,
 CRM_DONATION_DATE DATE DEFAULT SYSDATE,
 CRM_FISCAL_YEAR VARCHAR2(4 BYTE) NULL,
 CRM_STATUS VARCHAR2(2 BYTE) NULL,		-- a - appeal, p - pledged, pp - partial payment, fp - full payment
 CRM_PLEDGED_AMOUNT NUMBER(*,2) DEFAULT 0,
 CRM_RECEIVED_AMOUNT NUMBER(*,2) DEFAULT 0,
 CRM_BALANCE_AMOUNT NUMBER(*,2) DEFAULT 0,
 CRM_REMARKS VARCHAR2(100 BYTE) NULL,
 CRM_CREATED_DATE DATE DEFAULT SYSDATE,
 CRM_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CRM_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CRM_DONATION_ID)
);
ALTER TABLE CRM_CLIENTS_DONATION ADD (
 CONSTRAINT CRM_CLIENTS_DONATION_R01
 FOREIGN KEY (CRM_CLIENT_ID)
 REFERENCES CRM_CLIENTS (CRM_CLIENT_ID));