ALTER TABLE DNT_TRACK
 DROP PRIMARY KEY CASCADE;
DROP TABLE DNT_TRACK CASCADE CONSTRAINTS;

  CREATE TABLE DNT_TRACK
   (	
   	DNT_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE, 
    DNT_TRACK_ID NUMBER(*,0) NOT NULL ENABLE, 
	DNT_INSTRU_ID VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	DNT_HOSP_NO VARCHAR2(10 BYTE), 
	DNT_PATIENT_NAME VARCHAR2(80 BYTE), 
	DNT_DATE DATE, 
	DNT_CREATED_DATE DATE DEFAULT SYSDATE, 
	DNT_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM', 
	DNT_MODIFIED_DATE DATE DEFAULT SYSDATE, 
	DNT_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM', 
	DNT_ENABLED NUMBER(*,0) DEFAULT 1, 
    PRIMARY KEY (DNT_TRACK_ID, DNT_SITE_CODE)
   ) ;

  CREATE INDEX DNT_TRACK_INDEX1 ON DNT_TRACK (DNT_INSTRU_ID) ;
