ALTER TABLE DNT_INSTRU
 DROP PRIMARY KEY CASCADE;
DROP TABLE DNT_INSTRU CASCADE CONSTRAINTS;

CREATE TABLE DNT_INSTRU
(
 DNT_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE, 
 DNT_INSTRU_ID VARCHAR2(10 BYTE) NOT NULL ENABLE, 
 DNT_NAME VARCHAR2(40 BYTE) NOT NULL ENABLE, 
 DNT_CREATED_DATE DATE DEFAULT SYSDATE, 
 DNT_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM', 
 DNT_MODIFIED_DATE DATE DEFAULT SYSDATE, 
 DNT_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM', 
 DNT_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (DNT_INSTRU_ID, DNT_SITE_CODE)
);