ALTER TABLE EE_ELEARNING_DOCUMENT
 DROP PRIMARY KEY CASCADE;
DROP TABLE EE_ELEARNING_DOCUMENT CASCADE CONSTRAINTS;

CREATE TABLE EE_ELEARNING_DOCUMENT
(
 EE_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 EE_ELEARNING_ID NUMBER(*,0) NOT NULL ENABLE,
 EE_DOCUMENT_ID NUMBER(*,0) NULL,
 EE_CREATED_DATE DATE DEFAULT SYSDATE,
 EE_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 EE_MODIFIED_DATE DATE DEFAULT SYSDATE,
 EE_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 EE_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (EE_SITE_CODE, EE_ELEARNING_ID, EE_DOCUMENT_ID)
);
ALTER TABLE EE_ELEARNING_DOCUMENT ADD (
 CONSTRAINT EE_ELEARNING_DOCUMENT_R01
 FOREIGN KEY (EE_SITE_CODE, EE_ELEARNING_ID)
 REFERENCES EE_ELEARNING (EE_SITE_CODE, EE_ELEARNING_ID));
ALTER TABLE EE_ELEARNING_DOCUMENT ADD (
 CONSTRAINT EE_ELEARNING_DOCUMENT_R02
 FOREIGN KEY (EE_DOCUMENT_ID)
 REFERENCES CO_DOCUMENT (CO_DOCUMENT_ID));

INSERT INTO EE_ELEARNING_DOCUMENT (EE_SITE_CODE, EE_ELEARNING_ID, EE_DOCUMENT_ID) VALUES ('twah', 1, 1);
INSERT INTO EE_ELEARNING_DOCUMENT (EE_SITE_CODE, EE_ELEARNING_ID, EE_DOCUMENT_ID) VALUES ('twah', 2, 3);
INSERT INTO EE_ELEARNING_DOCUMENT (EE_SITE_CODE, EE_ELEARNING_ID, EE_DOCUMENT_ID) VALUES ('twah', 3, 2);
INSERT INTO EE_ELEARNING_DOCUMENT (EE_SITE_CODE, EE_ELEARNING_ID, EE_DOCUMENT_ID) VALUES ('twah', 5, 4);
INSERT INTO EE_ELEARNING_DOCUMENT (EE_SITE_CODE, EE_ELEARNING_ID, EE_DOCUMENT_ID) VALUES ('twah', 5, 5);
INSERT INTO EE_ELEARNING_DOCUMENT (EE_SITE_CODE, EE_ELEARNING_ID, EE_DOCUMENT_ID) VALUES ('twah', 6, 7);
INSERT INTO EE_ELEARNING_DOCUMENT (EE_SITE_CODE, EE_ELEARNING_ID, EE_DOCUMENT_ID) VALUES ('twah', 7, 8);
INSERT INTO EE_ELEARNING_DOCUMENT (EE_SITE_CODE, EE_ELEARNING_ID, EE_DOCUMENT_ID) VALUES ('twah', 8, 9);
INSERT INTO EE_ELEARNING_DOCUMENT (EE_SITE_CODE, EE_ELEARNING_ID, EE_DOCUMENT_ID) VALUES ('twah', 9, 10);
INSERT INTO EE_ELEARNING_DOCUMENT (EE_SITE_CODE, EE_ELEARNING_ID, EE_DOCUMENT_ID) VALUES ('twah', 9, 37);
INSERT INTO EE_ELEARNING_DOCUMENT (EE_SITE_CODE, EE_ELEARNING_ID, EE_DOCUMENT_ID) VALUES ('twah', 10, 14);
INSERT INTO EE_ELEARNING_DOCUMENT (EE_SITE_CODE, EE_ELEARNING_ID, EE_DOCUMENT_ID) VALUES ('twah', 11, 15);
INSERT INTO EE_ELEARNING_DOCUMENT (EE_SITE_CODE, EE_ELEARNING_ID, EE_DOCUMENT_ID) VALUES ('twah', 11, 16);
INSERT INTO EE_ELEARNING_DOCUMENT (EE_SITE_CODE, EE_ELEARNING_ID, EE_DOCUMENT_ID) VALUES ('twah', 13, 64);
INSERT INTO EE_ELEARNING_DOCUMENT (EE_SITE_CODE, EE_ELEARNING_ID, EE_DOCUMENT_ID) VALUES ('twah', 13, 65);