ALTER TABLE EE_ELEARNING_QUESTION
 DROP PRIMARY KEY CASCADE;
DROP TABLE EE_ELEARNING_QUESTION CASCADE CONSTRAINTS;

CREATE TABLE EE_ELEARNING_QUESTION
(
 EE_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 EE_ELEARNING_ID NUMBER(*,0) NOT NULL ENABLE,
 EE_ELEARNING_QID NUMBER(*,0) NOT NULL ENABLE,
 EE_QUESTION VARCHAR2(1000 BYTE),
 EE_CREATED_DATE DATE DEFAULT SYSDATE,
 EE_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 EE_MODIFIED_DATE DATE DEFAULT SYSDATE,
 EE_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 EE_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (EE_SITE_CODE, EE_ELEARNING_ID, EE_ELEARNING_QID)
);
ALTER TABLE EE_ELEARNING_QUESTION ADD (
 CONSTRAINT EE_ELEARNING_QUESTION_R01
 FOREIGN KEY (EE_SITE_CODE, EE_ELEARNING_ID)
 REFERENCES EE_ELEARNING (EE_SITE_CODE, EE_ELEARNING_ID));
