ALTER TABLE EE_EVENT_ORDER
 DROP PRIMARY KEY CASCADE;
DROP TABLE EE_EVENT_ORDER CASCADE CONSTRAINTS;

CREATE TABLE EE_EVENT_ORDER
(
 EE_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 EE_MODULE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,	-- education, lmc
 EE_EVENT_ID NUMBER(*,0) NOT NULL ENABLE,
 EE_EVENT_ORDER NUMBER(*,0) NOT NULL ENABLE,
 EE_CREATED_DATE DATE DEFAULT SYSDATE,
 EE_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 EE_MODIFIED_DATE DATE DEFAULT SYSDATE,
 EE_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 EE_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (EE_SITE_CODE, EE_MODULE_CODE, EE_EVENT_ID)
);
ALTER TABLE EE_EVENT_ORDER ADD (
 CONSTRAINT EE_EVENT_ORDER_R01
 FOREIGN KEY (EE_SITE_CODE, EE_MODULE_CODE, EE_EVENT_ID)
 REFERENCES CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID));

INSERT INTO EE_EVENT_ORDER (EE_SITE_CODE, EE_MODULE_CODE, EE_EVENT_ID, EE_EVENT_ORDER) VALUES ('twah', 'education', 1010, 1);
INSERT INTO EE_EVENT_ORDER (EE_SITE_CODE, EE_MODULE_CODE, EE_EVENT_ID, EE_EVENT_ORDER) VALUES ('twah', 'education', 1020, 2);
INSERT INTO EE_EVENT_ORDER (EE_SITE_CODE, EE_MODULE_CODE, EE_EVENT_ID, EE_EVENT_ORDER) VALUES ('twah', 'education', 1025, 3);
INSERT INTO EE_EVENT_ORDER (EE_SITE_CODE, EE_MODULE_CODE, EE_EVENT_ID, EE_EVENT_ORDER) VALUES ('twah', 'education', 1030, 4);
INSERT INTO EE_EVENT_ORDER (EE_SITE_CODE, EE_MODULE_CODE, EE_EVENT_ID, EE_EVENT_ORDER) VALUES ('twah', 'education', 1070, 5);
INSERT INTO EE_EVENT_ORDER (EE_SITE_CODE, EE_MODULE_CODE, EE_EVENT_ID, EE_EVENT_ORDER) VALUES ('twah', 'education', 1080, 6);

INSERT INTO EE_EVENT_ORDER (EE_SITE_CODE, EE_MODULE_CODE, EE_EVENT_ID, EE_EVENT_ORDER) VALUES ('twah', 'education', 1040, 7);
INSERT INTO EE_EVENT_ORDER (EE_SITE_CODE, EE_MODULE_CODE, EE_EVENT_ID, EE_EVENT_ORDER) VALUES ('twah', 'education', 1045, 8);
INSERT INTO EE_EVENT_ORDER (EE_SITE_CODE, EE_MODULE_CODE, EE_EVENT_ID, EE_EVENT_ORDER) VALUES ('twah', 'education', 1060, 9);
INSERT INTO EE_EVENT_ORDER (EE_SITE_CODE, EE_MODULE_CODE, EE_EVENT_ID, EE_EVENT_ORDER) VALUES ('twah', 'education', 1120, 10);
