ALTER TABLE EE_ELEARNING
 DROP PRIMARY KEY CASCADE;
DROP TABLE EE_ELEARNING CASCADE CONSTRAINTS;

CREATE TABLE EE_ELEARNING
(
 EE_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 EE_MODULE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,	-- education, lmc
 EE_EVENT_ID NUMBER(*,0) NOT NULL ENABLE,
 EE_ELEARNING_ID NUMBER(*,0) NOT NULL ENABLE,
 EE_TOPIC VARCHAR2(200 BYTE),
 EE_TOPIC_ZH VARCHAR2(200 BYTE),
 EE_QUESTION_NUM NUMBER(*,0) DEFAULT 0,
 EE_PASSGRADE NUMBER(*,0) DEFAULT 0,
 EE_DURATION NUMBER(*,0) DEFAULT 0,
 EE_DOCUMENTS_NO NUMBER(*,0) DEFAULT 0,
 EE_SWFFILE_EN VARCHAR2(200 BYTE),
 EE_SWFFILE_ZH VARCHAR2(200 BYTE),
 EE_SORT_ORDER NUMBER(*,0),
 EE_BG_COLOR VARCHAR2(6 BYTE),	-- RGB code
 EE_DESCRIPTION VARCHAR2(500 BYTE),
 EE_REQUIRED_STAFFCAT VARCHAR2(50 BYTE),
 EE_CREATED_DATE DATE DEFAULT SYSDATE,
 EE_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 EE_MODIFIED_DATE DATE DEFAULT SYSDATE,
 EE_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 EE_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (EE_SITE_CODE, EE_ELEARNING_ID)
);
ALTER TABLE EE_ELEARNING ADD (
 CONSTRAINT EE_ELEARNING_R01
 FOREIGN KEY (EE_SITE_CODE)
 REFERENCES CO_SITE (CO_SITE_CODE));

-- twah
INSERT INTO EE_ELEARNING(EE_SITE_CODE, EE_MODULE_CODE, EE_EVENT_ID, EE_ELEARNING_ID, EE_TOPIC, EE_TOPIC_ZH, EE_QUESTION_NUM, EE_PASSGRADE, EE_DURATION, EE_DOCUMENTS_NO, EE_SORT_ORDER) VALUES ('twah', 'education', 1010, 1, 'SHARE Review (Nursing Staff; Clinical Staff; Ancillary Staff; Other Staff)', '與爾共享重温 (護理員工; 醫療員工; 輔助員工; 其他員工)',  10, 9, 120, 1, 1);
INSERT INTO EE_ELEARNING(EE_SITE_CODE, EE_MODULE_CODE, EE_EVENT_ID, EE_ELEARNING_ID, EE_TOPIC, EE_TOPIC_ZH, EE_QUESTION_NUM, EE_PASSGRADE, EE_DURATION, EE_DOCUMENTS_NO, EE_SORT_ORDER) VALUES ('twah', 'education', 1020, 2, 'Basic Infection Control (Nursing Staff; Clinical Staff)', '基本感染控制 (護理員工; 醫療員工)', 10, 6, 120, 1, 2);
INSERT INTO EE_ELEARNING(EE_SITE_CODE, EE_MODULE_CODE, EE_EVENT_ID, EE_ELEARNING_ID, EE_TOPIC, EE_TOPIC_ZH, EE_QUESTION_NUM, EE_PASSGRADE, EE_DURATION, EE_DOCUMENTS_NO, EE_SORT_ORDER) VALUES ('twah', 'education', 1025, 3, 'Basic Infection Control (Ancillary Staff; Other Staff)', '基本感染控制 (輔助員工; 其他員工)', 10, 6, 120, 1, 3);
INSERT INTO EE_ELEARNING(EE_SITE_CODE, EE_MODULE_CODE, EE_EVENT_ID, EE_ELEARNING_ID, EE_TOPIC, EE_TOPIC_ZH, EE_QUESTION_NUM, EE_PASSGRADE, EE_DURATION, EE_DOCUMENTS_NO, EE_SORT_ORDER) VALUES ('twah', 'education', 1030, 4, 'Manual Handling (Nursing Staff)', '人力提舉 (護理員工; 診斷影像員工)', 20, 16, 120, 1, 4);
INSERT INTO EE_ELEARNING(EE_SITE_CODE, EE_MODULE_CODE, EE_EVENT_ID, EE_ELEARNING_ID, EE_TOPIC, EE_TOPIC_ZH, EE_QUESTION_NUM, EE_PASSGRADE, EE_DURATION, EE_DOCUMENTS_NO, EE_SORT_ORDER) VALUES ('twah', 'education', 1030, 5, 'Manual Handling (Clinical Staff; Ancillary Staff; Other Staff)', '人力提舉 (醫療員工; 輔助員工; 其他員工)', 20, 16, 120, 1, 5);
INSERT INTO EE_ELEARNING(EE_SITE_CODE, EE_MODULE_CODE, EE_EVENT_ID, EE_ELEARNING_ID, EE_TOPIC, EE_TOPIC_ZH, EE_QUESTION_NUM, EE_PASSGRADE, EE_DURATION, EE_DOCUMENTS_NO, EE_SORT_ORDER) VALUES ('twah', 'education', 1080, 11, 'Medical Gas Safety', '醫療氣體安全 (護理員工; 醫療員工-化驗室員工豁免; 維修員工)', 20, 16, 120, 0, 6);

INSERT INTO EE_ELEARNING(EE_SITE_CODE, EE_MODULE_CODE, EE_EVENT_ID, EE_ELEARNING_ID, EE_TOPIC, EE_TOPIC_ZH, EE_QUESTION_NUM, EE_PASSGRADE, EE_DURATION, EE_DOCUMENTS_NO, EE_SORT_ORDER) VALUES ('twah', 'education', 1040, 12, 'Cardio-pulmonary Resuscitation + AED (RN)', '心肺復甦法 + 自動體外去顫術 (RN)', 1, 1, 0, 0, 4);
INSERT INTO EE_ELEARNING(EE_SITE_CODE, EE_MODULE_CODE, EE_EVENT_ID, EE_ELEARNING_ID, EE_TOPIC, EE_TOPIC_ZH, EE_QUESTION_NUM, EE_PASSGRADE, EE_DURATION, EE_DOCUMENTS_NO, EE_SORT_ORDER) VALUES ('twah', 'education', 1045, 13, 'Cardio-pulmonary Resuscitation + AED (EN, HCA, CA; Clinical Staff)', '心肺復甦法 + 自動體外去顫術 (EN, HCA, CA; 醫療員工)', 10, 6, 120, 0, 5);
INSERT INTO EE_ELEARNING(EE_SITE_CODE, EE_MODULE_CODE, EE_EVENT_ID, EE_ELEARNING_ID, EE_TOPIC, EE_TOPIC_ZH, EE_QUESTION_NUM, EE_PASSGRADE, EE_DURATION, EE_DOCUMENTS_NO, EE_SORT_ORDER) VALUES ('twah', 'education', 1060, 14, 'Fire Safety (Nursing Staff; Clinical Staff; Ancillary Staff; Other Staff)', '防火安全 (護理員工; 醫療員工; 輔助員工; 其他員工)', 1, 1, 0, 0, 3);
INSERT INTO EE_ELEARNING(EE_SITE_CODE, EE_MODULE_CODE, EE_EVENT_ID, EE_ELEARNING_ID, EE_TOPIC, EE_TOPIC_ZH, EE_QUESTION_NUM, EE_PASSGRADE, EE_DURATION, EE_DOCUMENTS_NO, EE_SORT_ORDER) VALUES ('twah', 'education', 1110, 15, 'Hospital Orientation (New Staff)', '醫院迎新 (新入職員工)', 1, 1, 0, 0, 1);
INSERT INTO EE_ELEARNING(EE_SITE_CODE, EE_MODULE_CODE, EE_EVENT_ID, EE_ELEARNING_ID, EE_TOPIC, EE_TOPIC_ZH, EE_QUESTION_NUM, EE_PASSGRADE, EE_DURATION, EE_DOCUMENTS_NO, EE_SORT_ORDER) VALUES ('twah', 'education', 1120, 16, 'SHARE Seminar (New Staff)', '與爾共享研討 (新入職員工)', 1, 1, 0, 0, 2);
