ALTER TABLE EL_ELEAVE_APPROVED
 DROP PRIMARY KEY CASCADE;
DROP TABLE EL_ELEAVE_APPROVED CASCADE CONSTRAINTS;

CREATE TABLE EL_ELEAVE_APPROVED
(
 EL_ELEAVE_ID NUMBER(*,0) NOT NULL ENABLE,
 EL_ELEAVE_APPROVED_ID NUMBER(*,0) NOT NULL ENABLE,
 EL_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 EL_APPROVAL_STAFF_ID VARCHAR2(10 BYTE) NULL,
 EL_CREATED_DATE DATE DEFAULT SYSDATE,
 EL_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 EL_MODIFIED_DATE DATE DEFAULT SYSDATE,
 EL_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 EL_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (EL_ELEAVE_ID, EL_ELEAVE_APPROVED_ID)
);
ALTER TABLE EL_ELEAVE_APPROVED ADD (
 CONSTRAINT EL_ELEAVE_APPROVED_R01
 FOREIGN KEY (EL_ELEAVE_ID)
 REFERENCES EL_ELEAVE (EL_ELEAVE_ID));