ALTER TABLE EL_STAFFS_HOLIDAY
 DROP PRIMARY KEY CASCADE;
DROP TABLE EL_STAFFS_HOLIDAY CASCADE CONSTRAINTS;

CREATE TABLE EL_STAFFS_HOLIDAY
(
 EL_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 EL_STAFF_ID VARCHAR2(10 BYTE) NOT NULL,
 EL_ANNUAL_DAYS NUMBER(*,0) NOT NULL,
 EL_SICK_DAYS NUMBER(*,0) NOT NULL,
 EL_BIRTHDAY_DAYS NUMBER(*,0) DEFAULT 1,
 EL_CREATED_DATE DATE DEFAULT SYSDATE,
 EL_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 EL_MODIFIED_DATE DATE DEFAULT SYSDATE,
 EL_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 EL_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (EL_SITE_CODE, EL_STAFF_ID)
);
ALTER TABLE EL_STAFFS_HOLIDAY ADD (
 CONSTRAINT EL_STAFFS_HOLIDAY_R01
 FOREIGN KEY (EL_SITE_CODE, EL_STAFF_ID)
 REFERENCES CO_STAFFS (CO_SITE_CODE, CO_STAFF_ID));
