ALTER TABLE EL_TYPE
 DROP PRIMARY KEY CASCADE;
DROP TABLE EL_TYPE CASCADE CONSTRAINTS;

CREATE TABLE EL_TYPE
(
 EL_TYPE_ID NUMBER(*,0) NOT NULL ENABLE,
 EL_TYPE_DESC VARCHAR2(100 BYTE),
 EL_CREATED_DATE DATE DEFAULT SYSDATE,
 EL_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 EL_MODIFIED_DATE DATE DEFAULT SYSDATE,
 EL_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 EL_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (EL_TYPE_ID)
);

--INSERT INTO EL_TYPE(EL_TYPE_ID, EL_TYPE_DESC) VALUES ('Annual Leave');
INSERT INTO EL_TYPE(EL_TYPE_ID, EL_TYPE_DESC) VALUES (2, 'Birthday Leave');
INSERT INTO EL_TYPE(EL_TYPE_ID, EL_TYPE_DESC) VALUES (3, 'Holiday Leave');
INSERT INTO EL_TYPE(EL_TYPE_ID, EL_TYPE_DESC) VALUES (4, 'Sick Leave');