ALTER TABLE EL_TRANSACTION
 DROP PRIMARY KEY CASCADE;
DROP TABLE EL_TRANSACTION CASCADE CONSTRAINTS;

CREATE TABLE EL_TRANSACTION
(
 EL_TRANSACTION_ID NUMBER (*,0) NOT NULL,
 EL_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 EL_STAFF_ID VARCHAR2(10 BYTE) NOT NULL,
 EL_HOLIDAY_TYPE NUMBER(*,0) NOT NULL,
 EL_VALUE NUMBER(*,0) DEFAULT 0,
 EL_CREATED_DATE DATE DEFAULT SYSDATE,
 EL_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 EL_MODIFIED_DATE DATE DEFAULT SYSDATE,
 EL_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 EL_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (EL_TRANSACTION_ID)
);
