ALTER TABLE HAA_CHECKLIST
 DROP PRIMARY KEY CASCADE;
DROP TABLE HAA_CHECKLIST CASCADE CONSTRAINTS;

CREATE TABLE HAA_CHECKLIST
(
 HAA_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 HAA_CHECKLIST_ID NUMBER(*,0) NOT NULL ENABLE,
 HAA_CORP_NAME VARCHAR2(100 BYTE),
 HAA_BUSINESS_TYPE VARCHAR2(50 BYTE),
 HAA_CONTRACT_DATE_FROM DATE NULL,
 HAA_CONTRACT_DATE_TO DATE NULL,
 HAA_CODE VARCHAR2(30 BYTE),
 HAA_CREATED_DATE DATE DEFAULT SYSDATE,
 HAA_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 HAA_MODIFIED_DATE DATE DEFAULT SYSDATE,
 HAA_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 HAA_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (HAA_SITE_CODE, HAA_CHECKLIST_ID)
);
ALTER TABLE HAA_CHECKLIST ADD (
 CONSTRAINT HAA_CHECKLIST_R01
 FOREIGN KEY (HAA_SITE_CODE)
 REFERENCES CO_SITE (CO_SITE_CODE));