ALTER TABLE HAT_PATIENT
 DROP PRIMARY KEY CASCADE;
DROP TABLE HAT_PATIENT CASCADE CONSTRAINTS;

CREATE TABLE HAT_PATIENT_IMTINFO
(
 HAT_ADMNO NUMBER(*,0) DEFAULT 1,
 HAT_IMTINFO_ID NUMBER(*,0),
 HAT_CREATED_DATE DATE DEFAULT SYSDATE,
 HAT_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 HAT_MODIFIED_DATE DATE DEFAULT SYSDATE,
 HAT_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 HAT_ENABLED NUMBER(*,0) DEFAULT 1,
);