CREATE OR REPLACE FUNCTION "HAT_GET_COUNTRY"
(V_COUCODE VARCHAR2)
	RETURN Types.cursor_type
AS
	outcur types.cursor_type;
BEGIN
	OPEN outcur FOR
		SELECT COUDESC
		FROM   COUNTRY@IWEB
		WHERE  COUCODE = v_COUCODE
		AND    ROWNUM < 100
		ORDER BY COUCODE;
	RETURN OUTCUR;
END HAT_GET_COUNTRY;

/