CREATE OR REPLACE FUNCTION "HAT_CMB_COUNTRY" 
RETURN types.cursor_type 
AS
outcur types.cursor_type;
BEGIN
	OPEN outcur FOR 
		SELECT COUCODE,COUDESC
		FROM   COUNTRY@IWEB
		WHERE  ROWNUM<100
		ORDER BY COUDESC;
		RETURN outcur;
END HAT_CMB_COUNTRY;

/