CREATE OR REPLACE FUNCTION "HAT_CMB_LOCATION" 
RETURN types.cursor_type 
AS
outcur types.cursor_type;
BEGIN
	OPEN outcur FOR 
		SELECT LOCCODE,LOCNAME
		FROM LOCATION@IWEB
		WHERE ROWNUM < 100
		ORDER BY LOCNAME;
		RETURN outcur;
END HAT_CMB_LOCATION;

/