ALTER TABLE HAT_XREPORTDTLS
 DROP PRIMARY KEY CASCADE;
DROP TABLE HAT_XREPORTDTLS CASCADE CONSTRAINTS;

CREATE TABLE HAT_XREPORTDTLS 
(	
	XRPID NUMBER(22,0), 
	XRDDTLS LONG RAW, 
	XRDSIZE NUMBER(22,0), 
	XWORDRPT BLOB, 
	ISWORD NUMBER(1,0)
);