ALTER TABLE HAT_PATIENT_DOCUMENTS
 DROP PRIMARY KEY CASCADE;
DROP TABLE HAT_PATIENT_DOCUMENTS CASCADE CONSTRAINTS;

CREATE TABLE HAT_PATIENT_DOCUMENTS
(
 HAT_ADMNO NUMBER(*,0) DEFAULT 1,
 HAT_DOCUMENT_ID NUMBER(*,0) DEFAULT 1,
 HAT_DOCUMENT_DESC VARCHAR2(200 BYTE) NOT NULL,
 HAT_CREATED_DATE DATE DEFAULT SYSDATE,
 HAT_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 HAT_MODIFIED_DATE DATE DEFAULT SYSDATE,
 HAT_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 HAT_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (HAT_ADMNO, HAT_DOCUMENT_ID)
);
ALTER TABLE HAT_PATIENT_DOCUMENTS ADD (
 CONSTRAINT HAT_PATIENT_DOCUMENTS_R01
 FOREIGN KEY (HAT_ADMNO)
 REFERENCES HAT_PATIENT (HAT_ADMNO));