ALTER TABLE PMP_PROJECT_COMMENTS
 DROP PRIMARY KEY CASCADE;
DROP TABLE PMP_PROJECT_COMMENTS CASCADE CONSTRAINTS;

CREATE TABLE PMP_PROJECT_COMMENTS
(
 PMP_PROJECT_ID NUMBER(*,0) NOT NULL,
 PMP_COMMENT_ID NUMBER(*,0) DEFAULT 1,
 PMP_COMMENT_HISTORY_ID NUMBER(*,0) DEFAULT 0,
 PMP_COMMENT_TYPE VARCHAR2(20 BYTE) NOT NULL,
 PMP_TOPIC_DESC VARCHAR2(100 BYTE) NOT NULL,
 PMP_INVOLVE_DEPARTMENT_CODE NUMBER(*,0) NULL,
 PMP_INVOLVE_USER_ID VARCHAR2(20 BYTE) NULL,
 PMP_DEADLINE DATE NULL,
 PMP_EMAIL_NOTIFY VARCHAR2(1 BYTE) NULL,
 PMP_CREATED_DATE DATE DEFAULT SYSDATE,
 PMP_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 PMP_MODIFIED_DATE DATE DEFAULT SYSDATE,
 PMP_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 PMP_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (PMP_PROJECT_ID, PMP_COMMENT_ID, PMP_COMMENT_HISTORY_ID)
);
ALTER TABLE PMP_PROJECT_COMMENTS ADD (
 CONSTRAINT PMP_PROJECT_COMMENTS_R01
 FOREIGN KEY (PMP_PROJECT_ID)
 REFERENCES PMP_PROJECTS (PMP_PROJECT_ID));