ALTER TABLE PMP_PROJECT_COMMENT_TYPES
 DROP PRIMARY KEY CASCADE;
DROP TABLE PMP_PROJECT_COMMENT_TYPES CASCADE CONSTRAINTS;

CREATE TABLE PMP_PROJECT_COMMENT_TYPES
(
 PMP_COMMENT_TYPE VARCHAR2(20 BYTE) NOT NULL,
 PMP_ORDER_SEQUENCE NUMBER(*,0) DEFAULT 1,
 PMP_CREATED_DATE DATE DEFAULT SYSDATE,
 PMP_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 PMP_MODIFIED_DATE DATE DEFAULT SYSDATE,
 PMP_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 PMP_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (PMP_COMMENT_TYPE)
);
SET DEFINE OFF
INSERT INTO PMP_PROJECT_COMMENT_TYPES (PMP_COMMENT_TYPE, PMP_ORDER_SEQUENCE) VALUES ('urgent', 0);
INSERT INTO PMP_PROJECT_COMMENT_TYPES (PMP_COMMENT_TYPE, PMP_ORDER_SEQUENCE) VALUES ('q & a', 1);
INSERT INTO PMP_PROJECT_COMMENT_TYPES (PMP_COMMENT_TYPE, PMP_ORDER_SEQUENCE) VALUES ('issue', 1);
INSERT INTO PMP_PROJECT_COMMENT_TYPES (PMP_COMMENT_TYPE, PMP_ORDER_SEQUENCE) VALUES ('to do', 1);
INSERT INTO PMP_PROJECT_COMMENT_TYPES (PMP_COMMENT_TYPE, PMP_ORDER_SEQUENCE) VALUES ('in progress', 2);
INSERT INTO PMP_PROJECT_COMMENT_TYPES (PMP_COMMENT_TYPE, PMP_ORDER_SEQUENCE) VALUES ('memo', 3);
INSERT INTO PMP_PROJECT_COMMENT_TYPES (PMP_COMMENT_TYPE, PMP_ORDER_SEQUENCE) VALUES ('done', 4);
INSERT INTO PMP_PROJECT_COMMENT_TYPES (PMP_COMMENT_TYPE, PMP_ORDER_SEQUENCE) VALUES ('delete', 5);
INSERT INTO PMP_PROJECT_COMMENT_TYPES (PMP_COMMENT_TYPE, PMP_ORDER_SEQUENCE) VALUES ('archive', 6);