ALTER TABLE AC_DOCUMENT_ACCESS
 DROP PRIMARY KEY CASCADE;
DROP TABLE AC_DOCUMENT_ACCESS CASCADE CONSTRAINTS;

CREATE TABLE AC_DOCUMENT_ACCESS
(
 AC_DOCUMENT_ID NUMBER(*,0) NOT NULL ENABLE,
 AC_SITE_CODE VARCHAR2(10 BYTE) DEFAULT 'hkah' NOT NULL ENABLE,
 AC_STAFF_ID VARCHAR2(10 BYTE) DEFAULT 'ALL' NOT NULL ENABLE,
 AC_GROUP_ID VARCHAR2(50 BYTE) DEFAULT 'ALL',
 AC_CREATED_DATE DATE DEFAULT SYSDATE,
 AC_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 AC_MODIFIED_DATE DATE DEFAULT SYSDATE,
 AC_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 AC_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (AC_DOCUMENT_ID, AC_SITE_CODE, AC_STAFF_ID, AC_GROUP_ID)
);

ALTER TABLE AC_DOCUMENT_ACCESS ADD (
 CONSTRAINT AC_DOCUMENT_ACCESS_R01
 FOREIGN KEY (AC_DOCUMENT_ID)
 REFERENCES CO_DOCUMENT (CO_DOCUMENT_ID));

--ALTER TABLE AC_DOCUMENT_ACCESS ADD (
-- CONSTRAINT AC_DOCUMENT_ACCESS_R02
-- FOREIGN KEY (AC_SITE_CODE, AC_STAFF_ID)
-- REFERENCES CO_STAFFS (CO_SITE_CODE, CO_STAFF_ID));

/*
select AC_DOCUMENT_ID, AC_SITE_CODE, AC_STAFF_ID, AC_GROUP_ID, count(1)
from AC_DOCUMENT_ACCESS
group by AC_DOCUMENT_ID, AC_SITE_CODE, AC_STAFF_ID, AC_GROUP_ID
having count(1) > 1;

select * from AC_DOCUMENT_ACCESS2 where AC_DOCUMENT_ID not in (select CO_DOCUMENT_ID from CO_DOCUMENT);

insert into AC_DOCUMENT_ACCESS2 select AC_DOCUMENT_ID, AC_SITE_CODE, AC_STAFF_ID, AC_GROUP_ID, AC_CREATED_DATE, AC_CREATED_USER, AC_MODIFIED_DATE, AC_MODIFIED_USER, AC_ENABLED FROM AC_DOCUMENT_ACCESS;

insert into AC_DOCUMENT_ACCESS select * from AC_DOCUMENT_ACCESS2;
*/