ALTER TABLE AC_FUNCTION_ACCESS_LOG
 DROP PRIMARY KEY CASCADE;
DROP TABLE AC_FUNCTION_ACCESS_LOG CASCADE CONSTRAINTS;

CREATE TABLE AC_FUNCTION_ACCESS_LOG
(
 AC_FUNCTION_ID VARCHAR2(50 BYTE) NOT NULL,
 AC_REFERER VARCHAR2(3000 BYTE),
 AC_USER_TYPE VARCHAR2(10 BYTE) NOT NULL,	-- staff, patient
 AC_USER_ID VARCHAR2(20 BYTE),
 AC_IP_ADDRESS VARCHAR2(20 BYTE),
 AC_CREATED_DATE DATE DEFAULT SYSDATE,
 AC_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 AC_MODIFIED_DATE DATE DEFAULT SYSDATE,
 AC_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 AC_ENABLED NUMBER(*,0) DEFAULT 1
);