ALTER TABLE AC_FUNCTION_ACCESS
 DROP PRIMARY KEY CASCADE;
DROP TABLE AC_FUNCTION_ACCESS CASCADE CONSTRAINTS;

CREATE TABLE AC_FUNCTION_ACCESS
(
 AC_FUNCTION_ID VARCHAR2(50 BYTE) NOT NULL,
 AC_SITE_CODE VARCHAR2(10 BYTE) DEFAULT 'ALL',
 AC_STAFF_ID VARCHAR2(10 BYTE) DEFAULT 'ALL',
 AC_GROUP_ID VARCHAR2(50 BYTE) DEFAULT 'ALL',
 AC_ACCESS_MODE VARCHAR2(1 BYTE) DEFAULT 'F',	/* [F]ull, [R]ead */
 AC_CREATED_DATE DATE DEFAULT SYSDATE,
 AC_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 AC_MODIFIED_DATE DATE DEFAULT SYSDATE,
 AC_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 AC_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (AC_FUNCTION_ID, AC_SITE_CODE, AC_STAFF_ID, AC_GROUP_ID)
);
ALTER TABLE AC_FUNCTION_ACCESS ADD (
 CONSTRAINT AC_FUNCTION_ACCESS_R01
 FOREIGN KEY (AC_FUNCTION_ID)
 REFERENCES AC_FUNCTION (AC_FUNCTION_ID));
