ALTER TABLE AC_FUNCTION_HIT_RATE
 DROP PRIMARY KEY CASCADE;
DROP TABLE AC_FUNCTION_HIT_RATE CASCADE CONSTRAINTS;

CREATE TABLE AC_FUNCTION_HIT_RATE
(
 AC_FUNCTION_ID VARCHAR2(50 BYTE) NOT NULL,
 AC_HIT_DATE VARCHAR2(10 BYTE) NOT NULL,
 AC_HIT_RATE int DEFAULT 1,
 AC_CREATED_DATE DATE DEFAULT SYSDATE,
 AC_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 AC_MODIFIED_DATE DATE DEFAULT SYSDATE,
 AC_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 AC_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (AC_FUNCTION_ID, AC_HIT_DATE)
);
ALTER TABLE AC_FUNCTION_HIT_RATE ADD (
 CONSTRAINT AC_FUNCTION_HIT_RATE_R01
 FOREIGN KEY (AC_FUNCTION_ID)
 REFERENCES AC_FUNCTION (AC_FUNCTION_ID));