ALTER TABLE AC_FUNCTION
 DROP PRIMARY KEY CASCADE;
DROP TABLE AC_FUNCTION CASCADE CONSTRAINTS;

CREATE TABLE AC_FUNCTION
(
 AC_FUNCTION_ID VARCHAR2(50 BYTE) NOT NULL,
 AC_FUNCTION_DESC VARCHAR2(50 BYTE),
 AC_GROUP_ID VARCHAR2(30 BYTE) NOT NULL,
 AC_INTRANET_ONLY NUMBER(*,0) DEFAULT 0,	-- 0 for all, 1 for intranet only
 AC_CREATED_DATE DATE DEFAULT SYSDATE,
 AC_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 AC_MODIFIED_DATE DATE DEFAULT SYSDATE,
 AC_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 AC_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (AC_FUNCTION_ID)
);
