ALTER TABLE AC_USER_GROUPS
 DROP PRIMARY KEY CASCADE;
DROP TABLE AC_USER_GROUPS CASCADE CONSTRAINTS;

CREATE TABLE AC_USER_GROUPS
(
 AC_SITE_CODE VARCHAR2(10 BYTE) NULL,
 AC_STAFF_ID VARCHAR2(10 BYTE) NULL,
 AC_GROUP_ID VARCHAR2(50 BYTE) NOT NULL ENABLE,
 AC_CREATED_DATE DATE DEFAULT SYSDATE,
 AC_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 AC_MODIFIED_DATE DATE DEFAULT SYSDATE,
 AC_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 AC_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (AC_SITE_CODE, AC_STAFF_ID, AC_GROUP_ID)
);
ALTER TABLE AC_USER_GROUPS ADD (
 CONSTRAINT AC_USER_GROUPS_R01
 FOREIGN KEY (AC_GROUP_ID)
 REFERENCES CO_GROUPS (CO_GROUP_ID));
ALTER TABLE AC_USER_GROUPS ADD (
 CONSTRAINT AC_USER_GROUPS_R02
 FOREIGN KEY (AC_SITE_CODE, AC_STAFF_ID)
 REFERENCES CO_STAFFS (CO_SITE_CODE, CO_STAFF_ID));
