CREATE TABLE BA_CHECKLIST_PROGRESS
(
  BA_SITE_CODE VARCHAR2(10) NOT NULL,
  BA_CHECKLIST_ID NUMBER NOT NULL,
  BA_CHECKLIST_DID NUMBER NOT NULL,
  BA_PROGRESS VARCHAR2(1000),
  BA_FIRST_CONTACT_DATE DATE,
  BA_CREATED_DATE DATE DEFAULT SYSDATE,
  BA_CREATED_USER VARCHAR2(30) DEFAULT 'SYSTEM',
  BA_MODIFIED_DATE DATE DEFAULT SYSDATE,
  BA_MODIFIED_USER VARCHAR2(30) DEFAULT 'SYSTEM',
  BA_ENABLED NUMBER, 
  PRIMARY KEY (BA_CHECKLIST_ID, BA_CHECKLIST_PID)
);

ALTER TABLE BA_CHECKLIST_PROGRESS ADD (
 CONSTRAINT BA_CHECKLIST_PROGRESS_R01
 FOREIGN KEY (BA_SITE_CODE)
 REFERENCES CO_SITE (CO_SITE_CODE));
 
