CREATE TABLE HKAH.BA_CHECKLIST_DEPT
   (
   	BA_CHECKLIST_DID NUMBER NOT NULL , 
   	BA_CHECKLIST_DEPT_DESC VARCHAR2(50 BYTE),
	BA_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM', 
	BA_CREATED_DATE DATE DEFAULT SYSDATE, 
	BA_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM', 
	BA_MODIFIED_DATE DATE DEFAULT SYSDATE,
	PRIMARY KEY (BA_CHECKLIST_DID)
	};