ALTER TABLE BA_CHECKLIST
 DROP PRIMARY KEY CASCADE;
DROP TABLE BA_CHECKLIST CASCADE CONSTRAINTS;

CREATE TABLE BA_CHECKLIST
(
  BA_SITE_CODE VARCHAR2(10) NOT NULL,
  BA_MODULE_CODE VARCHAR2(10 BYTE) DEFAULT 'marketing',	-- marketing, external
  BA_CHECKLIST_ID NUMBER NOT NULL,
  BA_CHECKLIST_PARENT_ID NUMBER NULL,
  BA_REQ_DEPARTMENT_CODE NUMBER(*,0) NULL,
  BA_RES_DEPARTMENT_CODE NUMBER(*,0) NULL,
  BA_CORP_NAME VARCHAR2(100) NULL,
  BA_BUSINESS_TYPE VARCHAR2(50) NULL,
  BA_BUSINESS_NATURE VARCHAR2(50) NULL,
  BA_BUSINESS_INFO VARCHAR2(300) NULL,
  BA_CONTRACT_DATE_FROM DATE NULL,
  BA_CONTRACT_DATE_TO DATE NULL,
  BA_CODE VARCHAR2(30) NULL,
  BA_REMARK VARCHAR2(500) NULL,
  BA_EXPIRED VARCHAR2(20) DEFAULT 'NO',
  BA_OPT_CURRENCY VARCHAR2(3) NULL,
  BA_OPT_AMOUNT NUMBER(*,2) NULL,
  BA_OPT_UNIT VARCHAR2(20) NULL,
  BA_CONTINGENCY VARCHAR2(20) NULL,
  BA_CREATED_DATE DATE DEFAULT SYSDATE,
  BA_CREATED_USER VARCHAR2(30) DEFAULT 'SYSTEM',
  BA_MODIFIED_DATE DATE DEFAULT SYSDATE,
  BA_MODIFIED_USER VARCHAR2(30) DEFAULT 'SYSTEM',
  BA_ENABLED NUMBER(*,0) DEFAULT 1,
  PRIMARY KEY (BA_SITE_CODE, BA_MODULE_CODE, BA_CHECKLIST_ID)
);

ALTER TABLE BA_CHECKLIST ADD (
 CONSTRAINT BA_CHECKLIST_R01
 FOREIGN KEY (BA_SITE_CODE)
 REFERENCES CO_SITE (CO_SITE_CODE));