ALTER TABLE BA_RENEW
 DROP PRIMARY KEY CASCADE;
DROP TABLE BA_RENEW CASCADE CONSTRAINTS;

CREATE TABLE BA_RENEW
(
  BA_SITE_CODE VARCHAR2(10) NOT NULL,
  BA_MODULE_CODE VARCHAR2(10 BYTE) DEFAULT 'marketing',	-- marketing, external
  BA_CHECKLIST_ID NUMBER NOT NULL,
  BA_RENEW_ID NUMBER NOT NULL,
  BA_CONTRACT_DATE_FROM DATE NULL,
  BA_CONTRACT_DATE_TO DATE NULL,
  BA_APPROVAL_DATE DATE NULL,
  BA_APPROVAL_USER VARCHAR2(30) NULL,
  BA_CREATED_DATE DATE DEFAULT SYSDATE,
  BA_CREATED_USER VARCHAR2(30) DEFAULT 'SYSTEM',
  BA_MODIFIED_DATE DATE DEFAULT SYSDATE,
  BA_MODIFIED_USER VARCHAR2(30) DEFAULT 'SYSTEM',
  BA_ENABLED NUMBER(*,0) DEFAULT 1,
  BA_REQ_DEPARTMENT_CODE NUMBER,
  BA_BUSINESS_INFO       VARCHAR2(300 BYTE),
  BA_OPT_CURRENCY        VARCHAR2(3 BYTE),
  BA_OPT_AMOUNT          NUMBER,
  BA_OPT_UNIT            VARCHAR2(10 BYTE),
  BA_REMARK              VARCHAR2(500 BYTE),
  BA_ASSODEPT_CODE       VARCHAR2(100 BYTE),
  BA_ASSODEPT_NAME       VARCHAR2(500 BYTE),
  BA_ASSODEPT_REQUEST_ID VARCHAR2(100 BYTE),
  DOC_ID                 VARCHAR2(200 BYTE),
  PRIMARY KEY (BA_SITE_CODE, BA_MODULE_CODE, BA_CHECKLIST_ID, BA_RENEW_ID)
);

ALTER TABLE BA_RENEW ADD (
 CONSTRAINT BA_RENEW_R01
 FOREIGN KEY (BA_SITE_CODE, BA_MODULE_CODE, BA_CHECKLIST_ID)
 REFERENCES BA_CHECKLIST (BA_SITE_CODE, BA_MODULE_CODE, BA_CHECKLIST_ID));