ALTER TABLE CE_CONTINUING_EDUCATION
 DROP PRIMARY KEY CASCADE;
DROP TABLE CE_CONTINUING_EDUCATION CASCADE CONSTRAINTS;

CREATE TABLE CE_CONTINUING_EDUCATION
(
 CE_CONTINUING_EDUCATION_ID NUMBER(*,0) NOT NULL ENABLE,
 CE_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 CE_STAFF_ID VARCHAR2(10 BYTE) NOT NULL,
 CE_COURSE_NAME VARCHAR2(50 BYTE) NOT NULL,
 CE_COURSE_SPONSOR VARCHAR2(100 BYTE) NOT NULL,     --SPONSOR/ORGANIZER OF COURSE
 CE_DOCUMENT_LOCATION VARCHAR2(200 BYTE),
 CE_CONTINUING_EDUCATION add( CE_DOCUMENT_ID VARCHAR2(200 BYTE),
 CE_LOCATION_ATTENDANCE VARCHAR2(100 BYTE) NOT NULL,
 CE_FROM_DATE DATE DEFAULT SYSDATE,
 CE_TO_DATE DATE DEFAULT SYSDATE,
 CE_APPLIED_HOURS NUMBER(*,2) NOT NULL,		--hours requested
 CE_FEE NUMBER(*,2) NOT NULL,
 CE_BENEFIT_EMPLOYEE  VARCHAR2(500 BYTE) NOT NULL,
 CE_BENEFIT_DEPARTMENT  VARCHAR2(500 BYTE) NOT NULL,
 CE_STATUS VARCHAR2(1 BYTE) DEFAULT 'O',		-- O - Open, M - Approved by Manager, A - APPROVED BY ADMINISTRATOR H - APPROVED BY HR, R - Reject, C - Cancel
 CE_APPROVE_MGR_STAFF_ID VARCHAR2(10 BYTE) NULL,    -- dept head/supervisor approval
 CE_APPROVE_MGR_DATE DATE NULL,
 CE_APPROVE_ADMIN_STAFF_ID VARCHAR2(10 BYTE) NULL,   -- director /president /vice-president approval
 CE_APPROVE_ADMIN_DATE DATE NULL,
  CE_APPROVE_HR_STAFF_ID VARCHAR2(10 BYTE) NULL,
 CE_APPROVE_HR_DATE DATE NULL,
 CE_CREATED_DATE DATE DEFAULT SYSDATE,
 CE_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CE_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CE_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CE_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CE_CONTINUING_EDUCATION_ID)
);
ALTER TABLE CE_CONTINUING_EDUCATION ADD (
 CONSTRAINT CE_CONTINUING_EDUCATION_R01
 FOREIGN KEY (CE_SITE_CODE, CE_STAFF_ID)
 REFERENCES CO_STAFFS (CO_SITE_CODE, CO_STAFF_ID));
 --alter table CE_CONTINUING_EDUCATION add( CE_DOCUMENT_ID VARCHAR2(200 BYTE));