ALTER TABLE CE_TOTAL
 DROP PRIMARY KEY CASCADE;
DROP TABLE CE_TOTAL CASCADE CONSTRAINTS;

CREATE TABLE CE_TOTAL
(
 CE_TOTAL_ID NUMBER(*,0) NOT NULL ENABLE,
 CE_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 CE_DEPT_ID VARCHAR2(10 BYTE) NULL,
 CE_DEPT_DESC VARCHAR2(30 BYTE)  NULL,    
 CE_POSITION_DESC VARCHAR2(30 BYTE) NULL, 
 CE_POSITION_CODE VARCHAR2(10 BYTE) NULL,
 CE_HIRE_DATE DATE NOT NULL,
-- CE_RATE NUMBER(*,0) NOT NULL,  --XXX
 CE_STAFF_ID VARCHAR2(10 BYTE) NOT NULL,
 CE_B_YEAR DATE NOT NULL,             --BUDGETED_YEAR
 CE_BY_HOURS  NUMBER(*,2) NOT NULL,    --BUDGETED_YEAR_HOURS
 CE_BY_AMOUNT  NUMBER(*,2) NOT NULL,   --BUDGETED_YEAR_AMOUNT
 CE_BL_HOURS  NUMBER(*,2) NOT NULL ,    --BUDGETED_LEFT_HOURS
 CE_BL_AMOUNT  NUMBER(*,2) NOT NULL ,   --BUDGETED_LEFT_AMOUNT 
 CE_REMARK VARCHAR2(200 BYTE) NULL,
 CE_CREATED_DATE DATE DEFAULT SYSDATE,
 CE_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CE_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CE_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 
 CE_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CE_TOTAL_ID)
);


alter table CE_TOTAL MODIFY( CE_DEPT_DESC VARCHAR2(30 BYTE)  NULL );
alter table CE_TOTAL MODIFY(CE_POSITION_DESC VARCHAR2(30 BYTE) NULL) ;
alter table CE_TOTAL MODIFY(CE_POSITION_CODE VARCHAR2(10 BYTE) NULL) ;
--ALTER TABLE CE_TOTAL DROP COLUMN CE_RATE;
alter table CE_TOTAL ADD(  CE_BUDGETED_YEAR DATE NOT NULL );
alter table CE_TOTAL ADD(  CE_BUDGETED_YEAR_HOURS NUMBER(*,2) NOT NULL );
alter table CE_TOTAL ADD(  CE_BUDGETED_YEAR_AMOUNT NUMBER(*,2) NOT NULL );
alter table CE_TOTAL ADD(  CE_BUDGETED_LEFT_HOURS NUMBER(*,2) NOT NULL );
alter table CE_TOTAL ADD(  CE_BUDGETED_LEFT_AMOUNT  NUMBER(*,2) NOT NULL );

update ce_total t set t.ce_dept_id=(select s.co_department_code from co_staffs s where t.ce_staff_id=s.co_staff_id),
t.ce_dept_desc=(select b.co_department_desc from co_staffs b where t.ce_staff_id=b.co_staff_id);

