ALTER TABLE CH_REPORT_LOG
 DROP PRIMARY KEY CASCADE;
DROP TABLE CH_REPORT_LOG CASCADE CONSTRAINTS;

CREATE TABLE CH_REPORT_LOG
  (
      CO_SITE_CODE     	        VARCHAR2(10 BYTE),
      CH_REPORT_ID	            NUMBER NOT NULL,  
      CH_REPORT_MODULE          VARCHAR2(10 BYTE) NOT NULL,
      CH_REPORT_PATNO           VARCHAR2(10 BYTE),
      CH_REPORT_PATH            VARCHAR2(1000 BYTE),
      CH_REPORT_KEY_ID          VARCHAR2(50 BYTE),
      CH_REPORT_DETAIL          VARCHAR2(1000 BYTE),
      CH_REPORT_REMARK          VARCHAR2(1000 BYTE),
      CH_REPORT_COMMENT         VARCHAR2(1000 BYTE),
      CH_REPORT_FIXED           NUMBER(1,0) DEFAULT 0,
      CH_REPORT_FIXED_DATE      DATE,
  	  CH_CREATE_DATE 			DATE DEFAULT SYSDATE,
      CH_CREATE_USER 			VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
      CH_MODIFIED_DATE 		    DATE DEFAULT SYSDATE,
      CH_MODIFIED_USER 		    VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
      CH_ENABLED 				NUMBER(1,0) DEFAULT 1,
      PRIMARY KEY(CH_REPORT_ID)
  );