--Init
  --Insert to CO_EVENT
Insert into CO_EVENT (CO_SITE_CODE,CO_MODULE_CODE,CO_EVENT_ID,CO_EVENT_DESC,CO_EVENT_SHORT_DESC,CO_EVENT_CATEGORY,CO_EVENT_TYPE,CO_DEPARTMENT_CODE,CO_EVENT_REMARK,CO_EVENT_REMARK2,CO_CREATED_DATE,CO_CREATED_USER,CO_MODIFIED_DATE,CO_MODIFIED_USER,CO_ENABLED,CO_EVENT_TYPE2,CO_REQUIRE_ASSESSMENT_PASS) values ('hkah','christmas',1,'Christmas Gathering 2011',null,'other','party',null,null,null,SYSDATE,'SYSTEM',SYSDATE,'SYSTEM',1,null,'N');

  --Insert to CO_SCHEDULE
INSERT INTO CO_SCHEDULE (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_SCHEDULE_ID, CO_SCHEDULE_DESC, CO_SCHEDULE_START, CO_SCHEDULE_END, CO_SCHEDULE_SIZE) VALUES ('hkah', 'christmas', '1', '1', 'Group 1', TO_DATE('17-11月 -11', 'DD-MON-RR'), TO_DATE('30-11月 -11', 'DD-MON-RR'), '12');
INSERT INTO CO_SCHEDULE (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_SCHEDULE_ID, CO_SCHEDULE_DESC, CO_SCHEDULE_START, CO_SCHEDULE_END, CO_SCHEDULE_SIZE) VALUES ('hkah', 'christmas', '1', '2', 'Group 2', TO_DATE('17-11月 -11', 'DD-MON-RR'), TO_DATE('30-11月 -11', 'DD-MON-RR'), '12');
INSERT INTO CO_SCHEDULE (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_SCHEDULE_ID, CO_SCHEDULE_DESC, CO_SCHEDULE_START, CO_SCHEDULE_END, CO_SCHEDULE_SIZE) VALUES ('hkah', 'christmas', '1', '3', 'Group 3', TO_DATE('17-11月 -11', 'DD-MON-RR'), TO_DATE('30-11月 -11', 'DD-MON-RR'), '12');
INSERT INTO CO_SCHEDULE (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_SCHEDULE_ID, CO_SCHEDULE_DESC, CO_SCHEDULE_START, CO_SCHEDULE_END, CO_SCHEDULE_SIZE) VALUES ('hkah', 'christmas', '1', '4', 'Group 4', TO_DATE('17-11月 -11', 'DD-MON-RR'), TO_DATE('30-11月 -11', 'DD-MON-RR'), '12');
INSERT INTO CO_SCHEDULE (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_SCHEDULE_ID, CO_SCHEDULE_DESC, CO_SCHEDULE_START, CO_SCHEDULE_END, CO_SCHEDULE_SIZE) VALUES ('hkah', 'christmas', '1', '5', 'Group 5', TO_DATE('17-11月 -11', 'DD-MON-RR'), TO_DATE('30-11月 -11', 'DD-MON-RR'), '12');
INSERT INTO CO_SCHEDULE (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_SCHEDULE_ID, CO_SCHEDULE_DESC, CO_SCHEDULE_START, CO_SCHEDULE_END, CO_SCHEDULE_SIZE) VALUES ('hkah', 'christmas', '1', '6', 'Group 6', TO_DATE('17-11月 -11', 'DD-MON-RR'), TO_DATE('30-11月 -11', 'DD-MON-RR'), '12');
INSERT INTO CO_SCHEDULE (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_SCHEDULE_ID, CO_SCHEDULE_DESC, CO_SCHEDULE_START, CO_SCHEDULE_END, CO_SCHEDULE_SIZE) VALUES ('hkah', 'christmas', '1', '7', 'Group 7', TO_DATE('17-11月 -11', 'DD-MON-RR'), TO_DATE('30-11月 -11', 'DD-MON-RR'), '12');
INSERT INTO CO_SCHEDULE (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_SCHEDULE_ID, CO_SCHEDULE_DESC, CO_SCHEDULE_START, CO_SCHEDULE_END, CO_SCHEDULE_SIZE) VALUES ('hkah', 'christmas', '1', '8', 'Group 8', TO_DATE('17-11月 -11', 'DD-MON-RR'), TO_DATE('30-11月 -11', 'DD-MON-RR'), '12');
INSERT INTO CO_SCHEDULE (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_SCHEDULE_ID, CO_SCHEDULE_DESC, CO_SCHEDULE_START, CO_SCHEDULE_END, CO_SCHEDULE_SIZE) VALUES ('hkah', 'christmas', '1', '9', 'Group 9', TO_DATE('17-11月 -11', 'DD-MON-RR'), TO_DATE('30-11月 -11', 'DD-MON-RR'), '12');
INSERT INTO CO_SCHEDULE (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_SCHEDULE_ID, CO_SCHEDULE_DESC, CO_SCHEDULE_START, CO_SCHEDULE_END, CO_SCHEDULE_SIZE) VALUES ('hkah', 'christmas', '1', '10', 'Group 10', TO_DATE('17-11月 -11', 'DD-MON-RR'), TO_DATE('30-11月 -11', 'DD-MON-RR'), '12');
INSERT INTO CO_SCHEDULE (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_SCHEDULE_ID, CO_SCHEDULE_DESC, CO_SCHEDULE_START, CO_SCHEDULE_END, CO_SCHEDULE_SIZE) VALUES ('hkah', 'christmas', '1', '11', 'Group 11', TO_DATE('17-11月 -11', 'DD-MON-RR'), TO_DATE('30-11月 -11', 'DD-MON-RR'), '12');
INSERT INTO CO_SCHEDULE (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_SCHEDULE_ID, CO_SCHEDULE_DESC, CO_SCHEDULE_START, CO_SCHEDULE_END, CO_SCHEDULE_SIZE) VALUES ('hkah', 'christmas', '1', '12', 'Group 12', TO_DATE('17-11月 -11', 'DD-MON-RR'), TO_DATE('30-11月 -11', 'DD-MON-RR'), '12');
INSERT INTO CO_SCHEDULE (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_SCHEDULE_ID, CO_SCHEDULE_DESC, CO_SCHEDULE_START, CO_SCHEDULE_END, CO_SCHEDULE_SIZE) VALUES ('hkah', 'christmas', '1', '13', 'Group 13', TO_DATE('17-11月 -11', 'DD-MON-RR'), TO_DATE('30-11月 -11', 'DD-MON-RR'), '12');
INSERT INTO CO_SCHEDULE (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_SCHEDULE_ID, CO_SCHEDULE_DESC, CO_SCHEDULE_START, CO_SCHEDULE_END, CO_SCHEDULE_SIZE) VALUES ('hkah', 'christmas', '1', '14', 'Group 14', TO_DATE('17-11月 -11', 'DD-MON-RR'), TO_DATE('30-11月 -11', 'DD-MON-RR'), '12');
INSERT INTO CO_SCHEDULE (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_SCHEDULE_ID, CO_SCHEDULE_DESC, CO_SCHEDULE_START, CO_SCHEDULE_END, CO_SCHEDULE_SIZE) VALUES ('hkah', 'christmas', '1', '15', 'Group 15', TO_DATE('17-11月 -11', 'DD-MON-RR'), TO_DATE('30-11月 -11', 'DD-MON-RR'), '12');
INSERT INTO CO_SCHEDULE (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_SCHEDULE_ID, CO_SCHEDULE_DESC, CO_SCHEDULE_START, CO_SCHEDULE_END, CO_SCHEDULE_SIZE) VALUES ('hkah', 'christmas', '1', '16', 'Group 16', TO_DATE('17-11月 -11', 'DD-MON-RR'), TO_DATE('30-11月 -11', 'DD-MON-RR'), '12');
INSERT INTO CO_SCHEDULE (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_SCHEDULE_ID, CO_SCHEDULE_DESC, CO_SCHEDULE_START, CO_SCHEDULE_END, CO_SCHEDULE_SIZE) VALUES ('hkah', 'christmas', '1', '17', 'Group 17', TO_DATE('17-11月 -11', 'DD-MON-RR'), TO_DATE('30-11月 -11', 'DD-MON-RR'), '12');
INSERT INTO CO_SCHEDULE (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_SCHEDULE_ID, CO_SCHEDULE_DESC, CO_SCHEDULE_START, CO_SCHEDULE_END, CO_SCHEDULE_SIZE) VALUES ('hkah', 'christmas', '1', '18', 'Group 18', TO_DATE('17-11月 -11', 'DD-MON-RR'), TO_DATE('30-11月 -11', 'DD-MON-RR'), '12');
INSERT INTO CO_SCHEDULE (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_SCHEDULE_ID, CO_SCHEDULE_DESC, CO_SCHEDULE_START, CO_SCHEDULE_END, CO_SCHEDULE_SIZE) VALUES ('hkah', 'christmas', '1', '19', 'Group 19', TO_DATE('17-11月 -11', 'DD-MON-RR'), TO_DATE('30-11月 -11', 'DD-MON-RR'), '12');
INSERT INTO CO_SCHEDULE (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_SCHEDULE_ID, CO_SCHEDULE_DESC, CO_SCHEDULE_START, CO_SCHEDULE_END, CO_SCHEDULE_SIZE) VALUES ('hkah', 'christmas', '1', '20', 'Group 20', TO_DATE('17-11月 -11', 'DD-MON-RR'), TO_DATE('30-11月 -11', 'DD-MON-RR'), '12');
INSERT INTO CO_SCHEDULE (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_SCHEDULE_ID, CO_SCHEDULE_DESC, CO_SCHEDULE_START, CO_SCHEDULE_END, CO_SCHEDULE_SIZE) VALUES ('hkah', 'christmas', '1', '21', 'Group 21', TO_DATE('17-11月 -11', 'DD-MON-RR'), TO_DATE('30-11月 -11', 'DD-MON-RR'), '12');
INSERT INTO CO_SCHEDULE (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_SCHEDULE_ID, CO_SCHEDULE_DESC, CO_SCHEDULE_START, CO_SCHEDULE_END, CO_SCHEDULE_SIZE) VALUES ('hkah', 'christmas', '1', '22', 'Group 22', TO_DATE('17-11月 -11', 'DD-MON-RR'), TO_DATE('30-11月 -11', 'DD-MON-RR'), '12');
INSERT INTO CO_SCHEDULE (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_SCHEDULE_ID, CO_SCHEDULE_DESC, CO_SCHEDULE_START, CO_SCHEDULE_END, CO_SCHEDULE_SIZE) VALUES ('hkah', 'christmas', '1', '23', 'Group 23', TO_DATE('17-11月 -11', 'DD-MON-RR'), TO_DATE('30-11月 -11', 'DD-MON-RR'), '12');
INSERT INTO CO_SCHEDULE (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_SCHEDULE_ID, CO_SCHEDULE_DESC, CO_SCHEDULE_START, CO_SCHEDULE_END, CO_SCHEDULE_SIZE) VALUES ('hkah', 'christmas', '1', '24', 'Group 24', TO_DATE('17-11月 -11', 'DD-MON-RR'), TO_DATE('30-11月 -11', 'DD-MON-RR'), '12');
INSERT INTO CO_SCHEDULE (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_SCHEDULE_ID, CO_SCHEDULE_DESC, CO_SCHEDULE_START, CO_SCHEDULE_END, CO_SCHEDULE_SIZE) VALUES ('hkah', 'christmas', '1', '25', 'Group 25', TO_DATE('17-11月 -11', 'DD-MON-RR'), TO_DATE('30-11月 -11', 'DD-MON-RR'), '12');
INSERT INTO CO_SCHEDULE (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_SCHEDULE_ID, CO_SCHEDULE_DESC, CO_SCHEDULE_START, CO_SCHEDULE_END, CO_SCHEDULE_SIZE) VALUES ('hkah', 'christmas', '1', '26', 'Group 26', TO_DATE('17-11月 -11', 'DD-MON-RR'), TO_DATE('30-11月 -11', 'DD-MON-RR'), '12');
INSERT INTO CO_SCHEDULE (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_SCHEDULE_ID, CO_SCHEDULE_DESC, CO_SCHEDULE_START, CO_SCHEDULE_END, CO_SCHEDULE_SIZE) VALUES ('hkah', 'christmas', '1', '27', 'Group 27', TO_DATE('17-11月 -11', 'DD-MON-RR'), TO_DATE('30-11月 -11', 'DD-MON-RR'), '12');
INSERT INTO CO_SCHEDULE (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_SCHEDULE_ID, CO_SCHEDULE_DESC, CO_SCHEDULE_START, CO_SCHEDULE_END, CO_SCHEDULE_SIZE) VALUES ('hkah', 'christmas', '1', '28', 'Group 28', TO_DATE('17-11月 -11', 'DD-MON-RR'), TO_DATE('30-11月 -11', 'DD-MON-RR'), '12');
INSERT INTO CO_SCHEDULE (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_SCHEDULE_ID, CO_SCHEDULE_DESC, CO_SCHEDULE_START, CO_SCHEDULE_END, CO_SCHEDULE_SIZE) VALUES ('hkah', 'christmas', '1', '29', 'Group 29', TO_DATE('17-11月 -11', 'DD-MON-RR'), TO_DATE('30-11月 -11', 'DD-MON-RR'), '12');
INSERT INTO CO_SCHEDULE (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_SCHEDULE_ID, CO_SCHEDULE_DESC, CO_SCHEDULE_START, CO_SCHEDULE_END, CO_SCHEDULE_SIZE) VALUES ('hkah', 'christmas', '1', '30', 'Group 30', TO_DATE('17-11月 -11', 'DD-MON-RR'), TO_DATE('30-11月 -11', 'DD-MON-RR'), '12');
INSERT INTO CO_SCHEDULE (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_SCHEDULE_ID, CO_SCHEDULE_DESC, CO_SCHEDULE_START, CO_SCHEDULE_END, CO_SCHEDULE_SIZE) VALUES ('hkah', 'christmas', '1', '31', 'Waiting', TO_DATE('17-11月 -11', 'DD-MON-RR'), TO_DATE('30-11月 -11', 'DD-MON-RR'), '0');
INSERT INTO CO_SCHEDULE (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_SCHEDULE_ID, CO_SCHEDULE_DESC, CO_SCHEDULE_START, CO_SCHEDULE_END, CO_SCHEDULE_SIZE) VALUES ('hkah', 'christmas', '1', '32', 'Cancel', TO_DATE('17-11月 -11', 'DD-MON-RR'), TO_DATE('30-11月 -11', 'DD-MON-RR'), '0');
commit;

--Reset DB
UPDATE CO_SCHEDULE
SET CO_SCHEDULE_ENROLLED = 0
WHERE CO_MODULE_CODE = 'christmas'
AND   CO_EVENT_ID = 1
AND   CO_ENABLED = 1;

DELETE FROM CO_ENROLLMENT WHERE CO_MODULE_CODE = 'christmas' AND CO_EVENT_ID = 1;
commit;

--ENROLL to any group
  --schedule id 1-30(Group 1 to Group 30)
  --schedule id 31 (Waiting)
  --schedule id 32 (Cancel)
UPDATE CO_SCHEDULE
SET    CO_SCHEDULE_ENROLLED = CO_SCHEDULE_ENROLLED + 1, CO_MODIFIED_DATE = SYSDATE, CO_MODIFIED_USER = 'SYSTEM'
WHERE  CO_SITE_CODE = 'hkah'
AND    CO_MODULE_CODE = 'christmas'
AND    CO_EVENT_ID = 1
AND    CO_SCHEDULE_ID = schedule id --indicate the schedule id 
AND   (CO_SCHEDULE_SIZE >= CO_SCHEDULE_ENROLLED + 1 OR CO_SCHEDULE_SIZE = 0)
AND    CO_ENABLED = 1;

  --please make sure the result of the above update is successful, then run the sql below
Insert into CO_ENROLLMENT 
(CO_SITE_CODE,CO_MODULE_CODE,CO_EVENT_ID,
CO_SCHEDULE_ID,
CO_ENROLL_ID,
CO_USER_TYPE,
CO_USER_ID,
CO_ENROLL_NO,CO_ATTEND_DATE,CO_ATTEND_STATUS,CO_REMARK,CO_CREATED_DATE,CO_CREATED_USER,
CO_MODIFIED_DATE,CO_MODIFIED_USER,CO_ENABLED,CO_ATTEND_DATE2,CO_ASSESSMENT_PASS_DATE,HAS_FOLLOWUP) 
values 
('hkah','christmas',1,
schedule id,--indicate the schedule id
(SELECT MAX(CO_ENROLL_ID) + 1 FROM CO_ENROLLMENT WHERE CO_SITE_CODE = 'hkah' AND CO_MODULE_CODE = 'christmas' AND CO_EVENT_ID = 1),
'participant',
staff id,--indicate the staff id  
1,null,0,null,SYSDATE,'SYSTEM',
SYSDATE,'SYSTEM',1, null, null,'N');
commit;

--withdraw
UPDATE CO_ENROLLMENT
SET CO_ENABLED = 0, CO_MODIFIED_DATE = SYSDATE, CO_MODIFIED_USER='SYSTEM'
WHERE CO_SITE_CODE = 'hkah'
AND CO_MODULE_CODE = 'christmas'
AND CO_SCHEDULE_ID = 31 AND CO_ENABLED = 1

  (SELECT CO_SCHEDULE_ID FROM CO_ENROLLMENT WHERE CO_SITE_CODE = 'hkah' AND CO_MODULE_CODE = 'christmas' 
  AND CO_USER_ID=staff id AND CO_ENABLED = 1)
AND CO_USER_ID = staff id;
COMMIT;
