ALTER TABLE CIS_LAB_LOG
 DROP PRIMARY KEY CASCADE;
DROP TABLE CIS_LAB_LOG CASCADE CONSTRAINTS;

CREATE TABLE CIS_LAB_LOG
(
 CIS_LAB_ID NUMBER(*,0) NOT NULL ENABLE,
 CIS_LAB_NUM VARCHAR2(20 BYTE) NOT NULL ENABLE,
 CIS_DOCCODE VARCHAR2(20 BYTE),
 CIS_LOGTYPE VARCHAR2(20 BYTE),
 CIS_TEST_CAT VARCHAR2(20 BYTE),
 CIS_RPT_NO VARCHAR2(20 BYTE),
 CIS_RPT_VERSION VARCHAR2(20 BYTE),
 CIS_FILE_PATH VARCHAR2(200 BYTE),
 CIS_DOC_EMAIL VARCHAR2(200 BYTE),
 CIS_SENDMAIL_STATUS VARCHAR2(20 BYTE),
 CIS_READDOC_STATUS VARCHAR2(10 BYTE) DEFAULT '0',
 CO_CREATED_DATE DATE DEFAULT SYSDATE,
 CO_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_MODIFIED_DATE DATE,
 CO_MODIFIED_USER VARCHAR2(30 BYTE),
 CO_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CIS_LAB_ID,CIS_LAB_NUM)
);