ALTER TABLE CO_AUTO_EMAIL_DAILY
 DROP PRIMARY KEY CASCADE;
DROP TABLE CO_AUTO_EMAIL_DAILY CASCADE CONSTRAINTS;

CREATE TABLE CO_AUTO_EMAIL_DAILY
(
 CO_AUTO_EMAIL_ID NUMBER(*,0) NOT NULL ENABLE,
 CO_DESCRIPTION VARCHAR2(100 BYTE) NOT NULL,
 CO_ALERT_ID VARCHAR2(50 BYTE) NOT NULL,
 CO_CRITERIA_SQL VARCHAR2(1000 BYTE),
 CO_TABLE_HEADER VARCHAR2(1000 BYTE),
 CO_EMAIL_HEADER VARCHAR2(1000 BYTE),
 CO_EMAIL_CONTENT VARCHAR2(1000 BYTE),
 CO_START_HOUR VARCHAR2(2 BYTE) DEFAULT '00',
 CO_CREATED_DATE DATE DEFAULT SYSDATE,
 CO_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CO_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CO_AUTO_EMAIL_ID)
);