CREATE TABLE "CO_AUTO_SMS_DAILY" (
	"CO_AUTO_SMS_ID" NUMBER(*,0) NOT NULL ENABLE,
	"CO_DESCRIPTION" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"CO_LOGIN_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE,
	"CO_PASSWORD_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE,
	"CO_CRITERIA_SQL" VARCHAR2(3500 BYTE) NOT NULL ENABLE,
	"CO_START_HOUR" VARCHAR2(2 BYTE) DEFAULT '00' NOT NULL ENABLE,
	"CO_END_HOUR" VARCHAR2(2 BYTE) DEFAULT '00' NOT NULL ENABLE,
	"CO_PREEXEC_SP" VARCHAR2(1000 BYTE),
	"CO_PROEXEC_SQL" VARCHAR2(1000 BYTE),
	"CO_LOG_TYPE" VARCHAR2(20 BYTE),
	"CO_CREATED_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"CO_CREATED_USER" VARCHAR2(30 BYTE) DEFAULT 'SYSTEM' NOT NULL ENABLE,
	"CO_MODIFIED_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"CO_MODIFIED_USER" VARCHAR2(30 BYTE) DEFAULT 'SYSTEM' NOT NULL ENABLE,
	"CO_ENABLED" NUMBER DEFAULT 1 NOT NULL ENABLE,
	PRIMARY KEY ("CO_AUTO_SMS_ID")
);

100	PSS	adventisthosp_pi_hk	QARMSIOOPKRATJRO	"SELECT '1', P.PATPAGER, NHS_UTL_ERRORMESSAGE@IWEB('MOBILESMS', 'PSS', DECODE(P.MOTHCODE, 'TRC', 'zh-HK', 'SMC', 'zh-CN', 'en'))
FROM   PATIENT@IWEB P
WHERE P.PATNO = '434381'"	21	21			18-AUG-20 14:33:52	SYSTEM	18-AUG-20 14:33:52	SYSTEM	1