CREATE TABLE "CO_ALERT"
  (
    "CO_ALERT_ID"      VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "CO_ALERT_DESC"    VARCHAR2(100 BYTE),
    "CO_ALERT_CONTENT" VARCHAR2(1000 BYTE),
    "CO_CRITERIA_SQL"  VARCHAR2(1000 BYTE),
    "CO_EMAIL"         VARCHAR2(255 BYTE),
    "CO_CREATED_DATE" DATE DEFAULT SYSDATE,
    "CO_CREATED_USER" VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
    "CO_MODIFIED_DATE" DATE DEFAULT SYSDATE,
    "CO_MODIFIED_USER" VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
    "CO_ENABLED"       NUMBER(*,0) DEFAULT 1,
    PRIMARY KEY ("CO_ALERT_ID")
  )