ALTER TABLE CO_AUTO_EMAIL_LIST
 DROP PRIMARY KEY CASCADE;
DROP TABLE CO_AUTO_EMAIL_LIST CASCADE CONSTRAINTS;

CREATE TABLE CO_AUTO_EMAIL_LIST
  (
      CO_SITE_CODE     	    VARCHAR2(10 BYTE),
      CO_AUTO_ID		    NUMBER NOT NULL,  
      CO_AUTO_LIST_ID       NUMBER NOT NULL,  
      CO_EMAIL_TO           VARCHAR2(100 BYTE),
      CO_EMAIL_CC           VARCHAR2(100 BYTE),
      CO_EMAIL_BCC          VARCHAR2(100 BYTE),
      CO_RECV_PATNO         VARCHAR2(10 BYTE),
      CO_RECV_FIRSTNAME     VARCHAR2(100 BYTE),
      CO_RECV_LASTNAME      VARCHAR2(100 BYTE),
      CO_RECV_TITDESC       VARCHAR2(10 BYTE),
      CO_STATUS      	    VARCHAR2(1 BYTE) DEFAULT 'N',
      CREATE_DATE 			DATE DEFAULT SYSDATE,
      CREATE_USER 			VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
      MODIFIED_DATE 		DATE DEFAULT SYSDATE,
      MODIFIED_USER 		VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
      ENABLE 				NUMBER(1,0) DEFAULT 1,
      PRIMARY KEY(CO_AUTO_LIST_ID)
  );