ALTER TABLE CO_APPROVAL_USER
 DROP PRIMARY KEY CASCADE;
DROP TABLE CO_APPROVAL_USER CASCADE CONSTRAINTS;

CREATE TABLE CO_APPROVAL_USER
(
 CO_MODULE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,	-- education, lmc
 CO_CATEGORY VARCHAR2(10 BYTE) NOT NULL ENABLE,
 CO_REQUEST_SITE_CODE VARCHAR2(10 BYTE) DEFAULT 'hkah',	-- hkah, twah
 CO_REQUEST_DEPARTMENT_CODE NUMBER(*,0) NULL,
 CO_REQUEST_USER_TYPE VARCHAR2(10 BYTE) NULL,
 CO_REQUEST_USER_ID VARCHAR2(20 BYTE) NULL,
 CO_REQUEST_GROUP_ID VARCHAR2(30 BYTE) DEFAULT 'ALL',
 CO_APPROVAL_SITE_CODE VARCHAR2(10 BYTE) DEFAULT 'hkah',	-- hkah, twah
 CO_APPROVAL_DEPARTMENT_CODE NUMBER(*,0) NULL,
 CO_APPROVAL_USER_TYPE VARCHAR2(10 BYTE) NOT NULL,	-- staff, patient
 CO_APPROVAL_USER_ID VARCHAR2(20 BYTE) NOT NULL,
 CO_APPROVAL_PRIORITY NUMBER(*,0) DEFAULT 1, 
 CO_CREATED_DATE DATE DEFAULT SYSDATE,
 CO_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CO_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_ENABLED NUMBER(*,0) DEFAULT 1
);
ALTER TABLE CO_APPROVAL_USER ADD (
 CONSTRAINT CO_APPROVAL_USER_R01
 FOREIGN KEY (CO_REQUEST_SITE_CODE)
 REFERENCES CO_SITE (CO_SITE_CODE));
ALTER TABLE CO_APPROVAL_USER ADD (
 CONSTRAINT CO_APPROVAL_USER_R02
 FOREIGN KEY (CO_REQUEST_DEPARTMENT_CODE)
 REFERENCES CO_DEPARTMENTS (CO_DEPARTMENT_CODE));

INSERT INTO CO_APPROVAL_USER (CO_MODULE_CODE, CO_CATEGORY, CO_REQUEST_SITE_CODE, CO_REQUEST_DEPARTMENT_CODE, CO_APPROVAL_USER_TYPE, CO_APPROVAL_USER_ID) VALUES ('crm', 'client', 'hkah', '660', 'staff', '3272');
INSERT INTO CO_APPROVAL_USER (CO_MODULE_CODE, CO_CATEGORY, CO_REQUEST_SITE_CODE, CO_REQUEST_DEPARTMENT_CODE, CO_APPROVAL_USER_TYPE, CO_APPROVAL_USER_ID) VALUES ('crm', 'client', 'hkah', '520', 'staff', '3927');
INSERT INTO CO_APPROVAL_USER (CO_MODULE_CODE, CO_CATEGORY, CO_REQUEST_SITE_CODE, CO_REQUEST_DEPARTMENT_CODE, CO_APPROVAL_USER_TYPE, CO_APPROVAL_USER_ID) VALUES ('crm', 'client', 'hkah', '750', 'staff', '3229');
INSERT INTO CO_APPROVAL_USER (CO_MODULE_CODE, CO_CATEGORY, CO_REQUEST_SITE_CODE, CO_REQUEST_DEPARTMENT_CODE, CO_APPROVAL_USER_TYPE, CO_APPROVAL_USER_ID) VALUES ('crm', 'client', 'hkah', '670', 'staff', '3880');
INSERT INTO CO_APPROVAL_USER (CO_MODULE_CODE, CO_CATEGORY, CO_REQUEST_SITE_CODE, CO_REQUEST_DEPARTMENT_CODE, CO_APPROVAL_USER_TYPE, CO_APPROVAL_USER_ID) VALUES ('crm', 'client', 'twah', '660', 'staff', '4123');
INSERT INTO CO_APPROVAL_USER (CO_MODULE_CODE, CO_CATEGORY, CO_REQUEST_SITE_CODE, CO_REQUEST_DEPARTMENT_CODE, CO_APPROVAL_USER_TYPE, CO_APPROVAL_USER_ID) VALUES ('crm', 'client', 'twah', '520', 'staff', '17008');
INSERT INTO CO_APPROVAL_USER (CO_MODULE_CODE, CO_CATEGORY, CO_REQUEST_SITE_CODE, CO_REQUEST_DEPARTMENT_CODE, CO_APPROVAL_USER_TYPE, CO_APPROVAL_USER_ID) VALUES ('crm', 'client', 'twah', '750', 'staff', '21036');
INSERT INTO CO_APPROVAL_USER (CO_MODULE_CODE, CO_CATEGORY, CO_REQUEST_SITE_CODE, CO_REQUEST_DEPARTMENT_CODE, CO_APPROVAL_USER_TYPE, CO_APPROVAL_USER_ID) VALUES ('crm', 'client', 'twah', '670', 'staff', '4123');

-- kenneth.ho (approval)
-- wk.lam
INSERT INTO CO_APPROVAL_USER (CO_MODULE_CODE, CO_CATEGORY, CO_REQUEST_USER_TYPE, CO_REQUEST_USER_ID, CO_APPROVAL_USER_TYPE, CO_APPROVAL_USER_ID) VALUES ('eleave', 'approve', 'doctor', 'DR1528', 'doctor', 'DR164');
-- charmaine.tse
INSERT INTO CO_APPROVAL_USER (CO_MODULE_CODE, CO_CATEGORY, CO_REQUEST_USER_TYPE, CO_REQUEST_USER_ID, CO_APPROVAL_USER_TYPE, CO_APPROVAL_USER_ID) VALUES ('eleave', 'approve', 'doctor', 'DR1533', 'doctor', 'DR164');
-- buddy.wong (approval)
-- selina.pang
INSERT INTO CO_APPROVAL_USER (CO_MODULE_CODE, CO_CATEGORY, CO_REQUEST_USER_TYPE, CO_REQUEST_USER_ID, CO_APPROVAL_USER_TYPE, CO_APPROVAL_USER_ID) VALUES ('eleave', 'approve', 'doctor', 'DR1499', 'doctor', 'DR435');
-- lina.chan
INSERT INTO CO_APPROVAL_USER (CO_MODULE_CODE, CO_CATEGORY, CO_REQUEST_USER_TYPE, CO_REQUEST_USER_ID, CO_APPROVAL_USER_TYPE, CO_APPROVAL_USER_ID) VALUES ('eleave', 'approve', 'doctor', 'DR1489', 'doctor', 'DR435');
-- henry.kwan
INSERT INTO CO_APPROVAL_USER (CO_MODULE_CODE, CO_CATEGORY, CO_REQUEST_USER_TYPE, CO_REQUEST_USER_ID, CO_APPROVAL_USER_TYPE, CO_APPROVAL_USER_ID) VALUES ('eleave', 'approve', 'doctor', 'DR1494', 'doctor', 'DR435');
-- backup list
-- rachel
INSERT INTO CO_APPROVAL_USER (CO_MODULE_CODE, CO_CATEGORY, CO_REQUEST_USER_TYPE, CO_REQUEST_USER_ID, CO_APPROVAL_USER_TYPE, CO_APPROVAL_USER_ID, CO_APPROVAL_PRIORITY) VALUES ('eleave', 'approve', 'doctor', 'ALL', 'staff', '3784', 1);
-- kiky.lee
INSERT INTO CO_APPROVAL_USER (CO_MODULE_CODE, CO_CATEGORY, CO_REQUEST_USER_TYPE, CO_REQUEST_USER_ID, CO_APPROVAL_USER_TYPE, CO_APPROVAL_USER_ID, CO_APPROVAL_PRIORITY) VALUES ('eleave', 'approve', 'doctor', 'ALL', 'staff', '3397', 2);
-- marla.lan
INSERT INTO CO_APPROVAL_USER (CO_MODULE_CODE, CO_CATEGORY, CO_REQUEST_USER_TYPE, CO_REQUEST_USER_ID, CO_APPROVAL_USER_TYPE, CO_APPROVAL_USER_ID, CO_APPROVAL_PRIORITY) VALUES ('eleave', 'approve', 'doctor', 'ALL', 'staff', '2698', 2);
-- eve
INSERT INTO CO_APPROVAL_USER (CO_MODULE_CODE, CO_CATEGORY, CO_REQUEST_USER_TYPE, CO_REQUEST_USER_ID, CO_APPROVAL_USER_TYPE, CO_APPROVAL_USER_ID, CO_APPROVAL_PRIORITY) VALUES ('eleave', 'approve', 'doctor', 'ALL', 'staff', '1573', 2);
-- Anita Wong (added on 2010/06/25, requested by eve)
INSERT INTO CO_APPROVAL_USER (CO_MODULE_CODE, CO_CATEGORY, CO_REQUEST_USER_TYPE, CO_REQUEST_USER_ID, CO_APPROVAL_USER_TYPE, CO_APPROVAL_USER_ID, CO_APPROVAL_PRIORITY) VALUES ('eleave', 'approve', 'doctor', 'ALL', 'staff', '4325', 2);

--
INSERT INTO CO_APPROVAL_USER (CO_MODULE_CODE, CO_CATEGORY, CO_REQUEST_DEPARTMENT_CODE, CO_REQUEST_USER_TYPE, CO_REQUEST_USER_ID, CO_APPROVAL_USER_TYPE, CO_APPROVAL_USER_ID, CO_APPROVAL_PRIORITY) VALUES ('eleave', 'approve', '720', 'staff', 'ALL', 'staff', '3722', 1);
INSERT INTO CO_APPROVAL_USER (CO_MODULE_CODE, CO_CATEGORY, CO_REQUEST_USER_TYPE, CO_REQUEST_USER_ID, CO_APPROVAL_USER_TYPE, CO_APPROVAL_USER_ID, CO_APPROVAL_PRIORITY) VALUES ('eleave', 'verify', 'staff', 'ALL', 'staff', '4223', 1);
INSERT INTO CO_APPROVAL_USER (CO_MODULE_CODE, CO_CATEGORY, CO_REQUEST_USER_TYPE, CO_REQUEST_USER_ID, CO_APPROVAL_USER_TYPE, CO_APPROVAL_USER_ID, CO_APPROVAL_PRIORITY) VALUES ('eleave', 'confirm', 'staff', 'ALL', 'staff', '3043', 1);