ALTER TABLE CO_AUTO_EMAIL
 DROP PRIMARY KEY CASCADE;
DROP TABLE CO_AUTO_EMAIL CASCADE CONSTRAINTS;

CREATE TABLE CO_AUTO_EMAIL
(
	CO_SITE_CODE     	    VARCHAR2(10 BYTE),
  	CO_AUTO_ID		        NUMBER NOT NULL,  
  	CO_START_DATE			DATE NOT NULL,
  	CO_RECV_NO_EACHTIME		NUMBER DEFAULT 10,
  	CO_TIME_GAP   	        NUMBER DEFAULT 180,
  	CO_EMAIL_FROM         	VARCHAR2(100 BYTE) NOT NULL,  
  	CO_EMAIL_REPLYTO        VARCHAR2(100 BYTE),
  	CO_EMAIL_CC             VARCHAR2(100 BYTE),
  	CO_EMAIL_BCC            VARCHAR2(100 BYTE),
  	CO_EMAIL_SUBJECT        VARCHAR2(300 BYTE) NOT NULL,
  	CO_EMAIL_CONTENT_URL    VARCHAR2(500 BYTE) NOT NULL,
  	CO_STATUS      	        VARCHAR2(1 BYTE) DEFAULT 'N',
  	CREATE_DATE 			DATE DEFAULT SYSDATE,
  	CREATE_USER 			VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
  	MODIFIED_DATE 			DATE DEFAULT SYSDATE,
  	MODIFIED_USER 			VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
  	ENABLE 					NUMBER(1,0) DEFAULT 1,
  	PRIMARY KEY(CO_AUTO_ID)
);