ALTER TABLE CO_DEPARTMENTS
 DROP PRIMARY KEY CASCADE;
DROP TABLE CO_DEPARTMENTS CASCADE CONSTRAINTS;

CREATE TABLE CO_DEPARTMENTS
(
 CO_DEPARTMENT_CODE VARCHAR2(10) NOT NULL ENABLE,
 CO_DEPARTMENT_SHORT_DESC VARCHAR2(10 BYTE),
 CO_DEPARTMENT_DESC VARCHAR2(100 BYTE),
 CO_DEPARTMENT_CATEGORY VARCHAR2(20 BYTE),
 CO_DEPARTMENT_HEAD VARCHAR2(10 BYTE),
 CO_DEPARTMENT_SUBHEAD VARCHAR2(10 BYTE), 
 CO_DEPARTMENT_SUPERVISOR VARCHAR2(10 BYTE),
 CO_CREATED_DATE DATE DEFAULT SYSDATE,
 CO_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CO_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CO_DEPARTMENT_CODE)
);
ALTER TABLE CO_DEPARTMENTS ADD (
 CONSTRAINT CO_DEPARTMENT_R01
 FOREIGN KEY (CO_SITE_CODE)
 REFERENCES CO_SITE (CO_SITE_CODE));

SET DEFINE OFF
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('100', 'Intensive Care Unit');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('110', 'Medical Unit');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('120', 'Obstetrics');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('130', 'Pediatrics');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('140', 'Surgical Unit');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('150', 'Integrated Unit');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('200', 'Cardiac Catheterization Laboratory');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('210', 'Cardiopulmonary Laboratory');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('220', 'Central Supply');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('230', 'Clinical Laboratory');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('240', 'C T Scan');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('245', 'Cyberknife Centre');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('250', 'Day Case Unit');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('260', 'Dental Clinic');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('270', 'Dental Laboratory');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('275', 'Derm Laser');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('280', 'Diagnostic Imaging');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('285', 'Eecp Centre');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('290', 'Eye Centre');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('295', 'Eye Lasik');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('300', 'Food & Dietetic');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('310', 'Health Assessment Services');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('320', 'Heart Center');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('330', 'Haemodialysis Centre');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('340', 'M R I');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('350', 'Nuclear Medicine');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('360', 'Operating Room');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('365', 'Endoscopy Unit');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('366', 'Minimal Invasive Surgery & Endo Education Centre');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('370', 'Outpatient Nursing/Emergency Room');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('380', 'Pharmacy');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('390', 'Physical Therapy');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('400', 'Physician Services');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('410', 'Radiology');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('430', 'Sleep And Respiratory Disorders Centre');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('440', 'Speech Therapy');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('450', 'Stone Centre');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('460', 'Well Baby Clinic');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('510', 'Church School');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('520', 'Lifestyle Management Centre');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('530', 'Staff Quarters');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('600', 'Accounting');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('610', 'Administration - CEO');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('611', 'Project Management');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('612', 'Internal Audit');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('613', 'Patient Relation');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('620', 'Administration - CFO');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('630', 'Administration - VPA');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('640', 'Administration - VPF');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('650', 'Administration - VPM');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('660', 'Chaplaincy Services');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('670', 'Development Off/HKAH Foundation');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('680', 'Godown');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('685', 'Material Management');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('690', 'Grounds');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('700', 'Housekeeping');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('710', 'Human Resources');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('720', 'Information Technology');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('730', 'Linen');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('740', 'Plant Operations/Maintenance');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('750', 'Marketing & Business Development');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('760', 'Medical Records');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('770', 'Nursing Administration');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('780', 'Nursing - Infection Control');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('785', 'Nursing - OSH/EHS');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('790', 'Nursing Staff Education');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('800', 'Patient Business Manager');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('810', 'Guest Relation');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('820', 'Communications & Inpatient');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('830', 'Outpatient Registration');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('840', 'Patients Accounts');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('860', 'Purchasing');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('870', 'Quality Improvement');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('880', 'Security');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('900', 'Administration - Others');

-- special
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('993', 'Administration - COO');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('994', 'Doctor Helper');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('995', 'Doctor');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('996', 'Other');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('997', 'VP for Medical Affair');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('998', 'Chief of Medical Staff');
INSERT INTO CO_DEPARTMENTS (CO_DEPARTMENT_CODE, CO_DEPARTMENT_DESC) VALUES('999', 'Medical Program Administration/Marketing');

update CO_DEPARTMENTS set CO_DEPARTMENT_CATEGORY = 'LA RUE';
update CO_DEPARTMENTS set CO_DEPARTMENT_CATEGORY = 'ANCILLARY' WHERE CO_DEPARTMENT_CODE IN ('300', '700', '740');
update CO_DEPARTMENTS set CO_DEPARTMENT_CATEGORY = 'CLINICAL' WHERE CO_DEPARTMENT_CODE IN ('992', '240', '200', '210', '230', '820', '245', '250', '260', '270', '280', '995', '994', '365', '330', '320', '780', '150', '100', '340', '350', '770', '785', '120', '415', '360', '370', '830', '800', '613', '840', '130', '380', '390', '400', '410', '430');