ALTER TABLE CO_DOCUMENT_MAIL_LIST
 DROP PRIMARY KEY CASCADE;
DROP TABLE CO_DOCUMENT_MAIL_LIST CASCADE CONSTRAINTS;

CREATE TABLE CO_DOCUMENT_MAIL_LIST
(
 CO_DOCUMENT_MAIL_LIST_ID NUMBER(*,0) NOT NULL ENABLE,
 CO_DOCUMENT_ID NUMBER(*,0) NOT NULL ENABLE,
 CO_SEND_TYPE VARCHAR2(5 BYTE),	-- ('from', 'to', 'cc', 'bcc')
 CO_USERNAME VARCHAR2(30 BYTE),	-- get email address from CO_USERS table by CO_USERNAME
 CO_EMAIL VARCHAR2(255 BYTE),	-- use this email address if CO_MAIL is specified
 CO_CREATED_DATE DATE DEFAULT SYSDATE,
 CO_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CO_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CO_DOCUMENT_MAIL_LIST_ID, CO_DOCUMENT_ID)
);

SET DEFINE OFF
INSERT INTO CO_DOCUMENT_MAIL_LIST(CO_DOCUMENT_MAIL_LIST_ID, CO_DOCUMENT_ID, CO_SEND_TYPE, CO_USERNAME) VALUES (1, 326, 'to', 'rachel.yeung');
INSERT INTO CO_DOCUMENT_MAIL_LIST(CO_DOCUMENT_MAIL_LIST_ID, CO_DOCUMENT_ID, CO_SEND_TYPE, CO_USERNAME) VALUES (2, 326, 'to', 'sally.leung');
INSERT INTO CO_DOCUMENT_MAIL_LIST(CO_DOCUMENT_MAIL_LIST_ID, CO_DOCUMENT_ID, CO_SEND_TYPE, CO_USERNAME) VALUES (3, 326, 'to', 'sharona.tong');
INSERT INTO CO_DOCUMENT_MAIL_LIST(CO_DOCUMENT_MAIL_LIST_ID, CO_DOCUMENT_ID, CO_SEND_TYPE, CO_USERNAME) VALUES (4, 326, 'to', '4325'); -- Anita
INSERT INTO CO_DOCUMENT_MAIL_LIST(CO_DOCUMENT_MAIL_LIST_ID, CO_DOCUMENT_ID, CO_SEND_TYPE, CO_USERNAME) VALUES (5, 326, 'to', 'eve.lee');
INSERT INTO CO_DOCUMENT_MAIL_LIST(CO_DOCUMENT_MAIL_LIST_ID, CO_DOCUMENT_ID, CO_SEND_TYPE, CO_USERNAME) VALUES (6, 326, 'to', 'kattral.lee');
