ALTER TABLE CO_DISCHARGE_EMAIL
 DROP PRIMARY KEY CASCADE;
DROP TABLE CO_DISCHARGE_EMAIL CASCADE CONSTRAINTS;

CREATE TABLE CO_DISCHARGE_EMAIL
(
 CO_DCEID NUMBER(*,0) NOT NULL ENABLE,
 CO_LASTEMAILSEND_DATE DATE DEFAULT SYSDATE,
 CO_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CO_DCEID)
);

INSERT INTO CO_DISCHARGE_EMAIL (CO_DCEID) VALUES ('1');