ALTER TABLE CO_DEPARTMENT_MAPPING
 DROP PRIMARY KEY CASCADE;
DROP TABLE CO_DEPARTMENT_MAPPING CASCADE CONSTRAINTS;

CREATE TABLE CO_DEPARTMENT_MAPPING
(
 CO_DEPARTMENT_CODE1 VARCHAR2(10) NOT NULL ENABLE,
 CO_DEPARTMENT_CODE2 VARCHAR2(10) NOT NULL ENABLE,
 CO_DEPARTMENT_CODE2 VARCHAR2(5),
 CO_DEPARTMENT_CODE_HR VARCHAR2(50),
 CO_CREATED_DATE DATE DEFAULT SYSDATE,
 CO_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CO_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CO_DEPARTMENT_CODE1, CO_DEPARTMENT_CODE2)
);