ALTER TABLE CO_ENROLLMENT_DOCUMENT
 DROP PRIMARY KEY CASCADE;
DROP TABLE CO_ENROLLMENT_DOCUMENT CASCADE CONSTRAINTS;

CREATE TABLE CO_ENROLLMENT_DOCUMENT
(
 CO_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 CO_MODULE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,	-- education, lmc
 CO_EVENT_ID NUMBER(*,0) NOT NULL ENABLE,
 CO_SCHEDULE_ID NUMBER(*,0) NULL,
 CO_ENROLL_ID NUMBER(*,0) NOT NULL ENABLE,
 CO_DOCUMENT_ID NUMBER(*,0) NULL,
 CO_CREATED_DATE DATE DEFAULT SYSDATE,
 CO_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CO_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_ENROLL_ID, CO_DOCUMENT_ID)
);
ALTER TABLE CO_ENROLLMENT_DOCUMENT ADD (
 CONSTRAINT CO_ENROLLMENT_DOCUMENT_R01
 FOREIGN KEY (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_ENROLL_ID)
 REFERENCES CO_ENROLLMENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_ENROLL_ID));
ALTER TABLE CO_ENROLLMENT_DOCUMENT ADD (
 CONSTRAINT CO_ENROLLMENT_DOCUMENT_R02
 FOREIGN KEY (CO_DOCUMENT_ID)
 REFERENCES CO_DOCUMENT (CO_DOCUMENT_ID));