ALTER TABLE CO_ENROLLMENT_FAMILYTYPE
 DROP PRIMARY KEY CASCADE;
DROP TABLE CO_ENROLLMENT_FAMILYTYPE CASCADE CONSTRAINTS;

CREATE TABLE CO_ENROLLMENT_FAMILYTYPE
(
 CO_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 CO_MODULE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,	-- education, lmc
 CO_FAMILYTYPE_ID NUMBER(*,0) NOT NULL ENABLE,
 CO_FAMILYTYPE_DESC VARCHAR2(100 BYTE),
 CO_FAMILYTYPE_DISCOUNT NUMBER(*,0),
 CO_FAMILYTYPE_DISCOUNT_DESC VARCHAR2(100 BYTE),
 CO_COUNT_SEATS NUMBER(*,0) DEFAULT 1,
 CO_CREATED_DATE DATE DEFAULT SYSDATE,
 CO_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CO_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_ENABLED NUMBER(*,0) DEFAULT 1
);
