ALTER TABLE CO_ENROLLMENT_FAMILY
 DROP PRIMARY KEY CASCADE;
DROP TABLE CO_ENROLLMENT_FAMILY CASCADE CONSTRAINTS;

CREATE TABLE CO_ENROLLMENT_FAMILY
(
 CO_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 CO_MODULE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,	-- education, lmc
 CO_EVENT_ID NUMBER(*,0) NOT NULL ENABLE,
 CO_SCHEDULE_ID NUMBER(*,0) NOT NULL ENABLE,
 CO_ENROLL_ID NUMBER(*,0) NOT NULL ENABLE,
 CO_FAMILY_TYPE_ID NUMBER(*,0) NOT NULL ENABLE,
 CO_USER_ID VARCHAR2(30 BYTE),
 CO_ENROLL_NO NUMBER(*,0) DEFAULT 0,
 CO_REMARK VARCHAR2(100 BYTE),
 CO_CREATED_DATE DATE DEFAULT SYSDATE,
 CO_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CO_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_ENABLED NUMBER(*,0) DEFAULT 1
);
