ALTER TABLE CO_EVENT
 DROP PRIMARY KEY CASCADE;
DROP TABLE CO_EVENT CASCADE CONSTRAINTS;

CREATE TABLE CO_EVENT
(
 CO_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 CO_MODULE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,	-- education, lmc
 CO_EVENT_ID NUMBER(*,0) NOT NULL ENABLE,
 CO_EVENT_DESC VARCHAR2(800 BYTE),
 CO_EVENT_SHORT_DESC VARCHAR2(50 BYTE) NULL,
 CO_EVENT_CATEGORY VARCHAR2(10 BYTE),	-- [compulsory], [inservice], [ce]Continuous Education, [other]
 CO_EVENT_TYPE VARCHAR2(20 BYTE),	-- [class] Room, [online], [self] learn
 CO_EVENT_TYPE2 VARCHAR2(20 BYTE),
 CO_DEPARTMENT_CODE NUMBER(*,0) NULL,
 CO_EVENT_REMARK VARCHAR2(100 BYTE) NULL,
 CO_EVENT_REMARK2 VARCHAR2(100 BYTE) NULL,
 CO_REQUIRE_ASSESSMENT_PASS VARCHAR2(1 BYTE) DEFAULT 'N',
 CO_NON_HOSP_COURSE VARCHAR2(1 BYTE) DEFAULT 'N',
 CRM_CAMPAIGN_ID NUMBER(*,0) NULL,
 CO_CREATED_DATE DATE DEFAULT SYSDATE,
 CO_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CO_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID)
);
ALTER TABLE CO_EVENT ADD (
 CONSTRAINT CO_EVENT_R01
 FOREIGN KEY (CO_SITE_CODE)
 REFERENCES CO_SITE (CO_SITE_CODE));

-- testing
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 4, NULL, 'Fitness Club', 'other', 'class');
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 5, NULL, 'Fitness Plus', 'other', 'class');

INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 7, NULL, 'Fractional Flow Reserve', 'other', 'class');
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 8, NULL, 'CRM Training', 'other', 'class');
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 10, NULL, 'Prepared Childbirth (English)', 'other', 'class');
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 11, NULL, 'Infection Control Issues (Cantonese)', 'other', 'class');
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 12, NULL, 'Dietary Training', 'other', 'class');

-- mandatory
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 1010, NULL, 'Share (1hr)', 'compulsory', 'online');
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 1020, NULL, 'Standard Precaution', 'compulsory', 'online');
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 1030, NULL, 'Manual Handling', 'compulsory', 'class');
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 1040, NULL, 'Fire Safety/Disaster', 'compulsory', 'online');
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 1050, NULL, 'CPR', 'compulsory', 'class');
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 1060, NULL, 'CPR (Layman)', 'compulsory', 'class');
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 1070, NULL, 'Medical Gas Safety', 'compulsory', 'online');

-- new staff
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 1110, NULL, 'SHARE 5hrs (NE)', 'compulsory', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 1120, NULL, 'Cultural Awarness (NE)', 'compulsory', 'class');
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 1130, NULL, 'Hospital Orientation(NE)', 'compulsory', 'class');
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 1140, NULL, 'Nursing Orientation(NE)', 'compulsory', 'class');
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 1200, NULL, 'Volunteers Orientation', 'compulsory', 'class');

-- in-service and special training
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2010, NULL, 'Mock Code', 'inservice', 'class');
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_REMARK, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2020, NULL, 'Floor-to-floor', 'On-Site Fire Safety/Disaster Drill and Procedure', 'inservice', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2030, NULL, 'OSH-Workplace Violence', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2040, NULL, 'OSH-FMS.5', 'other', 'class');

--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2070, NULL, 'PI-Sentinel Event', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2080, NULL, 'PI-JCI Goals', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2090, NULL, 'PI-Tools', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2100, NULL, 'Fire Safety', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2110, NULL, 'TRENT', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2120, NULL, 'The use of Fractional flow Reserce', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2130, NULL, 'IC-Jan', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2140, NULL, 'Inf Control', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2150, NULL, 'IC-ICU', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2160, NULL, 'IC-SRL2', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2170, NULL, 'IC-Renovation', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2180, NULL, 'IC-Issues', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2190, NULL, 'IC-for HCA', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2200, NULL, 'IC-Fit Tx', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2210, NULL, 'PCI Wk', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2220, NULL, 'IC-Trent', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2230, NULL, 'Telephone Service Skills', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2240, NULL, 'Vegetarianism', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2250, NULL, 'Review of Valueable and New Int''l Standard', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2260, NULL, 'OSH-EH', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2270, NULL, 'OSH-Fall P', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2280, NULL, 'OSH-needlestick', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2290, NULL, 'OSH-Height', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2300, NULL, 'ECG', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2310, NULL, 'PI-Audit (12B)', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2320, NULL, 'PI-Audit', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2330, NULL, 'PI-RCA', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2340, NULL, 'Tracer Methodology', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2350, NULL, 'Food and Drug', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2360, NULL, 'Gardasil', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2370, NULL, 'OSH-MSDS', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2380, NULL, 'Common Cancers in HK', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2390, NULL, 'ASC Training', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2400, NULL, 'Influenza', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2410, NULL, 'IV Needless', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2420, NULL, 'Pain Mangt', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2430, NULL, 'Medications', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2440, NULL, 'Drop-in Jap', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2450, NULL, 'Mandarin Course', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2460, NULL, 'Sichuan', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2470, NULL, 'Drugs', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2480, NULL, 'Intro. of maternal', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2490, NULL, 'New techniques in tx.', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2500, NULL, 'IC-Avian Flu', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2510, NULL, 'Clinical Waste Management', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2520, NULL, 'Hepatitis', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2530, NULL, 'Renovation', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2540, NULL, 'NLP course', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2550, NULL, 'Eldly Abuse', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2560, NULL, 'JCI-Comatose', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2570, NULL, 'Inf. Diseases Notification', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2580, NULL, 'Fire drill', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2590, NULL, 'Varicose Veins', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2600, NULL, 'Child Abuse', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2610, NULL, 'Psychiatric', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2620, NULL, 'Japanese Class', 'other', 'class');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2630, NULL, 'CNE-Organ', 'other', 'class');

INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_REMARK, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2700, NULL, 'PI Lecture', 'Topic TBA', 'other', 'class');
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_REMARK, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2710, NULL, 'Pharmacy', 'Pharmacological Approach In Pain Manangement', 'other', 'class');
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_REMARK, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2720, NULL, 'Easy Intrepretation Of Echo Results', '', 'other', 'class');
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_REMARK, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2730, NULL, 'CNE - Care Of Cardiac Pediatric Patients In Icu Setting', '', 'other', 'class');
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_REMARK, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2740, NULL, 'CME/CNE - Congential Heart Disease- What Can Be Done In The Private Setting?', '', 'other', 'class');
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_REMARK, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2750, NULL, 'CNE - Breavement Counselling', 'Agnes Tin, Teaching Consultant, HKU Centre On Behavioral Health', 'other', 'class');
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_REMARK, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2760, NULL, 'Usage Of Concealment Trolley', 'For All Nurses and HCA''S', 'other', 'class');
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_REMARK, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2770, NULL, 'IC In Daily Work Of Maintenance Staff', '', 'other', 'class');
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_REMARK, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2780, NULL, 'Professional Exchange Session For Mainland Cardiac Nurses', '', 'other', 'class');
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_REMARK, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2790, NULL, 'Half-Day Orientation Program For Agency Nurses And Hca''s Various Presenters', '', 'other', 'class');
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_REMARK, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2800, NULL, 'Endoscopic Reprossessing And Disinfection Training', '', 'other', 'class');

INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_REMARK, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 2810, NULL, 'Walk-In It Training On Clinical Management System', 'CSR Order Entry and Electronic Medical Chart', 'other', 'class');
  
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_REMARK, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 3010, NULL, 'Interest Club-Photography', 'Basics Of Photography', 'other', 'class');

--OSH-Fall Prevention
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 4010, NULL, 'Clinical Waste Management', 'inservice', 'class', 'OSH');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 4020, NULL, 'ECG Recognition and Airway Management ', 'inservice', 'class', 'OSH');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 4030, NULL, 'Employee Health Talk on Diagnositic Imaging Lab and DI', 'inservice', 'class', 'OSH');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 4040, NULL, 'Hepatitis', 'inservice', 'class', 'OSH');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 4050, NULL, 'Management of haszdous materials -MSDS', 'inservice', 'class', 'OSH');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 4060, NULL, 'Manual Handling (Chi)', 'inservice', 'class', 'OSH');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 4070, NULL, 'Needle Stick Prevention', 'inservice', 'class', 'OSH');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 4080, NULL, 'Needlestick Incidents, Management and Reporting', 'inservice', 'class', 'OSH');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 4090, NULL, 'Occupational Health Promotional Day', 'inservice', 'class', 'OSH');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 4100, NULL, 'OSH-Fall Prevention', 'inservice', 'class', 'OSH');

--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 4210, NULL, 'Audit for all staff', 'inservice', 'class', 'IC');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 4220, NULL, 'Avian Flu Triage Assessment Update', 'inservice', 'class', 'IC');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 4230, NULL, 'Food and Drug Interactions', 'inservice', 'class', 'IC');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 4240, NULL, 'IC standards requiring 1-year JCI Compliance', 'inservice', 'class', 'IC');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 4250, NULL, 'IC-Hospital Environment During Renovation (Chi)', 'inservice', 'class', 'IC');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 4260, NULL, 'Infection C standards requiring 1 year compliance', 'inservice', 'class', 'IC');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 4270, NULL, 'Infection control Class for HCA (Chi)', 'inservice', 'class', 'IC');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 4280, NULL, 'Infection control Class for HCA (Eng)', 'inservice', 'class', 'IC');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 4290, NULL, 'Infection Control in ICU', 'inservice', 'class', 'IC');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 4300, NULL, 'Infection Control- Management During Renovation', 'inservice', 'class', 'IC');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 4310, NULL, 'Infection Control Update', 'inservice', 'class', 'IC');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 4320, NULL, 'Infection Diseases Notification', 'inservice', 'class', 'IC');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 4330, NULL, 'Influenza Information Update Sessions', 'inservice', 'class', 'IC');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 4340, NULL, 'Managementof infection Control Issues at HKAH', 'inservice', 'class', 'IC');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 4350, NULL, 'Must Know IC issues at HKAH during Winter and Spring Times', 'inservice', 'class', 'IC');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 4360, NULL, 'N95 Fit Test', 'inservice', 'class', 'IC');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 4370, NULL, 'PCI Fun Day', 'inservice', 'class', 'IC');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 4380, NULL, 'SARS/Avian Flu Drill', 'inservice', 'class', 'IC');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 4390, NULL, 'Serious Response Level and Update on Avian Flu', 'inservice', 'class', 'IC');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 4400, NULL, 'Standard Precaution (Chi)', 'inservice', 'class', 'IC');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 4410, NULL, 'Trent Preparations for Infection Control (Chi)', 'inservice', 'class', 'IC');
--INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 4420, NULL, 'Trent Preparations for Infection Control (Eng)', 'inservice', 'class', 'IC');

INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_SHORT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 5010, NULL, 'Basic Life Support for Healthcare Provider', 'BLS', 'ce', 'self');
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_SHORT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 5020, NULL, 'Advanced Cardiac Life Support Course', 'ACLS', 'ce', 'self');
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_REMARK, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 5990, NULL, 'Others', '', 'ce', 'self');

INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 6010, NULL, 'Precaution', 'other', 'online');
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_SHORT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 6020, NULL, 'Competency Test for Care of Comatose Patients', 'Care of Comatose Patients', 'inservice', 'online');
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_SHORT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 6030, NULL, 'Competency Test for Patient Fall Assessment and Documentation', 'Patient Fall Assessment and Documentation', 'inservice', 'online');
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 6040, NULL, 'Staff Knowledge on ERSM', 'other', 'online');
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_DEPARTMENT_CODE, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE) VALUES ('hkah', 'education', 6210, NULL, 'MRI Safety', 'inservice', 'online');

INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_EVENT_DESC, CO_EVENT_CATEGORY) VALUES ('hkah', 'booking', 1001, '1B-Seminar', 'seminar');
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_EVENT_DESC, CO_EVENT_CATEGORY) VALUES ('hkah', 'booking', 1002, '1B-Conference', 'conference');
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_EVENT_DESC, CO_EVENT_CATEGORY) VALUES ('hkah', 'booking', 1003, '1B-Meeting', 'meeting');
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_EVENT_DESC, CO_EVENT_CATEGORY) VALUES ('hkah', 'booking', 1004, '12B-Board', 'board');
--e-appraisal
INSERT INTO CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_EVENT_DESC, CO_EVENT_CATEGORY) VALUES ('hkah', 'appraisal', 6306, 'Performance Evaluation', 'other');
--IV Therapy
INSERT INTO CO_EVENT ( CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_EVENT_DESC, CO_EVENT_CATEGORY, CO_EVENT_TYPE, CO_REQUIRE_ASSESSMENT_PASS)VALUES ('hkah','education',6307,'Intravenous Therapy','other','class','Y');