ALTER TABLE CO_ENROLLMENT_FOLLOWUP
 DROP PRIMARY KEY CASCADE;
DROP TABLE CO_ENROLLMENT_FOLLOWUP CASCADE CONSTRAINTS;

CREATE TABLE CO_ENROLLMENT_FOLLOWUP
(
 CO_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 CO_EVENT_ID NUMBER(*,0) NOT NULL ENABLE,
 CO_SCHEDULE_ID NUMBER(*,0) NULL,
 CO_USER_ID VARCHAR2(20 BYTE) NOT NULL,
 CO_ENROLL_NO NUMBER(*,0) DEFAULT 1,
 REMARK VARCHAR2(300 BYTE) NULL,
 CO_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_CREATED_DATE DATE DEFAULT SYSDATE,
 REMARK_ID NUMBER(*,0)
);

ALTER TABLE CO_ENROLLMENT_FOLLOWUP ADD (
 CONSTRAINT CO_ENROLLMENT_R01
 FOREIGN KEY (CO_SITE_CODE, CO_EVENT_ID)
 REFERENCES CO_EVENT (CO_SITE_CODE, CO_EVENT_ID));