ALTER TABLE CO_EMAIL_IDPWD
 DROP PRIMARY KEY CASCADE;
DROP TABLE CO_EMAIL_IDPWD CASCADE CONSTRAINTS;

CREATE TABLE CO_EMAIL_IDPWD
(
 CO_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 CO_EMAIL_ID VARCHAR2(255 BYTE),
 CO_EMAIL_PWD VARCHAR2(255 BYTE),
 CO_CREATED_DATE DATE DEFAULT SYSDATE,
 CO_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CO_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CO_SITE_CODE, CO_EMAIL_ID, CO_EMAIL_PWD)
);
