ALTER TABLE CO_GROUPS
 DROP PRIMARY KEY CASCADE;
DROP TABLE CO_GROUPS CASCADE CONSTRAINTS;

CREATE TABLE CO_GROUPS
(
 CO_GROUP_ID VARCHAR2(50 BYTE) NOT NULL ENABLE,
 CO_GROUP_DESC VARCHAR2(255 BYTE),
 CO_GROUP_LEVEL VARCHAR2(255 BYTE),
 CO_CREATED_DATE DATE DEFAULT SYSDATE,
 CO_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CO_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CO_GROUP_ID)
);

SET DEFINE OFF
-- access control with group level
INSERT INTO CO_GROUPS (CO_GROUP_ID, CO_GROUP_DESC, CO_GROUP_LEVEL) VALUES ('admin', 'Administrator', 1);
INSERT INTO CO_GROUPS (CO_GROUP_ID, CO_GROUP_DESC, CO_GROUP_LEVEL) VALUES ('author', 'Author', 2);
INSERT INTO CO_GROUPS (CO_GROUP_ID, CO_GROUP_DESC, CO_GROUP_LEVEL) VALUES ('officeAdministrator','Office Administrator', 3);
INSERT INTO CO_GROUPS (CO_GROUP_ID, CO_GROUP_DESC, CO_GROUP_LEVEL) VALUES ('manager', 'Manager', 6);
INSERT INTO CO_GROUPS (CO_GROUP_ID, CO_GROUP_DESC, CO_GROUP_LEVEL) VALUES ('staff', 'Staff', 7);
INSERT INTO CO_GROUPS (CO_GROUP_ID, CO_GROUP_DESC, CO_GROUP_LEVEL) VALUES ('doctor', 'Doctor', 7);
INSERT INTO CO_GROUPS (CO_GROUP_ID, CO_GROUP_DESC, CO_GROUP_LEVEL) VALUES ('guest', 'Guest', 8);

-- other access group
INSERT INTO CO_GROUPS (CO_GROUP_ID, CO_GROUP_DESC, CO_GROUP_LEVEL) VALUES ('managerHR', 'HR Manager', 0);
INSERT INTO CO_GROUPS (CO_GROUP_ID, CO_GROUP_DESC, CO_GROUP_LEVEL) VALUES ('managerEducation', 'Education Manager', 0);
INSERT INTO CO_GROUPS (CO_GROUP_ID, CO_GROUP_DESC, CO_GROUP_LEVEL) VALUES ('crm', 'CRM', 0);
INSERT INTO CO_GROUPS (CO_GROUP_ID, CO_GROUP_DESC, CO_GROUP_LEVEL) VALUES ('meetingRoom.booking', 'Meeting Room Booking', 0);
INSERT INTO CO_GROUPS (CO_GROUP_ID, CO_GROUP_DESC, CO_GROUP_LEVEL) VALUES ('ghc2hkah', 'GHC', 0);
INSERT INTO CO_GROUPS (CO_GROUP_ID, CO_GROUP_DESC, CO_GROUP_LEVEL) VALUES ('eleave', 'E-Leave', 0);
INSERT INTO CO_GROUPS (CO_GROUP_ID, CO_GROUP_DESC, CO_GROUP_LEVEL) VALUES ('senior.management', 'Senior Management', 0);
INSERT INTO CO_GROUPS (CO_GROUP_ID, CO_GROUP_DESC, CO_GROUP_LEVEL) VALUES ('administration.statistic', 'Administration Statistic', 0);
INSERT INTO CO_GROUPS (CO_GROUP_ID, CO_GROUP_DESC, CO_GROUP_LEVEL) VALUES ('administration.patient.info', 'Administration Statistic about Patient', 0);
INSERT INTO CO_GROUPS (CO_GROUP_ID, CO_GROUP_DESC, CO_GROUP_LEVEL) VALUES ('department.head', 'Department Head', 0);
INSERT INTO CO_GROUPS (CO_GROUP_ID, CO_GROUP_DESC, CO_GROUP_LEVEL) VALUES ('nominate.ignore.list', 'Nominate Ignore List', 0);
INSERT INTO CO_GROUPS (CO_GROUP_ID, CO_GROUP_DESC, CO_GROUP_LEVEL) VALUES ('admission.at.ward', 'Admission At Ward', 0);
INSERT INTO CO_GROUPS (CO_GROUP_ID, CO_GROUP_DESC, CO_GROUP_LEVEL) VALUES ('call.back.patient.appointment', 'Call Back Patient Appointment', 0);
INSERT INTO CO_GROUPS (CO_GROUP_ID, CO_GROUP_DESC, CO_GROUP_LEVEL) VALUES ('cts', 'Credential Tracking System', 0);
INSERT INTO CO_GROUPS (CO_GROUP_ID, CO_GROUP_DESC, CO_GROUP_LEVEL) VALUES ('epo', 'Electronic Purchase Order', 0);
INSERT INTO CO_GROUPS (CO_GROUP_ID, CO_GROUP_DESC, CO_GROUP_LEVEL) VALUES ('haa', 'Health Assessment', 0);
INSERT INTO CO_GROUPS (CO_GROUP_ID, CO_GROUP_DESC, CO_GROUP_LEVEL) VALUES ('unit.manager', 'Unit Manager', 0);
INSERT INTO CO_GROUPS (CO_GROUP_ID, CO_GROUP_DESC, CO_GROUP_LEVEL) VALUES ('administration.statistic.report', 'Administration Statistic on report', 0);
INSERT INTO CO_GROUPS (CO_GROUP_ID, CO_GROUP_DESC, CO_GROUP_LEVEL) VALUES ('administration.statistic.hat', 'AdministrationStatistic on Hats', 0);
INSERT INTO CO_GROUPS (CO_GROUP_ID, CO_GROUP_DESC, CO_GROUP_LEVEL) VALUES ('ba', 'Billing Agreement', 0);
INSERT INTO CO_GROUPS (CO_GROUP_ID, CO_GROUP_DESC, CO_GROUP_LEVEL) VALUES ('view.important.letter', 'View important letter', 0);
INSERT INTO CO_GROUPS (CO_GROUP_ID, CO_GROUP_DESC, CO_GROUP_LEVEL) VALUES ('ic.reports', 'Infection Control Surveillance', 0);
INSERT INTO CO_GROUPS (CO_GROUP_ID, CO_GROUP_DESC, CO_GROUP_LEVEL) VALUES ('forwardScanning', 'Forward Scanning', 0);
INSERT INTO CO_GROUPS (CO_GROUP_ID, CO_GROUP_DESC, CO_GROUP_LEVEL) VALUES ('di', 'Diagnosis Imaging', 0);
INSERT INTO CO_GROUPS (CO_GROUP_ID, CO_GROUP_DESC, CO_GROUP_LEVEL) VALUES ('policy', 'Policy and Resources', 0);
INSERT INTO CO_GROUPS (CO_GROUP_ID, CO_GROUP_DESC, CO_GROUP_LEVEL) VALUES ('board.meet.rpt', 'Board Meeting Reports', 0);
INSERT INTO CO_GROUPS (CO_GROUP_ID, CO_GROUP_DESC, CO_GROUP_LEVEL) VALUES ('managementTr', 'Management Trainee', 0);