ALTER TABLE CO_LOCATION
 DROP PRIMARY KEY CASCADE;
DROP TABLE CO_LOCATION CASCADE CONSTRAINTS;

CREATE TABLE CO_LOCATION
(
 CO_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 CO_LOCATION_ID NUMBER(*,0) NOT NULL ENABLE,
 CO_LOCATION_DESC VARCHAR2(100 BYTE),
 CO_CREATED_DATE DATE DEFAULT SYSDATE,
 CO_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CO_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CO_LOCATION_ID)
);
INSERT INTO CO_LOCATION(CO_SITE_CODE, CO_LOCATION_ID, CO_LOCATION_DESC) VALUES('hkah', 1, '1B');
INSERT INTO CO_LOCATION(CO_SITE_CODE, CO_LOCATION_ID, CO_LOCATION_DESC) VALUES('hkah', 2, '4C');
INSERT INTO CO_LOCATION(CO_SITE_CODE, CO_LOCATION_ID, CO_LOCATION_DESC) VALUES('hkah', 3, '12B');
INSERT INTO CO_LOCATION(CO_SITE_CODE, CO_LOCATION_ID, CO_LOCATION_DESC) VALUES('hkah', 4, 'LMC');
INSERT INTO CO_LOCATION(CO_SITE_CODE, CO_LOCATION_ID, CO_LOCATION_DESC) VALUES('hkah', 5, 'CP LAB');
INSERT INTO CO_LOCATION(CO_SITE_CODE, CO_LOCATION_ID, CO_LOCATION_DESC) VALUES('hkah', 6, 'URGENT CARE');
INSERT INTO CO_LOCATION(CO_SITE_CODE, CO_LOCATION_ID, CO_LOCATION_DESC) VALUES('hkah', 7, 'OT');
INSERT INTO CO_LOCATION(CO_SITE_CODE, CO_LOCATION_ID, CO_LOCATION_DESC) VALUES('hkah', 8, '7/F CAFETERIA');
INSERT INTO CO_LOCATION(CO_SITE_CODE, CO_LOCATION_ID, CO_LOCATION_DESC) VALUES('hkah', 9, 'DI DEPT');
INSERT INTO CO_LOCATION(CO_SITE_CODE, CO_LOCATION_ID, CO_LOCATION_DESC) VALUES('hkah', 10, 'OPD');
INSERT INTO CO_LOCATION(CO_SITE_CODE, CO_LOCATION_ID, CO_LOCATION_DESC) VALUES('hkah', 11, '3B');
INSERT INTO CO_LOCATION(CO_SITE_CODE, CO_LOCATION_ID, CO_LOCATION_DESC) VALUES('hkah', 12, '2/F');