ALTER TABLE CO_NEWS
 DROP PRIMARY KEY CASCADE;
DROP TABLE CO_NEWS CASCADE CONSTRAINTS;

CREATE TABLE CO_NEWS
(
 CO_NEWS_ID NUMBER(*,0) NOT NULL ENABLE,
 CO_NEWS_CATEGORY VARCHAR2(20 BYTE),
 CO_NEWS_TYPE VARCHAR2(60 BYTE),
 CO_NEWS_SENDER VARCHAR2(60 BYTE),
 CO_TITLE VARCHAR2(500 BYTE),
 CO_TITLE_URL VARCHAR2(500 BYTE),
 CO_TITLE_IMAGE VARCHAR2(100 BYTE),
 CO_POST_DATE DATE DEFAULT SYSDATE,
 CO_EXPIRE_DATE DATE,
 CO_EVENT_DATE DATE,
 CO_HIT_RATE INT DEFAULT 0,
 CO_LIKED INT DEFAULT 0,
 CO_CREATED_DATE DATE DEFAULT SYSDATE,
 CO_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CO_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CO_NEWS_ID, CO_NEWS_CATEGORY)
);