ALTER TABLE CO_PATIENT_UPDATE_EMAIL
 DROP PRIMARY KEY CASCADE;
DROP TABLE CO_PATIENT_UPDATE_EMAIL CASCADE CONSTRAINTS;

CREATE TABLE CO_PATIENT_UPDATE_EMAIL
(
 CO_PUEID NUMBER(*,0) NOT NULL ENABLE,
 CO_LASTEMAILSEND_DATE DATE DEFAULT SYSDATE,
 CO_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CO_PUEID)
);

INSERT INTO CO_PATIENT_UPDATE_EMAIL (CO_PUEID) VALUES ('1');