ALTER TABLE CO_REPORT
 DROP PRIMARY KEY CASCADE;
DROP TABLE CO_REPORT CASCADE CONSTRAINTS;

COMMIT;

CREATE TABLE CO_REPORT 
(
	CO_SITE_CODE   		VARCHAR2(4 BYTE),
	CO_REPORT_ID		NUMBER NOT NULL ENABLE,
	CO_REPORT_TYPE		VARCHAR2(20 BYTE),
	CO_TEMPLATE_ID		NUMBER NOT NULL ENABLE,
	CREATE_DATE 		DATE DEFAULT SYSDATE,
    CREATE_USER 		VARCHAR2(50 BYTE) DEFAULT 'SYSTEM',
    MODIFIED_DATE 		DATE DEFAULT SYSDATE,
    MODIFIED_USER 		VARCHAR2(50 BYTE) DEFAULT 'SYSTEM',
    ENABLE        		NUMBER(1,0) DEFAULT 1,
    PRIMARY KEY (CO_REPORT_ID)
);

COMMIT;

ALTER TABLE CO_REPORT ADD (
 CONSTRAINT CO_REPORT_FK1
 FOREIGN KEY (CO_TEMPLATE_ID)
 REFERENCES CO_TEMPLATE (CO_TEMPLATE_ID));
 
COMMIT;