ALTER TABLE CO_STAFF_EVENT_INTERVAL DROP PRIMARY KEY CASCADE;
DROP TABLE CO_STAFF_EVENT_INTERVAL CASCADE CONSTRAINTS;

CREATE TABLE CO_STAFF_EVENT_INTERVAL
(
 CO_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 CO_CATEGORY VARCHAR2(2 BYTE) NULL,     --[N]ursing,[P]aramedical,other [H]ealthcare, [o]ther grades of Staff
 CO_MODULE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,	-- education, lmc
 CO_EVENT_ID NUMBER(*,0) NOT NULL ENABLE,
 CO_TIME_INTERVAL NUMBER(*,0) DEFAULT 12, -- by month
 CO_CREATED_DATE DATE DEFAULT SYSDATE,
 CO_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CO_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CO_SITE_CODE, CO_CATEGORY, CO_MODULE_CODE, CO_EVENT_ID)
);


ALTER TABLE CO_STAFF_EVENT_INTERVAL ADD (
 CONSTRAINT CO_STAFF_EVENT_INTERVAL_R01
 FOREIGN KEY (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID)
 REFERENCES CO_EVENT (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID));
 
 ALTER TABLE CO_STAFFS MODIFY CO_CATEGORY VARCHAR2(2 BYTE);
 
INSERT INTO co_staff_event_interval (co_site_code,co_category,co_module_code,co_event_id,co_time_interval,co_created_date,co_created_user,co_modified_date,co_modified_user,co_enabled) VALUES ('hkah','1','education','1010',12,SYSDATE,'SYSTEM',SYSDATE,'SYSTEM',1);
INSERT INTO co_staff_event_interval (co_site_code,co_category,co_module_code,co_event_id,co_time_interval,co_created_date,co_created_user,co_modified_date,co_modified_user,co_enabled) VALUES ('hkah','2','education','1010',12,SYSDATE,'SYSTEM',SYSDATE,'SYSTEM',1);
INSERT INTO co_staff_event_interval (co_site_code,co_category,co_module_code,co_event_id,co_time_interval,co_created_date,co_created_user,co_modified_date,co_modified_user,co_enabled) VALUES ('hkah','31','education','1010',12,SYSDATE,'SYSTEM',SYSDATE,'SYSTEM',1);
INSERT INTO co_staff_event_interval (co_site_code,co_category,co_module_code,co_event_id,co_time_interval,co_created_date,co_created_user,co_modified_date,co_modified_user,co_enabled) VALUES ('hkah','32','education','1010',12,SYSDATE,'SYSTEM',SYSDATE,'SYSTEM',1);
INSERT INTO co_staff_event_interval (co_site_code,co_category,co_module_code,co_event_id,co_time_interval,co_created_date,co_created_user,co_modified_date,co_modified_user,co_enabled) VALUES ('hkah','33','education','1010',12,SYSDATE,'SYSTEM',SYSDATE,'SYSTEM',1);
INSERT INTO co_staff_event_interval (co_site_code,co_category,co_module_code,co_event_id,co_time_interval,co_created_date,co_created_user,co_modified_date,co_modified_user,co_enabled) VALUES ('hkah','41','education','1010',12,SYSDATE,'SYSTEM',SYSDATE,'SYSTEM',1);
INSERT INTO co_staff_event_interval (co_site_code,co_category,co_module_code,co_event_id,co_time_interval,co_created_date,co_created_user,co_modified_date,co_modified_user,co_enabled) VALUES ('hkah','42','education','1010',12,SYSDATE,'SYSTEM',SYSDATE,'SYSTEM',1);
INSERT INTO co_staff_event_interval (co_site_code,co_category,co_module_code,co_event_id,co_time_interval,co_created_date,co_created_user,co_modified_date,co_modified_user,co_enabled) VALUES ('hkah','1','education','1040',12,SYSDATE,'SYSTEM',SYSDATE,'SYSTEM',1);
INSERT INTO co_staff_event_interval (co_site_code,co_category,co_module_code,co_event_id,co_time_interval,co_created_date,co_created_user,co_modified_date,co_modified_user,co_enabled) VALUES ('hkah','2','education','1040',12,SYSDATE,'SYSTEM',SYSDATE,'SYSTEM',1);
INSERT INTO co_staff_event_interval (co_site_code,co_category,co_module_code,co_event_id,co_time_interval,co_created_date,co_created_user,co_modified_date,co_modified_user,co_enabled) VALUES ('hkah','31','education','1040',12,SYSDATE,'SYSTEM',SYSDATE,'SYSTEM',1);
INSERT INTO co_staff_event_interval (co_site_code,co_category,co_module_code,co_event_id,co_time_interval,co_created_date,co_created_user,co_modified_date,co_modified_user,co_enabled) VALUES ('hkah','32','education','1040',12,SYSDATE,'SYSTEM',SYSDATE,'SYSTEM',1);
INSERT INTO co_staff_event_interval (co_site_code,co_category,co_module_code,co_event_id,co_time_interval,co_created_date,co_created_user,co_modified_date,co_modified_user,co_enabled) VALUES ('hkah','33','education','1040',12,SYSDATE,'SYSTEM',SYSDATE,'SYSTEM',1);
INSERT INTO co_staff_event_interval (co_site_code,co_category,co_module_code,co_event_id,co_time_interval,co_created_date,co_created_user,co_modified_date,co_modified_user,co_enabled) VALUES ('hkah','41','education','1040',12,SYSDATE,'SYSTEM',SYSDATE,'SYSTEM',1);
INSERT INTO co_staff_event_interval (co_site_code,co_category,co_module_code,co_event_id,co_time_interval,co_created_date,co_created_user,co_modified_date,co_modified_user,co_enabled) VALUES ('hkah','42','education','1040',12,SYSDATE,'SYSTEM',SYSDATE,'SYSTEM',1);
INSERT INTO co_staff_event_interval (co_site_code,co_category,co_module_code,co_event_id,co_time_interval,co_created_date,co_created_user,co_modified_date,co_modified_user,co_enabled) VALUES ('hkah','1','education','1030',12,SYSDATE,'SYSTEM',SYSDATE,'SYSTEM',1);
INSERT INTO co_staff_event_interval (co_site_code,co_category,co_module_code,co_event_id,co_time_interval,co_created_date,co_created_user,co_modified_date,co_modified_user,co_enabled) VALUES ('hkah','2','education','1030',12,SYSDATE,'SYSTEM',SYSDATE,'SYSTEM',1);
INSERT INTO co_staff_event_interval (co_site_code,co_category,co_module_code,co_event_id,co_time_interval,co_created_date,co_created_user,co_modified_date,co_modified_user,co_enabled) VALUES ('hkah','31','education','1030',12,SYSDATE,'SYSTEM',SYSDATE,'SYSTEM',1);
INSERT INTO co_staff_event_interval (co_site_code,co_category,co_module_code,co_event_id,co_time_interval,co_created_date,co_created_user,co_modified_date,co_modified_user,co_enabled) VALUES ('hkah','32','education','1030',12,SYSDATE,'SYSTEM',SYSDATE,'SYSTEM',1);
INSERT INTO co_staff_event_interval (co_site_code,co_category,co_module_code,co_event_id,co_time_interval,co_created_date,co_created_user,co_modified_date,co_modified_user,co_enabled) VALUES ('hkah','33','education','1030',12,SYSDATE,'SYSTEM',SYSDATE,'SYSTEM',1);
INSERT INTO co_staff_event_interval (co_site_code,co_category,co_module_code,co_event_id,co_time_interval,co_created_date,co_created_user,co_modified_date,co_modified_user,co_enabled) VALUES ('hkah','41','education','1030',12,SYSDATE,'SYSTEM',SYSDATE,'SYSTEM',1);
INSERT INTO co_staff_event_interval (co_site_code,co_category,co_module_code,co_event_id,co_time_interval,co_created_date,co_created_user,co_modified_date,co_modified_user,co_enabled) VALUES ('hkah','42','education','1030',12,SYSDATE,'SYSTEM',SYSDATE,'SYSTEM',1);
INSERT INTO co_staff_event_interval (co_site_code,co_category,co_module_code,co_event_id,co_time_interval,co_created_date,co_created_user,co_modified_date,co_modified_user,co_enabled) VALUES ('hkah','1','education','1020',12,SYSDATE,'SYSTEM',SYSDATE,'SYSTEM',1);
INSERT INTO co_staff_event_interval (co_site_code,co_category,co_module_code,co_event_id,co_time_interval,co_created_date,co_created_user,co_modified_date,co_modified_user,co_enabled) VALUES ('hkah','2','education','1020',12,SYSDATE,'SYSTEM',SYSDATE,'SYSTEM',1);
INSERT INTO co_staff_event_interval (co_site_code,co_category,co_module_code,co_event_id,co_time_interval,co_created_date,co_created_user,co_modified_date,co_modified_user,co_enabled) VALUES ('hkah','31','education','1020',12,SYSDATE,'SYSTEM',SYSDATE,'SYSTEM',1);
INSERT INTO co_staff_event_interval (co_site_code,co_category,co_module_code,co_event_id,co_time_interval,co_created_date,co_created_user,co_modified_date,co_modified_user,co_enabled) VALUES ('hkah','32','education','1020',12,SYSDATE,'SYSTEM',SYSDATE,'SYSTEM',1);
INSERT INTO co_staff_event_interval (co_site_code,co_category,co_module_code,co_event_id,co_time_interval,co_created_date,co_created_user,co_modified_date,co_modified_user,co_enabled) VALUES ('hkah','33','education','1020',12,SYSDATE,'SYSTEM',SYSDATE,'SYSTEM',1);
INSERT INTO co_staff_event_interval (co_site_code,co_category,co_module_code,co_event_id,co_time_interval,co_created_date,co_created_user,co_modified_date,co_modified_user,co_enabled) VALUES ('hkah','41','education','1020',12,SYSDATE,'SYSTEM',SYSDATE,'SYSTEM',1);
INSERT INTO co_staff_event_interval (co_site_code,co_category,co_module_code,co_event_id,co_time_interval,co_created_date,co_created_user,co_modified_date,co_modified_user,co_enabled) VALUES ('hkah','42','education','1020',12,SYSDATE,'SYSTEM',SYSDATE,'SYSTEM',1);
INSERT INTO co_staff_event_interval (co_site_code,co_category,co_module_code,co_event_id,co_time_interval,co_created_date,co_created_user,co_modified_date,co_modified_user,co_enabled) VALUES ('hkah','1','education','1070',12,SYSDATE,'SYSTEM',SYSDATE,'SYSTEM',1);
INSERT INTO co_staff_event_interval (co_site_code,co_category,co_module_code,co_event_id,co_time_interval,co_created_date,co_created_user,co_modified_date,co_modified_user,co_enabled) VALUES ('hkah','2','education','1070',12,SYSDATE,'SYSTEM',SYSDATE,'SYSTEM',1);
INSERT INTO co_staff_event_interval (co_site_code,co_category,co_module_code,co_event_id,co_time_interval,co_created_date,co_created_user,co_modified_date,co_modified_user,co_enabled) VALUES ('hkah','33','education','1070',12,SYSDATE,'SYSTEM',SYSDATE,'SYSTEM',1);
INSERT INTO co_staff_event_interval (co_site_code,co_category,co_module_code,co_event_id,co_time_interval,co_created_date,co_created_user,co_modified_date,co_modified_user,co_enabled) VALUES ('hkah','1','education','1050',12,SYSDATE,'SYSTEM',SYSDATE,'SYSTEM',1);
INSERT INTO co_staff_event_interval (co_site_code,co_category,co_module_code,co_event_id,co_time_interval,co_created_date,co_created_user,co_modified_date,co_modified_user,co_enabled) VALUES ('hkah','2','education','1050',12,SYSDATE,'SYSTEM',SYSDATE,'SYSTEM',1);
INSERT INTO co_staff_event_interval (co_site_code,co_category,co_module_code,co_event_id,co_time_interval,co_created_date,co_created_user,co_modified_date,co_modified_user,co_enabled) VALUES ('hkah','32','education','1050',12,SYSDATE,'SYSTEM',SYSDATE,'SYSTEM',1);
INSERT INTO co_staff_event_interval (co_site_code,co_category,co_module_code,co_event_id,co_time_interval,co_created_date,co_created_user,co_modified_date,co_modified_user,co_enabled) VALUES ('hkah','1','education','1110',999,SYSDATE,'SYSTEM',SYSDATE,'SYSTEM',1);
INSERT INTO co_staff_event_interval (co_site_code,co_category,co_module_code,co_event_id,co_time_interval,co_created_date,co_created_user,co_modified_date,co_modified_user,co_enabled) VALUES ('hkah','2','education','1110',999,SYSDATE,'SYSTEM',SYSDATE,'SYSTEM',1);
INSERT INTO co_staff_event_interval (co_site_code,co_category,co_module_code,co_event_id,co_time_interval,co_created_date,co_created_user,co_modified_date,co_modified_user,co_enabled) VALUES ('hkah','31','education','1110',999,SYSDATE,'SYSTEM',SYSDATE,'SYSTEM',1);
INSERT INTO co_staff_event_interval (co_site_code,co_category,co_module_code,co_event_id,co_time_interval,co_created_date,co_created_user,co_modified_date,co_modified_user,co_enabled) VALUES ('hkah','32','education','1110',999,SYSDATE,'SYSTEM',SYSDATE,'SYSTEM',1);
INSERT INTO co_staff_event_interval (co_site_code,co_category,co_module_code,co_event_id,co_time_interval,co_created_date,co_created_user,co_modified_date,co_modified_user,co_enabled) VALUES ('hkah','33','education','1110',999,SYSDATE,'SYSTEM',SYSDATE,'SYSTEM',1);
INSERT INTO co_staff_event_interval (co_site_code,co_category,co_module_code,co_event_id,co_time_interval,co_created_date,co_created_user,co_modified_date,co_modified_user,co_enabled) VALUES ('hkah','41','education','1110',999,SYSDATE,'SYSTEM',SYSDATE,'SYSTEM',1);
INSERT INTO co_staff_event_interval (co_site_code,co_category,co_module_code,co_event_id,co_time_interval,co_created_date,co_created_user,co_modified_date,co_modified_user,co_enabled) VALUES ('hkah','42','education','1110',999,SYSDATE,'SYSTEM',SYSDATE,'SYSTEM',1);


UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '1001';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '1014';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '1028';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '1029';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '1037';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '1039';
UPDATE co_staffs SET co_category = '32' WHERE co_staff_id = '1040';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '1050';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '1061';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '1067';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '1069';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '1074';
UPDATE co_staffs SET co_category = '31' WHERE co_staff_id = '1077';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '1079';
UPDATE co_staffs SET co_category = '31' WHERE co_staff_id = '1086';
UPDATE co_staffs SET co_category = '32' WHERE co_staff_id = '1103';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '1107';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '1113';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '1118';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '1122';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '1143';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '1150';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '1156';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '1174';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '1186';
UPDATE co_staffs SET co_category = '33' WHERE co_staff_id = '1267';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '1283';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '1334';
UPDATE co_staffs SET co_category = '32' WHERE co_staff_id = '1388';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '1422';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '1425';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '1565';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '1573';
UPDATE co_staffs SET co_category = '32' WHERE co_staff_id = '1588';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '1596';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '1612';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '1621';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '1648';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '1676';
UPDATE co_staffs SET co_category = '32' WHERE co_staff_id = '1681';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '1718';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '1727';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '1747';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '1756';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '1767';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '1781';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '1807';
UPDATE co_staffs SET co_category = '32' WHERE co_staff_id = '1809';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '1820';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '1821';
UPDATE co_staffs SET co_category = '33' WHERE co_staff_id = '1834';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '1873';
UPDATE co_staffs SET co_category = '32' WHERE co_staff_id = '1877';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '1900';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '1917';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '1927';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '1953';
UPDATE co_staffs SET co_category = '32' WHERE co_staff_id = '1990';
UPDATE co_staffs SET co_category = '32' WHERE co_staff_id = '1999';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '2040';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '2055';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '2072';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '2075';
UPDATE co_staffs SET co_category = '33' WHERE co_staff_id = '2080';
UPDATE co_staffs SET co_category = '33' WHERE co_staff_id = '2101';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '2109';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '2115';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '2126';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '2139';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '2147';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '2155';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '2157';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '2169';
UPDATE co_staffs SET co_category = '32' WHERE co_staff_id = '2185';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '2190';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '2192';
UPDATE co_staffs SET co_category = '33' WHERE co_staff_id = '2214';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '2220';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '2225';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '2228';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '2233';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '2269';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '2305';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '2321';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '2327';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '2360';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '2383';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '2390';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '2402';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '2404';
UPDATE co_staffs SET co_category = '33' WHERE co_staff_id = '2410';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '2411';
UPDATE co_staffs SET co_category = '31' WHERE co_staff_id = '2414';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '2429';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '2433';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '2455';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '2458';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '2461';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '2467';
UPDATE co_staffs SET co_category = '31' WHERE co_staff_id = '2469';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '2483';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '2508';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '2533';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '2536';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '2537';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '2572';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '2576';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '2589';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '2609';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '2625';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '2638';
UPDATE co_staffs SET co_category = '33' WHERE co_staff_id = '2648';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '2653';
UPDATE co_staffs SET co_category = '32' WHERE co_staff_id = '2657';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '2658';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '2667';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '2670';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '2681';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '2686';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '2698';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '2742';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '2745';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '2755';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '2766';
UPDATE co_staffs SET co_category = '32' WHERE co_staff_id = '2775';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '2815';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '2830';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '2845';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '2852';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '2899';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '2902';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '2903';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '2907';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '2909';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '2932';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '2938';
UPDATE co_staffs SET co_category = '31' WHERE co_staff_id = '2944';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '2966';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '2972';
UPDATE co_staffs SET co_category = '32' WHERE co_staff_id = '2978';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '2987';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '2991';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '2994';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3001';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3007';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3012';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3024';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3025';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '3026';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '3027';
UPDATE co_staffs SET co_category = '31' WHERE co_staff_id = '3029';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3030';
UPDATE co_staffs SET co_category = '31' WHERE co_staff_id = '3032';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3033';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3037';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '3043';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3044';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3046';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3051';
UPDATE co_staffs SET co_category = '32' WHERE co_staff_id = '3052';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3053';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3072';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '3075';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3078';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '3081';
UPDATE co_staffs SET co_category = '33' WHERE co_staff_id = '3084';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3093';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3094';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '3102';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3106';
UPDATE co_staffs SET co_category = '32' WHERE co_staff_id = '3122';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3153';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3154';
UPDATE co_staffs SET co_category = '32' WHERE co_staff_id = '3161';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3170';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3174';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3176';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '3179';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '3181';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3185';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3192';
UPDATE co_staffs SET co_category = '32' WHERE co_staff_id = '3209';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3212';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '3213';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3220';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3221';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3224';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3226';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '3229';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3235';
UPDATE co_staffs SET co_category = '32' WHERE co_staff_id = '3241';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3242';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3243';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3247';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '3248';
UPDATE co_staffs SET co_category = '32' WHERE co_staff_id = '3251';
UPDATE co_staffs SET co_category = '32' WHERE co_staff_id = '3254';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '3260';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '3272';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3276';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3282';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3290';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '3297';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '3308';
UPDATE co_staffs SET co_category = '32' WHERE co_staff_id = '3317';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '3320';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '3326';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3328';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3334';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3338';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3356';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3368';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3370';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '3384';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3392';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3394';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3395';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3396';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3399';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3419';
UPDATE co_staffs SET co_category = '32' WHERE co_staff_id = '3420';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3431';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3444';
UPDATE co_staffs SET co_category = '31' WHERE co_staff_id = '3445';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3457';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3460';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3462';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3464';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3465';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3466';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '3468';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3470';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3471';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '3475';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '3476';
UPDATE co_staffs SET co_category = '32' WHERE co_staff_id = '3479';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3485';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '3487';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '3494';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3496';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3497';
UPDATE co_staffs SET co_category = '31' WHERE co_staff_id = '3504';
UPDATE co_staffs SET co_category = '31' WHERE co_staff_id = '3508';
UPDATE co_staffs SET co_category = '31' WHERE co_staff_id = '3516';
UPDATE co_staffs SET co_category = '32' WHERE co_staff_id = '3521';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '3527';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '3549';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3551';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '3561';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '3564';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '3566';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '3567';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3569';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3570';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '3577';
UPDATE co_staffs SET co_category = '31' WHERE co_staff_id = '3588';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3590';
UPDATE co_staffs SET co_category = '31' WHERE co_staff_id = '3597';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3600';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '3603';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3605';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3615';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3616';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '3619';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3620';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3624';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3625';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3630';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '3631';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3634';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3635';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3637';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3639';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3640';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3641';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3645';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '3648';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '3650';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '3658';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3660';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3662';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3666';
UPDATE co_staffs SET co_category = '32' WHERE co_staff_id = '3668';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3669';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3677';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3689';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3690';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '3692';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3694';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3697';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '3705';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3713';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3715';
UPDATE co_staffs SET co_category = '32' WHERE co_staff_id = '3717';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3718';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3720';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3721';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '3722';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '3723';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '3724';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '3726';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3731';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3735';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '3736';
UPDATE co_staffs SET co_category = '31' WHERE co_staff_id = '3737';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '3739';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3740';
UPDATE co_staffs SET co_category = '31' WHERE co_staff_id = '3746';
UPDATE co_staffs SET co_category = '31' WHERE co_staff_id = '3747';
UPDATE co_staffs SET co_category = '31' WHERE co_staff_id = '3750';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '3754';
UPDATE co_staffs SET co_category = '32' WHERE co_staff_id = '3756';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '3757';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3759';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '3761';
UPDATE co_staffs SET co_category = '32' WHERE co_staff_id = '3763';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3765';
UPDATE co_staffs SET co_category = '32' WHERE co_staff_id = '3769';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3770';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3775';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '3778';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3779';
UPDATE co_staffs SET co_category = '33' WHERE co_staff_id = '3780';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '3784';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '3785';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3787';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '3789';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '3798';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '3799';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3800';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3803';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '3804';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '3807';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '3809';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '3816';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '3818';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '3819';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '3822';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '3823';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3827';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '3828';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3829';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3830';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3832';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3833';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3835';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '3840';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3841';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3845';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '3846';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3847';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '3848';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '3849';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3850';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3854';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '3861';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3870';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '3880';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '3883';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3888';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3889';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3890';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3894';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '3896';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3902';
UPDATE co_staffs SET co_category = '32' WHERE co_staff_id = '3906';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3908';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3911';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3912';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '3913';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3914';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '3919';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3922';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3924';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '3927';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '3928';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3933';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3934';
UPDATE co_staffs SET co_category = '31' WHERE co_staff_id = '3935';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '3940';
UPDATE co_staffs SET co_category = '33' WHERE co_staff_id = '3941';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3942';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3945';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '3946';
UPDATE co_staffs SET co_category = '32' WHERE co_staff_id = '3948';
UPDATE co_staffs SET co_category = '31' WHERE co_staff_id = '3949';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3950';
UPDATE co_staffs SET co_category = '32' WHERE co_staff_id = '3951';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '3952';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3953';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3954';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3957';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '3960';
UPDATE co_staffs SET co_category = '32' WHERE co_staff_id = '3962';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3963';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3964';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3966';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '3967';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3968';
UPDATE co_staffs SET co_category = '31' WHERE co_staff_id = '3972';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3973';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3976';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3977';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3978';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '3979';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3980';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '3981';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '3982';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3985';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3986';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '3987';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '3988';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '3989';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '3992';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '3993';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '3994';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '3995';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '3996';
UPDATE co_staffs SET co_category = '31' WHERE co_staff_id = '3999';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '4001';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '4002';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '4006';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '4007';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '4010';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '4011';
UPDATE co_staffs SET co_category = '33' WHERE co_staff_id = '4012';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '4015';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '4017';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '4018';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '4019';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '4020';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '4021';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '4024';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '4027';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '4032';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '4033';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '4034';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '4036';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '4038';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '4044';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '4045';
UPDATE co_staffs SET co_category = '32' WHERE co_staff_id = '4049';
UPDATE co_staffs SET co_category = '31' WHERE co_staff_id = '4052';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '4053';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '4054';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '4056';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '4060';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '4061';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '4062';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '4063';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '4065';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '4067';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '4068';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '4069';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '4070';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '4071';
UPDATE co_staffs SET co_category = '32' WHERE co_staff_id = '4072';
UPDATE co_staffs SET co_category = '32' WHERE co_staff_id = '4073';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '4076';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '4077';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '4078';
UPDATE co_staffs SET co_category = '32' WHERE co_staff_id = '4079';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '4080';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '4083';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '4084';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '4086';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '4088';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '4089';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '4090';
UPDATE co_staffs SET co_category = '32' WHERE co_staff_id = '4091';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '4092';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '4095';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '4098';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '4099';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '4101';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '4102';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '4103';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '4104';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '4105';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '4106';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '4107';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '4108';
UPDATE co_staffs SET co_category = '32' WHERE co_staff_id = '4110';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '4111';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '4112';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '4113';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '4114';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '4118';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '4119';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '4121';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '4122';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '4123';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '4124';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '4125';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '4127';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '4129';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '4130';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '4131';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '4132';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '4133';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '4135';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '4136';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '4137';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '4138';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '4141';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '4143';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '4145';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '4146';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '4147';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '4150';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '4151';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '4152';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '4153';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '4154';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '4155';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '4156';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '4157';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '4158';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '4160';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '4161';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '4162';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '4163';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '4164';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '4165';
UPDATE co_staffs SET co_category = '32' WHERE co_staff_id = '4168';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '4171';
UPDATE co_staffs SET co_category = '32' WHERE co_staff_id = '4172';
UPDATE co_staffs SET co_category = '32' WHERE co_staff_id = '4173';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '4176';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '4177';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '4179';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '4181';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '4183';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '4185';
UPDATE co_staffs SET co_category = '41' WHERE co_staff_id = '4186';
UPDATE co_staffs SET co_category = '32' WHERE co_staff_id = '4187';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '4188';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '4189';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = '4190';
UPDATE co_staffs SET co_category = '42' WHERE co_staff_id = '4191';
UPDATE co_staffs SET co_category = '1' WHERE co_staff_id = '4192';
UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = 'M002';

UPDATE co_staffs SET co_category = '2' WHERE co_staff_id = 'M002';


