ALTER TABLE CO_STAFFS_ROSTER_POSITION
 DROP PRIMARY KEY CASCADE;
DROP TABLE CO_STAFFS_ROSTER_POSITION CASCADE CONSTRAINTS;

CREATE TABLE CO_STAFFS_ROSTER_POSITION 
(
	CO_SITE_CODE 		    VARCHAR2(10 BYTE) NOT NULL,
	CO_STAFF_ID			    VARCHAR2(10 BYTE) NOT NULL,
	CO_STAFF_ROLE		    VARCHAR2(10 BYTE),
  	CO_DEPARTMENT_CODE  	VARCHAR2(10 BYTE) NOT NULL,
  	CO_INCHARGE         	VARCHAR2(1 BYTE) DEFAULT 'N',
	CO_CREATED_DATE		  	DATE DEFAULT SYSDATE,
	CO_CREATED_USER		  	VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
	CO_MODIFIED_DATE	  	DATE DEFAULT SYSDATE,
	CO_MODIFIED_USER	  	VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
	CO_ENABLED			    NUMBER DEFAULT 1,
	PRIMARY KEY (CO_SITE_CODE, CO_STAFF_ID, CO_DEPARTMENT_CODE)
);
COMMIT;

INSERT INTO CO_STAFFS_ROSTER_POSITION (CO_SITE_CODE,CO_STAFF_ID,CO_STAFF_ROLE,CO_DEPARTMENT_CODE,CO_INCHARGE) 
        VALUES ('hkah','4785','RN','100','N');
INSERT INTO CO_STAFFS_ROSTER_POSITION (CO_SITE_CODE,CO_STAFF_ID,CO_STAFF_ROLE,CO_DEPARTMENT_CODE,CO_INCHARGE) 
        VALUES ('hkah','1900','UM','100','Y');
INSERT INTO CO_STAFFS_ROSTER_POSITION (CO_SITE_CODE,CO_STAFF_ID,CO_STAFF_ROLE,CO_DEPARTMENT_CODE,CO_INCHARGE) 
        VALUES ('hkah','2533','SRN','100','Y');
INSERT INTO CO_STAFFS_ROSTER_POSITION (CO_SITE_CODE,CO_STAFF_ID,CO_STAFF_ROLE,CO_DEPARTMENT_CODE,CO_INCHARGE) 
        VALUES ('hkah','2966','RN','100','Y');
INSERT INTO CO_STAFFS_ROSTER_POSITION (CO_SITE_CODE,CO_STAFF_ID,CO_STAFF_ROLE,CO_DEPARTMENT_CODE,CO_INCHARGE) 
        VALUES ('hkah','3046','RN','100','Y');
INSERT INTO CO_STAFFS_ROSTER_POSITION (CO_SITE_CODE,CO_STAFF_ID,CO_STAFF_ROLE,CO_DEPARTMENT_CODE,CO_INCHARGE) 
        VALUES ('hkah','3465','RN','100','Y');
INSERT INTO CO_STAFFS_ROSTER_POSITION (CO_SITE_CODE,CO_STAFF_ID,CO_STAFF_ROLE,CO_DEPARTMENT_CODE,CO_INCHARGE) 
        VALUES ('hkah','3933','RN','100','Y');
INSERT INTO CO_STAFFS_ROSTER_POSITION (CO_SITE_CODE,CO_STAFF_ID,CO_STAFF_ROLE,CO_DEPARTMENT_CODE,CO_INCHARGE) 
        VALUES ('hkah','3902','RN','100','Y');
INSERT INTO CO_STAFFS_ROSTER_POSITION (CO_SITE_CODE,CO_STAFF_ID,CO_STAFF_ROLE,CO_DEPARTMENT_CODE,CO_INCHARGE) 
        VALUES ('hkah','4070','RN','100','Y');
INSERT INTO CO_STAFFS_ROSTER_POSITION (CO_SITE_CODE,CO_STAFF_ID,CO_STAFF_ROLE,CO_DEPARTMENT_CODE,CO_INCHARGE) 
        VALUES ('hkah','4141','RN','100','Y');
INSERT INTO CO_STAFFS_ROSTER_POSITION (CO_SITE_CODE,CO_STAFF_ID,CO_STAFF_ROLE,CO_DEPARTMENT_CODE,CO_INCHARGE) 
        VALUES ('hkah','4154','RN','100','Y');
INSERT INTO CO_STAFFS_ROSTER_POSITION (CO_SITE_CODE,CO_STAFF_ID,CO_STAFF_ROLE,CO_DEPARTMENT_CODE,CO_INCHARGE) 
        VALUES ('hkah','4197','RN','100','Y');
INSERT INTO CO_STAFFS_ROSTER_POSITION (CO_SITE_CODE,CO_STAFF_ID,CO_STAFF_ROLE,CO_DEPARTMENT_CODE,CO_INCHARGE) 
        VALUES ('hkah','4210','RN','100','Y');
INSERT INTO CO_STAFFS_ROSTER_POSITION (CO_SITE_CODE,CO_STAFF_ID,CO_STAFF_ROLE,CO_DEPARTMENT_CODE,CO_INCHARGE) 
        VALUES ('hkah','4246','RN','100','Y');
INSERT INTO CO_STAFFS_ROSTER_POSITION (CO_SITE_CODE,CO_STAFF_ID,CO_STAFF_ROLE,CO_DEPARTMENT_CODE,CO_INCHARGE) 
        VALUES ('hkah','4315','RN','100','Y');
INSERT INTO CO_STAFFS_ROSTER_POSITION (CO_SITE_CODE,CO_STAFF_ID,CO_STAFF_ROLE,CO_DEPARTMENT_CODE,CO_INCHARGE) 
        VALUES ('hkah','4333','RN','100','Y');
INSERT INTO CO_STAFFS_ROSTER_POSITION (CO_SITE_CODE,CO_STAFF_ID,CO_STAFF_ROLE,CO_DEPARTMENT_CODE,CO_INCHARGE) 
        VALUES ('hkah','4526','RN','100','N');
INSERT INTO CO_STAFFS_ROSTER_POSITION (CO_SITE_CODE,CO_STAFF_ID,CO_STAFF_ROLE,CO_DEPARTMENT_CODE,CO_INCHARGE) 
        VALUES ('hkah','4758','RN','100','N');
INSERT INTO CO_STAFFS_ROSTER_POSITION (CO_SITE_CODE,CO_STAFF_ID,CO_STAFF_ROLE,CO_DEPARTMENT_CODE,CO_INCHARGE) 
        VALUES ('hkah','4355','RN','100','Y');
INSERT INTO CO_STAFFS_ROSTER_POSITION (CO_SITE_CODE,CO_STAFF_ID,CO_STAFF_ROLE,CO_DEPARTMENT_CODE,CO_INCHARGE) 
        VALUES ('hkah','4578','RN','100','N');
INSERT INTO CO_STAFFS_ROSTER_POSITION (CO_SITE_CODE,CO_STAFF_ID,CO_STAFF_ROLE,CO_DEPARTMENT_CODE,CO_INCHARGE) 
        VALUES ('hkah','4614','RN','100','N');
INSERT INTO CO_STAFFS_ROSTER_POSITION (CO_SITE_CODE,CO_STAFF_ID,CO_STAFF_ROLE,CO_DEPARTMENT_CODE,CO_INCHARGE) 
        VALUES ('hkah','4449','RN','100','N');
INSERT INTO CO_STAFFS_ROSTER_POSITION (CO_SITE_CODE,CO_STAFF_ID,CO_STAFF_ROLE,CO_DEPARTMENT_CODE,CO_INCHARGE) 
        VALUES ('hkah','4677','RN','100','N');
INSERT INTO CO_STAFFS_ROSTER_POSITION (CO_SITE_CODE,CO_STAFF_ID,CO_STAFF_ROLE,CO_DEPARTMENT_CODE,CO_INCHARGE) 
        VALUES ('hkah','3966','RN','100','N');
INSERT INTO CO_STAFFS_ROSTER_POSITION (CO_SITE_CODE,CO_STAFF_ID,CO_STAFF_ROLE,CO_DEPARTMENT_CODE,CO_INCHARGE) 
        VALUES ('hkah','3639','RN','100','N');
INSERT INTO CO_STAFFS_ROSTER_POSITION (CO_SITE_CODE,CO_STAFF_ID,CO_STAFF_ROLE,CO_DEPARTMENT_CODE,CO_INCHARGE) 
        VALUES ('hkah','3697','RN','100','N');
INSERT INTO CO_STAFFS_ROSTER_POSITION (CO_SITE_CODE,CO_STAFF_ID,CO_STAFF_ROLE,CO_DEPARTMENT_CODE,CO_INCHARGE) 
        VALUES ('hkah','3850','RN','100','N');
INSERT INTO CO_STAFFS_ROSTER_POSITION (CO_SITE_CODE,CO_STAFF_ID,CO_STAFF_ROLE,CO_DEPARTMENT_CODE,CO_INCHARGE) 
        VALUES ('hkah','4083','RN','100','N');
INSERT INTO CO_STAFFS_ROSTER_POSITION (CO_SITE_CODE,CO_STAFF_ID,CO_STAFF_ROLE,CO_DEPARTMENT_CODE,CO_INCHARGE) 
        VALUES ('hkah','4053','RN','100','N');
INSERT INTO CO_STAFFS_ROSTER_POSITION (CO_SITE_CODE,CO_STAFF_ID,CO_STAFF_ROLE,CO_DEPARTMENT_CODE,CO_INCHARGE) 
        VALUES ('hkah','4189','RN','100','N');
INSERT INTO CO_STAFFS_ROSTER_POSITION (CO_SITE_CODE,CO_STAFF_ID,CO_STAFF_ROLE,CO_DEPARTMENT_CODE,CO_INCHARGE) 
        VALUES ('hkah','4241','RN','100','N');
INSERT INTO CO_STAFFS_ROSTER_POSITION (CO_SITE_CODE,CO_STAFF_ID,CO_STAFF_ROLE,CO_DEPARTMENT_CODE,CO_INCHARGE) 
        VALUES ('hkah','4460','RN','100','N');
INSERT INTO CO_STAFFS_ROSTER_POSITION (CO_SITE_CODE,CO_STAFF_ID,CO_STAFF_ROLE,CO_DEPARTMENT_CODE,CO_INCHARGE) 
        VALUES ('hkah','4281','RN','100','N');
INSERT INTO CO_STAFFS_ROSTER_POSITION (CO_SITE_CODE,CO_STAFF_ID,CO_STAFF_ROLE,CO_DEPARTMENT_CODE,CO_INCHARGE) 
        VALUES ('hkah','4362','RN','100','N');
INSERT INTO CO_STAFFS_ROSTER_POSITION (CO_SITE_CODE,CO_STAFF_ID,CO_STAFF_ROLE,CO_DEPARTMENT_CODE,CO_INCHARGE) 
        VALUES ('hkah','4774','RN','100','N');
INSERT INTO CO_STAFFS_ROSTER_POSITION (CO_SITE_CODE,CO_STAFF_ID,CO_STAFF_ROLE,CO_DEPARTMENT_CODE,CO_INCHARGE) 
        VALUES ('hkah','4157','HCA','100','N');
INSERT INTO CO_STAFFS_ROSTER_POSITION (CO_SITE_CODE,CO_STAFF_ID,CO_STAFF_ROLE,CO_DEPARTMENT_CODE,CO_INCHARGE) 
        VALUES ('hkah','3444','HCA','100','N');
INSERT INTO CO_STAFFS_ROSTER_POSITION (CO_SITE_CODE,CO_STAFF_ID,CO_STAFF_ROLE,CO_DEPARTMENT_CODE,CO_INCHARGE) 
        VALUES ('hkah','4616','HCA','100','N');
INSERT INTO CO_STAFFS_ROSTER_POSITION (CO_SITE_CODE,CO_STAFF_ID,CO_STAFF_ROLE,CO_DEPARTMENT_CODE,CO_INCHARGE) 
        VALUES ('hkah','4742','HCA','100','N');
COMMIT;