ALTER TABLE CO_SESSION_LOGIN
 DROP PRIMARY KEY CASCADE;
DROP TABLE CO_SESSION_LOGIN CASCADE CONSTRAINTS;

CREATE TABLE CO_SESSION_LOGIN
(
 CO_SESSION_LOGIN_ID VARCHAR2(10 BYTE) NOT NULL,
 CO_EMAIL VARCHAR2(50 BYTE),
 CO_CREATED_DATE DATE DEFAULT SYSDATE,
 CO_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CO_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CO_SESSION_LOGIN_ID)
);