ALTER TABLE CO_TEMPLATE
 DROP PRIMARY KEY CASCADE;
DROP TABLE CO_TEMPLATE CASCADE CONSTRAINTS;

COMMIT;

CREATE TABLE CO_TEMPLATE
 (
    CO_SITE_CODE   		VARCHAR2(4 BYTE),
    CO_TEMPLATE_TYPE 	VARCHAR2(20 BYTE),
    CO_TEMPLATE_ID   	NUMBER NOT NULL ENABLE,
    CO_TEMPLATE_NAME 	VARCHAR2(50 BYTE),
    CO_DEFAULT_DISPLAY	VARCHAR2(10 BYTE) DEFAULT 'CATEGORY',
    CREATE_DATE 		DATE DEFAULT SYSDATE,
    CREATE_USER 		VARCHAR2(50 BYTE) DEFAULT 'SYSTEM',
    MODIFIED_DATE 		DATE DEFAULT SYSDATE,
    MODIFIED_USER 		VARCHAR2(50 BYTE) DEFAULT 'SYSTEM',
    ENABLE        		NUMBER(1,0) DEFAULT 1,
    PRIMARY KEY (CO_TEMPLATE_ID)
 );
 
COMMIT;

INSERT INTO CO_TEMPLATE(CO_SITE_CODE, CO_TEMPLATE_TYPE, CO_TEMPLATE_ID, 
						CO_TEMPLATE_NAME, CO_DEFAULT_DISPLAY) 
		VALUES('hkah', 'survey', '1', 'Health and Lifestyle Survey', 'PAGE');
		
COMMIT;