ALTER TABLE CO_TASK
 DROP PRIMARY KEY CASCADE;
DROP TABLE CO_TASK CASCADE CONSTRAINTS;

CREATE TABLE CO_TASK
(
 CO_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 CO_TASK_ID NUMBER(*,0) NOT NULL ENABLE,
 CO_TASK_NAME VARCHAR2(30 BYTE) NOT NULL,
 CO_FUNCTION_URL VARCHAR2(100 BYTE) NOT NULL,
 CO_JOB_NAME VARCHAR2(30 BYTE) NOT NULL,
 CO_CLASS_NAME VARCHAR2(30 BYTE) NULL,
 CO_CREATED_DATE DATE DEFAULT SYSDATE,
 CO_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CO_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CO_TASK_ID)
);
ALTER TABLE CO_TASK ADD (
 CONSTRAINT CO_TASK_R01
 FOREIGN KEY (CO_SITE_CODE)
 REFERENCES CO_SITE (CO_SITE_CODE));
INSERT INTO CO_TASK (CO_SITE_CODE, CO_TASK_ID, CO_TASK_NAME, CO_FUNCTION_URL, CO_JOB_NAME, CO_CLASS_NAME) VALUES ('hkah', 1, 'Class Schedule', '/education/class_enrollment.jsp', 'courseID', 'classID');
INSERT INTO CO_TASK (CO_SITE_CODE, CO_TASK_ID, CO_TASK_NAME, CO_FUNCTION_URL, CO_JOB_NAME, CO_CLASS_NAME) VALUES ('hkah', 2, 'E-Learning', '/education/elearning_test.jsp', 'elearningID', '');
INSERT INTO CO_TASK (CO_SITE_CODE, CO_TASK_ID, CO_TASK_NAME, CO_FUNCTION_URL, CO_JOB_NAME, CO_CLASS_NAME) VALUES ('hkah', 3, 'E-Leave', '/eleave/apply.jsp', 'eleaveID', '');
INSERT INTO CO_TASK (CO_SITE_CODE, CO_TASK_ID, CO_TASK_NAME, CO_FUNCTION_URL, CO_JOB_NAME, CO_CLASS_NAME) VALUES ('hkah', 4, 'Continuing Education', '/education/ce.jsp', 'ceID', '');