ALTER TABLE CO_TEMPLATE_RECORD
 DROP PRIMARY KEY CASCADE;
DROP TABLE CO_TEMPLATE_RECORD CASCADE CONSTRAINTS;

COMMIT;

CREATE TABLE CO_TEMPLATE_RECORD
(
	CO_REPORT_ID					NUMBER NOT NULL ENABLE,				
    CO_TEMPLATE_CONTENT_ID      	NUMBER NOT NULL ENABLE,
    CO_TEMPLATE_RECORD_ID			NUMBER NOT NULL ENABLE,
    CO_TEMPLATE_RECORD_GROUP		NUMBER NOT NULL ENABLE,
    CO_TEMPLATE_RECORD_VALUE		VARCHAR2(500 BYTE),
    CREATE_DATE 					DATE DEFAULT SYSDATE,
    CREATE_USER 					VARCHAR2(50 BYTE) DEFAULT 'SYSTEM',
    MODIFIED_DATE 					DATE DEFAULT SYSDATE,
    MODIFIED_USER 					VARCHAR2(50 BYTE) DEFAULT 'SYSTEM',
    ENABLE        					NUMBER(1,0) DEFAULT 1,
    PRIMARY KEY (CO_TEMPLATE_RECORD_ID)
);

COMMIT;

ALTER TABLE CO_TEMPLATE_RECORD ADD (
 CONSTRAINT CO_TEMPLATE_RECORD_FK1
 FOREIGN KEY (CO_TEMPLATE_CONTENT_ID)
 REFERENCES CO_TEMPLATE_CONTENT (CO_TEMPLATE_CONTENT_ID));
 
ALTER TABLE CO_TEMPLATE_RECORD ADD (
 CONSTRAINT CO_TEMPLATE_RECORD_FK2
 FOREIGN KEY (CO_REPORT_ID)
 REFERENCES CO_REPORT (CO_REPORT_ID));
 
COMMIT;