ALTER TABLE CO_TEMPLATE_CATEGORY
 DROP PRIMARY KEY CASCADE;
DROP TABLE CO_TEMPLATE_CATEGORY CASCADE CONSTRAINTS;

COMMIT;

CREATE TABLE CO_TEMPLATE_CATEGORY
(
    CO_TEMPLATE_ID            	NUMBER NOT NULL ENABLE,
    CO_TEMPLATE_CATEGORY_ID   	NUMBER NOT NULL ENABLE,
    CO_TEMPLATE_CATEGORY_NAME 	VARCHAR2(200 BYTE),
    CO_PARENT_ID            	NUMBER,
    CO_STYLE_COLUMN         	NUMBER,
    CO_IS_MULTI             	NUMBER(1,0),
    CO_ORDER                	NUMBER,
    CO_PAGE						NUMBER NOT NULL,
    CREATE_DATE 				DATE DEFAULT SYSDATE,
    CREATE_USER 				VARCHAR2(50 BYTE) DEFAULT 'SYSTEM',
    MODIFIED_DATE 				DATE DEFAULT SYSDATE,
    MODIFIED_USER 				VARCHAR2(50 BYTE) DEFAULT 'SYSTEM',
    ENABLE        				NUMBER(1,0) DEFAULT 1,
    PRIMARY KEY (CO_TEMPLATE_CATEGORY_ID) 
);

COMMIT;

ALTER TABLE CO_TEMPLATE_CATEGORY ADD (
 CONSTRAINT CO_TEMPLATE_CATEGORY_FK1
 FOREIGN KEY (CO_TEMPLATE_ID)
 REFERENCES CO_TEMPLATE (CO_TEMPLATE_ID));
 
COMMIT;

INSERT INTO CO_TEMPLATE_CATEGORY(CO_TEMPLATE_ID, CO_TEMPLATE_CATEGORY_ID, CO_TEMPLATE_CATEGORY_NAME,
					CO_PARENT_ID, CO_STYLE_COLUMN, CO_IS_MULTI, CO_ORDER, CO_PAGE)
		VALUES('1', '1', 'Basic Information', null, '4', '0', '1', '1');

INSERT INTO CO_TEMPLATE_CATEGORY(CO_TEMPLATE_ID, CO_TEMPLATE_CATEGORY_ID, CO_TEMPLATE_CATEGORY_NAME,
					CO_PARENT_ID, CO_STYLE_COLUMN, CO_IS_MULTI, CO_ORDER, CO_PAGE)
		VALUES('1', '2', 'Current and Past Health History', null, '1', '0', '2', '1');
		
INSERT INTO CO_TEMPLATE_CATEGORY(CO_TEMPLATE_ID, CO_TEMPLATE_CATEGORY_ID, CO_TEMPLATE_CATEGORY_NAME,
					CO_PARENT_ID, CO_STYLE_COLUMN, CO_IS_MULTI, CO_ORDER, CO_PAGE)
		VALUES('1', '3', 'Current Health Concerns', '2', '1', '0', '3', '1');
		
INSERT INTO CO_TEMPLATE_CATEGORY(CO_TEMPLATE_ID, CO_TEMPLATE_CATEGORY_ID, CO_TEMPLATE_CATEGORY_NAME,
					CO_PARENT_ID, CO_STYLE_COLUMN, CO_IS_MULTI, CO_ORDER, CO_PAGE)
		VALUES('1', '4', 'Current Medication', '2', '1', '0', '4', '1');

INSERT INTO CO_TEMPLATE_CATEGORY(CO_TEMPLATE_ID, CO_TEMPLATE_CATEGORY_ID, CO_TEMPLATE_CATEGORY_NAME,
					CO_PARENT_ID, CO_STYLE_COLUMN, CO_IS_MULTI, CO_ORDER, CO_PAGE)
		VALUES('1', '5', 'Allergies / Sensitivities', '2', '1', '0', '5', '1');

INSERT INTO CO_TEMPLATE_CATEGORY(CO_TEMPLATE_ID, CO_TEMPLATE_CATEGORY_ID, CO_TEMPLATE_CATEGORY_NAME,
					CO_PARENT_ID, CO_STYLE_COLUMN, CO_IS_MULTI, CO_ORDER, CO_PAGE)
		VALUES('1', '6', 'Lifestyle History', '2', '6', '0', '6', '2');

INSERT INTO CO_TEMPLATE_CATEGORY(CO_TEMPLATE_ID, CO_TEMPLATE_CATEGORY_ID, CO_TEMPLATE_CATEGORY_NAME,
					CO_PARENT_ID, CO_STYLE_COLUMN, CO_IS_MULTI, CO_ORDER, CO_PAGE)
		VALUES('1', '7', 'Past Health History', '2', '1', '0', '7', '2');
		
INSERT INTO CO_TEMPLATE_CATEGORY(CO_TEMPLATE_ID, CO_TEMPLATE_CATEGORY_ID, CO_TEMPLATE_CATEGORY_NAME,
					CO_PARENT_ID, CO_STYLE_COLUMN, CO_IS_MULTI, CO_ORDER, CO_PAGE)
		VALUES('1', '8', 'Immunizations', '2', '6', '0', '8', '3');
		
INSERT INTO CO_TEMPLATE_CATEGORY(CO_TEMPLATE_ID, CO_TEMPLATE_CATEGORY_ID, CO_TEMPLATE_CATEGORY_NAME,
					CO_PARENT_ID, CO_STYLE_COLUMN, CO_IS_MULTI, CO_ORDER, CO_PAGE)
		VALUES('1', '9', 'Family Health History', '2', '6', '0', '9', '3');

INSERT INTO CO_TEMPLATE_CATEGORY(CO_TEMPLATE_ID, CO_TEMPLATE_CATEGORY_ID, CO_TEMPLATE_CATEGORY_NAME,
					CO_PARENT_ID, CO_STYLE_COLUMN, CO_IS_MULTI, CO_ORDER, CO_PAGE)
		VALUES('1', '10', 'Body System Review', '2', '8', '0', '10', '4');
		
INSERT INTO CO_TEMPLATE_CATEGORY(CO_TEMPLATE_ID, CO_TEMPLATE_CATEGORY_ID, CO_TEMPLATE_CATEGORY_NAME,
					CO_PARENT_ID, CO_STYLE_COLUMN, CO_IS_MULTI, CO_ORDER, CO_PAGE)
		VALUES('1', '11', 'Gynecological History<br/><b>(FEMALE patients ONLY)</b>', '2', '5', '0', '11', '5');

INSERT INTO CO_TEMPLATE_CATEGORY(CO_TEMPLATE_ID, CO_TEMPLATE_CATEGORY_ID, CO_TEMPLATE_CATEGORY_NAME,
					CO_PARENT_ID, CO_STYLE_COLUMN, CO_IS_MULTI, CO_ORDER, CO_PAGE)
		VALUES('1', '12', 'Obstetrical History<br/><b>(FEMALE patients ONLY)</b>', '2', '2', '0', '12', '5');
		
COMMIT;