ALTER TABLE CRM_CAMPAIGN
 DROP PRIMARY KEY CASCADE;
DROP TABLE CRM_CAMPAIGN CASCADE CONSTRAINTS;

CREATE TABLE CRM_CAMPAIGN
(
 CRM_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 CRM_CAMPAIGN_ID NUMBER(*,0) DEFAULT 1,
 CRM_CAMPAIGN_DESC VARCHAR2(800 BYTE) NULL,
 CRM_CAMPAIGN_SHORT_DESC VARCHAR2(50 BYTE) NULL,
 CRM_CAMPAIGN_CATEGORY VARCHAR2(10 BYTE) NULL,
 CRM_CAMPAIGN_TYPE VARCHAR2(20 BYTE) NULL,
 CRM_CAMPAIGN_REMARK VARCHAR2(100 BYTE) NULL,
 CRM_CREATED_DATE DATE DEFAULT SYSDATE,
 CRM_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CRM_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CRM_CAMPAIGN_ID)
);
INSERT INTO CRM_CAMPAIGN (CRM_SITE_CODE, CRM_CAMPAIGN_ID, CRM_CAMPAIGN_DESC) VALUES ('hkah', 1, 'Campaign 1');
INSERT INTO CRM_CAMPAIGN (CRM_SITE_CODE, CRM_CAMPAIGN_ID, CRM_CAMPAIGN_DESC) VALUES ('hkah', 2, 'Campaign 2');
INSERT INTO CRM_CAMPAIGN (CRM_SITE_CODE, CRM_CAMPAIGN_ID, CRM_CAMPAIGN_DESC) VALUES ('hkah', 3, 'Campaign 3');
INSERT INTO CRM_CAMPAIGN (CRM_SITE_CODE, CRM_CAMPAIGN_ID, CRM_CAMPAIGN_DESC) VALUES ('hkah', 4, 'Campaign 4');
INSERT INTO CRM_CAMPAIGN (CRM_SITE_CODE, CRM_CAMPAIGN_ID, CRM_CAMPAIGN_DESC) VALUES ('hkah', 5, 'Campaign 5');