ALTER TABLE CRM_PARAMETER
 DROP PRIMARY KEY CASCADE;
DROP TABLE CRM_PARAMETER CASCADE CONSTRAINTS;

CREATE TABLE CRM_PARAMETER
(
 CRM_PARAMETER_TYPE VARCHAR2(20 BYTE) NOT NULL,
 CRM_PARAMETER_ID NUMBER(*,0) DEFAULT 1,
 CRM_PARAMETER_DESC VARCHAR2(100 BYTE) NULL,
 CRM_PARAMETER_LABEL VARCHAR2(20 BYTE) NULL,
 CRM_PARAMETER_PARENT_ID NUMBER(*,0) NULL,
 CRM_CREATED_DATE DATE DEFAULT SYSDATE,
 CRM_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CRM_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID)
);
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_LABEL) VALUES ('title', 1, 'label.mr');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_LABEL) VALUES ('title', 2, 'label.miss');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_LABEL) VALUES ('title', 3, 'label.ms');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_LABEL) VALUES ('title', 4, 'label.mrs');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_LABEL) VALUES ('title', 5, 'label.doctor');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_LABEL) VALUES ('title', 6, 'label.sir');

INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('religion', 1, 'Christian');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('religion', 2, 'Buddhism');

INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_LABEL) VALUES ('occupation', 01, 'label.administration');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_LABEL) VALUES ('occupation', 02, 'label.professionals');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_LABEL) VALUES ('occupation', 03, 'label.salesman');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_LABEL) VALUES ('occupation', 04, 'label.whiteCollar');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_LABEL) VALUES ('occupation', 05, 'label.blueCollar');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_LABEL) VALUES ('occupation', 06, 'label.selfEmployed');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_LABEL) VALUES ('occupation', 07, 'label.businessman');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_LABEL) VALUES ('occupation', 08, 'label.housewives');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_LABEL) VALUES ('occupation', 09, 'label.students');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_LABEL) VALUES ('occupation', 11, 'label.retired');

INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('activity', 1, 'Telephone Call');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('activity', 2, 'Follow Up');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('activity', 3, 'Material Sent');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('activity', 4, 'Event');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('activity', 5, 'Info Request');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('activity', 6, 'Promotion');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('activity', 7, 'Donation');

INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('country', 1, 'Hong Kong');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('country', 2, 'China');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('country', 3, 'Japan');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('country', 4, 'Taiwai');

INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_LABEL) VALUES ('area', 1, 'label.hongKongIsland');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_LABEL) VALUES ('area', 2, 'label.kowloon');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_LABEL) VALUES ('area', 3, 'label.newTerritories');

INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC, CRM_PARAMETER_PARENT_ID) VALUES ('district', 01, 'Central and Western', 1);
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC, CRM_PARAMETER_PARENT_ID) VALUES ('district', 02, 'Eastern District', 1);
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC, CRM_PARAMETER_PARENT_ID) VALUES ('district', 03, 'Southern District', 1);
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC, CRM_PARAMETER_PARENT_ID) VALUES ('district', 04, 'Wanchai District', 1);

INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC, CRM_PARAMETER_PARENT_ID) VALUES ('district', 05, 'Kowloon City', 2);
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC, CRM_PARAMETER_PARENT_ID) VALUES ('district', 06, 'Kwun Tong', 2);
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC, CRM_PARAMETER_PARENT_ID) VALUES ('district', 07, 'Sham Shui Po', 2);
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC, CRM_PARAMETER_PARENT_ID) VALUES ('district', 08, 'Wong Tai Sin', 2);
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC, CRM_PARAMETER_PARENT_ID) VALUES ('district', 09, 'Yau Tsim Mong', 2);

INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC, CRM_PARAMETER_PARENT_ID) VALUES ('district', 10, 'Kwai Tsing', 3);
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC, CRM_PARAMETER_PARENT_ID) VALUES ('district', 11, 'Tsuen Wan', 3);
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC, CRM_PARAMETER_PARENT_ID) VALUES ('district', 12, 'Tuen Mun', 3);
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC, CRM_PARAMETER_PARENT_ID) VALUES ('district', 13, 'Yuen Long', 3);
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC, CRM_PARAMETER_PARENT_ID) VALUES ('district', 14, 'Shatin', 3);
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC, CRM_PARAMETER_PARENT_ID) VALUES ('district', 15, 'Tai Po', 3);
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC, CRM_PARAMETER_PARENT_ID) VALUES ('district', 16, 'Northern NT', 3);
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC, CRM_PARAMETER_PARENT_ID) VALUES ('district', 17, 'Sai Kung', 3);
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC, CRM_PARAMETER_PARENT_ID) VALUES ('district', 18, 'Cheung Chau', 3);
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC, CRM_PARAMETER_PARENT_ID) VALUES ('district', 19, 'Lantau Island', 3);

INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_LABEL) VALUES ('education', 1, 'label.primarySchool');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_LABEL) VALUES ('education', 2, 'label.highSchool');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_LABEL) VALUES ('education', 3, 'label.college');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_LABEL) VALUES ('education', 4, 'label.university');

INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('ageGroup', 1, '0 - 10');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('ageGroup', 2, '11 - 20');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('ageGroup', 3, '21 - 30');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('ageGroup', 4, '31 - 40');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('ageGroup', 5, '41 - 50');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('ageGroup', 6, '51 - 60');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('ageGroup', 7, '61 or above');

INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('income', 1, 'below 10000');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('income', 2, '10001 - 20000');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('income', 3, '20001 - 30000');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('income', 4, '30001 - 40000');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('income', 5, '40001 - 50000');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('income', 6, '50001 - 60000');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('income', 7, '60001 or above');

INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('preferContactMethod', 1, 'Telephone');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('preferContactMethod', 2, 'In person');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('preferContactMethod', 3, 'By Mail');

INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('cardType', 1, 'Gold');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('cardType', 2, 'Platinum');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('cardType', 3, 'Normal');

INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('medical', 01, '中風');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('medical', 02, '心臟病');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('medical', 03, '心絞痛');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('medical', 04, '高血壓');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('medical', 05, '高膽固醇');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('medical', 06, '糖尿病');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('medical', 07, '腸胃病');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('medical', 08, '坐骨神經痛');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('medical', 09, '哮喘');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('medical', 10, '肺病');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('medical', 11, '癌症');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('medical', 12, '乳癌');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('medical', 13, '腸癌');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('medical', 14, '前列腺癌');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('medical', 15, '前列腺增生');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('medical', 17, '腎病');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('medical', 18, '尿道炎');

INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_LABEL) VALUES ('hobby', 0, 'label.others');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('hobby', 1, 'Badmonton');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('hobby', 2, 'Swimming');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('hobby', 3, 'Basket Ball');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('hobby', 4, 'Football');

INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('hospitalFacility', 01, '男士健康');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('hospitalFacility', 02, '女士健康');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('hospitalFacility', 03, '兒童健康');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('hospitalFacility', 04, '嬰兒護理');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('hospitalFacility', 05, '營養飲食');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('hospitalFacility', 06, '運動');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('hospitalFacility', 07, '體重控制');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('hospitalFacility', 08, '壓力控制');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('hospitalFacility', 09, '水療及推拿');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('hospitalFacility', 10, '糖尿病小組');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('hospitalFacility', 12, '素食烹飪班');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('hospitalFacility', 13, 'Cancer - weight');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('hospitalFacility', 14, 'Brest cancer');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('hospitalFacility', 15, 'Weight control  - women');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('hospitalFacility', 16, 'Heart');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('hospitalFacility', 17, 'DI');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('hospitalFacility', 18, 'Allergy');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('hospitalFacility', 19, 'Digestive problem');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('hospitalFacility', 20, 'Orth');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('hospitalFacility', 21, 'Urology');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('hospitalFacility', 22, 'Prenatal');

INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('materials', 1, '翠柏(長者)');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('materials', 2, '兒童課');
INSERT INTO CRM_PARAMETER (CRM_PARAMETER_TYPE, CRM_PARAMETER_ID, CRM_PARAMETER_DESC) VALUES ('materials', 3, '全人健康通訊');