ALTER TABLE CRM_PHYSICAL_FIGURE
 DROP PRIMARY KEY CASCADE;
DROP TABLE CRM_PHYSICAL_FIGURE CASCADE CONSTRAINTS;

CREATE TABLE CRM_PHYSICAL_FIGURE
(
 CRM_FIGURE_ID NUMBER(*,0) DEFAULT 1,
 CRM_FIGURE_DESC VARCHAR2(100 BYTE) NULL,
 CRM_FIGURE_DESC_CHI VARCHAR2(100 BYTE) NULL,
 CRM_FIGURE_MEASURE VARCHAR2(100 BYTE) NULL,
 CRM_FIGURE_MEASURE_CHI VARCHAR2(100 BYTE) NULL,
 CRM_FIGURE_TYPE VARCHAR2(10 BYTE) DEFAULT 'string',	-- string, boolean
 CRM_CREATED_DATE DATE DEFAULT SYSDATE,
 CRM_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CRM_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CRM_FIGURE_ID)
);
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (01, 'Height', '高度', '', 'm', 'string');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (02, 'Weight', '體重', '', 'Kg', 'string');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (03, 'Blood Up', '血壓 (上)', '', 'mm Hg', 'string');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (04, 'Blood Down', '血壓 (下)', '', 'mm Hg', 'string');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (05, 'Body Fat', '體脂', '', '%', 'string');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (06, 'Waist', '腰', '', '', 'string');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (07, 'Hip', '臀', '', '', 'string');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (08, 'Urine Glucose', '尿糖', '', 've', 'string');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (09, 'Blood Glucose', '血糖', '', 'mmo/l', 'string');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (10, 'Diabetes', '糖尿病', '', 'mmol/L', 'string');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (11, 'Cholesterol', '膽固醇', '', 'mmol/L', 'string');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (12, 'Smoking', '吸煙', '', '日/枝', 'string');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (13, 'Exercies', '運動', '', '分鐘/日', 'string');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (14, 'Family HD', '家庭病歷', '', '', 'string');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (15, 'Character', '性格', '', '', 'string');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (16, 'Soft', '柔軟度', '', 'cm', 'string');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (17, 'Step', '踏步測試', '', '/分', 'string');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (18, 'Grapple', '手握力', '', '', 'string');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (19, 'One Mile', '一公里測試', '', '', 'string');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (20, '', 'A Total', '', '', 'string');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (21, '', '食慾不振', '', '', 'boolean');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (22, '', '體重下降', '', '', 'boolean');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (23, '', '胃氣脹', '', '', 'boolean');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (24, '', '氣谷', '', '', 'boolean');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (25, '', '胃酸過多', '', '', 'boolean');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (26, '', '出血', '', '', 'boolean');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (27, '', '腹痛', '', '', 'boolean');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (28, '', '大便習慣', '', '', 'boolean');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (29, '', '便後急', '', '', 'boolean');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (30, '', '黏性大便', '', '', 'boolean');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (31, '', '大便焦黑', '', '', 'boolean');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (32, '', '大便出血', '', '', 'boolean');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (33, '', 'IPSS', '', '', 'string');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (34, '', 'IPSS 評分', '', '', 'string');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (35, '', '生活質數', '', '', 'boolean');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (36, '', '末尾滴尿', '', '', 'boolean');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (37, '', '尿道痛', '', '', 'boolean');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (38, '', '血尿', '', '', 'boolean');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (39, '', '尿混濁', '', '', 'boolean');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (40, '', '尿失禁', '', '', 'boolean');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (41, '', '腹部及陰囊腫塊', '', '', 'boolean');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (42, '', '精血', '', '', 'boolean');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (43, '', '尿道石', '', '', 'boolean');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (44, '', '腰痛', '', '', 'boolean');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (45, '', '下腹疼痛', '', '', 'boolean');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (46, '', '骨痛', '', '', 'boolean');

INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (51, 'Height', '身高', '', 'mm', 'string');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (52, 'Weight', '體重', '', 'lb', 'string');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (53, '', '體脂', '', '', 'string');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (54, '', '癌症', '', '', 'boolean');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (55, '', '高血壓', '', '', 'boolean');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (56, '', '糖尿病', '', '', 'boolean');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (57, '', '心臟病', '', '', 'boolean');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (58, '', '心絞痛', '', '', 'boolean');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (59, '', '高膽固醇', '', '', 'boolean');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (60, '', '哮喘', '', '', 'boolean');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (61, '', '中風', '', '', 'boolean');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (62, '', '肺病', '', '', 'boolean');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (63, '', '脊椎毛病', '', '', 'boolean');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (64, '', '滕蓋毛病', '', '', 'boolean');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (65, '', '坐骨神經痛', '', '', 'boolean');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (66, '', '抑鬱症', '', '', 'boolean');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (67, '', '其他病症', '', '', 'string');
INSERT INTO CRM_PHYSICAL_FIGURE (CRM_FIGURE_ID, CRM_FIGURE_DESC, CRM_FIGURE_DESC_CHI, CRM_FIGURE_MEASURE, CRM_FIGURE_MEASURE_CHI, CRM_FIGURE_TYPE) VALUES (68, '', '長期藥物', '', '', 'string');