ALTER TABLE CRM_QUESTIONAIRE_QUESTION
 DROP PRIMARY KEY CASCADE;
DROP TABLE CRM_QUESTIONAIRE_QUESTION CASCADE CONSTRAINTS;

CREATE TABLE CRM_QUESTIONAIRE_QUESTION
(
 CRM_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 CRM_QUESTIONAIRE_ID NUMBER(*,0) NOT NULL ENABLE,
 CRM_QUESTIONAIRE_QID NUMBER(*,0) NOT NULL ENABLE,
 CRM_QUESTION VARCHAR2(200 BYTE),
 CRM_CREATED_DATE DATE DEFAULT SYSDATE,
 CRM_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CRM_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID)
);
ALTER TABLE CRM_QUESTIONAIRE_QUESTION ADD (
 CONSTRAINT CRM_QUESTIONAIRE_QUESTION_R01
 FOREIGN KEY (CRM_SITE_CODE, CRM_QUESTIONAIRE_ID)
 REFERENCES CRM_QUESTIONAIRE (CRM_SITE_CODE, CRM_QUESTIONAIRE_ID));
INSERT INTO CRM_QUESTIONAIRE_QUESTION(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTION) VALUES ('hkah', 1, 1, 'Question 1.');
INSERT INTO CRM_QUESTIONAIRE_QUESTION(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTION) VALUES ('hkah', 1, 2, 'Question 2.');
INSERT INTO CRM_QUESTIONAIRE_QUESTION(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTION) VALUES ('hkah', 1, 3, 'Question 3.');
INSERT INTO CRM_QUESTIONAIRE_QUESTION(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTION) VALUES ('hkah', 1, 4, 'Question 4.');
INSERT INTO CRM_QUESTIONAIRE_QUESTION(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTION) VALUES ('hkah', 1, 5, 'Question 5.');
INSERT INTO CRM_QUESTIONAIRE_QUESTION(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTION) VALUES ('hkah', 2, 1, 'Question 1.');
INSERT INTO CRM_QUESTIONAIRE_QUESTION(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTION) VALUES ('hkah', 2, 2, 'Question 2.');
INSERT INTO CRM_QUESTIONAIRE_QUESTION(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTION) VALUES ('hkah', 2, 3, 'Question 3.');
INSERT INTO CRM_QUESTIONAIRE_QUESTION(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTION) VALUES ('hkah', 2, 4, 'Question 4.');
INSERT INTO CRM_QUESTIONAIRE_QUESTION(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTION) VALUES ('hkah', 2, 5, 'Question 5.');
INSERT INTO CRM_QUESTIONAIRE_QUESTION(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTION) VALUES ('hkah', 3, 1, 'Question 1.');
INSERT INTO CRM_QUESTIONAIRE_QUESTION(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTION) VALUES ('hkah', 3, 2, 'Question 2.');
INSERT INTO CRM_QUESTIONAIRE_QUESTION(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTION) VALUES ('hkah', 3, 3, 'Question 3.');
INSERT INTO CRM_QUESTIONAIRE_QUESTION(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTION) VALUES ('hkah', 3, 4, 'Question 4.');
INSERT INTO CRM_QUESTIONAIRE_QUESTION(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTION) VALUES ('hkah', 3, 5, 'Question 5.');
INSERT INTO CRM_QUESTIONAIRE_QUESTION(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTION) VALUES ('hkah', 4, 1, 'Question 1.');
INSERT INTO CRM_QUESTIONAIRE_QUESTION(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTION) VALUES ('hkah', 4, 2, 'Question 2.');
INSERT INTO CRM_QUESTIONAIRE_QUESTION(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTION) VALUES ('hkah', 4, 3, 'Question 3.');
INSERT INTO CRM_QUESTIONAIRE_QUESTION(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTION) VALUES ('hkah', 4, 4, 'Question 4.');
INSERT INTO CRM_QUESTIONAIRE_QUESTION(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTION) VALUES ('hkah', 4, 5, 'Question 5.');
INSERT INTO CRM_QUESTIONAIRE_QUESTION(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTION) VALUES ('hkah', 5, 1, 'Question 1.');
INSERT INTO CRM_QUESTIONAIRE_QUESTION(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTION) VALUES ('hkah', 5, 2, 'Question 2.');
INSERT INTO CRM_QUESTIONAIRE_QUESTION(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTION) VALUES ('hkah', 5, 3, 'Question 3.');
INSERT INTO CRM_QUESTIONAIRE_QUESTION(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTION) VALUES ('hkah', 5, 4, 'Question 4.');
INSERT INTO CRM_QUESTIONAIRE_QUESTION(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_QID, CRM_QUESTION) VALUES ('hkah', 5, 5, 'Question 5.');
