ALTER TABLE CRM_PHYSICAL_FIGURE_GROUP
 DROP PRIMARY KEY CASCADE;
DROP TABLE CRM_PHYSICAL_FIGURE_GROUP CASCADE CONSTRAINTS;

CREATE TABLE CRM_PHYSICAL_FIGURE_GROUP
(
 CRM_FIGURE_GROUP_ID NUMBER(*,0) DEFAULT 1,
 CRM_FIGURE_GROUP_DESC VARCHAR2(100 BYTE) NULL,
 CRM_CREATED_DATE DATE DEFAULT SYSDATE,
 CRM_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CRM_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CRM_FIGURE_GROUP_ID)
);

INSERT INTO CRM_PHYSICAL_FIGURE_GROUP (CRM_FIGURE_GROUP_ID, CRM_FIGURE_GROUP_DESC) VALUES (1, 'Standard');
INSERT INTO CRM_PHYSICAL_FIGURE_GROUP (CRM_FIGURE_GROUP_ID, CRM_FIGURE_GROUP_DESC) VALUES (2, 'Digest');
INSERT INTO CRM_PHYSICAL_FIGURE_GROUP (CRM_FIGURE_GROUP_ID, CRM_FIGURE_GROUP_DESC) VALUES (3, 'IPSS');
INSERT INTO CRM_PHYSICAL_FIGURE_GROUP (CRM_FIGURE_GROUP_ID, CRM_FIGURE_GROUP_DESC) VALUES (4, 'Newstart');