ALTER TABLE CRM_CLUBS
 DROP PRIMARY KEY CASCADE;
DROP TABLE CRM_CLUBS CASCADE CONSTRAINTS;

CREATE TABLE CRM_CLUBS
(
 CRM_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 CRM_CLUB_ID NUMBER(*,0) NOT NULL ENABLE,
 CRM_CLUB_DESC VARCHAR2(100 BYTE) NOT NULL,
 CRM_CREATED_DATE DATE DEFAULT SYSDATE,
 CRM_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CRM_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CRM_CLUB_ID)
);
ALTER TABLE CRM_CLUBS ADD (
 CONSTRAINT CRM_CLUBS_R01
 FOREIGN KEY (CRM_SITE_CODE)
 REFERENCES CRM_SITE (CRM_SITE_CODE));