ALTER TABLE CRM_CLIENTS_PHYSICAL
 DROP PRIMARY KEY CASCADE;
DROP TABLE CRM_CLIENTS_PHYSICAL CASCADE CONSTRAINTS;

CREATE TABLE CRM_CLIENTS_PHYSICAL
(
 CRM_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 CRM_MODULE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,	-- education, lmc
 CRM_EVENT_ID NUMBER(*,0) NOT NULL ENABLE,
 CRM_SCHEDULE_ID NUMBER(*,0) NOT NULL,
 CRM_USER_TYPE VARCHAR2(10 BYTE) NOT NULL,	-- staff, patient
 CRM_USER_ID VARCHAR2(20 BYTE) NOT NULL,
 CRM_FIGURE_ID NUMBER(*,0) NULL,
 CRM_FIGURE_VALUE VARCHAR2(100 BYTE) NULL,
 CRM_CREATED_DATE DATE DEFAULT SYSDATE,
 CRM_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CRM_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CRM_SITE_CODE, CRM_MODULE_CODE, CRM_EVENT_ID, CRM_SCHEDULE_ID, CRM_USER_TYPE, CRM_USER_ID, CRM_FIGURE_ID)
);
ALTER TABLE CRM_CLIENTS_PHYSICAL ADD (
 CONSTRAINT CRM_CLIENTS_PHYSICAL_R01
 FOREIGN KEY (CRM_SITE_CODE, CRM_MODULE_CODE, CRM_EVENT_ID, CRM_SCHEDULE_ID)
 REFERENCES CO_SCHEDULE (CO_SITE_CODE, CO_MODULE_CODE, CO_EVENT_ID, CO_SCHEDULE_ID));