ALTER TABLE CRM_QUESTIONAIRE
 DROP PRIMARY KEY CASCADE;
DROP TABLE CRM_QUESTIONAIRE CASCADE CONSTRAINTS;

CREATE TABLE CRM_QUESTIONAIRE
(
 CRM_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 CRM_QUESTIONAIRE_ID NUMBER(*,0) NOT NULL ENABLE,
 CRM_QUESTIONAIRE_DESC VARCHAR2(100 BYTE),
 CRM_DOCUMENT_ID NUMBER(*,0) NULL,
 CRM_CREATED_DATE DATE DEFAULT SYSDATE,
 CRM_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CRM_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CRM_SITE_CODE, CRM_QUESTIONAIRE_ID)
);
ALTER TABLE CRM_QUESTIONAIRE ADD (
 CONSTRAINT CRM_QUESTIONAIRE_R01
 FOREIGN KEY (CRM_SITE_CODE)
 REFERENCES CRM_INSTITUTION (CRM_SITE_CODE));
INSERT INTO CRM_QUESTIONAIRE(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_DESC, CRM_DOCUMENT_ID) VALUES ('hkah', 1, 'Questionaire 1', 1 );
INSERT INTO CRM_QUESTIONAIRE(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_DESC, CRM_DOCUMENT_ID) VALUES ('hkah', 2, 'Questionaire 2', 1 );
INSERT INTO CRM_QUESTIONAIRE(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_DESC, CRM_DOCUMENT_ID) VALUES ('hkah', 3, 'Questionaire 3', 1 );
INSERT INTO CRM_QUESTIONAIRE(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_DESC, CRM_DOCUMENT_ID) VALUES ('hkah', 4, 'Questionaire 4', 1 );
INSERT INTO CRM_QUESTIONAIRE(CRM_SITE_CODE, CRM_QUESTIONAIRE_ID, CRM_QUESTIONAIRE_DESC, CRM_DOCUMENT_ID) VALUES ('hkah', 5, 'Questionaire 5', 1 );