ALTER TABLE CRM_TARGET
 DROP PRIMARY KEY CASCADE;
DROP TABLE CRM_TARGET CASCADE CONSTRAINTS;

CREATE TABLE CRM_TARGET
(
 CRM_TARGET_ID NUMBER(*,0) NOT NULL ENABLE,
 CRM_TARGET_CODE VARCHAR2(10 BYTE),
 CRM_TARGET_NAME VARCHAR2(200 BYTE),
 CRM_TARGET_DESCRIPTION VARCHAR2(200 BYTE),
 CRM_CREATED_DATE DATE DEFAULT SYSDATE,
 CRM_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CRM_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CRM_TARGET_ID)
);

INSERT INTO CRM_TARGET(CRM_TARGET_ID, CRM_TARGET_NAME, CRM_TARGET_DESCRIPTION) VALUES(1, 'AE', 'American Express');
INSERT INTO CRM_TARGET(CRM_TARGET_ID, CRM_TARGET_NAME, CRM_TARGET_DESCRIPTION) VALUES(2, 'HSBC', 'HSBC Credit Card');
INSERT INTO CRM_TARGET(CRM_TARGET_ID, CRM_TARGET_NAME, CRM_TARGET_DESCRIPTION) VALUES(3, 'SCB', 'Standard Chartered Bank');
INSERT INTO CRM_TARGET(CRM_TARGET_ID, CRM_TARGET_NAME, CRM_TARGET_DESCRIPTION) VALUES(4, 'BOC', 'Bank of China');
INSERT INTO CRM_TARGET(CRM_TARGET_ID, CRM_TARGET_NAME, CRM_TARGET_DESCRIPTION) VALUES(5, 'Manhattan', 'Manhattan');
INSERT INTO CRM_TARGET(CRM_TARGET_ID, CRM_TARGET_NAME, CRM_TARGET_DESCRIPTION) VALUES(6, 'AIG', null);
INSERT INTO CRM_TARGET(CRM_TARGET_ID, CRM_TARGET_NAME, CRM_TARGET_DESCRIPTION) VALUES(7, 'Citibank', 'Citibank International');
INSERT INTO CRM_TARGET(CRM_TARGET_ID, CRM_TARGET_NAME, CRM_TARGET_DESCRIPTION) VALUES(8, 'DBS', 'DBS Bank HK Ltd');
INSERT INTO CRM_TARGET(CRM_TARGET_ID, CRM_TARGET_NAME, CRM_TARGET_DESCRIPTION) VALUES(9, 'Diners', 'Diners Card');
INSERT INTO CRM_TARGET(CRM_TARGET_ID, CRM_TARGET_NAME, CRM_TARGET_DESCRIPTION) VALUES(10, 'Hang Seng', 'Hang Seng Bank');
INSERT INTO CRM_TARGET(CRM_TARGET_ID, CRM_TARGET_NAME, CRM_TARGET_DESCRIPTION) VALUES(11, 'AE Centurion', 'American Express Centurion Card');
INSERT INTO CRM_TARGET(CRM_TARGET_ID, CRM_TARGET_NAME, CRM_TARGET_DESCRIPTION) VALUES(12, 'AE Platinum', 'American Express Platinum Card');
INSERT INTO CRM_TARGET(CRM_TARGET_ID, CRM_TARGET_NAME, CRM_TARGET_DESCRIPTION) VALUES(13, 'Selective Clients', 'Selective Clients');
INSERT INTO CRM_TARGET(CRM_TARGET_ID, CRM_TARGET_NAME, CRM_TARGET_DESCRIPTION) VALUES(14, 'Staff/dependent', null);
INSERT INTO CRM_TARGET(CRM_TARGET_ID, CRM_TARGET_NAME, CRM_TARGET_DESCRIPTION) VALUES(15, 'SCB Inifinite Visa', 'Standard Chartered Infinite Visa Card');
INSERT INTO CRM_TARGET(CRM_TARGET_ID, CRM_TARGET_NAME, CRM_TARGET_DESCRIPTION) VALUES(16, 'Ind Bank', 'Industrial Bank Platunum Credit Card');
INSERT INTO CRM_TARGET(CRM_TARGET_ID, CRM_TARGET_NAME, CRM_TARGET_DESCRIPTION) VALUES(17, 'General Patients', null);
INSERT INTO CRM_TARGET(CRM_TARGET_ID, CRM_TARGET_NAME, CRM_TARGET_DESCRIPTION) VALUES(18, 'General Patient', null);
INSERT INTO CRM_TARGET(CRM_TARGET_ID, CRM_TARGET_NAME, CRM_TARGET_DESCRIPTION) VALUES(19, 'Evangelism meeting-seminar Gift holder', 'Seminar Gift Record holder');
