ALTER TABLE CRM_EXPORT_COLUMN
 DROP PRIMARY KEY CASCADE;
DROP TABLE CRM_EXPORT_COLUMN CASCADE CONSTRAINTS;

CREATE TABLE CRM_EXPORT_COLUMN
(
 CRM_EXPORT_COLUMN_ID VARCHAR2(50 BYTE) NOT NULL,
 CRM_EXPORT_COLUMN_LABEL VARCHAR2(50 BYTE) NOT NULL,
 CRM_CREATED_DATE DATE DEFAULT SYSDATE,
 CRM_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CRM_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CRM_EXPORT_COLUMN_ID)
);
INSERT INTO CRM_EXPORT_COLUMN (CRM_EXPORT_COLUMN_ID, CRM_EXPORT_COLUMN_LABEL) VALUES ('CRM_SITE_CODE',                'site_code');
INSERT INTO CRM_EXPORT_COLUMN (CRM_EXPORT_COLUMN_ID, CRM_EXPORT_COLUMN_LABEL) VALUES ('CRM_LASTNAME',                 'lastname');
INSERT INTO CRM_EXPORT_COLUMN (CRM_EXPORT_COLUMN_ID, CRM_EXPORT_COLUMN_LABEL) VALUES ('CRM_FIRSTNAME',                'firstname');
INSERT INTO CRM_EXPORT_COLUMN (CRM_EXPORT_COLUMN_ID, CRM_EXPORT_COLUMN_LABEL) VALUES ('CRM_CHINESENAME',              'chinesename');
INSERT INTO CRM_EXPORT_COLUMN (CRM_EXPORT_COLUMN_ID, CRM_EXPORT_COLUMN_LABEL) VALUES ('CRM_TITLE',                    'title');
INSERT INTO CRM_EXPORT_COLUMN (CRM_EXPORT_COLUMN_ID, CRM_EXPORT_COLUMN_LABEL) VALUES ('CRM_RELIGION',                 'regligion');
INSERT INTO CRM_EXPORT_COLUMN (CRM_EXPORT_COLUMN_ID, CRM_EXPORT_COLUMN_LABEL) VALUES ('CRM_SEX',                      'sex');
INSERT INTO CRM_EXPORT_COLUMN (CRM_EXPORT_COLUMN_ID, CRM_EXPORT_COLUMN_LABEL) VALUES ('CRM_DOB_YY',                   'dob_yyr');
INSERT INTO CRM_EXPORT_COLUMN (CRM_EXPORT_COLUMN_ID, CRM_EXPORT_COLUMN_LABEL) VALUES ('CRM_DOB_MM',                   'dob_mm');
INSERT INTO CRM_EXPORT_COLUMN (CRM_EXPORT_COLUMN_ID, CRM_EXPORT_COLUMN_LABEL) VALUES ('CRM_DOB_DD',                   'dob_dd');
INSERT INTO CRM_EXPORT_COLUMN (CRM_EXPORT_COLUMN_ID, CRM_EXPORT_COLUMN_LABEL) VALUES ('CRM_DECEASE_YY',               'decease_yy');
INSERT INTO CRM_EXPORT_COLUMN (CRM_EXPORT_COLUMN_ID, CRM_EXPORT_COLUMN_LABEL) VALUES ('CRM_DECEASE_MM',               'decease_mm');
INSERT INTO CRM_EXPORT_COLUMN (CRM_EXPORT_COLUMN_ID, CRM_EXPORT_COLUMN_LABEL) VALUES ('CRM_DECEASE_DD',               'decease_dd');
INSERT INTO CRM_EXPORT_COLUMN (CRM_EXPORT_COLUMN_ID, CRM_EXPORT_COLUMN_LABEL) VALUES ('CRM_AGE_GROUP',                'age_group');
INSERT INTO CRM_EXPORT_COLUMN (CRM_EXPORT_COLUMN_ID, CRM_EXPORT_COLUMN_LABEL) VALUES ('CRM_EDUCATION_LEVEL',          'education_level');
INSERT INTO CRM_EXPORT_COLUMN (CRM_EXPORT_COLUMN_ID, CRM_EXPORT_COLUMN_LABEL) VALUES ('CRM_OCCUPATION',               'occupation');
INSERT INTO CRM_EXPORT_COLUMN (CRM_EXPORT_COLUMN_ID, CRM_EXPORT_COLUMN_LABEL) VALUES ('CRM_HKID',                     'hkid');
INSERT INTO CRM_EXPORT_COLUMN (CRM_EXPORT_COLUMN_ID, CRM_EXPORT_COLUMN_LABEL) VALUES ('CRM_PASSPORT',                 'passport');
INSERT INTO CRM_EXPORT_COLUMN (CRM_EXPORT_COLUMN_ID, CRM_EXPORT_COLUMN_LABEL) VALUES ('CRM_STREET1',                  'street1');
INSERT INTO CRM_EXPORT_COLUMN (CRM_EXPORT_COLUMN_ID, CRM_EXPORT_COLUMN_LABEL) VALUES ('CRM_STREET2',                  'street2');
INSERT INTO CRM_EXPORT_COLUMN (CRM_EXPORT_COLUMN_ID, CRM_EXPORT_COLUMN_LABEL) VALUES ('CRM_STREET3',                  'street3');
INSERT INTO CRM_EXPORT_COLUMN (CRM_EXPORT_COLUMN_ID, CRM_EXPORT_COLUMN_LABEL) VALUES ('CRM_LOCATION',                 'location');
INSERT INTO CRM_EXPORT_COLUMN (CRM_EXPORT_COLUMN_ID, CRM_EXPORT_COLUMN_LABEL) VALUES ('CRM_DISTRICT',                 'district');
INSERT INTO CRM_EXPORT_COLUMN (CRM_EXPORT_COLUMN_ID, CRM_EXPORT_COLUMN_LABEL) VALUES ('CRM_COUNTRY',                  'country');
INSERT INTO CRM_EXPORT_COLUMN (CRM_EXPORT_COLUMN_ID, CRM_EXPORT_COLUMN_LABEL) VALUES ('CRM_LANGUAGE',                 'language');
INSERT INTO CRM_EXPORT_COLUMN (CRM_EXPORT_COLUMN_ID, CRM_EXPORT_COLUMN_LABEL) VALUES ('CRM_HOME_NUMBER',              'home_number');
INSERT INTO CRM_EXPORT_COLUMN (CRM_EXPORT_COLUMN_ID, CRM_EXPORT_COLUMN_LABEL) VALUES ('CRM_OFFICE_NUMBER',            'office_number');
INSERT INTO CRM_EXPORT_COLUMN (CRM_EXPORT_COLUMN_ID, CRM_EXPORT_COLUMN_LABEL) VALUES ('CRM_MOBILE_NUMBER',            'mobile_number');
INSERT INTO CRM_EXPORT_COLUMN (CRM_EXPORT_COLUMN_ID, CRM_EXPORT_COLUMN_LABEL) VALUES ('CRM_FAX_NUMBER',               'fax_number');
INSERT INTO CRM_EXPORT_COLUMN (CRM_EXPORT_COLUMN_ID, CRM_EXPORT_COLUMN_LABEL) VALUES ('CRM_EMAIL',                    'email');
INSERT INTO CRM_EXPORT_COLUMN (CRM_EXPORT_COLUMN_ID, CRM_EXPORT_COLUMN_LABEL) VALUES ('CRM_EMERGENCY_CONTACT_PERSON', 'emergency_contact_person');
INSERT INTO CRM_EXPORT_COLUMN (CRM_EXPORT_COLUMN_ID, CRM_EXPORT_COLUMN_LABEL) VALUES ('CRM_EMERGENCY_CONTACT_NUMBER', 'emergency_contact_number');
INSERT INTO CRM_EXPORT_COLUMN (CRM_EXPORT_COLUMN_ID, CRM_EXPORT_COLUMN_LABEL) VALUES ('CRM_FACEBOOK',                 'facebook');
INSERT INTO CRM_EXPORT_COLUMN (CRM_EXPORT_COLUMN_ID, CRM_EXPORT_COLUMN_LABEL) VALUES ('CRM_INCOME',                   'income');
INSERT INTO CRM_EXPORT_COLUMN (CRM_EXPORT_COLUMN_ID, CRM_EXPORT_COLUMN_LABEL) VALUES ('CRM_WILLING_PROMOTION',        'willing_promotion');
INSERT INTO CRM_EXPORT_COLUMN (CRM_EXPORT_COLUMN_ID, CRM_EXPORT_COLUMN_LABEL) VALUES ('CRM_PREFER_CONTACT_METHOD',    'prefer_contact_method');