CREATE TABLE "CRM_QUESTIONAIRE_CLIENT_ANSWER"
  (
    "CRM_SITE_CODE"        VARCHAR2(10 BYTE) NOT NULL ENABLE,
    "CRM_QUESTIONAIRE_ID"  NUMBER NOT NULL ENABLE,
    "CRM_QUESTIONAIRE_QID" NUMBER NOT NULL ENABLE,
    "CRM_QUESTIONAIRE_AID" NUMBER NOT NULL ENABLE,
    "CRM_USERNAME"         VARCHAR2(20 BYTE),
    "CRM_CREATED_DATE" DATE DEFAULT SYSDATE,
    "CRM_CREATED_USER" VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
    "CRM_MODIFIED_DATE" DATE DEFAULT SYSDATE,
    "CRM_MODIFIED_USER"     VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
    "CRM_ENABLED"           NUMBER DEFAULT 1,
    "CRM_QUESTIONAIRE_CAID" NUMBER NOT NULL ENABLE
  );