ALTER TABLE CRM_CLIENTS_DONATION_RECEIPT
 DROP PRIMARY KEY CASCADE;
DROP TABLE CRM_CLIENTS_DONATION_RECEIPT CASCADE CONSTRAINTS;

CREATE TABLE CRM_CLIENTS_DONATION_RECEIPT
(
 CRM_RECEIPT_ID VARCHAR2(10 BYTE) NOT NULL ENABLE,
 CRM_CLIENT_ID NUMBER(*,0) DEFAULT 1,
 CRM_DONATION_ID NUMBER(*,0) DEFAULT 1,
 CRM_RECEIPT_LASTNAME VARCHAR2(30 BYTE) NULL,
 CRM_RECEIPT_FIRSTNAME VARCHAR2(60 BYTE) NULL,
 CRM_RECEIPT_CURR VARCHAR2(100 BYTE) NULL,
 CRM_RECEIPT_AMOUNT NUMBER(*,2) DEFAULT 0,
 CRM_RECEIPT_DATE DATE DEFAULT SYSDATE,
 CRM_CREATED_DATE DATE DEFAULT SYSDATE,
 CRM_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CRM_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_ENABLED NUMBER(*,0) DEFAULT 1,
 CRM_RECEIPT_ITEM VARCHAR2(100 BYTE) NULL,
 CRM_PRINT_DATE DATE NULL,
 PRIMARY KEY (CRM_RECEIPT_ID)
);
ALTER TABLE CRM_CLIENTS_DONATION_RECEIPT ADD (
 CONSTRAINT CRM_CLIENTS_DONATION_RECEIPT_R01
 FOREIGN KEY (CRM_CLIENT_ID, CRM_DONATION_ID)
 REFERENCES CRM_CLIENTS_DONATION (CRM_CLIENT_ID, CRM_DONATION_ID));