ALTER TABLE CRM_CLIENTS_NEWSTART
 DROP PRIMARY KEY CASCADE;
DROP TABLE CRM_CLIENTS_NEWSTART CASCADE CONSTRAINTS;

COMMIT;

CREATE TABLE CRM_CLIENTS_NEWSTART
(
	CRM_NS_ID         NUMBER NOT NULL ENABLE,
    CRM_USERNAME      VARCHAR2(20 BYTE),
    CRM_NS_NUTRITION  VARCHAR2(20 BYTE),
    CRM_NS_EXERCISE   VARCHAR2(20 BYTE),
    CRM_NS_WATER      VARCHAR2(20 BYTE),
    CRM_NS_SUNLIGHT   VARCHAR2(20 BYTE),
    CRM_NS_TEMPERANCE VARCHAR2(20 BYTE),
    CRM_NS_AIR        VARCHAR2(20 BYTE),
    CRM_NS_REST       VARCHAR2(20 BYTE),
    CRM_NS_TRUST      VARCHAR2(20 BYTE),
    CRM_NS_ENABLED       NUMBER DEFAULT 1,
    CRM_NS_TOTAL         VARCHAR2(20 BYTE),
    CRM_NS_LEVEL         VARCHAR2(20 BYTE),
    CRM_NS_CREATED_DATE DATE DEFAULT SYSDATE,
    CRM_NS_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
    CRM_NS_MODIFIED_DATE DATE DEFAULT SYSDATE,
    CRM_NS_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
    PRIMARY KEY (CRM_NS_ID) 
);

COMMIT;