CREATE TABLE "CRM_ACTION"
  (
    "CRM_ACTION_TYPE" VARCHAR2(1 BYTE) NOT NULL ENABLE,
    "CRM_ACTION_DESC" VARCHAR2(100 BYTE),
    "CRM_CREATED_DATE" DATE DEFAULT SYSDATE,
    "CRM_CREATED_USER" VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
    "CRM_MODIFIED_DATE" DATE DEFAULT SYSDATE,
    "CRM_MODIFIED_USER" VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
    "CRM_ENABLED"       NUMBER(*,0) DEFAULT 1,
    PRIMARY KEY ("CRM_ACTION_TYPE")
  );