ALTER TABLE CRM_PROMOTION_DOCUMENT
 DROP PRIMARY KEY CASCADE;
DROP TABLE CRM_PROMOTION_DOCUMENT CASCADE CONSTRAINTS;

CREATE TABLE CRM_PROMOTION_DOCUMENT
(
 CRM_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 CRM_MODULE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 CRM_EVENT_ID NUMBER(*,0) NOT NULL ENABLE,
 CRM_DOCUMENT_ID NUMBER(*,0) NOT NULL ENABLE,
 CRM_DOCUMENT_TYPE VARCHAR2(10 BYTE),
 CRM_CREATED_DATE DATE DEFAULT SYSDATE,
 CRM_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CRM_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CRM_SITE_CODE, CRM_MODULE_CODE, CRM_EVENT_ID, CRM_DOCUMENT_ID)
);
ALTER TABLE CRM_PROMOTION_DOCUMENT ADD (
 CONSTRAINT CRM_PROMOTION_DOCUMENT_R01
 FOREIGN KEY (CRM_SITE_CODE, CRM_MODULE_CODE, CRM_EVENT_ID)
 REFERENCES CRM_PROMOTION (CRM_SITE_CODE, CRM_MODULE_CODE, CRM_EVENT_ID));