ALTER TABLE CRM_PROMOTION_ENQUIRY
 DROP PRIMARY KEY CASCADE;
DROP TABLE CRM_PROMOTION_ENQUIRY CASCADE CONSTRAINTS;

CREATE TABLE CRM_PROMOTION_ENQUIRY
(
 CRM_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 CRM_MODULE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 CRM_EVENT_ID NUMBER(*,0) NOT NULL ENABLE,
 CRM_PROMO_ENQ_PID NUMBER(*,0) NOT NULL ENABLE,
 CRM_ENQUIRY VARCHAR2(50 BYTE),
 CRM_PHONE VARCHAR2(50 BYTE),
 CRM_CREATED_DATE DATE DEFAULT SYSDATE,
 CRM_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CRM_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CRM_SITE_CODE, CRM_MODULE_CODE, CRM_EVENT_ID, CRM_PROMO_ENQ_PID)
);
ALTER TABLE CRM_PROMOTION_ENQUIRY ADD (
 CONSTRAINT CRM_PROMOTION_ENQUIRY_R01
 FOREIGN KEY (CRM_SITE_CODE, CRM_MODULE_CODE, CRM_EVENT_ID)
 REFERENCES CRM_PROMOTION (CRM_SITE_CODE, CRM_MODULE_CODE, CRM_EVENT_ID));