ALTER TABLE CRM_CLIENTS_ACCESS_CONTROL
 DROP PRIMARY KEY CASCADE;
DROP TABLE CRM_CLIENTS_ACCESS_CONTROL CASCADE CONSTRAINTS;

CREATE TABLE CRM_CLIENTS_ACCESS_CONTROL
(
 CRM_CLIENT_ID NUMBER(*,0) DEFAULT 1,
 CRM_SITE_CODE VARCHAR2(10 BYTE) NOT NULL,
 CRM_DEPARTMENT_CODE NUMBER(*,0) NOT NULL,
 CRM_CREATED_DATE DATE DEFAULT SYSDATE,
 CRM_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CRM_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CRM_CLIENT_ID, CRM_SITE_CODE, CRM_DEPARTMENT_CODE)
);
ALTER TABLE CRM_CLIENTS_ACCESS_CONTROL ADD (
 CONSTRAINT CRM_CLIENTS_ACCESS_CONTROL_R01
 FOREIGN KEY (CRM_CLIENT_ID)
 REFERENCES CRM_CLIENTS (CRM_CLIENT_ID));
ALTER TABLE CRM_CLIENTS_ACCESS_CONTROL ADD (
 CONSTRAINT CRM_CLIENTS_ACCESS_CONTROL_R02
 FOREIGN KEY (CRM_SITE_CODE)
 REFERENCES CO_SITE (CO_SITE_CODE));
ALTER TABLE CRM_CLIENTS_ACCESS_CONTROL ADD (
 CONSTRAINT CRM_CLIENTS_ACCESS_CONTROL_R03
 FOREIGN KEY (CRM_DEPARTMENT_CODE)
 REFERENCES CO_DEPARTMENTS (CO_DEPARTMENT_CODE));