ALTER TABLE CRM_CLIENTS_MEDICAL
 DROP PRIMARY KEY CASCADE;
DROP TABLE CRM_CLIENTS_MEDICAL CASCADE CONSTRAINTS;

CREATE TABLE CRM_CLIENTS_MEDICAL
(
 CRM_CLIENT_ID NUMBER(*,0) DEFAULT 1,
 CRM_MEDICAL_ID NUMBER(*,0) DEFAULT 1,
 CRM_MEDICAL_SEQ NUMBER(*,0) NOT NULL ENABLE,
 CRM_MEDICAL_TYPE VARCHAR2(1 BYTE) DEFAULT 'I' ,	-- [I]ndividual, [F]amily
 CRM_MEDICAL_REMARKS VARCHAR2(100 BYTE) NULL,
 CRM_CREATED_DATE DATE DEFAULT SYSDATE,
 CRM_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CRM_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CRM_CLIENT_ID, CRM_MEDICAL_ID, CRM_MEDICAL_SEQ, CRM_MEDICAL_TYPE)
);