ALTER TABLE CRM_PROMOTION_TARGET
 DROP PRIMARY KEY CASCADE;
DROP TABLE CRM_PROMOTION_TARGET CASCADE CONSTRAINTS;

CREATE TABLE CRM_PROMOTION_TARGET
(
 CRM_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 CRM_MODULE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 CRM_EVENT_ID NUMBER(*,0) NOT NULL ENABLE,
 CRM_TARGET_ID NUMBER(*,0) NOT NULL ENABLE,
 CRM_TARGET_TYPE VARCHAR2(10 BYTE) DEFAULT 'corporate',
 CRM_CREATED_DATE DATE DEFAULT SYSDATE,
 CRM_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CRM_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CRM_SITE_CODE, CRM_MODULE_CODE, CRM_EVENT_ID, CRM_TARGET_ID)
);
ALTER TABLE CRM_PROMOTION_TARGET ADD (
 CONSTRAINT CRM_PROMOTION_TARGET_R01
 FOREIGN KEY (CRM_SITE_CODE, CRM_MODULE_CODE, CRM_EVENT_ID)
 REFERENCES CRM_PROMOTION (CRM_SITE_CODE, CRM_MODULE_CODE, CRM_EVENT_ID));