ALTER TABLE CRM_GROUP
 DROP PRIMARY KEY CASCADE;
DROP TABLE CRM_GROUP CASCADE CONSTRAINTS;

COMMIT;

CREATE TABLE CRM_GROUP
(
	CRM_SITE_CODE				VARCHAR2(10 BYTE),
    CRM_GROUP_ID				NUMBER NOT NULL,
    CRM_GROUP_DESC				VARCHAR2(50 BYTE),
    CRM_CREATED_DATE			DATE DEFAULT SYSDATE,
    CRM_CREATED_USER			VARCHAR2(50 BYTE) DEFAULT 'SYSTEM',
    CRM_CREATED_SITE_CODE		VARCHAR2(10 BYTE),
    CRM_CREATED_DAPARTMENT_CODE	NUMBER, 
    CRM_MODIFIED_DATE			DATE DEFAULT SYSDATE,
    CRM_MODIFIED_USER			VARCHAR2(50 BYTE) DEFAULT 'SYSTEM',
    CRM_ENABLED					NUMBER(1,0) DEFAULT 1,
    PRIMARY KEY (CRM_GROUP_ID) 
);

COMMIT;