ALTER TABLE CRM_APPEALS
 DROP PRIMARY KEY CASCADE;
DROP TABLE CRM_APPEALS CASCADE CONSTRAINTS;

CREATE TABLE CRM_APPEALS
(
 CRM_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 CRM_APPEAL_ID NUMBER(*,0) DEFAULT 1,
 CRM_APPEAL_DESC VARCHAR2(100 BYTE) NULL,
 CRM_CREATED_DATE DATE DEFAULT SYSDATE,
 CRM_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_MODIFIED_DATE DATE DEFAULT SYSDATE,
 CRM_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CRM_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (CRM_APPEAL_ID)
);
INSERT INTO CRM_APPEALS (CRM_SITE_CODE, CRM_APPEAL_ID, CRM_APPEAL_DESC) VALUES ('hkah', 1, 'Appeal 1');
INSERT INTO CRM_APPEALS (CRM_SITE_CODE, CRM_APPEAL_ID, CRM_APPEAL_DESC) VALUES ('hkah', 2, 'Appeal 2');
INSERT INTO CRM_APPEALS (CRM_SITE_CODE, CRM_APPEAL_ID, CRM_APPEAL_DESC) VALUES ('hkah', 3, 'Appeal 3');
INSERT INTO CRM_APPEALS (CRM_SITE_CODE, CRM_APPEAL_ID, CRM_APPEAL_DESC) VALUES ('hkah', 4, 'Appeal 4');
INSERT INTO CRM_APPEALS (CRM_SITE_CODE, CRM_APPEAL_ID, CRM_APPEAL_DESC) VALUES ('hkah', 5, 'Appeal 5');