CREATE TABLE "CROS_GENERATE_LOG"
  (
    "TOKEN_ID" VARCHAR2(36 BYTE) NOT NULL ENABLE,
    "ERRCODE"  NUMBER(5,0),
    "ERRMSG"   VARCHAR2(300 BYTE),
    "CREATE_DATE" DATE DEFAULT SYSDATE,
    "CREATE_USER" VARCHAR2(50 BYTE) DEFAULT 'SYSTEM',
    "MODIFIED_DATE" DATE DEFAULT SYSDATE,
    "MODIFIED_USER" VARCHAR2(50 BYTE) DEFAULT 'SYSTEM',
    "ENABLE"        NUMBER(1,0) DEFAULT 1,
    CONSTRAINT "CROS_GENERATE_LOG_PK" PRIMARY KEY ("TOKEN_ID")
  )