ALTER TABLE DE_SMS_INFO
 DROP PRIMARY KEY CASCADE;
DROP TABLE DE_SMS_INFO CASCADE CONSTRAINTS;

CREATE TABLE DE_SMS_INFO
( 
 DE_SMS_ID   		 NUMBER(*,0) DEFAULT 1, 
 DE_TITLE  		     VARCHAR2(10 BYTE),
 DE_FIRSTNAME 		 VARCHAR2(100 BYTE),
 DE_LASTNAME  		 VARCHAR2(100 BYTE),
 DE_MOBILE    		 VARCHAR2(30 BYTE),
 DE_NEXTAPPTPROVIDER VARCHAR2(30 BYTE),
 DE_nextapptdate     VARCHAR2(30 BYTE),
 DE_nextappttime 	 VARCHAR2(30 BYTE),
 DE_CREATED_DATE	 DATE DEFAULT SYSDATE,
 DE_CREATED_USER 	 VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 DE_MODIFIED_DATE	 DATE DEFAULT SYSDATE,
 DE_MODIFIED_USER 	 VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 DE_ENABLED 	 	 NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (DE_SMS_ID)
);
