ALTER TABLE DI_RPT_LOG
 DROP PRIMARY KEY CASCADE;
DROP TABLE DI_RPT_LOG CASCADE CONSTRAINTS;

CREATE TABLE DI_RPT_LOG
(
 DI_RPT_ID NUMBER(*,0) NOT NULL ENABLE,
 DI_SEQ_NUM VARCHAR2(20 BYTE) NOT NULL ENABLE,
 DI_ACCESS_NUM VARCHAR2(50 BYTE) NOT NULL ENABLE,
 DI_RPT_VERSION VARCHAR2(50 BYTE),
 DI_DOCCODE VARCHAR2(20 BYTE),
 DI_FILE_PATH VARCHAR2(200 BYTE),
 DI_DOC_EMAIL VARCHAR2(200 BYTE),
 DI_SENDMAIL_STATUS VARCHAR2(20 BYTE),
 DI_READDOC_STATUS VARCHAR2(10 BYTE) DEFAULT '0',
 CO_CREATED_DATE DATE DEFAULT SYSDATE,
 CO_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 CO_MODIFIED_DATE DATE,
 CO_MODIFIED_USER VARCHAR2(30 BYTE),
 CO_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (DI_RPT_ID,DI_SEQ_NUM)
);