ALTER TABLE DS_CORPORATE_PLAN
 DROP PRIMARY KEY CASCADE;
DROP TABLE DS_CORPORATE_PLAN CASCADE CONSTRAINTS;

CREATE TABLE DS_CORPORATE_PLAN
(
 DS_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 DS_DEPARTMENT_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 DS_FINANCIAL_YEAR VARCHAR2(4 BYTE) NOT NULL ENABLE,
 DS_PLAN_ID NUMBER(*,0) NOT NULL ENABLE,
 DS_SUBJECT VARCHAR2(100 BYTE),
 DS_CREATED_DATE DATE DEFAULT SYSDATE,
 DS_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 DS_MODIFIED_DATE DATE DEFAULT SYSDATE,
 DS_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 DS_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (DS_SITE_CODE, DS_DEPARTMENT_CODE, DS_FINANCIAL_YEAR, DS_PLAN_ID)
);
ALTER TABLE DS_CORPORATE_PLAN ADD (
 CONSTRAINT DS_CORPORATE_PLAN_R01
 FOREIGN KEY (DS_SITE_CODE)
 REFERENCES CO_SITE (CO_SITE_CODE));