ALTER TABLE DS_COMMENT
 DROP PRIMARY KEY CASCADE;
DROP TABLE DS_COMMENT CASCADE CONSTRAINTS;

CREATE TABLE DS_COMMENT
(
 DS_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 DS_DEPARTMENT_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 DS_FINANCIAL_YEAR VARCHAR2(4 BYTE) NOT NULL ENABLE,
 DS_PLAN_ID NUMBER(*,0) NOT NULL ENABLE,
 DS_GOAL_ID NUMBER(*,0) NOT NULL ENABLE,
 DS_OBJECT_TYPE VARCHAR2(50 BYTE) NOT NULL,
 DS_OBJECT_ID NUMBER(*,0) NOT NULL,
 DS_COMMENT_STATUS VARCHAR2(30 BYTE),
 DS_COMMENT_DESC VARCHAR2(200 BYTE) NOT NULL,
 DS_COMMENT_USER_ID VARCHAR2(30 BYTE) NOT NULL,
 DS_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 DS_CREATED_DATE DATE DEFAULT SYSDATE,
 DS_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 DS_MODIFIED_DATE DATE DEFAULT SYSDATE,
 DS_ENABLED NUMBER(*,0) DEFAULT 1
);
ALTER TABLE DS_COMMENT ADD (
 CONSTRAINT DS_COMMENT_R01
 FOREIGN KEY (DS_SITE_CODE, DS_DEPARTMENT_CODE, DS_FINANCIAL_YEAR, DS_PLAN_ID, DS_GOAL_ID)
 REFERENCES DS_GOAL (DS_SITE_CODE, DS_DEPARTMENT_CODE, DS_FINANCIAL_YEAR, DS_PLAN_ID, DS_GOAL_ID));