ALTER TABLE DS_TASK
 DROP PRIMARY KEY CASCADE;
DROP TABLE DS_TASK CASCADE CONSTRAINTS;

CREATE TABLE DS_TASK
(
 DS_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 DS_DEPARTMENT_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 DS_FINANCIAL_YEAR VARCHAR2(4 BYTE) NOT NULL ENABLE,
 DS_PLAN_ID NUMBER(*,0) NOT NULL ENABLE,
 DS_GOAL_ID NUMBER(*,0) NOT NULL ENABLE,
 DS_TASK_ID NUMBER(*,0) NOT NULL ENABLE,
 DS_TASK_DESC VARCHAR2(2000 BYTE) NULL,
 DS_EST_COMPLETE_DATE DATE NULL,
 DS_COMPLETE_DATE DATE NULL,
 DS_TASK_ORDER NUMBER(*,0) NULL,
 DS_APPROVED VARCHAR2(1 BYTE) DEFAULT 'N',
 DS_APPROVED_DATE DATE NULL,
 DS_APPROVED_BY VARCHAR2(30 BYTE) NULL,
 DS_CREATED_DATE DATE DEFAULT SYSDATE,
 DS_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 DS_MODIFIED_DATE DATE DEFAULT SYSDATE,
 DS_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 DS_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (DS_SITE_CODE, DS_DEPARTMENT_CODE, DS_FINANCIAL_YEAR, DS_PLAN_ID, DS_GOAL_ID, DS_TASK_ID)
);
ALTER TABLE DS_TASK ADD (
 CONSTRAINT DS_TASK_R01
 FOREIGN KEY (DS_SITE_CODE, DS_DEPARTMENT_CODE, DS_FINANCIAL_YEAR, DS_PLAN_ID, DS_GOAL_ID)
 REFERENCES DS_GOAL (DS_SITE_CODE, DS_DEPARTMENT_CODE, DS_FINANCIAL_YEAR, DS_PLAN_ID, DS_GOAL_ID));