ALTER TABLE EA_APPRAISAL
 DROP PRIMARY KEY CASCADE;
DROP TABLE EA_APPRAISAL CASCADE CONSTRAINTS;

CREATE TABLE EA_APPRAISAL
(
 EA_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 EA_APPRAISAL_ID NUMBER(*,0) NOT NULL ENABLE,
 EA_APPRAISED_STAFF_ID VARCHAR2(30 BYTE),
 EA_APPRAISAL_YEAR VARCHAR2(30 BYTE),
 EA_TYPE VARCHAR2(10 BYTE),
 EA_EMPLOYEE_POINTS NUMBER(*,0),
 EA_APPRAISER_POINTS NUMBER(*,0),
 EA_APPROVED_APPRAISER VARCHAR2(100 BYTE),
 EA_APPRAISER_APPROVED_DATE DATE,
 EA_STAFF_APPROVED_DATE DATE,
 EA_SUPERVISOR VARCHAR2(100 BYTE),
 EA_SUPERVISOR_REVIEW_DATE DATE,
 EA_CREATE_DATE DATE,
 EA_CREATE_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 EA_MODIFIED_DATE DATE,
 EA_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 EA_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (EA_APPRAISAL_ID, EA_APPRAISIED_STAFF_ID,EA_APPRAISAL_YEAR)
);