ALTER TABLE EE_ELEARNING_STAFF
 DROP PRIMARY KEY CASCADE;
DROP TABLE EE_ELEARNING_STAFF CASCADE CONSTRAINTS;

CREATE TABLE EE_ELEARNING_STAFF
(
 EE_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 EE_MODULE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,	-- education, lmc
 EE_EVENT_ID NUMBER(*,0) NOT NULL ENABLE,
 EE_ENROLL_ID NUMBER(*,0) NOT NULL ENABLE,
 EE_ELEARNING_ID NUMBER(*,0) NOT NULL ENABLE,
 EE_CORRECT_ANS NUMBER(*,0) DEFAULT 0,
 EE_USER_TYPE VARCHAR2(10 BYTE) NOT NULL,	-- staff, patient
 EE_USER_ID VARCHAR2(20 BYTE) NOT NULL,
 EE_CREATED_DATE DATE DEFAULT SYSDATE,
 EE_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 EE_MODIFIED_DATE DATE DEFAULT SYSDATE,
 EE_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 EE_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (EE_SITE_CODE, EE_MODULE_CODE, EE_EVENT_ID, EE_ENROLL_ID, EE_ELEARNING_ID, EE_USER_TYPE, EE_USER_ID)
);
ALTER TABLE EE_ELEARNING_STAFF ADD (
 CONSTRAINT EE_ELEARNING_STAFF_R01
 FOREIGN KEY (EE_SITE_CODE, EE_ELEARNING_ID)
 REFERENCES EE_ELEARNING (EE_SITE_CODE, EE_ELEARNING_ID));