ALTER TABLE EE_ELEARNING
 DROP PRIMARY KEY CASCADE;
DROP TABLE EE_ELEARNING CASCADE CONSTRAINTS;

CREATE TABLE EE_ELEARNING
(
 EE_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 EE_MODULE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,	-- education, lmc
 EE_EVENT_ID NUMBER(*,0) NOT NULL ENABLE,
 EE_ELEARNING_ID NUMBER(*,0) NOT NULL ENABLE,
 EE_TOPIC VARCHAR2(200 BYTE),
 EE_TOPIC_ZH VARCHAR2(200 BYTE),
 EE_QUESTION_NUM NUMBER(*,0) DEFAULT 0,
 EE_PASSGRADE NUMBER(*,0) DEFAULT 0,
 EE_DURATION NUMBER(*,0) DEFAULT 0,
 EE_DOCUMENTS_NO NUMBER(*,0) DEFAULT 0,
 EE_SWFFILE_EN VARCHAR2(200 BYTE),
 EE_SWFFILE_ZH VARCHAR2(200 BYTE),
 EE_SORT_ORDER NUMBER(*,0),
 EE_BG_COLOR VARCHAR2(6 BYTE),	-- RGB code
 EE_DESCRIPTION VARCHAR2(500 BYTE),
 EE_REQUIRED_STAFFCAT VARCHAR2(50 BYTE),
 EE_CREATED_DATE DATE DEFAULT SYSDATE,
 EE_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 EE_MODIFIED_DATE DATE DEFAULT SYSDATE,
 EE_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 EE_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (EE_SITE_CODE, EE_ELEARNING_ID)
);
ALTER TABLE EE_ELEARNING ADD (
 CONSTRAINT EE_ELEARNING_R01
 FOREIGN KEY (EE_SITE_CODE)
 REFERENCES CO_SITE (CO_SITE_CODE));

INSERT INTO EE_ELEARNING(EE_SITE_CODE, EE_MODULE_CODE, EE_EVENT_ID, EE_ELEARNING_ID, EE_TOPIC, EE_QUESTION_NUM, EE_PASSGRADE, EE_DURATION, EE_DOCUMENTS_NO, EE_SWFFILE_EN, EE_SWFFILE_ZH) VALUES ('hkah', 'education', 1030, 6, 'Manual Handling For Nursing And Allied Health Staff', 20, 16, 60, 1, '/swf/MH/index.html', NULL);
INSERT INTO EE_ELEARNING(EE_SITE_CODE, EE_MODULE_CODE, EE_EVENT_ID, EE_ELEARNING_ID, EE_TOPIC, EE_QUESTION_NUM, EE_PASSGRADE, EE_DURATION, EE_DOCUMENTS_NO, EE_SWFFILE_EN, EE_SWFFILE_ZH) VALUES ('hkah', 'education', 1030, 7, 'Manual Handling For Ancillary And Others Staff', 20, 16, 60, 4, '/swf/MHO_en/index.html', '/swf/MHO_zh/index.html');
INSERT INTO EE_ELEARNING(EE_SITE_CODE, EE_MODULE_CODE, EE_EVENT_ID, EE_ELEARNING_ID, EE_TOPIC, EE_QUESTION_NUM, EE_PASSGRADE, EE_DURATION, EE_DOCUMENTS_NO, EE_SWFFILE_EN, EE_SWFFILE_ZH) VALUES ('hkah', 'education', 1040, 8, 'Fire Safety/Disaster', 20, 16, 60, 1, '/swf/FSD_zh/index.html', NULL);
INSERT INTO EE_ELEARNING(EE_SITE_CODE, EE_MODULE_CODE, EE_EVENT_ID, EE_ELEARNING_ID, EE_TOPIC, EE_QUESTION_NUM, EE_PASSGRADE, EE_DURATION, EE_DOCUMENTS_NO, EE_SWFFILE_EN, EE_SWFFILE_ZH) VALUES ('hkah', 'education', 1070, 5, 'Medical Gas Safety', 8, 6, 60, 3, '/swf/Medical Gas Safety_320X240.swf', NULL);
INSERT INTO EE_ELEARNING(EE_SITE_CODE, EE_MODULE_CODE, EE_EVENT_ID, EE_ELEARNING_ID, EE_TOPIC, EE_QUESTION_NUM, EE_PASSGRADE, EE_DURATION, EE_DOCUMENTS_NO, EE_SWFFILE_EN, EE_SWFFILE_ZH) VALUES ('hkah', 'education', 1010, 9, 'SHARE Again', 15, 8, 60, 2, '/swf/SHARE Again_en.swf', '/swf/SHARE Again_zh.swf');
INSERT INTO EE_ELEARNING(EE_SITE_CODE, EE_MODULE_CODE, EE_EVENT_ID, EE_ELEARNING_ID, EE_TOPIC, EE_QUESTION_NUM, EE_PASSGRADE, EE_DURATION, EE_DOCUMENTS_NO, EE_SWFFILE_EN, EE_SWFFILE_ZH) VALUES ('hkah', 'education', 1020, 10, 'Infection Control For Nursing And Allied Health Staff', 10, 6, 60, 1, NULL, NULL);
INSERT INTO EE_ELEARNING(EE_SITE_CODE, EE_MODULE_CODE, EE_EVENT_ID, EE_ELEARNING_ID, EE_TOPIC, EE_QUESTION_NUM, EE_PASSGRADE, EE_DURATION, EE_DOCUMENTS_NO, EE_SWFFILE_EN, EE_SWFFILE_ZH) VALUES ('hkah', 'education', 1020, 11, 'Infection Control For Ancillary And Others Staff', 12, 8, 60, 2, NULL, NULL);
INSERT INTO EE_ELEARNING(EE_SITE_CODE, EE_MODULE_CODE, EE_EVENT_ID, EE_ELEARNING_ID, EE_TOPIC, EE_QUESTION_NUM, EE_PASSGRADE, EE_DURATION, EE_DOCUMENTS_NO, EE_SWFFILE_EN, EE_SWFFILE_ZH) VALUES ('hkah', 'education', 1200, 12, 'Orientation for Volunteers', 12, 8, 0, 0, NULL, NULL);

INSERT INTO EE_ELEARNING(EE_SITE_CODE, EE_MODULE_CODE, EE_EVENT_ID, EE_ELEARNING_ID, EE_TOPIC, EE_QUESTION_NUM, EE_PASSGRADE, EE_DURATION, EE_DOCUMENTS_NO, EE_SWFFILE_EN, EE_SWFFILE_ZH) VALUES ('hkah', 'education', 6010, 1, 'Precaution', 10, 8, 60, 1, NULL, NULL);
INSERT INTO EE_ELEARNING(EE_SITE_CODE, EE_MODULE_CODE, EE_EVENT_ID, EE_ELEARNING_ID, EE_TOPIC, EE_QUESTION_NUM, EE_PASSGRADE, EE_DURATION, EE_DOCUMENTS_NO, EE_SWFFILE_EN, EE_SWFFILE_ZH) VALUES ('hkah', 'education', 6020, 2, 'Competency Test for Care of Comatose Patients', 5, 5, 60, 1, '/swf/Nursing coma patients.swf', NULL);
INSERT INTO EE_ELEARNING(EE_SITE_CODE, EE_MODULE_CODE, EE_EVENT_ID, EE_ELEARNING_ID, EE_TOPIC, EE_QUESTION_NUM, EE_PASSGRADE, EE_DURATION, EE_DOCUMENTS_NO, EE_SWFFILE_EN, EE_SWFFILE_ZH) VALUES ('hkah', 'education', 6030, 3, 'Competency Test for Patient Fall Assessment and Documentation', 4, 4, 60, 1, '/swf/Fall PP.swf', NULL);
INSERT INTO EE_ELEARNING(EE_SITE_CODE, EE_MODULE_CODE, EE_EVENT_ID, EE_ELEARNING_ID, EE_TOPIC, EE_QUESTION_NUM, EE_PASSGRADE, EE_DURATION, EE_DOCUMENTS_NO, EE_SWFFILE_EN, EE_SWFFILE_ZH) VALUES ('hkah', 'education', 6040, 4, 'Staff Knowledge on ERSM', 10, 8, 60, NULL, NULL, NULL);
INSERT INTO EE_ELEARNING(EE_SITE_CODE, EE_MODULE_CODE, EE_EVENT_ID, EE_ELEARNING_ID, EE_TOPIC, EE_QUESTION_NUM, EE_PASSGRADE, EE_DURATION, EE_DOCUMENTS_NO, EE_SWFFILE_EN, EE_SWFFILE_ZH) VALUES ('hkah', 'education', 6210, 13, 'MRI Safety', 11, 11, 60, 2, '/swf/MRI SAFETY_flv.swf', NULL);
INSERT INTO EE_ELEARNING(EE_SITE_CODE, EE_MODULE_CODE, EE_EVENT_ID, EE_ELEARNING_ID, EE_TOPIC, EE_QUESTION_NUM, EE_PASSGRADE, EE_DURATION, EE_DOCUMENTS_NO, EE_SWFFILE_EN, EE_SWFFILE_ZH) VALUES ('hkah', 'education', 6307, 14, 'Intravenous Therapy', 29,, 60, 2, '/swf/MRI SAFETY_flv.swf', NULL);
