ALTER TABLE EE_ELEARNING_VIDEO
 DROP PRIMARY KEY CASCADE;
DROP TABLE EE_ELEARNING_VIDEO CASCADE CONSTRAINTS;

CREATE TABLE EE_ELEARNING_VIDEO
(
 EE_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 EE_ELEARNING_ID NUMBER(*,0) NOT NULL ENABLE,
 EE_ELEARNING_VIDEO_ID NUMBER(*,0) NOT NULL ENABLE,
 EE_SWFFILE_LANG VARCHAR2(1 BYTE),	-- e english, z traditional chinese
 EE_SWFFILE VARCHAR2(200 BYTE),
 EE_CREATED_DATE DATE DEFAULT SYSDATE,
 EE_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 EE_MODIFIED_DATE DATE DEFAULT SYSDATE,
 EE_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 EE_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (EE_SITE_CODE, EE_ELEARNING_ID, EE_ELEARNING_VIDEO_ID)
);
ALTER TABLE EE_ELEARNING_VIDEO ADD (
 CONSTRAINT EE_ELEARNING_VIDEO_R01
 FOREIGN KEY (EE_SITE_CODE, EE_ELEARNING_ID)
 REFERENCES EE_ELEARNING (EE_SITE_CODE, EE_ELEARNING_ID));