ALTER TABLE EE_MENU_MODULE
 DROP PRIMARY KEY CASCADE;
DROP TABLE EE_MENU_MODULE CASCADE CONSTRAINTS;

CREATE TABLE EE_MENU_MODULE 
(	
 EE_MODULE_CODE VARCHAR2(20 BYTE) NOT NULL ENABLE, 
 EE_DESCRIPTION_EN VARCHAR2(200 BYTE), 
 EE_DESCRIPTION_ZH VARCHAR2(200 BYTE), 
 EE_PARENT_MODULE_CODE VARCHAR2(10 BYTE), 
 EE_SORT_ORDER NUMBER(*,0), 
 EE_REVISED_DATE DATE DEFAULT SYSDATE, 
 EE_CREATED_DATE DATE DEFAULT SYSDATE, 
 EE_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM', 
 EE_MODIFIED_DATE DATE DEFAULT SYSDATE, 
 EE_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM', 
 EE_ENABLED NUMBER(*,0) DEFAULT 1, 
 EE_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE, 
 EE_BG_COLOR VARCHAR2(6 BYTE), 
 EE_URL VARCHAR2(100 BYTE), 
 PRIMARY KEY (EE_MODULE_CODE, EE_SITE_CODE)
);

INSERT INTO EE_MENU_MODULE (EE_SITE_CODE, EE_MODULE_CODE, EE_DESCRIPTION_EN, EE_DESCRIPTION_ZH, EE_URL, EE_REVISED_DATE, EE_BG_COLOR, EE_SORT_ORDER) 
  VALUES ('twah', 'education.hep', 'Hospital Education Policies', '院內教育政策', 'hospital_policies.htm', TO_DATE('2010/04/09', 'yyyy/MM/dd'), 'FFCC99', 10);
INSERT INTO EE_MENU_MODULE (EE_SITE_CODE, EE_MODULE_CODE, EE_DESCRIPTION_EN, EE_DESCRIPTION_ZH, EE_URL, EE_REVISED_DATE, EE_BG_COLOR, EE_SORT_ORDER) 
  VALUES ('twah', 'education.is_cal', 'In-service Education Calendar', '院內教育月曆', 'inserv_calendar.htm', TO_DATE('2010/04/10', 'yyyy/MM/dd'), 'FFFF00', 9);
INSERT INTO EE_MENU_MODULE (EE_SITE_CODE, EE_MODULE_CODE, EE_DESCRIPTION_EN, EE_DESCRIPTION_ZH, EE_URL, EE_REVISED_DATE, EE_BG_COLOR, EE_SORT_ORDER) 
  VALUES ('twah', 'education.is_info', 'Mandatory In-service Education: Information', '院內必修課程(資訊)', 'mand_inserv_info.htm', TO_DATE('2010/04/08', 'yyyy/MM/dd'), 'FFFF00', 8);
INSERT INTO EE_MENU_MODULE (EE_SITE_CODE, EE_MODULE_CODE, EE_DESCRIPTION_EN, EE_DESCRIPTION_ZH, EE_URL, EE_REVISED_DATE, EE_BG_COLOR, EE_SORT_ORDER) 
  VALUES ('twah', 'education.is_content', 'Mandatory In-service Education: Contents', '院內必修課程(內容)', 'mand_inserv_content.htm', TO_DATE('2010/04/08', 'yyyy/MM/dd'), 'FFFF00', 7);
INSERT INTO EE_MENU_MODULE (EE_SITE_CODE, EE_MODULE_CODE, EE_DESCRIPTION_EN, EE_DESCRIPTION_ZH, EE_URL, EE_REVISED_DATE, EE_BG_COLOR, EE_SORT_ORDER) 
  VALUES ('twah', 'education.other_is', 'Other In-service Education', '其他院內教育', 'other_inserv.htm', TO_DATE('2010/04/08', 'yyyy/MM/dd'), 'CCFFFF', 6);
INSERT INTO EE_MENU_MODULE (EE_SITE_CODE, EE_MODULE_CODE, EE_DESCRIPTION_EN, EE_DESCRIPTION_ZH, EE_URL, EE_REVISED_DATE, EE_BG_COLOR, EE_SORT_ORDER) 
  VALUES ('twah', 'education.cee', 'Continuing External Education', '持續院外教育', 'cont_ext_edu.htm', TO_DATE('2010/03/02', 'yyyy/MM/dd'), 'CCFFFF', 5);
INSERT INTO EE_MENU_MODULE (EE_SITE_CODE, EE_MODULE_CODE, EE_DESCRIPTION_EN, EE_DESCRIPTION_ZH, EE_URL, EE_REVISED_DATE, EE_BG_COLOR, EE_SORT_ORDER) 
  VALUES ('twah', 'education.is_review', 'In-service Education Review', '院內教育重温', 'inserv_review.htm', TO_DATE('2010/04/14', 'yyyy/MM/dd'), 'CC99FF', 4);
INSERT INTO EE_MENU_MODULE (EE_SITE_CODE, EE_MODULE_CODE, EE_DESCRIPTION_EN, EE_DESCRIPTION_ZH, EE_URL, EE_REVISED_DATE, EE_BG_COLOR, EE_SORT_ORDER) 
  VALUES ('twah', 'education.ebp', 'Evidence-based Practice', '實証為本實務', 'evidence_practice.htm', TO_DATE('2010/04/09', 'yyyy/MM/dd'), 'CCFFCC', 3);
INSERT INTO EE_MENU_MODULE (EE_SITE_CODE, EE_MODULE_CODE, EE_DESCRIPTION_EN, EE_DESCRIPTION_ZH, EE_URL, EE_REVISED_DATE, EE_BG_COLOR, EE_SORT_ORDER) 
  VALUES ('twah', 'education.lsb', 'Literature Search Based', '文獻查考為本', 'literature_search.htm', TO_DATE('2010/04/08', 'yyyy/MM/dd'), 'CCFFCC', 2);
INSERT INTO EE_MENU_MODULE (EE_SITE_CODE, EE_MODULE_CODE, EE_DESCRIPTION_EN, EE_DESCRIPTION_ZH, EE_URL, EE_REVISED_DATE, EE_BG_COLOR, EE_SORT_ORDER) 
  VALUES ('twah', 'education.nchk', 'The Nursing Council of Hong Kong', '香港護士管理局', 'nchk.htm', TO_DATE('2010/04/08', 'yyyy/MM/dd'), 'C0C0C0', 1);
set def off;
INSERT INTO EE_MENU_MODULE (EE_SITE_CODE, EE_MODULE_CODE, EE_DESCRIPTION_EN, EE_DESCRIPTION_ZH, EE_URL, EE_REVISED_DATE, EE_BG_COLOR, EE_SORT_ORDER) 
  VALUES ('twah', 'education.smart', 'SMART Strategic & Operation Plan', '', 'smart_sop.htm', TO_DATE('2014/08/07', 'yyyy/MM/dd'), 'CCCCFF', 1);
  
  