ALTER TABLE EE_MENU_CONTENT_INSERV_REVIEW
 DROP PRIMARY KEY CASCADE;
DROP TABLE EE_MENU_CONTENT_INSERV_REVIEW CASCADE CONSTRAINTS;

CREATE TABLE EE_MENU_CONTENT_INSERV_REVIEW 
(	
 EE_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE, 
 EE_MENU_CONTENT_ID NUMBER NOT NULL ENABLE, 
 EE_MODULE_CODE VARCHAR2(20 BYTE), 
 EE_CATEGORY_CODE VARCHAR2(10 BYTE), 
 EE_CATEGORY_DESCRIPTION_EN VARCHAR2(200 BYTE), 
 EE_CATEGORY_DESCRIPTION_ZH VARCHAR2(200 BYTE), 
 EE_BG_COLOR VARCHAR2(6 BYTE), 
 EE_CREATED_DATE DATE DEFAULT SYSDATE, 
 EE_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM', 
 EE_MODIFIED_DATE DATE DEFAULT SYSDATE, 
 EE_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM', 
 EE_ENABLED NUMBER DEFAULT 1, 
 PRIMARY KEY (EE_SITE_CODE, EE_MENU_CONTENT_ID)
);
ALTER TABLE EE_MENU_CONTENT_INSERV_REVIEW ADD (
 CONSTRAINT EE_MENU_CONTENT_INSERV_RE_R01
 FOREIGN KEY (EE_SITE_CODE, EE_MENU_CONTENT_ID)
 REFERENCES EE_MENU_CONTENT (EE_SITE_CODE, EE_MENU_CONTENT_ID));

----------------------------------
-- In-service Education Review (Category)
----------------------------------
INSERT INTO EE_MENU_CONTENT_INSERV_REVIEW (EE_SITE_CODE, EE_MENU_CONTENT_ID, EE_MODULE_CODE, EE_CATEGORY_CODE, EE_CATEGORY_DESCRIPTION_EN, EE_CATEGORY_DESCRIPTION_ZH, EE_BG_COLOR)
  VALUES ('twah', 98, 'education.is_review', 'HO', 'Hospital Orientation (4-hour)', null, null);
INSERT INTO EE_MENU_CONTENT_INSERV_REVIEW (EE_SITE_CODE, EE_MENU_CONTENT_ID, EE_MODULE_CODE, EE_CATEGORY_CODE, EE_CATEGORY_DESCRIPTION_EN, EE_CATEGORY_DESCRIPTION_ZH, EE_BG_COLOR)
  VALUES ('twah', 99, 'education.is_review', 'S6', 'SHARE Seminar (6-hour)', null, null);
INSERT INTO EE_MENU_CONTENT_INSERV_REVIEW (EE_SITE_CODE, EE_MENU_CONTENT_ID, EE_MODULE_CODE, EE_CATEGORY_CODE, EE_CATEGORY_DESCRIPTION_EN, EE_CATEGORY_DESCRIPTION_ZH, EE_BG_COLOR)
  VALUES ('twah', 100, 'education.is_review', 'MIE', 'Mandatory In-service Education', null, 'FFFF00');
INSERT INTO EE_MENU_CONTENT_INSERV_REVIEW (EE_SITE_CODE, EE_MENU_CONTENT_ID, EE_MODULE_CODE, EE_CATEGORY_CODE, EE_CATEGORY_DESCRIPTION_EN, EE_CATEGORY_DESCRIPTION_ZH, EE_BG_COLOR)
  VALUES ('twah', 101, 'education.is_review', 'S1', 'SHARE Spirit (1-hour)', null, null);
INSERT INTO EE_MENU_CONTENT_INSERV_REVIEW (EE_SITE_CODE, EE_MENU_CONTENT_ID, EE_MODULE_CODE, EE_CATEGORY_CODE, EE_CATEGORY_DESCRIPTION_EN, EE_CATEGORY_DESCRIPTION_ZH, EE_BG_COLOR)
  VALUES ('twah', 102, 'education.is_review', 'IC', 'Basic Infection Control', null, null);
INSERT INTO EE_MENU_CONTENT_INSERV_REVIEW (EE_SITE_CODE, EE_MENU_CONTENT_ID, EE_MODULE_CODE, EE_CATEGORY_CODE, EE_CATEGORY_DESCRIPTION_EN, EE_CATEGORY_DESCRIPTION_ZH, EE_BG_COLOR)
  VALUES ('twah', 103, 'education.is_review', 'MH', 'Manual Handling (A)', null, null);
INSERT INTO EE_MENU_CONTENT_INSERV_REVIEW (EE_SITE_CODE, EE_MENU_CONTENT_ID, EE_MODULE_CODE, EE_CATEGORY_CODE, EE_CATEGORY_DESCRIPTION_EN, EE_CATEGORY_DESCRIPTION_ZH, EE_BG_COLOR)
  VALUES ('twah', 104, 'education.is_review', null, 'Manual Handling (B)', null, null);
INSERT INTO EE_MENU_CONTENT_INSERV_REVIEW (EE_SITE_CODE, EE_MENU_CONTENT_ID, EE_MODULE_CODE, EE_CATEGORY_CODE, EE_CATEGORY_DESCRIPTION_EN, EE_CATEGORY_DESCRIPTION_ZH, EE_BG_COLOR)
  VALUES ('twah', 105, 'education.is_review', 'CPR', 'Cardio-pulmonary Resusitation + AED', null, null);
INSERT INTO EE_MENU_CONTENT_INSERV_REVIEW (EE_SITE_CODE, EE_MENU_CONTENT_ID, EE_MODULE_CODE, EE_CATEGORY_CODE, EE_CATEGORY_DESCRIPTION_EN, EE_CATEGORY_DESCRIPTION_ZH, EE_BG_COLOR)
  VALUES ('twah', 106, 'education.is_review', 'FS', 'Fire Safety', null, null);
INSERT INTO EE_MENU_CONTENT_INSERV_REVIEW (EE_SITE_CODE, EE_MENU_CONTENT_ID, EE_MODULE_CODE, EE_CATEGORY_CODE, EE_CATEGORY_DESCRIPTION_EN, EE_CATEGORY_DESCRIPTION_ZH, EE_BG_COLOR)
  VALUES ('twah', 107, 'education.is_review', 'MGS', 'Medical Gas Safety', null, null);
INSERT INTO EE_MENU_CONTENT_INSERV_REVIEW (EE_SITE_CODE, EE_MENU_CONTENT_ID, EE_MODULE_CODE, EE_CATEGORY_CODE, EE_CATEGORY_DESCRIPTION_EN, EE_CATEGORY_DESCRIPTION_ZH, EE_BG_COLOR)
  VALUES ('twah', 108, 'education.is_review', null, null, null, null);
INSERT INTO EE_MENU_CONTENT_INSERV_REVIEW (EE_SITE_CODE, EE_MENU_CONTENT_ID, EE_MODULE_CODE, EE_CATEGORY_CODE, EE_CATEGORY_DESCRIPTION_EN, EE_CATEGORY_DESCRIPTION_ZH, EE_BG_COLOR)
  VALUES ('twah', 109, 'education.is_review', 'PI', 'Performance Improvement', null, 'FF99CC');
INSERT INTO EE_MENU_CONTENT_INSERV_REVIEW (EE_SITE_CODE, EE_MENU_CONTENT_ID, EE_MODULE_CODE, EE_CATEGORY_CODE, EE_CATEGORY_DESCRIPTION_EN, EE_CATEGORY_DESCRIPTION_ZH, EE_BG_COLOR)
  VALUES ('twah', 110, 'education.is_review', 'IC', 'Infection Control', null, 'FF99CC');
INSERT INTO EE_MENU_CONTENT_INSERV_REVIEW (EE_SITE_CODE, EE_MENU_CONTENT_ID, EE_MODULE_CODE, EE_CATEGORY_CODE, EE_CATEGORY_DESCRIPTION_EN, EE_CATEGORY_DESCRIPTION_ZH, EE_BG_COLOR)
  VALUES ('twah', 111, 'education.is_review', 'OSH', 'Occupational Safety & Health', null, 'FF99CC');
INSERT INTO EE_MENU_CONTENT_INSERV_REVIEW (EE_SITE_CODE, EE_MENU_CONTENT_ID, EE_MODULE_CODE, EE_CATEGORY_CODE, EE_CATEGORY_DESCRIPTION_EN, EE_CATEGORY_DESCRIPTION_ZH, EE_BG_COLOR)
  VALUES ('twah', 112, 'education.is_review', null, null, null, null);
INSERT INTO EE_MENU_CONTENT_INSERV_REVIEW (EE_SITE_CODE, EE_MENU_CONTENT_ID, EE_MODULE_CODE, EE_CATEGORY_CODE, EE_CATEGORY_DESCRIPTION_EN, EE_CATEGORY_DESCRIPTION_ZH, EE_BG_COLOR)
  VALUES ('twah', 113, 'education.is_review', 'IM', 'Information Management', null, null);
INSERT INTO EE_MENU_CONTENT_INSERV_REVIEW (EE_SITE_CODE, EE_MENU_CONTENT_ID, EE_MODULE_CODE, EE_CATEGORY_CODE, EE_CATEGORY_DESCRIPTION_EN, EE_CATEGORY_DESCRIPTION_ZH, EE_BG_COLOR)
  VALUES ('twah', 114, 'education.is_review', 'CS', 'Customer Service', null, 'FF99CC');
INSERT INTO EE_MENU_CONTENT_INSERV_REVIEW (EE_SITE_CODE, EE_MENU_CONTENT_ID, EE_MODULE_CODE, EE_CATEGORY_CODE, EE_CATEGORY_DESCRIPTION_EN, EE_CATEGORY_DESCRIPTION_ZH, EE_BG_COLOR)
  VALUES ('twah', 115, 'education.is_review', null, null, null, null);
INSERT INTO EE_MENU_CONTENT_INSERV_REVIEW (EE_SITE_CODE, EE_MENU_CONTENT_ID, EE_MODULE_CODE, EE_CATEGORY_CODE, EE_CATEGORY_DESCRIPTION_EN, EE_CATEGORY_DESCRIPTION_ZH, EE_BG_COLOR)
  VALUES ('twah', 116, 'education.is_review', null, null, null, null);
INSERT INTO EE_MENU_CONTENT_INSERV_REVIEW (EE_SITE_CODE, EE_MENU_CONTENT_ID, EE_MODULE_CODE, EE_CATEGORY_CODE, EE_CATEGORY_DESCRIPTION_EN, EE_CATEGORY_DESCRIPTION_ZH, EE_BG_COLOR)
  VALUES ('twah', 117, 'education.is_review', null, null, null, null);
INSERT INTO EE_MENU_CONTENT_INSERV_REVIEW (EE_SITE_CODE, EE_MENU_CONTENT_ID, EE_MODULE_CODE, EE_CATEGORY_CODE, EE_CATEGORY_DESCRIPTION_EN, EE_CATEGORY_DESCRIPTION_ZH, EE_BG_COLOR)
  VALUES ('twah', 118, 'education.is_review', 'CE', 'Clinical Education', null, null);
INSERT INTO EE_MENU_CONTENT_INSERV_REVIEW (EE_SITE_CODE, EE_MENU_CONTENT_ID, EE_MODULE_CODE, EE_CATEGORY_CODE, EE_CATEGORY_DESCRIPTION_EN, EE_CATEGORY_DESCRIPTION_ZH, EE_BG_COLOR)
  VALUES ('twah', 119, 'education.is_review', 'CE-O', 'Other / Multidisciplinary', null, 'CC99FF');
INSERT INTO EE_MENU_CONTENT_INSERV_REVIEW (EE_SITE_CODE, EE_MENU_CONTENT_ID, EE_MODULE_CODE, EE_CATEGORY_CODE, EE_CATEGORY_DESCRIPTION_EN, EE_CATEGORY_DESCRIPTION_ZH, EE_BG_COLOR)
  VALUES ('twah', 120, 'education.is_review', 'CE-CC', 'Critical Care', null, 'CC99FF');
INSERT INTO EE_MENU_CONTENT_INSERV_REVIEW (EE_SITE_CODE, EE_MENU_CONTENT_ID, EE_MODULE_CODE, EE_CATEGORY_CODE, EE_CATEGORY_DESCRIPTION_EN, EE_CATEGORY_DESCRIPTION_ZH, EE_BG_COLOR)
  VALUES ('twah', 121, 'education.is_review', 'CE-MC', 'Medical Care', null, 'CC99FF');
INSERT INTO EE_MENU_CONTENT_INSERV_REVIEW (EE_SITE_CODE, EE_MENU_CONTENT_ID, EE_MODULE_CODE, EE_CATEGORY_CODE, EE_CATEGORY_DESCRIPTION_EN, EE_CATEGORY_DESCRIPTION_ZH, EE_BG_COLOR)
  VALUES ('twah', 122, 'education.is_review', 'CE-SC', 'Surgical Care', null, 'CC99FF');
INSERT INTO EE_MENU_CONTENT_INSERV_REVIEW (EE_SITE_CODE, EE_MENU_CONTENT_ID, EE_MODULE_CODE, EE_CATEGORY_CODE, EE_CATEGORY_DESCRIPTION_EN, EE_CATEGORY_DESCRIPTION_ZH, EE_BG_COLOR)
  VALUES ('twah', 123, 'education.is_review', 'CE-OR', 'Operating Room', null, 'CC99FF');
INSERT INTO EE_MENU_CONTENT_INSERV_REVIEW (EE_SITE_CODE, EE_MENU_CONTENT_ID, EE_MODULE_CODE, EE_CATEGORY_CODE, EE_CATEGORY_DESCRIPTION_EN, EE_CATEGORY_DESCRIPTION_ZH, EE_BG_COLOR)
  VALUES ('twah', 124, 'education.is_review', 'CE-OC', 'Obstetric Care', null, 'CC99FF');
INSERT INTO EE_MENU_CONTENT_INSERV_REVIEW (EE_SITE_CODE, EE_MENU_CONTENT_ID, EE_MODULE_CODE, EE_CATEGORY_CODE, EE_CATEGORY_DESCRIPTION_EN, EE_CATEGORY_DESCRIPTION_ZH, EE_BG_COLOR)
  VALUES ('twah', 125, 'education.is_review', 'CE-PC', 'Pediatric Care', null, 'CC99FF');
INSERT INTO EE_MENU_CONTENT_INSERV_REVIEW (EE_SITE_CODE, EE_MENU_CONTENT_ID, EE_MODULE_CODE, EE_CATEGORY_CODE, EE_CATEGORY_DESCRIPTION_EN, EE_CATEGORY_DESCRIPTION_ZH, EE_BG_COLOR)
  VALUES ('twah', 126, 'education.is_review', 'CE-CA', 'Clinical Alert', null, 'CC99FF');
INSERT INTO EE_MENU_CONTENT_INSERV_REVIEW (EE_SITE_CODE, EE_MENU_CONTENT_ID, EE_MODULE_CODE, EE_CATEGORY_CODE, EE_CATEGORY_DESCRIPTION_EN, EE_CATEGORY_DESCRIPTION_ZH, EE_BG_COLOR)
  VALUES ('twah', 127, 'education.is_review', 'ME', 'Management Education', null, '99CCFF');

