ALTER TABLE EL_DETAILS_VALUE
 DROP PRIMARY KEY CASCADE;
DROP TABLE EL_DETAILS_VALUE CASCADE CONSTRAINTS;

CREATE TABLE EL_DETAILS_VALUE
(
  EL_SITE_CODE VARCHAR2(10),
  EL_DETAILS_ID NUMBER NOT NULL,
  EL_LEAVE_ID NUMBER,
  EL_DETAILS_TYPE VARCHAR2(30 BYTE),
  EL_DETAILS_VALUE VARCHAR2(200 BYTE),
  EL_DETAILS_DATATYPE VARCHAR2(50 BYTE),
  EL_CREATED_DATE DATE DEFAULT SYSDATE,
  EL_CREATED_USER VARCHAR2(30) DEFAULT 'SYSTEM',
  EL_MODIFIED_DATE DATE DEFAULT SYSDATE,
  EL_MODIFIED_USER VARCHAR2(30) DEFAULT 'SYSTEM',
  EL_ENABLED NUMBER(*,0) DEFAULT 1,
  PRIMARY KEY (EL_DETAILS_ID)
);

ALTER TABLE EL_DETAILS_VALUE ADD (
 CONSTRAINT EL_DETAILS_VALUE_R01
 FOREIGN KEY (EL_SITE_CODE)
 REFERENCES CO_SITE (CO_SITE_CODE));