ALTER TABLE EL_ELEAVE
 DROP PRIMARY KEY CASCADE;
DROP TABLE EL_ELEAVE CASCADE CONSTRAINTS;

CREATE TABLE EL_ELEAVE
(
 EL_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 EL_ELEAVE_ID NUMBER(*,0) NOT NULL ENABLE,
 EL_STAFF_ID VARCHAR2(10 BYTE) NOT NULL,
 EL_LEAVE_TYPE VARCHAR2(10 BYTE) NOT NULL,
 EL_FROM_DATE DATE DEFAULT SYSDATE,
 EL_TO_DATE DATE DEFAULT SYSDATE,
 EL_APPLIED_DAYS NUMBER(*,2) DEFAULT 0,
 EL_APPLIED_HOURS NUMBER(*,2) DEFAULT 0,
 EL_REQUEST_REMARKS VARCHAR2(100 BYTE) NULL,
 EL_RESPONSE_REMARKS VARCHAR2(100 BYTE) NULL,
 EL_LEAVE_STATUS VARCHAR2(2 BYTE) DEFAULT 'O',		-- O - Open, A - Approval, R - Reject, C - Confirmed
 EL_PUBLIC_HOLIDAY DATE NULL,
 EL_CREATED_DATE DATE DEFAULT SYSDATE,
 EL_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 EL_MODIFIED_DATE DATE DEFAULT SYSDATE,
 EL_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 EL_ENABLED NUMBER(*,0) DEFAULT 1,
 EL_STATUS VARCHAR2(20 BYTE) DEFAULT 'NS',,
 EL_PARENT_ID VARCHAR2(30 BYTE),
 PRIMARY KEY (EL_SITE_CODE, EL_ELEAVE_ID)
);
ALTER TABLE EL_ELEAVE ADD (
 CONSTRAINT EL_ELEAVE_R01
 FOREIGN KEY (EL_SITE_CODE, EL_STAFF_ID)
 REFERENCES CO_STAFFS (CO_SITE_CODE, CO_STAFF_ID));