ALTER TABLE EL_EMPLOYEE
 DROP PRIMARY KEY CASCADE;
DROP TABLE EL_EMPLOYEE CASCADE CONSTRAINTS;

CREATE TABLE EL_EMPLOYEE
(
 EL_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 EL_STAFF_ID VARCHAR2(10 BYTE) NOT NULL,
 EL_DEPARTMENT_CODE NUMBER(*,0) NULL,
 EL_DEPARTMENT_DESC VARCHAR2(100 BYTE) NULL,
 EL_LASTNAME VARCHAR2(30 BYTE),
 EL_FIRSTNAME VARCHAR2(60 BYTE),
 EL_BIRTHDATE DATE,
 EL_POSITION_CODE VARCHAR2(10 BYTE) NULL,
 EL_POSITION_DESC VARCHAR2(100 BYTE) NULL,
 EL_EMAIL VARCHAR2(100 BYTE) NULL,
 EL_FTE VARCHAR2(20 BYTE) NULL,
 EL_CREATED_DATE DATE DEFAULT SYSDATE,
 EL_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 EL_MODIFIED_DATE DATE DEFAULT SYSDATE,
 EL_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 EL_ENABLED NUMBER(*,0) DEFAULT 1,
 EL_STATUS VARCHAR2(20 BYTE) NULL,
 PRIMARY KEY (EL_SITE_CODE, EL_STAFF_ID)
);
ALTER TABLE EL_EMPLOYEE ADD (
 CONSTRAINT EL_EMPLOYEE_R01
 FOREIGN KEY (EL_SITE_CODE)
 REFERENCES CO_SITE (CO_SITE_CODE));