ALTER TABLE EL_ELEAVE_HISTORY
 DROP PRIMARY KEY CASCADE;
DROP TABLE EL_ELEAVE_HISTORY CASCADE CONSTRAINTS;

CREATE TABLE EL_ELEAVE_HISTORY
(
 EL_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 EL_LEAVE_ID NUMBER(*,0) NOT NULL,
 EL_STAFF_ID VARCHAR2(10) NOT NULL,
 EL_LEAVE_TYPE VARCHAR2(10) NOT NULL,
 EL_FROM_DATE DATE DEFAULT SYSDATE,
 EL_TO_DATE DATE DEFAULT SYSDATE,
 EL_APPLIED_DAYS NUMBER(*,2),
 EL_APPLIED_HOURS NUMBER(*,0),
 EL_REMARKS VARCHAR2(100),
 EL_PUBLIC_HOLIDAY DATE,
 EL_PAY_YEAR NUMBER(*,0),
 EL_PAY_PERIOD NUMBER(*,0),
 EL_CREATED_DATE DATE DEFAULT SYSDATE,
 EL_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 EL_MODIFIED_DATE DATE DEFAULT SYSDATE,
 EL_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 EL_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (EL_SITE_CODE, EL_LEAVE_ID)
);