ALTER TABLE EL_ELEAVE_BALANCEDATE
 DROP PRIMARY KEY CASCADE;
DROP TABLE EL_ELEAVE_BALANCEDATE CASCADE CONSTRAINTS;

CREATE TABLE EL_ELEAVE_BALANCEDATE
(
 EL_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 EL_BALDATE_ID NUMBER(*,0) NOT NULL ENABLE,
 EL_MODULE VARCHAR2(30 BYTE) DEFAULT 'eleave',
 EL_ASAT_DATE DATE DEFAULT SYSDATE,
 EL_SYNC_DATE DATE DEFAULT SYSDATE,
 EL_CREATED_DATE DATE DEFAULT SYSDATE,
 EL_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 EL_MODIFIED_DATE DATE DEFAULT SYSDATE,
 EL_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 EL_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (EL_SITE_CODE, EL_MODULE, EL_BALDATE_ID)
);