ALTER TABLE EL_ELEAVE_BALANCE
 DROP PRIMARY KEY CASCADE;
DROP TABLE EL_ELEAVE_BALANCE CASCADE CONSTRAINTS;

CREATE TABLE EL_ELEAVE_BALANCE
(
 EL_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 EL_YEAR NUMBER(*,0) DEFAULT 9999,
 EL_STAFF_ID VARCHAR2(10 BYTE) NOT NULL,
 EL_LEAVE_TYPE VARCHAR2(10 BYTE) DEFAULT 'AL',
 EL_ACTUAL_BALANCE NUMBER(*,1) DEFAULT 20,
 EL_PENDING_BALANCE NUMBER(*,1) DEFAULT 20,
 EL_CREATED_DATE DATE DEFAULT SYSDATE,
 EL_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 EL_MODIFIED_DATE DATE DEFAULT SYSDATE,
 EL_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 EL_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (EL_SITE_CODE, EL_YEAR, EL_STAFF_ID, EL_LEAVE_TYPE)
);