ALTER TABLE EL_EMPLOYEE_ELEAVE_TYPE
 DROP PRIMARY KEY CASCADE;
DROP TABLE EL_EMPLOYEE_ELEAVE_TYPE CASCADE CONSTRAINTS;
CREATE TABLE EL_EMPLOYEE_ELEAVE_TYPE
(
 EL_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 EL_STAFF_ID VARCHAR2(10 BYTE) NOT NULL ENABLE,
 EL_LEAVE_TYPE VARCHAR2(4 BYTE) NOT NULL ENABLE,
 EL_LEAVE_TYPE_DESC VARCHAR2(100 BYTE) NOT NULL ENABLE,
 EL_CREATED_DATE DATE DEFAULT SYSDATE,
 EL_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 EL_MODIFIED_DATE DATE DEFAULT SYSDATE,
 EL_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 EL_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (EL_SITE_CODE, EL_STAFF_ID, EL_LEAVE_TYPE)
);