ALTER TABLE EL_LEAVE_HISTORY
 DROP PRIMARY KEY CASCADE;
DROP TABLE EL_LEAVE_HISTORY CASCADE CONSTRAINTS;

CREATE TABLE EL_LEAVE_HISTORY
(
 EL_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 EL_LEAVE_ID NUMBER(*,0) NOT NULL ENABLE,
 EL_STAFF_ID VARCHAR2(10 BYTE) NOT NULL,
 EL_LEAVE_TYPE VARCHAR2(10 BYTE) NOT NULL,
 EL_FROM_DATE DATE DEFAULT SYSDATE,
 EL_TO_DATE DATE DEFAULT SYSDATE,
 EL_APPLIED_DAYS NUMBER(*,2) DEFAULT 0,
 EL_APPLIED_HOURS NUMBER(*,0) DEFAULT 0,
 EL_REMARKS VARCHAR2(100 BYTE) NULL,
 EL_PUBLIC_HOLIDAY DATE NULL,
 EL_CREATED_DATE DATE DEFAULT SYSDATE,
 EL_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 EL_MODIFIED_DATE DATE DEFAULT SYSDATE,
 EL_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 EL_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (EL_SITE_CODE, EL_LEAVE_ID)
);
ALTER TABLE EL_LEAVE_HISTORY ADD (
 CONSTRAINT EL_LEAVE_HISTORY_R01
 FOREIGN KEY (EL_SITE_CODE, EL_STAFF_ID)
 REFERENCES CO_STAFFS (CO_SITE_CODE, CO_STAFF_ID));