ALTER TABLE EL_PUBLIC_HOLIDAY
 DROP PRIMARY KEY CASCADE;
DROP TABLE EL_PUBLIC_HOLIDAY CASCADE CONSTRAINTS;

CREATE TABLE EL_PUBLIC_HOLIDAY
(
 EL_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 EL_HOLIDAY DATE,
 EL_DESC VARCHAR2(100 BYTE) NULL,
 EL_CREATED_DATE DATE DEFAULT SYSDATE,
 EL_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 EL_MODIFIED_DATE DATE DEFAULT SYSDATE,
 EL_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 EL_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (EL_SITE_CODE, EL_HOLIDAY)
);