ALTER TABLE ENEWSLETTER
 DROP PRIMARY KEY CASCADE;
DROP TABLE ENEWSLETTER CASCADE CONSTRAINTS;

CREATE TABLE ENEWSLETTER
(
 ENL_ID NUMBER(*,0) NOT NULL ENABLE,
 ENL_PATIENT_TYPE VARCHAR2(20 BYTE),
 ENL_TITLE VARCHAR2(500 BYTE),
 ENL_URL VARCHAR2(500 BYTE),
 ENL_POST_DATE DATE DEFAULT SYSDATE,
 ENL_EXPIRE_DATE DATE,
 ENL_CREATED_DATE DATE DEFAULT SYSDATE,
 ENL_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 ENL_MODIFIED_DATE DATE DEFAULT SYSDATE,
 ENL_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 ENL_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (ENL_ID, ENL_PATIENT_TYPE)
);