ALTER TABLE ENEWSLETTER_CONTENT
 DROP PRIMARY KEY CASCADE;
DROP TABLE ENEWSLETTER_CONTENT CASCADE CONSTRAINTS;

CREATE TABLE ENEWSLETTER_CONTENT
(
 ENL_ID NUMBER(*,0) NOT NULL ENABLE,
 ENL_PATIENT_TYPE VARCHAR2(20 BYTE),
 ENL_DEPT VARCHAR2(100 BYTE),
 ENL_CONTENT_ID NUMBER(*,0) NOT NULL ENABLE,
 ENC_CONTENT_TITLE VARCHAR2(1000 BYTE),
 ENC_CONTENT_DESC VARCHAR2(1000 BYTE),
 ENL_CONTENT_URL VARCHAR2(500 BYTE),
 ENL_CREATED_DATE DATE DEFAULT SYSDATE,
 ENL_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 ENL_MODIFIED_DATE DATE DEFAULT SYSDATE,
 ENL_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 ENL_ENABLED NUMBER(*,0) DEFAULT 1
);

ALTER TABLE ENEWSLETTER_CONTENT ADD (
 CONSTRAINT ENEWSLETTER_CONTENT_R01
 FOREIGN KEY (ENL_ID)
 REFERENCES ENEWSLETTER (ENL_ID, ENL_PATIENT_TYPE));