create or replace
FUNCTION F_FS_EXPORT2FLEX (
I_POSTYM IN VARCHAR2,
o_errmsg OUT VARCHAR2)
RETURN VARCHAR2 
AS
V_VOUREF VARCHAR2(8) := '00000001';
V_OUTVOCHDATE VARCHAR2(10) := TO_CHAR(LAST_DAY(TO_DATE(I_POSTYM||'01','yyyymmdd')),'dd/mm/yyyy');
V_ALL VARCHAR2(32767);
V_DTL VARCHAR2(32767);
V_TXT VARCHAR2(32767);
V_AMT NUMBER(22,2) :=0;
v_outDebTotalAmt NUMBER(22,2) :=0;

CURSOR c_chargeTo IS
SELECT
'JV'||
V_VOUREF||
v_outVochDate||
SUBSTR(RPAD(DECODE(REQUEST_TYPE,'1','7200','2','7300','3','7200','4','8600','5','8250','6','7200'),10),1,10)||
SUBSTR(RPAD(	DECODE(CHARGE_TO,'820','800','830','800',CHARGE_TO),8),1,8)||
SUBSTR(RPAD(' ',10),1,10)||
' '||
SUBSTR(RPAD(' ',2),1,2)||
' '||
SUBSTR(RPAD(' ',2),1,2)||
SUBSTR(RPAD(' ',3),1,3)||
SUBSTR(RPAD(' ',2),1,2)||
SUBSTR(RPAD(' ',2),1,2)||
' '||
SUBSTR(RPAD(' ',2),1,2)||
SUBSTR(RPAD(' ',3),1,3)||
SUBSTR(RPAD(' ',2),1,2)||
'HKD'||
SUBSTR(TO_CHAR(TAIAN.SET_DECIMAL@tah(NVL(CHARGE_AMOUNT,0),10)),1,10)||
SUBSTR(TO_CHAR(TAIAN.SET_DECIMAL@tah(1,10)),1,8)||
SUBSTR(TO_CHAR(TAIAN.SET_DECIMAL@tah(NVL(CHARGE_AMOUNT,0),10)),1,10)||
'D'||
SUBSTR(RPAD(' ',60),1,60)||
SUBSTR(RPAD(' ',4),1,4)||
UPPER(SUBSTR(RPAD(TO_CHAR(TO_DATE(I_POSTYM,'yyyymm'),'MONYY', 'nls_date_language=american')||' 300 '||DECODE(REQUEST_TYPE,'1','Cafeteria Item','2','Cafeteria Miscellaneous Item')||' supplies (self user)',120),1,120)) AS TXT,
TAIAN.SET_DECIMAL@tah(NVL(CHARGE_AMOUNT,0),10)
FROM FS_REQUEST
WHERE TO_CHAR(POST_DATE,'YYYYMM') = I_POSTYM
AND REQ_STATUS = 'P'
AND NVL(CHARGE_AMOUNT,0)>0
ORDER BY CHARGE_TO,REQUEST_TYPE
;

BEGIN
  O_ERRMSG := 'OK';

	OPEN c_chargeTo;
	LOOP
	FETCH C_CHARGETO INTO V_TXT,V_AMT;
	EXIT WHEN C_CHARGETO%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE('[V_TXT]:'||V_TXT);
    V_DTL := V_DTL||V_TXT||chr(13)||chr(10);
    V_OUTDEBTOTALAMT :=V_OUTDEBTOTALAMT + V_AMT;
	END LOOP;
	CLOSE C_CHARGETO;
  
  IF V_TXT IS NOT NULL THEN
      V_ALL := 'JV'||V_VOUREF||v_outVochDate||'1750'||RPAD(' ',6,' ')||RPAD(' ',8,' ')||RPAD(' ',10,' ')||RPAD(' ',1,' ')||RPAD(' ',10,' ')||RPAD(' ',10,' ')||'HKD';
      IF V_OUTDEBTOTALAMT = 0 THEN 
        V_ALL := V_ALL||SUBSTR(TO_CHAR(V_OUTDEBTOTALAMT)||'0000000000',1,10); 
      ELSE
        V_ALL := V_ALL||SUBSTR(TO_CHAR(V_OUTDEBTOTALAMT)||'.'||'0000000000',1,10);  
      END IF;
          
      V_ALL := V_ALL||'1.000000';
      IF V_OUTDEBTOTALAMT = 0 THEN 
        V_ALL := V_ALL||SUBSTR(TO_CHAR(V_OUTDEBTOTALAMT)||'0000000000',1,10); 
      ELSE
        V_ALL := V_ALL||SUBSTR(TO_CHAR(V_OUTDEBTOTALAMT)||'.'||'0000000000',1,10);  
      END IF;		
      dbms_output.put_line('[V_ALL]:'||V_ALL);	
      V_ALL := V_ALL||'C'||RPAD(' ',60,' ')||RPAD(' ',4,' ')||SUBSTR(('ISSUE TO VARIOUS DEPARTMENT FOR '||I_POSTYM||RPAD(' ',120,' ')),1,120);	
      V_DTL := V_DTL||V_ALL;
  END IF;
  
	RETURN V_DTL;
EXCEPTION
WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('An ERROR was encountered - '||SQLCODE||' -ERROR- '||SQLERRM);
  O_ERRMSG := 'An ERROR was encountered - '||SQLCODE||' -ERROR- '||SQLERRM;      
  RETURN NULL;      
END F_FS_EXPORT2FLEX;
/