create or replace
FUNCTION F_UPDATE_ORDERED (
v_action		IN VARCHAR2,--ADD
AS_REQNO IN EPO_REQUEST_M.REQ_NO%TYPE,
AS_MODBY IN EPO_REQUEST_D.MOD_BY%TYPE,
AS_MODDATE IN VARCHAR2,
o_errmsg OUT VARCHAR2)
RETURN VARCHAR2
IS
LS_OUTSTANDING NUMBER;
LS_RETURN NUMBER;
LS_SYSDATE DATE;

BEGIN
--	LS_SYSDATE := SYSDATE;
  
  SELECT SUM(D.OUTSTANDING) 
  INTO LS_OUTSTANDING
  FROM EPO_REQUEST_D D 
  WHERE D.REQ_NO = AS_REQNO
  AND D.APPROVE_FLAG>0;

	UPDATE 
  EPO_REQUEST_M ERM
	SET ERM.REQ_STATUS = 'O',
	ERM.MOD_BY = AS_MODBY,
	ERM.MOD_DATE = TO_DATE(AS_MODDATE,'DDMMYYYYHH24MISS')
	WHERE ERM.REQ_NO = AS_REQNO
  AND ERM.REQ_STATUS IN ('P','A','Z','D')
	AND LS_OUTSTANDING = 0;
  
  IF SQL%FOUND THEN  -- update succeeded
    LS_RETURN :=	'1';
  ELSE
    LS_RETURN :=	'0';
  END IF;
  
  RETURN LS_RETURN;
EXCEPTION
WHEN OTHERS THEN
      raise_application_error(-20001,'An error was encountered - '||SQLCODE||' -ERROR- '||SQLERRM);
      RETURN NULL;      
END F_UPDATE_ORDERED;