CREATE TABLE FS_ORDER_REMARK
  (
    PATIENT_ID    VARCHAR2(20 BYTE) NOT NULL ENABLE,
    PATIENT_REMARK VARCHAR2(20 BYTE),
    CREATE_DATE DATE DEFAULT SYSDATE,
    CREATE_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
    ENABLE      NUMBER(1,0) DEFAULT 1
  );