create or replace
FUNCTION "GET_ALERT_CODE"(V_PATNO IN VARCHAR2,
                                            V_USRID IN VARCHAR2)
  RETURN VARCHAR2 AS
  ALTCODECUR    TYPES.CURSOR_TYPE;
  P_ALTCODETEMP VARCHAR2(100);
  P_ALTCODE     VARCHAR2(100);
BEGIN
  OPEN ALTCODECUR FOR
    SELECT A.ALTCODE
      FROM PATALTLINK@IWEB P, ALERT@IWEB A
     WHERE P.ALTID = A.ALTID
       AND P.PATNO = V_PATNO
       AND P.PALCDATE IS NULL
       AND P.ALTID IN (SELECT DISTINCT R.ALTID
                         FROM USRROLE@IWEB U, ROLALTLINK@IWEB R
                        WHERE U.ROLID = R.ROLID
                          AND (U.USRID = V_USRID OR V_USRID IS NULL))
     ORDER BY A.ALTCODE;

  LOOP
    FETCH ALTCODECUR
      INTO P_ALTCODETEMP;
    EXIT WHEN ALTCODECUR%NOTFOUND;
    P_ALTCODE := P_ALTCODE || ',' || P_ALTCODETEMP;
  END LOOP;
  CLOSE ALTCODECUR;
  IF LENGTH(P_ALTCODE) > 1 THEN
    RETURN SUBSTR(P_ALTCODE, 2);
  END IF;
  RETURN '';
END;