ALTER TABLE GHC_CLIENT_REJECTDATE
 DROP PRIMARY KEY CASCADE;
DROP TABLE GHC_CLIENT_REJECTDATE CASCADE CONSTRAINTS;

CREATE TABLE GHC_CLIENT_REJECTDATE
(
 GHC_CLIENT_ID NUMBER(*,0) DEFAULT 1,
 GHC_REQUEST_APPOINTDATE DATE NOT NULL,
 GHC_CREATED_DATE DATE DEFAULT SYSDATE,
 GHC_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 GHC_MODIFIED_DATE DATE DEFAULT SYSDATE,
 GHC_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 GHC_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (GHC_CLIENT_ID, GHC_REQUEST_APPOINTDATE)
);