ALTER TABLE GHC_COMMENTS
 DROP PRIMARY KEY CASCADE;
DROP TABLE GHC_COMMENTS CASCADE CONSTRAINTS;

CREATE TABLE GHC_COMMENTS
(
 GHC_CLIENT_ID NUMBER(*,0) NOT NULL,
 GHC_COMMENT_ID NUMBER(*,0) DEFAULT 1,
 GHC_TOPIC_DESC VARCHAR2(100 BYTE) NOT NULL,
 GHC_COMMENT_DESC VARCHAR2(3800 BYTE) NULL,
 GHC_INVOLVE_DEPARTMENT_CODE NUMBER(*,0) NULL,
 GHC_INVOLVE_USER_ID VARCHAR2(20 BYTE) NULL,
 GHC_SKIP VARCHAR2(1 BYTE) NULL,
 GHC_CREATED_DATE DATE DEFAULT SYSDATE,
 GHC_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 GHC_MODIFIED_DATE DATE DEFAULT SYSDATE,
 GHC_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 GHC_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (GHC_CLIENT_ID, GHC_COMMENT_ID)
);
ALTER TABLE GHC_COMMENTS ADD (
 CONSTRAINT GHC_COMMENTS_R01
 FOREIGN KEY (GHC_CLIENT_ID)
 REFERENCES GHC_CLIENTS (GHC_CLIENT_ID));