ALTER TABLE HAA_CHECKLIST_PROGRESS
 DROP PRIMARY KEY CASCADE;
DROP TABLE HAA_CHECKLIST_PROGRESS CASCADE CONSTRAINTS;

CREATE TABLE HAA_CHECKLIST_PROGRESS
(
 HAA_CHECKLIST_PID NUMBER(*,0) NOT NULL ENABLE,
 HAA_PROGRESS VARCHAR2(200 BYTE),
 HAA_INDENT NUMBER(*,0),
 HAA_DEPT VARCHAR2(50 BYTE),
 HAA_INIT_PARTY VARCHAR2(100 BYTE),
 HAA_RSPN VARCHAR2(50 BYTE),
 HAA_MODIFIED_DATE DATE DEFAULT SYSDATE,
 HAA_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 HAA_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (HAA_CHECKLIST_PID)
);

INSERT INTO HAA_CHECKLIST_PROGRESS(HAA_CHECKLIST_PID, HAA_PROGRESS, HAA_INDENT, HAA_DEPT, HAA_INIT_PARTY, HAA_RSPN) VALUES (1, '1. To prepare Quote.', 0, 'Mkt', 'Jessica', '');
INSERT INTO HAA_CHECKLIST_PROGRESS(HAA_CHECKLIST_PID, HAA_PROGRESS, HAA_INDENT, HAA_DEPT, HAA_INIT_PARTY, HAA_RSPN) VALUES (2, '2. Send to Fin for Approval (for tailor-made package only)', 0, 'Fin', 'Sandy/Alfred', 'Fin:');
INSERT INTO HAA_CHECKLIST_PROGRESS(HAA_CHECKLIST_PID, HAA_PROGRESS, HAA_INDENT, HAA_DEPT, HAA_INIT_PARTY, HAA_RSPN) VALUES (3, '3. Send to Corp. after Fin approved', 0, 'Mkt', 'Jessica', '');
INSERT INTO HAA_CHECKLIST_PROGRESS(HAA_CHECKLIST_PID, HAA_PROGRESS, HAA_INDENT, HAA_DEPT, HAA_INIT_PARTY, HAA_RSPN) VALUES (4, '4. Follow-up Corp. enquiry', 0, 'Mkt', 'Jessica/Mei', '');
INSERT INTO HAA_CHECKLIST_PROGRESS(HAA_CHECKLIST_PID, HAA_PROGRESS, HAA_INDENT, HAA_DEPT, HAA_INIT_PARTY, HAA_RSPN) VALUES (5, '5. Inform Health A, PBO, FIN - renewal / new bus.', 0, 'Mkt', 'Jessica/Mei', '');
INSERT INTO HAA_CHECKLIST_PROGRESS(HAA_CHECKLIST_PID, HAA_PROGRESS, HAA_INDENT, HAA_DEPT, HAA_INIT_PARTY, HAA_RSPN) VALUES (6, '6. To prepare Agreement', 0, 'Mkt', 'Mei/Jessica', '');
INSERT INTO HAA_CHECKLIST_PROGRESS(HAA_CHECKLIST_PID, HAA_PROGRESS, HAA_INDENT, HAA_DEPT, HAA_INIT_PARTY, HAA_RSPN) VALUES (7, '7. Send to Fin for Approval Review', 0, 'Fin', 'Sandy', 'Fin:');
INSERT INTO HAA_CHECKLIST_PROGRESS(HAA_CHECKLIST_PID, HAA_PROGRESS, HAA_INDENT, HAA_DEPT, HAA_INIT_PARTY, HAA_RSPN) VALUES (8, '8. Revise agreement (if needed)', 0, 'Mkt', 'Jessica/Mei', '');
INSERT INTO HAA_CHECKLIST_PROGRESS(HAA_CHECKLIST_PID, HAA_PROGRESS, HAA_INDENT, HAA_DEPT, HAA_INIT_PARTY, HAA_RSPN) VALUES (9, '9. Agreement for Corporate Review', 0, 'Mkt', 'Jessica/Mei', '');
INSERT INTO HAA_CHECKLIST_PROGRESS(HAA_CHECKLIST_PID, HAA_PROGRESS, HAA_INDENT, HAA_DEPT, HAA_INIT_PARTY, HAA_RSPN) VALUES (10, '10. Revise agreement (if needed)', 0, 'Mkt', 'Jessica/Mei/Sandy', 'Fin:');
INSERT INTO HAA_CHECKLIST_PROGRESS(HAA_CHECKLIST_PID, HAA_PROGRESS, HAA_INDENT, HAA_DEPT, HAA_INIT_PARTY, HAA_RSPN) VALUES (11, '11. Final Approval on Agreement', 0, 'Mkt', 'Jessica/Mei/Sandy', 'Fin:');
INSERT INTO HAA_CHECKLIST_PROGRESS(HAA_CHECKLIST_PID, HAA_PROGRESS, HAA_INDENT, HAA_DEPT, HAA_INIT_PARTY, HAA_RSPN) VALUES (12, '12. Further to Setp 5, PBO and Fin need to:', 0, '', '', '');
INSERT INTO HAA_CHECKLIST_PROGRESS(HAA_CHECKLIST_PID, HAA_PROGRESS, HAA_INDENT, HAA_DEPT, HAA_INIT_PARTY, HAA_RSPN) VALUES (13, 'a) Amend Cost breakdown (when using existing code but package price has adjusted)', 1, 'Fin', 'Kiky', '');
INSERT INTO HAA_CHECKLIST_PROGRESS(HAA_CHECKLIST_PID, HAA_PROGRESS, HAA_INDENT, HAA_DEPT, HAA_INIT_PARTY, HAA_RSPN) VALUES (14, 'b) Set <u>Package Code</u> (if needed)', 1, 'Fin', 'Kiky', '');
INSERT INTO HAA_CHECKLIST_PROGRESS(HAA_CHECKLIST_PID, HAA_PROGRESS, HAA_INDENT, HAA_DEPT, HAA_INIT_PARTY, HAA_RSPN) VALUES (15, 'c) Set <u>AR Code (for new corporate ONLY)</u>', 1, 'PBO', 'Becky/Rita', '');
INSERT INTO HAA_CHECKLIST_PROGRESS(HAA_CHECKLIST_PID, HAA_PROGRESS, HAA_INDENT, HAA_DEPT, HAA_INIT_PARTY, HAA_RSPN) VALUES (16, 'd) Develop / Edit corporate profile (if needed)', 1, 'Health A.', 'Philip/Donna', 'Health A:');
INSERT INTO HAA_CHECKLIST_PROGRESS(HAA_CHECKLIST_PID, HAA_PROGRESS, HAA_INDENT, HAA_DEPT, HAA_INIT_PARTY, HAA_RSPN) VALUES (17, '13. Inform IT to update Code / cost breakdown on HATS', 0, 'Fin', 'Kiky', 'I.T:');
INSERT INTO HAA_CHECKLIST_PROGRESS(HAA_CHECKLIST_PID, HAA_PROGRESS, HAA_INDENT, HAA_DEPT, HAA_INIT_PARTY, HAA_RSPN) VALUES (18, '14. Inform Fin, Health. A, OPD, Mkt Package Code updated', 0, 'IT', 'Kenneth', '');
INSERT INTO HAA_CHECKLIST_PROGRESS(HAA_CHECKLIST_PID, HAA_PROGRESS, HAA_INDENT, HAA_DEPT, HAA_INIT_PARTY, HAA_RSPN) VALUES (19, '15. Double check if the <u>Package code</u> is updated', 0, 'PBO', 'Becky/Rita', '');
INSERT INTO HAA_CHECKLIST_PROGRESS(HAA_CHECKLIST_PID, HAA_PROGRESS, HAA_INDENT, HAA_DEPT, HAA_INIT_PARTY, HAA_RSPN) VALUES (20, '16. Set up <u>AR code (new corp.)</u> and inform Health. A, Fin and Mkt', 0, 'PBO', 'Becky/Rita', '');
INSERT INTO HAA_CHECKLIST_PROGRESS(HAA_CHECKLIST_PID, HAA_PROGRESS, HAA_INDENT, HAA_DEPT, HAA_INIT_PARTY, HAA_RSPN) VALUES (21, '17. Filing Agreement (scanned), Original Agreement for Fin', 0, 'Mkt/Fin', 'Mei/Sandy', '');
INSERT INTO HAA_CHECKLIST_PROGRESS(HAA_CHECKLIST_PID, HAA_PROGRESS, HAA_INDENT, HAA_DEPT, HAA_INIT_PARTY, HAA_RSPN) VALUES (22, '18. Corporate Payment / Stateemnt enquiry', 0, 'PBO', 'Becky/Rita', '');
INSERT INTO HAA_CHECKLIST_PROGRESS(HAA_CHECKLIST_PID, HAA_PROGRESS, HAA_INDENT, HAA_DEPT, HAA_INIT_PARTY, HAA_RSPN) VALUES (23, '19. Corporation other enquiry on health talk for other business opportunity', 0, 'Mkt', 'Jessica/Mei', '');