ALTER TABLE HAA_CHECKLIST_DATE
 DROP PRIMARY KEY CASCADE;
DROP TABLE HAA_CHECKLIST_DATE CASCADE CONSTRAINTS;

CREATE TABLE HAA_CHECKLIST_DATE
(
 HAA_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
 HAA_CHECKLIST_ID NUMBER(*,0) NOT NULL ENABLE,
 HAA_CHECKLIST_DID NUMBER(*,0) NOT NULL ENABLE,
 HAA_INIT_DATE DATE,
 HAA_CMPLT_DATE DATE,
 HAA_CREATED_DATE DATE DEFAULT SYSDATE,
 HAA_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 HAA_MODIFIED_DATE DATE DEFAULT SYSDATE,
 HAA_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 HAA_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (HAA_CHECKLIST_ID, HAA_CHECKLIST_DID)
);
ALTER TABLE HAA_CHECKLIST_DATE ADD (
 CONSTRAINT HAA_CHECKLIST_DATE_R01
 FOREIGN KEY (HAA_SITE_CODE, HAA_CHECKLIST_ID)
 REFERENCES HAA_CHECKLIST (HAA_SITE_CODE, HAA_CHECKLIST_ID));