CREATE OR REPLACE FUNCTION "HAT_ACT_PHARMACYTICKETNO" (
	i_action   IN VARCHAR2,
	i_locid    IN VARCHAR2,
	i_patno    IN VARCHAR2,
	i_ticketno IN VARCHAR2,
	o_errmsg   OUT VARCHAR2
)
	RETURN VARCHAR2
AS
	v_CURRDATE VARCHAR2(10);
	v_COUNT NUMBER;
	v_PREFIX VARCHAR(10);
	v_TICKETNO VARCHAR(20);
	v_ESTIMATED_DATE DATE;
	v_MAXNUM NUMBER := 999;
	v_BUFFER_TIME NUMBER;
	v_REGID NUMBER;
BEGIN
	o_errmsg := 'OK';

	SELECT TO_CHAR(SYSDATE, 'YYYYMMDD') INTO v_CURRDATE FROM DUAL;

	-- ticket no
	SELECT COUNT(1) + 1 INTO v_COUNT FROM PH_TICKET_QUEUE WHERE PH_LOC_ID = i_locid AND PH_TICKET_DT = v_CURRDATE;

	IF i_locid = 'NW' THEN
		v_BUFFER_TIME := 2;
		SELECT PH_LOC_PREFIX INTO v_PREFIX FROM PH_LOCATION WHERE PH_LOC_ID = i_locid AND PH_LOC_TYPE = 'O';
	ELSIF i_locid = 'OW' THEN
		v_BUFFER_TIME := 4;
		SELECT PH_LOC_PREFIX INTO v_PREFIX FROM PH_LOCATION WHERE PH_LOC_ID = i_locid AND PH_LOC_TYPE = 'O';
	ELSE
		v_BUFFER_TIME := 4;
		SELECT PH_LOC_PREFIX || TO_CHAR(SYSDATE, 'DDD') INTO v_PREFIX FROM PH_LOCATION WHERE PH_LOC_ID = i_locid AND PH_LOC_TYPE != 'O';
	END IF;

	IF v_COUNT > v_MAXNUM THEN
		v_TICKETNO := v_PREFIX || v_COUNT;
	ELSE
		v_TICKETNO := v_PREFIX || LPAD(v_COUNT, LENGTH(v_MAXNUM), '0');
	END IF;

	-- estimated date
	SELECT COUNT(1) INTO v_COUNT FROM PH_TICKET_QUEUE WHERE PH_LOC_ID = i_locid AND PH_TICKET_DT = v_CURRDATE AND PH_STATUS != -1 AND PH_COLLECTION_DATE IS NOT NULL;
	IF v_COUNT >= 10 THEN
		BEGIN
			SELECT SYSDATE + (SUM(Q2.TIMEDIFF) - MAX(Q2.TIMEDIFF) - MIN(Q2.TIMEDIFF)) / 8 + (v_BUFFER_TIME / 1440)
				INTO v_ESTIMATED_DATE
			FROM (
				SELECT PH_COLLECTION_DATE - PH_CREATED_DATE TIMEDIFF
				FROM PH_TICKET_QUEUE
				WHERE PH_LOC_ID = i_locid
				AND   PH_TICKET_DT = TO_CHAR(SYSDATE, 'YYYYMMDD')
				AND   PH_STATUS != -1
				AND   PH_COLLECTION_DATE IS NOT NULL
				ORDER BY PH_CREATED_DATE DESC) Q2
			WHERE ROWNUM <= 10
			ORDER BY ROWNUM;
		EXCEPTION
		WHEN OTHERS THEN
			v_ESTIMATED_DATE := NULL;
		END;
	END IF;

	-- only for discharge
	IF i_locid = 'DIS' AND i_patno IS NOT NULL THEN
		SELECT COUNT(1) INTO v_COUNT FROM REG@IWEB WHERE PATNO = i_patno AND REGTYPE = 'I';
		IF v_COUNT > 0 THEN
			SELECT MAX(REGID) INTO v_REGID FROM REG@IWEB WHERE PATNO = i_patno AND REGTYPE = 'I';
		END IF;
	END IF;

	INSERT INTO PH_TICKET_QUEUE (
		PH_LOC_ID, PH_TICKET_DT, PH_TICKET_QUEUE_ID, PH_EST_COMPLETED_DATE, PH_PATNO, PH_REGID
	) VALUES (
		i_locid, v_CURRDATE, v_TICKETNO, v_ESTIMATED_DATE, i_patno, v_REGID
	);

	RETURN v_TICKETNO;

END HAT_ACT_PHARMACYTICKETNO;
/
