create global temporary table HAT_BED_BOOKED_TMP (
 HAT_PERIOD DATE NOT NULL,
 HAT_WRDCODE VARCHAR2(4 BYTE) NOT NULL,
 HAT_ACMCODE VARCHAR2(1 BYTE) NOT NULL,
 HAT_ROMCODE VARCHAR2(3 BYTE) NOT NULL,
 HAT_BEDCODE VARCHAR2(8 BYTE) NULL,
 HAT_BEDSEX VARCHAR2(1 BYTE) DEFAULT 'U',
 HAT_BOOKED_OT NUMBER(*,0) DEFAULT 0,
 HAT_BOOKED_CCIC NUMBER(*,0) DEFAULT 0,
 HAT_PBPID NUMBER(22) NULL,
 HAT_PATNO VARCHAR2(10) NULL,
 HAT_PATNAME VARCHAR2(50) NULL,
 HAT_PATCNAME VARCHAR2(20) NULL,
 HAT_DOCCODE VARCHAR2(4) NULL,
 HAT_STATUS VARCHAR2(1 BYTE) NOT NULL
) on commit preserve rows;