CREATE OR REPLACE FUNCTION "HAT_GET_DOCTORONCALL" (
	i_DOCCODE VARCHAR2,
	i_DAYOFMONTH VARCHAR2
)
	RETURN VARCHAR2
AS
	v_DAYOFMONTH VARCHAR2(2) := 0;
	v_NOOFRECORD NUMBER;
	v_DATEFROM VARCHAR2(20);
	v_DATETO VARCHAR2(20);
BEGIN
	IF i_DAYOFMONTH IS NULL THEN
		RETURN i_DAYOFMONTH;
	END IF;

	IF LENGTH(i_DAYOFMONTH) = 1 THEN
		v_DAYOFMONTH := '0' || i_DAYOFMONTH;
	ELSE
		v_DAYOFMONTH := i_DAYOFMONTH;
	END IF;

	SELECT v_DAYOFMONTH || '/' || TO_CHAR(ADD_MONTHS(SYSDATE, -1), 'MM/YYYY') || ' 00:00:00' INTO v_DATEFROM FROM DUAL;
	SELECT v_DAYOFMONTH || '/' || TO_CHAR(ADD_MONTHS(SYSDATE, -1), 'MM/YYYY') || ' 23:59:59' INTO v_DATETO FROM DUAL;

	SELECT COUNT(1) INTO v_NOOFRECORD
	FROM   OPD_URGCARE@CIS
	WHERE  START_TIME >= TO_DATE(v_DATEFROM, 'DD/MM/YYYY HH24:MI:SS')
	AND    END_TIME <= TO_DATE(v_DATETO, 'DD/MM/YYYY HH24:MI:SS')
	AND    DOCCODE = i_DOCCODE;

	IF v_NOOFRECORD > 0 THEN
		RETURN '[' || v_DAYOFMONTH || ']';
	ELSE
		RETURN v_DAYOFMONTH;
	END IF;
EXCEPTION
WHEN OTHERS THEN
	RETURN v_DAYOFMONTH;
END HAT_GET_DOCTORONCALL;
/
