CREATE OR REPLACE FUNCTION "HAT_GET_DOCTORNAME" (
	i_DOCCODE VARCHAR2
)
	RETURN VARCHAR2
AS
	v_COUNT NUMBER;
	v_DOCNAME VARCHAR2(100);
BEGIN
	SELECT COUNT(1) INTO v_COUNT
	FROM   DOCTOR@IWEB
	WHERE  DOCSTS = -1
	AND    DOCCODE = i_DOCCODE;

	IF v_COUNT = 1 THEN
		SELECT TRIM(INITCAP(TITTLE || ' ' || DECODE(INSTR(DOCGNAME, ','), 0, DOCFNAME || ' ' || DOCGNAME, TRIM(SUBSTR(DOCGNAME, INSTR(DOCGNAME, ',') + 1)) || ' ' || DOCFNAME)))
		INTO   v_DOCNAME
		FROM   DOCTOR@IWEB
		WHERE  DOCSTS = -1
		AND    DOCCODE = i_DOCCODE;

		RETURN v_DOCNAME;
	ELSE
		RETURN i_DOCCODE;
	END IF;
EXCEPTION
WHEN OTHERS THEN
	RETURN i_DOCCODE;
END HAT_GET_DOCTORNAME;
/
