/*
SET SERVEROUTPUT ON
DECLARE v_PATNO		NUMBER;
BEGIN
	dbms_output.put_line (HAT_GET_NEXT_PATNO());
END;
*/
CREATE OR REPLACE FUNCTION "HAT_GET_NEXT_PATNO"
RETURN NUMBER
IS
	v_PATNO		NUMBER;
BEGIN
	-- update counter
	UPDATE SYSPARAM@IWEB
	SET    PARAM1 = LPAD(TO_CHAR(TO_NUMBER(PARAM1) + 1), GREATEST(LENGTH(TO_NUMBER(PARAM1)+1),LENGTH(PARAM1)), '0')
	WHERE  PARCDE = 'NEXTPATNO';

	-- retrieve latest patno
	SELECT PARAM1 INTO v_PATNO FROM SYSPARAM@IWEB WHERE PARCDE = 'NEXTPATNO';

	COMMIT;

	RETURN v_PATNO;
END;

/