ALTER TABLE HAT_BED_DETAIL_LOG
 DROP PRIMARY KEY CASCADE;
DROP TABLE HAT_BED_DETAIL_LOG CASCADE CONSTRAINTS;

CREATE TABLE HAT_BED_DETAIL_LOG
(
 HAT_PERIOD DATE NOT NULL,
 HAT_WRDCODE VARCHAR2(4 BYTE) NOT NULL,
 HAT_ACMCODE VARCHAR2(1 BYTE) NOT NULL,
 HAT_ROMCODE VARCHAR2(3 BYTE) NOT NULL,
 HAT_BEDCODE VARCHAR2(8 BYTE) NULL,
 HAT_STATUS VARCHAR2(1 BYTE) NULL,
 HAT_CREATED_DATE DATE DEFAULT SYSDATE,
 HAT_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 HAT_MODIFIED_DATE DATE DEFAULT SYSDATE,
 HAT_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 HAT_ENABLED NUMBER(*,0) DEFAULT 1
);

CREATE INDEX HAT_BED_DETAIL_LOG_IDX1
ON HAT_BED_DETAIL_LOG(HAT_PERIOD, HAT_WRDCODE, HAT_ACMCODE, HAT_ROMCODE, HAT_BEDCODE);
