ALTER TABLE HAT_BED_STAT
 DROP PRIMARY KEY CASCADE;
DROP TABLE HAT_BED_STAT CASCADE CONSTRAINTS;

CREATE TABLE HAT_BED_STAT
(
 HAT_PERIOD DATE NOT NULL,
 HAT_ACMCODE VARCHAR2(1 BYTE) NOT NULL,
 HAT_WRDCODE VARCHAR2(4 BYTE) NOT NULL,
 HAT_WRDCODE_ORDER NUMBER(*,0) DEFAULT 0,
 HAT_TOTAL NUMBER(*,0) DEFAULT 0,
 HAT_BOOKED NUMBER(*,0) DEFAULT 0,
 HAT_BOOKED_OT NUMBER(*,0) DEFAULT 0,
 HAT_BOOKED_CCIC NUMBER(*,0) DEFAULT 0,
 HAT_BOOKED_BOTH NUMBER(*,0) DEFAULT 0,
 HAT_OCCUPIED NUMBER(*,0) DEFAULT 0,
 HAT_AVAILABLE NUMBER(*,0) DEFAULT 0,
 HAT_AVAILABLE_M NUMBER(*,0) DEFAULT 0,
 HAT_AVAILABLE_F NUMBER(*,0) DEFAULT 0,
 HAT_AVAILABLE_X NUMBER(*,0) DEFAULT 0,
 HAT_ADJUST NUMBER(*,0) DEFAULT 0,
 HAT_CREATED_DATE DATE DEFAULT SYSDATE,
 HAT_MODIFIED_DATE DATE DEFAULT SYSDATE,
 HAT_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (HAT_PERIOD, HAT_ACMCODE, HAT_WRDCODE)
);