ALTER TABLE HAT_BED_DETAIL
 DROP PRIMARY KEY CASCADE;
DROP TABLE HAT_BED_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE HAT_BED_DETAIL
(
 HAT_PERIOD DATE NOT NULL,
 HAT_WRDCODE VARCHAR2(4 BYTE) NOT NULL,
 HAT_ACMCODE VARCHAR2(1 BYTE) NOT NULL,
 HAT_ROMCODE VARCHAR2(3 BYTE) NOT NULL,
 HAT_BEDCODE VARCHAR2(8 BYTE) NULL,
 HAT_BEDSEX VARCHAR2(1 BYTE) DEFAULT 'U',
 HAT_PATNAME VARCHAR2(50) NULL,
 HAT_PATCNAME VARCHAR2(20) NULL,
 HAT_DOCCODE VARCHAR2(4) NULL,
 HAT_STATUS VARCHAR2(1 BYTE) NULL,
 HAT_NEED_UNBLOCK VARCHAR2(1 BYTE) NULL,
 HAT_CREATED_DATE DATE DEFAULT SYSDATE,
 HAT_MODIFIED_DATE DATE DEFAULT SYSDATE,
 HAT_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (HAT_PERIOD, HAT_WRDCODE, HAT_ACMCODE, HAT_ROMCODE, HAT_BEDCODE)
);