ALTER TABLE HAT_PATIENT_ALLERGY
 DROP PRIMARY KEY CASCADE;
DROP TABLE HAT_PATIENT_ALLERGY CASCADE CONSTRAINTS;

CREATE TABLE HAT_PATIENT_ALLERGY (
    CO_SITE_CODE     VARCHAR2(4 BYTE),
    PATNO            VARCHAR2(10 BYTE),
    REGTYPE          VARCHAR2(1 BYTE),
    REGID            NUMBER(22,0),
    WRDCODE			 VARCHAR2(10 BYTE),
    BEDCODE          VARCHAR2(20 BYTE),
    ALLERGY          VARCHAR2(50 BYTE),
    CREATE_DATE DATE DEFAULT SYSDATE,
    CREATE_USER VARCHAR2(50 BYTE) DEFAULT 'SYSTEM',
    MODIFIED_DATE DATE DEFAULT SYSDATE,
    MODIFIED_USER VARCHAR2(50 BYTE) DEFAULT 'SYSTEM',
    ENABLE        NUMBER(1,0) DEFAULT 1,
    UPDATED        NUMBER(1,0) DEFAULT 1
);

COMMIT;

Insert into HAT_PATIENT_ALLERGY (CO_SITE_CODE,PATNO,REGTYPE,REGID,WRDCODE,BEDCODE,ALLERGY,CREATE_DATE,CREATE_USER,MODIFIED_DATE,MODIFIED_USER,ENABLE,UPDATED) values ('hkah','0',null,null,'U100',null,null,SYSDATE,SYSDATE,'SYSTEM',0,1);
Insert into HAT_PATIENT_ALLERGY (CO_SITE_CODE,PATNO,REGTYPE,REGID,WRDCODE,BEDCODE,ALLERGY,CREATE_DATE,CREATE_USER,MODIFIED_DATE,MODIFIED_USER,ENABLE,UPDATED) values ('hkah','0',null,null,'U200',null,null,SYSDATE,SYSDATE,'SYSTEM',0,1);
Insert into HAT_PATIENT_ALLERGY (CO_SITE_CODE,PATNO,REGTYPE,REGID,WRDCODE,BEDCODE,ALLERGY,CREATE_DATE,CREATE_USER,MODIFIED_DATE,MODIFIED_USER,ENABLE,UPDATED) values ('hkah','0',null,null,'U300',null,null,SYSDATE,SYSDATE,'SYSTEM',0,1);
Insert into HAT_PATIENT_ALLERGY (CO_SITE_CODE,PATNO,REGTYPE,REGID,WRDCODE,BEDCODE,ALLERGY,CREATE_DATE,CREATE_USER,MODIFIED_DATE,MODIFIED_USER,ENABLE,UPDATED) values ('hkah','0',null,null,'U3NW',null,null,SYSDATE,SYSDATE,'SYSTEM',0,1);
Insert into HAT_PATIENT_ALLERGY (CO_SITE_CODE,PATNO,REGTYPE,REGID,WRDCODE,BEDCODE,ALLERGY,CREATE_DATE,CREATE_USER,MODIFIED_DATE,MODIFIED_USER,ENABLE,UPDATED) values ('hkah','0',null,null,'U400',null,null,SYSDATE,SYSDATE,'SYSTEM',0,1);
