ALTER TABLE HL7_UPDATE_EMAIL
 DROP PRIMARY KEY CASCADE;
DROP TABLE HL7_UPDATE_EMAIL CASCADE CONSTRAINTS;

CREATE TABLE HL7_UPDATE_EMAIL
(
 HL7_HUEID NUMBER(*,0) NOT NULL ENABLE,
 HL7_LASTEMAILSEND_DATE DATE DEFAULT SYSDATE,
 HL7_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (HL7_HUEID)
);

INSERT INTO HL7_UPDATE_EMAIL (HL7_HUEID) VALUES ('1');