ALTER TABLE HRD_EMPLOYEE_VOTE
 DROP PRIMARY KEY CASCADE;
DROP TABLE HRD_EMPLOYEE_VOTE CASCADE CONSTRAINTS;

CREATE TABLE HRD_EMPLOYEE_VOTE
(
 HRD_SITE_CODE VARCHAR2(10 BYTE) DEFAULT 'hkah',
 HRD_NOMINATEE_STAFF_ID VARCHAR2(10 BYTE) NOT NULL,
 HRD_STAFF_ID VARCHAR2(10 BYTE) NOT NULL,
 HRD_COMMENT_DESC VARCHAR2(3000 BYTE) NOT NULL,
 HRD_COMMITTEE_FORWARD_DATE DATE NULL,
 HRD_COMMITTEE_DECISION VARCHAR2(3000 BYTE) NULL,
 HRD_FINALIST VARCHAR2(1 BYTE) NULL,
 HRD_NOT_SELECTED VARCHAR2(1 BYTE) NULL,
 HRD_NOT_RULE VARCHAR2(1 BYTE) NULL,
 HRD_CREATED_DATE DATE DEFAULT SYSDATE,
 HRD_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 HRD_MODIFIED_DATE DATE DEFAULT SYSDATE,
 HRD_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 HRD_ENABLED NUMBER(*,0) DEFAULT 1,
 HRD_NOMINATION_YEAR VARCHAR2(20 BYTE) NULL,
 HRD_ALLOWDISPLAY VARCHAR2(20 BYTE) NULL,
 PRIMARY KEY (HRD_STAFF_ID)
);
ALTER TABLE HRD_EMPLOYEE_VOTE ADD (
 CONSTRAINT HRD_EMPLOYEE_VOTE_R01
 FOREIGN KEY (HRD_SITE_CODE, HRD_STAFF_ID)
 REFERENCES CO_STAFFS (CO_SITE_CODE, CO_STAFF_ID));