CREATE TABLE "IC_BLD_MRSA_ESBL"
  (
    "IC_SITE_CODE" VARCHAR2(10 BYTE) NOT NULL ENABLE,
    "CASE_NUM"     NUMBER NOT NULL ENABLE,
    "CASE_DATE" DATE NOT NULL ENABLE,
    "LAB_NUM" VARCHAR2(8 BYTE) NOT NULL ENABLE,
    "HOSPNUM" VARCHAR2(12 BYTE) NOT NULL ENABLE,
    "PATNAME" VARCHAR2(100 BYTE),
    "PATSEX"  VARCHAR2(1 BYTE),
    "PATBDATE" DATE,
    "AGE"      VARCHAR2(3 BYTE),
    "MONTH"    VARCHAR2(3 BYTE),
    "WARD"     VARCHAR2(30 BYTE),
    "ROOM_NUM" VARCHAR2(3 BYTE),
    "BED_NUM"  VARCHAR2(8 BYTE),
    "DATE_IN" DATE,
    "SOURCE"      VARCHAR2(1 BYTE) DEFAULT 'H',
    "CASE_DEFINE" VARCHAR2(1 BYTE) DEFAULT 'N',
    "STATUS"      VARCHAR2(1 BYTE) DEFAULT 'I',
    "BODY_SYSTEM" VARCHAR2(20 BYTE) DEFAULT 'UTI',
    "BC_DATE" DATE,
    "ISOLATE_ORGAN"  VARCHAR2(100 BYTE),
    "PHX"            VARCHAR2(20 BYTE) DEFAULT 'DM',
    "CLINICAL_INFO"  VARCHAR2(200 BYTE),
    "BP_P"           VARCHAR2(10 BYTE),
    "BP_P_TEMP"      VARCHAR2(10 BYTE),
    "WCC"            VARCHAR2(10 BYTE),
    "WCC_N"          VARCHAR2(10 BYTE),
    "WCC_L"          VARCHAR2(10 BYTE),
    "DEVICE"         VARCHAR2(20 BYTE) DEFAULT 'ETT',
    "PROC"           VARCHAR2(100 BYTE),
    "CHEST_SIGN"     VARCHAR2(100 BYTE),
    "IVSITE"         VARCHAR2(20 BYTE) DEFAULT 'Pain',
    "URINARY"        VARCHAR2(20 BYTE) DEFAULT 'Dysuria',
    "OTHER_PHY_SIGN" VARCHAR2(100 BYTE),
    "ANTIBIOTICS"    VARCHAR2(100 BYTE),
    "FINAL_DISP"     VARCHAR2(10 BYTE) DEFAULT 'Home',
    "IC_CREATED_DATE" DATE DEFAULT NULL,
    "IC_CREATED_USER" VARCHAR2(30 BYTE) DEFAULT NULL,
    "IC_MODIFIED_DATE" DATE DEFAULT NULL,
    "IC_MODIFIED_USER" VARCHAR2(30 BYTE) DEFAULT NULL,
    "IC_ENABLED"       NUMBER(*,0) DEFAULT 1,
    "ICTYPE"           VARCHAR2(5 BYTE),
    "PHX_OTHER"        VARCHAR2(200 BYTE),
    "IVCATHETER"       VARCHAR2(10 BYTE),
    "IVCATHETER_OTHER" VARCHAR2(50 BYTE),
    "IVSITE_OTHER"     VARCHAR2(20 BYTE),
    "TRANSFER_TO"      VARCHAR2(50 BYTE),
    "HOSP_DEFINE"      VARCHAR2(1 BYTE) DEFAULT 'N',
    "ADMISSION_CO"     VARCHAR2(200 BYTE),
    "DEVICE_MRSA_ESBL" VARCHAR2(200 BYTE),
    "URINARY_OTHER"    VARCHAR2(20 BYTE),
    "ISOLATE"          VARCHAR2(2 BYTE),
    "STD_PRECAUTION"   VARCHAR2(1 BYTE),
    "TRAN_DATE" DATE,
    "TRANSFER" VARCHAR2(100 BYTE),
    CONSTRAINT "IC_BLD_MRSA_ESBL_PK" PRIMARY KEY ("CASE_NUM")
  );
  
CREATE INDEX "IC_BLD_MRSA_ESBL_INDEX1" ON "IC_BLD_MRSA_ESBL"
  (
    "ICTYPE",
    "CASE_NUM",
    "CASE_DATE"
  );
  
CREATE INDEX "IC_BLD_MRSA_ESBL_INDEX2" ON "IC_BLD_MRSA_ESBL"
  (
    "LAB_NUM",
    "DATE_IN",
    "HOSPNUM"
  );