CREATE TABLE "IC_GE_RESP"
  (
    "IC_SITE_CODE" VARCHAR2(10 BYTE) NOT NULL ENABLE,
    "CASE_NUM"     NUMBER NOT NULL ENABLE,
    "CASE_DATE" DATE NOT NULL ENABLE,
    "LAB_NUM" VARCHAR2(8 BYTE) NOT NULL ENABLE,
    "HOSPNUM" VARCHAR2(12 BYTE) NOT NULL ENABLE,
    "PATNAME" VARCHAR2(100 BYTE),
    "PATSEX"  VARCHAR2(1 BYTE),
    "PATBDATE" DATE,
    "AGE"      VARCHAR2(3 BYTE),
    "MONTH"    VARCHAR2(3 BYTE),
    "WARD"     VARCHAR2(30 BYTE),
    "ROOM_NUM" VARCHAR2(3 BYTE),
    "BED_NUM"  VARCHAR2(8 BYTE),
    "DATE_IN" DATE,
    "TOCC"      VARCHAR2(1 BYTE),
    "FEVER38C"  VARCHAR2(5 BYTE),
    "ADMIT_ICU" VARCHAR2(1 BYTE),
    "ONSET_DATE" DATE,
    "DV"      VARCHAR2(1 BYTE),
    "HAI_CAI" VARCHAR2(1 BYTE),
    "OAHR"    VARCHAR2(1 BYTE),
    "REMARKS" VARCHAR2(100 BYTE),
    "IC_CREATED_DATE" DATE DEFAULT NULL,
    "IC_CREATED_USER" VARCHAR2(30 BYTE) DEFAULT NULL,
    "IC_MODIFIED_DATE" DATE DEFAULT NULL,
    "IC_MODIFIED_USER" VARCHAR2(30 BYTE) DEFAULT NULL,
    "IC_ENABLED"       NUMBER(*,0) DEFAULT 1,
    "ICTYPE"           VARCHAR2(5 BYTE),
    "TOCC2"            VARCHAR2(3 BYTE),
    "ISOLATE"          VARCHAR2(2 BYTE),
    "STD_PRECAUTION"   VARCHAR2(1 BYTE),
    "TRAN_DATE" DATE,
    "TRANSFER" VARCHAR2(100 BYTE),
    CONSTRAINT "IC_GE_RESP_PK" PRIMARY KEY ("CASE_NUM")
  );
  
CREATE INDEX "IC_GE_RESP_INDEX1" ON "IC_GE_RESP"
  (
    "LAB_NUM",
    "DATE_IN",
    "HOSPNUM"
  );
  
CREATE INDEX "IC_GE_RESP_INDEX2" ON "IC_GE_RESP"
  (
    "ICTYPE",
    "CASE_NUM",
    "CASE_DATE"
  );