CREATE TABLE "IC_ICU_DAILY"
  (
    "IC_SITE_CODE" VARCHAR2(10 BYTE) NOT NULL ENABLE,
    "CASE_NUM"     NUMBER NOT NULL ENABLE,
    "HOSP_ADM_DATE" DATE NOT NULL ENABLE,
    "LAB_NUM" VARCHAR2(8 BYTE) NOT NULL ENABLE,
    "HOSPNUM" VARCHAR2(12 BYTE) NOT NULL ENABLE,
    "PATNAME" VARCHAR2(100 BYTE),
    "PATSEX"  VARCHAR2(1 BYTE),
    "PATBDATE" DATE,
    "AGE"      VARCHAR2(3 BYTE),
    "MONTH"    VARCHAR2(3 BYTE),
    "WARD"     VARCHAR2(30 BYTE),
    "ROOM_NUM" VARCHAR2(3 BYTE),
    "BED_NUM"  VARCHAR2(8 BYTE),
    "DATE_IN" DATE,
    "REC_DATE" DATE,
    "TEMP"        VARCHAR2(10 BYTE),
    "WBC"         VARCHAR2(10 BYTE),
    "BP"          VARCHAR2(10 BYTE),
    "UO"          VARCHAR2(10 BYTE),
    "VENT_FIO2"   VARCHAR2(50 BYTE),
    "CXR"         VARCHAR2(50 BYTE),
    "RESP_SS"     VARCHAR2(20 BYTE),
    "PROGRESS"    VARCHAR2(100 BYTE),
    "ANTIBIOTICS" VARCHAR2(100 BYTE),
    "LAB_RESULT"  VARCHAR2(100 BYTE),
    "IC_CREATED_DATE" DATE DEFAULT NULL,
    "IC_CREATED_USER" VARCHAR2(30 BYTE) DEFAULT NULL,
    "IC_MODIFIED_DATE" DATE DEFAULT NULL,
    "IC_MODIFIED_USER" VARCHAR2(30 BYTE) DEFAULT NULL,
    "IC_ENABLED"       NUMBER(*,0) DEFAULT 1,
    "ICTYPE"           VARCHAR2(5 BYTE),
    CONSTRAINT "IC_ICU_DAILY_PK" PRIMARY KEY ("CASE_NUM")
  );
  
  
CREATE INDEX "IC_ICU_DAILY_INDEX1" ON "IC_ICU_DAILY"
  (
    "LAB_NUM",
    "DATE_IN",
    "HOSPNUM"
  );
  
CREATE INDEX "IC_ICU_DAILY_INDEX2" ON "IC_ICU_DAILY"
  (
    "ICTYPE",
    "CASE_NUM",
    "HOSP_ADM_DATE"
  );