CREATE TABLE "IC_INFORMATION_PAGE"
  (
    "IC_PAGE_CATEGORY"  VARCHAR2(20 BYTE) NOT NULL ENABLE,
    "IC_INFORMATION_ID" NUMBER NOT NULL ENABLE,
    "IC_PAGE_DESC"      VARCHAR2(500 BYTE),
    "IC_PAGE_LINK"      VARCHAR2(500 BYTE),
    "IC_EVENT_DATE" DATE,
    "IC_CREATED_DATE" DATE DEFAULT SYSDATE,
    "IC_CREATED_USER" VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
    "IC_MODIFIED_DATE" DATE DEFAULT SYSDATE,
    "IC_MODIFIED_USER" VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
    "IC_ENABLED"       NUMBER(*,0) DEFAULT 1,
    PRIMARY KEY ("IC_PAGE_CATEGORY", "IC_INFORMATION_ID")
  )