create or replace
FUNCTION "NHS_CMB_DOCTOR_ORDERBYNAME"
  RETURN TYPES.CURSOR_TYPE AS
  OUTCUR TYPES.CURSOR_TYPE;
BEGIN
  OPEN OUTCUR FOR
    SELECT DOCCODE, DOCFNAME || ' ' || DOCGNAME
      FROM DOCTOR@IWEB
     WHERE DOCSTS = -1
     ORDER BY 2;
  RETURN OUTCUR;
END NHS_CMB_DOCTOR_ORDERBYNAME;