create or replace
Function "NHS_LIS_TASK_CP"
(
	p_SITE_CODE IN VARCHAR2,
	p_YEAR IN VARCHAR2,
	p_DEPT_CODE IN VARCHAR2,
  p_PLAN_ID IN VARCHAR2,
  p_GOAL_ID IN VARCHAR2,
  p_TASK_ID IN VARCHAR2
)
  RETURN Types.Cursor_Type
As
  OUTCUR TYPES.cursor_type;
Begin 
    OPEN OUTCUR FOR
    SELECT DECODE(T.DS_SITE_CODE, 'hkah', 'HK', 'twah', 'TW', 'BH'),
           T.DS_DEPARTMENT_CODE, T.DS_FINANCIAL_YEAR,
           T.DS_PLAN_ID, P.DS_SUBJECT,
           T.DS_GOAL_ID, M.DS_DESC,
           T.DS_TASK_ID, T.DS_TASK_DESC,
           '',
           '',
           TO_CHAR(T.DS_EST_COMPLETE_DATE, 'DD/MM/YYYY'),
           TO_CHAR(T.DS_COMPLETE_DATE, 'DD/MM/YYYY')
    FROM   DS_CORPORATE_PLAN P, DS_GOAL M, DS_TASK T
    WHERE  T.DS_ENABLED = 1
    AND    T.DS_SITE_CODE = P.DS_SITE_CODE
    AND    T.DS_DEPARTMENT_CODE = P.DS_DEPARTMENT_CODE
    AND    T.DS_FINANCIAL_YEAR = P.DS_FINANCIAL_YEAR
    AND    T.DS_PLAN_ID = P.DS_PLAN_ID
    AND    T.DS_SITE_CODE = M.DS_SITE_CODE
    AND    T.DS_DEPARTMENT_CODE = M.DS_DEPARTMENT_CODE
    AND    T.DS_FINANCIAL_YEAR = M.DS_FINANCIAL_YEAR
    AND    T.DS_PLAN_ID = M.DS_PLAN_ID
    AND    T.DS_GOAL_ID = M.DS_GOAL_ID
    AND    UPPER(T.DS_SITE_CODE) LIKE p_SITE_CODE || '%'
    AND    T.DS_FINANCIAL_YEAR = p_YEAR
    AND    T.DS_DEPARTMENT_CODE = p_DEPT_CODE
    AND    T.DS_PLAN_ID = p_PLAN_ID
    AND   (p_GOAL_ID IS NULL OR T.DS_GOAL_ID = p_GOAL_ID)
    ORDER BY T.DS_SITE_CODE, T.DS_DEPARTMENT_CODE, T.DS_FINANCIAL_YEAR;
    RETURN OUTCUR; 
END NHS_LIS_TASK_CP;