create or replace
FUNCTION NHS_RPT_PR_FORM (
  v_PrNo VARCHAR2
)
  RETURN Types.cursor_type
AS
  outcur types.cursor_type;
BEGIN
  OPEN outcur FOR
  SELECT 
  PPM.PUR_NO, 
  TO_CHAR(TO_DATE(PPM.PUR_DATE,'YYYYMMDD'),'DD/MM/YYYY') AS PR_DATE, 
  TRIM(PN.DEPT_ENAME) AS PR_DEPT,
  (SELECT TRIM(SUB.USER_NAME) FROM SYS_USER_BASIC@TAH SUB WHERE TRIM(SUB.USER_ID) = TRIM(PPM.PUR_OP) OR TRIM(SUB.USER_ALIAS) = TRIM(PPM.PUR_OP)) AS REQ_BY,
  PN.AREA,
  PPM.APPROVE_FLAG,
  (SELECT TRIM(SUB.USER_NAME) FROM SYS_USER_BASIC@TAH SUB WHERE TRIM(SUB.USER_ID) = TRIM(PPM.APPROVE_BY) OR TRIM(SUB.USER_ALIAS) = TRIM(PPM.APPROVE_BY)) AS APPROVE_BY,
  TO_CHAR(TO_DATE(PPM.APPROVE_DATE,'YYYYMMDDHH24MI'),'DD/MM/YYYY') AS APPROVE_DATE
  FROM PMS_PUR_M@TAH PPM, PN_DEPT@TAH PN
  WHERE PPM.PUR_DEPT = PN.DEPT_ID(+)
  AND PPM.PUR_NO = v_PrNo;
RETURN OUTCUR;
END NHS_RPT_PR_FORM;