create or replace
FUNCTION "NHS_CMB_ARCODE"
  RETURN Types.CURSOR_type
AS
  outcur types.cursor_type;
BEGIN
  OPEN OUTCUR FOR
      SELECT ARCCODE, ARCNAME
      FROM ARCODE@IWEB
      ORDER BY ARCCODE;
   RETURN OUTCUR;
END NHS_CMB_ARCODE;