create or replace
FUNCTION "NHS_LIS_REGPKGLINK"(V_PATNO IN VARCHAR2)
  RETURN TYPES.CURSOR_TYPE AS
  OUTCUR TYPES.CURSOR_TYPE;
BEGIN
  OPEN OUTCUR FOR
    SELECT L.PKGCODE, K.PKGNAME
      FROM PACKAGE@IWEB K, REGPKGLINK@IWEB L, PATIENT@IWEB P
     WHERE P.REGID_C = L.REGID
       AND L.PKGCODE = K.PKGCODE
       AND P.PATNO = V_PATNO;
  RETURN OUTCUR;
END NHS_LIS_REGPKGLINK;