create or replace
FUNCTION NHS_LIS_ARCODE (
  V_ARCCODE ARCODE.ARCCODE@IWEB%TYPE
)
  RETURN Types.cursor_type
AS
  OUTCUR TYPES.CURSOR_TYPE;
  SQLSTR VARCHAR2(3000);
BEGIN
/*
 SQLSTR := '
      SELECT
        ARLMTAMT, CVREDATE, COPAYTYP, COPAYAMT, FURGRTAMT, FURGRTDATE, ITMTYPED, ITMTYPEH, ITMTYPES, ITMTYPEO
      FROM ARCODE@IWEB
      WHERE TRIM(ARCCODE) = TRIM('||V_ARCCODE||')';
  OPEN OUTCUR FOR SQLSTR;
*/
  open outcur for
    SELECT
    ARLMTAMT, TO_CHAR(CVREDATE,'dd/MM/yyyy'), COPAYTYP, COPAYAMT, FURGRTAMT, FURGRTDATE, ITMTYPED, ITMTYPEH, ITMTYPES, ITMTYPEO, TO_CHAR(NCTRSDATE,'dd/MM/yyyy'), TO_CHAR(NCTREDATE,'dd/MM/yyyy')
    FROM ARCODE@IWEB
    WHERE ARCCODE = V_ARCCODE;
  RETURN OUTCUR;
END NHS_LIS_ARCODE;