create or replace
FUNCTION NHS_GET_TRANSACTION_DETAIL
(v_SLPNO SLIP.SLPNO@IWEB%TYPE)
  RETURN Types.cursor_type
AS
  outcur Types.cursor_type;
BEGIN
  OPEN outcur FOR
    SELECT
      S.SLPNO, S.REGID, S.SLPTYPE, S.SLPSTS, S.DPTCODE, S.SLPCAMT, S.SLPDAMT,
      S.SLPPAMT,
      S.SLPCAMT + S.SLPDAMT + S.SLPPAMT AS BALANCE,
      P.PATNO,
      NVL(S.SLPFNAME, P.PATFNAME) AS PATFNAME,
      NVL(S.SLPGNAME, P.PATGNAME) AS PATGNAME,
      I.BEDCODE, B.EXTPHONE,
      TO_CHAR(R.REGDATE, 'dd/MM/YYYY HH24:MI:SS'),
      D.DOCCODE, D.DOCFNAME, D.DOCGNAME, I.ACMCODE,
      TO_CHAR(I.INPDDATE, 'dd/MM/YYYY HH24:MI:SS'),
      SP.SPCNAME, I.INPID, S.PATREFNO, S.PCYID, S.SLPPLYNO, S.SLPVCHNO, S.ARCCODE,
      DECODE(P.PATSTAFF, -1, 'Y', 'N'),
      S.SLPREMARK, S.COPAYTYP, S.ARLMTAMT,
      TO_CHAR(S.CVREDATE, 'dd/MM/YYYY'), S.COPAYAMT,
      DECODE(S.ITMTYPEH, 0, 'N', 'Y'),
      DECODE(S.ITMTYPED, 0, 'N', 'Y'),
      DECODE(S.ITMTYPES, 0, 'N', 'Y'),
      DECODE(S.ITMTYPEO, 0, 'N', 'Y'),
      S.FURGRTAMT,
      TO_CHAR(S.FURGRTDATE, 'dd/MM/YYYY'),
      TO_CHAR(S.PRINTDATE, 'dd/MM/YYYY'),
      S.COPAYAMTACT, S.RMKMODUSR, to_char(S.RMKMODDT,'dd/MM/YYYY HH24:MI:SS'), S.SLPUSEAR,
      DECODE(S.SLPMANALL, -1, 'Y', 'N'),
      S.SLPREMARK, S.SLPHDISC, S.SLPDDISC, S.SLPSDISC
    FROM ACM@IWEB A, BED@IWEB B, DOCTOR@IWEB D, INPAT@IWEB I, PATIENT@IWEB P, REG@IWEB R, SLIP@IWEB S, SPEC@IWEB SP
    WHERE S.REGID = R.REGID(+)
    AND S.PATNO = P.PATNO(+)
    AND R.INPID = I.INPID(+)
    AND S.DOCCODE = D.DOCCODE
    AND D.SPCCODE = SP.SPCCODE
    AND I.BEDCODE = B.BEDCODE(+)
    AND I.ACMCODE = A.ACMCODE(+)
    AND S.SLPNO = v_SLPNO;
  RETURN outcur;
END NHS_GET_TRANSACTION_DETAIL;