create or replace
FUNCTION "NHS_GET_LOCATION"
(V_LOCCODE LOCATION.LOCCODE@IWEB%type)
  RETURN Types.cursor_type
AS
  outcur types.cursor_type;
BEGIN
  OPEN outcur FOR
      SELECT L.LOCCODE, L.LOCNAME, L.DSTCODE, D.DSTNAME, L.STECODE
      FROM   LOCATION@IWEB L, DISTRICT@IWEB D
      WHERE  LOCCODE = v_LOCCODE
      AND    L.DSTCODE = D.DSTCODE(+)
      AND    ROWNUM < 100
      ORDER BY L.LOCCODE;
   RETURN OUTCUR;
END NHS_GET_LOCATION;