create or replace
FUNCTION "NHS_GET_BOOKING"(V_BKGID IN VARCHAR2)
  RETURN TYPES.CURSOR_TYPE
AS
  OUTCUR TYPES.CURSOR_TYPE;
  v_DOC_TYPE VARCHAR(1);
  v_EDC_MONTH DATE;
  v_count INTEGER;
BEGIN
	SELECT COUNT(1) INTO v_count FROM OB_BOOKINGS WHERE OB_BKG_ID = V_BKGID AND OB_ENABLED = 1;
	IF v_count > 0 THEN
		SELECT OB_DOC_TYPE, OB_ESTIMATE_DELIVERYDATE INTO v_DOC_TYPE, v_EDC_MONTH FROM OB_BOOKINGS WHERE OB_BKG_ID = V_BKGID AND OB_ENABLED = 1;
	END IF;

	OPEN OUTCUR FOR
		SELECT B.PATNO,
			B.BKGPNAME,
			B.BKGPCNAME,
			B.BKGPTEL,
			B.BKGMTEL,
			B.BKGRMK,
			B.BKSID,
			B.SMS,
			B.SMCID,
			v_DOC_TYPE,
			TO_CHAR(v_EDC_MONTH, 'mm')
		FROM  BOOKING@IWEB B, SCHEDULE@IWEB S, DOCTOR@IWEB D, PATIENT@IWEB P
		WHERE B.SCHID = S.SCHID
		AND   S.DOCCODE = D.DOCCODE
		AND   B.PATNO = P.PATNO(+)
		AND   B.BKGID = V_BKGID;
	RETURN OUTCUR;
END NHS_GET_BOOKING;