create or replace
FUNCTION "NHS_CMB_DOCTOR_SPECIALTY"
  RETURN TYPES.CURSOR_TYPE AS
  OUTCUR TYPES.CURSOR_TYPE;
BEGIN
  OPEN OUTCUR FOR
    SELECT D.DOCCODE, S.SPCNAME
      FROM SPEC@IWEB S, DOCTOR@IWEB D
     WHERE D.SPCCODE = S.SPCCODE
       AND D.DOCSTS = -1
     ORDER BY S.SPCNAME;
  RETURN OUTCUR;
END NHS_CMB_DOCTOR_SPECIALTY;