create or replace
FUNCTION "NHS_CMB_EDULEVEL"
  RETURN Types.CURSOR_type
AS
  outcur types.cursor_type;
BEGIN
  OPEN OUTCUR FOR
      SELECT EDUID, DESCRIPTION
      FROM EDULEVEL@IWEB
      WHERE ROWNUM < 100
      ORDER BY EDUID;
   RETURN OUTCUR;
END NHS_CMB_EDULEVEL;