create or replace
FUNCTION "NHS_LIS_BEDPREBOK"(V_PBPID IN VARCHAR2)
  RETURN TYPES.CURSOR_TYPE AS
  OUTCUR TYPES.CURSOR_TYPE;
BEGIN
  OPEN OUTCUR FOR
    SELECT B.PBPID,
           B.DOCCODE,
           TO_CHAR(B.BPBODATE, 'DD/MM/YYYY HH24:MI:SS'),
           TO_CHAR(B.BPBHDATE, 'DD/MM/YYYY HH24:MI:SS'),
           B.USRID,
           B.BPBSTS,
           B.STECODE,
           B.PATNO,
           B.BPBPNAME,
           B.BPBCNAME,
           B.ACMCODE,
           B.WRDCODE,
           B.BPBRMK,
           B.OTAID,
           B.ARCCODE,
           B.COPAYTYP,
           B.COPAYAMT,
           B.POLICY,
           B.ARLMTAMT,
           TO_CHAR(B.CVREDATE, 'DD/MM/YYYY HH24:MI'),
           B.ISDOCTOR,
           B.ISSPECIAL,
           B.ISHOSPITAL,
           B.ISOTHER,
           B.VOUCHER,
           B.PATFNAME,
           B.PATGNAME,
           B.ISMAINLAND,
           B.FORDELIVERY,
           B.PATKHTEL,
           B.PATPAGER,
           B.PATIDNO,
           B.BPBTYPE,
           B.BPBNO,
           B.CABLABRMK,
           B.BEDCODE,
           TO_CHAR(B.BEDTIME, 'DD/MM/YYYY HH24:MI'),
           B.SEX,
           B.SLPNO,
           B.EDITUSER,
           TO_CHAR(B.EDITDATE, 'DD/MM/YYYY HH24:MI'),
           B.ISREFUSED,
           B.REFUSEREASON,
           B.REFUSEDUSERID,
           TO_CHAR(B.REFUSEDDATE, 'DD/MM/YYYY HH24:MI'),
           B.ACTIVATEDUSERID,
           TO_CHAR(B.ACTIVATEDDATE, 'DD/MM/YYYY HH24:MI'),
           B.FURGRTAMT,
           TO_CHAR(B.FURGRTDATE,'DD/MM/YYYY'),
           B.ESTSTAYLEN,
           B.PATDOCTYPE,
           B.HUSDOCNO,
           B.HUSDOCTYPE,
           B.HUSGNAME,
           B.HUSFNAME,
           B.SMSSENTDT,
           B.EMAILSENTDT,
           B.FA_PATNO,
           B.FA_HKIC,
           B.FA_CNAME,
           TO_CHAR(B.FA_DOB,'DD/MM/YYYY'),
           B.FA_TEL,
           B.FA_HKIDHOLDER,
           B.FA_RESIDENCE,
           DECODE(B.FA_BIRTHEXACTFLAG, '-1', 'Y', '0', 'N'),
           B.FA_INFOSOURCE,
           TO_CHAR(B.ANTCHKDT1,'DD/MM/YYYY'),
           TO_CHAR(B.ANTCHKDT2,'DD/MM/YYYY'),
           TO_CHAR(B.ANTCHKDT3,'DD/MM/YYYY'),
           TO_CHAR(B.ANTCHKDT4,'DD/MM/YYYY'),
           TO_CHAR(B.ANTCHKDT5,'DD/MM/YYYY'),
           TO_CHAR(B.ANTCHKDT6,'DD/MM/YYYY'),
           TO_CHAR(B.ANTCHKDT7,'DD/MM/YYYY'),
           TO_CHAR(B.ANTCHKDT8,'DD/MM/YYYY'),
           TO_CHAR(B.ANTCHKDT9,'DD/MM/YYYY'),
           TO_CHAR(B.ANTCHKDT10,'DD/MM/YYYY'),
           U1.USRNAME,
           U2.USRNAME
      FROM BEDPREBOK@IWEB B, USR@IWEB U1, USR@IWEB U2
     WHERE B.PBPID = V_PBPID
     AND   B.REFUSEDUSERID = U1.USRID (+)
     AND   B.ACTIVATEDUSERID = U2.USRID (+);
  RETURN OUTCUR;
END NHS_LIS_BEDPREBOK;