create or replace
FUNCTION "NHS_CMB_GOAL"
(
	p_SITE_CODE IN VARCHAR2,
	p_YEAR IN VARCHAR2,
	p_DEPT_CODE IN VARCHAR2,
  p_PLAN_ID IN VARCHAR2
)
	RETURN Types.cursor_type
AS
	outcur types.cursor_type;
BEGIN
	OPEN outcur FOR
    SELECT DISTINCT DS_GOAL_ID, DS_DESC
		FROM   DS_GOAL
		WHERE  DS_ENABLED = 1
    AND    UPPER(DS_SITE_CODE) LIKE p_SITE_CODE || '%'
    AND    DS_FINANCIAL_YEAR = p_YEAR
    AND    DS_DEPARTMENT_CODE = p_DEPT_CODE
    AND    DS_PLAN_ID = p_PLAN_ID
		ORDER  BY DS_DESC;
	RETURN outcur;
END NHS_CMB_GOAL;