create or replace
FUNCTION "NHS_LIS_PREBOKDUPLICATE"(V_PATNO    IN VARCHAR2,
                                                     V_PATIDNO  IN VARCHAR2,
                                                     V_PATFNAME IN VARCHAR2,
                                                     V_PATGNAME IN VARCHAR2)
  RETURN TYPES.CURSOR_TYPE AS
  OUTCUR    TYPES.CURSOR_TYPE;
  V_BPDAY   NUMBER;
  V_BPDOC   NUMBER;
  V_BPGN    NUMBER;
  V_CHKFLAG VARCHAR2(10);
  PATGNAME  VARCHAR2(20);
  SQLSTR    VARCHAR2(500);
  SQLSTR2   VARCHAR2(5000);
  SQLSTR3   VARCHAR2(5000);
  WHERESQL1 VARCHAR2(500);
  WHERESQL2 VARCHAR2(500);
  WHERESQL3 VARCHAR2(500);
  NAMELEN   NUMBER;
BEGIN
  SELECT PARAM1 INTO V_CHKFLAG FROM SYSPARAM@IWEB WHERE PARCDE = 'DUPBPCHKF';
  IF V_CHKFLAG = 'Y' THEN
    SELECT TO_NUMBER(PARAM1) INTO V_BPDAY
      FROM SYSPARAM@IWEB WHERE PARCDE = 'DUPBPDAY';
    SELECT TO_NUMBER(PARAM1)  INTO V_BPDOC
      FROM SYSPARAM@IWEB WHERE PARCDE = 'DUPBPDOC';
    SELECT TO_NUMBER(PARAM1) INTO V_BPGN
      FROM SYSPARAM@IWEB WHERE PARCDE = 'DUPBPGN';
    IF V_BPDAY < 1 THEN
      V_BPDAY := 1;
    END IF;
    IF V_BPDOC < 1 THEN
      V_BPDOC := 1;
    END IF;
    IF V_BPGN < 1 THEN
      V_BPGN := 1;
    END IF;

    SQLSTR := '
    SELECT PBPID FROM BEDPREBOK@IWEB
     WHERE BPBSTS = ''N''
       AND TRUNC(BPBHDATE) BETWEEN TRUNC(SYSDATE) AND
           TRUNC(SYSDATE) + TO_NUMBER(''' || V_BPDAY || ''')';
    IF V_PATNO IS NOT NULL THEN
      WHERESQL1 := ' AND PATNO=''' || V_PATNO || '''';
    END IF;
    IF V_PATIDNO IS NOT NULL THEN
      WHERESQL2 := ' ';
      IF V_PATNO IS NOT NULL THEN
        WHERESQL2 := ' AND PATNO IS NULL ';
      END IF;
      WHERESQL2 := WHERESQL2 ||
                   ' AND SUBSTR(REPLACE(UPPER(PATIDNO),'' '',''''),1,' ||
                   V_BPDOC || ')=''' || V_PATIDNO || '''';
    END IF;
    IF V_PATFNAME IS NOT NULL AND V_PATGNAME IS NOT NULL THEN
      WHERESQL3 := ' ';
      NAMELEN   := ROUND(LENGTH(V_PATGNAME) * TO_NUMBER(V_BPGN) / 100);
      PATGNAME  := SUBSTR(V_PATGNAME, 1, NAMELEN);
      IF V_PATNO IS NOT NULL THEN
        WHERESQL3 := WHERESQL3 || ' AND PATNO IS NULL ';
      END IF;
      IF V_PATIDNO IS NOT NULL THEN
        WHERESQL3 := WHERESQL3 || ' AND PATIDNO IS NULL ';
      END IF;
      WHERESQL3 := WHERESQL3 || ' AND UPPER(PATFNAME)=UPPER(''' ||
                   V_PATFNAME || ''') AND SUBSTR(UPPER(PATGNAME),1,' ||
                   NAMELEN || ')=UPPER(''' || PATGNAME || ''')';
    END IF;
    IF LENGTH(WHERESQL1) > 1 THEN
      IF SQLSTR2 IS NULL THEN
        SQLSTR2 := SQLSTR || WHERESQL1;
      ELSE
        SQLSTR2 := SQLSTR2 || ' UNION ' || SQLSTR || WHERESQL1;
      END IF;
    END IF;
    IF LENGTH(WHERESQL2) > 1 THEN
      IF SQLSTR2 IS NULL THEN
        SQLSTR2 := SQLSTR || WHERESQL2;
      ELSE
        SQLSTR2 := SQLSTR2 || ' UNION ' || SQLSTR || WHERESQL2;
      END IF;
    END IF;
    IF LENGTH(WHERESQL3) > 1 THEN
      IF SQLSTR2 IS NULL THEN
        SQLSTR2 := SQLSTR || WHERESQL3;
      ELSE
        SQLSTR2 := SQLSTR2 || ' UNION ' || SQLSTR || WHERESQL3;
      END IF;
    END IF;

    SQLSTR3 := '
  SELECT '''',
           UPPER(B.PATFNAME || '' '' || B.PATGNAME) AS PATNAME,
           B.PATNO,
           B.PATIDNO,
           (SELECT D.DOCFNAME || '' '' || D.DOCGNAME || '' ('' || B.DOCCODE || '')''
              FROM DOCTOR@IWEB D
             WHERE D.DOCCODE = B.DOCCODE) AS DOCNAME,
           B.WRDCODE,
           TO_CHAR(B.BPBHDATE, ''DD/MM/YYYY HH24:MI:SS'') AS HOSDATE,
           TO_CHAR(B.BPBODATE, ''DD/MM/YYYY HH24:MI:SS'') AS ORDDATE,
           C.USRNAME AS CREATEUSERNAME
      FROM BEDPREBOK@IWEB B,USR@IWEB C
      WHERE B.USRID=C.USRID
     AND B.PBPID IN (' || SQLSTR2 ||
               ') ORDER BY PATNAME,HOSDATE';
  ELSE
    SQLSTR3 := 'SELECT * FROM DUAL WHERE 1=2';
  END IF;

  OPEN OUTCUR FOR SQLSTR3;
  RETURN OUTCUR;
END NHS_LIS_PREBOKDUPLICATE;