create or replace
FUNCTION      "NHS_GET_ARCODEBYACODE"(V_ARCCODE IN VARCHAR2)
  RETURN TYPES.CURSOR_TYPE AS
  OUTCUR TYPES.CURSOR_TYPE;
BEGIN
  OPEN OUTCUR FOR
    SELECT COPAYTYP,
           COPAYAMT,
           ARLMTAMT,
           TO_CHAR(CVREDATE,'DD/MM/YYYY'),
           ITMTYPED,
           ITMTYPEH,
           ITMTYPES,
           ITMTYPEO,
           FURGRTAMT,
           TO_CHAR(FURGRTDATE,'DD/MM/YYYY')
      FROM ARCODE@IWEB
     WHERE ARCCODE = V_ARCCODE;
  RETURN OUTCUR;
END;