ALTER TABLE NUROB_DELI_RM
 DROP PRIMARY KEY CASCADE;
DROP TABLE NUROB_DELI_RM CASCADE CONSTRAINTS;

CREATE TABLE NUROB_DELI_RM
(
 NUROB_SITE_CODE VARCHAR2(10 BYTE) NOT NULL,		-- {'hkah', 'twah'}
 NUROB_DELI_RM_ID NUMBER(*,0) NOT NULL,				-- Ref. No.
 NUROB_MO_PATNO VARCHAR2(10 BYTE),					-- Mother's Hosp. No.
 NUROB_MO_PATNAME VARCHAR2(40 BYTE),				-- Mother's Name
 NUROB_MO_PATFNAME VARCHAR2(20 BYTE),				-- Mother's Name (First name)
 NUROB_MO_PATGNAME VARCHAR2(20 BYTE),				-- Mother's Name (Given name)
 NUROB_MO_PATCNAME VARCHAR2(10 BYTE),				-- Mother's Name (Chinese name)
 NUROB_PHYS_STAFF_ID VARCHAR2(10 BYTE),				-- Physician (Link to CO_STAFFS.CO_STAFF_ID)
 NUROB_PHYS_NAME VARCHAR2(20 BYTE),					-- Physician (Name, if NUROB_PHYS_STAFF_ID is null)
 NUROB_AGE NUMBER(3,0),								-- Age
 NUROB_GRAV VARCHAR2(1 BYTE),						-- Grav.
 NUROB_PARA VARCHAR2(1 BYTE),						-- Para.
 NUROB_EDC DATE,									-- E.D.C.
 NUROB_ABN_MAT_HIS VARCHAR2(200 BYTE),				-- Abnormal Maternal History
 NUROB_ANC VARCHAR2(1 BYTE),						-- ANC
 NUROB_OPD_VISITS VARCHAR2(3 BYTE),					-- O.P.D. Visits
 NUROB_FEED VARCHAR2(2 BYTE),						-- Feed
 NUROB_RUBELLA_TITER VARCHAR2(2 BYTE),				-- Rubella Titer
 NUROB_HBSAG VARCHAR2(2 BYTE),						-- HBsAg {'P', 'N'} (Positive or Negative)
 NUROB_VDRL VARCHAR2(2 BYTE),						-- VDRL {'NR'}
 NUROB_HIV VARCHAR2(2 BYTE),						-- HIV {'P', 'N'} (Positive or Negative)
 NUROB_INDU_PE2 VARCHAR2(1 BYTE),					-- Induction PE2 {'P', 'N'}		
 NUROB_INDU_PIT VARCHAR2(1 BYTE),					-- Induction PIT {'P', 'N'}
 NUROB_IOL_REASON VARCHAR2(200 BYTE),				-- Reason od IOL
 NUROB_POSITION VARCHAR2(2 BYTE),					-- {'Vx'}
 NUROB_ANESTHESIA VARCHAR2(2 BYTE),					-- Anesthesia
 NUROB_DELI_DATE DATE,								-- Delivery date and time
 NUROB_MODE_REASON VARCHAR2(400 BYTE),				-- Mode & Reason of Delivery
 NUROB_EPI_REPAIR VARCHAR2(20 BYTE),				-- Episiotomy & Repair
 NUROB_PLACENTA VARCHAR2(20 BYTE),					-- Placenta
 NUROB_LABO_DURA NUMBER(*,0),						-- labour Duration (number of seconds)
 NUROB_APGAR_FROM NUMBER(2,0),						-- Apgar (between from) {1-10}
 NUROB_APGAR_TO NUMBER(2,0),						-- Apgar (between to) {1-10}
 NUROB_SEX CHAR(1 BYTE),							-- Sex {'F', 'M'}
 NUROB_WEIGHT NUMBER(4,0),							-- Weight
 NUROB_POST_NATAL VARCHAR2(200 BYTE),				-- Post-natal Complication & Condition of Baby
 NUROB_NUR_ASSIST_NAME VARCHAR2(20 BYTE),			-- Nurses Assist
 NUROB_NUR_CIRC_NAME VARCHAR2(20 BYTE),				-- Nurses Circ.
 NUROB_CREATED_DATE DATE DEFAULT SYSDATE,
 NUROB_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 NUROB_MODIFIED_DATE DATE DEFAULT SYSDATE,
 NUROB_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 NUROB_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (NUROB_SITE_CODE, NUROB_DELI_RM_ID)
);