create or replace
FUNCTION OB_BOOKING_GET ( i_bookingID VARCHAR2, i_pbpID VARCHAR2 )
RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
	v_ward_code VARCHAR2(10);
	v_pbpID VARCHAR2(10);
	v_count INTEGER;
	v_edccount INTEGER;
BEGIN
	v_pbpID := i_pbpID;
	v_count := 0;
	v_edccount := 0;

	IF i_bookingID IS NOT NULL THEN
		SELECT COUNT(1) INTO v_count FROM OB_BOOKINGS WHERE OB_BOOKING_ID = i_bookingID AND OB_BOOKING_STATUS = 'B';
		IF v_count = 1 THEN
			SELECT OB_PBP_ID INTO v_pbpID FROM OB_BOOKINGS WHERE OB_BOOKING_ID = i_bookingID AND OB_BOOKING_STATUS = 'B';
		END IF;
		SELECT COUNT(1) INTO v_edccount FROM OB_BOOKING_HISTORY WHERE OB_BOOKING_ID = i_bookingID AND OB_EXPECTED_DELIVERYDATE IS NOT NULL;
	ELSIF v_pbpID IS NOT NULL THEN
		v_count := 1;
	END IF;

	IF v_count = 1 THEN
		-- get ward code
		SELECT PARAM1 INTO v_ward_code FROM SYSPARAM@IWEB WHERE PARCDE = 'obwardcode';

		OPEN OUTCUR FOR
		SELECT B.OB_BOOKING_ID, BB.PBPID,
		       BB.DOCCODE, D.DOCFNAME || ' ' || D.DOCGNAME, BB.PATNO,
		       BB.PATFNAME, BB.PATGNAME, BB.BPBCNAME,
		       BB.PATPAGER, TO_CHAR(B.OB_DOB, 'dd/MM/YYYY'), BB.PATDOCTYPE, BB.PATIDNO,
		       TO_CHAR(B.OB_ESTIMATE_DELIVERYDATE, 'dd/MM/YYYY'),
		       TO_CHAR(BB.BPBHDATE, 'dd/MM/YYYY'),
		       BB.HUSFNAME, BB.HUSGNAME, BB.FA_CNAME,
		       BB.FA_TEL, TO_CHAR(BB.FA_DOB, 'dd/MM/YYYY'),
		       DECODE(BB.HUSDOCTYPE, '9', (DECODE(BB.FA_HKIDHOLDER, 'Y', '9Y', '9')), BB.HUSDOCTYPE),
		       BB.HUSDOCNO,
		       TO_CHAR(B.OB_CHECKED_DATE1, 'dd/MM/YYYY'),
		       TO_CHAR(B.OB_CHECKED_DATE2, 'dd/MM/YYYY'),
		       TO_CHAR(B.OB_CHECKED_DATE3, 'dd/MM/YYYY'),
		       TO_CHAR(B.OB_CHECKED_DATE4, 'dd/MM/YYYY'),
		       TO_CHAR(B.OB_CHECKED_DATE5, 'dd/MM/YYYY'),
		       B.OB_LAB_TEST_READY, B.OB_CANCEL_REASON, TO_CHAR(B.OB_HOLD_EXPIRY_DATE, 'dd/MM/YYYY'), DECODE(BB.BPBSTS, 'D', 'X', 'B'),
		       v_edccount,
		       BB.BPBRMK
		FROM   BEDPREBOK@IWEB BB, OB_BOOKINGS B, DOCTOR@IWEB D
		WHERE  BB.DOCCODE = D.DOCCODE (+)
		AND    BB.PBPID = B.OB_PBP_ID (+)
		AND    BB.PBPID = v_pbpID
		AND    BB.WRDCODE = v_ward_code
		AND    BB.FORDELIVERY = '-1';
	ELSE
		OPEN OUTCUR FOR
		SELECT B.OB_BOOKING_ID, B.OB_PBP_ID,
		       B.OB_DOCTOR_CODE, D.DOCFNAME || ' ' || D.DOCGNAME, B.OB_PATIENT_ID,
		       B.OB_LASTNAME, B.OB_FIRSTNAME, B.OB_CHINESENAME,
		       B.OB_CONTACT_NO, TO_CHAR(B.OB_DOB, 'dd/MM/YYYY'), B.OB_DOC_TYPE, B.OB_DOC_NO,
		       TO_CHAR(B.OB_ESTIMATE_DELIVERYDATE, 'dd/MM/YYYY'),
		       TO_CHAR(B.OB_EXPECTED_DELIVERYDATE, 'dd/MM/YYYY'),
		       B.OB_KIN_LASTNAME, B.OB_KIN_FIRSTNAME, B.OB_KIN_CHINESENAME,
		       B.OB_KIN_CONTACT_NO, TO_CHAR(B.OB_KIN_DOB, 'dd/MM/YYYY'),
		       B.OB_KIN_DOC_TYPE,
		       B.OB_KIN_DOC_NO,
		       TO_CHAR(B.OB_CHECKED_DATE1, 'dd/MM/YYYY'),
		       TO_CHAR(B.OB_CHECKED_DATE2, 'dd/MM/YYYY'),
		       TO_CHAR(B.OB_CHECKED_DATE3, 'dd/MM/YYYY'),
		       TO_CHAR(B.OB_CHECKED_DATE4, 'dd/MM/YYYY'),
		       TO_CHAR(B.OB_CHECKED_DATE5, 'dd/MM/YYYY'),
		       B.OB_LAB_TEST_READY, B.OB_CANCEL_REASON, TO_CHAR(B.OB_HOLD_EXPIRY_DATE, 'dd/MM/YYYY'), B.OB_BOOKING_STATUS,
		       v_edccount,
		       B.OB_PBOREMARK
		FROM   OB_BOOKINGS B, DOCTOR@IWEB D
		WHERE  B.OB_DOCTOR_CODE = D.DOCCODE (+)
		AND    B.OB_BOOKING_ID = i_bookingID
		AND    B.OB_ENABLED = 1;
	END IF;
	RETURN OUTCUR;
END OB_BOOKING_GET;
/