ALTER TABLE OB_BOOKING_HISTORY
 DROP PRIMARY KEY CASCADE;
DROP TABLE OB_BOOKING_HISTORY CASCADE CONSTRAINTS;

CREATE TABLE OB_BOOKING_HISTORY
(
 OB_BOOKING_ID NUMBER(*,0) DEFAULT 1,
 OB_BOOKING_HISTORY_ID NUMBER(*,0) DEFAULT 1,
 OB_PBP_ID NUMBER(*,0),
 OB_EXPECTED_DELIVERYDATE DATE NULL,
 OB_BOOKING_STATUS VARCHAR2(2 BYTE) DEFAULT 'O',		-- O - Open, B - Confirmed, W - Waiting, X - Cancel
 OB_BOOKING_REMARKS VARCHAR2(200 BYTE),
 OB_CANCEL_REASON VARCHAR2(20 BYTE),
 OB_CREATED_DATE DATE DEFAULT SYSDATE,
 OB_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 OB_MODIFIED_DATE DATE DEFAULT SYSDATE,
 OB_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 OB_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (OB_BOOKING_ID, OB_BOOKING_HISTORY_ID)
);
ALTER TABLE OB_BOOKING_HISTORY ADD (
 CONSTRAINT OB_BOOKING_HISTORY_R01
 FOREIGN KEY (OB_BOOKING_ID)
 REFERENCES OB_BOOKINGS (OB_BOOKING_ID));
