ALTER TABLE OB_BOOKINGS
 DROP PRIMARY KEY CASCADE;
DROP TABLE OB_BOOKINGS CASCADE CONSTRAINTS;

CREATE TABLE OB_BOOKINGS
(
 OB_BOOKING_ID NUMBER(*,0) DEFAULT 1,
 OB_PBP_ID NUMBER(*,0),
 OB_DOCTOR_CODE VARCHAR2(4 BYTE) NULL,
 OB_PATIENT_ID VARCHAR2(20 BYTE) NULL,
 OB_LASTNAME VARCHAR2(20 BYTE) NULL,
 OB_FIRSTNAME VARCHAR2(20 BYTE) NULL,
 OB_CHINESENAME VARCHAR2(30 BYTE) NULL,
 OB_CONTACT_NO VARCHAR2(20 BYTE) NULL,
 OB_DOB DATE NULL,
 OB_DOC_TYPE VARCHAR2(1 BYTE) NULL, -- hk, china
 OB_DOC_NO VARCHAR2(20 BYTE) NULL,
 OB_ESTIMATE_DELIVERYDATE DATE NULL,
 OB_EXPECTED_DELIVERYDATE DATE NULL,
 OB_KIN_LASTNAME VARCHAR2(20 BYTE) NULL,
 OB_KIN_FIRSTNAME VARCHAR2(20 BYTE) NULL,
 OB_KIN_CHINESENAME VARCHAR2(30 BYTE) NULL,
 OB_KIN_CONTACT_NO VARCHAR2(20 BYTE) NULL,
 OB_KIN_DOB DATE NULL,
 OB_KIN_DOC_TYPE VARCHAR2(1 BYTE) NULL,
 OB_KIN_DOC_NO VARCHAR2(25 BYTE) NULL,
 OB_CHECKED_DATE1 DATE,
 OB_CHECKED_DATE2 DATE,
 OB_CHECKED_DATE3 DATE,
 OB_CHECKED_DATE4 DATE,
 OB_CHECKED_DATE5 DATE,
 OB_LAB_TEST_READY VARCHAR2(1 BYTE),
 OB_CANCEL_REASON VARCHAR2(20 BYTE),
 OB_HOLD_EXPIRY_DATE DATE,
 OB_BKG_ID NUMBER(*,0),
 OB_PBOREMARK VARCHAR2(75 BYTE),
 OB_BOOKING_STATUS VARCHAR2(2 BYTE) DEFAULT 'O',		-- O - Open, B - Confirmed, W - Waiting, X - Delete
 OB_CREATED_DATE DATE DEFAULT SYSDATE,
 OB_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 OB_MODIFIED_DATE DATE DEFAULT SYSDATE,
 OB_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 OB_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (OB_BOOKING_ID)
);