create or replace
FUNCTION OB_CHECK_PATIENT_ID ( i_patientID VARCHAR2 )
RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
	v_ward_code VARCHAR2(10);
	v_count1 INTEGER;
	v_count2 INTEGER;
	v_count3 INTEGER;
BEGIN
	v_count1 := 0;
	v_count2 := 0;

	-- get ward code
	SELECT PARAM1 INTO v_ward_code FROM SYSPARAM@IWEB WHERE PARCDE = 'obwardcode';

	SELECT COUNT(1) INTO v_count1
	FROM   BEDPREBOK@IWEB
	WHERE  WRDCODE = v_ward_code
	AND    PATIDNO = i_patientID
	AND    BPBSTS = 'N'
	AND    FORDELIVERY = '-1';

	SELECT COUNT(1) INTO v_count2
	FROM   OB_BOOKINGS B, BOOKING@IWEB BK
	WHERE  B.OB_BKG_ID = BK.BKGID
	AND    B.OB_DOC_NO = i_patientID
	AND    B.OB_BOOKING_STATUS = 'T'
	AND    B.OB_HOLD_EXPIRY_DATE > SYSDATE
	AND    BK.BKGSTS IN ('N', 'F')
	AND    BK.BKGSDATE > SYSDATE;

	SELECT COUNT(1) INTO v_count3
	FROM   OB_BOOKINGS
	WHERE  OB_DOC_NO = i_patientID
	AND    OB_BOOKING_STATUS = 'W'
	AND    OB_ENABLED = 1;

	OPEN OUTCUR FOR
	SELECT v_count1 + v_count2 + v_count3 FROM DUAL;

	RETURN OUTCUR;
END OB_CHECK_PATIENT_ID;
/