ALTER TABLE OB_DOCTOR_QUOTA
 DROP PRIMARY KEY CASCADE;
DROP TABLE OB_DOCTOR_QUOTA CASCADE CONSTRAINTS;

/*
Question
Cancel -> transfer to assigned patient (ML -> ML = ok, ML -> HK = ok, HK -> ML = not ok?)
Pending -> no down payment within 2 weeks, auto/manual cancel?
VIP/Staff -> no cancel even no down payment?
Quota -> if this month is full quota, can the doctor use previous or advance quota?
*/
CREATE TABLE OB_DOCTOR_QUOTA
(
 OB_DOCTOR_CODE VARCHAR2(4 BYTE) NOT NULL ENABLE,
 OB_DOCTOR_TYPE VARCHAR2(2 BYTE) NOT NULL, -- HD - InHouse, AD - associated, OD - others
 OB_DOCTOR_ML_QUOTA_MONTH NUMBER(*,0) NULL,
 OB_DOCTOR_HK_QUOTA_MONTH NUMBER(*,0) NULL,
 OB_DOCTOR_ML_QUOTA_YEAR NUMBER(*,0) NULL,
 OB_DOCTOR_HK_QUOTA_YEAR NUMBER(*,0) NULL,
 OB_AUTO_CANCEL VARCHAR2(1) DEFAULT 'Y',
 OB_EFFECTIVE_DATE DATE NOT NULL,
 OB_CREATED_DATE DATE DEFAULT SYSDATE,
 OB_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 OB_MODIFIED_DATE DATE DEFAULT SYSDATE,
 OB_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 OB_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (OB_DOCTOR_CODE, OB_EFFECTIVE_DATE)
);

--Pang, Selina
INSERT INTO OB_DOCTOR_QUOTA (OB_DOCTOR_CODE, OB_DOCTOR_TYPE, OB_DOCTOR_ML_QUOTA_MONTH, OB_DOCTOR_HK_QUOTA_MONTH, OB_DOCTOR_ML_QUOTA_YEAR, OB_DOCTOR_HK_QUOTA_YEAR, OB_AUTO_CANCEL, OB_EFFECTIVE_DATE) VALUES ('1499', 'HD', 20, 0, -999, -999, 'N', TO_DATE('01/01/2012', 'dd/mm/yyyy'));
INSERT INTO OB_DOCTOR_QUOTA (OB_DOCTOR_CODE, OB_DOCTOR_TYPE, OB_DOCTOR_ML_QUOTA_MONTH, OB_DOCTOR_HK_QUOTA_MONTH, OB_DOCTOR_ML_QUOTA_YEAR, OB_DOCTOR_HK_QUOTA_YEAR, OB_AUTO_CANCEL, OB_EFFECTIVE_DATE) VALUES ('1499', 'HD', 99, 99, -999, -999, 'N', TO_DATE('01/01/2013', 'dd/mm/yyyy'));

--Wan, Macor(?)
--INSERT INTO OB_DOCTOR_QUOTA (OB_DOCTOR_CODE, OB_DOCTOR_TYPE, OB_DOCTOR_ML_QUOTA_MONTH, OB_DOCTOR_HK_QUOTA_MONTH, OB_DOCTOR_ML_QUOTA_YEAR, OB_DOCTOR_HK_QUOTA_YEAR) VALUES ('559', 'AD', 8, 10, -999, -999);

--Chow, Stephanie
--INSERT INTO OB_DOCTOR_QUOTA (OB_DOCTOR_CODE, OB_DOCTOR_TYPE, OB_DOCTOR_ML_QUOTA_MONTH, OB_DOCTOR_HK_QUOTA_MONTH, OB_DOCTOR_ML_QUOTA_YEAR, OB_DOCTOR_HK_QUOTA_YEAR) VALUES ('566', 'AD', 3, 10, -999, -999);

--Lam, Yung Han
--INSERT INTO OB_DOCTOR_QUOTA (OB_DOCTOR_CODE, OB_DOCTOR_TYPE, OB_DOCTOR_ML_QUOTA_MONTH, OB_DOCTOR_HK_QUOTA_MONTH, OB_DOCTOR_ML_QUOTA_YEAR, OB_DOCTOR_HK_QUOTA_YEAR) VALUES ('1054', 'AD', 5, 5, -999, -999);

--Chan, Joe
INSERT INTO OB_DOCTOR_QUOTA (OB_DOCTOR_CODE, OB_DOCTOR_TYPE, OB_DOCTOR_ML_QUOTA_MONTH, OB_DOCTOR_HK_QUOTA_MONTH, OB_DOCTOR_ML_QUOTA_YEAR, OB_DOCTOR_HK_QUOTA_YEAR, OB_EFFECTIVE_DATE) VALUES ('1168', 'AD', 0, 7, -999, -999, TO_DATE('01/01/2012', 'dd/mm/yyyy'));
INSERT INTO OB_DOCTOR_QUOTA (OB_DOCTOR_CODE, OB_DOCTOR_TYPE, OB_DOCTOR_ML_QUOTA_MONTH, OB_DOCTOR_HK_QUOTA_MONTH, OB_DOCTOR_ML_QUOTA_YEAR, OB_DOCTOR_HK_QUOTA_YEAR, OB_EFFECTIVE_DATE) VALUES ('1168', 'AD', 2, 5, -999, -999, TO_DATE('01/10/2012', 'dd/mm/yyyy'));
INSERT INTO OB_DOCTOR_QUOTA (OB_DOCTOR_CODE, OB_DOCTOR_TYPE, OB_DOCTOR_ML_QUOTA_MONTH, OB_DOCTOR_HK_QUOTA_MONTH, OB_DOCTOR_ML_QUOTA_YEAR, OB_DOCTOR_HK_QUOTA_YEAR, OB_EFFECTIVE_DATE) VALUES ('1168', 'AD', 99, 99, -999, -999, TO_DATE('01/01/2013', 'dd/mm/yyyy'));

--Ngai, Cora
INSERT INTO OB_DOCTOR_QUOTA (OB_DOCTOR_CODE, OB_DOCTOR_TYPE, OB_DOCTOR_ML_QUOTA_MONTH, OB_DOCTOR_HK_QUOTA_MONTH, OB_DOCTOR_ML_QUOTA_YEAR, OB_DOCTOR_HK_QUOTA_YEAR, OB_EFFECTIVE_DATE) VALUES ('1256', 'AD', 0, 6, -999, -999, TO_DATE('01/01/2012', 'dd/mm/yyyy'));
INSERT INTO OB_DOCTOR_QUOTA (OB_DOCTOR_CODE, OB_DOCTOR_TYPE, OB_DOCTOR_ML_QUOTA_MONTH, OB_DOCTOR_HK_QUOTA_MONTH, OB_DOCTOR_ML_QUOTA_YEAR, OB_DOCTOR_HK_QUOTA_YEAR, OB_EFFECTIVE_DATE) VALUES ('1256', 'AD', 2, 4, -999, -999, TO_DATE('01/10/2012', 'dd/mm/yyyy'));
INSERT INTO OB_DOCTOR_QUOTA (OB_DOCTOR_CODE, OB_DOCTOR_TYPE, OB_DOCTOR_ML_QUOTA_MONTH, OB_DOCTOR_HK_QUOTA_MONTH, OB_DOCTOR_ML_QUOTA_YEAR, OB_DOCTOR_HK_QUOTA_YEAR, OB_EFFECTIVE_DATE) VALUES ('1256', 'AD', 99, 99, -999, -999, TO_DATE('01/01/2013', 'dd/mm/yyyy'));

--Ho, Philip
--INSERT INTO OB_DOCTOR_QUOTA (OB_DOCTOR_CODE, OB_DOCTOR_TYPE, OB_DOCTOR_ML_QUOTA_MONTH, OB_DOCTOR_HK_QUOTA_MONTH, OB_DOCTOR_ML_QUOTA_YEAR, OB_DOCTOR_HK_QUOTA_YEAR) VALUES ('956', 'AD', 2, 3, -999, -999);

--Stevenson, Robert
INSERT INTO OB_DOCTOR_QUOTA (OB_DOCTOR_CODE, OB_DOCTOR_TYPE, OB_DOCTOR_ML_QUOTA_MONTH, OB_DOCTOR_HK_QUOTA_MONTH, OB_DOCTOR_ML_QUOTA_YEAR, OB_DOCTOR_HK_QUOTA_YEAR, OB_EFFECTIVE_DATE) VALUES ('683', 'AD', 0, 5, -999, -999, TO_DATE('01/01/2012', 'dd/mm/yyyy'));
INSERT INTO OB_DOCTOR_QUOTA (OB_DOCTOR_CODE, OB_DOCTOR_TYPE, OB_DOCTOR_ML_QUOTA_MONTH, OB_DOCTOR_HK_QUOTA_MONTH, OB_DOCTOR_ML_QUOTA_YEAR, OB_DOCTOR_HK_QUOTA_YEAR, OB_EFFECTIVE_DATE) VALUES ('683', 'AD', 99, 99, -999, -999, TO_DATE('01/01/2013', 'dd/mm/yyyy'));

--Chan, Ben
--INSERT INTO OB_DOCTOR_QUOTA (OB_DOCTOR_CODE, OB_DOCTOR_TYPE, OB_DOCTOR_ML_QUOTA_MONTH, OB_DOCTOR_HK_QUOTA_MONTH, OB_DOCTOR_ML_QUOTA_YEAR, OB_DOCTOR_HK_QUOTA_YEAR) VALUES ('1599', 'AD', 0, 3, -999, -999);

--Wong, Wilfred
--INSERT INTO OB_DOCTOR_QUOTA (OB_DOCTOR_CODE, OB_DOCTOR_TYPE, OB_DOCTOR_ML_QUOTA_MONTH, OB_DOCTOR_HK_QUOTA_MONTH, OB_DOCTOR_ML_QUOTA_YEAR, OB_DOCTOR_HK_QUOTA_YEAR) VALUES ('1127', 'AD', 1, 2, -999, -999);

--Others
INSERT INTO OB_DOCTOR_QUOTA (OB_DOCTOR_CODE, OB_DOCTOR_TYPE, OB_DOCTOR_ML_QUOTA_MONTH, OB_DOCTOR_HK_QUOTA_MONTH, OB_DOCTOR_ML_QUOTA_YEAR, OB_DOCTOR_HK_QUOTA_YEAR, OB_EFFECTIVE_DATE) VALUES ('9999', 'ZZ', 0, 99, -999, -999, TO_DATE('01/01/2012', 'dd/mm/yyyy'));
INSERT INTO OB_DOCTOR_QUOTA (OB_DOCTOR_CODE, OB_DOCTOR_TYPE, OB_DOCTOR_ML_QUOTA_MONTH, OB_DOCTOR_HK_QUOTA_MONTH, OB_DOCTOR_ML_QUOTA_YEAR, OB_DOCTOR_HK_QUOTA_YEAR, OB_EFFECTIVE_DATE) VALUES ('9999', 'ZZ', 0, 99, -999, -999, TO_DATE('01/01/2013', 'dd/mm/yyyy'));
