ALTER TABLE PAT_SERVICES
 DROP PRIMARY KEY CASCADE;
DROP TABLE PAT_SERVICES CASCADE CONSTRAINTS;

CREATE TABLE PAT_SERVICES (
    CO_SITE_CODE     VARCHAR2(4 BYTE),
    PSID             NUMBER NOT NULL ENABLE,
    PATNO            VARCHAR2(10 BYTE),
    REGTYPE          VARCHAR2(1 BYTE),
    REGID            NUMBER(22,0),
    PATIENT_NAME     VARCHAR2(100 BYTE),
    WRDCODE          VARCHAR2(20 BYTE),
    ROMCODE          VARCHAR2(20 BYTE),
    BEDCODE          VARCHAR2(20 BYTE),
    ALLERGY          VARCHAR2(50 BYTE),
    SERVICE_TYPE     VARCHAR2(50 BYTE),
    SERVICE_CATEGORY VARCHAR2(50 BYTE),
    SERVICE_ITEM     VARCHAR2(50 BYTE),
    STATUS           VARCHAR2(50 BYTE),
    REMARK           VARCHAR2(500 BYTE),
    EFFECTIVE_DATE DATE DEFAULT SYSDATE,
    CREATE_DATE DATE DEFAULT SYSDATE,
    CREATE_USER VARCHAR2(50 BYTE) DEFAULT 'SYSTEM',
    MODIFIED_DATE DATE DEFAULT SYSDATE,
    MODIFIED_USER VARCHAR2(50 BYTE) DEFAULT 'SYSTEM',
    ENABLE        NUMBER(1,0) DEFAULT 1,
    PRIMARY KEY(PSID)
)

COMMIT;