ALTER TABLE PATIENT_SERVICE_STATUS
 DROP PRIMARY KEY CASCADE;
DROP TABLE PATIENT_SERVICE_STATUS CASCADE CONSTRAINTS;

CREATE TABLE PATIENT_SERVICE_STATUS
(
	PSID 			NUMBER NOT NULL ENABLE,
	PATIENT_ID 		VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	SERVICE_TYPE 	VARCHAR2(20 BYTE),
	STATUS 			VARCHAR2(20 BYTE),
	REMARK 			VARCHAR2(300 BYTE),
	CREATE_DATE 	DATE DEFAULT SYSDATE,
	CREATE_USER		VARCHAR2(50 BYTE) DEFAULT 'SYSTEM',
	MODIFIED_DATE	DATE DEFAULT SYSDATE,
	MODIFIED_USER	VARCHAR2(50 BYTE) DEFAULT 'SYSTEM',
	ENABLE			NUMBER DEFAULT 1,
	PRIMARY KEY (PSID)
);