CREATE TABLE "PBCATCOL"
  (
    "PBC_TNAM" VARCHAR2(60 BYTE) NOT NULL ENABLE,
    "PBC_TID"  NUMBER(*,0),
    "PBC_OWNR" VARCHAR2(60 BYTE) NOT NULL ENABLE,
    "PBC_CNAM" VARCHAR2(60 BYTE) NOT NULL ENABLE,
    "PBC_CID"  NUMBER(*,0),
    "PBC_LABL" VARCHAR2(254 BYTE),
    "PBC_LPOS" NUMBER(*,0),
    "PBC_HDR"  VARCHAR2(254 BYTE),
    "PBC_HPOS" NUMBER(*,0),
    "PBC_JTFY" NUMBER(*,0),
    "PBC_MASK" VARCHAR2(61 BYTE),
    "PBC_CASE" NUMBER(*,0),
    "PBC_HGHT" NUMBER(*,0),
    "PBC_WDTH" NUMBER(*,0),
    "PBC_PTRN" VARCHAR2(61 BYTE),
    "PBC_BMAP" CHAR(1 BYTE),
    "PBC_INIT" VARCHAR2(254 BYTE),
    "PBC_CMNT" VARCHAR2(254 BYTE),
    "PBC_EDIT" VARCHAR2(61 BYTE),
    "PBC_TAG"  VARCHAR2(254 BYTE)
  );
  
CREATE UNIQUE INDEX "PBSYSCATCOLDICT_IDX" ON "PBCATCOL"
  (
    "PBC_TNAM", "PBC_OWNR", "PBC_CNAM"
  );
  
CREATE TABLE "PBCATEDT"
  (
    "PBE_NAME" VARCHAR2(60 BYTE),
    "PBE_EDIT" VARCHAR2(254 BYTE),
    "PBE_TYPE" NUMBER(*,0),
    "PBE_CNTR" NUMBER(*,0),
    "PBE_SEQN" NUMBER(*,0),
    "PBE_FLAG" NUMBER(*,0),
    "PBE_WORK" VARCHAR2(32 BYTE)
  );
  
CREATE UNIQUE INDEX "PBSYSPBE_IDX" ON "PBCATEDT"
  (
    "PBE_NAME", "PBE_SEQN"
  );
  
CREATE TABLE "PBCATFMT"
  (
    "PBF_NAME" VARCHAR2(60 BYTE),
    "PBF_FRMT" VARCHAR2(254 BYTE),
    "PBF_TYPE" NUMBER(*,0) NOT NULL ENABLE,
    "PBF_CNTR" NUMBER(*,0)
  );
  
CREATE UNIQUE INDEX "PBSYSCATFRMTS_IDX" ON "PBCATFMT"
  (
    "PBF_NAME"
  );
  
CREATE TABLE "PBCATTBL"
  (
    "PBT_TNAM" VARCHAR2(60 BYTE) NOT NULL ENABLE,
    "PBT_TID"  NUMBER(*,0),
    "PBT_OWNR" VARCHAR2(60 BYTE) NOT NULL ENABLE,
    "PBD_FHGT" NUMBER(*,0),
    "PBD_FWGT" NUMBER(*,0),
    "PBD_FITL" CHAR(1 BYTE),
    "PBD_FUNL" CHAR(1 BYTE),
    "PBD_FCHR" NUMBER(*,0),
    "PBD_FPTC" NUMBER(*,0),
    "PBD_FFCE" VARCHAR2(36 BYTE),
    "PBH_FHGT" NUMBER(*,0),
    "PBH_FWGT" NUMBER(*,0),
    "PBH_FITL" CHAR(1 BYTE),
    "PBH_FUNL" CHAR(1 BYTE),
    "PBH_FCHR" NUMBER(*,0),
    "PBH_FPTC" NUMBER(*,0),
    "PBH_FFCE" VARCHAR2(36 BYTE),
    "PBL_FHGT" NUMBER(*,0),
    "PBL_FWGT" NUMBER(*,0),
    "PBL_FITL" CHAR(1 BYTE),
    "PBL_FUNL" CHAR(1 BYTE),
    "PBL_FCHR" NUMBER(*,0),
    "PBL_FPTC" NUMBER(*,0),
    "PBL_FFCE" VARCHAR2(36 BYTE),
    "PBT_CMNT" VARCHAR2(254 BYTE)
  );
  
CREATE UNIQUE INDEX "PBSYSCATPBT_IDX" ON "PBCATTBL"
  (
    "PBT_TNAM", "PBT_OWNR"
  );
  
CREATE TABLE "PBCATVLD"
  (
    "PBV_NAME" VARCHAR2(60 BYTE),
    "PBV_VALD" VARCHAR2(254 BYTE),
    "PBV_TYPE" NUMBER(*,0),
    "PBV_CNTR" NUMBER(*,0),
    "PBV_MSG"  VARCHAR2(254 BYTE)
  );
  
CREATE UNIQUE INDEX "PBSYSCATVLDS_IDX" ON "PBCATVLD"
  (
    "PBV_NAME"
  );
  
  
  