ALTER TABLE PH_CHECKOUT
DROP PRIMARY KEY CASCADE;
DROP TABLE PH_CHECKOUT CASCADE CONSTRAINTS;

CREATE TABLE PH_CHECKOUT
(
	PH_SITE_CODE       VARCHAR2(10 BYTE),
	PH_CHECKOUT_ID     NUMBER NOT NULL,
	PH_PATNO           VARCHAR2(10 BYTE),
	PH_IN_DATE         DATE DEFAULT SYSDATE,
	PH_OUT_DATE        DATE DEFAULT SYSDATE,
	PH_PICKUP_DATE     DATE,
	PH_BEDCODE         VARCHAR2(10 BYTE),
	PH_REMARK          VARCHAR2(1000 BYTE),
	PH_OUT_STATUS      VARCHAR2(10 BYTE),
	PH_PICKUP_STATUS   VARCHAR2(10 BYTE),
	PH_CREATE_DATE     DATE DEFAULT SYSDATE,
	PH_CREATE_USER     VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
	PH_MODIFIED_DATE   DATE DEFAULT SYSDATE,
	PH_MODIFIED_USER   VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
	PH_ENABLED         NUMBER(1,0) DEFAULT 1,
	PRIMARY KEY(PH_SITE_CODE, PH_CHECKOUT_ID)
);