ALTER TABLE PH_TICKET_QUEUE
 DROP PRIMARY KEY CASCADE;
DROP TABLE PH_TICKET_QUEUE CASCADE CONSTRAINTS;

CREATE TABLE PH_TICKET_QUEUE
(
 PH_LOC_ID VARCHAR2(10) DEFAULT 'OW' NOT NULL,
 PH_TICKET_DT VARCHAR2(10 BYTE) NOT NULL,
 PH_TICKET_QUEUE_ID VARCHAR2(10 BYTE) NOT NULL,
 PH_PATNO VARCHAR2(10 BYTE) NULL,
 PH_PRESCRIPTION_DATE DATE,
 PH_DISPENSING_DATE DATE,
 PH_CHARGED_DATE DATE,
 PH_COLLECTION_DATE DATE,
 PH_COMPLETED_DATE DATE,
 PH_CANCELLED_DATE DATE,
 PH_EST_COMPLETED_DATE DATE,
 PH_STATUS NUMBER DEFAULT 1,
 PH_CREATED_DATE DATE DEFAULT SYSDATE,
 PH_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 PH_MODIFIED_DATE DATE DEFAULT SYSDATE,
 PH_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 PH_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (PH_LOC_ID, PH_TICKET_DT, PH_TICKET_QUEUE_ID)
);