ALTER TABLE PI_REPORT_FLWUP_PERSON
 DROP PRIMARY KEY CASCADE;
DROP TABLE PI_REPORT_FLWUP_PERSON CASCADE CONSTRAINTS;

CREATE TABLE PI_REPORT_FLWUP_PERSON
  (
  	PIRID          		NUMBER NOT NULL,
  	FLWID				NUMBER,
  	FLW_PERSON_ID		NUMBER,
    TYPE				VARCHAR2(3 BYTE),
    CO_STAFF_ID			VARCHAR2(10 BYTE),
    CO_DEPARTMENT_CODE	NUMBER,
    CO_EMAIL			VARCHAR2(100 BYTE),
    CREATE_DATE 		DATE DEFAULT SYSDATE,
    CREATE_USER    		VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
    MODIFIED_DATE 		DATE DEFAULT SYSDATE,
    MODIFIED_USER 		VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
    ENABLE         	  	NUMBER(1,0) DEFAULT 1
  );
  
ALTER TABLE PI_REPORT_FLWUP_PERSON ADD (
 CONSTRAINT PI_REPORT_FLWUP_PERSON_FK1
 FOREIGN KEY (PIRID)
 REFERENCES PI_REPORT (PIRID));
 
ALTER TABLE PI_REPORT_FLWUP_PERSON ADD (
 CONSTRAINT PI_REPORT_FLWUP_PERSON_FK2
 FOREIGN KEY (FLWID)
 REFERENCES PI_REPORT_FLWUP (FLWID));
 
COMMIT;