ALTER TABLE PI_REPORT_PX_COMMENT
 DROP PRIMARY KEY CASCADE;
DROP TABLE PI_REPORT_PX_COMMENT CASCADE CONSTRAINTS;

CREATE TABLE PI_REPORT_PX_COMMENT
  (
    PIRID        NUMBER NOT NULL ENABLE,
    PIR_PXID     NUMBER,
    PIR_RISK_ASS VARCHAR2(5 BYTE),
    CREATE_USER  VARCHAR2(30 BYTE) DEFAULT 'admin',
    CREATE_DATE DATE DEFAULT sysdate,
    MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'admin',
    MODIFIED_DATE DATE DEFAULT sysdate,
    ENABLE                    NUMBER DEFAULT 1,
    PIR_HIGH_ALERT            NUMBER DEFAULT '7',
    PIR_BEFORE_WARD           NUMBER,
    PIR_BEFORE_OUTPAT         NUMBER,
    PIR_AFTER_WARD_INV        NUMBER,
    PIR_AFTER_WARD_GIVEN      NUMBER,
    PIR_AFTER_OUTPAT_NOTTAKEN NUMBER,
    PIR_AFTER_OUTPAT_TAKEN    NUMBER,
    PIR_BEFORE_DISCHARGE      NUMBER,
    PIR_AFTER_DISCHARGE       NUMBER,
    PIR_BEFORE_ADMIN          NUMBER,
    PIR_AFTER_ADMIN           NUMBER,
    PIR_BEFORE_ADMIN_UNIT     NUMBER,
    PIR_AFTER_ADMIN_UNIT      NUMBER,
    CONSTRAINT PI_REPORT_PX_COMMENT_PK PRIMARY KEY (PIRID)
  );