ALTER TABLE PI_REPORT_FLWUP
 DROP PRIMARY KEY CASCADE;
DROP TABLE PI_REPORT_FLWUP CASCADE CONSTRAINTS;

CREATE TABLE PI_REPORT_FLWUP
  (
  	PIRID          	NUMBER NOT NULL,
  	FLWID			NUMBER NOT NULL,
    ACTION			VARCHAR2(100 BYTE),
    REMARK			VARCHAR2(500 BYTE),
    NOTIFY			VARCHAR2(1 BYTE) DEFAULT 'N',
    REMIND			VARCHAR2(1 BYTE) DEFAULT 'N',
    STATUS			VARCHAR2(1 BYTE),
    CREATE_DATE 	DATE DEFAULT SYSDATE,
    CREATE_USER    	VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
    MODIFIED_DATE 	DATE DEFAULT SYSDATE,
    MODIFIED_USER 	VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
    ENABLE           NUMBER(1,0) DEFAULT 1,
    PRIMARY KEY(FLWID)
  );
  
ALTER TABLE PI_REPORT_FLWUP ADD (
 CONSTRAINT PI_REPORT_FLWUP_FK1
 FOREIGN KEY (PIRID)
 REFERENCES PI_REPORT (PIRID));
 
COMMIT;