ALTER TABLE PI_REPORT_FLWUP_DIALOG
 DROP PRIMARY KEY CASCADE;
DROP TABLE PI_REPORT_FLWUP_DIALOG CASCADE CONSTRAINTS;

CREATE TABLE PI_REPORT_FLWUP_DIALOG
  (
    PIRID        NUMBER,
    PIR_FLWID    NUMBER NOT NULL ENABLE,
    PIR_FLW_TYPE VARCHAR2(20 BYTE) DEFAULT 'Message',
    PIR_FLW_DATE DATE,
    PIR_FLW_FROM VARCHAR2(20 BYTE),
    PIR_FLW_DUE_DATE DATE,
    PIR_FLW_COMPLETE_DATE DATE,
    PIR_FLW_ACTION VARCHAR2(4000 BYTE),
    CREATE_DATE DATE DEFAULT SYSDATE,
    CREATE_USER VARCHAR2(30 BYTE) DEFAULT 'admin',
    MODIFIED_DATE DATE DEFAULT sysdate,
    MODIFIED_USER  VARCHAR2(30 BYTE) DEFAULT 'admin',
    ENABLE         NUMBER DEFAULT 1,
    PIR_RES_PARTY  VARCHAR2(50 BYTE),
    PIR_WFL_STATUS VARCHAR2(20 BYTE),
    PIR_RES_PARTY2 VARCHAR2(20 BYTE),
    CONSTRAINT PI_REPORT_FLWUP_DIALOG_PK PRIMARY KEY (PIR_FLWID)
  );