ALTER TABLE PI_REPORT_OPTION_GROUP_BACKUP
 DROP PRIMARY KEY CASCADE;
DROP TABLE PI_REPORT_OPTION_GROUP_BACKUP CASCADE CONSTRAINTS;

CREATE TABLE PI_REPORT_OPTION_GROUP_BACKUP
  (
    PI_SITE_CODE     VARCHAR2(10 BYTE),
    PI_GRPID         NUMBER NOT NULL ENABLE,
    PI_PARENT_GRPID  NUMBER,
    PI_MODULE_CODE   VARCHAR2(20 BYTE),
    PI_GRP_TYPE      VARCHAR2(50 BYTE),
    PI_GRP_DESC      VARCHAR2(100 BYTE),
    PI_CATEGORY_DESC VARCHAR2(30 BYTE),
    PI_ORDER         NUMBER,
    PI_CREATE_DATE DATE,
    PI_CREATE_USER VARCHAR2(30 BYTE),
    PI_MODIFIED_DATE DATE,
    PI_MODIFIED_USER  VARCHAR2(30 BYTE),
    PI_ENABLED        NUMBER(*,0),
    PI_DISPLAYGENERAL NUMBER(*,0)
  );