ALTER TABLE PI_REPORT_FLWUP_DIALOG_PERSON
 DROP PRIMARY KEY CASCADE;
DROP TABLE PI_REPORT_FLWUP_DIALOG_PERSON CASCADE CONSTRAINTS;

CREATE TABLE PI_REPORT_FLWUP_DIALOG_PERSON
  (
    PIRID          NUMBER NOT NULL ENABLE,
    PIR_FLWID      NUMBER NOT NULL ENABLE,
    PIR_FLWPID     NUMBER NOT NULL ENABLE,
    PIR_FLW_PERSON VARCHAR2(50 BYTE),
    CREATE_DATE DATE DEFAULT sysdate,
    CREATE_USER VARCHAR2(30 BYTE) DEFAULT 'admin',
    MODIFIED_DATE DATE DEFAULT sysdate,
    MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'admin',
    ENABLE        NUMBER DEFAULT 1,
    PIR_FLW_EMAIL VARCHAR2(50 BYTE),
    CONSTRAINT PI_REPORT_FLWUP_DIALOG_PE_PK PRIMARY KEY (PIR_FLWPID)
  );