ALTER TABLE PI_REPORT_INVOLVE_PERSON
 DROP PRIMARY KEY CASCADE;
DROP TABLE PI_REPORT_INVOLVE_PERSON CASCADE CONSTRAINTS;

CREATE TABLE PI_REPORT_INVOLVE_PERSON
  (
    PIRID                 NUMBER NOT NULL ENABLE,
    PIR_IP_ID             NUMBER NOT NULL ENABLE,
    IS_PATIENT            NUMBER(1,0),
    IS_STAFF              NUMBER(1,0),
    IS_VISTOR_OR_RELATIVE NUMBER(1,0),
    IS_OTHER              NUMBER(1,0),
    PATNO                 VARCHAR2(10 BYTE),
    STAFF_ID              VARCHAR2(10 BYTE),
    PERSON_NAME           VARCHAR2(100 BYTE),
    SEX                   VARCHAR2(1 BYTE),
    AGE                   VARCHAR2(20 BYTE),
    DATE_OF_BIRTH DATE,
    RANK                        VARCHAR2(100 BYTE),
    DEPT_CODE                   NUMBER,
    REMARK                      VARCHAR2(100 BYTE),
    SAME_REPORT_PERSON          NUMBER(1,0),
    RELATIONSHIP                VARCHAR2(20 BYTE),
    VISTOR_RELATIVES_OF_PATIENT NUMBER(1,0),
    VISTOR_RELATIVES_OF_STAFF   NUMBER(1,0),
    PERSON_STATUS               VARCHAR2(20 BYTE),
    PHYSICIAN                   VARCHAR2(100 BYTE),
    DIAGNOSIS                   VARCHAR2(300 BYTE),
    CREATE_DATE DATE DEFAULT SYSDATE,
    CREATE_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
    MODIFIED_DATE DATE DEFAULT SYSDATE,
    MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
    ENABLE        NUMBER(1,0) DEFAULT 1,
    TEL           VARCHAR2(50 BYTE),
    ADDR          VARCHAR2(100 BYTE),
    PRIMARY KEY (PIR_IP_ID)
  )

ALTER TABLE PI_REPORT_INVOLVE_PERSON ADD (
 CONSTRAINT PI_REPORT_INVOLVE_PERSON_FK1
 FOREIGN KEY (PIRID)
 REFERENCES PI_REPORT (PIRID));