ALTER TABLE PI_REPORT_FOLLOWUP_TO
 DROP PRIMARY KEY CASCADE;
DROP TABLE PI_REPORT_FOLLOWUP_TO CASCADE CONSTRAINTS;

CREATE TABLE PI_REPORT_FOLLOWUP_TO
  (
    PIRID           NUMBER NOT NULL ENABLE,
    PIR_FLWID       NUMBER NOT NULL ENABLE,
    PIR_FLW_TOEMAIL VARCHAR2(100 BYTE),
    CREATE_DATE DATE DEFAULT SYSDATE,
    CREATE_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
    MODIFIED_DATE DATE DEFAULT SYSDATE,
    MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
    ENABLE        NUMBER(1,0) DEFAULT 1
  );