ALTER TABLE PI_REPORT_MSG
 DROP PRIMARY KEY CASCADE;
DROP TABLE PI_REPORT_MSG CASCADE CONSTRAINTS;

CREATE TABLE PI_REPORT_MSG
  (
  	PIRID          	NUMBER NOT NULL,
  	FLWID			NUMBER,
    MSGID			NUMBER NOT NULL,
    TYPE			VARCHAR2(30 BYTE),
    MESSAGE			VARCHAR2(500 BYTE),
    CREATE_DATE 	DATE DEFAULT SYSDATE,
    CREATE_USER    	VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
    MODIFIED_DATE 	DATE DEFAULT SYSDATE,
    MODIFIED_USER 	VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
    ENABLE           NUMBER(1,0) DEFAULT 1,
    PRIMARY KEY(MSGID)
  );
  
ALTER TABLE PI_REPORT_MSG ADD (
 CONSTRAINT PI_REPORT_MSG_FK1
 FOREIGN KEY (PIRID)
 REFERENCES PI_REPORT (PIRID));
 
ALTER TABLE PI_REPORT_MSG ADD (
 CONSTRAINT PI_REPORT_MSG_FK2
 FOREIGN KEY (FLWID)
 REFERENCES PI_REPORT_FLWUP (FLWID));
 
COMMIT;