ALTER TABLE PI_REPORT_OPTION_GROUP_SEL
 drop primary key cascade;
DROP TABLE PI_REPORT_OPTION_GROUP_SEL CASCADE CONSTRAINTS;

CREATE TABLE PI_REPORT_OPTION_GROUP_SEL
(
    PI_SITE_CODE     varchar2(10 byte),
    PI_GRPID_SEL  NUMBER NOT NULL ENABLE,
    PI_PARENT_GRPID  NUMBER,
    PI_SELECT_GRPID  NUMBER,
    PI_MODULE_CODE   VARCHAR2(20 BYTE),  
    PI_ORDER         NUMBER,
    PI_CREATE_DATE DATE DEFAULT SYSDATE,
    PI_CREATE_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
    PI_MODIFIED_DATE DATE DEFAULT SYSDATE,
    PI_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
    PI_ENABLED       number(*,0) default 1,   
    PRIMARY KEY (PI_GRPID_SEL)
);

alter table PI_REPORT_OPTION_GROUP_SEL add (
 CONSTRAINT PI_REPORT_OPTION_GROUP_SEL_R01
 FOREIGN KEY (PI_SITE_CODE)
 REFERENCES CO_SITE (CO_SITE_CODE));
  
 insert into PI_REPORT_OPTION_GROUP_SEL
(PI_SITE_CODE,PI_GRPID_SEL, PI_PARENT_GRPID, PI_SELECT_GRPID, PI_MODULE_CODE, PI_ORDER)
values
('hkah',1 , 45, 11, 'patient_fall', 1);
 insert into PI_REPORT_OPTION_GROUP_SEL
(PI_SITE_CODE,PI_GRPID_SEL, PI_PARENT_GRPID, PI_SELECT_GRPID, PI_MODULE_CODE, PI_ORDER)
values
('hkah',2 , 47, 26, 'visitor_fall', 1);
 insert into PI_REPORT_OPTION_GROUP_SEL
(PI_SITE_CODE,PI_GRPID_SEL, PI_PARENT_GRPID, PI_SELECT_GRPID, PI_MODULE_CODE, PI_ORDER)
values
('hkah',3 , 49, 26, 'patient_injury', 1);
 insert into PI_REPORT_OPTION_GROUP_SEL
(PI_SITE_CODE,PI_GRPID_SEL , PI_PARENT_GRPID, PI_SELECT_GRPID, PI_MODULE_CODE, PI_ORDER)
values
('hkah',4 , 51, 26, 'visitor_injury', 1);
 insert into PI_REPORT_OPTION_GROUP_SEL
(PI_SITE_CODE,PI_GRPID_SEL , PI_PARENT_GRPID, PI_SELECT_GRPID, PI_MODULE_CODE, PI_ORDER)
values
('hkah',5 , 53, 12, 'medication_error', 1);
 insert into PI_REPORT_OPTION_GROUP_SEL
(PI_SITE_CODE,PI_GRPID_SEL , PI_PARENT_GRPID, PI_SELECT_GRPID, PI_MODULE_CODE, PI_ORDER)
values
('hkah',6 , 53, 14, 'medication_error', 2);
 insert into PI_REPORT_OPTION_GROUP_SEL
(PI_SITE_CODE,PI_GRPID_SEL , PI_PARENT_GRPID, PI_SELECT_GRPID, PI_MODULE_CODE, PI_ORDER)
values
('hkah',7 , 55, 17, 'equipment', 1);
 insert into PI_REPORT_OPTION_GROUP_SEL
(PI_SITE_CODE,PI_GRPID_SEL , PI_PARENT_GRPID, PI_SELECT_GRPID, PI_MODULE_CODE, PI_ORDER)
values
('hkah',8 , 57, 13, 'other', 1);
 insert into PI_REPORT_OPTION_GROUP_SEL
(PI_SITE_CODE,PI_GRPID_SEL , PI_PARENT_GRPID, PI_SELECT_GRPID, PI_MODULE_CODE, PI_ORDER)
values
('hkah',9 , 57, 15, 'other', 2);
 insert into PI_REPORT_OPTION_GROUP_SEL
(PI_SITE_CODE,PI_GRPID_SEL , PI_PARENT_GRPID, PI_SELECT_GRPID, PI_MODULE_CODE, PI_ORDER)
values
('hkah',10 , 57, 16, 'other', 3);
 insert into PI_REPORT_OPTION_GROUP_SEL
(PI_SITE_CODE,PI_GRPID_SEL , PI_PARENT_GRPID, PI_SELECT_GRPID, PI_MODULE_CODE, PI_ORDER)
values
('hkah',11 , 57, 19, 'other', 4);
 insert into PI_REPORT_OPTION_GROUP_SEL
(PI_SITE_CODE,PI_GRPID_SEL , PI_PARENT_GRPID, PI_SELECT_GRPID, PI_MODULE_CODE, PI_ORDER)
values
('hkah',12 , 57, 20, 'other', 5);
 insert into PI_REPORT_OPTION_GROUP_SEL
(PI_SITE_CODE,PI_GRPID_SEL , PI_PARENT_GRPID, PI_SELECT_GRPID, PI_MODULE_CODE, PI_ORDER)
values
('hkah',13 , 57, 21, 'other', 6);
 insert into PI_REPORT_OPTION_GROUP_SEL
(PI_SITE_CODE,PI_GRPID_SEL , PI_PARENT_GRPID, PI_SELECT_GRPID, PI_MODULE_CODE, PI_ORDER)
values
('hkah',14 , 57, 22, 'other', 7);
 insert into PI_REPORT_OPTION_GROUP_SEL
(PI_SITE_CODE,PI_GRPID_SEL , PI_PARENT_GRPID, PI_SELECT_GRPID, PI_MODULE_CODE, PI_ORDER)
values
('hkah',15 , 57, 23, 'other', 8);
 insert into PI_REPORT_OPTION_GROUP_SEL
(PI_SITE_CODE,PI_GRPID_SEL , PI_PARENT_GRPID, PI_SELECT_GRPID, PI_MODULE_CODE, PI_ORDER)
values
('hkah',16 , 57, 24, 'other', 9);
 insert into PI_REPORT_OPTION_GROUP_SEL
(PI_SITE_CODE,PI_GRPID_SEL , PI_PARENT_GRPID, PI_SELECT_GRPID, PI_MODULE_CODE, PI_ORDER)
values
('hkah',17 , 57, 25, 'other', 10);
 insert into PI_REPORT_OPTION_GROUP_SEL
(PI_SITE_CODE,PI_GRPID_SEL , PI_PARENT_GRPID, PI_SELECT_GRPID, PI_MODULE_CODE, PI_ORDER)
values
('hkah',18 , 57, 26, 'other', 11);
 insert into PI_REPORT_OPTION_GROUP_SEL
(PI_SITE_CODE,PI_GRPID_SEL , PI_PARENT_GRPID, PI_SELECT_GRPID, PI_MODULE_CODE, PI_ORDER)
values
('hkah',19 , 59, 18, 'security', 1);

COMMIT;
