ALTER TABLE PI_REPORT_CONTENT
 DROP PRIMARY KEY CASCADE;
DROP TABLE PI_REPORT_CONTENT CASCADE CONSTRAINTS;

CREATE TABLE PI_REPORT_CONTENT
  (
  	PI_SITE_CODE   	VARCHAR2(10 BYTE),
  	PIRID          	NUMBER NOT NULL ENABLE,
  	PI_CONTENT_GRPID NUMBER DEFAULT 0,
    PI_GRPID      NUMBER,
  	PI_CONTENT_ID	NUMBER NOT NULL,
    PI_OPTION_ID   	NUMBER,
    PI_VALUE       	VARCHAR2(500 BYTE),   
    CREATE_USER    	VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
	CREATE_DATE 	DATE DEFAULT SYSDATE,
    MODIFIED_USER 	VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
    MODIFIED_DATE 	DATE DEFAULT SYSDATE,
    ENABLE           NUMBER(1,0) DEFAULT 1
  );
  
ALTER TABLE PI_REPORT_CONTENT ADD (
 CONSTRAINT PI_REPORT_CONTENT_FK1
 FOREIGN KEY (PIRID)
 REFERENCES PI_REPORT (PIRID));
 
 ALTER TABLE PI_REPORT_CONTENT ADD (
 CONSTRAINT PI_REPORT_CONTENT_FK2
 FOREIGN KEY (PI_SITE_CODE)
 REFERENCES CO_SITE (CO_SITE_CODE));