ALTER TABLE PI_REPORT_OPTION_GROUP
 DROP PRIMARY KEY CASCADE;
DROP TABLE PI_REPORT_OPTION_GROUP CASCADE CONSTRAINTS;

CREATE TABLE PI_REPORT_OPTION_GROUP
(
    PI_SITE_CODE     VARCHAR2(10 BYTE),
    PI_GRPID         NUMBER NOT NULL ENABLE,
    PI_PARENT_GRPID  NUMBER,
    PI_MODULE_CODE   VARCHAR2(20 BYTE),
    PI_GRP_TYPE      VARCHAR2(50 BYTE),
    PI_GRP_DESC      VARCHAR2(100 BYTE),
    PI_CATEGORY_DESC VARCHAR2(30 BYTE),
    PI_ORDER         NUMBER,
    PI_CREATE_DATE DATE DEFAULT SYSDATE,
    PI_CREATE_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
    PI_MODIFIED_DATE DATE DEFAULT SYSDATE,
    PI_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
    PI_ENABLED       NUMBER(*,0) DEFAULT 1,
    PI_DISPLAYGENERAL NUMBER(*,0) DEFAULT 0,
    PRIMARY KEY (PI_GRPID)
);

ALTER TABLE PI_REPORT_OPTION_GROUP ADD (
 CONSTRAINT PI_REPORT_OPTION_GROUP_R01
 FOREIGN KEY (PI_SITE_CODE)
 REFERENCES CO_SITE (CO_SITE_CODE));

 
 INSERT INTO PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER)
VALUES
('hkah', '1', null, null, 'classification', 'Incident Classiification', null, 1);
INSERT INTO PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER, PI_ENABLED)
VALUES
('hkah', '2', null, 'general_incident', 'category', 'CLINICAL SERVICE INVOLVED (OTHER THAN THE PLACE OF OCCURRENCE)', 'clinical_service', 1 ,0);
INSERT INTO PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER)
VALUES
('hkah', '3', '43', 'general_incident', 'category', 'PATIENT FACTORS PRIOR TO EVENT', 'patient_factors', 1);
INSERT INTO PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER)
VALUES
('hkah', '4', '43', 'general_incident', 'category', 'PATIENT/ FAMILY ATTITUDE DURING/ AFTER EVENT', 'patient_family', 4);
INSERT INTO PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER, PI_ENABLED)
VALUES
('hkah', '5', null, 'general_incident', 'group', 'Types', null, 4 , 0);
INSERT INTO PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER)
VALUES
('hkah', '6', null, 'general_incident', 'group', 'Action', null, 5);
INSERT INTO PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER)
VALUES
('hkah', '7', null, 'general_incident', 'group', 'Outcome', null, 6);
INSERT INTO PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER)
VALUES
('hkah', '8', '7', 'general_incident', 'category', 'ATTACHMENTS', 'attachments', 7);
INSERT INTO PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER)
VALUES
('hkah', '9', null, 'general_incident', 'category', 'FURTHER NOTICE', 'further_notice', 8);
INSERT INTO PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER)
VALUES
('hkah', '10', null, 'general_incident', 'category', 
  'RISK ANALYSIS/ ON SITE INVESTIGATION/ FOLLOW UP ACTIONS AND PREVENTIVE ACTIONS/ RECOMMENDATION', 'risk_analysis', 9);
INSERT INTO PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER)
VALUES
('hkah', '11', null, null, 'category', 'PATIENT FALL', 'patient_fall', 1);
INSERT INTO PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER)
VALUES
('hkah', '12', null, null, 'category', 'MEDICATION', 'medication', 2);
INSERT INTO PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER)
VALUES
('hkah', '13', null, null, 'category', 'INFUSTION/ BLOOD PRODUCT TRANSFUSION', 'infustion_blood', 3);
INSERT INTO PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER, PI_ENABLED)
VALUES
('hkah', '14', null, null, 'category', 'ADMINISTRATION ERROR', 'administration_error', 4 , 0);
INSERT INTO PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER)
VALUES
('hkah', '15', null, null, 'category', 'PROCEDURE/ TREATMENT/ COMMUNICATION', 'procedure_treatment', 5);
INSERT INTO PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER)
VALUES
('hkah', '16', null, null, 'category', 'OT/ OPD/ OB/ DC (SPECIFIC)', 'ot_opd', 6);
INSERT INTO PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER)
VALUES
('hkah', '17', null, null, 'category', 'EQUIPMENT', 'equipment', 7);
INSERT INTO PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER)
VALUES
('hkah', '18', null, null, 'category', 'SAFETY/ SECURITY', 'safety_security', 8);
INSERT INTO PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER)
VALUES
('hkah', '19', null, null, 'category', 'PATIENT IDENTIFICATION', 'patient_identification', 9);
INSERT INTO PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER)
VALUES
('hkah', '20', null, null, 'category', 'SPECIMEN IDENTIFICATION', 'specimen_identification', 10);
INSERT INTO PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER)
VALUES
('hkah', '21', null, null, 'category', 'SPECIMEN COLLECTION', 'specimen_collection', 11);
INSERT INTO PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER)
VALUES
('hkah', '22', null, null, 'category', 'SPECIMEN CONDITION', 'specimen_condition', 12);
INSERT INTO PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER)
VALUES
('hkah', '23', null, null, 'category', 'SPECIAL PROCESS', 'special_process', 13);
INSERT INTO PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER)
VALUES
('hkah', '24', null, null, 'category', 'SPCIMEN INFORMATION', 'specimen_information', 14);
INSERT INTO PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER)
VALUES
('hkah', '25', null, null, 'category', 'MISCELLANEOUS', 'miscellaneous', 15);
INSERT INTO PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER)
VALUES
('hkah', '26', null, null, 'category', 'OTHER', 'other', 16);
INSERT INTO PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER)
VALUES
('hkah', '27', '6', 'general_incident', 'category', 'NOTIFICATION TO DOCTOR', 'notification', 1);
INSERT INTO PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER)
VALUES
('hkah', '28', '6', 'general_incident', 'category', 'FOLLOW-UP TREATMENT', 'followup_treatment', 2);
INSERT INTO PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER)
VALUES
('hkah', '29', '6', 'general_incident', 'category', 'FOLLOW-UP', 'follow_up', 3);
INSERT INTO PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER)
VALUES
('hkah', '30', '43', 'general_incident', 'category', 'NATURE OF INJURY', 'nature_of_injury', 2);
INSERT INTO PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER)
VALUES
('hkah', '31', '43', 'general_incident', 'category', 'RATING OF INJURY', 'assessment_of_injury', 3);
INSERT INTO PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER)
VALUES
('hkah', '32', null, null, 'incident_type', 'GENERAL INCIDENT REPORT', 'general_incident', 1);
INSERT INTO PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER)
VALUES
('hkah', '33', null, null, 'incident_type', 'STAFF INJURY', 'staff_injury', 2);
INSERT INTO PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER)
VALUES
('hkah', '34', null, 'staff_injury', 'category', 'DESCRIPTION OF ACCIDENT', 'description_of_accident', 1);
INSERT INTO PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER)
VALUES
('hkah', '35', null, 'staff_injury', 'category', 'NATURE OF INJURY', 'nature_of_injury', 2);
INSERT INTO PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER)
VALUES
('hkah', '36', null, 'staff_injury', 'category', 'TYPE OF INCIDENT (TICK ONE BOX)', 'type_of_incident', 3);
INSERT INTO PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER)
VALUES
('hkah', '37', null, 'staff_injury', 'category', 'IMMEDIATE ACTION TAKEN', 'immediate_action', 4);
INSERT INTO PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER)
VALUES
('hkah', '38', null, 'staff_injury', 'category', 'ATTACHMENTS', 'attachments', 5);
INSERT INTO PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER)
VALUES
('hkah', '39', null, 'staff_injury', 'category', 'NOTIFICATION TO DOCTOR', 'notification', 6);
INSERT INTO PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER)
VALUES
('hkah', '40', null, 'staff_injury', 'category', 'FOLLOW-UP TREATMENT', 'followup_treatment', 7);
INSERT INTO PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER)
VALUES
('hkah', '41', null, 'staff_injury', 'category', 'ASSESSMENT OF INJURY', 'assessment_of_injury', 9);
INSERT INTO PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER)
VALUES
('hkah', '42', null, 'staff_injury', 'category', 'NATURE OF INJURY', 'nature_of_injury', 8);
INSERT INTO PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER)
VALUES
('hkah', '43', null, 'general_incident', 'group', 'Narrative Description Of Occurrence', null, 3);

insert into PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER,PI_DISPLAYGENERAL)
values
('hkah', '44', null, null, 'incident_type', 'GENERAL INCIDENT REPORT - PATIENT FALL', 'patient_fall', 3, 32);
insert into PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER)
values
('hkah', '45', null, 'patient_fall', 'group', 'Detail Information', null, 4);
insert into PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER,PI_DISPLAYGENERAL)
values
('hkah', '46', null, null, 'incident_type', 'GENERAL INCIDENT REPORT - VISITOR FALL', 'visitor_fall', 3, 32);
insert into PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER)
values
('hkah', '47', null, 'visitor_fall', 'group', 'Detail Information', null, 4);
insert into PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER,PI_DISPLAYGENERAL)
values
('hkah', '48', null, null, 'incident_type', 'GENERAL INCIDENT REPORT - PATIENT FALL', 'patient_injury', 3, 32);
insert into PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER)
values
('hkah', '49', null, 'patient_injury', 'group', 'Detail Information', null, 4);
insert into PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER,PI_DISPLAYGENERAL)
values
('hkah', '50', null, null, 'incident_type', 'GENERAL INCIDENT REPORT - VISITOR INJURY', 'visitor_injury', 3, 32);
insert into PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER)
values
('hkah', '51', null, 'visitor_injury', 'group', 'Detail Information', null, 4);
insert into PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER,PI_DISPLAYGENERAL)
values
('hkah', '52', null, null, 'incident_type', 'GENERAL INCIDENT REPORT - MEDICATION ERROR', 'medication_error', 3, 32);
insert into PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER)
values
('hkah', '53', null, 'medication_error', 'group', 'Detail Information', null, 4);
insert into PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER,PI_DISPLAYGENERAL)
values
('hkah', '54', null, null, 'incident_type', 'GENERAL INCIDENT REPORT - EQUIPMENT', 'equipment', 3, 32);
insert into PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER)
values
('hkah', '55', null, 'equipment', 'group', 'Detail Information', null, 4);
insert into PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER,PI_DISPLAYGENERAL)
values
('hkah', '56', null, null, 'incident_type', 'GENERAL INCIDENT REPORT - OTHER', 'other', 3, 32);
insert into PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER)
values
('hkah', '57', null, 'other', 'group', 'Detail Information', null, 4);
insert into PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER,PI_DISPLAYGENERAL)
values
('hkah', '58', null, null, 'incident_type', 'GENERAL INCIDENT REPORT - SECURITY', 'security', 3, 32);
insert into PI_REPORT_OPTION_GROUP
(PI_SITE_CODE, PI_GRPID, PI_PARENT_GRPID, PI_MODULE_CODE, PI_GRP_TYPE, PI_GRP_DESC, PI_CATEGORY_DESC, PI_ORDER)
values
('hkah', '59', null, 'security', 'group', 'Detail Information', null, 4);

COMMIT;
