ALTER TABLE PI_REPORT_FOLLOWUP
 DROP PRIMARY KEY CASCADE;
DROP TABLE PI_REPORT_FOLLOWUP CASCADE CONSTRAINTS;

CREATE TABLE PI_REPORT_FOLLOWUP
  (
    PIRID        NUMBER NOT NULL ENABLE,
    PIR_FLWID    NUMBER NOT NULL ENABLE,
    PIR_FLW_TYPE VARCHAR2(20 BYTE) DEFAULT 'MESSAGE',
    PIR_FLW_FROM VARCHAR2(20 BYTE),
    PIR_FLW_DUE_DATE DATE,
    PIR_FLW_COMPLETE_DATE DATE,
    PIR_FLW_ACTION VARCHAR2(1000 BYTE),
    CREATE_DATE DATE DEFAULT SYSDATE,
    CREATE_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
    MODIFIED_DATE DATE DEFAULT SYSDATE,
    MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
    ENABLE        NUMBER(1,0) DEFAULT 1,
    PRIMARY KEY (PIR_FLWID)
  );