ALTER TABLE PI_REPORT_FLWUP_DIALOG_ADD_RPT
 DROP PRIMARY KEY CASCADE;
DROP TABLE PI_REPORT_FLWUP_DIALOG_ADD_RPT CASCADE CONSTRAINTS;

CREATE TABLE PI_REPORT_FLWUP_DIALOG_ADD_RPT
  (
    PIRID            NUMBER,
    PIR_ARID         NUMBER NOT NULL ENABLE,
    PIR_AR_FROM      VARCHAR2(20 BYTE),
    PIR_AR_DEPT_CODE VARCHAR2(20 BYTE),
    PIR_AR_DEPT_DESC VARCHAR2(100 BYTE),
    PIR_AR_CONTENT   VARCHAR2(4000 BYTE),
    CREATE_DATE DATE DEFAULT SYSDATE,
    CREATE_USER VARCHAR2(20 BYTE) DEFAULT 'admin',
    MODIFIED_DATE DATE DEFAULT sysdate,
    MODIFIED_USER VARCHAR2(20 BYTE) DEFAULT 'admin',
    ENABLE        NUMBER DEFAULT 1,
    CONSTRAINT PI_REPORT_FLWUP_DIALOG_AD_PK PRIMARY KEY (PIR_ARID)
  );