ALTER TABLE PI_REPORT_STATUS
 DROP PRIMARY KEY CASCADE;
DROP TABLE PI_REPORT_STATUS CASCADE CONSTRAINTS;

CREATE TABLE PI_REPORT_STATUS
  (
    PIRID              NUMBER NOT NULL ENABLE,
    PIR_REJECT         VARCHAR2(20 BYTE),
    PIR_FLWUP          VARCHAR2(20 BYTE),
    PIR_FLWUP_COMPLETE VARCHAR2(20 BYTE),
    PIR_FINAL_FACTOR   VARCHAR2(500 BYTE),
    PIR_FINAL_REC      VARCHAR2(500 BYTE),
    PIR_CLOSE_EVAL     VARCHAR2(500 BYTE),
    PIR_CLOSE_HAPPEN   VARCHAR2(500 BYTE),
    CREATE_DATE DATE DEFAULT SYSDATE,
    CREATE_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
    MODIFIED_DATE DATE DEFAULT SYSDATE,
    MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
    ENABLE        NUMBER(1,0) DEFAULT 1
  );