ALTER TABLE PI_REPORT_FLW_REPLY
 DROP PRIMARY KEY CASCADE;
DROP TABLE PI_REPORT_FLW_REPLY CASCADE CONSTRAINTS;

CREATE TABLE PI_REPORT_FLW_REPLY
  (
    PIRID        NUMBER NOT NULL ENABLE,
    PI_FLW_ID    NUMBER NOT NULL ENABLE,
    PI_REPLY_ID  NUMBER NOT NULL ENABLE,
    PI_REPLY_MSG VARCHAR2(200 BYTE),
    CREATE_DATE DATE DEFAULT SYSDATE,
    CREATE_USER VARCHAR2(50 BYTE) DEFAULT 'SYSTEM',
    MODIFIED_DATE DATE DEFAULT SYSDATE,
    MODIFIED_USER VARCHAR2(50 BYTE) DEFAULT 'SYSTEM',
    ENABLE        NUMBER(1,0) DEFAULT 1
  );