ALTER TABLE PI_REPORT
DROP PRIMARY KEY CASCADE;
DROP TABLE PI_REPORT CASCADE CONSTRAINTS;

CREATE TABLE PI_REPORT
(
	PIR_SITE_CODE VARCHAR2(10 BYTE),
	PIRID NUMBER NOT NULL ENABLE,
	PIR_PNAME VARCHAR2(100 BYTE),
	PIR_RANK VARCHAR2(100 BYTE),
	PIR_DEPT_CODE VARCHAR2(10 BYTE),
	PIR_DEPT_CODE_FLWUP VARCHAR2(10 BYTE),
	PIR_INCIDENT_DATE DATE,
	PIR_INCIDENT_TIME VARCHAR2(5 BYTE),
	PIR_INCIDENT_PLACE VARCHAR2(50 BYTE),
	PIR_INCIDENT_PLACE_FREETEXT VARCHAR2(200 BYTE),
	PIR_INCIDENT_TYPE VARCHAR2(30 BYTE),
	PIR_INCIDENT_CLASSIFICATION VARCHAR2(50 BYTE),
	PIR_INCIDENT_CLASS_PI VARCHAR2(20 BYTE),
	PIR_NEAR_MISS NUMBER DEFAULT 0,
	PIR_NEAR_MISS_PI NUMBER DEFAULT NULL,
	PIR_HAZARDOUS_CONDITION NUMBER DEFAULT 0,
	PIR_HAZARDOUS_CONDITION_PI NUMBER DEFAULT NULL,
	PIR_STATUS NUMBER(2,0) DEFAULT 0,
	PIR_REL_PIRID NUMBER,
	PIR_RESPONSIBLE_PARTY VARCHAR2(20 BYTE),
	PIR_RESPONSIBLE_PARTY2 VARCHAR2(20 BYTE),
	PIR_RESPONSIBLE_PARTY_FLWUP VARCHAR2(20 BYTE),
	PIR_SENTINEL_EVENT NUMBER DEFAULT 0,
	PIR_SENTINEL_EVENT_ID NUMBER,
	PIR_TRAFFIC_LIGHT VARCHAR2(1 BYTE),
	PIR_PI_ASS_INJURY VARCHAR2(2 BYTE),
	PIR_PI_REMARK VARCHAR2(2000 BYTE),
	PIR_PI_REMARK2 VARCHAR2(2000 BYTE),
	PIR_PI_REMARK3 VARCHAR2(2000 BYTE),
	PIR_PX_RESPONSIBLE_PARTY VARCHAR2(20 BYTE),
	PIR_PX_RESPONSIBLE_PARTY2 VARCHAR2(20 BYTE),
	PIR_PX_NURSE VARCHAR2(20 BYTE),
	PIR_UMDM_REMARK VARCHAR2(2000 BYTE),
	PIR_PI_REMARK_DON VARCHAR2(2000 BYTE),
	PIR_PI_REMARK_VPA VARCHAR2(2000 BYTE),
	PIR_INCIDENT_TYPE_PI VARCHAR2(30 BYTE),
	PIR_INOUT_PAT VARCHAR2(5 BYTE),
	PIR_OUTCOME NUMBER DEFAULT NULL,
	PIR_CREATED_DATE DATE DEFAULT SYSDATE,
	PIR_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
	PIR_MODIFIED_DATE DATE DEFAULT SYSDATE,
	PIR_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
	PIR_ENABLED NUMBER(1,0) DEFAULT 1,
	CONSTRAINT PI_REPORT_PK PRIMARY KEY (PIRID)
);

--PIR_STATUS: 0 - Created, 1 - Not Reject, 2 - Follow Up, 3 - Complete, 4 - Reject, 5 - No Follow Up