ALTER TABLE PMP_PROJECT_COMMENT_LINKS
 DROP PRIMARY KEY CASCADE;
DROP TABLE PMP_PROJECT_COMMENT_LINKS CASCADE CONSTRAINTS;

CREATE TABLE PMP_PROJECT_COMMENT_LINKS
(
 PMP_PROJECT_ID NUMBER(*,0) NOT NULL,
 PMP_COMMENT_ID NUMBER(*,0) DEFAULT 1,
 PMP_PROJECT_COMMENT_LINK_ID NUMBER(*,0) NOT NULL,
 PMP_CREATED_DATE DATE DEFAULT SYSDATE,
 PMP_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 PMP_MODIFIED_DATE DATE DEFAULT SYSDATE,
 PMP_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 PMP_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (PMP_PROJECT_ID, PMP_COMMENT_ID, PMP_PROJECT_COMMENT_LINK_ID)
);
ALTER TABLE PMP_PROJECT_COMMENT_LINKS ADD (
 CONSTRAINT PMP_PROJECT_COMMENT_LINKS_R01
 FOREIGN KEY (PMP_PROJECT_ID)
 REFERENCES PMP_PROJECTS (PMP_PROJECT_ID));