ALTER TABLE PMP_MANPOWER
 DROP PRIMARY KEY CASCADE;
DROP TABLE PMP_MANPOWER CASCADE CONSTRAINTS;

CREATE TABLE PMP_MANPOWER
(
	PMP_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
	PMP_REQUEST_YEAR VARCHAR2(4 BYTE) NOT NULL ENABLE,
	PMP_REQUEST_DEPARTMENT_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
	PMP_PERFORM_YEAR VARCHAR2(4 BYTE) NOT NULL ENABLE,
	PMP_PERFORM_DEPARTMENT_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
	PMP_SERVICE_CAT VARCHAR2(10 BYTE) NOT NULL ENABLE,
	PMP_PROJECT_ID VARCHAR2(100 BYTE) NOT NULL ENABLE,
	PMP_MODULE_ID VARCHAR2(100 BYTE) NOT NULL ENABLE,
	PMP_TASK_ID VARCHAR2(100 BYTE) NOT NULL ENABLE,
	PMP_TASK_TYPE VARCHAR2(20 BYTE) NOT NULL ENABLE,
	PMP_REQUIREMENT VARCHAR2(128 BYTE),
	PMP_STAGE VARCHAR2(20 BYTE),
	PMP_CYCLE NUMBER(*,0) DEFAULT 1,
	PMP_USER_ID VARCHAR2(10 BYTE) NOT NULL ENABLE,
	PMP_STATUS VARCHAR2(20 BYTE) NOT NULL ENABLE,
	PMP_WEEK VARCHAR2(2 BYTE) NOT NULL ENABLE,
	PMP_MANPOWER_USED NUMBER NULL,
	PMP_CREATED_DATE DATE DEFAULT SYSDATE,
	PMP_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
	PMP_MODIFIED_DATE DATE DEFAULT SYSDATE,
	PMP_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
	PMP_ENABLED NUMBER(*,0) DEFAULT 1,
	PRIMARY KEY (PMP_SITE_CODE, PMP_REQUEST_YEAR, PMP_REQUEST_DEPARTMENT_CODE, PMP_PERFORM_YEAR, PMP_PERFORM_DEPARTMENT_CODE, PMP_SERVICE_CAT, PMP_PROJECT_ID, PMP_MODULE_ID, PMP_TASK_ID, PMP_TASK_TYPE, PMP_REQUIREMENT, PMP_USER_ID, PMP_WEEK)
);