ALTER TABLE PMP_TASK
 DROP PRIMARY KEY CASCADE;
DROP TABLE PMP_TASK CASCADE CONSTRAINTS;

CREATE TABLE PMP_TASK
(
	PMP_SITE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
	PMP_REQUEST_YEAR VARCHAR2(4 BYTE) NOT NULL ENABLE,
	PMP_REQUEST_DEPARTMENT_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
	PMP_PERFORM_YEAR VARCHAR2(4 BYTE) NOT NULL ENABLE,
	PMP_PERFORM_DEPARTMENT_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
	PMP_SERVICE_CAT VARCHAR2(10 BYTE) NOT NULL ENABLE,
	PMP_PROJECT_ID VARCHAR2(100 BYTE) NOT NULL ENABLE,
	PMP_MODULE_ID VARCHAR2(100 BYTE) NOT NULL ENABLE,
	PMP_TASK_ID VARCHAR2(100 BYTE) NOT NULL ENABLE,
	PMP_TASK_TYPE VARCHAR2(20 BYTE) NOT NULL ENABLE,
	PMP_MANPOWER_REQUIRED NUMBER NOT NULL ENABLE,
	PMP_MANPOWER_LEFT NUMBER DEFAULT 0 NOT NULL ENABLE,
	PMP_CURRENT_STATUS VARCHAR2(20 BYTE) NOT NULL ENABLE,
	PMP_PRIORITIZE NUMBER DEFAULT 9 NOT NULL ENABLE,
	PMP_IN_PROGRESS_SDATE DATE NULL,
	PMP_IN_PROGRESS_EDATE DATE NULL,
	PMP_COMPLETED_SDATE DATE NULL,
	PMP_COMPLETED_EDATE DATE NULL,
	PMP_UAT_SDATE DATE NULL,
	PMP_UAT_EDATE DATE NULL,
	PMP_READY_SDATE DATE NULL,
	PMP_READY_EDATE DATE NULL,
	PMP_LIVE_RUN_SDATE DATE NULL,
	PMP_LIVE_RUN_EDATE DATE NULL,
	PMP_CREATED_DATE DATE DEFAULT SYSDATE,
	PMP_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
	PMP_MODIFIED_DATE DATE DEFAULT SYSDATE,
	PMP_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
	PMP_ENABLED NUMBER(*,0) DEFAULT 1,
	PRIMARY KEY (PMP_SITE_CODE, PMP_REQUEST_YEAR, PMP_REQUEST_DEPARTMENT_CODE, PMP_PERFORM_YEAR, PMP_PERFORM_DEPARTMENT_CODE, PMP_SERVICE_CAT, PMP_PROJECT_ID, PMP_MODULE_ID, PMP_TASK_ID, PMP_TASK_TYPE)
);

INSERT INTO PMP_TASK
(PMP_SITE_CODE,
PMP_REQUEST_YEAR,
PMP_REQUEST_DEPARTMENT_CODE,
PMP_PERFORM_YEAR,
PMP_PERFORM_DEPARTMENT_CODE,
PMP_SERVICE_CAT,
PMP_PROJECT_ID,
PMP_MODULE_ID,
PMP_TASK_ID,
PMP_TASK_TYPE,
PMP_MANPOWER_REQUIRED,
PMP_CURRENT_STATUS
)
SELECT
	PMP_SITE_CODE,
	PMP_REQUEST_YEAR,
	PMP_REQUEST_DEPARTMENT_CODE,
	PMP_PERFORM_YEAR,
	PMP_PERFORM_DEPARTMENT_CODE,
	PMP_SERVICE_CAT,
	PMP_PROJECT_ID,
	PMP_MODULE_ID,
	PMP_TASK_ID,
	PMP_TASK_TYPE,
	SUM(DECODE(PMP_MANPOWER_USED, NULL, 0, PMP_MANPOWER_USED)),
	'IN PROGRESS'
FROM PMP_MANPOWER
GROUP BY PMP_SITE_CODE, PMP_REQUEST_YEAR, PMP_REQUEST_DEPARTMENT_CODE, PMP_PERFORM_YEAR, PMP_PERFORM_DEPARTMENT_CODE, PMP_SERVICE_CAT, PMP_PROJECT_ID, PMP_MODULE_ID, PMP_TASK_ID, PMP_TASK_TYPE;

UPDATE PMP_TASK P
SET   (PMP_CURRENT_STATUS) = (
		SELECT PMP_STATUS
		FROM   PMP_MANPOWER
		WHERE  PMP_SITE_CODE = P.PMP_SITE_CODE
		AND    PMP_PROJECT_ID = P.PMP_PROJECT_ID
		AND    PMP_MODULE_ID = P.PMP_MODULE_ID
		AND    PMP_TASK_ID = P.PMP_TASK_ID
		AND    PMP_WEEK = (SELECT MAX(PMP_WEEK)
     					FROM PMP_MANPOWER
     					WHERE  PMP_SITE_CODE = P.PMP_SITE_CODE
						AND    PMP_PROJECT_ID = P.PMP_PROJECT_ID
     					AND    PMP_MODULE_ID = P.PMP_MODULE_ID
     					AND    PMP_TASK_ID = P.PMP_TASK_ID)
);