ALTER TABLE PMP_PROJECT_COMMENTS_CONTENT
 DROP PRIMARY KEY CASCADE;
DROP TABLE PMP_PROJECT_COMMENTS_CONTENT CASCADE CONSTRAINTS;

CREATE TABLE PMP_PROJECT_COMMENTS_CONTENT
(
 PMP_PROJECT_ID NUMBER(*,0) NOT NULL,
 PMP_COMMENT_ID NUMBER(*,0) DEFAULT 1,
 PMP_COMMENT_HISTORY_ID NUMBER(*,0) DEFAULT 0,
 PMP_CONTENT_ID NUMBER(*,0) NOT NULL,
 PMP_CONTENT VARCHAR2(3800 BYTE) NULL,
 PMP_CREATED_DATE DATE DEFAULT SYSDATE,
 PMP_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 PMP_MODIFIED_DATE DATE DEFAULT SYSDATE,
 PMP_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 PMP_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (PMP_PROJECT_ID, PMP_COMMENT_ID, PMP_COMMENT_HISTORY_ID, PMP_CONTENT_ID)
);
ALTER TABLE PMP_PROJECT_COMMENTS_CONTENT ADD (
 CONSTRAINT PMP_PROJECT_COMMENTS_CONTENT_1
 FOREIGN KEY (PMP_PROJECT_ID)
 REFERENCES PMP_PROJECTS (PMP_PROJECT_ID));