ALTER TABLE PMP_PROJECT
 DROP PRIMARY KEY CASCADE;
DROP TABLE PMP_PROJECT CASCADE CONSTRAINTS;

CREATE TABLE PMP_PROJECT
(
	PMP_SERVICE_CAT VARCHAR2(10 BYTE) NOT NULL ENABLE,
	PMP_PROJECT_ID VARCHAR2(100 BYTE) NOT NULL ENABLE,
	PMP_CURRENT_STATUS VARCHAR2(20 BYTE) NOT NULL ENABLE,
	PMP_IN_PROGRESS_SDATE DATE NULL,
	PMP_IN_PROGRESS_EDATE DATE NULL,
	PMP_COMPLETED_SDATE DATE NULL,
	PMP_COMPLETED_EDATE DATE NULL,
	PMP_UAT_SDATE DATE NULL,
	PMP_UAT_EDATE DATE NULL,
	PMP_READY_SDATE DATE NULL,
	PMP_READY_EDATE DATE NULL,
	PMP_LIVE_RUN_SDATE DATE NULL,
	PMP_LIVE_RUN_EDATE DATE NULL,
	PMP_CREATED_DATE DATE DEFAULT SYSDATE,
	PMP_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
	PMP_MODIFIED_DATE DATE DEFAULT SYSDATE,
	PMP_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
	PMP_ENABLED NUMBER(*,0) DEFAULT 1,
	PRIMARY KEY (PMP_SERVICE_CAT, PMP_PROJECT_ID)
);

INSERT INTO PMP_PROJECT
(PMP_SERVICE_CAT,
PMP_PROJECT_ID,
PMP_CURRENT_STATUS
)
SELECT
	PMP_SERVICE_CAT,
	PMP_PROJECT_ID,
	'IN PROGRESS'
FROM PMP_MANPOWER
GROUP BY PMP_SERVICE_CAT, PMP_PROJECT_ID;

UPDATE PMP_PROJECT P
SET   (PMP_CURRENT_STATUS) = (
		SELECT PMP_STATUS
		FROM   PMP_MANPOWER
		WHERE  PMP_SERVICE_CAT = P.PMP_SERVICE_CAT
		AND    PMP_PROJECT_ID = P.PMP_PROJECT_ID
		AND    PMP_WEEK = (SELECT MAX(PMP_WEEK)
     					FROM   PMP_MANPOWER
     					WHERE  PMP_SERVICE_CAT = P.PMP_SERVICE_CAT
     					AND    PMP_PROJECT_ID = P.PMP_PROJECT_ID)
);