ALTER TABLE PMP_PROJECT_CONTACTS
 DROP PRIMARY KEY CASCADE;
DROP TABLE PMP_PROJECT_CONTACTS CASCADE CONSTRAINTS;

CREATE TABLE PMP_PROJECT_CONTACTS
(
 PMP_PROJECT_ID NUMBER(*,0) NOT NULL,
 PMP_COMMENT_ID NUMBER(*,0) NOT NULL,
 PMP_COMMENT_HISTORY_ID NUMBER(*,0) DEFAULT 0,
 PMP_CONTACT_TYPE VARCHAR2(10 BYTE) NOT NULL,	-- to, from, cc
 PMP_CONTACT_USER_TYPE VARCHAR2(10 BYTE) NOT NULL,	-- staff, patient
 PMP_CONTACT_USER_ID VARCHAR2(20 BYTE) NOT NULL,
 PMP_CONTACT_EMAIL VARCHAR2(100 BYTE),
 PMP_CREATED_DATE DATE DEFAULT SYSDATE,
 PMP_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 PMP_MODIFIED_DATE DATE DEFAULT SYSDATE,
 PMP_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 PMP_ENABLED NUMBER(*,0) DEFAULT 1
);
ALTER TABLE PMP_PROJECT_CONTACTS ADD (
 CONSTRAINT PMP_PROJECT_CONTACTS_R01
 FOREIGN KEY (PMP_PROJECT_ID, PMP_COMMENT_ID, PMP_COMMENT_HISTORY_ID)
 REFERENCES PMP_PROJECT_COMMENTS (PMP_PROJECT_ID, PMP_COMMENT_ID, PMP_COMMENT_HISTORY_ID));