ALTER TABLE PMP_PROJECTS
 DROP PRIMARY KEY CASCADE;
DROP TABLE PMP_PROJECTS CASCADE CONSTRAINTS;

CREATE TABLE PMP_PROJECTS
(
 PMP_PROJECT_ID NUMBER(*,0) DEFAULT 1,
 PMP_PROJECT_DESC VARCHAR2(100 BYTE) NULL,
 PMP_REQ_USER_TYPE VARCHAR2(10 BYTE) NOT NULL,	-- staff, patient
 PMP_REQ_USER_ID VARCHAR2(20 BYTE) NOT NULL,
 PMP_EXPECT_LAUNCH_DATE DATE DEFAULT SYSDATE,
 PMP_ACTUAL_LAUNCH_DATE DATE DEFAULT SYSDATE,
 PMP_APPROVAL_REMARKS VARCHAR2(100 BYTE) NULL,
 PMP_BUDEGET_REMARKS VARCHAR2(100 BYTE) NULL,
 PMP_DOCUMENTS VARCHAR2(1000 BYTE) NULL,
 PMP_STATUS VARCHAR2(20 BYTE) DEFAULT 'preparation',
 PMP_CREATED_DATE DATE DEFAULT SYSDATE,
 PMP_CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 PMP_MODIFIED_DATE DATE DEFAULT SYSDATE,
 PMP_MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
 PMP_ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (PMP_PROJECT_ID)
);