ALTER TABLE RH_THERAPIST
 DROP PRIMARY KEY CASCADE;
DROP TABLE RH_THERAPIST CASCADE CONSTRAINTS;

CREATE TABLE RH_THERAPIST
(
  RH_THERAPIST_CODE VARCHAR2(10 BYTE),
  RH_THERAPIST_NAME VARCHAR2(50 BYTE),
  RH_STAFF_ID VARCHAR2(10 BYTE) NOT NULL,
  RH_CREATED_DATE DATE DEFAULT SYSDATE,
  RH_CREATED_USER VARCHAR2(30) DEFAULT 'SYSTEM',
  RH_MODIFIED_DATE DATE DEFAULT SYSDATE,
  RH_MODIFIED_USER VARCHAR2(30) DEFAULT 'SYSTEM',
  RH_ENABLED NUMBER(*,0) DEFAULT 1,
  PRIMARY KEY (RH_THERAPIST_CODE)
);

INSERT INTO RH_THERAPIST (RH_THERAPIST_CODE, RH_THERAPIST_NAME, RH_STAFF_ID) VALUES ('CC', 'Catherine Chan', '3950');
--INSERT INTO RH_THERAPIST (RH_THERAPIST_CODE, RH_THERAPIST_NAME, RH_STAFF_ID) VALUES ('CL', 'Chung Lilian', '');
--INSERT INTO RH_THERAPIST (RH_THERAPIST_CODE, RH_THERAPIST_NAME, RH_STAFF_ID) VALUES ('CSH', 'Chan Sai Hong', '');
--INSERT INTO RH_THERAPIST (RH_THERAPIST_CODE, RH_THERAPIST_NAME, RH_STAFF_ID) VALUES ('DG', 'Donna Gee', '');
--INSERT INTO RH_THERAPIST (RH_THERAPIST_CODE, RH_THERAPIST_NAME, RH_STAFF_ID) VALUES ('HL', 'Haley Lo', '');
INSERT INTO RH_THERAPIST (RH_THERAPIST_CODE, RH_THERAPIST_NAME, RH_STAFF_ID) VALUES ('JT', 'Jocelyn Tam', '3012');
--INSERT INTO RH_THERAPIST (RH_THERAPIST_CODE, RH_THERAPIST_NAME, RH_STAFF_ID) VALUES ('LC', 'Leung Connie', '');
--INSERT INTO RH_THERAPIST (RH_THERAPIST_CODE, RH_THERAPIST_NAME, RH_STAFF_ID) VALUES ('SN', 'Shirley Ngai', '');
--INSERT INTO RH_THERAPIST (RH_THERAPIST_CODE, RH_THERAPIST_NAME, RH_STAFF_ID) VALUES ('SW', 'Sthenny Wong', '');
INSERT INTO RH_THERAPIST (RH_THERAPIST_CODE, RH_THERAPIST_NAME, RH_STAFF_ID) VALUES ('TW', 'Tony Wong', '3462');
INSERT INTO RH_THERAPIST (RH_THERAPIST_CODE, RH_THERAPIST_NAME, RH_STAFF_ID) VALUES ('VL', 'Vincent Li', '3212');
--INSERT INTO RH_THERAPIST (RH_THERAPIST_CODE, RH_THERAPIST_NAME, RH_STAFF_ID) VALUES ('VW', 'Vivian Wong', '');
INSERT INTO RH_THERAPIST (RH_THERAPIST_CODE, RH_THERAPIST_NAME, RH_STAFF_ID) VALUES ('WJ', 'Joe Wong', '3605');
--INSERT INTO RH_THERAPIST (RH_THERAPIST_CODE, RH_THERAPIST_NAME, RH_STAFF_ID) VALUES ('YC', 'Youkar Cheung', '');
--INSERT INTO RH_THERAPIST (RH_THERAPIST_CODE, RH_THERAPIST_NAME, RH_STAFF_ID) VALUES ('JW', 'Jolly Wan', '');
--INSERT INTO RH_THERAPIST (RH_THERAPIST_CODE, RH_THERAPIST_NAME, RH_STAFF_ID) VALUES ('KW', 'Kathie Wong', '');
--INSERT INTO RH_THERAPIST (RH_THERAPIST_CODE, RH_THERAPIST_NAME, RH_STAFF_ID) VALUES ('EY', 'Emily Yuen', '');
--INSERT INTO RH_THERAPIST (RH_THERAPIST_CODE, RH_THERAPIST_NAME, RH_STAFF_ID) VALUES ('JL', 'Jag Lee', '');
--INSERT INTO RH_THERAPIST (RH_THERAPIST_CODE, RH_THERAPIST_NAME, RH_STAFF_ID) VALUES ('LJ', 'Jacky Leung', '');
INSERT INTO RH_THERAPIST (RH_THERAPIST_CODE, RH_THERAPIST_NAME, RH_STAFF_ID) VALUES ('LM', 'Melani Li', '4543');
--INSERT INTO RH_THERAPIST (RH_THERAPIST_CODE, RH_THERAPIST_NAME, RH_STAFF_ID) VALUES ('TC', 'Tara Choy', '');
INSERT INTO RH_THERAPIST (RH_THERAPIST_CODE, RH_THERAPIST_NAME, RH_STAFF_ID) VALUES ('EC', 'Esther Chan', '4383');
--INSERT INTO RH_THERAPIST (RH_THERAPIST_CODE, RH_THERAPIST_NAME, RH_STAFF_ID) VALUES ('NH', 'Noel Ho', '');
--INSERT INTO RH_THERAPIST (RH_THERAPIST_CODE, RH_THERAPIST_NAME, RH_STAFF_ID) VALUES ('PL', 'Polly Lam', '');
--INSERT INTO RH_THERAPIST (RH_THERAPIST_CODE, RH_THERAPIST_NAME, RH_STAFF_ID) VALUES ('LK', 'Lily Kwong', '');
INSERT INTO RH_THERAPIST (RH_THERAPIST_CODE, RH_THERAPIST_NAME, RH_STAFF_ID) VALUES ('AP', 'Anthony Poon', '5063');
INSERT INTO RH_THERAPIST (RH_THERAPIST_CODE, RH_THERAPIST_NAME, RH_STAFF_ID) VALUES ('AN', 'Anthony Poon', '5063');
INSERT INTO RH_THERAPIST (RH_THERAPIST_CODE, RH_THERAPIST_NAME, RH_STAFF_ID) VALUES ('WY1', 'Winnie Yeung', '4099');
--INSERT INTO RH_THERAPIST (RH_THERAPIST_CODE, RH_THERAPIST_NAME, RH_STAFF_ID) VALUES ('AD', 'Ada Ngan', '');
--INSERT INTO RH_THERAPIST (RH_THERAPIST_CODE, RH_THERAPIST_NAME, RH_STAFF_ID) VALUES ('TP', 'Tommy Poon', '');
INSERT INTO RH_THERAPIST (RH_THERAPIST_CODE, RH_THERAPIST_NAME, RH_STAFF_ID) VALUES ('JTG', 'Joseph Tang', '4249');
INSERT INTO RH_THERAPIST (RH_THERAPIST_CODE, RH_THERAPIST_NAME, RH_STAFF_ID) VALUES ('SLU', 'Stan Lau', '4163');
--INSERT INTO RH_THERAPIST (RH_THERAPIST_CODE, RH_THERAPIST_NAME, RH_STAFF_ID) VALUES ('IC', 'Irene Cheung', '');
--INSERT INTO RH_THERAPIST (RH_THERAPIST_CODE, RH_THERAPIST_NAME, RH_STAFF_ID) VALUES ('IR', 'Irene Chan', '');
INSERT INTO RH_THERAPIST (RH_THERAPIST_CODE, RH_THERAPIST_NAME, RH_STAFF_ID) VALUES ('JE', 'Jennifer Liu', '4311');
INSERT INTO RH_THERAPIST (RH_THERAPIST_CODE, RH_THERAPIST_NAME, RH_STAFF_ID) VALUES ('JC', 'Jack Lee', '4540');
INSERT INTO RH_THERAPIST (RH_THERAPIST_CODE, RH_THERAPIST_NAME, RH_STAFF_ID) VALUES ('JM', 'Jody Mak', '4581');