SELECT P.PATNO AS PATIENT_NO, P.MOTHCODE AS LANGUAGE, B.BKGPNAME AS BOOKING_PATIENT_ENG_NAME, 
B.BKGPCNAME AS BOOKING_PATIENT_CHI_NAME, B.SMCID AS SMS_TEMPLATE, P.COUCODE AS COUNTRY_CODE, 
P.PATPAGER AS MOBILE_PATIENT_RECORD, BKGMTEL AS MOBILE_BOOKING_RECORD ,D.DOCCODE AS DOCTOR_CODE, 
CD.CO_DISPLAYNAME AS DOCTOR_DISPLAY_NAME, D.DOCFNAME || ' ' || D.DOCGNAME AS DOCTOR_ENG_NAME, 
D.DOCCNAME AS DOCTOR_CHI_NAME, TO_CHAR(B.BKGSDATE, 'DD/MM/YYYY') AS BOOKING_DATE, 
B.BKGID AS BOOKING_ID, B.BKGSTS AS BOOKING_STATUS, P.PATSMS, B.SMS

 FROM BOOKING@IWEB B, SCHEDULE@IWEB S, DOCTOR@IWEB D, PATIENT@IWEB P, CO_DOCTORS CD

 WHERE B.BKGSDATE >=
 TO_DATE('14/03/2012 00:00:00', 'DD/MM/YYYY HH24:MI:SS')
 AND   B.BKGSDATE <=
 TO_DATE('14/03/2012 23:59:59', 'DD/MM/YYYY HH24:MI:SS')
 AND   S.SCHID(+) = B.SCHID
 AND   D.DOCCODE(+) = S.DOCCODE
 AND   P.PATNO(+) = B.PATNO
 AND    CD.CO_DOC_CODE(+) = S.DOCCODE
 AND   B.BKGSTS = 'N'
 AND   B.USRID <> 'HACCESS'
 AND   CD.CO_DOC_CODE(+) = S.DOCCODE
 AND   (P.PATSMS = '-1' OR P.PATNO IS NULL) --revSMS
 AND   P.PATSMS = '0' --notRevSMS
 AND   D.DOCCODE <> 'OPDN'
 AND   D.DOCCODE <> 'N020'
 AND   D.DOCCODE <> 'N024'