ALTER TABLE TMP_AMC_SLIP
 DROP PRIMARY KEY CASCADE;
DROP TABLE TMP_AMC_SLIP CASCADE CONSTRAINTS;

CREATE TABLE TMP_AMC_SLIP
(
  PATNO 	VARCHAR2(30 BYTE),
  SLPNO	  	VARCHAR2(45 BYTE),
  REGID	    NUMBER(22) ,
  PATTYPE   VARCHAR2(4 BYTE),
  PATFNAME  VARCHAR2(40 BYTE),
  PATGNAME  VARCHAR2(40 BYTE)
);