package com.hkah.web.db.hibernate;
// default package
// Generated 2010年3月23日 下午02:52:33 by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;

/**
 * AcDocumentAccessId generated by hbm2java
 */
public class AcDocumentAccessId implements java.io.Serializable {

	private BigDecimal acDocumentId;
	private String acUsername;
	private String acUserId;
	private String acStaffId;
	private String acGroupId;

	public AcDocumentAccessId() {
	}

	public AcDocumentAccessId(BigDecimal acDocumentId, String acUsername,
			String acUserId, String acStaffId, String acGroupId) {
		this.acDocumentId = acDocumentId;
		this.acUsername = acUsername;
		this.acUserId = acUserId;
		this.acStaffId = acStaffId;
		this.acGroupId = acGroupId;
	}

	public BigDecimal getAcDocumentId() {
		return this.acDocumentId;
	}

	public void setAcDocumentId(BigDecimal acDocumentId) {
		this.acDocumentId = acDocumentId;
	}

	public String getAcUsername() {
		return this.acUsername;
	}

	public void setAcUsername(String acUsername) {
		this.acUsername = acUsername;
	}

	public String getAcUserId() {
		return this.acUserId;
	}

	public void setAcUserId(String acUserId) {
		this.acUserId = acUserId;
	}

	public String getAcGroupId() {
		return this.acGroupId;
	}

	public String getAcStaffId() {
		return acStaffId;
	}

	public void setAcStaffId(String acStaffId) {
		this.acStaffId = acStaffId;
	}

	public void setAcGroupId(String acGroupId) {
		this.acGroupId = acGroupId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AcDocumentAccessId))
			return false;
		AcDocumentAccessId castOther = (AcDocumentAccessId) other;

		return ((this.getAcDocumentId() == castOther.getAcDocumentId()) || (this
				.getAcDocumentId() != null
				&& castOther.getAcDocumentId() != null && this
				.getAcDocumentId().equals(castOther.getAcDocumentId())))
				&& ((this.getAcUsername() == castOther.getAcUsername()) || (this
						.getAcUsername() != null
						&& castOther.getAcUsername() != null && this
						.getAcUsername().equals(castOther.getAcUsername())))
				&& ((this.getAcUserId() == castOther.getAcUserId()) || (this
						.getAcUserId() != null
						&& castOther.getAcUserId() != null && this
						.getAcUserId().equals(castOther.getAcUserId())))
				&& ((this.getAcStaffId() == castOther.getAcStaffId()) || (this
						.getAcStaffId() != null
						&& castOther.getAcStaffId() != null && this
						.getAcStaffId().equals(castOther.getAcStaffId())))						
				&& ((this.getAcGroupId() == castOther.getAcGroupId()) || (this
						.getAcGroupId() != null
						&& castOther.getAcGroupId() != null && this
						.getAcGroupId().equals(castOther.getAcGroupId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getAcDocumentId() == null ? 0 : this.getAcDocumentId()
						.hashCode());
		result = 37
				* result
				+ (getAcUsername() == null ? 0 : this.getAcUsername()
						.hashCode());
		result = 37 * result
				+ (getAcUserId() == null ? 0 : this.getAcUserId().hashCode());
		result = 37 * result
				+ (getAcStaffId() == null ? 0 : this.getAcStaffId().hashCode());		
		result = 37 * result
				+ (getAcGroupId() == null ? 0 : this.getAcGroupId().hashCode());
		return result;
	}

}
