package com.hkah.web.db.hibernate;

// Generated 2010年5月21日 下午02:30:49 by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CoDepartments generated by hbm2java
 */
public class CoDepartments implements java.io.Serializable {

	private BigDecimal coDepartmentCode;
	private String coDepartmentDesc;
	private Date coCreatedDate;
	private String coCreatedUser;
	private Date coModifiedDate;
	private String coModifiedUser;
	private Integer coEnabled;
	private Set<CrmPromotionDepartment> crmPromotionDepartments = new HashSet<CrmPromotionDepartment>(
			0);

	public CoDepartments() {
	}

	public CoDepartments(BigDecimal coDepartmentCode) {
		this.coDepartmentCode = coDepartmentCode;
	}

	public CoDepartments(BigDecimal coDepartmentCode, String coDepartmentDesc,
			Date coCreatedDate, String coCreatedUser, Date coModifiedDate,
			String coModifiedUser, Integer coEnabled,
			Set<CrmPromotionDepartment> crmPromotionDepartments) {
		this.coDepartmentCode = coDepartmentCode;
		this.coDepartmentDesc = coDepartmentDesc;
		this.coCreatedDate = coCreatedDate;
		this.coCreatedUser = coCreatedUser;
		this.coModifiedDate = coModifiedDate;
		this.coModifiedUser = coModifiedUser;
		this.coEnabled = coEnabled;
		this.crmPromotionDepartments = crmPromotionDepartments;
	}

	public BigDecimal getCoDepartmentCode() {
		return this.coDepartmentCode;
	}

	public void setCoDepartmentCode(BigDecimal coDepartmentCode) {
		this.coDepartmentCode = coDepartmentCode;
	}

	public String getCoDepartmentDesc() {
		return this.coDepartmentDesc;
	}

	public void setCoDepartmentDesc(String coDepartmentDesc) {
		this.coDepartmentDesc = coDepartmentDesc;
	}

	public Date getCoCreatedDate() {
		return this.coCreatedDate;
	}

	public void setCoCreatedDate(Date coCreatedDate) {
		this.coCreatedDate = coCreatedDate;
	}

	public String getCoCreatedUser() {
		return this.coCreatedUser;
	}

	public void setCoCreatedUser(String coCreatedUser) {
		this.coCreatedUser = coCreatedUser;
	}

	public Date getCoModifiedDate() {
		return this.coModifiedDate;
	}

	public void setCoModifiedDate(Date coModifiedDate) {
		this.coModifiedDate = coModifiedDate;
	}

	public String getCoModifiedUser() {
		return this.coModifiedUser;
	}

	public void setCoModifiedUser(String coModifiedUser) {
		this.coModifiedUser = coModifiedUser;
	}

	public Integer getCoEnabled() {
		return this.coEnabled;
	}

	public void setCoEnabled(Integer coEnabled) {
		this.coEnabled = coEnabled;
	}

	public Set<CrmPromotionDepartment> getCrmPromotionDepartments() {
		return this.crmPromotionDepartments;
	}

	public void setCrmPromotionDepartments(
			Set<CrmPromotionDepartment> crmPromotionDepartments) {
		this.crmPromotionDepartments = crmPromotionDepartments;
	}

}
