package com.hkah.web.db.hibernate;

// Generated 2010年7月2日 下午04:17:33 by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import java.util.Date;

/**
 * CoDocumentMailList generated by hbm2java
 */
public class CoDocumentMailList implements java.io.Serializable {

	private BigDecimal coDocumentMailListId;
	private BigDecimal coDocumentId;
	private String coSendType;
	private String coUsername;
	private String coEmail;
	private Date coCreatedDate;
	private String coCreatedUser;
	private Date coModifiedDate;
	private String coModifiedUser;
	private Integer coEnabled;
	
	// derived variable
	private String userEmail;

	public CoDocumentMailList() {
	}

	public CoDocumentMailList(BigDecimal coDocumentMailListId,
			BigDecimal coDocumentId) {
		this.coDocumentMailListId = coDocumentMailListId;
		this.coDocumentId = coDocumentId;
	}

	public CoDocumentMailList(BigDecimal coDocumentMailListId,
			BigDecimal coDocumentId, String coSendType, String coUsername,
			String coEmail, Date coCreatedDate, String coCreatedUser,
			Date coModifiedDate, String coModifiedUser, Integer coEnabled) {
		this.coDocumentMailListId = coDocumentMailListId;
		this.coDocumentId = coDocumentId;
		this.coSendType = coSendType;
		this.coUsername = coUsername;
		this.coEmail = coEmail;
		this.coCreatedDate = coCreatedDate;
		this.coCreatedUser = coCreatedUser;
		this.coModifiedDate = coModifiedDate;
		this.coModifiedUser = coModifiedUser;
		this.coEnabled = coEnabled;
	}

	public BigDecimal getCoDocumentMailListId() {
		return this.coDocumentMailListId;
	}

	public void setCoDocumentMailListId(BigDecimal coDocumentMailListId) {
		this.coDocumentMailListId = coDocumentMailListId;
	}

	public BigDecimal getCoDocumentId() {
		return this.coDocumentId;
	}

	public void setCoDocumentId(BigDecimal coDocumentId) {
		this.coDocumentId = coDocumentId;
	}

	public String getCoSendType() {
		return this.coSendType;
	}

	public void setCoSendType(String coSendType) {
		this.coSendType = coSendType;
	}

	public String getCoUsername() {
		return this.coUsername;
	}

	public void setCoUsername(String coUsername) {
		this.coUsername = coUsername;
	}

	public String getCoEmail() {
		return this.coEmail;
	}

	public void setCoEmail(String coEmail) {
		this.coEmail = coEmail;
	}

	public Date getCoCreatedDate() {
		return this.coCreatedDate;
	}

	public void setCoCreatedDate(Date coCreatedDate) {
		this.coCreatedDate = coCreatedDate;
	}

	public String getCoCreatedUser() {
		return this.coCreatedUser;
	}

	public void setCoCreatedUser(String coCreatedUser) {
		this.coCreatedUser = coCreatedUser;
	}

	public Date getCoModifiedDate() {
		return this.coModifiedDate;
	}

	public void setCoModifiedDate(Date coModifiedDate) {
		this.coModifiedDate = coModifiedDate;
	}

	public String getCoModifiedUser() {
		return this.coModifiedUser;
	}

	public void setCoModifiedUser(String coModifiedUser) {
		this.coModifiedUser = coModifiedUser;
	}

	public Integer getCoEnabled() {
		return this.coEnabled;
	}

	public void setCoEnabled(Integer coEnabled) {
		this.coEnabled = coEnabled;
	}

	/**
	 * @return the userEmail
	 */
	public String getUserEmail() {
		return userEmail;
	}

	/**
	 * @param userEmail the userEmail to set
	 */
	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}
	
	public String getActualEmail() {
		return this.getCoEmail() == null ? this.getUserEmail() : this.getCoEmail();
	}

}
