package com.hkah.web.db.hibernate;

// Generated 2010年5月21日 下午02:30:49 by Hibernate Tools 3.2.0.b9

import java.util.Date;

/**
 * CoSite generated by hbm2java
 */
public class CoSite implements java.io.Serializable {

	private String coSiteCode;
	private String coSiteDesc;
	private Date coCreatedDate;
	private String coCreatedUser;
	private Date coModifiedDate;
	private String coModifiedUser;
	private Integer coEnabled;

	public CoSite() {
	}

	public CoSite(String coSiteCode, String coSiteDesc) {
		this.coSiteCode = coSiteCode;
		this.coSiteDesc = coSiteDesc;
	}

	public CoSite(String coSiteCode, String coSiteDesc, Date coCreatedDate,
			String coCreatedUser, Date coModifiedDate, String coModifiedUser,
			Integer coEnabled) {
		this.coSiteCode = coSiteCode;
		this.coSiteDesc = coSiteDesc;
		this.coCreatedDate = coCreatedDate;
		this.coCreatedUser = coCreatedUser;
		this.coModifiedDate = coModifiedDate;
		this.coModifiedUser = coModifiedUser;
		this.coEnabled = coEnabled;
	}

	public String getCoSiteCode() {
		return this.coSiteCode;
	}

	public void setCoSiteCode(String coSiteCode) {
		this.coSiteCode = coSiteCode;
	}

	public String getCoSiteDesc() {
		return this.coSiteDesc;
	}

	public void setCoSiteDesc(String coSiteDesc) {
		this.coSiteDesc = coSiteDesc;
	}

	public Date getCoCreatedDate() {
		return this.coCreatedDate;
	}

	public void setCoCreatedDate(Date coCreatedDate) {
		this.coCreatedDate = coCreatedDate;
	}

	public String getCoCreatedUser() {
		return this.coCreatedUser;
	}

	public void setCoCreatedUser(String coCreatedUser) {
		this.coCreatedUser = coCreatedUser;
	}

	public Date getCoModifiedDate() {
		return this.coModifiedDate;
	}

	public void setCoModifiedDate(Date coModifiedDate) {
		this.coModifiedDate = coModifiedDate;
	}

	public String getCoModifiedUser() {
		return this.coModifiedUser;
	}

	public void setCoModifiedUser(String coModifiedUser) {
		this.coModifiedUser = coModifiedUser;
	}

	public Integer getCoEnabled() {
		return this.coEnabled;
	}

	public void setCoEnabled(Integer coEnabled) {
		this.coEnabled = coEnabled;
	}

}
