package com.hkah.web.db.hibernate;
// Generated 2010年3月23日 下午02:52:33 by Hibernate Tools 3.2.0.b9

import java.util.Date;

/**
 * CoUsers generated by hbm2java
 */
public class CoUsers implements java.io.Serializable {

	private String coUsername;
	private CoGroups coGroups;
	private String coSiteCode;
	private String coPassword;
	private String coLastname;
	private String coFirstname;
	private String coStreet;
	private String coPostalcode;
	private String coCity;
	private String coCountry;
	private String coLanguage;
	private String coEmail;
	private String coTelephone;
	private String coStaffYn;
	private String coStaffId;
	private String coRemark1;
	private String coRemark2;
	private String coRemark3;
	private Date coCreatedDate;
	private String coCreatedUser;
	private Date coModifiedDate;
	private String coModifiedUser;
	private Integer coEnabled;
	
	// display only
	private String nameDept;

	public CoUsers() {
	}

	public CoUsers(String coUsername, CoGroups coGroups, String coSiteCode) {
		this.coUsername = coUsername;
		this.coGroups = coGroups;
		this.coSiteCode = coSiteCode;
	}

	public CoUsers(String coUsername, CoGroups coGroups, String coSiteCode,
			String coPassword, String coLastname, String coFirstname,
			String coStreet, String coPostalcode, String coCity,
			String coCountry, String coLanguage, String coEmail,
			String coTelephone, String coStaffYn, String coStaffId,
			String coRemark1, String coRemark2, String coRemark3,
			Date coCreatedDate, String coCreatedUser, Date coModifiedDate,
			String coModifiedUser, Integer coEnabled) {
		this.coUsername = coUsername;
		this.coGroups = coGroups;
		this.coSiteCode = coSiteCode;
		this.coPassword = coPassword;
		this.coLastname = coLastname;
		this.coFirstname = coFirstname;
		this.coStreet = coStreet;
		this.coPostalcode = coPostalcode;
		this.coCity = coCity;
		this.coCountry = coCountry;
		this.coLanguage = coLanguage;
		this.coEmail = coEmail;
		this.coTelephone = coTelephone;
		this.coStaffYn = coStaffYn;
		this.coStaffId = coStaffId;
		this.coRemark1 = coRemark1;
		this.coRemark2 = coRemark2;
		this.coRemark3 = coRemark3;
		this.coCreatedDate = coCreatedDate;
		this.coCreatedUser = coCreatedUser;
		this.coModifiedDate = coModifiedDate;
		this.coModifiedUser = coModifiedUser;
		this.coEnabled = coEnabled;
	}

	public String getCoUsername() {
		return this.coUsername;
	}

	public void setCoUsername(String coUsername) {
		this.coUsername = coUsername;
	}

	public CoGroups getCoGroups() {
		return this.coGroups;
	}

	public void setCoGroups(CoGroups coGroups) {
		this.coGroups = coGroups;
	}

	public String getCoSiteCode() {
		return this.coSiteCode;
	}

	public void setCoSiteCode(String coSiteCode) {
		this.coSiteCode = coSiteCode;
	}

	public String getCoPassword() {
		return this.coPassword;
	}

	public void setCoPassword(String coPassword) {
		this.coPassword = coPassword;
	}

	public String getCoLastname() {
		return this.coLastname;
	}

	public void setCoLastname(String coLastname) {
		this.coLastname = coLastname;
	}

	public String getCoFirstname() {
		return this.coFirstname;
	}

	public void setCoFirstname(String coFirstname) {
		this.coFirstname = coFirstname;
	}

	public String getCoStreet() {
		return this.coStreet;
	}

	public void setCoStreet(String coStreet) {
		this.coStreet = coStreet;
	}

	public String getCoPostalcode() {
		return this.coPostalcode;
	}

	public void setCoPostalcode(String coPostalcode) {
		this.coPostalcode = coPostalcode;
	}

	public String getCoCity() {
		return this.coCity;
	}

	public void setCoCity(String coCity) {
		this.coCity = coCity;
	}

	public String getCoCountry() {
		return this.coCountry;
	}

	public void setCoCountry(String coCountry) {
		this.coCountry = coCountry;
	}

	public String getCoLanguage() {
		return this.coLanguage;
	}

	public void setCoLanguage(String coLanguage) {
		this.coLanguage = coLanguage;
	}

	public String getCoEmail() {
		return this.coEmail;
	}

	public void setCoEmail(String coEmail) {
		this.coEmail = coEmail;
	}

	public String getCoTelephone() {
		return this.coTelephone;
	}

	public void setCoTelephone(String coTelephone) {
		this.coTelephone = coTelephone;
	}

	public String getCoStaffYn() {
		return this.coStaffYn;
	}

	public void setCoStaffYn(String coStaffYn) {
		this.coStaffYn = coStaffYn;
	}

	public String getCoStaffId() {
		return this.coStaffId;
	}

	public void setCoStaffId(String coStaffId) {
		this.coStaffId = coStaffId;
	}

	public String getCoRemark1() {
		return this.coRemark1;
	}

	public void setCoRemark1(String coRemark1) {
		this.coRemark1 = coRemark1;
	}

	public String getCoRemark2() {
		return this.coRemark2;
	}

	public void setCoRemark2(String coRemark2) {
		this.coRemark2 = coRemark2;
	}

	public String getCoRemark3() {
		return this.coRemark3;
	}

	public void setCoRemark3(String coRemark3) {
		this.coRemark3 = coRemark3;
	}

	public Date getCoCreatedDate() {
		return this.coCreatedDate;
	}

	public void setCoCreatedDate(Date coCreatedDate) {
		this.coCreatedDate = coCreatedDate;
	}

	public String getCoCreatedUser() {
		return this.coCreatedUser;
	}

	public void setCoCreatedUser(String coCreatedUser) {
		this.coCreatedUser = coCreatedUser;
	}

	public Date getCoModifiedDate() {
		return this.coModifiedDate;
	}

	public void setCoModifiedDate(Date coModifiedDate) {
		this.coModifiedDate = coModifiedDate;
	}

	public String getCoModifiedUser() {
		return this.coModifiedUser;
	}

	public void setCoModifiedUser(String coModifiedUser) {
		this.coModifiedUser = coModifiedUser;
	}

	public Integer getCoEnabled() {
		return this.coEnabled;
	}

	public void setCoEnabled(Integer coEnabled) {
		this.coEnabled = coEnabled;
	}

	/**
	 * @return the nameDept
	 */
	public String getNameDept() {
		return nameDept;
	}

	/**
	 * @param nameDept the nameDept to set
	 */
	public void setNameDept(String nameDept) {
		this.nameDept = nameDept;
	}

}
