package com.hkah.web.db.hibernate;

// Generated 2010年5月21日 下午02:30:49 by Hibernate Tools 3.2.0.b9

import java.util.Date;

/**
 * CrmPromotionDepartment generated by hbm2java
 */
public class CrmPromotionDepartment implements java.io.Serializable {

	private CrmPromotionDepartmentId id;
	private CoDepartments coDepartments;
	private CrmPromotion crmPromotion;
	private Date crmCreatedDate;
	private String crmCreatedUser;
	private Date crmModifiedDate;
	private String crmModifiedUser;
	private Integer crmEnabled;

	public CrmPromotionDepartment() {
	}

	public CrmPromotionDepartment(CrmPromotionDepartmentId id,
			CoDepartments coDepartments, CrmPromotion crmPromotion) {
		this.id = id;
		this.coDepartments = coDepartments;
		this.crmPromotion = crmPromotion;
	}

	public CrmPromotionDepartment(CrmPromotionDepartmentId id,
			CoDepartments coDepartments, CrmPromotion crmPromotion,
			Date crmCreatedDate, String crmCreatedUser, Date crmModifiedDate,
			String crmModifiedUser, Integer crmEnabled) {
		this.id = id;
		this.coDepartments = coDepartments;
		this.crmPromotion = crmPromotion;
		this.crmCreatedDate = crmCreatedDate;
		this.crmCreatedUser = crmCreatedUser;
		this.crmModifiedDate = crmModifiedDate;
		this.crmModifiedUser = crmModifiedUser;
		this.crmEnabled = crmEnabled;
	}

	public CrmPromotionDepartmentId getId() {
		return this.id;
	}

	public void setId(CrmPromotionDepartmentId id) {
		this.id = id;
	}

	public CoDepartments getCoDepartments() {
		return this.coDepartments;
	}

	public void setCoDepartments(CoDepartments coDepartments) {
		this.coDepartments = coDepartments;
	}

	public CrmPromotion getCrmPromotion() {
		return this.crmPromotion;
	}

	public void setCrmPromotion(CrmPromotion crmPromotion) {
		this.crmPromotion = crmPromotion;
	}

	public Date getCrmCreatedDate() {
		return this.crmCreatedDate;
	}

	public void setCrmCreatedDate(Date crmCreatedDate) {
		this.crmCreatedDate = crmCreatedDate;
	}

	public String getCrmCreatedUser() {
		return this.crmCreatedUser;
	}

	public void setCrmCreatedUser(String crmCreatedUser) {
		this.crmCreatedUser = crmCreatedUser;
	}

	public Date getCrmModifiedDate() {
		return this.crmModifiedDate;
	}

	public void setCrmModifiedDate(Date crmModifiedDate) {
		this.crmModifiedDate = crmModifiedDate;
	}

	public String getCrmModifiedUser() {
		return this.crmModifiedUser;
	}

	public void setCrmModifiedUser(String crmModifiedUser) {
		this.crmModifiedUser = crmModifiedUser;
	}

	public Integer getCrmEnabled() {
		return this.crmEnabled;
	}

	public void setCrmEnabled(Integer crmEnabled) {
		this.crmEnabled = crmEnabled;
	}

}
