package com.hkah.web.db.hibernate;

// Generated Aug 3, 2010 4:07:00 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;

/**
 * CrmPromotionClient generated by hbm2java
 */
public class CrmPromotionClient implements java.io.Serializable {

	private CrmPromotionClientId id;
	private Date crmCreateDate;
	private String crmCreateUser;
	private Date crmModifiedDate;
	private String crmModifiedUser;
	private Integer crmEnabled;
	private CrmPromotion crmPromotion;
	private String crmClient_FirstName;
	private String crmClient_DisplayName;
	private String crmClient_LastName;
	private String crmClient_ChineseName;

	public CrmPromotionClient() {
	}

	public CrmPromotionClient(CrmPromotionClientId id) {
		this.id = id;
	}

	public CrmPromotionClient(CrmPromotionClientId id, Date crmCreateDate,
			String crmCreateUser, Date crmModifiedDate, String crmModifiedUser,
			Integer crmEnabled,String crmClient_FirstName, String crmClient_LastName, String crmClient_ChineseName) {
		this.id = id;
		this.crmCreateDate = crmCreateDate;
		this.crmCreateUser = crmCreateUser;
		this.crmModifiedDate = crmModifiedDate;
		this.crmModifiedUser = crmModifiedUser;
		this.crmEnabled = crmEnabled;
		this.crmClient_FirstName = crmClient_FirstName;
		this.crmClient_LastName = crmClient_LastName;
		this.crmClient_ChineseName = crmClient_ChineseName;
	}

	public CrmPromotionClientId getId() {
		return this.id;
	}

	public void setId(CrmPromotionClientId id) {
		this.id = id;
	}

	public Date getCrmCreateDate() {
		return this.crmCreateDate;
	}

	public CrmPromotion getCrmPromotion() {
		return this.crmPromotion;
	}

	public void setCrmPromotion(CrmPromotion crmPromotion) {
		this.crmPromotion = crmPromotion;
	}
	
	public void setCrmCreateDate(Date crmCreateDate) {
		this.crmCreateDate = crmCreateDate;
	}

	public String getCrmCreateUser() {
		return this.crmCreateUser;
	}

	public void setCrmCreateUser(String crmCreateUser) {
		this.crmCreateUser = crmCreateUser;
	}

	public Date getCrmModifiedDate() {
		return this.crmModifiedDate;
	}

	public void setCrmModifiedDate(Date crmModifiedDate) {
		this.crmModifiedDate = crmModifiedDate;
	}

	public String getCrmModifiedUser() {
		return this.crmModifiedUser;
	}

	public void setCrmModifiedUser(String crmModifiedUser) {
		this.crmModifiedUser = crmModifiedUser;
	}

	public String getCrmClient_FirstName() {
		return this.crmClient_FirstName;
	}

	public void setCrmClient_LastName(String crmClient_LastName) {
		this.crmClient_LastName = crmClient_LastName;
	}	
	
	public String getCrmClient_LastName() {
		return this.crmClient_LastName;
	}
	
	public void setCrmClient_ChineseName(String crmClient_ChineseName) {
		this.crmClient_ChineseName = crmClient_ChineseName;
	}	
	
	public String getCrmClient_ChineseName() {
		return this.crmClient_ChineseName;
	}
	
	public void setCrmClient_FirstName(String crmClient_FirstName) {
		this.crmClient_FirstName = crmClient_FirstName;
	}
	
	public Integer getCrmEnabled() {
		return this.crmEnabled;
	}
	
	public String getCrmClient_DisplayName() {
	   if ( (!"".equals(this.crmClient_ChineseName)|| this.crmClient_ChineseName != null) && ("".equals(this.crmClient_FirstName) || this.crmClient_FirstName == null)){
			  this.crmClient_DisplayName = this.crmClient_ChineseName;
		  }
	   else if(!"".equals(this.crmClient_FirstName) ||this.crmClient_FirstName != null && !"".equals(this.crmClient_LastName)|| this.crmClient_LastName != null){
		this.crmClient_DisplayName = this.crmClient_LastName + this.crmClient_FirstName;
	  }
	  else if ("".equals(this.crmClient_LastName) || this.crmClient_LastName == null){
		  this.crmClient_DisplayName = this.crmClient_FirstName; 
	  }
	  else if ("".equals(this.crmClient_FirstName) || this.crmClient_FirstName == null){
		  this.crmClient_DisplayName = this.crmClient_LastName; 
	  }

	  
	  return this.crmClient_DisplayName;
	}

	public void setCrmEnabled(Integer crmEnabled) {
		this.crmEnabled = crmEnabled;
	}

}
