package com.hkah.web.db.hibernate;

// Generated 2010年5月21日 下午02:30:49 by Hibernate Tools 3.2.0.b9

import java.util.Date;

/**
 * CrmPromotionDocument generated by hbm2java
 */
public class CrmPromotionDocument implements java.io.Serializable {

	private CrmPromotionDocumentId id;
	private String crmDocumentType;
	private CrmPromotion crmPromotion;
	private Date crmCreatedDate;
	private String crmCreatedUser;
	private Date crmModifiedDate;
	private String crmModifiedUser;
	private Integer crmEnabled;

	// derived variable
	private String coDirectory;
	private String coDocumentDesc;
	
	public CrmPromotionDocument() {
	}

	public CrmPromotionDocument(CrmPromotionDocumentId id,
			CrmPromotion crmPromotion) {
		this.id = id;
		this.crmPromotion = crmPromotion;
	}

	public CrmPromotionDocument(CrmPromotionDocumentId id,
			CrmPromotion crmPromotion, String crmDocumentType,
			Date crmCreatedDate, String crmCreatedUser, 
			Date crmModifiedDate, String crmModifiedUser, Integer crmEnabled) {
		this.id = id;
		this.crmPromotion = crmPromotion;
		this.crmDocumentType = crmDocumentType;
		this.crmCreatedDate = crmCreatedDate;
		this.crmCreatedUser = crmCreatedUser;
		this.crmModifiedDate = crmModifiedDate;
		this.crmModifiedUser = crmModifiedUser;
		this.crmEnabled = crmEnabled;
	}

	public CrmPromotionDocumentId getId() {
		return this.id;
	}

	public void setId(CrmPromotionDocumentId id) {
		this.id = id;
	}

	/**
	 * @return the crmDocumentType
	 */
	public String getCrmDocumentType() {
		return crmDocumentType;
	}

	/**
	 * @param crmDocumentType the crmDocumentType to set
	 */
	public void setCrmDocumentType(String crmDocumentType) {
		this.crmDocumentType = crmDocumentType;
	}

	public CrmPromotion getCrmPromotion() {
		return this.crmPromotion;
	}

	public void setCrmPromotion(CrmPromotion crmPromotion) {
		this.crmPromotion = crmPromotion;
	}

	public Date getCrmCreatedDate() {
		return this.crmCreatedDate;
	}

	public void setCrmCreatedDate(Date crmCreatedDate) {
		this.crmCreatedDate = crmCreatedDate;
	}

	public String getCrmCreatedUser() {
		return this.crmCreatedUser;
	}

	public void setCrmCreatedUser(String crmCreatedUser) {
		this.crmCreatedUser = crmCreatedUser;
	}

	public Date getCrmModifiedDate() {
		return this.crmModifiedDate;
	}

	public void setCrmModifiedDate(Date crmModifiedDate) {
		this.crmModifiedDate = crmModifiedDate;
	}

	public String getCrmModifiedUser() {
		return this.crmModifiedUser;
	}

	public void setCrmModifiedUser(String crmModifiedUser) {
		this.crmModifiedUser = crmModifiedUser;
	}

	public Integer getCrmEnabled() {
		return this.crmEnabled;
	}

	public void setCrmEnabled(Integer crmEnabled) {
		this.crmEnabled = crmEnabled;
	}

	/**
	 * @return the coDirectory
	 */
	public String getCoDirectory() {
		return coDirectory;
	}

	/**
	 * @param coDirectory the coDirectory to set
	 */
	public void setCoDirectory(String coDirectory) {
		this.coDirectory = coDirectory;
	}

	/**
	 * @return the coDocumentDesc
	 */
	public String getCoDocumentDesc() {
		return coDocumentDesc;
	}

	/**
	 * @param coDocumentDesc the coDocumentDesc to set
	 */
	public void setCoDocumentDesc(String coDocumentDesc) {
		this.coDocumentDesc = coDocumentDesc;
	}
	
}
