package com.hkah.web.db.hibernate;

// Generated 2010年5月21日 下午02:30:49 by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;

/**
 * CrmPromotionTargetId generated by hbm2java
 */
public class CrmPromotionTargetId implements java.io.Serializable {

	private String crmSiteCode;
	private String crmModuleCode;
	private BigDecimal crmEventId;
	private BigDecimal crmTargetId;

	public CrmPromotionTargetId() {
	}

	public CrmPromotionTargetId(String crmSiteCode, String crmModuleCode,
			BigDecimal crmEventId, BigDecimal crmTargetId) {
		this.crmSiteCode = crmSiteCode;
		this.crmModuleCode = crmModuleCode;
		this.crmEventId = crmEventId;
		this.crmTargetId = crmTargetId;
	}

	public String getCrmSiteCode() {
		return this.crmSiteCode;
	}

	public void setCrmSiteCode(String crmSiteCode) {
		this.crmSiteCode = crmSiteCode;
	}

	public String getCrmModuleCode() {
		return this.crmModuleCode;
	}

	public void setCrmModuleCode(String crmModuleCode) {
		this.crmModuleCode = crmModuleCode;
	}

	public BigDecimal getCrmEventId() {
		return this.crmEventId;
	}

	public void setCrmEventId(BigDecimal crmEventId) {
		this.crmEventId = crmEventId;
	}

	public BigDecimal getCrmTargetId() {
		return this.crmTargetId;
	}

	public void setCrmTargetId(BigDecimal crmTargetId) {
		this.crmTargetId = crmTargetId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CrmPromotionTargetId))
			return false;
		CrmPromotionTargetId castOther = (CrmPromotionTargetId) other;

		return ((this.getCrmSiteCode() == castOther.getCrmSiteCode()) || (this
				.getCrmSiteCode() != null
				&& castOther.getCrmSiteCode() != null && this.getCrmSiteCode()
				.equals(castOther.getCrmSiteCode())))
				&& ((this.getCrmModuleCode() == castOther.getCrmModuleCode()) || (this
						.getCrmModuleCode() != null
						&& castOther.getCrmModuleCode() != null && this
						.getCrmModuleCode()
						.equals(castOther.getCrmModuleCode())))
				&& ((this.getCrmEventId() == castOther.getCrmEventId()) || (this
						.getCrmEventId() != null
						&& castOther.getCrmEventId() != null && this
						.getCrmEventId().equals(castOther.getCrmEventId())))
				&& ((this.getCrmTargetId() == castOther.getCrmTargetId()) || (this
						.getCrmTargetId() != null
						&& castOther.getCrmTargetId() != null && this
						.getCrmTargetId().equals(castOther.getCrmTargetId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCrmSiteCode() == null ? 0 : this.getCrmSiteCode()
						.hashCode());
		result = 37
				* result
				+ (getCrmModuleCode() == null ? 0 : this.getCrmModuleCode()
						.hashCode());
		result = 37
				* result
				+ (getCrmEventId() == null ? 0 : this.getCrmEventId()
						.hashCode());
		result = 37
				* result
				+ (getCrmTargetId() == null ? 0 : this.getCrmTargetId()
						.hashCode());
		return result;
	}

}
