package com.hkah.web.db.hibernate;

// Generated 2010年5月21日 下午02:30:49 by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.Iterator;
import java.util.LinkedHashSet;
import java.util.Set;

import com.hkah.util.DateTimeUtil;
import com.hkah.web.controller.CRMController;

/**
 * CrmPromotion generated by hbm2java
 */
public class CrmPromotion implements java.io.Serializable {

	private CrmPromotionId id;
	private CrmPromotionRefCode crmPromotionRefCode;
	private CoEvent coEvent;
	private Date crmInitialDateFm;
	private Date crmInitialDateTo;
	private String crmPromoteRemarks;
	private String crmPromoteDetails;
	private String crmPromoteMaterials;
	private String crmRefCode;
	private String crmPromoteComment;
	private Date crmCreatedDate;
	private String crmCreatedUser;
	private Date crmModifiedDate;
	private String crmModifiedUser;
	private Integer crmEnabled;
	private Set<CrmPromotionDepartment> crmPromotionDepartments = new LinkedHashSet<CrmPromotionDepartment>(
			0);
	private Set<CrmPromotionTarget> crmPromotionTargets = new LinkedHashSet<CrmPromotionTarget>(
			0);
	private Set<CrmPromotionDocument> crmPromotionDocuments = new LinkedHashSet<CrmPromotionDocument>(
			0);
	private Set<CrmPromotionInstruction> crmPromotionInstructions = new LinkedHashSet<CrmPromotionInstruction>(
			0);
	private Set<CrmPromotionEnquiry> crmPromotionEnquiries = new LinkedHashSet<CrmPromotionEnquiry>(
			0);
	private Set<CrmPromotionClient> crmPromotionClient = new LinkedHashSet<CrmPromotionClient>(
			0);
	
	
	public CrmPromotion() {
	}

	public CrmPromotion(CrmPromotionId id) {
		this.id = id;
	}

	public CrmPromotion(CrmPromotionId id, CoEvent coEvent, CrmPromotionRefCode crmPromotionRefCode,
			Date crmInitialDateFm, Date crmInitialDateTo, String crmPromoteRemarks,
			String crmPromoteDetails, String crmPromoteMaterials,
			String crmRefCode, String crmPromoteComment, Date crmCreatedDate,
			String crmCreatedUser, Date crmModifiedDate,
			String crmModifiedUser, Integer crmEnabled,
			Set<CrmPromotionDepartment> crmPromotionDepartments,
			Set<CrmPromotionTarget> crmPromotionTargets,
			Set<CrmPromotionDocument> crmPromotionDocuments,
			Set<CrmPromotionInstruction> crmPromotionInstructions,
			Set<CrmPromotionEnquiry> crmPromotionEnquiries,
			Set<CrmPromotionClient>crmPromotionClient) {
		this.id = id;
		this.coEvent = coEvent;
		this.crmInitialDateFm = crmInitialDateFm;
		this.crmInitialDateTo = crmInitialDateTo;
		this.crmPromoteRemarks = crmPromoteRemarks;
		this.crmPromoteDetails = crmPromoteDetails;
		this.crmPromoteMaterials = crmPromoteMaterials;
		this.crmRefCode = crmRefCode;
		this.crmPromoteComment = crmPromoteComment;
		this.crmCreatedDate = crmCreatedDate;
		this.crmCreatedUser = crmCreatedUser;
		this.crmModifiedDate = crmModifiedDate;
		this.crmModifiedUser = crmModifiedUser;
		this.crmEnabled = crmEnabled;
		this.crmPromotionDepartments = crmPromotionDepartments;
		this.crmPromotionTargets = crmPromotionTargets;
		this.crmPromotionDocuments = crmPromotionDocuments;
		this.crmPromotionInstructions = crmPromotionInstructions;
		this.crmPromotionEnquiries = crmPromotionEnquiries;
		this.crmPromotionClient = crmPromotionClient;
		
	}

	public CrmPromotionId getId() {
		return this.id;
	}

	public void setId(CrmPromotionId id) {
		this.id = id;
	}

	public CrmPromotionRefCode getCrmPromotionRefCode() {
		return this.crmPromotionRefCode;
	}

	public void setCrmPromotionRefCode(CrmPromotionRefCode crmPromotionRefCode) {
		this.crmPromotionRefCode = crmPromotionRefCode;
	}

	public CoEvent getCoEvent() {
		return this.coEvent;
	}

	public void setCoEvent(CoEvent coEvent) {
		this.coEvent = coEvent;
	}

	public Date getCrmInitialDateFm() {
		return this.crmInitialDateFm;
	}

	public void setCrmInitialDateFm(Date crmInitialDateFm) {
		this.crmInitialDateFm = crmInitialDateFm;
	}

	public Date getCrmInitialDateTo() {
		return this.crmInitialDateTo;
	}

	public void setCrmInitialDateTo(Date crmInitialDateTo) {
		this.crmInitialDateTo = crmInitialDateTo;
	}

	public String getCrmPromoteRemarks() {
		return this.crmPromoteRemarks;
	}

	public void setCrmPromoteRemarks(String crmPromoteRemarks) {
		this.crmPromoteRemarks = crmPromoteRemarks;
	}

	public String getCrmPromoteDetails() {
		return this.crmPromoteDetails;
	}

	public void setCrmPromoteDetails(String crmPromoteDetails) {
		this.crmPromoteDetails = crmPromoteDetails;
	}

	public String getCrmPromoteMaterials() {
		return this.crmPromoteMaterials;
	}

	public void setCrmPromoteMaterials(String crmPromoteMaterials) {
		this.crmPromoteMaterials = crmPromoteMaterials;
	}

	public String getCrmRefCode() {
		return this.crmRefCode;
	}

	public void setCrmRefCode(String crmRefCode) {
		this.crmRefCode = crmRefCode;
	}

	public String getCrmPromoteComment() {
		return this.crmPromoteComment;
	}

	public void setCrmPromoteComment(String crmPromoteComment) {
		this.crmPromoteComment = crmPromoteComment;
	}

	public Date getCrmCreatedDate() {
		return this.crmCreatedDate;
	}

	public void setCrmCreatedDate(Date crmCreatedDate) {
		this.crmCreatedDate = crmCreatedDate;
	}

	public String getCrmCreatedUser() {
		return this.crmCreatedUser;
	}

	public void setCrmCreatedUser(String crmCreatedUser) {
		this.crmCreatedUser = crmCreatedUser;
	}

	public Date getCrmModifiedDate() {
		return this.crmModifiedDate;
	}

	public void setCrmModifiedDate(Date crmModifiedDate) {
		this.crmModifiedDate = crmModifiedDate;
	}

	public String getCrmModifiedUser() {
		return this.crmModifiedUser;
	}

	public void setCrmModifiedUser(String crmModifiedUser) {
		this.crmModifiedUser = crmModifiedUser;
	}

	public Integer getCrmEnabled() {
		return this.crmEnabled;
	}

	public void setCrmEnabled(Integer crmEnabled) {
		this.crmEnabled = crmEnabled;
	}

	public Set<CrmPromotionDepartment> getCrmPromotionDepartments() {
		return this.crmPromotionDepartments;
	}

	public void setCrmPromotionDepartments(
			Set<CrmPromotionDepartment> crmPromotionDepartments) {
		this.crmPromotionDepartments = crmPromotionDepartments;
	}

	public Set<CrmPromotionTarget> getCrmPromotionTargets() {
		return this.crmPromotionTargets;
	}

	public void setCrmPromotionTargets(
			Set<CrmPromotionTarget> crmPromotionTargets) {
		this.crmPromotionTargets = crmPromotionTargets;
	}

	public Set<CrmPromotionDocument> getCrmPromotionDocuments() {
		return this.crmPromotionDocuments;
	}

	public void setCrmPromotionDocuments(
			Set<CrmPromotionDocument> crmPromotionDocuments) {
		this.crmPromotionDocuments = crmPromotionDocuments;
	}

	public Set<CrmPromotionInstruction> getCrmPromotionInstructions() {
		return this.crmPromotionInstructions;
	}

	public void setCrmPromotionInstructions(
			Set<CrmPromotionInstruction> crmPromotionInstructions) {
		this.crmPromotionInstructions = crmPromotionInstructions;
	}

	public Set<CrmPromotionEnquiry> getCrmPromotionEnquiries() {
		return this.crmPromotionEnquiries;
	}

	public void setCrmPromotionEnquiries(
			Set<CrmPromotionEnquiry> crmPromotionEnquiries) {
		this.crmPromotionEnquiries = crmPromotionEnquiries;
	}
	//cherry//
	public Set<CrmPromotionClient> getCrmPromotionClient() {
		return this.crmPromotionClient;
	}

	public void setCrmPromotionClient(
			Set<CrmPromotionClient> crmPromotionClient) {
		this.crmPromotionClient = crmPromotionClient;
	}
	//cherry//
	public Set<CrmPromotionDocument> getCrmPromotionDocumentsDetail() {
		Set<CrmPromotionDocument> documentDetails = null;
		
		if (this.getCrmPromotionDocuments() != null && !this.getCrmPromotionDocuments().isEmpty()) {
			documentDetails = new LinkedHashSet<CrmPromotionDocument>(0);
			CrmPromotionDocument doc = null;
			for (Iterator<CrmPromotionDocument> itr = this.getCrmPromotionDocuments().iterator(); itr.hasNext(); ) {
				doc = itr.next();
				if (doc != null && CRMController.CRM_DOCUMENT_TYPE_DETAILS.equals(doc.getCrmDocumentType())) {
					documentDetails.add(doc);
				}
			}
		}
		
		return documentDetails;
	}
	
	public Set<CrmPromotionDocument> getCrmPromotionDocumentsMaterial() {
		Set<CrmPromotionDocument> documentMaterials = null;
		
		if (this.getCrmPromotionDocuments() != null && !this.getCrmPromotionDocuments().isEmpty()) {
			documentMaterials = new LinkedHashSet<CrmPromotionDocument>(0);
			CrmPromotionDocument doc = null;
			for (Iterator<CrmPromotionDocument> itr = this.getCrmPromotionDocuments().iterator(); itr.hasNext(); ) {
				doc = itr.next();
				if (doc != null && CRMController.CRM_DOCUMENT_TYPE_MATERIALS.equals(doc.getCrmDocumentType())) {
					documentMaterials.add(doc);
				}
			}
		}
		
		return documentMaterials;
	}
	
	public boolean isCurrent() {
		Date now = new Date();
		if (this.crmInitialDateFm != null && !now.before(crmInitialDateFm)) {
			if (this.crmInitialDateTo != null) {
				if (now.before(this.crmInitialDateTo)) {
					return true;
				} else {
					return false;
				}
			} else {
				return true;
			}
		}
		return false;
	}
	
	public boolean isComing() {
		Date now = new Date();
		if (this.crmInitialDateFm != null && now.before(crmInitialDateFm)) {
			return true;
		}
		return false;
	}
	
	public boolean isExpired() {
		Date now = new Date();
		if (this.crmInitialDateTo != null && now.after(crmInitialDateTo)) {
			return true;
		}
		return false;
	}
	
	// formatted output
	public String getCrmInitialDateFmDisplay() {
		if (this.getCrmInitialDateFm() != null) {
			return DateTimeUtil.formatDate(this.getCrmInitialDateFm());
		} else {
			return "";
		}
	}
	
	public String getCrmInitialDateToDisplay() {
		if (this.getCrmInitialDateTo() != null) {
			return DateTimeUtil.formatDate(this.getCrmInitialDateTo());
		} else {
			return "";
		}
	}
}
