package com.hkah.web.db.hibernate;

// Generated 2010年6月29日 下午03:58:53 by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;

/**
 * DbCommentDocumentId generated by hbm2java
 */
public class DbCommentDocumentId implements java.io.Serializable {

	private String dbSiteCode;
	private String dbModuleCode;
	private BigDecimal dbRecordId;
	private BigDecimal dbCommentId;
	private BigDecimal dbCommentDocumentId;
	private BigDecimal dbCommentSeq;

	public DbCommentDocumentId() {
	}

	public DbCommentDocumentId(String dbSiteCode, String dbModuleCode,
			BigDecimal dbRecordId, BigDecimal dbCommentId,
			BigDecimal dbCommentDocumentId, BigDecimal dbCommentSeq) {
		this.dbSiteCode = dbSiteCode;
		this.dbModuleCode = dbModuleCode;
		this.dbRecordId = dbRecordId;
		this.dbCommentId = dbCommentId;
		this.dbCommentDocumentId = dbCommentDocumentId;
		this.dbCommentSeq = dbCommentSeq;
	}

	public String getDbSiteCode() {
		return this.dbSiteCode;
	}

	public void setDbSiteCode(String dbSiteCode) {
		this.dbSiteCode = dbSiteCode;
	}

	public String getDbModuleCode() {
		return this.dbModuleCode;
	}

	public void setDbModuleCode(String dbModuleCode) {
		this.dbModuleCode = dbModuleCode;
	}

	public BigDecimal getDbRecordId() {
		return this.dbRecordId;
	}

	public void setDbRecordId(BigDecimal dbRecordId) {
		this.dbRecordId = dbRecordId;
	}

	public BigDecimal getDbCommentId() {
		return this.dbCommentId;
	}

	public void setDbCommentId(BigDecimal dbCommentId) {
		this.dbCommentId = dbCommentId;
	}

	public BigDecimal getDbCommentDocumentId() {
		return this.dbCommentDocumentId;
	}

	public void setDbCommentDocumentId(BigDecimal dbCommentDocumentId) {
		this.dbCommentDocumentId = dbCommentDocumentId;
	}

	public BigDecimal getDbCommentSeq() {
		return this.dbCommentSeq;
	}

	public void setDbCommentSeq(BigDecimal dbCommentSeq) {
		this.dbCommentSeq = dbCommentSeq;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DbCommentDocumentId))
			return false;
		DbCommentDocumentId castOther = (DbCommentDocumentId) other;

		return ((this.getDbSiteCode() == castOther.getDbSiteCode()) || (this
				.getDbSiteCode() != null
				&& castOther.getDbSiteCode() != null && this.getDbSiteCode()
				.equals(castOther.getDbSiteCode())))
				&& ((this.getDbModuleCode() == castOther.getDbModuleCode()) || (this
						.getDbModuleCode() != null
						&& castOther.getDbModuleCode() != null && this
						.getDbModuleCode().equals(castOther.getDbModuleCode())))
				&& ((this.getDbRecordId() == castOther.getDbRecordId()) || (this
						.getDbRecordId() != null
						&& castOther.getDbRecordId() != null && this
						.getDbRecordId().equals(castOther.getDbRecordId())))
				&& ((this.getDbCommentId() == castOther.getDbCommentId()) || (this
						.getDbCommentId() != null
						&& castOther.getDbCommentId() != null && this
						.getDbCommentId().equals(castOther.getDbCommentId())))
				&& ((this.getDbCommentDocumentId() == castOther
						.getDbCommentDocumentId()) || (this
						.getDbCommentDocumentId() != null
						&& castOther.getDbCommentDocumentId() != null && this
						.getDbCommentDocumentId().equals(
								castOther.getDbCommentDocumentId())))
				&& ((this.getDbCommentSeq() == castOther.getDbCommentSeq()) || (this
						.getDbCommentSeq() != null
						&& castOther.getDbCommentSeq() != null && this
						.getDbCommentSeq().equals(castOther.getDbCommentSeq())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getDbSiteCode() == null ? 0 : this.getDbSiteCode()
						.hashCode());
		result = 37
				* result
				+ (getDbModuleCode() == null ? 0 : this.getDbModuleCode()
						.hashCode());
		result = 37
				* result
				+ (getDbRecordId() == null ? 0 : this.getDbRecordId()
						.hashCode());
		result = 37
				* result
				+ (getDbCommentId() == null ? 0 : this.getDbCommentId()
						.hashCode());
		result = 37
				* result
				+ (getDbCommentDocumentId() == null ? 0 : this
						.getDbCommentDocumentId().hashCode());
		result = 37
				* result
				+ (getDbCommentSeq() == null ? 0 : this.getDbCommentSeq()
						.hashCode());
		return result;
	}

}
