package com.hkah.web.db.hibernate;
// Generated 2010年3月18日 下午03:36:11 by Hibernate Tools 3.2.0.b9

/**
 * DbCommentTypesId generated by hbm2java
 */
public class DbCommentTypesId implements java.io.Serializable {

	private String dbCommentTypeCode;
	private String dbModuleCode;

	public DbCommentTypesId() {
	}

	public DbCommentTypesId(String dbCommentTypeCode, String dbModuleCode) {
		this.dbCommentTypeCode = dbCommentTypeCode;
		this.dbModuleCode = dbModuleCode;
	}

	public String getDbCommentTypeCode() {
		return this.dbCommentTypeCode;
	}

	public void setDbCommentTypeCode(String dbCommentTypeCode) {
		this.dbCommentTypeCode = dbCommentTypeCode;
	}

	public String getDbModuleCode() {
		return this.dbModuleCode;
	}

	public void setDbModuleCode(String dbModuleCode) {
		this.dbModuleCode = dbModuleCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DbCommentTypesId))
			return false;
		DbCommentTypesId castOther = (DbCommentTypesId) other;

		return ((this.getDbCommentTypeCode() == castOther
				.getDbCommentTypeCode()) || (this.getDbCommentTypeCode() != null
				&& castOther.getDbCommentTypeCode() != null && this
				.getDbCommentTypeCode()
				.equals(castOther.getDbCommentTypeCode())))
				&& ((this.getDbModuleCode() == castOther.getDbModuleCode()) || (this
						.getDbModuleCode() != null
						&& castOther.getDbModuleCode() != null && this
						.getDbModuleCode().equals(castOther.getDbModuleCode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getDbCommentTypeCode() == null ? 0 : this
						.getDbCommentTypeCode().hashCode());
		result = 37
				* result
				+ (getDbModuleCode() == null ? 0 : this.getDbModuleCode()
						.hashCode());
		return result;
	}

}
