package com.hkah.web.db.hibernate;
// Generated 2010年3月19日 下午05:02:15 by Hibernate Tools 3.2.0.b9

import java.util.Date;

/**
 * DbCommentContactHistory generated by hbm2java
 */
public class DbCommentContactHistory implements java.io.Serializable {

	private DbCommentContactHistoryId id;
	private DbCommentHistory dbCommentHistory;
	private String dbContactType;
	private String dbContactUserType;
	private String dbContactUserId;
	private String dbContactEmail;
	private Date dbCreatedDate;
	private String dbCreatedUser;
	private Date dbModifiedDate;
	private String dbModifiedUser;
	private int dbEnabled;

	public DbCommentContactHistory() {
	}

	public DbCommentContactHistory(DbCommentContactHistoryId id,
			DbCommentHistory dbCommentHistory, String dbContactType,
			String dbContactUserType, String dbContactUserId) {
		this.id = id;
		this.dbCommentHistory = dbCommentHistory;
		this.dbContactType = dbContactType;
		this.dbContactUserType = dbContactUserType;
		this.dbContactUserId = dbContactUserId;
	}

	public DbCommentContactHistory(DbCommentContactHistoryId id,
			DbCommentHistory dbCommentHistory, String dbContactType,
			String dbContactUserType, String dbContactUserId,
			String dbContactEmail, Date dbCreatedDate, String dbCreatedUser,
			Date dbModifiedDate, String dbModifiedUser, int dbEnabled) {
		this.id = id;
		this.dbCommentHistory = dbCommentHistory;
		this.dbContactType = dbContactType;
		this.dbContactUserType = dbContactUserType;
		this.dbContactUserId = dbContactUserId;
		this.dbContactEmail = dbContactEmail;
		this.dbCreatedDate = dbCreatedDate;
		this.dbCreatedUser = dbCreatedUser;
		this.dbModifiedDate = dbModifiedDate;
		this.dbModifiedUser = dbModifiedUser;
		this.dbEnabled = dbEnabled;
	}

	public DbCommentContactHistoryId getId() {
		return this.id;
	}

	public void setId(DbCommentContactHistoryId id) {
		this.id = id;
	}

	public DbCommentHistory getDbCommentHistory() {
		return this.dbCommentHistory;
	}

	public void setDbCommentHistory(DbCommentHistory dbCommentHistory) {
		this.dbCommentHistory = dbCommentHistory;
	}

	public String getDbContactType() {
		return this.dbContactType;
	}

	public void setDbContactType(String dbContactType) {
		this.dbContactType = dbContactType;
	}

	public String getDbContactUserType() {
		return this.dbContactUserType;
	}

	public void setDbContactUserType(String dbContactUserType) {
		this.dbContactUserType = dbContactUserType;
	}

	public String getDbContactUserId() {
		return this.dbContactUserId;
	}

	public void setDbContactUserId(String dbContactUserId) {
		this.dbContactUserId = dbContactUserId;
	}

	public String getDbContactEmail() {
		return this.dbContactEmail;
	}

	public void setDbContactEmail(String dbContactEmail) {
		this.dbContactEmail = dbContactEmail;
	}

	public Date getDbCreatedDate() {
		return this.dbCreatedDate;
	}

	public void setDbCreatedDate(Date dbCreatedDate) {
		this.dbCreatedDate = dbCreatedDate;
	}

	public String getDbCreatedUser() {
		return this.dbCreatedUser;
	}

	public void setDbCreatedUser(String dbCreatedUser) {
		this.dbCreatedUser = dbCreatedUser;
	}

	public Date getDbModifiedDate() {
		return this.dbModifiedDate;
	}

	public void setDbModifiedDate(Date dbModifiedDate) {
		this.dbModifiedDate = dbModifiedDate;
	}

	public String getDbModifiedUser() {
		return this.dbModifiedUser;
	}

	public void setDbModifiedUser(String dbModifiedUser) {
		this.dbModifiedUser = dbModifiedUser;
	}

	public int getDbEnabled() {
		return this.dbEnabled;
	}

	public void setDbEnabled(int dbEnabled) {
		this.dbEnabled = dbEnabled;
	}

}
