package com.hkah.web.db.hibernate;
// Generated 2010年3月19日 下午05:02:15 by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;

/**
 * DbCommentContactHistoryId generated by hbm2java
 */
public class DbCommentContactHistoryId implements java.io.Serializable {

	private String dbSiteCode;
	private String dbModuleCode;
	private BigDecimal dbCommentId;
	private BigDecimal dbCommentHistoryId;
	private BigDecimal dbCommentContactHistoryId;
	private BigDecimal dbRecordId;

	public DbCommentContactHistoryId() {
	}

	public DbCommentContactHistoryId(String dbSiteCode, String dbModuleCode,
			BigDecimal dbCommentId, BigDecimal dbCommentHistoryId,
			BigDecimal dbCommentContactHistoryId, BigDecimal dbRecordId) {
		this.dbSiteCode = dbSiteCode;
		this.dbModuleCode = dbModuleCode;
		this.dbCommentId = dbCommentId;
		this.dbCommentHistoryId = dbCommentHistoryId;
		this.dbCommentContactHistoryId = dbCommentContactHistoryId;
		this.dbRecordId = dbRecordId;
	}

	public String getDbSiteCode() {
		return this.dbSiteCode;
	}

	public void setDbSiteCode(String dbSiteCode) {
		this.dbSiteCode = dbSiteCode;
	}

	public String getDbModuleCode() {
		return this.dbModuleCode;
	}

	public void setDbModuleCode(String dbModuleCode) {
		this.dbModuleCode = dbModuleCode;
	}

	public BigDecimal getDbCommentId() {
		return this.dbCommentId;
	}

	public void setDbCommentId(BigDecimal dbCommentId) {
		this.dbCommentId = dbCommentId;
	}

	public BigDecimal getDbCommentHistoryId() {
		return this.dbCommentHistoryId;
	}

	public void setDbCommentHistoryId(BigDecimal dbCommentHistoryId) {
		this.dbCommentHistoryId = dbCommentHistoryId;
	}

	public BigDecimal getDbCommentContactHistoryId() {
		return this.dbCommentContactHistoryId;
	}

	public void setDbCommentContactHistoryId(
			BigDecimal dbCommentContactHistoryId) {
		this.dbCommentContactHistoryId = dbCommentContactHistoryId;
	}

	public BigDecimal getDbRecordId() {
		return this.dbRecordId;
	}

	public void setDbRecordId(BigDecimal dbRecordId) {
		this.dbRecordId = dbRecordId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DbCommentContactHistoryId))
			return false;
		DbCommentContactHistoryId castOther = (DbCommentContactHistoryId) other;

		return ((this.getDbSiteCode() == castOther.getDbSiteCode()) || (this
				.getDbSiteCode() != null
				&& castOther.getDbSiteCode() != null && this.getDbSiteCode()
				.equals(castOther.getDbSiteCode())))
				&& ((this.getDbModuleCode() == castOther.getDbModuleCode()) || (this
						.getDbModuleCode() != null
						&& castOther.getDbModuleCode() != null && this
						.getDbModuleCode().equals(castOther.getDbModuleCode())))
				&& ((this.getDbCommentId() == castOther.getDbCommentId()) || (this
						.getDbCommentId() != null
						&& castOther.getDbCommentId() != null && this
						.getDbCommentId().equals(castOther.getDbCommentId())))
				&& ((this.getDbCommentHistoryId() == castOther
						.getDbCommentHistoryId()) || (this
						.getDbCommentHistoryId() != null
						&& castOther.getDbCommentHistoryId() != null && this
						.getDbCommentHistoryId().equals(
								castOther.getDbCommentHistoryId())))
				&& ((this.getDbCommentContactHistoryId() == castOther
						.getDbCommentContactHistoryId()) || (this
						.getDbCommentContactHistoryId() != null
						&& castOther.getDbCommentContactHistoryId() != null && this
						.getDbCommentContactHistoryId().equals(
								castOther.getDbCommentContactHistoryId())))
				&& ((this.getDbRecordId() == castOther.getDbRecordId()) || (this
						.getDbRecordId() != null
						&& castOther.getDbRecordId() != null && this
						.getDbRecordId().equals(castOther.getDbRecordId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getDbSiteCode() == null ? 0 : this.getDbSiteCode()
						.hashCode());
		result = 37
				* result
				+ (getDbModuleCode() == null ? 0 : this.getDbModuleCode()
						.hashCode());
		result = 37
				* result
				+ (getDbCommentId() == null ? 0 : this.getDbCommentId()
						.hashCode());
		result = 37
				* result
				+ (getDbCommentHistoryId() == null ? 0 : this
						.getDbCommentHistoryId().hashCode());
		result = 37
				* result
				+ (getDbCommentContactHistoryId() == null ? 0 : this
						.getDbCommentContactHistoryId().hashCode());
		result = 37
				* result
				+ (getDbRecordId() == null ? 0 : this.getDbRecordId()
						.hashCode());
		return result;
	}

}
