package com.hkah.web.db.hibernate;
// Generated 2010年3月18日 下午03:36:11 by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import java.util.Date;
import java.util.LinkedHashSet;
import java.util.Set;

import com.hkah.util.DateTimeUtil;

/**
 * DbComment generated by hbm2java
 */
public class DbComment implements java.io.Serializable {

	private DbCommentId id;
	private DbCommentTypes dbCommentTypes;
	private String dbTopicDesc;
	private String dbCommentDesc;
	private BigDecimal dbInvolveDepartmentCode;
	private String dbInvolveUserId;
	private String dbEmailNotify;
	private Date dbCreatedDate;
	private String dbCreatedUser;
	private Date dbModifiedDate;
	private String dbModifiedUser;
	private int dbEnabled;
	private Set<DbCommentHistory> dbCommentHistories = new LinkedHashSet<DbCommentHistory>();
	
	private String dbCommentTypes2;
	
	// formula fields
	private String involveDepartmentDesc;
	private String dbModifiedUserName;
	private String dbCreatedUserName;
	private int replies;
	private Date lastPostDate;

	public DbComment() {
	}

	public DbComment(DbCommentId id, DbCommentTypes dbCommentTypes,
			int dbEnabled) {
		this.id = id;
		this.dbCommentTypes = dbCommentTypes;
		this.dbEnabled = dbEnabled;
	}

	public DbComment(DbCommentId id, DbCommentTypes dbCommentTypes,
			String dbTopicDesc, String dbCommentDesc,
			BigDecimal dbInvolveDepartmentCode, String dbInvolveUserId,
			String dbEmailNotify, Date dbCreatedDate, String dbCreatedUser,
			Date dbModifiedDate, String dbModifiedUser, int dbEnabled,
			Set<DbCommentHistory> dbCommentHistories) {
		this.id = id;
		this.dbCommentTypes = dbCommentTypes;
		this.dbTopicDesc = dbTopicDesc;
		this.dbCommentDesc = dbCommentDesc;
		this.dbInvolveDepartmentCode = dbInvolveDepartmentCode;
		this.dbInvolveUserId = dbInvolveUserId;
		this.dbEmailNotify = dbEmailNotify;
		this.dbCreatedDate = dbCreatedDate;
		this.dbCreatedUser = dbCreatedUser;
		this.dbModifiedDate = dbModifiedDate;
		this.dbModifiedUser = dbModifiedUser;
		this.dbEnabled = dbEnabled;
		this.dbCommentHistories = dbCommentHistories;
	}

	public DbCommentId getId() {
		return this.id;
	}

	public void setId(DbCommentId id) {
		this.id = id;
	}

	public DbCommentTypes getDbCommentTypes() {
		return this.dbCommentTypes;
	}

	public void setDbCommentTypes(DbCommentTypes dbCommentTypes) {
		this.dbCommentTypes = dbCommentTypes;
	}

	public String getDbTopicDesc() {
		return this.dbTopicDesc;
	}

	public void setDbTopicDesc(String dbTopicDesc) {
		this.dbTopicDesc = dbTopicDesc;
	}

	public String getDbCommentDesc() {
		return this.dbCommentDesc;
	}

	public void setDbCommentDesc(String dbCommentDesc) {
		this.dbCommentDesc = dbCommentDesc;
	}

	public BigDecimal getDbInvolveDepartmentCode() {
		return this.dbInvolveDepartmentCode;
	}

	public void setDbInvolveDepartmentCode(BigDecimal dbInvolveDepartmentCode) {
		this.dbInvolveDepartmentCode = dbInvolveDepartmentCode;
	}

	public String getDbInvolveUserId() {
		return this.dbInvolveUserId;
	}

	public void setDbInvolveUserId(String dbInvolveUserId) {
		this.dbInvolveUserId = dbInvolveUserId;
	}

	public String getDbEmailNotify() {
		return this.dbEmailNotify;
	}

	public void setDbEmailNotify(String dbEmailNotify) {
		this.dbEmailNotify = dbEmailNotify;
	}

	public Date getDbCreatedDate() {
		return this.dbCreatedDate;
	}

	public void setDbCreatedDate(Date dbCreatedDate) {
		this.dbCreatedDate = dbCreatedDate;
	}

	public String getDbCreatedUser() {
		return this.dbCreatedUser;
	}

	public void setDbCreatedUser(String dbCreatedUser) {
		this.dbCreatedUser = dbCreatedUser;
	}

	public Date getDbModifiedDate() {
		return this.dbModifiedDate;
	}

	public void setDbModifiedDate(Date dbModifiedDate) {
		this.dbModifiedDate = dbModifiedDate;
	}

	public String getDbModifiedUser() {
		return this.dbModifiedUser;
	}

	public void setDbModifiedUser(String dbModifiedUser) {
		this.dbModifiedUser = dbModifiedUser;
	}

	public int getDbEnabled() {
		return this.dbEnabled;
	}

	public void setDbEnabled(int dbEnabled) {
		this.dbEnabled = dbEnabled;
	}

	public Set<DbCommentHistory> getDbCommentHistories() {
		return this.dbCommentHistories;
	}

	public void setDbCommentHistories(Set<DbCommentHistory> dbCommentHistories) {
		this.dbCommentHistories = dbCommentHistories;
	}

	/**
	 * @return the involveDepartmentDesc
	 */
	public String getInvolveDepartmentDesc() {
		return involveDepartmentDesc;
	}

	/**
	 * @param involveDepartmentDesc the involveDepartmentDesc to set
	 */
	public void setInvolveDepartmentDesc(String involveDepartmentDesc) {
		this.involveDepartmentDesc = involveDepartmentDesc;
	}
	
	/**
	 * @return the dbModifiedUserName
	 */
	public String getDbModifiedUserName() {
		return dbModifiedUserName;
	}
	
	/**
	 * @param dbModifiedUserName the dbModifiedUserName to set
	 */
	public void setDbModifiedUserName(String dbModifiedUserName) {
		this.dbModifiedUserName = dbModifiedUserName;
	}
	
	/**
	 * @return the dbCreatedUserName
	 */
	public String getDbCreatedUserName() {
		return dbCreatedUserName;
	}

	/**
	 * @param dbCreatedUserName the dbCreatedUserName to set
	 */
	public void setDbCreatedUserName(String dbCreatedUserName) {
		this.dbCreatedUserName = dbCreatedUserName;
	}

	/**
	 * @return the dbCommentTypes2
	 */
	public String getDbCommentTypes2() {
		return dbCommentTypes2;
	}

	/**
	 * @param dbCommentTypes2 the dbCommentTypes2 to set
	 */
	public void setDbCommentTypes2(String dbCommentTypes2) {
		this.dbCommentTypes2 = dbCommentTypes2;
	}
	
	// output getter
	public String getCreatedDateTimeString() {
		if (this.getDbCreatedDate() != null) {
			return DateTimeUtil.formatDateTimeWithoutSecond(this.getDbCreatedDate());
		} else {
			return "";
		}
	}
	
	public String getCreatedDateString() {
		if (this.getCreatedDateTimeString() != null &&
				this.getCreatedDateTimeString().length() >= 10) {
			return DateTimeUtil.date4Compare(this.getCreatedDateTimeString().substring(0, 10), true);
		} else {
			return "";
		}
	}
	
	public String getCreatedTimeString() {
		if (this.getCreatedDateTimeString() != null &&
				this.getCreatedDateTimeString().length() >= 11) {
			return this.getCreatedDateTimeString().substring(11);
		} else {
			return "";
		}
	}
	
	public String getModifiedDateTimeString() {
		if (this.getDbModifiedDate() != null) {
			return DateTimeUtil.formatDateTimeWithoutSecond(this.getDbModifiedDate());
		} else {
			return "";
		}
	}
	
	public String getModifiedDateString() {
		if (this.getModifiedDateTimeString() != null &&
				this.getModifiedDateTimeString().length() >= 10) {
			return DateTimeUtil.date4Compare(this.getModifiedDateTimeString().substring(0, 10), true);
		} else {
			return "";
		}
	}
	
	public String getModifiedTimeString() {
		if (this.getModifiedDateTimeString() != null &&
				this.getModifiedDateTimeString().length() >= 11) {
			return this.getModifiedDateTimeString().substring(11);
		} else {
			return "";
		}
	}

	/**
	 * @return the relies
	 */
	public int getReplies() {
		return replies;
	}

	/**
	 * @param relies the relies to set
	 */
	public void setReplies(int replies) {
		this.replies = replies;
	}

	/**
	 * @return the lastPostDate
	 */
	public Date getLastPostDate() {
		return lastPostDate;
	}

	/**
	 * @param lastPostDate the lastPostDate to set
	 */
	public void setLastPostDate(Date lastPostDate) {
		this.lastPostDate = lastPostDate;
	}
	
}
