package com.hkah.web.db.hibernate;

// Generated 2010年4月14日 上午08:52:02 by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * EeElearningQuestion generated by hbm2java
 */
public class EeElearningQuestion implements java.io.Serializable {

	private EeElearningQuestionId id;
	private String eeQuestion;
	private Date eeCreatedDate;
	private String eeCreatedUser;
	private Date eeModifiedDate;
	private String eeModifiedUser;
	private Integer eeEnabled;
	private Set<EeElearningAnswer> eeElearningAnswers = new HashSet<EeElearningAnswer>(0);

	public EeElearningQuestion() {
	}

	public EeElearningQuestion(EeElearningQuestionId id) {
		this.id = id;
	}

	public EeElearningQuestion(EeElearningQuestionId id, String eeQuestion,
			Date eeCreatedDate, String eeCreatedUser, Date eeModifiedDate,
			String eeModifiedUser, Integer eeEnabled, Set<EeElearningAnswer> eeElearningAnswers) {
		this.id = id;
		this.eeQuestion = eeQuestion;
		this.eeCreatedDate = eeCreatedDate;
		this.eeCreatedUser = eeCreatedUser;
		this.eeModifiedDate = eeModifiedDate;
		this.eeModifiedUser = eeModifiedUser;
		this.eeEnabled = eeEnabled;
		this.eeElearningAnswers = eeElearningAnswers;
	}

	public EeElearningQuestionId getId() {
		return this.id;
	}

	public void setId(EeElearningQuestionId id) {
		this.id = id;
	}

	public String getEeQuestion() {
		return this.eeQuestion;
	}

	public void setEeQuestion(String eeQuestion) {
		this.eeQuestion = eeQuestion;
	}

	public Date getEeCreatedDate() {
		return this.eeCreatedDate;
	}

	public void setEeCreatedDate(Date eeCreatedDate) {
		this.eeCreatedDate = eeCreatedDate;
	}

	public String getEeCreatedUser() {
		return this.eeCreatedUser;
	}

	public void setEeCreatedUser(String eeCreatedUser) {
		this.eeCreatedUser = eeCreatedUser;
	}

	public Date getEeModifiedDate() {
		return this.eeModifiedDate;
	}

	public void setEeModifiedDate(Date eeModifiedDate) {
		this.eeModifiedDate = eeModifiedDate;
	}

	public String getEeModifiedUser() {
		return this.eeModifiedUser;
	}

	public void setEeModifiedUser(String eeModifiedUser) {
		this.eeModifiedUser = eeModifiedUser;
	}

	public Integer getEeEnabled() {
		return this.eeEnabled;
	}

	public void setEeEnabled(Integer eeEnabled) {
		this.eeEnabled = eeEnabled;
	}

	public Set<EeElearningAnswer> getEeElearningAnswers() {
		return this.eeElearningAnswers;
	}

	public void setEeElearningAnswers(Set<EeElearningAnswer> eeElearningAnswers) {
		this.eeElearningAnswers = eeElearningAnswers;
	}

}
