package com.hkah.web.db.hibernate;

// Generated 2010年4月14日 上午08:52:02 by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;

/**
 * EeElearningQuestionId generated by hbm2java
 */
public class EeElearningQuestionId implements java.io.Serializable {

	private String eeSiteCode;
	private BigDecimal eeElearningId;
	private BigDecimal eeElearningQid;

	public EeElearningQuestionId() {
	}

	public EeElearningQuestionId(String eeSiteCode, BigDecimal eeElearningId,
			BigDecimal eeElearningQid) {
		this.eeSiteCode = eeSiteCode;
		this.eeElearningId = eeElearningId;
		this.eeElearningQid = eeElearningQid;
	}

	public String getEeSiteCode() {
		return this.eeSiteCode;
	}

	public void setEeSiteCode(String eeSiteCode) {
		this.eeSiteCode = eeSiteCode;
	}

	public BigDecimal getEeElearningId() {
		return this.eeElearningId;
	}

	public void setEeElearningId(BigDecimal eeElearningId) {
		this.eeElearningId = eeElearningId;
	}

	public BigDecimal getEeElearningQid() {
		return this.eeElearningQid;
	}

	public void setEeElearningQid(BigDecimal eeElearningQid) {
		this.eeElearningQid = eeElearningQid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EeElearningQuestionId))
			return false;
		EeElearningQuestionId castOther = (EeElearningQuestionId) other;

		return ((this.getEeSiteCode() == castOther.getEeSiteCode()) || (this
				.getEeSiteCode() != null
				&& castOther.getEeSiteCode() != null && this.getEeSiteCode()
				.equals(castOther.getEeSiteCode())))
				&& ((this.getEeElearningId() == castOther.getEeElearningId()) || (this
						.getEeElearningId() != null
						&& castOther.getEeElearningId() != null && this
						.getEeElearningId()
						.equals(castOther.getEeElearningId())))
				&& ((this.getEeElearningQid() == castOther.getEeElearningQid()) || (this
						.getEeElearningQid() != null
						&& castOther.getEeElearningQid() != null && this
						.getEeElearningQid().equals(
								castOther.getEeElearningQid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getEeSiteCode() == null ? 0 : this.getEeSiteCode()
						.hashCode());
		result = 37
				* result
				+ (getEeElearningId() == null ? 0 : this.getEeElearningId()
						.hashCode());
		result = 37
				* result
				+ (getEeElearningQid() == null ? 0 : this.getEeElearningQid()
						.hashCode());
		return result;
	}

}
