package com.hkah.web.db.hibernate;

// Generated 2010年4月14日 上午08:52:02 by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;

/**
 * EeElearningStaffAnswerId generated by hbm2java
 */
public class EeElearningStaffAnswerId implements java.io.Serializable {

	private String eeSiteCode;
	private String eeModuleCode;
	private BigDecimal eeEventId;
	private BigDecimal eeEnrollId;
	private BigDecimal eeElearningId;
	private BigDecimal eeElearningQid;
	private BigDecimal eeElearningAid;
	private String eeUserType;
	private String eeUserId;

	public EeElearningStaffAnswerId() {
	}

	public EeElearningStaffAnswerId(String eeSiteCode, String eeModuleCode,
			BigDecimal eeEventId, BigDecimal eeEnrollId,
			BigDecimal eeElearningId, BigDecimal eeElearningQid,
			BigDecimal eeElearningAid, String eeUserType, String eeUserId) {
		this.eeSiteCode = eeSiteCode;
		this.eeModuleCode = eeModuleCode;
		this.eeEventId = eeEventId;
		this.eeEnrollId = eeEnrollId;
		this.eeElearningId = eeElearningId;
		this.eeElearningQid = eeElearningQid;
		this.eeElearningAid = eeElearningAid;
		this.eeUserType = eeUserType;
		this.eeUserId = eeUserId;
	}

	public String getEeSiteCode() {
		return this.eeSiteCode;
	}

	public void setEeSiteCode(String eeSiteCode) {
		this.eeSiteCode = eeSiteCode;
	}

	public String getEeModuleCode() {
		return this.eeModuleCode;
	}

	public void setEeModuleCode(String eeModuleCode) {
		this.eeModuleCode = eeModuleCode;
	}

	public BigDecimal getEeEventId() {
		return this.eeEventId;
	}

	public void setEeEventId(BigDecimal eeEventId) {
		this.eeEventId = eeEventId;
	}

	public BigDecimal getEeEnrollId() {
		return this.eeEnrollId;
	}

	public void setEeEnrollId(BigDecimal eeEnrollId) {
		this.eeEnrollId = eeEnrollId;
	}

	public BigDecimal getEeElearningId() {
		return this.eeElearningId;
	}

	public void setEeElearningId(BigDecimal eeElearningId) {
		this.eeElearningId = eeElearningId;
	}

	public BigDecimal getEeElearningQid() {
		return this.eeElearningQid;
	}

	public void setEeElearningQid(BigDecimal eeElearningQid) {
		this.eeElearningQid = eeElearningQid;
	}

	public BigDecimal getEeElearningAid() {
		return this.eeElearningAid;
	}

	public void setEeElearningAid(BigDecimal eeElearningAid) {
		this.eeElearningAid = eeElearningAid;
	}

	public String getEeUserType() {
		return this.eeUserType;
	}

	public void setEeUserType(String eeUserType) {
		this.eeUserType = eeUserType;
	}

	public String getEeUserId() {
		return this.eeUserId;
	}

	public void setEeUserId(String eeUserId) {
		this.eeUserId = eeUserId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EeElearningStaffAnswerId))
			return false;
		EeElearningStaffAnswerId castOther = (EeElearningStaffAnswerId) other;

		return ((this.getEeSiteCode() == castOther.getEeSiteCode()) || (this
				.getEeSiteCode() != null
				&& castOther.getEeSiteCode() != null && this.getEeSiteCode()
				.equals(castOther.getEeSiteCode())))
				&& ((this.getEeModuleCode() == castOther.getEeModuleCode()) || (this
						.getEeModuleCode() != null
						&& castOther.getEeModuleCode() != null && this
						.getEeModuleCode().equals(castOther.getEeModuleCode())))
				&& ((this.getEeEventId() == castOther.getEeEventId()) || (this
						.getEeEventId() != null
						&& castOther.getEeEventId() != null && this
						.getEeEventId().equals(castOther.getEeEventId())))
				&& ((this.getEeEnrollId() == castOther.getEeEnrollId()) || (this
						.getEeEnrollId() != null
						&& castOther.getEeEnrollId() != null && this
						.getEeEnrollId().equals(castOther.getEeEnrollId())))
				&& ((this.getEeElearningId() == castOther.getEeElearningId()) || (this
						.getEeElearningId() != null
						&& castOther.getEeElearningId() != null && this
						.getEeElearningId()
						.equals(castOther.getEeElearningId())))
				&& ((this.getEeElearningQid() == castOther.getEeElearningQid()) || (this
						.getEeElearningQid() != null
						&& castOther.getEeElearningQid() != null && this
						.getEeElearningQid().equals(
								castOther.getEeElearningQid())))
				&& ((this.getEeElearningAid() == castOther.getEeElearningAid()) || (this
						.getEeElearningAid() != null
						&& castOther.getEeElearningAid() != null && this
						.getEeElearningAid().equals(
								castOther.getEeElearningAid())))
				&& ((this.getEeUserType() == castOther.getEeUserType()) || (this
						.getEeUserType() != null
						&& castOther.getEeUserType() != null && this
						.getEeUserType().equals(castOther.getEeUserType())))
				&& ((this.getEeUserId() == castOther.getEeUserId()) || (this
						.getEeUserId() != null
						&& castOther.getEeUserId() != null && this
						.getEeUserId().equals(castOther.getEeUserId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getEeSiteCode() == null ? 0 : this.getEeSiteCode()
						.hashCode());
		result = 37
				* result
				+ (getEeModuleCode() == null ? 0 : this.getEeModuleCode()
						.hashCode());
		result = 37 * result
				+ (getEeEventId() == null ? 0 : this.getEeEventId().hashCode());
		result = 37
				* result
				+ (getEeEnrollId() == null ? 0 : this.getEeEnrollId()
						.hashCode());
		result = 37
				* result
				+ (getEeElearningId() == null ? 0 : this.getEeElearningId()
						.hashCode());
		result = 37
				* result
				+ (getEeElearningQid() == null ? 0 : this.getEeElearningQid()
						.hashCode());
		result = 37
				* result
				+ (getEeElearningAid() == null ? 0 : this.getEeElearningAid()
						.hashCode());
		result = 37
				* result
				+ (getEeUserType() == null ? 0 : this.getEeUserType()
						.hashCode());
		result = 37 * result
				+ (getEeUserId() == null ? 0 : this.getEeUserId().hashCode());
		return result;
	}

}
