package com.hkah.web.db.hibernate;

// Generated 2010年4月14日 上午08:52:02 by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import java.util.Date;

/**
 * EeElearningStaffAnswer generated by hbm2java
 */
public class EeElearningStaffAnswer implements java.io.Serializable {

	private EeElearningStaffAnswerId id;
	private BigDecimal eeCorrectAns;
	private Date eeCreatedDate;
	private String eeCreatedUser;
	private Date eeModifiedDate;
	private String eeModifiedUser;
	private BigDecimal eeEnabled;

	public EeElearningStaffAnswer() {
	}

	public EeElearningStaffAnswer(EeElearningStaffAnswerId id) {
		this.id = id;
	}

	public EeElearningStaffAnswer(EeElearningStaffAnswerId id,
			BigDecimal eeCorrectAns, Date eeCreatedDate, String eeCreatedUser,
			Date eeModifiedDate, String eeModifiedUser, BigDecimal eeEnabled) {
		this.id = id;
		this.eeCorrectAns = eeCorrectAns;
		this.eeCreatedDate = eeCreatedDate;
		this.eeCreatedUser = eeCreatedUser;
		this.eeModifiedDate = eeModifiedDate;
		this.eeModifiedUser = eeModifiedUser;
		this.eeEnabled = eeEnabled;
	}

	public EeElearningStaffAnswerId getId() {
		return this.id;
	}

	public void setId(EeElearningStaffAnswerId id) {
		this.id = id;
	}

	public BigDecimal getEeCorrectAns() {
		return this.eeCorrectAns;
	}

	public void setEeCorrectAns(BigDecimal eeCorrectAns) {
		this.eeCorrectAns = eeCorrectAns;
	}

	public Date getEeCreatedDate() {
		return this.eeCreatedDate;
	}

	public void setEeCreatedDate(Date eeCreatedDate) {
		this.eeCreatedDate = eeCreatedDate;
	}

	public String getEeCreatedUser() {
		return this.eeCreatedUser;
	}

	public void setEeCreatedUser(String eeCreatedUser) {
		this.eeCreatedUser = eeCreatedUser;
	}

	public Date getEeModifiedDate() {
		return this.eeModifiedDate;
	}

	public void setEeModifiedDate(Date eeModifiedDate) {
		this.eeModifiedDate = eeModifiedDate;
	}

	public String getEeModifiedUser() {
		return this.eeModifiedUser;
	}

	public void setEeModifiedUser(String eeModifiedUser) {
		this.eeModifiedUser = eeModifiedUser;
	}

	public BigDecimal getEeEnabled() {
		return this.eeEnabled;
	}

	public void setEeEnabled(BigDecimal eeEnabled) {
		this.eeEnabled = eeEnabled;
	}

}
