package com.hkah.web.db.hibernate;

// Generated 2010年4月14日 上午09:59:06 by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * EeMenuModule generated by hbm2java
 */
public class EeMenuModule implements java.io.Serializable {

	private EeMenuModuleId id;
	private String eeDescriptionEn;
	private String eeDescriptionZh;
	private String eeParentModuleCode;
	private BigDecimal eeSortOrder;
	private Date eeRevisedDate;
	private Date eeCreatedDate;
	private String eeCreatedUser;
	private Date eeModifiedDate;
	private String eeModifiedUser;
	private Integer eeEnabled;
	private String eeBgColor;
	private String eeUrl;
	
	// child EeMenuModule
	private List<EeMenuModule> childEeMenuModuleList = new ArrayList<EeMenuModule>();

	public EeMenuModule() {
	}

	public EeMenuModule(EeMenuModuleId id) {
		this.id = id;
	}

	public EeMenuModule(EeMenuModuleId id, String eeDescriptionEn,
			String eeDescriptionZh, String eeParentModuleCode,
			BigDecimal eeSortOrder, Date eeRevisedDate, Date eeCreatedDate,
			String eeCreatedUser, Date eeModifiedDate, String eeModifiedUser,
			Integer eeEnabled, String eeBgColor, String eeUrl) {
		this.id = id;
		this.eeDescriptionEn = eeDescriptionEn;
		this.eeDescriptionZh = eeDescriptionZh;
		this.eeParentModuleCode = eeParentModuleCode;
		this.eeSortOrder = eeSortOrder;
		this.eeRevisedDate = eeRevisedDate;
		this.eeCreatedDate = eeCreatedDate;
		this.eeCreatedUser = eeCreatedUser;
		this.eeModifiedDate = eeModifiedDate;
		this.eeModifiedUser = eeModifiedUser;
		this.eeEnabled = eeEnabled;
		this.eeBgColor = eeBgColor;
		this.eeUrl = eeUrl;
	}

	public EeMenuModuleId getId() {
		return this.id;
	}

	public void setId(EeMenuModuleId id) {
		this.id = id;
	}

	public String getEeDescriptionEn() {
		return this.eeDescriptionEn;
	}

	public void setEeDescriptionEn(String eeDescriptionEn) {
		this.eeDescriptionEn = eeDescriptionEn;
	}

	public String getEeDescriptionZh() {
		return this.eeDescriptionZh;
	}

	public void setEeDescriptionZh(String eeDescriptionZh) {
		this.eeDescriptionZh = eeDescriptionZh;
	}

	public String getEeParentModuleCode() {
		return this.eeParentModuleCode;
	}

	public void setEeParentModuleCode(String eeParentModuleCode) {
		this.eeParentModuleCode = eeParentModuleCode;
	}

	public BigDecimal getEeSortOrder() {
		return this.eeSortOrder;
	}

	public void setEeSortOrder(BigDecimal eeSortOrder) {
		this.eeSortOrder = eeSortOrder;
	}

	public Date getEeRevisedDate() {
		return this.eeRevisedDate;
	}

	public void setEeRevisedDate(Date eeRevisedDate) {
		this.eeRevisedDate = eeRevisedDate;
	}

	public Date getEeCreatedDate() {
		return this.eeCreatedDate;
	}

	public void setEeCreatedDate(Date eeCreatedDate) {
		this.eeCreatedDate = eeCreatedDate;
	}

	public String getEeCreatedUser() {
		return this.eeCreatedUser;
	}

	public void setEeCreatedUser(String eeCreatedUser) {
		this.eeCreatedUser = eeCreatedUser;
	}

	public Date getEeModifiedDate() {
		return this.eeModifiedDate;
	}

	public void setEeModifiedDate(Date eeModifiedDate) {
		this.eeModifiedDate = eeModifiedDate;
	}

	public String getEeModifiedUser() {
		return this.eeModifiedUser;
	}

	public void setEeModifiedUser(String eeModifiedUser) {
		this.eeModifiedUser = eeModifiedUser;
	}

	public Integer getEeEnabled() {
		return this.eeEnabled;
	}

	public void setEeEnabled(Integer eeEnabled) {
		this.eeEnabled = eeEnabled;
	}

	public String getEeBgColor() {
		return this.eeBgColor;
	}

	public void setEeBgColor(String eeBgColor) {
		this.eeBgColor = eeBgColor;
	}
	
	public String getEeUrl() {
		return this.eeUrl;
	}

	public void setEeUrl(String eeUrl) {
		this.eeUrl = eeUrl;
	}
	
	/**
	 * @return the childEeMenuModuleList
	 */
	public List<EeMenuModule> getChildEeMenuModuleList() {
		return childEeMenuModuleList;
	}

	/**
	 * @param childEeMenuModuleList the childEeMenuModuleList to set
	 */
	public void setChildEeMenuModuleList(List<EeMenuModule> childEeMenuModuleList) {
		this.childEeMenuModuleList = childEeMenuModuleList;
	}

	// formatted output
	public String getBgColorStyle() {
		String style = " background-color: #RGB_HEX;";
		if (this.getEeBgColor() != null) {
			style = style.replace("RGB_HEX", this.getEeBgColor());
		} else {
			style = "";
		}
		
		return style;
	}
	
	public String getFormattedEeRevisedDate() {
		String moduleRevisedDateStr = null;
		if (this.getEeRevisedDate() != null) {
			moduleRevisedDateStr = (new SimpleDateFormat("yyyy-MM-dd")).format(this.getEeRevisedDate());
		} 
		return moduleRevisedDateStr;
	}
}
