package com.hkah.web.db.hibernate;

// Generated 2010年4月14日 上午09:34:43 by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import java.util.Date;

/**
 * EeMenuDocument generated by hbm2java
 */
public class EeMenuDocument implements java.io.Serializable {

	private EeMenuDocumentId id;
	private EeMenuContent eeMenuContent;
	private String eeModuleCode;
	private BigDecimal eeDocumentId;
	private String eeUrl;
	private String eeIsUrl;
	private Date eeCreatedDate;
	private String eeCreatedUser;
	private Date eeModifiedDate;
	private String eeModifiedUser;
	private Integer eeEnabled;
	
	// output
	private String documentUrl;
	private String documentDesc;

	public EeMenuDocument() {
	}

	public EeMenuDocument(EeMenuDocumentId id, EeMenuContent eeMenuContent) {
		this.id = id;
		this.eeMenuContent = eeMenuContent;
	}

	public EeMenuDocument(EeMenuDocumentId id, EeMenuContent eeMenuContent,
			String eeModuleCode, BigDecimal eeDocumentId, Date eeCreatedDate,
			String eeCreatedUser, Date eeModifiedDate, String eeModifiedUser,
			Integer eeEnabled, String eeUrl, String eeIsUrl) {
		this.id = id;
		this.eeMenuContent = eeMenuContent;
		this.eeModuleCode = eeModuleCode;
		this.eeDocumentId = eeDocumentId;
		this.eeCreatedDate = eeCreatedDate;
		this.eeCreatedUser = eeCreatedUser;
		this.eeModifiedDate = eeModifiedDate;
		this.eeModifiedUser = eeModifiedUser;
		this.eeEnabled = eeEnabled;
		this.eeUrl = eeUrl;
		this.eeIsUrl = eeIsUrl;
	}

	public EeMenuDocumentId getId() {
		return this.id;
	}

	public void setId(EeMenuDocumentId id) {
		this.id = id;
	}

	public EeMenuContent getEeMenuContent() {
		return this.eeMenuContent;
	}

	public void setEeMenuContent(EeMenuContent eeMenuContent) {
		this.eeMenuContent = eeMenuContent;
	}

	public String getEeModuleCode() {
		return this.eeModuleCode;
	}

	public void setEeModuleCode(String eeModuleCode) {
		this.eeModuleCode = eeModuleCode;
	}

	public BigDecimal getEeDocumentId() {
		return this.eeDocumentId;
	}

	public void setEeDocumentId(BigDecimal eeDocumentId) {
		this.eeDocumentId = eeDocumentId;
	}
	
	public String getEeUrl() {
		return this.eeUrl;
	}

	public void setEeUrl(String eeUrl) {
		this.eeUrl = eeUrl;
	}
	
	public String getEeIsUrl() {
		return this.eeIsUrl;
	}

	public void setEeIsUrl(String eeIsUrl) {
		this.eeIsUrl = eeIsUrl;
	}

	public Date getEeCreatedDate() {
		return this.eeCreatedDate;
	}

	public void setEeCreatedDate(Date eeCreatedDate) {
		this.eeCreatedDate = eeCreatedDate;
	}

	public String getEeCreatedUser() {
		return this.eeCreatedUser;
	}

	public void setEeCreatedUser(String eeCreatedUser) {
		this.eeCreatedUser = eeCreatedUser;
	}

	public Date getEeModifiedDate() {
		return this.eeModifiedDate;
	}

	public void setEeModifiedDate(Date eeModifiedDate) {
		this.eeModifiedDate = eeModifiedDate;
	}

	public String getEeModifiedUser() {
		return this.eeModifiedUser;
	}

	public void setEeModifiedUser(String eeModifiedUser) {
		this.eeModifiedUser = eeModifiedUser;
	}

	public Integer getEeEnabled() {
		return this.eeEnabled;
	}

	public void setEeEnabled(Integer eeEnabled) {
		this.eeEnabled = eeEnabled;
	}

	/**
	 * @return the documentUrl
	 */
	public String getDocumentUrl() {
		return documentUrl;
	}

	/**
	 * @param documentUrl the documentUrl to set
	 */
	public void setDocumentUrl(String documentUrl) {
		this.documentUrl = documentUrl;
	}

	/**
	 * @return the documentDesc
	 */
	public String getDocumentDesc() {
		return documentDesc;
	}

	/**
	 * @param documentDesc the documentDesc to set
	 */
	public void setDocumentDesc(String documentDesc) {
		this.documentDesc = documentDesc;
	}

	public boolean isDocumentUrlFilePath() {
		if (this.getDocumentUrl() != null && this.getDocumentUrl().startsWith("\\\\")) {
			return true;
		} else {
			return false;
		}
	}
}
