package com.hkah.web.db.hibernate;
// default package
// Generated 2010年3月10日 下午03:56:14 by Hibernate Tools 3.2.0.b9

/**
 * HaaChecklistDateId generated by hbm2java
 */
public class HaaChecklistDateId implements java.io.Serializable {

	private int haaChecklistId;
	private int haaChecklistDid;

	public HaaChecklistDateId() {
	}

	public HaaChecklistDateId(int haaChecklistId,
			int haaChecklistDid) {
		this.haaChecklistId = haaChecklistId;
		this.haaChecklistDid = haaChecklistDid;
	}

	public int getHaaChecklistId() {
		return this.haaChecklistId;
	}

	public void setHaaChecklistId(int haaChecklistId) {
		this.haaChecklistId = haaChecklistId;
	}

	public int getHaaChecklistDid() {
		return this.haaChecklistDid;
	}

	public void setHaaChecklistDid(int haaChecklistDid) {
		this.haaChecklistDid = haaChecklistDid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HaaChecklistDateId))
			return false;
		HaaChecklistDateId castOther = (HaaChecklistDateId) other;

		return ((this.getHaaChecklistId() == castOther.getHaaChecklistId()))
				&& ((this.getHaaChecklistDid() == castOther
						.getHaaChecklistDid()));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ this.getHaaChecklistId();
		result = 37
				* result
				+ this.getHaaChecklistDid();
		return result;
	}

}
