package com.hkah.web.db.hibernate;
// default package
// Generated 2010年3月10日 下午03:56:14 by Hibernate Tools 3.2.0.b9

import java.util.Date;

/**
 * HaaChecklistProgress generated by hbm2java
 */
public class HaaChecklistProgress implements java.io.Serializable {

	private int haaChecklistPid;
	private String haaProgress;
	private int haaIndent;
	private String haaDept;
	private String haaInitParty;
	private String haaRspn;
	private Date haaModifiedDate;
	private String haaModifiedUser;
	private int haaEnabled;

	public HaaChecklistProgress() {
	}

	public HaaChecklistProgress(int haaChecklistPid) {
		this.haaChecklistPid = haaChecklistPid;
	}

	public HaaChecklistProgress(int haaChecklistPid, String haaProgress,
			int haaIndent, String haaDept, String haaInitParty,
			String haaRspn, Date haaModifiedDate, String haaModifiedUser,
			int haaEnabled) {
		this.haaChecklistPid = haaChecklistPid;
		this.haaProgress = haaProgress;
		this.haaIndent = haaIndent;
		this.haaDept = haaDept;
		this.haaInitParty = haaInitParty;
		this.haaRspn = haaRspn;
		this.haaModifiedDate = haaModifiedDate;
		this.haaModifiedUser = haaModifiedUser;
		this.haaEnabled = haaEnabled;
	}

	public int getHaaChecklistPid() {
		return this.haaChecklistPid;
	}

	public void setHaaChecklistPid(int haaChecklistPid) {
		this.haaChecklistPid = haaChecklistPid;
	}

	public String getHaaProgress() {
		return this.haaProgress;
	}

	public void setHaaProgress(String haaProgress) {
		this.haaProgress = haaProgress;
	}

	public int getHaaIndent() {
		return this.haaIndent;
	}

	public void setHaaIndent(int haaIndent) {
		this.haaIndent = haaIndent;
	}

	public String getHaaDept() {
		return this.haaDept;
	}

	public void setHaaDept(String haaDept) {
		this.haaDept = haaDept;
	}

	public String getHaaInitParty() {
		return this.haaInitParty;
	}

	public void setHaaInitParty(String haaInitParty) {
		this.haaInitParty = haaInitParty;
	}

	public String getHaaRspn() {
		return this.haaRspn;
	}

	public void setHaaRspn(String haaRspn) {
		this.haaRspn = haaRspn;
	}

	public Date getHaaModifiedDate() {
		return this.haaModifiedDate;
	}

	public void setHaaModifiedDate(Date haaModifiedDate) {
		this.haaModifiedDate = haaModifiedDate;
	}

	public String getHaaModifiedUser() {
		return this.haaModifiedUser;
	}

	public void setHaaModifiedUser(String haaModifiedUser) {
		this.haaModifiedUser = haaModifiedUser;
	}

	public int getHaaEnabled() {
		return this.haaEnabled;
	}

	public void setHaaEnabled(int haaEnabled) {
		this.haaEnabled = haaEnabled;
	}

}
