create or replace FUNCTION NHS_LIS_ECGREPORTEDITOR (
	v_ACTION IN VARCHAR2,
    v_XRGID IN VARCHAR2
)
	RETURN Types.cursor_type

AS
	OUTCUR types.cursor_type;
	SQLSTR VARCHAR2(32767);
	S_FROM VARCHAR2(500);
    S_WHERE VARCHAR2(500);
BEGIN

/*
LATEIST RECORD:
SELECT  TO_CHAR(HIST.XRPDATE, 'DD/MM/YYYY HH24:MM:SS') AS XRPDATE, HIST.DOCCODE, HIST.XRPTITLE, HIST.USRID_P, HIST.USRID_T, 
        HIST.XRPTSTS, HIST.APPROVEBY, HIST.XRPCOMBINE, TO_CHAR(HIST.APPROVEDATE, 'DD/MM/YYYY HH24:MM:SS') AS APPROVEDATE,
        HIST.XRPID, HIST.VERNO, XRPCONTENT
FROM XREPORTHIST HIST, XREPORT RPT
WHERE HIST.XRPID = RPT.XRPIDHIST
AND HIST.XRGID = '381040';

VIEW HISTORY:
SELECT  TO_CHAR(HIST.XRPDATE, 'DD/MM/YYYY HH24:MM:SS') AS XRPDATE, HIST.DOCCODE, HIST.XRPTITLE, HIST.USRID_P, HIST.USRID_T, 
        HIST.XRPTSTS, HIST.APPROVEBY, HIST.XRPCOMBINE, TO_CHAR(HIST.APPROVEDATE, 'DD/MM/YYYY HH24:MM:SS') AS APPROVEDATE,
        HIST.XRPID, HIST.VERNO, XRPCONTENT
FROM XREPORTHIST HIST
WHERE HIST.XRGID = '381040'
ORDER BY HIST.VERNO DESC;
*/
IF v_ACTION = 'INFO' THEN
	S_FROM := ' FROM XREPORTHIST HIST, XREPORT RPT 
                WHERE HIST.XRPID = RPT.XRPIDHIST ';
ELSIF v_ACTION = 'HIST' THEN
	S_FROM := ' FROM XREPORTHIST HIST 
                WHERE 1=1 ';
END IF;

	SQLSTR := '	SELECT  TO_CHAR(HIST.XRPDATE, ''DD/MM/YYYY HH24:MM:SS'') AS XRPDATE, HIST.DOCCODE, HIST.XRPTITLE, HIST.USRID_P, HIST.USRID_T, 
                HIST.XRPTSTS, HIST.APPROVEBY, HIST.XRPCOMBINE, TO_CHAR(HIST.APPROVEDATE, ''DD/MM/YYYY HH24:MM:SS'') AS APPROVEDATE,
                HIST.XRPID, HIST.VERNO, XRPCONTENT';
	S_WHERE := 'AND HIST.XRGID = ''' || v_XRGID || ''' 
				ORDER BY HIST.VERNO DESC ' ;
	SQLSTR := SQLSTR || S_FROM || S_WHERE ;


OPEN OUTCUR FOR SQLSTR;
RETURN OUTCUR;

--RETURN SQLSTR;
END NHS_LIS_ECGREPORTEDITOR;