create or replace FUNCTION "NHS_ACT_DIREPORTAPPROVE" (
	v_action   IN VARCHAR2,
	v_XRGID  IN VARCHAR2,
	v_XRPID IN VARCHAR2,
    v_DOCCODE IN VARCHAR2,
	v_SIGNUSER IN VARCHAR2,-- input user
	v_USRID IN VARCHAR2, -- LOGIN USER
	o_errmsg   OUT VARCHAR2
)
	RETURN NUMBER
AS
	o_errcode NUMBER;
	
	SQLSTR VARCHAR2(32767);

	v_XRPPRNCNT XREPORTHIST.XRPPRNCNT%TYPE;
	v_XRPCOMBINE XREPORTHIST.XRPCOMBINE%TYPE;
	v_APPROVEDATE XREPORTHIST.APPROVEDATE%TYPE;
	v_APPROVEBY XREPORTHIST.APPROVEBY%TYPE;
	v_XRPTSTS XREPORTHIST.XRPTSTS%TYPE;
    
    l_XRPID XREPORTHIST.XRPID%TYPE;
    old_DOCCODE XREPORTHIST.DOCCODE%TYPE;
	v_STNID SLIPTX.STNID%TYPE;
	v_SLPNO SLIPTX.SLPNO%TYPE;
	v_STNDIDOC SLIPTX.STNDIDOC%TYPE;
	v_STNSTS SLIPTX.STNSTS%TYPE;
	new_STNID SLIPTX.SLPNO%TYPE;
	v_STNSEQ1 SLIPTX.STNSEQ%TYPE;
	v_STNSEQ2 SLIPTX.STNSEQ%TYPE;

BEGIN
	o_errcode := 0;
	o_errmsg := 'OK';
    -- if more than one xrgid have the same report update, then use xrpcombine.
	
	IF v_action = 'ADD' THEN
	
        SELECT DOCCODE INTO old_DOCCODE 
		FROM XREPORT 
		WHERE XRGID = v_XRGID;
	
		IF old_DOCCODE IS NOT NULL AND old_DOCCODE != v_DOCCODE THEN
			-- START ReverseSlipTxChangeDr
			SELECT TX.STNID, TX.SLPNO, TX.STNDIDOC, TX.STNSTS 
			INTO v_STNID, v_SLPNO, v_STNDIDOC, v_STNSTS
			FROM SLIPTX TX, XREG R
			WHERE TX.DIXREF = R.STNID 
			AND TX.STNSTS IN ('A','N')
			AND R.XRGID = v_XRGID;
			
			IF v_SLPNO IS NOT NULL AND v_STNDIDOC IS NOT NULL THEN 
				-- change Status
				UPDATE SLIPTX
				SET 
				STNSTS = 'C' 
				WHERE STNID = v_STNID;
				-- Add two record STNSTS='A/N' & STNSTS='R'
				v_STNSEQ1 := NHS_UTL_IncrementSlipSeq(v_SLPNO);
				IF v_STNSEQ1 < 0 THEN
					RETURN v_STNSEQ1;
				END IF;
				SELECT SEQ_SLIPTX.NEXTVAL INTO new_STNID FROM DUAL;	
				-- 1 STNSTS='A/N'
				IF v_STNSTS='A' OR v_STNSTS='N' THEN
					INSERT INTO SLIPTX 
					SELECT 
					new_STNID AS STNID, SLPNO, v_STNSEQ1 AS STNSEQ, v_STNSTS AS STNSTS, PKGCODE, --1,2,3,4,5
					ITMCODE, ITMTYPE, STNDISC, STNOAMT,	STNBAMT, --6,7,8,9,10
					STNNAMT, DOCCODE, ACMCODE, GLCCODE, USRID, --11,12,13,14,15
					STNTDATE, STNCDATE, STNADOC, STNDESC, STNRLVL, --16,17,18,19,20
					STNTYPE, STNXREF, DSCCODE, DIXREF, NULL AS STNDIDOC, --21,22,23,24,25
					STNDIFLAG, STNCPSFLAG, PCYID, STNASCM, UNIT, --26,27,28,29,30
					PCYID_O, TRANSVER, STNDESC1, CARDRATE, PAYMETHOD, --31,32,33,34,35
					IREFNO --36
					FROM SLIPTX 
					WHERE STNID = v_STNID;
				END IF;
				
				-- 2 STNSTS='R'
				v_STNSEQ2 := NHS_UTL_IncrementSlipSeq(v_SLPNO);
				IF v_STNSEQ2 < 0 THEN
					RETURN v_STNSEQ2;
				END IF;
				SELECT SEQ_SLIPTX.NEXTVAL INTO new_STNID FROM DUAL;	
				
				INSERT INTO SLIPTX 
				SELECT 
				new_STNID AS STNID, SLPNO, v_STNSEQ2 AS STNSEQ, 'R' AS STNSTS, PKGCODE, --1,2,3,4,5
				ITMCODE, ITMTYPE, STNDISC, STNOAMT,	STNBAMT, --6,7,8,9,10
				STNNAMT, DOCCODE, ACMCODE, GLCCODE, USRID, --11,12,13,14,15
				STNTDATE, STNCDATE, STNADOC, STNDESC, STNRLVL, --16,17,18,19,20
				STNTYPE, STNXREF, DSCCODE, DIXREF, NULL AS STNDIDOC, --21,22,23,24,25
				STNDIFLAG, STNCPSFLAG, PCYID, STNASCM, UNIT, --26,27,28,29,30
				PCYID_O, TRANSVER, STNDESC1, CARDRATE, PAYMETHOD, --31,32,33,34,35
				IREFNO --36
				FROM SLIPTX 
				WHERE STNID = v_STNID;
				
			END IF;
			-- END ReverseSlipTxChangeDr
            
		END IF;
		-- approveUpdate(vSignUser, xrpcombine)
        
		UPDATE XREPORTHIST 
		SET 
		APPROVEDATE = SYSDATE,
		XRPTSTS = 'A',
		APPROVEBY = v_SIGNUSER,
		SIGNUSR = v_SIGNUSER
		WHERE XRPID = v_XRPID;
		
		UPDATE XREPORT 
		SET 
		APPROVEDATE = SYSDATE
		WHERE XRPID = v_XRPID;
		
		--UpdateXRegSQL(rs.Fields("xrgid"), , REPORT_STATUS_COMPLETE = 0)
		UPDATE XREG
		SET
		XRGRPTFLAG = 0
		WHERE XRGID = v_XRGID;
		
	END IF;

	RETURN o_errcode;
END NHS_ACT_DIREPORTAPPROVE;