create or replace FUNCTION NHS_LIS_ECGEXAMREPORT (
	patNo IN VARCHAR2,
    diNo IN VARCHAR2
)
	RETURN Types.cursor_type

AS
	OUTCUR types.cursor_type;
	SQLSTR VARCHAR2(32767);
    
BEGIN

/*
SELECT  R.XRGID, TO_CHAR(R.XRGDATE, 'DD/MM/YYYY') AS XRGDATE, J.XJBNO, ST.ITMCODE, ST.STNDESC || ' ' || ST.STNDESC1 AS STNDESC, 
        DECODE(HIST.XRPTSTS, 'A', 'VER ' || HIST.VERNO || ' Approved', 'P', 'VER ' || HIST.VERNO || ' Draft', '') AS STATUS,
        TO_CHAR(HIST.XRPDATE, 'DD/MM/YYYY HH24:MM:SS') AS XRPDATE, HIST.DOCCODE, HIST.USRID_P, HIST.USRID_T, RPT.VERNO, 
        TO_CHAR(HIST.APPROVEDATE, 'DD/MM/YYYY HH24:MM:SS') AS APPROVEDATE, RPT.XRPPRNCNT,
        R.XRGREMARK, ST.PKGCODE, HIST.XRPID, HIST.XRPCOMBINE, 0 AS COMBINED,
		DECODE(RPT.XRPPRNCNT, NULL, 0, -1) AS REPORTED, HIST.XRPTITLE, J.CLINICNO, 
		DECODE(TRANSVER, NULL, '20060303', TRANSVER) AS TRANSVER, R.XRGRPTFLAG, HIST.XRPTSTS
FROM XJOB J, XREG R, SLIPTX ST, XREPORT RPT, XREPORTHIST HIST
WHERE J.XJBNO = R.XJBNO
AND R.STNID = ST.StnID
AND R.XRGSC <> '-1'
AND R.XRGID = HIST.XRGID (+)
AND HIST.XRPID = RPT.XRPIDHIST (+)
AND NOT (NVL(HIST.XRPTSTS, 'N') = 'A' AND HIST.XRPID <> RPT.XRPIDHIST)
AND (R.XRGRPTFLAG = '-1' OR R.XRGRPTFLAG = '0')
*/

	SQLSTR := '
                SELECT  R.XRGID, TO_CHAR(R.XRGDATE, ''DD/MM/YYYY'') AS XRGDATE, J.XJBNO, ST.ITMCODE, ST.STNDESC || '' '' || ST.STNDESC1 AS STNDESC, 
                        DECODE(HIST.XRPTSTS, ''A'', ''Ver. '' || HIST.VERNO || '' Approved'', ''P'', ''Ver. '' || HIST.VERNO || '' Draft'', '''') AS STATUS,
                        TO_CHAR(HIST.XRPDATE, ''DD/MM/YYYY HH24:MM:SS'') AS XRPDATE, HIST.DOCCODE, HIST.USRID_P, HIST.USRID_T, HIST.VERNO, 
                        TO_CHAR(HIST.APPROVEDATE, ''DD/MM/YYYY HH24:MM:SS'') AS APPROVEDATE, RPT.XRPPRNCNT,
                        R.XRGREMARK, ST.PKGCODE, HIST.XRPID, HIST.XRPCOMBINE, 0 AS COMBINED,
                        DECODE(RPT.XRPPRNCNT, NULL, 0, -1) AS REPORTED, HIST.XRPTITLE, J.CLINICNO, 
                        DECODE(TRANSVER, NULL, ''20060303'', TRANSVER) AS TRANSVER, R.XRGRPTFLAG, HIST.XRPTSTS
                FROM XJOB J, XREG R, SLIPTX ST, XREPORT RPT, XREPORTHIST HIST
                WHERE J.XJBNO = R.XJBNO
                AND R.STNID = ST.StnID
                AND R.XRGSC <> -1
                AND R.XRGID = HIST.XRGID (+)
                AND HIST.XRPID = RPT.XRPIDHIST (+)
                AND NOT (NVL(HIST.XRPTSTS, ''N'') = ''A'' AND HIST.XRPID <> RPT.XRPIDHIST)
                AND (R.XRGRPTFLAG = -1 OR R.XRGRPTFLAG = 0)
			';

IF diNo IS NULL THEN 
    SQLSTR := SQLSTR || 'AND J.PATNO = ''' || patNo || ''' ORDER BY J.XJBNO DESC, R.XRGDATE DESC';
ELSE   
    SQLSTR := SQLSTR || 'AND J.XJBNO = ''' || diNo || ''' ';
END IF;

OPEN OUTCUR FOR SQLSTR;
RETURN OUTCUR;

--RETURN SQLSTR;
END NHS_LIS_ECGEXAMREPORT;