create or replace FUNCTION NHS_GET_ECHOREPORTINFO (	
    v_XRGID IN VARCHAR2
)
RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;

BEGIN
	OPEN OUTCUR FOR
    SELECT  
        P.PATFNAME || ' ' ||  P.PATGNAME AS PATNAME, J.PATNO, ST.STNDESC || ' ' || ST.STNDESC1 AS EXAMNAME,
        R.XJBNO, TO_CHAR(P.PATBDATE, 'DD/MM/YYYY') AS PATBDATE, P.PATSEX, J.XJBTLOC, J.XJBTLOCDESC        
		FROM XREG R, XJOB J,SLIPTX ST, PATIENT P
		WHERE J.PATNO = P.PATNO 
		AND R.XJBNO = J.XJBNO
		AND R.STNID = ST.STNID 
		AND R.XRGID = v_XRGID;
  RETURN OUTCUR;
END NHS_GET_ECHOREPORTINFO;