create or replace FUNCTION "NHS_ACT_DIREOPENREPORT" (
	v_action   IN VARCHAR2,
	v_XRGID  IN VARCHAR2,
	v_XRPID IN VARCHAR2,
	v_SIGNUSER1 IN VARCHAR2,-- input user1
	--v_SIGNUSER2 IN VARCHAR2,-- input user2
	v_USRID IN VARCHAR2, -- LOGIN USER
	o_errmsg   OUT VARCHAR2
)
	RETURN NUMBER
AS
	o_errcode NUMBER;

	v_XRPTSTS XREPORTHIST.XRPTSTS%TYPE;
	v_XRPCOMBINE XREPORTHIST.XRPCOMBINE%TYPE;
	v_XRPTITLE XREPORTHIST.XRPTITLE%TYPE;
	v_XRPDATE XREPORTHIST.XRPDATE%TYPE;
	v_DOCCODE XREPORTHIST.DOCCODE%TYPE;
	v_USRID_T XREPORTHIST.USRID_T%TYPE;
	v_USRID_P XREPORTHIST.USRID_P%TYPE;
	v_XRPPRNCNT XREPORTHIST.XRPPRNCNT%TYPE;
	v_VERNO XREPORTHIST.VERNO%TYPE;	
	v_XRPCONTENT XREPORTHIST.XRPCONTENT%TYPE;
    
    new_XRPID XREPORTHIST.XRPID%TYPE;
	
	v_rptCnt NUMBER;

BEGIN
	o_errcode := 0;
	o_errmsg := 'OK';
	
	IF v_action = 'ADD' THEN

		--get old report info
		SELECT XRPTITLE, XRPDATE, DOCCODE, USRID_T, USRID_P, XRPPRNCNT, VERNO, XRPCONTENT 
		INTO v_XRPTITLE, v_XRPDATE, v_DOCCODE, v_USRID_T, v_USRID_P, v_XRPPRNCNT, v_VERNO, v_XRPCONTENT
		FROM XREPORTHIST
		WHERE XRGID = v_XRGID
		AND XRPID = v_XRPID;
		
		--new report id
		SELECT SEQ_XREPORT.NEXTVAL INTO new_XRPID FROM DUAL;
		
		v_XRPTSTS := 'P';
		v_XRPCOMBINE := new_XRPID;

		--new report record
		INSERT INTO XREPORTHIST 
		(XRPID, XRGID, XRPTITLE, XRPDATE, DOCCODE, 
		USRID_T, USRID_P, XRPPRNCNT, XRPCOMBINE, VERNO,
		XRPTSTS, XRPCONTENT)
		VALUES 
		(new_XRPID, v_XRGID, v_XRPTITLE, SYSDATE, v_DOCCODE, 
		v_USRID, v_USRID_P, v_XRPPRNCNT, v_XRPCOMBINE, v_VERNO+1,
		v_XRPTSTS, v_XRPCONTENT);
		
		-- link old record in xreport to new report
		UPDATE XREPORT
		SET 
		XRPIDHIST = new_XRPID,
		REOPEN1 = v_SIGNUSER1,
		--REOPEN2 = v_SIGNUSER2,
        VERNO = v_VERNO + 1
		WHERE XRGID = v_XRGID;
		
		UPDATE XREPORTHIST
		SET 
		REOPEN1 = v_SIGNUSER1
		--REOPEN2 = v_SIGNUSER2
		WHERE XRPID = v_XRPID;
		
		
		o_errcode := new_XRPID;
	END IF;

	RETURN o_errcode;
END NHS_ACT_DIREOPENREPORT;