create or replace FUNCTION NHS_LIS_ECGRPTQUEUE (
	REPORTED IN VARCHAR2,
    ECGQUEUEFROM IN VARCHAR2,
    ECGQUEUETO IN VARCHAR2
)
	RETURN Types.cursor_type
    --RETURN VARCHAR2
AS
	OUTCUR types.cursor_type;
	SQLSTR VARCHAR2(5000);
	SQLSTR1 VARCHAR2(5000);
	SQLSTR2 VARCHAR2(5000);
    WHERESQL VARCHAR2(5000);
    
BEGIN
    SQLSTR1 := 'SELECT R.XRGID, R.XRGDATE, R.XRGSNDDATE, J.XJBNO, J.DOCCODE, J.XJBTLOC, J.XJBTLOCDESC, TX.STNDESC || '' '' || TX.STNDESC1 AS STNDESC,
				DECODE(P.PMCID, NULL, NULL, 0, NULL, ''M'') MERGED, P.PATNO, P.PATFNAME || '' '' || P.PATGNAME AS PATNAME, ';
    
    SQLSTR2 := 'SELECT R.XRGID, R.XRGDATE, R.XRGSNDDATE, J.XJBNO, J.DOCCODE, J.XJBTLOC, J.XJBTLOCDESC, TX.STNDESC || '' '' || TX.STNDESC1 AS STNDESC,
				NULL MERGED, P.ORPNO AS PATNO, P.ORPFNAME || '' '' || P.ORPGNAME AS PATNAME, ';

	IF REPORTED = '1' THEN
	SQLSTR1 := SQLSTR1 || '	RPT.XRPID, RPT.XRPDATE, RPT.USRID_T, RPT.DOCCODE AS OLD_DOCCODE, RPT.DOCCODE AS NEW_DOCCODE
							FROM XJOB J, XREG R, PATIENT P, SLIPTX TX, XREPORT RPT 
							WHERE R.XRGID = RPT.XRGID ';
	SQLSTR2 := SQLSTR2 || '	RPT.XRPID, RPT.XRPDATE, RPT.USRID_T, RPT.DOCCODE AS OLD_DOCCODE, RPT.DOCCODE AS NEW_DOCCODE
							FROM XJOB J, XREG R, OUTREFPAT P, SLIPTX TX, XREPORT RPT
							WHERE R.XRGID = RPT.XRGID ';
	ELSE
	SQLSTR1 := SQLSTR1 || '	NULL AS XRPID, NULL AS XRPDATE, NULL AS USRID_T, NULL AS OLD_DOCCODE, NULL AS NEW_DOCCODE
							FROM XJOB J, XREG R, PATIENT P, SLIPTX TX
							WHERE R.XRGID NOT IN (SELECT XRGID FROM XREPORT) ';
	SQLSTR2 := SQLSTR2 || '	NULL AS XRPID, NULL AS XRPDATE, NULL AS USRID_T, NULL AS OLD_DOCCODE, NULL AS NEW_DOCCODE
							FROM XJOB J, XREG R, OUTREFPAT P, SLIPTX TX
							WHERE R.XRGID NOT IN (SELECT XRGID FROM XREPORT) ';
	END IF;

    WHERESQL := '
            AND J.XJBNO = R.XJBNO
			AND R.STNID = TX.STNID 
			AND R.XRGECG = ''-1''
			AND R.XRGECGFLAG = ''0''
            AND R.XRGSNDDATE >= TO_DATE(''' || ECGQUEUEFROM || ' 00:00:00'', ''DD/MM/YYYY HH24:MI:SS'')
            AND R.XRGSNDDATE < TO_DATE(''' || ECGQUEUETO || ' 23:59:59'', ''DD/MM/YYYY HH24:MI:SS'') ';
    
    SQLSTR :=   'SELECT XJBNO, NEW_DOCCODE, MERGED, PATNO, PATNAME,
                XRPDATE, STNDESC, USRID_T, XRGSNDDATE,
                XRGID, XRGDATE, DOCCODE, XJBTLOC, XJBTLOCDESC, XRPID, OLD_DOCCODE
                FROM ( ' ||
                SQLSTR1 || WHERESQL || 
                'AND J.PATNO = P.PATNO
                UNION ' ||
                SQLSTR2 || WHERESQL || 
                'AND J.PATNO = P.ORPNO 
                ORDER BY PATNO, XJBNO )';
    
OPEN OUTCUR FOR SQLSTR;
RETURN OUTCUR;
--RETURN SQLSTR;
END NHS_LIS_ECGRPTQUEUE;