@./registration/NHS_ACT_ADDBEDPREBOKCNT.sql
@./registration/NHS_ACT_ADDSTSPREBOK.sql
@./registration/NHS_ACT_BEDCHGHIS.sql
@./registration/NHS_ACT_BEDPREBOK.sql
@./registration/NHS_ACT_BEDPREBOKCNT.sql
@./registration/NHS_ACT_BEDPREBOKDEL.sql
@./registration/NHS_ACT_BEDPREBOKREACTIVE.sql
@./registration/NHS_ACT_BEDRESERVATION.sql
@./registration/NHS_ACT_BEDTRANSFER.sql
@./registration/NHS_ACT_DHBIRTHDTL.sql
@./registration/NHS_ACT_DOCCHGHIS.sql
@./registration/NHS_ACT_DOCINSTRUCTION.sql
@./registration/NHS_ACT_DOCTORTRANSFER.sql
@./registration/NHS_ACT_EBIRTHDTL.sql
@./registration/NHS_ACT_EBIRTHDTL_REG.sql
@./registration/NHS_ACT_EHR_PMI.sql
@./registration/NHS_ACT_HOMELEAVE.sql
@./registration/NHS_ACT_MEDPAT.sql
@./registration/NHS_ACT_MEDRECADDTX.sql
@./registration/NHS_ACT_MEDRECINSERT.sql
@./registration/NHS_ACT_MEDREC_ADD.sql
@./registration/NHS_ACT_MEDREC_ADD_TEST.sql
@./registration/NHS_ACT_OBCERT.sql
@./registration/NHS_ACT_PATALERT.sql
@./registration/NHS_ACT_PATIENT.sql
@./registration/NHS_ACT_PATIENTCATEGORY.sql
@./registration/NHS_ACT_PATIENTDISCHARGE.sql
@./registration/NHS_ACT_PATIENT_CONSENT.sql
@./registration/NHS_ACT_PATIENT_REG.sql
@./registration/NHS_ACT_REG_CANCEL.sql
@./registration/NHS_ACT_SPLITSLIP.sql
@./registration/NHS_ACT_SPLIT_SLIP.sql
@./registration/NHS_ACT_STSPREBOK.sql
@./registration/NHS_ACT_TICKETNO.sql
@./registration/NHS_ACT_TRANTOINPAT.sql
@./registration/NHS_ACT_WAITING2BEDPREBOK.sql
@./registration/NHS_GET_BED_INF.sql
@./registration/NHS_GET_BOOKINGCOUNT.sql
@./registration/NHS_GET_CHECKMANDATORY.sql
@./registration/NHS_GET_DOCCODE_EXIST.sql
@./registration/NHS_GET_DOCTOR.sql
@./registration/NHS_GET_EHR_PMI.sql
@./registration/NHS_GET_INPDDATE.sql
@./registration/NHS_GET_MEDRECDEFSET.sql
@./registration/NHS_GET_MEDRECLOC.sql
@./registration/NHS_GET_MEDRECMED.sql
@./registration/NHS_GET_MEDRECNEXTVOL_REG.sql
@./registration/NHS_GET_MEDREC_CUR.sql
@./registration/NHS_GET_MEDREC_FILL.sql
@./registration/NHS_GET_MEDTODAY_EXIST.sql
@./registration/NHS_GET_OBCERT.sql
@./registration/NHS_GET_OBPATEMAIL.sql
@./registration/NHS_GET_PATIENT.sql
@./registration/NHS_GET_PATIENT_CONSENT.sql
@./registration/NHS_GET_PATIENT_IDNO.sql
@./registration/NHS_GET_PATIENT_NEWREG.sql
@./registration/NHS_GET_PATIENT_NO_EXIST.sql
@./registration/NHS_GET_PREBOOKDETAIL.sql
@./registration/NHS_GET_PREBOOKING.sql
@./registration/NHS_GET_REGOPCAT.sql
@./registration/NHS_GET_SLIPHOMELEAVE.sql
@./registration/NHS_GET_SLIPISINPAT.sql
@./registration/NHS_GET_TICKETNO.sql
@./registration/NHS_GET_TRANSFERBED.sql
@./registration/NHS_GET_WAITINGBOOKCNT.sql
@./registration/NHS_LIS_ARCARDTYPE.sql
@./registration/NHS_LIS_ARCARDTYPESHOW.sql
@./registration/NHS_LIS_ARCODE.sql
@./registration/NHS_LIS_BEDCHGHIS.sql
@./registration/NHS_LIS_BEDPREBOK.sql
@./registration/NHS_LIS_BEDRESERVATION.sql
@./registration/NHS_LIS_DOCCHGHIS.sql
@./registration/NHS_LIS_DOCTOR_INSTRUCTION.sql
@./registration/NHS_LIS_DOC_PRIVILEGE.sql
@./registration/NHS_LIS_EHR_GETEHRNOBYIDS.sql
@./registration/NHS_LIS_EHR_PMIHIST.sql
@./registration/NHS_LIS_EHR_PMI_DUPL.sql
@./registration/NHS_LIS_HOMELEAVE.sql
@./registration/NHS_LIS_ITEM_WITHSUPP.sql
@./registration/NHS_LIS_OBBOOK.sql
@./registration/NHS_LIS_OSBILLALERT.sql
@./registration/NHS_LIS_PATALERT.sql
@./registration/NHS_LIS_PATALERTAVA.sql
@./registration/NHS_LIS_PATIENT.sql
@./registration/NHS_LIS_PATIENTCATEGORY.sql
@./registration/NHS_LIS_PATIENTSEARCH.sql
@./registration/NHS_LIS_PATIENTSEARCH2.sql
@./registration/NHS_LIS_PATIENT_ALERT.sql
@./registration/NHS_LIS_PATIENT_REG.sql
@./registration/NHS_LIS_PATSTATVIEW_FILLNUM.sql
@./registration/NHS_LIS_REGPKGLINK.sql
@./registration/NHS_LIS_REGPRINTADMISSIONFORM.sql
@./registration/NHS_LIS_REGPRINTCALLCHART.sql
@./registration/NHS_LIS_REGSEARCHPRINTDOB.sql
@./registration/NHS_LIS_SEARCHHOMELEAVE.sql
@./registration/NHS_LIS_SELECTSLIP.sql
@./registration/NHS_LIS_STATUSVIEWALL.sql
@./registration/NHS_LIS_STATUSVIEWALLDUP.sql
@./registration/NHS_LIS_STATUSVIEWINPAT.sql
@./registration/NHS_LIS_STATUSVIEWPB.sql
@./registration/NHS_LIS_STATUSVIEWPS.sql
@./registration/NHS_LIS_STATUSVIEWSINGLEDUP.sql
@./registration/NHS_LIS_SUBSPECIALTY.sql
@./registration/NHS_UTL_RESERVE_NEW_PATNO.sql
exit