create or replace FUNCTION "NHS_LIS_STATUSVIEWSINGLEDUP" (
	i_PATNO            IN VARCHAR2,
	i_PATIDNO          IN VARCHAR2,
	i_PATFNAME         IN VARCHAR2,
	i_PATGNAME         IN VARCHAR2,
	i_CHK_NULL_ID_ONLY IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
	v_GetDupPrebok BOOLEAN;
	SQLSTR VARCHAR2(5000);
	strSqlSingleDup VARCHAR2(2000);
BEGIN
	IF i_CHK_NULL_ID_ONLY = 'Y' AND i_PATNO IS NOT NULL AND i_PATIDNO IS NOT NULL THEN
		RETURN OUTCUR;
	END IF;

	v_GetDupPrebok := NHS_UTL_GETDUPPREBOK('PatStsView', strSqlSingleDup, NULL, i_PATNO, i_PATIDNO, i_PATFNAME, i_PATGNAME);
	IF NOT v_GetDupPrebok THEN
		RETURN OUTCUR;
	END IF;

	SQLSTR :='
		SELECT
			B.PBPID,
      BE.BPBREGTYPE,
			B.BPBSTS,
			B.BPBNO,
			B.PATNO,
			UPPER(B.PATFNAME || '' '' || B.PATGNAME) AS PATNAME,
			B.BPBCNAME AS PATCNAME,
			(SELECT D.DOCFNAME || '' '' || D.DOCGNAME || '' ('' || B.DOCCODE || '')''
				FROM DOCTOR D WHERE D.DOCCODE = B.DOCCODE) AS DOCNAME,
			B.SEX,
			TRUNC(MONTHS_BETWEEN(SYSDATE,
				NVL(P.PATBDATE,
				(SELECT OTABDATE
					FROM OT_APP
					WHERE PBPID = B.PBPID
					AND ROWNUM = 1))) / 12,
				0) AS AGE,
			B.ACMCODE,
			B.WRDCODE,
			TO_CHAR(B.BPBHDATE, ''DD/MM/YYYY HH24:MI:SS'') AS HOSDATE,
			B.PATIDNO,
			B.BEDCODE,
			TO_CHAR(B.BEDTIME, ''DD/MM/YYYY HH24:MI''),
			TO_CHAR(B.BPBODATE, ''DD/MM/YYYY'') AS ORDDATE,
			C.USRNAME AS CREATEUSERNAME,
			B.BPBRMK AS REMARK,
			B.PATKHTEL,
			B.PATPAGER,
			(SELECT P.OTPDESC
				FROM OT_PROC P
				WHERE P.OTPID = (SELECT MIN(OTPID)
									FROM OT_APP X
									WHERE X.PBPID = B.PBPID
									AND X.OTAOSDATE =
									(SELECT MIN(A.OTAOSDATE)
										FROM OT_APP A
										WHERE A.PBPID = B.PBPID))) AS OTPDESC,
			(SELECT TO_CHAR(MIN(A.OTAOSDATE), ''DD/MM/YYYY HH24:MI:SS'')
				FROM OT_APP A
				WHERE A.PBPID = B.PBPID) AS OTAOSDATE,
			B.CABLABRMK,
			B.SLPNO,
			D.USRNAME AS EDITUSERNAME,
			TO_CHAR(B.EDITDATE, ''DD/MM/YYYY''),
			TO_CHAR(B.SMSSENTDT, ''DD/MM/YYYY HH24:MI:SS''),
			TO_CHAR(B.EMAILSENTDT, ''DD/MM/YYYY HH24:MI:SS''),
			B.PBPID,
			B.ISREFUSED
		FROM BEDPREBOK B
		LEFT JOIN USR C
			ON C.USRID = B.USRID
		LEFT JOIN USR D
			ON D.USRID = B.EDITUSER
		LEFT JOIN PATIENT P
			ON B.PATNO = P.PATNO
    LEFT JOIN BEDPREBOK_EXTRA BE
      ON B.PBPID = BE.PBPID    
		WHERE B.PBPID IN (' || strSqlSingleDup || ') ORDER BY PATNAME, HOSDATE';

	OPEN OUTCUR FOR SQLSTR;
	RETURN OUTCUR;
END NHS_LIS_STATUSVIEWSINGLEDUP;
/