create or replace
FUNCTION "NHS_LIS_SELECTSLIP"
(
	v_REGID SLIP.REGID%TYPE
)
	RETURN Types.cursor_type
AS
	outcur types.cursor_type;
BEGIN
	open OUTCUR for
    select DECODE(S.SLPREMARK, '', '', '*') as REMARKEXIST,  S.SLPNO, S.SLPTYPE, S.SLPSTS,
           P.PATNO, NVL(S.SLPFNAME, P.PATFNAME) AS PATFNAME,
           NVL(S.SLPGNAME, P.PATGNAME) as PATGNAME, NVL(S.PATCNAME, P.PATCNAME) as PATCNAME,
           D.DOCCODE, D.DOCFNAME, D.DOCGNAME, D.DOCCNAME, I.INPDDATE,
           S.SLPCAMT + S.SLPDAMT + S.SLPPAMT AS SLPNAMT, S.USRID    
    FROM SLIP S, REG R, PATIENT P, DOCTOR D, INPAT I
    where   S.SLPSTS in ('A','C')
    AND  s.regid = v_REGID
    AND  S.REGID = R.REGID(+)
    AND S.PATNO = P.PATNO(+)
    AND S.DOCCODE = D.DOCCODE
    and R.INPID = I.INPID(+)
    ORDER BY SLPNO DESC;
    
	RETURN OUTCUR;
END NHS_LIS_SELECTSLIP;
/