CREATE OR REPLACE FUNCTION "NHS_LIS_EHR_PMI_DUPL" (
	v_PATNO	   IN VARCHAR2,
	v_EHRFNAME	   IN VARCHAR2,
	v_EHRGNAME	   IN VARCHAR2,
	v_EHRDOB	   IN VARCHAR2,
	v_EHRSEX	   IN VARCHAR2,
	v_EHRHKID	   IN VARCHAR2,
	v_EHRDOCNO	   IN VARCHAR2,
	v_EHRDOCTYPE	   IN VARCHAR2,
	v_EHREDOBIND	   IN VARCHAR2,
	v_MATCHTYPE	   IN VARCHAR2
)
	RETURN Types.cursor_type
AS
	OUTCUR Types.cursor_type;
	sqlStr VARCHAR2(5000);
BEGIN
	-- MATCH TYPE:
	-- 'ALL' - match all fields, exact match
	-- 'ID' - match HKID, DOCTYPE, DOCNO

	OPEN OUTCUR FOR 
		SELECT
		  PATNO,
		  EHRNO,
		  EHRFNAME,
		  EHRGNAME,
		  TO_CHAR(EHRDOB, 'DD/MM/YYYY'),
		  EHREDOBIND,
		  EHRSEX,
		  EHRHKID,
		  EHRDOCNO,
		  (SELECT EHRDESC || ' (' || EHRCODE || ')' FROM EHR_PMIDOCTYPE WHERE EHRCODE = EHRDOCTYPE) DOCTYPE
		FROM EHR_PMI
		WHERE 
			(v_MATCHTYPE = 'ALL' AND 
				(v_PATNO <> PATNO AND 
				NVL(EHRFNAME, 0) = NVL(v_EHRFNAME, 0) AND 
				NVL(EHRGNAME, 0) = NVL(v_EHRGNAME, 0) AND 
				NVL(TO_CHAR(EHRDOB, 'DD/MM/YYYY'), 0) = NVL(v_EHRDOB, 0) AND 
				NVL(EHREDOBIND, 0) = NVL(v_EHREDOBIND, 0) AND 
				NVL(EHRSEX, 0) = NVL(v_EHRSEX, 0) AND 
				TRIM(NVL(EHRHKID, 0)) = TRIM(NVL(v_EHRHKID, 0)) AND 
				NVL(EHRDOCNO, 0) = NVL(v_EHRDOCNO, 0) AND 
				NVL(EHRDOCTYPE, 0) = NVL(v_EHRDOCTYPE, 0)))
			OR
			((v_MATCHTYPE = 'ID' OR v_MATCHTYPE IS NULL) AND
				(v_PATNO <> PATNO AND 
				TRIM(NVL(EHRHKID, 0)) = TRIM(NVL(v_EHRHKID, 0)) AND 
				NVL(EHRDOCNO, 0) = NVL(v_EHRDOCNO, 0) AND 
				NVL(EHRDOCTYPE, 0) = NVL(v_EHRDOCTYPE, 0)))
		ORDER BY PATNO;
	RETURN OUTCUR;
END NHS_LIS_EHR_PMI_DUPL;
/
