create or replace FUNCTION "NHS_LIS_SHOWSAMEDTAPP" (
	v_patno IN VARCHAR2,
  v_date in VARCHAR2
)
	RETURN Types.cursor_type
AS
	OUTCUR types.cursor_type;
BEGIN
	OPEN OUTCUR FOR
  SELECT SIT.STENAME, S.DOCCODE, D.DOCFNAME||' '||D.DOCGNAME, TO_CHAR(B.BKGSDATE, 'DD/MM/YYYY'), TO_CHAR(B.BKGSDATE, 'HH24:MI'),
  B.PATNO, B.BKGPNAME, DECODE(S.DOCLOCID,1,'Urgent Care',2,'GP-SP',3,'Dental')
  FROM BOOKING B, SCHEDULE S, DOCTOR D, SITE SIT
  WHERE B.STECODE = SIT.STECODE
  AND B.SCHID = S.SCHID
  AND S.DOCCODE = D.DOCCODE
  AND B.PATNO = v_patno
  AND TRUNC(B.BKGSDATE, 'DD') = TO_DATE(v_date||' 00:00:00','DD/MM/YYYY HH24:MI:SS')
  AND S.DOCLOCID IN (1,2)
  AND BKGSTS = 'N'
  ORDER BY TO_CHAR(B.BKGSDATE, 'HH24:MI');
  RETURN OUTCUR;
END NHS_LIS_SHOWSAMEDTAPP;
/