create or replace FUNCTION "NHS_LIS_STATUSVIEWALLDUP" (
	v_DUMMY IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
	v_GetDupPrebok BOOLEAN;
	v_Count NUMBER;
	v_DUPBPDAY NUMBER;
	SQLSTR VARCHAR2(5000);
	STRSQLALLDUP VARCHAR2(2000);
BEGIN
	V_GETDUPPREBOK := NHS_UTL_GETDUPPREBOK('AllDup', STRSQLALLDUP, NULL, NULL, NULL, NULL, NULL);

	IF NOT v_GetDupPrebok THEN
		RETURN OUTCUR;
	END IF;

	SELECT COUNT(1) INTO v_Count FROM SYSPARAM WHERE PARCDE = 'DUPBPDAY';
	IF v_Count = 1 THEN
		SELECT DECODE(TO_NUMBER(PARAM1), NULL, 1, 0, 1, TO_NUMBER(PARAM1)) INTO v_DUPBPDAY FROM SYSPARAM WHERE PARCDE = 'DUPBPDAY';
	ELSE
		v_DUPBPDAY := 1;
	END IF;

	SQLSTR := 'SELECT
			D.PBPID,
			D.BPBSTS,
			D.BPBREGTYPE,
			D.BPBNO,
			D.PATNO,
			DECODE(NVL(P.TITDESC, ''''), '''', '''',  ''<font color=blue>'' || P.TITDESC || ''</font> '') || D.PATNAME,
			D.BPBCNAME,
			D.DOCNAME,
			DECODE(NVL(D.SEX, ''''), '''', '''', ''M'', ''<font color=blue>M</font>'', ''F'', ''<font color=red>F</font>'', D.SEX),
			D.AGE,
			D.ACMCODE,
			D.WRDCODE,
			TO_CHAR(D.HOSDATE, ''DD/MM/YYYY HH24:MI:SS'') AS HOSDATE,
			D.PATIDNO,
			D.BEDCODE,
			TO_CHAR(D.BEDTIME, ''DD/MM/YYYY HH24:MI''),
			TO_CHAR(ORDDATE, ''DD/MM/YYYY'') AS ORDDATE,
			D.CREATEUSERNAME,
			D.BPBRMK AS REMARK,
			D.PATKHTEL,
			D.PATPAGER,
			D.OTPDESC,
			TO_CHAR(D.OTAOSDATE, ''DD/MM/YYYY HH24:MI:SS'') AS OTAOSDATE,
			D.CABLABRMK,
			D.SLPNO,
			D.EDITUSERNAME,
			TO_CHAR(D.EDITDATE, ''DD/MM/YYYY''),
			TO_CHAR(D.SMSSENTDT, ''DD/MM/YYYY HH24:MI:SS''),
			TO_CHAR(D.EMAILSENTDT, ''DD/MM/YYYY HH24:MI:SS''),
			D.PBPID,
			D.ISREFUSED
		FROM PREBOOKING_DETAIL D
		LEFT JOIN PATIENT P ON D.PATNO = P.PATNO
		WHERE TRUNC(D.HOSDATE) BETWEEN TRUNC(SYSDATE) AND TRUNC(SYSDATE) + TO_NUMBER(' || TO_CHAR(v_DUPBPDAY) || ')
		AND  (D.PBPID IN (' || strSqlAllDup || ')
			OR D.PBPID IN (SELECT PBPID_WITHPATNO FROM PREBOOKING_DUPNAME)
			OR D.PBPID IN (SELECT PBPID_WITHOUTPATNO FROM PREBOOKING_DUPNAME)
		)
		ORDER BY D.PATNAME, D.HOSDATE';

	OPEN OUTCUR FOR SQLSTR;
	RETURN OUTCUR;
END NHS_LIS_STATUSVIEWALLDUP;
/
