create or replace
FUNCTION "NHS_GET_WAITINGBOOKCNT"(V_EDC    IN VARCHAR2)
  RETURN TYPES.CURSOR_TYPE AS
  V_EDCDATE  DATE;
  V_curWaitingcnt NUMBER;
  V_obBookCnt NUMBER;
  V_TotalCnt NUMBER;
  OUTCUR     TYPES.CURSOR_TYPE;
BEGIN
  SELECT TO_DATE(V_EDC, 'DD/MM/YYYY') INTO V_EDCDATE FROM DUAL;

  SELECT COUNT(*) 
  INTO V_curWaitingcnt
    FROM BEDPREBOK
   WHERE TO_CHAR(BPBHDATE, 'YYYYMM') = TO_CHAR(V_EDCDATE, 'YYYYMM')
     AND BPBTYPE = 'W'
     AND BPBSTS <>'D'
     AND FORDELIVERY = -1;

  SELECT COUNT(*) 
  INTO V_obBookCnt
    FROM BEDPREBOK
   WHERE TO_CHAR(BPBHDATE, 'YYYYMM') = TO_CHAR(V_EDCDATE, 'YYYYMM')
     AND BPBSTS <>'D'
     AND FORDELIVERY = -1;
     
  BEGIN
    SELECT BPBCNT
    INTO V_TotalCnt
      FROM BEDPREBOKCNT
     WHERE BPBMONTH = TO_CHAR(V_EDCDATE, 'YYYYMM');       
  EXCEPTION
  WHEN OTHERS THEN
    V_TotalCnt:=0;
  END;


  OPEN OUTCUR FOR
    SELECT  V_curWaitingcnt,
            V_obBookCnt,
            V_TotalCnt
      FROM DUAL;
  RETURN OUTCUR;
END NHS_GET_WAITINGBOOKCNT;
/