create or replace FUNCTION                                    NHS_LIS_DTDVBTABLELIST (
	AID_sql IN VARCHAR2,
  v_USRID IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
	SQLSTR VARCHAR2(3000);
BEGIN
	SQLSTR := '
		select  
      AL.ALERT,
      B.SCHID,
      B.SLTID,
      B.BKGID,
			to_char(B.BKGSDATE,''dd/mm/yyyy hh24:mi''),
			TO_CHAR(B.BKGEDATE, ''HH24:MI'') ,
			d.DOCFNAME ||'' ''|| d.DOCGNAME as appDoctor,
			B.PATNO,
			B.BKGPNAME as name,
			B.BKGSTS,
      B.BKGMTEL||'' / ''||B.BKGPTEL,
      DL.DOCLOCNAME AS RM,
      B.BKGRMK,
			TO_CHAR(B.BKGCDATE, ''DD/MM/YYYY HH24:MI''),
			U1.USRNAME,
      U2.USRNAME,
      TO_CHAR(B.BKGADATE, ''DD/MM/YYYY HH24:MI''),
      DL.DOCLOCID,
      D.DOCCODE,
      B.BKGPTEL
		from  BOOKING B
    INNER JOIN DOCLOCATION DL ON B.DOCLOCID = DL.DOCLOCID
    INNER JOIN SCHEDULE S ON B.SCHID = S.SCHID 
    LEFT JOIN DOCTOR D ON S.DOCCODE = D.DOCCODE 
    LEFT JOIN USR U1 ON B.USRID = U1.USRID
		LEFT JOIN USR U2 ON B.CANCELBY = U2.USRID 
    LEFT OUTER JOIN ( SELECT PL.PATNO, LISTAGG( A.ALTCODE, '','' ) WITHIN GROUP ( ORDER BY A.ALTCODE ) ALERT
						FROM PATALTLINK PL, ALERT A
						WHERE PL.ALTID = A.ALTID  AND PL.PALCDATE IS NULL
            AND PL.ALTID IN ( SELECT DISTINCT R.ALTID FROM USRROLE U, ROLALTLINK R WHERE U.ROLID = R.ROLID ';
                        	IF v_USRID IS NOT NULL THEN
                SQLSTR := SQLSTR || ' AND U.USRID = ''' || v_USRID || ''') ';
              END IF;
            SQLSTR := SQLSTR || ' GROUP BY PL.PATNO ) AL ON AL.PATNO = B.PATNO WHERE 1=1 ';
    SQLSTR := SQLSTR || AID_sql ||' ORDER BY B.BKGSDATE';
    DBMS_OUTPUT.PUT_LINE(SQLSTR);
	OPEN OUTCUR FOR SQLSTR;
	RETURN OUTCUR;
END NHS_LIS_DTDVBTABLELIST;
/
