CREATE OR REPLACE FUNCTION "NHS_LIS_STATUSVIEWINPAT"(
	V_PATNO    IN VARCHAR2,
	V_FNAME    IN VARCHAR2,
	V_GNAME    IN VARCHAR2,
	V_WRDCODE  IN VARCHAR2,
	V_DOCCODE  IN VARCHAR2,
	V_REGFDATE IN VARCHAR2,
	V_REGTDATE IN VARCHAR2,
	V_ORDERBY  IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE AS
	OUTCUR TYPES.CURSOR_TYPE;
	SQLSTR VARCHAR2(2000);
BEGIN
	SQLSTR := '
		SELECT
			DECODE(LINK.NUM, NULL, '''', ''*'') || DECODE(E.SPRQTID, NULL, '''', ''#'') AS ALERT,
			PAT.PATNO,
			DECODE(NVL(PAT.TITDESC, ''''), '''', '''',  ''<font color=blue>'' || PAT.TITDESC || ''</font> '') || PAT.PATFNAME || '' '' || PAT.PATGNAME AS PATNAME,
			PAT.PATCNAME,
			B.BEDCODE,
			B.EXTPHONE,
			decode(E.SPRQTID,''0'',''DND'',''1'',''INCOGNITO''),
			S.SLPNO,
			TO_CHAR(REG.REGDATE,''DD/MM/YYYY HH24:MI:SS''),
			DOC2.DOCFNAME || '' '' || DOC2.DOCGNAME AS DOCCODE_REG,
			DOC1.DOCFNAME || '' '' || DOC1.DOCGNAME AS DOCCODE_ATT,
			TRUNC(MONTHS_BETWEEN(SYSDATE, PAT.PATBDATE) / 12) AS AGE,
			DECODE(NVL(PAT.PATSEX, ''''), '''', '''', ''M'', ''<font color=blue>M</font>'', ''F'', ''<font color=red>F</font>'', PAT.PATSEX),
			INP.ACMCODE,
			RM.WRDCODE,
			INP.INPREMARK,
			REG.REGID,
			REG.REGSTS
      		FROM ROOM RM,
			BED B,
			INPAT INP,
			REG REG,
			(SELECT COUNT(PALID) AS NUM, PATNO
				FROM PATALTLINK
				WHERE USRID_C IS NULL
				GROUP BY PATNO
				HAVING COUNT(PALID) > 0) LINK,
			SLIP S,
			Slip_Extra E,
			PATIENT PAT,
			DOCTOR DOC1,
			DOCTOR DOC2
		WHERE REG.REGTYPE = ''I''
		AND REG.REGSTS = ''N''
		AND INP.INPDDATE IS NULL
		AND REG.INPID = INP.INPID + 0
		AND PAT.PATNO = REG.PATNO
		AND INP.BEDCODE = B.BEDCODE
		AND B.ROMCODE = RM.ROMCODE
		AND S.SLPNO = REG.SLPNO
		AND REG.SLPNO = E.SLPNO(+)
		AND PAT.PATNO = LINK.PATNO(+)
		AND S.DOCCODE = DOC1.DOCCODE
		AND REG.DOCCODE = DOC2.DOCCODE ';
	IF V_PATNO IS NOT NULL THEN
		SQLSTR := SQLSTR || ' AND PAT.PATNO = ''' || V_PATNO || '''';
	END IF;
	IF V_FNAME IS NOT NULL THEN
		SQLSTR := SQLSTR || ' AND PAT.PATFNAME = ''' || V_FNAME || '''';
	END IF;
	IF V_GNAME IS NOT NULL THEN
		SQLSTR := SQLSTR || ' AND PAT.PATGNAME = ''' || V_GNAME || '''';
	END IF;
	IF V_WRDCODE IS NOT NULL THEN
		SQLSTR := SQLSTR || ' AND RM.WRDCODE = ''' || V_WRDCODE || '''';
	END IF;
	IF V_DOCCODE IS NOT NULL THEN
		SQLSTR := SQLSTR || ' AND S.DOCCODE = ''' || V_DOCCODE || '''';
	END IF;
	IF V_REGFDATE IS NOT NULL THEN
		SQLSTR := SQLSTR || ' AND REG.REGDATE >= TO_DATE(''' || V_REGFDATE || ''',''dd/mm/yyyy'')';
	END IF;
	IF V_REGTDATE IS NOT NULL THEN
		SQLSTR := SQLSTR || ' AND REG.REGDATE < TO_DATE(''' || V_REGTDATE || ''',''dd/mm/yyyy'') + 1';
	END IF;
	IF V_ORDERBY IS NOT NULL THEN
		SQLSTR := SQLSTR || ' ORDER BY ' || V_ORDERBY;
	END IF;

	OPEN OUTCUR FOR SQLSTR;
	RETURN OUTCUR;
END NHS_LIS_STATUSVIEWINPAT;
/
