CREATE OR REPLACE FUNCTION "NHS_GET_EHR_PMI" (
	V_PATNO	   IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
BEGIN
	OPEN OUTCUR FOR 
		SELECT
		  EP.PATNO,
		  EP.EHRNO,
		  EP.EHRFNAME,
		  EP.EHRGNAME,
		  TO_CHAR(EP.EHRDOB, 'DD/MM/YYYY'),
		  EP.EHREDOBIND,
		  EP.EHRSEX,
		  EP.EHRHKID,
		  EP.EHRDOCNO,
		  EP.EHRDOCTYPE,
		  EP.ACTIVE,
		  TO_CHAR((SELECT MAX(EHRDEATHDATE) KEEP (DENSE_RANK LAST ORDER BY EHRID)
			FROM EHR_PMIHIST
    		WHERE PATNO = EP.PATNO), 'DD/MM/YYYY') DEATHDATE,
    	  CASE WHEN INSTR(EP.EHRHKID, ' ') = 1 THEN 'Y' ELSE 'N' END EHRHKID_ISADDSPC,
    	  CASE WHEN P.PATNB = -1 THEN 
    	  	(SELECT TO_CHAR(MAX(REGID) KEEP (DENSE_RANK FIRST ORDER BY REGID)) REGID
			FROM REG
			WHERE PATNO = P.PATNO
			AND REGNB = -1
			AND REGSTS = 'N')
    	  ELSE 'N/A' END PATNB_REGID
		FROM PATIENT P LEFT JOIN EHR_PMI EP 
			ON P.PATNO = EP.PATNO
		WHERE P.PATNO = V_PATNO;
	RETURN OUTCUR;
END NHS_GET_EHR_PMI;
/
