CREATE OR REPLACE FUNCTION NHS_GET_DOCTOR (
	v_DOCCODE IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
BEGIN
	OPEN OUTCUR FOR
		SELECT DR.DOCCODE,
			DR.DOCFNAME,
			DR.DOCGNAME,
			DR.DOCCNAME,
			DR.DOCIDNO,
			DR.DOCSEX,
			'',
			DR.SPCCODE,
			DECODE(DR.DOCSTS, -1, 'Y', 'N'),
			DR.DOCTYPE,
			DR.DOCPCT_I,
			DR.DOCPCT_O,
			DR.DOCPCT_D,
			DR.DOCADD1,
			DR.DOCADD2,
			DR.DOCADD3,
			DR.DOCHTEL,
			DR.DOCOTEL,
			DR.DOCPTEL,
			DR.DOCTSLOT,
			DR.DOCQUALI,
			TO_CHAR(DR.DOCTDATE, 'DD/MM/YYYY'),
			TO_CHAR(DR.DOCSDATE, 'DD/MM/YYYY'),
			DR.DOCHOMADD1,
			DR.DOCHOMADD2,
			DR.DOCHOMADD3,
			DR.DOCOFFADD1,
			DR.DOCOFFADD2,
			DR.DOCOFFADD3,
			DECODE(DR.DOCCSHOLY, -1, 'Y', 'N'),
			DR.DOCMTEL,
			DR.DOCEMAIL,
			DR.DOCFAXNO,
			DR.DOCHOMADD4,
			DR.DOCADD4,
			DR.DOCOFFADD4,
			DECODE(DR.DOCPICKLIST, -1, 'Y', 'N'),
			DECODE(DR.DOCQUALIFY, -1, 'Y', 'N'),
			TO_CHAR(DR.DOCBDATE, 'DD/MM/YYYY'),
			DR.RPTTO,
			DECODE(DR.ISDOCTOR, -1, 'Y', 'N'),
			DR.TITTLE,
			DECODE(DR.ISOTSURGEON, -1, 'Y', 'N'),
			DECODE(DR.ISOTANESTHETIST, -1, 'Y', 'N'),
			DECODE(DR.SHOWPROFILE, -1, 'Y', 'N'),
			DR.BRNO,
			DECODE(DR.ISOTENDOSCOPIST, -1, 'Y', 'N'),
			DR.DOCREMARK,
			DT.ECERT1,
			DT.ECERT2,
			DT.ECERT3,
			DT.ECERT4,
			DT.ECERT5,
			DT.ECERT6,
			DT.ECERT7,
			DT.ECERT8,
			DT.ECERT9,
			DT.ECERT10,
			DT.CCERT1,
			DT.CCERT2,
			DT.CCERT3,
			DT.CCERT4,
			DT.CCERT5,
			DT.CCERT6,
			DT.CCERT7,
			DT.CCERT8,
			DT.CCERT9,
			DT.CCERT10,
			TO_CHAR(DR.APLDATE, 'DD/MM/YYYY'),
			TO_CHAR(DR.MPSCDATE, 'DD/MM/YYYY'),
			TO_CHAR(DR.OPPEDATE, 'DD/MM/YYYY'),
			DR.DOCINSURCOMP,
			DECODE(DR.DOCTYPE, 'C', 'Consultant', 'I', 'Inhouse', '-'),
			DE.PBO_REMARK,
			DECODE(DE.STODECLARATION,-1,'Y','N')
------------unused items from doctor table----------------------
--			USRID, DAYINSTRUCTION, INPINSTRUCTION,
--			OUPINSTRUCTION, PAYINSTRUCTION, BRNO, DOCREMARK,
--			CPSDATE, SLDATE
		FROM  DOCTOR DR
		LEFT JOIN DOCTOR_EXTRA DE ON DR.DOCCODE = DE.DOCCODE
		LEFT JOIN DOCCERT DT ON DR.DOCCODE = DT.DOCCODE
		WHERE DR.DOCCODE = v_DOCCODE;

	RETURN OUTCUR;
END NHS_GET_DOCTOR;
/
