CREATE OR REPLACE FUNCTION "NHS_LIS_DUPLPATIENT" (
	v_PATNO    IN VARCHAR2,
	v_PATBDATE IN VARCHAR2,
	v_PATFNAME IN VARCHAR2,
	v_PATGNAME IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
	sqlStr VARCHAR2(5000);
BEGIN
	sqlStr := '
		SELECT
			P.PATNO,
			P.PATFNAME,
			P.PATGNAME,
			P.PATMNAME,
			P.PATCNAME,
			E.EHRFNAME,
			E.EHRGNAME,
			P.PATSEX PATSEX,
			TO_CHAR(P.PATBDATE, ''DD/MM/YYYY'') PATBDATE,
			P.PATPAGER,
			P.PATHTEL,
			P.PATIDNO,
			P.PATVCNT,
			TO_CHAR(R.REGDATE, ''DD/MM/YYYY'') LASTUPD
		FROM   PATIENT P
		LEFT   JOIN EHR_PMI E ON P.PATNO = E.PATNO
		LEFT   JOIN REG R ON P.REGID_C = R.REGID ';

	sqlStr := sqlStr || 'WHERE TO_CHAR(P.PATBDATE, ''DD/MM/YYYY'') = ''' || TO_CHAR(TO_DATE(v_PATBDATE, 'DD/MM/YYYY'), 'DD/MM/YYYY') || ''' ';
	sqlStr := sqlStr || 'AND   P.PATFNAME LIKE ''%' || v_PATFNAME || '%'' ';
	sqlStr := sqlStr || 'AND   P.PATGNAME LIKE ''%' || v_PATGNAME || '%'' ';
	sqlStr := sqlStr || 'AND   ROWNUM <= 100 ';
	sqlStr := sqlStr || 'order by P.PATNO ';

	OPEN OUTCUR FOR sqlStr;
	RETURN OUTCUR;

END NHS_LIS_DUPLPATIENT;
/
