CREATE OR REPLACE FUNCTION NHS_LIS_BEDRESERVATION (
	v_BEDCODE   VARCHAR2,
	v_ROMCODE   VARCHAR2,
	v_WRDCODE   VARCHAR2,
	v_ROMSEX    VARCHAR2,
	v_ACMCODE   VARCHAR2,
	v_VACANT    VARCHAR2,
	v_CLEAN     VARCHAR2,
	v_OFFICIAL  VARCHAR2,
	v_DATEFROM  VARCHAR2,
	v_DATETO    VARCHAR2
)
	RETURN Types.cursor_type
AS
	OUTCUR              TYPES.CURSOR_TYPE;
	SQLSTR              VARCHAR2(2500);
	CLEANSQL            VARCHAR2(1000);
	VACANTNOTCLEANSQL   VARCHAR2(1000);
	NOTVACANTSQL        VARCHAR2(1000);

	VACANTSQL           VARCHAR2(100);
	OFFICIALSQL         VARCHAR2(100);
	DATERANGESQL        VARCHAR2(300);
	BEDASSIGNSQL        VARCHAR2(500);
BEGIN
	IF v_VACANT = 'N' THEN
		VACANTSQL := 'AND BEDSTS = ''O'' ';
	ELSIF v_VACANT = 'Y' THEN
		VACANTSQL := 'AND BEDSTS = ''F'' ';
	ELSE
		VACANTSQL := '';
	END IF;

	IF v_OFFICIAL = 'N' THEN
		OFFICIALSQL := 'AND BEDOFF = ''0'' ';
	ELSIF v_OFFICIAL = 'Y' THEN
		OFFICIALSQL := 'AND BEDOFF = ''-1'' ';
	ELSE
		OFFICIALSQL := '';
	END IF;

	IF v_DATEFROM IS NOT NULL THEN
		DATERANGESQL := 'AND BEDRDATE >= TO_DATE(''' || v_DATEFROM || ' 00:00:00'',''DD/MM/YYYY HH24:MI:SS'') ';
	END IF;

	IF v_DATETO IS NOT NULL THEN
		DATERANGESQL := DATERANGESQL || 'AND BEDRDATE <= TO_DATE(''' || v_DATETO || ' 23:59:59'',''DD/MM/YYYY HH24:MI:SS'') ';
	END IF;

	IF v_BEDCODE IS NOT NULL THEN
		BEDASSIGNSQL := BEDASSIGNSQL || 'AND B.BEDCODE LIKE''' || v_BEDCODE || '%'' ';
	END IF;

	IF v_ROMCODE IS NOT NULL THEN
		BEDASSIGNSQL := BEDASSIGNSQL || 'AND B.ROMCODE LIKE''' || v_ROMCODE || '%'' ';
	END IF;

	IF v_WRDCODE IS NOT NULL THEN
		BEDASSIGNSQL := BEDASSIGNSQL || 'AND R.WRDCODE=''' || v_WRDCODE || ''' ';
	END IF;

	IF v_ROMSEX IS NOT NULL THEN
		BEDASSIGNSQL := BEDASSIGNSQL || 'AND R.ROMSEX=''' || v_ROMSEX || ''' ';
	END IF;

	IF v_ACMCODE IS NOT NULL THEN
		BEDASSIGNSQL := BEDASSIGNSQL || 'AND R.ACMCODE=''' || v_ACMCODE || ''' ';
	END IF;

	BEDASSIGNSQL := BEDASSIGNSQL || VACANTSQL || OFFICIALSQL || DATERANGESQL;

	CLEANSQL := '
		SELECT DISTINCT /*+ ORDERED USE_NL(b, r, a) INDEX(b IDX_Bed_101) INDEX(r idx_room_101) */
			B.BEDCODE, ACMNAME, BEDSTS, ''Y'' AS CLEAN, '''' AS PATNO,
			'''' AS PATNAME, '''' AS PATSEX, BEDREMARK,
			TO_CHAR(BEDRDATE, ''DD/MM/YYYY''), '''' AS DOCCODE, BEDOFF
		FROM  BED B, ROOM R, ACM A
		WHERE B.ROMCODE = R.ROMCODE
		AND   A.ACMCODE = R.ACMCODE
		AND   BEDSTS = ''F''
		AND (UPPER(BEDREMARK) NOT LIKE ''INVALID%'' OR BEDREMARK IS NULL) ';

	VACANTNOTCLEANSQL := '
		SELECT DISTINCT /*+ ORDERED USE_NL(B, R, A) INDEX(B IDX_BED_101) INDEX(R IDX_ROOM_101)*/
			B.BEDCODE, ACMNAME, BEDSTS, ''N'' AS CLEAN, '''' AS PATNO,
			'''' AS PATNAME, '''' AS PATSEX, BEDREMARK,
			TO_CHAR(BEDRDATE, ''DD/MM/YYYY''), '''' AS DOCCODE, BEDOFF
		FROM BED B, ROOM R, ACM A
		WHERE B.ROMCODE = R.ROMCODE
		AND A.ACMCODE = R.ACMCODE
		AND BEDSTS = ''F''
		AND (UPPER(BEDREMARK) NOT LIKE ''INVALID%'' OR BEDREMARK IS NULL) ';

	NOTVACANTSQL := '
		SELECT DISTINCT /*+ ORDERED USE_NL(B, R, A, I, G, P) INDEX(B IDX_BED_101) INDEX(R IDX_ROOM_101)
			INDEX(I IDX_INPAT_101) INDEX(P IDX_PATIENT_101)*/
			B.BEDCODE, ACMNAME, BEDSTS, ''N'' AS CLEAN, P.PATNO,
			P.PATFNAME || '' '' || P.PATGNAME AS PATNAME, P.PATSEX, BEDREMARK,
			TO_CHAR(BEDRDATE, ''DD/MM/YYYY''), G.DOCCODE, BEDOFF
		FROM BED B, ROOM R, INPAT I, REG G, PATIENT P, ACM A
		WHERE B.BEDCODE = I.BEDCODE(+)
		AND B.ROMCODE = R.ROMCODE
		AND A.ACMCODE = R.ACMCODE
		AND I.INPID = G.INPID
		AND INPDDATE IS NULL
		AND G.PATNO = P.PATNO
		AND G.REGSTS = ''N''
		AND BEDSTS = ''O''
		AND (UPPER(BEDREMARK) NOT LIKE ''INVALID%'' OR BEDREMARK IS NULL) ';

	IF v_CLEAN = 'N' THEN
		SQLSTR := NOTVACANTSQL || BEDASSIGNSQL || 'UNION ALL ' ||
			VACANTNOTCLEANSQL || BEDASSIGNSQL || 'AND B.BEDDDATE > (SYSDATE - 40/1440) ORDER BY BEDCODE ';
	ELSIF v_CLEAN = 'Y' THEN
		SQLSTR := CLEANSQL || BEDASSIGNSQL || 'AND B.BEDDDATE <= (SYSDATE - 40/1440) ORDER BY BEDCODE ';
	ELSE
		SQLSTR := NOTVACANTSQL || BEDASSIGNSQL || 'UNION ALL ' ||
			VACANTNOTCLEANSQL || BEDASSIGNSQL || 'AND B.BEDDDATE > (SYSDATE - 40/1440) ' ||
			'UNION ALL ' || CLEANSQL || BEDASSIGNSQL ||
			'AND B.BEDDDATE <= (SYSDATE - 40/1440) ORDER BY BEDCODE ';
	END IF;

	OPEN outcur FOR sqlstr;
	RETURN OUTCUR;
END NHS_LIS_BEDRESERVATION;
/
