create or replace FUNCTION "NHS_LIS_PATIENTSEARCH"(
	i_PATNO       IN VARCHAR2,
	i_PATFNAME    IN VARCHAR2,
	i_PATGNAME    IN VARCHAR2,
	i_PATCNAME    IN VARCHAR2,
	i_DOCCODE     IN VARCHAR2,
	i_SLPNO       IN VARCHAR2,
	i_REGTYPE     IN VARCHAR2,
	i_RegDateFrom IN VARCHAR2,
	i_RegDateTo   IN VARCHAR2,
	i_DisDateFrom IN VARCHAR2,
	i_DisDateTo   IN VARCHAR2,
	i_REGSTS      IN VARCHAR2,
	i_CURINPAT    IN VARCHAR2,
	i_WRDCODE     IN VARCHAR2,
	i_BEDCODE     IN VARCHAR2,
	i_CreateBy	  IN VARCHAR2,
	i_UsrID       IN VARCHAR2,
	i_SORT        IN VARCHAR2,
  	i_SPEC        IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
BEGIN
	OPEN OUTCUR FOR
		NHS_LIS_PATIENTSEARCH2(i_PATNO, i_PATFNAME, i_PATGNAME, i_PATCNAME, i_DOCCODE, i_SLPNO, i_REGTYPE, i_RegDateFrom, i_RegDateTo, i_DisDateFrom, i_DisDateTo, i_REGSTS, i_CURINPAT, i_WRDCODE, i_BEDCODE, i_CreateBy, i_UsrID, i_SORT, i_SPEC);
	RETURN OUTCUR;
END NHS_LIS_PATIENTSEARCH;
/
