create or replace
FUNCTION "NHS_LIS_REGPKGLINK"(
  V_PATNO IN VARCHAR2,
  V_REGID_IN VARCHAR2
)
  RETURN TYPES.CURSOR_TYPE AS
  OUTCUR TYPES.CURSOR_TYPE;
BEGIN
  IF V_REGID_IN IS NOT NULL THEN
    OPEN OUTCUR FOR
      SELECT L.PKGCODE, K.PKGNAME, NULL, NULL, NULL, NULL, NULL
        FROM PACKAGE K, REGPKGLINK L, PATIENT P
       WHERE V_REGID_IN = L.REGID
         AND L.PKGCODE = K.PKGCODE
         AND P.PATNO = V_PATNO;
  ELSE
    OPEN OUTCUR FOR
      SELECT L.PKGCODE, K.PKGNAME, NULL, NULL, NULL, NULL, NULL
        FROM PACKAGE K, REGPKGLINK L, PATIENT P
       WHERE P.REGID_C = L.REGID
         AND L.PKGCODE = K.PKGCODE
         AND P.PATNO = V_PATNO;
  END IF;
  RETURN OUTCUR;
END NHS_LIS_REGPKGLINK;
/