CREATE OR REPLACE FUNCTION "NHS_ACT_WAITING2BEDPREBOK"
(V_ACTION IN VARCHAR2,
V_USRID  IN VARCHAR2,
V_BOOKINGID  IN VARCHAR2,
O_ERRMSG OUT VARCHAR2)
RETURN NUMBER
AS
	O_ERRCODE NUMBER;
  	OUTCUR TYPES.CURSOR_TYPE;
BEGIN
	O_ERRCODE := 0;
	O_ERRMSG  := 'OK';

--	OUTCUR := OB_BOOKING_CREATE@PORTAL(V_USRID, V_BOOKINGID, 'Y');

	RETURN O_ERRCODE;
EXCEPTION
WHEN OTHERS THEN
	ROLLBACK;
	dbms_output.put_line('An ERROR was encountered - '||SQLCODE||' -ERROR- '||SQLERRM);

	RETURN -1;
END NHS_ACT_WAITING2BEDPREBOK;
/
