CREATE OR REPLACE FUNCTION NHS_ACT_PATIENT_IDSCANNER (
	i_DocType   IN VARCHAR2,
	i_DocID     IN VARCHAR2,
	i_FirstName IN VARCHAR2,
	i_LastName  IN VARCHAR2,
	i_Sex       IN VARCHAR2,
	i_DOB       IN VARCHAR2,
	i_LocalIP   IN VARCHAR2
)
	RETURN Types.cursor_type
AS
	OUTCUR types.cursor_type;
	v_Count NUMBER;
BEGIN
	SELECT COUNT(1) INTO v_Count FROM HPSTATUS WHERE HPTYPE = 'IDSCANNER' AND HPKEY = i_LocalIP AND HPSTATUS = 'DocType';
	IF v_Count = 0 THEN
		INSERT INTO HPSTATUS (HPTYPE, HPKEY, HPSTATUS, HPRMK) VALUES ('IDSCANNER', i_LocalIP, 'DocType', i_DocType);
	ELSE
		UPDATE HPSTATUS SET HPRMK = i_DocType, HPCDATE = SYSDATE WHERE HPTYPE = 'IDSCANNER' AND HPKEY = i_LocalIP AND HPSTATUS = 'DocType';
	END IF;

	SELECT COUNT(1) INTO v_Count FROM HPSTATUS WHERE HPTYPE = 'IDSCANNER' AND HPKEY = i_LocalIP AND HPSTATUS = 'DocType';
	IF v_Count = 0 THEN
		INSERT INTO HPSTATUS (HPTYPE, HPKEY, HPSTATUS, HPRMK) VALUES ('IDSCANNER', i_LocalIP, 'DocType', i_DocType);
	ELSE
		UPDATE HPSTATUS SET HPRMK = i_DocType, HPCDATE = SYSDATE WHERE HPTYPE = 'IDSCANNER' AND HPKEY = i_LocalIP AND HPSTATUS = 'DocType';
	END IF;

	SELECT COUNT(1) INTO v_Count FROM HPSTATUS WHERE HPTYPE = 'IDSCANNER' AND HPKEY = i_LocalIP AND HPSTATUS = 'DocID';
	IF v_Count = 0 THEN
		INSERT INTO HPSTATUS (HPTYPE, HPKEY, HPSTATUS, HPRMK) VALUES ('IDSCANNER', i_LocalIP, 'DocID', i_DocID);
	ELSE
		UPDATE HPSTATUS SET HPRMK = i_DocID, HPCDATE = SYSDATE WHERE HPTYPE = 'IDSCANNER' AND HPKEY = i_LocalIP AND HPSTATUS = 'DocID';
	END IF;

	SELECT COUNT(1) INTO v_Count FROM HPSTATUS WHERE HPTYPE = 'IDSCANNER' AND HPKEY = i_LocalIP AND HPSTATUS = 'FirstName';
	IF v_Count = 0 THEN
		INSERT INTO HPSTATUS (HPTYPE, HPKEY, HPSTATUS, HPRMK) VALUES ('IDSCANNER', i_LocalIP, 'FirstName', i_FirstName);
	ELSE
		UPDATE HPSTATUS SET HPRMK = i_FirstName, HPCDATE = SYSDATE WHERE HPTYPE = 'IDSCANNER' AND HPKEY = i_LocalIP AND HPSTATUS = 'FirstName';
	END IF;

	SELECT COUNT(1) INTO v_Count FROM HPSTATUS WHERE HPTYPE = 'IDSCANNER' AND HPKEY = i_LocalIP AND HPSTATUS = 'LastName';
	IF v_Count = 0 THEN
		INSERT INTO HPSTATUS (HPTYPE, HPKEY, HPSTATUS, HPRMK) VALUES ('IDSCANNER', i_LocalIP, 'LastName', i_LastName);
	ELSE
		UPDATE HPSTATUS SET HPRMK = i_LastName, HPCDATE = SYSDATE WHERE HPTYPE = 'IDSCANNER' AND HPKEY = i_LocalIP AND HPSTATUS = 'LastName';
	END IF;

	SELECT COUNT(1) INTO v_Count FROM HPSTATUS WHERE HPTYPE = 'IDSCANNER' AND HPKEY = i_LocalIP AND HPSTATUS = 'Sex';
	IF v_Count = 0 THEN
		INSERT INTO HPSTATUS (HPTYPE, HPKEY, HPSTATUS, HPRMK) VALUES ('IDSCANNER', i_LocalIP, 'Sex', i_Sex);
	ELSE
		UPDATE HPSTATUS SET HPRMK = i_Sex, HPCDATE = SYSDATE WHERE HPTYPE = 'IDSCANNER' AND HPKEY = i_LocalIP AND HPSTATUS = 'Sex';
	END IF;

	SELECT COUNT(1) INTO v_Count FROM HPSTATUS WHERE HPTYPE = 'IDSCANNER' AND HPKEY = i_LocalIP AND HPSTATUS = 'DOB';
	IF v_Count = 0 THEN
		INSERT INTO HPSTATUS (HPTYPE, HPKEY, HPSTATUS, HPRMK) VALUES ('IDSCANNER', i_LocalIP, 'DOB', i_DOB);
	ELSE
		UPDATE HPSTATUS SET HPRMK = i_DOB, HPCDATE = SYSDATE WHERE HPTYPE = 'IDSCANNER' AND HPKEY = i_LocalIP AND HPSTATUS = 'DOB';
	END IF;

	OPEN OUTCUR FOR
		SELECT 1 FROM DUAL;
	RETURN OUTCUR;
EXCEPTION
WHEN OTHERS THEN
	ROLLBACK;
	RETURN OUTCUR;
END NHS_ACT_PATIENT_IDSCANNER;
/
