CREATE OR REPLACE FUNCTION "NHS_LIS_PATALERTAVA" (
	v_PATNO IN VARCHAR2,
	v_USRID IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
BEGIN
	OPEN OUTCUR FOR
		SELECT '', ALTCODE, ALTDESC, ALTID
		FROM ALERT
		WHERE ALTID NOT IN (SELECT ALTID
							FROM PATALTLINK
							WHERE PATNO = v_PATNO
							AND USRID_C IS NULL)
		AND ALTID IN (SELECT DISTINCT R.ALTID
					FROM USRROLE U, ROLALTLINK R
					WHERE U.ROLID = R.ROLID
					AND U.USRID = v_USRID)
--		AND ALERT = -1
		ORDER BY ALTCODE;

		RETURN OUTCUR;
END NHS_LIS_PATALERTAVA;
/
