CREATE OR REPLACE FUNCTION "NHS_ACT_BEDCHGHIS" (
	v_ACTION      IN VARCHAR2,
	v_PRE_BHSID   IN VARCHAR2,
	v_PRE_REGID   IN VARCHAR2,
	v_PRE_PATNO   IN VARCHAR2,
	v_PRE_BEDCODE IN VARCHAR2,
	v_PRE_SDATE   IN VARCHAR2,
	v_PRE_EDATE   IN VARCHAR2,
	v_BHSID       IN VARCHAR2,
	v_REGID       IN VARCHAR2,
	v_PATNO       IN VARCHAR2,
	v_BEDCODE     IN VARCHAR2,
	v_SDATE       IN VARCHAR2,
	v_EDATE       IN VARCHAR2,
	v_USRID       IN VARCHAR2,
	o_ERRMSG      OUT VARCHAR2
)
	RETURN NUMBER
AS
	o_ERRCODE NUMBER;
	v_NOOFREC NUMBER;
BEGIN
	o_ERRCODE := 0;
	o_ERRMSG  := 'OK';

	IF v_ACTION = 'ADD' OR v_ACTION = 'MOD' THEN
		IF v_PRE_BHSID IS NOT NULL THEN
			SELECT COUNT(1) INTO v_NOOFREC FROM BEDHIST WHERE BHSID = v_PRE_BHSID;

			IF v_NOOFREC > 0 THEN
				UPDATE BEDHIST
				SET
--					REGID    = v_PRE_REGID,
--					PATNO    = v_PRE_PATNO,
					BEDCODE  = v_PRE_BEDCODE,
					BHSDATE  = TO_DATE(v_PRE_SDATE, 'DD/MM/YYYY HH24:MI:SS'),
					BHSEDATE = TO_DATE(v_PRE_EDATE, 'DD/MM/YYYY HH24:MI:SS')
--					DHSSTS   = 'N',
--					USRID    = v_USRID
				 WHERE BHSID = v_PRE_BHSID;
			ELSE
				o_ERRCODE := -1;
				o_ERRMSG := 'Fail to update due to record not exist.';
			END IF;
		END IF;

		SELECT COUNT(1) INTO v_NOOFREC FROM BEDHIST WHERE BHSID = v_BHSID;
		IF v_NOOFREC > 0 THEN
			UPDATE BEDHIST
			SET
--				REGID    = v_REGID,
--				PATNO    = v_PATNO,
				BEDCODE  = v_BEDCODE,
				BHSDATE  = TO_DATE(v_SDATE, 'DD/MM/YYYY HH24:MI:SS'),
				BHSEDATE = TO_DATE(v_EDATE, 'DD/MM/YYYY HH24:MI:SS'),
--				DHSSTS   = 'N',
				USRID    = v_USRID
			 WHERE BHSID = v_BHSID;
		ELSE
			SELECT COUNT(1) INTO v_NOOFREC FROM BEDHIST WHERE REGID = v_REGID AND PATNO = v_PATNO AND BHSEDATE IS NULL;
			IF v_NOOFREC = 1 THEN
				UPDATE BEDHIST
				SET
--					REGID    = v_REGID,
--					PATNO    = v_PATNO,
--					BHSDATE  = TO_DATE(v_SDATE, 'DD/MM/YYYY HH24:MI:SS'),
					BHSEDATE = TO_DATE(v_SDATE, 'DD/MM/YYYY HH24:MI:SS')
--					USRID    = v_USRID
				 WHERE REGID = v_REGID
				 AND   PATNO = v_PATNO
				 AND   BHSEDATE IS NULL;
			END IF;

			INSERT INTO BEDHIST
			VALUES (
				SEQ_BEDHIST.NEXTVAL,
				v_REGID,
				v_PATNO,
				v_BEDCODE,
				TO_DATE(v_SDATE, 'DD/MM/YYYY HH24:MI:SS'),
				TO_DATE(v_EDATE, 'DD/MM/YYYY HH24:MI:SS'),
				v_USRID
			);
		END IF;
	ELSIF v_ACTION = 'DEL' THEN
		SELECT COUNT(1) INTO v_NOOFREC FROM BEDHIST WHERE BHSID = v_PRE_BHSID;

		IF v_NOOFREC > 0 THEN
			UPDATE BEDHIST
			SET
--				REGID    = v_PRE_REGID,
--				PATNO    = v_PRE_PATNO,
--				BEDCODE  = v_PRE_BEDCODE,
--				BHSDATE  = TO_DATE(v_PRE_SDATE, 'DD/MM/YYYY HH24:MI:SS'),
				BHSEDATE = TO_DATE(v_PRE_EDATE, 'DD/MM/YYYY HH24:MI:SS')
--				DHSSTS   = 'N',
--				USRID    = v_USRID
			WHERE BHSID = v_PRE_BHSID;
		ELSE
			o_ERRCODE := -1;
			o_ERRMSG := 'Fail to delete due to record not exist.';
		END IF;

		SELECT COUNT(1) INTO v_NOOFREC FROM BEDHIST WHERE BHSID = v_BHSID;

		IF v_NOOFREC > 0 THEN
			DELETE BEDHIST WHERE BHSID = v_BHSID;
		ELSE
			o_ERRCODE := -1;
			o_ERRMSG := 'Fail to delete due to record not exist.';
		END IF;
	END IF;
	RETURN o_ERRCODE;
EXCEPTION
WHEN OTHERS THEN
	ROLLBACK;
  	o_ERRCODE := -1;
	o_errMsg := 'Bed Change cannot save.';
	DBMS_OUTPUT.PUT_LINE('An ERROR was encountered - '||SQLCODE||' -ERROR- '||SQLERRM);
	RETURN o_errcode;
END NHS_ACT_BEDCHGHIS;
/
