CREATE OR REPLACE FUNCTION "NHS_LIS_STATUSVIEWPS"(V_REGID IN VARCHAR2)
  RETURN TYPES.CURSOR_TYPE AS
  OUTCUR TYPES.CURSOR_TYPE;
BEGIN
  OPEN OUTCUR FOR
    SELECT TO_CHAR(BHSDATE, 'DD/MM/YYYY'),
           TO_CHAR(BHSEDATE, 'DD/MM/YYYY'),
           BEDCODE
      FROM BEDHIST
     WHERE REGID = V_REGID
     ORDER BY BHSDATE DESC;
  RETURN OUTCUR;
END NHS_LIS_STATUSVIEWPS;
/
