create or replace
FUNCTION "NHS_LIS_REGPRINTCALLCHART" (
	i_SGNAME                IN VARCHAR2,
	i_PATNUM                IN VARCHAR2,
	i_CHARTLABELPATLOCATION IN VARCHAR2,
	i_STECODE               IN VARCHAR2,
	i_DOCCODE               IN VARCHAR2,
	i_USRID                 IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR   TYPES.CURSOR_TYPE;
	v_PATNOF VARCHAR2(50);
BEGIN
	SELECT LPAD(i_PATNUM, 10, ' ') INTO v_PATNOF FROM DUAL;
	OPEN OUTCUR FOR
		SELECT i_SGNAME AS BKGPNAME,
			i_PATNUM AS PATNO,
			SUBSTR(v_PATNOF, 1, 2) AS PATNOA,
			SUBSTR(v_PATNOF, 3, 2) AS PATNOB,
			SUBSTR(v_PATNOF, 5, 2) AS PATNOC,
			SUBSTR(v_PATNOF, 7, 2) AS PATNOD,
			SUBSTR(v_PATNOF, 9, 2) AS PATNOE,
			D.DOCFNAME || ' ' || D.DOCGNAME AS DOCNAME,
			D.DOCCODE,
			i_CHARTLABELPATLOCATION AS SPCNAME,
			TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI') AS BKGSDATE2,
			TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI') AS BKGSDATE,
			S.STENAME,
			s.stelogo,
      		GET_ALERT_CODE(i_PATNUM, i_USRID),
			(SELECT DECODE(PATSTAFF, -1, '(S)', '') FROM PATIENT WHERE PATNO = i_PATNUM),
			i_USRID as userID
		FROM  DOCTOR D, SPEC SP, SITE S
		WHERE D.SPCCODE = SP.SPCCODE
		AND   S.STECODE = i_STECODE
		AND   D.DOCCODE = i_DOCCODE;
	RETURN OUTCUR;
END NHS_LIS_REGPRINTCALLCHART;
/