CREATE OR REPLACE FUNCTION NHS_LIS_DOCTOR_INSTRUCTION (
	v_DocCode VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
BEGIN
	OPEN OUTCUR FOR
	SELECT Docfname, Docgname, DayInstruction, InpInstruction, OupInstruction, PayInstruction
	FROM   Doctor
	WHERE  DocCode = v_DocCode;

	RETURN OUTCUR;
END NHS_LIS_DOCTOR_INSTRUCTION;
/
