CREATE OR REPLACE FUNCTION "NHS_LIS_DOC_PRIVILEGE"(V_DOCCODE IN VARCHAR2)
  RETURN TYPES.CURSOR_TYPE AS
  OUTCUR TYPES.CURSOR_TYPE;
BEGIN
  OPEN OUTCUR FOR
    SELECT P.PRINAME
      FROM DOCPRILINK D, PRIVILEGE P
     WHERE D.PRICODE = P.PRICODE
       AND V_DOCCODE = D.DOCCODE
     ORDER BY P.PRINAME;
  RETURN OUTCUR;
END NHS_LIS_DOC_PRIVILEGE;
/
