CREATE OR REPLACE FUNCTION "NHS_GET_PATIENT_IDSCANNER" (
	i_LocalIP IN Bed.BedCode%TYPE
)
	RETURN Types.cursor_type
AS
	OUTCUR TYPES.CURSOR_TYPE;
	v_DocType VARCHAR2(200);
	v_DocID VARCHAR2(200);
	v_FirstName VARCHAR2(200);
	v_LastName VARCHAR2(200);
	v_Sex VARCHAR2(200);
	v_DOB VARCHAR2(200);
	v_Count NUMBER;
BEGIN
	SELECT COUNT(1) INTO v_Count FROM HPSTATUS WHERE HPTYPE = 'IDSCANNER' AND HPKEY = i_LocalIP AND HPCDATE > SYSDATE - 10/(24*60);
	IF v_Count > 0 THEN
		SELECT HPRMK INTO v_DocType FROM HPSTATUS WHERE HPTYPE = 'IDSCANNER' AND HPKEY = i_LocalIP AND HPSTATUS = 'DocType';
		SELECT HPRMK INTO v_DocID FROM HPSTATUS WHERE HPTYPE = 'IDSCANNER' AND HPKEY = i_LocalIP AND HPSTATUS = 'DocID';
		SELECT HPRMK INTO v_FirstName FROM HPSTATUS WHERE HPTYPE = 'IDSCANNER' AND HPKEY = i_LocalIP AND HPSTATUS = 'FirstName';
		SELECT HPRMK INTO v_LastName FROM HPSTATUS WHERE HPTYPE = 'IDSCANNER' AND HPKEY = i_LocalIP AND HPSTATUS = 'LastName';
		SELECT HPRMK INTO v_Sex FROM HPSTATUS WHERE HPTYPE = 'IDSCANNER' AND HPKEY = i_LocalIP AND HPSTATUS = 'Sex';
		SELECT HPRMK INTO v_DOB FROM HPSTATUS WHERE HPTYPE = 'IDSCANNER' AND HPKEY = i_LocalIP AND HPSTATUS = 'DOB';

		IF v_DocType = 'Passport' THEN
			v_DocType := 'OP';
		ELSIF v_DocType = 'Identification Card' THEN
			v_DocType := 'ID';
		ELSIF v_DocType = 'BirthCertificate' THEN
			v_DocType := 'BC';
		ELSE
			v_DocType := 'NA';
		END IF;

		OPEN OUTCUR FOR
			SELECT v_DocType, replace(replace(v_DocID,'(', ''),')', ''), v_FirstName, v_LastName, v_Sex, v_DOB FROM dual;
	END IF;
	RETURN OUTCUR;
 END NHS_GET_PATIENT_IDSCANNER;
/
