CREATE OR REPLACE FUNCTION "NHS_LIS_EHR_GETEHRNOBYIDS" (
	V_MODE		IN VARCHAR2,	
	V_HKID		IN VARCHAR2,
	V_DOCTYPE	IN VARCHAR2,
	V_DOCNO		IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
	SQLSTR VARCHAR2(500);
	V_ISHKID BOOLEAN;
BEGIN
	IF V_HKID IS NOT NULL THEN
		V_ISHKID := TRUE;
	ELSE
		V_ISHKID := FALSE;
	END IF;
	
	SQLSTR := 'SELECT EHRNO FROM EHR_PMIHIST WHERE EHRNO IS NOT NULL ';
	IF V_ISHKID THEN
		SQLSTR := SQLSTR || 'AND EHRHKID LIKE ''%' || V_HKID || '''';
	ELSE
		SQLSTR := SQLSTR || 'AND EHRDOCTYPE = ''' || V_DOCTYPE || ''' AND EHRDOCNO = ''' || V_DOCNO || '''';
	END IF;
	
	IF V_MODE = 'LATEST' THEN
		SQLSTR := SQLSTR || ' ORDER BY CREATEDATE DESC';
	ELSE
		SQLSTR := SQLSTR || ' ORDER BY EHRNO';
	END IF;

	OPEN OUTCUR FOR SQLSTR;
	RETURN OUTCUR;
END NHS_LIS_EHR_GETEHRNOBYIDS;
/
