create or replace FUNCTION NHS_LIS_BOOKINGDIAG (
	v_PATNO patient.patno%TYPE,
	v_PBPNO BEDPREBOK.PBPID%TYPE,
	v_BKGID BOOKING.BKGID%TYPE
)
	RETURN Types.cursor_type
AS
	OUTCUR TYPES.CURSOR_TYPE;
	STS_NORMAL VARCHAR2(1) := 'N';
	STS_CONFIRMED VARCHAR2(1) := 'F';
BEGIN
	OPEN outcur FOR
		SELECT 'O', S.DOCCODE, D.DOCFNAME || ' ' || D.DOCGNAME, TO_CHAR(B.bkgsdate, 'dd/Mon/yyyy HH12:MIAM', 'NLS_DATE_LANGUAGE=AMERICAN')
		FROM Booking B
		INNER JOIN Schedule S ON B.SCHID = S.SCHID
		INNER JOIN Doctor D ON S.DOCCODE = D.DOCCODE
		WHERE B.patno = v_PATNO
		AND   B.bkgsts = STS_NORMAL
		AND   B.BKGSDATE       >= TRUNC(sysdate)
		AND   TRUNC(B.BKGSDATE) <= ADD_MONTHS(TRUNC(sysdate), 3)
		AND  (v_BKGID IS NULL OR B.BKGID <> v_BKGID)
		UNION
		SELECT 'I', BP.DOCCODE, D.DOCFNAME || ' ' || D.DOCGNAME, TO_CHAR(BP.bpbhdate, 'dd/Mon/yyyy HH12:MIAM', 'NLS_DATE_LANGUAGE=AMERICAN')
		FROM BEDPREBOK BP
		INNER JOIN Doctor D ON BP.DOCCODE = D.DOCCODE
		WHERE BP.patno = v_PATNO
		AND   BP.bpbsts = STS_NORMAL
		AND   BP.BPBHDATE        >= TRUNC(sysdate)
		AND   TRUNC(BP.BPBHDATE) <= ADD_MONTHS(TRUNC(sysdate), 1)
		AND  (v_PBPNO IS NULL OR BP.PBPID <> v_PBPNO)
		UNION
		SELECT 'CP', DA.DOCCODE_R, D.DOCFNAME || ' ' || D.DOCGNAME, TO_CHAR(DA.DEPTAOSDATE, 'dd/Mon/yyyy HH12:MIAM', 'NLS_DATE_LANGUAGE=AMERICAN')
		FROM DEPT_APP DA
		INNER JOIN Doctor D ON DA.DOCCODE_R = D.DOCCODE
		WHERE DA.patno = v_PATNO
		AND   DA.DEPTASTS = STS_NORMAL
		AND   DA.DEPTAOSDATE        >= TRUNC(sysdate)
		AND   TRUNC(DA.DEPTAOSDATE) <= TRUNC(sysdate) + 3;

	RETURN OUTCUR;
END NHS_LIS_BOOKINGDIAG;
/
