CREATE OR REPLACE FUNCTION "NHS_LIS_EHR_PMIHIST" (
	V_MODE	   IN VARCHAR2,	
	v_PATNO	   IN VARCHAR2
)
	RETURN Types.cursor_type
AS
	OUTCUR Types.cursor_type;
	sqlStr VARCHAR2(3000);
BEGIN

	OPEN OUTCUR FOR 
		SELECT
		  PATNO,
		  EHRMSGNO,
		  EHREVENTCODE,
		  TO_CHAR(EHRENROLDATE, 'DD/MM/YYYY HH24:MI') EHRENROLDATE,
		  EHRNO,
		  TO_CHAR(EHRSDATE, 'DD/MM/YYYY HH24:MI') EHRSDATE,
		  TO_CHAR(EHREDATE, 'DD/MM/YYYY HH24:MI') EHREDATE,
		  TO_CHAR(CREATEDATE, 'DD/MM/YYYY HH24:MI') CREATEDATE_STR,
		  NVL((SELECT USRNAME FROM USR WHERE USRID = CREATEBY), CREATEBY) CREATEBY,
		  EHRFNAME,
		  EHRGNAME,
		  TO_CHAR(EHRDOB, 'DD/MM/YYYY') EHRDOB,
		  EHREDOBIND,
		  EHRSEX,
		  EHRHKID,
		  EHRDOCTYPE,
		  (SELECT EHRDESC || ' (' || EHRCODE || ')' FROM EHR_PMIDOCTYPE WHERE EHRCODE = EHRDOCTYPE) DOCTYPE,
		  EHRDOCNO,
		  TO_CHAR(EHRDEATHDATE, 'DD/MM/YYYY HH24:MI') EHRDEATHDATE
		FROM EHR_PMIHIST
		WHERE PATNO = v_PATNO
		 OR PATNO IN (SELECT DISTINCT FM_PATNO FROM PATMERCHT WHERE TO_PATNO = v_PATNO)
		 OR PATNO IN (SELECT DISTINCT TO_PATNO FROM PATMERCHT WHERE FM_PATNO = v_PATNO)
		ORDER BY CREATEDATE DESC;
	RETURN OUTCUR;
END NHS_LIS_EHR_PMIHIST;
/
