CREATE OR REPLACE FUNCTION "NHS_LIS_PATIENT_ALERT"(
	v_PATNO VARCHAR2,
	v_userid VARCHAR2 DEFAULT GET_CURRENT_STECODE
)
	RETURN Types.cursor_type
AS
	outcur types.cursor_type;
BEGIN
	OPEN outcur FOR
	SELECT A.ALTCODE, A.ALTDESC, A.PCYCODE, A.ARCCODE, 
	DECODE(LENGTH(A.PCYCODE), 0, 0, DECODE(LENGTH(A.ARCCODE), 0, 0, null,0,1))
	FROM   PATALTLINK P, ALERT A
	WHERE  P.ALTID = A.ALTID
	AND    P.PATNO = v_PATNO
	AND    P.USRID_C IS NULL
	AND    P.ALTID IN (
		SELECT DISTINCT R.ALTID
		FROM   USRROLE U, ROLALTLINK R
		WHERE  U.ROLID = R.ROLID
		AND    U.USRID = v_userid
	)
	AND    ROWNUM < 100
	ORDER  BY A.ALTCODE;

	RETURN OUTCUR;
END NHS_LIS_PATIENT_ALERT;
/
