CREATE OR REPLACE FUNCTION "NHS_GET_PATIENT" (
	v_PATNO IN VARCHAR2
)
	RETURN Types.cursor_type
AS
BEGIN
	RETURN NHS_LIS_PATIENT('GET', v_PATNO, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
END NHS_GET_PATIENT;
/
