CREATE OR REPLACE FUNCTION "NHS_ACT_PATIENT_CONSENT" (
	i_Action       IN VARCHAR2,
	i_PatNo        IN VARCHAR2,
	i_StartDate1   IN VARCHAR2,
	i_EndDate1     IN VARCHAR2,
	i_ArCode1      IN VARCHAR2,
	i_Remark1      IN VARCHAR2,
	i_StartDate2   IN VARCHAR2,
	i_EndDate2     IN VARCHAR2,
	i_ArCode2      IN VARCHAR2,
	i_Remark2      IN VARCHAR2,
	i_StartDate3   IN VARCHAR2,
	i_EndDate3     IN VARCHAR2,
	i_ArCode3      IN VARCHAR2,
	i_Remark3      IN VARCHAR2,
	i_InsuranceRmk IN VARCHAR2,
	i_UsrID        IN VARCHAR2,
	o_errmsg       OUT VARCHAR2
)
	RETURN VARCHAR2
AS
	v_NoOfRec NUMBER;
	v_CONSENTSDATE1 Patient_Extra.CONSENTSDATE1%TYPE;
	v_CONSENTEDATE1 Patient_Extra.CONSENTEDATE1%TYPE;
	v_CONSENTSDATE2 Patient_Extra.CONSENTSDATE2%TYPE;
	v_CONSENTEDATE2 Patient_Extra.CONSENTEDATE2%TYPE;
	v_CONSENTSDATE3 Patient_Extra.CONSENTSDATE3%TYPE;
	v_CONSENTEDATE3 Patient_Extra.CONSENTEDATE3%TYPE;

	v_StartDate1 Patient_Extra.CONSENTSDATE1%TYPE;
	v_EndDate1 Patient_Extra.CONSENTEDATE1%TYPE;
	v_ArCode1 Patient_Extra.CONSENTARCCODE1%TYPE;
	v_Remark1 Patient_Extra.CONSENTRMK1%TYPE;
	v_CONSENTUSER1 Patient_Extra.CONSENTUSER1%TYPE;
	v_CONSENTDATE1 Patient_Extra.CONSENTDATE1%TYPE;
	v_StartDate2 Patient_Extra.CONSENTSDATE2%TYPE;
	v_EndDate2 Patient_Extra.CONSENTEDATE2%TYPE;
	v_ArCode2 Patient_Extra.CONSENTARCCODE2%TYPE;
	v_Remark2 Patient_Extra.CONSENTRMK2%TYPE;
	v_CONSENTUSER2 Patient_Extra.CONSENTUSER2%TYPE;
	v_CONSENTDATE2 Patient_Extra.CONSENTDATE2%TYPE;
	v_StartDate3 Patient_Extra.CONSENTSDATE3%TYPE;
	v_EndDate3 Patient_Extra.CONSENTEDATE3%TYPE;
	v_ArCode3 Patient_Extra.CONSENTARCCODE3%TYPE;
	v_Remark3 Patient_Extra.CONSENTRMK3%TYPE;
	v_CONSENTUSER3 Patient_Extra.CONSENTUSER3%TYPE;
	v_CONSENTDATE3 Patient_Extra.CONSENTDATE3%TYPE;

	o_errCode NUMBER := 0;
BEGIN
	o_errmsg := 'OK';
	v_CONSENTSDATE1 := TO_DATE(i_StartDate1, 'DD/MM/YYYY');
	v_CONSENTEDATE1 := TO_DATE(i_EndDate1, 'DD/MM/YYYY');
	v_CONSENTSDATE2 := TO_DATE(i_StartDate2, 'DD/MM/YYYY');
	v_CONSENTEDATE2 := TO_DATE(i_EndDate2, 'DD/MM/YYYY');
	v_CONSENTSDATE3 := TO_DATE(i_StartDate3, 'DD/MM/YYYY');
	v_CONSENTEDATE3 := TO_DATE(i_EndDate3, 'DD/MM/YYYY');

	--update extra
	SELECT COUNT(1) INTO v_NoOfRec FROM Patient_Extra WHERE PATNO = i_PatNo;
	IF v_NoOfRec = 0 THEN
		IF i_StartDate1 IS NOT NULL OR i_EndDate1 IS NOT NULL OR i_ArCode1 IS NOT NULL OR i_Remark1 IS NOT NULL THEN
			v_CONSENTUSER1 := i_UsrID;
			v_CONSENTDATE1 := SYSDATE;
		END IF;

		IF i_StartDate2 IS NOT NULL OR i_EndDate2 IS NOT NULL OR i_ArCode2 IS NOT NULL OR i_Remark2 IS NOT NULL THEN
			v_CONSENTUSER2 := i_UsrID;
			v_CONSENTDATE2 := SYSDATE;
		END IF;

		IF i_StartDate3 IS NOT NULL OR i_EndDate3 IS NOT NULL OR i_ArCode3 IS NOT NULL OR i_Remark3 IS NOT NULL THEN
			v_CONSENTUSER3 := i_UsrID;
			v_CONSENTDATE3 := SYSDATE;
		END IF;

		INSERT INTO Patient_Extra (
			PATNO,
			CONSENTARCCODE1,
			CONSENTRMK1,
			CONSENTSDATE1,
			CONSENTEDATE1,
			CONSENTUSER1,
			CONSENTDATE1,
			CONSENTARCCODE2,
			CONSENTRMK2,
			CONSENTSDATE2,
			CONSENTEDATE2,
			CONSENTUSER2,
			CONSENTDATE2,
			CONSENTARCCODE3,
			CONSENTRMK3,
			CONSENTSDATE3,
			CONSENTEDATE3,
			CONSENTUSER3,
			CONSENTDATE3,
			INSUANCERMK
		) VALUES (
			i_PatNo,
			i_ArCode1,
			i_Remark1,
			v_CONSENTSDATE1,
			v_CONSENTEDATE1,
			v_CONSENTUSER1,
			v_CONSENTDATE1,
			i_ArCode2,
			i_Remark2,
			v_CONSENTSDATE2,
			v_CONSENTEDATE2,
			v_CONSENTUSER2,
			v_CONSENTDATE2,
			i_ArCode3,
			i_Remark3,
			v_CONSENTSDATE3,
			v_CONSENTEDATE3,
			v_CONSENTUSER3,
			v_CONSENTDATE3,
			i_InsuranceRmk
		);
	ELSE
		SELECT CONSENTSDATE1, CONSENTEDATE1, CONSENTARCCODE1, CONSENTRMK1, CONSENTUSER1, CONSENTDATE1,
			CONSENTSDATE2, CONSENTEDATE2, CONSENTARCCODE2, CONSENTRMK2, CONSENTUSER2, CONSENTDATE2,
			CONSENTSDATE3, CONSENTEDATE3, CONSENTARCCODE3, CONSENTRMK3, CONSENTUSER3, CONSENTDATE3
		INTO  v_StartDate1, v_EndDate1, v_ArCode1, v_Remark1, v_CONSENTUSER1, v_CONSENTDATE1,
			v_StartDate2, v_EndDate2, v_ArCode2, v_Remark2, v_CONSENTUSER2, v_CONSENTDATE2,
			v_StartDate3, v_EndDate3, v_ArCode3, v_Remark3, v_CONSENTUSER3, v_CONSENTDATE3
		FROM  Patient_Extra
		WHERE PATNO = i_PatNo;

		IF ((i_StartDate1 IS NULL AND v_StartDate1 IS NOT NULL) OR (i_StartDate1 IS NOT NULL AND v_StartDate1 IS NULL) OR v_CONSENTSDATE1 != v_StartDate1)
				OR ((i_EndDate1 IS NULL AND v_EndDate1 IS NOT NULL) OR (i_EndDate1 IS NOT NULL AND v_EndDate1 IS NULL) OR v_CONSENTEDATE1 != v_EndDate1)
				OR ((i_ArCode1 IS NULL AND v_ArCode1 IS NOT NULL) OR (i_ArCode1 IS NOT NULL AND v_ArCode1 IS NULL) OR i_ArCode1 != v_ArCode1)
				OR ((i_Remark1 IS NULL AND v_Remark1 IS NOT NULL) OR (i_Remark1 IS NOT NULL AND v_Remark1 IS NULL) OR i_Remark1 != v_Remark1) THEN
			v_CONSENTUSER1 := i_UsrID;
			v_CONSENTDATE1 := SYSDATE;
		END IF;

		IF ((i_StartDate2 IS NULL AND v_StartDate2 IS NOT NULL) OR (i_StartDate2 IS NOT NULL AND v_StartDate2 IS NULL) OR v_CONSENTSDATE2 != v_StartDate2)
				OR ((i_EndDate2 IS NULL AND v_EndDate2 IS NOT NULL) OR (i_EndDate2 IS NOT NULL AND v_EndDate2 IS NULL) OR v_CONSENTEDATE2 != v_EndDate2)
				OR ((i_ArCode2 IS NULL AND v_ArCode2 IS NOT NULL) OR (i_ArCode2 IS NOT NULL AND v_ArCode2 IS NULL) OR i_ArCode2 != v_ArCode2)
				OR ((i_Remark2 IS NULL AND v_Remark2 IS NOT NULL) OR (i_Remark2 IS NOT NULL AND v_Remark2 IS NULL) OR i_Remark2 != v_Remark2) THEN
			v_CONSENTUSER2 := i_UsrID;
			v_CONSENTDATE2 := SYSDATE;
		END IF;

		IF ((i_StartDate3 IS NULL AND v_StartDate3 IS NOT NULL) OR (i_StartDate3 IS NOT NULL AND v_StartDate3 IS NULL) OR v_CONSENTSDATE3 != v_StartDate3)
				OR ((i_EndDate3 IS NULL AND v_EndDate3 IS NOT NULL) OR (i_EndDate3 IS NOT NULL AND v_EndDate3 IS NULL) OR v_CONSENTEDATE3 != v_EndDate3)
				OR ((i_ArCode3 IS NULL AND v_ArCode3 IS NOT NULL) OR (i_ArCode3 IS NOT NULL AND v_ArCode3 IS NULL) OR i_ArCode3 != v_ArCode3)
				OR ((i_Remark3 IS NULL AND v_Remark3 IS NOT NULL) OR (i_Remark3 IS NOT NULL AND v_Remark3 IS NULL) OR i_Remark3 != v_Remark3) THEN
			v_CONSENTUSER3 := i_UsrID;
			v_CONSENTDATE3 := SYSDATE;
		END IF;

		UPDATE Patient_Extra
		SET
			CONSENTARCCODE1 = i_ArCode1,
			CONSENTRMK1 = i_Remark1,
			CONSENTSDATE1 = v_CONSENTSDATE1,
			CONSENTEDATE1 = v_CONSENTEDATE1,
			CONSENTUSER1 = v_CONSENTUSER1,
			CONSENTDATE1 = v_CONSENTDATE1,
			CONSENTARCCODE2 = i_ArCode2,
			CONSENTRMK2 = i_Remark2,
			CONSENTSDATE2 = v_CONSENTSDATE2,
			CONSENTEDATE2 = v_CONSENTEDATE2,
			CONSENTUSER2 = v_CONSENTUSER2,
			CONSENTDATE2 = v_CONSENTDATE2,
			CONSENTARCCODE3 = i_ArCode3,
			CONSENTRMK3 = i_Remark3,
			CONSENTSDATE3 = v_CONSENTSDATE3,
			CONSENTEDATE3 = v_CONSENTEDATE3,
			CONSENTUSER3 = v_CONSENTUSER3,
			CONSENTDATE3 = v_CONSENTDATE3,
			INSUANCERMK = i_InsuranceRmk
		WHERE PATNO = i_PatNo;
	END IF;

	RETURN o_errCode;
EXCEPTION
WHEN OTHERS THEN
	o_errcode := -1;
	o_errmsg:= o_errmsg || SQLERRM;
	ROLLBACK;
	RETURN o_errCode;
END NHS_ACT_PATIENT_CONSENT;
/
