CREATE OR REPLACE FUNCTION NHS_LIS_ARCODE (
	v_ARCCODE VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
	SQLSTR VARCHAR2(3000);
BEGIN
	OPEN OUTCUR FOR
	SELECT
		ArcCode, 
		ArcName,
		ARLMTAMT, 
		TO_CHAR(CVREDATE, 'dd/MM/yyyy'), 
		COPAYTYP, 
		COPAYAMT,
		FURGRTAMT, 
		TO_CHAR(FURGRTDATE, 'dd/MM/yyyy'),
		ITMTYPED, 
		ITMTYPEH, 
		ITMTYPES, 
		ITMTYPEO,
		TO_CHAR(NCTRSDATE, 'dd/MM/yyyy'), 
		TO_CHAR(NCTREDATE, 'dd/MM/yyyy'),
		PRINT_MRRPT
	FROM ARCODE
	WHERE UPPER(ARCCODE) = UPPER(v_ARCCODE);

	RETURN OUTCUR;
END NHS_LIS_ARCODE;
/
