CREATE OR REPLACE FUNCTION "NHS_ACT_BEDPREBOKDEL"(
	V_ACTION IN VARCHAR2,
	V_PBPID  IN VARCHAR2,
	V_USRID  IN VARCHAR2,
	O_ERRMSG OUT VARCHAR2
)
	RETURN NUMBER
AS
	O_ERRCODE NUMBER;
BEGIN
	O_ERRCODE := 0;
	O_ERRMSG  := 'OK';

	IF V_ACTION = 'DEL' THEN
		UPDATE BEDPREBOK
		SET    BPBSTS = 'D', EDITUSER = V_USRID, EDITDATE = SYSDATE
		WHERE  PBPID = V_PBPID
		AND    BPBSTS = 'N';

	    UPDATE OT_APP
	    set    PBPID = null
	    WHERE  PBPID = V_PBPID
	    AND    otasts = 'N';
	END IF;

	RETURN O_ERRCODE;
EXCEPTION
WHEN OTHERS THEN
	ROLLBACK;
	dbms_output.put_line('An ERROR was encountered - '||SQLCODE||' -ERROR- '||SQLERRM);

	RETURN -1;
END NHS_ACT_BEDPREBOKDEL;
/
