create or replace FUNCTION "NHS_LIS_BEDPREBOK" (
	v_PBPID IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
	v_ACTID VARCHAR2(22);
	v_ACTCODE ARCARDTYPE.ACTCODE%TYPE;
	v_BE FIN_EST_HOSP.OSB_BE%TYPE;
	v_Festid FIN_EST_HOSP.FESTID%Type;
	v_Count NUMBER;
BEGIN
	-- Get Slip Misc
	SELECT COUNT(1) INTO v_Count FROM BEDPREBOK_EXTRA WHERE PBPID = v_PBPID;
	IF v_COUNT = 1 THEN
		SELECT ACTID INTO v_ACTID
		FROM   BEDPREBOK_EXTRA
		WHERE  PBPID = v_PBPID;
	END IF;

	IF v_ACTID IS NOT NULL THEN
		SELECT DECODE(ACT.ActActive, -1, ACT.Actcode, NULL) INTO v_ACTCODE
		FROM Arcardtype ACT
		WHERE ACT.ACTID = v_ACTID;
	END IF;

	SELECT COUNT(1) INTO v_Count FROM Fin_Est_Hosp WHERE PBPID = v_PBPID;
	IF v_COUNT = 1 THEN
		SELECT Osb_Be, FESTID INTO v_BE, v_Festid
		FROM Fin_Est_Hosp Fe
		WHERE Fe.Pbpid = V_Pbpid;
	END IF;

	OPEN OUTCUR FOR
		SELECT B.PBPID,
			B.DOCCODE,
			TO_CHAR(B.BPBODATE, 'DD/MM/YYYY HH24:MI:SS'),
			TO_CHAR(B.BPBHDATE, 'DD/MM/YYYY HH24:MI:SS'),
			B.USRID,
			B.BPBSTS,
			B.STECODE,
			B.PATNO,
			B.BPBPNAME,
			B.BPBCNAME,
			B.ACMCODE,
			B.WRDCODE,
			B.BPBRMK,
			B.OTAID,
			B.ARCCODE,
			B.COPAYTYP,
			B.COPAYAMT,
			B.POLICY,
			TO_CHAR(B.CVREDATE, 'DD/MM/YYYY'),
			B.ARLMTAMT,
			B.FURGRTAMT,
			TO_CHAR(B.FURGRTDATE,'DD/MM/YYYY'),
			B.ISDOCTOR,
			B.ISSPECIAL,
			B.ISHOSPITAL,
			B.ISOTHER,
			B.VOUCHER,
			B.PATFNAME,
			B.PATGNAME,
			B.ISMAINLAND,
			B.FORDELIVERY,
			B.PATKHTEL,
			B.PATPAGER,
			B.PATIDNO,
			B.BPBTYPE,
			B.BPBNO,
			B.CABLABRMK,
			B.BEDCODE,
			TO_CHAR(B.BEDTIME, 'DD/MM/YYYY HH24:MI'),
			B.SEX,
			B.SLPNO,
			B.EDITUSER,
			TO_CHAR(B.EDITDATE, 'DD/MM/YYYY HH24:MI'),
			B.ISREFUSED,
			B.REFUSEREASON,
			(SELECT USRNAME FROM USR WHERE USRID = B.REFUSEDUSERID) REFUSEDUSERID,
			TO_CHAR(B.REFUSEDDATE, 'DD/MM/YYYY HH24:MI'),
			(SELECT USRNAME FROM USR WHERE USRID = B.ACTIVATEDUSERID) ACTIVATEDUSERID,
			TO_CHAR(B.ACTIVATEDDATE, 'DD/MM/YYYY HH24:MI'),
			B.ESTSTAYLEN,
			B.PATDOCTYPE,
			B.HUSDOCNO,
			B.HUSDOCTYPE,
			B.HUSGNAME,
			B.HUSFNAME,
			B.SMSSENTDT,
			B.EMAILSENTDT,
			B.FA_PATNO,
			B.FA_HKIC,
			B.FA_CNAME,
			TO_CHAR(B.FA_DOB,'DD/MM/YYYY'),
			B.FA_TEL,
			B.FA_HKIDHOLDER,
			B.FA_RESIDENCE,
			DECODE(B.FA_BIRTHEXACTFLAG, '-1', 'Y', '0', 'N'),
			B.FA_INFOSOURCE,
			TO_CHAR(B.ANTCHKDT1,'DD/MM/YYYY'),
			TO_CHAR(B.ANTCHKDT2,'DD/MM/YYYY'),
			TO_CHAR(B.ANTCHKDT3,'DD/MM/YYYY'),
			TO_CHAR(B.ANTCHKDT4,'DD/MM/YYYY'),
			TO_CHAR(B.ANTCHKDT5,'DD/MM/YYYY'),
			TO_CHAR(B.ANTCHKDT6,'DD/MM/YYYY'),
			TO_CHAR(B.ANTCHKDT7,'DD/MM/YYYY'),
			TO_CHAR(B.ANTCHKDT8,'DD/MM/YYYY'),
			TO_CHAR(B.ANTCHKDT9,'DD/MM/YYYY'),
			TO_CHAR(B.ANTCHKDT10,'DD/MM/YYYY'),
			U1.USRID,
			U2.USRID,
			B.OTREMARK,
			TO_CHAR(B.BPBEDATE, 'DD/MM/YYYY HH24:MI:SS'),
			BE.ACTID, v_ACTCODE,
			AR.Arcname,
			BE.PBMID,
			PBSID,
			PBSNO,
			ISRECLG,
			ARACMCODE,
			DECODE(B.STECODE,'HKAH',DECODE(BE.BPBREGTYPE,'D',(SELECT TO_CHAR(OTA.OTABDATE,'DD/MM/YYYY') FROM OT_APP OTA WHERE B.OTAID=OTA.OTAID),BE.PBPKGCODE),BE.PBPKGCODE),
			ESTGIVN,
			COPAYAMTACT,
			v_Festid,
			v_BE,
			BE.INSPREAUTHNO
		FROM BEDPREBOK B
		LEFT JOIN BEDPREBOK_EXTRA BE ON B.PBPID = BE.PBPID
		LEFT JOIN USR U1 ON B.REFUSEDUSERID = U1.USRID
		LEFT JOIN USR U2 ON B.ACTIVATEDUSERID = U2.USRID
		LEFT JOIN ARCODE AR ON B.ARCCODE = AR.ARCCODE
		WHERE B.PBPID = v_PBPID;

	RETURN OUTCUR;
END NHS_LIS_BEDPREBOK;
/