create or replace
FUNCTION NHS_GET_MEDRECNEXTVOL_REG (
V_PATNO IN VARCHAR2
) RETURN TYPES.CURSOR_TYPE AS
  OUTCUR TYPES.CURSOR_TYPE;
  NEWVOL VARCHAR2(8);
   TYPE rt IS record (
    PARCDE VARCHAR2(10),
    PARAM1 varchar2(50),
    PARAM2 varchar2(50),
    PARDESC VARCHAR2(30)
  );
  rtnType rt;
   rtnCursor TYPES.CURSOR_TYPE;
   MEDRECNEWVOLVOLUMENO NUMBER := 7;

BEGIN
  SELECT MAX(MRHVOLLAB) + 1
    INTO NEWVOL
    FROM MEDRECHDR
   WHERE MRHSTS <> 'P'
     AND PATNO = V_PATNO;

  IF NEWVOL IS NULL THEN
    --NEWVOL := '1';
    rtnCursor := NHS_GET_MEDRECDEFSET(MEDRECNEWVOLVOLUMENO);
      LOOP
        FETCH rtnCursor INTO rtnType ;
        EXIT WHEN rtnCursor%NOTFOUND;
      END LOOP;
      NEWVOL := RTNTYPE.PARAM1;
  END IF;
  NEWVOL := SUBSTR('00000'||NEWVOL,-2,2);

  OPEN OUTCUR FOR
    SELECT NEWVOL FROM DUAL;
  RETURN OUTCUR;
END NHS_GET_MEDRECNEXTVOL_REG;
/
