CREATE OR REPLACE FUNCTION "NHS_GET_PREBOOKING"(V_EDC    IN VARCHAR2)
  RETURN TYPES.CURSOR_TYPE AS
  V_EDCDATE  DATE;
  V_WARDCODE VARCHAR2(10);
  V_maxMPreBok VARCHAR2(50);
  V_maxDPreBok VARCHAR2(50);
  V_curMPreBok Integer;
  V_curDPreBok Integer;
  OUTCUR     TYPES.CURSOR_TYPE;
BEGIN
  SELECT TO_DATE(V_EDC, 'DD/MM/YYYY') INTO V_EDCDATE FROM DUAL;
  SELECT PARAM1 INTO V_WARDCODE FROM SYSPARAM WHERE PARCDE = 'obwardcode' AND ROWNUM = 1;
  SELECT PARAM1 INTO V_maxMPreBok FROM SYSPARAM WHERE PARCDE = 'maxmprebok' AND ROWNUM = 1;
  SELECT PARAM1 INTO V_maxDPreBok FROM SYSPARAM WHERE PARCDE = 'maxdprebok' AND ROWNUM = 1;

  SELECT COUNT(1) INTO V_curMPreBok
    FROM BEDPREBOK
   WHERE TO_CHAR(BPBHDATE, 'YYYYMM') = TO_CHAR(V_EDCDATE, 'YYYYMM')
     AND WRDCODE = V_WARDCODE
     AND BPBSTS IN ('F', 'N')
     AND FORDELIVERY = -1;

  SELECT COUNT(1) INTO V_curDPreBok
    FROM BEDPREBOK
   WHERE TO_CHAR(BPBHDATE, 'YYYYMMDD') = TO_CHAR(V_EDCDATE, 'YYYYMMDD')
     AND WRDCODE = V_WARDCODE
     AND BPBTYPE = 'B'
     AND BPBSTS IN ('F', 'N')
     AND FORDELIVERY = -1;

  OPEN OUTCUR FOR
    SELECT  V_maxMPreBok,
            V_maxDPreBok,
            V_curMPreBok,
            V_curDPreBok
      FROM DUAL;
  RETURN OUTCUR;
END NHS_GET_PREBOOKING;
/
