create or replace
FUNCTION "NHS_GET_MEDRECDEFSET" (V_PARAM2 IN VARCHAR2)
 RETURN Types.cursor_type
 AS
  OUTCUR TYPES.CURSOR_TYPE;
  MedRecNewPatVolumeNo NUMBER := 3;
  MedRecNewVolVolumeNo NUMBER := 7;
BEGIN
  OPEN OUTCUR FOR
    SELECT PARCDE, PARAM1, PARAM2, PARDESC
    FROM SYSPARAM
    WHERE PARCDE LIKE 'MR%'
    AND (TO_NUMBER(PARAM2)=V_PARAM2);
  RETURN OUTCUR;
EXCEPTION
WHEN OTHERS THEN
  OPEN OUTCUR FOR
    SELECT NULL AS PARCDE, NULL AS PARAM1, NULL AS PARAM2, NULL AS PARDESC
    FROM DUAL;
  RETURN OUTCUR;
END NHS_GET_MEDRECDEFSET;
/
