CREATE OR REPLACE FUNCTION "NHS_LIS_BEDCHGHIS"(V_REGID IN VARCHAR2)
  RETURN TYPES.CURSOR_TYPE AS
  OUTCUR TYPES.CURSOR_TYPE;
BEGIN
  OPEN OUTCUR FOR
    SELECT '',
           TO_CHAR(BH.BHSDATE, 'DD/MM/YYYY HH24:MI:SS'),
           TO_CHAR(BH.BHSEDATE, 'DD/MM/YYYY HH24:MI:SS'),
           BH.BEDCODE,
           W.DPTCODE,
           W.WRDNAME,
           BH.USRID,
           BH.BHSID,
           BH.REGID,
           BH.PATNO,
           I.ACMCODE
      FROM BEDHIST BH, WARD W, ROOM RM, BED B, REG R, INPAT I
     WHERE BH.BEDCODE = B.BEDCODE
       AND B.ROMCODE = RM.ROMCODE
       AND RM.WRDCODE = W.WRDCODE
       AND R.REGID = BH.REGID
       AND I.INPID = R.INPID
       AND BH.REGID = V_REGID
     ORDER BY BHSID;
  RETURN OUTCUR;
END NHS_LIS_BEDCHGHIS;
/
