CREATE OR REPLACE FUNCTION "NHS_LIS_DOCCHGHIS"(V_REGID IN VARCHAR2)
  RETURN TYPES.CURSOR_TYPE AS
  OUTCUR TYPES.CURSOR_TYPE;
BEGIN
  OPEN OUTCUR FOR
    SELECT '',
           TO_CHAR(DH.DHSDATE,'DD/MM/YYYY'),
           TO_CHAR(DH.DHSEDATE,'DD/MM/YYYY'),
           DH.DOCCODE,
           D.DOCFNAME || ' ' || D.DOCGNAME,
           D.DOCCNAME,
           SPC.SPCNAME,
           DH.USRID,
           D.SPCCODE,
           DH.DHSID,
           DH.REGID,
           DH.PATNO,
           DH.DHSSTS
      FROM DOCHIST DH, DOCTOR D, SPEC SPC
     WHERE D.DOCCODE = DH.DOCCODE
       AND SPC.SPCCODE = D.SPCCODE
       AND DH.REGID = V_REGID
     ORDER BY DHSID;
  RETURN OUTCUR;
END NHS_LIS_DOCCHGHIS;
/
