create or replace FUNCTION                     "NHS_LIS_DTDVATABLELIST" (
	v_BKGSDATE IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
	SQLSTR VARCHAR2(2000);
BEGIN
SQLSTR := 'SELECT 
      B.BKGID,
      B.BKGSTS,
			TO_CHAR(B.BKGSDATE, ''DD/MM/YYYY HH24:MI''),
			TO_CHAR(B.BKGEDATE, ''DD/MM/YYYY HH24:MI''),
			S.DOCCODE,
      B.BKGPNAME,
      '''',
      B.PATNO,
      D.DOCFNAME||'' ''||D.DOCGNAME,
      '''',
      '''',
      '''',
      B.BKGRMK,
      B.SLTID,
      B.SCHID
		FROM BOOKING B
		LEFT JOIN PATIENT P ON B.PATNO = P.PATNO
		INNER JOIN SCHEDULE S ON B.SCHID = S.SCHID 
    LEFT JOIN DOCTOR D ON S.DOCCODE = D.DOCCODE
    WHERE B.DOCLOCID = ''3''
    AND B.BKGSDATE >= TO_DATE(''' || v_BKGSDATE || ' 00:00:00'', ''DD/MM/YYYY HH24:MI:SS'')
		AND B.BKGSDATE < TO_DATE(''' || v_BKGSDATE || ' 00:00:00'', ''DD/MM/YYYY HH24:MI:SS'') + 1
    AND B.BKGEDATE >= TO_DATE(''' || v_BKGSDATE || ' 00:00:00'', ''DD/MM/YYYY HH24:MI:SS'') 
    AND B.BKGEDATE < TO_DATE(''' || v_BKGSDATE || ' 00:00:00'', ''DD/MM/YYYY HH24:MI:SS'') + 1
    AND   B.BKGSTS IN (''N'', ''F'')  ';
  DBMS_OUTPUT.PUT_LINE(SQLSTR);
	OPEN OUTCUR FOR SQLSTR;
	RETURN OUTCUR;
END NHS_LIS_DTDVATABLELIST;
/
