CREATE OR REPLACE FUNCTION NHS_ACT_ADDBEDPREBOKCNT (
	v_ACTION   IN VARCHAR2,
	v_BPBHDATE IN VARCHAR2,
	v_BPBTYPE  IN VARCHAR2,
	v_BPBCNT   IN VARCHAR2,
	v_USRID    IN VARCHAR2,
	v_STECODE  IN VARCHAR2,
	o_ERRMSG   OUT VARCHAR2
)
	RETURN NUMBER
AS
	o_ERRCODE    NUMBER;
	OUTCUR TYPES.CURSOR_TYPE;
BEGIN
	o_errcode := 0;
	o_errmsg := 'OK';
	IF v_action = 'ADD' THEN
		INSERT INTO BEDPREBOKCNT (BPBMONTH, BPBTYPE, BPBCNT, SITECODE)
		VALUES (v_BPBHDATE, v_BPBTYPE, v_BPBCNT, v_STECODE);
	ELSE
		o_errcode := -1;
		o_errmsg := 'Parameter error.';
	END IF;
	RETURN O_ERRCODE;
END NHS_ACT_ADDBEDPREBOKCNT;
/
