CREATE OR REPLACE FUNCTION "NHS_ACT_SPLITSLIP" (
	v_ACTION  IN VARCHAR2,
	v_REGID   IN VARCHAR2,
	v_STECODE IN VARCHAR2,
	v_USRID   IN VARCHAR2,
	O_ERRMSG  OUT VARCHAR2
)
	RETURN NUMBER
AS
	O_ERRCODE NUMBER := -1;
	v_SLIPNO VARCHAR2(15);
	v_SLPTYPE VARCHAR2(1);
	v_PATNO VARCHAR2(10);
	v_DOCCODE VARCHAR2(10);
	v_DPTCODE VARCHAR2(10);
BEGIN
	IF v_ACTION = 'ADD' THEN
		v_SLIPNO := GENERATE_SLIP_NO;

		SELECT S.PATNO, S.SLPTYPE, S.DOCCODE, S.DPTCODE
		INTO   v_PATNO, v_SLPTYPE, v_DOCCODE, v_DPTCODE
		FROM   REG R, SLIP S
		WHERE  R.SLPNO = S.SLPNO
		AND    R.REGID = v_REGID;

		INSERT INTO SLIP (
			SLPNO,
			SLPTYPE,
			PATNO,
			REGID,
			DOCCODE,
			DPTCODE,
			SLPSTS,
			SLPSEQ,
			SLPPSEQ,
			SLPHDISC,
			SLPDDISC,
			SLPSDISC,
			SLPPAMT,
			SLPCAMT,
			SLPDAMT,
			STECODE,
			USRID
		) VALUES (
			v_SLIPNO,
			NVL(v_SLPTYPE, 'O'),
			v_PATNO,
			v_REGID,
			v_DOCCODE,
			v_DPTCODE,
			'A',
			1,
			1,
			0,
			0,
			0,
			0,
			0,
			0,
			v_STECODE,
			v_USRID
		);
		
		INSERT INTO SLIP_EXTRA(
			SLPNO,
			SLPDATE
		) VALUES (
			v_SLIPNO,
			SYSDATE
		);		

		UPDATE REG SET SLPNO = v_SLIPNO WHERE REGID = v_REGID;

		UPDATE REG_EXTRA
		SET MODIFY_DATE = SYSDATE,
			MODIFY_USER = v_USRID
		WHERE regid = v_REGID;

		O_ERRCODE := v_SLIPNO;
		O_ERRMSG  := 'OK';
	END IF;
	RETURN O_ERRCODE;
END NHS_ACT_SPLITSLIP;
/
