CREATE OR REPLACE FUNCTION NHS_LIS_OSBILLALERT (
	v_PATNO slip.patno%TYPE
)
	RETURN Types.cursor_type
AS
	OUTCUR TYPES.CURSOR_TYPE;
	ISINPAT NUMBER;
	REG_STS_CANCEL VARCHAR2(1) := 'C';
BEGIN

	SELECT COUNT(1) INTO ISINPAT
	FROM  PATIENT P, REG R, INPAT IP
	WHERE P.REGID_C = R.REGID
	AND   R.INPID = IP.INPID
	AND   P.PATNO = V_PATNO
	AND   R.REGSTS <> REG_STS_CANCEL
	AND  (IP.INPDDATE IS NULL OR IP.INPDDATE = '');

	IF ISINPAT = 0 THEN
		OPEN outcur FOR
			SELECT slptype, slpno,(slppamt + slpcamt + slpdamt) as OSAmt
			FROM   slip
			WHERE  patno = v_PATNO
			AND  ( slppamt + slpcamt + slpdamt ) != 0
			ORDER BY SLPNO DESC;
	END IF;

	RETURN OUTCUR;
END NHS_LIS_OSBILLALERT;
/
