CREATE OR REPLACE FUNCTION "NHS_LIS_PATIENTCATEGORY"
(v_PCYCODE PATCAT.PCYCODE%TYPE,
v_PCYDESC  PATCAT.PCYDESC%TYPE)
  RETURN Types.cursor_type
AS
  outcur types.cursor_type;
BEGIN
  OPEN outcur FOR
    SELECT
        PCYID,
        PCYCODE,
        PCYDESC,
        DECODE(PCYREF,-1,'Y','N'),
        DECODE(PCYSCM,-1,'Y','N')
    FROM PATCAT
    WHERE ( PCYCODE LIKE '%' || v_PCYCODE || '%')
    AND ( PCYDESC LIKE '%' || v_PCYDESC || '%')
    AND ROWNUM < 100
    ORDER BY PCYCODE;
  RETURN OUTCUR;
END NHS_LIS_PATIENTCATEGORY;
/
