create or replace
FUNCTION "NHS_ACT_DOCCHGHIS" (
	v_ACTION      IN VARCHAR2,
	v_PRE_DHSID   IN VARCHAR2,
	v_PRE_REGID   IN VARCHAR2,
	v_PRE_PATNO   IN VARCHAR2,
	v_PRE_DOCCODE IN VARCHAR2,
	v_PRE_SDATE   IN VARCHAR2,
	v_PRE_EDATE   IN VARCHAR2,
	v_DHSID       IN VARCHAR2,
	v_REGID       IN VARCHAR2,
	v_PATNO       IN VARCHAR2,
	v_DOCCODE     IN VARCHAR2,
	v_SDATE       IN VARCHAR2,
	v_EDATE       IN VARCHAR2,
	v_USRID       IN VARCHAR2,
	o_ERRMSG      OUT VARCHAR2
)
	RETURN NUMBER
AS
	o_ERRCODE NUMBER;
	v_NOOFREC NUMBER;
BEGIN
	o_ERRCODE := 0;
	o_ERRMSG	:= 'OK';

	IF v_ACTION = 'ADD' OR v_ACTION = 'MOD' THEN
		IF v_PRE_DHSID IS NOT NULL THEN
			SELECT COUNT(1) INTO v_NOOFREC FROM DOCHIST WHERE DHSID = v_PRE_DHSID;

			IF v_NOOFREC > 0 THEN
				UPDATE DOCHIST
				SET
					REGID    = v_PRE_REGID,
					PATNO    = v_PRE_PATNO,
					DOCCODE  = v_PRE_DOCCODE,
					DHSDATE  = To_DATE(v_PRE_SDATE, 'DD/MM/YYYY HH24:MI:SS'),
					DHSEDATE = To_DATE(v_PRE_EDATE, 'DD/MM/YYYY HH24:MI:SS')
--					DHSSTS   = 'N',
--					USRID    = v_USRID
				WHERE DHSID  = v_PRE_DHSID;
			ELSE
				o_ERRCODE := -1;
				o_ERRMSG := 'Fail to update due to record not exist.';
			END IF;
		END IF;

		SELECT COUNT(1) INTO v_NOOFREC FROM DOCHIST WHERE DHSID = v_DHSID;
		IF v_NOOFREC = 0 THEN
			INSERT INTO DOCHIST
			VALUES (
				SEQ_DOCHIST.NEXTVAL,
				v_REGID,
				v_PATNO,
				v_DOCCODE,
				To_DATE(v_SDATE, 'DD/MM/YYYY HH24:MI:SS'),
				To_DATE(v_EDATE, 'DD/MM/YYYY HH24:MI:SS'),
				'C',
				v_USRID
			);
		ELSE
			 UPDATE DOCHIST
			 SET
			 	REGID    = v_REGID,
				PATNO    = v_PATNO,
				DOCCODE  = v_DOCCODE,
				DHSDATE  = TO_DATE(V_SDATE, 'DD/MM/YYYY HH24:MI:SS'),
				DHSEDATE = To_DATE(v_EDATE, 'DD/MM/YYYY HH24:MI:SS'),
--				DHSSTS   = 'N',
				USRID    = v_USRID
			 WHERE DHSID = v_DHSID;
		END IF;
	ELSIF v_ACTION = 'DEL' THEN
		SELECT COUNT(1) INTO v_NOOFREC FROM DOCHIST WHERE DHSID = v_PRE_DHSID;
		IF v_NOOFREC > 0 THEN
			UPDATE DOCHIST
			SET
--				REGID    = v_PRE_REGID,
--				PATNO    = v_PRE_PATNO,
--				DOCCODE  = v_PRE_DOCCODE,
--				DHSDATE  = To_DATE(v_PRE_SDATE, 'DD/MM/YYYY HH24:MI:SS'),
				DHSEDATE = To_DATE(v_PRE_EDATE, 'DD/MM/YYYY HH24:MI:SS')
--				DHSSTS   = 'N',
--				USRID    = v_USRID
			WHERE DHSID  = v_PRE_DHSID;
		ELSE
			o_ERRCODE := -1;
			o_ERRMSG := 'Fail to delete due to record not exist.';
		END IF;

		SELECT COUNT(1) INTO v_NOOFREC FROM DOCHIST WHERE DHSID = v_DHSID;

		IF v_NOOFREC > 0 THEN
			DELETE DOCHIST WHERE DHSID = v_DHSID;
		ELSE
			o_ERRCODE := -1;
			o_ERRMSG := 'Fail to delete due to record not exist.';
		END IF;
	END IF;
	RETURN o_ERRCODE;
EXCEPTION
WHEN OTHERS THEN
	ROLLBACK;
	o_ERRCODE := -1;
	o_errMsg := 'Doctor Change cannot save.';
	DBMS_OUTPUT.PUT_LINE('An ERROR was encountered - '||SQLCODE||' -ERROR- '||SQLERRM);
	RETURN o_errcode;
END NHS_ACT_DOCCHGHIS;
/