CREATE OR REPLACE FUNCTION "NHS_GET_PATIENT_CONSENT" (
	v_PATNO IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
BEGIN
	OPEN OUTCUR FOR
		SELECT
			PATNO,
			TO_CHAR(CONSENTSDATE1, 'DD/MM/YYYY'),
			TO_CHAR(CONSENTEDATE1, 'DD/MM/YYYY'),
			CONSENTARCCODE1,
			CONSENTRMK1,
			U1.USRNAME,
			TO_CHAR(P.CONSENTDATE1, 'DD/MM/YYYY HH24:MI:SS'),
			TO_CHAR(CONSENTSDATE2, 'DD/MM/YYYY'),
			TO_CHAR(CONSENTEDATE2, 'DD/MM/YYYY'),
			CONSENTARCCODE2,
			CONSENTRMK2,
			U2.USRNAME,
			TO_CHAR(P.CONSENTDATE2, 'DD/MM/YYYY HH24:MI:SS'),
			TO_CHAR(CONSENTSDATE3, 'DD/MM/YYYY'),
			TO_CHAR(CONSENTEDATE3, 'DD/MM/YYYY'),
			CONSENTARCCODE3,
			CONSENTRMK3,
			U3.USRNAME,
			TO_CHAR(P.CONSENTDATE3, 'DD/MM/YYYY HH24:MI:SS'),
			INSUANCERMK
		FROM PATIENT_EXTRA P
		LEFT JOIN USR U1 ON P.CONSENTUSER1 = U1.USRID
		LEFT JOIN USR U2 ON P.CONSENTUSER2 = U2.USRID
		LEFT JOIN USR U3 ON P.CONSENTUSER3 = U3.USRID
		WHERE PATNO = v_PATNO;
	RETURN OUTCUR;
END NHS_GET_PATIENT_CONSENT;
/
