CREATE OR REPLACE FUNCTION NHS_GET_DOCTOR_PBOREMARK (
	v_DocCode VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
BEGIN
	OPEN OUTCUR FOR
		SELECT PBO_REMARK
		FROM   DOCTOR_EXTRA
		WHERE  DOCCODE = v_DocCode;

	RETURN OUTCUR;
END NHS_GET_DOCTOR_PBOREMARK;
/
