CREATE OR REPLACE FUNCTION "NHS_ACT_BEDPREBOKREACTIVE"
(V_ACTION IN VARCHAR2,
V_PBPID  IN VARCHAR2,
V_USRID  IN VARCHAR2,
O_ERRMSG OUT VARCHAR2)
RETURN NUMBER AS
	O_ERRCODE NUMBER;
BEGIN
	O_ERRCODE := 0;
	O_ERRMSG  := 'OK';

	IF V_ACTION = 'ADD' THEN
		UPDATE BEDPREBOK
		SET    BPBSTS = 'N', EDITUSER = V_USRID, EDITDATE = SYSDATE
		WHERE  PBPID = V_PBPID
		AND    BPBSTS IN ('D', 'F') ;
	END IF;

	RETURN O_ERRCODE;
EXCEPTION
WHEN OTHERS THEN
	ROLLBACK;
	dbms_output.put_line('An ERROR was encountered - '||SQLCODE||' -ERROR- '||SQLERRM);

	RETURN -1;
END NHS_ACT_BEDPREBOKREACTIVE;
/
