CREATE OR REPLACE FUNCTION NHS_GET_TRANSFERBED (
	v_BED IN VARCHAR2
)
	RETURN types.cursor_type
AS
	outcur types.cursor_type;
BEGIN
	OPEN OUTCUR FOR
		SELECT HPSTATUS
		FROM   HPSTATUS
		WHERE  HPTYPE = 'BEDTXN'
		AND    HPKEY = v_BED
		AND    HPACTIVE = -1;

	RETURN OUTCUR;
END NHS_GET_TRANSFERBED;
/
