CREATE OR REPLACE FUNCTION "NHS_GET_PATIENT_IDNO" (
	v_PATIDNO IN VARCHAR2
)
	RETURN Types.cursor_type
AS
	a_PATIDNO PATIENT.PATIDNO%TYPE;
BEGIN
	IF v_PATIDNO IS NULL THEN
		a_PATIDNO := ' ';
	ELSE
		a_PATIDNO := v_PATIDNO;
	END if;

	RETURN NHS_LIS_PATIENT('LIS' , NULL, a_PATIDNO, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
END NHS_GET_PATIENT_IDNO;
/
