CREATE OR REPLACE FUNCTION "NHS_LIS_PATALERTEDIT" (
	v_PATNO IN VARCHAR2,
	v_USRID IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
	sqlstr VARCHAR2(2000);
BEGIN
	sqlstr := '
		SELECT '''', ALTCODE, ALTDESC, ALTID
		FROM ALERT
		WHERE ALTID NOT IN (SELECT ALTID
					FROM PATALTLINK
					WHERE PATNO = ''' || v_PATNO || '''
					AND USRID_C IS NULL)';

	IF v_USRID != GET_CURRENT_STECODE THEN
		sqlstr := sqlstr || ' AND ALTID IN (SELECT DISTINCT R.ALTID
					FROM USRROLE U, ROLALTLINKEDIT R
					WHERE U.ROLID = R.ROLID
					AND U.USRID = ''' || v_USRID || ''')';
	END IF;

--	AND ALERT = -1
	sqlstr := sqlstr || ' AND ALTDESC NOT LIKE ''%INACTIVE CODE%''
		ORDER BY ALTCODE';

	OPEN OUTCUR FOR sqlstr;
	RETURN OUTCUR;
END NHS_LIS_PATALERTEDIT;
/
