CREATE OR REPLACE FUNCTION "NHS_ACT_BEDPREBOKCNT"(
	v_ACTION   IN VARCHAR2,
	v_BPBMonth IN VARCHAR2,
	v_BPBType  IN VARCHAR2,
	v_SiteCode IN VARCHAR2,
	O_ERRMSG   OUT VARCHAR2
)
	RETURN NUMBER
AS
	O_ERRCODE NUMBER;
BEGIN
	O_ERRCODE := 0;
	O_ERRMSG  := 'OK';

	IF v_ACTION = 'ADD' THEN
		INSERT INTO BedPreBokCnt(BPBMonth, BPBType, BPBCNT, SiteCode)
		VALUES (v_BPBMonth, v_BPBType, 0, v_SiteCode);
	END IF;

	RETURN O_ERRCODE;
EXCEPTION
WHEN OTHERS THEN
	ROLLBACK;
	dbms_output.put_line('An ERROR was encountered - '||SQLCODE||' -ERROR- '||SQLERRM);

	RETURN -1;
END NHS_ACT_BEDPREBOKCNT;
/
