create or replace
FUNCTION      "NHS_GET_DEPTAPPBYNO" (
	v_deptaid IN dept_app.deptaid%TYPE
)
	RETURN TYPES.cursor_type
AS
	OUTCUR TYPES.cursor_type;
BEGIN
	OPEN OUTCUR FOR
		SELECT
			OA.PATNO,
			OA.DEPTAFNAME,
			OA.DEPTAGNAME,
			OA.DEPTASEX,
			OA.PATTYPE,
			TO_CHAR(OA.DEPTAOSDATE,'DD/MM/YYYY hh24:mi'),
			TO_CHAR(OA.DEPTAOEDATE,'DD/MM/YYYY hh24:mi'),
			OA.DEPTCID_RM,
			OA.DEPTPID,
			OA.DOCCODE_R,
			TO_CHAR(OA.DEPTABDATE,'DD/MM/YYYY'),
			DEPTAHKID,
			DEPTATEL,
			DEPTPRMK,
			DECODE(DEPTSPECBOOK, 1, 'Y', 'N'),
			DEPTWARD,
			DEPTBED,
      OA.DOCCODE_P
		FROM  DEPT_APP OA
		WHERE OA.DEPTAID = V_DEPTAID;
	RETURN OUTCUR;
END NHS_GET_DEPTAPPBYNO;
/
