create or replace FUNCTION "NHS_GET_PREBOOKDETAIL" (
	v_PBPID BEDPREBOK.PBPID%TYPE
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
	v_ARCCODE     BEDPREBOK.ARCCODE%TYPE;
	v_COPAYTYP    BEDPREBOK.COPAYTYP%TYPE;
	v_COPAYAMT    BEDPREBOK.COPAYAMT%TYPE;
	v_POLICY      BEDPREBOK.POLICY%TYPE;
	v_ARLMTAMT    BEDPREBOK.ARLMTAMT%TYPE;
	v_CVREDATE    BEDPREBOK.CVREDATE%TYPE;
	v_VOUCHER     BEDPREBOK.VOUCHER%TYPE;
	v_FURGRTAMT   BEDPREBOK.FURGRTAMT%TYPE;
	v_FURGRTDATE  BEDPREBOK.FURGRTDATE%TYPE;
	v_ISDOCTOR    BEDPREBOK.ISDOCTOR%TYPE;
	v_ISSPECIAL   BEDPREBOK.ISSPECIAL%TYPE;
	v_ISHOSPITAL  BEDPREBOK.ISHOSPITAL%TYPE;
	v_ISOTHER     BEDPREBOK.ISOTHER%TYPE;
	v_DOCCODE     BEDPREBOK.DOCCODE%TYPE;

	v_COPAYTYP2   ARCODE.COPAYTYP%TYPE;
	v_COPAYAMT2   ARCODE.COPAYAMT%TYPE;
	v_ARLMTAMT2   ARCODE.ARLMTAMT%TYPE;
	v_CVREDATE2   ARCODE.CVREDATE%TYPE;

	v_PBMID       BEDPREBOK_EXTRA.PBMID%TYPE;
	v_PBSNO       BEDPREBOK_EXTRA.PBSNO%TYPE;
	v_PBSID       BEDPREBOK_EXTRA.PBSID%TYPE;
	v_ACTID       BEDPREBOK_EXTRA.ACTID%TYPE;
	v_ISRECLG     BEDPREBOK_EXTRA.ISRECLG%TYPE;
	v_ARACMCODE   BEDPREBOK_EXTRA.ARACMCODE%TYPE;
	v_PBPKGCODE   BEDPREBOK_EXTRA.PBPKGCODE%TYPE;
	v_ESTGIVEN    BEDPREBOK_EXTRA.ESTGIVN%TYPE;
	v_COPAYAMTACT BEDPREBOK_EXTRA.COPAYAMTACT%TYPE;
	v_PREAUTHNO   BEDPREBOK_EXTRA.INSPREAUTHNO%TYPE;
	v_FESTID      FIN_EST_HOSP.FESTID%TYPE;
	v_BE 	      FIN_EST_HOSP.OSB_BE%TYPE;
  V_PBPKGCODE2 BEDPREBOK_EXTRA.PBPKGCODE2%TYPE;
	v_ACTDESC     VARCHAR(50);
	v_PBMCODE     VARCHAR2(10);

	v_noOfRec NUMBER;
BEGIN
	SELECT COUNT(1) INTO v_noOfRec FROM BEDPREBOK WHERE PBPID = v_PBPID;
	IF v_noOfRec > 0 THEN
		SELECT ARCCODE, COPAYTYP, COPAYAMT, POLICY, ARLMTAMT, CVREDATE, VOUCHER,
			FURGRTAMT, FURGRTDATE, ISDOCTOR, ISSPECIAL, ISHOSPITAL, ISOTHER, DOCCODE
		INTO v_ARCCODE, v_COPAYTYP, v_COPAYAMT, v_POLICY, v_ARLMTAMT, v_CVREDATE,
			v_VOUCHER, v_FURGRTAMT, v_FURGRTDATE, v_ISDOCTOR, v_ISSPECIAL, v_ISHOSPITAL,
			v_ISOTHER, v_DOCCODE
		FROM BEDPREBOK
		WHERE PBPID = v_PBPID;
	END IF;

	IF v_ARCCODE IS NOT NULL AND LENGTH(v_ARCCODE) > 0 THEN
		SELECT COUNT(1) INTO v_noOfRec FROM ARCODE WHERE ARCCODE = v_ARCCODE;
		if v_noOfRec > 0 then
			SELECT COPAYTYP, COPAYAMT, ARLMTAMT, CVREDATE
			INTO v_COPAYTYP2, v_COPAYAMT2, v_ARLMTAMT2, v_CVREDATE2
			FROM ARCODE
			WHERE ARCCODE = v_ARCCODE;
		end if;

		IF v_COPAYTYP IS NULL OR LENGTH(v_COPAYTYP) = 0 THEN
			v_COPAYTYP := v_COPAYTYP2;
		END IF;
		IF v_COPAYAMT IS NULL OR LENGTH(v_COPAYAMT) = 0 THEN
			v_COPAYAMT := v_COPAYAMT2;
		END IF;
		IF v_ARLMTAMT IS NULL OR LENGTH(v_ARLMTAMT) = 0 THEN
			v_ARLMTAMT := v_ARLMTAMT2;
		END IF;
		IF v_CVREDATE IS NULL OR LENGTH(v_CVREDATE) = 0 THEN
			v_CVREDATE := v_CVREDATE2;
		END IF;
	END IF;

	SELECT COUNT(1) INTO v_noOfRec FROM BEDPREBOK_EXTRA WHERE PBPID = v_PBPID;
	IF v_noOfRec > 0 THEN
		SELECT PBMID, PBSNO, PBSID, ACTID,
			(SELECT art.actdesc FROM arcardtype art WHERE art.actid = BE.actid) AS arcardtype,
			ISRECLG, ARACMCODE, PBPKGCODE, ESTGIVN, COPAYAMTACT, INSPREAUTHNO, PBPKGCODE2
		INTO   v_PBMID, v_PBSNO, v_PBSID, v_ACTID, v_ACTDESC, v_ISRECLG, v_ARACMCODE, v_PBPKGCODE, v_ESTGIVEN, v_COPAYAMTACT, v_PREAUTHNO, V_PBPKGCODE2
		FROM   BEDPREBOK_EXTRA BE
		WHERE  PBPID = v_PBPID;
	END IF;

	SELECT count(1) INTO v_noOfRec FROM Fin_Est_Hosp WHERE PBPID = v_PBPID;
	IF (v_noOfRec > 0) THEN
		SELECT Osb_Be, FESTID INTO v_BE, v_FESTID
		FROM   Fin_Est_Hosp
		WHERE  PBPID = v_PBPID;
	END IF;

	IF v_PBMID IS NOT NULL AND LENGTH(v_PBMID) > 0 THEN
		IF v_PBMID = '0' THEN
			v_PBMCODE := 'DEP';
		ELSE
			v_PBMCODE := 'DEP' || v_PBMID;
		END IF;
	END IF;

	OPEN OUTCUR FOR
		SELECT v_ARCCODE, v_COPAYTYP, v_COPAYAMT, v_POLICY, v_ARLMTAMT, TO_CHAR(v_CVREDATE, 'DD/MM/YYYY'),
			v_VOUCHER, v_FURGRTAMT, TO_CHAR(v_FURGRTDATE, 'DD/MM/YYYY'), v_ISDOCTOR, v_ISSPECIAL, v_ISHOSPITAL,
			v_ISOTHER, v_DOCCODE, v_PBMID, v_PBSNO, v_PBSID, v_PBMCODE, v_ACTID, v_ACTDESC, v_ISRECLG, v_ARACMCODE,
			v_PBPKGCODE, v_ESTGIVEN, v_COPAYAMTACT, v_FESTID, v_BE, v_PREAUTHNO, V_PBPKGCODE2
		FROM DUAL;

	RETURN OUTCUR;
END NHS_GET_PREBOOKDETAIL;
/
