/****************************************************************************/
/*            (c) Copyright Black Ice Software Inc.  1994.                  */
/*                   All Rights Reserved                                    */
/*                   Unpublished and confidential material.                 */
/*                   --- Do not Reproduce or Disclose ---                   */
/*                                                                          */
/*                                                                          */
/****************************************************************************/
/*
  $Log:   K:\archive\faxsrc40\inc\errorcl.h  $
 * 
 *    Rev 4.31   24 Mar 1998 12:23:30   Zoltan
 * No change.
 * 
 *    Rev 4.30   01 Dec 1997 14:12:38   Zoltan
 * 
 *    Rev 4.28   26 Aug 1997 19:14:26   Gyuri
 * No change.
 * 
 *    Rev 4.27   08 May 1996 15:07:28   joe
 * 
 *    Rev 4.21   22 Mar 1996 15:48:30   Albert
 * No change.
 * 
 *    Rev 4.20   21 Mar 1996 16:34:46   Albert
 * No change.
 * 
 *    Rev 4.7   16 Mar 1996 12:14:20   joe
 * No change.
 * 
 *    Rev 4.6   14 Mar 1996 15:07:00   Albert
 * No change.
 * 
 *    Rev 4.5   09 Mar 1996 19:06:24   Albert
 * No change.
 * 
 *    Rev 4.4   09 Mar 1996 12:45:02   Albert
 * No change.
 * 
 *    Rev 4.3   08 Mar 1996 14:54:46   Albert
 * No change.
 * 
 *    Rev 4.2   08 Mar 1996 11:36:58   Albert
 * No change.
 * 
 *    Rev 4.1   05 Mar 1996 17:55:18   Albert
 * No change.
 * 
 *    Rev 4.0   05 Mar 1996 10:12:28   Albert
 * Initial revision.
 * 
 *    Rev 0.911   03 Mar 1996 13:37:42   Albert
 * No change.
 * 
 *    Rev 0.910   02 Mar 1996 15:34:10   Albert
 * No change.
 * 
 *    Rev 0.804   01 Mar 1996 13:18:40   Albert
 * No change.
 * 
 *    Rev 0.803   21 Feb 1996 09:46:42   Albert
 * 
*/
#ifndef __CLERROR_H
#define __CLERROR_H

#pragma pack(4)


//*****************************************************************************
#pragma pack()
#endif  // __CLERROR_H 
