CREATE OR REPLACE TRIGGER PATIENT_UPDATE_LOG_TRIGGER
after update of PATFNAME, PATGNAME, PATCNAME, PATSEX, PATBDATE, PATADD1, PATADD2, PATADD3, PATHTEL, PATOTEL, LOCCODE
on PATIENT FOR EACH ROW
BEGIN
	IF UPDATING THEN
		if  TRIM(:NEW.PATFNAME) <> TRIM(:OLD.PATFNAME)
			or TRIM(:NEW.PATGNAME) <> TRIM(:OLD.PATGNAME)
			or TRIM(:NEW.PATCNAME) <> TRIM(:OLD.PATCNAME)
			or :NEW.PATSEX <> :OLD.PATSEX
			or :NEW.PATBDATE <> :OLD.PATBDATE
			or :NEW.PATADD1 <> :OLD.PATADD1
			or :NEW.PATADD2 <> :OLD.PATADD2
			or :NEW.PATADD3 <> :OLD.PATADD3
			or :NEW.PATHTEL <> :OLD.PATHTEL
			or :NEW.PATOTEL <> :OLD.PATOTEL
			or :NEW.LOCCODE <> :OLD.LOCCODE THEN
			INSERT INTO PATIENT_UPDATE_LOG (
				PULID, PATNO,
				OLDPATFNAME, OLDPATGNAME, OLDPATCNAME, OLDPATSEX, OLDPATBDATE,
				OLDPATADD1, OLDPATADD2, OLDPATADD3, OLDPATHTEL, OLDPATOTEL, OLDLOCCODE,
				NEWPATFNAME, NEWPATGNAME, NEWPATCNAME, NEWPATSEX, NEWPATBDATE,
				NEWPATADD1, NEWPATADD2, NEWPATADD3, NEWPATHTEL, NEWPATOTEL, NEWLOCCODE,
				USRID, PULDATE
			) values (
				SEQ_PATIENT_UPDATE_LOG.NEXTVAL, :old.PATNO,
				:OLD.PATFNAME, :OLD.PATGNAME, :OLD.PATCNAME, :OLD.PATSEX, :OLD.PATBDATE,
				:OLD.PATADD1, :OLD.PATADD2, :OLD.PATADD3, :OLD.PATHTEL, :OLD.PATOTEL, :OLD.LOCCODE,
				:NEW.PATFNAME, :NEW.PATGNAME, :NEW.PATCNAME, :NEW.PATSEX, :NEW.PATBDATE,
				:NEW.PATADD1, :NEW.PATADD2, :NEW.PATADD3, :NEW.PATHTEL, :NEW.PATOTEL, :NEW.LOCCODE,
				USER, SYSDATE
			);
		END IF;
	END IF;
END;
/
