create or replace FUNCTION ADD_TICKET_QUEUE(
	i_PATNO      VARCHAR2,
	i_REGID      NUMBER,
	i_WRDCODE    VARCHAR2,
	i_BEDCODE    VARCHAR2,
	i_PLAN_DATE  DATE
)
	RETURN BOOLEAN
AS
	v_Count NUMBER;
BEGIN
	SELECT COUNT(1) INTO v_Count FROM PATIENT WHERE PATNO = i_PATNO;
	IF v_Count = 0 THEN
		RETURN FALSE;
	END IF;

	SELECT COUNT(1) INTO v_Count FROM REG WHERE REGID = i_REGID;
	IF v_Count = 0 THEN
		RETURN FALSE;
	END IF;

	SELECT COUNT(1) INTO v_Count FROM WARD WHERE WRDCODE = i_WRDCODE;
	IF v_Count = 0 THEN
		RETURN FALSE;
	END IF;

	INSERT INTO TICKET_QUEUE (PATNO, REGID, WRDCODE, BEDCODE, PLAN_DATE)
	VALUES (i_PATNO, i_REGID, i_WRDCODE, i_BEDCODE, i_PLAN_DATE);

	RETURN TRUE;
END;
/
