@./common/NHS_ACT_CashierVoidEntry.sql
@./common/NHS_ACT_CashierVoidEntryClear.sql
@./common/NHS_ACT_CashierVoidEntryPost.sql
@./common/NHS_ACT_CHECKSLIPS.sql
@./common/NHS_ACT_DELETE.sql
@./common/NHS_ACT_LOGON.sql
@./common/NHS_ACT_LOGON_SSO.sql
@./common/NHS_ACT_MERGESLIP.sql
@./common/NHS_ACT_PATCHALERT.sql
@./common/NHS_ACT_RECORDLOCK.sql
@./common/NHS_ACT_RECORDLOCKCHECK.sql
@./common/NHS_ACT_RECORDUNLOCK.sql
@./common/NHS_ACT_RECORDUNLOCK_BYOTHER.sql
@./common/NHS_ACT_SIGNOFF.sql
@./common/NHS_ACT_SLIPLOCK.sql
@./common/NHS_ACT_SLIPUNLOCK.sql
@./common/NHS_ACT_SLPPAYALLLOCKAR.sql
@./common/NHS_ACT_SLPPAYALLUNLOCKAR.sql
@./common/NHS_ACT_SYSLOG.sql
@./common/NHS_ACT_UPDATE.sql
@./common/NHS_ACT_VoidCashierTransaction.sql
@./common/NHS_CHK_CanProceed.sql
@./common/NHS_CHK_DUPLPREBOK.sql
@./common/NHS_CHK_KEEPALIVE.sql
@./common/NHS_GET_CARDNEWREF.sql
@./common/NHS_GET_COMPUTERNAME.sql
@./common/NHS_GET_LOOKUP.sql
@./common/NHS_GET_LOOKUP_WITHDBLINK.sql
@./common/NHS_GET_MEDICALRECORDID.sql
@./common/NHS_GET_NEXT_XJOBNO.sql
@./common/NHS_GET_PACKAGEALERT.sql
@./common/NHS_GET_PATIENTRPTLANG.sql
@./common/NHS_GET_RECORDLOCK.sql
@./common/NHS_GET_ROOM_EXIST.sql
@./common/NHS_GET_SITECODE.sql
@./common/NHS_GET_SLIPLOCK.sql
@./common/NHS_GET_Slpno2Date.sql
@./common/NHS_GET_SYSDATE.sql
@./common/NHS_GET_SYSPARAM.sql
@./common/NHS_LIS_ALERTSEARCH.sql
@./common/NHS_LIS_CHECKBEDSTATUS.sql
@./common/NHS_LIS_DISABLEFUNC.sql
@./common/NHS_LIS_DOCTORSEARCH.sql
@./common/NHS_LIS_DUPLPREBOK.sql
@./common/NHS_LIS_GETLOCKUSER.sql
@./common/NHS_LIS_GETMERGEDSLIP.sql
@./common/NHS_LIS_ITEMCHARGEVALIDATE.sql
@./common/NHS_LIS_LOOKUP.sql
@./common/NHS_LIS_LOOKUP_EMPTY.sql
@./common/NHS_LIS_LOOKUP_WITHDBLINK.sql
@./common/NHS_LIS_PATIENT_ALERT2.sql
@./common/NHS_LIS_SLIP.sql
@./common/NHS_LIS_SEARCHALERT.sql
@./common/NHS_LIS_SEARCH_TALERT.sql
@./common/NHS_LIS_SQL.sql
@./common/NHS_LIS_SUBDISEASEBYABBR.sql
@./common/NHS_SYS_AddCharge.sql
@./common/NHS_SYS_AddDeposit.sql
@./common/NHS_SYS_LookupItemCharge.sql
@./common/NHS_SYS_LookupPackageCharge.sql
@./common/NHS_SYS_UnconfirmDeposit.sql
@./common/NHS_UTL_AddCashierTransaction.sql
@./common/NHS_UTL_AddDefaultItems.sql
@./common/NHS_UTL_AddEntry.sql
@./common/NHS_UTL_AddPackageEntry.sql
@./common/NHS_UTL_ADDTXENTRY.sql
@./common/NHS_UTL_ADJUSTENTRY.sql
@./common/NHS_UTL_ARCREDITALLOC.sql
@./common/NHS_UTL_AREntry.sql
@./common/NHS_UTL_ARPaymentEntry.sql
@./common/NHS_UTL_AUTOSLIPCAT.sql
@./common/NHS_UTL_BPBTYPE.sql
@./common/NHS_UTL_CanCloseIPSlip.sql
@./common/NHS_UTL_CanProceed.sql
@./common/NHS_UTL_CashierEntry.sql
@./common/NHS_UTL_CashierReceiptNumber.sql
@./common/NHS_UTL_ConPceChange.sql
@./common/NHS_UTL_DeleteTelLog.sql
@./common/NHS_UTL_FastCashierEntry.sql
@./common/NHS_UTL_FillNewCPS.sql
@./common/NHS_UTL_GetCardNewRef.sql
@./common/NHS_UTL_GETCHARGECODE.sql
@./common/NHS_UTL_GetCreditCardRate.sql
@./common/NHS_UTL_GetDupPrebok.sql
@./common/NHS_UTL_GETSKIPDOCCODE.sql
@./common/NHS_UTL_IncrementSlipSeq.sql
@./common/NHS_UTL_InsertMisAddr.sql
@./common/NHS_UTL_isChequeTransaction.sql
@./common/NHS_UTL_IsLastActiveSlip.sql
@./common/NHS_UTL_ItemChargeValidate.sql
@./common/NHS_UTL_ItmPkgCodeValidate.sql
@./common/NHS_UTL_LASTTEST.sql
@./common/NHS_UTL_LookupAcmCode.sql
@./common/NHS_UTL_LookupGlCode.sql
@./common/NHS_UTL_LookupGLCodeChgACM.sql
@./common/NHS_UTL_LookUpItmCode.sql
@./common/NHS_UTL_LookUpPkgCode.sql
@./common/NHS_UTL_LOOKUP_PALERTCODES.sql
@./common/NHS_UTL_MOVEPACKAGETOSLIP.sql
@./common/NHS_UTL_MovePkgToPkgtx.sql
@./common/NHS_UTL_MovePkgToSliptx.sql
@./common/NHS_UTL_MOVESLIPTOPACKAGE.sql
@./common/NHS_UTL_MoveToPkgtx.sql
@./common/NHS_UTL_MoveToSliptx.sql
@./common/NHS_UTL_PaymentCapturePostTx.sql
@./common/NHS_UTL_PreTransaction.sql
@./common/NHS_UTL_reCalculateCPS.sql
@./common/NHS_UTL_SCMArCrReverse.sql
@./common/NHS_UTL_SCMAuto.sql
@./common/NHS_UTL_SCMGETCHG.sql
@./common/NHS_UTL_SCMGETPAY.sql
@./common/NHS_UTL_SCMReverse.sql
@./common/NHS_UTL_SCMUpdate.sql
@./common/NHS_UTL_SLIP.sql
@./common/NHS_UTL_SlpPayAllArCrReverse.sql
@./common/NHS_UTL_SlpPayAllAuto.sql
@./common/NHS_UTL_SlpPayAllAutoCal.sql
@./common/NHS_UTL_SLPPAYALLCHECK.sql
@./common/NHS_UTL_SLPPAYALLGETCHGSQL.sql
@./common/NHS_UTL_SLPPAYALLGETPAYSQL.sql
@./common/NHS_UTL_SLPPAYALLLOCKAR.sql
@./common/NHS_UTL_SlpPayAllReverse.sql
@./common/NHS_UTL_SLPPAYALLUNLOCKAR.sql
@./common/NHS_UTL_TransferDeposit.sql
@./common/NHS_UTL_UpdateBalance.sql
@./common/NHS_UTL_UpdateSchedule.sql
@./common/NHS_UTL_UpdateSlip.sql
@./common/NHS_UTL_UpdateSliptxStatus.sql
exit