CREATE OR REPLACE FUNCTION "GET_ALERT_CODE" (
	v_PATNO IN VARCHAR2,
	v_USRID IN VARCHAR2
)
	RETURN VARCHAR2
AS
	P_ALTCODE VARCHAR2(1000);
BEGIN
	SELECT LISTAGG( A.ALTCODE, ',' ) WITHIN GROUP ( ORDER BY A.ALTCODE ) INTO P_ALTCODE
	FROM  PATALTLINK P, ALERT A
	WHERE P.ALTID = A.ALTID
	AND   P.PATNO = v_PATNO
	AND   P.PALCDATE IS NULL
	AND   P.ALTID IN (
		SELECT DISTINCT R.ALTID
		FROM  USRROLE U, ROLALTLINK R
		WHERE U.ROLID = R.ROLID
		AND  (U.USRID = v_USRID OR v_USRID IS NULL)
	);

	RETURN P_ALTCODE;
END;
/
