CREATE OR REPLACE
FUNCTION "NHS_GET_ROOM_EXIST" (
	i_RomCode VARCHAR2
)
	RETURN Types.cursor_type
AS
	outcur types.cursor_type;
BEGIN
	OPEN OUTCUR FOR
		SELECT ROMCODE
		FROM   ROOM
		WHERE  UPPER(ROMCODE) = UPPER(I_ROMCODE)
		AND    rownum = 1;
	RETURN OUTCUR;
END NHS_GET_ROOM_EXIST;
/