CREATE OR REPLACE FUNCTION "NHS_UTL_ALERTQUOTA" (
	i_BKGALERT IN VARCHAR2,
	i_DOCCODE  IN VARCHAR2,
	i_BKGDATE  IN DATE
)
	RETURN VARCHAR
AS
	v_COUNT NUMBER := 0;
	v_AVAILABLE_D NUMBER := 0;
	v_AVAILABLE_D2 NUMBER := 0;
	v_AVAILABLE_M NUMBER := 0;
	v_AVAILABLE_Y NUMBER := 0;
	v_QUOTAD NUMBER := 0;
	v_QUOTAM NUMBER := 0;
	v_QUOTAY NUMBER := 0;
	o_errcode NUMBER := 0;
	v_BKGALERT VARCHAR2(10);
	v_BKGDATE VARCHAR2(10);
	v_BKGSDATE DATE;
	v_BKGEDATE DATE;
	v_BKGSDATE_NOSHOW DATE;
	v_BKGSDATE_AM DATE;
	v_BKGEDATE_AM DATE;
	v_BKGSDATE_PM DATE;
	v_BKGEDATE_PM DATE;
	v_DISPLAY_MESSAGE VARCHAR2(100);
BEGIN
	-- share quota
	IF GET_CURRENT_STECODE = 'HKAH' AND (i_BKGALERT = '71' OR i_BKGALERT = '72' OR i_BKGALERT = '73') THEN
		v_BKGALERT := '70';
	ELSE
		v_BKGALERT := i_BKGALERT;
	END IF;

	SELECT COUNT(1) INTO v_COUNT FROM BOOKINGALERT WHERE BKAID = v_BKGALERT AND (BKAQUOTAD = -1 OR BKAQUOTAM = -1 OR BKAQUOTAY = -1);
	IF v_COUNT = 0 THEN
		RETURN '0';
	END IF;

	SELECT BKAQUOTAD, BKAQUOTAM, BKAQUOTAY INTO v_QUOTAD, v_QUOTAM, v_QUOTAY
	FROM BOOKINGALERT WHERE BKAID = v_BKGALERT AND (BKAQUOTAD = -1 OR BKAQUOTAM = -1 OR BKAQUOTAY = -1);

	-- no quota for saturday (except C-19 HC, C-19 TEST (OPDN))
	IF v_QUOTAD = -1 AND TO_CHAR(i_BKGDATE, 'D') = 7 AND v_BKGALERT not in ('25', '70') THEN
		RETURN '0';
	END IF;

	IF v_QUOTAD = -1 THEN
		v_BKGDATE := TO_CHAR(i_BKGDATE, 'DD/MM/YYYY');
		SELECT COUNT(1) INTO v_COUNT FROM HPSTATUS WHERE HPTYPE = 'QUOTADAILY' AND HPKEY = v_BKGALERT AND HPSTATUS = v_BKGDATE;
		IF v_COUNT = 1 THEN
			SELECT TO_NUMBER(HPRMK) - TO_NUMBER(NVL(HPRMK1, '0')) INTO v_QUOTAD FROM HPSTATUS WHERE HPTYPE = 'QUOTADAILY' AND HPKEY = v_BKGALERT AND HPSTATUS = v_BKGDATE;
		ELSE
			v_QUOTAD := 0;
		END IF;
	ELSE
		v_QUOTAD := 0;
	END IF;

	IF v_QUOTAM = -1 THEN
		v_BKGDATE := TO_CHAR(i_BKGDATE, 'MM/YYYY');
		SELECT COUNT(1) INTO v_COUNT FROM HPSTATUS WHERE HPTYPE = 'QUOTAMONTH' AND HPKEY = v_BKGALERT AND HPSTATUS = v_BKGDATE;
		IF v_COUNT = 1 THEN
			SELECT TO_NUMBER(HPRMK) - TO_NUMBER(NVL(HPRMK1, '0')) INTO v_QUOTAM FROM HPSTATUS WHERE HPTYPE = 'QUOTAMONTH' AND HPKEY = v_BKGALERT AND HPSTATUS = v_BKGDATE;
		ELSE
			v_QUOTAM := 0;
		END IF;
	ELSE
		v_QUOTAM := 0;
	END IF;

	IF v_QUOTAY = -1 THEN
		v_BKGDATE := TO_CHAR(i_BKGDATE, 'YYYY');
		SELECT COUNT(1) INTO v_COUNT FROM HPSTATUS WHERE HPTYPE = 'QUOTAYEAR' AND HPKEY = v_BKGALERT AND HPSTATUS = v_BKGDATE;
		IF v_COUNT = 1 THEN
			SELECT TO_NUMBER(HPRMK) - TO_NUMBER(NVL(HPRMK1, '0')) INTO v_QUOTAY FROM HPSTATUS WHERE HPTYPE = 'QUOTAYEAR' AND HPKEY = v_BKGALERT AND HPSTATUS = v_BKGDATE;
		ELSE
			v_QUOTAY := 0;
		END IF;
	ELSE
		v_QUOTAY := 0;
	END IF;

	IF o_errcode >= 0 AND v_QUOTAD > 0 THEN
		v_BKGSDATE := TRUNC(i_BKGDATE);

		IF GET_CURRENT_STECODE = 'HKAH' AND v_BKGALERT = '10' THEN
			-- special handle C-19
			SELECT COUNT(1) INTO v_COUNT
			FROM   BOOKING
			WHERE  BKGSTS IN ('N', 'F')
			AND    BKGALERT IN ('11', '12', '13')
			AND    BKGSDATE >= v_BKGSDATE
			AND    BKGEDATE < v_BKGSDATE + 1;
		ELSIF GET_CURRENT_STECODE = 'HKAH' AND v_BKGALERT = '20' THEN
			-- special handle C-19
			SELECT COUNT(1) INTO v_COUNT
			FROM   BOOKING
			WHERE  BKGSTS IN ('N', 'F')
			AND    BKGALERT IN ('21', '22', '23')
			AND    BKGSDATE >= v_BKGSDATE
			AND    BKGEDATE < v_BKGSDATE + 1;
		ELSIF GET_CURRENT_STECODE = 'HKAH' AND v_BKGALERT = '70' THEN
			-- special handle C-19 HC
			SELECT COUNT(1) INTO v_COUNT
			FROM   BOOKING
			WHERE  BKGSTS IN ('N', 'F')
			AND    BKGALERT IN ('71', '72', '73')
			AND    BKGSDATE >= v_BKGSDATE
			AND    BKGEDATE < v_BKGSDATE + 1;
		ELSE
			SELECT COUNT(1) INTO v_COUNT
			FROM   BOOKING
			WHERE  BKGSTS IN ('N', 'F')
			AND    BKGALERT = v_BKGALERT
			AND    BKGSDATE >= v_BKGSDATE
			AND    BKGEDATE < v_BKGSDATE + 1;
		END IF;

		v_AVAILABLE_D := v_QUOTAD - v_COUNT;
		IF v_AVAILABLE_D <= 0 THEN
			o_errcode := -1;
		ELSE
			IF GET_CURRENT_STECODE = 'HKAH' AND (v_BKGALERT = '11' OR v_BKGALERT = '12' OR v_BKGALERT = '13') THEN
				-- special handle C-19
				v_BKGDATE := TO_CHAR(i_BKGDATE, 'DD/MM/YYYY');
				SELECT COUNT(1) INTO v_COUNT FROM HPSTATUS WHERE HPTYPE = 'QUOTADAILY' AND HPKEY = '10' AND HPSTATUS = v_BKGDATE;
				IF v_COUNT = 1 THEN
					SELECT TO_NUMBER(HPRMK) - TO_NUMBER(NVL(HPRMK1, '0')) INTO v_QUOTAD FROM HPSTATUS WHERE HPTYPE = 'QUOTADAILY' AND HPKEY = '10' AND HPSTATUS = v_BKGDATE;
				ELSE
					v_QUOTAD := 0;
				END IF;

				SELECT COUNT(1) INTO v_COUNT
				FROM   BOOKING
				WHERE  BKGSTS IN ('N', 'F')
				AND    BKGALERT IN ('11', '12', '13')
				AND    BKGSDATE >= v_BKGSDATE
				AND    BKGEDATE < v_BKGSDATE + 1;

				v_AVAILABLE_D2 := v_QUOTAD - v_COUNT;
				IF v_AVAILABLE_D2 <= 0 THEN
					o_errcode := -1;
				ELSIF v_AVAILABLE_D > v_AVAILABLE_D2 THEN
					o_errcode := v_AVAILABLE_D2;
				ELSE
					o_errcode := v_AVAILABLE_D;
				END IF;
			ELSIF GET_CURRENT_STECODE = 'HKAH' AND (v_BKGALERT = '21' OR v_BKGALERT = '22' OR v_BKGALERT = '23') THEN
				-- special handle C-19
				v_BKGDATE := TO_CHAR(i_BKGDATE, 'DD/MM/YYYY');
				SELECT COUNT(1) INTO v_COUNT FROM HPSTATUS WHERE HPTYPE = 'QUOTADAILY' AND HPKEY = '20' AND HPSTATUS = v_BKGDATE;
				IF v_COUNT = 1 THEN
					SELECT TO_NUMBER(HPRMK) - TO_NUMBER(NVL(HPRMK1, '0')) INTO v_QUOTAD FROM HPSTATUS WHERE HPTYPE = 'QUOTADAILY' AND HPKEY = '20' AND HPSTATUS = v_BKGDATE;
				ELSE
					v_QUOTAD := 0;
				END IF;

				SELECT COUNT(1) INTO v_COUNT
				FROM   BOOKING
				WHERE  BKGSTS IN ('N', 'F')
				AND    BKGALERT IN ('21', '22', '23')
				AND    BKGSDATE >= v_BKGSDATE
				AND    BKGEDATE < v_BKGSDATE + 1;

				v_AVAILABLE_D2 := v_QUOTAD - v_COUNT;
				IF v_AVAILABLE_D2 <= 0 THEN
					o_errcode := -1;
				ELSIF v_AVAILABLE_D > v_AVAILABLE_D2 THEN
					o_errcode := v_AVAILABLE_D2;
				ELSE
					o_errcode := v_AVAILABLE_D;
				END IF;
			ELSE
				o_errcode := v_AVAILABLE_D;
			END IF;
		END IF;
	END IF;

	IF o_errcode >= 0 AND v_QUOTAM > 0 THEN
		v_BKGSDATE := TO_DATE('01/' || TO_CHAR(i_BKGDATE, 'MM/YYYY') || ' 00:00:00', 'DD/MM/YYYY HH24:MI:SS');

		SELECT COUNT(1) INTO v_COUNT
		FROM   BOOKING
		WHERE  BKGSTS IN ('N', 'F')
		AND    BKGALERT = v_BKGALERT
		AND    BKGSDATE >= v_BKGSDATE
		AND    BKGEDATE < ADD_MONTHS(v_BKGSDATE, 1);

		v_AVAILABLE_M := v_QUOTAM - v_COUNT;
		IF v_AVAILABLE_M <= 0 THEN
			o_errcode := -1;
		ELSIF v_QUOTAD = 0 OR v_AVAILABLE_D > v_AVAILABLE_M THEN
			o_errcode := v_AVAILABLE_M;
		END IF;
	END IF;

	IF o_errcode >= 0 AND (v_QUOTAY > 0 OR (GET_CURRENT_STECODE = 'HKAH' AND v_BKGALERT = '34')) THEN
		v_BKGSDATE := TO_DATE('01/01/' || TO_CHAR(i_BKGDATE, 'YYYY') || ' 00:00:00', 'DD/MM/YYYY HH24:MI:SS');
		v_BKGEDATE := TO_DATE('31/12/' || TO_CHAR(i_BKGDATE, 'YYYY') || ' 23:59:59', 'DD/MM/YYYY HH24:MI:SS');
		v_BKGSDATE_NOSHOW := TO_DATE(TO_CHAR(SYSDATE, 'DD/MM/YYYY') || ' 00:00:00', 'DD/MM/YYYY HH24:MI:SS');
		v_BKGSDATE_AM := TO_DATE(TO_CHAR(i_BKGDATE, 'DD/MM/YYYY') || ' 00:00:00', 'DD/MM/YYYY HH24:MI:SS');
		v_BKGEDATE_AM := TO_DATE(TO_CHAR(i_BKGDATE, 'DD/MM/YYYY') || ' 11:59:59', 'DD/MM/YYYY HH24:MI:SS');
		v_BKGSDATE_PM := TO_DATE(TO_CHAR(i_BKGDATE, 'DD/MM/YYYY') || ' 12:00:00', 'DD/MM/YYYY HH24:MI:SS');
		v_BKGEDATE_PM := TO_DATE(TO_CHAR(i_BKGDATE, 'DD/MM/YYYY') || ' 23:59:59', 'DD/MM/YYYY HH24:MI:SS');

		IF TO_CHAR(SYSDATE, 'HH24') >= '21' THEN
			v_BKGSDATE_NOSHOW := v_BKGSDATE_NOSHOW + 1;
		END IF;

		SELECT COUNT(1) INTO v_COUNT
		FROM   BOOKING
		WHERE  BKGALERT = v_BKGALERT
		AND  ((BKGSTS = 'F'
		AND    BKGSDATE >= v_BKGSDATE
		AND    BKGEDATE <= v_BKGEDATE)
		OR    (BKGSTS = 'N'
		AND    BKGSDATE >= v_BKGSDATE_NOSHOW
		AND    BKGEDATE <= v_BKGEDATE));

		v_AVAILABLE_Y := v_QUOTAY - v_COUNT;

		-- special handle FLU VACC
		IF v_AVAILABLE_Y > 0 AND GET_CURRENT_STECODE = 'HKAH' AND v_BKGALERT IN ('31', '32', '33', '41', '42', '43') THEN
			IF (v_BKGALERT = '31' OR v_BKGALERT = '41') AND i_DOCCODE IS NOT NULL THEN
				SELECT COUNT(1) INTO v_COUNT FROM HPSTATUS WHERE HPTYPE = 'QUOTAYEAR' AND HPKEY = v_BKGALERT AND HPSTATUS = v_BKGDATE || '_' || i_DOCCODE;
				IF v_COUNT = 1 THEN
					SELECT TO_NUMBER(HPRMK) - TO_NUMBER(NVL(HPRMK1, '0')) INTO v_QUOTAY FROM HPSTATUS WHERE HPTYPE = 'QUOTAYEAR' AND HPKEY = v_BKGALERT AND HPSTATUS = v_BKGDATE || '_' || i_DOCCODE;

					SELECT COUNT(1) INTO v_COUNT
					FROM   BOOKING B
					INNER JOIN SCHEDULE S ON B.SCHID = S.SCHID
					WHERE  S.DOCCODE = i_DOCCODE
					AND    BKGALERT = v_BKGALERT
					AND  ((BKGSTS = 'F'
					AND    BKGSDATE >= v_BKGSDATE
					AND    BKGEDATE <= v_BKGEDATE)
					OR    (BKGSTS = 'N'
					AND    BKGSDATE >= v_BKGSDATE_NOSHOW
					AND    BKGEDATE <= v_BKGEDATE));

					v_AVAILABLE_Y := v_QUOTAY - v_COUNT;
				ELSE
					v_AVAILABLE_Y := 0;
				END IF;
			END IF;

			-- check daily quota for AM/PM
			IF v_AVAILABLE_Y > 0 THEN
				IF TO_CHAR(i_BKGDATE, 'HH24') >= '12' THEN
					SELECT COUNT(1) INTO v_COUNT
					FROM   BOOKING
					WHERE  BKGALERT = v_BKGALERT
					AND  ((BKGSTS = 'F'
					AND    BKGSDATE >= v_BKGSDATE)
					OR    (BKGSTS = 'N'
					AND    BKGSDATE >= v_BKGSDATE_NOSHOW))
					AND    BKGSDATE >= v_BKGSDATE_PM
					AND    BKGEDATE <= v_BKGEDATE_PM;

					IF v_COUNT > 40 THEN
						v_AVAILABLE_Y := 0;
					END IF;
				ELSE
					SELECT COUNT(1) INTO v_COUNT
					FROM   BOOKING
					WHERE  BKGALERT = v_BKGALERT
					AND  ((BKGSTS = 'F'
					AND    BKGSDATE >= v_BKGSDATE)
					OR    (BKGSTS = 'N'
					AND    BKGSDATE >= v_BKGSDATE_NOSHOW))
					AND    BKGSDATE >= v_BKGSDATE_AM
					AND    BKGEDATE <= v_BKGEDATE_AM;

					IF v_COUNT > 20 THEN
						v_AVAILABLE_Y := 0;
					END IF;
				END IF;
			END IF;
		ELSIF GET_CURRENT_STECODE = 'HKAH' AND v_BKGALERT = '34' THEN
			SELECT COUNT(1) INTO v_COUNT
			FROM   BOOKING
			WHERE  BKGALERT IN ('31', '32', '33', '41', '42', '43')
			AND  ((BKGSTS = 'F'
			AND    BKGSDATE >= v_BKGSDATE)
			OR    (BKGSTS = 'N'
			AND    BKGSDATE >= v_BKGSDATE_NOSHOW))
			AND    BKGSDATE >= v_BKGSDATE_AM
			AND    BKGEDATE <= v_BKGEDATE_AM;

			IF v_COUNT > 20 THEN
				v_DISPLAY_MESSAGE := '0';
			ELSE
				v_DISPLAY_MESSAGE := TO_CHAR(20 - v_COUNT);
			END IF;
			v_DISPLAY_MESSAGE := v_DISPLAY_MESSAGE || '(AM) ';

			SELECT COUNT(1) INTO v_COUNT
			FROM   BOOKING
			WHERE  BKGALERT IN ('31', '32', '33', '41', '42', '43')
			AND  ((BKGSTS = 'F'
			AND    BKGSDATE >= v_BKGSDATE)
			OR    (BKGSTS = 'N'
			AND    BKGSDATE >= v_BKGSDATE_NOSHOW))
			AND    BKGSDATE >= v_BKGSDATE_PM
			AND    BKGEDATE <= v_BKGEDATE_PM;

			IF v_COUNT > 40 THEN
				v_DISPLAY_MESSAGE := v_DISPLAY_MESSAGE || '0';
			ELSE
				v_DISPLAY_MESSAGE := v_DISPLAY_MESSAGE || TO_CHAR(40 - v_COUNT);
			END IF;
			v_DISPLAY_MESSAGE := v_DISPLAY_MESSAGE || '(PM)';

			RETURN v_DISPLAY_MESSAGE;
		END IF;

		IF v_AVAILABLE_Y <= 0 THEN
			o_errcode := -1;
		ELSE
			o_errcode := v_AVAILABLE_Y;
		END IF;
	END IF;

	IF o_errcode < 0 THEN
		o_errcode := 0;
	END IF;

	RETURN TO_CHAR(o_errcode);
EXCEPTION
WHEN OTHERS THEN
	DBMS_OUTPUT.PUT_LINE('An ERROR was encountered - '||SQLCODE||' -ERROR- '||SQLERRM);
	RETURN 0;
END NHS_UTL_ALERTQUOTA;
/
