create or replace FUNCTION "NHS_LIS_DOCTORSEARCH" (
	v_DOCCODE     IN VARCHAR2,
	v_DOCFNAME    IN VARCHAR2,
	v_DOCGNAME    IN VARCHAR2,
	v_DOCSEX      IN VARCHAR2,
	v_DOCTYPE     IN VARCHAR2,
	v_SPCCODE     IN VARCHAR2,
	v_DOCBDATE    IN VARCHAR2,
	v_DOCSTS      IN VARCHAR2,
	v_DOCCOMP     IN VARCHAR2,
	v_MSTRDOCCODE IN VARCHAR2,
	v_DOCEMAIL    IN VARCHAR2,
	v_filterDoc   IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
  	SQLSTR VARCHAR2(1000);
BEGIN
  	SQLSTR := 'SELECT '''', DR.MSTRDOCCODE, DR.DOCCODE, DR.DOCFNAME, DR.DOCGNAME, DR.COMPANY,DR.DOCSEX, SP.SPCNAME, DR.SPCCODE, DR.DOCMTEL,
			DR.DOCPTEL, DR.DOCHTEL, DR.DOCOTEL, DR.DOCEMAIL, DR.DOCTYPE, DR.DOCOFFADD1, DR.DOCOFFADD2, DR.DOCOFFADD3, DR.DOCOFFADD4,
			DR.DOCTDATE
		FROM DOCTOR DR, SPEC SP
		WHERE DR.SPCCODE = SP.SPCCODE(+) ';

	IF v_DOCCODE IS NOT NULL THEN
		SQLSTR := SQLSTR || 'AND (DR.DOCCODE LIKE ''%' || v_DOCCODE || '%'') ';
	END IF;

	IF v_DOCFNAME IS NOT NULL THEN
		SQLSTR := SQLSTR || 'AND (DR.DOCFNAME LIKE '''|| v_DOCFNAME || '%'') ';
	END IF;

	IF v_DOCGNAME IS NOT NULL THEN
		SQLSTR := SQLSTR || 'AND (DR.DOCGNAME LIKE ''%' || v_DOCGNAME || '%'') ';
	END IF;

	IF v_DOCSEX IS NOT NULL THEN
		SQLSTR := SQLSTR || 'AND (DR.DOCSEX = ''' || v_DOCSEX || ''') ';
	END IF;

	IF v_DOCTYPE IS NOT NULL THEN
		SQLSTR := SQLSTR || 'AND (DR.DOCTYPE = ''' || v_DOCTYPE || ''') ';
	END IF;

	IF v_SPCCODE IS NOT NULL THEN
		SQLSTR := SQLSTR || 'AND (DR.SPCCODE LIKE ''%' || v_SPCCODE || '%'') ';
	END IF;

	IF v_DOCBDATE IS NOT NULL THEN
		SQLSTR := SQLSTR || 'AND (DR.DOCBDATE = TO_DATE('''||v_DOCBDATE||''', ''DD/MM/YYYY'')) ';
	END IF;

	IF v_DOCSTS IS NOT NULL THEN
		SQLSTR := SQLSTR || 'AND (DR.DOCSTS = '''|| v_DOCSTS ||''') ';
	END IF;

	IF v_DOCCOMP IS NOT NULL THEN
		SQLSTR := SQLSTR || 'AND (DR.COMPANY LIKE ''' || v_DOCCOMP || '%'') ';
--		SQLSTR := SQLSTR || 'AND (DR.COMPANY = '''|| v_DOCCOMP ||''') ';
	END IF;

	IF v_DOCEMAIL IS NOT NULL THEN
		SQLSTR := SQLSTR || 'AND (DR.DOCEMAIL LIKE ''%' || v_DOCEMAIL || '%'') ';
	END IF;

	IF v_MSTRDOCCODE IS NOT NULL THEN
		SQLSTR := SQLSTR || 'AND (DR.MSTRDOCCODE = ''' || v_MSTRDOCCODE || ''' OR DR.DOCCODE = ''' || v_MSTRDOCCODE ||''') ';
	END IF;

	IF v_filterDoc = 'Y' THEN
		SQLSTR := SQLSTR || NHS_UTL_GETSKIPDOCCODE('DR.DOCCODE');
	END IF;
	SQLSTR := SQLSTR || ' ORDER BY DECODE(DR.MSTRDOCCODE, NULL, ''1'', ''2''), DR.MSTRDOCCODE, DR.DOCCODE ';

	--DBMS_OUTPUT.PUT_LINE(SQLSTR);
	OPEN OUTCUR FOR SQLSTR;

	RETURN OUTCUR;
END NHS_LIS_DOCTORSEARCH;
/
