CREATE OR REPLACE FUNCTION NHS_UTL_GETSKIPDOCCODE (
	i_DocCodeField IN VARCHAR2
)
	RETURN VARCHAR2
IS
	v_noOfRecord NUMBER;
	v_IGNOREDOCCODE VARCHAR2(2000) := '';
BEGIN
	SELECT COUNT(1) INTO v_noOfRecord
	FROM SYSPARAM
	WHERE PARCDE = 'SKIPDOC';

	IF v_noOfRecord > 0 THEN
		FOR R IN (
			SELECT PARAM1 INTO v_IGNOREDOCCODE
			FROM SYSPARAM
			WHERE PARCDE = 'SKIPDOC'
		)
		LOOP
			v_IGNOREDOCCODE := v_IGNOREDOCCODE || ' AND UPPER(' || i_DocCodeField || ') NOT LIKE UPPER(''' || R.PARAM1 || ''') ';
		END LOOP;
	END IF;

	RETURN v_IGNOREDOCCODE;
END NHS_UTL_GETSKIPDOCCODE;
/
