CREATE OR REPLACE FUNCTION "NHS_GET_SLIPLOCK"
(
	v_SLIPNO VARCHAR2
)
	RETURN Types.cursor_type
AS
	OUTCUR types.cursor_type;
BEGIN
	OPEN OUTCUR FOR
	SELECT R.USRID, U.USRNAME
	FROM   RLOCK R, USR U
	WHERE  R.USRID = U.USRID
	AND    UPPER(R.RLKTYPE) = UPPER('Slip')
	AND    R.RLKKEY = v_SLIPNO;
	RETURN OUTCUR;
END NHS_GET_SLIPLOCK;
/


