CREATE OR REPLACE FUNCTION "NHS_UTL_SLPPAYALLGETPAYSQL" (
	v_SLPNO     IN VARCHAR2,
	v_WITHZERO  IN BOOLEAN
)
	RETURN VARCHAR2
AS
	SQLSTR VARCHAR2(5000);
	SLIPTX_TYPE_CREDIT VARCHAR2(1) := 'C';
	SLIPTX_TYPE_REFUND VARCHAR2(1) := 'R';
	SLIPTX_TYPE_PAYMENT_C VARCHAR2(1) := 'S';
	SLIPTX_TYPE_DEPOSIT_I VARCHAR2(1) := 'I';
	SLIPTX_STATUS_NORMAL VARCHAR2(1) := 'N';
	SLIPTX_TYPE_PAYMENT_A VARCHAR2(1) := 'P';
	ARTX_STATUS_NORMAL VARCHAR2(1) := 'N';
BEGIN
	-- for credit and cash
	SQLSTR := '
			SELECT T.STNTYPE || T.STNID AS KEY, T.STNTYPE, T.ITMCODE,
				T.STNDESC, T.STNXREF, T.STNCDATE, T.STNID AS PAYREF,
				'''' AS ARCCODE, T.STNNAMT AS STNNAMT
			FROM SLIPTX T, SLPPAYDTL SPD ';

	IF v_SLPNO IS NULL THEN
		SQLSTR := SQLSTR || 'WHERE 1 = 2 ';
	ELSE
		SQLSTR := SQLSTR ||
			'WHERE T.SLPNO = ''' || v_SLPNO || '''
				AND T.STNTYPE IN (
					''' || SLIPTX_TYPE_CREDIT || ''',
					''' || SLIPTX_TYPE_REFUND || ''',
					''' || SLIPTX_TYPE_PAYMENT_C || ''',
					''' || SLIPTX_TYPE_DEPOSIT_I || ''')
				AND T.STNID = SPD.PAYREF(+)
				AND T.STNADOC IS NULL
				AND T.STNSTS = ''' || SLIPTX_STATUS_NORMAL || ''' ';
	END IF;

	SQLSTR := SQLSTR ||
			'GROUP BY T.STNTYPE || T.STNID, T.STNTYPE, T.ITMCODE, T.STNDESC,
				T.STNNAMT, T.STNXREF, T.STNCDATE, T.STNID ';

	IF NOT v_WITHZERO THEN
		SQLSTR := SQLSTR || 'HAVING T.STNNAMT <> 0 ';
	END IF;

	-- for AR
	SQLSTR := SQLSTR ||
			'UNION ALL
				SELECT T.STNTYPE || C.ATXID AS KEY, T.STNTYPE, T.ITMCODE,
					T.STNDESC, T.STNXREF, C.ATXCDATE AS STNCDATE, C.ATXID AS PAYREF,
					C.ARCCODE, C.ATXAMT AS STNNAMT
				FROM SLIPTX T, ARTX D, ARTX C,
					(SELECT * FROM SLPPAYDTL
					  WHERE SLPNO = ''' || v_SLPNO || '''
					  AND STNTYPE = ''' || SLIPTX_TYPE_PAYMENT_A || ''') SPD ';

	IF v_SLPNO IS NULL THEN
		SQLSTR := SQLSTR || 'WHERE 1 = 2 ';
	ELSE
		SQLSTR := SQLSTR ||
			'WHERE T.SLPNO = ''' || v_SLPNO || '''
			   AND T.STNTYPE = ''' || SLIPTX_TYPE_PAYMENT_A || '''
			   AND T.STNXREF = D.ATXID
			   AND D.SLPNO = T.SLPNO
			   AND C.SLPNO = T.SLPNO
			   AND D.ATXID = C.ATXREFID
			   AND C.ATXID = SPD.PAYREF(+)
			   AND T.STNSTS = ''' || SLIPTX_STATUS_NORMAL || '''
			   AND C.ARPID IS NOT NULL
			   AND D.ATXSTS = ''' || ARTX_STATUS_NORMAL || '''
			   AND C.ATXSTS = ''' || ARTX_STATUS_NORMAL || '''
			   AND T.STNADOC IS NULL ';
	END IF;

	SQLSTR := SQLSTR ||
			  'GROUP BY T.STNTYPE || C.ATXID, T.STNTYPE, T.ITMCODE, T.STNDESC,
						C.ATXAMT, T.STNXREF, C.ATXCDATE, C.ATXID, C.ARCCODE ';

	IF NOT v_WITHZERO THEN
		SQLSTR := SQLSTR ||
				  'HAVING C.ATXAMT <> 0 ';
	END IF;

	SQLSTR := SQLSTR || 'ORDER BY KEY DESC ';

	RETURN SQLSTR;
END NHS_UTL_SLPPAYALLGETPAYSQL;
/
