CREATE OR REPLACE FUNCTION "NHS_UTL_SMSMESSAGE" (
	i_Language IN VARCHAR2,
	i_SMSID    IN VARCHAR2,
	i_DOCCODE  IN VARCHAR2,
	i_BookDate IN DATE
)
	RETURN VARCHAR2
AS
	outcur Types.cursor_type;
	v_BOOKING_MSG VARCHAR2(1000);
BEGIN
	v_BOOKING_MSG := NHS_UTL_ERRORMESSAGE('MOBILESMS', i_SMSID, i_Language);

	IF i_DOCCODE IS NOT NULL THEN
    IF i_SMSID NOT IN ('3','4','5','6') THEN   
    	v_BOOKING_MSG := REPLACE(v_BOOKING_MSG, '{0}', NHS_UTL_GETDOCTORNAME(i_Language, i_DOCCODE));
    ELSE 
      v_BOOKING_MSG := REPLACE(v_BOOKING_MSG, '{0}', i_DOCCODE);
    END IF;
	END IF;

	IF i_BookDate IS NOT NULL THEN
		IF i_SMSID = 'BOOKINGSMS' OR i_SMSID IN ('3','4','5','6') THEN
					v_BOOKING_MSG := REPLACE(v_BOOKING_MSG, '{1}', NHS_UTL_SMSDATEFORMAT_MODULE(i_Language, i_BookDate, 'DATE_APP'));
		ELSE
          v_BOOKING_MSG := REPLACE(v_BOOKING_MSG, '{1}', NHS_UTL_SMSDATEFORMAT(i_Language, i_BookDate));
		END IF;
	END IF;

	RETURN v_BOOKING_MSG;

END NHS_UTL_SMSMESSAGE;