create or replace FUNCTION "NHS_UTL_GETDOCCHGCODE" (
	v_SlpNo IN VARCHAR2
)
	RETURN VARCHAR2
AS
	CHGCODECUR    TYPES.CURSOR_TYPE;
	P_CHGCODETEMP VARCHAR2(1000);
	P_CHGCODE     VARCHAR2(1000);
BEGIN
	OPEN CHGCODECUR FOR
		SELECT st.ItmCode
		FROM   SlipTx st, Item i
		WHERE  st.SLPNO = v_SlpNo
		AND    st.ItmCode = i.ItmCode
		AND    i.ItmCode in ('DFGC','DFSC','DFE1','DFE2','DFE3','DFE4','DFE5','DFP','DFHD','DFH','DF1','DFCA','DFUS','DFSU','DF')
		ORDER BY st.ItmCode;
	LOOP
		FETCH CHGCODECUR
		INTO P_CHGCODETEMP;
		EXIT WHEN CHGCODECUR%NOTFOUND;
		P_CHGCODE := P_CHGCODE || ',' || P_CHGCODETEMP;
	END LOOP;
	CLOSE CHGCODECUR;

	IF LENGTH(P_CHGCODE) > 1 THEN
		RETURN SUBSTR(P_CHGCODE, 2);
	END IF;
	RETURN '';
END;
/
