create or replace FUNCTION NHS_UTL_BOOKING_NEWCASE (
	i_SCHID IN VARCHAR2,
	i_SLTID IN VARCHAR2
)
	RETURN NUMBER
AS
	v_COUNT NUMBER;
BEGIN
	SELECT COUNT(1) INTO v_COUNT
	FROM BOOKING
	WHERE SCHID = i_SCHID
	AND   SLTID = i_SLTID
	AND   PATNO IS NULL
	AND   BKGSTS IN ('N', 'F');

	RETURN v_COUNT;

END NHS_UTL_BOOKING_NEWCASE;
/
