CREATE OR REPLACE FUNCTION "NHS_ACT_MERGESLIP" (
	i_ACTION  IN VARCHAR2,
	i_SLPNO   IN VARCHAR2,
	i_SLPNO1  IN VARCHAR2,
	i_SLPNO2  IN VARCHAR2,
	i_SLPNO3  IN VARCHAR2,
	i_SLPNO4  IN VARCHAR2,
	i_SLPNO5  IN VARCHAR2,
	i_SLPNO6  IN VARCHAR2,
	i_SLPNO7  IN VARCHAR2,
	i_SLPNO8  IN VARCHAR2,
	i_SLPNO9  IN VARCHAR2,
	i_SLPNO10 IN VARCHAR2,
	i_USRID   IN VARCHAR2,
	o_ERRMSG  OUT VARCHAR2
)
	RETURN NUMBER
AS
	v_SEQID NUMBER;
	v_Count NUMBER;
	v_SlipNo VARCHAR2(20);
	v_SlipMerge VARCHAR2(100);
	o_errcode NUMBER;
	MERGESLIPCUR TYPES.CURSOR_TYPE;
BEGIN
	v_SEQID := 0;
	o_ERRMSG := 'OK';
	o_errcode := 0;

	IF i_ACTION = 'ADD' THEN
		IF i_SLPNO1 IS NOT NULL
				OR i_SLPNO2 IS NOT NULL OR i_SLPNO3 IS NOT NULL
				OR i_SLPNO4 IS NOT NULL OR i_SLPNO5 IS NOT NULL
				OR i_SLPNO6 IS NOT NULL OR i_SLPNO7 IS NOT NULL
				OR i_SLPNO8 IS NOT NULL OR i_SLPNO9 IS NOT NULL
				OR i_SLPNO10 IS NOT NULL THEN

			SELECT COUNT(1) INTO v_Count
			FROM   SLIPMERGE
			WHERE  SLPNO = i_SLPNO;

			IF v_Count > 0 THEN
				SELECT SEQID INTO v_SEQID
				FROM   SLIPMERGE
				WHERE  SLPNO = i_SLPNO;
			ELSE
				SELECT SEQ_SLIPMERGE.NEXTVAL INTO v_SEQID FROM DUAL;
			END IF;

			IF v_Count = 0 THEN
				INSERT INTO SLIPMERGE (SLPNO, SEQID, MRGDATE, USRID) VALUES (i_SLPNO, v_SEQID, SYSDATE, i_USRID);
			END IF;

			IF i_SLPNO1 IS NOT NULL THEN
				SELECT COUNT(1) INTO v_Count
				FROM   SLIPMERGE
				WHERE  SLPNO = i_SLPNO1;

				IF v_Count = 0 THEN
					INSERT INTO SLIPMERGE (SLPNO, SEQID, MRGDATE, USRID) VALUES (i_SLPNO1, v_SEQID, SYSDATE, i_USRID);
				END IF;
			END IF;

			IF i_SLPNO2 IS NOT NULL THEN
				SELECT COUNT(1) INTO v_Count
				FROM   SLIPMERGE
				WHERE  SLPNO = i_SLPNO2;

				IF v_Count = 0 THEN
					INSERT INTO SLIPMERGE (SLPNO, SEQID, MRGDATE, USRID) VALUES (i_SLPNO2, v_SEQID, SYSDATE, i_USRID);
				END IF;
			END IF;

			IF i_SLPNO3 IS NOT NULL THEN
				SELECT COUNT(1) INTO v_Count
				FROM   SLIPMERGE
				WHERE  SLPNO = i_SLPNO3;

				IF v_Count = 0 THEN
					INSERT INTO SLIPMERGE (SLPNO, SEQID, MRGDATE, USRID) VALUES (i_SLPNO3, v_SEQID, SYSDATE, i_USRID);
				END IF;
			END IF;

			IF i_SLPNO4 IS NOT NULL THEN
				SELECT COUNT(1) INTO v_Count
				FROM   SLIPMERGE
				WHERE  SLPNO = i_SLPNO4;

				IF v_Count = 0 THEN
					INSERT INTO SLIPMERGE (SLPNO, SEQID, MRGDATE, USRID) VALUES (i_SLPNO4, v_SEQID, SYSDATE, i_USRID);
				END IF;
			END IF;

			IF i_SLPNO5 IS NOT NULL THEN
				SELECT COUNT(1) INTO v_Count
				FROM   SLIPMERGE
				WHERE  SLPNO = i_SLPNO5;

				IF v_Count = 0 THEN
					INSERT INTO SLIPMERGE (SLPNO, SEQID, MRGDATE, USRID) VALUES (i_SLPNO5, v_SEQID, SYSDATE, i_USRID);
				END IF;
			END IF;

			IF i_SLPNO6 IS NOT NULL THEN
				SELECT COUNT(1) INTO v_Count
				FROM   SLIPMERGE
				WHERE  SLPNO = i_SLPNO6;

				IF v_Count = 0 THEN
					INSERT INTO SLIPMERGE (SLPNO, SEQID, MRGDATE, USRID) VALUES (i_SLPNO6, v_SEQID, SYSDATE, i_USRID);
				END IF;
			END IF;

			IF i_SLPNO7 IS NOT NULL THEN
				SELECT COUNT(1) INTO v_Count
				FROM   SLIPMERGE
				WHERE  SLPNO = i_SLPNO7;

				IF v_Count = 0 THEN
					INSERT INTO SLIPMERGE (SLPNO, SEQID, MRGDATE, USRID) VALUES (i_SLPNO7, v_SEQID, SYSDATE, i_USRID);
				END IF;
			END IF;

			IF i_SLPNO8 IS NOT NULL THEN
				SELECT COUNT(1) INTO v_Count
				FROM   SLIPMERGE
				WHERE  SLPNO = i_SLPNO8;

				IF v_Count = 0 THEN
					INSERT INTO SLIPMERGE (SLPNO, SEQID, MRGDATE, USRID) VALUES (i_SLPNO8, v_SEQID, SYSDATE, i_USRID);
				END IF;
			END IF;

			IF i_SLPNO9 IS NOT NULL THEN
				SELECT COUNT(1) INTO v_Count
				FROM   SLIPMERGE
				WHERE  SLPNO = i_SLPNO9;

				IF v_Count = 0 THEN
					INSERT INTO SLIPMERGE (SLPNO, SEQID, MRGDATE, USRID) VALUES (i_SLPNO9, v_SEQID, SYSDATE, i_USRID);
				END IF;
			END IF;

			IF i_SLPNO10 IS NOT NULL THEN
				SELECT COUNT(1) INTO v_Count
				FROM   SLIPMERGE
				WHERE  SLPNO = i_SLPNO10;

				IF v_Count = 0 THEN
					INSERT INTO SLIPMERGE (SLPNO, SEQID, MRGDATE, USRID) VALUES (i_SLPNO10, v_SEQID, SYSDATE, i_USRID);
				END IF;
			END IF;
		END IF;
	ELSIF i_ACTION = 'DEL' THEN
		SELECT COUNT(1) INTO v_Count
		FROM SLIPMERGE
		WHERE SLPNO = i_SLPNO;

		IF v_Count > 0 THEN
			SELECT SEQID INTO v_SEQID
			FROM   SLIPMERGE
			WHERE  SLPNO = i_SLPNO;

			OPEN MERGESLIPCUR FOR
				SELECT SLPNO
				FROM   SLIPMERGE
				WHERE  SEQID = v_SEQID;
			LOOP
				FETCH MERGESLIPCUR
				INTO v_SlipNo;
				EXIT WHEN MERGESLIPCUR%NOTFOUND;
				IF v_SlipMerge IS NULL THEN
					v_SlipMerge := v_SlipNo;
				ELSE
					v_SlipMerge := v_SlipMerge || ',' || v_SlipNo;
				END IF;
			END LOOP;
			CLOSE MERGESLIPCUR;

			DELETE FROM SLIPMERGE
			WHERE SEQID = v_SEQID;

			o_errcode := NHS_ACT_SYSLOG('DEL', 'SLIPMERGE', v_SlipMerge, 'Unmerge slip by user', i_USRID, NULL, o_errmsg);
		END IF;
	END IF;

	RETURN v_SEQID;
EXCEPTION
WHEN OTHERS THEN
	ROLLBACK;
	dbms_output.put_line('An ERROR was encountered - '||SQLCODE||' -ERROR- '||SQLERRM);
	o_ERRMSG := 'Fail to merge due to ' || SQLERRM;

	RETURN -999;
END NHS_ACT_MERGESLIP;
/
