CREATE OR REPLACE FUNCTION "NHS_SMS_VACCINEAPPOINTMENT" (
	i_language IN VARCHAR2,
	i_bkgID    IN VARCHAR2
)
	RETURN VARCHAR2
AS
	outcur Types.cursor_type;
	v_DOCCODE DOCTOR.DOCCODE%TYPE;
	v_PATNO BOOKING.PATNO%TYPE;
	v_BKGSDATE BOOKING.BKGSDATE%TYPE;
	v_BKGALERT BOOKING.BKGALERT%TYPE;
	v_BKGID1 BOOKING.BKGID%TYPE;
	v_BKGID2 BOOKING.BKGID%TYPE;
	v_BOOKINGTIME1 DATE;
	v_BOOKINGTIME2 DATE;
	v_BOOKING_MSG VARCHAR2(1000);
	v_COUNT NUMBER;

	STATUS_NORMAL VARCHAR2(1) := 'N';
BEGIN
	SELECT COUNT(1) INTO v_COUNT FROM BOOKING WHERE BKGID = i_bkgid AND BKGSTS = STATUS_NORMAL;

	IF v_COUNT = 1 THEN
		SELECT PATNO, BKGSDATE, BKGALERT INTO v_PATNO, v_BKGSDATE, v_BKGALERT
		FROM BOOKING B
		WHERE  BKGID = i_bkgid
		AND    BKGSTS = STATUS_NORMAL;

		IF v_PATNO IS NOT NULL THEN
			SELECT COUNT(1) INTO v_COUNT
			FROM   HPSTATUS
			WHERE  HPSTATUS = v_PATNO
			AND    HPTYPE = 'VACCINE'
			AND    HPKEY = 'COVID19';

			IF v_COUNT = 1 THEN
				SELECT HP.HPRMK1, HP.HPRMK2
				INTO   v_BKGID1, v_BKGID2
				FROM   BOOKING B
				LEFT JOIN HPSTATUS HP ON B.PATNO = HP.HPSTATUS
				WHERE  B.BKGID = i_bkgid
				AND    HPTYPE = 'VACCINE'
				AND    HPKEY = 'COVID19';
			END IF;

			IF v_BKGID1 IS NOT NULL THEN
				SELECT COUNT(1) INTO v_COUNT
				FROM BOOKING B
				LEFT JOIN SCHEDULE S ON B.SCHID = S.SCHID
				WHERE BKGID = v_BKGID1
				AND   BKGSTS = STATUS_NORMAL
				AND   B.BKGSDATE > SYSDATE;

				IF v_COUNT = 1 THEN
					SELECT B.BKGSDATE
					INTO   v_BOOKINGTIME1
					FROM BOOKING B
					LEFT JOIN SCHEDULE S ON B.SCHID = S.SCHID
					WHERE BKGID = v_BKGID1
					AND   BKGSTS = STATUS_NORMAL
					AND   B.BKGSDATE > SYSDATE;
				END IF;
			END IF;

			IF v_BKGID2 IS NOT NULL THEN
				SELECT COUNT(1) INTO v_COUNT
				FROM BOOKING B
				LEFT JOIN SCHEDULE S ON B.SCHID = S.SCHID
				WHERE BKGID = v_BKGID2
				AND   BKGSTS = STATUS_NORMAL
				AND   B.BKGSDATE > SYSDATE;

				IF v_COUNT = 1 THEN
					SELECT B.BKGSDATE
					INTO   v_BOOKINGTIME2
					FROM BOOKING B
					LEFT JOIN SCHEDULE S ON B.SCHID = S.SCHID
					WHERE BKGID = v_BKGID2
					AND   BKGSTS = STATUS_NORMAL
					AND   B.BKGSDATE > SYSDATE;
				END IF;
			END IF;
		ELSE
			IF v_BKGALERT = '61' OR v_BKGALERT = '63' THEN
				v_BOOKINGTIME1 := v_BKGSDATE;
			ELSIF v_BKGALERT = '62' THEN
				v_BOOKINGTIME2 := v_BKGSDATE;
			END IF;
		END IF;


		IF v_BOOKINGTIME1 IS NOT NULL AND v_BOOKINGTIME2 IS NOT NULL THEN
			v_BOOKING_MSG := NHS_UTL_SMSMESSAGE(i_language, 'COVIDALL', v_DOCCODE, v_BOOKINGTIME1);

			v_BOOKING_MSG := REPLACE(v_BOOKING_MSG, '{2}', NHS_UTL_SMSDATEFORMAT(i_language, v_BOOKINGTIME2, 'DATE'));
		ELSIF v_BOOKINGTIME1 IS NOT NULL THEN
			v_BOOKING_MSG := NHS_UTL_SMSMESSAGE(i_language, 'COVID1', v_DOCCODE, v_BOOKINGTIME1);
		ELSE
			v_BOOKING_MSG := NHS_UTL_SMSMESSAGE(i_language, 'COVID2', v_DOCCODE, v_BOOKINGTIME2);
		END IF;

		RETURN v_BOOKING_MSG;
	END IF;

	RETURN NULL;

END NHS_SMS_VACCINEAPPOINTMENT;
/
