CREATE OR REPLACE FUNCTION "NHS_LIS_GETPRIMARYSLIP" (
	v_SLIPNO IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR  TYPES.CURSOR_TYPE;
	v_CNT   NUMBER;
	v_SEQID NUMBER;
BEGIN
	SELECT COUNT(1) INTO v_CNT FROM SLIPMERGE WHERE SLPNO = v_SLIPNO;
	IF v_CNT > 0 THEN
		SELECT SEQID
		INTO   v_SEQID
		FROM   SLIPMERGE
		WHERE  SLPNO = v_SLIPNO
		ORDER BY MRGDATE DESC;
	ELSE
		v_SEQID := -1;
	END IF;

	OPEN OUTCUR FOR
		SELECT SLPNO
		FROM   SLIPMERGE
		WHERE  SEQID = v_SEQID
		AND    USRID = 'PRIMARYSLP';
	RETURN OUTCUR;
END NHS_LIS_GETPRIMARYSLIP;
/
