CREATE OR REPLACE FUNCTION "NHS_UTL_MOVEPACKAGETOSLIP" (
	v_SLPNO   IN VARCHAR2,
	v_PTNID   IN VARCHAR2,
	I_USRID   IN VARCHAR2
)
	RETURN NUMBER
AS
	O_ERRCODE NUMBER;
	v_ERRMSG VARCHAR2(100);
	RS_PKG PKGTX%ROWTYPE;
	RS_SLIP SLIP%ROWTYPE;
	v_ITMTYPE ITEM.ITMTYPE%TYPE;
	v_RPTLVL PKGTX.PTNRLVL%TYPE;
	v_DISCOUNT SLIP.SLPHDISC%TYPE;
	v_CPSID ARCODE.CPSID%TYPE;
	v_RATE1 ITEMCHG.ITCAMT1%TYPE;
	v_RATE2 ITEMCHG.ITCAMT2%TYPE;
	v_RATE3 ITEMCHG.ITCAMT1%TYPE;
	v_RATE4 ITEMCHG.ITCAMT2%TYPE;
	v_ITMRLVL ITEM.ITMRLVL%TYPE;
	v_Cpspct NUMBER;
	v_COUNT NUMBER;
	v_TxDate VARCHAR2(10);

	TYPE_DOCTOR VARCHAR2(1) := 'D';
	TYPE_HOSPITAL VARCHAR2(1) := 'H';
	TXN_SPECIAL_REPORTLEVEL NUMBER := 4;
BEGIN
	O_ERRCODE := 0;

	SELECT * INTO RS_SLIP FROM SLIP WHERE SLPNO = v_SLPNO;

	SELECT * INTO RS_PKG FROM PKGTX WHERE PTNID = TO_NUMBER(v_PTNID);

	SELECT ITMTYPE INTO v_ITMTYPE FROM ITEM WHERE ITMCODE = RS_PKG.ITMCODE;

	SELECT COUNT(1) INTO v_COUNT
	FROM   SLIP S, ARCODE A
	WHERE  S.ARCCODE = A.ARCCODE
	AND    S.SLPNO = v_SLPNO;

	IF v_COUNT > 0 THEN
		SELECT CPSID INTO v_CPSID
		FROM   SLIP S, ARCODE A
		WHERE  S.ARCCODE = A.ARCCODE
		AND    S.SLPNO = v_SLPNO;
	END IF;

	IF RS_PKG.PTNTDATE IS NOT NULL THEN
		v_TxDate := TO_CHAR(RS_PKG.PTNTDATE, 'DD/MM/YYYY');
	ELSE
		v_TxDate := TO_CHAR(SYSDATE, 'DD/MM/YYYY');
	END IF;

	NHS_SYS_LOOKUPITEMCHARGE(v_TxDate, RS_PKG.ITMCODE, RS_SLIP.SLPTYPE, RS_PKG.ACMCODE, TRUE, v_ITMRLVL, v_RATE1, v_RATE2, v_RATE3, v_RATE4, v_CPSID, v_Cpspct, NULL);

	--Get Discount
	IF v_CPSID IS NULL OR LENGTH(v_CPSID) = 0 THEN
		IF v_ITMTYPE = TYPE_DOCTOR THEN
			v_DISCOUNT := RS_SLIP.SLPDDISC;
		ELSIF v_ITMTYPE = TYPE_HOSPITAL THEN
			v_DISCOUNT := RS_SLIP.SLPHDISC;
		ELSE
			v_DISCOUNT := RS_SLIP.SLPSDISC;
		END IF;
	ELSE
		IF v_Cpspct IS NULL OR LENGTH(v_Cpspct) = 0 THEN
			IF v_ITMTYPE = TYPE_DOCTOR THEN
				v_DISCOUNT := RS_SLIP.SLPDDISC;
			ELSIF v_ITMTYPE = TYPE_HOSPITAL THEN
				v_DISCOUNT := RS_SLIP.SLPHDISC;
			ELSE
				v_DISCOUNT := RS_SLIP.SLPSDISC;
			END IF;
		ELSE
			v_DISCOUNT := v_Cpspct;
		END IF;
	END IF;

	IF RS_PKG.PTNRLVL = TXN_SPECIAL_REPORTLEVEL THEN
		v_RPTLVL := v_ITMRLVL;---get from itemchg from NHS_ACT_ADD_ENTRY
	ELSE
		v_RPTLVL := RS_PKG.PTNRLVL;
	END IF;

	o_errcode := NHS_UTL_ADDENTRY(
		v_SLPNO,
		RS_PKG.ITMCODE,
		v_ITMTYPE,
		'D',
		RS_PKG.PTNOAMT,
		RS_PKG.PTNBAMT,
		RS_PKG.DOCCODE,
		v_RPTLVL,
		RS_PKG.ACMCODE,
		v_DISCOUNT,
		NULL,
		SYSDATE,
		RS_PKG.PTNTDATE,
		RS_PKG.PTNDESC,
		RS_PKG.PTNSTS,
		NULL,
		NULL,
		FALSE,
		NULL,
		RS_PKG.DIXREF,
		RS_PKG.PTNDIFLAG IS NOT NULL,
		RS_PKG.PTNCPSFLAG,
		NULL,
		RS_PKG.UNIT,
		RS_PKG.PTNDESC1,
		RS_PKG.IREFNO,
		NULL,
		I_USRID);

	IF O_ERRCODE < 0 THEN
		O_ERRCODE := -1;
		RETURN O_ERRCODE;
	ELSE
		O_ERRCODE := NHS_ACT_SETPACKAGEENTRY('MOD', v_PTNID, 'M', NULL, v_ERRMSG);
	END IF;

	IF O_ERRCODE < 0 THEN
		O_ERRCODE:=-1;
		RETURN O_ERRCODE;
	END IF;

	RETURN o_errcode;
EXCEPTION
WHEN OTHERS THEN
	o_errcode := -1;
	DBMS_OUTPUT.PUT_LINE('An ERROR was encountered - '||SQLCODE||' -ERROR- '||SQLERRM);
	RETURN o_errcode;
end NHS_UTL_MOVEPACKAGETOSLIP;
/
