CREATE OR REPLACE FUNCTION "NHS_SMS_PATIENTAPPOINTMENT" (
	i_language IN VARCHAR2,
	i_bkgID    IN VARCHAR2
)
	RETURN VARCHAR2
AS
	outcur Types.cursor_type;
	v_DOCCODE DOCTOR.DOCCODE%TYPE;
	v_BOOKINGTIME DATE;
	v_COUNT NUMBER;
BEGIN
	SELECT COUNT(1) INTO v_COUNT FROM BOOKING WHERE BKGID = i_bkgid;

	IF v_COUNT = 1 THEN
		SELECT S.DOCCODE, B.BKGSDATE
		INTO v_DOCCODE, v_BOOKINGTIME
		FROM BOOKING B
		LEFT JOIN SCHEDULE S ON B.SCHID = S.SCHID
		WHERE BKGID = i_bkgid;

		RETURN NHS_UTL_SMSMESSAGE(i_language, 'APPOINTMENT', v_DOCCODE, v_BOOKINGTIME);
	END IF;

	RETURN NULL;

END NHS_SMS_PATIENTAPPOINTMENT;
/
