--Deposit.bas / TransferDeposit
CREATE OR REPLACE FUNCTION "NHS_UTL_TRANSFERDEPOSIT"(
	i_DEPOSITID IN VARCHAR2,
	i_SLIPNO    IN VARCHAR2,
	i_ITEMCODE  IN VARCHAR2,
	i_usrid     IN VARCHAR2,
	O_ERRMSG    OUT VARCHAR2
)
	RETURN NUMBER
AS
	DPSCUR       TYPES.CURSOR_TYPE;
	v_COUNT      NUMBER;
	DAMT         NUMBER;
	TAMT         NUMBER;
	v_DPSAMT     NUMBER;
	v_FLAG       NUMBER;
	v_AMOUNT     NUMBER;
	v_AMT        NUMBER;
	v_A          NUMBER;
	v_B          NUMBER;
	v_DPSTDATE   DATE;
	v_DPSCDATE   DATE;
	v_DOCCODE    DOCTOR.DOCCODE%TYPE;
	v_ITMRLVL    VARCHAR2(20);
	v_GLCCODE    VARCHAR2(20);
	v_ACMCODE    ACM.ACMCODE%TYPE;
	v_STNDESC    VARCHAR2(200);
	v_OLDSLIP    VARCHAR2(15);
	v_ITEMNAME   VARCHAR2(50);
	v_SPAY       VARCHAR2(20);
	v_CRARATE    VARCHAR2(20);
	v_SLIPTX_SEQ VARCHAR2(20);
	v_TRANS      VARCHAR(20);
BEGIN
	O_ERRMSG  := 'OK';
	v_DPSCDATE := SYSDATE;

	SELECT COUNT(1) INTO v_COUNT
	FROM   DEPOSIT D, SLIPTX SX
	WHERE  D.DPSID = I_DEPOSITID
	AND    SX.STNXREF = I_DEPOSITID
	AND    SX.STNBAMT = D.DPSAMT
	AND    SX.STNSTS = 'N'
	AND    SX.ITMCODE = I_ITEMCODE;

	IF v_COUNT = 1 THEN
		SELECT SLPNO_S,
			DPSAMT,
			DPSTDATE,
			SX.DOCCODE,
			SX.STNRLVL,
			SX.GLCCODE,
			SX.ACMCODE,
			SX.STNDESC
		INTO v_OLDSLIP,
			v_DPSAMT,
			v_DPSTDATE,
			v_DOCCODE,
			v_ITMRLVL,
			v_GLCCODE,
			v_ACMCODE,
			v_STNDESC
		FROM  DEPOSIT D, SLIPTX SX
		WHERE D.DPSID = I_DEPOSITID
		AND   SX.STNXREF = I_DEPOSITID
		AND   SX.STNBAMT = D.DPSAMT
		AND   SX.STNSTS = 'N'
		AND   SX.ITMCODE = I_ITEMCODE;
	ELSE
		RETURN -1;
	END IF;

	SELECT COUNT(1) INTO v_COUNT FROM ITEM WHERE ITMCODE = I_ITEMCODE;
	IF v_COUNT = 1 THEN
		SELECT ITMNAME INTO v_ITEMNAME FROM ITEM WHERE ITMCODE = I_ITEMCODE;
	END IF;

	SELECT COUNT(1) INTO v_COUNT FROM SLIPTX WHERE SLPNO = v_OLDSLIP AND STNXREF = I_DEPOSITID;
	IF v_COUNT = 1 THEN
		SELECT STNNAMT INTO DAMT FROM SLIPTX WHERE SLPNO = v_OLDSLIP AND STNXREF = I_DEPOSITID;
	END IF;

	SELECT COUNT(1) INTO v_COUNT FROM SLIP WHERE SLPNO = v_OLDSLIP;
	IF v_COUNT = 1 THEN
		SELECT SLPDAMT INTO TAMT FROM SLIP WHERE SLPNO = v_OLDSLIP;
	END IF;

	OPEN DPSCUR FOR
		SELECT T.MTD, ROUND(SUM(T.AMT) / TAMT * DAMT) AS AMT
		FROM (
			SELECT NVL(CX.CTNCTYPE, 'Cash') AS MTD, SUM(CH.CTXAMT) AS AMT
			FROM CASHTX CH, CARDTX CX
			WHERE CH.CTNID = CX.CTNID(+)
			AND CH.SLPNO = v_OLDSLIP
			GROUP BY CTNCTYPE
				UNION ALL
			SELECT 'Cash' AS MTD, -SLPCAMT AS AMT
			FROM SLIP
			WHERE SLPNO = v_OLDSLIP) T
		GROUP BY T.MTD
		HAVING SUM(T.AMT) > 0;

	IF (SQL%ROWCOUNT = 0) THEN
		v_FLAG := NHS_ACT_ADDENTRY('ADD',
					i_SLIPNO,
					i_ITEMCODE,
					'',
					'I',
					-v_DPSAMT,
					-v_DPSAMT,
					v_DOCCODE,
					v_ITMRLVL,
					'',
					NULL,
					'',
					to_char(v_DPSCDATE, 'dd/mm/yyyy'),
					to_char(v_DPSTDATE, 'dd/mm/yyyy'),
					v_ITEMNAME || ' ' || v_OLDSLIP || '(Cash)',
					'',
					v_GLCCODE,
					i_DEPOSITID,
					NULL,
					NULL,
					NULL,
					NULL,
					NULL,
					NULL,
					NULL,
					NULL,
					NULL,
					i_usrid,
					O_ERRMSG);
	ELSE
		LOOP
			FETCH DPSCUR INTO v_SPAY, v_AMOUNT;
			EXIT WHEN DPSCUR%NOTFOUND;

			v_SPAY := TRIM(v_SPAY);
			v_FLAG := NHS_ACT_ADDENTRY('ADD',
					i_SLIPNO,
					i_ITEMCODE,
					'',
					'I',
					-v_AMOUNT,
					-v_AMOUNT,
					v_DOCCODE,
					v_ITMRLVL,
					'',
					NULL,
					'',
					to_char(v_DPSCDATE, 'dd/mm/yyyy'),
					to_char(v_DPSTDATE, 'dd/mm/yyyy'),
					v_ITEMNAME || ' ' || v_OLDSLIP || '(' ||
					v_SPAY || ')',
					'',
					v_GLCCODE,
					i_DEPOSITID,
					NULL,
					NULL,
					NULL,
					NULL,
					NULL,
					NULL,
					NULL,
					NULL,
					NULL,
					i_usrid,
					O_ERRMSG);

			IF v_SPAY <> 'Cash' THEN

				SELECT COUNT(1) INTO v_COUNT FROM CARDRATE WHERE CRANAME = v_SPAY;
				IF v_COUNT = 1 THEN
					SELECT CRARATE
					INTO   v_CRARATE
					FROM   CARDRATE
					WHERE  CRANAME = v_SPAY;
				END IF;

				UPDATE SLIPTX
				SET    PAYMETHOD = v_SPAY, CARDRATE = v_CRARATE
				WHERE  STNID = v_FLAG;
			END IF;
		END LOOP;

		SELECT SUM(STNNAMT)
		INTO   v_AMT
		FROM   SLIPTX
		WHERE  SLPNO = I_SLIPNO
		AND    STNXREF = I_DEPOSITID;

		v_A := v_AMT + v_DPSAMT;
		IF v_A <> 0 THEN
			SELECT STNNAMT INTO v_B FROM SLIPTX WHERE STNID = v_FLAG;

			v_A := v_B - v_A;

			UPDATE SLIPTX
			SET    STNOAMT = v_A, STNBAMT = v_A, STNNAMT = v_A
			WHERE  STNID = v_FLAG;
		END IF;
	END IF;

	UPDATE DEPOSIT
	SET
		DPSSTS    = 'T',
		DPSLCDATE = SYSDATE,
		DPSLTDATE = SYSDATE,
		SLPNO_T   = i_SLIPNO
	WHERE DPSID = i_DEPOSITID;

	SELECT COUNT(1) INTO v_COUNT FROM SLIPTX WHERE STNXREF = I_DEPOSITID AND SLPNO = v_OLDSLIP AND STNSTS = 'N';
	IF v_COUNT = 1 THEN
		SELECT TRANSVER
		INTO   v_TRANS
		FROM   SLIPTX
		WHERE  STNXREF = I_DEPOSITID
		AND    SLPNO = v_OLDSLIP
		AND    STNSTS = 'N';
	END IF;

	UPDATE SLIPTX SET TRANSVER = v_TRANS WHERE STNID = v_FLAG;

	CLOSE DPSCUR;

	RETURN v_FLAG;
END NHS_UTL_TRANSFERDEPOSIT;
/
