CREATE OR REPLACE FUNCTION "NHS_CHK_CANPROCEED"
(
	i_SITE_CODE VARCHAR2,
	i_DAYEND_YN VARCHAR2
)
	RETURN Types.cursor_type
AS
	OUTCUR types.cursor_type;
	v_UTIME DATE;
	o_errcode NUMBER;
BEGIN
	v_UTIME := NHS_UTL_CANPROCEED(i_SITE_CODE, i_DAYEND_YN);

	IF v_UTIME IS NOT NULL THEN
		OPEN OUTCUR FOR
		SELECT v_UTIME FROM DUAL;
	ELSE
		OPEN OUTCUR FOR
		SELECT 1 FROM DUAL WHERE 1 != 1;
	END IF;

	RETURN OUTCUR;
END NHS_CHK_CANPROCEED;
/
