create or replace FUNCTION NHS_UTL_ISINPATIENT (
	i_patno  IN VARCHAR2
)
	RETURN VARCHAR2
AS
	v_COUNT NUMBER;

	REG_TYPE_INPATIENT VARCHAR(1) := 'I';
	REG_CAT_NORMAL VARCHAR(1) := 'N';
BEGIN
	SELECT COUNT(1) INTO v_COUNT
	FROM   PATIENT P
	INNER JOIN REG R ON P.REGID_C = R.REGID
	INNER JOIN INPAT I ON R.INPID = I.INPID
	WHERE  P.PATNO = i_patno
	AND    R.REGSTS = REG_CAT_NORMAL
	AND    R.REGTYPE = REG_TYPE_INPATIENT
	AND    I.INPDDATE IS NULL;

	IF v_COUNT = 0 THEN
		RETURN 'N';
	ELSE
		RETURN 'Y';
	END IF;

END NHS_UTL_ISINPATIENT;
/
