create or replace FUNCTION "NHS_LIS_DUPLPREBOK" (
	v_ACTION IN VARCHAR2,
	v_PATNO  IN VARCHAR2,
	v_HKID	 IN VARCHAR2,
	v_FNAME  IN VARCHAR2,
	v_GNAME  IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
--	RETURN VARCHAR2
AS
	OUTCUR TYPES.CURSOR_TYPE;
	v_ISDUPLICATE BOOLEAN := FALSE;
	v_Sql VARCHAR2(5000);
	v_SqlStr VARCHAR2(6000);
BEGIN
	IF v_ACTION = 'ADD' OR v_ACTION = 'MOD' THEN
		IF v_ACTION = 'ADD' THEN
			v_ISDUPLICATE := NHS_UTL_GETDUPPREBOK('NewPB', v_Sql, NULL, v_PATNO, v_HKID, REPLACE(v_FNAME, '''', ''''''), REPLACE(v_GNAME, '''', ''''''));
		ELSIF v_ACTION = 'MOD' THEN
			v_ISDUPLICATE := NHS_UTL_GETDUPPREBOK('EditPB', v_Sql, NULL, v_PATNO, v_HKID, REPLACE(v_FNAME, '''', ''''''), REPLACE(v_GNAME, '''', ''''''));
		END IF;

		IF v_ISDUPLICATE AND v_Sql IS NOT NULL THEN
			v_SqlStr := 'SELECT '''',BE.BPBREGTYPE,
					UPPER(B.PATFNAME || '' '' || B.PATGNAME) AS PATNAME,
					B.PATNO,
					B.PATIDNO,
					D.DOCFNAME || '' '' || D.DOCGNAME || '' ('' || B.DOCCODE || '')'' AS DOCNAME,
					B.WRDCODE,
					TO_CHAR(B.BPBHDATE, ''DD/MM/YYYY HH24:MI:SS'') AS HOSDATE,
					TO_CHAR(B.BPBODATE, ''DD/MM/YYYY HH24:MI:SS'') AS ORDDATE,
					C.USRNAME AS CREATEUSERNAME
				FROM  BEDPREBOK B
					LEFT JOIN USR C ON B.USRID = C.USRID
					LEFT JOIN DOCTOR D ON B.DOCCODE = D.DOCCODE
          left outer join BEDPREBOK_EXTRA BE on B.PBPID = BE.PBPID          
				WHERE B.PBPID IN (' || v_Sql || ') ORDER BY PATNAME, HOSDATE';

			OPEN OUTCUR FOR v_SqlStr;
			RETURN OUTCUR;
--			RETURN v_SqlStr;
		END IF;
	END IF;

	RETURN NULL;
END NHS_LIS_DUPLPREBOK;
/