CREATE OR REPLACE FUNCTION NHS_UTL_SlpPayAllCheck (
	i_SlpNo IN VARCHAR2
)
	RETURN VARCHAR2
AS
	OUTCUR types.cursor_type;
	v_cnt NUMBER(22,0);
	v_rtn VARCHAR2(1);
	v_SlpManAll NUMBER(22,0);

	SLIP_PAYMENT_CHECK_NONE VARCHAR2(1) := 'N';
	SLIP_PAYMENT_CHECK_MANUAL VARCHAR2(1) := 'M';
	SLIP_PAYMENT_CHECK_AUTO VARCHAR2(1) := 'A';
BEGIN
	OPEN OUTCUR FOR 'SELECT COUNT(1) FROM (' || NHS_UTL_SlpPayAllGetChgSQL(i_SlpNo) || ') t';
		LOOP
			FETCH OUTCUR INTO v_cnt;
			EXIT WHEN OUTCUR%NOTFOUND;
		END LOOP;
	CLOSE OUTCUR;

	IF v_cnt = 0 THEN
		v_rtn := SLIP_PAYMENT_CHECK_NONE;
	ELSE
		SELECT SlpManAll INTO v_SlpManAll FROM Slip WHERE SlpNo = i_SlpNo;
		IF v_SlpManAll = -1 THEN
			v_rtn := SLIP_PAYMENT_CHECK_MANUAL;
		ELSE
			v_rtn := SLIP_PAYMENT_CHECK_AUTO;
		END IF;
	END IF;

	RETURN v_rtn;
END NHS_UTL_SLPPAYALLCHECK;
/
