CREATE OR REPLACE FUNCTION "NHS_CHK_DUPLPREBOK" (
	v_ACTION IN VARCHAR2,
	v_PATNO  IN VARCHAR2,
	v_HKID	 IN VARCHAR2,
	v_FNAME  IN VARCHAR2,
	v_GNAME  IN VARCHAR2
)
	RETURN BOOLEAN
AS
	v_ISDUPLICATE BOOLEAN := FALSE;
	v_Sql VARCHAR2(5000);
BEGIN
	IF v_ACTION = 'ADD' OR v_ACTION = 'MOD' THEN
		IF v_ACTION = 'ADD' THEN
			v_ISDUPLICATE := NHS_UTL_GETDUPPREBOK('NewPB', v_Sql, NULL, v_PATNO, v_HKID, REPLACE(v_FNAME, '''', ''''''), REPLACE(v_GNAME, '''', ''''''));
		ELSIF v_ACTION = 'MOD' THEN
			v_ISDUPLICATE := NHS_UTL_GETDUPPREBOK('EditPB', v_Sql, NULL, v_PATNO, v_HKID, REPLACE(v_FNAME, '''', ''''''), REPLACE(v_GNAME, '''', ''''''));
		END IF;
	END IF;

	RETURN v_ISDUPLICATE;
END NHS_CHK_DUPLPREBOK;
/
