create or replace FUNCTION NHS_UTL_ISPATIENTSTAFF (
	i_patno  IN VARCHAR2
)
	RETURN VARCHAR2
AS
	v_COUNT NUMBER;
BEGIN
	IF GET_CURRENT_STECODE = 'TWAH' THEN
		SELECT COUNT(1) INTO v_COUNT
		FROM   ALERT A
		INNER JOIN PATALTLINK PL ON A.ALTID = PL.ALTID
		WHERE  A.ALTCODE IN ('PT', 'FT')
		AND    PL.PALCDATE IS NULL
		AND    PL.USRID_C IS NULL
		AND    PL.PATNO = i_patno;
	ELSE
		SELECT COUNT(1) INTO v_COUNT
		FROM   ALERT A
		INNER JOIN PATALTLINK PL ON A.ALTID = PL.ALTID
		WHERE  A.ALTCODE IN ('Y1S', 'Y2S', 'Y1D', 'PTS')
		AND    PL.PALCDATE IS NULL
		AND    PL.USRID_C IS NULL
		AND    PL.PATNO = i_patno;
	END IF;

	IF v_COUNT > 0 THEN
		RETURN 'Y';
	ELSE
		RETURN 'N';
	END IF;

END NHS_UTL_ISPATIENTSTAFF;
/
