CREATE OR REPLACE FUNCTION "NHS_SMS_PATIENTREGISTRATION" (
	i_language IN VARCHAR2,
	i_schID    IN VARCHAR2
)
	RETURN VARCHAR2
AS
	outcur Types.cursor_type;
	v_DOCCODE DOCTOR.DOCCODE%TYPE;
	v_BOOKINGTIME DATE;
	v_BOOKINGSTIME VARCHAR2(20);
	v_BOOKINGPTIME VARCHAR2(20);
	v_BOOKING_MSG VARCHAR2(1000);
	v_REGID REG.REGID%TYPE;
	v_COUNT NUMBER;
BEGIN
	SELECT COUNT(1) INTO v_COUNT
	FROM  SCHEDULE
	WHERE SCHID = i_schID;

	IF v_COUNT = 1 THEN
		SELECT DOCCODE, SCHSDATE
		INTO v_DOCCODE, v_BOOKINGTIME
		FROM  SCHEDULE
		WHERE SCHID = i_schID;

		v_BOOKING_MSG := NHS_UTL_SMSMESSAGE(i_language, 'REGISTRATION', v_DOCCODE, v_BOOKINGTIME);

		SELECT MIN (REGID) INTO v_REGID
		FROM BOOKING B
		INNER JOIN SCHEDULE S ON B.SCHID = S.SCHID
		INNER JOIN REG R ON B.BKGID = R.BKGID
		WHERE S.SCHID = i_schID
		AND   R.REGSTS = 'N';

		SELECT TO_CHAR(B.BKGSDATE, 'HH24:MI', 'NLS_DATE_LANGUAGE = ''American'''), TO_CHAR(R.REGDATE, 'HH24:MI', 'NLS_DATE_LANGUAGE = ''American''')
		INTO v_BOOKINGSTIME, v_BOOKINGPTIME
		FROM BOOKING B
		INNER JOIN SCHEDULE S ON B.SCHID = S.SCHID
		INNER JOIN REG R ON B.BKGID = R.BKGID
		WHERE S.SCHID = i_schID
		AND   R.REGSTS = 'N'
		AND   R.REGID = v_REGID;

		v_BOOKING_MSG := REPLACE(v_BOOKING_MSG, '{2}', v_BOOKINGSTIME);
		v_BOOKING_MSG := REPLACE(v_BOOKING_MSG, '{3}', v_BOOKINGPTIME);

		RETURN v_BOOKING_MSG;
	END IF;

	RETURN NULL;

END NHS_SMS_PATIENTREGISTRATION;
/
