CREATE OR REPLACE
FUNCTION "NHS_GET_SITECODE" 
	RETURN Types.cursor_type
AS
	OUTCUR Types.cursor_type;
BEGIN
   OPEN OUTCUR FOR
   SELECT GET_CURRENT_STECODE
   FROM   DUAL;
   RETURN OUTCUR;
END NHS_GET_SITECODE;
/
