create or replace FUNCTION NHS_UTL_GETESURVEYLINK (
    i_regID IN NUMBER
)
    RETURN VARCHAR2 
AS 
    V_ELINK VARCHAR2(20000);
    V_REGID NUMBER(22, 0);
BEGIN
    SELECT PARAM1 INTO V_ELINK
    FROM SYSPARAM
    WHERE PARCDE = 'E_SUV_SMS';
    
    SELECT REGID INTO V_REGID
    FROM REG
    WHERE REGID = i_regID;

    V_ELINK := V_ELINK || V_REGID;
    
    RETURN V_ELINK;
END NHS_UTL_GETESURVEYLINK;