CREATE OR REPLACE FUNCTION "NHS_GET_CARDNEWREF"(
	i_SlipNumber IN VARCHAR2
)
	RETURN TYPES.cursor_type
AS
	OUTCUR   TYPES.cursor_type;
	v_EcrRef VARCHAR2(20);
BEGIN
	v_EcrRef := NHS_UTL_GETCARDNEWREF(i_SlipNumber);

	OPEN OUTCUR FOR
		SELECT v_EcrRef FROM DUAL;
	RETURN OUTCUR;
END NHS_GET_CARDNEWREF;
/


