create or replace FUNCTION NHS_UTL_ISHOLIDAY (
	i_DATE IN DATE
)
	RETURN VARCHAR2
AS
	v_COUNT NUMBER;
	v_DAYOFWEEK VARCHAR2(1);
BEGIN
	SELECT COUNT(1) INTO v_COUNT
	FROM PUBLIC_HOLIDAY
	WHERE TO_CHAR(HOLIDAY, 'DD/MM/YYYY') = TO_CHAR(i_DATE, 'DD/MM/YYYY')
	AND   ENABLED = 1;

	IF v_COUNT > 0 THEN
		RETURN 'Y';
	ELSE
		-- saturday
		SELECT TO_CHAR(i_DATE, 'D') INTO v_DAYOFWEEK FROM DUAL;
		IF v_DAYOFWEEK = '7' THEN
			RETURN 'Y';
		ELSE
			RETURN 'N';
		END IF;
	END IF;

END NHS_UTL_ISHOLIDAY;
/
