CREATE OR REPLACE
FUNCTION "NHS_LIS_SUBDISEASEBYABBR" (
  V_ABBR IN VARCHAR2
)
  RETURN Types.cursor_type
AS
  outcur types.cursor_type;
BEGIN
  OPEN OUTCUR FOR 
      SELECT SDSABB, SDSCODE, SDSDESC
      FROM SDISEASE
      WHERE (V_ABBR IS NULL OR SDSABB LIKE '' || V_ABBR ||'%')
      ORDER BY SDSABB;
  RETURN OUTCUR;
END NHS_LIS_SUBDISEASEBYABBR;
/