CREATE OR REPLACE FUNCTION "NHS_LIS_PATIENT_ALERT2"
(V_PATNO IN VARCHAR2,
V_USRID IN VARCHAR2)
  RETURN TYPES.CURSOR_TYPE AS
  OUTCUR        TYPES.CURSOR_TYPE;
  P_ALTCODE     VARCHAR2(100);
BEGIN
  P_ALTCODE:=GET_ALERT_CODE(V_PATNO,V_USRID);
  OPEN OUTCUR FOR
    SELECT P_ALTCODE FROM DUAL;
  RETURN OUTCUR;
END NHS_LIS_PATIENT_ALERT2;
/
