CREATE OR REPLACE FUNCTION "NHS_ACT_SIGNOFF" (
	i_ACTION        IN VARCHAR2,
	i_USERID        IN VARCHAR2,
	i_CASHIERCODE   IN VARCHAR2,
	i_COMPUTERNAME  IN VARCHAR2,
	o_ERRMSG        OUT VARCHAR2
)
	RETURN NUMBER
AS
	o_errcode NUMBER;
	v_Count NUMBER;
	CASHIER_STS_NORMAL VARCHAR2(1) := 'N';
	CASHIER_STS_OFF VARCHAR2(1) := 'O';
BEGIN
	O_ERRCODE := 0;
	O_ERRMSG  := 'OK';

	-- sign off cahsier
	SELECT COUNT(1) INTO v_Count FROM CASHIER WHERE CSHCODE = i_CASHIERCODE AND CSHSTS = CASHIER_STS_NORMAL;
	IF v_Count = 1 THEN
		UPDATE CASHIER
		SET CSHSTS = CASHIER_STS_OFF,
			CSHFDATE = SYSDATE
		WHERE CSHCODE = i_CASHIERCODE
		AND   CSHSTS = CASHIER_STS_NORMAL;
	END IF;

	SELECT COUNT(1) INTO v_Count FROM USR WHERE USRID = i_USERID;
	IF v_Count = 1 THEN
		-- inactive user
		UPDATE USR
		SET ISUSING = 0
		WHERE USRID = i_USERID;

		-- release rlock
		DELETE FROM RLOCK
		WHERE USRID = i_USERID
		AND RLKMAC = i_COMPUTERNAME;
	END IF;

	RETURN O_ERRCODE;
EXCEPTION
WHEN OTHERS THEN
	ROLLBACK;
	dbms_output.put_line('An ERROR was encountered - ' || SQLCODE || ' -ERROR- ' || SQLERRM);
	o_ERRMSG := SQLERRM || o_ERRMSG;

	return -999;
END NHS_ACT_SIGNOFF;
/
