CREATE OR REPLACE FUNCTION "NHS_ACT_SLIPUNLOCK" (
	I_ACTION       IN VARCHAR2,
	I_SLPNOS       IN VARCHAR2,
	I_LOCKTYPE     IN VARCHAR2,
	I_COMPUTERNAME IN VARCHAR2,
	I_USRID        IN VARCHAR2,
	O_ERRMSG       OUT VARCHAR2
)
	RETURN NUMBER
AS
	O_ERRCODE NUMBER;
BEGIN
	O_ERRCODE := 0;

	FOR SLIPS IN (
		SELECT REGEXP_SUBSTR(I_SLPNOS, '[^,]+', 1, LEVEL) AS SLIP, ROWNUM
		FROM   DUAL
		CONNECT BY REGEXP_SUBSTR(I_SLPNOS, '[^,]+', 1, LEVEL) IS NOT NULL)
	LOOP
		IF LENGTH(TRIM(SLIPS.SLIP)) > 0 THEN
			O_ERRCODE := NHS_ACT_RECORDUNLOCK(I_ACTION, I_LOCKTYPE, TRIM(SLIPS.SLIP), I_COMPUTERNAME, I_USRID, O_ERRMSG);
		END IF;
	END LOOP;

	RETURN O_ERRCODE;
EXCEPTION
WHEN OTHERS THEN
	ROLLBACK;
	dbms_output.put_line('An ERROR was encountered - ' || SQLCODE || ' -ERROR- ' || SQLERRM);
	o_ERRMSG := SQLERRM || o_ERRMSG;

	RETURN -999;
END NHS_ACT_SLIPUNLOCK;
/
