CREATE OR REPLACE FUNCTION NHS_ACT_PATIENTACTIVITYLOG (
	i_ACTION      IN VARCHAR2,
	i_PATNO       IN VARCHAR2,
	i_MODULE      IN VARCHAR2,
	i_ACTION_TYPE IN VARCHAR2,
	i_REMARK      IN VARCHAR2,
	i_USERID      IN VARCHAR2,
	i_PCNAME      IN VARCHAR2,
	i_ErrMsg      OUT VARCHAR2
)
	RETURN NUMBER
AS
	O_ERRCODE NUMBER;
	O_ERRMSG VARCHAR2(100);
	v_PCNAME SysLog.PCName%Type;
BEGIN
	O_ERRCODE := 0;
	O_ERRMSG := 'OK';

	-- trim computer name if too big
	IF LENGTH(i_PCNAME) > 100 THEN
		v_PCNAME := SUBSTR(i_PCNAME, 1, 100);
	ELSE
		v_PCNAME := i_PCNAME;
	END IF;

	INSERT INTO PATIENT_ACTIVITY_LOG (PATNO, MODULE, ACTION_TYPE, REMARK, PCNAME, CREATED_USER)
	VALUES (i_PATNO, i_MODULE, i_ACTION_TYPE, i_REMARK, v_PCNAME, i_USERID);

	RETURN O_ERRCODE;
EXCEPTION
WHEN OTHERS THEN
	ROLLBACK;
	O_ERRMSG := 'Fail to add patient log.';
	DBMS_OUTPUT.PUT_LINE('An ERROR was encountered - '||SQLCODE||' -ERROR- '||SQLERRM);
	RETURN -1;
END NHS_ACT_PATIENTACTIVITYLOG;
/
