CREATE OR REPLACE
FUNCTION "NHS_GET_COMPUTERNAME"(
   V_IP In Varchar2
)
  RETURN types.CURSOR_TYPE
AS
  Outcur Types.Cursor_Type;
Begin
 	OPEN OUTCUR FOR
    SELECT  UPPER(COMPUTERNAME)
    FROM COMPUTER_MAPPING
    WHERE UPPER(COMPUTERIP) = UPPER(V_IP)
    AND ENABLE = 1;
 RETURN OUTCUR;
END NHS_GET_COMPUTERNAME;
/