/*
 * Deploy on 20220215 20:00
 */
ALTER TABLE DOCTOR_MAPPING
 DROP PRIMARY KEY CASCADE;
DROP TABLE DOCTOR_MAPPING CASCADE CONSTRAINTS;

CREATE TABLE DOCTOR_MAPPING
(
 DOCCODE_OLD VARCHAR2(10 BYTE) NOT NULL,
 DOCCODE_NEW VARCHAR2(10 BYTE) NOT NULL,
 SWITCHOVERDATE DATE,
 PATCHEDDATE	DATE,
 ENABLED NUMBER(*,0) DEFAULT 1,
 PRIMARY KEY (DOCCODE_OLD)
);


-- convert sp
SET SERVEROUTPUT ON
DECLARE
	v_COUNT_1 NUMBER;
BEGIN
	FOR R IN (
		SELECT DOCCODE_OLD, DOCCODE_NEW, SWITCHOVERDATE
		FROM   DOCTOR_MAPPING
		WHERE  ENABLED = 1
		AND 	PATCHEDDATE IS NULL
	) LOOP
		-- SCHEDULE --
		UPDATE 	SCHEDULE
		SET    	DOCCODE = R.DOCCODE_NEW
		WHERE  	DOCCODE = R.DOCCODE_OLD
		AND		SCHSDATE >= R.SWITCHOVERDATE;

		-- OT_APP --
		UPDATE 	OT_APP
		SET    	DOCCODE_S = R.DOCCODE_NEW
		WHERE  	DOCCODE_S = R.DOCCODE_OLD
		AND		OTAOSDATE >= R.SWITCHOVERDATE;
		
		UPDATE 	OT_APP
		SET    	DOCCODE_A = R.DOCCODE_NEW
		WHERE  	DOCCODE_A = R.DOCCODE_OLD
		AND		OTAOSDATE >= R.SWITCHOVERDATE;
		
		UPDATE 	OT_APP
		SET    	DOCCODE_R = R.DOCCODE_NEW
		WHERE  	DOCCODE_R = R.DOCCODE_OLD
		AND		OTAOSDATE >= R.SWITCHOVERDATE;
		
		UPDATE 	OT_APP
		SET    	DOCCODE_E = R.DOCCODE_NEW
		WHERE  	DOCCODE_E = R.DOCCODE_OLD
		AND		OTAOSDATE >= R.SWITCHOVERDATE;
		
		-- OT_APP_SURG --
		UPDATE 	OT_APP_SURG
		SET    	DOCCODE = R.DOCCODE_NEW
		WHERE  	DOCCODE = R.DOCCODE_OLD
		AND		OTAID IN (
		    select otaid from OT_APP
		    where otaosdate >= R.SWITCHOVERDATE
		);

		-- TEMPLATE --
		INSERT INTO TEMPLATE(TEMID, DOCCODE, TEMDAY, TEMSTIME, TEMETIME, TEMLEN, STECODE, DOCPRACTICE, DOCLOCID)
		SELECT SEQ_TEMPLATE.NEXTVAL, R.DOCCODE_NEW, TEMDAY, TEMSTIME, TEMETIME, TEMLEN, STECODE, DOCPRACTICE, DOCLOCID
		FROM TEMPLATE
		WHERE DOCCODE = R.DOCCODE_OLD
		AND R.DOCCODE_OLD <> R.DOCCODE_NEW;
		
		-- HPSTATUS (auto insert consultation fee)
		INSERT INTO HPSTATUS(HPTYPE, HPKEY, HPSTATUS, HPCDATE, HPCUSR, HPMUSR, HPACTIVE)
		SELECT HPTYPE, R.DOCCODE_NEW, HPSTATUS, SYSDATE, HPCUSR, HPMUSR, HPACTIVE
		FROM HPSTATUS
		WHERE  HPTYPE = 'DOC2ITEM'
		AND HPKEY = R.DOCCODE_OLD
		AND R.DOCCODE_OLD <> R.DOCCODE_NEW;
		
		-- ARDRCHG (insurance doctor agreeable rate)
		INSERT INTO ARDRCHG(ARDRCHGID, ARCCODE, ITMCODE, PKGCODE, ARDCTYPE, ACMCODE, DOCCODE, ARDCAMT, ARDCPCT, ARDCSDT, ARDCEDT, CPSID)
		SELECT SEQ_ARDRCHG.NEXTVAL, ARCCODE, ITMCODE, PKGCODE, ARDCTYPE, ACMCODE, R.DOCCODE_NEW, ARDCAMT, ARDCPCT, ARDCSDT, ARDCEDT, CPSID
		FROM ARDRCHG
		WHERE DOCCODE = R.DOCCODE_OLD
		AND R.DOCCODE_OLD <> R.DOCCODE_NEW;
	END LOOP;      
		
	-- UPDATE FLAG
	UPDATE DOCTOR_MAPPING SET PATCHEDDATE = SYSDATE WHERE PATCHEDDATE IS NULL AND ENABLED = 1;
END;
/

