create or replace FUNCTION NHS_GET_QUOTATIONITEM_MULTI
(   
    v_CATEGORY IN VARCHAR2, 
    v_PATTYPE IN VARCHAR2,
    v_ITMCODE IN VARCHAR2,
    v_OPTION IN VARCHAR2,
    v_ITMPREFIX IN VARCHAR2,
    v_CONTRAST IN VARCHAR2,
    v_TIMESLOT IN VARCHAR2
)
RETURN TYPES.CURSOR_TYPE
AS

OUTCUR TYPES.CURSOR_TYPE;
o_outcur types.cursor_type;
SQLSTR VARCHAR2(32767);

v_QUOTATIONITM PQITEM.ITMCODE%TYPE;
v_QUOTATIONPKG VARCHAR2(15);
v_ACMCODE ITEMCHG.ACMCODE%TYPE;
v_ITMAMT NUMBER := 0;
v_ITMDESC PQITEM.ITMDESC%TYPE;
v_OPTDESC PQCATEGORY.OPTDESC%TYPE;
v_SLOT PQCATEGORY.TIMESLOT%TYPE;
v_SLOTDESC VARCHAR2(50);
v_GETPKG BOOLEAN := FALSE;
v_PATTYPEDESC VARCHAR2(50);
v_ADDPKGCODE PQCATEGORY.ADDPKGCODE%TYPE:=NULL;
v_Count    NUMBER;
v_cat PQCATEGORY.PQCATEGORY%TYPE;
v_opt PQCATEGORY.PQCATEGORY%TYPE;
BEGIN
    
    IF (GET_CURRENT_STECODE() = 'HKAH' AND v_CATEGORY = 'XR' AND v_ITMCODE = '001') THEN --SPECIAL HAANDLE FOR LITHORTRIPSY
        v_cat := 'PL';
        v_opt := CASE WHEN INSTR(v_OPTION,'P') = 1 THEN 'PL' ELSE 'ZL' END;
    ELSE
      v_cat := v_CATEGORY;
      v_opt := v_OPTION;
    END IF;
             
    IF v_TIMESLOT IS NULL OR LENGTH(v_TIMESLOT) = 0 THEN
      SELECT OPTDESCPREFIX||OPTDESC INTO v_SLOTDESC FROM PQCATEGORY WHERE pqcategory = v_cat AND TIMESLOT IS NULL;
    ELSE 
      SELECT OPTDESCPREFIX||OPTDESC INTO v_SLOTDESC FROM PQCATEGORY WHERE pqcategory = v_cat AND TIMESLOT = v_TIMESLOT;
    END IF;
    
        o_outcur :=  NHS_GET_QUOTATIONITEM(v_cat,v_PATTYPE, v_ITMCODE, v_opt,
              v_ITMPREFIX, v_CONTRAST, v_TIMESLOT);
    
      IF o_outcur IS NOT NULL THEN
        LOOP
            FETCH o_outcur INTO v_QUOTATIONITM, v_QUOTATIONPKG, v_ITMDESC, v_SLOT, v_OPTDESC, v_ITMAMT, v_PATTYPEDESC;
            SQLSTR := 'SELECT '''||v_QUOTATIONITM||''', '''||v_QUOTATIONPKG||''', '''||v_ITMDESC||''', '''||v_SLOT||''', '
                        ||'DECODE(GET_CURRENT_STECODE,''TWAH'','''||v_OPTDESC||''','''||v_SLOTDESC||'''), '||v_ITMAMT||', '''||v_PATTYPEDESC||''','''' FROM DUAL';
                  DBMS_OUTPUT.PUT_LINE('SQLSTR1 ='|| SQLSTR);

            EXIT WHEN o_outcur%notfound;    
        END LOOP;
      END IF;

            
      SELECT COUNT(1) INTO v_Count FROM PQCATEGORY WHERE PQCATEGORY = v_cat AND PKGPREFIX = v_opt AND TIMESLOT = v_TIMESLOT;
      IF v_COUNT = 1 THEN
        SELECT ADDPKGCODE INTO v_ADDPKGCODE FROM PQCATEGORY WHERE PQCATEGORY = v_cat AND PKGPREFIX = v_opt AND TIMESLOT = v_TIMESLOT;
      END IF;
DBMS_OUTPUT.PUT_LINE('v_ADDPKGCODE ='|| v_ADDPKGCODE);

      IF V_ADDPKGCODE IS NOT NULL THEN
            o_outcur :=  NHS_GET_QUOTATIONITEM(v_cat,v_PATTYPE, v_ADDPKGCODE, v_opt,
            v_ITMPREFIX, v_CONTRAST, v_TIMESLOT);
            DBMS_OUTPUT.PUT_LINE(' NHS_GET_QUOTATIONITEM('''||v_cat||', '''||v_PATTYPE||''', '''||v_ADDPKGCODE||''', '''||v_opt||''', '''||v_ITMPREFIX||''', '''||v_CONTRAST||''', '''||v_TIMESLOT||''')');

            IF o_outcur IS NOT NULL THEN
            LOOP
                FETCH o_outcur INTO v_QUOTATIONITM, v_QUOTATIONPKG, v_ITMDESC, v_SLOT, v_OPTDESC, v_ITMAMT, v_PATTYPEDESC;
                SQLSTR := SQLSTR ||' UNION SELECT '''||v_QUOTATIONITM||''', '''||v_QUOTATIONPKG||''', '''||v_ITMDESC||''', '''||v_SLOT||''', '
                            ||'DECODE(GET_CURRENT_STECODE,''TWAH'','''||v_OPTDESC||''','''||v_SLOTDESC||'''), '||v_ITMAMT||', '''||v_PATTYPEDESC||''',''N'' FROM DUAL';
                EXIT WHEN o_outcur%notfound;    
            END LOOP;
            SQLSTR := SQLSTR||' ORDER BY 8 DESC';
          END IF;
      END IF;
DBMS_OUTPUT.PUT_LINE('SQLSTR = ' || SQLSTR);
    OPEN OUTCUR FOR SQLSTR;   
    RETURN OUTCUR;
END NHS_GET_QUOTATIONITEM_MULTI;
/