echo "Build COMMON"
sqlplus hkah/hkah@HAT_DEV @./common/build.sql
echo "Build Acc.Receivable"
sqlplus hkah/hkah@HAT_DEV @./Acc.Receivable/build.sql
echo "Build Admin"
sqlplus hkah/hkah@HAT_DEV @./admin/build.sql
echo "Build Cashier"
sqlplus hkah/hkah@HAT_DEV @./Cashier/build.sql
echo "Build CMB"
sqlplus hkah/hkah@HAT_DEV @./cmb/build.sql
echo "Build E-Birth"
sqlplus hkah/hkah@HAT_DEV @./E-Birth/build.sql
echo "Build Med.Record"
sqlplus hkah/hkah@HAT_DEV @./Med.Record/build.sql
echo "Build OT"
sqlplus hkah/hkah@HAT_DEV @./ot/build.sql
echo "Build Prt Call Cht"
sqlplus hkah/hkah@HAT_DEV @./PrtCallCht/build.sql
echo "Build Registration"
sqlplus hkah/hkah@HAT_DEV @./registration/build.sql
echo "Build Report"
sqlplus hkah/hkah@HAT_DEV @./Report/build.sql
echo "Build Schedule"
sqlplus hkah/hkah@HAT_DEV @./schedule/build.sql
echo "Build SCM"
sqlplus hkah/hkah@HAT_DEV @./SCM/build.sql
echo "Build Transaction"
sqlplus hkah/hkah@HAT_DEV @./transaction/build.sql
echo "Build Done"