ALTER TABLE AA_QUERY
 DROP PRIMARY KEY CASCADE;
DROP TABLE AA_QUERY CASCADE CONSTRAINTS;

CREATE TABLE AA_QUERY(    
    NAME        VARCHAR2(100 BYTE) NOT NULL,
    STATEMENT   VARCHAR2(2000 BYTE) NOT NULL,
    STATEMENT_NO NUMBER(3,0),
    CONSTRAINT "PK_AA_QUERY" PRIMARY KEY ("NAME")
);

-- HKAH only
INSERT INTO AA_QUERY(NAME, STATEMENT, STATEMENT_NO) VALUES ('1-Doctor Discount-WITH 25 VISITS or 20 ADMISSIONS PER YEAR', 'select docfname, docgname, doccode, sum(cnt1) as "WITH 25 VISITS PER YEAR", sum(cnt2) as "OR WITH 20 ADMISSIONS PER YEAR" from (select  a.docfname, a.docgname, t.doccode, count(*) as cnt1, 0 as cnt2, ''slip visit'' type from slip t, doctor a where a.doccode = t.doccode and slpno > to_char(sysdate-366, ''yyyyddd'') and a.doccode <> ''999'' and a.doccode < ''A'' group by a.docfname, a.docgname, t.doccode having count(*) >= 25 union all (select a.docfname, a.docgname, r.doccode, 0, count(*), ''admission'' type from reg r, doctor a where r.regsts = ''N'' and  r.regdate >= sysdate - 366 and r.regtype = ''I'' and r.doccode >= ''1'' and r.doccode < ''999'' and a.doccode = r.doccode and a.doccode <> ''999'' and a.doccode < ''A'' group by a.docfname, a.docgname, r.doccode having count(*) >= 20)) group by docfname, docgname, doccode order by docfname, docgname', 1);
INSERT INTO AA_QUERY(NAME, STATEMENT, STATEMENT_NO) VALUES ('2-Doctor Contacts by name', 'select dr.docfname||'', ''||dr.docgname Name, dr.doccode Code, dr.docmtel MOBILE, dr.DOCPTEL DOCPTEL, dr.DOCOTEL OFFICE, dr.DOCHTEL HOME, dr.docfaxno FAX, dr.docsex Gender, sp.spcname Specialty, dr.docadd1 address1, dr.docadd2 address2, dr.docadd3 address3 from doctor dr, spec sp where dr.spccode = sp.spccode and dr.docsts = -1 order by name, sp.spcname', 2);
INSERT INTO AA_QUERY(NAME, STATEMENT, STATEMENT_NO) VALUES ('Doctor Contacts by specialty', 'select dr.docfname||'', ''||dr.docgname Name, dr.doccode Code, dr.docmtel MOBILE, dr.DOCPTEL, dr.DOCOTEL OFFICE, dr.DOCHTEL HOME, dr.docfaxno FAX, dr.docsex Gender, sp.spcname Specialty, dr.docadd1 address1, dr.docadd2 address2, dr.docadd3 address3 from doctor dr, spec sp where dr.spccode = sp.spccode and dr.docsts = -1 order by sp.spcname, Name', 3);
INSERT INTO AA_QUERY(NAME, STATEMENT, STATEMENT_NO) VALUES ('Current Ward View', 'SELECT HKAH_REG.REGDATE AS ADMIT_DATE, HKAH_INPAT.BEDCODE AS BED, HKAH_REG.PATNO, HKAH_INPAT.DOCCODE_A AS DOCTOR, HKAH_PATIENT.PATFNAME||'', ''||HKAH_PATIENT.PATGNAME AS NAME, HKAH_PATIENT.PATSEX AS GENDER, TRUNC(MONTHS_BETWEEN(SYSDATE,HKAH_PATIENT.PATBDATE)/12) AS AGE FROM inpat   HKAH_INPAT, reg     HKAH_REG, patient HKAH_PATIENT WHERE HKAH_INPAT.INPID = HKAH_REG.INPID AND   HKAH_REG.PATNO = HKAH_PATIENT.PATNO AND   HKAH_INPAT.INPDDATE Is Null AND   HKAH_REG.REGSTS = ''N'' ORDER BY BED', 4);
INSERT INTO AA_QUERY(NAME, STATEMENT, STATEMENT_NO) VALUES ('Check Doctor Payroll Confirmed', 'SELECT HKAH_SLPPAYHDR.SPHID, HKAH_SLPPAYHDR.SPHDATE, HKAH_SLPPAYHDR.DATEEND, HKAH_SLPPAYHDR.CONFIRM FROM SLPPAYHDR HKAH_SLPPAYHDR ORDER BY HKAH_SLPPAYHDR.SPHID DESC', 5);
INSERT INTO AA_QUERY(NAME, STATEMENT, STATEMENT_NO) VALUES ('reg doc hist discrepancy', 'SELECT REG.PATNO,TRUNC(REG.regdate) reg_date, TRUNC(DOCHIST.DHSDATE) doc_start_date, TRUNC(INPAT.INPDDATE) disch_date,TRUNC(DOCHIST.DHSEDATE) doc_end_date FROM INPAT INPAT,REG REG,DOCHIST DOCHIST WHERE (REG.INPID=INPAT.INPID) AND(REG.REGID=DOCHIST.REGID) AND (REG.regdate > TO_DATE(''01-05-07'', ''DD-MM-YY'')) AND(REG.REGTYPE=''I'') AND ((TRUNC(REG.regdate)<>TRUNC(DOCHIST.dhsdate)) OR (TRUNC(INPAT.inpddate)<>TRUNC(DOCHIST.dhsedate))) and DOCHIST.DHSSTS = ''N'' ORDER BY REG.REGDATE', 6);
INSERT INTO AA_QUERY(NAME, STATEMENT, STATEMENT_NO) VALUES ('Find missing dr code slip', 'SELECT SLIP.PATNO, SLIPTX.SLPNO, SLIPTX.ITMCODE FROM ITEM, SLIPTX, SLIP WHERE SLIPTX.SLPNO=SLIP.SLPNO AND ITEM.ITMCODE = SLIPTX.ITMCODE AND SLIPTX.DOCCODE Is Null', 7);
INSERT INTO AA_QUERY(NAME, STATEMENT, STATEMENT_NO) VALUES ('DI SLIP CHECK', 'SELECT REG.PATNO,REG.SLPNO,SLIPTX.STNSEQ, REG.DOCCODE, SLIP.DOCCODE,SLIPTX.ITMCODE FROM REG REG,SLIP SLIP,SLIPTX SLIPTX WHERE (REG.SLPNO=SLIP.SLPNO) AND (SLIP.SLPNO=SLIPTX.SLPNO) AND (REG.DOCCODE = SLIPTX.DOCCODE) AND (SLIPTX.ITMCODE LIKE ''D_93_'' OR SLIPTX.ITMCODE LIKE ''D_95_'') AND SLIPTX.STNSTS = ''N'' AND SLIPTX.ITMTYPE = ''D''', 9);
INSERT INTO AA_QUERY(NAME, STATEMENT, STATEMENT_NO) VALUES ('Call today', 'select * from booking where usrid = ''CALL'' and to_char(bkgcdate,''dd/mm/yyyy'') = to_char(sysdate,''dd/mm/yyyy'')', 10);
INSERT INTO AA_QUERY(NAME, STATEMENT, STATEMENT_NO) VALUES ('doctor_spec_3', 'SELECT d.DOCCODE , d.DOCFNAME, d.DOCGNAME, d.DOCADD1,d.DOCADD2, d.DOCADD3, d.DOCOTEL, d.DOCMTEL,d.DOCPTEL, d.DOCFAXNO, (select sp.spcname from doctor dr, spec sp where ( ( dr.doccode < ''A'' and to_number(dr.docsts) <> 0 and (to_number(dr.doccode) < 7000) ) or       ( dr.doccode < ''A'' and to_number(dr.docsts) <> 0 and (to_number(dr.doccode) >= 9000) ) ) and   sp.spccode = dr.spccode and dr.doccode = d.doccode) spec1, (select s.spcname from docspclink L, doctor doc, spec s where L.dslid in (select min(dslid) from docspclink group by doccode) and doc.doccode = L.doccode and to_number(doc.docsts) <> 0 and L.spccode = s.spccode and doc.doccode = d.doccode) spec2, DECODE( (select s.spcname from docspclink L, doctor doc, spec s where L.dslid in (select min(dslid) from docspclink group by doccode) and doc.doccode = L.doccode and to_number(doc.docsts) <> 0 and L.spccode = s.spccode and doc.doccode = d.doccode), (select spe.spcname from docspclink Lk, doctor do, spec spe where Lk.dslid in (select max(dslid) from docspclink group by doccode) and do.doccode = Lk.doccode and to_number(do.docsts) <> 0 and Lk.spccode = spe.spccode and do.doccode = d.doccode),'''',(select spe.spcname from docspclink Lk, doctor do, spec spe where Lk.dslid in (select max(dslid) from docspclink group by doccode) and do.doccode = Lk.doccode and to_number(do.docsts) <> 0 and Lk.spccode = spe.spccode and do.doccode = d.doccode)) spec3 FROM DOCTOR d WHERE d.doccode in ( select dr.doccode from doctor dr, spec sp where( ( dr.doccode < ''A'' and to_number(dr.docsts) <> 0 and (to_number(dr.doccode) < 7000) ) or       ( dr.doccode < ''A'' and to_number(dr.docsts) <> 0 and (to_number(dr.doccode) >= 9000) ) ) and   sp.spccode = dr.spccode ) order by d.docfname', 11);
INSERT INTO AA_QUERY(NAME, STATEMENT, STATEMENT_NO) VALUES ('Outstanding balance', 'select sp.slpno, sum(st.stnnamt) as total from slip sp, sliptx st where sp.slpno = st.slpno and to_date(to_char(st.stncdate,''dd/mm/yyyy''),''dd/mm/yyyy'') < to_date(''21/12/2005'',''dd/mm/yyyy'') and sp.slptype = ''I'' group by sp.slpno, sp.slptype having sum(st.stnnamt) <> 0 order by sum(st.stnnamt)', 12);
INSERT INTO AA_QUERY(NAME, STATEMENT, STATEMENT_NO) VALUES ('COD 900-5850', 'SELECT st.SLPNO FROM SLIPTX st WHERE st.ITMCODE=''COD'' AND st.GLCCODE <> ''900-5850''', 13);
INSERT INTO AA_QUERY(NAME, STATEMENT, STATEMENT_NO) VALUES ('Dr_without_emails', 'SELECT d.DOCCODE, d.DOCFNAME, d.DOCGNAME, d.DOCOTEL, d.DOCFAXNO, d.DOCADD1, d.DOCADD2, d.DOCADD3, d.DOCADD4 from doctor d where d.docsts= -1 and d.doccode not like ''7___'' and d.doccode not like ''9___'' and d.doccode not like ''T%'' and d.doccode not like ''S%'' and d.doccode not like ''BE%''  and d.DOCEMAIL is null order by d.docfname', 14);
INSERT INTO AA_QUERY(NAME, STATEMENT, STATEMENT_NO) VALUES ('HAT_PRICE', 'select c.itmcode as item_code, i.itmname as item_name ,d.dptname as dept_name, ''I'' || MAX(DECODE(c.acmcode, ''I'', RPAD(c.itcamt1,Length(c.itcamt1)+1,'' ''))) || ''P'' || MAX(DECODE(c.acmcode, ''P'', RPAD(c.itcamt1,Length(c.itcamt1)+1,'' ''))) ||  ''S'' || MAX(DECODE(c.acmcode, ''S'', RPAD(c.itcamt1,Length(c.itcamt1)+1,'' ''))) ||  ''T'' || MAX(DECODE(c.acmcode, ''T'', RPAD(c.itcamt1,Length(c.itcamt1)+1,'' ''))) IPST, MAX(DECODE(c.itctype, ''O'', RPAD(c.itcamt1,Length(c.itcamt1)+1,'' ''),'' - '')) Outpatient_price from item i, itemchg c, dept d where i.itmcode = c.itmcode and c.cpsid is null and c.cpspct is null and i.dptcode = d.dptcode and c.pkgcode is null and c.itcamt1 <> 0 group by c.itmcode, i.itmname,d.dptname order by c.itmcode', 15);
INSERT INTO AA_QUERY(NAME, STATEMENT, STATEMENT_NO) VALUES ('GOLD CARD Member', 'SELECT PATIENT.PATFNAME, PATIENT.PATGNAME, PATIENT.PATNO, PATALTLINK.PALDATE,  ALERT.ALTDESC FROM patient, pataltlink, alert where PATALTLINK.PATNO = PATIENT.PATNO and PATALTLINK.ALTID = ALERT.ALTID and PATALTLINK.PALCDATE Is Null and ALERT.ALTCODE=''GOLD'' order by patient.patfname, patient.patgname', 16);
INSERT INTO AA_QUERY(NAME, STATEMENT, STATEMENT_NO) VALUES ('Top 10 Surgeons Last 30 days', 'SELECT DOCTOR.DOCCODE,DOCTOR.DOCFNAME,DOCTOR.DOCGNAME,count(*) Admitted FROM OT_LOG,OT_PROC,DOCTOR WHERE OT_LOG.OTPID = OT_PROC.OTPID and OT_LOG.DOCCODE_S = DOCTOR.DOCCODE and OT_LOG.OTLPATIN >= sysdate - 30 group by DOCTOR.DOCCODE, DOCTOR.DOCFNAME, doctor.docgname having count(*) >= 1 order by admitted desc, doctor.docfname, doctor.docfname', 17);
INSERT INTO AA_QUERY(NAME, STATEMENT, STATEMENT_NO) VALUES ('Top 20 Surgeries Last 30 Days', 'SELECT substr(OT_PROC.OTPDESC,1,50), count(*) Admitted FROM OT_LOG,OT_PROC,DOCTOR WHERE OT_LOG.OTPID = OT_PROC.OTPID and OT_LOG.DOCCODE_S = DOCTOR.DOCCODE and OT_LOG.OTLPATIN >= sysdate - 30 group by ot_proc.otpdesc having count(*) >= 1 order by admitted desc', 18);
INSERT INTO AA_QUERY(NAME, STATEMENT, STATEMENT_NO) VALUES ('ZIP Part 1', 'select to_char(sum(tx.stnnamt)) as SumOfStnnamt, tx.usrid,tx.itmcode from slip sp , sliptx tx where sp.slpno = tx.slpno AND to_date(to_char(tx.stncdate,''dd/mm/yyyy''),''dd/mm/yyyy'') >= to_date(''20/12/2005'',''dd/mm/yyyy'') AND to_date(to_char(tx.stncdate,''dd/mm/yyyy''),''dd/mm/yyyy'') < TO_DATE(''21/12/2005'',''dd/mm/yyyy'') and sp.slptype = ''I'' and tx.itmcode = ''REF'' group by tx.usrid,tx.itmcode,sp.slptype', 84);
INSERT INTO AA_QUERY(NAME, STATEMENT, STATEMENT_NO) VALUES ('ZIP Part 2', 'select sum(tx.stnnamt) as SumOfStnnamt, sum(tx.stnbamt) as SumOfStnbamt, tx.stndisc, tx.usrid, tx.itmcode, tx.glccode, sp.slpno,tx.stnsts from slip sp, sliptx tx where sp.slpno = tx.slpno and tx.itmcode <> ''PAYME'' and tx.itmcode <> ''REF''and sp.slptype = ''I'' and to_date(to_char(tx.stncdate,''dd/mm/yyyy''),''dd/mm/yyyy'') >= TO_DATE(''20/12/2005'',''dd/mm/yyyy'') and to_date(to_char(tx.stncdate,''dd/mm/yyyy''),''dd/mm/yyyy'') < TO_DATE(''21/12/2005'',''dd/mm/yyyy'') group by tx.stndisc,tx.usrid,tx.itmcode, tx.glccode, sp.slpno,tx.stnsts, sp.slptype,tx.stncdate', 85);
INSERT INTO AA_QUERY(NAME, STATEMENT, STATEMENT_NO) VALUES ('ZIP Part 3', 'SELECT SUM(tx.stnnamt) AS SumOfStnnamt, tx.usrid FROM slip sp, sliptx tx WHERE sp.slpno = tx.slpno AND sp.slptype = ''I'' AND tx.itmcode = ''PAYME'' AND TO_DATE(TO_CHAR(tx.stncdate,''dd/mm/yyyy''),''dd/mm/yyyy'') >= TO_DATE(''20/12/2005'',''dd/mm/yyyy'') AND TO_DATE(TO_CHAR(tx.stncdate,''dd/mm/yyyy''),''dd/mm/yyyy'') < TO_DATE(''21/12/2005'',''dd/mm/yyyy'') GROUP BY tx.usrid, sp.slptype, tx.stncdate, tx.itmcode', 86);
INSERT INTO AA_QUERY(NAME, STATEMENT, STATEMENT_NO) VALUES ('ZOP Part 1', 'select sum(tx.stnnamt) as SumOfStnnamt, tx.usrid from slip sp, sliptx tx where sp.slpno = tx.slpno and sp.slptype = ''O'' and tx.itmcode = ''REF'' and TO_DATE(TO_CHAR(tx.stncdate,''dd/mm/yyyy''),''dd/mm/yyyy'') >= TO_DATE(''02/12/2005'' ,''dd/mm/yyyy'') AND TO_DATE(TO_CHAR(tx.stncdate,''dd/mm/yyyy''),''dd/mm/yyyy'') < TO_DATE(''03/12/2005'' ,''dd/mm/yyyy'') group by sp.slpno,tx.itmcode,tx.stncdate,tx.usrid', 87);
INSERT INTO AA_QUERY(NAME, STATEMENT, STATEMENT_NO) VALUES ('ZOP Part 2', 'select tx.stnnamt as TotalAmount , tx.usrid, tx.itmcode, tx.glccode from slip sp, sliptx tx where sp.slpno = tx.slpno and sp.slptype = ''O'' and TO_DATE(TO_CHAR(tx.stncdate,''dd/mm/yyyy''),''dd/mm/yyyy'') >= TO_DATE(''02/12/2005'',''dd/mm/yyyy'') AND TO_DATE(TO_CHAR(tx.stncdate,''dd/mm/yyyy''),''dd/mm/yyyy'') < TO_DATE(''03/12/2005'',''dd/mm/yyyy'')', 88); 
INSERT INTO AA_QUERY(NAME, STATEMENT, STATEMENT_NO) VALUES ('ZOP Part 3', 'select sum(tx.stnnamt) as SumOfStnnamt, tx.usrid from slip sp, sliptx tx where sp.slpno = tx.slpno and sp.slptype = ''O'' and tx.itmcode = ''PAYME'' and TO_DATE(TO_CHAR(tx.stncdate,''dd/mm/yyyy''),''dd/mm/yyyy'') >= TO_DATE(''02/12/2005'',''dd/mm/yyyy'') AND TO_DATE(TO_CHAR(tx.stncdate,''dd/mm/yyyy''),''dd/mm/yyyy'') < TO_DATE(''03/12/2005'',''dd/mm/yyyy'') group by sp.slpno,tx.itmcode,tx.stncdate,tx.usrid', 89);
INSERT INTO AA_QUERY(NAME, STATEMENT, STATEMENT_NO) VALUES ('ZMAXID2', 'select NAME, STATEMENT, STATEMENT_NO from aa_query', 90);
INSERT INTO AA_QUERY(NAME, STATEMENT, STATEMENT_NO) VALUES ('ZMAXID', 'select * from aa_query', 90);

COMMIT;