ALTER TABLE ALERT ADD PCYCODE VARCHAR2(2);
ALTER TABLE ALERT ADD ARCCODE VARCHAR2(5);

--TWAH Only
UPDATE ALERT 
SET PCYCODE = 'ST', ARCCODE = 'T1975'
WHERE ALTCODE = 'FT';

UPDATE ALERT 
SET PCYCODE = 'ST', ARCCODE = 'T1975'
WHERE ALTCODE = 'PT';

COMMIT;