ALTER TABLE ALERTGROUP
DROP PRIMARY KEY CASCADE;
DROP TABLE ALERTGROUP CASCADE CONSTRAINTS;

CREATE TABLE "ALERTGROUP"
(	"ALTID" NUMBER(22,0) NOT NULL ENABLE,
	"ATGID" VARCHAR2(10 BYTE) DEFAULT 'ALL' NOT NULL ENABLE,
	CONSTRAINT "ALERTGROUP_PK" PRIMARY KEY ("ALTID", "ATGID")
);