DROP TABLE APPBILLS;

CREATE TABLE  "APPBILLS" 
   (           "BILLID" NUMBER(22,0) NOT NULL ENABLE, 
                "PATNO" VARCHAR2(10 BYTE), 
                "BILLTYPE" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
                "BILLSTS" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
                "BILLPAMT" FLOAT(126), 
                "BILLOAMT" FLOAT(126), 
                "BILLTITLE" VARCHAR2(100 BYTE), 
                "BILLREMARK" VARCHAR2(1000 BYTE), 
                "ISDISPAYMT" VARCHAR2(20 BYTE), 
                "BILLDATE" DATE, 
                "BILLCUSER" VARCHAR2(10 BYTE), 
                "BILLTDATE" DATE, 
                "SLPNO" VARCHAR2(20 BYTE), 
                "ISREQRECEIPT" VARCHAR2(20 BYTE), 
                "BILLSTMTTYPE" VARCHAR2(20 BYTE), 
                 PRIMARY KEY ("BILLID")
);



CREATE SEQUENCE "SEQ_APPBILLS"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;