DROP TABLE APPBILLSTX;

CREATE TABLE "APPBILLSTX" 
   (           "BILLID" NUMBER(22,0) NOT NULL ENABLE, 
                "BILLTXID" NUMBER(22,0) NOT NULL ENABLE, 
                "BILLTXAMT" FLOAT(126), 
                "BILLTXSTS" VARCHAR2(10 BYTE), 
                "REFID" VARCHAR2(100 BYTE), 
                "TXID" VARCHAR2(100 BYTE), 
                "CARDNO" VARCHAR2(100 BYTE), 
                "PAYMETHOD" VARCHAR2(100 BYTE), 
                "TXDATE" DATE, 
                "CREATE_USER" VARCHAR2(20 BYTE), 
                "CREATE_DATE" DATE, 
                "MODIFIED_USER" VARCHAR2(20 BYTE), 
                "MODIFIED_DATE" DATE, 
                "ISNOTFSEND" VARCHAR2(2 BYTE), 
                 PRIMARY KEY ("BILLTXID")
   );



CREATE SEQUENCE " SEQ_APPBILLSTX"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;