CREATE TABLE ARCARD_CHECKLIST_DTL (
ACTID NUMBER(22,0),
TYPE VARCHAR2(6),
CHECK_ID VARCHAR2(2),
OTHER_DESC VARCHAR2(100),
ENABLED NUMBER(1)
)


CREATE TABLE ARCARD_CHECKLIST
(
CHECK_ID VARCHAR2(2),
CHECK_TYPE VARCHAR2(1),
DESCRIPTION VARCHAR2(100)
);


INSERT INTO ARCARD_CHECKLIST_DTL (
ACTID,
TYPE,
CHECK_ID,
OTHER_DESC,
ENABLED                                                                                                                                                                                
)
SELECT ART.ACTID,'In',AC.CHECK_ID,NULL,0  
FROM ARCARD_CHECKLIST AC, ARCARDTYPE ART
UNION ALL
SELECT ART.ACTID,'Out',AC.CHECK_ID,NULL,0  
FROM ARCARD_CHECKLIST AC, ARCARDTYPE ART
;
/