ALTER TABLE ARCARDTYPE ADD COLOUR1 VARCHAR2(20);
ALTER TABLE ARCARDTYPE ADD COLOUR2 VARCHAR2(20);
ALTER TABLE ARCARDTYPE ADD EBILLING NUMBER(1) DEFAULT 0;
ALTER TABLE ARCARDTYPE ADD SENDORGINV NUMBER(1) DEFAULT 0;
ALTER TABLE ARCARDTYPE ADD SAMPLEINV VARCHAR2(2000);
ALTER TABLE ARCARDTYPE ADD ARCARDSDATE DATE;
ALTER TABLE ARCARDTYPE ADD ARCARDEDATE DATE;
ALTER TABLE ARCARDTYPE ADD UPLOADTOPORTAL NUMBER(1) DEFAULT 0;
ALTER TABLE ARCARDTYPE ADD BILLINGOTHER VARCHAR2(500);