DROP TABLE ARNATURE;
CREATE TABLE ARNATURE 
(
	ARNID		NUMBER(10) NOT NULL,
	ARNNAME		VARCHAR2(100 BYTE),
	ARNACTIVE	NUMBER(1),
	CONSTRAINT "PK_ARNATURE" PRIMARY KEY ("ARNID")
);
/

INSERT INTO ARNATURE(ARNID, ARNNAME, ARNACTIVE)
VALUES ('1', 'Insurance', '-1');

INSERT INTO ARNATURE(ARNID, ARNNAME, ARNACTIVE)
VALUES ('2', 'TPA', '-1');

INSERT INTO ARNATURE(ARNID, ARNNAME, ARNACTIVE)
VALUES ('3', 'Corporate', '-1');

INSERT INTO ARNATURE(ARNID, ARNNAME, ARNACTIVE)
VALUES ('4', 'Credit Card', '-1');

INSERT INTO ARNATURE(ARNID, ARNNAME, ARNACTIVE)
VALUES ('5', 'Medical Facility', '-1');

INSERT INTO ARNATURE(ARNID, ARNNAME, ARNACTIVE)
VALUES ('6', 'Consulate', '-1');

INSERT INTO ARNATURE(ARNID, ARNNAME, ARNACTIVE)
VALUES ('7', 'HA', '-1');

INSERT INTO ARNATURE(ARNID, ARNNAME, ARNACTIVE)
VALUES ('8', 'VIP', '-1');

INSERT INTO ARNATURE(ARNID, ARNNAME, ARNACTIVE)
VALUES ('9', 'Funds', '-1');

INSERT INTO ARNATURE(ARNID, ARNNAME, ARNACTIVE)
VALUES ('99', 'Others', '-1');


COMMIT;