ALTER TABLE BEDPREBOK_EXTRA
DROP PRIMARY KEY CASCADE;
DROP TABLE BEDPREBOK_EXTRA CASCADE CONSTRAINTS;

CREATE TABLE BEDPREBOK_EXTRA(
	PBPID NUMBER(22,0) NOT NULL ENABLE,
	PBMID NUMBER(10,0),
	PBSNO VARCHAR2(20),
	ISRECLG NUMBER(1,0),
	ARACMCODE VARCHAR2(10),
	PBSID NUMBER(10,0),
	PBPKGCODE VARCHAR2(10),
	ACTID NUMBER(22,0),
	ESTGIVN NUMBER(1,0),
	COPAYAMTACT NUMBER(22,0),
	FESTID NUMBER(22,0),
	PRIMARY KEY (PBPID)
);

ALTER TABLE BEDPREBOK_EXTRA ADD (
	CONSTRAINT BEDPREBOK_EXTRA_R01
	FOREIGN KEY (PBPID)
	REFERENCES BEDPREBOK (PBPID));
