ALTER TABLE BOOKING ADD BkgADate DATE;
ALTER TABLE BOOKING ADD BkgMAC VARCHAR2(20);

ALTER TABLE BOOKING MODIFY BKGRMK VARCHAR2(100);
ALTER TABLE BOOKING ADD BkgAlert VARCHAR2(20);
ALTER TABLE BOOKING ADD DOCLOCID NUMBER(22, 0);