ALTER TABLE BOOKINGALERT
 DROP PRIMARY KEY CASCADE;
DROP TABLE BOOKINGALERT CASCADE CONSTRAINTS;

CREATE TABLE BOOKINGALERT(
    BKAID    NUMBER(10,0) NOT NULL ENABLE,
    BKAORD   NUMBER(5,0),
    BKADESC  VARCHAR2(100 BYTE),
    BKACODE  VARCHAR2(10 BYTE),
    BKAQUOTA NUMBER(5,0) DEFAULT 0 NOT NULL,
    BKASTS   NUMBER(1,0) DEFAULT -1 NOT NULL,
    CONSTRAINT "PK_BOOKINGALERT" PRIMARY KEY ("BKAID")
);

--hkah
INSERT INTO BOOKINGALERT (BKAID, BKAORD, BKADESC, BKASTS) VALUES (0, 0, 'NOT APPLICABLE', -1);
INSERT INTO BOOKINGALERT (BKAID, BKAORD, BKADESC, BKASTS) VALUES (1, 1, 'MERS', -1);
INSERT INTO BOOKINGALERT (BKAID, BKAORD, BKADESC, BKASTS) VALUES (2, 2, 'FEVER', 0);
INSERT INTO BOOKINGALERT (BKAID, BKAORD, BKADESC, BKASTS) VALUES (3, 3, 'PNEUMONIA', 0);
INSERT INTO BOOKINGALERT (BKAID, BKAORD, BKADESC, BKASTS) VALUES (4, 4, 'DIARRHOEA', 0);

commit;
