ALTER TABLE BOOKING_EXTRA
DROP PRIMARY KEY CASCADE;
DROP TABLE BOOKING_EXTRA CASCADE CONSTRAINTS;

CREATE TABLE BOOKING_EXTRA(
	BKGID	 NUMBER(22, 0) NOT NULL ENABLE,
	BKGUUSER VARCHAR2(10),
	BKGUDATE DATE,
	LBLRMK VARCHAR2(22 BYTE),
	PAYMENTMETHOD VARCHAR2(1 BYTE),
	NATUREOFVISIT VARCHAR2(10 BYTE),
	BKGID_C NUMBER(22, 0),
	DOCSMSSDT DATE,
	DOCSMSSDTOK DATE,
	DOCSMSRTNMSG VARCHAR2(20 BYTE),
	EXTDOCCODE VARCHAR2(100 BYTE),
	PRIMARY KEY (BKGID)
);

ALTER TABLE BOOKING_EXTRA ADD (
	CONSTRAINT BOOKING_EXTRA_R01
	FOREIGN KEY (BKGID)
	REFERENCES BOOKING (BKGID));


ALTER TABLE BOOKING_EXTRA ADD DOCSMSSDT DATE;
ALTER TABLE BOOKING_EXTRA ADD DOCSMSSDTOK DATE;
ALTER TABLE BOOKING_EXTRA ADD DOCSMSRTNMSG VARCHAR2(20);