ALTER TABLE CARDTX MODIFY CTNMID VARCHAR2(40); -- 15 -> 40
ALTER TABLE CARDTX MODIFY CTNCNO VARCHAR2(40); -- 19 -> 40
ALTER TABLE CARDTX MODIFY CTNRRN VARCHAR2(40); -- 12 -> 40
ALTER TABLE CARDTX MODIFY REFNO VARCHAR2(40); -- 20 -> 40
--ALTER TABLE CARDTX ADD TXID VARCHAR2(32);
--ALTER TABLE CARDTX ADD OPENID VARCHAR2(48);
--ALTER TABLE CARDTX ADD RFNO VARCHAR2(40);
--ALTER TABLE CARDTX ADD RFID VARCHAR2(40);
