CREATE TABLE CASHIER_HISTORY(
	CSHCODE VARCHAR2(3 BYTE) NOT NULL ENABLE,
	CSHACT VARCHAR2(10 BYTE) NOT NULL ENABLE,
	CSHTS DATE NOT NULL ENABLE,
	USRID VARCHAR2(10 BYTE) NOT NULL ENABLE,
	CSHTYPE VARCHAR2(1 BYTE),
	CSHSTS VARCHAR2(1 BYTE) NOT NULL ENABLE,
	CSHRCNT NUMBER(22,0) NOT NULL ENABLE,
	CSHMAC VARCHAR2(20 BYTE),
	CSHODATE DATE,
	CSHFDATE DATE,
	CSHSID NUMBER(22,0) NOT NULL ENABLE,
	STECODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
	CSHADV FLOAT(126) NOT NULL ENABLE,
	CSHPAYIN FLOAT(126) NOT NULL ENABLE,
	CSHPAYOUT FLOAT(126) NOT NULL ENABLE,
	CSHREC FLOAT(126) NOT NULL ENABLE,
	CSHCHQ FLOAT(126) NOT NULL ENABLE,
	CSHEPS FLOAT(126) NOT NULL ENABLE,
	CSHCARD FLOAT(126) NOT NULL ENABLE,
	CSHOTHER FLOAT(126) NOT NULL ENABLE,
	CSHCRCNT NUMBER(22,0) NOT NULL ENABLE,
	CSHVCNT NUMBER(22,0) NOT NULL ENABLE,
	CSHATP FLOAT(126),
	CSHATPOUT FLOAT(126),
	CSHCHQOUT FLOAT(126),
	CSHCARDOUT FLOAT(126),
	CSHOCTOUT FLOAT(126),
	CSHOCTIN FLOAT(126),
	CSHCUPOUT FLOAT(126),
	CSHCUPIN FLOAT(126)
	CSHQROUT FLOAT(126),
	CSHQRIN FLOAT(126)
);

ALTER TABLE CASHIER_HISTORY ADD CSHQROUT FLOAT(126);
ALTER TABLE CASHIER_HISTORY ADD CSHQRIN FLOAT(126);
