DROP TABLE COVERAGE;
CREATE TABLE COVERAGE 
(
	"CARDID" 				VARCHAR2(20 BYTE) NOT NULL,
	"HEALTHTEXT"			VARCHAR2(80 BYTE),
	"IMMUNIZATIONTEXT"		VARCHAR2(80 BYTE),
	"PRENATALTEXT"			VARCHAR2(80 BYTE),
	"COVERATE"				VARCHAR2(20 BYTE),
	"WBTEXT"				VARCHAR2(80 BYTE)
);
/
alter table COVERAGE add ACTID NUMBER(22); 

SET DEFINE OFF

INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('MIT', '-	Covered (contact Prestige)', 'some covered (*attachment)', 'Covered', 'Baby Health check', 'Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('HSBCSI', 'Not Covered', 'Covered', 'Covered', 'Well-baby', 'Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('ISOSAIU', 'Not Covered', 'Not Covered', 'Not Covered', 'Well-baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('FUJITSU', 'Covered (contact Prestige)', 'some covered (*attachment)', 'Covered', 'Baby Health check', 'Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('QHCL4', 'according to LOG', 'according to LOG', 'according to LOG', 'OP medical report', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('NFCL', 'Not Covered', '', 'Not Covered', 'Dietician', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('GHAL15', 'Not Covered', 'Not Covered', 'Cover if with Authorization Letter', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('BUPAI5', 'Refer to LOG', 'Refer to LOG', 'Refer to LOG', 'WELL-BABY', 'Refer to LOG');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('AAO', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('AC', 'Refer to LOG', 'Refer to LOG', 'Refer to LOG', 'Well Baby', 'Refer to LOG');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('ACC', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('ACEI2', 'Not Covered', 'Not Covered', 'Not Covered', 'Well-baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('ACI', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('AIA1', 'Not Covered', 'Not Covered', 'Depends, Check w/ Co', 'Well-baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('AIAHS1', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('AIAHS2', 'Not Covered', 'Not Covered', 'Not Covered', 'Well-baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('AIAHS3', 'Not Covered', 'Not Covered', 'Not Covered', 'Well-baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('AIG', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('AIGJAP', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('AIGJAP2', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('AIGJAP3', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('AIOI', 'Not Covered', 'Not Covered', 'Not Covered', 'Wel- baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('AIUJAP', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('AIUJAP2', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('AIUJAP3', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('ALA', 'Refer Letter of Guarantee', 'Refer Letter of Guarantee', 'Refer Letter of Guarantee', 'Well-baby', 'Refer Letter of Guarantee');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('ALC', 'Refer to LOA', 'Refer to LOA', 'Refer to LOA', 'Well Baby', 'Refer to LOA');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('ALL', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('AMCG', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('AMP', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('AND', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('AOHK', 'Refer to LOG', 'Refer to LOG', 'Refer to LOG', 'Well-Bay', 'Refer to LOG');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('AONC', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('APR', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('ASA', 'Not Covered', 'Not Covered', 'Not Covered', 'Well-baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('ASH', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('ASI', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('AUCC', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('AUCG', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('AWC', 'Refer to LOG', 'Refer to LOG', 'Refer to LOG', 'Well-baby', 'Refer to LOG');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('AXAC1', 'Not Covered', 'Not Covered', 'Covered (CB Wordings)', 'Well-baby', 'Covered (CB Wordings)');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('AXAG1', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('AXAG2', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('BANG', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('BATC', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('BC', 'Not Covered', 'Not Covered', 'Not Covered', 'Well-baby / Dental', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('BC1', 'Not Covered', 'Not Covered', 'Not Covered', 'Well-baby / Dental', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('BCCPCE', 'Not Covered', 'Not Covered', 'Not Covered', 'Well-baby / Dental', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('BCEOS', 'Not Covered', 'Not Covered', 'Not Covered', 'Well-baby / Dental', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('BCPOLY', 'Not Covered', 'Not Covered', 'Not Covered', 'Well-baby / Dental', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('BHP', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('BOC', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('BOEIN', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('BRCG', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('BREC', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('BS', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('BUPAI', 'Refer to LOG', 'Refer to LOG', 'Refer to LOG', 'WELL-BABY', 'Refer to LOG');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('BUPAS', 'Not Covered', 'Not Covered', 'Covered (w/ MA wordings)', 'Well-baby /dietitian', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('BUPAS2', 'Not Covered', 'Not Covered', 'Not Covered', 'Well-baby /dietitian', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('BUPASG', 'Not Covered', 'Not Covered', 'Not Covered', 'Well-baby /dietitian', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('BUPASHN', 'Not Covered', 'Not Covered', 'Covered (w/ MA Wordings)', 'Well-baby /dietitian', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('BYRNE', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('CALTE', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('CCC', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('CEGA', 'Not Covered', 'Not Covered', 'Not Covered', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('CGC', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('CHU', 'Not Covered', 'Not Covered', 'Not Covered', 'well-baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('CIGHK', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('CIGIN', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('CIGUS', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('CIM', 'Not Covered', 'Covered', '"Maternity" shown on card', 'Cosmetic Treatment', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('CLI', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('CLP', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('CMG', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('COC', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('COMM', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('COSMOS', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('CP', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('DAIWA', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('DAIWI', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('DAP', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('DEC', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('DETP', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('DF', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('DHI', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('DHI2', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('DHI3', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('DOC', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('DOHM', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('DRV', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('EAC', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('EAJ', 'Not Covered', 'Not Covered', 'Not Covered', 'Well-baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('EC', 'Refer to LOG', 'Refer to LOG', 'Refer to LOG', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('EC1', 'Refer to LOG', 'Refer to LOG', 'Refer to LOG', 'Well-baby', 'Refer to LOG');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('EDP', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('ELIC', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('ERICS', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('EURO', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('EUROP', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('FALCO', 'Confirm with FALCO', 'Covered', 'Confrim with FALCO', 'Well-baby', 'Confirm with FALCO');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('FF', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('FINNISH', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('FORTIS', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('FORTIS2', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('FUJI', 'Not Covered', 'Not Covered', 'Not Covered', 'Well-baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('GAG', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('GATE', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('GD', 'Refer to LOG', 'Refer to LOG', 'Refer to LOG', 'Well-baby', 'Refer to LOG');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('GHAL', 'Not Covered', 'Not Covered', 'Covered with auth letter', 'Well-baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('GII', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('GLE', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('GMC', 'Not Covered', 'Not Covered', 'Not Covered', 'Pharmacy & Rehab', 'NO direct billing');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('GPT', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('GT', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('GTEI', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('HITA', 'Covered', 'some covered (*attachment)', 'Covered', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('HKE', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('HKJC', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('HKM', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('HKRFU', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('HMMP', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('HS', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('HS1', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('HS2', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('HS3', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('HSBC', 'Not Covered', 'Covered', 'Covered', 'Well-baby', 'Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('HSBC1', 'Not Covered', 'Covered (special price)', 'Covered', 'Well-baby', 'Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('HSBCCO', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('HSBCJA', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('HSBCKCRC', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('HSBCMTR', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('HSBCPC', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('HSBCS', 'Not Covered', 'Not Covered', 'Not Covered', 'Physio', 'Self Pay / refer to Panel');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('HSBFC', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('HTH', 'Refer to LOG', 'Refer to LOG', 'Refer to LOG', 'Well-baby', 'Refer to  LOG');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('HUT', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('IBL', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('IBM', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('IF', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('IGAS', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('IGNZ', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('IHID', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('IMA', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('IMS', 'not Covered (prior approval is required)', 'Check with IMS', 'Covered', 'Well-baby', 'Check with IMS');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('INC', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('ING', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('ING2', 'Not Covered', 'Not Covered', 'Not Covered', 'Well-baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('IPA', 'Not Covered', 'Not Covered', 'Not Covered', 'Well-baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('ISOSU', 'Not Covered', 'Not Covered', 'Not Covered', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('JAI', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('JAIC', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('JC', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('JCOLS', 'Not Covered', 'Not Covered', 'Not Covered', 'Well Baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('JHN', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('JHS', 'Not Covered', 'Covered (except newborn)', 'Covered', 'Optical Glass', 'Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('JIA', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('JIA1', 'Not Covered', 'Not Covered', 'Not Covered', 'Well-baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('JSS', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('KPMG', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('KUCG', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('KYOEI', 'Not Covered', 'Not Covered', 'Not Covered', 'Well-baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('LIB', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('LII', 'Cover by LOG', 'Refer to LOG', 'Refer to LOG', 'Well-baby', 'Refer to LOG');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('MACG', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('MANUL', 'Not Covered', 'Not Covered', 'Not Covered', 'Well-baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('MANUL1G', 'Not Covered', 'Not Covered', 'Not Covered', 'Well-baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('MANUL1S', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('MANULI', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('MASA', 'Refer by LOG', 'Refer by LOG', 'Refer by LOG', 'Well-baby', 'Refer by LOG');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('MC', 'Covered', 'Covered', 'Covered', 'Well-baby', 'Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('MCA', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('MCD', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('MCPPO', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('MERC', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('MIC', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('MITA', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('MITSU', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('MITSUI', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('MITSUISU', 'Not Covered', 'Not Covered', 'Not Covered', 'Well-baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('MLC', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('MLUS', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('MMA', 'Not Covered', 'Not Covered', 'Not Covered', 'Well-baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('MOB', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('MUFG', 'Not Covered', 'Not Covered', 'Not Covered', 'Well-baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('NC', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('NESHK', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('NEW', 'Not Covered', 'Not Covered', 'Not Covered', 'Well-baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('NEWZ', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('NGFSS', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('NICHI', 'Not Covered', 'Not Covered', 'Not Covered', 'Well-baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('NIPE', 'Not Covered', 'Not Covered', 'Not Covered', 'Well-baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('NIPI', 'Not Covered', 'Not Covered', 'Not Covered', 'Well-baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('NISS', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('NISSA', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('NISSAJI', 'Not Covered', 'Not Covered', 'Not Covered', 'Well-baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('NISSEAJ', 'Not Covered', 'Not Covered', 'Not Covered', 'Well-baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('NISSH', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('NISSHI', 'Not Covered', 'Not Covered', 'Not Covered', 'Well-baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('NLH', 'Refer to LOG', 'Refer to LOG', 'Refer to LOG', 'Well-baby', 'Refer to LOG');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('NORMU', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('OAP', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('OHRA', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('OME', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('OP1', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('PC', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('PCI', 'Not Covered', 'Not Covered', 'Covered ( w/ CB wordings)', 'Well-baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('PEC', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('PG', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('PHIL', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('PIHK', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('PII', 'Not Covered', 'Not Covered', 'Not Covered', 'Well-baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('PPP', 'Not Covered', 'Not Covered', 'Not Covered', 'Dental, Physio', 'Self-pay');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('PRICI', 'Covered', 'Covered', 'Covered', 'Travel Medicine', 'Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('PRICICO', 'Covered', 'Covered', 'Covered', 'Travel Medicine', 'Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('PRUD', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('QBE', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('QHCPA', 'Not Covered', 'Not Covered', 'Not Covered', 'Well-baby /dietitian', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('QHMS', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('RAF', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('RC', 'Refer to LOG', 'Refer to LOG', 'Refer to LOG', 'Well-baby', 'Refer to LOG');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('RICOH', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('ROY', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('RYO', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('SAL', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('SAN', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('SAS', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('SBCM', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('SECOM', 'Not Covered', 'Not Covered', 'Not Covered', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('SOJIT', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('SOMP', 'Not Covered', 'Not Covered', 'Not Covered', 'Well-baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('SUMI', 'Not Covered', 'Not Covered', 'Not Covered', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('SUMITO', 'Not Covered', 'Not Covered', 'Not Covered', 'Well-baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('SUNL', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('TAIUN', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('TARGET', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('TMD', 'Not Covered', 'Not Covered', 'Not Covered', 'Well-baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('TOKIO', 'Not Covered', 'Not Covered', 'Not Covered', 'Well-baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('TOKIO1', 'Not Covered', 'Not Covered', 'Not Covered', 'Well-baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('TPLI', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('TRYG', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('TSW', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('TTTS', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('TUCG', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('TYSO', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('UA', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('UFJ', 'Not Covered', 'Not Covered', 'Not Covered', 'Well-baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('UHC', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('UMP', 'Not Covered', 'Not Covered', 'Not Covered', 'Well-baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('USN', 'Refer to LOG', 'Refer to LOG', 'Refer to LOG', 'Well-baby', 'Refer to LOG');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('VHI1', 'Covered', 'Not Covered', 'Not Covered', 'Well-baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('VI', 'by guarantee (VI1)', 'Not Covered', '', 'dental,physio', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('VI2', 'Check-up service with member ID no starting with "206/"', 'By LOG', 'By LOG', 'Well-baby', 'BY LOG');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('VIL', 'By LOG', 'By LOG', 'By LOG', 'Well-kig', 'By LOG');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('WAA', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('WAC', 'Refer to LOG', 'Refer to LOG', 'Refer to LOG', 'Well-log', 'Refer to LOG');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('WAP', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('WR', 'Not Covered', 'Not Covered', 'Not Covered', 'Well Baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('YASU', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('ZC', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('ZIM', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('BOC2', '', '', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('PRICICO2', 'Covered', 'Covered', 'Covered', 'Travel Medicine', 'Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('H.S.', 'Not Covered', 'Not Covered', 'Not Covered', 'well-baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('SONY', 'Not Covered', 'Not Covered', 'Not Covered', 'well-baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('Pcross', 'Not Covered', 'Not Covered', 'Not Covered', 'well-baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('LII2', 'Cover by LOG', 'Refer to LOG', 'Refer to LOG', 'Well-baby', 'Refer to LOG');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('BUPASHN1', 'Not Covered', 'Not Covered', 'Covered (w/ MA Wordings)', 'Well-baby /dietitian', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('BUPAS1', 'Not Covered', 'Not Covered', 'Covered (w/ MA wordings)', 'Well-baby /dietitian', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('ISUZU', 'Covered', 'some covered (*attachment)', 'Covered', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('JSR', 'Not Covered', 'Not Covered', 'Not Covered', 'Well-baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('BUPAI3', 'Refer to LOG', 'Refer to LOG', 'Refer to LOG', 'WELL-BABY', 'Refer to LOG');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('BUPAI2', 'Refer to LOG', 'Refer to LOG', 'Refer to LOG', 'WELL-BABY', 'Refer to LOG');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('BUPAI1', 'Refer to LOG', 'Refer to LOG', 'Refer to LOG', 'WELL-BABY', 'Refer to LOG');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('NIPE1', 'Not Covered', 'Not Covered', 'Not Covered', 'Well-baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('AIAHS4', 'Not Covered', 'Not Covered', 'Covered (with "MAT" wordings)', 'Well-baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('AIAHS5', 'Not Covered', 'Not Covered', 'Not Covered', 'Well-baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('WellBe', 'Covered', 'Not Covered', 'Not Covered', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('QHCL1', 'special  LOG (not on-line LOG)', 'see on-line  LOG', 'see on-line  LOG', 'OP medical report', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('QHCL3', 'special  LOG (not on-line LOG)', 'refer on-line LOG', 'refer on-line LOG', 'OP medical report', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('QHCL2', 'special  LOG (not on-line LOG)', 'refer on-line LOG', 'refer on-line LOG', 'OP medical report', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('TRICA', 'Not Covered', 'Not Covered', 'Not Covered', 'Over counter drug', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('MGS', 'Not Covered', 'Not Covered', 'Not Covered', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('QHCL5', 'special  LOG (not on-line LOG)', 'refer on-line LOG', 'refer on-line LOG', 'OP medical report', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('NITTO', 'Not Covered', 'Not Covered', 'Not Covered', 'Well-baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('MYTS', 'Not Covered', 'Not Covered', 'Not Covered', 'Well Baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('KIRIN', 'Covered (contact Prestige)', 'Covered', 'Covered', 'physio /dental check', 'not covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('MEDILINK', '', '', '', 'OP Surgery,MRI,CT', 'pre-authorization');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('VI_A+', 'by guarantee (VI1)', 'pay & claim', '', 'dental,physio', 'pay & claim');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('VI_Aramco', 'by guarantee (VI1)', 'pay & claim', '', 'dental,physio', 'pay & claim');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('SINOMED', 'Not Covered', 'Not Covered', 'Not Covered', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('MAI', 'Not Covered', 'Not Covered', 'Not Covered', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('MAIG', 'Not Covered', 'Not Covered', 'Not Covered', ' Physio & Dental', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('AXAC2', 'Not Covered', 'Not Covered', 'Covered (CB Wordings)', 'Well-Baby', 'Covered (CB Wordings)');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('UNITEDH', 'Refer to LOG', 'Refer to LOG', 'Refer to LOG', 'Well Baby', 'Refer to LOG');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('GeoBlue', 'Refer to LOG', 'Refer to LOG', 'Refer to LOG', 'Well Baby', 'Refer to LOG');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('NYK', 'Not Covered', 'Not Covered', 'Not Covered', 'Well baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('PHHKL', 'refer Guarantee', 'refer Guarantee', 'refer Guarantee', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('Healix', 'refer to LOG', 'refer to LOG', 'refer to LOG', 'Well Baby', 'refer to LOG');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('BUPASHN3', 'Not Covered', 'Not Covered', 'Covered (w/ MA Wordings)', 'Well-baby /dietitian', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('BUPASHN2', 'Not Covered', 'Not Covered', 'Covered (w/ MA Wordings)', 'Well-baby /dietitian', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('GHAL2', 'Not Covered', 'Not Covered', 'Cover if with Authorization Letter', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('GHAL10', 'Not Covered', 'Not Covered', 'Cover if with Authorization Letter', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('GHAL9', 'Not Covered', 'Not Covered', 'Cover if with Authorization Letter', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('GHAL1', 'Not Covered', 'Not Covered', 'Cover if with Authorization Letter', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('GHAL7', 'Not Covered', 'Not Covered', 'Cover if with Authorization Letter', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('GHAL4', 'Not Covered', 'Not Covered', 'Cover if with Authorization Letter', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('GHAL5', 'Not Covered', 'Not Covered', 'Cover if with Authorization Letter', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('WellBe1', 'Covered', 'Not Covered', 'Not Covered', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('FANUC', 'Not Covered', 'Not Covered', 'Not Covered', 'Well Baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('PAHI2', 'Not Covered', 'Not Covered', 'Not Covered', 'Well Baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('PAHI1', 'Not Covered', 'Not Covered', 'Not Covered', 'Well Baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('HKAH', 'Not Covered', 'Covered', 'Not Covered', 'Physio, rita, becky,', 'covered (refer LOG, co0jsuruoj,. Physio not )');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('TM', 'Covered (Contact Prestige)', 'Covered', 'Covered', 'Well-baby', 'Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('GHAL14', 'Not Covered', 'Not Covered', 'Covered if with Authorisation letter', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('FWD', '', '', '', 'maternity / mental', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('WATAMI', 'Not Covered', 'Not Covered', 'Not Covered', 'Well baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('ACEI3', 'Not Covered', 'Not Covered', 'Not Covered', 'Well Baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('TOYOTA', 'Not Covered', 'Not Covered', 'Not Covered', 'Pre-natal', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('BUPAS4', 'Not Covered', 'Not Covered', 'Covered (w/ MA Wordings)', 'Well-baby /dietitian', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('BUPAS5', 'Covered', 'Covered', 'Covered (w/ MA wordings)', 'Well-baby /dietitian', 'Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('TOSHIBA', 'Not Covered', 'Not Covered', 'Not Covered', 'Well Baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('DALI', 'Refer to LOG', 'Refer to LOG', 'Refer to LOG', 'Well Baby', 'Refer to LOG');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('HIROSE', 'Covered (contact Prestige)', 'Covered', 'Covered', 'Well-baby', 'Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('DRKA', 'refer LOG', 'refer LOG', 'refer LOG', 'Well Baby', 'refer LOG');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('NHI', 'Not Covered', 'Not Covered', 'check card face', 'Dental & Well Baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('MSIGP', 'Not Covered', 'Not Covered', 'Not Covered', 'Well-Baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('RENESAS', 'Covered (contact Prestige)', 'some covered (*attachment)', 'Covered', 'Baby Health check', 'Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('NOMURA', 'refer to LOA', 'refer to LOA', 'refer to LOA', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('Murata', 'Covered (contact Prestige)', 'Covered', 'Covered', 'Baby Health check', 'Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('HSBC-A', 'Not Covered', 'Covered', 'Covered', 'Well Baby', 'Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('HSBCS1', 'Not Covered', 'Not Covered', 'Not Covered', 'Physio', 'Self Pay / refer to Panel');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('NIPI1', 'Not Covered', 'Not Covered', 'Not Covered', 'Well Baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('NOMURA1', 'Pre-arrange', 'Cover Flu-shot (Other types, Pay & Claim)', 'Covered Prenatal only', 'Physio', 'Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('CMNGen1', 'Not Covered', 'Not Covered', 'Not Covered', 'Well baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('NAXIS', 'Not Covered', 'Not Covered', 'Not Covered', 'Well Baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('AMA', 'Not Covered', 'Not Covered', 'Not Covered', 'Well baby, Physio', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('GHAL12', 'Not Covered', 'Not Covered', 'Cover if with Authorization Letter', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('GHAL8', 'Not Covered', 'Not Covered', 'Cover if with Authorization Letter', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('GHAL6', 'Not Covered', 'Not Covered', 'Cover if with Authorization Letter', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('GHAL11', 'Not Covered', 'Not Covered', 'Cover if with Authorization Letter', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('MAPFRE', 'Not Covered', 'Not Covered', 'Not Covered', 'Well Baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('NEC', 'Covered (contact Prestige)', 'Covered', 'Not Covered', 'Baby Health check', 'Covered (contact Prestige)');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('Sony_PI', 'Not Covered', 'Not Covered', 'Not Covered', 'Well Baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('JD', 'Not Covered', 'Not Covered', 'Not Covered', 'Well Baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('TPC', 'Not Covered', 'refer to LOG', 'refer to LOG', 'Well Baby', 'refer to LOG');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('MOFA', 'Pre-arrange', 'Pay & Claim', 'Covered (Pre-natal only)', 'Physio', 'by LOA (for each visit)');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('OKAMURA', 'Not Covered', 'Not Covered', 'Not Covered', 'Well Baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('HSBC-A1', 'Not Covered', 'Covered', 'Covered', 'Well-baby', 'Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('TSCL', 'refer to LOG', 'refer to LOG', 'refer to LOG', 'Well Baby', 'refer to LOG');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('HIS', 'refer to LOG', 'refer to LOG', '', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('DKV3', 'Not Covered', 'Not Covered', 'Not Covered', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('DALI1', 'Not Covered', 'Not Covered', 'Not Covered', 'Well Baby', 'refer to LOG');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('IPA1', 'Not Covered', 'Not Covered', 'Not Covered', 'Wellbaby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('TOKIO2', 'Not Covered', 'Not Covered', 'Not Covered', 'Well-baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('WellBe2', 'Covered', 'Not Covered', 'Not Covered', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('SOSI', 'upto Euro $1,000', 'upto Euro $1,000', 'Not Covered', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('SOSI1', 'upto Euro $1,000', 'upto Euro $1,000', 'Not Covered', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('MEID', 'Covered (contact Prestige)', 'Covered', 'Covered', 'Well Baby', 'Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('AIU', 'Not Covered', 'Not Covered', 'Not Covered', 'Well Baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('CS', 'refer LOG', 'refer LOG', 'refer LOG', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('RKCG', 'Refer to LOG', 'Refer to LOG', 'Refer to LOG', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('NHI1', 'Not Covered', 'Not Covered', 'check card face', 'Well Baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('OPTEX', 'covered (contact Prestige)', 'Covered', 'Covered', 'Well Baby', 'Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('AJIN', '', '', '', 'Well Baby', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('DAIW', 'Not Covered', 'Not Covered', 'Not Covered', 'Well baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('NIPI2', 'Not Covered', 'Not Covered', 'Not Covered', 'Well Baby', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('MSHC', 'Refer to card face', 'Refer to card face', 'Not Covered', 'Vision', 'Refer to card face');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('QHM', 'Not Covered', 'Not Covered', 'Not Covered', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('GHAL3', 'Not Covered', 'Not Covered', 'Cover if with Authorization Letter', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('GHAL13', 'Not Covered', 'Not Covered', 'Cover if with Authorization Letter', '', '');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('BUPAS3', 'Not Covered', 'Not Covered', 'Covered (w/ MA wordings)', 'Well-baby /dietitian', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('CIGIN_VI', 'Not Covered', 'Not Covered', '', 'Physiotherapy', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('NFMCL', 'Not Covered', '', 'Not Covered', 'Dietician', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('WFPL', 'Not Covered', '', 'Not Covered', 'Dietician', 'Not Covered');


INSERT INTO COVERAGE (CARDID, HEALTHTEXT, IMMUNIZATIONTEXT, PRENATALTEXT, COVERATE, WBTEXT) 
VALUES ('CIGVI', 'No direct bill', 'No direct bill', '', 'Dental, Physio', 'No direct bill');

COMMIT;