DROP TABLE DEPT_APP;

DROP SEQUENCE SEQ_DEPT_APP;
CREATE SEQUENCE SEQ_DEPT_APP MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE ;

CREATE TABLE DEPT_APP
  (
  	"DEPTTYPE" VARCHAR2(40 BYTE) NOT NULL ,
    "DEPTAID"   NUMBER(10,0) NOT NULL ,
    "PATNO" VARCHAR2(10 BYTE) ,
    "DEPTAFNAME" VARCHAR2(40 BYTE) NOT NULL ,
    "DEPTAGNAME" VARCHAR2(40 BYTE) NOT NULL ,
    "DEPTAHKID" VARCHAR2(20 BYTE) ,
    "DEPTABDATE" DATE ,
    "DEPTATEL" VARCHAR2(20 BYTE),
    "DEPTAOSDATE" DATE NOT NULL,
    "DEPTAOEDATE" DATE NOT NULL,
    "DEPTCID_RM" NUMBER(10,0) NOT NULL,
    "DEPTPID" NUMBER(10,0) NOT NULL,
    "DEPTASTS" VARCHAR2(1 BYTE) NOT NULL,
    "DEPTACDATE" DATE NOT NULL,
    "DEPTUSRID" VARCHAR2(10 BYTE) NOT NULL,
    "STECODE" VARCHAR2(10 BYTE) NOT NULL,
    "DEPTASEX" VARCHAR2(1 BYTE),
    "PATTYPE" VARCHAR2(1 BYTE),
    "DOCCODE_R" VARCHAR2(10 BYTE),
    "CANCELRSNCDE" VARCHAR2(2 BYTE),
    "DEPTACNCLRMK" VARCHAR2(100 BYTE),
    "CANCELISADM" VARCHAR2(10 BYTE),
    "CANCELBY" VARCHAR2(10 BYTE),
    "CANCELRSNCDE2" VARCHAR2(10 BYTE),
    "DEPTPRMK" VARCHAR2(400 BYTE),
    "DEPTSPECBOOK" NUMBER(10,0),
    "DEPTWARD" VARCHAR2(10 BYTE),
    "DEPTBED" VARCHAR2(10 BYTE),
    "CREATE_USER" VARCHAR2(20 BYTE),
    "CREATE_DATE" DATE
  );
