DROP TABLE DEPT_CODE;
CREATE TABLE DEPT_CODE
  (
  	"DEPTTYPE" VARCHAR2(40 BYTE) NOT NULL ,
    "DEPTCID"   NUMBER(10,0) NOT NULL,
    "DEPTCTYPE" VARCHAR2(2 BYTE) NOT NULL,
    "DEPTCORD"   NUMBER(5,0) NOT NULL,
    "DEPTCDESC" VARCHAR2(50 BYTE) NOT NULL,
    "DEPTCNUM_1"   NUMBER(10,0),
    "DEPTCCHR_1" VARCHAR2(10 BYTE),
    "DEPTCSTS"   NUMBER(1,0) NOT NULL,
    "STECODE" VARCHAR2(10 BYTE) NOT NULL
  );