DROP TABLE DEPT_PROC;
CREATE TABLE DEPT_PROC
  (
  	"DEPTTYPE" VARCHAR2(40 BYTE) NOT NULL ,
    "DEPTPID"   NUMBER(10,0) NOT NULL,
    "DEPTPCODE" VARCHAR2(20 BYTE) NOT NULL,
    "DEPTPSFORM" VARCHAR2(15 BYTE) NOT NULL,
    "DEPTPDESC" VARCHAR2(100 BYTE) NOT NULL,
    "DEPTPTYPE" VARCHAR2(1 BYTE) NOT NULL,
    "DEPTPSTS"   NUMBER(1,0) NOT NULL,
    "PKGCODE" VARCHAR2(10 BYTE) ,
    "ITMCODE" VARCHAR2(10 BYTE) ,
    "DEPTPDUR"   NUMBER(5,0) ,
    "DEPTPINT"   NUMBER(5,0) ,
    "STECODE" VARCHAR2(10 BYTE) NOT NULL,
    "DEPTPSURCHARGE"   NUMBER(10,2)
  );
