ALTER TABLE DEPT ADD DPTABBR VARCHAR2(20);
ALTER TABLE DEPT ADD PRTPICKLIST NUMBER(1);

UPDATE DEPT SET DPTABBR = 'Lab', PRTPICKLIST = '1' WHERE DPTCODE = '230-';
UPDATE DEPT SET DPTABBR = 'CT', PRTPICKLIST = '1' WHERE DPTCODE = '240-';
UPDATE DEPT SET DPTABBR = 'DI', PRTPICKLIST = '1' WHERE DPTCODE = '280-';
UPDATE DEPT SET DPTABBR = 'MRI', PRTPICKLIST = '1' WHERE DPTCODE = '340-';

COMMIT;
' 