ALTER TABLE DOCITMPCTHIST
DROP PRIMARY KEY CASCADE;
DROP TABLE DOCITMPCTHIST CASCADE CONSTRAINTS;

CREATE TABLE DOCITMPCTHIST(
	DIPHID 				NUMBER(22, 0) NOT NULL ENABLE,
	DOCCODE           	VARCHAR2(10) NOT NULL ENABLE,  
	CONSTARTDATE 		DATE NOT NULL ENABLE,         
	CONENDDATE          DATE NOT NULL ENABLE,    
    SLPTYPE          	VARCHAR2(1),
    PCYID            	NUMBER(22),   
    DSCCODE          	VARCHAR2(10), 
    ITMCODE          	VARCHAR2(10), 
    DIPPCT           	FLOAT(126),   
    DIPFIX           	FLOAT(126),   
    STECODE        		VARCHAR2(10) NOT NULL, 
	PRIMARY KEY (DIPHID)
);

CREATE SEQUENCE "SEQ_DOCITMPCTHIST"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;