ALTER TABLE DOCLOCATION
DROP PRIMARY KEY CASCADE;
DROP TABLE DOCLOCATION CASCADE CONSTRAINTS;

CREATE TABLE DOCLOCATION(
	DOCLOCID NUMBER(22, 0) NOT NULL ENABLE,
	DOCLOCNAME VARCHAR2(50),
	REGOPCAT VARCHAR2(1),
	PRIMARY KEY (DOCLOCID)
);
