ALTER TABLE DOCPCTHIST
DROP PRIMARY KEY CASCADE;
DROP TABLE DOCPCTHIST CASCADE CONSTRAINTS;

CREATE TABLE DOCPCTHIST(
	DPHID 				NUMBER(22, 0) NOT NULL ENABLE,
	DOCCODE           	VARCHAR2(10) NOT NULL ENABLE,  
	CONSTARTDATE 		DATE NOT NULL ENABLE,         
	CONENDDATE          DATE NOT NULL ENABLE,    
	DOCPCT_I          	FLOAT(126),      
	DOCPCT_O          	FLOAT(126),        
	DOCPCT_D          	FLOAT(126),  
	PRIMARY KEY (DPHID)
);

CREATE SEQUENCE "SEQ_DOCPCTHIST"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;