ALTER TABLE DOCTOR_EXTRA
DROP PRIMARY KEY CASCADE;
DROP TABLE DOCTOR_EXTRA CASCADE CONSTRAINTS;

CREATE TABLE DOCTOR_EXTRA(
	DOCCODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
	SMDINSTRUCTION VARCHAR2(300 BYTE),
	DOC_CREATED_DATE DATE,
	DOC_CREATED_USER VARCHAR2(20 BYTE),
	DOC_UPDATED_DATE DATE,
	DOC_UPDATED_USER VARCHAR2(20 BYTE),
	SMSTEL VARCHAR2(20 BYTE),
	SMSTEL2 VARCHAR2(20 BYTE),
	SMSTYPE VARCHAR2(20 BYTE),
	CTS_ARCHIVE_FILE_ID NUMBER,
	PBO_REMARK VARCHAR2(100 BYTE),
	STODECLARATION NUMBER(1,0),
	SENDRISEMAIL NUMBER(1,0) DEFAULT -1,
	SENDRISEMAIL_MODDT DATE DEFAULT SYSDATE,
	PRIMARY KEY(DOCCODE)
);

ALTER TABLE DOCTOR_EXTRA ADD (
	CONSTRAINT DOCTOR_EXTRA_R01
	FOREIGN KEY (DOCCODE)
	REFERENCES DOCTOR (DOCCODE));
