ALTER TABLE DOCTOR ADD COMPANY VARCHAR2(100);
ALTER TABLE DOCTOR ADD MSTRDOCCODE VARCHAR2(10);
ALTER TABLE DOCTOR ADD EHRUID NUMBER(10,0);
ALTER TABLE DOCTOR ADD SMDINSTRUCTION VARCHAR2(200);
ALTER TABLE DOCTOR_UPDATE_LOG ADD EHRUID NUMBER(10,0);


DROP SEQUENCE SEQ_DOCUPTRELDOC_LOG;
CREATE SEQUENCE SEQ_DOCUPTRELDOC_LOG MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE ;

DROP TABLE DOCTOR_UPDATE_LOG;
CREATE TABLE DOCTOR_UPDATE_LOG
  (
    "SEQ_NO" NUMBER NOT NULL ENABLE,
    "DOCCODE"  VARCHAR2(10 BYTE),
    "DOCFNAME" VARCHAR2(20 BYTE),
    "DOCGNAME" VARCHAR2(20 BYTE),
    "DOCCNAME" VARCHAR2(10 BYTE),
    "DOCIDNO"  VARCHAR2(15 BYTE),
    "DOCSEX"   VARCHAR2(1 BYTE),
    "SPCCODE"  VARCHAR2(10 BYTE),
    "DOCSTS"   NUMBER(22,0),
    "DOCTYPE"  VARCHAR2(1 BYTE),
    "DOCPCT_I" FLOAT(126),
    "DOCPCT_O" FLOAT(126),
    "DOCPCT_D" FLOAT(126),
    "DOCADD1"  VARCHAR2(40 BYTE),
    "DOCADD2"  VARCHAR2(40 BYTE),
    "DOCADD3"  VARCHAR2(40 BYTE),
    "DOCHTEL"  VARCHAR2(20 BYTE),
    "DOCOTEL"  VARCHAR2(20 BYTE),
    "DOCPTEL"  VARCHAR2(20 BYTE),
    "DOCTSLOT" NUMBER(22,0),
    "DOCQUALI" VARCHAR2(40 BYTE),
    "DOCTDATE" DATE,
    "DOCSDATE" DATE,
    "DOCHOMADD1"  VARCHAR2(40 BYTE),
    "DOCHOMADD2"  VARCHAR2(40 BYTE),
    "DOCHOMADD3"  VARCHAR2(40 BYTE),
    "DOCOFFADD1"  VARCHAR2(40 BYTE),
    "DOCOFFADD2"  VARCHAR2(40 BYTE),
    "DOCOFFADD3"  VARCHAR2(40 BYTE),
    "DOCCSHOLY"   NUMBER(22,0),
    "DOCMTEL"     VARCHAR2(20 BYTE),
    "DOCEMAIL"    VARCHAR2(70 BYTE),
    "DOCFAXNO"    VARCHAR2(20 BYTE),
    "DOCHOMADD4"  VARCHAR2(40 BYTE),
    "DOCADD4"     VARCHAR2(40 BYTE),
    "DOCOFFADD4"  VARCHAR2(40 BYTE),
    "DOCPICKLIST" NUMBER(1,0),
    "USRID"       VARCHAR2(10 BYTE),
    "DOCQUALIFY"  NUMBER(1,0),
    "DOCBDATE" DATE,
    "RPTTO"           VARCHAR2(1 BYTE),
    "ISDOCTOR"        NUMBER(1,0),
    "TITTLE"          VARCHAR2(10 BYTE),
    "ISOTSURGEON"     NUMBER(1,0),
    "ISOTANESTHETIST" NUMBER(1,0),
    "SHOWPROFILE"     NUMBER(1,0),
    "DAYINSTRUCTION"  VARCHAR2(200 BYTE),
    "INPINSTRUCTION"  VARCHAR2(200 BYTE),
    "OUPINSTRUCTION"  VARCHAR2(200 BYTE),
    "PAYINSTRUCTION"  VARCHAR2(200 BYTE),
    "BRNO"            VARCHAR2(30 BYTE),
    "DOCREMARK"       VARCHAR2(75 BYTE),
    "CPSDATE" DATE,
    "APLDATE" DATE,
    "MPSCDATE" DATE,
    "SLDATE" DATE,
    "ISOTENDOSCOPIST" NUMBER(1,0),
    "CHKPRCPRIV"      NUMBER(1,0),
    "DOCINSURCOMP"    VARCHAR2(50 BYTE),
    "OPPEDATE" DATE,
    "RECEIVEPROMO"      NUMBER(1,0),
    "RECEIVEPROMOBYFAX" NUMBER(1,0),
    "OPPSDATE" DATE,
    "CLINSDATE" DATE,
    "HKMCLICNO"      VARCHAR2(6 BYTE),
    "ISPOSTSCHEDULE" NUMBER(1,0),
    "CREATED_DATE" DATE,
    "CREATED_USER" VARCHAR2(10)
  );

DROP TABLE DOCCERT_LOG;
CREATE TABLE DOCCERT_LOG
  (
  	"SEQ_NO" NUMBER NOT NULL ENABLE,
    "DOCCODE" VARCHAR2(10 BYTE),
    "ECERT1"  VARCHAR2(50 BYTE),
    "ECERT2"  VARCHAR2(50 BYTE),
    "ECERT3"  VARCHAR2(50 BYTE),
    "ECERT4"  VARCHAR2(50 BYTE),
    "ECERT5"  VARCHAR2(50 BYTE),
    "ECERT6"  VARCHAR2(50 BYTE),
    "ECERT7"  VARCHAR2(50 BYTE),
    "ECERT8"  VARCHAR2(50 BYTE),
    "ECERT9"  VARCHAR2(50 BYTE),
    "ECERT10" VARCHAR2(50 BYTE),
    "CCERT1"  VARCHAR2(100 BYTE),
    "CCERT2"  VARCHAR2(100 BYTE),
    "CCERT3"  VARCHAR2(100 BYTE),
    "CCERT4"  VARCHAR2(100 BYTE),
    "CCERT5"  VARCHAR2(100 BYTE),
    "CCERT6"  VARCHAR2(100 BYTE),
    "CCERT7"  VARCHAR2(100 BYTE),
    "CCERT8"  VARCHAR2(100 BYTE),
    "CCERT9"  VARCHAR2(100 BYTE),
    "CCERT10" VARCHAR2(100 BYTE),
    "CREATED_DATE" DATE,
    "CREATED_USER" VARCHAR2(10)
  );

DROP TABLE DOCPRILINK_LOG;
CREATE TABLE DOCPRILINK_LOG
  (
    "SEQ_NO" NUMBER NOT NULL ENABLE,
    "DPLID"   NUMBER(22,0),
    "DOCCODE" VARCHAR2(10 BYTE),
    "PRICODE" VARCHAR2(20 BYTE),
    "DPLSDATE" DATE,
    "DPLTDATE" DATE,
    "CREATED_DATE" DATE,
    "CREATED_USER" VARCHAR2(10)
  );

DROP TABLE DOCDPTLINK_LOG;
CREATE TABLE DOCDPTLINK_LOG
  (
  	"SEQ_NO" NUMBER NOT NULL ENABLE,
    "DDLID"   NUMBER(22,0),
    "DOCCODE" VARCHAR2(10 BYTE),
    "DPTCODE" VARCHAR2(10 BYTE),
    "CREATED_DATE" DATE,
    "CREATED_USER" VARCHAR2(10)
  );


DROP TABLE DOCSPCLINK_LOG;
CREATE TABLE DOCSPCLINK_LOG
  (
  	"SEQ_NO" NUMBER NOT NULL ENABLE,
    "DSLID"      NUMBER(22,0),
    "DOCCODE"    VARCHAR2(10 BYTE),
    "SPCCODE"    VARCHAR2(10 BYTE),
    "ISOFFICIAL" NUMBER(1,0),
    "CREATED_DATE" DATE,
    "CREATED_USER" VARCHAR2(10)
    );

DROP TABLE DOCQLFLINK_LOG;
CREATE TABLE DOCQLFLINK_LOG
  (
  	"SEQ_NO" NUMBER NOT NULL ENABLE,
    "DQLID"   NUMBER(22,0),
    "DOCCODE" VARCHAR2(10 BYTE),
    "QLFID"   NUMBER(22,0),
    "DQLIDATE" DATE,
    "CREATED_DATE" DATE,
    "CREATED_USER" VARCHAR2(10)
  ) ;


DROP TABLE DOCBASSAL_LOG;
CREATE TABLE DOCBASSAL_LOG
  (
  	"SEQ_NO" NUMBER NOT NULL ENABLE,
    "DBSID"   NUMBER(22,0),
    "DOCCODE" VARCHAR2(10 BYTE),
    "DBSSDATE" DATE,
    "DBSEDATE" DATE,
    "DBSAMT" FLOAT(126),
    "CREATED_DATE" DATE,
    "CREATED_USER" VARCHAR2(10)
  );

DROP TABLE DOCAPVLINK_LOG;
CREATE TABLE DOCAPVLINK_LOG
  (
  	"SEQ_NO" NUMBER NOT NULL ENABLE,
    "DALID"   NUMBER(22,0),
    "DOCCODE" VARCHAR2(10 BYTE),
    "CMTNAME" VARCHAR2(100 BYTE),
    "ACTNO"   VARCHAR2(20 BYTE),
    "APVDATE" DATE,
    "CREATED_DATE" DATE,
    "CREATED_USER" VARCHAR2(10)
  );
/