ALTER TABLE EHR_SV_VPCONFIG
 DROP PRIMARY KEY CASCADE;
DROP TABLE EHR_SV_VPCONFIG CASCADE CONSTRAINTS;

CREATE TABLE EHR_SV_VPCONFIG
(
	SYS_CODE	VARCHAR2(50 BYTE) NOT NULL ENABLE,
	SYS_CODE_SHORT	VARCHAR2(10 BYTE),
	EMR_LOCAL_SKEY	VARCHAR2(255 BYTE) NOT NULL ENABLE,
	EMR_SYS_ID	VARCHAR2(15 BYTE) NOT NULL ENABLE,
	EMR_VER		VARCHAR2(20 BYTE) NOT NULL ENABLE,
	EMR_CERT_MARK  VARCHAR2(256 BYTE),
    LAST_UPDATED DATE DEFAULT SYSDATE NOT NULL ENABLE,
	PRIMARY KEY (SYS_CODE)
);

CREATE INDEX IDX_EHR_SV_VPCONFIG ON EHR_SV_VPCONFIG(SYS_CODE);