ALTER TABLE EHR_SPCCODE_MAPPING
 DROP PRIMARY KEY CASCADE;
DROP TABLE EHR_SPCCODE_MAPPING CASCADE CONSTRAINTS;

CREATE TABLE EHR_SPCCODE_MAPPING(
	EHR_SPCCODE			VARCHAR2(20 BYTE) NOT NULL ENABLE,
	EHR_SPCNAME			VARCHAR2(200 BYTE),
	HOSP_SPCCODE		VARCHAR2(20 BYTE),
	CONSTRAINT "EHR_SPCCODE_MAPPING_PK" PRIMARY KEY ("EHR_SPCCODE")
);

CREATE INDEX IDX_EHR_SPCCODE_MAPPING_HOSP ON EHR_SPCCODE_MAPPING("HOSP_SPCCODE");
