ALTER TABLE EHR_DATA_UPLOAD_LOG
 DROP PRIMARY KEY CASCADE;
DROP TABLE EHR_DATA_UPLOAD_LOG CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_EHR_DATA_UPLOAD_LOG;
CREATE SEQUENCE SEQ_EHR_DATA_UPLOAD_LOG MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE ;

CREATE TABLE EHR_DATA_UPLOAD_LOG
(
	ID				NUMBER(22, 0) NOT NULL ENABLE,
	DOMAIN_CODE		VARCHAR2(6 BYTE) NOT NULL ENABLE,	-- ADR, AL1, ...
	UPLOAD_DATE		DATE NOT NULL ENABLE,
	EHR_NO			VARCHAR2(12 BYTE) NOT NULL ENABLE,
	PATNO			VARCHAR2(10 BYTE),
	START_DATE		DATE,
	END_DATE   		DATE,
	UPLOAD_MODE   	VARCHAR2(3 BYTE),	-- DM, INC
	SUCCESS			VARCHAR2(1 BYTE),	-- Y, N
	PRIMARY KEY (ID)
);