ALTER TABLE EHR_PMI
 DROP PRIMARY KEY CASCADE;
DROP TABLE EHR_PMI CASCADE CONSTRAINTS;

CREATE TABLE EHR_PMI(
	PATNO			VARCHAR2(10 BYTE) NOT NULL ENABLE,
	EHRNO			VARCHAR2(12 BYTE),
	EHRFNAME		VARCHAR2(40 BYTE),
	EHRGNAME		VARCHAR2(40 BYTE),
	EHRDOB			DATE NOT NULL ENABLE,
	EHRSEX			VARCHAR2(1 BYTE) NOT NULL ENABLE,
	EHRHKID			VARCHAR2(12 BYTE),
	EHRDOCNO		VARCHAR2(30 BYTE),
	EHRDOCTYPE		VARCHAR2(6 BYTE),
	ACTIVE			NUMBER(1) DEFAULT 0 NOT NULL ENABLE ,
	EHREDOBIND		VARCHAR2(4 BYTE),
	INITLAB			DATE,
	INITRIS			DATE,
	INITRXP			DATE,
	INITRXD			DATE,
	INITADR			DATE,
	INITALG			DATE,
	INITCNS			DATE,
	INITBIRTH		DATE,
	INITENCTR		DATE,
	CONSTRAINT "PK_EHR_PMI" PRIMARY KEY ("PATNO")
);

CREATE INDEX IDX_EHR_PMI_EHRNO ON EHR_PMI("EHRNO");
