ALTER TABLE EHR_PMIDOCTYPE
 DROP PRIMARY KEY CASCADE;
DROP TABLE EHR_PMIDOCTYPE CASCADE CONSTRAINTS;

CREATE TABLE EHR_PMIDOCTYPE(
	EHRCODE			VARCHAR2(10 BYTE) NOT NULL ENABLE,
	EHRDESC			VARCHAR2(100 BYTE),
	EHRSEQ			NUMBER(22),
	CONSTRAINT "PK_EHR_PMIDOCTYPE" PRIMARY KEY ("EHRCODE")
);

INSERT INTO EHR_PMIDOCTYPE(EHRCODE, EHRDESC, EHRSEQ) VALUES ('AR', 'Adoption Certificate', 1);
INSERT INTO EHR_PMIDOCTYPE(EHRCODE, EHRDESC, EHRSEQ) VALUES ('BC', 'Birth Certification - HK', 2);
INSERT INTO EHR_PMIDOCTYPE(EHRCODE, EHRDESC, EHRSEQ) VALUES ('DI', 'Document of Identity for Visa Purposes', 3);
INSERT INTO EHR_PMIDOCTYPE(EHRCODE, EHRDESC, EHRSEQ) VALUES ('EC', 'Exemption Certification', 4);
INSERT INTO EHR_PMIDOCTYPE(EHRCODE, EHRDESC, EHRSEQ) VALUES ('ID', 'HKID Card', 5);
INSERT INTO EHR_PMIDOCTYPE(EHRCODE, EHRDESC, EHRSEQ) VALUES ('ID235B', 'Permit to Remain in HKSAR (ID 235B)', 6);
INSERT INTO EHR_PMIDOCTYPE(EHRCODE, EHRDESC, EHRSEQ) VALUES ('ED', 'eHR document', 7);
INSERT INTO EHR_PMIDOCTYPE(EHRCODE, EHRDESC, EHRSEQ) VALUES ('OC', 'Identity/travel documents - PRC', 8);
INSERT INTO EHR_PMIDOCTYPE(EHRCODE, EHRDESC, EHRSEQ) VALUES ('OP', 'Identity/travel documents - overseas', 9);
INSERT INTO EHR_PMIDOCTYPE(EHRCODE, EHRDESC, EHRSEQ) VALUES ('OW', 'One-way Permit', 10);
INSERT INTO EHR_PMIDOCTYPE(EHRCODE, EHRDESC, EHRSEQ) VALUES ('PS', 'HKSAR Passport', 11);
INSERT INTO EHR_PMIDOCTYPE(EHRCODE, EHRDESC, EHRSEQ) VALUES ('RP', 'Re-entry Permit', 12);
INSERT INTO EHR_PMIDOCTYPE(EHRCODE, EHRDESC, EHRSEQ) VALUES ('TW', 'Two-way Permit', 13);