ALTER TABLE EHR_DATA_UPLOAD_ALERT_LOG
 DROP PRIMARY KEY CASCADE;
DROP TABLE EHR_DATA_UPLOAD_ALERT_LOG CASCADE CONSTRAINTS;

CREATE TABLE EHR_DATA_UPLOAD_ALERT_LOG
(
	BATCH_ID		VARCHAR2(15 BYTE) NOT NULL ENABLE,
	ALERT_CODE		VARCHAR2(15 BYTE) NOT NULL ENABLE,
	SEND_DATE		DATE,
	SUCCESS			VARCHAR2(1 BYTE),	-- Y, N
	PRIMARY KEY (BATCH_ID, ALERT_CODE)
);