ALTER TABLE EHR_SYS_CONFIG
 DROP PRIMARY KEY CASCADE;
DROP TABLE EHR_SYS_CONFIG CASCADE CONSTRAINTS;

CREATE TABLE EHR_SYS_CONFIG
(
	PARAM_NAME				VARCHAR2(50 BYTE) NOT NULL ENABLE,
	PARAM_NAME_DESC			VARCHAR2(255 BYTE),
	PARAM_VALUE				VARCHAR2(255 BYTE),
	PARAM_VALUE_TYPE		VARCHAR2(20 BYTE),
	PARAM_POSSIBLE_VALUE	VARCHAR2(255 BYTE),
	PARAM_LEVEL   			VARCHAR2(20 BYTE),
	ACTIVE					NUMBER(1) DEFAULT -1 NOT NULL ENABLE ,	-- 0, -1
	CREATE_USER				VARCHAR2(30 BYTE) DEFAULT 'SYSTEM' NOT NULL ENABLE,
    CREATE_DATE 			DATE DEFAULT SYSDATE NOT NULL ENABLE,
    UPDATE_USER				VARCHAR2(30 BYTE) DEFAULT 'SYSTEM' NOT NULL ENABLE,
    UPDATE_DATE 			DATE DEFAULT SYSDATE NOT NULL ENABLE,
	PRIMARY KEY (PARAM_NAME)
);


--HKAH UAT
INSERT INTO EHR_SYS_CONFIG (PARAM_NAME, PARAM_NAME_DESC, PARAM_VALUE) VALUES ('pmi_ws_c_url', 'PMI web services client url', 'http://160.100.2.73:9081/hepr/ws/pmi/PmiWebS.wsdl');

--TWAH UAT
INSERT INTO EHR_SYS_CONFIG (PARAM_NAME, PARAM_NAME_DESC, PARAM_VALUE) VALUES ('pmi_ws_c_url', 'PMI web services client url', 'http://192.168.0.128/hepr/ws/pmi/PmiWebS.wsdl');
