ALTER TABLE EHR_SV_VP_REQ
 DROP PRIMARY KEY CASCADE;
DROP TABLE EHR_SV_VP_REQ CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_EHR_SV_VP_REQ;
CREATE SEQUENCE SEQ_EHR_SV_VP_REQ MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE ;

CREATE TABLE EHR_SV_VP_REQ
(
	REQ_ID			NUMBER(22,0) NOT NULL ENABLE,
	SYS_CODE		VARCHAR2(50 BYTE) NOT NULL ENABLE,
	STATUS			VARCHAR2(5 BYTE) NOT NULL ENABLE,
	STATUS_DESC		VARCHAR2(20 BYTE),
	VP				VARCHAR2(15 BYTE),
	VP_EXP_DATE		DATE,
	VP_ISSUE_DATE   DATE,
	ACTIVE			NUMBER(1) DEFAULT 0 NOT NULL ENABLE ,
	CREATE_USER		VARCHAR2(30 BYTE) DEFAULT 'SYSTEM' NOT NULL ENABLE,
    CREATE_DATE 	DATE DEFAULT SYSDATE NOT NULL ENABLE,
	PRIMARY KEY (SYS_CODE)
);