ALTER TABLE EHR_PMIHIST
 DROP PRIMARY KEY CASCADE;
DROP TABLE EHR_PMIHIST CASCADE CONSTRAINTS;

CREATE TABLE EHR_PMIHIST(
	EHRID			NUMBER(22,0) NOT NULL ENABLE,
	PATNO			VARCHAR2(10 BYTE),
	EHRNO			VARCHAR2(12 BYTE),
	EHRENROLDATE	DATE,
	EHRSDATE		DATE,
	EHREDATE		DATE,
	EHRFNAME		VARCHAR2(40 BYTE),
	EHRGNAME		VARCHAR2(40 BYTE),
	EHRDOB  		DATE,
	EHRSEX			VARCHAR2(1 BYTE),
	EHRHKID			VARCHAR2(12 BYTE),
	EHRDOCNO		VARCHAR2(30 BYTE),
	EHRDOCTYPE		VARCHAR2(6 BYTE),
	CREATEDATE		DATE DEFAULT SYSDATE NOT NULL ENABLE,
	CREATEBY		VARCHAR2(10 BYTE) NOT NULL ENABLE,
	EHRMSGNO		VARCHAR2(20 BYTE),
	EHREVENTCODE	VARCHAR2(3 BYTE),
	EHRDEATHDATE	DATE,
	EHREDOBIND		VARCHAR2(4 BYTE),
	CONSTRAINT "PK_EHR_PMIHIST" PRIMARY KEY ("EHRID")
);

CREATE SEQUENCE SEQ_EHR_PMIHIST
    INCREMENT BY 1
    START WITH 1
    NOMAXVALUE
    NOCYCLE
    CACHE 10;
