ALTER TABLE HLETRDTL
 DROP PRIMARY KEY CASCADE;
DROP TABLE HLETRDTL CASCADE CONSTRAINTS;

CREATE TABLE HLETRDTL(
	HLTYPE			VARCHAR2(10 BYTE) NOT NULL ENABLE,
	HLKEY			VARCHAR2(20 BYTE) NOT NULL ENABLE,
	HLSEQ			VARCHAR2(50 BYTE) NOT NULL ENABLE,
	HLHDATE			DATE,
	HLCDATE			DATE DEFAULT SYSDATE,
	HLHUSR			VARCHAR2(50 BYTE),
	HLCUSR			VARCHAR2(50 BYTE),
	HLRMK			VARCHAR2(200 BYTE));
