ALTER TABLE HPSTATUS
 DROP PRIMARY KEY CASCADE;
DROP TABLE HPSTATUS CASCADE CONSTRAINTS;

CREATE TABLE HPSTATUS(
	HPTYPE			VARCHAR2(20 BYTE) NOT NULL ENABLE,
	HPKEY			VARCHAR2(30 BYTE) NOT NULL ENABLE,
	HPSTATUS		VARCHAR2(100 BYTE) NOT NULL ENABLE,
	HPSDATE			DATE,
	HPEDATE			DATE,
	HPRMK			VARCHAR2(200 BYTE),
	HPCDATE			DATE DEFAULT SYSDATE,
	HPMDATE			DATE,
	HPCUSR			VARCHAR2(50 BYTE),
	HPMUSR			VARCHAR2(50 BYTE),
	HPACTIVE		NUMBER(1),
	CONSTRAINT "PK_HPSTATUS" PRIMARY KEY ("HPTYPE", "HPKEY", "HPSTATUS")
);
