ALTER TABLE MARITALSTATUS
 DROP PRIMARY KEY CASCADE;
DROP TABLE MARITALSTATUS CASCADE CONSTRAINTS;

CREATE TABLE MARITALSTATUS(
	MARCODE	VARCHAR2(1 BYTE) NOT NULL ENABLE,
	MARDESC	VARCHAR2(20 BYTE) NOT NULL ENABLE,
	MARORDER NUMBER NOT NULL ENABLE,
	CONSTRAINT "PK_MARITALSTATUS" PRIMARY KEY ("MARCODE")
);

INSERT INTO MARITALSTATUS(MARCODE, MARDESC, MARORDER) VALUES ('S', 'Single', 1);
INSERT INTO MARITALSTATUS(MARCODE, MARDESC, MARORDER) VALUES ('M', 'Married', 3);
INSERT INTO MARITALSTATUS(MARCODE, MARDESC, MARORDER) VALUES ('D', 'Divorce', 4);
INSERT INTO MARITALSTATUS(MARCODE, MARDESC, MARORDER) VALUES ('X', 'Separate', 5);
INSERT INTO MARITALSTATUS(MARCODE, MARDESC, MARORDER) VALUES ('W', 'Widow', 6);
INSERT INTO MARITALSTATUS(MARCODE, MARDESC, MARORDER) VALUES ('Z', 'Widower', 7);

-- for HKAH only
INSERT INTO MARITALSTATUS(MARCODE, MARDESC, MARORDER) VALUES ('E', 'Engaged', 2);
INSERT INTO MARITALSTATUS(MARCODE, MARDESC, MARORDER) VALUES ('O', 'Other', 8);

commit;
