ALTER TABLE MARKETINGSOURCE
 DROP PRIMARY KEY CASCADE;
DROP TABLE MARKETINGSOURCE CASCADE CONSTRAINTS;

CREATE TABLE MARKETINGSOURCE(
	MKTSRCCODE	VARCHAR2(1 BYTE) NOT NULL ENABLE,
	MKTSRCDESC	VARCHAR2(20 BYTE) NOT NULL ENABLE,
	CONSTRAINT "PK_MARKETINGSOURCE" PRIMARY KEY ("MKTSRCCODE")
);

INSERT INTO MARKETINGSOURCE(MKTSRCCODE, MKTSRCDESC) VALUES ('E', 'E-newsletter');
INSERT INTO MARKETINGSOURCE(MKTSRCCODE, MKTSRCDESC) VALUES ('F', 'Friends/ Relatives');
INSERT INTO MARKETINGSOURCE(MKTSRCCODE, MKTSRCDESC) VALUES ('H', 'Hospital Website');
INSERT INTO MARKETINGSOURCE(MKTSRCCODE, MKTSRCDESC) VALUES ('N', 'Newspaper/ Magazine');
INSERT INTO MARKETINGSOURCE(MKTSRCCODE, MKTSRCDESC) VALUES ('I', 'Insurance Company');
INSERT INTO MARKETINGSOURCE(MKTSRCCODE, MKTSRCDESC) VALUES ('D', 'Doctor');
INSERT INTO MARKETINGSOURCE(MKTSRCCODE, MKTSRCDESC) VALUES ('O', 'Other');
INSERT INTO MARKETINGSOURCE(MKTSRCCODE, MKTSRCDESC) VALUES ('S', 'Not specified');

commit;
