ALTER TABLE MEDRECBATCH
 DROP PRIMARY KEY CASCADE;
DROP TABLE MEDRECBATCH CASCADE CONSTRAINTS;

CREATE TABLE MEDRECBATCH(
	MRBNO NUMBER(22, 0) NOT NULL ENABLE,
	PATNO VARCHAR2(10 BYTE) NOT NULL ENABLE,
	MRHVOLLAB VARCHAR2(5 BYTE) NOT NULL ENABLE,
	MRHREMARK VARCHAR2(100 BYTE),
	MRHID NUMBER(22, 0),
	MRBSTS NUMBER DEFAULT -1 NOT NULL ENABLE,
	MRBDATE DATE DEFAULT SYSDATE NOT NULL ENABLE,
	CONSTRAINT "PK_MEDRECBATCH" PRIMARY KEY ("MRBNO", "PATNO", "MRHVOLLAB")
);
