ALTER TABLE OT_APP_EXTRA
DROP PRIMARY KEY CASCADE;
DROP TABLE OT_APP_EXTRA CASCADE CONSTRAINTS;

CREATE TABLE OT_APP_EXTRA(
	OTAID NUMBER(10,0) NOT NULL ENABLE,
	SMSSDT DATE,
	SMSSDTOK DATE,
	SMSRTNMSG VARCHAR2(20),
	FEREQ VARCHAR2(1),
	FEREC VARCHAR2(1),
	OTAUPUSR VARCHAR2(10 BYTE),
	OTAUPDT DATE,
	PRIMARY KEY(OTAID)
);

ALTER TABLE OT_APP_EXTRA ADD (
	CONSTRAINT OT_APP_EXTRA_R01
	FOREIGN KEY (OTAID)
	REFERENCES OT_APP (OTAID));
