INSERT INTO OT_CODE(OTCID, OTCTYPE, OTCORD, OTCDESC, OTCSTS, STECODE) VALUES ('60000', 'AD', '01', 'Admitted', '-1', 'HKAH');
INSERT INTO OT_CODE(OTCID, OTCTYPE, OTCORD, OTCDESC, OTCSTS, STECODE) VALUES ('60001', 'AD', '02', 'Not Admitted', '-1', 'HKAH');

INSERT INTO OT_CODE(OTCID, OTCTYPE, OTCORD, OTCDESC, OTCSTS, STECODE) VALUES ('60002', 'CA', '01', 'GP', '-1', 'HKAH');
INSERT INTO OT_CODE(OTCID, OTCTYPE, OTCORD, OTCDESC, OTCSTS, STECODE) VALUES ('60003', 'CA', '02', 'OPD', '-1', 'HKAH');
INSERT INTO OT_CODE(OTCID, OTCTYPE, OTCORD, OTCDESC, OTCSTS, STECODE) VALUES ('60004', 'CA', '03', 'Surgeon', '-1', 'HKAH');
INSERT INTO OT_CODE(OTCID, OTCTYPE, OTCORD, OTCDESC, OTCSTS, STECODE) VALUES ('60005', 'CA', '04', 'Patient', '-1', 'HKAH');
INSERT INTO OT_CODE(OTCID, OTCTYPE, OTCORD, OTCDESC, OTCSTS, STECODE) VALUES ('60006', 'CA', '05', 'Relative', '-1', 'HKAH');
INSERT INTO OT_CODE(OTCID, OTCTYPE, OTCORD, OTCDESC, OTCSTS, STECODE) VALUES ('60007', 'CA', '06', 'Others', '-1', 'HKAH');

INSERT INTO OT_CODE(OTCID, OTCTYPE, OTCORD, OTCDESC, OTCSTS, STECODE) VALUES ('60008', 'RA', '01', 'Clincial', '-1', 'HKAH');
INSERT INTO OT_CODE(OTCID, OTCTYPE, OTCORD, OTCDESC, OTCSTS, STECODE) VALUES ('60009', 'RA', '02', 'Financial', '-1', 'HKAH');
INSERT INTO OT_CODE(OTCID, OTCTYPE, OTCORD, OTCDESC, OTCSTS, STECODE) VALUES ('60010', 'RA', '03', 'Insurance', '-1', 'HKAH');
INSERT INTO OT_CODE(OTCID, OTCTYPE, OTCORD, OTCDESC, OTCSTS, STECODE) VALUES ('60011', 'RA', '04', 'Discharged', '-1', 'HKAH');
INSERT INTO OT_CODE(OTCID, OTCTYPE, OTCORD, OTCDESC, OTCSTS, STECODE) VALUES ('60012', 'RA', '05', 'Rescheduled', '-1', 'HKAH');
INSERT INTO OT_CODE(OTCID, OTCTYPE, OTCORD, OTCDESC, OTCSTS, STECODE) VALUES ('60013', 'RA', '06', 'SVD', '-1', 'HKAH');
INSERT INTO OT_CODE(OTCID, OTCTYPE, OTCORD, OTCDESC, OTCSTS, STECODE) VALUES ('60014', 'RA', '07', 'Transferred', '-1', 'HKAH');
INSERT INTO OT_CODE(OTCID, OTCTYPE, OTCORD, OTCDESC, OTCSTS, STECODE) VALUES ('60015', 'RA', '08', 'Refusal', '-1', 'HKAH');
INSERT INTO OT_CODE(OTCID, OTCTYPE, OTCORD, OTCDESC, OTCSTS, STECODE) VALUES ('60016', 'RA', '09', 'Deceased', '-1', 'HKAH');
INSERT INTO OT_CODE(OTCID, OTCTYPE, OTCORD, OTCDESC, OTCSTS, STECODE) VALUES ('60017', 'RA', '10', 'Others', '-1', 'HKAH');

commit;
