ALTER TABLE OT_LOG_EXTRA
DROP PRIMARY KEY CASCADE;
DROP TABLE OT_LOG_EXTRA CASCADE CONSTRAINTS;

CREATE TABLE OT_LOG_EXTRA(
	OTLID NUMBER(10,0) NOT NULL ENABLE,
	FEREQ VARCHAR2(1),
	FEREC VARCHAR2(1),
	OTLUPUSR VARCHAR2(10 BYTE),
	OTLUPDT DATE,
	PRIMARY KEY(OTLID)
);

ALTER TABLE OT_LOG_EXTRA ADD (
	CONSTRAINT OT_LOG_EXTRA_R01
	FOREIGN KEY (OTLID)
	REFERENCES OT_LOG (OTLID));
