CREATE INDEX "IDX_OT_LOG_PATNO_SLPNO" ON "OT_LOG" ("PATNO", "SLPNO")
	PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING
	STORAGE(
	PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
	TABLESPACE "INDX_OT" ;