ALTER TABLE PATEHR
 DROP PRIMARY KEY CASCADE;
DROP TABLE PATEHR CASCADE CONSTRAINTS;

CREATE TABLE PATEHR(
	PATNO			VARCHAR2(10 BYTE) NOT NULL ENABLE,
	PATEHRNO		VARCHAR2(12 BYTE) NOT NULL ENABLE,
	PATEHRFNAME		VARCHAR2(40 BYTE),
	PATEHRGNAME		VARCHAR2(40 BYTE),
	PATEHRHKID		VARCHAR2(40 BYTE),
	PATEHRDOCNO		VARCHAR2(40 BYTE),
	PATEHRDOCTYPE	VARCHAR2(40 BYTE),
	PATEHRACTIVE	NUMBER,
	CONSTRAINT "PK_PATEHR" PRIMARY KEY ("PATNO")
);

CREATE INDEX IDX_PATEHR_PATEHRNO ON PATEHR("PATEHRNO");
