ALTER TABLE PATEHRHIST
 DROP PRIMARY KEY CASCADE;
DROP TABLE PATEHRHIST CASCADE CONSTRAINTS;

CREATE TABLE PATEHRHIST(
	PATNO			VARCHAR2(10 BYTE) NOT NULL ENABLE,
	PATEHRHISTID	NUMBER(22) NOT NULL ENABLE,
	PATEHRNO		VARCHAR2(12 BYTE) NOT NULL ENABLE,
	PATEHRENROLDATE	DATE NOT NULL ENABLE,
	PATEHRSDATE		DATE,
	PATEHRSUPDDATE	DATE,
	PATEHRSUPDBY	VARCHAR2(10 BYTE),
	PATEHREDATE		DATE,
	PATEHREUPDDATE	DATE,
	PATEHREUPDBY	VARCHAR2(10 BYTE),
	CONSTRAINT "PK_PATEHRHIST" PRIMARY KEY ("PATNO", "PATEHRHISTID")
);
