ALTER TABLE PATIENT ADD
(
	PATIDCOUCODE VARCHAR2(3),
	PATCHKID NUMBER(1, 0),
	PATCHKIDUPUSR VARCHAR2(10 BYTE), PATCHKIDUPDT DATE,
	PATPAGERUPUSR VARCHAR2(10 BYTE), PATPAGERUPDT DATE,
	PATHTELUPUSR VARCHAR2(10 BYTE), PATHTELUPDT DATE,
	PATOTELUPUSR VARCHAR2(10 BYTE), PATOTELUPDT DATE,
	PATFAXNOUPUSR VARCHAR2(10 BYTE), PATFAXNOUPDT DATE,
	PATADDUPUSR VARCHAR2(10 BYTE), PATADDUPDT DATE,
	RMKUPUSR VARCHAR2(10 BYTE), RMKUPDT DATE,
	PATMKTSRC VARCHAR2(1 BYTE)
);
