CREATE TABLE PATIENT_ACTIVITY_LOG
(
	"PATNO" VARCHAR2(10 BYTE) NOT NULL ENABLE,
	"MODULE" VARCHAR2(10 BYTE) NOT NULL ENABLE,
	"ACTION_TYPE" VARCHAR2(10 BYTE) NOT NULL ENABLE,
	"REMARK" VARCHAR2(1000 BYTE),
	"PCNAME" VARCHAR2(100 BYTE),
	"CREATED_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"CREATED_USER" VARCHAR2(20 BYTE) DEFAULT 'SYSTEM' NOT NULL ENABLE,
	"UPDATED_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"UPDATED_USER" VARCHAR2(20 BYTE) DEFAULT 'SYSTEM' NOT NULL ENABLE,
	"ACTION_DATE" DATE,
	"ACTION_USER" VARCHAR2(20 BYTE)
);