ALTER TABLE PATIENT_EXTRA
DROP PRIMARY KEY CASCADE;
DROP TABLE PATIENT_EXTRA CASCADE CONSTRAINTS;

CREATE TABLE PATIENT_EXTRA(
	PATNO	        VARCHAR2(10 BYTE) NOT NULL ENABLE,
	CONSENTARCCODE1 VARCHAR2(5 BYTE),
	CONSENTRMK1     VARCHAR2(20 BYTE),
	CONSENTSDATE1   DATE,
	CONSENTEDATE1   DATE,
	CONSENTUSER1    VARCHAR2(10),
	CONSENTDATE1    DATE,
	CONSENTARCCODE2 VARCHAR2(5 BYTE),
	CONSENTRMK2     VARCHAR2(20 BYTE),
	CONSENTSDATE2   DATE,
	CONSENTEDATE2   DATE,
	CONSENTUSER2    VARCHAR2(10),
	CONSENTDATE2    DATE,
	CONSENTARCCODE3 VARCHAR2(5 BYTE),
	CONSENTRMK3     VARCHAR2(20 BYTE),
	CONSENTSDATE3   DATE,
	CONSENTEDATE3   DATE,
	CONSENTUSER3    VARCHAR2(10),
	CONSENTDATE3    DATE,
	DOCTYPE         VARCHAR2(20 BYTE),
	PATMKTRMK       VARCHAR2(20 BYTE),
	DENTALNO        VARCHAR2(20 BYTE),
	PATMISCRMK      VARCHAR2(50 BYTE),
	LASTPRTDATE2    DATE,
	PATCDATE        DATE,
	PRIMARY KEY(PATNO)
);

ALTER TABLE PATIENT_EXTRA ADD (
	CONSTRAINT PATIENT_EXTRA_R01
	FOREIGN KEY (PATNO)
	REFERENCES PATIENT (PATNO));
