ALTER TABLE PATIENT_SYNC_PENDING
 DROP PRIMARY KEY CASCADE;
DROP TABLE PATIENT_SYNC_PENDING CASCADE CONSTRAINTS;

CREATE TABLE PATIENT_SYNC_PENDING(
	PATNO		VARCHAR2(10 BYTE) NOT NULL ENABLE,
	ACTION		VARCHAR2(20 BYTE),
	STECODE		VARCHAR2(10 BYTE) NOT NULL ENABLE,
	LASTUPD		DATE NOT NULL ENABLE,
	SYNC_DATE	DATE,
	CONSTRAINT "PK_PATIENT_SYNC_PENDING" PRIMARY KEY ("PATNO", "LASTUPD")
);