ALTER TABLE PATIENT_AMC1
 DROP PRIMARY KEY CASCADE;
DROP TABLE PATIENT_AMC1 CASCADE CONSTRAINTS;

CREATE TABLE PATIENT_AMC1
   (AMC1PATNO 	VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	PATNO 		VARCHAR2(10 BYTE), 
	PATIDNO 	VARCHAR2(20 BYTE), 
	DOCTYPE 	VARCHAR2(20 BYTE), 
	PATIDCOUCODE VARCHAR2(3 BYTE), 
	PATFNAME 	VARCHAR2(40 BYTE) NOT NULL ENABLE,  
	PATGNAME 	VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	PATCNAME 	VARCHAR2(10 CHAR), 
	PATBDATE 	DATE, 
	PATSEX 		VARCHAR2(1 BYTE) NOT NULL ENABLE,
	TITDESC     VARCHAR2(10),    
	PATPAGER 	VARCHAR2(20 CHAR), 
	PATPGRCOUCODE VARCHAR2(3 BYTE), 
	PATHTEL 	VARCHAR2(20 BYTE), 
	PATEMAIL 	VARCHAR2(80 BYTE), 
	PATADD1 	VARCHAR2(40 CHAR), 
	PATADD2 	VARCHAR2(40 CHAR), 
	PATADD3 	VARCHAR2(40 CHAR), 
	LOCCODE 	VARCHAR2(10 BYTE), 
	COUCODE     VARCHAR2(3),
	PATSTAFF 	NUMBER(22,0), 
	PATRMK 		VARCHAR2(100 CHAR),
	IMPORTDATE 	DATE,
	CONSTRAINT "PK_PATIENT_AMC1" PRIMARY KEY ("AMC1PATNO")
);