DROP TABLE PATIENT_UPDATE_LOG;

CREATE TABLE PATIENT_UPDATE_LOG(
	PULID       NUMBER(10,0) NOT NULL,
	PATNO       VARCHAR2(10 byte) NOT NULL,
	OLDPATFNAME VARCHAR2(40 byte),
	OLDPATGNAME VARCHAR2(40 byte),
	OLDPATCNAME VARCHAR2(20 byte),
	OLDPATSEX   VARCHAR2(1 byte),
	OLDPATBDATE DATE,
	OLDPATADD1  VARCHAR2(40 BYTE),
	OLDPATADD2  VARCHAR2(40 BYTE),
	OLDPATADD3  VARCHAR2(40 BYTE),
	OLDPATHTEL  VARCHAR2(20 BYTE),
	OLDPATOTEL  VARCHAR2(20 BYTE),
	OLDLOCCODE  VARCHAR2(10 BYTE),
	NEWPATFNAME VARCHAR2(40 byte),
	NEWPATGNAME VARCHAR2(40 byte),
	NEWPATCNAME VARCHAR2(20 byte),
	NEWPATSEX   VARCHAR2(1 byte),
	NEWPATBDATE DATE,
	NEWPATADD1  VARCHAR2(40 BYTE),
	NEWPATADD2  VARCHAR2(40 BYTE),
	NEWPATADD3  VARCHAR2(40 BYTE),
	NEWPATHTEL  VARCHAR2(20 BYTE),
	NEWPATOTEL  VARCHAR2(20 BYTE),
	NEWLOCCODE  VARCHAR2(10 BYTE),
	USRID       VARCHAR2(20 BYTE),
	PULDATE     DATE
);

CREATE SEQUENCE SEQ_PATIENT_UPDATE_LOG
    INCREMENT BY 1
    START WITH 1
    NOMAXVALUE
    nocycle
    CACHE 10;
