ALTER TABLE PATNO_RESERVED
 DROP PRIMARY KEY CASCADE;
DROP TABLE PATNO_RESERVED CASCADE CONSTRAINTS;

CREATE TABLE PATNO_RESERVED(
	PATNO	VARCHAR2(10 BYTE) NOT NULL ENABLE,
	RSV_DATE	DATE NOT NULL ENABLE,
	USE_DATE	DATE,
	PRIMARY KEY(PATNO)
);