ALTER TABLE PUBLIC_HOLIDAY
 DROP PRIMARY KEY CASCADE;
DROP TABLE PUBLIC_HOLIDAY CASCADE CONSTRAINTS;

CREATE TABLE PUBLIC_HOLIDAY (
    HOLIDAY			    DATE NOT NULL,
    DESCRIPTION		  VARCHAR2(100 BYTE),
    CREATED_DATE 	  DATE DEFAULT SYSDATE,
    CREATED_USER 	  VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
    MODIFIED_DATE 	DATE DEFAULT SYSDATE,
    MODIFIED_USER 	VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
    ENABLED       	NUMBER(1) DEFAULT 1,
    SMS_ENABLE    	NUMBER DEFAULT 0,
    CONSTRAINT "PK_PUBLIC_HOLIDAY" PRIMARY KEY("HOLIDAY")
);

COMMIT;
