ALTER TABLE REG_EXTRA
DROP PRIMARY KEY CASCADE;
DROP TABLE REG_EXTRA CASCADE CONSTRAINTS;

CREATE TABLE REG_EXTRA(
	REGID			NUMBER(22,0) NOT NULL ENABLE,
	CREATE_DATE		DATE	DEFAULT SYSDATE,
	CREATE_USER		VARCHAR2(20),
	CREATE_LOC		VARCHAR2(50),
	MODIFY_DATE		DATE	DEFAULT	SYSDATE,
	MODIFY_USER		VARCHAR2(20),
	PRIMARY KEY (REGID)
);

ALTER TABLE REG_EXTRA ADD (
	CONSTRAINT REG_EXTRA_R01
	FOREIGN KEY (REGID)
	REFERENCES REG (REGID));
/