ALTER TABLE RELATIONSHIP
 DROP PRIMARY KEY CASCADE;
DROP TABLE RELATIONSHIP CASCADE CONSTRAINTS;

CREATE TABLE RELATIONSHIP(
	RELATIONCODE	VARCHAR2(3 BYTE) NOT NULL ENABLE,
	RELATIONDESC	VARCHAR2(20 BYTE) NOT NULL ENABLE,
	ISEHR			VARCHAR2(1 BYTE) NOT NULL ENABLE,
	CONSTRAINT "PK_RELATIONSHIP" PRIMARY KEY ("RELATIONCODE")
);

INSERT INTO RELATIONSHIP(RELATIONCODE, RELATIONDESC, ISEHR) VALUES ('AU', 'AUNT', 'Y');
INSERT INTO RELATIONSHIP(RELATIONCODE, RELATIONDESC, ISEHR) VALUES ('BR', 'BROTHER', 'Y');
INSERT INTO RELATIONSHIP(RELATIONCODE, RELATIONDESC, ISEHR) VALUES ('CO', 'COUSIN', 'Y');
INSERT INTO RELATIONSHIP(RELATIONCODE, RELATIONDESC, ISEHR) VALUES ('DA', 'DAUGHTER', 'Y');
INSERT INTO RELATIONSHIP(RELATIONCODE, RELATIONDESC, ISEHR) VALUES ('FA', 'FATHER', 'Y');
INSERT INTO RELATIONSHIP(RELATIONCODE, RELATIONDESC, ISEHR) VALUES ('FR', 'FRIEND', 'Y');
INSERT INTO RELATIONSHIP(RELATIONCODE, RELATIONDESC, ISEHR) VALUES ('GC', 'GRANDCHILD', 'Y');
INSERT INTO RELATIONSHIP(RELATIONCODE, RELATIONDESC, ISEHR) VALUES ('GU', 'GUARDIAN', 'Y');
INSERT INTO RELATIONSHIP(RELATIONCODE, RELATIONDESC, ISEHR) VALUES ('HU', 'HUSBAND', 'Y');
INSERT INTO RELATIONSHIP(RELATIONCODE, RELATIONDESC, ISEHR) VALUES ('IL', 'IN-LAW', 'Y');
INSERT INTO RELATIONSHIP(RELATIONCODE, RELATIONDESC, ISEHR) VALUES ('MAI', 'MAID', 'Y');
INSERT INTO RELATIONSHIP(RELATIONCODE, RELATIONDESC, ISEHR) VALUES ('MO', 'MOTHER', 'Y');
INSERT INTO RELATIONSHIP(RELATIONCODE, RELATIONDESC, ISEHR) VALUES ('NE', 'NEPHEW', 'Y');
INSERT INTO RELATIONSHIP(RELATIONCODE, RELATIONDESC, ISEHR) VALUES ('NI', 'NIECE', 'Y');
INSERT INTO RELATIONSHIP(RELATIONCODE, RELATIONDESC, ISEHR) VALUES ('OT', 'OTHER RELATIONSHIP', 'Y');
INSERT INTO RELATIONSHIP(RELATIONCODE, RELATIONDESC, ISEHR) VALUES ('SI', 'SISTER', 'Y');
INSERT INTO RELATIONSHIP(RELATIONCODE, RELATIONDESC, ISEHR) VALUES ('SO', 'SON', 'Y');
INSERT INTO RELATIONSHIP(RELATIONCODE, RELATIONDESC, ISEHR) VALUES ('UN', 'UNCLE', 'Y');
INSERT INTO RELATIONSHIP(RELATIONCODE, RELATIONDESC, ISEHR) VALUES ('WI', 'WIFE', 'Y');
INSERT INTO RELATIONSHIP(RELATIONCODE, RELATIONDESC, ISEHR) VALUES ('HCP', 'HEALTHCARE PROVIDER', 'Y');

-- HKAH Only
INSERT INTO RELATIONSHIP(RELATIONCODE, RELATIONDESC, ISEHR) VALUES ('EM', 'EMPLOYER', 'N');
INSERT INTO RELATIONSHIP(RELATIONCODE, RELATIONDESC, ISEHR) VALUES ('CW', 'COWORKER', 'N');

COMMIT;
