ALTER TABLE SCHEDULE ADD BLOCKDATE DATE;
ALTER TABLE SCHEDULE ADD UNBLOCKDATE DATE;

ALTER TABLE SCHEDULE rename column BLOCKDATE to SCHDATE_B;
ALTER TABLE SCHEDULE rename column UNBLOCKDATE to SCHDATE_U;
ALTER TABLE SCHEDULE ADD SCHDATE_C DATE;
ALTER TABLE SCHEDULE ADD DOCLOCID NUMBER(22, 0);
