ALTER TABLE SLIP_EXTRA
DROP PRIMARY KEY CASCADE;
DROP TABLE SLIP_EXTRA CASCADE CONSTRAINTS;

CREATE TABLE SLIP_EXTRA(
	SLPNO	     VARCHAR2(15 BYTE) NOT NULL ENABLE,
	SLPMID	     NUMBER(10,0) NULL,
	SLPSNO       VARCHAR2(20),
	SENDBILLDATE DATE,
	SENDBILLTYPE VARCHAR2(10),
	SLPDATE      DATE,
	SMTRMK	     VARCHAR2(4000),
	SMTRMKUSER   VARCHAR2(20),
	SPRQTID      NUMBER(10,0),
	ISRECLG      NUMBER(1,0),
	ARACMCODE    VARCHAR2(10),
	PBPKGCODE    VARCHAR2(10),
	ESTGIVN      NUMBER(1,0),
	NOSIGN       VARCHAR2(10),
	SLPADDRMK3   VARCHAR2(3000),
	PRIMARY KEY (SLPNO)
);

ALTER TABLE SLIP_EXTRA ADD (
	CONSTRAINT SLIP_EXTRA_R01
	FOREIGN KEY (SLPNO)
	REFERENCES SLIP (SLPNO));
/