ALTER TABLE SLIPTX_EXTRA
DROP PRIMARY KEY CASCADE;
DROP TABLE SLIPTX_EXTRA CASCADE CONSTRAINTS;

CREATE TABLE SLIPTX_EXTRA(
	STNID	 NUMBER(22, 0) NOT NULL ENABLE,
	SLPNO	 VARCHAR2(15 BYTE) NOT NULL ENABLE,
	STNSEQ   NUMBER(22,0) NOT NULL ENABLE,
	STNSDATE DATE DEFAULT SYSDATE,
	PRIMARY KEY (STNID)
);

ALTER TABLE SLIPTX_EXTRA ADD (
	CONSTRAINT SLIPTX_EXTRA_R01
	FOREIGN KEY (STNID)
	REFERENCES SLIPTX (STNID));
/