DROP TABLE SPECITEM;
CREATE TABLE SPECITEM
(
	SPCCODE         VARCHAR2(10 BYTE) DEFAULT 'ALL',
	DOCCODE         VARCHAR2(10 BYTE) DEFAULT 'ALL',
	ITMCODE		VARCHAR2(10 BYTE) NOT NULL,
	ACTIVE		NUMBER(1) DEFAULT -1,
	CONSTRAINT "PK_SPECITEM" PRIMARY KEY ("SPCCODE", "DOCCODE", "ITMCODE")
);


--TWAH
Insert into SPECITEM (SPCCODE,ITMCODE,ACTIVE) values ('NE','RE01',-1);
Insert into SPECITEM (SPCCODE,ITMCODE,ACTIVE) values ('PL','RE02',-1);
Insert into SPECITEM (SPCCODE,ITMCODE,ACTIVE) values ('ON','RE03',-1);
Insert into SPECITEM (SPCCODE,ITMCODE,ACTIVE) values ('RH','RE04',-1);
Insert into SPECITEM (SPCCODE,ITMCODE,ACTIVE) values ('NP','RE05',-1);
Insert into SPECITEM (SPCCODE,ITMCODE,ACTIVE) values ('RP','RE06',-1);
Insert into SPECITEM (SPCCODE,ITMCODE,ACTIVE) values ('TH','RE08',-1);
Insert into SPECITEM (SPCCODE,ITMCODE,ACTIVE) values ('NS','RE09',-1);
Insert into SPECITEM (SPCCODE,ITMCODE,ACTIVE) values ('PM','RE10',-1);
Insert into SPECITEM (SPCCODE,ITMCODE,ACTIVE) values ('HP','RE12',-1);
Insert into SPECITEM (SPCCODE,ITMCODE,ACTIVE) values ('HH','RE13',-1);
Insert into SPECITEM (SPCCODE,ITMCODE,ACTIVE) values ('OB','RE15',-1);
Insert into SPECITEM (SPCCODE,ITMCODE,ACTIVE) values ('ED','RE16',-1);
Insert into SPECITEM (SPCCODE,ITMCODE,ACTIVE) values ('IN','RE20',-1);
Insert into SPECITEM (SPCCODE,ITMCODE,ACTIVE) values ('OP','RE25',-1);
Insert into SPECITEM (SPCCODE,ITMCODE,ACTIVE) values ('SU','RE30',-1);
Insert into SPECITEM (SPCCODE,ITMCODE,ACTIVE) values ('SK','RE35',-1);
Insert into SPECITEM (SPCCODE,ITMCODE,ACTIVE) values ('EN','RE40',-1);
Insert into SPECITEM (SPCCODE,ITMCODE,ACTIVE) values ('OR','RE45',-1);
Insert into SPECITEM (SPCCODE,ITMCODE,ACTIVE) values ('CA','RE50',-1);
Insert into SPECITEM (SPCCODE,ITMCODE,ACTIVE) values ('UR','RE55',-1);
Insert into SPECITEM (SPCCODE,ITMCODE,ACTIVE) values ('MH','RE60',-1);
Insert into SPECITEM (SPCCODE,ITMCODE,ACTIVE) values ('GM','RE63',-1);
Insert into SPECITEM (SPCCODE,ITMCODE,ACTIVE) values ('GP','RE70',0);
Insert into SPECITEM (DOCCODE,ITMCODE,ACTIVE) values ('P203','RE10G',-1);
Insert into SPECITEM (DOCCODE,ITMCODE,ACTIVE) values ('P206','RE10G',-1);
COMMIT;