ALTER TABLE SYSLOG
 DROP PRIMARY KEY CASCADE;
DROP TABLE SYSLOG CASCADE CONSTRAINTS;

CREATE TABLE SYSLOG
(
  MODULE  VARCHAR2(100),
  ACTION  VARCHAR2(200),
  REMARK  VARCHAR2(500),
  USERID  VARCHAR2(100),
  SYSTIME DATE DEFAULT SYSDATE,
  PCNAME  VARCHAR2(100)
);
COMMIT;