--BOTH
DELETE FROM SYSPARAM WHERE PARCDE IN ('PRTRLBL', 'PRTRMEDLBL', 'PRTRTWBADT', 'PRTRTWBBB', 'MaxLabel',
										'PRTFORM');
DELETE FROM SYSPARAM WHERE PARCDE IN ('DBEnv', 'DOCFEEPATH', 'DERptPath', 'OTRPTPATH', 'ptIgUrlSte',
										'HomeVisit', 'RegPatRk1', 'RegPatRk2', 'RegChkDoc', 'PatIDConty',
										'PatChkID', 'PatAMCCMP', 'PRTMRCARD', 'PRGENLBL',
										'PRPATCARD', 'AUTOREGLBL', 'PRTPATCARD', 'PRCALLCHRT', 'rptServer',
										'PBkAMCCMP', 'TXALERT');
--TWAH
DELETE FROM SYSPARAM WHERE PARCDE IN ('PRTRLBLC', 'PatLocDef');

--BOTH
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('PRTRLBL', 'LABEL', NULL, 'Printer of label');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('PRTRMEDLBL', 'MEDCHARTLABEL', NULL, 'Printer of call chart label');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('PRTRTWBADT', 'WRISTBANDADULT', NULL, 'PRINTER WRISTBAND ADULT');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('PRTRTWBBB', 'WRISTBANDBABY', NULL, 'Printer of Wrist Band Baby');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('MaxLabel', '20', 'Nil', 'Max Num of label');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('PRTFORM', 'HATSFORM', NULL, 'Printer for HATS Form');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('EHRENABLE', 'Y', NULL, 'Enable Patient > eHR Tab');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('EHRPMIALT', '00000000000000', 'YYYYMMDDHH24MISS', 'Ehr PMI last Alert');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('EHRPMILNK', 'http://160.100.2.73/HKAHEHR/uploadPmi', NULL, 'Ehr PMI Upload server link');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('EHRPMIBLNK', 'http://160.100.2.73/HKAHEHR/', NULL, 'Ehr PMI base link');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('EHRPMICKPD', 'ID', NULL, 'EhrPMI Chk p duplicate method');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('EHRSAAMWSL', 'http://160.100.2.73:9081/hepr/ws/transform/saam/SaamDataTransformWebS.wsdl', NULL, 'SAAM web services wsdl');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('EHREPISWSL', 'http://160.100.2.73:9081/hepr/ws/transform/epis/EpisDataTransformWebS.wsdl', NULL, 'EPIS web services wsdl');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('PREBOOKALT', '3', NULL, 'No. of Pre-bookings allowed');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('FILTERBILL', 'ZrptIP', NULL, 'Filter weekly bill file');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('PatRegDocC', 'N', NULL, 'Enable doctor combo in PatReg');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('PRTRLBLC', 'HATS_A4', NULL, 'Printer of LABEL C');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('CLCHARTLOG', 'Y', NULL, 'Req log of print call chart');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('TXALERT', 'Y', NULL, 'Patient Alert in Txn Detail');


-- AMC
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('PatRegDocC', 'Y', NULL, 'Enable doctor combo in PatReg');

--HKAH
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('DBEnv', '160.100.3.55', 'Nil', 'Database Environment');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('DOCFEEPATH', '\\160.100.1.10\Report\DocFeeReport\', null, 'Doctor Fee Report Path');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('DERptPath', '\\160.100.1.10\Report\', NULL, 'Dayend report path');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('OTRPTPATH', '\\160.100.2.79\hat\prod\ot\report\', NULL, 'OT Report Path (New storage)');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('ptIgUrlSte', 'www-server', 'Nil', 'where PatImage Page Locate');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('HomeVisit', 'N', 'Nil', 'Show Home Visit');
--INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('RegPatRk1', 'REG', 'Nil', 'Show Patient Remark1 in Reg');
--INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('RegPatRk2', 'REGAD', 'Nil', 'Show Patient Remark2 in Reg');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('RegChkDoc', 'Y', 'Nil', 'Check Doctor 1st Visit in Reg');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('PatIDConty', 'Y', 'Nil', 'Show Patient ID Country');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('PatChkID', 'Y', 'Nil', 'Show Patient CHK ID');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('PatAMCCMP', 'Y', 'Nil', 'Show Patient AMC/CMP');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('PBkAMCCMP', 'Y', 'Nil', 'Show Pre Book AMC/CMP');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('PRTMRCARD', 'z1emboss', NULL, 'Printer for MR Card');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('PRGENLBL', 'N', NULL, 'General Label in Reg Tab');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('PRPATCARD', 'Y', NULL, 'Patient Card in Reg Tab');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('AUTOREGLBL', 'N', NULL, 'Auto Print Label for reg');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('PRTPATCARD', 'K3', NULL, 'Printer for Patient Card');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('PRCALLCHRT', 'N', NULL, 'Call chart dialog in Reg Tab');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('CLAPPLBL', 'N', NULL, 'Close after prt applbl');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('AUTOCOMPAR', 'N', NULL, 'Auto complete AR Code');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('PICKLBLORD', 'P', NULL, 'Deafult order of picklist label');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('AUTPRTRECE', 'N', NULL, 'Prompt printing receipt(Auto)');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('2DLBLREGID', 'N', NULL, '2D Label with RegID');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('MERGEDTOAL', 'N', NULL, 'Merged to Patient Alert');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('CHIAPPDATE', 'N', NULL, 'Show chi date in appt label');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('AppAltShow', 'Y', 'Nil', 'Show Doctor Appointment Alert');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('AppAltEnty', 'N', 'Nil', 'Entry Doctor Appointment Alert');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('PRTADMLBL', 'Y', NULL, 'print adm label');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('SKIPDOC', '7___', NULL, 'Ignore the pattern of doccode');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('ALFOCUS', 'SLPNO', NULL, 'Default focus to AR Allocation');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('CARDOTHLOC', 'Y', NULL, 'Print card to other location');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('PRTPTCARD2', 'K3-IPD', NULL, 'Printer for Patient Card');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('PRTMRCARD2', 'z1emboss-IPD', NULL, 'Printer for MR Card');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('PRTPTCARD3', 'K3-INFORM', NULL, 'Printer for Patient Card');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('PRTMRCARD3', 'z1emboss-INFORM', NULL, 'Printer for MR Card');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('HIDEADRLBL', 'Y', NULL, 'Hide address label btn');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('HLTXNDT', 'Y', NULL, 'Highlight txndate(Add Charge)');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('PREBOOKALT', '3', NULL, 'No. of Pre-bookings allowed');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('RpPageSize', 'A4', NULL, 'The Page Size of Total Receipt');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('CsPageSize', 'A4', NULL, 'Page Size of Charge Summary');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('ArBlockEvt', 'MIS1', NULL, 'Block any related event of AR');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('ArSignMeth', 'A', NULL, 'Determine AR Sign method');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('ARBillStmt', 'Y', NULL, 'Show Bill to AR in statment');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('EPSREFSTN', 'Y', NULL, 'Is Shorten EPS Reference No');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('PATDOCTYP', 'Y', NULL, 'Is Show Patient Doc Type');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('OPStmtCopy', 'Y', NULL, 'OP Statment - default copy');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('NRNOTELBLN', '0', NULL, 'Number of Nurse Note Label');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('OTTABVIEW', 'S', NULL, 'The Tab View Mode of OT');

--UAT
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('rptServer', '160.100.2.73:9080', 'Nil', 'Report Server');

--TWAH
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('DBEnv', '192.168.0.172', 'Nil', 'Database Environment');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('DOCFEEPATH', '\\192.168.0.145\hat\Report\DocFeeReport\', null, 'Doctor Fee Report Path');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('DERptPath', '\\192.168.0.145\hat\report\', NULL, 'Dayend report path');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('OTRPTPATH', '\\it-server6\hat\hats1\ot\report\', NULL, 'OT Report Path (New storage)');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('ptIgUrlSte', '192.168.0.20', 'Nil', 'where PatImage Page Locate');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('HomeVisit', 'Y', 'Nil', 'Show Home Visit');
--INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('RegPatRk1', 'N', 'Nil', 'Show Patient Remark1 in Reg');
--INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('RegPatRk2', 'N', 'Nil', 'Show Patient Remark2 in Reg');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('RegChkDoc', 'N', 'Nil', 'Check Doctor 1st Visit in Reg');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('PatIDConty', 'N', 'Nil', 'Show Patient ID Country');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('PatChkID', 'N', 'Nil', 'Show Patient CHK ID');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('PatAMCCMP', 'N', 'Nil', 'Show Patient AMC/CMP');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('DCardDue', '31/12/2017', 'Nil', 'Discount card due date');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('PRGENLBL', 'Y', NULL, 'General Label in Reg Tab');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('PRPATCARD', 'Y', NULL, 'Patient Card in Reg Tab');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('AUTOREGLBL', 'Y', NULL, 'Auto Print Label for reg');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('PRTPATCARD', 'REDCARD', NULL, 'Printer for Patient Card');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('PRCALLCHRT', 'Y', NULL, 'Call chart dialog in Reg Tab');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('CLAPPLBL', 'Y', NULL, 'Close after prt applbl');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('AUTOCOMPAR', 'N', NULL, 'Auto complete AR Code');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('PICKLBLORD', 'T', NULL, 'Deafult order of picklist label');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('AUTPRTRECE', 'Y', NULL, 'Prompt printing receipt(Auto)');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('2DLBLREGID', 'Y', NULL, '2D Label with RegID');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('MERGEDTOAL', 'Y', NULL, 'Merged to Patient Alert');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('CHIAPPDATE', 'Y', NULL, 'Show chi date in appt label');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('PRTADMLBL', 'N', NULL, 'print adm label');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('ALFOCUS', 'AAMOUNT', NULL, 'Default focus to AR Allocation');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('HLTXNDT', 'N', NULL, 'Highlight txndate(Add Charge)');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('TRANSBLBL', 'Y', NULL, 'Transfer Bed Label');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('REGLBLMULI', 'N', NULL, 'Multi locations of reg label');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('ARIVLBLMR', 'MRLABEL', NULL, 'Print label to MR');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('NRNOTELBLN', '1', NULL, 'Number of Nurse Note Label');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('OTTABVIEW', 'M', NULL, 'The Tab View Mode of OT');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('TICKETOPT', 'Y', NULL, 'Show print ticket label option');

--UAT
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('rptServer', '160.100.2.73:9080', 'Nil', 'Report Server');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('DocFeeARun', 'N', 'Nil', 'Allow Doc Fee rpt actual run');


--HKAH ONLY
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('PatLocDef', '#1', 'Nil', 'Default Patient Loation');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('TxRegDt', 'Y', 'Nil', 'Show RegDate in Tx Search ');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('TxDtlColMu', 'Y', 'Nil', 'Enable Col Menu in Tx Dtl');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('PKGSHBTN', 'Y', NULL, 'enable pkg schbtn in add chge');	-- AMC

--TWAH ONLY

-- HKAH UAT
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('EHRHCPID', '7629734262', NULL, 'HCP identifier');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('EHRHCIID', '7999503147', NULL, 'HCI identifier');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('EHRHCPNAME', 'ADV TEST', NULL, 'HCP name');

INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('CSHOFFCLS', 'Y', NULL, 'Sign off cashier when w close');	-- HKAH, AMC
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('CSHOFFCLS', 'N', NULL, 'Sign off cashier when w close'); -- TWAH

-- AMC ONLY
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('DOCFEEPATH', 'C:\hat\Report\DocFeeReport\', null, 'Doctor Fee Report Path');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('PRTRNP', 'N', null, 'Not print receipt cashier p/r');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('PRTVOIDS', 'N', null, 'Not print cashier void sheet');

-- Op Statement
-- HKAH
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('OpPageSize', 'A4', null, 'OP statement report page size');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('OpPageOrie', 'LANDSCAPE', null, 'OP statement page orientation');
-- TWAH
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('OpPageSize', 'A5', null, 'OP statement report page size');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('OpPageOrie', 'LANDSCAPE', null, 'OP statement page orientation');
-- AMC
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('OpPageSize', 'A5', null, 'OP statement report page size');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('OpPageOrie', 'PORTRAIT', null, 'OP statement page orientation');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('OpShowSgnL', 'Y', null, 'OP statement show signature ln');
INSERT INTO SYSPARAM (PARCDE, PARAM1, PARAM2, PARDESC) VALUES ('ArSignMeth', 'B', NULL, 'Determine AR Sign method');

commit;
