ALTER TABLE USRACCESSDOC
DROP PRIMARY KEY CASCADE;
DROP TABLE USRACCESSDOC CASCADE CONSTRAINTS;

CREATE TABLE "USRACCESSDOC" 
(	"USRID" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"DOCCODE" VARCHAR2(10 BYTE) DEFAULT 'ALL' NOT NULL ENABLE, 
	"SPCCODE" VARCHAR2(10 BYTE) DEFAULT 'ALL' NOT NULL ENABLE, 
 CONSTRAINT "USRACCESSDOC_PK" PRIMARY KEY ("USRID", "DOCCODE", "SPCCODE")
);