ALTER TABLE USRFUNCSEC
DROP PRIMARY KEY CASCADE;
DROP TABLE USRFUNCSEC CASCADE CONSTRAINTS;

CREATE TABLE USRFUNCSEC(
	UsrID	VARCHAR2(10 BYTE) NOT NULL ENABLE,
	FscID	NUMBER(22,0) NOT NULL ENABLE,
	CONSTRAINT "PK_USRFUNCSEC" PRIMARY KEY (UsrID, FscID)
);

ALTER TABLE USRFUNCSEC ADD (
	CONSTRAINT USRFUNCSEC_R01
	FOREIGN KEY (UsrID)
	REFERENCES Usr (UsrID));

ALTER TABLE USRFUNCSEC ADD (
	CONSTRAINT USRFUNCSEC_R02
	FOREIGN KEY (FscID)
	REFERENCES FuncSec (FscID));

