//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.30 at 04:23:32 PM CST 
//


package hk.gov.ehr.hepr.ws;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InvrDataUploadRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InvrDataUploadRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="uploadMode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="InvrRecords" type="{http://ehr.gov.hk/hepr/ws}InvrUploadRecord" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InvrDataUploadRequest", propOrder = {
    "uploadMode",
    "invrRecords"
})
public class InvrDataUploadRequest {

    @XmlElement(required = true)
    protected String uploadMode;
    @XmlElement(name = "InvrRecords")
    protected List<InvrUploadRecord> invrRecords;

    /**
     * Gets the value of the uploadMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUploadMode() {
        return uploadMode;
    }

    /**
     * Sets the value of the uploadMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUploadMode(String value) {
        this.uploadMode = value;
    }

    /**
     * Gets the value of the invrRecords property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the invrRecords property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInvrRecords().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InvrUploadRecord }
     * 
     * 
     */
    public List<InvrUploadRecord> getInvrRecords() {
        if (invrRecords == null) {
            invrRecords = new ArrayList<InvrUploadRecord>();
        }
        return this.invrRecords;
    }

}
