//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.30 at 04:23:32 PM CST 
//


package hk.gov.ehr.hepr.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.hl7.v3.LabResultMBDetail;
import org.hl7.v3.Participant;


/**
 * <p>Java class for LabmbUploadRecord complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LabmbUploadRecord">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:hl7-org:v3}participant"/>
 *         &lt;element ref="{urn:hl7-org:v3}labResultMBDetail"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LabmbUploadRecord", propOrder = {
    "participant",
    "labResultMBDetail"
})
public class LabmbUploadRecord {

    @XmlElement(namespace = "urn:hl7-org:v3", required = true)
    protected Participant participant;
    @XmlElement(namespace = "urn:hl7-org:v3", required = true)
    protected LabResultMBDetail labResultMBDetail;

    /**
     * Gets the value of the participant property.
     * 
     * @return
     *     possible object is
     *     {@link Participant }
     *     
     */
    public Participant getParticipant() {
        return participant;
    }

    /**
     * Sets the value of the participant property.
     * 
     * @param value
     *     allowed object is
     *     {@link Participant }
     *     
     */
    public void setParticipant(Participant value) {
        this.participant = value;
    }

    /**
     * Gets the value of the labResultMBDetail property.
     * 
     * @return
     *     possible object is
     *     {@link LabResultMBDetail }
     *     
     */
    public LabResultMBDetail getLabResultMBDetail() {
        return labResultMBDetail;
    }

    /**
     * Sets the value of the labResultMBDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link LabResultMBDetail }
     *     
     */
    public void setLabResultMBDetail(LabResultMBDetail value) {
        this.labResultMBDetail = value;
    }

}
