//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DEMO.RC
//
#define IDR_MAINFRAME                   2
#define IDR_IMGTYPE                     3
#define IDS_ALLFILTER                   4
#define IDR_FAXTYPE                     4
#define IDS_FORMFILTER                  5
#define IDS_OPENFILE                    6
#define IDS_OPENFORM                    7
#define IDS_SAVEFILE                    8
#define IDS_CLOSEDOCUMENT               9
#define IDS_SAVEFILTER                  10
#define IDS_SAVEANNO                    10
#define IDS_CONVOLUTIONERR              11
#define IDS_STARTBRIGHTNESS             12
#define IDS_COMPUTEBRIGHTNESS           13
#define IDS_MAKEDCX                     14
#define IDS_SAVEFAILED                  15
#define IDS_LOADERR                     16
#define IDS_UNKNOWNFORMAT               17
#define IDS_LOADANNO                    18
#define IDR_SENDLOGTYPE                 50
#define IDR_RECLOGTYPE                  51
#define IDR_OUTLOGTYPE                  52
#define IDR_FAXBLOCKTYPE                53
#define IDR_POLLTYPE                    54
#define IDR_POLLLOGTYPE                 54
#define IDD_ABOUTBOX                    100
#define IDC_BASE                        100
#define IDC_LIST2                       100
#define IDD_DIMENSIONS                  101
#define IDC_TIFFFILE                    101
#define IDC_E_STEPNUM                   101
#define IDC_WIDTH                       102
#define IDD_LOADDIM                     102
#define IDC_R_STEPNUM                   102
#define IDC_EDIT3                       102
#define IDC_HEIGHT                      103
#define IDD_LOADOPTIONS                 103
#define IDC_NEW2                        103
#define IDC_FROMPHONE                   103
#define IDC_PLANES                      104
#define IDD_SAVEPARAM                   104
#define IDC_DEL2                        104
#define IDL_LISTBOX                     104
#define IDC_BITS                        105
#define IDD_DITHERING                   105
#define IDC_HORZDPI                     106
#define IDD_ROTATING                    106
#define IDC_EDIT                        106
#define IDC_VERTDPI                     107
#define IDD_SKEWING                     107
#define IDC_VIEW                        107
#define IDD_SCALING                     108
#define IDC_NEW1                        108
#define IDC_DEL1                        109
#define IDC_OFFSET                      110
#define IDC_CONTRAST                    110
#define IDC_E1                          110
#define IDC_SHOW                        110
#define IDC_BITORDER                    111
#define IDD_COLOR2GRAY                  111
#define IDC_E2                          111
#define IDC_BYTEORDER                   112
#define IDD_CONTRAST                    112
#define IDC_E3                          112
#define IDC_SEARCH                      112
#define IDC_SCREEN                      113
#define IDI_CONTRAST                    113
#define IDC_E4                          113
#define IDC_TEXT                        113
#define IDC_BITMAP                      114
#define IDI_BRIGHTNESS                  114
#define IDC_E5                          114
#define ID_NOCOMP                       115
#define IDC_E6                          115
#define ID_PACKBITS                     116
#define IDD_CUSTOM_ZOOM                 116
#define IDC_E7                          116
#define ID_LZW                          117
#define IDD_ZOOM_STEP                   117
#define ID_LZW_DIFF                     118
#define IDC_E9                          118
#define IDC_CUR_ZOOM                    118
#define ID_CCITTG2                      119
#define IDC_E10                         119
#define IDD_MYSAVE                      119
#define ID_CCITTG31D                    120
#define ID_CCITTG32D                    121
#define IDD_HALFTONE                    121
#define ID_CCITTG4                      122
#define IDC_CUR_MAGNIFY                 122
#define IDD_ASCII2DIB                   122
#define ID_MONO                         123
#define IDD_INPUTFORM                   123
#define ID_GREY                         124
#define ID_COLOR                        125
#define IDC_TIFFVERSION                 126
#define IDC_IMAGEVERSION                126
#define IDD_PORTENABLE                  126
#define IDC_BITMANIVERSION              127
#define IDC_TIFFVERSIO                  127
#define IDC_FAXWAIT                     127
#define IDC_GIFVERSION                  128
#define IDR_TOOLBAR_0                   128
#define IDC_COMPRESSION                 129
#define IDC_TGAVERSION                  129
#define IDD_PBEDIT                      129
#define IDR_TOOLBAR_1                   129
#define IDC_FLOYD                       130
#define IDC_PCXVERSION                  130
#define IDD_PBGROUP                     130
#define IDR_TOOLBAR_2                   130
#define IDC_JARVISH                     131
#define IDC_FAXVERSION                  131
#define IDD_PBSEARCH                    131
#define IDR_TOOLBAR_3                   131
#define IDC_CAPPIX_SMOTH                132
#define IDD_PBPERSON                    132
#define IDR_TOOLBAR_4                   132
#define IDC_ANNOVERSION                 132
#define IDC_CAPPIX_SHARP                133
#define IDD_PBVIEW                      133
#define IDR_TOOLBAR_5                   133
#define IDC_DEPTH1                      134
#define IDD_STATUS                      134
#define IDC_ANNOMOVE                    134
#define IDC_DEPTH4                      135
#define IDB_BITMAP1                     135
#define IDB_NAMEU                       135
#define IDC_DEPTH8                      136
#define IDI_BFT                         136
#define IDB_NAMED                       136
#define IDC_DEGREE                      137
#define IDI_COLOR                       137
#define IDB_NAMEX                       137
#define IDC_SLOW                        138
#define IDI_NORMAL                      138
#define IDB_NAMES                       138
#define IDC_FAST                        139
#define IDC_EDIT1                       139
#define IDB_NUMBERD                     139
#define IDC_DISTANCE                    140
#define IDC_DAY                         140
#define IDB_NUMBERS                     140
#define IDC_TIME                        140
#define IDC_FROMNAME                    140
#define IDC_X_AXIS                      141
#define IDC_YEAR                        141
#define IDB_NUMBERU                     141
#define IDC_TEL                         141
#define IDC_Y_AXIS                      142
#define IDC_HOUR                        142
#define IDB_NUMBERX                     142
#define IDC_MINUTE                      143
#define IDB_DATED                       143
#define IDB_SDATE                       144
#define IDC_BILINEAR                    145
#define IDB_DATEU                       145
#define IDC_CUBIC_SPLINE                146
#define IDB_DATEx                       146
#define IDB_SNAME                       146
#define IDC_NOANTIALISING               147
#define IDB_DATES                       147
#define IDC_ANTIALISING3                148
#define IDB_TIMED                       148
#define IDC_ANTIALISING5                149
#define IDB_TIMES                       149
#define IDC_PSYCHOVISUAL                150
#define IDC_R1                          150
#define IDB_TIMEU                       150
#define IDC_R2                          151
#define IDB_TIMEX                       151
#define IDB_SPAGE                       151
#define IDC_BRIGHTNESS                  152
#define IDC_R3                          152
#define IDB_PAGED                       152
#define IDC_CVALUE                      153
#define IDC_R4                          153
#define IDB_PAGES                       153
#define IDC_BVALUE                      154
#define IDC_R5                          154
#define IDB_PAGEU                       154
#define IDC_R6                          155
#define IDC_JPEG_STAT                   155
#define IDB_PAGEX                       155
#define IDB_SPHN                        155
#define IDC_R7                          156
#define IDC_RADIO1                      156
#define IDB_STIME                       156
#define IDC_R8                          157
#define IDC_RADIO2                      157
#define IDD_PORTSET                     157
#define IDC_EDIT2                       158
#define IDC_R9                          158
#define IDC_RADIO3                      158
#define IDC_R10                         159
#define IDC_SCROLL1                     159
#define IDD_PORTSEL                     159
#define IDC_FROMCOMP                    159
#define IDC_LIST1                       161
#define IDD_OPENBCHANNEL                161
#define IDC_ADD                         162
#define IDC_REMOVE                      163
#define IDC_BFT                         164
#define IDC_GROUP                       165
#define IDC_GNUM                        166
#define IDC_NACT                        167
#define IDD_PBPOSITION                  167
#define IDC_GRPSAVE                     168
#define IDD_OPENNMSCHANNEL              169
#define IDC_TESTMODEM                   171
#define IDC_TEST1                       172
#define IDC_TEST2                       173
#define IDD_APP_EXIT                    173
#define IDC_TEST3                       174
#define IDC_TEST11                      175
#define IDC_ENABLEPORT                  176
#define IDC_ENABLEECM                   177
#define IDC_ENABLEECMS                  177
#define IDC_Z_ERROR                     178
#define IDC_ENABLEBFT                   178
#define IDC_E_BASE                      179
#define IDC_STATIC1                     179
#define IDC_ENABLEECMR                  179
#define IDC_R_BASE                      180
#define IDC_FAXLISTX1                   181
#define IDC_RESET                       182
#define IDC_HDRSTRING                   183
#define IDC_UNSELECT                    183
#define IDC_SHOWALL                     183
#define IDC_MONTH                       184
#define IDC_COMPANY                     185
#define IDC_PAGES                       186
#define IDC_CDATE                       187
#define IDC_CTIME                       188
#define IDC_YMARGIN                     189
#define IDC_SDATE                       189
#define IDC_COMBO1                      189
#define IDC_XMARGIN                     190
#define IDC_STIME                       190
#define IDC_COMMAND                     190
#define IDC_YDPI                        191
#define IDC_NAME                        191
#define IDC_BMPHEADER                   191
#define IDC_XDPI                        192
#define IDC_NUMBER                      192
#define IDC_LINESPACE                   193
#define IDC_TABS                        194
#define IDC_UNCOMPRESSED                194
#define IDC_FONTSEL                     195
#define IDC_G31D                        195
#define IDC_INCH                        196
#define IDC_G32D                        196
#define IDC_METER                       197
#define IDC_G4                          197
#define IDC_MESUREGROUP                 198
#define IDC_RECPOLLING                  198
#define IDC_COLOR                       198
#define IDC_DIR                         199
#define IDD_PORTSETUP                   200
#define IDC_TEST                        200
#define IDD_SENDFAX                     201
#define IDD_CLOSEFAX                    202
#define IDC_TYPE                        202
#define IDD_ABORT_FAX                   203
#define IDC_CHANNELS                    203
#define IDD_FAXEVENT                    204
#define IDC_BID                         204
#define IDC_CFILE                       204
#define IDD_RECEIVE                     205
#define IDC_HEADER                      205
#define IDD_RECFAX                      206
#define IDC_FOOTER                      206
#define IDD_FAXCONFIG                   207
#define IDD_POLLING                     208
#define IDC_CONFIG                      208
#define IDD_OPENGCHANNEL                209
#define IDD_COVER                       210
#define IDC_TOFAX                       211
#define IDD_GETLINEWIDTH                211
#define IDC_FROMFAX                     212
#define IDC_TONAME                      213
#define IDC_TOCOMP                      214
#define IDC_TOPHONE                     215
#define IDC_SENDCOVER                   216
#define IDC_CUSTOM                      217
#define IDC_DEFAULT                     218
#define IDC_CHECK1                      219
#define IDC_BUTTON1                     220
#define IDC_BUTTON2                     221
#define IDC_TEXT2                       221
#define IDC_PORTLIC                     221
#define IDC_BUTTON3                     222
#define IDC_TEXT1                       222
#define IDC_PORTS                       222
#define IDC_FINEFAXPAGE                 223
#define IDC_TESTDIALTONE                223
#define IDC_STANDARDFAXPAGE             224
#define IDC_WEB                         224
#define IDC_CHANNELBC                   225
#define IDC_EMAIL                       225
#define IDC_HEADERBC                    226
#define IDC_BIDIBVERSION                226
#define IDD_OPENBCCHANNEL               227
#define IDC_BIJPEGVERSION               227
#define IDC_BIPRINTVERSION              228
#define IDC_BICPVERSION                 229
#define IDC_BIDISPVERSION               230
#define IDC_E8                          231
#define IDC_BROWSE                      232
#define IDC_DTMF                        233
#define IDC_BROOK_VERSION               234
#define IDC_BROOK_NUMBER                235
#define IDC_CLOSING                     239
#define IDC_FAXLIST                     300
#define IDC_SETUP                       301
#define IDC_DEBUG                       302
#define IDC_FAXPORTS                    303
#define IDC_DRDEBUG                     303
#define IDC_PORTLIST                    304
#define IDC_IDSTRING                    305
#define IDC_NOFRING                     306
#define IDC_DEBUGFILE                   307
#define IDC_FAXNUMBER                   308
#define IDC_DRDEBUGFILE                 308
#define IDC_ACTPAGE                     311
#define IDC_FCLEAR                      312
#define IDC_EVENTLIST                   313
#define IDCH_AUTOANSW                   314
#define IDEE_RINGS                      316
#define IDC_REC_MANUAL                  317
#define IDC_STO_OFF                     318
#define IDC_STO_ON                      319
#define IDC_STO_DIAL                    320
#define IDC_SENDQUEUE                   400
#define IDC_SPV_LOW                     400
#define IDC_SEND_MANUAL                 401
#define IDC_SPV_MEDIUM                  401
#define IDC_SENDIMMEDIATE               402
#define IDC_SPV_HIGH                    402
#define IDC_SEND_POLLING                403
#define IDC_B2400                       500
#define IDC_R4800                       501
#define IDC_B7200                       502
#define IDC_B9600                       503
#define IDC_B12000                      504
#define IDC_B14400                      505
#define IDC_B16800                      506
#define IDC_B19200                      507
#define IDC_B21600                      508
#define IDC_B24000                      509
#define IDC_B26400                      510
#define IDC_B28800                      511
#define IDC_B31200                      512
#define IDC_B33600                      513
#define IDD_DIALOG1                     515
#define IDD_OPENDCHANNEL                516
#define IDC_CHANNELSBC                  517
#define IDD_CMTXCHANNEL                 518
#define IDC_CHANNELSC                   519
#define IDC_HEADERC                     520
#define IDD_NMS                         521
#define IDC_CHANNELSNMS                 522
#define IDC_PROTOCOLL                   1051
#define IDC_DID                         1052
#define IDC_SPINDID                     1053
#define IDM_FITOWINDOW                  32769
#define IDM_CENTERIMAGE                 32770
#define IDM_ZOOMIN                      32772
#define IDM_ZOOMOUT                     32773
#define IDM_ROTATE90                    32774
#define IDM_ROTATE180                   32775
#define IDM_ROTATE270                   32776
#define IDM_FLIPHORIZONTAL              32777
#define IDM_FLIPVERTICAL                32778
#define IDM_DIMENSIONS                  32779
#define IDM_PAGEFORWARD                 32780
#define IDM_PAGEBACKWAD                 32781
#define IDM_EDIT_DELETE                 32782
#define IDM_HELP_SEARCH                 32783
#define IDM_FILE_OPEN_FORM              32784
#define IDM_TOOLS_NOTE                  32785
#define IDM_TOOLS_FONT                  32786
#define IDM_VIEW_INVERT                 32787
#define IDM_VIEW_DITHER                 32788
#define IDM_ROTATE                      32789
#define IDM_VIEW_SKEW                   32790
#define IDM_VIEW_ROTATE                 32791
#define IDM_VIEW_CONV_MONO              32792
#define IDM_VIEW_CONV_GRAY              32793
#define IDM_VIEW_SCALE                  32794
#define IDM_VIEV_CONV_NOANTIALISING     32795
#define IDM_VIEW_CONV_GRAY_ANTIALIZING3x3 32796
#define IDM_VIEV_CONV_GRAY_NOANTIALISING 32797
#define IDM_VIEW_CONV_GRAY_ANTIALISING5x5 32798
#define IDM_VIEW_BRIGHTNESS             32800
#define IDM_LOW_PASS3x3                 32801
#define IDM_HIGH_PASS3x3                32802
#define IDM_HIGH_PASS5x5                32803
#define IDM_VIEW_COLOR_TO_GRAY          32804
#define ID_IMAGE_CONVERTTO_GRAYSCALE    32807
#define ID_IMAGE_CONVERTTO_24BITCOLOR   32808
#define IDM_IMAGE_CONV_TO_24            32808
#define IDM_LOWMEM                      32810
#define IDM_ZOOM_MODE                   32811
#define IDM_CUSTOM_ZOOM                 32812
#define IDM_SHOW_PIX                    32813
#define IDM_SHOW_DPI                    32814
#define IDM_ZOOM_STEPS                  32815
#define IDM_HALFTONE                    32816
#define IDM_MAGNIFY                     32817
#define ID_FAX_SENDFILES                32818
#define ID_FAX_DISABLE                  32819
#define ID_PORTSETUP                    32824
#define ID_FAX_POLL                     32825
#define ID_FAX_BROOK                    32826
#define IDM_BROOK_DEBUG                 32827
#define ID_FAX_GAMMA                    32828
#define ID_PHONEBOOK_EDIT               32829
#define ID_PHONEBOOK_IMPORT             32830
#define ID_PHONEBOOK_EXPORT             32831
#define IDM_EDIT_PAGING                 32832
#define ID_ANNOTATION_IMAGE             32841
#define ID_CLOSE_DOCUMENT               32842
#define IDM_DIALOGIC                    32843
#define IDD_BICOM                       32844
#define IDM_SENDCOVER                   32845
#define IDD_CMTX                        32846
#define IDM_SENDASCII                   32847
#define IDM_FAXMANAGER                  32849
#define ID_BUTTON32850                  32850
#define ID_BUTTON32851                  32851
#define ID_BUTTON32852                  32852
#define ID_BUTTON32853                  32853
#define ID_BUTTON32854                  32854
#define ID_BUTTON32855                  32855
#define ID_BUTTON32856                  32856
#define ID_BUTTON32857                  32857
#define ID_BUTTON32858                  32858
#define ID_BUTTON32859                  32859
#define ID_BUTTON32860                  32860
#define ID_BUTTON32861                  32861
#define ID_BUTTON32862                  32862
#define ID_BUTTON32863                  32863
#define ID_BUTTON32864                  32864
#define ID_BUTTON32865                  32865
#define ID_BUTTON32866                  32866
#define ID_BUTTON32867                  32867
#define ID_BUTTON32868                  32868
#define ID_BUTTON32869                  32869
#define ID_BUTTON32870                  32870
#define ID_BUTTON32871                  32871
#define ID_BUTTON32872                  32872
#define ID_BUTTON32873                  32873
#define ID_BUTTON32874                  32874
#define ID_BUTTON32875                  32875
#define ID_BUTTON32879                  32879
#define IDM_FITTOWIDTH                  32880
#define ID_HELP_FAXCSDKHELP             32881
#define ID_FAX_PORTSETUP                33000
#define ID_FAX_PORT_CLOSE               33001
#define ID_FAX_ABORT                    33002
#define ID_FAX_SEND                     33003
#define ID_FAX_REC                      33004
#define ID_FAX_EVENT                    33005
#define ID_FAX_CONFIG                   33006
#define ID_ANNOTATION_FONT              33823
#define ID_ANNOTATION_OBJECT_WHITEOUT   33824
#define ID_ANNOTATION_OBJECT_HILITE     33825
#define ID_ANNOTATION_OBJECT_NOTE       33826
#define ID_ANNOTATION_OBJECT_LINE       33827
#define ID_ANNOTATION_OBJECT_RECTANGLE  33828
#define ID_ANNOTATION_OBJECT_ELLIPSE    33829
#define ID_ANNOTATION_OBJECT_STAMP      33830
#define ID_ANNOTATION_COLOR_BLACK       33831
#define ID_ANNOTATION_COLOR_YELLOW      33832
#define ID_ANNOTATION_COLOR_GREY        33833
#define ID_ANNOTATION_COLOR_BLUE        33834
#define ID_ANNOTATION_COLOR_RED         33835
#define ID_ANNOTATION_COLOR_PURPLE      33836
#define ID_ANNOTATION_COLOR_GREEN       33837
#define ID_ANNOTATION_COLOR_LIGHTBLUE   33838
#define ID_ANNOTATION_COLOR_LIGHTGRAY   33839
#define ID_ANNOTATION_LINE              33840
#define ID_ANNOTATION_LINETYPE_LINE     33841
#define ID_ANNOTATION_LINETYPE_ARROW    33842
#define ID_ANNOTATION_LINETYPE_FILLEDARROW 33843
#define ID_ANNOTATION_LINETYPE_DOUBLEARROW 33844
#define ID_ANNOTATION_LINETYPE_DOUBLEFILLEDARROY 33845
#define ID_ANNOTATION_OBJECT_WHITEOUT2  33846
#define ID_ANNOTATION_OBJECT_HILITE2    33847
#define ID_ANNOTATION_OBJECT_NOTE2      33848
#define ID_ANNOTATION_OBJECT_LINE2      33849
#define ID_ANNOTATION_OBJECT_RECTANGLE2 33850
#define ID_ANNOTATION_SELECT            33851
#define ID_ANNOTATION_OBJECT_ELLIPSE2   33852
#define ID_ANNOTATION_SAVEANNOTATION    33853
#define ID_ANNOTATION_OBJECT_STAMP2     33854
#define ID_VIEW_ANNOTATIONTOOLBAR       33855
#define ID_ANNOTATION_LOADANNOTATION    33858
#define ID_ANNOTATION_BURNIN            33862
#define IDS_LOADFROMTAG                 57610
#define IDS_SAVETAG                     57611
#define ID_INDICATOR_IMAGENO            59142
#define ID_INDICATOR_IMAGETOTAL         59143
#define IDS_WARNING                     61216

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        174
#define _APS_NEXT_COMMAND_VALUE         32889
#define _APS_NEXT_CONTROL_VALUE         240
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
