CREATE OR REPLACE FUNCTION "NHS_LIS_OTLOGINST"
(V_OTLID IN VARCHAR2)

 RETURN TYPES.CURSOR_TYPE AS
  OUTCUR TYPES.CURSOR_TYPE;
BEGIN
  OPEN OUTCUR FOR
    SELECT '', U.OTCID, C.OTCDESC,U.OLUCMT, U.OLUID, U.OTLID
      FROM OT_LOG_INST U, OT_CODE C
     WHERE U.OTCID = C.OTCID
       AND U.OTLID = V_OTLID;
  RETURN OUTCUR;

END NHS_LIS_OTLOGINST;
/
