CREATE OR REPLACE FUNCTION "NHS_ACT_OTLOGIMPL" (
	v_ACTION IN VARCHAR2,
	v_OTCID  IN VARCHAR2,
	v_OLICMT IN VARCHAR2,
	v_OLIID  IN VARCHAR2,
	v_OTLID  IN VARCHAR2,
	o_ERRMSG OUT VARCHAR2
)
  	RETURN NUMBER
AS
	o_ERRCODE NUMBER;
	v_NEWID   NUMBER;
	v_NOOFREC NUMBER;
BEGIN
  	o_ERRCODE := 0;
  	o_ERRMSG  := 'OK';

	IF v_ACTION = 'DEL' THEN
		DELETE FROM OT_LOG_IMPL WHERE OLIID = v_OLIID;
	ELSIF v_ACTION = 'DEL_OTLID' THEN
		DELETE FROM OT_LOG_IMPL WHERE OTLID = v_OTLID;
	ELSE
		SELECT COUNT(1) INTO v_NOOFREC FROM OT_LOG_IMPL WHERE OLIID = v_OLIID;

  	  	-- INSERT/UPDATE
	  	IF v_NOOFREC = 0 THEN
	    		SELECT SEQ_OT_LOG_IMPL.NEXTVAL INTO v_NEWID FROM DUAL;
	    		INSERT INTO OT_LOG_IMPL (
	    			OLIID,
				OTLID,
				OTCID,
				OLICMT
	    		) VALUES (
	    			v_NEWID,
	    			TO_NUMBER(v_OTLID),
	    			TO_NUMBER(v_OTCID),
	    			v_OLICMT
	    		);
	  	ELSIF v_NOOFREC > 0 THEN
	      		UPDATE OT_LOG_IMPL
	         	SET OTCID = TO_NUMBER(v_OTCID), OLICMT = v_OLICMT
	       		WHERE OLIID = TO_NUMBER(v_OLIID)
	         	AND OTLID = TO_NUMBER(v_OTLID);
	  	ELSE
	    		o_ERRCODE := -61;
	    		o_ERRMSG  := 'Fail to update due to record not exist.';
	  	END IF;
  	END IF;
  	RETURN o_ERRCODE;
EXCEPTION
WHEN OTHERS THEN
	ROLLBACK;
	dbms_output.put_line('An ERROR was encountered - '||SQLCODE||' -ERROR- '||SQLERRM);
	o_ERRCODE := -60;
	o_ERRMSG := SQLERRM;
	RETURN o_ERRCODE;
END NHS_ACT_OTLOGIMPL;
/
