CREATE OR REPLACE FUNCTION "NHS_ACT_OTMISCCODETABLE_M_D" (
	v_ACTION IN VARCHAR2,
 	v_OTCID  IN VARCHAR2,
 	O_ERRMSG OUT VARCHAR2
)
	RETURN NUMBER
AS
 	O_ERRCODE NUMBER;
 	v_noOfRec NUMBER;
BEGIN
  	O_ERRCODE := 0;
  	O_Errmsg  := 'OK';

  	SELECT COUNT(1) INTO v_noOfRec FROM OT_CODE WHERE OTCID = v_OTCID;
   	If v_noOfRec > 0 Then
  		delete OT_CODE where OTCID = v_OTCID;
    END IF;

	RETURN O_Errcode;
END NHS_ACT_OTMISCCODETABLE_M_D;
/
