CREATE OR REPLACE FUNCTION "NHS_ACT_OTAPPPROC" (
	v_ACTION  IN VARCHAR2,
	v_OAPID   IN VARCHAR2,
	v_OTAID   IN VARCHAR2,
	v_OTPCODE IN VARCHAR2,
	O_ERRMSG  OUT VARCHAR2
)
	RETURN NUMBER
AS
	O_ERRCODE NUMBER;
	v_NEWID NUMBER;
	v_NOOFREC NUMBER;
	v_OTPID VARCHAR2(22);
BEGIN
	O_ERRCODE := 0;
	O_ERRMSG  := 'OK';

	IF v_ACTION = 'DEL' THEN
		DELETE FROM OT_APP_PROC WHERE OAPID = v_OAPID;
	ELSIF v_ACTION = 'DEL_OTAID' THEN
		DELETE FROM OT_APP_PROC WHERE OTAID = v_OTAID;
	ELSE
		SELECT COUNT(1) INTO v_NOOFREC FROM OT_APP_PROC WHERE OAPID = v_OAPID;
		SELECT OTPID INTO v_OTPID FROM OT_PROC WHERE OTPCODE = v_OTPCODE AND OTPSTS = -1;

		-- INSERT/UPDATE
		IF v_NOOFREC = 0 THEN
			SELECT SEQ_OT_APP_PROC.NEXTVAL INTO v_NEWID FROM DUAL;
			INSERT INTO OT_APP_PROC (
				OAPID,
				OTAID,
				OTPID
			) VALUES (
				v_NEWID,
				TO_NUMBER(v_OTAID),
				TO_NUMBER(v_OTPID)
			);
		ELSIF v_NOOFREC > 0 THEN
			UPDATE OT_APP_PROC
			SET    OTPID = v_OTPID
			WHERE  OAPID = TO_NUMBER(v_OAPID)
			AND    OTAID = TO_NUMBER(v_OTAID);
		ELSE
			O_ERRCODE := -1;
			O_ERRMSG  := 'Fail to update due to record not exist.';
		END IF;
	END IF;

	RETURN O_ERRCODE;
END NHS_ACT_OTAPPPROC;
/
