CREATE OR REPLACE FUNCTION "NHS_LIS_OTLOGIMPL"
(V_OTLID IN VARCHAR2)

 RETURN TYPES.CURSOR_TYPE AS
  OUTCUR TYPES.CURSOR_TYPE;
BEGIN
  OPEN OUTCUR FOR
    SELECT '', I.OTCID, C.OTCDESC, I.OLICMT,I.OLIID,I.OTLID
      FROM OT_LOG_IMPL I, OT_CODE C
     WHERE I.OTCID = C.OTCID
       AND I.OTLID = V_OTLID;
  RETURN OUTCUR;

END NHS_LIS_OTLOGIMPL;
/
