CREATE OR REPLACE FUNCTION "NHS_GET_OTAPPBYNO" (
	v_otaid IN ot_app.otaid%TYPE
)
	RETURN TYPES.cursor_type
AS
	OUTCUR TYPES.cursor_type;
BEGIN
	OPEN OUTCUR FOR
		SELECT
			OA.PATNO,
			OA.OTAFNAME,
			OA.OTAGNAME,
			OA.OTASEX,
			OA.PATTYPE,
			TO_CHAR(OA.OTAOSDATE,'DD/MM/YYYY hh24:mi'),
			TO_CHAR(OA.OTAOEDATE,'DD/MM/YYYY hh24:mi'),
			OA.OTCID_RM,
			OA.OTPID,
			OA.DOCCODE_R,
			OA.OTARMK,
			OA.OTADIAG,
			OA.DOCCODE_S,
			TO_CHAR(OA.OTASNDATE,'DD/MM/YYYY hh24:mi'),
			OA.DOCCODE_A,
			TO_CHAR(OA.OTAANDATE,'DD/MM/YYYY hh24:mi'),
			OA.OTCID_AM,
			OA.DOCCODE_E,
			TO_CHAR(OA.OTAENDATE,'DD/MM/YYYY hh24:mi'),
			OA.OTAPROCRMK,
			OA.PBPID,
			TO_CHAR(OA.OTABDATE,'DD/MM/YYYY'),
			B.BPBSTS,
			B.ISREFUSED,
			(SELECT USRNAME FROM USR WHERE USRID = B.REFUSEDUSERID),
			(SELECT USRNAME FROM USR WHERE USRID = B.ACTIVATEDUSERID),
			OTAHKID,
			OTATEL,
			B.BPBCNAME,
			B.PATPAGER,
			OAS.DOCCODE,
			TO_CHAR(OAS.OTASNDATE,'DD/MM/YYYY HH24:MI'),
			OTE.FEREQ,
			OTE.FEREC
		FROM OT_APP OA
		LEFT JOIN BEDPREBOK B ON OA.PBPID = B.PBPID
		LEFT JOIN OT_APP_SURG OAS ON OA.OTAID = OAS.OTAID
		LEFT JOIN OT_APP_EXTRA OTE ON OA.OTAID = OTE.OTAID
		WHERE OA.OTAID = V_OTAID;
	RETURN OUTCUR;

END NHS_GET_OTAPPBYNO;
/
