CREATE OR REPLACE FUNCTION "NHS_GET_OTAPP" (
	v_otaid IN ot_app.otaid%TYPE
)
	RETURN TYPES.cursor_type
AS
	OUTCUR TYPES.cursor_type;
BEGIN
     	OPEN OUTCUR FOR
      		SELECT
      			OA.OTAID, OA.PATNO, OA.OTAFNAME, OA.OTAGNAME, OA.OTAHKID, TO_CHAR(OA.OTABDATE,'DD/MM/YYYY hh24:mi'), OA.OTATEL,
         		TO_CHAR(OA.OTAOSDATE,'DD/MM/YYYY hh24:mi'), TO_CHAR(OA.OTAOEDATE,'DD/MM/YYYY hh24:mi'), OA.OTCID_RM, OA.OTPID, OA.OTCID_AM, OA.DOCCODE_S,
         		OA.DOCCODE_A, TO_CHAR(OA.OTASNDATE,'DD/MM/YYYY hh24:mi'), TO_CHAR(OA.OTAANDATE,'DD/MM/YYYY hh24:mi'), OA.OTARMK, OA.OTASTS, TO_CHAR(OA.OTACDATE,'DD/MM/YYYY hh24:mi'),
         		OA.OTUSRID, OA.STECODE, OA.OTASEX, OA.PBPID, OA.PATTYPE, OA.OTAPROCRMK, OA.OTADIAG,
         		OA.DOCCODE_E, TO_CHAR(OA.OTAENDATE,'DD/MM/YYYY hh24:mi'), OA.DOCCODE_R, OA.CANCELRSNCDE, OA.OTACNCLRMK,
			OTE.FEREQ, OTE.FEREC
      		FROM OT_APP OA
      		LEFT JOIN OT_APP_EXTRA OTE ON OA.OTAID = OTE.OTAID
      		WHERE OA.OTAID = V_OTAID;
     	RETURN OUTCUR;
END NHS_GET_OTAPP;
/
