CREATE OR REPLACE FUNCTION "NHS_ACT_OTLOGDRUG" (
	v_ACTION  IN VARCHAR2,
	v_OTCID   IN VARCHAR2,
	v_OLDCOST IN VARCHAR2,
	v_OLDUNIT IN VARCHAR2,
	v_OLDQTY  IN VARCHAR2,
	v_OLDCMT  IN VARCHAR2,
	v_OLDID   IN VARCHAR2,
	v_OTLID   IN VARCHAR2,
	o_ERRMSG  OUT VARCHAR2
)
	RETURN NUMBER
AS
	o_ERRCODE NUMBER;
	v_NEWID NUMBER;
	v_NOOFREC NUMBER;
BEGIN
	o_ERRCODE := 0;
	o_ERRMSG  := 'OK';

	IF v_ACTION = 'DEL' THEN
		DELETE FROM OT_LOG_DRUG WHERE OLDID = v_OLDID;
	ELSIF v_ACTION = 'DEL_OTLID' THEN
		DELETE FROM OT_LOG_DRUG WHERE OTLID = v_OTLID;
	ELSE
		SELECT COUNT(1) INTO v_NOOFREC FROM OT_LOG_DRUG WHERE OLDID = v_OLDID;

		-- INSERT/UPDATE
		IF v_NOOFREC = 0 THEN
			SELECT SEQ_OT_LOG_DRUG.NEXTVAL INTO v_NEWID FROM DUAL;
			INSERT INTO OT_LOG_DRUG (
				OLDID,
				OTLID,
				OTCID,
				OLDCOST,
				OLDUNIT,
				OLDQTY,
				OLDCMT
			) VALUES (
				v_NEWID,
				TO_NUMBER(v_OTLID),
				TO_NUMBER(v_OTCID),
				TO_NUMBER(v_OLDCOST),
				v_OLDUNIT,
				TO_NUMBER(v_OLDQTY),
				v_OLDCMT);
		ELSIF v_NOOFREC > 0 THEN
			UPDATE OT_LOG_DRUG
			SET
				OTCID  =  TO_NUMBER(v_OTCID),
				OLDCOST = TO_NUMBER(v_OLDCOST),
				OLDUNIT = v_OLDUNIT,
				OLDQTY  = TO_NUMBER(v_OLDQTY),
				OLDCMT  = v_OLDCMT
			WHERE OLDID   = TO_NUMBER(v_OLDID)
			AND OTLID   = TO_NUMBER(v_OTLID);
		ELSE
			o_ERRCODE := -91;
			o_ERRMSG  := 'Fail to update due to record not exist.';
		END IF;
	END IF;
	RETURN o_ERRCODE;
EXCEPTION
WHEN OTHERS THEN
	ROLLBACK;
	dbms_output.put_line('An ERROR was encountered - '||SQLCODE||' -ERROR- '||SQLERRM);
	o_ERRCODE := -90;
	o_errmsg := SQLERRM;
	RETURN o_ERRCODE;
END NHS_ACT_OTLOGDRUG;
/
