CREATE OR REPLACE FUNCTION "NHS_LIS_OTLOGTEAMMEB"
(V_OTLID IN VARCHAR2)

  RETURN TYPES.CURSOR_TYPE AS
  OUTCUR TYPES.CURSOR_TYPE;
BEGIN
  OPEN OUTCUR FOR
    SELECT ' ',T.OTCID_SF, C1.OTCDESC, T.OTCID_FN, C2.OTCDESC,T.OLTID, T.OTLID
      FROM OT_LOG_TEAM T, OT_CODE C1, OT_CODE C2
     WHERE T.OTCID_SF = C1.OTCID
       AND T.OTCID_FN = C2.OTCID
       AND OTLID = V_OTLID;
  RETURN OUTCUR;

END NHS_LIS_OTLOGTEAMMEB;
/
