CREATE OR REPLACE FUNCTION "NHS_LST_PROCSTAT" (
	v_TYPE     IN VARCHAR2,
	v_DOCCODE  IN VARCHAR2,
	v_PROCCODE IN VARCHAR2,
	v_ACMCODE  IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
BEGIN
	IF v_DOCCODE IS NOT NULL THEN
		IF v_TYPE = 'ProFeeInput' THEN
			OPEN OUTCUR FOR
				SELECT FEE, COUNT(1), MAX(PERCENTILE)
				FROM (
					SELECT
						SURGEON_FEE AS FEE, ROUND((PERCENT_RANK() OVER (ORDER BY SURGEON_FEE ASC)) * 100) AS PERCENTILE
					FROM   FIN_ESTIMATE
					WHERE  DOCCODE = v_DOCCODE
					AND    CODE IN (SELECT REFCODE FROM FIN_CODE WHERE PROCCODE = v_PROCCODE)
					AND    ACMCODE = v_ACMCODE
				)
				GROUP BY FEE
				ORDER BY FEE;
		ELSIF v_TYPE = 'AnaesthetistFeeInput' THEN
			OPEN OUTCUR FOR
				SELECT FEE, COUNT(1), MAX(PERCENTILE)
				FROM (
					SELECT
						ANAES_FEE AS FEE, ROUND((PERCENT_RANK() OVER (ORDER BY ANAES_FEE ASC)) * 100) AS PERCENTILE
					FROM   FIN_ESTIMATE
					WHERE  DOCCODE = v_DOCCODE
					AND    CODE IN (SELECT REFCODE FROM FIN_CODE WHERE PROCCODE = v_PROCCODE)
					AND    ACMCODE = v_ACMCODE
				)
				GROUP BY FEE
				ORDER BY FEE;
		ELSIF v_TYPE = 'OtherInput2' THEN
			OPEN OUTCUR FOR
				SELECT FEE, COUNT(1), MAX(PERCENTILE)
				FROM (
					SELECT
						DR_FEE AS FEE, ROUND((PERCENT_RANK() OVER (ORDER BY DR_FEE ASC)) * 100) AS PERCENTILE
					FROM   FIN_ESTIMATE
					WHERE  DOCCODE = v_DOCCODE
					AND    CODE IN (SELECT REFCODE FROM FIN_CODE WHERE PROCCODE = v_PROCCODE)
					AND    ACMCODE = v_ACMCODE
				)
				GROUP BY FEE
				ORDER BY FEE;
		ELSIF v_TYPE = 'OTInput' THEN
			OPEN OUTCUR FOR
				SELECT FEE, COUNT(1), MAX(PERCENTILE)
				FROM (
					SELECT
						OT AS FEE, ROUND((PERCENT_RANK() OVER (ORDER BY OT ASC)) * 100) AS PERCENTILE
					FROM   FIN_ESTIMATE
					WHERE  DOCCODE = v_DOCCODE
					AND    CODE IN (SELECT REFCODE FROM FIN_CODE WHERE PROCCODE = v_PROCCODE)
					AND    ACMCODE = v_ACMCODE
				)
				GROUP BY FEE
				ORDER BY FEE;
		ELSIF v_TYPE = 'OtherInput3' THEN
			OPEN OUTCUR FOR
				SELECT FEE, COUNT(1), MAX(PERCENTILE)
				FROM (
					SELECT
						HOSP_FEE - RM - OT - DI - LAB AS FEE, ROUND((PERCENT_RANK() OVER (ORDER BY HOSP_FEE - RM - OT - DI - LAB ASC)) * 100) AS PERCENTILE
					FROM   FIN_ESTIMATE
					WHERE  DOCCODE = v_DOCCODE
					AND    CODE IN (SELECT REFCODE FROM FIN_CODE WHERE PROCCODE = v_PROCCODE)
					AND    ACMCODE = v_ACMCODE
				)
				GROUP BY FEE
				ORDER BY FEE;
		END IF;
	ELSE
		IF v_TYPE = 'ProFeeInput' THEN
			OPEN OUTCUR FOR
				SELECT FEE, COUNT(1), MAX(PERCENTILE)
				FROM (
					SELECT
						SURGEON_FEE AS FEE, ROUND((PERCENT_RANK() OVER (ORDER BY SURGEON_FEE ASC)) * 100) AS PERCENTILE
					FROM   FIN_ESTIMATE
					WHERE  CODE IN (SELECT REFCODE FROM FIN_CODE WHERE PROCCODE = v_PROCCODE)
					AND    ACMCODE = v_ACMCODE
				)
				GROUP BY FEE
				ORDER BY FEE;
		ELSIF v_TYPE = 'AnaesthetistFeeInput' THEN
			OPEN OUTCUR FOR
				SELECT FEE, COUNT(1), MAX(PERCENTILE)
				FROM (
					SELECT
						ANAES_FEE AS FEE, ROUND((PERCENT_RANK() OVER (ORDER BY ANAES_FEE ASC)) * 100) AS PERCENTILE
					FROM   FIN_ESTIMATE
					WHERE  CODE IN (SELECT REFCODE FROM FIN_CODE WHERE PROCCODE = v_PROCCODE)
					AND    ACMCODE = v_ACMCODE
				)
				GROUP BY FEE
				ORDER BY FEE;
		ELSIF v_TYPE = 'OtherInput2' THEN
			OPEN OUTCUR FOR
				SELECT FEE, COUNT(1), MAX(PERCENTILE)
				FROM (
					SELECT
						DR_FEE AS FEE, ROUND((PERCENT_RANK() OVER (ORDER BY DR_FEE ASC)) * 100) AS PERCENTILE
					FROM   FIN_ESTIMATE
					WHERE  CODE IN (SELECT REFCODE FROM FIN_CODE WHERE PROCCODE = v_PROCCODE)
					AND    ACMCODE = v_ACMCODE
				)
				GROUP BY FEE
				ORDER BY FEE;
		ELSIF v_TYPE = 'OTInput' THEN
			OPEN OUTCUR FOR
				SELECT FEE, COUNT(1), MAX(PERCENTILE)
				FROM (
					SELECT
						OT AS FEE, ROUND((PERCENT_RANK() OVER (ORDER BY OT ASC)) * 100) AS PERCENTILE
					FROM   FIN_ESTIMATE
					WHERE  CODE IN (SELECT REFCODE FROM FIN_CODE WHERE PROCCODE = v_PROCCODE)
					AND    ACMCODE = v_ACMCODE
				)
				GROUP BY FEE
				ORDER BY FEE;
		ELSIF v_TYPE = 'OtherInput3' THEN
			OPEN OUTCUR FOR
				SELECT FEE, COUNT(1), MAX(PERCENTILE)
				FROM (
					SELECT
						HOSP_FEE - RM - OT - DI - LAB AS FEE, ROUND((PERCENT_RANK() OVER (ORDER BY HOSP_FEE - RM - OT - DI - LAB ASC)) * 100) AS PERCENTILE
					FROM   FIN_ESTIMATE
					WHERE  CODE IN (SELECT REFCODE FROM FIN_CODE WHERE PROCCODE = v_PROCCODE)
					AND    ACMCODE = v_ACMCODE
				)
				GROUP BY FEE
				ORDER BY FEE;
		END IF;
	END IF;

	RETURN OUTCUR;
END NHS_LST_PROCSTAT;
/
