CREATE OR REPLACE
FUNCTION "NHS_GET_ARCODEBYACODE"(
  V_ARCCODE IN VARCHAR2, 
  V_PREARCCODE IN VARCHAR2,
  V_PBPID IN VARCHAR2
)
  RETURN TYPES.CURSOR_TYPE AS
  OUTCUR TYPES.CURSOR_TYPE;
BEGIN
  IF V_PREARCCODE IS NULL THEN
    OPEN OUTCUR FOR
      SELECT COPAYTYP,
             COPAYAMT,
             ARLMTAMT,
             TO_CHAR(CVREDATE,'DD/MM/YYYY'),
             ITMTYPED,
             ITMTYPEH,
             ITMTYPES,
             ITMTYPEO,
             FURGRTAMT,
             TO_CHAR(FURGRTDATE,'DD/MM/YYYY'),
             ARCNAME
        FROM ARCODE
       WHERE ARCCODE = V_ARCCODE;
    RETURN OUTCUR;
  ELSE
    IF V_ARCCODE <> V_PREARCCODE THEN
      OPEN OUTCUR FOR
        SELECT COPAYTYP,
               COPAYAMT,
               ARLMTAMT,
               TO_CHAR(CVREDATE,'DD/MM/YYYY'),
               ITMTYPED,
               ITMTYPEH,
               ITMTYPES,
               ITMTYPEO,
               FURGRTAMT,
               TO_CHAR(FURGRTDATE,'DD/MM/YYYY'),
               ARCNAME
          FROM ARCODE
         WHERE ARCCODE = V_ARCCODE;
      RETURN OUTCUR;
    ELSE
      OPEN OUTCUR FOR
        SELECT COPAYTYP, COPAYAMT, ARLMTAMT, TO_CHAR(CVREDATE,'DD/MM/YYYY'),
                ISDOCTOR, ISHOSPITAL, ISSPECIAL, ISOTHER
        FROM BEDPREBOK
        WHERE PBPID = V_PBPID;
      RETURN OUTCUR;
    END IF;
  END IF;
END;
/