CREATE OR REPLACE FUNCTION "NHS_LIS_OTLOGMETH"
(V_OTLID IN VARCHAR2)

  RETURN TYPES.CURSOR_TYPE AS
  OUTCUR TYPES.CURSOR_TYPE;
BEGIN
  OPEN OUTCUR FOR
  SELECT '',M.OLMID,M.OTLID,M.OTCID,C.OTCDESC
    FROM OT_CODE C, OT_LOG_METH M
   WHERE M.OTCID = C.OTCID
     AND M.OTLID = V_OTLID;
  RETURN OUTCUR;

END NHS_LIS_OTLOGMETH;
/
