CREATE OR REPLACE FUNCTION "NHS_LIS_OTLOGDRUG"
(V_OTLID IN VARCHAR2)

 RETURN TYPES.CURSOR_TYPE AS
  OUTCUR TYPES.CURSOR_TYPE;
BEGIN
  OPEN OUTCUR FOR
    SELECT '', D.OTCID, C.OTCDESC,D.OLDCOST,D.OLDUNIT,D.OLDQTY,D.OLDCMT, D.OLDID,D.OTLID
      FROM OT_LOG_DRUG D, OT_CODE C
     WHERE D.OTCID = C.OTCID
       AND D.OTLID = V_OTLID;
  RETURN OUTCUR;

END NHS_LIS_OTLOGDRUG;
/
