CREATE OR REPLACE FUNCTION "NHS_LIS_OTLOGANES"
(V_OTLID IN VARCHAR2)

  RETURN TYPES.CURSOR_TYPE AS
  OUTCUR TYPES.CURSOR_TYPE;
BEGIN
  OPEN OUTCUR FOR
    SELECT '',
           A.OLAID,
           A.OTLID,
           D.DOCFNAME || ' ' || D.DOCGNAME,
           --A.DOCCODE,
           A.DOCCODE
      FROM OT_LOG_ANES A, DOCTOR D
     WHERE A.DOCCODE = D.DOCCODE
       AND A.OTLID = V_OTLID;
  RETURN OUTCUR;

END NHS_LIS_OTLOGANES;
/
