CREATE OR REPLACE FUNCTION "NHS_LIS_OTLOGEQUI"
(V_OTLID IN VARCHAR2)

 RETURN TYPES.CURSOR_TYPE AS
  OUTCUR TYPES.CURSOR_TYPE;
BEGIN
  OPEN OUTCUR FOR
    SELECT '', E.OTCID, C.OTCDESC, E.OLECMT, E.OLEID, E.OTLID
      FROM OT_LOG_EQUI E, OT_CODE C
     WHERE E.OTCID = C.OTCID
       AND E.OTLID = TO_NUMBER(V_OTLID);
  RETURN OUTCUR;

END NHS_LIS_OTLOGEQUI;
/
