CREATE OR REPLACE FUNCTION "NHS_GET_PROCRANGE" (
	i_PROCCODE IN VARCHAR2,
	i_ACMCODE IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
BEGIN
	OPEN OUTCUR FOR
		SELECT
			LOS, COUNT(1)
		FROM FIN_ESTIMATE
		WHERE  CODE IN (SELECT REFCODE FROM FIN_CODE WHERE PROCCODE = i_PROCCODE)
		AND    ACMCODE = i_ACMCODE
		GROUP BY LOS
		ORDER BY LOS;
	RETURN OUTCUR;
END NHS_GET_PROCRANGE;
/
