CREATE OR REPLACE FUNCTION "NHS_LIS_OTAPPBSE" (
	v_OTAOSDATE  IN VARCHAR2,
	v_OTAOEDATE  IN VARCHAR2,
	v_OTASTS     IN VARCHAR2,
	v_PATNO      IN VARCHAR2,
	v_OTAFNAME   IN VARCHAR2,
	v_OTCID      IN VARCHAR2,
	v_OTPID      IN VARCHAR2,
	v_DOCCODE_S  IN VARCHAR2,
	v_DOCCODE_SS IN VARCHAR2,
	v_DOCCODE_A  IN VARCHAR2,
	v_DOCCODE_E  IN VARCHAR2,
	v_SORTER     IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	SQLSTR VARCHAR2(2000);
	OUTCUR TYPES.CURSOR_TYPE;
BEGIN
	SQLSTR := '
		SELECT A.OTAID,
			'''' AS ALLERGY,
			DECODE(A.PATTYPE,''D'',A.PATTYPE,'''') AS PATTYPE,
			TO_CHAR(A.OTAOSDATE, ''DD/MM/YYYY HH24:MI''),
			TO_CHAR(A.OTAOEDATE, ''DD/MM/YYYY HH24:MI''),
			DECODE(PAT.PMCID, NULL, NULL, 0, NULL, ''M'') AS MERGED,
			A.PATNO,
			A.OTAFNAME,
			A.OTAGNAME,
			A.OTAFNAME || '' '' || A.OTAGNAME AS PATNAME,
			TRUNC(MONTHS_BETWEEN(SYSDATE, A.OTABDATE) / 12) AS AGE,
			C.OTCDESC AS OTPDESC_RM,
			P.OTPDESC,
			SD.DOCFNAME || '' '' || SD.DOCGNAME AS SDRNAME,
			TO_CHAR(A.OTASNDATE, ''DD/MM/YYYY HH24:MI''),
			(SELECT D.DOCFNAME || '' '' || D.DOCGNAME  FROM DOCTOR D WHERE OAS.DOCCODE = D.DOCCODE) AS SECSDRNAME,
			TO_CHAR(OAS.OTASNDATE,''DD/MM/YYYY HH24:MI'') AS SECSDREDATE,
			AD.DOCFNAME || '' '' || AD.DOCGNAME AS ADRNAME,
			TO_CHAR(A.OTAANDATE, ''dd/mm/yyyy hh24:mi''),
			ED.DOCFNAME || '' '' || ED.DOCGNAME AS EDRNAME,
			TO_CHAR(A.OTAENDATE, ''DD/MM/YYYY HH24:MI''),
			DECODE(A.OTASTS, ''N'', ''Normal'', ''F'', ''Confirmed'', ''C'', ''Cancel'') AS STATUS,
			A.OTARMK,
			U.USRNAME,
			A.OTASTS,
			TO_CHAR(E.SMSSDT , ''DD/MM/YYYY HH24:MI''),
			TO_CHAR(E.SMSSDTOK , ''DD/MM/YYYY HH24:MI''),
			E.SMSRTNMSG
		FROM OT_APP  A,
			OT_APP_SURG OAS,
			OT_PROC P,
			DOCTOR  SD,
			DOCTOR  AD,
			DOCTOR  ED,
			USR     U,
			OT_CODE C,
			PATIENT PAT,
			OT_APP_EXTRA E
		WHERE A.OTPID = P.OTPID
		AND A.OTAID = OAS.OTAID(+)
		AND A.DOCCODE_S = SD.DOCCODE(+)
		AND A.DOCCODE_A = AD.DOCCODE
		AND A.DOCCODE_E = ED.DOCCODE(+)
		AND A.OTUSRID = U.USRID
		AND A.OTCID_RM = C.OTCID
		AND A.PATNO = PAT.PATNO(+)
		AND C.OTCTYPE = ''RM''
    	AND A.OTAID = E.OTAID(+) ';

	IF v_OTAOSDATE IS NOT NULL THEN
		SQLSTR:=SQLSTR ||' AND TRUNC(A.OTAOSDATE, ''mi'') >= TO_DATE(''' || v_OTAOSDATE || ''', ''DD/MM/YYYY HH24:MI'')';
	END IF;

	IF v_OTAOEDATE IS NOT NULL THEN
		SQLSTR:=SQLSTR ||' AND TRUNC(A.OTAOSDATE, ''mi'') <= TO_DATE(''' || v_OTAOEDATE || ''', ''DD/MM/YYYY HH24:MI'') ';
	END IF;

	IF v_OTASTS IS NOT NULL THEN
		SQLSTR := SQLSTR || ' AND A.OTASTS = ''' || v_OTASTS || '''';
	END IF;

	IF v_PATNO IS NOT NULL THEN
		SQLSTR := SQLSTR || ' AND A.PATNO = ''' || v_PATNO || '''';
	END IF;

	IF v_OTAFNAME IS NOT NULL THEN
		SQLSTR := SQLSTR || ' AND A.OTAFNAME || '' '' || A.OTAGNAME LIKE ''' || v_OTAFNAME||'%''';
	END IF;

	IF v_OTCID IS NOT NULL THEN
		SQLSTR := SQLSTR || ' AND C.OTCID = ''' || v_OTCID || '''';
	END IF;

	IF v_OTPID IS NOT NULL THEN
		SQLSTR := SQLSTR || ' AND P.OTPID = '||v_OTPID;
	END IF;

	IF v_DOCCODE_S IS NOT NULL THEN
		SQLSTR := SQLSTR || ' AND A.DOCCODE_S = ''' || v_DOCCODE_S || '''';
	END IF;

	IF v_DOCCODE_SS IS NOT NULL THEN
		SQLSTR := SQLSTR || ' AND OAS.DOCCODE = ''' || v_DOCCODE_SS || '''';
	END IF;

	IF v_DOCCODE_A IS NOT NULL THEN
		SQLSTR := SQLSTR || ' AND A.DOCCODE_A = ''' || v_DOCCODE_A || '''';
	END IF;

	IF v_DOCCODE_E IS NOT NULL THEN
		SQLSTR := SQLSTR || ' AND A.DOCCODE_E = ''' || v_DOCCODE_E || '''';
	END IF;

	If V_Sorter Is Not Null Then
	    If V_Sorter = 'DAYCASE' Then
	      Sqlstr := Sqlstr || ' AND A.PATTYPE = ''D'' ';
	      Sqlstr := Sqlstr || ' ORDER BY A.OTAOSDATE ';
	    ELSE
	      Sqlstr := Sqlstr || ' ORDER BY '||V_Sorter;
	    END IF;
	END IF;

	OPEN OUTCUR FOR SQLSTR;
	RETURN OUTCUR;
END NHS_LIS_OTAPPBSE;
/
