create or replace
FUNCTION "NHS_LIS_OTAPPPROC_OTLOG" (
	v_OTAID IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
BEGIN
  	OPEN OUTCUR FOR
  		SELECT '', '', '', P.OTPID, P2.OTPDESC || ' ' || P2.OTPCODE, P2.OTPCODE
    	FROM   OT_APP_PROC P, OT_PROC P2
   		WHERE  P.OTPID = P2.OTPID
     	AND    P.OTAID = v_OTAID;
  	RETURN OUTCUR;

END NHS_LIS_OTAPPPROC_OTLOG;
/
