CREATE OR REPLACE FUNCTION "NHS_LIS_DVATABLELIST" (
	v_STDSTART IN VARCHAR2,
	v_SITECODE IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
BEGIN
	OPEN OUTCUR FOR
		SELECT A.OTAID, A.OTASTS, TO_CHAR(A.OTAOSDATE,'dd/mm/yyyy hh24:mi'),
				TO_CHAR(A.OTAOEDATE,'dd/mm/yyyy hh24:mi'), C.OTCID, C.OTCDESC,
				C.OTCORD, DECODE(A.DOCCODE_E, NULL, D.DOCFNAME || ' ' || D.DOCGNAME,DS.DOCFNAME || ' ' || DS.DOCGNAME) AS DOCNAME,
				P.OTPSFORM
		FROM  OT_PROC P, OT_APP A, OT_CODE C, DOCTOR D, DOCTOR DS
		WHERE A.OTPID = P.OTPID
		AND   A.OTCID_RM = C.OTCID
		AND   A.DOCCODE_S = D.DOCCODE(+)
		AND   A.DOCCODE_E = DS.DOCCODE(+)
		AND   C.OTCSTS  = -1
		AND   C.OTCTYPE = 'RM'
		AND   (A.OTASTS = 'N' OR A.OTASTS = 'F')
		AND   TRUNC(A.OTAOSDATE) <= TO_DATE(v_STDSTART, 'dd/mm/yyyy')
		AND   TRUNC(A.OTAOEDATE) >= TO_DATE(v_STDSTART, 'dd/mm/yyyy')
		AND   A.STECODE = v_SITECODE
		ORDER BY C.OTCORD, A.OTAOSDATE;
  RETURN OUTCUR;
END NHS_LIS_DVATABLELIST;
/
