CREATE OR REPLACE FUNCTION "NHS_LIS_OTLOGSUR"
(V_OTLID IN VARCHAR2)

  RETURN TYPES.CURSOR_TYPE AS
  OUTCUR TYPES.CURSOR_TYPE;
BEGIN
  OPEN OUTCUR FOR
  SELECT '',S.OLSID,S.OTLID,D.DOCFNAME ||' '|| D.DOCGNAME,S.DOCCODE
    FROM  OT_LOG_SURG S,DOCTOR D
   WHERE S.DOCCODE = D.DOCCODE
     AND S.OTLID = V_OTLID;
  RETURN OUTCUR;

END NHS_LIS_OTLOGSUR;
/
