CREATE OR REPLACE FUNCTION "NHS_GET_PROCFEE" (
	i_DOCCODE  IN VARCHAR2,
	i_PROCCODE IN VARCHAR2,
	i_DAY      IN VARCHAR2,
	i_ACMCODE  IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
	v_ACMCODE ACM.ACMCODE%TYPE;
	v_Count NUMBER;
	v_RMMinT NUMBER;
	v_RMMaxT NUMBER;
	v_OTChargesMinT NUMBER;
	v_OTChargesMaxT NUMBER;
	v_OtherFeeMinT NUMBER;
	v_OtherFeeMaxT NUMBER;
	v_DocMinP NUMBER;
	v_DocMaxP NUMBER;
	v_SurgicalMinP NUMBER;
	v_SurgicalMaxP NUMBER;
	v_AnaestheistMinP NUMBER;
	v_AnaestheistMaxP NUMBER;
	v_ConsultationMinP NUMBER;
	v_ConsultationMaxP NUMBER;
	v_OtherDocFeeMinP NUMBER;
	v_OtherDocFeeMaxP NUMBER;
	v_RMMinP NUMBER;
	v_RMMaxP NUMBER;
	v_OTChargesMinP NUMBER;
	v_OTChargesMaxP NUMBER;
	v_OtherFeeMinP NUMBER;
	v_OtherFeeMaxP NUMBER;
	v_SurgeonFeeMin NUMBER;
	v_SurgeonFeeMax NUMBER;
	v_SurgeonFeeAvg NUMBER;
	v_SurgeonFeeMedian NUMBER;
	v_AnaesFeeMin NUMBER;
	v_AnaesFeeMax NUMBER;
	v_AnaesFeeAvg NUMBER;
	v_AnaesFeeMedian NUMBER;
	v_DrFeeMin NUMBER;
	v_DrFeeMax NUMBER;
	v_DrFeeAvg NUMBER;
	v_DrFeeMedian NUMBER;
	v_RmMin NUMBER;
	v_RmMax NUMBER;
	v_RmAvg NUMBER;
	v_RmMedian NUMBER;
	v_OtMin NUMBER;
	v_OtMax NUMBER;
	v_OtAvg NUMBER;
	v_OtMedian NUMBER;
	v_HospFeeMin NUMBER;
	v_HospFeeMax NUMBER;
	v_HospFeeAvg NUMBER;
	v_HospFeeMedian NUMBER;
	v_TotalMin NUMBER;
	v_TotalMax NUMBER;
	v_TotalAvg NUMBER;
	v_TotalMedian NUMBER;
BEGIN
	IF i_ACMCODE = 'K' THEN
		v_ACMCODE := 'L';
	ELSE
		v_ACMCODE := i_ACMCODE;
	END IF;

	-- hospital
	-- column 2
	SELECT COUNT(1) INTO v_Count FROM FIN_PACKAGE WHERE PROCCODE = i_PROCCODE AND ACMCODE = v_ACMCODE AND (LOS = -1 OR LOS = i_DAY) AND CHGTYPE = 'RM_2';
	IF v_Count = 1 THEN
		SELECT CHGAMTFROM, CHGAMTTO INTO v_RMMinP, v_RMMaxP FROM FIN_PACKAGE WHERE PROCCODE = i_PROCCODE AND ACMCODE = v_ACMCODE AND (LOS = -1 OR LOS = i_DAY) AND CHGTYPE = 'RM_2';
	END IF;

	SELECT COUNT(1) INTO v_Count FROM FIN_PACKAGE WHERE PROCCODE = i_PROCCODE AND ACMCODE = v_ACMCODE AND (LOS = -1 OR LOS = i_DAY) AND CHGTYPE = 'OT_2';
	IF v_Count = 1 THEN
		SELECT CHGAMTFROM, CHGAMTTO INTO v_OTChargesMinP, v_OTChargesMaxP FROM FIN_PACKAGE WHERE PROCCODE = i_PROCCODE AND ACMCODE = v_ACMCODE AND (LOS = -1 OR LOS = i_DAY) AND CHGTYPE = 'OT_2';
	END IF;

	SELECT COUNT(1) INTO v_Count FROM FIN_PACKAGE WHERE PROCCODE = i_PROCCODE AND ACMCODE = v_ACMCODE AND (LOS = -1 OR LOS = i_DAY) AND CHGTYPE = 'OH_2';
	IF v_Count = 1 THEN
		SELECT CHGAMTFROM, CHGAMTTO INTO v_OtherFeeMinP, v_OtherFeeMaxP FROM FIN_PACKAGE WHERE PROCCODE = i_PROCCODE AND ACMCODE = v_ACMCODE AND (LOS = -1 OR LOS = i_DAY) AND CHGTYPE = 'OH_2';
	END IF;

	-- column 1
	SELECT COUNT(1) INTO v_Count FROM FIN_PACKAGE WHERE PROCCODE = i_PROCCODE AND ACMCODE = v_ACMCODE AND (LOS = -1 OR LOS = i_DAY) AND CHGTYPE = 'RM_1';
	IF v_Count = 1 THEN
		SELECT CHGAMTFROM, CHGAMTTO INTO v_RMMinT, v_RMMaxT FROM FIN_PACKAGE WHERE PROCCODE = i_PROCCODE AND ACMCODE = v_ACMCODE AND (LOS = -1 OR LOS = i_DAY) AND CHGTYPE = 'RM_1';
	END IF;

	SELECT COUNT(1) INTO v_Count FROM FIN_PACKAGE WHERE PROCCODE = i_PROCCODE AND ACMCODE = v_ACMCODE AND (LOS = -1 OR LOS = i_DAY) AND CHGTYPE = 'OT_1';
	IF v_Count = 1 THEN
		SELECT CHGAMTFROM, CHGAMTTO INTO v_OTChargesMinT, v_OTChargesMaxT FROM FIN_PACKAGE WHERE PROCCODE = i_PROCCODE AND ACMCODE = v_ACMCODE AND (LOS = -1 OR LOS = i_DAY) AND CHGTYPE = 'OT_1';
	END IF;

	SELECT COUNT(1) INTO v_Count FROM FIN_PACKAGE WHERE PROCCODE = i_PROCCODE AND ACMCODE = v_ACMCODE AND (LOS = -1 OR LOS = i_DAY) AND CHGTYPE = 'OH_1';
	IF v_Count = 1 THEN
		SELECT CHGAMTFROM, CHGAMTTO INTO v_OtherFeeMinT, v_OtherFeeMaxT FROM FIN_PACKAGE WHERE PROCCODE = i_PROCCODE AND ACMCODE = v_ACMCODE AND (LOS = -1 OR LOS = i_DAY) AND CHGTYPE = 'OH_1';
	END IF;

	-- doctor
	SELECT COUNT(1) INTO v_Count FROM FIN_PACKAGE WHERE PROCCODE = i_PROCCODE AND ACMCODE = v_ACMCODE AND DOCCODE = 'ALL' AND (LOS = -1 OR LOS = i_DAY) AND CHGTYPE = 'DR_1';
	IF v_Count = 1 THEN
		SELECT CHGAMTFROM, CHGAMTTO INTO v_DocMinP, v_DocMaxP FROM FIN_PACKAGE WHERE PROCCODE = i_PROCCODE AND ACMCODE = v_ACMCODE AND DOCCODE = 'ALL' AND (LOS = -1 OR LOS = i_DAY) AND CHGTYPE = 'DR_1';
	END IF;

	SELECT COUNT(1) INTO v_Count FROM FIN_PACKAGE WHERE PROCCODE = i_PROCCODE AND ACMCODE = v_ACMCODE AND DOCCODE = 'ALL' AND (LOS = -1 OR LOS = i_DAY) AND CHGTYPE = 'SG_1';
	IF v_Count = 1 THEN
		SELECT CHGAMTFROM, CHGAMTTO INTO v_SurgicalMinP, v_SurgicalMaxP FROM FIN_PACKAGE WHERE PROCCODE = i_PROCCODE AND ACMCODE = v_ACMCODE AND DOCCODE = 'ALL' AND (LOS = -1 OR LOS = i_DAY) AND CHGTYPE = 'SG_1';
	END IF;

	SELECT COUNT(1) INTO v_Count FROM FIN_PACKAGE WHERE PROCCODE = i_PROCCODE AND ACMCODE = v_ACMCODE AND DOCCODE = 'ALL' AND (LOS = -1 OR LOS = i_DAY) AND CHGTYPE = 'AN_1';
	IF v_Count = 1 THEN
		SELECT CHGAMTFROM, CHGAMTTO INTO v_AnaestheistMinP, v_AnaestheistMaxP FROM FIN_PACKAGE WHERE PROCCODE = i_PROCCODE AND ACMCODE = v_ACMCODE AND DOCCODE = 'ALL' AND (LOS = -1 OR LOS = i_DAY) AND CHGTYPE = 'AN_1';
	END IF;

	SELECT COUNT(1) INTO v_Count FROM FIN_PACKAGE WHERE PROCCODE = i_PROCCODE AND ACMCODE = v_ACMCODE AND DOCCODE = 'ALL' AND (LOS = -1 OR LOS = i_DAY) AND CHGTYPE = 'CF_1';
	IF v_Count = 1 THEN
		SELECT CHGAMTFROM, CHGAMTTO INTO v_ConsultationMinP, v_ConsultationMaxP FROM FIN_PACKAGE WHERE PROCCODE = i_PROCCODE AND ACMCODE = v_ACMCODE AND DOCCODE = 'ALL' AND (LOS = -1 OR LOS = i_DAY) AND CHGTYPE = 'CF_1';
	END IF;

	SELECT COUNT(1) INTO v_Count FROM FIN_PACKAGE WHERE PROCCODE = i_PROCCODE AND ACMCODE = v_ACMCODE AND DOCCODE = 'ALL' AND (LOS = -1 OR LOS = i_DAY) AND CHGTYPE = 'OD_1';
	IF v_Count = 1 THEN
		SELECT CHGAMTFROM, CHGAMTTO INTO v_OtherDocFeeMinP, v_OtherDocFeeMaxP FROM FIN_PACKAGE WHERE PROCCODE = i_PROCCODE AND ACMCODE = v_ACMCODE AND DOCCODE = 'ALL' AND (LOS = -1 OR LOS = i_DAY) AND CHGTYPE = 'OD_1';
	END IF;

--	SELECT COUNT(1) INTO v_Count FROM FIN_ESTIMATE WHERE CODE IN (SELECT REFCODE FROM FIN_CODE WHERE PROCCODE = i_PROCCODE) AND ACMCODE = v_ACMCODE AND LOS = i_DAY;
	SELECT COUNT(1) INTO v_Count FROM FIN_ESTIMATE WHERE CODE IN (SELECT REFCODE FROM FIN_CODE WHERE PROCCODE = i_PROCCODE) AND ACMCODE = v_ACMCODE;
	IF v_Count > 0 THEN
		IF i_DOCCODE IS NOT NULL THEN
			SELECT
				MIN(SURGEON_FEE), MAX(SURGEON_FEE), ROUND(AVG(SURGEON_FEE)), MEDIAN(SURGEON_FEE),
				MIN(ANAES_FEE), MAX(ANAES_FEE), ROUND(AVG(ANAES_FEE)), MEDIAN(ANAES_FEE),
				MIN(DR_FEE), MAX(DR_FEE), ROUND(AVG(DR_FEE)), MEDIAN(DR_FEE),
				MIN(RM), MAX(RM), ROUND(AVG(RM)), MEDIAN(RM),
				MIN(OT), MAX(OT), ROUND(AVG(OT)), MEDIAN(OT),
				MIN(HOSP_FEE - RM - OT), MAX(HOSP_FEE - RM - OT), ROUND(AVG(HOSP_FEE - RM - OT)), MEDIAN(HOSP_FEE - RM - OT),
				MIN(TOTAL), MAX(TOTAL), ROUND(AVG(TOTAL)), MEDIAN(TOTAL)
			INTO
				v_SurgeonFeeMin, v_SurgeonFeeMax, v_SurgeonFeeAvg, v_SurgeonFeeMedian,
				v_AnaesFeeMin, v_AnaesFeeMax, v_AnaesFeeAvg, v_AnaesFeeMedian,
				v_DrFeeMin, v_DrFeeMax, v_DrFeeAvg, v_DrFeeMedian,
				v_RmMin, v_RmMax, v_RmAvg, v_RmMedian,
				v_OtMin, v_OtMax, v_OtAvg, v_OtMedian,
				v_HospFeeMin, v_HospFeeMax, v_HospFeeAvg, v_HospFeeMedian,
				v_TotalMin, v_TotalMax, v_TotalAvg, v_TotalMedian
			FROM   FIN_ESTIMATE
			WHERE  DOCCODE = i_DOCCODE
			AND    CODE IN (SELECT REFCODE FROM FIN_CODE WHERE PROCCODE = i_PROCCODE)
			AND    ACMCODE = v_ACMCODE
			AND   (LOS = i_DAY OR GET_CURRENT_STECODE = 'TWAH');
		ELSE
			SELECT
				MIN(SURGEON_FEE), MAX(SURGEON_FEE), ROUND(AVG(SURGEON_FEE)), MEDIAN(SURGEON_FEE),
				MIN(ANAES_FEE), MAX(ANAES_FEE), ROUND(AVG(ANAES_FEE)), MEDIAN(ANAES_FEE),
				MIN(DR_FEE), MAX(DR_FEE), ROUND(AVG(DR_FEE)), MEDIAN(DR_FEE),
				MIN(RM), MAX(RM), ROUND(AVG(RM)), MEDIAN(RM),
				MIN(OT), MAX(OT), ROUND(AVG(OT)), MEDIAN(OT),
				MIN(HOSP_FEE - RM - OT), MAX(HOSP_FEE - RM - OT), ROUND(AVG(HOSP_FEE - RM - OT)), MEDIAN(HOSP_FEE - RM - OT),
				MIN(TOTAL), MAX(TOTAL), ROUND(AVG(TOTAL)), MEDIAN(TOTAL)
			INTO
				v_SurgeonFeeMin, v_SurgeonFeeMax, v_SurgeonFeeAvg, v_SurgeonFeeMedian,
				v_AnaesFeeMin, v_AnaesFeeMax, v_AnaesFeeAvg, v_AnaesFeeMedian,
				v_DrFeeMin, v_DrFeeMax, v_DrFeeAvg, v_DrFeeMedian,
				v_RmMin, v_RmMax, v_RmAvg, v_RmMedian,
				v_OtMin, v_OtMax, v_OtAvg, v_OtMedian,
				v_HospFeeMin, v_HospFeeMax, v_HospFeeAvg, v_HospFeeMedian,
				v_TotalMin, v_TotalMax, v_TotalAvg, v_TotalMedian
			FROM   FIN_ESTIMATE
			WHERE  CODE IN (SELECT REFCODE FROM FIN_CODE WHERE PROCCODE = i_PROCCODE)
			AND    ACMCODE = v_ACMCODE
			AND   (LOS = i_DAY OR GET_CURRENT_STECODE = 'TWAH');
		END IF;


		-- doctor
		v_DocMinP := null;
		v_DocMaxP := null;
		SELECT COUNT(1) INTO v_Count FROM FIN_PACKAGE WHERE PROCCODE = i_PROCCODE AND ACMCODE = v_ACMCODE AND (DOCCODE = i_DOCCODE OR DOCCODE = 'ALL') AND (LOS = -1 OR LOS = i_DAY) AND CHGTYPE = 'DR_1';
		IF v_Count = 1 THEN
			SELECT CHGAMTFROM, CHGAMTTO INTO v_DocMinP, v_DocMaxP FROM FIN_PACKAGE WHERE PROCCODE = i_PROCCODE AND ACMCODE = v_ACMCODE AND (DOCCODE = i_DOCCODE OR DOCCODE = 'ALL') AND (LOS = -1 OR LOS = i_DAY) AND CHGTYPE = 'DR_1';
		END IF;

		v_SurgicalMinP := null;
		v_SurgicalMaxP := null;
		SELECT COUNT(1) INTO v_Count FROM FIN_PACKAGE WHERE PROCCODE = i_PROCCODE AND ACMCODE = v_ACMCODE AND (DOCCODE = i_DOCCODE OR DOCCODE = 'ALL') AND (LOS = -1 OR LOS = i_DAY) AND CHGTYPE = 'SG_1';
		IF v_Count = 1 THEN
			SELECT CHGAMTFROM, CHGAMTTO INTO v_SurgicalMinP, v_SurgicalMaxP FROM FIN_PACKAGE WHERE PROCCODE = i_PROCCODE AND ACMCODE = v_ACMCODE AND (DOCCODE = i_DOCCODE OR DOCCODE = 'ALL') AND (LOS = -1 OR LOS = i_DAY) AND CHGTYPE = 'SG_1';
		END IF;

		v_AnaestheistMinP := null;
		v_AnaestheistMaxP := null;
		SELECT COUNT(1) INTO v_Count FROM FIN_PACKAGE WHERE PROCCODE = i_PROCCODE AND ACMCODE = v_ACMCODE AND (DOCCODE = i_DOCCODE OR DOCCODE = 'ALL') AND (LOS = -1 OR LOS = i_DAY) AND CHGTYPE = 'AN_1';
		IF v_Count = 1 THEN
			SELECT CHGAMTFROM, CHGAMTTO INTO v_AnaestheistMinP, v_AnaestheistMaxP FROM FIN_PACKAGE WHERE PROCCODE = i_PROCCODE AND ACMCODE = v_ACMCODE AND (DOCCODE = i_DOCCODE OR DOCCODE = 'ALL') AND (LOS = -1 OR LOS = i_DAY) AND CHGTYPE = 'AN_1';
		END IF;

		v_ConsultationMinP := null;
		v_ConsultationMaxP := null;
		SELECT COUNT(1) INTO v_Count FROM FIN_PACKAGE WHERE PROCCODE = i_PROCCODE AND ACMCODE = v_ACMCODE AND (DOCCODE = i_DOCCODE OR DOCCODE = 'ALL') AND (LOS = -1 OR LOS = i_DAY) AND CHGTYPE = 'CF_1';
		IF v_Count = 1 THEN
			SELECT CHGAMTFROM, CHGAMTTO INTO v_ConsultationMinP, v_ConsultationMaxP FROM FIN_PACKAGE WHERE PROCCODE = i_PROCCODE AND ACMCODE = v_ACMCODE AND (DOCCODE = i_DOCCODE OR DOCCODE = 'ALL') AND (LOS = -1 OR LOS = i_DAY) AND CHGTYPE = 'CF_1';
		END IF;

		v_OtherDocFeeMinP := null;
		v_OtherDocFeeMaxP := null;
		SELECT COUNT(1) INTO v_Count FROM FIN_PACKAGE WHERE PROCCODE = i_PROCCODE AND ACMCODE = v_ACMCODE AND (DOCCODE = i_DOCCODE OR DOCCODE = 'ALL') AND (LOS = -1 OR LOS = i_DAY) AND CHGTYPE = 'OD_1';
		IF v_Count = 1 THEN
			SELECT CHGAMTFROM, CHGAMTTO INTO v_OtherDocFeeMinP, v_OtherDocFeeMaxP FROM FIN_PACKAGE WHERE PROCCODE = i_PROCCODE AND ACMCODE = v_ACMCODE AND (DOCCODE = i_DOCCODE OR DOCCODE = 'ALL') AND (LOS = -1 OR LOS = i_DAY) AND CHGTYPE = 'OD_1';
		END IF;
	END IF;

	OPEN OUTCUR FOR
		SELECT
			v_SurgeonFeeMin, v_SurgeonFeeMax, v_SurgeonFeeAvg, v_SurgeonFeeMedian,
			v_AnaesFeeMin, v_AnaesFeeMax, v_AnaesFeeAvg, v_AnaesFeeMedian,
			v_DrFeeMin, v_DrFeeMax, v_DrFeeAvg, v_DrFeeMedian,
			v_RmMin, v_RmMax, v_RmAvg, v_RmMedian,
			v_OtMin, v_OtMax, v_OtAvg, v_OtMedian,	-- 16 ~ 19
			v_HospFeeMin, v_HospFeeMax, v_HospFeeAvg, v_HospFeeMedian,	-- 20 ~ 23
			v_OtMin + v_HospFeeMin, v_OtMax + v_HospFeeMax, v_TotalAvg, v_TotalMedian, -- 24 ~ 27
			v_RMMinT, v_RMMaxT, v_OTChargesMinT, v_OTChargesMaxT, v_OtherFeeMinT, v_OtherFeeMaxT,	-- 28 ~ 33
			v_RMMinP, v_RMMaxP, v_OTChargesMinP, v_OTChargesMaxP, v_OtherFeeMinP, v_OtherFeeMaxP,	-- 34 ~ 39
			v_DocMinP, v_DocMaxP, v_SurgicalMinP, v_SurgicalMaxP, v_AnaestheistMinP, v_AnaestheistMaxP,	-- 40 ~ 45
			v_ConsultationMinP, v_ConsultationMaxP, v_OtherDocFeeMinP, v_OtherDocFeeMaxP	-- 46 ~ 49
		FROM DUAL;

	RETURN OUTCUR;
END NHS_GET_PROCFEE;
/
