CREATE OR REPLACE FUNCTION "NHS_GET_BEDPRECNT"(V_OTAID IN OT_APP.OTAID%TYPE)
RETURN TYPES.CURSOR_TYPE
 AS
  OUTCUR TYPES.CURSOR_TYPE;
BEGIN
  OPEN OUTCUR FOR
    SELECT COUNT(*)
      FROM BEDPREBOK
     WHERE OTAID = V_OTAID
       AND BPBSTS = 'N';
  RETURN OUTCUR;
END NHS_GET_BEDPRECNT;
/
