CREATE OR REPLACE FUNCTION "NHS_LIS_OTLOGBROWSER"(
	v_OTLSDATE  IN VARCHAR2,
	v_OTLEDATE  IN VARCHAR2,
	v_OTLSTS    IN VARCHAR2,
	v_PATNO     IN VARCHAR2,
	v_OTPID     IN NUMBER,
	v_SLPTYPE   IN VARCHAR2,
	v_DOCCODE_S IN VARCHAR2,
	v_DOCCODE_A IN VARCHAR2,
	v_DOCCODE_E IN VARCHAR2,
	v_OR        IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
BEGIN
	OPEN OUTCUR FOR
		SELECT
			'',
			OL.OTLID,
			'' AS ALLERGY,
			TO_CHAR(OL.OTLDATE,'DD/MM/YYYY'),
			TO_CHAR(OL.OTLOSDATE,'HH24:MI'),
			TO_CHAR(OL.OTLOEDATE,'HH24:MI'),
			DECODE(P.PMCID, NULL, NULL, 0, NULL, 'M') AS MERGED,
			(SELECT OC.OTCDESC FROM OT_APP OA, OT_CODE OC WHERE OA.OTAID = OL.OTAID AND OA.OTCID_RM = OC.OTCID AND OC.OTCTYPE = 'RM' AND OC.OTCSTS = -1) AS OP_RM,
			OL.PATNO,
			P.PATFNAME || ' ' || P.PATGNAME AS PATNAME,
			S.SLPTYPE,
			TRUNC(TRUNC(MONTHS_BETWEEN(SYSDATE, P.PATBDATE)) / 12) AS AGE,
			OP.OTPCODE,
			SD.DOCFNAME || ' ' || SD.DOCGNAME AS SNAME,
			AD.DOCFNAME || ' ' || AD.DOCGNAME AS ANAME,
			ED.DOCFNAME || ' ' || ED.DOCGNAME AS ENAME,
			OL.OTLSTS,
			OL.OTLRMK,
			OE.FEREQ,
			OE.FEREC
		FROM
			OT_LOG  OL,
			PATIENT P,
			SLIP    S,
			OT_PROC OP,
			DOCTOR  SD,
			DOCTOR  AD,
			DOCTOR  ED,
			OT_LOG_EXTRA OE
		WHERE OL.PATNO = P.PATNO
		AND   OL.OTPID = OP.OTPID
		AND   OL.DOCCODE_S = SD.DOCCODE (+)
		AND   OL.DOCCODE_A = AD.DOCCODE
		AND   OL.DOCCODE_E = ED.DOCCODE (+)
		AND   OL.OTLID = OE.OTLID (+)
		AND   S.SLPNO = OL.SLPNO
		AND   S.PATNO = OL.PATNO
		AND  (TRUNC(OL.OTLDATE) >= TO_DATE(v_OTLSDATE, 'DD/MM/YYYY') OR v_OTLSDATE Is Null)
		AND  (TRUNC(OL.OTLDATE) <= TO_DATE(v_OTLEDATE, 'DD/MM/YYYY') OR v_OTLEDATE Is Null)
		AND  (OL.OTLSTS = v_OTLSTS OR v_OTLSTS IS NULL)
		AND  (P.PATNO = v_PATNO OR v_PATNO IS NULL)
		AND  (OL.OTPID = v_OTPID OR v_OTPID IS NULL)
		AND  (S.SLPTYPE = v_SLPTYPE OR v_SLPTYPE IS NULL)
		AND  (OL.DOCCODE_S = v_DOCCODE_S OR v_DOCCODE_S IS NULL)
		AND  (OL.DOCCODE_A = v_DOCCODE_A OR v_DOCCODE_A IS NULL)
		AND  (OL.DOCCODE_E = v_DOCCODE_E OR v_DOCCODE_E IS NULL)
		AND  (OL.OTLROOM = v_OR OR v_OR IS NULL)
		ORDER BY OTLOSDATE DESC;

	RETURN OUTCUR;
END NHS_LIS_OTLOGBROWSER;
/
