create or replace
FUNCTION "NHS_LIS_INACTIVEDOCTOR_PREBOK"
RETURN TYPES.CURSOR_TYPE AS
  OUTCUR TYPES.CURSOR_TYPE;
BEGIN

  OPEN OUTCUR FOR
      SELECT DISTINCT *
    FROM (
      SELECT B.PATNO, UPPER(B.PATFNAME || ' ' || B.PATGNAME) AS PATNAME,
             B.BPBCNAME AS PATCNAME, 
             DS.DOCFNAME || ' ' || DS.DOCGNAME || ' (' || DS.DOCCODE || ')' as DOCNAME,
             TO_CHAR(DS.DOCTDATE, 'dd/mm/yyyy hh24:mi:ss'), TO_CHAR(OTA.OTAOSDATE, 'dd/mm/yyyy hh24:mi:ss'), TO_CHAR(B.BPBHDATE, 'dd/mm/yyyy hh24:mi:ss') as HOSDATE, 
             B.WRDCODE, OTP.OTPDESC, B.PATIDNO, TO_CHAR(B.BPBODATE, 'dd/mm/yyyy')as ORDDATE,
             C.USRNAME AS CREATEUSERNAME, TO_CHAR(B.EDITDATE, 'dd/mm/yyyy'), D.USRNAME AS EDITUSERNAME
      FROM BEDPREBOK B LEFT JOIN USR C ON C.USRID = B.USRID
            LEFT JOIN USR D ON D.USRID = B.EDITUSER
            LEFT JOIN PATIENT P ON B.PATNO = P.PATNO
            LEFT JOIN DOCTOR DR ON B.DOCCODE = DR.DOCCODE
            LEFT JOIN OT_APP OTA ON OTA.PBPID = B.PBPID
            LEFT JOIN OT_PROC OTP ON OTP.OTPID = OTA.OTPID
            LEFT JOIN DOCTOR DS ON DS.DOCCODE = OTA.DOCCODE_S
      WHERE TRUNC(DS.DOCTDATE) <= TRUNC(OTA.OTAOSDATE)
      AND B.BPBSTS = 'N'
      AND NVL(B.ISREFUSED, 0) = 0
      AND TRUNC(B.BPBHDATE) >= TRUNC(SYSDATE)
      AND NVL(OTP.OTPDESC, ' ') <> ' '
      UNION ALL
      SELECT B.PATNO, UPPER(B.PATFNAME || ' ' || B.PATGNAME) AS PATNAME,
             B.BPBCNAME AS PATCNAME,
             DA.DOCFNAME || ' ' || DA.DOCGNAME || ' (' || DA.DOCCODE || ')' as DOCNAME,
             TO_CHAR(DA.DOCTDATE, 'dd/mm/yyyy hh24:mi:ss'), TO_CHAR(OTA.OTAOSDATE, 'dd/mm/yyyy hh24:mi:ss'), TO_CHAR(B.BPBHDATE, 'dd/mm/yyyy hh24:mi:ss') as HOSDATE, 
             B.WRDCODE, OTP.OTPDESC, B.PATIDNO, TO_CHAR(B.BPBODATE, 'dd/mm/yyyy')AS ORDDATE,
             C.USRNAME AS CREATEUSERNAME, TO_CHAR(B.EDITDATE, 'dd/mm/yyyy'), D.USRNAME AS EDITUSERNAME
      FROM BEDPREBOK B LEFT JOIN USR C ON C.USRID = B.USRID
            LEFT JOIN USR D ON D.USRID = B.EDITUSER
            LEFT JOIN PATIENT P ON B.PATNO = P.PATNO
            LEFT JOIN DOCTOR DR ON B.DOCCODE = DR.DOCCODE
            LEFT JOIN OT_APP OTA ON OTA.PBPID = B.PBPID
            LEFT JOIN OT_PROC OTP ON OTP.OTPID = OTA.OTPID
            LEFT JOIN DOCTOR DA ON DA.DOCCODE = OTA.DOCCODE_A
      WHERE TRUNC(DA.DOCTDATE) <= TRUNC(OTA.OTAOSDATE)
      AND B.BPBSTS = 'N'
      AND NVL(B.ISREFUSED, 0) = 0
      AND TRUNC(B.BPBHDATE) >= TRUNC(SYSDATE)
      AND NVL(OTP.OTPDESC, ' ') <> ' '
      UNION ALL
      SELECT B.PATNO, UPPER(B.PATFNAME || ' ' || B.PATGNAME) AS PATNAME,
             B.BPBCNAME AS PATCNAME, 
             DE.DOCFNAME || ' ' || DE.DOCGNAME || ' (' || DE.DOCCODE || ')' as DOCNAME,
             TO_CHAR(DE.DOCTDATE, 'dd/mm/yyyy hh24:mi:ss'), TO_CHAR(OTA.OTAOSDATE, 'dd/mm/yyyy hh24:mi:ss'), TO_CHAR(B.BPBHDATE, 'dd/mm/yyyy hh24:mi:ss') as HOSDATE, 
             B.WRDCODE, OTP.OTPDESC, B.PATIDNO, TO_CHAR(B.BPBODATE, 'dd/mm/yyyy')AS ORDDATE,
             C.USRNAME AS CREATEUSERNAME, TO_CHAR(B.EDITDATE, 'dd/mm/yyyy'), D.USRNAME AS EDITUSERNAME
      FROM BEDPREBOK B LEFT JOIN USR C ON C.USRID = B.USRID
            LEFT JOIN USR D ON D.USRID = B.EDITUSER
            LEFT JOIN PATIENT P ON B.PATNO = P.PATNO
            LEFT JOIN DOCTOR DR ON B.DOCCODE = DR.DOCCODE
            LEFT JOIN OT_APP OTA ON OTA.PBPID = B.PBPID
            LEFT JOIN OT_PROC OTP ON OTP.OTPID = OTA.OTPID
            LEFT JOIN DOCTOR DE ON DE.DOCCODE = OTA.DOCCODE_E
      WHERE TRUNC(DE.DOCTDATE) <= TRUNC(OTA.OTAOSDATE)
      AND B.BPBSTS = 'N'
      AND NVL(B.ISREFUSED, 0) = 0
      AND TRUNC(B.BPBHDATE) >= TRUNC(SYSDATE)
      AND NVL(OTP.OTPDESC, ' ') <> ' '
      UNION ALL
      SELECT B.PATNO, UPPER(B.PATFNAME || ' ' || B.PATGNAME) AS PATNAME,
             B.BPBCNAME AS PATCNAME, 
             DR.DOCFNAME || ' ' || DR.DOCGNAME || ' (' || B.DOCCODE || ')' as DOCNAME,
             TO_CHAR(DR.DOCTDATE, 'dd/mm/yyyy hh24:mi:ss'), TO_CHAR(OTA.OTAOSDATE, 'dd/mm/yyyy hh24:mi:ss'), TO_CHAR(B.BPBHDATE, 'dd/mm/yyyy hh24:mi:ss') as HOSDATE, 
             B.WRDCODE, OTP.OTPDESC, B.PATIDNO, TO_CHAR(B.BPBODATE, 'dd/mm/yyyy')AS ORDDATE,
             C.USRNAME AS CREATEUSERNAME, TO_CHAR(B.EDITDATE, 'dd/mm/yyyy'), D.USRNAME AS EDITUSERNAME
      FROM BEDPREBOK B LEFT JOIN USR C ON C.USRID = B.USRID
            LEFT JOIN USR D ON D.USRID = B.EDITUSER
            LEFT JOIN PATIENT P ON B.PATNO = P.PATNO
            LEFT JOIN DOCTOR DR ON B.DOCCODE = DR.DOCCODE
            LEFT JOIN OT_APP OTA ON OTA.PBPID = B.PBPID
            LEFT JOIN OT_PROC OTP ON OTP.OTPID = OTA.OTPID
      WHERE TRUNC(DR.DOCTDATE) <= TRUNC(B.BPBHDATE)
      AND B.BPBSTS = 'N'
      AND NVL(B.ISREFUSED, 0) = 0
      and TRUNC(B.BPBHDATE) >= TRUNC(sysdate)
      and NVL(OTP.OTPDESC, ' ') <> ' ')
      ORDER BY DOCNAME;
  RETURN OUTCUR;
END NHS_LIS_INACTIVEDOCTOR_PREBOK;
/