CREATE OR REPLACE FUNCTION "NHS_ACT_OTLOGTEAMMEB" (
	v_ACTION    IN VARCHAR2,
	v_OTCID_SF  IN VARCHAR2,
	v_OTCID_FN  IN VARCHAR2,
	v_OLTID     IN VARCHAR2,
	v_OTLID     IN VARCHAR2,
	o_ERRMSG    OUT VARCHAR2
)
 	RETURN NUMBER
AS
	o_ERRCODE NUMBER;
	v_NEWID NUMBER;
	v_NOOFREC NUMBER;
BEGIN
  	o_ERRCODE := 0;
  	o_ERRMSG  := 'OK';

	IF v_ACTION = 'DEL' THEN
		DELETE FROM OT_LOG_TEAM WHERE OLTID = v_OLTID;
	ELSIF v_ACTION = 'DEL_OTLID' THEN
		DELETE FROM OT_LOG_TEAM WHERE OTLID = v_OTLID;
	ELSE
		SELECT COUNT(1) INTO v_NOOFREC FROM OT_LOG_TEAM WHERE OLTID = v_OLTID;

		-- INSERT/UPDATE
		IF v_NOOFREC = 0 THEN
			SELECT SEQ_OT_LOG_TEAM.NEXTVAL INTO v_NEWID FROM DUAL;
			INSERT INTO OT_LOG_TEAM (
				OLTID,
				OTLID,
				OTCID_SF,
				OTCID_FN
			) VALUES (
				v_NEWID,
				TO_NUMBER(v_OTLID),
				TO_NUMBER(v_OTCID_SF),
				TO_NUMBER(v_OTCID_FN)
			);
		ELSIF v_NOOFREC > 0 THEN
			UPDATE OT_LOG_TEAM
			SET
				OTCID_SF = TO_NUMBER(v_OTCID_SF),
				OTCID_FN = TO_NUMBER(v_OTCID_FN)
			WHERE OLTID = TO_NUMBER(v_OLTID)
			AND OTLID = TO_NUMBER(v_OTLID);
		ELSE
			o_ERRCODE := -51;
			o_ERRMSG  := 'Fail to update due to record not exist.';
		END IF;
  	END IF;
  	RETURN o_ERRCODE;
EXCEPTION
WHEN OTHERS THEN
	ROLLBACK;
	dbms_output.put_line('An ERROR was encountered - '||SQLCODE||' -ERROR- '||SQLERRM);
	o_ERRCODE := -50;
	o_errmsg := SQLERRM;
	RETURN o_ERRCODE;
END NHS_ACT_OTLOGTEAMMEB;
/
