CREATE OR REPLACE FUNCTION "NHS_LIS_OTLOGPROC"
(V_OTLID IN VARCHAR2)

  RETURN TYPES.CURSOR_TYPE AS
  OUTCUR TYPES.CURSOR_TYPE;
BEGIN
  OPEN OUTCUR FOR
  SELECT '',P.OLPID,P.OTLID,P.OTPID, P2.OTPDESC || ' ' || P2.OTPCODE,
         P2.OTPCODE
    FROM OT_LOG_PROC P, OT_PROC P2
   WHERE P.OTPID = P2.OTPID
     AND P.OTLID = V_OTLID;
  RETURN OUTCUR;

END NHS_LIS_OTLOGPROC;
/
