/****************************************************************************/
/* winflags.h  (c) Copyright Black Ice Software Inc.  1989 - 1993            */
/*                   All Rights Reserved                                    */
/*                   Unpublished and confidential material.                 */
/*                   --- Do not Reproduce or Disclose ---                   */
/****************************************************************************/


#if _MSC_VER >= 800
#pragma warning(disable:4201 4214)
/* 4201: nameless struct/union */
/* 4214: bit field types other then int */
#endif

/* #define STRICT	 in AFX.H   */			
#define WIN32_LEAN_AND_MEAN     1
#define NOSERVICE               1
