alter table labm_bb_product modify (pcode varchar2(8));

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E0009V00', 'Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E0009VA0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E0009VB0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E0009VC0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E0009VD0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E0009VE0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E0009VF0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E0009VG0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E0009VH0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E0009VI0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E0009VJ0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6507V00', 'Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6507VA0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6507VB0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6507VC0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6507VD0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6507VE0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6507VF0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6507VG0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6507VH0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6507VI0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6507VJ0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E0053V00', 'Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E0053VA0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E0053VB0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E0053VC0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E0053VD0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E0053VE0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E0053VF0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E0053VG0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E0053VH0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E0053VI0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E0053VJ0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5128V00', 'Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5128VA0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5128VB0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5128VC0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5128VD0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5128VE0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5128VF0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5128VG0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5128VH0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5128VI0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5128VJ0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E0017V00', 'Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E0017VA0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E0017VB0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E0017VC0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E0017VD0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E0017VE0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E0017VF0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E0017VG0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E0017VH0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E0017VI0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E0017VJ0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7424V00', 'Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7424VA0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7424VB0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7424VC0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7424VD0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7424VE0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7424VF0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7424VG0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7424VH0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7424VI0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7424VJ0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E0061V00', 'Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E0061VA0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E0061VB0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E0061VC0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E0061VD0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E0061VE0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E0061VF0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E0061VG0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E0061VH0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E0061VI0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E0061VJ0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E4209V00', 'Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E4209VA0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E4209VB0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E4209VC0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E4209VD0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E4209VE0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E4209VF0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E4209VG0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E4209VH0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E4209VI0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E4209VJ0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6508V00', 'Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6508VA0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6508VB0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6508VC0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6508VD0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6508VE0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6508VF0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6508VG0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6508VH0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6508VI0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6508VJ0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E4396V00', 'Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E4396VA0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E4396VB0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E4396VC0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E4396VD0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E4396VE0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E4396VF0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E4396VG0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E4396VH0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E4396VI0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E4396VJ0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5356V00', 'Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5356VA0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5356VB0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5356VC0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5356VD0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5356VE0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5356VF0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5356VG0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5356VH0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5356VI0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5356VJ0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5584V00', 'Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5584VA0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5584VB0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5584VC0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5584VD0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5584VE0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5584VF0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5584VG0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5584VH0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5584VI0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5584VJ0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6509V00', 'Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6509VA0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6509VB0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6509VC0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6509VD0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6509VE0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6509VF0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6509VG0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6509VH0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6509VI0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6509VJ0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5064V00', 'Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5064VA0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5064VB0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5064VC0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5064VD0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5064VE0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5064VF0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5064VG0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5064VH0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5064VI0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5064VJ0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5357V00', 'Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5357VA0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5357VB0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5357VC0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5357VD0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5357VE0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5357VF0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5357VG0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5357VH0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5357VI0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5357VJ0', 'Divided Whole Blood');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7425V00', 'Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7425VA0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7425VB0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7425VC0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7425VD0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7425VE0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7425VF0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7425VG0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7425VH0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7425VI0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7425VJ0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6053V00', 'Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6053VA0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6053VB0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6053VC0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6053VD0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6053VE0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6053VF0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6053VG0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6053VH0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6053VI0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6053VJ0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7426V00', 'Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7426VA0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7426VB0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7426VC0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7426VD0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7426VE0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7426VF0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7426VG0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7426VH0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7426VI0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7426VJ0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6467V00', 'Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6467VA0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6467VB0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6467VC0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6467VD0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6467VE0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6467VF0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6467VG0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6467VH0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6467VI0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6467VJ0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7427V00', 'Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7427VA0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7427VB0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7427VC0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7427VD0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7427VE0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7427VF0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7427VG0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7427VH0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7427VI0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7427VJ0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7428V00', 'Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7428VA0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7428VB0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7428VC0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7428VD0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7428VE0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7428VF0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7428VG0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7428VH0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7428VI0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7428VJ0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7429V00', 'Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7429VA0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7429VB0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7429VC0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7429VD0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7429VE0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7429VF0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7429VG0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7429VH0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7429VI0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7429VJ0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7430V00', 'Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7430VA0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7430VB0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7430VC0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7430VD0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7430VE0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7430VF0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7430VG0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7430VH0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7430VI0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7430VJ0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7431V00', 'Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7431VA0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7431VB0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7431VC0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7431VD0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7431VE0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7431VF0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7431VG0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7431VH0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7431VI0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7431VJ0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7432V00', 'Washed Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7432VA0', 'Divided Washed Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7432VB0', 'Divided Washed Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7432VC0', 'Divided Washed Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7432VD0', 'Divided Washed Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7432VE0', 'Divided Washed Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7432VF0', 'Divided Washed Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7432VG0', 'Divided Washed Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7432VH0', 'Divided Washed Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7432VI0', 'Divided Washed Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7432VJ0', 'Divided Washed Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7433V00', 'Washed Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7433VA0', 'Divided Washed Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7433VB0', 'Divided Washed Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7433VC0', 'Divided Washed Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7433VD0', 'Divided Washed Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7433VE0', 'Divided Washed Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7433VF0', 'Divided Washed Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7433VG0', 'Divided Washed Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7433VH0', 'Divided Washed Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7433VI0', 'Divided Washed Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7433VJ0', 'Divided Washed Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7434V00', 'Washed Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7434VA0', 'Divided Washed Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7434VB0', 'Divided Washed Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7434VC0', 'Divided Washed Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7434VD0', 'Divided Washed Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7434VE0', 'Divided Washed Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7434VF0', 'Divided Washed Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7434VG0', 'Divided Washed Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7434VH0', 'Divided Washed Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7434VI0', 'Divided Washed Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7434VJ0', 'Divided Washed Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7435V00', 'Washed Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7435VA0', 'Divided Washed Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7435VB0', 'Divided Washed Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7435VC0', 'Divided Washed Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7435VD0', 'Divided Washed Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7435VE0', 'Divided Washed Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7435VF0', 'Divided Washed Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7435VG0', 'Divided Washed Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7435VH0', 'Divided Washed Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7435VI0', 'Divided Washed Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7435VJ0', 'Divided Washed Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7436V00', 'Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7436VA0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7436VB0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7436VC0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7436VD0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7436VE0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7436VF0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7436VG0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7436VH0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7436VI0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7436VJ0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7437V00', 'Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7437VA0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7437VB0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7437VC0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7437VD0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7437VE0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7437VF0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7437VG0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7437VH0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7437VI0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7437VJ0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7438V00', 'Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7438VA0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7438VB0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7438VC0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7438VD0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7438VE0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7438VF0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7438VG0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7438VH0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7438VI0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7438VJ0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7439V00', 'Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7439VA0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7439VB0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7439VC0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7439VD0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7439VE0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7439VF0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7439VG0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7439VH0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7439VI0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7439VJ0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7440V00', 'Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7440VA0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7440VB0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7440VC0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7440VD0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7440VE0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7440VF0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7440VG0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7440VH0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7440VI0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7440VJ0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7441V00', 'Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7441VA0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7441VB0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7441VC0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7441VD0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7441VE0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7441VF0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7441VG0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7441VH0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7441VI0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7441VJ0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7442V00', 'Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7442VA0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7442VB0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7442VC0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7442VD0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7442VE0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7442VF0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7442VG0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7442VH0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7442VI0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7442VJ0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7443V00', 'Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7443VA0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7443VB0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7443VC0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7443VD0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7443VE0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7443VF0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7443VG0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7443VH0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7443VI0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7443VJ0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7445V00', 'Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7445VA0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7445VB0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7445VC0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7445VD0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7445VE0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7445VF0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7445VG0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7445VH0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7445VI0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7445VJ0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7446V00', 'Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7446VA0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7446VB0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7446VC0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7446VD0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7446VE0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7446VF0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7446VG0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7446VH0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7446VI0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7446VJ0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7447V00', 'Deglycerolized Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7447VA0', 'Divided Deglycerolized Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7447VB0', 'Divided Deglycerolized Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7447VC0', 'Divided Deglycerolized Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7447VD0', 'Divided Deglycerolized Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7447VE0', 'Divided Deglycerolized Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7447VF0', 'Divided Deglycerolized Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7447VG0', 'Divided Deglycerolized Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7447VH0', 'Divided Deglycerolized Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7447VI0', 'Divided Deglycerolized Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7447VJ0', 'Divided Deglycerolized Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7448V00', 'Deglycerolized Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7448VA0', 'Divided Deglycerolized Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7448VB0', 'Divided Deglycerolized Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7448VC0', 'Divided Deglycerolized Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7448VD0', 'Divided Deglycerolized Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7448VE0', 'Divided Deglycerolized Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7448VF0', 'Divided Deglycerolized Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7448VG0', 'Divided Deglycerolized Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7448VH0', 'Divided Deglycerolized Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7448VI0', 'Divided Deglycerolized Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7448VJ0', 'Divided Deglycerolized Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7449V00', 'Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7449VA0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7449VB0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7449VC0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7449VD0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7449VE0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7449VF0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7449VG0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7449VH0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7449VI0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7449VJ0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7450V00', 'Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7450VA0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7450VB0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7450VC0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7450VD0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7450VE0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7450VF0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7450VG0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7450VH0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7450VI0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7450VJ0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7451V00', 'Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7451VA0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7451VB0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7451VC0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7451VD0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7451VE0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7451VF0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7451VG0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7451VH0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7451VI0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7451VJ0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7452V00', 'Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7452VA0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7452VB0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7452VC0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7452VD0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7452VE0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7452VF0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7452VG0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7452VH0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7452VI0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7452VJ0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5358V00', 'Cryoprecipitate');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5358VA0', 'Divided Cryoprecipitate');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5358VB0', 'Divided Cryoprecipitate');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5358VC0', 'Divided Cryoprecipitate');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5358VD0', 'Divided Cryoprecipitate');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5358VE0', 'Divided Cryoprecipitate');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5358VF0', 'Divided Cryoprecipitate');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5358VG0', 'Divided Cryoprecipitate');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5358VH0', 'Divided Cryoprecipitate');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5358VI0', 'Divided Cryoprecipitate');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5358VJ0', 'Divided Cryoprecipitate');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8264V00', 'Cryoprecipitate');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8264VA0', 'Divided Cryoprecipitate');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8264VB0', 'Divided Cryoprecipitate');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8264VC0', 'Divided Cryoprecipitate');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8264VD0', 'Divided Cryoprecipitate');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8264VE0', 'Divided Cryoprecipitate');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8264VF0', 'Divided Cryoprecipitate');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8264VG0', 'Divided Cryoprecipitate');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8264VH0', 'Divided Cryoprecipitate');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8264VI0', 'Divided Cryoprecipitate');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8264VJ0', 'Divided Cryoprecipitate');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2807V00', 'Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2807VA0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2807VB0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2807VC0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2807VD0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2807VE0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2807VF0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2807VG0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2807VH0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2807VI0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2807VJ0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6506V00', 'Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6506VA0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6506VB0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6506VC0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6506VD0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6506VE0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6506VF0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6506VG0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6506VH0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6506VI0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6506VJ0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3093V00', 'Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3093VA0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3093VB0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3093VC0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3093VD0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3093VE0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3093VF0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3093VG0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3093VH0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3093VI0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3093VJ0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2940V00', 'Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2940VA0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2940VB0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2940VC0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2940VD0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2940VE0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2940VF0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2940VG0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2940VH0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2940VI0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2940VJ0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2981V00', 'Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2981VA0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2981VB0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2981VC0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2981VD0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2981VE0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2981VF0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2981VG0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2981VH0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2981VI0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2981VJ0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7454V00', 'Pooled Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5151V00', 'Pooled Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7455V00', 'Pooled Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2823V00', 'Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2823VA0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2823VB0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2823VC0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2823VD0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2823VE0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2823VF0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2823VG0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2823VH0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2823VI0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2823VJ0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7456V00', 'Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7456VA0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7456VB0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7456VC0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7456VD0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7456VE0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7456VF0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7456VG0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7456VH0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7456VI0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7456VJ0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6884V00', 'Pooled Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8259V00', 'Pooled Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3928V00', 'Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3928VA0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3928VB0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3928VC0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3928VD0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3928VE0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3928VF0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3928VG0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3928VH0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3928VI0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3928VJ0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3930V00', 'Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3930VA0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3930VB0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3930VC0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3930VD0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3930VE0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3930VF0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3930VG0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3930VH0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3930VI0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3930VJ0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8257V00', 'Pooled Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8255V00', 'Pooled Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8260V00', 'Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8260VA0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8260VB0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8260VC0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8260VD0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8260VE0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8260VF0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8260VG0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8260VH0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8260VI0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8260VJ0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8262V00', 'Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8262VA0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8262VB0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8262VC0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8262VD0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8262VE0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8262VF0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8262VG0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8262VH0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8262VI0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8262VJ0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E4213V00', 'Apheresis Fresh Frozen Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E4213VA0', 'Divided Apheresis Fresh Frozen Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E4213VB0', 'Divided Apheresis Fresh Frozen Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E4213VC0', 'Divided Apheresis Fresh Frozen Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E4213VD0', 'Divided Apheresis Fresh Frozen Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E4213VE0', 'Divided Apheresis Fresh Frozen Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E4213VF0', 'Divided Apheresis Fresh Frozen Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E4213VG0', 'Divided Apheresis Fresh Frozen Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E4213VH0', 'Divided Apheresis Fresh Frozen Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E4213VI0', 'Divided Apheresis Fresh Frozen Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E4213VJ0', 'Divided Apheresis Fresh Frozen Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5359V00', 'Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5359VA0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5359VB0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5359VC0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5359VD0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5359VE0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5359VF0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5359VG0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5359VH0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5359VI0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5359VJ0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5690V00', 'Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5690VA0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5690VB0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5690VC0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5690VD0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5690VE0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5690VF0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5690VG0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5690VH0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5690VI0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5690VJ0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8261V00', 'Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8261VA0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8261VB0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8261VC0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8261VD0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8261VE0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8261VF0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8261VG0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8261VH0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8261VI0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8261VJ0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7458V00', 'Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7458VA0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7458VB0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7458VC0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7458VD0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7458VE0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7458VF0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7458VG0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7458VH0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7458VI0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7458VJ0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7459V00', 'Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7459VA0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7459VB0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7459VC0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7459VD0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7459VE0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7459VF0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7459VG0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7459VH0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7459VI0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7459VJ0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7460V00', 'Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7460VA0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7460VB0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7460VC0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7460VD0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7460VE0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7460VF0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7460VG0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7460VH0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7460VI0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7460VJ0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7461V00', 'Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7461VA0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7461VB0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7461VC0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7461VD0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7461VE0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7461VF0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7461VG0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7461VH0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7461VI0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7461VJ0', 'Divided Red Blood Cells');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6080V00', 'Leukocytes');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6080VA0', 'Divided Leukocytes');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6080VB0', 'Divided Leukocytes');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6080VC0', 'Divided Leukocytes');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6080VD0', 'Divided Leukocytes');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6080VE0', 'Divided Leukocytes');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6080VF0', 'Divided Leukocytes');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6080VG0', 'Divided Leukocytes');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6080VH0', 'Divided Leukocytes');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6080VI0', 'Divided Leukocytes');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6080VJ0', 'Divided Leukocytes');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7462V00', 'Leukocytes');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7462VA0', 'Divided Leukocytes');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7462VB0', 'Divided Leukocytes');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7462VC0', 'Divided Leukocytes');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7462VD0', 'Divided Leukocytes');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7462VE0', 'Divided Leukocytes');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7462VF0', 'Divided Leukocytes');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7462VG0', 'Divided Leukocytes');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7462VH0', 'Divided Leukocytes');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7462VI0', 'Divided Leukocytes');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7462VJ0', 'Divided Leukocytes');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8268V00', 'Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8268VA0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8268VB0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8268VC0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8268VD0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8268VE0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8268VF0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8268VG0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8268VH0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8268VI0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8268VJ0', 'Divided Plasma');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2982V00', 'Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2982VA0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2982VB0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2982VC0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2982VD0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2982VE0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2982VF0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2982VG0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2982VH0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2982VI0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2982VJ0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2809V00', 'Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2809VA0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2809VB0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2809VC0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2809VD0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2809VE0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2809VF0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2809VG0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2809VH0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2809VI0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2809VJ0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2816V00', 'Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2816VA0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2816VB0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2816VC0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2816VD0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2816VE0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2816VF0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2816VG0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2816VH0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2816VI0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E2816VJ0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3045V00', 'Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3045VA0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3045VB0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3045VC0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3045VD0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3045VE0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3045VF0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3045VG0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3045VH0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3045VI0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3045VJ0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3929V00', 'Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3929VA0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3929VB0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3929VC0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3929VD0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3929VE0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3929VF0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3929VG0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3929VH0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3929VI0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3929VJ0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6249V00', 'Pooled Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6250V00', 'Pooled Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6251V00', 'Pooled Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6252V00', 'Pooled Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6253V00', 'Pooled Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6254V00', 'Pooled Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6255V00', 'Pooled Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6647V00', 'Pooled Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6882V00', 'Pooled Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6883V00', 'Pooled Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6885V00', 'Pooled Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6886V00', 'Pooled Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E6887V00', 'Pooled Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7453V00', 'Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7453VA0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7453VB0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7453VC0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7453VD0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7453VE0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7453VF0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7453VG0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7453VH0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7453VI0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7453VJ0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7457V00', 'Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7457VA0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7457VB0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7457VC0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7457VD0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7457VE0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7457VF0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7457VG0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7457VH0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7457VI0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7457VJ0', 'Divided Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E7864V00', 'Pooled Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8256V00', 'Pooled Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3062V00', 'Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3062VA0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3062VB0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3062VC0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3062VD0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3062VE0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3062VF0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3062VG0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3062VH0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3062VI0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3062VJ0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3931V00', 'Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3931VA0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3931VB0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3931VC0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3931VD0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3931VE0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3931VF0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3931VG0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3931VH0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3931VI0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E3931VJ0', 'Divided Apheresis Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E5996V00', 'Pooled Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION) 
VALUES ('E8258V00', 'Pooled Platelets');

INSERT INTO LABM_BB_PRODUCT (PCODE, DESCRIPTION, SHOW_SEQ) 
VALUES ('E8263V00', 'Plasma', '14');

update labm_bb_product set show_seq = '06' where description like '%Apheresis%' and show_seq is null;
update labm_bb_product set show_seq = '05' where description like '%Cryoprecipitate%' and show_seq is null;
update labm_bb_product set show_seq = '12' where description like '%Deglyceroli%' and show_seq is null;
update labm_bb_product set show_seq = '13' where description like '%Leukocytes%' and show_seq is null;
update labm_bb_product set show_seq = '14' where description like '%Plasma%' and show_seq is null;
update labm_bb_product set show_seq = '03' where description like '%Platelet%' and show_seq is null;
update labm_bb_product set show_seq = '01' where description like 'Red Blood Cell%' and show_seq is null;
update labm_bb_product set show_seq = '01' where description like 'Divided Red Blood Cell%' and show_seq is null;
update labm_bb_product set show_seq = '09' where description like '%Washed Red Blood Cell%' and show_seq is null;
update labm_bb_product set show_seq = '02' where description like '%Whole Blood%' and show_seq is null;

insert into labm_bb_grading (grading, bllodgp, barcode)
values ('09', 'Bombay negative', 'G60');
insert into labm_bb_grading (grading, bllodgp, barcode)
values ('10', 'Bombay positive', 'H60');
insert into labm_bb_grading (grading, bllodgp, barcode)
values ('11', 'O p-Bombay neg', 'I60');
insert into labm_bb_grading (grading, bllodgp, barcode)
values ('12', 'O p-Bombay pos', 'J60');
insert into labm_bb_grading (grading, bllodgp, barcode)
values ('13', 'A p-Bombay neg', 'K60');
insert into labm_bb_grading (grading, bllodgp, barcode)
values ('14', 'B p-Bombay neg', 'L60');
insert into labm_bb_grading (grading, bllodgp, barcode)
values ('15', 'AB p-Bombay neg', 'M60');
insert into labm_bb_grading (grading, bllodgp, barcode)
values ('16', 'A p-Bombay pos', 'N60');
insert into labm_bb_grading (grading, bllodgp, barcode)
values ('17', 'B p-Bombay pos', 'O60');
insert into labm_bb_grading (grading, bllodgp, barcode)
values ('18', 'AB p-Bombay pos', 'Q60');