DROP VIEW PREBOOKING_DETAIL;
COMMIT;

CREATE VIEW PREBOOKING_DETAIL AS
  SELECT PBPID, PATNO, PATFNAME, PATGNAME, PATNAME, PATCNAME, DOCCODE, DOCNAME, SEX, ACMCODE, WRDCODE, HOSDATE, ORDDATE, USRID, BPBRMK,
        BPBSTS, PATIDNO, PATKHTEL, PATPAGER, BPBTYPE, BPBNO, BEDCODE, BEDTIME, OTAOSDATE, OTPDESC, FORDELIVERY, CABLABRMK, SLPNO,
        EDITUSER, EDITDATE, CREATEUSERNAME, EDITUSERNAME, AGE, ISREFUSED, SMSSENTDT, EMAILSENTDT, BPBCNAME, BPBREGTYPE
FROM (
      SELECT B.PBPID, B.PATNO, B.PATFNAME, B.PATGNAME, UPPER(B.PATFNAME || ' ' || B.PATGNAME) AS PATNAME, B.BPBCNAME AS PATCNAME,
              B.DOCCODE, 
              (
                SELECT D.DOCFNAME || ' ' || D.DOCGNAME || ' (' || B.DOCCODE || ')'
                FROM DOCTOR D
                WHERE D.DOCCODE = B.DOCCODE
              ) AS DOCNAME, B.SEX, B.ACMCODE, B.WRDCODE, B.BPBHDATE AS HOSDATE, B.BPBODATE AS ORDDATE, B.USRID, B.BPBRMK,
              DECODE(B.BPBSTS, 'D', 'C', 'N', 'N') AS BPBSTS, B.PATIDNO, B.PATKHTEL, B.PATPAGER, B.BPBTYPE, B.BPBNO,
              B.BEDCODE, B.BEDTIME, 
              (
                SELECT MIN(A.OTAOSDATE)
                FROM OT_APP A
                WHERE A.PBPID = B.PBPID
              ) AS OTAOSDATE, 
              (
                SELECT P.OTPDESC
                FROM OT_PROC P
                WHERE P.OTPID = (
                      SELECT MIN(OTPID)
                      FROM OT_APP X
                      WHERE X.PBPID = B.PBPID
                      AND X.OTAOSDATE = (
                            SELECT MIN(A.OTAOSDATE)
                            FROM OT_APP A
                            WHERE A.PBPID = B.PBPID
                          )
                    )
              ) AS OTPDESC, B.FORDELIVERY, B.CABLABRMK, B.SLPNO, B.EDITUSER, B.EDITDATE,
              C.USRNAME AS CREATEUSERNAME, D.USRNAME AS EDITUSERNAME,
              TRUNC(MONTHS_BETWEEN(SYSDATE, NVL(P.PATBDATE, (SELECT OTABDATE FROM OT_APP WHERE PBPID = B.PBPID AND ROWNUM = 1)))/12, 0) AS AGE,
              B.ISREFUSED, B.SMSSENTDT, B.EMAILSENTDT, B.BPBCNAME, BE.BPBREGTYPE
      FROM	BEDPREBOK B LEFT JOIN
            USR C ON C.USRID = B.USRID LEFT JOIN
            USR D ON D.USRID = B.EDITUSER LEFT JOIN           
            PATIENT P ON B.PATNO = P.PATNO LEFT JOIN
            BEDPREBOK_EXTRA BE ON B.PBPID = BE.PBPID
)
WHERE BPBSTS = 'N';
/