DROP VIEW PREBOOKING_DUPNAME;
COMMIT;

CREATE VIEW PREBOOKING_DUPNAME AS
SELECT ID.PBPID AS PBPID_WITHPATNO, NOID.PBPID AS PBPID_WITHOUTPATNO
FROM (
		SELECT PBPID, PATNO, PATIDNO, UPPER(PATFNAME) AS PATFNAME, UPPER(PATGNAME) AS PATGNAME, SUBSTR(UPPER(PATGNAME), 1, DECODE(ROUND(LENGTH(UPPER(PATGNAME)) * 15 / 100), 0, 1, ROUND(LENGTH(UPPER(PATGNAME)) * 15 / 100))) AS CHKGANME
		FROM BEDPREBOK
		WHERE BPBSTS = 'N' 
		AND TRUNC(BPBHDATE) BETWEEN TRUNC(SYSDATE) AND TRUNC(SYSDATE) + (SELECT DECODE(TO_NUMBER(PARAM1), NULL, 1, 0, 1, TO_NUMBER(PARAM1)) FROM SYSPARAM WHERE PARCDE = 'DUPBPDAY')
		AND PATNO IS NOT NULL
		AND PATIDNO IS NOT NULL
		ORDER BY PATFNAME, PATGNAME
	) ID, 
	(
		SELECT PBPID, PATNO, PATIDNO, UPPER(PATFNAME) AS PATFNAME, UPPER(PATGNAME) AS PATGNAME, SUBSTR(UPPER(PATGNAME), 1, DECODE(ROUND(LENGTH(UPPER(PATGNAME)) * 15 / 100), 0, 1, ROUND(LENGTH(UPPER(PATGNAME)) * 15 / 100))) AS CHKGANME
		FROM BEDPREBOK
		WHERE BPBSTS = 'N' 
		AND TRUNC(BPBHDATE) BETWEEN TRUNC(SYSDATE) AND TRUNC(SYSDATE) + (SELECT DECODE(TO_NUMBER(PARAM1), NULL, 1, 0, 1, TO_NUMBER(PARAM1)) FROM SYSPARAM WHERE PARCDE = 'DUPBPDAY')
		AND PATNO IS NULL
		AND PATIDNO IS NULL
		ORDER BY PATFNAME, PATGNAME
	) NOID
WHERE ID.PATFNAME = NOID.PATFNAME
AND ID.CHKGANME = NOID.CHKGANME(+);