DROP VIEW SLIPTX_STATEMENT_CHGRLVL;
COMMIT;

CREATE OR REPLACE FORCE VIEW SLIPTX_STATEMENT_CHGRLVL ("STNDESC1", "STNDESC", "UNIT", "STNTYPE", "ITMTYPE", "STNRLVL", "STNID", "ITMCODE", "PKGCODE", "STNSEQ", "SLPNO", "STNSTS", "DSCCODE", "GLCCODE", "STNNAMT", "STNBAMT", "STNTDATE")
AS
  SELECT STX.STNDESC1,
    STX.STNDESC,
    STX.UNIT,
    STX.STNTYPE,
    STX.ITMTYPE,
    NHS_GET_ARCSLPRLVL(S.ARCCODE,S.SLPTYPE,STX.STNRLVL,STX.DSCCODE,STX.PKGCODE) AS STNRLVL,
    STX.STNID,
    STX.ITMCODE,
    STX.PKGCODE,
    STX.STNSEQ,
    STX.SLPNO,
	    STX.STNSTS,
	    STX.DSCCODE,
    STX.GLCCODE,
    STX.STNNAMT,
    STX.STNBAMT,
    STX.STNTDATE
  FROM SLIPTX STX,
    SLIP S
  WHERE STX.SLPNO = S.SLPNO
  AND STX.STNSTS IN ('N', 'A');
/