CREATE OR REPLACE FUNCTION "NHS_LIS_LOCATION"
(V_LOCCODE LOCATION.LOCCODE%TYPE,
v_LOCNAME LOCATION.LOCNAME%TYPE,
v_DSTCODE LOCATION.DSTCODE%TYPE)
  RETURN Types.cursor_type
AS
  outcur types.cursor_type;
BEGIN
  OPEN outcur FOR
      SELECT
        L.LOCCODE, L.LOCNAME, L.DSTCODE, D.DSTNAME, L.STECODE
      FROM LOCATION L, DISTRICT D
      WHERE ( LOCCODE LIKE '%' || v_LOCCODE || '%')
      AND ( L.LOCNAME like '%' || v_LOCNAME || '%')
      AND ( L.DSTCODE like '%' || v_DSTCODE || '%')
      AND L.DSTCODE=D.DSTCODE(+)
      AND ROWNUM < 100
      ORDER BY L.LOCCODE;
   RETURN OUTCUR;
END NHS_LIS_LOCATION;
/


