CREATE OR REPLACE FUNCTION "NHS_LIS_MEDRECLOC"
(V_MRLID MEDRECLOC.MRLID%TYPE,
v_MRLDESC MEDRECLOC.MRLDESC%TYPE)
  RETURN Types.cursor_type
AS
  outcur types.cursor_type;
BEGIN
  OPEN outcur FOR
      SELECT
        L.MRLID, L.MRLDESC,L.STECODE
      FROM MEDRECLOC L
      WHERE ( MRLID LIKE '%' || v_MRLID || '%')
      AND ( L.MRLDESC like '%' || v_MRLDESC || '%')
      ORDER BY L.MRLID;
   RETURN OUTCUR;
END NHS_LIS_MEDRECLOC;
/


