CREATE OR REPLACE FUNCTION "NHS_LIS_SPECIALTY"
(V_SPCCODE SPEC.SPCCODE%TYPE,
v_SPCNAME SPEC.SPCNAME%TYPE)
  RETURN Types.cursor_type
AS
  outcur types.cursor_type;
BEGIN
  OPEN outcur FOR

    SELECT
        SPCCODE, SPCNAME
    FROM SPEC
    WHERE ( SPCCODE LIKE '%' || v_SPCCODE || '%')
    AND (SPCNAME like '%' || V_SPCNAME || '%')
    AND ROWNUM < 100
    ORDER BY SPCCODE;
  RETURN OUTCUR;
END NHS_LIS_SPECIALTY;
/


