CREATE OR REPLACE FUNCTION "NHS_LIS_DOCTOR_DEPT"
(V_DOCCODE DOCDPTLINK.DOCCODE%TYPE)
    RETURN tYPES.CURSOR_TYPE
AS
    OUTCUR types.CURSOR_TYPE;
BEGIN
   OPEN OUTCUR FOR
    SELECT
       --K.DDLID, K.DOCCODE,
       K.DPTCODE, t.dptname, t.dptcname, K.DDLID
    FROM DOCDPTLINK K , DEPT T
    WHERE k.dptcode= t.dptcode(+)
    AND v_doccode=K.DOCCODE
    ORDER BY K.DPTCODE;
    RETURN OUTCUR;
END NHS_LIS_DOCTOR_DEPT;
/


