CREATE OR REPLACE FUNCTION "NHS_LIS_RELIGIOUS"
(V_RELCODE RELIGIOUS.RELCODE%TYPE,
v_RELDESC RELIGIOUS.RELDESC%TYPE)
  RETURN Types.CURSOR_type
AS
  outcur types.cursor_type;
BEGIN
  OPEN OUTCUR FOR
      SELECT
        RELCODE, RELDESC
      FROM RELIGIOUS
      WHERE ( RELCODE LIKE '%' || v_RELCODE || '%')
      AND ( RELDESC like '%' || v_RELDESC || '%')
     -- AND ROWNUM < 100
      ORDER BY RELCODE;
   RETURN OUTCUR;
END NHS_LIS_RELIGIOUS;
/


