CREATE OR REPLACE FUNCTION "NHS_ACT_CARDTX" (
	v_action   IN VARCHAR2,
	v_CTNID    IN CARDTX.CTNID%TYPE,
	v_CTNSTS   IN CARDTX.CTNSTS%TYPE,
	v_CTNTAMT  IN CARDTX.CTNTAMT%TYPE,
	v_CSHCODE  IN CARDTX.CSHCODE%TYPE,
	v_CTNTYPE  IN CARDTX.CTNTYPE%TYPE,
	v_CTNREF   IN CARDTX.CTNREF%TYPE,
	v_CTNAMT   IN CARDTX.CTNAMT%TYPE,
	v_CTNTIPS  IN CARDTX.CTNTIPS%TYPE,
	v_CTNRSPC  IN CARDTX.CTNRSPC%TYPE,
	v_CTNRSPD  IN CARDTX.CTNRSPD%TYPE,
	v_CTNTIME  IN CARDTX.CTNID%TYPE,
	v_CTNCTYPE IN CARDTX.CTNCTYPE%TYPE,
	v_CTNCNO   IN CARDTX.CTNCNO%TYPE,
	v_CTNEXP   IN CARDTX.CTNEXP%TYPE,
	v_CTNHOLD  IN CARDTX.CTNHOLD%TYPE,
	v_CTNTID   IN CARDTX.CTNTID%TYPE,
	v_CTNMID   IN CARDTX.CTNMID%TYPE,
	v_CTNTRACE IN CARDTX.CTNTRACE%TYPE,
	v_CTNBATCH IN CARDTX.CTNID%TYPE,
	v_CTNACODE IN CARDTX.CTNACODE%TYPE,
	v_CTNRRN   IN CARDTX.CTNID%TYPE,
	v_CTNSNO   IN CARDTX.CTNSNO%TYPE,
	v_CTNVDATE IN CARDTX.CTNVDATE%TYPE,
	v_CTNDACC  IN CARDTX.CTNDACC %TYPE,
	v_CTNARESP IN CARDTX.CTNARESP%TYPE,
	v_CTNSCNT  IN CARDTX.CTNSCNT%TYPE,
	v_CTNSAMT  IN CARDTX.CTNSAMT%TYPE,
	v_CTNRCNT  IN CARDTX.CTNRCNT%TYPE,
	v_CTNRAMT  IN CARDTX.CTNRAMT%TYPE,
	v_REFNO    IN CARDTX.REFNO%TYPE,
	o_errmsg   OUT VARCHAR2
)
	RETURN NUMBER
AS
	O_ERRCODE NUMBER;
	v_noOfRec NUMBER;
BEGIN
	o_errcode := 0;
	o_errmsg := 'OK';

	SELECT count(1) INTO v_noOfRec FROM CARDTX WHERE CTNID = v_CTNID;

	IF v_action = 'ADD' THEN
		IF v_noOfRec = 0 THEN
			INSERT INTO CARDTX (
				CTNID, CTNSTS, CTNTAMT, CTNTDATE, CSHCODE,
				CTNTYPE, CTNREF, CTNAMT, CTNTIPS,CTNRSPC,
				CTNRSPD, CTNTIME, CTNCTYPE, CTNCNO, CTNEXP,
				CTNHOLD, CTNTID, CTNMID, CTNTRACE, CTNBATCH,
				CTNACODE, CTNRRN, CTNSNO, CTNVDATE, CTNDACC,
				CTNARESP, CTNSCNT, CTNSAMT, CTNRCNT, CTNRAMT, STECODE,
				REFNO
			) VALUES (
				v_CTNID, v_CTNSTS, v_CTNTAMT, SYSDATE, v_CSHCODE,
				v_CTNTYPE, v_CTNREF, v_CTNAMT, v_CTNTIPS,v_CTNRSPC,
				v_CTNRSPD, v_CTNTIME, TRIM(v_CTNCTYPE), v_CTNCNO, v_CTNEXP,
				v_CTNHOLD, v_CTNTID, v_CTNMID, v_CTNTRACE, v_CTNBATCH,
				v_CTNACODE, v_CTNRRN, v_CTNSNO, v_CTNVDATE, v_CTNDACC,
				v_CTNARESP, v_CTNSCNT, v_CTNSAMT, v_CTNRCNT, v_CTNRAMT, GET_CURRENT_STECODE,
				v_REFNO
			);
		ELSE
			o_errcode := -1;
			o_errmsg := 'Record already exists.';
		END IF;
	ELSIF v_action = 'MOD' THEN
		IF v_noOfRec > 0 THEN
			UPDATE	CARDTX
			SET
				CTNSTS   = v_CTNSTS,
				CTNTAMT  = v_CTNTAMT,
				CSHCODE  = v_CSHCODE,
				CTNTYPE  = v_CTNTYPE,
				CTNREF   = v_CTNREF,
				CTNAMT   = v_CTNAMT,
				CTNTIPS  = v_CTNTIPS,
				CTNRSPC  = v_CTNRSPC,
				CTNRSPD  = v_CTNRSPD,
				CTNTIME  = v_CTNTIME,
				CTNCTYPE = v_CTNCTYPE,
				CTNCNO   = v_CTNCNO,
				CTNEXP   = v_CTNEXP,
				CTNHOLD  = v_CTNHOLD,
				CTNTID   = v_CTNTID,
				CTNMID   = v_CTNMID,
				CTNTRACE = v_CTNTRACE,
				CTNBATCH = v_CTNBATCH,
				CTNACODE = v_CTNACODE,
				CTNRRN   = v_CTNRRN,
				CTNSNO   = v_CTNSNO,
				CTNVDATE = v_CTNVDATE,
				CTNDACC  = v_CTNDACC,
				CTNARESP = v_CTNARESP,
				CTNSCNT  = v_CTNSCNT,
				CTNSAMT  = v_CTNSAMT,
				CTNRCNT  = v_CTNRCNT,
				CTNRAMT  = v_CTNRAMT,
				REFNO    = v_REFNO
			WHERE CTNID = v_CTNID;
		ELSE
			o_errcode := -1;
			o_errmsg := 'Fail to update due to record not exist.';
		END IF;
	ELSIF v_action = 'DEL' THEN
		IF v_noOfRec > 0 THEN
			DELETE CARDTX WHERE CTNID = v_CTNID;
		ELSE
			o_errcode := -1;
			o_errmsg := 'Fail to delete due to record not exist.';
		END IF;
	END IF;

	return O_ERRCODE;
END NHS_ACT_CARDTX;
/
