create or replace
FUNCTION "NHS_LIS_DOCTOR_PRIVILEGE"(
  V_DOCCODE DOCPRILINK.DOCCODE%TYPE,
  V_ISADMINPAGE IN VARCHAR2
)
    RETURN tYPES.CURSOR_TYPE
AS
    OUTCUR types.CURSOR_TYPE;
BEGIN

  IF V_ISADMINPAGE = 'Y' THEN
    OPEN OUTCUR FOR
       SELECT
          --D.DPLID, D.DOCCODE,
          D.PRICODE, P.PRINAME,
          TO_CHAR(D.DPLSDATE,'DD/MM/YYYY'),
          TO_CHAR(D.DPLTDATE,'DD/MM/YYYY'),
          D.DPLID
       FROM DOCPRILINK D, PRIVILEGE P
       WHERE D.PRICODE=P.PRICODE(+)
       AND v_doccode=D.DOCCODE
       ORDER BY D.PRICODE;
    RETURN OUTCUR;
  ELSE
    OPEN OUTCUR FOR
      SELECT P.PRICODE, P.PRINAME, TO_CHAR(NVL(PL.DPLSDATE, D.DOCSDATE), 'DD/MM/YYYY') SDATE,
              TO_CHAR(NVL(PL.DPLTDATE, DOCTDATE), 'DD/MM/YYYY') TDATE,
              D.DOCFNAME || ' ' || D.DOCGNAME || ' (' ||D.DOCCODE || ')' AS DRNAME,
              TO_CHAR(DOCTDATE, 'DD/MM/YYYY')
      FROM DOCTOR D, DOCPRILINK PL, PRIVILEGE P
      WHERE D.DOCCODE = PL.DOCCODE
      AND PL.PRICODE = P.PRICODE
      AND D.DOCCODE = V_DOCCODE
      ORDER BY PRINAME;
    RETURN OUTCUR;
  END IF;
END NHS_LIS_DOCTOR_PRIVILEGE;
/