CREATE OR REPLACE FUNCTION "NHS_LIS_ACCOUNT_RECEIVABLE" (
	v_ARCCODE ARCODE.ARCCODE%TYPE,
	v_ARCNAME ARCODE.ARCNAME%TYPE
)
	RETURN Types.cursor_type
AS
	outcur Types.cursor_type;
BEGIN
	OPEN outcur FOR

	SELECT
		A.ARCCODE, A.ARCNAME, A.ARCCNAME, A.GLCCODE, A.RETGLCCODE, A.ARCADD1,
		A.ARCADD2, A.ARCADD3, A.ARCTEL, A.FAX, A.EMAIL, A.ARCCT, A.ARCTITLE,
		A.ARCUAMT, A.ARCAMT, A.CPSID, C.CPSCODE,
		A.ARCADMCNAME, A.ADMTTL, A.ADMEMAIL, A.ARCADMCP, A.ARCADMCF,
		DECODE(A.ARCSND, -1, 'Y', 'N'),
		A.FURCCT, A.FURTTL, A.FUREMAIL, A.FURTEL, A.FURFAX,
		A.COPAYTYP, A.ARLMTAMT, TO_CHAR(A.CVREDATE ,'dd/MM/YYYY'), A.COPAYAMT,
		DECODE(A.ITMTYPED, -1, 'Y', 'N'),
		DECODE(A.ITMTYPEH, -1, 'Y', 'N'),
		DECODE(A.ITMTYPES, -1, 'Y', 'N'),
		DECODE(A.ITMTYPEO, -1, 'Y', 'N'),
		TO_CHAR(a.AR_S_DATE, 'dd/MM/YYYY'),
		TO_CHAR(a.AR_E_DATE, 'dd/MM/YYYY'),
		U.USRNAME,
		TO_CHAR(a.ARCUPDDATE, 'dd/MM/YYYY hh24:mi:ss'),
		DECODE(A.AR_ACTIVE, -1, 'Y', 'N'),
		a.ARCPRIMCOMP,
		TO_CHAR(a.NCTRSDATE, 'dd/MM/YYYY'),
		TO_CHAR(A.NCTREDATE, 'dd/MM/YYYY'),
		A.ARCADD4,
		A.PRINT_MRRPT
	FROM  ARCODE A, CONPCESET C, USR U
	WHERE A.CPSID = C.CPSID (+)
	AND   A.ARCUPDUSR = U.USRID (+)
	AND  (v_ARCCODE IS NULL OR A.ARCCODE LIKE '%' || v_ARCCODE || '%')
	AND  (v_ARCNAME IS NULL OR A.ARCNAME LIKE '%' || v_ARCNAME || '%')
	ORDER BY A.ARCCODE ASC;

	RETURN outcur;
END NHS_LIS_Account_Receivable;
/