CREATE OR REPLACE FUNCTION "NHS_LIS_QUALIFICATION"
(V_QLFID QUALIFICATION.QLFID%TYPE,
v_QLFNAME QUALIFICATION.QLFNAME%TYPE)
  RETURN Types.cursor_type
AS
  outcur types.cursor_type;
BEGIN
  OPEN outcur FOR

    SELECT
        QLFID, QLFNAME
    FROM QUALIFICATION
    WHERE ( QLFID LIKE '%' || v_QLFID || '%')
    AND (QLFNAME LIKE '%' || V_QLFNAME || '%')
    AND ROWNUM < 100
    ORDER BY QLFID;
  RETURN OUTCUR;
END NHS_LIS_QUALIFICATION;
/


