CREATE OR REPLACE FUNCTION "NHS_LIS_MOTHERLANG"
(V_MOTHCODE MOTHERLANG.MOTHCODE%TYPE,
v_MOTHDESC MOTHERLANG.MOTHDESC%TYPE)
  RETURN Types.cursor_type
AS
  outcur types.cursor_type;
BEGIN
  OPEN outcur FOR
      SELECT
        MOTHCODE, MOTHDESC
      FROM MOTHERLANG
      WHERE ( MOTHCODE LIKE '%' || v_MOTHCODE || '%')
      AND ( MOTHDESC like '%' || v_MOTHDESC || '%')
      ORDER BY MOTHCODE;
   RETURN OUTCUR;
END NHS_LIS_MOTHERLANG;
/


