CREATE OR REPLACE FUNCTION "NHS_LIS_CALLCHARTPURPOSE"
(
  v_PURPOSE CALLCHARTPURPOSE.PURPOSE%TYPE
)
  RETURN Types.cursor_type
AS
  outcur types.cursor_type;
BEGIN
  OPEN outcur FOR
    SELECT
      SEQ,
      PURPOSE
    FROM CALLCHARTPURPOSE
    WHERE ( PURPOSE LIKE '%' || v_PURPOSE || '%')
    AND ROWNUM < 100
    ORDER BY PURPOSE;
  RETURN OUTCUR;
END NHS_LIS_CALLCHARTPURPOSE;
/


