CREATE OR REPLACE FUNCTION "NHS_LIS_PRIVILEGE"
(V_PRICODE PRIVILEGE.PRICODE%TYPE,
v_PRINAME PRIVILEGE.PRINAME%TYPE)
  RETURN Types.cursor_type
AS
  outcur types.cursor_type;
BEGIN
  OPEN outcur FOR

    SELECT
        PRICODE, PRINAME
    FROM PRIVILEGE
    WHERE ( PRICODE LIKE '%' || v_PRICODE || '%')
    AND (PRINAME like '%' || V_PRINAME || '%')
    AND ROWNUM < 100
    ORDER BY PRICODE;
  RETURN OUTCUR;
END NHS_LIS_PRIVILEGE;
/


