create or replace
function "NHS_LIS_DOCTOR_APPROVAL"
(V_DOCCODE DOCAPVLINK.DOCCODE%TYPE)
    RETURN tYPES.CURSOR_TYPE
AS
    OUTCUR types.CURSOR_TYPE;
BEGIN
   open OUTCUR for
    select CMTNAME, ACTNO,  TO_CHAR(APVDATE,'DD/MM/YYYY') , DALID
    from DOCAPVLINK 
    WHERE  DOCCODE=V_DOCCODE
    order by apvdate desc;
  RETURN OUTCUR;
END NHS_LIS_DOCTOR_APPROVAL;
/