CREATE OR REPLACE FUNCTION "NHS_LIS_DEPTSERVICE"
(V_DSCCODE DPSERV.DSCCODE%TYPE,
v_DSCDESC DPSERV.DSCDESC%TYPE)
  RETURN Types.cursor_type
AS
  outcur types.cursor_type;
BEGIN
  OPEN outcur FOR
      SELECT
        DSCCODE, DSCDESC, DSCCDESC
      FROM DPSERV
      WHERE ( DSCCODE LIKE '%' || v_DSCCODE || '%')
      AND ( DSCDESC like '%' || v_DSCDESC || '%')
      AND ROWNUM < 100
      ORDER BY DSCCODE;
   RETURN OUTCUR;
END NHS_LIS_DEPTSERVICE;
/


