CREATE OR REPLACE FUNCTION "NHS_LIS_CASHIER"
(V_CSHCODE CASHIER.CSHCODE%TYPE,
 V_USRID CASHIER.USRID%TYPE)
  RETURN Types.cursor_type
AS
  outcur types.cursor_type;
BEGIN
  OPEN outcur FOR
      SELECT
        CSHCODE,
        CSHSTS,
        USRID,CSHMAC,
        TO_CHAR(CSHODATE,'DD/MM/YYYY HH24:MI:SS'),
        TO_CHAR(CSHFDATE,'DD/MM/YYYY HH24:MI:SS'),
        CSHRCNT,CSHVCNT
      FROM CASHIER
      WHERE ( USRID LIKE '%' || v_USRID || '%')
      AND ( CSHCODE LIKE '%' || v_CSHCODE || '%')
      ORDER BY USRID;
   RETURN OUTCUR;
END NHS_LIS_CASHIER;
/


