create or replace
FUNCTION "NHS_LIS_ROOM"
(
  V_ROMCODE     ROOM.ROMCODE%TYPE,
  V_ROMSEX      ROOM.ROMSEX%TYPE,
  V_WRDCODE     ROOM.WRDCODE%TYPE,
  V_ACMCODE     ROOM.ACMCODE%TYPE
)
  RETURN Types.cursor_type
AS
  outcur types.cursor_type;
BEGIN
  OPEN outcur FOR
      SELECT
        R.ROMCODE, R.ROMSEX, R.WRDCODE,
        WA.WRDNAME, R.ACMCODE, AC.ACMNAME, R.STECODE
      FROM ROOM R, WARD WA, ACM AC
      WHERE R.WRDCODE=WA.WRDCODE
      AND R.ACMCODE=AC.ACMCODE
      AND ( 
            (V_ROMCODE IS NULL OR UPPER(R.ROMCODE) LIKE '%' || V_ROMCODE || '%')
            AND (V_ROMSEX IS NULL OR UPPER(R.ROMSEX) LIKE '%' || V_ROMSEX || '%')
            AND (V_WRDCODE IS NULL OR UPPER(R.WRDCODE) LIKE '%' || V_WRDCODE || '%')
            AND (V_ACMCODE IS NULL OR UPPER(R.ACMCODE) LIKE '%' || V_ACMCODE || '%')
          )
      --AND ROWNUM < 100
      ORDER BY R.ROMCODE;
   RETURN OUTCUR;
END NHS_LIS_ROOM;
/