CREATE OR REPLACE FUNCTION "NHS_GET_LOCATION"
(V_LOCCODE LOCATION.LOCCODE%TYPE)
  RETURN Types.cursor_type
AS
  outcur types.cursor_type;
BEGIN
  OPEN outcur FOR
      SELECT L.LOCCODE, L.LOCNAME, L.DSTCODE, D.DSTNAME, L.STECODE
      FROM   LOCATION L, DISTRICT D
      WHERE  LOCCODE = v_LOCCODE
      AND    L.DSTCODE = D.DSTCODE(+)
      ORDER BY L.LOCCODE;
   RETURN OUTCUR;
END NHS_GET_LOCATION;
/


