CREATE OR REPLACE FUNCTION "NHS_LIS_SUBREASON"
(V_SRSNCODE SREASON.SRSNCODE%TYPE,
  V_SRSNNEW  SREASON.SRSNNEW%TYPE)
  RETURN Types.cursor_type
AS
  outcur types.cursor_type;
BEGIN
  OPEN outcur FOR
    SELECT
      A.SRSNCODE,
      A.SRSNDESC,
      DECODE(A.SRSNNEW,'-1','Y','N'),
      A.SRSNTABNUM,
      A.SRSNROWNUM,
      A.RSNCODE,
      B0.RSNDESC
 FROM SREASON A, REASON B0
 WHERE A.RSNCODE = B0.RSNCODE
 AND (A.SRSNCODE LIKE '%' || V_SRSNCODE || '%')
 AND (A.SRSNNEW = v_SRSNNEW)
 AND ROWNUM <100
 ORDER BY A.SRSNCODE;
  RETURN OUTCUR;
END NHS_LIS_SUBREASON;
/


