create or replace
FUNCTION "NHS_ACT_DOCPCTHIST_D"
(V_ACTION   IN VARCHAR2,
 V_USERID   IN VARCHAR2,
 V_DPHID	IN VARCHAR2,
 O_ERRMSG   OUT VARCHAR2)
RETURN NUMBER AS
	O_ERRCODE    number;
	v_noOfRec NUMBER;
BEGIN
	O_ERRCODE := 0;
	O_ERRMSG  := 'OK';
	select COUNT(1) into V_NOOFREC from DOCPCTHIST where DPHID = V_DPHID;
	IF v_noOfRec > 0 THEN
  		delete DOCPCTHIST where DPHID = V_DPHID;
	END IF;

	RETURN O_ERRCODE;
END NHS_ACT_DOCPCTHIST_D;
/