CREATE OR REPLACE FUNCTION "NHS_LIS_PACKAGE" (
	v_PKGCODE IN VARCHAR2,
	v_PKGNAME IN VARCHAR2,
	v_PKGRLVL IN VARCHAR2,
	v_DPTCODE IN VARCHAR2,
	v_SLPNO   IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	v_SLPTYPE SLIP.SLPTYPE%TYPE;
	v_ACMCODE INPAT.ACMCODE%TYPE;
	v_stntdate DATE := TRUNC(SYSDATE);
	outcur types.cursor_type;
	sqlBuf varchar2(500);
BEGIN
	IF v_SLPNO IS NOT NULL THEN
		SELECT S.SLPTYPE, I.ACMCODE
		INTO   v_SLPTYPE, v_ACMCODE
		FROM   SLIP S, REG R, INPAT I
		WHERE  S.REGID = R.REGID(+)
		AND    R.INPID = I.INPID(+)
		AND    S.SLPNO = v_SLPNO;
	END IF;

	sqlBuf := '
		SELECT P.PKGCODE, P.PKGNAME, P.PKGCNAME, P.DPTCODE, P.PKGRLVL, P.PKGTYPE, P.PKGALERT, SUM(I.ITCAMT1)
		FROM   PACKAGE P
		LEFT JOIN ITEMCHG I ON P.PKGCODE = I.PKGCODE AND ( I.itcsdt IS NULL OR I.itcsdt <= v_stntdate ) AND ( I.itcedt IS NULL OR I.itcedt >= v_stntdate )
		LEFT JOIN ITEM IM ON I.ITMCODE = IM.ITMCODE
		WHERE  1=1 ';

	IF v_SLPTYPE IS NOT NULL THEN
		  sqlBuf := sqlBuf || ' AND I.CPSID IS NULL AND I.ITCTYPE = ''' || v_SLPTYPE || '''';
	END IF;

	IF v_ACMCODE IS NOT NULL THEN
		sqlBuf := sqlBuf || ' AND I.ACMCODE = ''' || v_ACMCODE || '''';
	END IF;

	IF v_PKGCODE IS NOT NULL THEN
		sqlBuf := sqlBuf || ' AND P.PKGCODE LIKE ''' || v_PKGCODE || '%''';
	END IF;

	IF v_PKGNAME IS NOT NULL THEN
		sqlBuf := sqlBuf || ' AND P.PKGNAME LIKE ''' || v_PKGNAME || '%''';
	END IF;

	IF v_PKGRLVL IS NOT NULL THEN
		IF ltrim(v_PKGRLVL,'0123456789') IS NULL THEN -- v_PKGRLVL is one number string
			sqlBuf := sqlBuf || ' AND P.PKGRLVL = ' || TO_NUMBER(v_PKGRLVL);
		END IF;
	END IF;

	IF v_DPTCODE IS NOT NULL AND LENGTH(v_DPTCODE) > 0 THEN
		sqlBuf := sqlBuf || ' AND DptCode = ''' || v_DPTCODE || '''';
	END IF;

	sqlBuf := sqlBuf || ' GROUP BY P.PKGCODE, P.PKGNAME, P.PKGCNAME, P.DPTCODE, P.PKGRLVL, P.PKGTYPE, P.PKGALERT';
	sqlBuf := sqlBuf || ' ORDER BY P.PKGCODE, P.PKGNAME';

	OPEN outcur FOR sqlBuf;
	RETURN OUTCUR;
END NHS_LIS_PACKAGE;
/
