CREATE OR REPLACE FUNCTION "NHS_LIS_BED"
(V_BEDCODE BED.BEDCODE%TYPE)
  RETURN Types.cursor_type
AS
  outcur types.cursor_type;
BEGIN
  OPEN outcur FOR
    SELECT
    BEDCODE,
    DECODE(BEDOFF,'-1','Y','N'),
    BEDDESC,ROMCODE,
	  BEDSTS,
	  TO_CHAR(BEDDDATE,'DD/MM/YYYY'),
	  BEDREMARK,
	  TO_CHAR(BEDRDATE,'DD/MM/YYYY'),
	  STECODE,
	  EXTPHONE
    FROM BED
    WHERE ( BEDCODE LIKE '%' || v_BEDCODE || '%')
    ORDER BY BEDCODE;
  RETURN OUTCUR;
END NHS_LIS_BED;
/


