CREATE OR REPLACE FUNCTION "NHS_LIS_TITLE"
(v_TITDESC TITLE.TITDESC%TYPE)
  RETURN Types.CURSOR_type
AS
  outcur types.cursor_type;
BEGIN
  OPEN OUTCUR FOR
      SELECT
         TITDESC,TITDESC AS TITDESC2
      FROM TITLE
      WHERE ( TITDESC like '%' || v_TITDESC || '%')
      --AND ROWNUM < 100
      ORDER BY TITDESC;
   RETURN OUTCUR;
END NHS_LIS_TITLE;
/
