CREATE OR REPLACE FUNCTION "NHS_LIS_RACE"
(v_RACDESC RACE.RACDESC%TYPE)
  RETURN Types.CURSOR_type
AS
  outcur types.cursor_type;
BEGIN
  OPEN OUTCUR FOR
      SELECT
         RACDESC,RACDESC as RACDESC2
      FROM RACE
      WHERE ( RACDESC like '%' || v_RACDESC || '%')
     -- AND ROWNUM < 100
      ORDER BY RACDESC;
   RETURN OUTCUR;
END NHS_LIS_RACE;
/
