create or replace FUNCTION "NHS_GET_ALLBRKDOWNTOCOLUMN" (
	V_DSCCODE DPSERV.DSCCODE%TYPE,
  V_CHGRPTLVL ARCODE.INP_CHG_RPTLVL%TYPE
)
	RETURN VARCHAR2
IS
	V_RTN NUMBER(1);
BEGIN
  CASE V_DSCCODE
  WHEN 'CL' THEN
    IF INSTR(V_CHGRPTLVL,'CL')>0 THEN
      V_RTN := -1;
    ELSE
      V_RTN := 0;
    END IF;
  WHEN 'OR' THEN
    IF INSTR(V_CHGRPTLVL,'OR')>0 THEN
      V_RTN := -1;
    ELSE
      V_RTN := 0;
    END IF;
  WHEN 'CS' THEN
    IF INSTR(V_CHGRPTLVL,'CS')>0 THEN
      V_RTN := -1;
    ELSE
      V_RTN := 0;
    END IF;
  ELSE
    V_RTN := 0;
  END CASE;

RETURN V_RTN;
END NHS_GET_ALLBRKDOWNTOCOLUMN;
/