CREATE OR REPLACE FUNCTION "NHS_LIS_EDULEVEL"
(v_DESCRIPTION EDULEVEL.DESCRIPTION%TYPE)
  RETURN Types.cursor_type
AS
  outcur types.cursor_type;
BEGIN
  OPEN outcur FOR
      SELECT
       EDUID,
       DESCRIPTION,
       EDUSTS
      FROM EDULEVEL
      WHERE ( DESCRIPTION LIKE '%' || v_DESCRIPTION || '%')
      ORDER BY DESCRIPTION;
   RETURN OUTCUR;
END NHS_LIS_EDULEVEL;
/


