CREATE OR REPLACE FUNCTION "NHS_LIS_DISTRICT"
(V_DSTCODE DISTRICT.DSTCODE%TYPE,
v_DSTNAME DISTRICT.DSTNAME%TYPE)
  RETURN Types.cursor_type
AS
  outcur types.cursor_type;
BEGIN
  OPEN outcur FOR
      SELECT
        DSTCODE, DSTNAME
      FROM DISTRICT
      WHERE ( DSTCODE LIKE '%' || v_DSTCODE || '%')
      AND ( DSTNAME like '%' || v_DSTNAME || '%')
      ORDER BY DSTCODE;
   RETURN OUTCUR;
END NHS_LIS_DISTRICT;
/


