create or replace
FUNCTION "NHS_GET_MSTR_DOCCODE" (
	i_DocCode VARCHAR2
)
RETURN TYPES.CURSOR_TYPE
AS
  OUTCUR TYPES.CURSOR_TYPE;
	V_MSTR_DOCCODE DOCTOR.MSTRDOCCODE%TYPE;
  V_CHKDOCCODE DOCTOR.MSTRDOCCODE%TYPE;
BEGIN

  V_CHKDOCCODE := I_DOCCODE;

  BEGIN
    SELECT MSTRDOCCODE 
    INTO V_MSTR_DOCCODE 
    FROM DOCTOR 
    WHERE DOCCODE = i_DocCode;
  EXCEPTION
  WHEN OTHERS THEN
    V_CHKDOCCODE := NULL;
  END;
  
  WHILE V_MSTR_DOCCODE IS NOT NULL LOOP
    V_CHKDOCCODE := V_MSTR_DOCCODE;
    V_MSTR_DOCCODE := NULL;
    
    BEGIN  
       SELECT MSTRDOCCODE 
       INTO V_MSTR_DOCCODE 
       FROM DOCTOR 
       WHERE DOCCODE = V_CHKDOCCODE;
    EXCEPTION
    WHEN OTHERS THEN
      V_MSTR_DOCCODE := NULL;
    END;          
  END LOOP;
 
  OPEN OUTCUR FOR
  SELECT V_CHKDOCCODE FROM DUAL;
   
  RETURN OUTCUR;
  
END NHS_GET_MSTR_DOCCODE;
/