CREATE OR REPLACE FUNCTION "NHS_LIS_DOCTOR_QUALIFICATION" (
	v_DOCCODE DOCQLFLINK.DOCCODE%TYPE
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
BEGIN
	OPEN OUTCUR FOR
		SELECT
			D.qlfid, q.qlfname || ' ' || q.qlfcname,
			TO_CHAR(d.dqlidate, 'DD/MM/YYYY'), D.DQLID
		FROM  DOCQLFLINK D, qualification Q
		WHERE D.qlfid = q.qlfid
		AND   v_DOCCODE = D.DOCCODE
		AND   q.qlfcname IS NOT NULL
		ORDER BY d.qlfid;
	RETURN OUTCUR;
END NHS_LIS_DOCTOR_QUALIFICATION;
/
