CREATE OR REPLACE FUNCTION "NHS_ACT_DOCPCTHIST" (
	V_ACTION   	IN VARCHAR2,
	V_USERID    IN VARCHAR2,
	V_DOCCODE  	IN DOCPCTHIST.DOCCODE%TYPE,
 	V_TABLE     IN DOCPCTHIST_OBJ_TAB,
 	O_ERRMSG    OUT VARCHAR2
 )

RETURN NUMBER AS
 O_ERRCODE    number;
 v_noOfRec NUMBER;

BEGIN
  O_ERRCODE := 0;
  O_ERRMSG  := 'OK';

  for I in 1..V_TABLE.COUNT LOOP
    select COUNT(1) into V_NOOFREC from DOCPCTHIST where DPHID = V_TABLE(I).DPHID;    
       if V_NOOFREC = 0 then
         INSERT INTO DOCPCTHIST
          (
			DPHID,
			DOCCODE,
			CONSTARTDATE,
			CONENDDATE,
			DOCPCT_I,
			DOCPCT_O,
			DOCPCT_D
          ) values (
            SEQ_DOCPCTHIST.NEXTVAL,
            V_DOCCODE,
            TO_DATE(V_TABLE(I).CONSTARTDATE, 'DD/MM/YYYY'),
            TO_DATE(V_TABLE(I).CONENDDATE, 'DD/MM/YYYY'),
            V_TABLE(I).DOCPCT_I,
            V_TABLE(I).DOCPCT_O,
            V_TABLE(I).DOCPCT_D
          );
      ELSE
      	UPDATE DOCPCTHIST SET
          CONSTARTDATE = TO_DATE(V_TABLE(I).CONSTARTDATE, 'DD/MM/YYYY'),
          CONENDDATE =  TO_DATE(V_TABLE(I).CONENDDATE, 'DD/MM/YYYY'),
          DOCPCT_I =  V_TABLE(I).DOCPCT_I,
          DOCPCT_O =  V_TABLE(I).DOCPCT_O,
          DOCPCT_D =  V_TABLE(I).DOCPCT_D
      	WHERE DPHID = V_TABLE(I).DPHID;
      END IF;
  END LOOP;

  RETURN O_ERRCODE;
END NHS_ACT_DOCPCTHIST;
/
