CREATE OR REPLACE FUNCTION "NHS_GET_PACKAGE"
(V_PKGCODE PACKAGE.PKGCODE%TYPE)
  RETURN Types.cursor_type
AS
  outcur types.cursor_type;
BEGIN
  OPEN outcur FOR
      SELECT
        PKGCODE, PKGNAME
      FROM PACKAGE
      WHERE PKGCODE = v_PKGCODE
      ORDER BY PKGCODE;
   RETURN OUTCUR;
END NHS_GET_PACKAGE;
/


