CREATE OR REPLACE FUNCTION "NHS_LIS_WARD2"
(V_WRDCODE WARD.WRDCODE%TYPE)
  RETURN Types.cursor_type
AS
  outcur types.cursor_type;
BEGIN
  OPEN outcur FOR
      SELECT
        W.WRDCODE, W.WRDNAME, W.DPTCODE, D.DPTNAME, W.STECODE
      FROM WARD W, DEPT D
      WHERE ( WRDCODE LIKE '%' || v_WRDCODE || '%')
     AND W.DPTCODE=D.DPTCODE
 --     AND ROWNUM < 100
      ORDER BY W.WRDCODE;
   RETURN OUTCUR;
END NHS_LIS_WARD2;
/


