CREATE OR REPLACE FUNCTION "NHS_LIS_CARDRATE"
(V_CRANAME CARDRATE.CRANAME%TYPE)
  RETURN Types.cursor_type
AS
  outcur types.cursor_type;
BEGIN
  OPEN outcur FOR
      SELECT
        CRANAME, CRARATE, PAYCODE
      FROM CARDRATE
      WHERE ( CRANAME LIKE '%' || v_CRANAME || '%')
      AND ROWNUM < 100
      ORDER BY CRANAME;
   RETURN OUTCUR;
END NHS_LIS_CARDRATE;
/


