CREATE OR REPLACE FUNCTION "NHS_ACT_BUDGETFEES" (
	V_ACTION IN VARCHAR2,
	V_PARAM  IN VARCHAR2,
	O_ERRMSG OUT VARCHAR2
)
	RETURN NUMBER
AS
	O_ERRCODE NUMBER;
BEGIN
	O_ERRCODE := 0;
	O_ERRMSG  := 'OK';

	DELETE FROM ITEMCHG WHERE CPSID IS NULL;
	INSERT INTO ITEMCHG (
		ITCID,
		ITMCODE,
		PKGCODE,
		ACMCODE,
		ITCTYPE,
		GLCCODE,
		ITCAMT1,
		ITCAMT2,
		STECODE)
	SELECT ITCID,
		ITMCODE,
		PKGCODE,
		ACMCODE,
		ITCTYPE,
		GLCCODE,
		NVL(ITCAMT3, ITCAMT1),
		NVL(ITCAMT4, ITCAMT2),
		STECODE
	FROM BUDGET;

	DELETE FROM CREDITCHG WHERE CPSID IS NULL;
	INSERT INTO CREDITCHG (CICID,
		ITMCODE,
		PKGCODE,
		ACMCODE,
		ITCTYPE,
		GLCCODE,
		ITCAMT1,
		ITCAMT2,
		STECODE)
	SELECT CICID,
		ITMCODE,
		PKGCODE,
		ACMCODE,
		ITCTYPE,
		GLCCODE,
		NVL(ITCAMT3, ITCAMT1),
		NVL(ITCAMT4, ITCAMT2),
		STECODE
	FROM CREDITBGT;

	RETURN O_ERRCODE;
END NHS_ACT_BUDGETFEES;
/
