CREATE OR REPLACE FUNCTION "NHS_LIS_DOCPCTHIST"
(V_DOCCODE DOCTOR.DOCCODE%TYPE)
    RETURN TYPES.CURSOR_TYPE
AS
    OUTCUR TYPES.CURSOR_TYPE;
BEGIN
   OPEN OUTCUR FOR
    SELECT
       DPHID,
       DOCCODE,
       TO_CHAR(CONSTARTDATE, 'DD/MM/YYYY'), 
       TO_CHAR(CONENDDATE, 'DD/MM/YYYY'),
       DOCPCT_I,
       DOCPCT_O,
       DOCPCT_D
    FROM DOCPCTHIST
    WHERE DOCCODE = V_DOCCODE
    ORDER BY DOCCODE, CONSTARTDATE DESC;
    RETURN OUTCUR;
END NHS_LIS_DOCPCTHIST;
/
