ALTER TABLE CMS_PHOTO
 DROP PRIMARY KEY CASCADE;
DROP TABLE CMS_PHOTO CASCADE CONSTRAINTS;

CREATE TABLE CMS_PHOTO
(
 CMSM_ID NUMBER(*,0)  NOT NULL ,
 CMSM_USER_ID VARCHAR2(20 BYTE),
 CMSM_PATNO VARCHAR2(20 BYTE),
 CMSM_REGID VARCHAR2(20 BYTE),
 CMSM_TESTTYPE VARCHAR2(20 BYTE),
 CMSM_IMG_PATH VARCHAR2(100 BYTE),
 CMSM_COMMENT VARCHAR2(200 BYTE),
 CMSM_STECODE VARCHAR2(20 BYTE),
 CMSM_MODULE VARCHAR2(50 BYTE), 
 CMSM_CREATED_DATE DATE DEFAULT SYSDATE,
 CMSM_MODIFIED_DATE DATE DEFAULT SYSDATE,
 PRIMARY KEY (CMSM_ID)
);