CREATE OR REPLACE
TYPE ADDCHARGES_INFO AS OBJECT
( /* TODO enter attribute and method declarations here */
	PKGCODE       VARCHAR2(10 BYTE),
	ITMCODE       VARCHAR2(10 BYTE),
	AMOUNT        VARCHAR2(130 BYTE),
	DOCCODE       VARCHAR2(10 BYTE),
	TXNDATE       VARCHAR2(10 BYTE),
	DESCRITION    VARCHAR2(80 BYTE),
	ACMCODE       VARCHAR2(10 BYTE),
	CPS           VARCHAR2(1 BYTE),
	IREFNO        VARCHAR2(90 BYTE),
	ITMRLVL       VARCHAR2(22 BYTE),
	CPSID         VARCHAR2(22 BYTE),
	PTNOAMT       VARCHAR2(130 BYTE),
	ISPKG         VARCHAR2(1 BYTE)
);
/
