create or replace
TYPE APPT_INFO AS OBJECT
(
  ISCANCEL        VARCHAR2(10 BYTE),
  APPT_DATE       VARCHAR2(10 BYTE),
  REMARK          VARCHAR2(500 BYTE),
  UPDATED_USER    VARCHAR2(100 BYTE),
  UPDATED_DATE    VARCHAR2(10 BYTE),
  SEQNO           VARCHAR2(1000 BYTE),
  APPT_STS		    VARCHAR2(1 BYTE),
  PAT_TYPE        VARCHAR2(1 BYTE)
);
/
