create or replace
TYPE IMMUNIZATION_INFO AS OBJECT
(
  IMMUNIZATION_ITEM_ID        VARCHAR2(10000 BYTE),
  IMMUNIZATION_ITEM_NAME      VARCHAR2(255 BYTE),
  INJECTION_DATE              VARCHAR2(10 BYTE),
  DURATION                    VARCHAR2(10000 BYTE),
  NEXT_IMMUNIZATION_ITEM_ID   VARCHAR2(10000 BYTE),
  NEXT_IMMUNIZATION_ITEM_NAME VARCHAR2(255 BYTE),
  NEXT_INJECTION_DATE         VARCHAR2(10 BYTE),
  REMARKS                     VARCHAR2(500 BYTE),
  SEQ_NO                      VARCHAR2(1000 BYTE),
  CREATED_DATE		            VARCHAR2(10 BYTE),
  CREATED_USER                VARCHAR2(50 BYTE)
);
/
