create or replace
TYPE MEDBKG_PROBLEMS AS OBJECT
(
	SEQNO					VARCHAR2(1000 BYTE),
	CLASSIFICATION_CODE   	VARCHAR2(255 BYTE),
	REMARK                	VARCHAR2(500 BYTE),
	STATUS					VARCHAR2(10 BYTE),
	CREATE_DATE				VARCHAR2(20 BYTE),
	CREATE_USER				VARCHAR2(20 BYTE),
	UPDATE_DATE				VARCHAR2(20 BYTE),
	UPDATE_USER				VARCHAR2(20 BYTE)
);
/
