create or replace
TYPE MEDBKG_FAMILY_HISTORY AS OBJECT
(
	SEQNO					VARCHAR2(1000 BYTE),
	CREATE_DATE   			VARCHAR2(20 BYTE),
	REMARKS                	VARCHAR2(500 BYTE),
	UPDATE_USER				VARCHAR2(20 BYTE),
	UPDATE_DATE				VARCHAR2(20 BYTE),
	CREATE_USER				VARCHAR2(20 BYTE)
);
/
