ALTER TABLE NHS_PRINTERINFO
	DROP PRIMARY KEY CASCADE;
DROP TABLE NHS_PRINTERINFO CASCADE CONSTRAINTS;

CREATE TABLE NHS_PRINTERINFO
(
	COMPUTER_IP VARCHAR2(30 BYTE),
	PRINTER_TYPE VARCHAR2(50 BYTE),
	PRINTER_NAME VARCHAR2(200 BYTE),
	CREATED_DATE DATE DEFAULT SYSDATE,
	CREATED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
	MODIFIED_DATE DATE DEFAULT SYSDATE,
	MODIFIED_USER VARCHAR2(30 BYTE) DEFAULT 'SYSTEM',
	ENABLED NUMBER(*, 0) DEFAULT 1
);

-- default data (testing)
INSERT INTO NHS_PRINTERINFO (COMPUTER_IP, PRINTER_TYPE, PRINTER_NAME) VALUES ('127.0.0.1', 'LABEL', 'Datamax-O''Neil E-4205A Mark III');
INSERT INTO NHS_PRINTERINFO (COMPUTER_IP, PRINTER_TYPE, PRINTER_NAME) VALUES ('160.100.2.215', 'WRISTBABY', 'WBLblAdult');
INSERT INTO NHS_PRINTERINFO (COMPUTER_IP, PRINTER_TYPE, PRINTER_NAME) VALUES ('160.100.4.131', 'LABEL', 'HP LaserJet P2050 Series PCL6');
INSERT INTO NHS_PRINTERINFO (COMPUTER_IP, PRINTER_TYPE, PRINTER_NAME) VALUES ('160.100.4.131', 'WRISTBABY', 'HP LaserJet P2050 Series PCL6');
INSERT INTO NHS_PRINTERINFO (COMPUTER_IP, PRINTER_TYPE, PRINTER_NAME) VALUES ('160.100.4.131', 'WRISTADULT', 'HP LaserJet P2050 Series PCL6');
INSERT INTO NHS_PRINTERINFO (COMPUTER_IP, PRINTER_TYPE, PRINTER_NAME) VALUES ('160.100.2.215', 'WRISTADULT', 'WBLblAdult');
INSERT INTO NHS_PRINTERINFO (COMPUTER_IP, PRINTER_TYPE, PRINTER_NAME) VALUES ('160.100.2.80', 'LABEL', 'Datamax-O''Neil E-4205A Mark III');
/
