create or replace
TYPE OTAPPPROC AS OBJECT
(
  DUMMY		VARCHAR2(1 BYTE),
  OAPID		VARCHAR2(22 BYTE),
  OTAID		VARCHAR2(22 BYTE),
  OTPID		VARCHAR2(22 BYTE),
  OTPDESC	VARCHAR2(100 BYTE),
  OTPCODE	VARCHAR2(20 BYTE)
);
/