create or replace
TYPE OTLOGPROC AS OBJECT
(
  DUMMY		VARCHAR2(1 BYTE),
  OLPID		VARCHAR2(22 BYTE),
  OTLID		VARCHAR2(22 BYTE),
  OTPID		VARCHAR2(22 BYTE),
  OTPDESC	VARCHAR2(100 BYTE),
  OTPCODE	VARCHAR2(20 BYTE)
);
/
