create or replace
TYPE OTLOGEQUI AS OBJECT
(
  DUMMY		VARCHAR2(1 BYTE),
  OTCID		VARCHAR2(22 BYTE),
  OTCDESC	VARCHAR2(50 BYTE),
  OLECMT	VARCHAR2(50 BYTE),
  OLEID		VARCHAR2(22 BYTE),
  OTLID		VARCHAR2(22 BYTE)
);
/
