create or replace
TYPE OTLOGTEAM AS OBJECT
(
  DUMMY		VARCHAR2(1 BYTE),
  OTCID_SF	VARCHAR2(22 BYTE),
  OTCDESC1	VARCHAR2(50 BYTE),
  OTCID_FN	VARCHAR2(22 BYTE),
  OTCDESC2	VARCHAR2(50 BYTE),
  OLTID		VARCHAR2(22 BYTE),
  OTLID		VARCHAR2(22 BYTE)
);
/
