create or replace
TYPE OTLOGDRUG AS OBJECT
(
  DUMMY		VARCHAR2(1 BYTE),
  OTCID		VARCHAR2(22 BYTE),
  OTCDESC	VARCHAR2(50 BYTE),
  OLDCOST	VARCHAR2(5 BYTE),
  OLDUNIT	VARCHAR2(10 BYTE),
  OLDQTY	VARCHAR2(5 BYTE),
  OLDCMT	VARCHAR2(50 BYTE),
  OLDID		VARCHAR2(22 BYTE),
  OTLID		VARCHAR2(22 BYTE)
);
/
