create or replace
TYPE OTLOGINST AS OBJECT
(
  DUMMY		VARCHAR2(1 BYTE),
  OTCID		VARCHAR2(22 BYTE),
  OTCDESC	VARCHAR2(50 BYTE),
  OLUCMT	VARCHAR2(50 BYTE),
  OLUID		VARCHAR2(22 BYTE),
  OTLID		VARCHAR2(22 BYTE)
);
/
