create or replace
TYPE OTLOGIMPL AS OBJECT
(
  DUMMY		VARCHAR2(1 BYTE),
  OTCID		VARCHAR2(22 BYTE),
  OTCDESC   VARCHAR2(50 BYTE),
  OLICMT	VARCHAR2(50 BYTE),
  OLIID		VARCHAR2(22 BYTE),
  OTLID		VARCHAR2(22 BYTE)
);
/
