create or replace TYPE queuingList_Obj IS OBJECT (
    REGID NUMBER(22),
    WAITQUEUENO NUMBER,
    PATQUEUENO NUMBER(22),
    MESSAGE VARCHAR2(200),
    DOCCODE VARCHAR2(10),
    DOCNAME VARCHAR2(81),
    DOCCNAME VARCHAR2(10 CHAR),    
    SPCCODE VARCHAR2(10),
    SPCNAME VARCHAR2(50),
    SPCCNAME VARCHAR2(60),     
    BKGSDATE DATE,
    DOCIMG VARCHAR2(100)
  );