create or replace
TYPE TEMPLATE_SCH AS OBJECT
(
	DOC_FULLNAME   VARCHAR2(41 BYTE),
	TEMDAY         VARCHAR2(22 BYTE),
	TEMDAY_NAME    VARCHAR2(10 BYTE),
	TEMLEN         VARCHAR2(22 BYTE),
	TEMSTIME_STR   VARCHAR2(5 BYTE),
	TEMETIME_STR   VARCHAR2(5 BYTE),
	DOCPRACTICE    VARCHAR2(120 BYTE),
	TEMID          VARCHAR2(22 BYTE),
	DOCCODE        VARCHAR2(10 BYTE)
);
/
