@./SCM/NHS_LIS_COMCONTRACT.sql
@./SCM/NHS_LIS_TMCONTRACT.sql
@./SCM/NHS_LIS_REFCONTRACTFORM.sql
@./SCM/NHS_ACT_COMCONDPSERV.sql
@./SCM/NHS_ACT_COMCONITEM.sql
@./SCM/NHS_ACT_REFCONTRACTFORM.sql
@./SCM/NHS_LIS_GENCONTRACT.sql
exit