CREATE OR REPLACE FUNCTION "NHS_LIS_COMCONTRACT"

 RETURN TYPES.CURSOR_TYPE AS
  OUTCUR TYPES.CURSOR_TYPE;
BEGIN
  OPEN OUTCUR FOR
    SELECT '', PCYID, PCYCODE, PCYDESC FROM PATCAT ORDER BY PCYCODE;

  RETURN OUTCUR;
END NHS_LIS_COMCONTRACT;
/
