CREATE OR REPLACE FUNCTION "NHS_ACT_REFCONTRACTFORM" (
	V_ACTION    IN VARCHAR2,
	V_CID       IN VARCHAR2,
	V_CMCODE    IN VARCHAR2,
	V_CMCNAME   IN VARCHAR2,
	V_FORMULA   IN VARCHAR2,
	O_ERRMSG    OUT VARCHAR2
)
	RETURN NUMBER
AS
	O_ERRCODE NUMBER;
	V_NOOFREC NUMBER;
BEGIN
	O_ERRCODE := 0;
	O_ERRMSG := 'OK';
	SELECT COUNT(1) INTO V_NOOFREC FROM CMCFORM WHERE CID = V_CID;

	IF V_ACTION = 'ADD' THEN
		IF V_NOOFREC = 0 THEN
			INSERT INTO CMCFORM ( CID, CMCODE, CMCNAME, FORMULA )
			VALUES ( SEQ_CMCFORM.NEXTVAL, V_CMCODE, V_CMCNAME, V_FORMULA );
		END IF;
	ELSIF V_ACTION = 'MOD' THEN
		IF V_NOOFREC > 0 THEN
			UPDATE CMCFORM
			SET
				CMCODE = V_CMCODE,
				CMCNAME  = V_CMCNAME,
				FORMULA = V_FORMULA
			WHERE CID = V_CID;
		ELSE
			O_ERRCODE := -1;
			O_ERRMSG  := 'Fail to update due to record not exist.';
		END IF;
	ELSIF V_ACTION = 'DEL' THEN
		IF V_NOOFREC > 0 THEN
			DELETE CMCFORM WHERE CID = V_CID;
		ELSE
			O_ERRCODE := -1;
			O_ERRMSG  := 'Fail to delete due to record not exist.';
		END IF;
	END IF;
	RETURN O_ERRCODE;

END NHS_ACT_REFCONTRACTFORM;
/
