CREATE OR REPLACE FUNCTION "NHS_LIS_REFCONTRACTFORM"
 (V_ IN VARCHAR2)
  RETURN TYPES.CURSOR_TYPE
   AS
  OUTCUR TYPES.CURSOR_TYPE;
BEGIN
  OPEN OUTCUR FOR
    SELECT '',CID, CMCODE, CMCNAME, FORMULA FROM CMCFORM;
  RETURN OUTCUR;
END NHS_LIS_REFCONTRACTFORM;
/
