CREATE OR REPLACE FUNCTION "NHS_LIS_GENCONTRACT"(V_PCYID IN VARCHAR2)

 RETURN TYPES.CURSOR_TYPE AS
  OUTCUR TYPES.CURSOR_TYPE;
BEGIN
  OPEN OUTCUR FOR
    SELECT '',
           CID,
           PCYID,
           ITCTYPE,
           DSCCODE,
           DSCCODE,
           APPCONTR,
           TO_CHAR(EFF_DT_FRM,'DD/MM/YYYY'),
           TO_CHAR(EFF_DT_TO,'DD/MM/YYYY')
      FROM CMCDPS CD
      WHERE PCYID=V_PCYID;

  RETURN OUTCUR;
END NHS_LIS_GENCONTRACT;
/
