CREATE OR REPLACE FUNCTION "NHS_LIS_TMCONTRACT"(V_PCYID IN VARCHAR2)

 RETURN TYPES.CURSOR_TYPE AS
  OUTCUR TYPES.CURSOR_TYPE;
BEGIN
  OPEN OUTCUR FOR
    SELECT '',
           CID,
           PCYID,
           ITCTYPE,
           ITMCODE,
           ITMCODE,     
           APPCONTR,
           TO_CHAR(EFF_DT_FRM,'DD/MM/YYYY'),
           TO_CHAR(EFF_DT_TO,'DD/MM/YYYY')
      FROM CMCITM
      WHERE PCYID=V_PCYID;

  RETURN OUTCUR;
END NHS_LIS_TMCONTRACT;
/
