set define off;
@./transaction/NHS_ACT_ACCOUNT_RECEIVABLE.sql
@./transaction/NHS_ACT_ADDCASHIER.sql
@./transaction/NHS_ACT_ADDDEPOSIT.sql
@./transaction/NHS_ACT_ADDENTRY.sql
@./transaction/NHS_ACT_ADDENTRYST.sql
@./transaction/NHS_ACT_ADDENTRYST_AMC.sql
@./transaction/NHS_ACT_ADDPKGENTRY.sql
@./transaction/NHS_ACT_ADD_ENTRY.sql
@./transaction/NHS_ACT_ADJUSTCPSENTRY.sql
@./transaction/NHS_ACT_ADJUSTPKGENTRY.sql
@./transaction/NHS_ACT_ARCANCELENTRY.sql
@./transaction/NHS_ACT_ARENTRY.sql
@./transaction/NHS_ACT_ARPAYMENTCANCEL.sql
@./transaction/NHS_ACT_BEDRESERVATION.sql
@./transaction/NHS_ACT_CANCELPACKAGE.sql
@./transaction/NHS_ACT_ChangeAcm.sql
@./transaction/NHS_ACT_CHANGEACM_FORRPT.sql
@./transaction/NHS_ACT_CHGAMTDIS.sql
@./transaction/NHS_ACT_CHGRPTLVL.sql
@./transaction/NHS_ACT_CONFIRMDEPOSIT.sql
@./transaction/NHS_ACT_CREATESLIP.sql
@./transaction/NHS_ACT_DELETEDEPOSIT.sql
@./transaction/NHS_ACT_DEPOSIT.sql
@./transaction/NHS_ACT_ENTRY.sql
@./transaction/NHS_ACT_INSERTMISADDR.sql
@./transaction/NHS_ACT_IPSTATPRINTHIST.sql
@./transaction/NHS_ACT_ISCASHIERCLOSED.sql
@./transaction/NHS_ACT_ItemCancel.sql
@./transaction/NHS_ACT_ITEMCANCELPOST.sql
@./transaction/NHS_ACT_ITEMCHG.sql
@./transaction/NHS_ACT_MISADDREF.sql
@./transaction/NHS_ACT_MOVEITEMTOREF.sql
@./transaction/NHS_ACT_MOVEPACKAGETOSLIP.sql
@./transaction/NHS_ACT_PaymentCapture.sql
@./transaction/NHS_ACT_PKGCHARGECAPTURE.sql
@./transaction/NHS_ACT_PKGTRANS.sql
@./transaction/NHS_ACT_POSTTRASACTIONS.sql
@./transaction/NHS_ACT_REFUND.sql
@./transaction/NHS_ACT_REVERSEENTRY.sql
@./transaction/NHS_ACT_SCMREVERSE.sql
@./transaction/NHS_ACT_SCMSLIPTXREVERSE.sql
@./transaction/NHS_ACT_SCMUPDCASCADEREVERSE.sql
@./transaction/NHS_ACT_SETENTRY.sql
@./transaction/NHS_ACT_SETPACKAGEENTRY.sql
@./transaction/NHS_ACT_SLIP.sql
@./transaction/NHS_ACT_SLIPSMTRMK.sql
@./transaction/NHS_ACT_SLPPAYALLDOCCODERVS.sql
@./transaction/NHS_ACT_SLPPAYALLREVERSE.sql
@./transaction/NHS_ACT_SLPPAYALLSLIPTXREVERSE.sql
@./transaction/NHS_ACT_SLPPAYDTL.sql
@./transaction/NHS_ACT_SPECOMDTL.sql
@./transaction/NHS_ACT_SUPP.sql
@./transaction/NHS_ACT_TELLOG.sql
@./transaction/NHS_ACT_TXNBED_MODIFY.sql
@./transaction/NHS_ACT_TxnClose.sql
@./transaction/NHS_ACT_TXNDOCTOR_MODIFY.sql
@./transaction/NHS_ACT_TXNREMARK.sql
@./transaction/NHS_ACT_TXNRMDER.sql
@./transaction/NHS_ACT_TXNSLIPPAYALL_PAY.sql
@./transaction/NHS_ACT_TXNSLIPPAYALL_PAY1.sql
@./transaction/NHS_ACT_TXNSLIPTX_MODIFY.sql
@./transaction/NHS_ACT_UPDATE_DOCCODE_NA.sql
@./transaction/NHS_ACT_UPDATEBALANCE.sql
@./transaction/NHS_ACT_UPDATEENTRYDISCOUNT.sql
@./transaction/NHS_ACT_UpdateFirstPrintDate.sql
@./transaction/NHS_ACT_UpdateOBBk.sql
@./transaction/NHS_ACT_UPDATEPKGCODE.sql
@./transaction/NHS_ACT_UPDATEREGNOSIGN.sql
@./transaction/NHS_ACT_UPDATESLIP.sql
@./transaction/NHS_ACT_UPDATESLIPDISCOUNT.sql
@./transaction/NHS_ACT_UPDATESLIPTXSTATUS.sql
@./transaction/NHS_ACT_UPDATETRANSACTION.sql
@./transaction/NHS_GET_ACMCODE.sql
@./transaction/NHS_GET_CALSPECAMT.sql
@./transaction/NHS_GET_CHG.sql
@./transaction/NHS_GET_ConPceChange.sql
@./transaction/NHS_GET_CREDITCHG.sql
@./transaction/NHS_GET_ISSHWPYINSTN.sql
@./transaction/NHS_GET_ITEMCHG.sql
@./transaction/NHS_GET_ITEM_EXIST.sql
@./transaction/NHS_GET_ITMPKGCODEVALIDATE.sql
@./transaction/NHS_GET_LOOKUPITEMCHARGE.sql
@./transaction/NHS_GET_OBBOOK.sql
@./transaction/NHS_GET_PRTSUPPDR.sql
@./transaction/NHS_GET_REGDISCHARGE.sql
@./transaction/NHS_GET_SLIPISINPAT.sql
@./transaction/NHS_GET_SLIPMERGE.sql
@./transaction/NHS_GET_SLPRMK.sql
@./transaction/NHS_GET_TOTALCREDIT.sql
@./transaction/NHS_GET_TRANSACTION_DETAIL.sql
@./transaction/NHS_GET_TXNCalRefItem.sql
@./transaction/NHS_GET_TXNRMDER.sql
@./transaction/NHS_LIS_CONPCECHANGE.sql
@./transaction/NHS_LIS_DEPATSUBCHRG.sql
@./transaction/NHS_LIS_DEPOSIT.sql
@./transaction/NHS_LIS_DOCITMPCT.sql
@./transaction/NHS_LIS_DOCTRANS.sql
@./transaction/NHS_LIS_HAT_GETLABCHARGES.sql
@./transaction/NHS_LIS_IPRPTHIS.sql
@./transaction/NHS_LIS_ITEM.sql
@./transaction/NHS_LIS_PATIENTADD.sql
@./transaction/NHS_LIS_PKGCHARGECAPTURE.sql
@./transaction/NHS_LIS_PKGTRANS.sql
@./transaction/NHS_LIS_REFUND.sql
@./transaction/NHS_LIS_SEARCHLOOKUP.sql
@./transaction/NHS_LIS_SHOWOT.sql
@./transaction/NHS_LIS_SLIPMBLINK.sql
@./transaction/NHS_LIS_SLIPSEARCH.sql
@./transaction/NHS_LIS_SLIPSEARCHBYITEM.sql
@./transaction/NHS_LIS_SUBDISEASE_SEARCH.sql
@./transaction/NHS_LIS_SUBREASON_SEARCH.sql
@./transaction/NHS_LIS_SUPP.sql
@./transaction/NHS_LIS_TELLOG.sql
@./transaction/NHS_LIS_TELLOGLOOKUP.sql
@./transaction/NHS_LIS_TRANSACTION_CREDIT.sql
@./transaction/NHS_LIS_TRANSACTION_DETAIL.sql
@./transaction/NHS_LIS_TRANSACTION_DETAIL_C.sql
@./transaction/NHS_LIS_TRANSACTION_SUBDETAIL.sql
@./transaction/NHS_LIS_TXNSLIPPAYALL_ALL.sql
@./transaction/NHS_LIS_TXNSLIPPAYALL_CHG.sql
@./transaction/NHS_LIS_TXNSLIPPAYALL_PAY.sql
@./transaction/NHS_LIS_TXNSLIP_AFTERDISCHARGE.sql
@./transaction/NHS_UTL_RECALCULATECPS_FORRPT.sql
@./transaction/NHS_UTL_UPDATE_DOCCODE_NA.sql
exit