create or replace
FUNCTION "NHS_LIS_DOCTRANS"
(
  V_SLPNO SLIP.SLPNO%TYPE,
  V_DOCCODE SLIPTX.DOCCODE%TYPE,
  V_TYPE_DEBIT SLIPTX.STNTYPE%TYPE,
  V_STATUS_NORMAL SLIPTX.STNSTS%TYPE,
  V_STATUS_ADJUST SLIPTX.STNSTS%TYPE,
  V_TYPE_DOCTOR SLIPTX.ITMTYPE%TYPE
)
  RETURN Types.cursor_type
AS
  outcur types.cursor_type;
BEGIN
  OPEN outcur FOR
    SELECT TX.DIXREF, S.SLPTYPE, S.PCYID, TX.DSCCODE, TX.ITMCODE, SUM(STNNAMT) AS STNNAMT
    FROM SLIP S, SLIPTX TX
    WHERE S.SLPNO = V_SLPNO
    AND S.SLPNO = TX.SLPNO
    AND TX.STNTYPE = V_TYPE_DEBIT
    AND TX.DOCCODE = V_DOCCODE
    AND TX.STNSTS IN (V_STATUS_NORMAL, V_STATUS_ADJUST)
    AND TX.ITMTYPE = V_TYPE_DOCTOR
    GROUP BY TX.DIXREF, S.SLPTYPE, S.PCYID, TX.DSCCODE, TX.ITMCODE;
  RETURN OUTCUR;
END NHS_LIS_DOCTRANS;
/