CREATE OR REPLACE FUNCTION "NHS_LIS_TXNSLIPPAYALL_PAY" (
	v_slpno slip.slpno%TYPE
)
	RETURN Types.cursor_type
AS
	outcur types.cursor_type;
BEGIN
	OPEN outcur FOR
	SELECT T.STNTYPE || T.STNID AS KEY,
		   T.STNTYPE,
		   T.ITMCODE,
		   T.STNDESC,
		   '' AS ARCCODE,
		   T.STNNAMT + NVL(SUM(SPD.SPDAAMT), 0) AS STNNAMT,
		   TO_CHAR(T.STNCDATE,'dd/MM/yyyy') AS stncdate,
		   T.STNID AS PAYREF,
		   T.STNXREF
	  FROM SLIPTX T, SLPPAYDTL SPD
	 WHERE T.SLPNO = v_slpno
	   AND T.STNTYPE IN ('C', 'R', 'S', 'I')
	   AND T.STNID = SPD.PAYREF(+)
	   AND T.SLPNO = SPD.SLPNO(+)
	   AND T.STNTYPE = SPD.STNTYPE(+)
	   AND T.STNADOC IS NULL
	   AND T.STNSTS = 'N'
	 GROUP BY T.STNTYPE || T.STNID,
			  T.STNTYPE,
			  T.ITMCODE,
			  T.STNDESC,
			  T.STNNAMT,
			  T.STNXREF,
			  T.STNCDATE,
			  T.STNID
	HAVING T.STNNAMT + NVL(SUM(SPD.SPDAAMT), 0) <> 0
	UNION ALL
	SELECT T.STNTYPE || C.ATXID AS KEY,
		   T.STNTYPE,
		   T.ITMCODE,
		   (CASE WHEN LENGTH(T.STNDESC || ' (' || AX.ARPRECNO || ')') > 80 THEN T.STNDESC ELSE T.STNDESC || ' (' || AX.ARPRECNO || ')' END),
		   C.ARCCODE,
		   C.ATXAMT + NVL(SUM(SPD.SPDAAMT), 0) AS STNNAMT,
		   TO_CHAR(C.ATXCDATE,'dd/MM/yyyy') AS stncdate,
		   C.ATXID AS PAYREF,
		   T.STNXREF
	  FROM SLIPTX T,
		   ARTX D,
		   ARTX C,
		   (SELECT *
			  FROM SLPPAYDTL
			 WHERE SLPNO = v_slpno
			   AND STNTYPE = 'P') SPD,
			ARPTX AX
	 WHERE T.SLPNO = v_slpno
	   AND T.STNTYPE = 'P'
	   AND T.STNXREF = D.ATXID
	   AND D.SLPNO = T.SLPNO
	   AND C.SLPNO = T.SLPNO
	   AND D.ATXID = C.ATXREFID
	   AND C.ATXID = SPD.PAYREF(+)
	   AND C.ARPID = AX.ARPID(+)
	   AND T.STNSTS = 'N'
	   AND C.ARPID IS NOT NULL
	   AND D.ATXSTS = 'N'
	   AND C.ATXSTS = 'N'
	   AND T.STNADOC IS NULL
	 GROUP BY T.STNTYPE || C.ATXID,
			  T.STNTYPE,
			  T.ITMCODE,
			  T.STNDESC,
			  AX.ARPRECNO,
			  C.ATXAMT,
			  T.STNXREF,
			  C.ATXCDATE,
			  C.ATXID,
			  C.ARCCODE
	HAVING C.ATXAMT + NVL(SUM(SPD.SPDAAMT), 0) <> 0
	ORDER BY KEY DESC;

	RETURN OUTCUR;
END NHS_LIS_TXNSLIPPAYALL_PAY;
/
