CREATE OR REPLACE FUNCTION NHS_GET_SLPTELEMED (
	V_SLIPNO VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
BEGIN
	OPEN OUTCUR FOR
		SELECT
            NVL(U.USRNAME, SE.TELEMEDMODUSR),
			TO_CHAR(SE.TELEMEDMODDT, 'DD/MM/YYYY HH24:MI:SS'),
			SE.TELEMEDURL,
			SE.TELEMEDID,
			SE.TELEMEDPASSCODE,
			TO_CHAR(SE.TELEMEDSMSDT, 'DD/MM/YYYY HH24:MI:SS'),
			TO_CHAR(SE.TELEMEDSMSDTOK, 'DD/MM/YYYY HH24:MI:SS'),
            NVL(U2.USRNAME, SE.TELEMEDSMSUSR),
            SE.TELEMEDSMSRTNMSG
		FROM  SLIP S
		LEFT  JOIN SLIP_EXTRA SE ON S.SLPNO = SE.SLPNO
		LEFT  JOIN USR U ON SE.TELEMEDMODUSR = U.USRID
        LEFT  JOIN USR U2 ON SE.TELEMEDSMSUSR = U2.USRID
		WHERE S.SLPNO = V_SLIPNO;
	RETURN OUTCUR;
END NHS_GET_SLPTELEMED;
/
