create or replace
FUNCTION NHS_ACT_IPSTATPRINTHIST (
  V_ACTION    IN VARCHAR2,
  V_ISCOPY    IN VARCHAR2,
  V_PRINTSEQ  IN VARCHAR2,
  V_USER      IN VARCHAR2,
  V_SLPNO     IN VARCHAR2,
  V_PRNNAME   IN VARCHAR2,
  O_ERRMSG    OUT VARCHAR2
)
RETURN NUMBER
AS
  O_ERRCODE     NUMBER;
  V_NEXT_SEQ    NUMBER;
  V_SYSDATE     DATE;
BEGIN
  O_ERRMSG := 'OK';
  V_SYSDATE := SYSDATE;

  SELECT MAX(SEQ) + 1 INTO V_NEXT_SEQ
  FROM IPSTATPRINTHIST;

  INSERT INTO IPSTATPRINTHIST (
      SEQ, PRINTDATE, COPY, PRNSEQ, USR, SLPNO, PRNRPT)
  VALUES (
      V_NEXT_SEQ, V_SYSDATE, V_ISCOPY, V_PRINTSEQ, V_USER, V_SLPNO, V_PRNNAME);

  O_ERRCODE := 999;

RETURN O_ERRCODE;
EXCEPTION
WHEN OTHERS THEN
	ROLLBACK;
	dbms_output.put_line('An ERROR was encountered - '||SQLCODE||' -ERROR- '||SQLERRM);

	RETURN -1;
END NHS_ACT_IPSTATPRINTHIST;
/
