CREATE OR REPLACE FUNCTION "NHS_GET_OBBOOK"(V_SLPNO IN VARCHAR2)
  RETURN TYPES.CURSOR_TYPE AS
  OUTCUR TYPES.CURSOR_TYPE;
BEGIN
  OPEN OUTCUR FOR
    SELECT NVL(S.SLPFNAME, P.PATFNAME) AS PATFNAME,
           NVL(S.SLPGNAME, P.PATGNAME) AS PATGNAME,
           S.BPBNO,
           BPB.BPBPNAME,
           S.BPBNOUSERID,
           U.USRNAME,
           TO_CHAR(S.BPBEDITDATE, 'DD/MM/YYYY'),
           TO_CHAR(S.EDC, 'DD/MM/YYYY'),
           TO_CHAR(S.FIRSTPRTDT, 'DD/MM/YYYY'),
           TO_CHAR(S.ISSUEDT, 'DD/MM/YYYY'),
           TO_CHAR(S.EDCEDITDATE, 'DD/MM/YYYY'),
           S.EDCUSERID,
           U2.USRNAME
      FROM SLIP S, PATIENT P, BEDPREBOK BPB, USR U, USR U2
     WHERE S.PATNO = P.PATNO(+)
       AND S.BPBNO = BPB.BPBNO(+)
       AND S.BPBNOUSERID = U.USRID(+)
       AND S.EDCUSERID = U2.USRID(+)
       AND S.SLPNO = V_SLPNO;
  RETURN OUTCUR;
END NHS_GET_OBBOOK;
/
