CREATE OR REPLACE FUNCTION "NHS_ACT_ADDPKGENTRY" (
	i_ACTION           IN VARCHAR2,
	i_SLIPNO           IN VARCHAR2,
	i_PACKAGECODE      IN VARCHAR2,
	i_ITEMCODE         IN VARCHAR2,
	i_STNOAMT          IN VARCHAR2,
	i_STNBAMT          IN VARCHAR2,
	i_DOCTORCODE       IN VARCHAR2,
	i_REPORTLEVEL      IN VARCHAR2,
	i_ACCOMODATIONCODE IN VARCHAR2,
	i_CAPTUREDATE      IN VARCHAR2,
	i_TRANSACTIONDATE  IN VARCHAR2,
	i_DESCRIPTION      IN VARCHAR2,
	i_STATUS           IN VARCHAR2,
--	i_CASHIERCLOSED    IN VARCHAR2,
	i_BEDCODE          IN VARCHAR2,
	i_DIXREF           IN VARCHAR2,
	i_FLAGTODI         IN VARCHAR2, --'1' is true,'0' false
	i_CONPCESETFLAG    IN VARCHAR2,
	i_UNITAMT          IN VARCHAR2,
	i_STNDESC1         IN VARCHAR2,
	i_IREFNO           IN VARCHAR2,
	i_PkgcodeInLkUpGlccode         IN VARCHAR2, --'1' is true,'0' false
	i_USRID            IN VARCHAR2,
	O_ERRMSG           OUT VARCHAR2
)
	RETURN NUMBER
AS
	O_ERRCODE  NUMBER;
	v_FLAGTODI BOOLEAN := FALSE;
	v_PkgcodeInLkUpGlccode BOOLEAN := FALSE;
BEGIN
	O_ERRCODE := 0;
	O_ERRMSG  := 'OK';

	IF i_FLAGTODI = 1 THEN
		v_FLAGTODI := TRUE;
	END IF;

	IF i_PkgcodeInLkUpGlccode = 1 THEN
		v_PkgcodeInLkUpGlccode := TRUE;
	END IF;

	IF i_ACTION = 'ADD' THEN
		O_ERRCODE := NHS_UTL_AddPackageEntry(
			i_SLIPNO,
			i_PACKAGECODE,
			i_ITEMCODE,
			TO_NUMBER(i_STNOAMT),
			TO_NUMBER(i_STNBAMT),
			i_DOCTORCODE,
			TO_NUMBER(i_REPORTLEVEL),
			i_ACCOMODATIONCODE,
			TO_DATE(i_CAPTUREDATE, 'DD/MM/YYYY HH24:MI:SS'),
			TO_DATE(i_TRANSACTIONDATE, 'DD/MM/YYYY HH24:MI:SS'),
			i_DESCRIPTION,
			i_STATUS,
			i_BEDCODE,
			TO_NUMBER(i_DIXREF),
			v_FLAGTODI,
			i_CONPCESETFLAG,
			TO_NUMBER(i_UNITAMT),
			i_STNDESC1,
			i_IREFNO,
			NULL,
			NULL,
			v_PkgcodeInLkUpGlccode,
			i_USRID
		);

		IF O_ERRCODE IS NULL THEN
			O_ERRCODE := -1;
      		O_ERRMSG := 'NHS_UTL_AddPackageEntry execute failed';
		END IF;
	END IF;
	RETURN O_ERRCODE;
END NHS_ACT_ADDPKGENTRY;
/
