create or replace FUNCTION "NHS_GET_CHECKCHGALERTMSG" (
	V_ITMCODE IN VARCHAR2,
  V_SLPTYPE IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
BEGIN

	OPEN OUTCUR FOR
    SELECT HPRMK||HPRMK1 FROM HPSTATUS WHERE
    HPTYPE = 'CHGALTMSG'
    AND (HPSTATUS = V_SLPTYPE  OR HPSTATUS = 'A')
    AND HPKEY = V_ITMCODE
    AND HPACTIVE = -1;
	RETURN OUTCUR;
END NHS_GET_CHECKCHGALERTMSG;
/
