CREATE OR REPLACE FUNCTION "NHS_ACT_FINESTHOSP" (
	v_action             IN VARCHAR2,
	V_FESTID             IN FIN_EST_HOSP.FESTID%TYPE,
	V_PBPID              IN FIN_EST_HOSP.PBPID%TYPE,
	V_REGID              IN FIN_EST_HOSP.REGID%TYPE,
	V_SLPNO              IN FIN_EST_HOSP.SLPNO%TYPE,
	V_PATNO              IN FIN_EST_HOSP.PATNO%TYPE,
	V_DOCCODE            IN FIN_EST_HOSP.PATNO%TYPE,
	V_PROCCODE           IN FIN_EST_HOSP.PROCCODE%TYPE,
	v_DIAGNOSIS          IN FIN_EST_HOSP.DIAGNOSIS%TYPE,
	v_LOS                IN FIN_EST_HOSP.LOS%TYPE,
	v_ACMCODE            IN FIN_EST_HOSP.ACMCODE%TYPE,
	v_AB_BYDRB4ADM       IN FIN_EST_HOSP.AB_BYDRB4ADM%TYPE,
	v_OSB_BE             IN FIN_EST_HOSP.OSB_BE%TYPE,
	v_A_PDBYSTS          IN FIN_EST_HOSP.A_PDBYSTS%TYPE,
	v_B_PDBYSTS          IN FIN_EST_HOSP.B_PDBYSTS%TYPE,
	v_A_SIGN_PAT_LOC     IN FIN_EST_HOSP.A_SIGN_PAT_LOC%TYPE,
	v_A_SIGN_DOC_LOC     IN FIN_EST_HOSP.A_SIGN_DOC_LOC%TYPE,
	v_B_SIGN_PAT_LOC     IN FIN_EST_HOSP.B_SIGN_PAT_LOC%TYPE,
	v_DRRNDDAYSUMMIN1    IN FIN_EST_HOSP.DRRNDDAYSUMMIN1%TYPE,
	v_DRRNDDAYSUMMAX1    IN FIN_EST_HOSP.DRRNDDAYSUMMAX1%TYPE,
	v_PROFEEMIN          IN FIN_EST_HOSP.PROFEEMIN%TYPE,
	v_PROFEEMAX          IN FIN_EST_HOSP.PROFEEMAX%TYPE,
	v_ANAESTHETISTFEEMIN IN FIN_EST_HOSP.ANAESTHETISTFEEMIN%TYPE,
	v_ANAESTHETISTFEEMAX IN FIN_EST_HOSP.ANAESTHETISTFEEMAX%TYPE,
	v_OTHERMIN1          IN FIN_EST_HOSP.OTHERMIN1%TYPE,
	v_OTHERMAX1          IN FIN_EST_HOSP.OTHERMAX1%TYPE,
	v_OTHERMIN2          IN FIN_EST_HOSP.OTHERMIN2%TYPE,
	v_OTHERMAX2          IN FIN_EST_HOSP.OTHERMAX2%TYPE,
	v_RMSUMMIN           IN FIN_EST_HOSP.RMSUMMIN%TYPE,
	v_RMSUMMAX           IN FIN_EST_HOSP.RMSUMMAX%TYPE,
	v_OTMAX              IN FIN_EST_HOSP.OTMAX%TYPE,
	v_OTMIN              IN FIN_EST_HOSP.OTMIN%TYPE,
	v_OTHERMIN3          IN FIN_EST_HOSP.OTHERMIN3%TYPE,
	v_OTHERMAX3          IN FIN_EST_HOSP.OTHERMAX3%TYPE,
	V_USER               IN FIN_EST_HOSP.CREATE_USER%TYPE,
	o_errmsg             OUT VARCHAR2
)
	RETURN NUMBER
AS
	o_errcode NUMBER;
	v_noOfRec NUMBER;
	v_ID      NUMBER;
	V_REG_SLPNO  SLIP.SLPNO%Type;
	I_BE FIN_EST_HOSP.OSB_BE%TYPE;
BEGIN
	o_errcode := 0;
	O_Errmsg := 'OK';
	V_Noofrec := 0;

	O_Errcode := Nhs_Act_Syslog(V_Action, 'NHS_ACT_FINESTHOSP',V_Action,'[V_Festid]:'||V_Festid, '', Null, O_Errmsg);

	If V_Festid Is Not Null And Length(V_Festid) > 0 Then
		Select Count(1) Into V_Noofrec From Fin_Est_Hosp Where Festid = V_Festid;
	END IF;

	IF v_noOfRec = 0 THEN
		SELECT SEQ_FEST.NEXTVAL INTO V_ID FROM DUAL;
		INSERT INTO FIN_EST_HOSP
		  (
			FESTID, PBPID, REGID, SLPNO, PATNO,
			DOCCODE, PROCCODE, DIAGNOSIS, LOS, ACMCODE,
			AB_BYDRB4ADM, OSB_BE, A_PDBYSTS, B_PDBYSTS, A_SIGN_PAT_LOC,
			A_SIGN_DOC_LOC, B_SIGN_PAT_LOC, DRRNDDAYSUMMIN1,DRRNDDAYSUMMAX1, PROFEEMIN,
			PROFEEMAX, ANAESTHETISTFEEMIN, ANAESTHETISTFEEMAX, OTHERMIN1, OTHERMAX1,
			OTHERMIN2, OTHERMAX2, RMSUMMIN, RMSUMMAX,OTMAX,
			OTMIN, OTHERMIN3, OTHERMAX3, CREATE_DATE, CREATE_USER,
			MODIFIED_DATE,MODIFIED_USER,ENABLED
		  ) VALUES (
			V_ID, V_PBPID, V_REGID, V_SLPNO, V_PATNO,
			V_DOCCODE, V_PROCCODE, V_DIAGNOSIS, V_LOS, V_ACMCODE,
			V_AB_BYDRB4ADM, V_OSB_BE, V_A_PDBYSTS, V_B_PDBYSTS, V_A_SIGN_PAT_LOC,
			V_A_SIGN_DOC_LOC, V_B_SIGN_PAT_LOC, V_DRRNDDAYSUMMIN1, V_DRRNDDAYSUMMAX1, V_PROFEEMIN,
			V_PROFEEMAX, V_ANAESTHETISTFEEMIN, V_ANAESTHETISTFEEMAX, V_OTHERMIN1, V_OTHERMAX1,
			V_OTHERMIN2, V_OTHERMAX2, V_RMSUMMIN, V_RMSUMMAX, V_OTMAX,
			V_OTMIN, V_OTHERMIN3, V_OTHERMAX3,SYSDATE,V_USER,
			SYSDATE,V_USER,'-1'
		  );
		o_errcode := V_ID;
	ELSE
		Select OSB_BE Into I_BE From Fin_Est_Hosp Where Festid = V_Festid;
		IF ( I_BE IS NOT NULL AND I_BE = '-1' AND v_OSB_BE = '0') THEN
					    -- delete existing BE when unclick the checkbox
					      DELETE FROM FIN_EST_HOSP
					      WHERE PBPID = V_PBPID
					      AND FESTID = V_Festid ;
		ELSE
			V_ID := V_FESTID;
			o_errcode := Nhs_Act_Syslog(V_Action, 'NHS_ACT_FINESTHOSP',V_Action,'[V_ID]:'||V_ID, '', Null, O_Errmsg);

			UPDATE FIN_EST_HOSP
			SET
				PBPID = V_PBPID,
				REGID = V_REGID,
				Slpno = V_Slpno,
				PATNO = V_PATNO,
				DOCCODE = V_DOCCODE,
				PROCCODE = V_PROCCODE,
				DIAGNOSIS = V_DIAGNOSIS,
				LOS = V_LOS,
				ACMCODE = V_ACMCODE,
				AB_BYDRB4ADM       = V_AB_BYDRB4ADM,
				OSB_BE             = V_OSB_BE,
				A_PDBYSTS          = V_A_PDBYSTS,
				B_PDBYSTS          = V_B_PDBYSTS,
				A_SIGN_PAT_LOC     = V_A_SIGN_PAT_LOC,
				A_SIGN_DOC_LOC     = V_A_SIGN_DOC_LOC,
				B_SIGN_PAT_LOC     = V_B_SIGN_PAT_LOC,
				DRRNDDAYSUMMIN1    = V_DRRNDDAYSUMMIN1,
				DRRNDDAYSUMMAX1    = V_DRRNDDAYSUMMAX1,
				PROFEEMIN          = V_PROFEEMIN,
				PROFEEMAX          = V_PROFEEMAX,
				ANAESTHETISTFEEMIN = V_ANAESTHETISTFEEMIN,
				ANAESTHETISTFEEMAX = V_ANAESTHETISTFEEMAX,
				OTHERMIN1          = V_OTHERMIN1,
				OTHERMAX1          = V_OTHERMAX1,
				OTHERMIN2          = V_OTHERMIN2,
				OTHERMAX2          = V_OTHERMAX2,
				RMSUMMIN           = V_RMSUMMIN,
				RMSUMMAX           = V_RMSUMMAX,
				OTMAX              = V_OTMAX,
				OTMIN              = V_OTMIN,
				OTHERMIN3          = V_OTHERMIN3,
				OTHERMAX3          = V_OTHERMAX3,
				MODIFIED_DATE      = SYSDATE,
				MODIFIED_USER      = V_USER
			WHERE
				Festid = V_Id
				And enabled = -1;
				o_errcode := V_ID;
		END IF;
	END IF;

	RETURN o_errcode;
EXCEPTION
WHEN OTHERS THEN
	ROLLBACK;
	DBMS_OUTPUT.PUT_LINE('An ERROR was encountered - '||SQLCODE||' -ERROR- '||SQLERRM);
	RETURN o_errcode;
END NHS_ACT_FINESTHOSP;
/
