create or replace
FUNCTION "NHS_GET_TOTALCREDIT"
(
  V_SLPNO SLIP.SLPNO%TYPE,
  V_DOCCODE SLIPTX.DOCCODE%TYPE,
  V_STATUS_NORMAL SLIPTX.STNSTS%TYPE,
  V_STATUS_ADJUST SLIPTX.STNSTS%TYPE,
  V_TYPE_CREDIT SLIPTX.STNTYPE%TYPE
)
  RETURN Types.cursor_type
AS
  outcur types.cursor_type;
BEGIN
  OPEN outcur FOR
    SELECT NVL(SUM(STNNAMT), 0)
    FROM SLIPTX TX, ITEM I
    WHERE TX.SLPNO = V_SLPNO
    AND TX.DOCCODE = V_DOCCODE
    AND TX.STNSTS IN (V_STATUS_NORMAL, V_STATUS_ADJUST)
    AND TX.STNTYPE = V_TYPE_CREDIT
    AND TX.ITMCODE = I.ITMCODE
    AND I.ITMDOCCR = '-1';
  RETURN OUTCUR;
END NHS_GET_TOTALCREDIT;
/