create or replace FUNCTION "NHS_ACT_SUPP" (
	v_ACTION    IN VARCHAR2,
	v_STNID     IN VARCHAR2,
	v_USRID     IN VARCHAR2,
	v_TSLID_C   IN VARCHAR2,
	v_SUPP      IN TEMPLATE_OBJ_TAB,
	o_ERRMSG    OUT VARCHAR2
)
	RETURN NUMBER
AS
	o_ERRCODE     NUMBER;
	v_TSLID       VARCHAR(22);
	MAX_TSLID     NUMBER;
	v_TSLDATE_A   DATE;
	v_TSLDATE_C   DATE;
BEGIN
	o_ERRCODE := 0;
	o_ERRMSG := 'OK';
	v_TSLID := '';

	IF v_ACTION = 'MOD' THEN
		FOR I IN 1..v_SUPP.COUNT LOOP
			v_TSLID := v_SUPP(I).COLUMN01;
			v_TSLDATE_A := To_DATE(v_SUPP(I).COLUMN10 || ' ' || v_SUPP(I).COLUMN13, 'DD/MM/YYYY HH24:MI:SS');

			IF LENGTH(v_SUPP(I).COLUMN12) > 0 THEN
				v_TSLDATE_C := To_DATE(v_SUPP(I).COLUMN12 || ' ' || v_SUPP(I).COLUMN14, 'DD/MM/YYYY HH24:MI:SS');
			END IF;

			IF LENGTH(v_TSLID) > 0 THEN
				UPDATE TXNENDOSDTLS
				SET DOCCODE_O = v_SUPP(I).COLUMN05,
				DOCCODE_T = v_SUPP(I).COLUMN06,
				REMARK = v_SUPP(I).COLUMN07,
        AMOUNT = v_SUPP(I).COLUMN08
				WHERE TSLID = v_TSLID;

				o_ERRCODE := '992';
				o_ERRMSG := 'Step Update';
			ELSE
        SELECT SEQ_TXNENDOSDTLS.NEXTVAL INTO MAX_TSLID FROM DUAL;

				INSERT INTO TXNENDOSDTLS(
					TSLID, STNID, SUPCODE, USRID_A, TSLDATE_A, USRID_C, TSLDATE_C,
					DOCCODE_O, DOCCODE_T, REMARK, AMOUNT
				) VALUES(
					MAX_TSLID, v_STNID, v_SUPP(I).COLUMN03, v_SUPP(I).COLUMN09, v_TSLDATE_A,
					v_SUPP(I).COLUMN11, v_TSLDATE_C, v_SUPP(I).COLUMN05, v_SUPP(I).COLUMN06,
					v_SUPP(I).COLUMN07, v_SUPP(I).COLUMN08);

				o_ERRCODE := '991';
				o_ERRMSG := 'Step New';
			END IF;
		END LOOP;
	ELSIF v_ACTION = 'DEL' THEN
		v_TSLID := v_TSLID_C;

		UPDATE TXNENDOSDTLS
		SET TSLDATE_C = SYSDATE,
		USRID_C = v_USRID
		WHERE TSLID = v_TSLID;

		o_ERRCODE := '993';
		o_ERRMSG := 'Step Delete';
	END IF;

	RETURN o_ERRCODE;
EXCEPTION
WHEN OTHERS THEN
	ROLLBACK;
	dbms_output.put_line('An ERROR was encountered - '||SQLCODE||' -ERROR- '||SQLERRM);

	RETURN -1;
END NHS_ACT_SUPP;
/