create or replace
FUNCTION      "NHS_LIS_SHOWOT" (
  V_SLPNO IN VARCHAR2
)
  RETURN TYPES.CURSOR_TYPE
AS
  OUTCUR TYPES.CURSOR_TYPE;
BEGIN

  OPEN OUTCUR FOR 
            SELECT TO_CHAR(A.OTLDATE, 'DD/MM/YYYY'), B.OTPDESC, A.DOCCODE_R, C.DOCFNAME || ' ' || C.DOCGNAME AS REFDRNAME,
                    DECODE(A.OTLSPEC, -1, 'Yes', 'No') AS OTLSPEC, 
                    (SELECT OTCDESC FROM OT_CODE WHERE OTCID = A.OTLSPECDEST AND OTCTYPE = 'SD') AS OTLSPECDEST 
            FROM OT_LOG A, OT_PROC B, DOCTOR C
            WHERE A.SLPNO = V_SLPNO 
            AND (A.OTLSTS = 'A' OR A.OTLSTS = 'C')
            AND A.OTPID = B.OTPID 
            AND A.DOCCODE_R = C.DOCCODE(+)
            ORDER BY A.OTLDATE DESC, OTPDESC ASC;


  RETURN OUTCUR;

END NHS_LIS_SHOWOT;
/