CREATE OR REPLACE FUNCTION "NHS_ACT_PKGCHARGECAPTURE" (
	v_ACTION    IN VARCHAR2,
	V_SLPNO     IN VARCHAR2,
	v_SLPTYPE   IN VARCHAR2,
	V_BEDCODE   IN VARCHAR2,
	V_USRID     IN VARCHAR2,
	v_ADDCHARGE IN ADDCHARGES_INFO_TAB,
	o_ERRMSG    OUT VARCHAR2
)
	RETURN NUMBER
AS
	O_ERRCODE NUMBER;
  	V_TXNDATE DATE;
  	v_GLCCode PkgTx.GlcCode%TYPE;
BEGIN
	o_ERRCODE := -1;
	o_ERRMSG := 'OK';

	IF v_ACTION = 'MOD' THEN
		FOR I IN 1..V_ADDCHARGE.COUNT LOOP
			V_TXNDATE := TO_DATE(V_ADDCHARGE(I).TXNDATE || ' 00:00:00', 'DD/MM/YYYY HH24:MI:SS');
      			V_GLCCODE := NHS_UTL_LOOKUPGLCODE(TO_CHAR(V_ADDCHARGE(I).TXNDATE, 'DD/MM/YYYY'), V_ADDCHARGE(I).ITMCODE, V_BEDCODE, V_SLPTYPE, NULL,
				NULL,
				CASE WHEN V_ADDCHARGE(I).ISPKG = 'Y' THEN
				V_ADDCHARGE(I).PKGCODE
				ELSE
				NULL
				END,
				V_ADDCHARGE(I).ACMCODE, null);

			o_ERRCODE := NHS_UTL_ADDPACKAGEENTRY (V_SLPNO, V_ADDCHARGE(I).PKGCODE, V_ADDCHARGE(I).ITMCODE,
                               V_ADDCHARGE(I).PTNOAMT, V_ADDCHARGE(I).AMOUNT,
                               V_ADDCHARGE(I).DOCCODE, V_ADDCHARGE(I).ITMRLVL,
                               V_ADDCHARGE(I).ACMCODE, SYSDATE, V_TXNDATE,
                               V_ADDCHARGE(I).DESCRITION, NULL, V_BEDCODE, NULL, FALSE,
                               V_ADDCHARGE(I).CPS, 1, null, V_ADDCHARGE(I).IREFNO, null,
                               V_GLCCODE, false, V_USRID);

      			IF O_ERRCODE < 0 THEN
        			ROLLBACK;
        			O_ERRMSG := 'Error occur in Adding Charges';
        			RETURN -1;
      			END IF;
		END LOOP;
	END IF;

	RETURN o_ERRCODE;
EXCEPTION
WHEN OTHERS THEN
	ROLLBACK;
	dbms_output.put_line('An ERROR was encountered - '||SQLCODE||' -ERROR- '||SQLERRM);

	RETURN -1;
END NHS_ACT_PKGCHARGECAPTURE;
/
