CREATE OR REPLACE FUNCTION "NHS_LIS_PATIENTADD"(V_PATNO IN VARCHAR2)
  RETURN TYPES.CURSOR_TYPE AS
  OUTCUR TYPES.CURSOR_TYPE;
BEGIN
  OPEN OUTCUR FOR
    SELECT PATFNAME || ' ' || PATGNAME, PATADD1, PATADD2, PATADD3, COUDESC
      FROM PATIENT, COUNTRY
     WHERE PATNO = V_PATNO
       AND PATIENT.COUCODE = COUNTRY.COUCODE(+);
  RETURN OUTCUR;
END NHS_LIS_PATIENTADD;
/
