CREATE OR REPLACE FUNCTION NHS_LIS_SLIPMBLINK(V_SLPNO IN VARCHAR2)
  RETURN TYPES.CURSOR_TYPE AS

  OUTCUR TYPES.CURSOR_TYPE;
BEGIN
  OPEN OUTCUR FOR
    SELECT S.SLPNO
      FROM SLIP S
     WHERE S.PATNO IN (SELECT MB.PATNO_B
                         FROM MBLINK MB, SLIP S
                        WHERE MB.PATNO_M = S.PATNO
                          AND S.SLPNO = V_SLPNO);
  RETURN OUTCUR;
END NHS_LIS_SLIPMBLINK;
/
