create or replace
FUNCTION                "NHS_GET_FINESTHOSP" (
	V_FROM IN VARCHAR2,
	V_KEY  IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
	V_FESTID VARCHAR2(20);
	V_Count Number;
  v_PROCGOV VARCHAR2(100);

Begin
  
	OPEN OUTCUR FOR
		SELECT 
			Festid, Pbpid, Regid, Slpno, Patno,              
			DOCCODE, fe.PROCCODE,FCG.GOVDESC, DIAGNOSIS, LOS, ACMCODE,            
			AB_BYDRB4ADM, OSB_BE, A_PDBYSTS, B_PDBYSTS, A_SIGN_PAT_LOC,     
			A_SIGN_DOC_LOC, B_SIGN_PAT_LOC, DRRNDDAYSUMMIN1,DRRNDDAYSUMMAX1, PROFEEMIN,          
			PROFEEMAX, ANAESTHETISTFEEMIN, ANAESTHETISTFEEMAX, OTHERMIN1, OTHERMAX1,          
			OTHERMIN2, OTHERMAX2, RMSUMMIN, RMSUMMAX,OTMIN,
      OTMAX,OTHERMIN3, OTHERMAX3, CREATE_DATE, CREATE_USER, 
			Modified_Date,Modified_User
			From Fin_Est_Hosp Fe ,Fin_Code Fc,Fin_Code_Gov Fcg
			Where Fe.Festid = V_Key 
      And Fe.Proccode = Fc.Proccode(+)
      AND FC.GOVCODE = FCG.GOVCODE(+)
      AND ENABLED = -1;

	RETURN OUTCUR;
END NHS_GET_FINESTHOSP;
/
