CREATE OR REPLACE FUNCTION "NHS_LIS_TXNSLIP_AFTERDISCHARGE"(
	i_SlipNo IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
	v_RegID NUMBER;
	v_InpID NUMBER;
	v_InpdDate DATE;
	v_Count NUMBER;
BEGIN
	SELECT COUNT(1) INTO v_Count FROM Slip WHERE SlpNo = i_SlipNo AND RegID IS NOT NULL;
	IF v_Count > 0 THEN
		SELECT RegID INTO v_RegID FROM Slip WHERE SlpNo = i_SlipNo AND RegID IS NOT NULL;
	ELSE
		RETURN NULL;
	END IF;

	SELECT COUNT(1) INTO v_Count FROM Reg WHERE RegID = v_RegID;
	IF v_Count > 0 THEN
		SELECT InpID INTO v_InpID FROM Reg WHERE RegID = v_RegID;
	ELSE
		RETURN NULL;
	END IF;

	SELECT COUNT(1) INTO v_Count FROM InPat WHERE InPID = v_InpID;
	IF v_Count > 0 THEN
		SELECT InpdDate INTO v_InpdDate FROM InPat WHERE InPID = v_InpID;
	ELSE
		RETURN NULL;
	END IF;

	OPEN OUTCUR FOR
		SELECT StnSeq, TO_CHAR(StnTDate, 'DD/MM/YYYY HH24:MI:SS'), ItmCode, StnDesc
		FROM   SlipTX
		WHERE  SlpNo = i_SlipNo
		AND    StnSts in ('N', 'A')
		AND  ( v_InpdDate IS NULL
		OR    (TO_DATE(TO_CHAR(StnTDate, 'DD/MM/YYYY'), 'DD/MM/YYYY') <> StnTDate AND TO_DATE(TO_CHAR(v_InpdDate, 'DD/MM/YYYY'), 'DD/MM/YYYY') <> v_InpdDate AND StnTDate > v_InpdDate)
		OR    (TO_DATE(TO_CHAR(StnTDate, 'DD/MM/YYYY'), 'DD/MM/YYYY') > TO_DATE(TO_CHAR(v_InpdDate, 'DD/MM/YYYY'), 'DD/MM/YYYY')))
		ORDER BY stnseq asc;

	RETURN OUTCUR;
END NHS_LIS_TXNSLIP_AFTERDISCHARGE;
/
