CREATE OR REPLACE FUNCTION "NHS_ACT_SLPTELEMED" (
	i_Action  IN VARCHAR2,
	i_SlpNo   IN VARCHAR2,
	i_TELEMEDURL  IN VARCHAR2,
	i_TELEMEDID  IN VARCHAR2,
	i_TELEMEDPASSCODE  IN VARCHAR2,
	i_USRID  IN VARCHAR2,
	o_errmsg  OUT VARCHAR2
)
  RETURN NUMBER
AS
	o_errcode NUMBER;
	v_Count NUMBER;
BEGIN
	o_errcode := -1;
	o_errmsg := 'OK';

	SELECT COUNT(1) INTO v_Count FROM SLIP_EXTRA WHERE SlpNo = i_SlpNo;
	IF v_Count > 0 THEN
		UPDATE SLIP_EXTRA
		SET    TELEMEDURL = i_TELEMEDURL,
			TELEMEDID = i_TELEMEDID,
			TELEMEDPASSCODE = i_TELEMEDPASSCODE,
			TELEMEDMODUSR = i_USRID,
			TELEMEDMODDT = SYSDATE
		WHERE  SlpNo = i_SlpNo;
	ELSE
		INSERT INTO SLIP_EXTRA (
			SlpNo,
			TELEMEDURL,
			TELEMEDID,
			TELEMEDPASSCODE,
			TELEMEDMODUSR,
			TELEMEDMODDT
		) VALUES (
			i_SlpNo,
			i_TELEMEDURL,
			i_TELEMEDID,
			i_TELEMEDPASSCODE,
			i_USRID,
			SYSDATE
		);
	END IF;

	o_errcode := 0;
	RETURN o_errcode;
EXCEPTION
WHEN OTHERS THEN
	ROLLBACK;
	o_errmsg := 'Cannot save telemedicine details. Error [' || SQLCODE || '] ' || SQLERRM;
	RETURN -999;
END NHS_ACT_SLPTELEMED;
/
