CREATE OR REPLACE FUNCTION "NHS_ACT_UPDATESLIP" (
	v_action    IN VARCHAR2,
	v_slpno     IN VARCHAR2,
	o_errmsg    OUT VARCHAR2
)
	RETURN NUMBER
AS
	O_ERRCODE NUMBER;
	v_noOfRec NUMBER;
BEGIN
	O_ERRCODE := 0;
	O_ERRMSG := 'OK';

	NHS_UTL_UPDATESLIP(v_slpno);

	RETURN o_errcode;
END NHS_ACT_UPDATESLIP;
/
