create or replace FUNCTION "NHS_GET_DESCMAPPING" (
  V_ID IN VARCHAR2
)
	RETURN VARCHAR2
AS
  V_DESC VARCHAR(200);
begin


		SELECT DESCRIPTION into V_DESC from DESCRIPTION_MAPPING where TYPE||'.'||ID = V_ID;


	RETURN V_DESC;
end NHS_GET_DESCMAPPING;
/
