create or replace
FUNCTION "NHS_ACT_SPECOMDTL"(
  V_ACTION		IN VARCHAR2,
  V_SLPTYPE   IN SPECOMDTL.SLPTYPE%TYPE,
  V_SYDSTS    IN SPECOMDTL.SYDSTS%TYPE,
  V_SLPNO     IN SPECOMDTL.SLPNO%TYPE,
  V_STNID     IN SPECOMDTL.STNID%TYPE,
  V_DOCCODE   IN SPECOMDTL.DOCCODE%TYPE,
  V_PCYID     IN SPECOMDTL.PCYID%TYPE,
  V_STNTYPE   IN SPECOMDTL.STNTYPE%TYPE,
  V_PAYREF    IN SPECOMDTL.PAYREF%TYPE,
  V_SYDAAMT   IN SPECOMDTL.SYDAAMT%TYPE,
  V_STNXREF   IN VARCHAR2,
  V_PAYKEY    IN VARCHAR2,
  O_ERRMSG		OUT VARCHAR2)
RETURN NUMBER
AS
  O_ERRCODE		NUMBER;
  V_SYDID     NUMBER;
  V_CTNCTYPE  SPECOMDTL.CTNCTYPE%TYPE;
  V_CRARATE   SPECOMDTL.CRARATE%TYPE;
  V_LCTNID    CASHTX.CTNID%TYPE;
BEGIN
  O_ERRCODE := 0;
  O_ERRMSG := 'OK';
  
  SELECT SEQ_SPECOMDTL.NEXTVAL INTO V_SYDID FROM DUAL; 
  
  IF V_STNTYPE = 'S' OR (V_STNTYPE = 'R' AND V_STNXREF IS NOT NULL AND LENGTH(V_STNXREF) > 0) THEN
    SELECT CRANAME, CRARATE INTO V_CTNCTYPE, V_CRARATE
    FROM CASHTX CTX, CARDTX CTN, CARDRATE CR
    WHERE CTXID = V_STNXREF
    AND CTX.CTNID = CTN.CTNID
    AND (
          (CTX.CTXMETH <> 'E' AND UPPER(RTRIM(CTN.CTNCTYPE)) = CR.CRANAME) OR
          (CTX.CTXMETH = 'E' AND CR.CRANAME = 'EPS')
        );
  ELSIF V_STNTYPE = 'P' THEN
    SELECT CTNID INTO V_LCTNID
    FROM CASHTX
    WHERE CTXSNO = (SELECT ARPTX.ARPRECNO 
                    FROM ARPTX, ARTX
                    WHERE ARPTX.ARPID = ARTX.ARPID
                    AND ARTX.ATXID = V_PAYREF);
    
    IF V_LCTNID IS NOT NULL AND LENGTH(V_LCTNID) > 0 THEN
        SELECT UPPER(TRIM(TO_CHAR(CTNCTYPE))) INTO V_CTNCTYPE
        FROM CARDTX
        WHERE CTNID = V_LCTNID;
        
        SELECT CRARATE INTO V_CRARATE
        FROM CARDRATE
        WHERE CRANAME = V_CTNCTYPE;
    ELSE
      V_CTNCTYPE := NULL;
      V_CRARATE := NULL;
    END IF;
  ELSIF V_STNTYPE = 'I' THEN
    SELECT PAYMETHOD, CARDRATE INTO V_CTNCTYPE, V_CRARATE
    FROM SLIPTX
    WHERE STNID = V_PAYKEY;
    
    IF LENGTH(V_CRARATE) <= 0 OR LENGTH(V_CTNCTYPE) <= 0 THEN
      V_CRARATE := NULL;
    END IF;
  ELSE 
    V_CTNCTYPE := NULL;
    V_CRARATE := NULL;
  END IF;

  INSERT INTO 
  SPECOMDTL(SYDID, 
            SLPTYPE, 
            SYDSTS, 
            SLPNO, 
            STNID, 
            DOCCODE, 
            SYDCDATE, 
            PCYID, 
            STNTYPE, 
            PAYREF, 
            SYDAAMT,
            CTNCTYPE,
            CRARATE) 
  VALUES(V_SYDID, 
          V_SLPTYPE, 
          V_SYDSTS, 
          V_SLPNO, 
          V_STNID, 
          V_DOCCODE, 
          SYSDATE, 
          V_PCYID, 
          V_STNTYPE, 
          V_PAYREF, 
          V_SYDAAMT,
          V_CTNCTYPE,
          V_CRARATE);
          
  RETURN O_ERRCODE;
END NHS_ACT_SPECOMDTL;
/