package hk.gov.ehr.epis.transform.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.0
 * 2015-06-30T10:42:55.053+08:00
 * Generated source version: 3.1.0
 * 
 */
@WebServiceClient(name = "EpisDataTransformResourceService", 
                  wsdlLocation = "EpisDataTransformWebS.wsdl",
                  targetNamespace = "http://ehr.gov.hk/epis/transform/ws") 
public class EpisDataTransformResourceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ehr.gov.hk/epis/transform/ws", "EpisDataTransformResourceService");
    public final static QName EpisDataTransformResourceSoap11 = new QName("http://ehr.gov.hk/epis/transform/ws", "EpisDataTransformResourceSoap11");
    static {
        URL url = null;
        try {
            url = new URL("http://160.100.2.73:9081/hepr/ws/transform/epis/EpisDataTransformWebS.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EpisDataTransformResourceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://160.100.2.73:9081/hepr/ws/transform/epis/EpisDataTransformWebS.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EpisDataTransformResourceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EpisDataTransformResourceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EpisDataTransformResourceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public EpisDataTransformResourceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public EpisDataTransformResourceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public EpisDataTransformResourceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns EpisDataTransformResource
     */
    @WebEndpoint(name = "EpisDataTransformResourceSoap11")
    public EpisDataTransformResource getEpisDataTransformResourceSoap11() {
        return super.getPort(EpisDataTransformResourceSoap11, EpisDataTransformResource.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EpisDataTransformResource
     */
    @WebEndpoint(name = "EpisDataTransformResourceSoap11")
    public EpisDataTransformResource getEpisDataTransformResourceSoap11(WebServiceFeature... features) {
        return super.getPort(EpisDataTransformResourceSoap11, EpisDataTransformResource.class, features);
    }

}
