
package hk.gov.ehr.alert.ws.beans;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.0
 * 2016-05-26T14:56:54.199+08:00
 * Generated source version: 3.1.0
 * 
 */
public final class AlertResource_AlertResourceSoap11_Client {

    private static final QName SERVICE_NAME = new QName("http://ehr.gov.hk/alert/ws/beans", "AlertResourceService");

    private AlertResource_AlertResourceSoap11_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AlertResourceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        AlertResourceService ss = new AlertResourceService(wsdlURL, SERVICE_NAME);
        AlertResource port = ss.getAlertResourceSoap11();  
        
        {
        System.out.println("Invoking getExistingPatientAllergyLog...");
        hk.gov.ehr.alert.ws.beans.AllergyLogRequest _getExistingPatientAllergyLog_getExistingPatientAllergyLogRequest = new hk.gov.ehr.alert.ws.beans.AllergyLogRequest();
        _getExistingPatientAllergyLog_getExistingPatientAllergyLogRequest.setRefKey("RefKey-353511715");
        hk.gov.ehr.alert.ws.beans.AllergyLogResponse _getExistingPatientAllergyLog__return = port.getExistingPatientAllergyLog(_getExistingPatientAllergyLog_getExistingPatientAllergyLogRequest);
        System.out.println("getExistingPatientAllergyLog.result=" + _getExistingPatientAllergyLog__return);


        }
        {
        System.out.println("Invoking getPatientSummaryByPatientRefKey...");
        hk.gov.ehr.alert.ws.beans.SummaryRequest _getPatientSummaryByPatientRefKey_getPatientSummaryByPatientRefKeyRequest = new hk.gov.ehr.alert.ws.beans.SummaryRequest();
        _getPatientSummaryByPatientRefKey_getPatientSummaryByPatientRefKeyRequest.setRefKey("RefKey-1345593681");
        hk.gov.ehr.alert.ws.beans.SummaryResponse _getPatientSummaryByPatientRefKey__return = port.getPatientSummaryByPatientRefKey(_getPatientSummaryByPatientRefKey_getPatientSummaryByPatientRefKeyRequest);
        System.out.println("getPatientSummaryByPatientRefKey.result=" + _getPatientSummaryByPatientRefKey__return);


        }
        {
        System.out.println("Invoking handlePatientAlert...");
        hk.gov.ehr.alert.ws.beans.HandlePatientAlertRequest _handlePatientAlert_handlePatientAlertRequest = new hk.gov.ehr.alert.ws.beans.HandlePatientAlertRequest();
        hk.gov.ehr.alert.ws.beans.AlertDTO _handlePatientAlert_handlePatientAlertRequestAlertDTO = new hk.gov.ehr.alert.ws.beans.AlertDTO();
        _handlePatientAlert_handlePatientAlertRequestAlertDTO.setAlertSeqNo("AlertSeqNo-1271326269");
        _handlePatientAlert_handlePatientAlertRequestAlertDTO.setAlertCode("AlertCode1972982655");
        _handlePatientAlert_handlePatientAlertRequestAlertDTO.setAlertDesc("AlertDesc-1480728246");
        _handlePatientAlert_handlePatientAlertRequestAlertDTO.setPatientKey("PatientKey-723997319");
        _handlePatientAlert_handlePatientAlertRequestAlertDTO.setAdditionInfo("AdditionInfo-318571207");
        _handlePatientAlert_handlePatientAlertRequestAlertDTO.setCategoryDesc("CategoryDesc-922343972");
        _handlePatientAlert_handlePatientAlertRequestAlertDTO.setClassifiedIndicator("ClassifiedIndicator1869051555");
        _handlePatientAlert_handlePatientAlertRequestAlertDTO.setValidFrom(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-05-26T14:56:54.269+08:00"));
        _handlePatientAlert_handlePatientAlertRequestAlertDTO.setValidTo(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-05-26T14:56:54.279+08:00"));
        _handlePatientAlert_handlePatientAlertRequestAlertDTO.setHospitalCode("HospitalCode-1599546064");
        _handlePatientAlert_handlePatientAlertRequestAlertDTO.setMigrateData(false);
        _handlePatientAlert_handlePatientAlertRequestAlertDTO.setSourceSystem("SourceSystem1645556957");
        _handlePatientAlert_handlePatientAlertRequestAlertDTO.setCreateDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-05-26T14:56:54.279+08:00"));
        _handlePatientAlert_handlePatientAlertRequestAlertDTO.setUser("User2142487332");
        _handlePatientAlert_handlePatientAlertRequestAlertDTO.setUserHosp("UserHosp-1068545092");
        _handlePatientAlert_handlePatientAlertRequestAlertDTO.setUserId("UserId1285006236");
        _handlePatientAlert_handlePatientAlertRequestAlertDTO.setUserRank("UserRank341445059");
        _handlePatientAlert_handlePatientAlertRequestAlertDTO.setUserRankDesc("UserRankDesc-1240988186");
        _handlePatientAlert_handlePatientAlertRequestAlertDTO.setDeleteReason("DeleteReason763582973");
        _handlePatientAlert_handlePatientAlertRequestAlertDTO.setUpdateBy("UpdateBy1174977567");
        _handlePatientAlert_handlePatientAlertRequestAlertDTO.setUpdateDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-05-26T14:56:54.279+08:00"));
        _handlePatientAlert_handlePatientAlertRequestAlertDTO.setUpdateHosp("UpdateHosp1463269216");
        _handlePatientAlert_handlePatientAlertRequestAlertDTO.setUpdateRank("UpdateRank-1334643031");
        _handlePatientAlert_handlePatientAlertRequestAlertDTO.setUpdateRankDesc("UpdateRankDesc326326343");
        _handlePatientAlert_handlePatientAlertRequestAlertDTO.setUpdateUser("UpdateUser1013173443");
        _handlePatientAlert_handlePatientAlertRequestAlertDTO.setAlertType("AlertType-1813258846");
        _handlePatientAlert_handlePatientAlertRequestAlertDTO.setVersion(Integer.valueOf(-1845214254));
        _handlePatientAlert_handlePatientAlertRequest.setAlertDTO(_handlePatientAlert_handlePatientAlertRequestAlertDTO);
        hk.gov.ehr.alert.ws.beans.AuditDTO _handlePatientAlert_handlePatientAlertRequestAuditDTO = new hk.gov.ehr.alert.ws.beans.AuditDTO();
        _handlePatientAlert_handlePatientAlertRequestAuditDTO.setWorkstationId("WorkstationId-1494432243");
        _handlePatientAlert_handlePatientAlertRequestAuditDTO.setLoginId("LoginId-2091326481");
        _handlePatientAlert_handlePatientAlertRequestAuditDTO.setHkId("HkId-737291664");
        _handlePatientAlert_handlePatientAlertRequestAuditDTO.setMrn("Mrn152005814");
        _handlePatientAlert_handlePatientAlertRequestAuditDTO.setWorkstationIpAddress("WorkstationIpAddress261904603");
        _handlePatientAlert_handlePatientAlertRequest.setAuditDTO(_handlePatientAlert_handlePatientAlertRequestAuditDTO);
        _handlePatientAlert_handlePatientAlertRequest.setActionType("ActionType-1456866445");
        hk.gov.ehr.alert.ws.beans.ResponseBean _handlePatientAlert__return = port.handlePatientAlert(_handlePatientAlert_handlePatientAlertRequest);
        System.out.println("handlePatientAlert.result=" + _handlePatientAlert__return);


        }
        {
        System.out.println("Invoking updatePatientAllergy...");
        hk.gov.ehr.alert.ws.beans.UpdatePatientAllergyRequest _updatePatientAllergy_updatePatientAllergyRequest = new hk.gov.ehr.alert.ws.beans.UpdatePatientAllergyRequest();
        hk.gov.ehr.alert.ws.beans.AllergyDTO _updatePatientAllergy_updatePatientAllergyRequestAllergyDTO = new hk.gov.ehr.alert.ws.beans.AllergyDTO();
        _updatePatientAllergy_updatePatientAllergyRequestAllergyDTO.setAllergySeqNo("AllergySeqNo412550072");
        _updatePatientAllergy_updatePatientAllergyRequestAllergyDTO.setPatientKey("PatientKey-1471448040");
        _updatePatientAllergy_updatePatientAllergyRequestAllergyDTO.setDisplayName("DisplayName1171455625");
        _updatePatientAllergy_updatePatientAllergyRequestAllergyDTO.setShortDisplayName("ShortDisplayName58171559");
        _updatePatientAllergy_updatePatientAllergyRequestAllergyDTO.setAllergenType("AllergenType1699145416");
        hk.gov.ehr.alert.ws.beans.AllergenDTO _updatePatientAllergy_updatePatientAllergyRequestAllergyDTOAllergenDTO = new hk.gov.ehr.alert.ws.beans.AllergenDTO();
        _updatePatientAllergy_updatePatientAllergyRequestAllergyDTOAllergenDTO.setAllergenId("AllergenId47539952");
        _updatePatientAllergy_updatePatientAllergyRequestAllergyDTOAllergenDTO.setVtm("Vtm1968983725");
        _updatePatientAllergy_updatePatientAllergyRequestAllergyDTOAllergenDTO.setTradeName("TradeName-1653769516");
        _updatePatientAllergy_updatePatientAllergyRequestAllergyDTOAllergenDTO.setBan("Ban-964294435");
        _updatePatientAllergy_updatePatientAllergyRequestAllergyDTOAllergenDTO.setAbbreviation("Abbreviation-818736274");
        _updatePatientAllergy_updatePatientAllergyRequestAllergyDTOAllergenDTO.setOtherName("OtherName-1916395695");
        _updatePatientAllergy_updatePatientAllergyRequestAllergyDTOAllergenDTO.setDisplayNameType("DisplayNameType600200145");
        _updatePatientAllergy_updatePatientAllergyRequestAllergyDTOAllergenDTO.setDisplayName("DisplayName-1643047687");
        _updatePatientAllergy_updatePatientAllergyRequestAllergyDTOAllergenDTO.setShortDisplayName("ShortDisplayName1792101437");
        _updatePatientAllergy_updatePatientAllergyRequestAllergyDTO.setAllergenDTO(_updatePatientAllergy_updatePatientAllergyRequestAllergyDTOAllergenDTO);
        _updatePatientAllergy_updatePatientAllergyRequestAllergyDTO.setAllergenCode("AllergenCode-1572851483");
        _updatePatientAllergy_updatePatientAllergyRequestAllergyDTO.setCertainty("Certainty-931821839");
        _updatePatientAllergy_updatePatientAllergyRequestAllergyDTO.setAdditionInfo("AdditionInfo-1108483335");
        _updatePatientAllergy_updatePatientAllergyRequestAllergyDTO.setHospitalCode("HospitalCode-1101585396");
        _updatePatientAllergy_updatePatientAllergyRequestAllergyDTO.setSourceSystem("SourceSystem1110844791");
        _updatePatientAllergy_updatePatientAllergyRequestAllergyDTO.setCreateDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-05-26T14:56:54.279+08:00"));
        _updatePatientAllergy_updatePatientAllergyRequestAllergyDTO.setUserId("UserId1279130140");
        _updatePatientAllergy_updatePatientAllergyRequestAllergyDTO.setUser("User112845798");
        _updatePatientAllergy_updatePatientAllergyRequestAllergyDTO.setUserHosp("UserHosp-808612535");
        _updatePatientAllergy_updatePatientAllergyRequestAllergyDTO.setUserRank("UserRank657798944");
        _updatePatientAllergy_updatePatientAllergyRequestAllergyDTO.setUserRankDesc("UserRankDesc912065851");
        _updatePatientAllergy_updatePatientAllergyRequestAllergyDTO.setDeleteReason("DeleteReason-1350402166");
        _updatePatientAllergy_updatePatientAllergyRequestAllergyDTO.setUpdateBy("UpdateBy1514285615");
        _updatePatientAllergy_updatePatientAllergyRequestAllergyDTO.setUpdateDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-05-26T14:56:54.279+08:00"));
        _updatePatientAllergy_updatePatientAllergyRequestAllergyDTO.setUpdateUser("UpdateUser1204969921");
        _updatePatientAllergy_updatePatientAllergyRequestAllergyDTO.setUpdateRank("UpdateRank871492569");
        _updatePatientAllergy_updatePatientAllergyRequestAllergyDTO.setUpdateRankDesc("UpdateRankDesc927807302");
        _updatePatientAllergy_updatePatientAllergyRequestAllergyDTO.setUpdateHosp("UpdateHosp-411526910");
        java.util.List<hk.gov.ehr.alert.ws.beans.ManifestBean> _updatePatientAllergy_updatePatientAllergyRequestAllergyDTOManifestBean = new java.util.ArrayList<hk.gov.ehr.alert.ws.beans.ManifestBean>();
        hk.gov.ehr.alert.ws.beans.ManifestBean _updatePatientAllergy_updatePatientAllergyRequestAllergyDTOManifestBeanVal1 = new hk.gov.ehr.alert.ws.beans.ManifestBean();
        _updatePatientAllergy_updatePatientAllergyRequestAllergyDTOManifestBeanVal1.setManifestationSeqNo("ManifestationSeqNo1499263983");
        _updatePatientAllergy_updatePatientAllergyRequestAllergyDTOManifestBeanVal1.setManifestationDesc("ManifestationDesc-131019514");
        _updatePatientAllergy_updatePatientAllergyRequestAllergyDTOManifestBeanVal1.setListType("ListType2088673827");
        _updatePatientAllergy_updatePatientAllergyRequestAllergyDTOManifestBeanVal1.setStatus("Status128827545");
        _updatePatientAllergy_updatePatientAllergyRequestAllergyDTOManifestBean.add(_updatePatientAllergy_updatePatientAllergyRequestAllergyDTOManifestBeanVal1);
        _updatePatientAllergy_updatePatientAllergyRequestAllergyDTO.getManifestBean().addAll(_updatePatientAllergy_updatePatientAllergyRequestAllergyDTOManifestBean);
        _updatePatientAllergy_updatePatientAllergyRequestAllergyDTO.setMigrateData(false);
        _updatePatientAllergy_updatePatientAllergyRequestAllergyDTO.setVersion(Integer.valueOf(1039805823));
        hk.gov.ehr.alert.ws.beans.AllergyTermDTO _updatePatientAllergy_updatePatientAllergyRequestAllergyDTOAllergyTermDTO = new hk.gov.ehr.alert.ws.beans.AllergyTermDTO();
        _updatePatientAllergy_updatePatientAllergyRequestAllergyDTOAllergyTermDTO.setAllergySeqNo("AllergySeqNo564958758");
        _updatePatientAllergy_updatePatientAllergyRequestAllergyDTOAllergyTermDTO.setTermId(27582749);
        _updatePatientAllergy_updatePatientAllergyRequestAllergyDTOAllergyTermDTO.setTermDesc("TermDesc240795478");
        _updatePatientAllergy_updatePatientAllergyRequestAllergyDTO.setAllergyTermDTO(_updatePatientAllergy_updatePatientAllergyRequestAllergyDTOAllergyTermDTO);
        _updatePatientAllergy_updatePatientAllergyRequest.setAllergyDTO(_updatePatientAllergy_updatePatientAllergyRequestAllergyDTO);
        hk.gov.ehr.alert.ws.beans.AuditDTO _updatePatientAllergy_updatePatientAllergyRequestAuditDTO = new hk.gov.ehr.alert.ws.beans.AuditDTO();
        _updatePatientAllergy_updatePatientAllergyRequestAuditDTO.setWorkstationId("WorkstationId-1721860085");
        _updatePatientAllergy_updatePatientAllergyRequestAuditDTO.setLoginId("LoginId1666781927");
        _updatePatientAllergy_updatePatientAllergyRequestAuditDTO.setHkId("HkId1517186319");
        _updatePatientAllergy_updatePatientAllergyRequestAuditDTO.setMrn("Mrn1128448355");
        _updatePatientAllergy_updatePatientAllergyRequestAuditDTO.setWorkstationIpAddress("WorkstationIpAddress505892903");
        _updatePatientAllergy_updatePatientAllergyRequest.setAuditDTO(_updatePatientAllergy_updatePatientAllergyRequestAuditDTO);
        hk.gov.ehr.alert.ws.beans.ResponseBean _updatePatientAllergy__return = port.updatePatientAllergy(_updatePatientAllergy_updatePatientAllergyRequest);
        System.out.println("updatePatientAllergy.result=" + _updatePatientAllergy__return);


        }
        {
        System.out.println("Invoking hasMigrateData...");
        hk.gov.ehr.alert.ws.beans.HasMigrateDataRequest _hasMigrateData_hasMigrateDataRequest = new hk.gov.ehr.alert.ws.beans.HasMigrateDataRequest();
        _hasMigrateData_hasMigrateDataRequest.setRefKey("RefKey-1009204892");
        hk.gov.ehr.alert.ws.beans.HasMigrateDataResponse _hasMigrateData__return = port.hasMigrateData(_hasMigrateData_hasMigrateDataRequest);
        System.out.println("hasMigrateData.result=" + _hasMigrateData__return);


        }
        {
        System.out.println("Invoking hasStructuredMigrateData...");
        hk.gov.ehr.alert.ws.beans.HasStructMigrateDataRequest _hasStructuredMigrateData_hasStructuredMigrateDataRequest = new hk.gov.ehr.alert.ws.beans.HasStructMigrateDataRequest();
        _hasStructuredMigrateData_hasStructuredMigrateDataRequest.setRefKey("RefKey-858460529");
        hk.gov.ehr.alert.ws.beans.HasStructMigrateDataResponse _hasStructuredMigrateData__return = port.hasStructuredMigrateData(_hasStructuredMigrateData_hasStructuredMigrateDataRequest);
        System.out.println("hasStructuredMigrateData.result=" + _hasStructuredMigrateData__return);


        }
        {
        System.out.println("Invoking getPatientAdrLog...");
        hk.gov.ehr.alert.ws.beans.AdrLogRequest _getPatientAdrLog_getPatientAdrLogRequest = new hk.gov.ehr.alert.ws.beans.AdrLogRequest();
        _getPatientAdrLog_getPatientAdrLogRequest.setRefKey("RefKey207679822");
        hk.gov.ehr.alert.ws.beans.AdrLogResponse _getPatientAdrLog__return = port.getPatientAdrLog(_getPatientAdrLog_getPatientAdrLogRequest);
        System.out.println("getPatientAdrLog.result=" + _getPatientAdrLog__return);


        }
        {
        System.out.println("Invoking handleLocalEMRDownloadPatientAdrAndAllergy...");
        hk.gov.ehr.alert.ws.beans.LocalEMRDownloadRequestBean _handleLocalEMRDownloadPatientAdrAndAllergy_handleLocalEMRDownloadPatientAdrAndAllergyRequest = new hk.gov.ehr.alert.ws.beans.LocalEMRDownloadRequestBean();
        _handleLocalEMRDownloadPatientAdrAndAllergy_handleLocalEMRDownloadPatientAdrAndAllergyRequest.setSource("Source-436866331");
        hk.gov.ehr.alert.ws.beans.common.EhrPatientDTO _handleLocalEMRDownloadPatientAdrAndAllergy_handleLocalEMRDownloadPatientAdrAndAllergyRequestEhrPatientDTO = new hk.gov.ehr.alert.ws.beans.common.EhrPatientDTO();
        _handleLocalEMRDownloadPatientAdrAndAllergy_handleLocalEMRDownloadPatientAdrAndAllergyRequestEhrPatientDTO.setEhrNo("EhrNo-2088690414");
        _handleLocalEMRDownloadPatientAdrAndAllergy_handleLocalEMRDownloadPatientAdrAndAllergyRequestEhrPatientDTO.setHkid("Hkid610041050");
        _handleLocalEMRDownloadPatientAdrAndAllergy_handleLocalEMRDownloadPatientAdrAndAllergyRequestEhrPatientDTO.setDocType("DocType-168915124");
        _handleLocalEMRDownloadPatientAdrAndAllergy_handleLocalEMRDownloadPatientAdrAndAllergyRequestEhrPatientDTO.setDocNum("DocNum-1088298480");
        _handleLocalEMRDownloadPatientAdrAndAllergy_handleLocalEMRDownloadPatientAdrAndAllergyRequestEhrPatientDTO.setPersonEngSurName("PersonEngSurName409442869");
        _handleLocalEMRDownloadPatientAdrAndAllergy_handleLocalEMRDownloadPatientAdrAndAllergyRequestEhrPatientDTO.setPersonEngGivenName("PersonEngGivenName595953172");
        _handleLocalEMRDownloadPatientAdrAndAllergy_handleLocalEMRDownloadPatientAdrAndAllergyRequestEhrPatientDTO.setPersonEngFullName("PersonEngFullName-1248695229");
        _handleLocalEMRDownloadPatientAdrAndAllergy_handleLocalEMRDownloadPatientAdrAndAllergyRequestEhrPatientDTO.setSex("Sex-1283512940");
        _handleLocalEMRDownloadPatientAdrAndAllergy_handleLocalEMRDownloadPatientAdrAndAllergyRequestEhrPatientDTO.setBirthDate("BirthDate-1279500944");
        _handleLocalEMRDownloadPatientAdrAndAllergy_handleLocalEMRDownloadPatientAdrAndAllergyRequest.setEhrPatientDTO(_handleLocalEMRDownloadPatientAdrAndAllergy_handleLocalEMRDownloadPatientAdrAndAllergyRequestEhrPatientDTO);
        hk.gov.ehr.alert.ws.beans.AuditDTO _handleLocalEMRDownloadPatientAdrAndAllergy_handleLocalEMRDownloadPatientAdrAndAllergyRequestAuditDTO = new hk.gov.ehr.alert.ws.beans.AuditDTO();
        _handleLocalEMRDownloadPatientAdrAndAllergy_handleLocalEMRDownloadPatientAdrAndAllergyRequestAuditDTO.setWorkstationId("WorkstationId1623978311");
        _handleLocalEMRDownloadPatientAdrAndAllergy_handleLocalEMRDownloadPatientAdrAndAllergyRequestAuditDTO.setLoginId("LoginId1329692027");
        _handleLocalEMRDownloadPatientAdrAndAllergy_handleLocalEMRDownloadPatientAdrAndAllergyRequestAuditDTO.setHkId("HkId903311132");
        _handleLocalEMRDownloadPatientAdrAndAllergy_handleLocalEMRDownloadPatientAdrAndAllergyRequestAuditDTO.setMrn("Mrn543185055");
        _handleLocalEMRDownloadPatientAdrAndAllergy_handleLocalEMRDownloadPatientAdrAndAllergyRequestAuditDTO.setWorkstationIpAddress("WorkstationIpAddress1441258667");
        _handleLocalEMRDownloadPatientAdrAndAllergy_handleLocalEMRDownloadPatientAdrAndAllergyRequest.setAuditDTO(_handleLocalEMRDownloadPatientAdrAndAllergy_handleLocalEMRDownloadPatientAdrAndAllergyRequestAuditDTO);
        hk.gov.ehr.alert.ws.beans.LocalEMRDownloadResponseBean _handleLocalEMRDownloadPatientAdrAndAllergy__return = port.handleLocalEMRDownloadPatientAdrAndAllergy(_handleLocalEMRDownloadPatientAdrAndAllergy_handleLocalEMRDownloadPatientAdrAndAllergyRequest);
        System.out.println("handleLocalEMRDownloadPatientAdrAndAllergy.result=" + _handleLocalEMRDownloadPatientAdrAndAllergy__return);


        }
        {
        System.out.println("Invoking getPatientLog...");
        hk.gov.ehr.alert.ws.beans.LogRequest _getPatientLog_getPatientLogRequest = new hk.gov.ehr.alert.ws.beans.LogRequest();
        _getPatientLog_getPatientLogRequest.setRefKey("RefKey493942678");
        hk.gov.ehr.alert.ws.beans.LogResponse _getPatientLog__return = port.getPatientLog(_getPatientLog_getPatientLogRequest);
        System.out.println("getPatientLog.result=" + _getPatientLog__return);


        }
        {
        System.out.println("Invoking hasFreeTextMigrateData...");
        hk.gov.ehr.alert.ws.beans.HasFreeMigrateDataRequest _hasFreeTextMigrateData_hasFreeTextMigrateDataRequest = new hk.gov.ehr.alert.ws.beans.HasFreeMigrateDataRequest();
        _hasFreeTextMigrateData_hasFreeTextMigrateDataRequest.setRefKey("RefKey342281213");
        hk.gov.ehr.alert.ws.beans.HasFreeMigrateDataResponse _hasFreeTextMigrateData__return = port.hasFreeTextMigrateData(_hasFreeTextMigrateData_hasFreeTextMigrateDataRequest);
        System.out.println("hasFreeTextMigrateData.result=" + _hasFreeTextMigrateData__return);


        }
        {
        System.out.println("Invoking getExistingPatientAdrLog...");
        hk.gov.ehr.alert.ws.beans.AdrLogRequest _getExistingPatientAdrLog_getExistingPatientAdrLogRequest = new hk.gov.ehr.alert.ws.beans.AdrLogRequest();
        _getExistingPatientAdrLog_getExistingPatientAdrLogRequest.setRefKey("RefKey-1073749788");
        hk.gov.ehr.alert.ws.beans.AdrLogResponse _getExistingPatientAdrLog__return = port.getExistingPatientAdrLog(_getExistingPatientAdrLog_getExistingPatientAdrLogRequest);
        System.out.println("getExistingPatientAdrLog.result=" + _getExistingPatientAdrLog__return);


        }
        {
        System.out.println("Invoking getPatientAllergy...");
        hk.gov.ehr.alert.ws.beans.AllergyRequest _getPatientAllergy_getPatientAllergyRequest = new hk.gov.ehr.alert.ws.beans.AllergyRequest();
        _getPatientAllergy_getPatientAllergyRequest.setRefKey("RefKey-1184531417");
        hk.gov.ehr.alert.ws.beans.AllergyResponse _getPatientAllergy__return = port.getPatientAllergy(_getPatientAllergy_getPatientAllergyRequest);
        System.out.println("getPatientAllergy.result=" + _getPatientAllergy__return);


        }
        {
        System.out.println("Invoking getPatientAllergyLogByPeriod...");
        hk.gov.ehr.alert.ws.beans.PatientLogByPeriodRequest _getPatientAllergyLogByPeriod_getPatientAllergyLogByPeriodRequest = new hk.gov.ehr.alert.ws.beans.PatientLogByPeriodRequest();
        _getPatientAllergyLogByPeriod_getPatientAllergyLogByPeriodRequest.setRefKey("RefKey39494845");
        _getPatientAllergyLogByPeriod_getPatientAllergyLogByPeriodRequest.setStartTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-05-26T14:56:54.289+08:00"));
        _getPatientAllergyLogByPeriod_getPatientAllergyLogByPeriodRequest.setEndTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-05-26T14:56:54.289+08:00"));
        hk.gov.ehr.alert.ws.beans.AllergyLogResponse _getPatientAllergyLogByPeriod__return = port.getPatientAllergyLogByPeriod(_getPatientAllergyLogByPeriod_getPatientAllergyLogByPeriodRequest);
        System.out.println("getPatientAllergyLogByPeriod.result=" + _getPatientAllergyLogByPeriod__return);


        }
        {
        System.out.println("Invoking getPatientAdr...");
        hk.gov.ehr.alert.ws.beans.AdrRequest _getPatientAdr_getPatientAdrRequest = new hk.gov.ehr.alert.ws.beans.AdrRequest();
        _getPatientAdr_getPatientAdrRequest.setRefKey("RefKey1750536530");
        hk.gov.ehr.alert.ws.beans.AdrResponse _getPatientAdr__return = port.getPatientAdr(_getPatientAdr_getPatientAdrRequest);
        System.out.println("getPatientAdr.result=" + _getPatientAdr__return);


        }
        {
        System.out.println("Invoking insertNkda...");
        hk.gov.ehr.alert.ws.beans.InsertNkdaRequest _insertNkda_insertNkdaRequest = new hk.gov.ehr.alert.ws.beans.InsertNkdaRequest();
        _insertNkda_insertNkdaRequest.setRefKey("RefKey1324880384");
        _insertNkda_insertNkdaRequest.setUserId("UserId1744690199");
        _insertNkda_insertNkdaRequest.setUser("User108259868");
        _insertNkda_insertNkdaRequest.setUserRank("UserRank-1673304473");
        _insertNkda_insertNkdaRequest.setUserRankDesc("UserRankDesc618566371");
        _insertNkda_insertNkdaRequest.setHospitalCode("HospitalCode1769114703");
        _insertNkda_insertNkdaRequest.setSourceSystem("SourceSystem-448057201");
        hk.gov.ehr.alert.ws.beans.InsertNkdaResponse _insertNkda__return = port.insertNkda(_insertNkda_insertNkdaRequest);
        System.out.println("insertNkda.result=" + _insertNkda__return);


        }
        {
        System.out.println("Invoking handlePmiPatientLogUpdate...");
        hk.gov.ehr.alert.ws.beans.PmiPatientLogUpdateRequestBean _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequest = new hk.gov.ehr.alert.ws.beans.PmiPatientLogUpdateRequestBean();
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequest.setSource("Source-260075174");
        hk.gov.ehr.alert.ws.beans.PmiPatientLogDTO _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestPmiPatientLogDTO = new hk.gov.ehr.alert.ws.beans.PmiPatientLogDTO();
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestPmiPatientLogDTO.setEhrNo("EhrNo1961398149");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestPmiPatientLogDTO.setEventCode("EventCode139097952");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestPmiPatientLogDTO.setAction("Action1023845533");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestPmiPatientLogDTO.setTrxDtm(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-05-26T14:56:54.289+08:00"));
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequest.setPmiPatientLogDTO(_handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestPmiPatientLogDTO);
        hk.gov.ehr.alert.ws.beans.download.EhrPatientAdrAndAllergyDownloadResult _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResult = new hk.gov.ehr.alert.ws.beans.download.EhrPatientAdrAndAllergyDownloadResult();
        hk.gov.ehr.alert.ws.beans.download.DownloadStatusDTO _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadStatusDTO = new hk.gov.ehr.alert.ws.beans.download.DownloadStatusDTO();
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadStatusDTO.setEhrNo("EhrNo561310207");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadStatusDTO.setStatusCode("StatusCode1206320118");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadStatusDTO.setStatusDescription("StatusDescription351169049");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResult.setDownloadStatusDTO(_handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadStatusDTO);
        hk.gov.ehr.alert.ws.beans.download.DownloadPatientDTO _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadPatientDTO = new hk.gov.ehr.alert.ws.beans.download.DownloadPatientDTO();
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadPatientDTO.setEhrNo("EhrNo687505828");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadPatientDTO.setHkid("Hkid-1390340348");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadPatientDTO.setDocType("DocType-2040826700");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadPatientDTO.setDocNum("DocNum-1752690864");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadPatientDTO.setPersonEngSurName("PersonEngSurName1685871702");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadPatientDTO.setPersonEngGivenName("PersonEngGivenName-1226770091");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadPatientDTO.setPersonEngFullName("PersonEngFullName-41267140");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadPatientDTO.setSex("Sex-1058118686");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadPatientDTO.setBirthDate("BirthDate-1149493149");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadPatientDTO.setRecordType("RecordType1718905281");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResult.setDownloadPatientDTO(_handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadPatientDTO);
        java.util.List<hk.gov.ehr.alert.ws.beans.download.DownloadAdrDTO> _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAdrDTOArray = new java.util.ArrayList<hk.gov.ehr.alert.ws.beans.download.DownloadAdrDTO>();
        hk.gov.ehr.alert.ws.beans.download.DownloadAdrDTO _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAdrDTOArrayVal1 = new hk.gov.ehr.alert.ws.beans.download.DownloadAdrDTO();
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAdrDTOArrayVal1.setEhrNo("EhrNo1000584675");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAdrDTOArrayVal1.setRecordKey("RecordKey1981212407");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAdrDTOArrayVal1.setEpisodeNo("EpisodeNo-1849510537");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAdrDTOArrayVal1.setHciId("HciId1858972893");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAdrDTOArrayVal1.setHciLongName("HciLongName-429470235");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAdrDTOArrayVal1.setHciShortName("HciShortName2066942602");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAdrDTOArrayVal1.setCausativeAgentRtName("CausativeAgentRtName-482246809");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAdrDTOArrayVal1.setCausativeAgentRtId("CausativeAgentRtId-452345560");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAdrDTOArrayVal1.setCausativeAgentRtDesc("CausativeAgentRtDesc-1707123010");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAdrDTOArrayVal1.setCausativeAgentLtCode("CausativeAgentLtCode-267016152");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAdrDTOArrayVal1.setCausativeAgentLtDesc("CausativeAgentLtDesc-19059290");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAdrDTOArrayVal1.setCausativeAgentTermId("CausativeAgentTermId-702747793");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAdrDTOArrayVal1.setCausativeAgentEhrDesc("CausativeAgentEhrDesc-821072968");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAdrDTOArrayVal1.setCausativeAgentVtmTermId("CausativeAgentVtmTermId1727299063");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAdrDTOArrayVal1.setCausativeAgentVtmEhrDesc("CausativeAgentVtmEhrDesc-992899587");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAdrDTOArrayVal1.setLevelOfSeverityCode("LevelOfSeverityCode-594467469");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAdrDTOArrayVal1.setLevelOfSeverityDesc("LevelOfSeverityDesc-388257595");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAdrDTOArrayVal1.setLevelOfSeverityLtDesc("LevelOfSeverityLtDesc-1923745799");
        java.util.List<hk.gov.ehr.alert.ws.beans.download.DownloadReactionDTO> _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAdrDTOArrayVal1DownloadReactionDTOArray = new java.util.ArrayList<hk.gov.ehr.alert.ws.beans.download.DownloadReactionDTO>();
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAdrDTOArrayVal1.getDownloadReactionDTOArray().addAll(_handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAdrDTOArrayVal1DownloadReactionDTOArray);
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAdrDTOArrayVal1.setDeleteReason("DeleteReason-1183623557");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAdrDTOArrayVal1.setCausativeAgentRemark("CausativeAgentRemark-43363640");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAdrDTOArrayVal1.setAdrNote("AdrNote-961882226");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAdrDTOArrayVal1.setEhrDisplayDataLevel("EhrDisplayDataLevel-717502062");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAdrDTOArrayVal1.setRecordCreationInstName("RecordCreationInstName1341135529");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAdrDTOArrayVal1.setRecordUpdateInstName("RecordUpdateInstName371089407");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAdrDTOArrayVal1.setTransactionType("TransactionType1851089355");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAdrDTOArrayVal1.setTransactionDtm("TransactionDtm1050614599");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAdrDTOArrayVal1.setLastUpdateDtm("LastUpdateDtm1845223426");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAdrDTOArray.add(_handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAdrDTOArrayVal1);
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResult.getDownloadAdrDTOArray().addAll(_handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAdrDTOArray);
        java.util.List<hk.gov.ehr.alert.ws.beans.download.DownloadAllergyDTO> _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAllergyDTOArray = new java.util.ArrayList<hk.gov.ehr.alert.ws.beans.download.DownloadAllergyDTO>();
        hk.gov.ehr.alert.ws.beans.download.DownloadAllergyDTO _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAllergyDTOArrayVal1 = new hk.gov.ehr.alert.ws.beans.download.DownloadAllergyDTO();
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAllergyDTOArrayVal1.setEhrNo("EhrNo1405988871");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAllergyDTOArrayVal1.setRecordKey("RecordKey302236884");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAllergyDTOArrayVal1.setEpisodeNo("EpisodeNo-950316856");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAllergyDTOArrayVal1.setHciId("HciId73336225");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAllergyDTOArrayVal1.setHciLongName("HciLongName1472887760");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAllergyDTOArrayVal1.setHciShortName("HciShortName-1594908040");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAllergyDTOArrayVal1.setTypeOfAllergenCode("TypeOfAllergenCode-571430096");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAllergyDTOArrayVal1.setTypeOfAllergenDesc("TypeOfAllergenDesc1481536316");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAllergyDTOArrayVal1.setTypeOfAllergenLtDesc("TypeOfAllergenLtDesc-1924921296");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAllergyDTOArrayVal1.setAllergenRtName("AllergenRtName2045020941");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAllergyDTOArrayVal1.setAllergenRtId("AllergenRtId-1168618614");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAllergyDTOArrayVal1.setAllergenRtDesc("AllergenRtDesc430130000");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAllergyDTOArrayVal1.setAllergenLtCode("AllergenLtCode-1579887094");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAllergyDTOArrayVal1.setAllergenLtDesc("AllergenLtDesc406508744");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAllergyDTOArrayVal1.setAllergenTermId("AllergenTermId-1145611882");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAllergyDTOArrayVal1.setAllergenEhrDesc("AllergenEhrDesc-240755555");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAllergyDTOArrayVal1.setAllergenVtmTermId("AllergenVtmTermId1291923628");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAllergyDTOArrayVal1.setAllergenVtmEhrDesc("AllergenVtmEhrDesc-1260907442");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAllergyDTOArrayVal1.setLevelOfCertaintyCode("LevelOfCertaintyCode-497593651");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAllergyDTOArrayVal1.setLevelOfCertaintyDesc("LevelOfCertaintyDesc-663245099");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAllergyDTOArrayVal1.setLevelOfCertaintyLtDesc("LevelOfCertaintyLtDesc2074459769");
        java.util.List<hk.gov.ehr.alert.ws.beans.download.DownloadManifestDTO> _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAllergyDTOArrayVal1DownloadManifestDTOArray = new java.util.ArrayList<hk.gov.ehr.alert.ws.beans.download.DownloadManifestDTO>();
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAllergyDTOArrayVal1.getDownloadManifestDTOArray().addAll(_handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAllergyDTOArrayVal1DownloadManifestDTOArray);
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAllergyDTOArrayVal1.setDeleteAllergenReason("DeleteAllergenReason-1452930422");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAllergyDTOArrayVal1.setAllergenRemark("AllergenRemark2133181859");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAllergyDTOArrayVal1.setAllergyNote("AllergyNote727713423");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAllergyDTOArrayVal1.setEhrDisplayDataLevel("EhrDisplayDataLevel1378613191");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAllergyDTOArrayVal1.setRecordCreationInstName("RecordCreationInstName-710272063");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAllergyDTOArrayVal1.setRecordUpdateInstName("RecordUpdateInstName224263435");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAllergyDTOArrayVal1.setTransactionType("TransactionType1607969921");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAllergyDTOArrayVal1.setTransactionDtm("TransactionDtm894740490");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAllergyDTOArrayVal1.setLastUpdateDtm("LastUpdateDtm-1829461021");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAllergyDTOArray.add(_handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAllergyDTOArrayVal1);
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResult.getDownloadAllergyDTOArray().addAll(_handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResultDownloadAllergyDTOArray);
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequest.setEhrPatientAdrAndAllergyDownloadResult(_handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestEhrPatientAdrAndAllergyDownloadResult);
        hk.gov.ehr.alert.ws.beans.AuditDTO _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestAuditDTO = new hk.gov.ehr.alert.ws.beans.AuditDTO();
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestAuditDTO.setWorkstationId("WorkstationId1948475456");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestAuditDTO.setLoginId("LoginId-453295122");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestAuditDTO.setHkId("HkId1942412593");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestAuditDTO.setMrn("Mrn-1186939870");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestAuditDTO.setWorkstationIpAddress("WorkstationIpAddress1023118017");
        _handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequest.setAuditDTO(_handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequestAuditDTO);
        hk.gov.ehr.alert.ws.beans.PmiPatientLogUpdateResponseBean _handlePmiPatientLogUpdate__return = port.handlePmiPatientLogUpdate(_handlePmiPatientLogUpdate_handlePmiPatientLogUpdateRequest);
        System.out.println("handlePmiPatientLogUpdate.result=" + _handlePmiPatientLogUpdate__return);


        }
        {
        System.out.println("Invoking getPatientAdrLogByPeriod...");
        hk.gov.ehr.alert.ws.beans.PatientLogByPeriodRequest _getPatientAdrLogByPeriod_getPatientAdrLogByPeriodRequest = new hk.gov.ehr.alert.ws.beans.PatientLogByPeriodRequest();
        _getPatientAdrLogByPeriod_getPatientAdrLogByPeriodRequest.setRefKey("RefKey-1563714467");
        _getPatientAdrLogByPeriod_getPatientAdrLogByPeriodRequest.setStartTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-05-26T14:56:54.299+08:00"));
        _getPatientAdrLogByPeriod_getPatientAdrLogByPeriodRequest.setEndTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-05-26T14:56:54.299+08:00"));
        hk.gov.ehr.alert.ws.beans.AdrLogResponse _getPatientAdrLogByPeriod__return = port.getPatientAdrLogByPeriod(_getPatientAdrLogByPeriod_getPatientAdrLogByPeriodRequest);
        System.out.println("getPatientAdrLogByPeriod.result=" + _getPatientAdrLogByPeriod__return);


        }
        {
        System.out.println("Invoking getPatientAllergyLog...");
        hk.gov.ehr.alert.ws.beans.AllergyLogRequest _getPatientAllergyLog_getPatientAllergyLogRequest = new hk.gov.ehr.alert.ws.beans.AllergyLogRequest();
        _getPatientAllergyLog_getPatientAllergyLogRequest.setRefKey("RefKey882108752");
        hk.gov.ehr.alert.ws.beans.AllergyLogResponse _getPatientAllergyLog__return = port.getPatientAllergyLog(_getPatientAllergyLog_getPatientAllergyLogRequest);
        System.out.println("getPatientAllergyLog.result=" + _getPatientAllergyLog__return);


        }
        {
        System.out.println("Invoking getPatientAlert...");
        hk.gov.ehr.alert.ws.beans.AlertRequest _getPatientAlert_getPatientAlertRequest = new hk.gov.ehr.alert.ws.beans.AlertRequest();
        _getPatientAlert_getPatientAlertRequest.setRefKey("RefKey-2112731704");
        hk.gov.ehr.alert.ws.beans.AlertResponse _getPatientAlert__return = port.getPatientAlert(_getPatientAlert_getPatientAlertRequest);
        System.out.println("getPatientAlert.result=" + _getPatientAlert__return);


        }

        System.exit(0);
    }

}
