CREATE OR REPLACE FUNCTION "NHS_LIS_BIRTHLOG" (
	v_BBPATNO       IN VARCHAR2,
	v_SENDDTFM      IN VARCHAR2,
	v_SENDDTTO      IN VARCHAR2,
	v_MOPATNO       IN VARCHAR2,
	v_DOBFM         IN VARCHAR2,
	v_DOBTO         IN VARCHAR2,
	v_RECSTATUS     IN VARCHAR2,
	v_BATCHNO       IN VARCHAR2,
	v_BIRTHRETURNNO IN VARCHAR2,
	v_ORDERBY       IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
	STRSQL VARCHAR2(2000);
BEGIN
	STRSQL := 'SELECT '''',
					EBIRTHID,
					BB_PATNO,
					BB_FNAME || '' '' || BB_GNAME,
					TO_CHAR(BB_DOB,''DD/MM/YYYY''),
					BIRTHRETURNNO,
					MO_PATNO,
					MO_FNAME || '' '' || MO_GNAME,
					DECODE(RECSTATUS, ''A'', ''Closed'', ''B'', ''Received'',
					''C'', ''Confirmed'', ''M'', ''Manual'', ''N'', ''Normal'',
					''R'', ''Rejected'', ''W'', ''Sending'', RECSTATUS),
					BATCHNO
				FROM EBIRTHDTL
				WHERE 1 = 1 ';

	IF v_BBPATNO IS NOT NULL THEN
		STRSQL := STRSQL || ' AND BB_PATNO = ''' || v_BBPATNO || '''';
	END IF;

	IF v_MOPATNO IS NOT NULL THEN
		STRSQL := STRSQL || ' AND MO_PATNO = ''' || v_MOPATNO || '''';
	END IF;

	IF v_BATCHNO IS NOT NULL THEN
		STRSQL := STRSQL || ' AND BATCHNO = ''' || v_BATCHNO || '''';
	END IF;

	IF v_RECSTATUS IS NOT NULL THEN
		IF v_RECSTATUS = 'C' THEN
			STRSQL := STRSQL || ' AND (RECSTATUS = ''C'' OR RECSTATUS = ''W'' OR RECSTATUS = ''B'')';
		ELSE
			STRSQL := STRSQL || ' AND RECSTATUS = ''' || v_RECSTATUS || '''';
		END IF;
	END IF;

	IF v_BIRTHRETURNNO IS NOT NULL THEN
		STRSQL := STRSQL || ' AND BIRTHRETURNNO = ''' || v_BIRTHRETURNNO || '''';
	END IF;

	IF v_SENDDTFM IS NOT NULL THEN
		STRSQL := STRSQL || ' AND SENDDATE >= TO_DATE(''' || v_SENDDTFM || ''', ''DD/MM/YYYY'')';
	END IF;

	IF v_SENDDTTO IS NOT NULL THEN
		STRSQL := STRSQL || ' AND SENDDATE < TO_DATE(''' || v_SENDDTTO || ''', ''DD/MM/YYYY'')+1';
	END IF;

	IF v_DOBFM IS NOT NULL THEN
		STRSQL := STRSQL || ' AND BB_DOB >= TO_DATE(''' || v_DOBFM || ''', ''DD/MM/YYYY'')';
	END IF;

	IF v_DOBTO IS NOT NULL THEN
		STRSQL := STRSQL || ' AND BB_DOB < TO_DATE(''' || v_DOBTO || ''', ''DD/MM/YYYY'')+1';
	END IF;

	IF v_ORDERBY IS NOT NULL THEN
		STRSQL := STRSQL || ' ORDER BY ' || v_ORDERBY;
	END IF;

	OPEN OUTCUR FOR STRSQL;
	RETURN OUTCUR;
END NHS_LIS_BIRTHLOG;
/
