CREATE OR REPLACE FUNCTION "NHS_GET_DHBIRTHDTLUPDATE"(
	V_BBPATNO IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
BEGIN
	OPEN OUTCUR FOR
		SELECT B.MOPATNO,
			B.BBPATNO,
			P.PATFNAME || ' ' || P.PATGNAME AS MONAME,
			T.PATFNAME || ' ' || T.PATGNAME AS BBNAME,
			B.MOSLPNO,
			B.WEIGHTATBIRTH AS BBWEIGHT,
			B.BBWEIGHUNIT AS WEIGHTUNIT,
			B.BIRTHORDER,
			TO_CHAR(B.DATEOFLASTLIVEBIRTH,'DD/MM/YYYY'),
			B.CHILDEVERBORNALIVE AS ALIVE,
			B.MALF_DET,
			B.MO_TRAVELDOCTYPE,
			B.MO_DOCNO,
			B.MALF1,
			B.MALF2,
			B.MALF3,
			B.MALF4,
			B.MALF5,
			B.MALF6,
			B.MALF7,
			B.MALF8,
			B.MALF9,
			B.CONFIRMBY,
			TO_CHAR(B.CONFIRMDATE,'DD/MM/YYYY HH24:MI:SS'),
			B.DHBIRTHNO,
			B.RecStatus
		FROM  DHBIRTHDTL B, PATIENT P, PATIENT T
		WHERE B.MOPATNO = P.PATNO(+)
		AND   B.BBPATNO = T.PATNO
		AND   BBPATNO = V_BBPATNO;
	RETURN OUTCUR;
END NHS_GET_DHBIRTHDTLUPDATE;
/
