CREATE OR REPLACE FUNCTION "NHS_ACT_DHBIRTHLOG" (
	v_ACTION  IN VARCHAR2,
	v_BATCHNO IN VARCHAR2,
	v_STATUS  IN VARCHAR2,
	v_USER    IN VARCHAR2,
	O_ERRMSG  OUT VARCHAR2
)
	RETURN NUMBER
AS
	O_ERRCODE NUMBER;
	v_BBPATNO VARCHAR2(10);
	OUTCUR  TYPES.CURSOR_TYPE;
BEGIN
	O_ERRCODE := 0;
	O_ERRMSG  := 'OK';

	UPDATE DHBIRTHDTL SET RECSTATUS = v_STATUS WHERE BATCHNO = v_BATCHNO;

	OPEN OUTCUR FOR SELECT BBPATNO FROM DHBIRTHDTL WHERE BATCHNO = v_BATCHNO;
		LOOP
			FETCH OUTCUR INTO v_BBPATNO;
			EXIT WHEN OUTCUR%NOTFOUND;

			INSERT INTO DHBIRTHHISTORY (
				HID,
				BB_PATNO,
				STATUS,
				EDIT_BY,
				SENDDT,
				REMARK,
				IS_MANUAL
			) VALUES (
				SEQ_DHHISTORY.NEXTVAL,
				v_BBPATNO,
				DECODE(v_STATUS, 'A', 'Closed', 'M', 'Edit', 'E', 'Exported',NULL),
				v_USER,
				SYSDATE,
				NULL,
				'Y');
		END LOOP;
	CLOSE OUTCUR;

	RETURN O_ERRCODE;
END NHS_ACT_DHBIRTHLOG;
/
