CREATE OR REPLACE FUNCTION "NHS_LIS_DHBIRTHLOG" (
	v_BBPATNO       IN VARCHAR2,
	v_SENDDTFM      IN VARCHAR2,
	v_SENDDTTO      IN VARCHAR2,
	v_MOPATNO       IN VARCHAR2,
	v_DOBFM         IN VARCHAR2,
	v_DOBTO         IN VARCHAR2,
	v_RECSTATUS     IN VARCHAR2,
	v_BATCHNO       IN VARCHAR2,
	v_BIRTHRETURNNO IN VARCHAR2,
	v_ORDERBY       IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
	STRSQL VARCHAR2(2000);
BEGIN
	STRSQL := 'SELECT '''',
					B.DHBIRTHID,
					B.BBPATNO AS BB_PATNO,
					P.PATFNAME || '' '' || P.PATGNAME AS BBNAME,
					TO_CHAR(P.PATBDATE,''DD/MM/YYYY'') AS BB_DOB,
					B.MOPATNO AS MO_PATNO,
					T.PATFNAME || '' '' || T.PATGNAME AS MONAME,
					DECODE(B.RECSTATUS, ''A'', ''Closed'', ''B'', ''Received'',
					''C'', ''Confirmed'', ''M'', ''Manual'', ''N'', ''Normal'',
					''R'', ''Rejected'', ''W'', ''Sending'', B.RECSTATUS) AS RECSTATUS,
					B.DHBIRTHNO AS BIRTHRETURNNO,
					B.BATCHNO AS BATCHNO,
					TO_CHAR(B.SENDDATE,''DD/MM/YYYY'')
				FROM  DHBIRTHDTL B, PATIENT P, PATIENT T
				WHERE B.BBPATNO = P.PATNO
				AND   B.MOPATNO = T.PATNO(+)';

	IF v_BBPATNO IS NOT NULL THEN
		STRSQL := STRSQL || ' AND B.BBPATNO  = ''' || v_BBPATNO || '''';
	END IF;

	IF v_MOPATNO IS NOT NULL THEN
		STRSQL := STRSQL || ' AND B.MOPATNO  = ''' || v_MOPATNO || '''';
	END IF;

	IF v_BATCHNO IS NOT NULL THEN
		STRSQL := STRSQL || ' AND B.BATCHNO  = ''' || v_BATCHNO || '''';
	END IF;

	IF v_RECSTATUS IS NOT NULL THEN
		IF v_RECSTATUS = 'C' THEN
			STRSQL := STRSQL || ' AND (RECSTATUS = ''C'' OR RECSTATUS = ''W'' OR RECSTATUS = ''B'')';
		ELSE
			STRSQL := STRSQL || ' AND RECSTATUS  = ''' || v_RECSTATUS || '''';
		END IF;
	END IF;

	IF v_BIRTHRETURNNO IS NOT NULL THEN
		STRSQL := STRSQL || ' AND B.DHBIRTHNO  = ''' || v_BIRTHRETURNNO || '''';
	END IF;

	IF v_SENDDTFM IS NOT NULL THEN
		STRSQL := STRSQL || ' AND B.SENDDATE >=TO_DATE(''' || v_SENDDTFM || ''', ''DD/MM/YYYY'')';
	END IF;

	IF v_SENDDTTO IS NOT NULL THEN
		STRSQL := STRSQL || ' AND B.SENDDATE < TO_DATE(''' || v_SENDDTTO || ''', ''DD/MM/YYYY'')+1';
	END IF;

	IF v_DOBFM IS NOT NULL THEN
		STRSQL := STRSQL || ' AND P.PATBDATE >=TO_DATE(''' || v_DOBFM || ''', ''DD/MM/YYYY'')';
	END IF;

	IF v_DOBTO IS NOT NULL THEN
		STRSQL := STRSQL || ' AND P.PATBDATE < TO_DATE(''' || v_DOBTO || ''', ''DD/MM/YYYY'') + 1';
	END IF;

	IF v_ORDERBY IS NOT NULL THEN
		IF v_ORDERBY = 'BB_DOB' THEN
			STRSQL := STRSQL || ' ORDER BY P.PATBDATE';
		ELSE
			STRSQL := STRSQL || ' ORDER BY '|| v_ORDERBY;
		END IF;
	END IF;

	OPEN OUTCUR FOR STRSQL;
	RETURN OUTCUR;
END NHS_LIS_DHBIRTHLOG;
/
