CREATE OR REPLACE FUNCTION "NHS_ACT_DHBIRTHDTLUPDATE" (
	v_ACTION   IN VARCHAR2,
	v_BBPATNO  IN VARCHAR2,
	v_DATELIVE IN VARCHAR2,
	v_ORDER    IN VARCHAR2,
	v_ALIVE    IN VARCHAR2,
	v_WEIGHT   IN VARCHAR2,
	v_UNIT     IN VARCHAR2,
	v_MDOCNO   IN VARCHAR2,
	v_DOCTYPE  IN VARCHAR2,
	v_MALFDET  IN VARCHAR2,
	v_M1       IN VARCHAR2,
	v_M2       IN VARCHAR2,
	v_M3       IN VARCHAR2,
	v_M4       IN VARCHAR2,
	v_M5       IN VARCHAR2,
	v_M6       IN VARCHAR2,
	v_M7       IN VARCHAR2,
	v_M8       IN VARCHAR2,
	v_M9       IN VARCHAR2,
	v_USER     IN VARCHAR2,
	v_ADDHIST  IN VARCHAR2,
	o_ERRMSG   OUT VARCHAR2
)
	RETURN NUMBER
AS
	o_ERRCODE NUMBER;
	o_LOGMSG VARCHAR2(100);
	v_UNIT2 VARCHAR2(10);
	v_RECSTATUS VARCHAR2(1);
	v_Count NUMBER;
BEGIN
	o_ERRCODE := 0;
	o_ERRMSG  := 'OK';

	IF v_ACTION = 'ADD' THEN
		SELECT COUNT(1) INTO v_Count FROM SYSPARAM WHERE PARCDE = 'weightunit';
		IF v_Count = 1 THEN
			SELECT PARAM1 INTO v_UNIT2 FROM SYSPARAM WHERE PARCDE = 'weightunit';
		END IF;

		SELECT MO_SLPNO INTO o_LOGMSG
		FROM   EBIRTHDTL
		WHERE  BB_PATNO = v_BBPATNO;

		o_ERRCODE := NHS_ACT_SYSLOG(v_ACTION, 'DHBIRTHDTLUPDATE', 'BB PATNO: '||v_BBPATNO, o_LOGMSG || ' is mother slpno', v_USER, NULL, o_ERRMSG);

		INSERT INTO DHBIRTHDTL (
			DHBIRTHID,
			BBPATNO,
			MOPATNO,
			MOSLPNO,
			BIRTHORDER,
			DATEOFLASTLIVEBIRTH,
			RECSTATUS,
			CHILDEVERBORNALIVE,
			BBWEIGHUNIT,
			MO_DOCNO,
			MO_TRAVELDOCTYPE)
		SELECT SEQ_DHBIRTHDTL.NEXTVAL,
			 BB_PATNO,
			 MO_PATNO,
			 MO_SLPNO,
			 BB_BIRTHORDER,
			 NULL,
			 'N',
			 0,
			 v_UNIT2,
			 DECODE(MO_HKIC, NULL, SUBSTR(MO_TRAVELDOCNO, 1, 20), MO_HKIC),
			 DECODE(MO_HKIC, NULL, MO_TRAVELDOCTYPE, 9)
		FROM EBIRTHDTL
		WHERE BB_PATNO = v_BBPATNO;
	ELSIF v_ACTION = 'MOD' THEN
		IF v_ADDHIST = 'Y' THEN
			UPDATE DHBIRTHDTL
			SET
				DATEOFLASTLIVEBIRTH = TO_DATE(v_DATELIVE, 'DD/MM/YYYY'),
				BIRTHORDER          = TO_NUMBER(v_ORDER),
				CHILDEVERBORNALIVE  = TO_NUMBER(v_ALIVE),
				WEIGHTATBIRTH       = TO_NUMBER(v_WEIGHT),
				BBWEIGHUNIT         = v_UNIT,
				MO_DOCNO            = v_MDOCNO,
				MO_TRAVELDOCTYPE    = v_DOCTYPE,
				MALF_DET            = v_MALFDET,
				MALF1               = v_M1,
				MALF2               = v_M2,
				MALF3               = v_M3,
				MALF4               = v_M4,
				MALF5               = v_M5,
				MALF6               = v_M6,
				MALF7               = v_M7,
				MALF8               = v_M8,
				MALF9               = v_M9
			WHERE BBPATNO = v_BBPATNO;

			INSERT INTO DHBIRTHHISTORY
			VALUES (
				SEQ_DHHISTORY.NEXTVAL,
				v_BBPATNO,
				'Edit',
				v_USER,
				SYSDATE,
				NULL,
				NULL);
		ELSE
			UPDATE DHBIRTHDTL
			SET
				BIRTHORDER       = TO_NUMBER(v_ORDER),
				MO_DOCNO         = v_MDOCNO,
				MO_TRAVELDOCTYPE = v_DOCTYPE
			WHERE BBPATNO = v_BBPATNO;
		END IF;
	ELSIF v_ACTION = 'DEL' THEN
		SELECT RECSTATUS
		INTO v_RECSTATUS
		FROM DHBIRTHDTL
		WHERE BBPATNO = v_BBPATNO;

		IF v_RECSTATUS = 'N' THEN
			DELETE FROM DHBIRTHDTL WHERE BBPATNO = v_BBPATNO;
			o_ERRMSG := 'Delete Successfully';
		ELSE
			o_ERRCODE := -1;
			o_ERRMSG := 'Only normal record can be deleted.';
		END IF;
	END IF;

	RETURN o_ERRCODE;
EXCEPTION
WHEN OTHERS THEN
	o_ERRCODE := -1;
	o_ERRMSG := substr(SQLERRM, 1, 200);
	ROLLBACK;
	RETURN o_ERRCODE;
END NHS_ACT_DHBIRTHDTLUPDATE;
/
