CREATE OR REPLACE FUNCTION "NHS_ACT_EBIRTHCONFIRM"(
	v_ACTION  IN VARCHAR2,
	v_BBPATNO IN VARCHAR2,
	v_USER    IN VARCHAR2,
	o_ERRMSG  OUT VARCHAR2
)
	RETURN NUMBER
AS
	o_ERRCODE NUMBER;
BEGIN
	o_ERRCODE := 0;
	o_ERRMSG  := 'OK';

	UPDATE EBIRTHDTL
	SET    RECSTATUS = 'C', CONFIRMBY = v_USER, COMFIRMDATE = SYSDATE
	WHERE  BB_PATNO = v_BBPATNO;

	INSERT INTO EBIRTHHISTORY (
		HID,
		BB_PATNO,
		STATUS,
		EDIT_BY,
		SENDDT,
		REMARK,
		IS_MANUAL
	) VALUES (
		SEQ_EBIRTHHISTORY.NEXTVAL,
		v_BBPATNO,
		'Confirm',
		v_USER,
		SYSDATE,
		NULL,
		NULL);
	RETURN o_ERRCODE;
END NHS_ACT_EBIRTHCONFIRM;
/
