CREATE OR REPLACE FUNCTION "NHS_LIS_DHSENDQUEUE"(I_FLAG IN VARCHAR2)
  RETURN TYPES.CURSOR_TYPE AS
  OUTCUR TYPES.CURSOR_TYPE;
  CHKBOXVAL VARCHAR2(5);
BEGIN

  IF I_FLAG = 'Y' THEN
    CHKBOXVAL := 'true';
  ELSE
    CHKBOXVAL := 'false';
  END IF;

  OPEN OUTCUR FOR
    SELECT '',
           '',
           B.MOPATNO,
           T.PATFNAME || ' ' || T.PATGNAME AS MONAME,
           B.BBPATNO,
           P.PATFNAME || ' ' || P.PATGNAME AS BBNAME,
           '' || CHKBOXVAL || '',
           TO_CHAR(P.PATBDATE,'DD/MM/YYYY'),
           B.CONFIRMBY,
           TO_CHAR(B.CONFIRMDATE,'DD/MM/YYYY HH24:MI:SS'),
           '' || I_FLAG || ''
      FROM DHBIRTHDTL B, PATIENT P, PATIENT T
     WHERE B.BBPATNO = P.PATNO
       AND B.MOPATNO = T.PATNO
       AND B.RECSTATUS = 'C'
       AND B.FORCE_SEND IS NULL;
  RETURN OUTCUR;
END NHS_LIS_DHSENDQUEUE;
/
