CREATE OR REPLACE FUNCTION "NHS_ACT_EBIRTHUNCONFIRM"(V_ACTION  IN VARCHAR2,
                                                     V_BBPATNO IN VARCHAR2,
                                                     V_USER    IN VARCHAR2,
                                                     O_ERRMSG  OUT VARCHAR2)

 RETURN NUMBER AS
  O_ERRCODE NUMBER;

BEGIN
  O_ERRCODE := 0;
  O_ERRMSG  := 'OK';

  UPDATE EBIRTHDTL
     SET RECSTATUS = 'N', CONFIRMBY = NULL, COMFIRMDATE = NULL
   WHERE BB_PATNO = V_BBPATNO;

  INSERT INTO EBIRTHHISTORY
  VALUES
    (SEQ_EBIRTHHISTORY.NEXTVAL,
     V_BBPATNO,
     'Un-confirm',
     V_USER,
     SYSDATE,
     NULL,
     NULL);
  RETURN O_ERRCODE;
END NHS_ACT_EBIRTHUNCONFIRM;
/
