CREATE OR REPLACE FUNCTION "NHS_GET_EBIRTHDATEFORMAT" (
	V_DATE IN DATE,
	V_TIME IN VARCHAR2
)
	RETURN VARCHAR2 AS
	V_RETURN_DATE VARCHAR2(20);
BEGIN
	IF V_DATE IS NOT NULL THEN
		IF SUBSTR(TO_CHAR(V_DATE,'DDMMYYYYHH24MISS'),-6,6) = '000000' THEN
			IF LENGTH(V_TIME)>0 THEN
				RETURN TO_CHAR(V_DATE,'DD/MM/YYYY') || ' ' || V_TIME;
			ELSE
				RETURN TO_CHAR(V_DATE,'DD/MM/YYYY');
			END IF;
		ELSE
			RETURN TO_CHAR(V_DATE,'DD/MM/YYYY hh24:mi:ss');
		END IF;
	ELSE
		RETURN NULL;
	END IF;
END NHS_GET_EBIRTHDATEFORMAT;
/
