CREATE OR REPLACE FUNCTION "NHS_LIS_BIRTHLOGHIST"(V_BBPATNO IN VARCHAR2)

 RETURN TYPES.CURSOR_TYPE
 AS
  OUTCUR TYPES.CURSOR_TYPE;

BEGIN
  OPEN OUTCUR FOR
    SELECT '', HID, BB_PATNO, IS_MANUAL, STATUS, EDIT_BY,
           TO_CHAR(SENDDT,'DD/MM/YYYY HH24:MI:SS'), REMARK
      FROM EBIRTHHISTORY
     WHERE BB_PATNO = V_BBPATNO
   ORDER BY SENDDT DESC;
  RETURN OUTCUR;
END NHS_LIS_BIRTHLOGHIST;
/
