//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.30 at 04:23:32 PM CST 
//


package org.hl7.v3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="epis_detail" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{urn:hl7-org:v3}record_key"/>
 *                   &lt;element ref="{urn:hl7-org:v3}transaction_dtm"/>
 *                   &lt;element ref="{urn:hl7-org:v3}transaction_type"/>
 *                   &lt;element ref="{urn:hl7-org:v3}last_update_dtm" minOccurs="0"/>
 *                   &lt;element ref="{urn:hl7-org:v3}episode_no" minOccurs="0"/>
 *                   &lt;element ref="{urn:hl7-org:v3}attendance_inst_id" minOccurs="0"/>
 *                   &lt;element name="epis_report_start_date" type="{urn:hl7-org:v3}epis_report_start_date" minOccurs="0"/>
 *                   &lt;element name="epis_report_end_date" type="{urn:hl7-org:v3}epis_report_end_date" minOccurs="0"/>
 *                   &lt;element name="epis_type_cd" type="{urn:hl7-org:v3}epis_type_cd" minOccurs="0"/>
 *                   &lt;element name="epis_type_desc" type="{urn:hl7-org:v3}epis_type_desc" minOccurs="0"/>
 *                   &lt;element name="epis_type_lt_desc" type="{urn:hl7-org:v3}epis_type_lt_desc" minOccurs="0"/>
 *                   &lt;element name="epis_report_title" type="{urn:hl7-org:v3}epis_report_title" minOccurs="0"/>
 *                   &lt;element name="epis_report_date" type="{urn:hl7-org:v3}epis_report_date" minOccurs="0"/>
 *                   &lt;element name="epis_txt_report" type="{urn:hl7-org:v3}epis_txt_report" minOccurs="0"/>
 *                   &lt;element name="epis_highlight" type="{urn:hl7-org:v3}epis_highlight" minOccurs="0"/>
 *                   &lt;element name="epis_remark" type="{urn:hl7-org:v3}epis_remark" minOccurs="0"/>
 *                   &lt;element ref="{urn:hl7-org:v3}file_ind" minOccurs="0"/>
 *                   &lt;element ref="{urn:hl7-org:v3}file_name" minOccurs="0"/>
 *                   &lt;element name="epis_report_id" type="{urn:hl7-org:v3}epis_report_id" minOccurs="0"/>
 *                   &lt;element ref="{urn:hl7-org:v3}record_creation_dtm" minOccurs="0"/>
 *                   &lt;element ref="{urn:hl7-org:v3}record_creation_inst_id" minOccurs="0"/>
 *                   &lt;element ref="{urn:hl7-org:v3}record_creation_inst_name" minOccurs="0"/>
 *                   &lt;element ref="{urn:hl7-org:v3}record_update_dtm" minOccurs="0"/>
 *                   &lt;element ref="{urn:hl7-org:v3}record_update_inst_id" minOccurs="0"/>
 *                   &lt;element ref="{urn:hl7-org:v3}record_update_inst_name" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "episDetail"
})
@XmlRootElement(name = "clinicalNoteDetail")
public class ClinicalNoteDetail {

    @XmlElement(name = "epis_detail", required = true)
    protected List<ClinicalNoteDetail.EpisDetail> episDetail;

    /**
     * Gets the value of the episDetail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the episDetail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEpisDetail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ClinicalNoteDetail.EpisDetail }
     * 
     * 
     */
    public List<ClinicalNoteDetail.EpisDetail> getEpisDetail() {
        if (episDetail == null) {
            episDetail = new ArrayList<ClinicalNoteDetail.EpisDetail>();
        }
        return this.episDetail;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{urn:hl7-org:v3}record_key"/>
     *         &lt;element ref="{urn:hl7-org:v3}transaction_dtm"/>
     *         &lt;element ref="{urn:hl7-org:v3}transaction_type"/>
     *         &lt;element ref="{urn:hl7-org:v3}last_update_dtm" minOccurs="0"/>
     *         &lt;element ref="{urn:hl7-org:v3}episode_no" minOccurs="0"/>
     *         &lt;element ref="{urn:hl7-org:v3}attendance_inst_id" minOccurs="0"/>
     *         &lt;element name="epis_report_start_date" type="{urn:hl7-org:v3}epis_report_start_date" minOccurs="0"/>
     *         &lt;element name="epis_report_end_date" type="{urn:hl7-org:v3}epis_report_end_date" minOccurs="0"/>
     *         &lt;element name="epis_type_cd" type="{urn:hl7-org:v3}epis_type_cd" minOccurs="0"/>
     *         &lt;element name="epis_type_desc" type="{urn:hl7-org:v3}epis_type_desc" minOccurs="0"/>
     *         &lt;element name="epis_type_lt_desc" type="{urn:hl7-org:v3}epis_type_lt_desc" minOccurs="0"/>
     *         &lt;element name="epis_report_title" type="{urn:hl7-org:v3}epis_report_title" minOccurs="0"/>
     *         &lt;element name="epis_report_date" type="{urn:hl7-org:v3}epis_report_date" minOccurs="0"/>
     *         &lt;element name="epis_txt_report" type="{urn:hl7-org:v3}epis_txt_report" minOccurs="0"/>
     *         &lt;element name="epis_highlight" type="{urn:hl7-org:v3}epis_highlight" minOccurs="0"/>
     *         &lt;element name="epis_remark" type="{urn:hl7-org:v3}epis_remark" minOccurs="0"/>
     *         &lt;element ref="{urn:hl7-org:v3}file_ind" minOccurs="0"/>
     *         &lt;element ref="{urn:hl7-org:v3}file_name" minOccurs="0"/>
     *         &lt;element name="epis_report_id" type="{urn:hl7-org:v3}epis_report_id" minOccurs="0"/>
     *         &lt;element ref="{urn:hl7-org:v3}record_creation_dtm" minOccurs="0"/>
     *         &lt;element ref="{urn:hl7-org:v3}record_creation_inst_id" minOccurs="0"/>
     *         &lt;element ref="{urn:hl7-org:v3}record_creation_inst_name" minOccurs="0"/>
     *         &lt;element ref="{urn:hl7-org:v3}record_update_dtm" minOccurs="0"/>
     *         &lt;element ref="{urn:hl7-org:v3}record_update_inst_id" minOccurs="0"/>
     *         &lt;element ref="{urn:hl7-org:v3}record_update_inst_name" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "recordKey",
        "transactionDtm",
        "transactionType",
        "lastUpdateDtm",
        "episodeNo",
        "attendanceInstId",
        "episReportStartDate",
        "episReportEndDate",
        "episTypeCd",
        "episTypeDesc",
        "episTypeLtDesc",
        "episReportTitle",
        "episReportDate",
        "episTxtReport",
        "episHighlight",
        "episRemark",
        "fileInd",
        "fileName",
        "episReportId",
        "recordCreationDtm",
        "recordCreationInstId",
        "recordCreationInstName",
        "recordUpdateDtm",
        "recordUpdateInstId",
        "recordUpdateInstName"
    })
    public static class EpisDetail {

        @XmlElement(name = "record_key", required = true)
        protected String recordKey;
        @XmlElement(name = "transaction_dtm", required = true)
        protected String transactionDtm;
        @XmlElement(name = "transaction_type", required = true)
        protected String transactionType;
        @XmlElement(name = "last_update_dtm")
        protected String lastUpdateDtm;
        @XmlElement(name = "episode_no")
        protected String episodeNo;
        @XmlElement(name = "attendance_inst_id")
        protected String attendanceInstId;
        @XmlElement(name = "epis_report_start_date")
        protected String episReportStartDate;
        @XmlElement(name = "epis_report_end_date")
        protected String episReportEndDate;
        @XmlElement(name = "epis_type_cd")
        protected String episTypeCd;
        @XmlElement(name = "epis_type_desc")
        protected String episTypeDesc;
        @XmlElement(name = "epis_type_lt_desc")
        protected String episTypeLtDesc;
        @XmlElement(name = "epis_report_title")
        protected String episReportTitle;
        @XmlElement(name = "epis_report_date")
        protected String episReportDate;
        @XmlElement(name = "epis_txt_report")
        protected String episTxtReport;
        @XmlElement(name = "epis_highlight")
        protected String episHighlight;
        @XmlElement(name = "epis_remark")
        protected String episRemark;
        @XmlElement(name = "file_ind")
        protected String fileInd;
        @XmlElement(name = "file_name")
        protected String fileName;
        @XmlElement(name = "epis_report_id")
        protected String episReportId;
        @XmlElement(name = "record_creation_dtm")
        protected String recordCreationDtm;
        @XmlElement(name = "record_creation_inst_id")
        protected String recordCreationInstId;
        @XmlElement(name = "record_creation_inst_name")
        protected String recordCreationInstName;
        @XmlElement(name = "record_update_dtm")
        protected String recordUpdateDtm;
        @XmlElement(name = "record_update_inst_id")
        protected String recordUpdateInstId;
        @XmlElement(name = "record_update_inst_name")
        protected String recordUpdateInstName;

        /**
         * Gets the value of the recordKey property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRecordKey() {
            return recordKey;
        }

        /**
         * Sets the value of the recordKey property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRecordKey(String value) {
            this.recordKey = value;
        }

        /**
         * Gets the value of the transactionDtm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTransactionDtm() {
            return transactionDtm;
        }

        /**
         * Sets the value of the transactionDtm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTransactionDtm(String value) {
            this.transactionDtm = value;
        }

        /**
         * Gets the value of the transactionType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTransactionType() {
            return transactionType;
        }

        /**
         * Sets the value of the transactionType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTransactionType(String value) {
            this.transactionType = value;
        }

        /**
         * Gets the value of the lastUpdateDtm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLastUpdateDtm() {
            return lastUpdateDtm;
        }

        /**
         * Sets the value of the lastUpdateDtm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLastUpdateDtm(String value) {
            this.lastUpdateDtm = value;
        }

        /**
         * Gets the value of the episodeNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEpisodeNo() {
            return episodeNo;
        }

        /**
         * Sets the value of the episodeNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEpisodeNo(String value) {
            this.episodeNo = value;
        }

        /**
         * Gets the value of the attendanceInstId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAttendanceInstId() {
            return attendanceInstId;
        }

        /**
         * Sets the value of the attendanceInstId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAttendanceInstId(String value) {
            this.attendanceInstId = value;
        }

        /**
         * Gets the value of the episReportStartDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEpisReportStartDate() {
            return episReportStartDate;
        }

        /**
         * Sets the value of the episReportStartDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEpisReportStartDate(String value) {
            this.episReportStartDate = value;
        }

        /**
         * Gets the value of the episReportEndDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEpisReportEndDate() {
            return episReportEndDate;
        }

        /**
         * Sets the value of the episReportEndDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEpisReportEndDate(String value) {
            this.episReportEndDate = value;
        }

        /**
         * Gets the value of the episTypeCd property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEpisTypeCd() {
            return episTypeCd;
        }

        /**
         * Sets the value of the episTypeCd property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEpisTypeCd(String value) {
            this.episTypeCd = value;
        }

        /**
         * Gets the value of the episTypeDesc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEpisTypeDesc() {
            return episTypeDesc;
        }

        /**
         * Sets the value of the episTypeDesc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEpisTypeDesc(String value) {
            this.episTypeDesc = value;
        }

        /**
         * Gets the value of the episTypeLtDesc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEpisTypeLtDesc() {
            return episTypeLtDesc;
        }

        /**
         * Sets the value of the episTypeLtDesc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEpisTypeLtDesc(String value) {
            this.episTypeLtDesc = value;
        }

        /**
         * Gets the value of the episReportTitle property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEpisReportTitle() {
            return episReportTitle;
        }

        /**
         * Sets the value of the episReportTitle property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEpisReportTitle(String value) {
            this.episReportTitle = value;
        }

        /**
         * Gets the value of the episReportDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEpisReportDate() {
            return episReportDate;
        }

        /**
         * Sets the value of the episReportDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEpisReportDate(String value) {
            this.episReportDate = value;
        }

        /**
         * Gets the value of the episTxtReport property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEpisTxtReport() {
            return episTxtReport;
        }

        /**
         * Sets the value of the episTxtReport property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEpisTxtReport(String value) {
            this.episTxtReport = value;
        }

        /**
         * Gets the value of the episHighlight property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEpisHighlight() {
            return episHighlight;
        }

        /**
         * Sets the value of the episHighlight property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEpisHighlight(String value) {
            this.episHighlight = value;
        }

        /**
         * Gets the value of the episRemark property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEpisRemark() {
            return episRemark;
        }

        /**
         * Sets the value of the episRemark property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEpisRemark(String value) {
            this.episRemark = value;
        }

        /**
         * Gets the value of the fileInd property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFileInd() {
            return fileInd;
        }

        /**
         * Sets the value of the fileInd property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFileInd(String value) {
            this.fileInd = value;
        }

        /**
         * Gets the value of the fileName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFileName() {
            return fileName;
        }

        /**
         * Sets the value of the fileName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFileName(String value) {
            this.fileName = value;
        }

        /**
         * Gets the value of the episReportId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEpisReportId() {
            return episReportId;
        }

        /**
         * Sets the value of the episReportId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEpisReportId(String value) {
            this.episReportId = value;
        }

        /**
         * Gets the value of the recordCreationDtm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRecordCreationDtm() {
            return recordCreationDtm;
        }

        /**
         * Sets the value of the recordCreationDtm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRecordCreationDtm(String value) {
            this.recordCreationDtm = value;
        }

        /**
         * Gets the value of the recordCreationInstId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRecordCreationInstId() {
            return recordCreationInstId;
        }

        /**
         * Sets the value of the recordCreationInstId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRecordCreationInstId(String value) {
            this.recordCreationInstId = value;
        }

        /**
         * Gets the value of the recordCreationInstName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRecordCreationInstName() {
            return recordCreationInstName;
        }

        /**
         * Sets the value of the recordCreationInstName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRecordCreationInstName(String value) {
            this.recordCreationInstName = value;
        }

        /**
         * Gets the value of the recordUpdateDtm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRecordUpdateDtm() {
            return recordUpdateDtm;
        }

        /**
         * Sets the value of the recordUpdateDtm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRecordUpdateDtm(String value) {
            this.recordUpdateDtm = value;
        }

        /**
         * Gets the value of the recordUpdateInstId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRecordUpdateInstId() {
            return recordUpdateInstId;
        }

        /**
         * Sets the value of the recordUpdateInstId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRecordUpdateInstId(String value) {
            this.recordUpdateInstId = value;
        }

        /**
         * Gets the value of the recordUpdateInstName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRecordUpdateInstName() {
            return recordUpdateInstName;
        }

        /**
         * Sets the value of the recordUpdateInstName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRecordUpdateInstName(String value) {
            this.recordUpdateInstName = value;
        }

    }

}
