//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.30 at 04:23:32 PM CST 
//


package org.hl7.v3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for inpatient_discharge_encounter_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="inpatient_discharge_encounter_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:hl7-org:v3}episode_no"/>
 *         &lt;element name="appointment_number" type="{urn:hl7-org:v3}appointment_number" minOccurs="0"/>
 *         &lt;element name="episode_start_dtm" type="{urn:hl7-org:v3}episode_start_dtm"/>
 *         &lt;element name="episode_urgency" type="{urn:hl7-org:v3}episode_urgency" minOccurs="0"/>
 *         &lt;element name="episode_start_specialty" type="{urn:hl7-org:v3}episode_start_specialty" minOccurs="0"/>
 *         &lt;element name="episode_start_specialty_remark" type="{urn:hl7-org:v3}episode_start_specialty_remark" minOccurs="0"/>
 *         &lt;element name="episode_attendance_ind" type="{urn:hl7-org:v3}episode_attendance_ind" minOccurs="0"/>
 *         &lt;element name="episode_end_dtm" type="{urn:hl7-org:v3}episode_end_dtm" minOccurs="0"/>
 *         &lt;element name="episode_end_specialty" type="{urn:hl7-org:v3}episode_end_specialty" minOccurs="0"/>
 *         &lt;element name="episode_end_specialty_remark" type="{urn:hl7-org:v3}episode_end_specialty_remark" minOccurs="0"/>
 *         &lt;element name="death_before_arrival_ind" type="{urn:hl7-org:v3}death_before_arrival_ind" minOccurs="0"/>
 *         &lt;element name="discharge_type" type="{urn:hl7-org:v3}discharge_type"/>
 *         &lt;element name="discharge_to_inst_id" type="{urn:hl7-org:v3}discharge_to_inst_id" minOccurs="0"/>
 *         &lt;element name="discharge_to_inst_name" type="{urn:hl7-org:v3}discharge_to_inst_name" minOccurs="0"/>
 *         &lt;element name="discharge_to_inst_lt_name" type="{urn:hl7-org:v3}discharge_to_inst_lt_name" minOccurs="0"/>
 *         &lt;element name="referral_no" type="{urn:hl7-org:v3}referral_no" minOccurs="0"/>
 *         &lt;element name="refer_from_inst_id" type="{urn:hl7-org:v3}refer_from_inst_id" minOccurs="0"/>
 *         &lt;element name="refer_from_inst_name" type="{urn:hl7-org:v3}refer_from_inst_name" minOccurs="0"/>
 *         &lt;element name="refer_from_inst_lt_name" type="{urn:hl7-org:v3}refer_from_inst_lt_name" minOccurs="0"/>
 *         &lt;element name="refer_from_prof_eng_name" type="{urn:hl7-org:v3}refer_from_prof_eng_name" minOccurs="0"/>
 *         &lt;element name="refer_from_prof_chi_name" type="{urn:hl7-org:v3}refer_from_prof_chi_name" minOccurs="0"/>
 *         &lt;element name="refer_from_encounter_no" type="{urn:hl7-org:v3}refer_from_encounter_no" minOccurs="0"/>
 *         &lt;element name="referral_source_cd" type="{urn:hl7-org:v3}referral_source_cd" minOccurs="0"/>
 *         &lt;element name="referral_source_desc" type="{urn:hl7-org:v3}referral_source_desc" minOccurs="0"/>
 *         &lt;element name="referral_source_lt_desc" type="{urn:hl7-org:v3}referral_source_lt_desc" minOccurs="0"/>
 *         &lt;element name="referral_specialty" type="{urn:hl7-org:v3}referral_specialty" minOccurs="0"/>
 *         &lt;element name="referral_specialty_remark" type="{urn:hl7-org:v3}referral_specialty_remark" minOccurs="0"/>
 *         &lt;element name="case_incharge_prof_eng_name" type="{urn:hl7-org:v3}case_incharge_prof_eng_name" minOccurs="0"/>
 *         &lt;element name="case_incharge_prof_chi_name" type="{urn:hl7-org:v3}case_incharge_prof_chi_name" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "inpatient_discharge_encounter_type", propOrder = {
    "episodeNo",
    "appointmentNumber",
    "episodeStartDtm",
    "episodeUrgency",
    "episodeStartSpecialty",
    "episodeStartSpecialtyRemark",
    "episodeAttendanceInd",
    "episodeEndDtm",
    "episodeEndSpecialty",
    "episodeEndSpecialtyRemark",
    "deathBeforeArrivalInd",
    "dischargeType",
    "dischargeToInstId",
    "dischargeToInstName",
    "dischargeToInstLtName",
    "referralNo",
    "referFromInstId",
    "referFromInstName",
    "referFromInstLtName",
    "referFromProfEngName",
    "referFromProfChiName",
    "referFromEncounterNo",
    "referralSourceCd",
    "referralSourceDesc",
    "referralSourceLtDesc",
    "referralSpecialty",
    "referralSpecialtyRemark",
    "caseInchargeProfEngName",
    "caseInchargeProfChiName"
})
public class InpatientDischargeEncounterType {

    @XmlElement(name = "episode_no", required = true)
    protected String episodeNo;
    @XmlElement(name = "appointment_number")
    protected String appointmentNumber;
    @XmlElement(name = "episode_start_dtm", required = true)
    protected String episodeStartDtm;
    @XmlElement(name = "episode_urgency")
    protected String episodeUrgency;
    @XmlElement(name = "episode_start_specialty")
    protected String episodeStartSpecialty;
    @XmlElement(name = "episode_start_specialty_remark")
    protected String episodeStartSpecialtyRemark;
    @XmlElement(name = "episode_attendance_ind")
    protected String episodeAttendanceInd;
    @XmlElement(name = "episode_end_dtm")
    protected String episodeEndDtm;
    @XmlElement(name = "episode_end_specialty")
    protected String episodeEndSpecialty;
    @XmlElement(name = "episode_end_specialty_remark")
    protected String episodeEndSpecialtyRemark;
    @XmlElement(name = "death_before_arrival_ind")
    protected String deathBeforeArrivalInd;
    @XmlElement(name = "discharge_type", required = true)
    protected String dischargeType;
    @XmlElement(name = "discharge_to_inst_id")
    protected String dischargeToInstId;
    @XmlElement(name = "discharge_to_inst_name")
    protected String dischargeToInstName;
    @XmlElement(name = "discharge_to_inst_lt_name")
    protected String dischargeToInstLtName;
    @XmlElement(name = "referral_no")
    protected String referralNo;
    @XmlElement(name = "refer_from_inst_id")
    protected String referFromInstId;
    @XmlElement(name = "refer_from_inst_name")
    protected String referFromInstName;
    @XmlElement(name = "refer_from_inst_lt_name")
    protected String referFromInstLtName;
    @XmlElement(name = "refer_from_prof_eng_name")
    protected String referFromProfEngName;
    @XmlElement(name = "refer_from_prof_chi_name")
    protected String referFromProfChiName;
    @XmlElement(name = "refer_from_encounter_no")
    protected String referFromEncounterNo;
    @XmlElement(name = "referral_source_cd")
    protected String referralSourceCd;
    @XmlElement(name = "referral_source_desc")
    protected String referralSourceDesc;
    @XmlElement(name = "referral_source_lt_desc")
    protected String referralSourceLtDesc;
    @XmlElement(name = "referral_specialty")
    protected String referralSpecialty;
    @XmlElement(name = "referral_specialty_remark")
    protected String referralSpecialtyRemark;
    @XmlElement(name = "case_incharge_prof_eng_name")
    protected String caseInchargeProfEngName;
    @XmlElement(name = "case_incharge_prof_chi_name")
    protected String caseInchargeProfChiName;

    /**
     * Gets the value of the episodeNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEpisodeNo() {
        return episodeNo;
    }

    /**
     * Sets the value of the episodeNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEpisodeNo(String value) {
        this.episodeNo = value;
    }

    /**
     * Gets the value of the appointmentNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppointmentNumber() {
        return appointmentNumber;
    }

    /**
     * Sets the value of the appointmentNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppointmentNumber(String value) {
        this.appointmentNumber = value;
    }

    /**
     * Gets the value of the episodeStartDtm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEpisodeStartDtm() {
        return episodeStartDtm;
    }

    /**
     * Sets the value of the episodeStartDtm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEpisodeStartDtm(String value) {
        this.episodeStartDtm = value;
    }

    /**
     * Gets the value of the episodeUrgency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEpisodeUrgency() {
        return episodeUrgency;
    }

    /**
     * Sets the value of the episodeUrgency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEpisodeUrgency(String value) {
        this.episodeUrgency = value;
    }

    /**
     * Gets the value of the episodeStartSpecialty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEpisodeStartSpecialty() {
        return episodeStartSpecialty;
    }

    /**
     * Sets the value of the episodeStartSpecialty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEpisodeStartSpecialty(String value) {
        this.episodeStartSpecialty = value;
    }

    /**
     * Gets the value of the episodeStartSpecialtyRemark property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEpisodeStartSpecialtyRemark() {
        return episodeStartSpecialtyRemark;
    }

    /**
     * Sets the value of the episodeStartSpecialtyRemark property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEpisodeStartSpecialtyRemark(String value) {
        this.episodeStartSpecialtyRemark = value;
    }

    /**
     * Gets the value of the episodeAttendanceInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEpisodeAttendanceInd() {
        return episodeAttendanceInd;
    }

    /**
     * Sets the value of the episodeAttendanceInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEpisodeAttendanceInd(String value) {
        this.episodeAttendanceInd = value;
    }

    /**
     * Gets the value of the episodeEndDtm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEpisodeEndDtm() {
        return episodeEndDtm;
    }

    /**
     * Sets the value of the episodeEndDtm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEpisodeEndDtm(String value) {
        this.episodeEndDtm = value;
    }

    /**
     * Gets the value of the episodeEndSpecialty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEpisodeEndSpecialty() {
        return episodeEndSpecialty;
    }

    /**
     * Sets the value of the episodeEndSpecialty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEpisodeEndSpecialty(String value) {
        this.episodeEndSpecialty = value;
    }

    /**
     * Gets the value of the episodeEndSpecialtyRemark property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEpisodeEndSpecialtyRemark() {
        return episodeEndSpecialtyRemark;
    }

    /**
     * Sets the value of the episodeEndSpecialtyRemark property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEpisodeEndSpecialtyRemark(String value) {
        this.episodeEndSpecialtyRemark = value;
    }

    /**
     * Gets the value of the deathBeforeArrivalInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeathBeforeArrivalInd() {
        return deathBeforeArrivalInd;
    }

    /**
     * Sets the value of the deathBeforeArrivalInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeathBeforeArrivalInd(String value) {
        this.deathBeforeArrivalInd = value;
    }

    /**
     * Gets the value of the dischargeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDischargeType() {
        return dischargeType;
    }

    /**
     * Sets the value of the dischargeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDischargeType(String value) {
        this.dischargeType = value;
    }

    /**
     * Gets the value of the dischargeToInstId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDischargeToInstId() {
        return dischargeToInstId;
    }

    /**
     * Sets the value of the dischargeToInstId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDischargeToInstId(String value) {
        this.dischargeToInstId = value;
    }

    /**
     * Gets the value of the dischargeToInstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDischargeToInstName() {
        return dischargeToInstName;
    }

    /**
     * Sets the value of the dischargeToInstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDischargeToInstName(String value) {
        this.dischargeToInstName = value;
    }

    /**
     * Gets the value of the dischargeToInstLtName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDischargeToInstLtName() {
        return dischargeToInstLtName;
    }

    /**
     * Sets the value of the dischargeToInstLtName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDischargeToInstLtName(String value) {
        this.dischargeToInstLtName = value;
    }

    /**
     * Gets the value of the referralNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferralNo() {
        return referralNo;
    }

    /**
     * Sets the value of the referralNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferralNo(String value) {
        this.referralNo = value;
    }

    /**
     * Gets the value of the referFromInstId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferFromInstId() {
        return referFromInstId;
    }

    /**
     * Sets the value of the referFromInstId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferFromInstId(String value) {
        this.referFromInstId = value;
    }

    /**
     * Gets the value of the referFromInstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferFromInstName() {
        return referFromInstName;
    }

    /**
     * Sets the value of the referFromInstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferFromInstName(String value) {
        this.referFromInstName = value;
    }

    /**
     * Gets the value of the referFromInstLtName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferFromInstLtName() {
        return referFromInstLtName;
    }

    /**
     * Sets the value of the referFromInstLtName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferFromInstLtName(String value) {
        this.referFromInstLtName = value;
    }

    /**
     * Gets the value of the referFromProfEngName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferFromProfEngName() {
        return referFromProfEngName;
    }

    /**
     * Sets the value of the referFromProfEngName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferFromProfEngName(String value) {
        this.referFromProfEngName = value;
    }

    /**
     * Gets the value of the referFromProfChiName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferFromProfChiName() {
        return referFromProfChiName;
    }

    /**
     * Sets the value of the referFromProfChiName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferFromProfChiName(String value) {
        this.referFromProfChiName = value;
    }

    /**
     * Gets the value of the referFromEncounterNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferFromEncounterNo() {
        return referFromEncounterNo;
    }

    /**
     * Sets the value of the referFromEncounterNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferFromEncounterNo(String value) {
        this.referFromEncounterNo = value;
    }

    /**
     * Gets the value of the referralSourceCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferralSourceCd() {
        return referralSourceCd;
    }

    /**
     * Sets the value of the referralSourceCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferralSourceCd(String value) {
        this.referralSourceCd = value;
    }

    /**
     * Gets the value of the referralSourceDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferralSourceDesc() {
        return referralSourceDesc;
    }

    /**
     * Sets the value of the referralSourceDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferralSourceDesc(String value) {
        this.referralSourceDesc = value;
    }

    /**
     * Gets the value of the referralSourceLtDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferralSourceLtDesc() {
        return referralSourceLtDesc;
    }

    /**
     * Sets the value of the referralSourceLtDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferralSourceLtDesc(String value) {
        this.referralSourceLtDesc = value;
    }

    /**
     * Gets the value of the referralSpecialty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferralSpecialty() {
        return referralSpecialty;
    }

    /**
     * Sets the value of the referralSpecialty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferralSpecialty(String value) {
        this.referralSpecialty = value;
    }

    /**
     * Gets the value of the referralSpecialtyRemark property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferralSpecialtyRemark() {
        return referralSpecialtyRemark;
    }

    /**
     * Sets the value of the referralSpecialtyRemark property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferralSpecialtyRemark(String value) {
        this.referralSpecialtyRemark = value;
    }

    /**
     * Gets the value of the caseInchargeProfEngName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaseInchargeProfEngName() {
        return caseInchargeProfEngName;
    }

    /**
     * Sets the value of the caseInchargeProfEngName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaseInchargeProfEngName(String value) {
        this.caseInchargeProfEngName = value;
    }

    /**
     * Gets the value of the caseInchargeProfChiName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaseInchargeProfChiName() {
        return caseInchargeProfChiName;
    }

    /**
     * Sets the value of the caseInchargeProfChiName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaseInchargeProfChiName(String value) {
        this.caseInchargeProfChiName = value;
    }

}
