create or replace FUNCTION "NHS_LIS_ARCHECKLIST_RMK"
(
  V_ACTID ARCARD_CHECKLIST_DTL.ACTID%TYPE,
  V_TYPE ARCARD_CHECKLIST_DTL.TYPE%TYPE,
  V_OTHERR1 ARCARD_CHECKLIST_DTL.CHECK_ID%TYPE,
  V_OTHERR2 ARCARD_CHECKLIST_DTL.CHECK_ID%TYPE,
  V_OTHERP1 ARCARD_CHECKLIST_DTL.CHECK_ID%TYPE,
  V_OTHERP2 ARCARD_CHECKLIST_DTL.CHECK_ID%TYPE
)
  RETURN TYPES.CURSOR_TYPE
--    RETURN VARCHAR2
AS
  OUTCUR TYPES.CURSOR_TYPE;
  LS_ID EXCLUSIONS.ID%TYPE;
  SQLSTR VARCHAR2(5000);
  
BEGIN
  OPEN OUTCUR FOR
  SELECT
  MAX(CASE WHEN CHECK_ID=V_OTHERR1 THEN OTHER_DESC ELSE NULL END) AS OTHER_R1,
  MAX(CASE WHEN CHECK_ID=V_OTHERR2 THEN OTHER_DESC ELSE NULL END) AS OTHER_R2,
  MAX(CASE WHEN CHECK_ID=V_OTHERP1 THEN OTHER_DESC ELSE NULL END) AS OTHER_P1,
  MAX(CASE WHEN CHECK_ID=V_OTHERP2 THEN OTHER_DESC ELSE NULL END) AS OTHER_P2
  FROM ARCARD_CHECKLIST_DTL
  WHERE ACTID = V_ACTID
  AND TYPE = V_TYPE ;

--  OPEN OUTCUR FOR SQLSTR;      
  RETURN OUTCUR;
--    RETURN SQLSTR;
END NHS_LIS_ARCHECKLIST_RMK;
/