create or replace FUNCTION "NHS_ACT_ARCHECKLIST"
(	V_ACTION IN VARCHAR2,
	V_ACTID IN VARCHAR2,
  	V_TYPE IN VARCHAR2,
	V_01 IN VARCHAR2,
	V_02 IN VARCHAR2,
	V_03 IN VARCHAR2,
	V_04 IN VARCHAR2,
	V_05 IN VARCHAR2,
	V_06 IN VARCHAR2,
	V_07 IN VARCHAR2,
	V_08 IN VARCHAR2,
	V_09 IN VARCHAR2,
	V_10 IN VARCHAR2,
	V_11 IN VARCHAR2,
	V_12 IN VARCHAR2,
	V_13 IN VARCHAR2,
	V_14 IN VARCHAR2,
	V_15 IN VARCHAR2,
	V_16 IN VARCHAR2,
	V_17 IN VARCHAR2,
	V_18 IN VARCHAR2,
	V_19 IN VARCHAR2,
	V_20 IN VARCHAR2,
	V_21 IN VARCHAR2,
	V_22 IN VARCHAR2,  
 	V_R01 IN VARCHAR2,
	V_R02 IN VARCHAR2,
	V_P01 IN VARCHAR2,
	V_P02 IN VARCHAR2,
	o_errmsg OUT VARCHAR2
)
	RETURN NUMBER
AS
  O_ERRCODE NUMBER;
  IDCOUNT NUMBER;
  V_EXISTS NUMBER;
  V_ID VARCHAR2(2);
  i NUMBER;

  CURSOR C_GETCHECKID IS
  SELECT CHECK_ID
  FROM ARCARD_CHECKLIST
  ORDER BY 1;
BEGIN
  o_errcode := 0;
  O_ERRMSG := 'OK';

  OPEN C_GETCHECKID;
	LOOP
	FETCH C_GETCHECKID INTO V_ID;
  EXIT WHEN C_GETCHECKID%NOTFOUND;
    IF V_ID = '01' THEN
      SELECT COUNT(ACTID)
      INTO V_EXISTS
      FROM ARCARD_CHECKLIST_DTL
      WHERE ACTID = V_ACTID
      AND TYPE = V_TYPE
      AND CHECK_ID = '01';

      IF V_EXISTS = 0 THEN
        INSERT INTO ARCARD_CHECKLIST_DTL (ACTID,TYPE,CHECK_ID,OTHER_DESC,ENABLED) VALUES (V_ACTID,V_TYPE,'01',NULL, V_01);
      ELSE
        UPDATE ARCARD_CHECKLIST_DTL
        SET ENABLED = V_01
        WHERE ACTID = V_ACTID
        AND TYPE = V_TYPE
        AND CHECK_ID = '01';
      END IF;
    ELSIF V_ID = '02' THEN
      SELECT COUNT(ACTID)
      INTO V_EXISTS
      FROM ARCARD_CHECKLIST_DTL
      WHERE ACTID = V_ACTID
      AND TYPE = V_TYPE
      AND CHECK_ID = '02';

      IF V_EXISTS = 0 THEN
        INSERT INTO ARCARD_CHECKLIST_DTL (ACTID,TYPE,CHECK_ID,OTHER_DESC,ENABLED) VALUES (V_ACTID,V_TYPE,'02',NULL, V_02);
      ELSE
        UPDATE ARCARD_CHECKLIST_DTL
        SET ENABLED = V_02
        WHERE ACTID = V_ACTID
        AND TYPE = V_TYPE
        AND CHECK_ID = '02';
      END IF;
    ELSIF V_ID = '03' THEN
      SELECT COUNT(ACTID)
      INTO V_EXISTS
      FROM ARCARD_CHECKLIST_DTL
      WHERE ACTID = V_ACTID
      AND TYPE = V_TYPE
      AND CHECK_ID = '03';

      IF V_EXISTS = 0 THEN
        INSERT INTO ARCARD_CHECKLIST_DTL (ACTID,TYPE,CHECK_ID,OTHER_DESC,ENABLED) VALUES (V_ACTID,V_TYPE,'03',NULL, V_03);
      ELSE
        UPDATE ARCARD_CHECKLIST_DTL
        SET ENABLED = V_03
        WHERE ACTID = V_ACTID
        AND TYPE = V_TYPE
        AND CHECK_ID = '03';
      END IF;
    ELSIF V_ID = '04' THEN
      SELECT COUNT(ACTID)
      INTO V_EXISTS
      FROM ARCARD_CHECKLIST_DTL
      WHERE ACTID = V_ACTID
      AND TYPE = V_TYPE
      AND CHECK_ID = '04';

      IF V_EXISTS = 0 THEN
        INSERT INTO ARCARD_CHECKLIST_DTL (ACTID,TYPE,CHECK_ID,OTHER_DESC,ENABLED) VALUES (V_ACTID,V_TYPE,'04',NULL, V_04);
      ELSE
        UPDATE ARCARD_CHECKLIST_DTL
        SET ENABLED = V_04
        WHERE ACTID = V_ACTID
        AND TYPE = V_TYPE
        AND CHECK_ID = '04';
      END IF;
    ELSIF V_ID = '05' THEN
      SELECT COUNT(ACTID)
      INTO V_EXISTS
      FROM ARCARD_CHECKLIST_DTL
      WHERE ACTID = V_ACTID
      AND TYPE = V_TYPE
      AND CHECK_ID = '05';

      IF V_EXISTS = 0 THEN
        INSERT INTO ARCARD_CHECKLIST_DTL (ACTID,TYPE,CHECK_ID,OTHER_DESC,ENABLED) VALUES (V_ACTID,V_TYPE,'05',NULL, V_05);
      ELSE
        UPDATE ARCARD_CHECKLIST_DTL
        SET ENABLED = V_05
        WHERE ACTID = V_ACTID
        AND TYPE = V_TYPE
        AND CHECK_ID = '05';
      END IF;
    ELSIF V_ID = '06' THEN
      SELECT COUNT(ACTID)
      INTO V_EXISTS
      FROM ARCARD_CHECKLIST_DTL
      WHERE ACTID = V_ACTID
      AND TYPE = V_TYPE
      AND CHECK_ID = '06';

      IF V_EXISTS = 0 THEN
        INSERT INTO ARCARD_CHECKLIST_DTL (ACTID,TYPE,CHECK_ID,OTHER_DESC,ENABLED) VALUES (V_ACTID,V_TYPE,'06',NULL, V_06);
      ELSE
        UPDATE ARCARD_CHECKLIST_DTL
        SET ENABLED = V_06
        WHERE ACTID = V_ACTID
        AND TYPE = V_TYPE
        AND CHECK_ID = '06';
      END IF;
    ELSIF V_ID = '07' THEN
      SELECT COUNT(ACTID)
      INTO V_EXISTS
      FROM ARCARD_CHECKLIST_DTL
      WHERE ACTID = V_ACTID
      AND TYPE = V_TYPE
      AND CHECK_ID = '07';

      IF V_EXISTS = 0 THEN
        INSERT INTO ARCARD_CHECKLIST_DTL (ACTID,TYPE,CHECK_ID,OTHER_DESC,ENABLED) VALUES (V_ACTID,V_TYPE,'07',NULL, V_07);
      ELSE
        UPDATE ARCARD_CHECKLIST_DTL
        SET ENABLED = V_07
        WHERE ACTID = V_ACTID
        AND TYPE = V_TYPE
        AND CHECK_ID = '07';
      END IF;
    ELSIF V_ID = '08' THEN
      SELECT COUNT(ACTID)
      INTO V_EXISTS
      FROM ARCARD_CHECKLIST_DTL
      WHERE ACTID = V_ACTID
      AND TYPE = V_TYPE
      AND CHECK_ID = '08';

      IF V_EXISTS = 0 THEN
        INSERT INTO ARCARD_CHECKLIST_DTL (ACTID,TYPE,CHECK_ID,OTHER_DESC,ENABLED) VALUES (V_ACTID,V_TYPE,'08',NULL, V_08);
      ELSE
        UPDATE ARCARD_CHECKLIST_DTL
        SET ENABLED = V_08
        WHERE ACTID = V_ACTID
        AND TYPE = V_TYPE
        AND CHECK_ID = '08';
      END IF;
    ELSIF V_ID = '09' THEN
      SELECT COUNT(ACTID)
      INTO V_EXISTS
      FROM ARCARD_CHECKLIST_DTL
      WHERE ACTID = V_ACTID
      AND TYPE = V_TYPE
      AND CHECK_ID = '09';

      IF V_EXISTS = 0 THEN
        INSERT INTO ARCARD_CHECKLIST_DTL (ACTID,TYPE,CHECK_ID,OTHER_DESC,ENABLED) VALUES (V_ACTID,V_TYPE,'09',NULL, V_09);
      ELSE
        UPDATE ARCARD_CHECKLIST_DTL
        SET ENABLED = V_09
        WHERE ACTID = V_ACTID
        AND TYPE = V_TYPE
        AND CHECK_ID = '09';
      END IF;
    ELSIF V_ID = '10' THEN
      SELECT COUNT(ACTID)
      INTO V_EXISTS
      FROM ARCARD_CHECKLIST_DTL
      WHERE ACTID = V_ACTID
      AND TYPE = V_TYPE
      AND CHECK_ID = '10';

      IF V_EXISTS = 0 THEN
        INSERT INTO ARCARD_CHECKLIST_DTL (ACTID,TYPE,CHECK_ID,OTHER_DESC,ENABLED) VALUES (V_ACTID,V_TYPE,'10',NULL, V_10);
      ELSE
        UPDATE ARCARD_CHECKLIST_DTL
        SET ENABLED = V_10
        WHERE ACTID = V_ACTID
        AND TYPE = V_TYPE
        AND CHECK_ID = '10';
      END IF;
    ELSIF V_ID = '11' THEN
      SELECT COUNT(ACTID)
      INTO V_EXISTS
      FROM ARCARD_CHECKLIST_DTL
      WHERE ACTID = V_ACTID
      AND TYPE = V_TYPE
      AND CHECK_ID = '11';

      IF V_EXISTS = 0 THEN
        INSERT INTO ARCARD_CHECKLIST_DTL (ACTID,TYPE,CHECK_ID,OTHER_DESC,ENABLED) VALUES (V_ACTID,V_TYPE,'11',NULL, V_11);
      ELSE
        UPDATE ARCARD_CHECKLIST_DTL
        SET ENABLED = V_11
        WHERE ACTID = V_ACTID
        AND TYPE = V_TYPE
        AND CHECK_ID = '11';
      END IF;
    ELSIF V_ID = '12' THEN
      SELECT COUNT(ACTID)
      INTO V_EXISTS
      FROM ARCARD_CHECKLIST_DTL
      WHERE ACTID = V_ACTID
      AND TYPE = V_TYPE
      AND CHECK_ID = '12';

      IF V_EXISTS = 0 THEN
        INSERT INTO ARCARD_CHECKLIST_DTL (ACTID,TYPE,CHECK_ID,OTHER_DESC,ENABLED) VALUES (V_ACTID,V_TYPE,'12',NULL, V_12);
      ELSE
        UPDATE ARCARD_CHECKLIST_DTL
        SET ENABLED = V_12
        WHERE ACTID = V_ACTID
        AND TYPE = V_TYPE
        AND CHECK_ID = '12';
      END IF;
    ELSIF V_ID = '13' THEN
      SELECT COUNT(ACTID)
      INTO V_EXISTS
      FROM ARCARD_CHECKLIST_DTL
      WHERE ACTID = V_ACTID
      AND TYPE = V_TYPE
      AND CHECK_ID = '13';

      IF V_EXISTS = 0 THEN
        INSERT INTO ARCARD_CHECKLIST_DTL (ACTID,TYPE,CHECK_ID,OTHER_DESC,ENABLED) VALUES (V_ACTID,V_TYPE,'13',NULL, V_13);
      ELSE
        UPDATE ARCARD_CHECKLIST_DTL
        SET ENABLED = V_13
        WHERE ACTID = V_ACTID
        AND TYPE = V_TYPE
        AND CHECK_ID = '13';
      END IF;
    ELSIF V_ID = '14' THEN
      SELECT COUNT(ACTID)
      INTO V_EXISTS
      FROM ARCARD_CHECKLIST_DTL
      WHERE ACTID = V_ACTID
      AND TYPE = V_TYPE
      AND CHECK_ID = '14';

      IF V_EXISTS = 0 THEN
        INSERT INTO ARCARD_CHECKLIST_DTL (ACTID,TYPE,CHECK_ID,OTHER_DESC,ENABLED) VALUES (V_ACTID,V_TYPE,'14',V_R01, V_14);
      ELSE
        UPDATE ARCARD_CHECKLIST_DTL
        SET ENABLED = V_14,
        OTHER_DESC = V_R01
        WHERE ACTID = V_ACTID
        AND TYPE = V_TYPE
        AND CHECK_ID = '14';
      END IF;
    ELSIF V_ID = '15' THEN
      SELECT COUNT(ACTID)
      INTO V_EXISTS
      FROM ARCARD_CHECKLIST_DTL
      WHERE ACTID = V_ACTID
      AND TYPE = V_TYPE
      AND CHECK_ID = '15';

      IF V_EXISTS = 0 THEN
        INSERT INTO ARCARD_CHECKLIST_DTL (ACTID,TYPE,CHECK_ID,OTHER_DESC,ENABLED) VALUES (V_ACTID,V_TYPE,'15',V_R02, V_15);
      ELSE
        UPDATE ARCARD_CHECKLIST_DTL
        SET ENABLED = V_15,
        OTHER_DESC = V_R02
        WHERE ACTID = V_ACTID
        AND TYPE = V_TYPE
        AND CHECK_ID = '15';
      END IF;
    ELSIF V_ID = '16' THEN
      SELECT COUNT(ACTID)
      INTO V_EXISTS
      FROM ARCARD_CHECKLIST_DTL
      WHERE ACTID = V_ACTID
      AND TYPE = V_TYPE
      AND CHECK_ID = '16';

      IF V_EXISTS = 0 THEN
        INSERT INTO ARCARD_CHECKLIST_DTL (ACTID,TYPE,CHECK_ID,OTHER_DESC,ENABLED) VALUES (V_ACTID,V_TYPE,'16',NULL, V_16);
      ELSE
        UPDATE ARCARD_CHECKLIST_DTL
        SET ENABLED = V_16
        WHERE ACTID = V_ACTID
        AND TYPE = V_TYPE
        AND CHECK_ID = '16';
      END IF;
    ELSIF V_ID = '17' THEN
      SELECT COUNT(ACTID)
      INTO V_EXISTS
      FROM ARCARD_CHECKLIST_DTL
      WHERE ACTID = V_ACTID
      AND TYPE = V_TYPE
      AND CHECK_ID = '17';

      IF V_EXISTS = 0 THEN
        INSERT INTO ARCARD_CHECKLIST_DTL (ACTID,TYPE,CHECK_ID,OTHER_DESC,ENABLED) VALUES (V_ACTID,V_TYPE,'17',NULL, V_17);
      ELSE
        UPDATE ARCARD_CHECKLIST_DTL
        SET ENABLED = V_17
        WHERE ACTID = V_ACTID
        AND TYPE = V_TYPE
        AND CHECK_ID = '17';
      END IF;
    ELSIF V_ID = '18' THEN
      SELECT COUNT(ACTID)
      INTO V_EXISTS
      FROM ARCARD_CHECKLIST_DTL
      WHERE ACTID = V_ACTID
      AND TYPE = V_TYPE
      AND CHECK_ID = '18';

      IF V_EXISTS = 0 THEN
        INSERT INTO ARCARD_CHECKLIST_DTL (ACTID,TYPE,CHECK_ID,OTHER_DESC,ENABLED) VALUES (V_ACTID,V_TYPE,'18',NULL, V_18);
      ELSE
        UPDATE ARCARD_CHECKLIST_DTL
        SET ENABLED = V_18
        WHERE ACTID = V_ACTID
        AND TYPE = V_TYPE
        AND CHECK_ID = '18';
      END IF;
    ELSIF V_ID = '19' THEN
      SELECT COUNT(ACTID)
      INTO V_EXISTS
      FROM ARCARD_CHECKLIST_DTL
      WHERE ACTID = V_ACTID
      AND TYPE = V_TYPE
      AND CHECK_ID = '19';

      IF V_EXISTS = 0 THEN
        INSERT INTO ARCARD_CHECKLIST_DTL (ACTID,TYPE,CHECK_ID,OTHER_DESC,ENABLED) VALUES (V_ACTID,V_TYPE,'19',V_P01, V_19);
      ELSE
        UPDATE ARCARD_CHECKLIST_DTL
        SET ENABLED = V_19,
        OTHER_DESC = V_P01
        WHERE ACTID = V_ACTID
        AND TYPE = V_TYPE
        AND CHECK_ID = '19';
      END IF;
    ELSIF V_ID = '20' THEN
      SELECT COUNT(ACTID)
      INTO V_EXISTS
      FROM ARCARD_CHECKLIST_DTL
      WHERE ACTID = V_ACTID
      AND TYPE = V_TYPE
      AND CHECK_ID = '20';

      IF V_EXISTS = 0 THEN
        INSERT INTO ARCARD_CHECKLIST_DTL (ACTID,TYPE,CHECK_ID,OTHER_DESC,ENABLED) VALUES (V_ACTID,V_TYPE,'20',V_P02, V_20);
      ELSE
        UPDATE ARCARD_CHECKLIST_DTL
        SET ENABLED = V_20,
        OTHER_DESC = V_P02
        WHERE ACTID = V_ACTID
        AND TYPE = V_TYPE
        AND CHECK_ID = '20';
      END IF;
    ELSIF V_ID = '21' THEN
      SELECT COUNT(ACTID)
      INTO V_EXISTS
      FROM ARCARD_CHECKLIST_DTL
      WHERE ACTID = V_ACTID
      AND TYPE = V_TYPE
      AND CHECK_ID = '21';

      IF V_EXISTS = 0 THEN
        INSERT INTO ARCARD_CHECKLIST_DTL (ACTID,TYPE,CHECK_ID,OTHER_DESC,ENABLED) VALUES (V_ACTID,V_TYPE,'21',NULL, V_21);
      ELSE
        UPDATE ARCARD_CHECKLIST_DTL
        SET ENABLED = V_21
        WHERE ACTID = V_ACTID
        AND TYPE = V_TYPE
        AND CHECK_ID = '21';
      END IF;
    ELSIF V_ID = '22' THEN
      SELECT COUNT(ACTID)
      INTO V_EXISTS
      FROM ARCARD_CHECKLIST_DTL
      WHERE ACTID = V_ACTID
      AND TYPE = V_TYPE
      AND CHECK_ID = '22';

      IF V_EXISTS = 0 THEN
        INSERT INTO ARCARD_CHECKLIST_DTL (ACTID,TYPE,CHECK_ID,OTHER_DESC,ENABLED) VALUES (V_ACTID,V_TYPE,'22',NULL, V_22);
      ELSE
        UPDATE ARCARD_CHECKLIST_DTL
        SET ENABLED = V_22
        WHERE ACTID = V_ACTID
        AND TYPE = V_TYPE
        AND CHECK_ID = '22';
      END IF;      
    END IF;
	END LOOP;
	CLOSE C_GETCHECKID;

  RETURN o_errcode;
EXCEPTION
WHEN OTHERS THEN
	o_errcode := -1;
	o_errmsg:= o_errmsg || SQLERRM;
	ROLLBACK;
	RETURN o_errCode;
END NHS_ACT_ARCHECKLIST;
/