create or replace
FUNCTION "NHS_LIS_ARCHECKLIST"
(
  V_ACTID ARCARD_CHECKLIST_DTL.ACTID%TYPE,
  V_TYPE ARCARD_CHECKLIST_DTL.TYPE%TYPE
)
  RETURN TYPES.CURSOR_TYPE
--    RETURN VARCHAR2
AS
  OUTCUR TYPES.CURSOR_TYPE;
  LS_ID EXCLUSIONS.ID%TYPE;
  SQLSTR VARCHAR2(5000);
  
BEGIN
  OPEN OUTCUR FOR
  SELECT * FROM (
     SELECT CHECK_ID, ENABLED
     FROM ARCARD_CHECKLIST_DTL ACD
     WHERE TYPE = V_TYPE
     AND ACD.ACTID = V_ACTID
  )
  PIVOT
  (
     SUM(ENABLED)
     FOR CHECK_ID IN ('01','02','03','04','05','06','07','08','09','10','11','12','13','14','15','16','17','18','19','20')
  )
  ;

--  OPEN OUTCUR FOR SQLSTR;      
  RETURN OUTCUR;
--    RETURN SQLSTR;
END NHS_LIS_ARCHECKLIST;
/