create or replace FUNCTION "NHS_ACT_GENEXCLUSION"
(	V_ACTION IN VARCHAR2,
  V_ACTID ARCARD_EXCLUSIONS.ACTID%TYPE, 
	V_01 IN VARCHAR2,
	V_02 IN VARCHAR2,
	V_03 IN VARCHAR2,
	V_04 IN VARCHAR2,
	V_05 IN VARCHAR2,
	V_06 IN VARCHAR2,
	V_07 IN VARCHAR2,
	V_08 IN VARCHAR2,
	V_09 IN VARCHAR2,
	V_10 IN VARCHAR2,
	V_11 IN VARCHAR2,
	V_12 IN VARCHAR2,
	V_13 IN VARCHAR2,
	V_14 IN VARCHAR2,
	V_15 IN VARCHAR2,
	V_16 IN VARCHAR2,
	V_17 IN VARCHAR2,
	V_18 IN VARCHAR2,
	V_19 IN VARCHAR2,
	V_20 IN VARCHAR2,
	V_21 IN VARCHAR2,
	V_22 IN VARCHAR2,
	V_23 IN VARCHAR2,
	V_24 IN VARCHAR2,
	V_25 IN VARCHAR2,
	V_26 IN VARCHAR2,
	V_27 IN VARCHAR2,
	V_28 IN VARCHAR2,
	V_29 IN VARCHAR2,
	V_30 IN VARCHAR2,
	V_31 IN VARCHAR2,
	V_32 IN VARCHAR2,
  V_33 IN VARCHAR2,
	o_errmsg OUT VARCHAR2
)
	RETURN NUMBER
AS
  O_ERRCODE NUMBER;
  IDCOUNT NUMBER;
  V_CARDID ACTID_CARDID_MAPPING.CARDID%TYPE;
  i NUMBER;
BEGIN
  o_errcode := 0;
  O_ERRMSG := 'OK';
  IDCOUNT := 0;
 
-- Administration fee
  IF V_01 = '01' THEN
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = V_01;
    
    IF IDCOUNT = 0 THEN
      SELECT CARDID INTO V_CARDID FROM ACTID_CARDID_MAPPING WHERE ACTID = V_ACTID;
    
      INSERT INTO ARCARD_EXCLUSIONS (CARDID, ID, ACTID) VALUES (V_CARDID, V_01, V_ACTID);
    END IF;    
  ELSE
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = '01';
    
    IF IDCOUNT > 0 THEN
      DELETE FROM ARCARD_EXCLUSIONS WHERE ACTID = V_ACTID AND ID = '01';
    END IF;    
  END IF;

-- Back support/ Girdle 
  IF V_02 = '02' THEN
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = V_02;
    
    IF IDCOUNT = 0 THEN
      SELECT CARDID INTO V_CARDID FROM ACTID_CARDID_MAPPING WHERE ACTID = V_ACTID;
    
      INSERT INTO ARCARD_EXCLUSIONS (CARDID, ID, ACTID) VALUES (V_CARDID, V_02, V_ACTID);
    END IF;    
  ELSE
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = '02';
    
    IF IDCOUNT > 0 THEN
      DELETE FROM ARCARD_EXCLUSIONS WHERE ACTID = V_ACTID AND ID = '02';
    END IF;    
  END IF;

-- BET/ Pilates  
  IF V_03 = '03' THEN
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = V_03;
    
    IF IDCOUNT = 0 THEN
      SELECT CARDID INTO V_CARDID FROM ACTID_CARDID_MAPPING WHERE ACTID = V_ACTID;
    
      INSERT INTO ARCARD_EXCLUSIONS (CARDID, ID, ACTID) VALUES (V_CARDID, V_03, V_ACTID);
    END IF;    
  ELSE
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = '03';
    
    IF IDCOUNT > 0 THEN
      DELETE FROM ARCARD_EXCLUSIONS WHERE ACTID = V_ACTID AND ID = '03';
    END IF;    
  END IF;

-- Birth Defects
  IF V_04 = '04' THEN
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = V_04;
    
    IF IDCOUNT = 0 THEN
      SELECT CARDID INTO V_CARDID FROM ACTID_CARDID_MAPPING WHERE ACTID = V_ACTID;
    
      INSERT INTO ARCARD_EXCLUSIONS (CARDID, ID, ACTID) VALUES (V_CARDID, V_04, V_ACTID);
    END IF;    
  ELSE
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = '04';
    
    IF IDCOUNT > 0 THEN
      DELETE FROM ARCARD_EXCLUSIONS WHERE ACTID = V_ACTID AND ID = '04';
    END IF;    
  END IF;

-- Companion Beds
  IF V_05 = '05' THEN
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = V_05;
    
    IF IDCOUNT = 0 THEN
      SELECT CARDID INTO V_CARDID FROM ACTID_CARDID_MAPPING WHERE ACTID = V_ACTID;
    
      INSERT INTO ARCARD_EXCLUSIONS (CARDID, ID, ACTID) VALUES (V_CARDID, V_05, V_ACTID);
    END IF;    
  ELSE
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = '05';
    
    IF IDCOUNT > 0 THEN
      DELETE FROM ARCARD_EXCLUSIONS WHERE ACTID = V_ACTID AND ID = '05';
    END IF;    
  END IF;
 
-- Congenital conditions
  IF V_06 = '06' THEN
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = V_06;
    
    IF IDCOUNT = 0 THEN
      SELECT CARDID INTO V_CARDID FROM ACTID_CARDID_MAPPING WHERE ACTID = V_ACTID;
    
      INSERT INTO ARCARD_EXCLUSIONS (CARDID, ID, ACTID) VALUES (V_CARDID, V_06, V_ACTID);
    END IF;    
  ELSE
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = '06';
    
    IF IDCOUNT > 0 THEN
      DELETE FROM ARCARD_EXCLUSIONS WHERE ACTID = V_ACTID AND ID = '06';
    END IF;    
  END IF;
  
-- Contraception
  IF V_07 = '07' THEN
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = V_07;
    
    IF IDCOUNT = 0 THEN
      SELECT CARDID INTO V_CARDID FROM ACTID_CARDID_MAPPING WHERE ACTID = V_ACTID;
    
      INSERT INTO ARCARD_EXCLUSIONS (CARDID, ID, ACTID) VALUES (V_CARDID, V_07, V_ACTID);
    END IF;    
  ELSE
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = '07';
    
    IF IDCOUNT > 0 THEN
      DELETE FROM ARCARD_EXCLUSIONS WHERE ACTID = V_ACTID AND ID = '07';
    END IF;    
  END IF;
  
-- Cosmetic related  
  IF V_08 = '08' THEN
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = V_08;
    
    IF IDCOUNT = 0 THEN
      SELECT CARDID INTO V_CARDID FROM ACTID_CARDID_MAPPING WHERE ACTID = V_ACTID;
    
      INSERT INTO ARCARD_EXCLUSIONS (CARDID, ID, ACTID) VALUES (V_CARDID, V_08, V_ACTID);
    END IF;    
  ELSE
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = '08';
    
    IF IDCOUNT > 0 THEN
      DELETE FROM ARCARD_EXCLUSIONS WHERE ACTID = V_ACTID AND ID = '08';
    END IF;    
  END IF;
  
-- Dental related  
  IF V_09 = '09' THEN
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = V_09;
    
    IF IDCOUNT = 0 THEN
      SELECT CARDID INTO V_CARDID FROM ACTID_CARDID_MAPPING WHERE ACTID = V_ACTID;
    
      INSERT INTO ARCARD_EXCLUSIONS (CARDID, ID, ACTID) VALUES (V_CARDID, V_09, V_ACTID);
    END IF;    
  ELSE
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = '09';
    
    IF IDCOUNT > 0 THEN
      DELETE FROM ARCARD_EXCLUSIONS WHERE ACTID = V_ACTID AND ID = '09';
    END IF;    
  END IF;
  
-- Developmental Abnormalities
  IF V_10 = '10' THEN
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = V_10;
    
    IF IDCOUNT = 0 THEN
      SELECT CARDID INTO V_CARDID FROM ACTID_CARDID_MAPPING WHERE ACTID = V_ACTID;
    
      INSERT INTO ARCARD_EXCLUSIONS (CARDID, ID, ACTID) VALUES (V_CARDID, V_10, V_ACTID);
    END IF;    
  ELSE
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = '10';
    
    IF IDCOUNT > 0 THEN
      DELETE FROM ARCARD_EXCLUSIONS WHERE ACTID = V_ACTID AND ID = '10';
    END IF;    
  END IF;

-- Dietician/ Dietary Consultation
  IF V_11 = '11' THEN
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = V_11;
    
    IF IDCOUNT = 0 THEN
      SELECT CARDID INTO V_CARDID FROM ACTID_CARDID_MAPPING WHERE ACTID = V_ACTID;
    
      INSERT INTO ARCARD_EXCLUSIONS (CARDID, ID, ACTID) VALUES (V_CARDID, V_11, V_ACTID);
    END IF;    
  ELSE
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = '11';
    
    IF IDCOUNT > 0 THEN
      DELETE FROM ARCARD_EXCLUSIONS WHERE ACTID = V_ACTID AND ID = '11';
    END IF;    
  END IF;
  
-- Eating Disorder
  IF V_12 = '12' THEN
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = V_12;
    
    IF IDCOUNT = 0 THEN
      SELECT CARDID INTO V_CARDID FROM ACTID_CARDID_MAPPING WHERE ACTID = V_ACTID;
    
      INSERT INTO ARCARD_EXCLUSIONS (CARDID, ID, ACTID) VALUES (V_CARDID, V_12, V_ACTID);
    END IF;    
  ELSE
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = '12';
    
    IF IDCOUNT > 0 THEN
      DELETE FROM ARCARD_EXCLUSIONS WHERE ACTID = V_ACTID AND ID = '12';
    END IF;    
  END IF;
  
-- Fertility related  
  IF V_13 = '13' THEN
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = V_13;
    
    IF IDCOUNT = 0 THEN
      SELECT CARDID INTO V_CARDID FROM ACTID_CARDID_MAPPING WHERE ACTID = V_ACTID;
    
      INSERT INTO ARCARD_EXCLUSIONS (CARDID, ID, ACTID) VALUES (V_CARDID, V_13, V_ACTID);
    END IF;    
  ELSE
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = '13';
    
    IF IDCOUNT > 0 THEN
      DELETE FROM ARCARD_EXCLUSIONS WHERE ACTID = V_ACTID AND ID = '13';
    END IF;    
  END IF;
  
  
-- Foot orthotics
  IF V_14 = '14' THEN
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = V_14;
    
    IF IDCOUNT = 0 THEN
      SELECT CARDID INTO V_CARDID FROM ACTID_CARDID_MAPPING WHERE ACTID = V_ACTID;
    
      INSERT INTO ARCARD_EXCLUSIONS (CARDID, ID, ACTID) VALUES (V_CARDID, V_14, V_ACTID);
    END IF;    
  ELSE
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = '14';
    
    IF IDCOUNT > 0 THEN
      DELETE FROM ARCARD_EXCLUSIONS WHERE ACTID = V_ACTID AND ID = '14';
    END IF;    
  END IF;
  
-- Hearing aids
  IF V_15 = '15' THEN
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = V_15;
    
    IF IDCOUNT = 0 THEN
      SELECT CARDID INTO V_CARDID FROM ACTID_CARDID_MAPPING WHERE ACTID = V_ACTID;
    
      INSERT INTO ARCARD_EXCLUSIONS (CARDID, ID, ACTID) VALUES (V_CARDID, V_15, V_ACTID);
    END IF;    
  ELSE
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = '15';
    
    IF IDCOUNT > 0 THEN
      DELETE FROM ARCARD_EXCLUSIONS WHERE ACTID = V_ACTID AND ID = '15';
    END IF;    
  END IF;

-- HIV and related disease
  IF V_16 = '16' THEN
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = V_16;
    
    IF IDCOUNT = 0 THEN
      SELECT CARDID INTO V_CARDID FROM ACTID_CARDID_MAPPING WHERE ACTID = V_ACTID;
    
      INSERT INTO ARCARD_EXCLUSIONS (CARDID, ID, ACTID) VALUES (V_CARDID, V_16, V_ACTID);
    END IF;    
  ELSE
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = '16';
    
    IF IDCOUNT > 0 THEN
      DELETE FROM ARCARD_EXCLUSIONS WHERE ACTID = V_ACTID AND ID = '16';
    END IF;    
  END IF;
  
-- Medical devices/ equipment
  IF V_17 = '17' THEN
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = V_17;
    
    IF IDCOUNT = 0 THEN
      SELECT CARDID INTO V_CARDID FROM ACTID_CARDID_MAPPING WHERE ACTID = V_ACTID;
    
      INSERT INTO ARCARD_EXCLUSIONS (CARDID, ID, ACTID) VALUES (V_CARDID, V_17, V_ACTID);
    END IF;    
  ELSE
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = '17';
    
    IF IDCOUNT > 0 THEN
      DELETE FROM ARCARD_EXCLUSIONS WHERE ACTID = V_ACTID AND ID = '17';
    END IF;    
  END IF;
  
-- Medical report or any document fee 
  IF V_18 = '18' THEN
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = V_18;
    
    IF IDCOUNT = 0 THEN
      SELECT CARDID INTO V_CARDID FROM ACTID_CARDID_MAPPING WHERE ACTID = V_ACTID;
    
      INSERT INTO ARCARD_EXCLUSIONS (CARDID, ID, ACTID) VALUES (V_CARDID, V_18, V_ACTID);
    END IF;    
  ELSE
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = '18';
    
    IF IDCOUNT > 0 THEN
      DELETE FROM ARCARD_EXCLUSIONS WHERE ACTID = V_ACTID AND ID = '18';
    END IF;    
  END IF;
  
-- Mental Health related  
  IF V_19 = '19' THEN
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = V_19;
    
    IF IDCOUNT = 0 THEN
      SELECT CARDID INTO V_CARDID FROM ACTID_CARDID_MAPPING WHERE ACTID = V_ACTID;
    
      INSERT INTO ARCARD_EXCLUSIONS (CARDID, ID, ACTID) VALUES (V_CARDID, V_19, V_ACTID);
    END IF;    
  ELSE
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = '19';
    
    IF IDCOUNT > 0 THEN
      DELETE FROM ARCARD_EXCLUSIONS WHERE ACTID = V_ACTID AND ID = '19';
    END IF;    
  END IF;
  
-- Occupational Therapy
  IF V_20 = '20' THEN
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = V_20;
    
    IF IDCOUNT = 0 THEN
      SELECT CARDID INTO V_CARDID FROM ACTID_CARDID_MAPPING WHERE ACTID = V_ACTID;
    
      INSERT INTO ARCARD_EXCLUSIONS (CARDID, ID, ACTID) VALUES (V_CARDID, V_20, V_ACTID);
    END IF;    
  ELSE
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = '20';
    
    IF IDCOUNT > 0 THEN
      DELETE FROM ARCARD_EXCLUSIONS WHERE ACTID = V_ACTID AND ID = '20';
    END IF;    
  END IF;
  
-- Optical/ Eye refractive error and sight defect related
  IF V_21 = '21' THEN
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = V_21;
    
    IF IDCOUNT = 0 THEN
      SELECT CARDID INTO V_CARDID FROM ACTID_CARDID_MAPPING WHERE ACTID = V_ACTID;
    
      INSERT INTO ARCARD_EXCLUSIONS (CARDID, ID, ACTID) VALUES (V_CARDID, V_21, V_ACTID);
    END IF;    
  ELSE
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = '21';
    
    IF IDCOUNT > 0 THEN
      DELETE FROM ARCARD_EXCLUSIONS WHERE ACTID = V_ACTID AND ID = '21';
    END IF;    
  END IF;
  
-- Overweight treatment  
  IF V_22 = '22' THEN
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = V_22;
    
    IF IDCOUNT = 0 THEN
      SELECT CARDID INTO V_CARDID FROM ACTID_CARDID_MAPPING WHERE ACTID = V_ACTID;
    
      INSERT INTO ARCARD_EXCLUSIONS (CARDID, ID, ACTID) VALUES (V_CARDID, V_22, V_ACTID);
    END IF;    
  ELSE
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = '22';
    
    IF IDCOUNT > 0 THEN
      DELETE FROM ARCARD_EXCLUSIONS WHERE ACTID = V_ACTID AND ID = '22';
    END IF;    
  END IF;
  
-- Personal expenses
  IF V_23 = '23' THEN
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = V_23;
    
    IF IDCOUNT = 0 THEN
      SELECT CARDID INTO V_CARDID FROM ACTID_CARDID_MAPPING WHERE ACTID = V_ACTID;
    
      INSERT INTO ARCARD_EXCLUSIONS (CARDID, ID, ACTID) VALUES (V_CARDID, V_23, V_ACTID);
    END IF;    
  ELSE
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = '23';
    
    IF IDCOUNT > 0 THEN
      DELETE FROM ARCARD_EXCLUSIONS WHERE ACTID = V_ACTID AND ID = '23';
    END IF;    
  END IF;

-- Pregnancy related 
  IF V_24 = '24' THEN
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = V_24;
    
    IF IDCOUNT = 0 THEN
      SELECT CARDID INTO V_CARDID FROM ACTID_CARDID_MAPPING WHERE ACTID = V_ACTID;
    
      INSERT INTO ARCARD_EXCLUSIONS (CARDID, ID, ACTID) VALUES (V_CARDID, V_24, V_ACTID);
    END IF;    
  ELSE
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = '24';
    
    IF IDCOUNT > 0 THEN
      DELETE FROM ARCARD_EXCLUSIONS WHERE ACTID = V_ACTID AND ID = '24';
    END IF;    
  END IF;
  
-- Private nursing
  IF V_25 = '25' THEN
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = V_25;
    
    IF IDCOUNT = 0 THEN
      SELECT CARDID INTO V_CARDID FROM ACTID_CARDID_MAPPING WHERE ACTID = V_ACTID;
    
      INSERT INTO ARCARD_EXCLUSIONS (CARDID, ID, ACTID) VALUES (V_CARDID, V_25, V_ACTID);
    END IF;    
  ELSE
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = '25';
    
    IF IDCOUNT > 0 THEN
      DELETE FROM ARCARD_EXCLUSIONS WHERE ACTID = V_ACTID AND ID = '25';
    END IF;    
  END IF;
 
-- Psychiatric Condition 
  IF V_26 = '26' THEN
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = V_26;
    
    IF IDCOUNT = 0 THEN
      SELECT CARDID INTO V_CARDID FROM ACTID_CARDID_MAPPING WHERE ACTID = V_ACTID;
    
      INSERT INTO ARCARD_EXCLUSIONS (CARDID, ID, ACTID) VALUES (V_CARDID, V_26, V_ACTID);
    END IF;    
  ELSE
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = '26';
    
    IF IDCOUNT > 0 THEN
      DELETE FROM ARCARD_EXCLUSIONS WHERE ACTID = V_ACTID AND ID = '26';
    END IF;    
  END IF;

-- Sexually transmitted disease
  IF V_27 = '27' THEN
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = V_27;
    
    IF IDCOUNT = 0 THEN
      SELECT CARDID INTO V_CARDID FROM ACTID_CARDID_MAPPING WHERE ACTID = V_ACTID;
    
      INSERT INTO ARCARD_EXCLUSIONS (CARDID, ID, ACTID) VALUES (V_CARDID, V_27, V_ACTID);
    END IF;    
  ELSE
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = '27';
    
    IF IDCOUNT > 0 THEN
      DELETE FROM ARCARD_EXCLUSIONS WHERE ACTID = V_ACTID AND ID = '27';
    END IF;    
  END IF;
  
-- Sleep disorder  
  IF V_28 = '28' THEN
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = V_28;
    
    IF IDCOUNT = 0 THEN
      SELECT CARDID INTO V_CARDID FROM ACTID_CARDID_MAPPING WHERE ACTID = V_ACTID;
    
      INSERT INTO ARCARD_EXCLUSIONS (CARDID, ID, ACTID) VALUES (V_CARDID, V_28, V_ACTID);
    END IF;    
  ELSE
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = '28';
    
    IF IDCOUNT > 0 THEN
      DELETE FROM ARCARD_EXCLUSIONS WHERE ACTID = V_ACTID AND ID = '28';
    END IF;    
  END IF;

-- Smoking ceasation 
  IF V_29 = '29' THEN
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = V_29;
    
    IF IDCOUNT = 0 THEN
      SELECT CARDID INTO V_CARDID FROM ACTID_CARDID_MAPPING WHERE ACTID = V_ACTID;
    
      INSERT INTO ARCARD_EXCLUSIONS (CARDID, ID, ACTID) VALUES (V_CARDID, V_29, V_ACTID);
    END IF;    
  ELSE
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = '29';
    
    IF IDCOUNT > 0 THEN
      DELETE FROM ARCARD_EXCLUSIONS WHERE ACTID = V_ACTID AND ID = '29';
    END IF;    
  END IF;
  
-- Speech Therapy
  IF V_30 = '30' THEN
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = V_30;
    
    IF IDCOUNT = 0 THEN
      SELECT CARDID INTO V_CARDID FROM ACTID_CARDID_MAPPING WHERE ACTID = V_ACTID;
    
      INSERT INTO ARCARD_EXCLUSIONS (CARDID, ID, ACTID) VALUES (V_CARDID, V_30, V_ACTID);
    END IF;    
  ELSE
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = '30';
    
    IF IDCOUNT > 0 THEN
      DELETE FROM ARCARD_EXCLUSIONS WHERE ACTID = V_ACTID AND ID = '30';
    END IF;    
  END IF;

-- Supplements
  IF V_31 = '31' THEN
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = V_31;
    
    IF IDCOUNT = 0 THEN
      SELECT CARDID INTO V_CARDID FROM ACTID_CARDID_MAPPING WHERE ACTID = V_ACTID;
    
      INSERT INTO ARCARD_EXCLUSIONS (CARDID, ID, ACTID) VALUES (V_CARDID, V_31, V_ACTID);
    END IF;    
  ELSE
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = '31';
    
    IF IDCOUNT > 0 THEN
      DELETE FROM ARCARD_EXCLUSIONS WHERE ACTID = V_ACTID AND ID = '31';
    END IF;    
  END IF;
  
-- Transplantation
  IF V_32 = '32' THEN
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = V_32;
    
    IF IDCOUNT = 0 THEN
      SELECT CARDID INTO V_CARDID FROM ACTID_CARDID_MAPPING WHERE ACTID = V_ACTID;
    
      INSERT INTO ARCARD_EXCLUSIONS (CARDID, ID, ACTID) VALUES (V_CARDID, V_32, V_ACTID);
    END IF;    
  ELSE
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = '32';
    
    IF IDCOUNT > 0 THEN
      DELETE FROM ARCARD_EXCLUSIONS WHERE ACTID = V_ACTID AND ID = '32';
    END IF;    
  END IF;
  
-- Walking aids/ Wheel Chair/ Crutches
  IF V_33 = '33' THEN
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = V_33;
    
    IF IDCOUNT = 0 THEN
      SELECT CARDID INTO V_CARDID FROM ACTID_CARDID_MAPPING WHERE ACTID = V_ACTID;
    
      INSERT INTO ARCARD_EXCLUSIONS (CARDID, ID, ACTID) VALUES (V_CARDID, V_33, V_ACTID);
    END IF;    
  ELSE
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = '33';
    
    IF IDCOUNT > 0 THEN
      DELETE FROM ARCARD_EXCLUSIONS WHERE ACTID = V_ACTID AND ID = '33';
    END IF;    
  END IF;
/*  
-- Sex change operations  
  IF V_34 = '34' THEN
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = V_34;
    
    IF IDCOUNT = 0 THEN
      SELECT CARDID INTO V_CARDID FROM ACTID_CARDID_MAPPING WHERE ACTID = V_ACTID;
    
      INSERT INTO ARCARD_EXCLUSIONS (CARDID, ID, ACTID) VALUES (V_CARDID, V_34, V_ACTID);
    END IF;    
  ELSE
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = '34';
    
    IF IDCOUNT > 0 THEN
      DELETE FROM ARCARD_EXCLUSIONS WHERE ACTID = V_ACTID AND ID = '34';
    END IF;    
  END IF;

-- Smoking Cessation  
  IF V_35 = '35' THEN
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = V_35;
    
    IF IDCOUNT = 0 THEN
      SELECT CARDID INTO V_CARDID FROM ACTID_CARDID_MAPPING WHERE ACTID = V_ACTID;
    
      INSERT INTO ARCARD_EXCLUSIONS (CARDID, ID, ACTID) VALUES (V_CARDID, V_35, V_ACTID);
    END IF;    
  ELSE
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = '35';
    
    IF IDCOUNT > 0 THEN
      DELETE FROM ARCARD_EXCLUSIONS WHERE ACTID = V_ACTID AND ID = '35';
    END IF;    
  END IF;
  
-- Special nursing care 
  IF V_36 = '36' THEN
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = V_36;
    
    IF IDCOUNT = 0 THEN
      SELECT CARDID INTO V_CARDID FROM ACTID_CARDID_MAPPING WHERE ACTID = V_ACTID;
    
      INSERT INTO ARCARD_EXCLUSIONS (CARDID, ID, ACTID) VALUES (V_CARDID, V_36, V_ACTID);
    END IF;    
  ELSE
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = '36';
    
    IF IDCOUNT > 0 THEN
      DELETE FROM ARCARD_EXCLUSIONS WHERE ACTID = V_ACTID AND ID = '36';
    END IF;    
  END IF;

-- Vaccination/Immunization  
  IF V_37 = '37' THEN
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = V_37;
    
    IF IDCOUNT = 0 THEN
      SELECT CARDID INTO V_CARDID FROM ACTID_CARDID_MAPPING WHERE ACTID = V_ACTID;
    
      INSERT INTO ARCARD_EXCLUSIONS (CARDID, ID, ACTID) VALUES (V_CARDID, V_37, V_ACTID);
    END IF;    
  ELSE
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = '37';
    
    IF IDCOUNT > 0 THEN
      DELETE FROM ARCARD_EXCLUSIONS WHERE ACTID = V_ACTID AND ID = '37';
    END IF;    
  END IF;
  
-- Planned treatment outside HK
  IF V_38 = '38' THEN
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = V_38;
    
    IF IDCOUNT = 0 THEN
      SELECT CARDID INTO V_CARDID FROM ACTID_CARDID_MAPPING WHERE ACTID = V_ACTID;
    
      INSERT INTO ARCARD_EXCLUSIONS (CARDID, ID, ACTID) VALUES (V_CARDID, V_38, V_ACTID);
    END IF;    
  ELSE
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = '38';
    
    IF IDCOUNT > 0 THEN
      DELETE FROM ARCARD_EXCLUSIONS WHERE ACTID = V_ACTID AND ID = '38';
    END IF;    
  END IF;

-- Pre-existing conditions
  IF V_39 = '39' THEN
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = V_39;
    
    IF IDCOUNT = 0 THEN
      SELECT CARDID INTO V_CARDID FROM ACTID_CARDID_MAPPING WHERE ACTID = V_ACTID;
    
      INSERT INTO ARCARD_EXCLUSIONS (CARDID, ID, ACTID) VALUES (V_CARDID, V_39, V_ACTID);
    END IF;    
  ELSE
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = '39';
    
    IF IDCOUNT > 0 THEN
      DELETE FROM ARCARD_EXCLUSIONS WHERE ACTID = V_ACTID AND ID = '39';
    END IF;    
  END IF;
 
-- Self inflicted injuries  
  IF V_40 = '40' THEN
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = V_40;
    
    IF IDCOUNT = 0 THEN
      SELECT CARDID INTO V_CARDID FROM ACTID_CARDID_MAPPING WHERE ACTID = V_ACTID;
    
      INSERT INTO ARCARD_EXCLUSIONS (CARDID, ID, ACTID) VALUES (V_CARDID, V_40, V_ACTID);
    END IF;    
  ELSE
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = '40';
    
    IF IDCOUNT > 0 THEN
      DELETE FROM ARCARD_EXCLUSIONS WHERE ACTID = V_ACTID AND ID = '40';
    END IF;    
  END IF;
  
-- Suicide/Attempt suicide
  IF V_41 = '41' THEN
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = V_41;
    
    IF IDCOUNT = 0 THEN
      SELECT CARDID INTO V_CARDID FROM ACTID_CARDID_MAPPING WHERE ACTID = V_ACTID;
    
      INSERT INTO ARCARD_EXCLUSIONS (CARDID, ID, ACTID) VALUES (V_CARDID, V_41, V_ACTID);
    END IF;    
  ELSE
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = '41';
    
    IF IDCOUNT > 0 THEN
      DELETE FROM ARCARD_EXCLUSIONS WHERE ACTID = V_ACTID AND ID = '41';
    END IF;    
  END IF;
  
-- Travel costs for treatment  
  IF V_42 = '42' THEN
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = V_42;
    
    IF IDCOUNT = 0 THEN
      SELECT CARDID INTO V_CARDID FROM ACTID_CARDID_MAPPING WHERE ACTID = V_ACTID;
    
      INSERT INTO ARCARD_EXCLUSIONS (CARDID, ID, ACTID) VALUES (V_CARDID, V_42, V_ACTID);
    END IF;    
  ELSE
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = '42';
    
    IF IDCOUNT > 0 THEN
      DELETE FROM ARCARD_EXCLUSIONS WHERE ACTID = V_ACTID AND ID = '42';
    END IF;    
  END IF;
  
-- Treatment conducted by family  
  IF V_43 = '43' THEN
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = V_43;
    
    IF IDCOUNT = 0 THEN
      SELECT CARDID INTO V_CARDID FROM ACTID_CARDID_MAPPING WHERE ACTID = V_ACTID;
    
      INSERT INTO ARCARD_EXCLUSIONS (CARDID, ID, ACTID) VALUES (V_CARDID, V_43, V_ACTID);
    END IF;    
  ELSE
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = '43';
    
    IF IDCOUNT > 0 THEN
      DELETE FROM ARCARD_EXCLUSIONS WHERE ACTID = V_ACTID AND ID = '43';
    END IF;    
  END IF;
  
-- Treatment outside geographic area
  IF V_44 = '44' THEN
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = V_44;
    
    IF IDCOUNT = 0 THEN
      SELECT CARDID INTO V_CARDID FROM ACTID_CARDID_MAPPING WHERE ACTID = V_ACTID;
    
      INSERT INTO ARCARD_EXCLUSIONS (CARDID, ID, ACTID) VALUES (V_CARDID, V_44, V_ACTID);
    END IF;    
  ELSE
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = '44';
    
    IF IDCOUNT > 0 THEN
      DELETE FROM ARCARD_EXCLUSIONS WHERE ACTID = V_ACTID AND ID = '44';
    END IF;    
  END IF;


-- Unproved treatment  
  IF V_45 = '45' THEN
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = V_45;
    
    IF IDCOUNT = 0 THEN
      SELECT CARDID INTO V_CARDID FROM ACTID_CARDID_MAPPING WHERE ACTID = V_ACTID;
    
      INSERT INTO ARCARD_EXCLUSIONS (CARDID, ID, ACTID) VALUES (V_CARDID, V_45, V_ACTID);
    END IF;    
  ELSE
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = '45';
    
    IF IDCOUNT > 0 THEN
      DELETE FROM ARCARD_EXCLUSIONS WHERE ACTID = V_ACTID AND ID = '45';
    END IF;    
  END IF;
  
-- War/riots//radioactive contamination  
  IF V_46 = '46' THEN
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = V_46;
    
    IF IDCOUNT = 0 THEN
      SELECT CARDID INTO V_CARDID FROM ACTID_CARDID_MAPPING WHERE ACTID = V_ACTID;
    
      INSERT INTO ARCARD_EXCLUSIONS (CARDID, ID, ACTID) VALUES (V_CARDID, V_46, V_ACTID);
    END IF;    
  ELSE
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = '46';
    
    IF IDCOUNT > 0 THEN
      DELETE FROM ARCARD_EXCLUSIONS WHERE ACTID = V_ACTID AND ID = '46';
    END IF;    
  END IF;
  
-- Well Baby  
  IF V_47 = '47' THEN
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = V_47;
    
    IF IDCOUNT = 0 THEN
      SELECT CARDID INTO V_CARDID FROM ACTID_CARDID_MAPPING WHERE ACTID = V_ACTID;
    
      INSERT INTO ARCARD_EXCLUSIONS (CARDID, ID, ACTID) VALUES (V_CARDID, V_47, V_ACTID);
    END IF;    
  ELSE
    SELECT COUNT(ID) 
    INTO IDCOUNT
    FROM ARCARD_EXCLUSIONS 
    WHERE ACTID = V_ACTID 
    AND ID = '47';
    
    IF IDCOUNT > 0 THEN
      DELETE FROM ARCARD_EXCLUSIONS WHERE ACTID = V_ACTID AND ID = '47';
    END IF;    
  END IF;  
*/
  RETURN o_errcode;
EXCEPTION  
WHEN OTHERS THEN
	o_errcode := -1;
	o_errmsg:= o_errmsg || SQLERRM;
	ROLLBACK;
	RETURN o_errCode;  
END NHS_ACT_GENEXCLUSION;
/