create or replace FUNCTION NHS_LIS_ARCARDLINKDTL (
	v_actid arcardtype.actid%TYPE
)
	RETURN Types.cursor_type
AS
	OUTCUR TYPES.CURSOR_TYPE;
BEGIN
	open OUTCUR for
		SELECT ACTYPE.ACTREGRMKIP, ACTYPE.ACTREGRMKOP, ACTYPE.ACTPAYRMKIP, ACTYPE.ACTPAYRMKOP, ACTYPE.REGRMKIPURL, ACTYPE.REGRMKOPURL, ACTYPE.COLOUR1, ACTYPE.COLOUR2,
		ACTERMIN.EXCLUSION AS EXCLUSIN, ACTERMOP.EXCLUSION AS EXCLUSOUT, ACTERMIN.VOUCHER AS VOUCHERIN, ACTERMOP.VOUCHER AS VOUCHEROUT, ACTERMIN.CLAIM_FORM AS CLAIMIN, ACTERMOP.CLAIM_FORM AS CLAIMOUT,
    ACTERMIN.NAME_LIST AS NAMELISTIN, ACTERMOP.NAME_LIST AS NAMELISTOUT,
		ACTERMIN.PRE_AUTHORISE_FORM AS PREAUTHIN, ACTERMOP.PRE_AUTHORISE_FORM AS PREAUTHOUT, ACTERMIN.PRE_AUTHORISATION_MEMO AS MEMEOIN, ACTERMOP.PRE_AUTHORISATION_MEMO AS MEMOOUT,
		ACTERMIN.REMARKS AS CONTACTRMKIN, ACTERMOP.REMARKS AS CONTACTRMKOUT, ACTERMIN.CONTACT_DETAILS AS CONTACTDTLIN, ACTERMOP.CONTACT_DETAILS AS CONTACTDTLOUT,
		ACTERMIN.CONTACT_PHONE AS CONTACTPHONEIN, ACTERMOP.CONTACT_PHONE AS CONTACTPHONEOUT, ACTERMIN.FAX AS CONTACTFAXIN, ACTERMOP.FAX AS CONTACTFAXOUT,
    ACTERMIN.BILLREMARKS AS BILLRMKIP, ACTERMOP.BILLREMARKS AS BILLRMKOP, ACTYPE.EBILLING, ACTYPE.SENDORGINV, ACTYPE.SAMPLEINV,
    ACTERMIN.EXCLUSIONREMARKS AS EXCLURMKIP, ACTERMOP.EXCLUSIONREMARKS AS EXCLURMKOP, ACTERMIN.CONTACT_EMAIL AS CONTACTEMAILIP, ACTERMOP.CONTACT_EMAIL AS CONTACTEMAILOP,
    TO_CHAR(ACTYPE.ARCARDSDATE,'DD/MM/YYYY'), TO_CHAR(ACTYPE.ARCARDEDATE,'DD/MM/YYYY'), ACTYPE.ACTACTIVE, UPLOADTOPORTAL, ACTYPE.BILLINGOTHER, ACTERMIN.POLICYSAMPLE, ACTERMOP.POLICYSAMPLE,
    ACTERMIN.OFC_HOUR, ACTERMOP.OFC_HOUR, ACTERMIN.ACKNOWLEDGE_FORM AS ACKNOWIN, ACTERMIN.DTL_PROCEDURES, ACTERMOP.DTL_PROCEDURES
--    ACTERMOP.ACKNOWLEDGE_FORM AS ACKNOWOUT,
		FROM ARCARDTYPE ACTYPE, ARCARDTERM ACTERMIN, ARCARDTERM ACTERMOP
		WHERE ACTYPE.ACTID=ACTERMIN.ACTID(+)
		AND ACTYPE.ACTID=ACTERMOP.ACTID(+)
		AND ACTERMIN.TYPE = 'In'
		AND ACTERMOP.TYPE = 'Out'
		AND ACTYPE.actid = v_actid;
	RETURN OUTCUR;
END NHS_LIS_ARCARDLINKDTL;
/