create or replace FUNCTION "NHS_LIS_AREXCLUSIONS"
(
  V_ARCODE ARCARD_EXCLUSIONS.ARCCODE%TYPE,
  V_ACTID ARCARD_EXCLUSIONS.ACTID%TYPE
)
  RETURN TYPES.CURSOR_TYPE
--    RETURN VARCHAR2
AS
  OUTCUR TYPES.CURSOR_TYPE;
  LS_ID EXCLUSIONS.ID%TYPE;
  LS_COLUMN VARCHAR2(100);
  SQLSTR VARCHAR2(5000);

  CURSOR c_getExclusion IS
  SELECT ID
  FROM EXCLUSIONS
  ORDER BY ID;
BEGIN
-- METHOD01

  OPEN OUTCUR FOR
  SELECT *
  FROM (SELECT EXCL.ID, NVL(AE.ENABLED,0) AS EX_ENABLED
  FROM EXCLUSIONS EXCL,
  (SELECT ID, 1 AS ENABLED FROM ARCARD_EXCLUSIONS WHERE ACTID = V_ACTID) AE
  WHERE EXCL.ID = AE.ID(+)) EX
  PIVOT (SUM(EX_ENABLED) AS SUM FOR (ID) IN (
  '01' AS CHK01, '02' AS CHK02, '03' AS CHK03, '04' AS CHK04, '05' AS CHK05, '06' AS CHK06, '07' AS CHK07, '08' AS CHK08, '09' AS CHK09, '10' AS CHK10,
  '11' AS CHK11, '12' AS CHK12, '13' AS CHK13, '14' AS CHK14, '15' AS CHK15, '16' AS CHK16, '17' AS CHK17, '18' AS CHK18, '19' AS CHK19, '20' AS CHK20,
  '21' AS CHK21, '22' AS CHK22, '23' AS CHK23, '24' AS CHK24, '25' AS CHK25, '26' AS CHK26, '27' AS CHK27, '28' AS CHK28, '29' AS CHK29, '30' AS CHK30,
  '31' AS CHK31, '32' AS CHK32, '33' AS CHK33
  --,'34' AS CHK34, '35' AS CHK35, '36' AS CHK36, '37' AS CHK37, '38' AS CHK38, '39' AS CHK39, '40' AS CHK40,
  --'41' AS CHK41, '42' AS CHK42, '43' AS CHK43, '44' AS CHK44, '45' AS CHK45, '46' AS CHK46, '47' AS CHK47, '48' AS CHK48
  ));

 /*
-- METHOD02

  LS_COLUMN := NULL;
  SQLSTR := 'SELECT';

  OPEN c_getExclusion;
  LOOP
  FETCH c_getExclusion INTO LS_ID;
  EXIT WHEN C_GETEXCLUSION%NOTFOUND;
    IF LS_COLUMN IS NULL THEN
      LS_COLUMN := ' SUM(CASE WHEN EX.ID = '''||LS_ID||''' THEN EX.EX_ENABLED ELSE 0 END) CHK'||LS_ID;
    ELSE
      LS_COLUMN := ', SUM(CASE WHEN EX.ID = '''||LS_ID||''' THEN EX.EX_ENABLED ELSE 0 END) CHK'||LS_ID;
    END IF;

    SQLSTR := SQLSTR||LS_COLUMN;
  END LOOP;
  CLOSE c_getExclusion;

  SQLSTR := SQLSTR||' FROM (SELECT EXCL.ID, NVL(AE.ENABLED,0) AS EX_ENABLED FROM EXCLUSIONS EXCL,'||
            ' (SELECT ID, 1 AS ENABLED FROM ARCARD_EXCLUSIONS WHERE ACTID ='''||V_ACTID||
            ''') AE WHERE EXCL.ID = AE.ID(+)) EX';

  OPEN OUTCUR FOR SQLSTR;

-- METHOD03

  SELECT
    SUM(CASE WHEN EX.ID = '01' THEN EX.EX_ENABLED ELSE 0 END) CHK01,
    SUM(CASE WHEN EX.ID = '02' THEN EX.EX_ENABLED ELSE 0 END) CHK02,
    SUM(CASE WHEN EX.ID = '03' THEN EX.EX_ENABLED ELSE 0 END) CHK03,
    SUM(CASE WHEN EX.ID = '04' THEN EX.EX_ENABLED ELSE 0 END) CHK04,
    SUM(CASE WHEN EX.ID = '05' THEN EX.EX_ENABLED ELSE 0 END) CHK05,
    SUM(CASE WHEN EX.ID = '06' THEN EX.EX_ENABLED ELSE 0 END) CHK06,
    SUM(CASE WHEN EX.ID = '07' THEN EX.EX_ENABLED ELSE 0 END) CHK07,
    SUM(CASE WHEN EX.ID = '08' THEN EX.EX_ENABLED ELSE 0 END) CHK08,
    SUM(CASE WHEN EX.ID = '09' THEN EX.EX_ENABLED ELSE 0 END) CHK09,
    SUM(CASE WHEN EX.ID = '10' THEN EX.EX_ENABLED ELSE 0 END) CHK10,
    SUM(CASE WHEN EX.ID = '11' THEN EX.EX_ENABLED ELSE 0 END) CHK11,
    SUM(CASE WHEN EX.ID = '12' THEN EX.EX_ENABLED ELSE 0 END) CHK12,
    SUM(CASE WHEN EX.ID = '13' THEN EX.EX_ENABLED ELSE 0 END) CHK13,
    SUM(CASE WHEN EX.ID = '14' THEN EX.EX_ENABLED ELSE 0 END) CHK14,
    SUM(CASE WHEN EX.ID = '15' THEN EX.EX_ENABLED ELSE 0 END) CHK15,
    SUM(CASE WHEN EX.ID = '16' THEN EX.EX_ENABLED ELSE 0 END) CHK16,
    SUM(CASE WHEN EX.ID = '17' THEN EX.EX_ENABLED ELSE 0 END) CHK17,
    SUM(CASE WHEN EX.ID = '18' THEN EX.EX_ENABLED ELSE 0 END) CHK18,
    SUM(CASE WHEN EX.ID = '19' THEN EX.EX_ENABLED ELSE 0 END) CHK19,
    SUM(CASE WHEN EX.ID = '20' THEN EX.EX_ENABLED ELSE 0 END) CHK20,
    SUM(CASE WHEN EX.ID = '21' THEN EX.EX_ENABLED ELSE 0 END) CHK21,
    SUM(CASE WHEN EX.ID = '22' THEN EX.EX_ENABLED ELSE 0 END) CHK22,
    SUM(CASE WHEN EX.ID = '23' THEN EX.EX_ENABLED ELSE 0 END) CHK23,
    SUM(CASE WHEN EX.ID = '24' THEN EX.EX_ENABLED ELSE 0 END) CHK24,
    SUM(CASE WHEN EX.ID = '25' THEN EX.EX_ENABLED ELSE 0 END) CHK25,
    SUM(CASE WHEN EX.ID = '26' THEN EX.EX_ENABLED ELSE 0 END) CHK26,
    SUM(CASE WHEN EX.ID = '27' THEN EX.EX_ENABLED ELSE 0 END) CHK27,
    SUM(CASE WHEN EX.ID = '28' THEN EX.EX_ENABLED ELSE 0 END) CHK28,
    SUM(CASE WHEN EX.ID = '29' THEN EX.EX_ENABLED ELSE 0 END) CHK29,
    SUM(CASE WHEN EX.ID = '30' THEN EX.EX_ENABLED ELSE 0 END) CHK30,
    SUM(CASE WHEN EX.ID = '31' THEN EX.EX_ENABLED ELSE 0 END) CHK31,
    SUM(CASE WHEN EX.ID = '32' THEN EX.EX_ENABLED ELSE 0 END) CHK32,
    SUM(CASE WHEN EX.ID = '33' THEN EX.EX_ENABLED ELSE 0 END) CHK33,
    SUM(CASE WHEN EX.ID = '34' THEN EX.EX_ENABLED ELSE 0 END) CHK34,
    SUM(CASE WHEN EX.ID = '35' THEN EX.EX_ENABLED ELSE 0 END) CHK35,
    SUM(CASE WHEN EX.ID = '36' THEN EX.EX_ENABLED ELSE 0 END) CHK36,
    SUM(CASE WHEN EX.ID = '37' THEN EX.EX_ENABLED ELSE 0 END) CHK37,
    SUM(CASE WHEN EX.ID = '38' THEN EX.EX_ENABLED ELSE 0 END) CHK38,
    SUM(CASE WHEN EX.ID = '39' THEN EX.EX_ENABLED ELSE 0 END) CHK39,
    SUM(CASE WHEN EX.ID = '40' THEN EX.EX_ENABLED ELSE 0 END) CHK40,
    SUM(CASE WHEN EX.ID = '41' THEN EX.EX_ENABLED ELSE 0 END) CHK41,
    SUM(CASE WHEN EX.ID = '42' THEN EX.EX_ENABLED ELSE 0 END) CHK42,
    SUM(CASE WHEN EX.ID = '43' THEN EX.EX_ENABLED ELSE 0 END) CHK43,
    SUM(CASE WHEN EX.ID = '44' THEN EX.EX_ENABLED ELSE 0 END) CHK44,
    SUM(CASE WHEN EX.ID = '45' THEN EX.EX_ENABLED ELSE 0 END) CHK45,
    SUM(CASE WHEN EX.ID = '46' THEN EX.EX_ENABLED ELSE 0 END) CHK46,
    SUM(CASE WHEN EX.ID = '47' THEN EX.EX_ENABLED ELSE 0 END) CHK47,
    SUM(CASE WHEN EX.ID = '48' THEN EX.EX_ENABLED ELSE 0 END) CHK48
    FROM
  (SELECT EXCL.ID, NVL(AE.ENABLED,0) AS EX_ENABLED
    FROM EXCLUSIONS EXCL,
    (SELECT ID, 1 AS ENABLED FROM ARCARD_EXCLUSIONS WHERE ACTID = V_ACTID) AE
    WHERE EXCL.ID = AE.ID(+)) EX;
    */
  RETURN OUTCUR;
--    RETURN SQLSTR;
END NHS_LIS_AREXCLUSIONS;
/