create or replace FUNCTION "NHS_GET_SLIPTX_CANCEL_STNSDATE"
(V_SLPNO SLIPTX.SLPNO%TYPE
,V_STNSEQ SLIPTX.STNSEQ%TYPE
,V_GENDATE IN VARCHAR2
)
  RETURN sliptx_extra.STNSDATE%TYPE
AS
  V_STNSDATE SLIPTX_EXTRA.STNSDATE%TYPE;
  V_STNCDATE SLIPTX.STNCDATE%TYPE;
BEGIN
    SELECT ST.STNCDATE, STE.STNSDATE
    INTO V_STNCDATE, V_STNSDATE 
    FROM SLIPTX ST, SLIPTX_EXTRA STE
    WHERE ST.STNID = STE.STNID(+)
    AND ST.SLPNO = V_SLPNO 
    AND ST.STNDESC = V_STNSEQ
    AND ST.STNSTS = 'U';
   
    IF V_GENDATE IS NOT NULL THEN
      IF V_STNSDATE < TO_DATE(V_GENDATE||' 00:00:00', 'DD/MM/YYYY HH24:MI:SS') THEN
        return null;
      ELSE
        SELECT ST.STNCDATE, STE.STNSDATE 
        INTO V_STNCDATE, V_STNSDATE 
        FROM SLIPTX ST, SLIPTX_EXTRA STE
        WHERE ST.STNID = STE.STNID(+) 
        AND ST.SLPNO = V_SLPNO 
        AND ST.STNSEQ = V_STNSEQ
        AND ST.STNSTS = 'C';
        
        return V_STNSDATE;        
      END IF;
    END IF;
RETURN V_STNSDATE;
end;
/