create or replace FUNCTION "NHS_LIS_ARCHECKLISTLIST"
(
  V_ACTID ARCARD_CHECKLIST_DTL.ACTID%TYPE,
  V_TYPE ARCARD_CHECKLIST_DTL.TYPE%TYPE,
  V_CHECKTYPE ARCARD_CHECKLIST.CHECK_TYPE%TYPE
)
  RETURN TYPES.CURSOR_TYPE
--    RETURN VARCHAR2
AS
  OUTCUR TYPES.CURSOR_TYPE;
  SQLSTR VARCHAR2(5000);
    
BEGIN

  IF V_CHECKTYPE IS NOT NULL THEN
    OPEN OUTCUR FOR 
    SELECT 
    (CASE WHEN ACD.CHECK_ID=14 THEN ACD.OTHER_DESC 
    WHEN ACD.CHECK_ID=15 THEN ACD.OTHER_DESC
    WHEN ACD.CHECK_ID=19 THEN ACD.OTHER_DESC 
    WHEN ACD.CHECK_ID=20 THEN ACD.OTHER_DESC
    ELSE AC.DESCRIPTION END) CHECK_ID,
    ACD.CHECK_ID
    FROM ARCARD_CHECKLIST_DTL ACD, ARCARD_CHECKLIST AC
    WHERE AC.CHECK_ID = ACD.CHECK_ID
    AND ACD.ACTID = V_ACTID 
    AND ACD.TYPE = V_TYPE
    AND AC.CHECK_TYPE = V_CHECKTYPE    
    AND ACD.ENABLED = -1
    ORDER BY ACD.CHECK_ID;  
  ELSE
    OPEN OUTCUR FOR 
    SELECT 
    (CASE WHEN ACD.CHECK_ID=14 THEN ACD.OTHER_DESC 
    WHEN ACD.CHECK_ID=15 THEN ACD.OTHER_DESC
    WHEN ACD.CHECK_ID=19 THEN ACD.OTHER_DESC 
    WHEN ACD.CHECK_ID=20 THEN ACD.OTHER_DESC
    ELSE AC.DESCRIPTION END) CHECK_ID,
    ACD.CHECK_ID
    FROM ARCARD_CHECKLIST_DTL ACD, ARCARD_CHECKLIST AC
    WHERE AC.CHECK_ID = ACD.CHECK_ID
    AND ACD.ACTID = V_ACTID 
    AND ACD.TYPE = V_TYPE
    AND ACD.ENABLED = -1
    ORDER BY ACD.CHECK_ID;  
  END IF;

/*  
	SELECT 
	DECODE(ID,
	'01','Pre-Authorisation needed',
	'02','Guarantee Letter',
	'03','Acknowledgement Admission',
	'04','Policy card copy',
	'05','Passport / ID copy',
	'06','HKAH Consent',
	'07','Claim form',
	'08','Cost estimation',
	'09','Medical report',
	'10','Med / Lab Breakdown',
	'11','Excess / Copay / Deductible / Exceeds Limit / Exclusions',
	'12','Authorization / Approval',
	'13',PARAM01,
	'14',PARAM02) AS CHECKLIST,
	ACTID
	FROM  ARCARD_CHECKLIST
	UNPIVOT INCLUDE NULLS (ENABLED FOR ID IN (
	VALUE01 AS '01', VALUE02 AS '02', VALUE03 AS '03', VALUE04 AS '04', VALUE05 AS '05',
	VALUE06 AS '06', VALUE07 AS '07', VALUE08 AS '08', VALUE09 AS '09', VALUE10 AS '10',
	VALUE11 AS '11', VALUE12 AS '12', VPARAM01 AS '13', VPARAM02 AS '14'))
	WHERE ACTID = V_ACTID
	AND ENABLED = '1'
	ORDER BY 1
	;
*/  
  RETURN OUTCUR;
--    RETURN SQLSTR;
END NHS_LIS_ARCHECKLISTLIST;
/