create or replace FUNCTION NHS_LIS_ACCOUNTRECEIVABLEDTL (
	v_ARCCODE ARCODE.ARCCODE%TYPE,
	v_ARCNAME ARCODE.ARCNAME%TYPE
)
	RETURN Types.cursor_type
--  RETURN VARCHAR2
AS
	outcur Types.cursor_type;
  SQLSTR VARCHAR2(32767);  
BEGIN

SQLSTR:='
	SELECT
		A.ARCCODE, A.ARCNAME, A.ARCCNAME, A.GLCCODE, A.RETGLCCODE, A.ARCADD1,
		A.ARCADD2, A.ARCADD3, A.ARCTEL, A.FAX, A.EMAIL, A.ARCCT, A.ARCTITLE,
		A.ARCUAMT, A.ARCAMT, A.CPSID, C.CPSCODE,
		A.ARCADMCNAME, A.ADMTTL, A.ADMEMAIL, A.ARCADMCP, A.ARCADMCF,
		DECODE(A.ARCSND, -1, ''Y'', ''N''),
		A.FURCCT, A.FURTTL, A.FUREMAIL, A.FURTEL, A.FURFAX,
		A.COPAYTYP, A.ARLMTAMT, TO_CHAR(A.CVREDATE ,''dd/MM/YYYY''), A.COPAYAMT,
		DECODE(A.ITMTYPED, -1, ''Y'', ''N''),
		DECODE(A.ITMTYPEH, -1, ''Y'', ''N''),
		DECODE(A.ITMTYPES, -1, ''Y'', ''N''),
		DECODE(A.ITMTYPEO, -1, ''Y'', ''N''),
		TO_CHAR(a.AR_S_DATE, ''dd/MM/YYYY''),
		TO_CHAR(a.AR_E_DATE, ''dd/MM/YYYY''),
		U.USRNAME,
		TO_CHAR(a.ARCUPDDATE, ''dd/MM/YYYY hh24:mi:ss''),
		DECODE(A.AR_ACTIVE, -1, ''Y'', ''N''),
		a.ARCPRIMCOMP,
		TO_CHAR(a.NCTRSDATE, ''dd/MM/YYYY''),
		TO_CHAR(A.NCTREDATE, ''dd/MM/YYYY''),
		A.ARCADD4,
		A.Print_Mrrpt,
    A.MSTR_AR,
    A.AR_INPATIENT,
    A.AR_OUTPATIENT,
    A.PAY_CHECK,
    A.ISDI,
    A.AR_AGREEMENT,
    A.AR_HTHASSMENT,
    A.AR_OTHERS,
    A.AR_OTHERS_TEXT,
    NHS_GET_ALLBRKDOWNTOCOLUMN(''CL'',A.INP_CHG_RPTLVL),
    NHS_GET_ALLBRKDOWNTOCOLUMN(''OR'',A.INP_CHG_RPTLVL),
    NHS_GET_ALLBRKDOWNTOCOLUMN(''CS'',A.INP_CHG_RPTLVL),
    NHS_GET_ALLBRKDOWNTOCOLUMN(''CL'',A.OP_CHG_RPTLVL),
    NHS_GET_ALLBRKDOWNTOCOLUMN(''OR'',A.OP_CHG_RPTLVL),
    NHS_GET_ALLBRKDOWNTOCOLUMN(''CS'',A.OP_CHG_RPTLVL),
		(SELECT USR.USRNAME FROM USR WHERE USR.USRID = A.AR_CREATEUSR) AS CREATEUSR,
		A.AR_CREATEDATE,
   (SELECT HPS.HPACTIVE FROM HPSTATUS HPS WHERE HPS.HPTYPE = ''ARSIGN'' AND HPS.HPSTATUS = ''SIGNATURE'' AND HPS.HPKEY = A.ARCCODE) AS PATSIGN,
    A.AR_NATURE,
    AE.ADMADD1,AE.ADMADD2,AE.ADMADD3,AE.ADMADD4,
    AE.AGCCCT,AE.AGCTITLE,
    AE.AGCTEL,AE.AGCFAX,AE.AGCEMAIL,
    AE.AGCADD1,AE.AGCADD2,AE.AGCADD3,AE.AGCADD4,
    AE.AUPCCT,AE.AUPTITLE,
    AE.AUPEMAIL,AE.AUPTEL,AE.AUPFAX,
    AE.AUPADD1,AE.AUPADD2,AE.AUPADD3,AE.AUPADD4,
    AE.PRECCT,AE.PRETITLE,
    AE.PREEMAIL,AE.PRETEL,AE.PREFAX,
    AE.PREADD1,AE.PREADD2,AE.PREADD3,AE.PREADD4,
	AE.AR_PCT
  FROM  ARCODE A, CONPCESET C, USR U, ARCODE_EXTRA AE
  WHERE A.CPSID = C.CPSID (+)
  AND A.ARCCODE = AE.ARCCODE(+)
  AND A.STECODE = AE.STECODE(+)
	AND A.ARCUPDUSR = U.USRID (+)
	AND ('''||v_ARCCODE||''' IS NULL OR A.ARCCODE ='''|| v_ARCCODE||''')
	ORDER BY A.ARCCODE ASC';
--RETURN SQLSTR;
  OPEN OUTCUR FOR SQLSTR;
  RETURN OUTCUR;
END NHS_LIS_ACCOUNTRECEIVABLEDTL;
/