create or replace
FUNCTION "NHS_LIS_AREXCLUSIONSLIST"
(
  V_ACTID ARCARD_EXCLUSIONS.ACTID%TYPE
)
  RETURN TYPES.CURSOR_TYPE
--    RETURN VARCHAR2
AS
  OUTCUR TYPES.CURSOR_TYPE;
  LS_ID EXCLUSIONS.ID%TYPE;
  SQLSTR VARCHAR2(5000);
  
BEGIN
  OPEN OUTCUR FOR
  SELECT EXCL.DESCRIPTION, EXCL.ID
  FROM EXCLUSIONS EXCL, ARCARD_EXCLUSIONS AE
  WHERE AE.ID = EXCL.ID
  AND AE.ACTID = V_ACTID
  ORDER BY DESCRIPTION;

--  OPEN OUTCUR FOR SQLSTR;      
  RETURN OUTCUR;
--    RETURN SQLSTR;
END NHS_LIS_AREXCLUSIONSLIST;
/