sampleList = ["Peter", "Paul", "Mary","Paul"]
sampleList.insert(0,"Wendy")
sampleList.append("Fred")
print(sampleList)
sampleList.remove("Paul")
print(sampleList[0])
print(sampleList[1])
print(sampleList[2])
print(sampleList[3])
print(sampleList[4])
print(sampleList[5])
print(sampleList[6])
sampleList.pop(0)
print(sampleList)
