CREATE DATABASE LINK "PORTAL"
  CONNECT TO HKAH IDENTIFIED BY HKAH USING '(DESCRIPTION =
(ADDRESS_LIST = (ADDRESS = (PROTOCOL = TCP)(HOST = 160.100.1.77)(PORT = 1521)))
(CONNECT_DATA = (SID = UPORTAL)) )';