CREATE DATABASE LINK "IWEB"
  CONNECT TO HKAH IDENTIFIED BY HKAH USING '(DESCRIPTION =
(ADDRESS_LIST = (ADDRESS = (PROTOCOL = TCP)(HOST = 127.0.0.1)(PORT = 1521)))
(CONNECT_DATA = (SERVICE_NAME = UHAT)) )';