CREATE OR REPLACE FUNCTION "NHS_ACT_CASHSTAT" (
	i_action   IN VARCHAR2,
	i_CashCode IN VARCHAR2,
	o_errmsg   OUT VARCHAR2
)
	RETURN NUMBER
AS
	o_errcode NUMBER := -1;
	v_Count NUMBER := -1;
	v_CSHSID NUMBER := 0;
	v_CSHATP NUMBER := 0;
	v_CSHATPOUT NUMBER := 0;
	v_CSHREC NUMBER := 0;
	v_CSHPAYOUT NUMBER := 0;
	v_CSHADV NUMBER := 0;
	v_CSHPAYIN NUMBER := 0;
	v_CSHCARD NUMBER := 0;
	v_CSHCARDOUT NUMBER := 0;
	v_CSHEPS NUMBER := 0;
	v_CSHCHQ NUMBER := 0;
	v_CSHCHQOUT NUMBER := 0;
	v_CSHOCTIN NUMBER := 0;
	v_CSHOCTOUT NUMBER := 0;
	v_CSHCUPIN NUMBER := 0;
	v_CSHCUPOUT NUMBER := 0;
	v_CSHQRIN NUMBER := 0;
	v_CSHQROUT NUMBER := 0;
	v_CSHCRCNT NUMBER := 0;
	v_CSHVCNT NUMBER := 0;

	CASHTX_TXNTYPE_RECEIVE VARCHAR2(1) := 'R';
	CASHTX_TXNTYPE_PAYOUT VARCHAR2(1) := 'P';
	CASHTX_TXNTYPE_ADVANCEPAYIN VARCHAR2(1) := 'A';
	CASHTX_PAYTYPE_CASH VARCHAR2(1) := 'C';
	CASHTX_PAYTYPE_CHEQUE VARCHAR2(1) := 'Q';
	CASHTX_PAYTYPE_CARD VARCHAR2(1) := 'D';
	CASHTX_PAYTYPE_CUP VARCHAR2(1) := 'U';
	CASHTX_PAYTYPE_QR VARCHAR2(1) := 'R';
	CASHTX_PAYTYPE_OCTOPUS VARCHAR2(1) := 'T';
	CASHTX_PAYTYPE_EPS VARCHAR2(1) := 'E';
	CASHTX_PAYTYPE_AUTOPAY VARCHAR2(1) := 'A';
BEGIN
	o_errmsg := 'Re-calculated';

	SELECT COUNT(1) INTO v_Count FROM Cashier WHERE CshCode = i_CashCode;
	IF v_Count = 0 THEN
		o_errmsg := 'Cashier not found.';
		RETURN o_errcode;
	END IF;

	-- keep history
	INSERT INTO CASHIER_HISTORY
	(CSHCODE, CSHACT, CSHTS, USRID, CSHTYPE, CSHSTS, CSHRCNT, CSHMAC, CSHODATE, CSHFDATE, CSHSID, STECODE, CSHADV, CSHPAYIN, CSHPAYOUT, CSHREC, CSHCHQ, CSHEPS, CSHCARD, CSHOTHER, CSHCRCNT, CSHVCNT, CSHATP, CSHATPOUT, CSHCHQOUT, CSHCARDOUT, CSHOCTOUT, CSHOCTIN, CSHCUPOUT, CSHCUPIN, CSHQROUT, CSHQRIN)
	SELECT CSHCODE, 'BEFORE', SYSDATE, USRID, CSHTYPE, CSHSTS, CSHRCNT, CSHMAC, CSHODATE, CSHFDATE, CSHSID, STECODE, CSHADV, CSHPAYIN, CSHPAYOUT, CSHREC, CSHCHQ, CSHEPS, CSHCARD, CSHOTHER, CSHCRCNT, CSHVCNT, CSHATP, CSHATPOUT, CSHCHQOUT, CSHCARDOUT, CSHOCTOUT, CSHOCTIN, CSHCUPOUT, CSHCUPIN, CSHQROUT, CSHQRIN
	FROM Cashier WHERE CshCode = i_CashCode;

	-- get CshSid
	SELECT CSHSID INTO v_CSHSID FROM Cashier WHERE CshCode = i_CashCode;

	-- Normal AutoPay (Receipt)
	SELECT SUM(C.CtxAmt) INTO v_CSHATP FROM CashTx C WHERE C.CshCode = i_CashCode AND C.CSHSID = v_CSHSID
	AND C.CtxSts = 'N' AND C.CtxMeth = CASHTX_PAYTYPE_AUTOPAY AND C.CtxType = CASHTX_TXNTYPE_RECEIVE;

	-- Normal AutoPay (Payout)
	SELECT SUM(C.CtxAmt) INTO v_CSHATPOUT FROM CashTx C WHERE C.CshCode = i_CashCode AND C.CSHSID = v_CSHSID
	AND C.CtxSts = 'N' AND C.CtxMeth = CASHTX_PAYTYPE_AUTOPAY AND C.CtxType = CASHTX_TXNTYPE_PAYOUT;

	-- Normal Cash (Receipt)
	SELECT SUM(C.CtxAmt) INTO v_CSHREC FROM CashTx C WHERE C.CshCode = i_CashCode AND C.CSHSID = v_CSHSID
	AND C.CtxSts = 'N' AND C.CtxMeth = CASHTX_PAYTYPE_CASH AND C.CtxType = CASHTX_TXNTYPE_RECEIVE;

	-- Normal Cash (Payout)
	SELECT SUM(C.CtxAmt) INTO v_CSHPAYOUT FROM CashTx C WHERE C.CshCode = i_CashCode AND C.CSHSID = v_CSHSID
	AND C.CtxSts = 'N' AND C.CtxMeth = CASHTX_PAYTYPE_CASH AND C.CtxType = CASHTX_TXNTYPE_PAYOUT;

	-- Normal Cash (Advance)
	SELECT SUM(C.CtxAmt) INTO v_CSHADV FROM CashTx C WHERE C.CshCode = i_CashCode AND C.CSHSID = v_CSHSID
	AND C.CtxSts = 'N' AND C.CtxMeth = CASHTX_PAYTYPE_CASH AND C.CtxType = CASHTX_TXNTYPE_ADVANCEPAYIN AND C.CtxAmt >= 0;

	-- Normal Cash (Advance)
	SELECT SUM(C.CtxAmt) INTO v_CSHPAYIN FROM CashTx C WHERE C.CshCode = i_CashCode AND C.CSHSID = v_CSHSID
	AND C.CtxSts = 'N' AND C.CtxMeth = CASHTX_PAYTYPE_CASH AND C.CtxType = CASHTX_TXNTYPE_ADVANCEPAYIN AND C.CtxAmt < 0;

	-- Normal Credit Card (Receipt)
	SELECT SUM(C.CtxAmt) INTO v_CSHCARD FROM CashTx C WHERE C.CshCode = i_CashCode AND C.CSHSID = v_CSHSID
	AND C.CtxSts = 'N' AND C.CtxMeth = CASHTX_PAYTYPE_CARD AND C.CtxType = CASHTX_TXNTYPE_RECEIVE;

	-- Normal Credit Card (Payout)
	SELECT SUM(C.CtxAmt) INTO v_CSHCARDOUT FROM CashTx C WHERE C.CshCode = i_CashCode AND C.CSHSID = v_CSHSID
	AND C.CtxSts = 'N' AND C.CtxMeth = CASHTX_PAYTYPE_CARD AND C.CtxType = CASHTX_TXNTYPE_PAYOUT;

	-- Normal EPS (Receipt)
	SELECT SUM(C.CtxAmt) INTO v_CSHEPS FROM CashTx C WHERE C.CshCode = i_CashCode AND C.CSHSID = v_CSHSID
	AND C.CtxSts = 'N' AND C.CtxMeth = CASHTX_PAYTYPE_EPS AND C.CtxType = CASHTX_TXNTYPE_RECEIVE;

	-- Normal Cheque (Receipt)
	SELECT SUM(C.CtxAmt) INTO v_CSHCHQ FROM CashTx C WHERE C.CshCode = i_CashCode AND C.CSHSID = v_CSHSID
	AND C.CtxSts = 'N' AND C.CtxMeth = CASHTX_PAYTYPE_CHEQUE AND C.CtxType = CASHTX_TXNTYPE_RECEIVE;

	-- Normal Cheque (Payout)
	SELECT SUM(C.CtxAmt) INTO v_CSHCHQOUT FROM CashTx C WHERE C.CshCode = i_CashCode AND C.CSHSID = v_CSHSID
	AND C.CtxSts = 'N' AND C.CtxMeth = CASHTX_PAYTYPE_CHEQUE AND C.CtxType = CASHTX_TXNTYPE_PAYOUT;

	-- Normal Octopus (Receipt)
	SELECT SUM(C.CtxAmt) INTO v_CSHOCTIN FROM CashTx C WHERE C.CshCode = i_CashCode AND C.CSHSID = v_CSHSID
	AND C.CtxSts = 'N' AND C.CtxMeth = CASHTX_PAYTYPE_OCTOPUS AND C.CtxType = CASHTX_TXNTYPE_RECEIVE;

	-- Normal Octopus (Payout)
	SELECT SUM(C.CtxAmt) INTO v_CSHOCTOUT FROM CashTx C WHERE C.CshCode = i_CashCode AND C.CSHSID = v_CSHSID
	AND C.CtxSts = 'N' AND C.CtxMeth = CASHTX_PAYTYPE_OCTOPUS AND C.CtxType = CASHTX_TXNTYPE_PAYOUT;

	-- Normal CUP (Receipt)
	SELECT SUM(C.CtxAmt) INTO v_CSHCUPIN FROM CashTx C WHERE C.CshCode = i_CashCode AND C.CSHSID = v_CSHSID
	AND C.CtxSts = 'N' AND C.CtxMeth = CASHTX_PAYTYPE_CUP AND C.CtxType = CASHTX_TXNTYPE_RECEIVE;

	-- Normal CUP (Payout)
	SELECT SUM(C.CtxAmt) INTO v_CSHCUPOUT FROM CashTx C WHERE C.CshCode = i_CashCode AND C.CSHSID = v_CSHSID
	AND C.CtxSts = 'N' AND C.CtxMeth = CASHTX_PAYTYPE_CUP AND C.CtxType = CASHTX_TXNTYPE_PAYOUT;

	-- Normal QR (Receipt)
	SELECT SUM(C.CtxAmt) INTO v_CSHQRIN FROM CashTx C WHERE C.CshCode = i_CashCode AND C.CSHSID = v_CSHSID
	AND C.CtxSts = 'N' AND C.CtxMeth = CASHTX_PAYTYPE_QR AND C.CtxType = CASHTX_TXNTYPE_RECEIVE;

	-- Normal QR (Payout)
	SELECT SUM(C.CtxAmt) INTO v_CSHQROUT FROM CashTx C WHERE C.CshCode = i_CashCode AND C.CSHSID = v_CSHSID
	AND C.CtxSts = 'N' AND C.CtxMeth = CASHTX_PAYTYPE_QR AND C.CtxType = CASHTX_TXNTYPE_PAYOUT;

	-- Normal CR issued
	SELECT COUNT(1) INTO v_CSHCRCNT FROM CashTx C WHERE C.CshCode = i_CashCode AND C.CSHSID = v_CSHSID
	AND C.CtxSts != 'V' AND C.CtxType = CASHTX_TXNTYPE_RECEIVE;

	-- Void
	SELECT COUNT(1) INTO v_CSHVCNT FROM CashTx C WHERE C.CshCode = i_CashCode AND C.CSHSID = v_CSHSID
	AND C.CtxSts = 'V' AND C.CtxType = CASHTX_TXNTYPE_RECEIVE;

	UPDATE Cashier
	SET
		CSHATP     = NVL(v_CSHATP, 0),
		CSHATPOUT  = NVL(v_CSHATPOUT, 0),
		CSHREC     = NVL(v_CSHREC, 0),
		CSHPAYOUT  = NVL(v_CSHPAYOUT, 0),
		CSHADV     = NVL(v_CSHADV, 0),
		CSHPAYIN   = NVL(v_CSHPAYIN, 0),
		CSHCARD    = NVL(v_CSHCARD, 0),
		CSHCARDOUT = NVL(v_CSHCARDOUT, 0),
		CSHEPS     = NVL(v_CSHEPS, 0),
		CSHCHQ     = NVL(v_CSHCHQ, 0),
		CSHCHQOUT  = NVL(v_CSHCHQOUT, 0),
		CSHOCTIN   = NVL(v_CSHOCTIN, 0),
		CSHOCTOUT  = NVL(v_CSHOCTOUT, 0),
		CSHCUPIN   = NVL(v_CSHCUPIN, 0),
		CSHCUPOUT  = NVL(v_CSHCUPOUT, 0),
		CSHQRIN    = NVL(v_CSHQRIN, 0),
		CSHQROUT   = NVL(v_CSHQROUT, 0),
		CSHCRCNT   = NVL(v_CSHCRCNT, 0),
		CSHVCNT    = NVL(v_CSHVCNT, 0)
	WHERE CshCode  = i_CashCode;

	-- keep history
	INSERT INTO CASHIER_HISTORY
	(CSHCODE, CSHACT, CSHTS, USRID, CSHTYPE, CSHSTS, CSHRCNT, CSHMAC, CSHODATE, CSHFDATE, CSHSID, STECODE, CSHADV, CSHPAYIN, CSHPAYOUT, CSHREC, CSHCHQ, CSHEPS, CSHCARD, CSHOTHER, CSHCRCNT, CSHVCNT, CSHATP, CSHATPOUT, CSHCHQOUT, CSHCARDOUT, CSHOCTOUT, CSHOCTIN, CSHCUPOUT, CSHCUPIN, CSHQROUT, CSHQRIN)
	SELECT CSHCODE, 'AFTER', SYSDATE, USRID, CSHTYPE, CSHSTS, CSHRCNT, CSHMAC, CSHODATE, CSHFDATE, CSHSID, STECODE, CSHADV, CSHPAYIN, CSHPAYOUT, CSHREC, CSHCHQ, CSHEPS, CSHCARD, CSHOTHER, CSHCRCNT, CSHVCNT, CSHATP, CSHATPOUT, CSHCHQOUT, CSHCARDOUT, CSHOCTOUT, CSHOCTIN, CSHCUPOUT, CSHCUPIN, CSHQROUT, CSHQRIN
	FROM Cashier WHERE CshCode = i_CashCode;

	RETURN o_errcode;
END NHS_ACT_CASHSTAT;
/
