CREATE OR REPLACE FUNCTION "NHS_LIS_CASHSTAT" (
	v_CASHCODE IN VARCHAR2
)
	RETURN TYPES.CURSOR_TYPE
AS
	OUTCUR TYPES.CURSOR_TYPE;
	v_CSHSID NUMBER := 0;
	v_CSHCARD_R_AE NUMBER := 0;
	v_CSHCARD_P_AE NUMBER := 0;
	v_CSHCARD_R_VISA_MASTER NUMBER := 0;
	v_CSHCARD_P_VISA_MASTER NUMBER := 0;
	v_CSHCARD_R_JCB NUMBER := 0;
	v_CSHCARD_P_JCB NUMBER := 0;

	CASHTX_TXNTYPE_RECEIVE VARCHAR2(1) := 'R';
	CASHTX_TXNTYPE_PAYOUT VARCHAR2(1) := 'P';
	CASHTX_PAYTYPE_CARD VARCHAR2(1) := 'D';
	CASHTX_PAYTYPE_QR VARCHAR2(1) := 'R';
BEGIN
	SELECT CSHSID INTO v_CSHSID FROM Cashier WHERE CshCode = v_CASHCODE;

	SELECT SUM(C.CtxAmt) INTO v_CSHCARD_R_AE FROM CashTx C, CardTx D WHERE C.CtnID = D.CtnID AND C.CshCode = v_CASHCODE AND C.CSHSID = v_CSHSID AND C.CtxSts = 'N' AND C.CtxMeth = CASHTX_PAYTYPE_CARD AND C.CtxType = CASHTX_TXNTYPE_RECEIVE AND trim(D.CtnCType) IN ('AE', 'AMEX');
	SELECT SUM(C.CtxAmt) INTO v_CSHCARD_P_AE FROM CashTx C, CardTx D WHERE C.CtnID = D.CtnID AND C.CshCode = v_CASHCODE AND C.CSHSID = v_CSHSID AND C.CtxSts = 'N' AND C.CtxMeth = CASHTX_PAYTYPE_CARD AND C.CtxType = CASHTX_TXNTYPE_PAYOUT AND trim(D.CtnCType) IN ('AE', 'AMEX');
	SELECT SUM(C.CtxAmt) INTO v_CSHCARD_R_VISA_MASTER FROM CashTx C, CardTx D WHERE C.CtnID = D.CtnID AND C.CshCode = v_CASHCODE AND C.CSHSID = v_CSHSID AND C.CtxSts = 'N' AND C.CtxMeth = CASHTX_PAYTYPE_CARD AND C.CtxType = CASHTX_TXNTYPE_RECEIVE AND trim(D.CtnCType) IN ('VISA', 'HSB_VISA', 'MASTER', 'MASTERCARD', 'HSB_MASTER');
	SELECT SUM(C.CtxAmt) INTO v_CSHCARD_P_VISA_MASTER FROM CashTx C, CardTx D WHERE C.CtnID = D.CtnID AND C.CshCode = v_CASHCODE AND C.CSHSID = v_CSHSID AND C.CtxSts = 'N' AND C.CtxMeth = CASHTX_PAYTYPE_CARD AND C.CtxType = CASHTX_TXNTYPE_PAYOUT AND trim(D.CtnCType) IN ('VISA', 'HSB_VISA', 'MASTER', 'MASTERCARD', 'HSB_MASTER');
	SELECT SUM(C.CtxAmt) INTO v_CSHCARD_R_JCB FROM CashTx C, CardTx D WHERE C.CtnID = D.CtnID AND C.CshCode = v_CASHCODE AND C.CSHSID = v_CSHSID AND C.CtxSts = 'N' AND C.CtxMeth = CASHTX_PAYTYPE_CARD AND C.CtxType = CASHTX_TXNTYPE_RECEIVE AND trim(D.CtnCType) IN ('JCB');
	SELECT SUM(C.CtxAmt) INTO v_CSHCARD_P_JCB FROM CashTx C, CardTx D WHERE C.CtnID = D.CtnID AND C.CshCode = v_CASHCODE AND C.CSHSID = v_CSHSID AND C.CtxSts = 'N' AND C.CtxMeth = CASHTX_PAYTYPE_CARD AND C.CtxType = CASHTX_TXNTYPE_PAYOUT AND trim(D.CtnCType) IN ('JCB');

	IF GET_CURRENT_STECODE() = 'HKAH' THEN
		OPEN OUTCUR FOR
			SELECT 1,
				'AUTOPAY',
				NVL(CSHATP, 0),
				NVL(CSHATPOUT, 0),
				NVL(CSHATP, 0) + NVL(CSHATPOUT, 0),
				NVL(CSHOTHER, 0),
				NVL(CSHCRCNT, 0),
				NVL(CSHRCNT, 0),
				NVL(CSHVCNT, 0)
			FROM  CASHIER
			WHERE CSHCODE = v_CASHCODE
			UNION
			SELECT 2,
				'CASH',
				NVL(CSHREC, 0),
				NVL(CSHPAYOUT, 0),
				NVL(CSHREC, 0) + NVL(CSHPAYOUT, 0),
				0,
				0,
				0,
				0
			FROM  CASHIER
			WHERE CSHCODE = v_CASHCODE
			UNION
			SELECT 3,
				'CC - AMEX',
				NVL(v_CSHCARD_R_AE, 0),
				NVL(v_CSHCARD_P_AE, 0),
				NVL(v_CSHCARD_R_AE, 0) + NVL(v_CSHCARD_P_AE, 0),
				0,
				0,
				0,
				0
			FROM  DUAL
			UNION
			SELECT 4,
				'CC - VISA / MASTER',
				NVL(v_CSHCARD_R_VISA_MASTER, 0),
				NVL(v_CSHCARD_P_VISA_MASTER, 0),
				NVL(v_CSHCARD_R_VISA_MASTER, 0) + NVL(v_CSHCARD_P_VISA_MASTER, 0),
				0,
				0,
				0,
				0
			FROM  DUAL
			UNION
			SELECT 5,
				'CC - JCB',
				NVL(v_CSHCARD_R_JCB, 0),
				NVL(v_CSHCARD_P_JCB, 0),
				NVL(v_CSHCARD_R_JCB, 0) + NVL(v_CSHCARD_P_JCB, 0),
				0,
				0,
				0,
				0
			FROM  DUAL
			UNION
			SELECT 6,
				'CHEQUE',
				NVL(CSHCHQ, 0),
				NVL(CSHCHQOUT, 0),
				NVL(CSHCHQ, 0) + NVL(CSHCHQOUT, 0),
				0,
				0,
				0,
				0
			FROM  CASHIER
			WHERE CSHCODE = v_CASHCODE
			UNION
			SELECT 7,
				'CUP',
				NVL(CSHCUPIN, 0),
				NVL(CSHCUPOUT, 0),
				NVL(CSHCUPIN, 0) + NVL(CSHCUPOUT, 0),
				0,
				0,
				0,
				0
			FROM  CASHIER
			WHERE CSHCODE = v_CASHCODE
			UNION
			SELECT 8,
				'EPS',
				NVL(CSHEPS, 0),
				0,
				NVL(CSHEPS, 0),
				0,
				0,
				0,
				0
			FROM  CASHIER
			WHERE CSHCODE = v_CASHCODE
			UNION
			SELECT 9,
				'WECHAT/ALIPAY',
				NVL(CSHQRIN, 0),
				NVL(CSHQROUT, 0),
				NVL(CSHQRIN, 0) + NVL(CSHQROUT, 0),
				0,
				0,
				0,
				0
			FROM  CASHIER
			WHERE CSHCODE = v_CASHCODE
			UNION
			SELECT 10,
				'TOTAL',
				NVL(CSHREC + CSHCARD + CSHCHQ + CSHEPS + CSHATP + CSHCUPIN + CSHOCTIN + CSHQRIN + CSHADV, 0),
				NVL(CSHPAYOUT + CSHCARDOUT + CSHCHQOUT + CSHATPOUT + CSHCUPOUT + CSHOCTOUT + CSHQROUT + CSHPAYIN, 0),
				NVL(CSHREC + CSHCARD + CSHCHQ + CSHEPS + CSHATP + CSHCUPIN + CSHOCTIN + CSHQRIN + CSHADV, 0)
					+ NVL(CSHPAYOUT + CSHCARDOUT + CSHCHQOUT + CSHATPOUT + CSHCUPOUT + CSHOCTOUT + CSHQROUT + CSHPAYIN, 0),
				0,
				0,
				0,
				0
			FROM CASHIER
			WHERE CSHCODE = v_CASHCODE;
	ELSE
		OPEN OUTCUR FOR
			SELECT 1,
				'CASH',
				NVL(CSHREC, 0),
				NVL(CSHPAYOUT, 0),
				NVL(CSHREC, 0) + NVL(CSHPAYOUT, 0),
				NVL(CSHOTHER, 0),
				NVL(CSHCRCNT, 0),
				NVL(CSHRCNT, 0),
				NVL(CSHVCNT, 0)
			FROM  CASHIER
			WHERE CSHCODE = v_CASHCODE
			UNION
			SELECT 2,
				'CREDIT CARD',
				NVL(CSHCARD, 0),
				NVL(CSHCARDOUT, 0),
				NVL(CSHCARD, 0) + NVL(CSHCARDOUT, 0),
				0,
				0,
				0,
				0
			FROM  CASHIER
			WHERE CSHCODE = v_CASHCODE
			UNION
			SELECT 3,
				'CHEQUE',
				NVL(CSHCHQ, 0),
				NVL(CSHCHQOUT, 0),
				NVL(CSHCHQ, 0) + NVL(CSHCHQOUT, 0),
				0,
				0,
				0,
				0
			FROM  CASHIER
			WHERE CSHCODE = v_CASHCODE
			UNION
			SELECT 4,
				'EPS',
				NVL(CSHEPS, 0),
				0,
				NVL(CSHEPS, 0),
				0,
				0,
				0,
				0
			FROM  CASHIER
			WHERE CSHCODE = v_CASHCODE
			UNION
			SELECT 5,
				'AUTOPAY',
				NVL(CSHATP, 0),
				NVL(CSHATPOUT, 0),
				NVL(CSHATP, 0) + NVL(CSHATPOUT, 0),
				0,
				0,
				0,
				0
			FROM  CASHIER
			WHERE CSHCODE = v_CASHCODE
			UNION
			SELECT 6,
				'CUP',
				NVL(CSHCUPIN, 0),
				NVL(CSHCUPOUT, 0),
				NVL(CSHCUPIN, 0) + NVL(CSHCUPOUT, 0),
				0,
				0,
				0,
				0
			FROM  CASHIER
			WHERE CSHCODE = v_CASHCODE
			UNION
			SELECT 7,
				'OCTOPUS',
				NVL(CSHOCTIN, 0),
				NVL(CSHOCTOUT, 0),
				NVL(CSHOCTIN, 0) + NVL(CSHOCTOUT, 0),
				0,
				0,
				0,
				0
			FROM  CASHIER
			WHERE CSHCODE = v_CASHCODE
			UNION
			SELECT 8,
				'WECHAT/ALIPAY',
				NVL(CSHQRIN, 0),
				NVL(CSHQROUT, 0),
				NVL(CSHQRIN, 0) + NVL(CSHQROUT, 0),
				0,
				0,
				0,
				0
			FROM  CASHIER
			WHERE CSHCODE = v_CASHCODE
			UNION
			SELECT 9,
				'Advance Payment/Withdraw',
				NVL(CSHADV, 0),
				NVL(CSHPAYIN, 0),
				NVL(CSHADV, 0) + NVL(CSHPAYIN, 0),
				0,
				0,
				0,
				0
			FROM  CASHIER
			WHERE CSHCODE = v_CASHCODE
			UNION
			SELECT 10,
				'TOTAL',
				NVL(CSHREC + CSHCARD + CSHCHQ + CSHEPS + CSHATP + CSHCUPIN + CSHOCTIN + CSHQRIN + CSHADV, 0),
				NVL(CSHPAYOUT + CSHCARDOUT + CSHCHQOUT + CSHATPOUT + CSHCUPOUT + CSHOCTOUT + CSHQROUT + CSHPAYIN, 0),
				NVL(CSHREC + CSHCARD + CSHCHQ + CSHEPS + CSHATP + CSHCUPIN + CSHOCTIN + CSHQRIN + CSHADV, 0)
					+ NVL(CSHPAYOUT + CSHCARDOUT + CSHCHQOUT + CSHATPOUT + CSHCUPOUT + CSHOCTOUT + CSHQROUT + CSHPAYIN, 0),
				0,
				0,
				0,
				0
			FROM CASHIER
			WHERE CSHCODE = v_CASHCODE;
	END IF;

	RETURN OUTCUR;
END NHS_LIS_CASHSTAT;
/
