CREATE OR REPLACE FUNCTION "NHS_ACT_CASHIERCLOSE"(
	v_ACTION  IN VARCHAR2,
	v_CshCode IN VARCHAR2,
	v_USRID   IN VARCHAR2,
	o_errmsg  OUT VARCHAR2
)
	RETURN NUMBER
AS
	o_errcode   NUMBER;
	v_OLDCshSID NUMBER;
BEGIN
	o_errcode := 0;
	o_errmsg  := 'OK';

	-- CashierClose
	BEGIN
		SELECT CshSID INTO v_OLDCshSID FROM Cashier WHERE CshCode = v_CshCode;
		EXCEPTION
		WHEN NO_DATA_FOUND THEN
			dbms_output.put_line('NO old CshSID found for CshCode:' || v_CshCode);
	END;

	-- Keep Cashier History
	INSERT INTO CASHIER_HISTORY
	(CSHCODE, CSHACT, CSHTS, USRID, CSHTYPE, CSHSTS, CSHRCNT, CSHMAC, CSHODATE, CSHFDATE, CSHSID, STECODE, CSHADV, CSHPAYIN, CSHPAYOUT, CSHREC, CSHCHQ, CSHEPS, CSHCARD, CSHOTHER, CSHCRCNT, CSHVCNT, CSHATP, CSHATPOUT, CSHCHQOUT, CSHCARDOUT, CSHOCTOUT, CSHOCTIN, CSHCUPOUT, CSHCUPIN, CSHQROUT, CSHQRIN)
	SELECT CSHCODE, 'HISTORY', SYSDATE, USRID, CSHTYPE, CSHSTS, CSHRCNT, CSHMAC, CSHODATE, CSHFDATE, CSHSID, STECODE, CSHADV, CSHPAYIN, CSHPAYOUT, CSHREC, CSHCHQ, CSHEPS, CSHCARD, CSHOTHER, CSHCRCNT, CSHVCNT, CSHATP, CSHATPOUT, CSHCHQOUT, CSHCARDOUT, CSHOCTOUT, CSHOCTIN, CSHCUPOUT, CSHCUPIN, CSHQROUT, CSHQRIN
	FROM Cashier WHERE CshCode = v_CshCode;

	-- CashierClose
	UPDATE Cashier
	SET CSHSTS = 'C',	-- CASHIER_STS_CLOSE
		CshSID = SEQ_CASHIER_SID.NEXTVAL,
		CSHFDATE = SYSDATE
	WHERE CshCode = v_CshCode;

	-- UpdateCashierTransaction
	UPDATE Cashtx SET CtxCDate = SYSDATE WHERE CshSID = v_OLDCshSID;

	-- UpdateARTransaction
	UPDATE Artx SET AtxCDate = SYSDATE WHERE AtxCDate IS NULL;

	UPDATE Arptx SET ArpCDate = SYSDATE WHERE ArpCDate IS NULL;

	-- UpdateCaptureDate
	UPDATE Sliptx
	SET    StnCDate = SYSDATE
	WHERE  StnCDate IS NULL
	AND    UsrID = v_USRID
	AND    StnType = 'S';	-- SLIPTX_TYPE_PAYMENT_C

	RETURN o_errcode;
EXCEPTION
WHEN OTHERS THEN
	ROLLBACK;
	dbms_output.put_line('An ERROR was encountered - '||SQLCODE||' -ERROR- '||SQLERRM);
	o_errmsg := 'Fail to close cashier.<br><font color=red>Error Code:' || SQLCODE || '</font>';

	RETURN -999;
END NHS_ACT_CASHIERCLOSE;
/
